### ISSUE TITLE
counsel-ag-occur does not respect extra args passed to counsel-ag via a prefix argument

### ISSUE THREAD

**Issue by cperl82** [abo-abo/swiper#1002]
For example, if you create the following test files in a test directory:
```
$ echo foobar > t.txt
$ echo foobar > t.c
```
Then, launch emacs and run `counsel-ag` with a prefix argument adding `--cc` to the arguments for `ag` and pull the results into a grep buffer with ivy-occur (typing `C-u M-x counsel-ag RET RET --cc RET foo C-c C-o`)

The results in the minibuffer (prior to `ivy-occur`) are properly restricted to just `t.c`, but `ivy-occur` results in a buffer with both files:
```
-*- mode:grep; default-directory: "/home/cperl/tmp/2017-05-13/" -*-
   
 2 candidates:  
./t.c:1:foobar
./t.txt:1:foobar
```
I had a quick look at the code and it looks like the issue is that `ivy-occur` dispatches to `counsel-ag-occur` which actually just does another run of `ag` but without extra args.

I don't fully grok all the code, what global state is safe to access when, or why it was doing a completely separate run of `ag`, but I seem to get better results with the following patch to `counsel-ag-occur`.

If you think its reasonable, I can look to generalize it to some of the other similar duplicate code for other grep like occur commands and submit a PR.

```diff
diff --git a/counsel.el b/counsel.el
index dc587ca..c5c2699 100644
--- a/counsel.el
+++ b/counsel.el
@@ -1776,16 +1776,7 @@ If non-nil, EXTRA-AG-ARGS string is appended to BASE-CMD."
   (unless (eq major-mode 'ivy-occur-grep-mode)
     (ivy-occur-grep-mode))
   (setq default-directory counsel--git-grep-dir)
-  (let* ((regex (counsel-unquote-regex-parens
-                 (setq ivy--old-re
-                       (ivy--regex
-                        (progn (string-match "\"\\(.*\\)\"" (buffer-name))
-                               (match-string 1 (buffer-name)))))))
-         (cands (split-string
-                 (shell-command-to-string
-                  (format counsel-ag-base-command (shell-quote-argument regex)))
-                 "\n"
-                 t)))
+  (let ((cands (ivy--filter ivy-text ivy--all-candidates)))
     ;; Need precise number of header lines for `wgrep' to work.
     (insert (format "-*- mode:grep; default-directory: %S -*-\n\n\n"
                     default-directory))
```

**Comment by abo-abo** [comment]
> If you think its reasonable, I can look to generalize it to some of the other similar duplicate code for other grep like occur commands and submit a PR.

Sounds good, please go ahead.
