### ISSUE TITLE
`counsel-unicode-char' results order is reversed.

### ISSUE THREAD

**Issue by wygulmage** [abo-abo/swiper#1003]
The desired result is usually at the bottom of the list.

To reproduce, search 'em dash', 'right single quotation mark', 'comma', or 'bullet' (and presumably most other characters).

I'm letting my ignorance show, but there didn't seem to be an easy way to fix this, e.g. ':search 'reverse' or hitting the results with `nreverse' somewhere.

**Comment by abo-abo** [comment]
Thanks.
