### ISSUE TITLE
Incorrect window-start with ivy-avy

### ISSUE THREAD

**Issue by basil-conto** [abo-abo/swiper#1004]
#### Steps to reproduce

1. `emacs -Q`
2. `M-x package-initialize RET`
3. `M-x ivy-mode RET`
4. `M-: (ivy-read "Pick a number: " (mapcar #'number-to-string (number-sequence 0 (ash ivy-height 1)))) RET`
5. `M->`
6. `C-'`
7. Select candidate `a`
8.
   * Expected result: `"12"`
   * Actual result: `"0"`

I believe I have narrowed the problem down to function `window-start` always returning `1`, even when scrolled further down the candidate list. What I find peculiar is that `window-end` is always correct and `(pos-visible-in-window-p (window-start)` is always `t`. I have tried calling `redisplay` and calling `window-end` as `(window-end nil t)` before calling `window-start` but the result is always the same.

**Comment by abo-abo** [comment]
Thanks for catching this. Please test.

**Comment by basil-conto** [comment]
Thank you for tending to this. I do not, however, think the problem is completely fixed. Although the correct candidate is selected now, the string returned by `ivy-read` includes the surrounding formatting context.

Adjusting my previous steps to reproduce:

1. `emacs -Q`
2. `M-x package-initialize RET`
3. `M-x ivy-mode RET`
4. `M-: (setq ivy-format-function #'ivy-format-function-arrow) RET`
5. `M-: (ivy-read "Pick a number: " (mapcar #'number-to-string (number-sequence 0 (ash ivy-height 1)))) RET`
6. `M->`
7. `C-'`
8. Select candidate `a`
9.
   * Expected result: `"12"`
   * Actual result: `"  12"`

**Comment by abo-abo** [comment]
Reopening. PRs welcome.

**Comment by basil-conto** [comment]
I'd like to investigate further but I don't expect to make much progress over the next month or two (I also need to submit a copyright assignment).

**Comment by abo-abo** [comment]
No problem, take your time.

**Comment by suryaaditya** [comment]
hi, not sure if this behavior observed is related to this issue:
Steps:
1. counsel-find-file
2.C-'(ivy-avy)
3.instead of the opening the file selected, it tries to open a brand new buffer.

C-' (ivy-avy) works as expected on commands like Counsel-M-x though.

**Comment by ryankask** [comment]
I'm seeing the same behaviour as @suryaaditya although it doesn't appear to work anywhere for me. For example, with `counsel-M-x` I see `apply: Wrong type argument: commandp, \ \ apropos`.

**Comment by abo-abo** [comment]
@suryaaditya Your example works fine on my system. Please try to reproduce with `emacs -Q` (or use `make plain` from this repo).

**Comment by ryankask** [comment]
@abo-abo I've taken up your suggestion and can reproduce the issue with the following setting:

`(setq ivy-format-function 'ivy-format-function-arrow)`

**Comment by abo-abo** [comment]
@ryankask Thanks. It's easy to fix once it's reproducible.

**Comment by avocadoras** [comment]
I'm having this issue with Emacs 26.1 on macOS mojave. 
1. Launch Emacs
2. `C-x C-f` (counsel-find-file)
3. Find-file: ~/.emacs/
4. "l"
5. open Dired by name buffer on another random file.

Weird because I had no issues before but now start to have some.
```
(use-package avy
  :ensure t
  :bind ("M-s" . avy-goto-word-1))

(use-package counsel
  :ensure t
  :config
  (counsel-mode))

(use-package ivy
  :ensure t
  :bind (("C-c C-r" . ivy-resume)
	 :map ivy-minibuffer-map
	 ("C-'" . ivy-avy))
  :config
  (ivy-mode 1)
  (setq ivy-use-virtual-buffers t)
  (setq ivy-count-format "%d/%d ")
  (setq ivy-display-style 'fancy))

(use-package swiper
  :ensure t
  :after (ivy avy)
  :bind ("C-s" . swiper))

  (use-package ivy-rich
    :ensure t
    :after ivy
    :init
    (setq ivy-rich-path-style 'abbrev
	  ivy-virtual-abbreviate 'full)
    :config (ivy-rich-mode 1))
;;  Actions
  ;;;;;;;;;;;;;;;
  ;;;  delete files when perusing your file system
;; (ivy-set-actions
;;  'counsel-find-file
;;  '(("d" delete-file "delete")))

(defun dired-mode-setup ()
  "Hook for dired-mode."
  (dired-hide-details-mode 1))
(add-hook 'dired-mode-hook 'dired-mode-setup)

;; allow dired to delete or copy dir
(setq dired-recursive-copies (quote always)) ; “always” means no asking
(setq dired-recursive-deletes (quote top)) ; “top” means ask once

(setq dired-dwim-target t)
```
