### ISSUE TITLE
Magic slash not working (Windows?)

### ISSUE THREAD

**Issue by glucas** [abo-abo/swiper#1015]
The recent changes to ivy--magic-file-slash appear to have broken things on my Emacs 25.1 setup on Windows: typing slashes just keeps appending slashes to the path, rather than cd'ing to '/'. 

If I remove the `(eq this-command 'self-insert-command)` check it starts working again. According to `view-lossage` those slashes are not doing a `self-insert-commant`:

     C-x C-f [counsel-find-file]
     / [anonymous-command]
     / [anonymous-command]

**Comment by glucas** [comment]
Never mind, pretty sure this is caused by some other aspects of my setup. I'll confirm and then close this issue.

**Comment by glucas** [comment]
Caused by another package hijacking '/' that I did not expect in the minibuffer. Sorry for the noise!

**Comment by abo-abo** [comment]
No problem:)
