### ISSUE TITLE
Broken file completion with TAB (`ivy-partial-or-done`)

### ISSUE THREAD

**Issue by tsdh** [abo-abo/swiper#102]
The commits 16eb4a22e1b7b4207f0a6df06d246c0d5caf398c and 9b9885d￼ added some new logic to `ivy-partial-or-done` which break candidate selection when finding files.

Concretely, when I do `C-x C-f tr` in my `~/Repos/uni/` directory, I get the candidates `trainbenchmark-ttc/`, ..., `transformation/`, ...  The selected candidate is `trainbenchmark-ttc/`.  When I hit `TAB` which is bound to `ivy-partial-or-done`, ivy changes into the directory `~/Repos/uni/transformation/` which is not the selected candidate.

This completion is the result of calling `(minibuffer-complete)`.

The previous `ivy-partial-or-done` without the extra-stuff before the `(or ...)` worked just fine for me.  What's the intention of the commits above?

**Comment by abo-abo** [comment]
> What's the intention of the commits above?

To get partial completion for tramp methods, user names, domains etc. It all should work now.

**Comment by tsdh** [comment]
Yes, it does work now.  Thanks!
