### ISSUE TITLE
Is there a way to configure regex-plus to support characters in addition to a space?

### ISSUE THREAD

**Issue by fallwith** [abo-abo/swiper#1022]
When I have Ivy set to the default of `regex-plus`, I find it difficult to find some files in my project that contain underscores. For example, I might have a file named `an_example.txt`. Without knowing exactly where the underscore is in the filename and having lots of files that start with `an`, I might enter in a search phrase of `ane`. Doing so causes `regex-plus` to find 0 results. This is presumably because it sees `an_example` as one word (because it contains no spaces), whereas I would prefer it to see two words. From what I understand, `regex-plus` will map `an example` into `an.*example`. I would like it to do the same for `an_example`. Is there anyway that `regex_plus` can be configured to replace underscores with `.*` as well as the default `space` character?

If not, I have two workarounds that are working fine. In the trivialized example I've given if I happened to know the word `example`, searching for it instead of `ane` would work just fine. My other workaround is to switch away from `regex-plus` over to `regex-fuzzy`. This definitely allows `ane` to work as desired, but is a bit overkill for my purposes and causes Ivy to be just a touch slower and to return more undesired results than `regex-plus` does.

**Comment by abo-abo** [comment]
You can write your own regex builder: just copy paste stuff from `ivy--regex` and configure `ivy-re-builders-alist`.

**Comment by fallwith** [comment]
Great - I'll have a look through `ivy.el` and experiment.

Thanks very much!
