### ISSUE TITLE
problem renaming file in dired with ivy/counsel

### ISSUE THREAD

**Issue by jave** [abo-abo/swiper#1023]
to reproduce:
- create an empty directory
- in this directory create a new directory called "aa"
- try to rename the directory to "a"

this last step will be problematic, since the name "aa" contains "a".

As a side note ido has the samme issue, but there you can use c-j to clarify that you dont want the suggested expansion, you want what is typed to be used verbatim.

**Comment by abo-abo** [comment]
Press <kbd>C-M-j</kbd>, it's in the FAQ already:)

**Comment by jave** [comment]
I should have known, sorry for the noise, and thanks!
