### ISSUE TITLE
Error on pressing TAB

### ISSUE THREAD

**Issue by drot** [abo-abo/swiper#1024]
Started occuring after the last commits:
![region](https://cloud.githubusercontent.com/assets/85483/26283162/8d2a7e1c-3e22-11e7-9f3a-90332100fa5d.png)

**Comment by skylerlee** [comment]
Yes, I have the same problem. Also, I can't use `<right>` key to select alternatives using `counsel-find-file`.

**Comment by manuel-uberti** [comment]
It's working fine here.

Could you try to replicate the error with `emacs -Q`? See [here](http://www.lunaryorn.com/posts/reproduce-bugs-in-emacs-Q.html), if you don't know how to do it.

**Comment by drot** [comment]
The issue still persists with `emacs -Q` and enabling `ivy-mode`.

**Comment by abo-abo** [comment]
What are the steps to reach the screenshot. I clearly see there's a problem, but I have no idea how you got there, everything works fine on my system.

**Comment by drot** [comment]
1. Start with `emacs -Q`
2. `M-x package-initialize`
3. `M-x ivy-mode`
4. `C-x C-f`
5. Complete `.emacs.d` with first TAB, after pressing TAB the second time to enter the directory the error above happens. `C-j` for example works normally.

**Comment by unmanbearpig** [comment]
I've got the same error in Emacs built from master via homebrew --HEAD on latest macOS.
It happens when I hit tab in `find-file`.

1. I type in a directory name or something that can be completed to a directory name
2. Hit tab and it completes the name with a `/` at the end
3. Hit tab again and expect to get a list of files in that directory, but instead get that error.

Here is a video https://youtu.be/I8rEwM-9gsY

I was running it with `emacs -Q -nw`, `package-initialize` and `ivy-mode`.
Let me know if I can help debugging it somehow.

**Comment by rakanalh** [comment]
I am seeing the same issue running the latest MELPA version:
```
ivy                20170519.824  dependency 
counsel            20170518.1425 dependency  

```

**Comment by abo-abo** [comment]
Thanks all, should be fixed now.

**Comment by abo-abo** [comment]
> Question: Previously, a single tab used to also work but now to tab strokes are required to select the completion... was the old behavior changed?

Please try to git bisect and find the commit when <kbd>TAB</kbd> changed. I never use <kbd>TAB</kbd>, so I wouldn't know.

**Comment by rakanalh** [comment]
@abo-abo out of curiosity, when you highlight the directory you need, what do YOU use to have ivy go into it and display files inside that directory?

**Comment by abo-abo** [comment]
@rakanalh <kbd>C-j</kbd> will do this.

**Comment by abo-abo** [comment]
I also have this binding in my config:

```elisp
(define-key ivy-minibuffer-map (kbd "<return>") 'ivy-alt-done)
```
