### ISSUE TITLE
read-file-name-function and ivy?

### ISSUE THREAD

**Issue by jave** [abo-abo/swiper#1026]
Should it be possible to use ivy with read-file-name?

In my case read-file-name-function doesnt contain an ivy function, and I cant find any mention of this in the ivy src. Have I missed some configuration?

**Comment by abo-abo** [comment]
The defaults should forward to `completing-read-function`, which forwards to ivy.

**Comment by jave** [comment]
Thanks.

For others with the same issue, this fixes it:

(setq read-file-name-function 'read-file-name-default)

The reason i got the problem is because im trying to make some functions for switching between helm, ivy and ido, so one can try them out. In this case ido and helm had messed up read-file-name-function, but didnt clean up after themselves.
