### ISSUE TITLE
Tab: ivy-partial-or-done

### ISSUE THREAD

**Issue by rakanalh** [abo-abo/swiper#1027]
Hi,

It seems to me that there was an issue introduced in recent versions of Ivy where hitting "TAB" would invoke `ivy-partial-or-done` which automatically and implicitly did what `ivy-alt-done` was doing if the candidate you hit `TAB` on was the only matching one.

So in case you try to `find-file` and type .emacs.d, given that there's no other file/dir that match these names hitting tab after typing `.emacs` would perform `ivy-alt-done` rather than requiring two tabs.

Thank you

**Comment by abo-abo** [comment]
Thanks.

**Comment by rakanalh** [comment]
Thank you for resolving this in such a timely manner! much appreciated

**Comment by abo-abo** [comment]
You're welcome.

**Comment by rakanalh** [comment]
So it was just upgradable through MELPA and i gave it a go. 
Say i have a directory called 
`~/Code`
So when i perform C-x C-f, starting `~`, i type 'code' then TAB, ivy doesn't advanced into the `Code` directory but rather shows the minibuffer as follows:
```
Find file: code/[cursor here]
./
../
```
Although the directory isn't empty.

I experimented with this a bit and found that pressing TAB on the only candidate directory is similar to pressing `/` so it just takes my input as is and not considering that what i want is to navigate into selected candidate.

**Comment by Lenbok** [comment]
I only see 2017-0515.1409 in melpa, which predates the fix for this issue, so perhaps melpa just hasn't built the new one (I don't know how often it rebuilds).

**Comment by rakanalh** [comment]
I have
```
ivy-20170522.913
```

**Comment by Lenbok** [comment]
My bad - I assumed that since we were in abo-abo/swiper repo, that I should be looking at the swiper package in melpa, but ivy melpa package is where we expect to see the fix.

**Comment by Lenbok** [comment]
I have updated to ivy-20170522.913 and can confirm that the problem you describe in https://github.com/abo-abo/swiper/issues/1027#issuecomment-303215381 still exists, so it seems this is not fixed.

**Comment by abo-abo** [comment]
@rakanalh Please open a new issue with some description of the directory structure and the steps.

**Comment by drot** [comment]
Works fine here, I made a [video](https://asciinema.org/a/dim7jexa1yry9sppm2fv956uf). Created the `Code` directory and some other directories inside. As seen on the video typing `code` and pressing `TAB` after that descends into the directory.

**Comment by abo-abo** [comment]
@drot Works fine for me too, but maybe it doesn't with some specific directory names of @rakanalh

**Comment by rakanalh** [comment]
Here's the follow up bug
https://github.com/abo-abo/swiper/issues/1029
