### ISSUE TITLE
Complete eval-expression history?

### ISSUE THREAD

**Issue by joonoro** [abo-abo/swiper#1028]
M-: runs `eval-expression`, it would be nice if there was a way to use Ivy to choose previous expressions from history.

**Comment by abo-abo** [comment]
With `counsel-mode`, `counsel-expression-history` is bound to <kbd>C-r</kbd>. See also README:

> (define-key read-expression-map (kbd "C-r") 'counsel-expression-history)

**Comment by joonoro** [comment]
Thanks! I didn't even realize there was a `counsel-mode`.

**Comment by therockmandolinist** [comment]
@abo-abo could this be modified to run the expression instead of inserting it?

**Comment by therockmandolinist** [comment]
Ah, nevermind, found the definition. Should be pretty straightforward.
