### ISSUE TITLE
Ivy mistakes choosing selected candidate vs the input directory

### ISSUE THREAD

**Issue by rakanalh** [abo-abo/swiper#1029]
Say i have a directory called
/tmp/Code

I create inner directories 
```
> cd /tmp/
> mkdir -p Code/{Python,Emacs}
> emacs -nw
``` 
So when i perform C-x C-f, starting at /tmp, i type 'code' then TAB, ivy doesn't advanced into the Code directory but rather shows the minibuffer as follows:

Find file: code/[cursor here]
./
../
Although the directory isn't empty.

I experimented with this a bit and found that pressing TAB on the only candidate directory is similar to pressing / so it just takes my input as is and not considering that what i want is to navigate into selected candidate.

I recorded an asciinema file to showcase the bug
https://asciinema.org/a/1fcbnjj2dl7h8n2aj08qwo0s0

**Comment by abo-abo** [comment]
Can't reproduce with 25.1.1. This repository has a nice command for reproducibility:

    make plain

Can you try it?

One more thing, looks like you have a `code` directory that exists somewhere, maybe in your home directory.

**Comment by rakanalh** [comment]
I tried `make plain`, reporting emacs version `GNU Emacs 25.2.1`  and i could not reproduce the issue as well. However, i also deleted the whole `elpa` directory in my `.emacs.d` and everything reinstalled while the issue still exists.
Yes, i do have a `Code` directory in my home directory, same issue happens when i try to go into that one as well.

**Comment by Lenbok** [comment]
For me I get the problem in my GUI emacsclients but not in my terminal emacsclients.

**Comment by Lenbok** [comment]
Screen recording showing the above: https://www.dropbox.com/s/k09611lwa9jyz0s/ivy-weird.webm?dl=0

**Comment by abo-abo** [comment]
@rakanalh Can you move the `Code` directory somewhere away from home. And see if you still have the issue with your example in `/tmp/`.

**Comment by rakanalh** [comment]
I renamed the directory into `MyCode` and followed the same steps but still get the same issue.
https://asciinema.org/a/216qd4ebcd24max7c6nl2r8ki

**Comment by abo-abo** [comment]
@rakanalh @Lenbok I can't fix it unless I get some way of reproducing the issue on my system. Can you try `make plain` again?
If you can't reproduce that, the issue is with your config. In that case, move parts of your Ivy config into a separate file, and load that file from the `make plain` Emacs.

**Comment by rakanalh** [comment]
I have updated my configuration yesterday with a bit of new stuff but they included moving ivy into it's own module and the issue is gone. 
Your help was very much appreciated @abo-abo. Thanks alot

**Comment by Lenbok** [comment]
I sorted out my issue also. I use company and yasnippet for in-buffer completion, and it turns out that that the lisp to make these work together wasn't properly taking ivy into account.
