### ISSUE TITLE
counsel-git-grep: add C-l for recentering the matched line, like in swiper?

### ISSUE THREAD

**Issue by zhaojiangbin** [abo-abo/swiper#103]
Oddly, in swiper, I don't see `C-l` listed in output of `C-h m`. But it does show up in output of `C-h b` as being bound to `swiper-recenter-top-bottom`.

**Comment by abo-abo** [comment]
Thanks for the suggestion.

> Oddly, in swiper, I don't see C-l listed in output of C-h m.

This is because `C-m m` only lists `ivy-minibuffer-map`, not `swiper-map`.
