### ISSUE TITLE
ivy-help hangs for 10+ seconds loading Org

### ISSUE THREAD

**Issue by miketz** [abo-abo/swiper#1032]
On my weaker windows laptop, it takes 10+ seconds for ivy-help to load org-mode.  I thought something was broken during the delay.  Too heavy a price to view static help content.
On my fast linux box with an SSD, org loads very quickly ~0.5 seconds.

Maybe a "loading org..." message could be printed. 
Maybe have a config variable to use outline-mode if org is not yet loaded.

**Comment by abo-abo** [comment]
> On my weaker windows laptop, it takes 10+ seconds for ivy-help to load org-mode.

It takes a long time, unless Org is already loaded.

Here's what I have in my config:

```elisp
(run-with-idle-timer
 3 nil
 (lambda () (require 'org)))
```

It's unfortunate that it will still take 10 seconds to load Org, but you can then keep Emacs open until you reboot.

**Comment by miketz** [comment]
I'll close the issue. The root problem (org load time) is not an ivy issue.  Just throwing it out there as people with fast machines will never notice the delay.

BTW in my config I re-define ivy-help to use outline mode.

(with-eval-after-load 'ivy
  ;; redefine `ivy-help' to use outline mode. To avoid a long wait loading org.
  (defun ivy-help ()
    "Help for `ivy'."
    (interactive)
    (let ((buf (get-buffer "*Ivy Help*")))
      (unless buf
        (setq buf (get-buffer-create "*Ivy Help*"))
        (with-current-buffer buf
          (insert-file-contents ivy-help-file)
          (if (member 'org features)
              (org-mode)
            (outline-mode))
          (view-mode)
          (goto-char (point-min))))
      (if (eq this-command 'ivy-help)
          (switch-to-buffer buf)
        (with-ivy-window
          (pop-to-buffer buf)))
      (view-mode)
      (goto-char (point-min)))))
