### ISSUE TITLE
How can counsel-find-file remember previous opened files

### ISSUE THREAD

**Issue by maplewizard** [abo-abo/swiper#1034]
I found that when I am using `counsel-find-file`, it always present `./` and `../` as the first two choices while I seldom use. Is it possible for it to remember previous opened files?

**Comment by abo-abo** [comment]
`./` and `../` are present in every directory, since they represent the current and the parent dir. Configurable with `ivy-extra-directories`.

Use <kbd>C-r</kbd> or <kbd>M-p</kbd> for previous files.

**Comment by abo-abo** [comment]
Closing as solved.
