### ISSUE TITLE
ivy-partial has become overeager in case folding

### ISSUE THREAD

**Issue by xendk** [abo-abo/swiper#1036]
`ivy-partial` folds pretty much everything to lowercase whenever it completes now, regardless of the presence of capital letters, rendering completion pretty useless with case sensitive data.

**Comment by abo-abo** [comment]
Example please.

**Comment by xendk** [comment]
Say that I have a /tmp/UpperCase file. Using `counsel-find-file` I have `/tmp/Up` in the minibuffer, and press tab, it changes it to `/tmp/uppercase`. Which works because it still selects the candidate, but if there's also an `uppercase` file, it gets annoying as that'll suddenly be the default.

**Comment by xendk** [comment]
And it absolutely kills the ivy-read on something case sensitive I'm trying to do.

**Comment by abo-abo** [comment]
What are your settings? Can you provide an example like this:

    (ivy-read "test: " '("one" "uppercase"))

**Comment by xendk** [comment]
Qute simple: 
```
(ivy-read
 "test: "
 '("case" "Case"))
```

Typing `Ca` and tab completes to `case`.

**Comment by cmm** [comment]
Not a real problem for me yet (no files that differ only by case), but definitely an eyesore.

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by xendk** [comment]
:+1: Excellent.
