### ISSUE TITLE
counsel-M-x raises Symbol's value as variable is void: smex-initialized-p

### ISSUE THREAD

**Issue by ecraven** [abo-abo/swiper#1038]
I have the following in my .emacs.d/init.el

````
(use-package swiper
  :bind (("C-." . ivy-switch-buffer))
  :config
  (progn
    (ivy-mode 1)
    (setq ivy-re-builders-alist '((swiper . ivy--regex-plus)
                                  (t . ivy--regex-fuzzy))))
  :ensure t)

(use-package counsel
  :ensure t
  :bind (("M-x" . counsel-M-x)
         ("C-x C-f" . counsel-find-file)
         ("C-h f" . counsel-describe-function)
         ("C-h v" . counsel-describe-variable)
         ("M-y" . counsel-yank-pop)
         ("C-x 8 RET" . counsel-unicode-char)
         ("C-M-y" . counsel-mark-ring)))
````

I deleted my .emacs.d/elpa, and let emacs install everything from scratch. I do *not* use `smex`. 

When I start a new emacs instance, I get:
````
funcall-interactively: Symbol’s value as variable is void: smex-initialized-p
````

I've seen that `counsel.el` includes `(defvar smex-initialized-p)`, however that does not seem to work correctly, as it is still undefined in my emacs :-/

GNU Emacs 25.2.1 (x86_64-unknown-linux-gnu, GTK+ Version 3.22.10) of 2017-04-22
  swiper             20170515.1409 installed

**Comment by abo-abo** [comment]
When `(require 'smex nil 'noerror)` returns non-nil, which it did, it means you have `smex` installed. What's possible is that you have a broken `smex.el` that does not define `smex-initialized-p`.

**Comment by basil-conto** [comment]
This issue does not sound related to `ivy`/`counsel`; can it be closed?

**Comment by ecraven** [comment]
yes, this hasn't happened again. sorry for forgetting about it.
