### ISSUE TITLE
Easier way to complete C-x f without using the right arrow key?

### ISSUE THREAD

**Issue by nosefouratyou** [abo-abo/swiper#1045]
Sorry to bother you guys again,

Is there another way to complete C-x f without having to use the arrow key? I find myself hitting enter and constantly opening dired by accident.

**Comment by nosefouratyou** [comment]
I guess I'm looking for how to rebind the enter key if highlighting a directory I guess?

**Comment by abo-abo** [comment]
Press `C-m`.

**Comment by nosefouratyou** [comment]
Er I was playing around and figured out that C-j does it, not C-m. But thank you for pointing me in the right direction!
