### ISSUE TITLE
ivy and ert

### ISSUE THREAD

**Issue by phillord** [abo-abo/swiper#1047]
With ivy-mode turned on, M-x ert does not work correctly, since ivy restricts to all the known completion values (which are the names of the ert tests). But I should be able to use any selector, most importantly `t` to run all of the tests.

**Comment by abo-abo** [comment]
Works for me: `M-x ert C-j t C-M-j`.

**Comment by abo-abo** [comment]
Should be easier now, please test.

**Comment by phillord** [comment]
Apologies for the slow response. I am still having problems with this, but the problem is a big inconsistent. If I run `M-x ert t`, then I get the correct result. However, if I do `M-x ert some-particular-test` and then `M-x ert t` again, the second time  `t` is not in the completion options, so I just get a test with the letter "t" in it.  Next time around, it's reset, and "t" appears as the default option again.
