### ISSUE TITLE
Doesn't work with rgrep anymore

### ISSUE THREAD

**Issue by mrkkrp** [abo-abo/swiper#1052]
Invoke `rgrep` then enter something, literally `something` for example, then hit enter and you should see:

```
Wrong type argument: stringp, ("*.d" "all" "el" "ch" "c" "cc" "cchh" "hh" "h" "l" ...)
```

I use `rgrep` regularly and it worked until today (I did an upgrade of Emacs packages).

**Comment by abo-abo** [comment]
Thanks.
