### ISSUE TITLE
~/ in counsel-find-file

### ISSUE THREAD

**Issue by aathan** [abo-abo/swiper#1058]
I'd like to suggest this optional feature. I may be able to provide a pull given pointers/suggestions for where to start such an implementation. I'm completely unfamiliar with the internals of the relevant packages.

Typing exactly the key sequence `~/` in counsel-find-file should maybe result in `~/` in the minibuffer, instead of `~//`

The sequence is muscle-memory for many people. I am still learning ivy, so forgive me if this is a naive suggestion. I've found I like it when modes work similarly to workflows outside the mode, where possible. It's often necessary to get to a file "starting from the home directory." Without my suggested behavior, getting to such a file becomes different than doing so outside of emacs (e.g., at a shell), and different from simply typing its path, and ~/ TAB also doesn't end up "doing the right thing."  Thanks for a great contribution to emacs.

**Comment by abo-abo** [comment]
There was a request for this already. See `ivy-magic-tilde`.

**Comment by abo-abo** [comment]
Closing as solved.
