### ISSUE TITLE
Long string trucated by ellipses are not searched by swiper.

### ISSUE THREAD

**Issue by codesoverhill** [abo-abo/swiper#1061]
Please look at the attached screenshot. 'color-theme-sanityinc-sol...' is not displayed as a candidate when searching for 'solar'. Am not sure if this is the intended behaviour but wanted to check. Am using abo-abo's config on linux with Emacs version 24.5.1
![swiper](https://user-images.githubusercontent.com/28491132/26961061-a14cadd0-4cf9-11e7-84cb-3eb031e1cb40.png)

--
Thanks.

**Comment by abo-abo** [comment]
This isn't a bug, since the actual text in the buffer is `sanityinc-sol...`. You can search for `sol\.\.\.` and get a match.

You can adjust `tabulated-list-format` for a wider first column if you like.
