### ISSUE TITLE
Selecting org-mode internal link candidates with ivy 

### ISSUE THREAD

**Issue by benmaughan** [abo-abo/swiper#1062]
In org mode, you can complete an internal heading by typing * and then M-<tab> which runs pcomplete to give you the possible completions of all the headings in the document. Is it possible to have the candidates offered through the ivy interface? I use (ivy-mode 1) but it doesn't take over this instance of completion.

Furthermore, this completion would give you the text e.g.

*heading one

which is not so useful if you want to create an internal link to that heading. What I would really like is a counsel function to provide the headings in the file as completion candidates and then generate a link like

[[heading one]]

Does such a thing exist? If not then I'll take a shot at putting something together for myself.

Cheers,
 Ben

**Comment by abo-abo** [comment]
You can ask on the org-mode mailing list for the Org function to call `completing-read`. They've made some progress switching some functions to `completing-read` already.

Also, there is `counsel-org-agenda-headlines`. And `worf-goto`.
