### ISSUE TITLE
Is it possible to search for the thing under the cursor with just one key binding?

### ISSUE THREAD

**Issue by zzhjerry** [abo-abo/swiper#1068]
I know `C-s C-w` or `C-s M-n` could do it. But I wonder if this can be done with just 1 key binding.

**Comment by abo-abo** [comment]
There's no option to do this. But it's easy to write some custom code. I can give an example if you need it.

**Comment by mtuzinskiy** [comment]
@abo-abo Yes, could you please give an example?
I would like to implement the `SPC-*` functionality from the Spacemacs, i.e. when pressing `SPC-*` on any word, it performs a project-wide search.

I mapped the `SPC-*` to 
```
(progn
    (counsel-projectile-ag)
    (ivy-next-history-element)))
```
But it doesn't work. I'm new to elisp. Please help.
P.S. Thank you for the great Ivy!

**Comment by abo-abo** [comment]
Here's a code that you could use:

```elisp
(defun ivy-with-thing-at-point (cmd)
  (let ((ivy-initial-inputs-alist
         (list
          (cons cmd (thing-at-point 'symbol)))))
    (funcall cmd)))

;; Example 1
(defun counsel-ag-thing-at-point ()
  (interactive)
  (ivy-with-thing-at-point 'counsel-ag))

;; Example 2
(defun swiper-thing-at-point ()
  (interactive)
  (ivy-with-thing-at-point 'swiper))
```

**Comment by mtuzinskiy** [comment]
@abo-abo tried it, doesn't work. The thing is that, unlike Swiper,  the `counsel-ag` has no `:inital-value` argument (as well as counsel-projectile-ag). What to do?

**Comment by abo-abo** [comment]
@mtuzinskiy You should update the package from Git, or wait a few hours and update from MELPA.

**Comment by wykurz** [comment]
This was working great for me until recently. Now running `swiper-thing-at-point` has an unfortunate side-effect of going to the last element found (rather than sticking to the one nearest to the cursor, as C-s M-n would. 

@abo-abo do you have any suggestions what may be going on? 

Thanks!

**Comment by basil-conto** [comment]
@wykurz If this is something you can reliably reproduce, please submit a bug report with a reproduction recipe. TIA.

**Comment by wykurz** [comment]
Yes, it's 100% reproducible. Created this: https://github.com/abo-abo/swiper/issues/2737

**Comment by wykurz** [comment]
For others trying to use this - `swiper-thing-at-point` is now defined in swiper.el itself. So to use it just create a key binding like:
```elisp
(global-set-key (kbd "M-s") 'swiper-thing-at-point)
```

**Comment by stsquad** [comment]
> Here's a code that you could use:
> 
> ```emacs-lisp
> (defun ivy-with-thing-at-point (cmd)
>   (let ((ivy-initial-inputs-alist
>          (list
>           (cons cmd (thing-at-point 'symbol)))))
>     (funcall cmd)))
> 
> ;; Example 1
> (defun counsel-ag-thing-at-point ()
>   (interactive)
>   (ivy-with-thing-at-point 'counsel-ag))
> 
> ;; Example 2
> (defun swiper-thing-at-point ()
>   (interactive)
>   (ivy-with-thing-at-point 'swiper))
> ```

Just for the historical record I found I needed to strip properties from the thing at point lest I get weird behavior searching for something from a "read-only" section of my cicre IRC buffer. So currently I have:

    (defun my-ivy-with-thing-at-point (cmd &optional dir)
      "Wrap a call to CMD with setting "
      (let ((ivy-initial-inputs-alist
             (list
              (cons cmd (substring-no-properties (thing-at-point 'symbol))))))
        (funcall cmd nil dir)))

    (defun my-counsel-ag-from-here (&optional dir)
      "Start ag but from the directory the file is in (otherwise I would
    be using git-grep)."
      (interactive "D")
      (my-ivy-with-thing-at-point
       'counsel-ag
       (or dir (file-name-directory (buffer-file-name)))))

    (defun my-counsel-git-grep ()
      (interactive)
      (my-ivy-with-thing-at-point
       'counsel-git-grep))
