### ISSUE TITLE
Semantics of TAB?

### ISSUE THREAD

**Issue by rootzlevel** [abo-abo/swiper#107]
So after all these changes to `ivy-partial-or-done`, I'm confused: What is the intended usage of <kbd>TAB</kbd>?

Right now, it's very unpredictable: For many candidates, I can't possibly know if `ivy-partial` will actually find a common completion or not. So, hitting <kbd>TAB</kbd> in file completion can have these effekts:

1. No common completion is found and the selected file is opened or the selected directory is entered (`ivy-alt-done`)
2. `ivy-partial` actually finds a common completion, inserts it in the minibuffer and possibly changes the selected candidate in the process. (If the common substring is a complete match for one of the candidates)

So after hitting <kbd>TAB</kbd> the system can be in two totally different states, that I can't predict beforehand. This induces quite a heavy mental burden to reparse the current state and possibly fix it, if `ivy-partial-or-done`'s action wasn't the intended one.

(Ignoring the tamp-completion feature, which I haven't tested), `ivy-partial-or-done` is now just a more unpredictable version of `ivy-alt-done` for me.
<hr>
I suggest an approach that is more similar to the original one:

After one <kbd>TAB</kbd>:
- Try `ivy-partial`. If it can complete something, insert it.
- If not, tell the user (by something similar  to the "match required" indicator)

After the second consecutive <kbd>TAB</kbd>
- Call `ivy-alt-done`

<hr>
Otherwise, bind `ivy-partial` or `ivy-alt-done` to <kbd>TAB</kbd>, as both are more predictable than `ivy-partial-or-done`

@tsdh CC, since you seem to like the current behaviour

**Comment by tsdh** [comment]
I don't see how these two states are so completely different. My main intend is to be able to navigate large hierarchies quickly mostly by tab and as few typing as possible.

But of course, it's no problem to add another alternative that behaves like you suggest.

W.r.t. default behavior, I think the current one is pretty similar to what ido also does. So it seems like a good one to me. But I wouldn't object to changing the default tab binding if others think it's too unpredictable.
