### ISSUE TITLE
Poor highlighting color and text color with solarized light theme

### ISSUE THREAD

**Issue by rieje** [abo-abo/swiper#1070]
As you can [see](https://ptpb.pw/AIbF0EizLdBVfktH_guqNCG10pIB.png) the results of swiper shows bad color for highlighting and also font color on the last line. Can I use the same highlight/font colors as what [solarized light theme](https://github.com/bbatsov/solarized-emacs) uses? For example, this is what the highlighting/font color looks like when I search using evil's `/`.

I'm new to emacs, apologies if I'm missing something that I may have overlooked before submitting an issue.

P.S. Might as well ask some noob questions:

* Is it possible to see all the keybindings of ivy and other packages in general inside emacs or do I typically have to look into the manual for this?

* I want to bind some keys to be more vim-like (I use evil):

`C-n` (ivy-next-line) to something like `C-j`
`C-p` (ivy-previous-line) to something like `C-k`

Is this a bad idea? How do I know if `C-j` for example is unused? Could I use this binding only when ivy is used so these custom bindings won't affect other bindings?

* How come I have to `ESC ESC ESC` 3 times to exit out of swiper (why can't I just `ESC` once)?

Apologies for my ignorance.

**Comment by abo-abo** [comment]
> As you can see the results of swiper shows bad color for highlighting and also font color on the last line. Can I use the same highlight/font colors as what solarized light theme uses? For example, this is what the highlighting/font color looks like when I search using evil's /.

You can raise your issue is with solarized-light. Emacs themes can have custom faces for all kinds of packages, this means custom code has to be added to solarized-light and not here.

> Is it possible to see all the keybindings of ivy and other packages in general inside emacs or do I typically have to look into the manual for this?

Press <kbd>C-h m</kbd>.

> I want to bind some keys to be more vim-like (I use evil):
>
> C-n (ivy-next-line) to something like C-j
> C-p (ivy-previous-line) to something like C-k
>
> Is this a bad idea? How do I know if C-j for example is unused? Could I use this binding only when ivy is used so these custom bindings won't affect other bindings?

Press e.g. <kbd>C-h k C-j</kbd> to see where <kbd>C-j</kbd> is bound. You can customize it separately using `ivy-minibuffer-map`.

> How come I have to ESC ESC ESC 3 times to exit out of swiper (why can't I just ESC once)?

This is standard Emacs stuff, <kbd>ESC</kbd> is used as a modifier e.g. <kbd>ESC x</kbd>. The Emacs binding for getting out is <kbd>C-g</kbd>.

**Comment by dunkarooftop** [comment]
@rieje 

Here is my config to have ESC to close the ivy mini buffer with 1 tap instead of 3

````
(use-package ivy :ensure t
  :diminish (ivy-mode . "")
  :init
  (ivy-mode 1)
  (setq projectile-completion-system  'ivy)
  :bind (:map ivy-minibuffer-map                              ;; THIS IS WHAT YOU NEED
         ([escape]   . minibuffer-keyboard-quit)) 
```

also in swiper

```
(use-package swiper
  :ensure t
  :bind (:map swiper-map
  ([escape] . minibuffer-keyboard-quit)))
```
