### ISSUE TITLE
How does swiper determine which result to select by default?

### ISSUE THREAD

**Issue by mindstormer12** [abo-abo/swiper#1078]
I have the following options:

    (setq ivy-initial-inputs-alist nil)
    (setq ivy-re-builders-alist '((t . ivy--regex-fuzzy)))

And `flx` installed (but not configured) to sort fuzzy results as you've recommended in a blog post.

* When I search for the string "`alias`", how does swiper determine which selection it's on by default? In the middle of all search results? Doesn't seem to be the case when I searched for other strings. The best candidate? Fuzzy search by its nature shows a lot of outputs and in the document I only have one line containing `alias` so I was hoping swiper selects it by default. Instead, it selects a line that doesn't have anything close to the string I'm searching for.

So I'm really confused as to which option gets highlighted by default in the results when swiper is used. It seems arbitrary to me and I was wondering if I can configure to select perhaps the best candidate, the middle all searches (which are sorted by line numbers), etc. This question probably has nothing to do with fuzzy searching.

**Comment by abo-abo** [comment]
Let's make sure we talk about the same things: do you mean `swiper` or something else?

Because for `swiper` it's really easy: the first match looking forward from the current point position is the default candidate.
