### ISSUE TITLE
Invalid regexp: "Trailing backslash"

### ISSUE THREAD

**Issue by rompy** [abo-abo/swiper#108]
Happens on windows (didn't try on linux).

When I'm in the root of a drive (eg: C:\, F:\) and i try 'cd' or 'C-x C-f' this error happens.
Probably has to do with the '\' at the end of C:\

**Comment by abo-abo** [comment]
I don't have access to a Windows machine. Maybe someone else could patch it.

The basics work:

```elisp
(ivy-read "drive: " '("C:\\" "D:\\"))
```

There's probably just a `regexp-quote` missing somewhere.
