### ISSUE TITLE
ivy-read can not init select first candidate when run second time.

### ISSUE THREAD

**Issue by tumashu** [abo-abo/swiper#1080]
```
(ivy-read "Input: " 'test :dynamic-collection t)

(defun test (x)
  (list x  "a" "b" "c"))

```

If I first run and select "c",  the second run will select "c" auto, instead of the first one

**Comment by abo-abo** [comment]
Fixed, thanks.

And I think it's a really clever way to add the input text to the collection; at first I didn't get what the code was doing:)

**Comment by tumashu** [comment]
:-)
