### ISSUE TITLE
Preview buffer without buffer creation

### ISSUE THREAD

**Issue by cryptomaniac512** [abo-abo/swiper#1082]
When searching in a project using a counsel-ag, I want to implement a preview, similar to the counsel-grep. Now I use copy-paste from counsel-ag with

```elisp
:update-fn (lambda ()
            (counsel-grep-action (ivy-state-current ivy-last)))
```

But it opens too much buffers when I navigate in result buffer. How I can implement result preview without opening buffer? I don't need to have buffer with result if it does not exists or before I open result manually.

**Comment by abo-abo** [comment]
First of all, you should be calling `counsel-git-grep-action`, since that's what `counsel-ag` has in the :action slot.
If you don't like that behavior, copy paste `counsel-git-grep-action` into your own function and adapt it slightly and call that function in `:update-fn`.
