### ISSUE TITLE
Ivy ignores '+' char when it follows any other character

### ISSUE THREAD

**Issue by mssdvd** [abo-abo/swiper#1083]
Ivy ignores the '+' character when it follows any other character
![image](https://user-images.githubusercontent.com/18464329/27519870-9448e20a-59fd-11e7-8a0c-89b1c1b9d938.png)

Counsel-M-x and execute-extended-command via ivy command don't work properly too.
![image](https://user-images.githubusercontent.com/18464329/27519909-4d1b8fa8-59fe-11e7-8fc7-926751e252cd.png)
![image](https://user-images.githubusercontent.com/18464329/27519912-6a8e3716-59fe-11e7-8764-48c14cca4fd7.png)

**Comment by raxod502** [comment]
The default behavior of Ivy is to interpret your query as a regex, with some special features. Try `c\+\+-mode`. If you don't want to use regexes, you can customize `ivy-re-builders-alist`, e.g. `(setf (alist-get t ivy-re-builders-alist) 'regexp-quote)`, or use `'counsel-M-x` in place of `t` to only disable regexes for `counsel-M-x`. In that case you will probably want to customize `ivy-initial-inputs-alist` as well, to remove the `^` character that gets inserted by default.

**Comment by mssdvd** [comment]
Thanks!

**Comment by abo-abo** [comment]
@raxod502 Thanks.
