### ISSUE TITLE
How to defalias load-theme to counsel-load-theme?

### ISSUE THREAD

**Issue by rieje** [abo-abo/swiper#1086]
How to defalias load-theme to counsel-load-theme? 

`(defalias 'load-theme 'counsel-load-theme)` does not work because the latter does not take any arguments. So is there some way to achieve the effect of an alias?

**Comment by therockmandolinist** [comment]
Works fine here (with counsel-mode on, load-theme and counsel-load-theme seem to behave in the same way anyway...)

**Comment by seagle0128** [comment]
correct. `(counsel-mode 1)` will remap `load-theme` to `counsel-load-theme`.
but another question, `load-library` works incorrectly. it shows more items than `counsel-load-library`. why?

**Comment by abo-abo** [comment]
`load-library` shows some duplicates. `counsel-load-library` shows only unique items.

**Comment by seagle0128** [comment]
Thanks for the quick reply.
Could you let me know how to defalias `load-library` to `counsel-load-libray`?

**Comment by abo-abo** [comment]
Not sure why you would need it, but here:

    (defalias 'load-library 'counsel-load-library)

**Comment by seagle0128** [comment]
Thanks. I just wanna replace `load-library` by `counsel-load-library`.

**Comment by abo-abo** [comment]
Then use `global-set-key` to bind `counsel-load-theme` to what you want.
`load-theme` isn't bound by default, `counsel-mode` will remap it if you bound it.
