### ISSUE TITLE
counsel--descbinds-cands failing

### ISSUE THREAD

**Issue by ambihelical** [abo-abo/swiper#1089]
I found that counsel--descbinds-cands was failing to find any bindings because there is a space before the function name in the output of describe-buffer-bindings (Emacs 25.2.1).  Changing the regex as follows fixes it:

```
      (while (not (eobp))
        (when (looking-at "^\\([^\t\n]+\\)\t+\s*\\(.*\\)$")
          (let ((key (match-string 1))
```

**Comment by abo-abo** [comment]
Thanks.
