### ISSUE TITLE
Quoting spaces

### ISSUE THREAD

**Issue by rootzlevel** [abo-abo/swiper#109]
With the current `ivy--split`, it's possible to match spaces, but only at the end of a word. I'd prefer to be able to quote spaces everywhere.

For example, matching the string *for example* alone is not possible, since `for__example` would also match *for this example*.

So this would mean, that `ivy--split` should split the string at a single space and just remove one space without splitting if there are more spaces.

**Comment by abo-abo** [comment]
Thanks.

**Comment by rootzlevel** [comment]
Thanks! Your reported-to-fixed time is amazing
