### ISSUE TITLE
ivy-use-selectable-prompt and minibuffer-prompt face

### ISSUE THREAD

**Issue by therockmandolinist** [abo-abo/swiper#1090]
When ivy-use-selectable-prompt is set, the minibuffer prompt is no longer colored (`minibuffer-prompt` face) except when that line is selected. Is this expected behavior and is there a way to change this?

It'd be nice if the prompt was colored with `minibuffer-prompt` face by default and the coloring changed (to something else) when selecting the prompt.

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by therockmandolinist** [comment]
Seems to work. Thanks!
