### ISSUE TITLE
[feature request] Honor completion-ignored-extensions

### ISSUE THREAD

**Issue by SkySkimmer** [abo-abo/swiper#1092]
`counsel-find-file` has `counsel-find-file-ignore-regexp` but emacs has a built in `completion-ignored-extensions`
```
Original value was 
(".o" "~" ".bin" ".lbin" ".so" ".a" ".ln" ".blg" ".bbl" ".elc" ".lof" ".glo" ".idx" ".lot" ".svn/" ".hg/" ".git/" ".bzr/" "CVS/" "_darcs/" "_MTN/" ".fmt" ".tfm" ".class" ".fas" ".lib" ".mem" ".x86f" ".sparcf" ".dfsl" ".pfsl" ".d64fsl" ".p64fsl" ".lx64fsl" ".lx32fsl" ".dx64fsl" ".dx32fsl" ".fx64fsl" ".fx32fsl" ".sx64fsl" ".sx32fsl" ".wx64fsl" ".wx32fsl" ".fasl" ".ufsl" ".fsl" ".dxl" ".lo" ".la" ".gmo" ".mo" ".toc" ".aux" ".cp" ".fn" ".ky" ".pg" ".tp" ".vr" ".cps" ".fns" ".kys" ".pgs" ".tps" ".vrs" ".pyc" ".pyo")


Documentation:
Completion ignores file names ending in any string in this list.
It does not ignore them if all possible completions end in one of
these strings or when displaying a list of completions.
It ignores directory names if they match any string in this list which
ends in a slash.
```
Language packages will add the appropriate object file extensions to this, eg https://github.com/ocaml/tuareg/blob/master/tuareg.el#L2412-L2416 

It would be nice if counsel respected this ignore list, probably with a toggle akin to `ido-ignore-extensions`.

**Comment by abo-abo** [comment]
Thanks, let me know if this is good enough.

> It would be nice if counsel respected this ignore list, probably with a toggle akin to ido-ignore-extensions.

I think juggling two variables at once isn't an optimal solution. I can add an option for `counsel-find-file-ignore-regexp` to be a custom function if necessary, but I think the `regexp-opt` should be enough.

**Comment by SkySkimmer** [comment]
That won't work with new packages modifying the `completion-ignored-extensions` will it?
Also if I have eg `/tmp/foo.bbl.foo` it should not be ignored.
Also I prefer writing in my init over using the customize system.

**Comment by abo-abo** [comment]
> That won't work with new packages modifying the completion-ignored-extensions will it?
> Also if I have eg /tmp/foo.bbl.foo it should not be ignored.
> Also I prefer writing in my init over using the customize system.

You'll have to add this to your config, preferably after `completion-ignored-extensions` is finalized:

    (setq counsel-find-file-ignore-regexp (regexp-opt completion-ignored-extensions))
