### ISSUE TITLE
Allow rotating between regex builders

### ISSUE THREAD

**Issue by glucas** [abo-abo/swiper#1093]
As requested here: https://emacs.stackexchange.com/questions/33921/how-to-switch-between-ivy-completion-styles

It might be useful if ivy-hydra's built-in `C-o m` command to toggle the re builder could also be used to switch to the `ivy--regex-ignore-order` builder -- or more generally to rotate between a customizable list of re builders.

**Comment by abo-abo** [comment]
Thanks, this would be useful to add. PR welcome.
