### ISSUE TITLE
Ivy vs. Cua Mode

### ISSUE THREAD

**Issue by technician77** [abo-abo/swiper#1099]
Took me some time to figure out but it turns out that when cua mode is enabled that M-v and C-v in minibuffer do not work, or to be exactly do something else. Is there a way to fix that without turning off cua mode?

Disclosure: I work on windows, not my choice. Constantly switching between the emacs standard bindings for copy/cut/paste and windows bindings got me headache so I turned on cua.

**Comment by basil-conto** [comment]
Do the keys `<prior>` and `<next>` (a.k.a. `PageUp` and `PageDown`) work, and is using them instead of `M-v` and `C-v`, respectively, an option?

**Comment by technician77** [comment]
No, they don't. They are coupled with M-v/C-v. If they work again, by disabling cua-mode, PageUp/Down also work again. Actually I prefer them over M-v/C-v since they are only one key.

When cua mode is enabled the beginning/end of buffer movement M-< and M-> C-Home and C-End works as expected. Problem is scroll-up/down is much more important at least to me.

**Comment by abo-abo** [comment]
Does this work for you?

```elisp
(define-key ivy-minibuffer-map (kbd "<next>") 'ivy-scroll-up-command)
(define-key ivy-minibuffer-map (kbd "<prior>") 'ivy-scroll-down-command)
```

**Comment by technician77** [comment]
It does. Thanks for that instant help.

**Comment by abo-abo** [comment]
You're welcome.
