### ISSUE TITLE
unfold sections in org-mode

### ISSUE THREAD

**Issue by bricewge** [abo-abo/swiper#11]
When used in an org buffer where some part of the file are folded swift don't temporary unfold them like isearch do. And when a search is stopped the folded section aren't unfold also, isearch do this.

**Comment by bricewge** [comment]
Thanks for the lightning response!
Now when the search end the section is unfold. But when the search is actually occurring the sections aren't temporary unfolded, so you can't see the context of your search.

**Comment by abo-abo** [comment]
I see now. This feature will take longer to implement.

**Comment by abo-abo** [comment]
Should work better now, let me know.

**Comment by bricewge** [comment]
Yes it is working now! 
However if a search is stopped with `C-g` the section where the cursor is doesn't come back to his initial state (ie: it stay unfolded if it was folded).

**Comment by abo-abo** [comment]
OK, should be better now.

**Comment by bricewge** [comment]
That's perfect, many thanks.
