### ISSUE TITLE
Reset to the first candidate when "C-h f" or "C-h v"

### ISSUE THREAD

**Issue by tumashu** [abo-abo/swiper#110]
is it possible deal with "describe-functions" (C-h f) and "describe-variable" (C-h v) like below?
for example,  I type "C-h f" at the end of "mapcar" 

```
Reset to the first candidate when switching directories

With ivy-mode you can select a file anywhere on your file system by switching directories repeatedly 

with C-j (ivy-alt-done). After moving to a new directory, the point should be on the first candidate.
```

**Comment by abo-abo** [comment]
> I type "C-h f" at the end of "mapcar"

Then the preselected candidate must be `mapcar`, which it is. I don't see a problem here.

**Comment by tumashu** [comment]
you said is right, but putting it to begin of menu is more easy "find-and-check".

**Comment by abo-abo** [comment]
I prefer to keep it the way it is. Having the candidate be between `mapcan` and `mapcar*` is more advantageous than having it at the top with no context.
