### ISSUE TITLE
How to toggle case-sensitive in a swiper session?

### ISSUE THREAD

**Issue by tddsg** [abo-abo/swiper#1104]
Hi,

I'd like to ask if it is possible to toggle case-sensitive during a `swiper` session?

I can do it during an `isearch` session, by pressing `M-c`, but couldn't figure how to do it with `swiper`.

Thank you for looking at my issue!

**Comment by fabacino** [comment]
Press `C-o` within swiper/ivy to get access to some options. You will find a toggle there for case-folding which might help you.

**Comment by tddsg** [comment]
Thank you for the suggestion. However, after pressing `C-o f` to toggle the case unfolding, it is a bit unfamiliar to me to get the cursor back to the place where I can continue the `swiper` session.

Would it make sense to make `swiper` can do something similar to `isearch`, i.e., just `M-c`?

Anyway, I will try learn to use to the `C-o` featuer of ivy.

**Comment by basil-conto** [comment]
@tddsg If you haven't already seen it, the relevant section of the Ivy Manual is [Hydra in the Minibuffer](http://oremacs.com/swiper/#hydra-in-the-minibuffer).

**Comment by ardpp** [comment]
@tddsg After `C-o C` pressing `C-o` again brings you back to the `swiper` session.
If you use this often you could bind the key like that 
`(define-key ivy-minibuffer-map (kbd "M-c") 'ivy-toggle-case-fold)`

**Comment by tddsg** [comment]
@basil-conto , @ardpp : thank you for the suggestion!

**Comment by abo-abo** [comment]
Thanks for helping, I close the issue.
