### ISSUE TITLE
when current buffer is inside a git repository, set git repository root path as default search path for counsel-locate 

### ISSUE THREAD

**Issue by beacoder** [abo-abo/swiper#1106]
when current buffer or file is inside a git repository, and we do a counsel-locate, can we default the search path for counsel-locate to the git repository root path ?

e.g :  
current file path:  /path/to/git-root/file.cpp
counsel-locate (/path/to/git-root) : 

as for the implementation: we could use the regexp option of locate to match again the root-path.
do you guys think it's valuable to implement it ?

thanks

**Comment by abo-abo** [comment]
`counsel-locate` wraps around `locate`, which is always system-wide. There's no option to restrict it to a directory. I don't think there should be, if you're looking in the current repo, use `counsel-git`.

**Comment by beacoder** [comment]
oh, forgive my ignorance, I think counsel-git is just the one I'm look for.
thanks.
