### ISSUE TITLE
counsel-git-grep fails with `Wrong number of arguments: nil, 1`

### ISSUE THREAD

**Issue by lepieru** [abo-abo/swiper#1107]
The `counsel-git-grep` interactive command fails with the error below:

```
Wrong number of arguments: nil, 1
```

I note this about a month ago.

Tested today on:
- GNU Emacs: 24.5.1 & 25.2.50.2
- Ivy: 20170711.910
- Counsel: 20170710.1111

**Comment by stotok** [comment]
I'm seeing the same issue.

**Comment by abo-abo** [comment]
Which OS? Can you reproduce with `emacs -Q`?

**Comment by lepieru** [comment]
Reproduced with `emacs -Q`.

Cannot reproduce on another computer with the same OS (Xubuntu 16.04 64bits, Linux 4.4.0-83-generic).

**Comment by abo-abo** [comment]
Please try it like this: clone this repository and type `make plain`. This works fine on my system (Ubuntu, Emacs 25, Git 2.13).

**Comment by lepieru** [comment]
This way it works with Emacs 25 but not with Emacs 24.

**Comment by abo-abo** [comment]
@lepieru Thanks for the info, I was able to reproduce on 24.5. Please check if it works now.

**Comment by lepieru** [comment]
I cannot reproduce it on Emacs 24 & 25.

Thank you for your work.
