### ISSUE TITLE
Ivy Ignoring User with Tramp

### ISSUE THREAD

**Issue by kevinjfoley** [abo-abo/swiper#1108]
When I run <kbd>C-x</kbd> <kbd>C-f</kbd> `/ssh:user@serverip:` <kbd>C-j</kbd> I get the following prompt : `Password for /ssh:serverip:` with no username.

If  I run the above under `emacs -q` tramp is able to connect fine without a password as I have a key for the user specified.

My setup for for ivy is:
```
(use-package ivy                        ; Minibuffer completion
  :defer t
  :init (ivy-mode 1)
  :bind (
         ("C-c b r" . ivy-resume)
         ("C-s" . swiper))
  :config
  ;; Include recentf and bookmarks to switch buffer, and tune the count format.
  (setq ivy-use-virtual-buffers t
        ivy-count-format "(%d/%d) "
        enable-recursive-minibuffers t
        ivy-re-builders-alist
        '((t . ivy--regex-fuzzy)))      
  :diminish ivy-mode)
```

Any idea why ivy seems to be dropping the user name I'm passing?

**Comment by abo-abo** [comment]
These work for me:

- `/ssh:` <kbd>RET</kbd>
- `/ssh:root@` <kbd>RET</kbd>
- `/ssh:ubuntu@cloud` <kbd>RET</kbd>

You get completion in stages, I use the first variant the most.

**Comment by kevinjfoley** [comment]
The problem is after I get the completion the user name is being thrown out.  So if I do
`/ssh:` <kbd>RET</kbd>
I'll get completions for previous connections I've attempted, however after I select one it gets rid of the user name and therefore the connection fails.

**Comment by kevinjfoley** [comment]
I just tried loading `ivy` under `emacs -Q` and it's working properly there.  I'm not sure what in my configuration would be causing the issue. Any suggestions on where to look?

**Comment by kevinjfoley** [comment]
I found the issue, at some point I added a proxy to `tramp-default-proxies-alist` which was messing things up.  Sorry for blaming your wonderful package @abo-abo, thanks for your work!

**Comment by abo-abo** [comment]
You're welcome.
