### ISSUE TITLE
Add ivy-switch-views to code

### ISSUE THREAD

**Issue by technician77** [abo-abo/swiper#1109]
Please have a look at #929 .
In this issue you suggested the function ivy-switch-views. How about adding it to the code of ivy? Since there are dedicated packages to offer similar functionality I think it makes sense to add it to the code. If you do a lot of window-switching using pre-defined windows or ivy-push-view it saves a lot of time over ivy-switch-buffer.

Kind regards,
tech77

**Comment by abo-abo** [comment]
Thanks.

**Comment by technician77** [comment]
I have to thank, one extra function not needed to be declared in the init.
