### ISSUE TITLE
counsel find file long path

### ISSUE THREAD

**Issue by longitude** [abo-abo/swiper#1110]
Hi, is it possible to wrap the file paths? I can't see the actual file name.

<img width="430" alt="screen shot 2017-07-18 at 7 15 41 am" src="https://user-images.githubusercontent.com/5510191/28314670-7f19823e-6b89-11e7-9e04-686b5e56451a.png">

**Comment by longitude** [comment]
Is there any way to wrap this text in mini buffer while using `counsel-find-file`

**Comment by abo-abo** [comment]
You can now set `ivy-truncate-lines` to nil to wrap the lines during completion.

**Comment by longitude** [comment]
awesome @abo-abo, thanks.

<img width="721" alt="screen shot 2017-07-28 at 7 21 28 pm" src="https://user-images.githubusercontent.com/5510191/28739579-0c443ba2-73ca-11e7-9812-253f7a931045.png">
