### ISSUE TITLE
Ivy interferes with `sql-connect` command

### ISSUE THREAD

**Issue by glucas** [abo-abo/swiper#1112]
At some point a change in ivy introduced a problem when trying to use the `sql-connect` command. The problem has been reported on [Emacs StackExchange](https://emacs.stackexchange.com/questions/34257/sql-connect-with-ivy): the completion cannot find a match regardless of the available set of connections and the input text. 

This was working fine in the past, but I don't recall when I first saw the problem appear. 

Think I can boil the test case down to this:

    (completing-read "Connection: " '("test") nil t nil nil '(nil) nil)

When I have ivy-mode on, this call won't let me complete 'test'. If I turn off ivy-mode, completion of 'test' works. It seems like the issue may be the DEF argument -- replacing that with `nil` works.

**Comment by abo-abo** [comment]
Thanks.
