### ISSUE TITLE
Add ivy-save-views to code 

### ISSUE THREAD

**Issue by technician77** [abo-abo/swiper#1113]
How about one more extra function to save all views to a file - which than can be loaded at emacs startup? This function would speed up the workflow for permanent views. I currently do this with macros with a function written by somebody else. In the case of ivy-views names were already given during ivy-push-view, so the code should be even simpler than the save-macro function shown below.
```
  (defun save-macro (name)
    "Save a macro. Take a name as an argument and save the last defined macro under this name."
    (interactive "SName of the macro :")
    (kmacro-name-last-macro name)
    (find-file "~/.emacs.d/macros.el")
    (goto-char (point-max))
    (newline)
    (insert-kbd-macro name)
    (newline)
    (save-buffer)
    (switch-to-buffer nil))
```
I load the macros using (load-file "~/.emacs.d/macros.el") and call macros directly in M-x.

**Comment by technician77** [comment]
Oh, it seem to be already discussed in #1079. But that shows there is demand for such a function.

**Comment by technician77** [comment]
Well I tried the user suggested functions, problem is that they don't produce elisp output so they must be explicitly loaded using a function, a simple (load-file "~/.emacs.d/ivy-views.el") won't work.

It works, but not really what I was looking for.

**Comment by basil-conto** [comment]
Closing in favour of #1079.  Please send further comments/clarifications/requests there.
