### ISSUE TITLE
[feature request] counsel mark ring for evil marks

### ISSUE THREAD

**Issue by rieje** [abo-abo/swiper#1117]
Basically, a counsel/swiper version of evil's `:marks`, which shows all the marks and their contents that can be navigated/selected. This would be far more useful than `:marks` as `:marks` does not show the contents (only line number), is on a separate buffer (this type of information being on the buffer akin to `counsel-yank-pop` is more fluid and intuitive), and being able to see the context of the mark contents in the actual buffer as you navigate through them in the minibuffer like the way swiper works is very useful.

I thought `counsel-mark-ring` was what I'm looking for but it's Emacs-related and I think it only works with marks that were pushed through different contexts (rather than manually pushed).

**Comment by abo-abo** [comment]
I don't know anything about how `evil` works. But if you find where it stores its marks, add it to `counsel-mark-ring` and open a PR.

**Comment by basil-conto** [comment]
Closing on the assumption that PRs #1368 (`counsel-evil-registers`) and #2247 (`counsel-evil-marks`) addressed this feature request.

Feel free to reopen if I'm mistaken.
