### ISSUE TITLE
Sample init file in README (or other documentation)

### ISSUE THREAD

**Issue by mn200** [abo-abo/swiper#112]
It would be nice if new users could be shown some sample things that they might add to their `init.el` files.

For example, I think I've done the right thing in writing

    (use-package swiper
      :ensure t
      :init (progn
              (ivy-mode))
      :bind (("C-s" . swiper)
             ("C-r" . swiper))
    )

but perhaps I'm missing out on other obvious things that I might do.

**Comment by abo-abo** [comment]
Thanks.

**Comment by mn200** [comment]
Thank you!  I'll have to look up the virtual buffer thing but I'm pleased I was roughly right.
