### ISSUE TITLE
Ivy-style code autocomplete duplicates prefix in Clojure mode

### ISSUE THREAD

**Issue by sooheon** [abo-abo/swiper#1120]
Typing the prefix of a symbol, and pressing tab in elisp mode gives me:

<img width="848" alt="screen shot 2017-07-26 at 2 21 35 pm" src="https://user-images.githubusercontent.com/302945/28605628-c63d49e0-720d-11e7-90f0-f7459a553141.png">

<img width="848" alt="screen shot 2017-07-26 at 2 21 46 pm" src="https://user-images.githubusercontent.com/302945/28605629-c67002a4-720d-11e7-9516-5dfede7308b7.png">

Doing the same in clojure mode gives me: 

<img width="848" alt="screen shot 2017-07-26 at 2 22 31 pm" src="https://user-images.githubusercontent.com/302945/28605676-e9720d7e-720d-11e7-9fb3-ba33fc71a21f.png">
<img width="848" alt="screen shot 2017-07-26 at 2 22 34 pm" src="https://user-images.githubusercontent.com/302945/28605677-e9a6fac0-720d-11e7-9be6-96a7f1d65924.png">

The prefix before starting completion gets repeated.

**Comment by abo-abo** [comment]
What's the source of the completion in `clojure-mode`? Do you get the same issue with `helm-mode`?

**Comment by sooheon** [comment]
The value of completion-at-point-functions is `(cider-complete-at-point tags-completion-at-point-function)`

Helm is not installing from Melpa for some reason, complaining about tar not found.

**Comment by abo-abo** [comment]
Works fine for me. Make sure it's not a problem with your config: by default, `tab` is not bound to completion. I call `complete-symbol` with <kbd>C-M-i</kbd>, and everything works.

I have the latest CIDER from Git, latest clojure-mode from MELPA.

**Comment by sooheon** [comment]
Unable to find a small repro case, closing for now.
