### ISSUE TITLE
read-directory-name offers files after changing directory

### ISSUE THREAD

**Issue by Wilfred** [abo-abo/swiper#1121]
`M-: (read-directory-name "foo: " "/etc/") RET DEL etc RET M->`

This is offering me files:

![ivy_files](https://user-images.githubusercontent.com/70800/28643975-88567a74-724f-11e7-86c6-f4aab918fd22.png)

Note that I'm not offered files when I initially view `/etc`, but only when leaving and re-entering the directory.

Possibly related: #804

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by Wilfred** [comment]
@abo-abo thanks, works as expected.
