### ISSUE TITLE
current regex completion style displayed in prompt [PATCH INCLUDED]

### ISSUE THREAD

**Issue by Boruch-Baum** [abo-abo/swiper#1124]
I found it annoying not being able to clearly know which completion method was currently being used by ivy, so I wrote a patch to add that information to the prompt, in the form of a short string, either "quote", "regex", "plus", "order", "fuzzy". It is extensible to future completion styles or user custom completion styles without extra work, because it pulls the string value from the suffix of the regex completion function name.

If you want me to re-submit this by cloning and making a pull request, I can do that, but it's a bit of a bother for such a simple patch, so please first let me know that you'll accept the pull (I see you have many pending). My preference is to avoid the clone / pull for this, and just ask for a mention in the commit / changelog.

[patch_ivy.txt](https://github.com/abo-abo/swiper/files/1181840/patch_ivy.txt)

**Comment by basil-conto** [comment]
In the same way that you find the lack of this information annoying, other users may find its permanent presence annoying. I think adding a user option to toggle this behaviour would be wisest.

Couple of nitpicks about the code itself:
* `ivy` uses `cl-lib`, so you should use `cl-search` instead of `search`.
* The indentation seems a bit off in places.

You may be interested in a relatively recent feature of [`ivy-hydra`](http://oremacs.com/swiper/#hydra-in-the-minibuffer), namely the easy rotation of regexp builders: #1094. The `ivy-hydra` panel always reports the current builder. See the user option `ivy--preferred-re-builders` and the `ivy-hydra` key `m`.

**Comment by Boruch-Baum** [comment]
1] I don't mind doing more coding work for this like adding a toggle option, but only once the project tells me that they want the contribution (ie. for my personal use the current code is fine, but I'm happy to contribute for others).

1.1] Another possible addition might be to indicate the current default action somewhere, either always or only once one invokes `ivy-next-action' or `ivy-prev-action'.

2] I haven't seen a need to install hydra, but as an outsider to that project, why have a 'panel' for a  keybindings modification package? Sounds like feature-creep that would be better within ivy itself.

**Comment by basil-conto** [comment]
I defer to the package author to speak from authority, but here are my 2 cents as a user:

1) Fair enough.

   1) I, and I'm sure others as well, would find this useful. However:

2) My understanding is that `ivy-hydra` is precisely the default intended interface for visual indication of the current action, regexp builder, etc. In particular, the keys `w`, `s` and `a` are bound to `ivy-prev-action`, `ivy-next-action` and `ivy-read-action`, respectively, and the panel summarises the current action.

   You are right that `hydra` is a keybindings modification package, but `ivy-hydra` uses `hydra` only for the developer's, not the user's, sake. The panel is not an interface to a keybinding package, but rather an interface summarising and allowing the switching of the regexp builder, current action, etc., just like your proposed changes. In other words, `hydra` is an implementation detail of `ivy-hydra`. Whether this was a good maintenance choice is a separate matter.

   For this reason, as well as the fact that `ivy-hydra` ships as a separate, optional "plugin" package, I find it hard to see how it counts as feature-creep at all, let alone negative creep.

   What I *would* describe as feature-creep, however, is the embedding of the `ivy-hydra` functionality into `ivy` proper. If such a conflation kept the `hydra` "implementation backend" I would consider it negative feature-creep, as it would introduce an additional dependency for functionality not directly related to `ivy` completion.

   If, instead, it were rewritten without the `hydra` dependency, I would consider it neutral/positive feature-creep, as it enriches `ivy` in terms of user-friendliness, power and flexibility. This is attested by the motivation for your patch.

   Please let me know if I've missed or misunderstood something.

**Comment by abo-abo** [comment]
I prefer that everyone opens pull requests.

The functionality in your patch is already available for customization in user's configs. Example:

```elisp
(defun test-prompt ()
  (format "(%S) M-x: " ivy--regex-function))

(ivy-set-prompt 'counsel-M-x 'test-prompt)
```
