### ISSUE TITLE
Default for `ivy-initial-inputs-alist` should be nil

### ISSUE THREAD

**Issue by Boruch-Baum** [abo-abo/swiper#1126]
I know this is an opinion, but here's my justification: the current default state undermines the strength of the default regex completion state. The only drawback of this suggestion is that the initial user entries will yield a larger list of candidates.

**Comment by abo-abo** [comment]
I like the current default. It's useful and it shows the option is there.

**Comment by basil-conto** [comment]
> the current default state undermines the strength of the default regex completion state

Depends on how you look at it, so yes, this is an opinion.

A more objective argument is that the current default goes against Emacs' core philosophy of being as unobtrusive/unopinionated as possible by default.
