### ISSUE TITLE
`ivy-hydra` as dependency or extension?

### ISSUE THREAD

**Issue by Boruch-Baum** [abo-abo/swiper#1127]
The documentation indicates that package `ivy-hydra` is an optional extension, but the `ivy` package binds `C-o` to something that attempts to load that package, which indicates that it is a dependency.

My opinion is that the `C-o` binding should not be made by package `ivy`, or it should be made conditionally on a check for the existence of package `ivy-hydra`.

**Comment by abo-abo** [comment]
I think most users would benefit from installing `ivy-hydra` and `swiper` and `counsel`. You can get by with just `ivy.el`, doesn't mean that you should. And it doesn't mean that the majority of users should write extra config because of a minor goal of providing a minimal ivy.el install.

**Comment by Boruch-Baum** [comment]
The point was that the package shouldn't be setting a keybinding that fails by default. Either define ivy-hydra as a dependency so the package manager will automatically pull it in, or have ivy itself, not the end-user, check before it creates the keybinding.
