### ISSUE TITLE
function `ivy-toggle-calling` doesn't always recognize initial default candidate & behaves badly

### ISSUE THREAD

**Issue by Boruch-Baum** [abo-abo/swiper#1128]
For the purpose of this issue description, consider `M-c` as the keybinding for function `ivy-toggle-calling`.

This problem is reproducible as follows:

Case 0: C-x b M-c
Result: It works! It opens the buffer to the selected candidate even though nothing has been typed in the input line.

Case 1a: M-x M-c
Result: Prints "Not an item" in the minibuffer, changes cursor focus to window outside minibuffer. Pressing `C-g` prints "Quit" in minibuffer, but minibuffer stays open, and cursor remains in another window. Change focus or do something else, and the original contents of the ivy minibuffer re-appear.

Case 1b: M-x <scroll> M-c
Result: It works.

Cases 2a & 3a: C-h f M-c     C-h v M-c
Result: Nothing happens

Cases 2b & 3b: C-h f <scroll> M-c     C-h v <scroll> M-c
Result: Nothing happens

**Comment by abo-abo** [comment]
`ivy-toggle-calling` makes sense only for functions that call `ivy-read` with an `:action` argument. This is a limitation of the `completing-read` interface and the built in functions that use it. There's not much that can be done about it right now, except preferring to use `counsel-...` functions on the user side.

**Comment by Boruch-Baum** [comment]
The suggestion would be that for the sake of consistency, since the package supplies counsel and is using it for some functions, keep it consistent and use counsel for the others.
