### ISSUE TITLE
freezes cursor action in other emacs clients

### ISSUE THREAD

**Issue by Boruch-Baum** [abo-abo/swiper#1131]
I am running emacs as a server with multiple non-gui client frames. If I begin an ivy instance in one client, and switch to a second client's frame, the cursor is frozen. This isn't just if the second client is in the minibuffer; it includes freezing of all user input in any buffer.

**Comment by abo-abo** [comment]
This is a generic Emacs bug, reproducible with just `read-from-minibuffer`. The only relation to `ivy` is that it relies on `read-from-minibuffer`. Use `report-emacs-bug`.
