### ISSUE TITLE
ivy-switch-buffer when virtual-buffers enabled, only has one entry for same-name, different-dir files

### ISSUE THREAD

**Issue by JJPandari** [abo-abo/swiper#1132]
e.g. I have a `path1/foo.el` and a `path2/foo.el` in my recentf list, `ivy-switch-buffer` only gives me one entry of `foo.el`, which leads to one of the two files.

Also, I tried to add  

```lisp
(setq ivy-use-virtual-buffers nil)

(defun recentf-list-no-properties ()
  (mapcar #'substring-no-properties recentf-list))
(ivy-set-sources
 'ivy-switch-buffer
 '((original-source)
   (recentf-list-no-properties)))
```

this adds full-path recentf list to 'ivy-switch-buffer' but when I pick one, ivy simply opens a buffer names the full-path name, not visiting the desired file.  

I'm using GUI emacs under Windows.

This is reasonable behaviour as I can see `ivy-switch-buffer` and `counsel-recentf` have quite different `:action`s. However I'm a beginner and not sure how to modify the `:action` to get desired result, and I feel this may be a common issue.

**Comment by ryankask** [comment]
Try this `(setq ivy-virtual-abbreviate 'full)` and see if helps.

**Comment by it6** [comment]
Is there a way to keep the `ivy-switch-buffer` view to `simple` (just the filename no path) and still see the both files that are opened recently.
