### ISSUE TITLE
problem with tab complete in shell

### ISSUE THREAD

**Issue by fkgruber** [abo-abo/swiper#1136]
Hi
I've been so me issues sometimes when I try to do tab complete on a shell and the windows is small.
Is there some adjustment to deal with cases like these?

For example, of the windows is big enough it works:
![image](https://user-images.githubusercontent.com/4311763/28921616-a48197b2-7824-11e7-9ef2-febc2c730683.png)

but if I shrink the windows a bit the tab complete just breaks. How to fix this?

![image](https://user-images.githubusercontent.com/4311763/28921647-cbcf95bc-7824-11e7-9ee4-e4b9623672f0.png)

Sometimes it works a partially:
![image](https://user-images.githubusercontent.com/4311763/28945631-46034b62-7875-11e7-8349-ec02a008e201.png)

**Comment by abo-abo** [comment]
Thanks. I've added a fall back to minibuffer for this situation.

**Comment by fkgruber** [comment]
Great thanks. is this change updated on melpa?

**Comment by abo-abo** [comment]
Yes. MELPA updates every 4 hours.

**Comment by fkgruber** [comment]
Which packages need to be updated? I updated ivy and counsel but I still see the same issue:
if I tab after ls fig_
![image](https://user-images.githubusercontent.com/4311763/29008278-5a3bde04-7ae2-11e7-9bff-adbd7c49c021.png)


I get 
![image](https://user-images.githubusercontent.com/4311763/29008280-6940de86-7ae2-11e7-8aba-055437ec496e.png)

**Comment by abo-abo** [comment]
Just remove the package from `elpa/` directory manually and restart/reinstall.

**Comment by fkgruber** [comment]
I tried removing ivy and counsel  and reinstalling and I still see the same issue. how can I check the version that is installed to make sure  I'm using the right one?
doing:
![image](https://user-images.githubusercontent.com/4311763/29344133-d5c165bc-8203-11e7-958d-00439241f374.png)
I get:
![image](https://user-images.githubusercontent.com/4311763/29344134-dc43e98c-8203-11e7-9a16-3599c06a6c48.png)

**Comment by fkgruber** [comment]
alternatively is there a way to disable ivy in a particular buffer while keeping it active in the rest?

**Comment by abo-abo** [comment]
You can use:

```elisp
(setq ivy-display-functions-alist nil)
```

But as far as I can see, the issue was fixed. If you can provide a reproducible scenario with `emacs -Q`, let me know.

**Comment by fkgruber** [comment]
I ran emacs -Q 
then executed

(package-initialize)
(ivy-mode 1)
(setq ivy-use-virtual-buffers t)
(setq enable-recursive-minibuffers t)

the I opened a second windows in the frame
opened a shell M-x shell

then make the shell window small using C-x ^

This breaks tab complete or C-M-i

Interestingly this does not happen in eshell. In eshell tab complete simply ignores ivy and C-M-i complete elisp commands and works fine.

**Comment by fkgruber** [comment]
Hi
I used 
(setq ivy-display-functions-alist nil)
to disable to options in-place ad use the minibufer instead. But how to do I go back to the default?

thanks

**Comment by abo-abo** [comment]
The previous fix was for the situation when there's not enough horizontal space.

The current fix is for the situation when there's not enough vertical space.

Please test again.
