### ISSUE TITLE
Does counsel-rg support colors? Also potential bug.

### ISSUE THREAD

**Issue by rieje** [abo-abo/swiper#1141]
Does counsel-rg support colors? When I change the base command from `--color never` to `--color auto`, it doesn't show any colors even though the base command when executed from the terminal does. If set to `always`, then I get weird results (ansi escape codes? Sorry, I'm a noob).

P.S. If I change the base command from `.` (current directory) to `~` and then use the prefix command `C-u` before executing `counsel-rg` to search in a particular directory like `/etc`, it doesn't show results from `/etc`. However, if I leave it the default (current directory) and do the same thing, then it shows the results. This seems like a bug, right? And should it be searching from both `/etc` and the current directory or just the current directory when the prefix argument is used?

**Comment by abo-abo** [comment]
> If set to always, then I get weird results (ansi escape codes?

That's correct. `counsel-rg` does highlight the file names and lines with colors, but not via ansi escape codes.

**Comment by abo-abo** [comment]
@dieggsy While it's possible, the `ansi-color-apply` solution is more complex and slower than what's being done now.
