### ISSUE TITLE
`ivy-restrict-to-matches' does not work with `counsel-git-grep'

### ISSUE THREAD

**Issue by Alexander-Shukaev** [abo-abo/swiper#1145]
Turns out `ivy-restrict-to-matches` has no effect when used with `counsel-git-grep`, which I indeed expected not to be implemented.  Any plans so far?

**Comment by Deewiant** [comment]
See also #902 (maybe this counts as a duplicate)

**Comment by abo-abo** [comment]
Indeed, it's a duplicate. Let's move the discussion there.
