### ISSUE TITLE
[Feature request] Highlight the regex matching part of the line in the candidates

### ISSUE THREAD

**Issue by rieje** [abo-abo/swiper#1147]
Similar to how there's (incremental) highlighting for candidates for Ivy/Counsel. For a specific example, I wanted to replace ag with ripgrep so I do a search in my init.el for "ag". Needless to say, I am getting tons of candidates. If the regex matching part of the string in each line is highlighted, it would be far easier to parse each line to see if it's what I'm looking for, rather than reading each line from left to right trying to find all instances of ag.

**Comment by abo-abo** [comment]
There's highlighting in both places by default. Unless I misunderstood what you're saying.

**Comment by rieje** [comment]
Through trial and error it seems the following is the culprit:

    (setq ivy-re-builders-alist
          '((swiper . ivy--regex-plus))
          (t . ivy--regex-ignore-order)))

Removing `(t . ivy--regex-ignore-order)` restores highlighting. Is this a bug or intended? Can I keep this setting and still have highlighting?

**Comment by abo-abo** [comment]
It's a bug then. I only use `ivy--regex-plus`, so I prioritize fixing that. PRs welcome.

**Comment by rieje** [comment]
Actually, I just checked and it seems commenting out either `(swiper . ivy--regex-plus)` or `(t . ivy--regex-ignore-order)` restores the intended behavior and having both settings results in no highlighting, so it's not an issue with `ivy--regex-ignore-order` but something else (hopefully that makes it more of a priority :)).

**Comment by abo-abo** [comment]
Please give me a reproducible scenario with `emacs -Q`.

**Comment by rieje** [comment]
With the following settings:

    (use-package ivy ; general completion mechanism
      :config
      (ivy-mode 1)
      (setq ivy-re-builders-alist
            '((swiper . ivy--regex-plus)
              (t . ivy--regex-ignore-order)
              )))

Use swiper and search for a string. incremental highlighting is shown in the visible buffer, but there is no highlighting of any sort in the minibuffer.

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by rieje** [comment]
Works now, thanks!
