### ISSUE TITLE
Changing the drive in Windows

### ISSUE THREAD

**Issue by kluge** [abo-abo/swiper#115]
Using find-file with ivy works well in moving within one drive. But I haven't figured out how to change the drive from e.g. C: to D:.

In ido-mode you can type "d:/" at any point and it changes to the root of D: drive. From my perspective the same logic could work really well. At least on Windows : is an illegal character in filenames so it's not going to conflict with files. And outside Windows there of course isn't even the concept of drives.

**Comment by abo-abo** [comment]
I don't have access to a Windows machine. But I'd welcome a reasonable patch. You just have to expand the code around this point:

```elisp
(when (string-match "//$" ivy-text)
  (ivy--cd "/"))
```

The change is simple, but it needs to be tested properly.

**Comment by abo-abo** [comment]
I hope it's fixed now.
