### ISSUE TITLE
ivy-completing-read does not allow selecting default value

### ISSUE THREAD

**Issue by darkfeline** [abo-abo/swiper#1156]
This can be demonstrated by calling `ert`.

``` emacs-lisp
(require 'ert)
(ert-deftest some-test ())
(call-interactively #'ert)
```

```
(1/1) Run tests (default t):
some-test
```

As far as I can tell, you can't actually select the default value of `t`.  Pressing `RET` selects `some-test` instead of `t`.  Pressing `C-M-j` selects the empty string (which is understandable).  The only way to select `t` is to type `t C-M-j` which is ridiculous for selecting a default value.

**Comment by darkfeline** [comment]
It looks like this is only happening because `ert` is passing an obarray as the collection?

**Comment by darkfeline** [comment]
Oh ffs, the preselect tries to match the collection by partial regexp match.

**Comment by darkfeline** [comment]
Looks like the bug is fixed in master, here's the bug locus in 0.9.1

https://github.com/abo-abo/swiper/blob/f4b433436668ac09f3d1815fbfb4b71f3e0690fa/ivy.el#L1708

**Comment by darkfeline** [comment]
I don't know what the proper procedure for this is, should bugfixes be backported, should I request a release, or should this bug be closed silently?

**Comment by abo-abo** [comment]
> I don't know what the proper procedure for this is, should bugfixes be backported, should I request a release, or should this bug be closed silently?

If there's a significant bug in ELPA that's fixed in master, I can make a minor release with a fix. No backports.

**Comment by darkfeline** [comment]
It would be nice to get a release with this fix.  I don't know if this counts as a significant bug, this causes it to be impossible to select the default value if the default value is a partial regexp match of another value in collection. `ert` is especially affected because the default value is `t` and test names often include `test`.

**Comment by abo-abo** [comment]
There's always <kbd>C-M-j</kbd> as the ultimate backup. If that doesn't work, the bug is indeed major.

**Comment by darkfeline** [comment]
<kbd>C-M-j</kbd> works in the sense that you type in the default value exactly.  So not major then, but very annoying as it makes the default choice harder to select than the other choices.

**Comment by basil-conto** [comment]
Can this issue be closed?

**Comment by darkfeline** [comment]
Looks like it's fixed in the latest release
