### ISSUE TITLE
los twhen selecting canditates

### ISSUE THREAD

**Issue by Lompik** [abo-abo/swiper#116]
Not really an issue but I was wondering :

While searching with `swiper-helm`, the screen is always centered on the candidates are centered in the searched buffer. Then when selecting a candidate and  after leaving swiper, it can be either centered, at bottom or at top of the buffer. Wouldn't it make more sense to be consistent with previous state of centering ?

**Comment by abo-abo** [comment]
Thanks.

**Comment by blaenk** [comment]
This is happening to me as well. I was gonna file an issue but I figured I'd search first and found this. I'm using regular swiper not swiper-helm and this is happening to me. Any idea?

**Comment by abo-abo** [comment]
@blaenk I've added a defcustom for this. I don't switch it on myself, since I want to avoid a double recenter. See if it helps you.

**Comment by blaenk** [comment]
@abo-abo It works, thank you!

Not sure what you mean about a double recenter though. I guess because when you're cycling through the candidates it centers the candidate in the buffer? I guess the problem for me is that once you choose it, it's no longer centered. The new defcustom works fine though, thanks again!

**Comment by abo-abo** [comment]
> once you choose it, it's no longer centered

It's recentered every time the candidate changes. That's the first recenter. But that one is w.r.t. the window width minus the height of the minibuffer.  When you exit, the window size increases, and it's no longer centered. So you'd maybe want a second recenter. But I dislike my screen moving too much.

Still, with the new defcustom you can hold <kbd>C-M-n</kbd> to have your line always centered.

**Comment by blaenk** [comment]
Ah I understand now why the line is no longer centered after choosing it. That makes sense.

Thanks again.
