### ISSUE TITLE
[Question] Is it possible to prefilter EShell history commands

### ISSUE THREAD

**Issue by juergenhoetzel** [abo-abo/swiper#1161]
In `EShell` I use

```elisp
(define-key eshell-mode-map [remap eshell-previous-matching-input-from-input] 'counsel-esh-history)
```

which works fine :+1: . But it would be even more useful if I could pass the current command line (from `(point)` to `(eshell-bol)` to prefilter the candidates. Is this feasible?

**Comment by juergenhoetzel** [comment]
> It's not hard, but you'll have to customize it. I don't think filtering the shell history on an already entered input is an established UX.

Thanks for your quick feedback! 

Could you give me a hint how to customize this? Im  am still studying `ivy` internals.

My use case in EShell:

1. I wan't to start an application using a specific parameter and start typing `application --property=`
2. Then I realize I forget the exact name of the parameter

It would be nice if i dont't have type the prefix of the command again.

**Comment by abo-abo** [comment]
Your use case isn't searching through history then. It's completion at point.

You can write your own function e.g. `(defun my-application-property-handler () ...)` and add it to `completion-at-point-functions`; then use `completion-at-point` (<kbd>C-M-i</kbd>).

See for example `org-completion-symbols` in my config for custom completion at point in Org-mode.

**Comment by juergenhoetzel** [comment]
Thanks for your hints ...and again for this awesome package. I have never looked back to `helm`
