### ISSUE TITLE
Insufficient matching with :dynamic-collection

### ISSUE THREAD

**Issue by fice-t** [abo-abo/swiper#1162]
Consider these two `ivy-read` forms:

```elisp
(ivy-read "Test: " (lambda (_s &optional _p _t) '("key" "krool")))
(ivy-read "Test: " (lambda (_s &optional _p _t) '("key" "krool")) :dynamic-collection t)
```

Typing, e.g., "l" in the first form will match the "l" in "krool", but not in the second form. Ideally, it would also match with a non-nil `:dynamic-collection.`

**Comment by fice-t** [comment]
@abo-abo: Looks like the `(ivy-state-dynamic-collection ivy-last)` branch in `ivy--exhibit` doesn't include an `ivy--filter` call like the other branch does. Including that call makes the `:dynamic-collection` case work as expected.

**Comment by abo-abo** [comment]
I think there's a misunderstanding here: `:dynamic-collection t` means that the collection function itself is responsible for the filtering. In other words, anything returned by the collection function already matches by definition.

Here's a sample code that works:

```elisp
(ivy-read "Test: "
          (lambda (s &optional _p _t)
            (cl-remove-if-not
             (lambda (x) (string-match s x))
             '("key" "krool")))
          :dynamic-collection t)

```
