### ISSUE TITLE
Is there a way to stop ivy autocomplete

### ISSUE THREAD

**Issue by longitude** [abo-abo/swiper#1169]
While autocomplete filenames in mini-buffer is great, sometimes I want to step out of autocomplete. 

For example I have a file named `abc.txts` I want to rename it to `abc.txt` autocomplete matchs my original file `abc.txts` and I have no option to rename file to be `abc.txt`. 

This is kind of an edge case but in general it would be ideal to stop ivy autocomplete and allow user to take over.

**Comment by abo-abo** [comment]
It's a common use case, there's an item in the FAQ for this: press <kbd>C-M-j</kbd> to have the completion accept the current text, instead of the current candidate.

**Comment by dieggsy** [comment]
@longitude FWIW you can also set `ivy-use-selectable-prompt` to `t` to allow choosing your own input as an option, which some find easier to remember than `C-M-j`.

**Comment by longitude** [comment]
Solved!! thanks @abo-abo and @dieggsy
