### ISSUE TITLE
Question concerning swiper-avy

### ISSUE THREAD

**Issue by ardpp** [abo-abo/swiper#117]
I try to use `swiper-avy` as described here https://github.com/abo-abo/swiper/releases/tag/0.5.0

If I have around 10 matches in swiper and press `C-'` then as expected keys a or s or d ... are assigned to the matches. When I press one of the keys then the minibuffer becomes active and "Mark set" is written there. I would expect the point to jump to the corresponding match. 

Am I doing something wrong?

Thanks, 
Andrej

**Comment by abo-abo** [comment]
What's your Emacs version? Can you try to reproduce the bug with only `swiper` and `avy` loaded?

**Comment by ardpp** [comment]
The Emacs version is 24.5.1
Now started emacs with `emacs -Q`, then loaded `swiper` and `avy`
and set the keys by evaluating the following in scratch buffer
  `(global-set-key (kbd "C-'") 'avy-goto-char-2))`
  `(global-set-key "\C-s" 'swiper)`
 ` (global-set-key "\C-r" 'swiper)`
still the same behaviour

**Comment by abo-abo** [comment]
I can't reproduce on 24.4.1, 24.5.2 or 25.  I'll see if I can make `swiper-avy` work in an alternative way.  Maybe someone else could confirm the bug as well.

**Comment by abo-abo** [comment]
Got it. The problem was the setting of `avy-all-windows`.  Thanks for bringing this up.

**Comment by ardpp** [comment]
It works as expected now, but only if I do not use 
`(global-set-key (kbd "C-'") 'avy-goto-char-2)`
in avy settings (as you suggested somewhere). Is it possible to have `C-'` for avy-goto-char-2 as long as it is not used for swiper-avy?

**Comment by ardpp** [comment]
Have to correct myself unfortunately. At the moment avy in swiper works well when matching candidates are close to each other so that they fit in one window. Then I just have avy acting on matching candidates and then it works as expected.  In my opinion it would be good to have avy in the "swiper area" where all the candidates are shown.

If the matching candidates are far away from each other, then I get the sam behaviour as befort, even if I do not use `(global-set-key (kbd "C-'") 'avy-goto-char-2)`

**Comment by ardpp** [comment]
I ovelooked that you wanted to jump to "one of the matches visible on screen". That works fine. Please disregard my complaint above.
