### ISSUE TITLE
ivy with 3.5M candidates is slow

### ISSUE THREAD

**Issue by jkitchin** [abo-abo/swiper#1174]
I have a list of 3.5 million candidates I wanted to use in ivy-read. It is pretty slow, it takes about 3 seconds to load the ivy selection minibuffer, and about that many seconds every time I type a letter to update. I can live with the initial delay, but I wondered if there was a way to delay the update to not occur during every key press, but maybe after some idle delay?

**Comment by abo-abo** [comment]
What's the source of the 3.5 million candidates? In any case, you can make use of `:dynamic-collection` to improve the speed. See e.g. `counsel-ag`.

**Comment by abo-abo** [comment]
Or if you're not connecting to a shell command, see `swiper-all`.

**Comment by basil-conto** [comment]
Another possible "optimisation" could be to make use of `counsel-more-chars` or similar to reduce the initial number of candidates as much as possible, right?

**Comment by abo-abo** [comment]
Yes, of course. It's not feasible to tackle 3.5 million candidates without optimizations:

```elisp
(progn (setq x (number-sequence 1 3500000))
       1)

(benchmark-run 1
  (mapcar (lambda (y) (* y y))
          x))
;; =>
;; (0.623433223
;;  1
;;  0.19014808799999994)
```

Just the simple number multiplication takes 0.6 seconds. Doing a regex match is longer.

**Comment by jkitchin** [comment]
The source of the 3.5M candidates is a file, with one candidate per line. I read the file once into a variable to get a list of the candidates, and then use the variable in an ivy-read. It looks like it is more responsive to use grep similar to what you did here: https://github.com/abo-abo/swiper/issues/163 with both of those suggestions.

Thanks for the tips!
