### ISSUE TITLE
Suggest to add a function to move cursor to the next/previous candidate on the same line

### ISSUE THREAD

**Issue by zzhjerry** [abo-abo/swiper#1175]
It's great to jump across lines after searching with `C-n` and `C-p`. It's much faster to get to the desired candidate than `isearch-forward`

But when there are more than one candidates appeared on the same line and the second or further candidate on the that line happens to be the place I want to put my cursor at after searching, I need to hit `RET` first to end searching and keep pressing `C-f` (or other jumping functions) until the cursor get to the point I wanted it to be. 

So I think it would be nice for me to be able to select next or previous occurrence of the candidate on the same line without ending the search. (a.k.a the cursor can be placed at the exact candidate's position within the search)

![image](https://user-images.githubusercontent.com/4972027/29758168-e4df9b9c-8be3-11e7-9e0f-3c7f0f4e3b4b.png)

A great experience would be:

1. Press `C-s` to start `swiper`
2. Press `C-s` to (be able to) select previous history
3. Press `C-n` and `C-p` to get to the desired line.
4. Press `C-s` to select next occurrence of the candidate on that line
5. Press `C-r` to select previous occurrence of the candidate on that line

**Comment by ardpp** [comment]
Have you tried `swiper-avy` which is bound to `C-'` during swiper search?

**Comment by abo-abo** [comment]
@ardpp Exactly, that's the current solution to multiple candidates on one line.

Additionally, `swiper-all` doesn't have this problem, since it's not line-based.

**Comment by zzhjerry** [comment]
Very appreciate your replies @abo-abo @ardpp. 

The reason I'm not in favor of `avy` way of cursor movement is it consumes more brain power when typing those jumping letters. However movement by searching and cycle through the list of candidates feels more natural, even it may require more repeated key strokes to get to the right place. (which is the reason I suggested `point 4`)

`swiper-all` is the closest to what I wanted, but it loses the ability to jump by lines, which has the same issue I mentioned about `isearch-forward`.

Hope this proposal could be re-considered.
