### ISSUE TITLE
counsel-git-grep does not accept spaces in search string

### ISSUE THREAD

**Issue by noorul** [abo-abo/swiper#1176]
The following command works in command line

git --no-pager grep --full-name -n --no-color -i -e 'def test_'

But when I try to search 'def test' using counsel-git-grep, it returns nothing.

**Comment by abo-abo** [comment]
Are you using custom `counsel` settings? I'm using the defaults, which translate the input `def test ` into the regex `def.*test`. You can get literal spaces by stacking multiple spaces: two spaces in a row match a single space etc.

In your input, the trailing space doesn't matter, the final regex given to the shell should be the same as for input `def test`.

**Comment by noorul** [comment]
I had a custom setting. I removed it and it works now, but it does not give the desired output.

When I use the following 

git --no-pager grep --full-name -n --no-color -i -e 'def test_'

It gives me only the ones start with "def test_" but counsel returns more like the ones with def generate_test_data() too. I am not sure why counsel is not passing the string as it is to git-grep

**Comment by dgchurchill** [comment]
I seem to have a related problem. I'm on Windows, with `counsel-git-grep-skip-counting-lines` set to its default of `nil`. This means `counsel--git-grep-count` gets initialized to 0 in `counsel-git-grep`. Then in `counsel-git-grep-function` the condition `(or counsel-git-grep-skip-counting-lines (> counsel--git-grep-count 20000))` evaluates to `nil` meaning the `(counsel-more-chars 3)` check is skipped and the executed command is `git --no-pager grep --full-name -n --no-color -i -e ''`.

Setting `counsel-git-grep-skip-counting-lines` to `t` seems to fix the git command being executed, but then I actually get no results. Still investigating...

**Comment by abo-abo** [comment]
@noorul This is expected and is a feature:

- input `def test` means: search for `def.*test`
- input `def  test` means: search for `def test`
- input `def   test` means: search for `def  test`
- etc.

@dgchurchill Try to customize `counsel-git-grep-cmd-default`. Windows has problems when single quotes get passed in a command.

**Comment by dgchurchill** [comment]
Thanks @abo-abo. Setting `counsel-git-grep-cmd-default` to `"git --no-pager grep --full-name -n --no-color -i -e \"%s\""` solved my problem. Apologies for hijacking this thread when my issue turned out to be unrelated.

**Comment by noorul** [comment]
@abo-abo `def  test_` worked! Thank you! Closing this!
