### ISSUE TITLE
counsel-dired-jump does not respect "find-program"

### ISSUE THREAD

**Issue by rgemulla** [abo-abo/swiper#1181]
I am using Emacs on Windows and customized the variable ```find-program``` to point to Cygwin's find executable. ```counsel-dired-jump``` does not respect this variable, however. This patch fixes the problem:

```lisp
-              (split-string
-               (shell-command-to-string "find * -type d -not -path '*\/.git*'")
-               "\n" t)
+              (split-string
+               (shell-command-to-string (concat find-program " * -type d -not -path '*\/.git*'"))
+               "\n" t)
```

The same issue arises in counsel-file-jump.

**Comment by abo-abo** [comment]
Thanks.

I remember having some success a year ago running a graphical Emacs installed from Cygwin. The integration was very seamless - 0 lines of customization compared to my Linux config. Except the display felt a bit clunkier compared to the native build. Just a suggestion, if you haven't tried it yet.
