### ISSUE TITLE
counsel-M-x populates history for the execute-extended-command

### ISSUE THREAD

**Issue by mookid** [abo-abo/swiper#1185]
On a setup that uses both `counsel-M-x` and `execute-extended-command`, the history becomes hard to use.

For instance:
`M-x counsel-M-x`
input "^cou git"
select the candidate `counsel-git`
later,
`M-x`
`M-p`

Here I get the previously entered string in the history, which is not really that helpful.

I see two possible improvements:
+ keep a separate history for the replacement command
+ keep a separate history and put the selected candidate in the history of the original command

What do you think about this?

**Comment by abo-abo** [comment]
> What do you think about this?

Doesn't using `counsel-M-x` imply you're using `ivy-mode`? In that case, `^cou git` still works for `execute-extended-command`.

**Comment by mookid** [comment]
I am not using `ivy-mode`, just binding a bunch of commands; I am interested in both behaviors.

**Comment by abo-abo** [comment]
Thanks.
