### ISSUE TITLE
counsel-rg opens files relative to the wrong directory

### ISSUE THREAD

**Issue by Stebalien** [abo-abo/swiper#1189]
In latest counsel version published on melpa (20170906.1103), `counsel-rg` (and probably all the searchers), open files relative to the current default directory, not relative to the project (git) root.

For example, say I'm viewing `foo/bar.c`, search for "thing", and find that `main.c` contains "thing", when I try to activate that search result, ivy will try to open `foo/main.c` instead of `main.c`.

**Comment by abo-abo** [comment]
@Stebalien I can't reproduce; I tried creating a small Git repo based on your description, but everything works for me.
@mookid Could you please check?

**Comment by mookid** [comment]
@abo-abo I'll take a look later today.

**Comment by Stebalien** [comment]
Were you visiting `foo/bar.c` (that is, was your default directory set to `foo`)?

**Comment by abo-abo** [comment]
@Stebalien I had no problem jumping from `foo/bar.c` to either `main.c` or `foo/main.c`.

**Comment by mookid** [comment]
I can't reproduce it either.

Detailed steps to reproduce:
```
$ mkdir swiper1189 && cd swiper1189 && git init
$ mkdir -p a/b/c/d
$ echo foobar >>a/b/c/d/foo.txt && git add a/b/c/d/foo.txt && git commit -m "test"
$ echo foobar >>main.c && git add main.c && git commit -m "test"
$ cd a/b/c/d
$ emacs -Q --eval '(push "~/swiper" load-path)' -l counsel.el foo.txt
```

there, 
+ `M-x counsel-rg foo RET` yields both results
+ `M-: default-directory` gives `/tmp/swiper1189/a/b/c/d/`

@Stebalien : can you try to reproduce and find what is missing in the recipe?

**Comment by manuel-uberti** [comment]
Can't reproduce it either.

**Comment by Stebalien** [comment]
This looks like it was magically fixed and I don't see any relevant commits... maybe a bad interaction with something else?

Oh well, sorry for the noise.
