### ISSUE TITLE
Virtual buffers not opening recentf files with full paths

### ISSUE THREAD

**Issue by qdot** [abo-abo/swiper#119]
With ivy-use-virtual-buffers set to true, I can see things from recentf when pulling up my buffer list. However, if it's for a file that's not currently open, when I select it the buffer opens with the file name, but in whatever the current path is.

**Comment by abo-abo** [comment]
Works fine for me. What's your Emacs version? Could you try to edebug `ivy--switch-buffer-action`?  Or just eval `ivy--virtual-buffers` and `ivy--current` after the bug happens.

**Comment by qdot** [comment]
I'm on 24.5. When I run ivy--virtual-buffers, I get back a list like

(#("smex.el" 0 7 (face ido-virtual)) #("WebIDL.py" 0 9 (face ido-virtual)) #("adoc-mode-autoloads.el" 0 22 (face ido-virtual)) #("flycheck-autoloads.el" 0 21 (face ido-virtual)) #("markdown-mode-autoloads.el" 0 26 (face ido-virtual)) ... )

Which looks like it has the name, and the font face, but is missing the file it should point to?

**Comment by abo-abo** [comment]
> Which looks like it has the name, and the font face, but is missing the file it should point to?

`ivy--virtual-buffers` variable holds the files alist.
`ivy--virtual-buffers` function returns only a list of strings.

**Comment by qdot** [comment]
Ah, ok, variable looks fine actually. Will see what's going wrong in switch-buffer. There may be a conflict between this and some of the old workgroups ido stuff I had set up.

**Comment by qdot** [comment]
Yup, ok, my fault. Turns out workgroups was using its switch to buffer while using ivy as the completion mechanism under it. So it got lists of virtual buffers but didn't know what to do with them, hence my issues.
