### ISSUE TITLE
counsel-org-tag add multiple tags at once? C-M-m only inserts 1st selected tag

### ISSUE THREAD

**Issue by zeltak** [abo-abo/swiper#1191]
Hi

This may be a trivial questions. but when i launch counsel-org-tag, how does one add multiple tags at the same time?  when i use C-M-m only the first tag is actually inserted to the heading. 

So if i want to and tag `A` and tag `B` to get `:A:B:` i use multi select (C-M-m) and select A and B in counsel-org-tag but i end up with :A: only.
EDIT: also another issue related to this is that i just notices that C-M-m dosent work in counsel-org-tag for some bizarre reason when i it is launched from a org-capture template using  `%^G` 

thx

Z

**Comment by abo-abo** [comment]
`C-M-m` and `C-m` are toggles. Be sure you're not turning `A` on with `C-M-m` and then turning it off with `C-m`.

**Comment by zeltak** [comment]
thx @abo-abo 
so after investigating a bit i can report the following
with point on header when i issue `counsel-org-tag` i can indeed use the multiselect `C-M-m` and as long as i use `C-M-j` to finalize it works quite well
But when counsel-org-tag is launced via the org capture method (`%^G` in the templates) the `C-M-m` just dosent do anything. is this a bug? or some conflict with counsel-org-tag and the orc-capture templates?

thx alot

Z

**Comment by abo-abo** [comment]
> But when counsel-org-tag is launced via the org capture method (%^G in the templates) the C-M-m just dosent do anything. is this a bug?

While it's not a good behavior, it's expected and can't be fixed. `C-M-m` works only if you call `counsel-org-tag`; when you capture a template `counsel-org-tag` isn't launched.

**Comment by zeltak** [comment]
i see bummer :) if so then any clue how to disable ivy *only* during the capture  (%^G in the templates). Now since i use Ivy gloably it auto uses `counsel-org-tag` for selecting tag in templates. Can i disable ivy just for the capture part?

thx @abo-abo 

Z

**Comment by abo-abo** [comment]
You can disable `ivy` for certain commands with `ivy-completing-read-handlers-alist`.

**Comment by zeltak** [comment]
mm thx!
i tried this

```

  (add-to-list
   'ivy-completing-read-handlers-alist
   '(org-set-tags-command . completing-read-default))
```
but that dosent really seem to work

any clue?

best

Z

**Comment by bdillahu** [comment]
@zeltak Did you by chance find a way to disable this?

**Comment by zeltak** [comment]
@bdillahu  not yet unfortunately.. :(

**Comment by abo-abo** [comment]
@zeltak You need to use the actual command you call (e.g. <kbd>M-x</kbd> `org-set-tags`):

```elisp
(add-to-list
   'ivy-completing-read-handlers-alist
   '(org-set-tags . completing-read-default))
```

In your above code you used `org-set-tags-command` instead, which is not correct.

**Comment by zeltak** [comment]
thx that worked!

Z
