### ISSUE TITLE
After latest update counsel-ag stopped working

### ISSUE THREAD

**Issue by UtamaruMonster** [abo-abo/swiper#1195]
Error that i get 
```Error in post-command-hook (ivy--exhibit): (void-variable counsel--git-grep-dir)```

**Comment by abo-abo** [comment]
The variable `counsel--git-grep-dir` was merged with `counsel--git-dir`.

So if you had some custom code relying on it, rename accordingly. If not, I think reinstalling / restarting Emacs should fix your issue.

**Comment by UtamaruMonster** [comment]
Sorry about that, already resolved should be on my side ```counsel--git-dir``` as u said.
