### ISSUE TITLE
negative pattern doesn not work for all the grep program

### ISSUE THREAD

**Issue by redguardtoo** [abo-abo/swiper#1199]
Input `keyword1 !keyword2`, and got zero candidates .

test with `counsel-git-grep`, `counsel-grep`, `counsel-ag`, `counsel-rg`, all failed (version 20170911.103 from melpa).

`counsel-git-grep-occur` is OK. Other `occur` failed.

**Comment by dcorking** [comment]
I think you opened a duplicate at https://github.com/abo-abo/swiper/issues/1342 where it got more attention.
