### ISSUE TITLE
save position of the last search

### ISSUE THREAD

**Issue by bricewge** [abo-abo/swiper#12]
With isearch when you have found something the position of the last search is recorded. So that after you can go back to what you just search. And also search again the same thing by doing `C-s C-s`

**Comment by bricewge** [comment]
Maybe I should have split this issue in two.
Now the position of the last searched item is recorded. But I still can't search my last search by doing `C-s C-s` like isearch.

**Comment by zeltak** [comment]
is the search my last search implemented already (i see this request is 1 year ago)? i would also love to bring up the last search term in swiper

thx

Z

**Comment by abo-abo** [comment]
@zeltak <kbd>C-s C-s</kbd>.
