### ISSUE TITLE
Question: what's the difference between `counsel` and `ivy-mode`

### ISSUE THREAD

**Issue by bixuanzju** [abo-abo/swiper#120]
It may be a silly question ;) After enabling `ivy-mode`, `describe-function` uses ivy completion method, is it different from, say invoking `counsel-describe-function`?

**Comment by abo-abo** [comment]
It's a good question.

With `ivy-mode`, Ivy is provided with a list of choices and it can help you to select one.  But it has no idea what will be done with the choice that you made - it has no idea which function called it.  And a lot of the time, it's good enough.

But take this example: `counsel-describe-function` improves on `describe-function`, its default action is to describe, but if you press <kbd>C-.</kbd> it will instead jump to that function's definition.  So in this case, Ivy *has control* on what will be done with the choice that you select.

Another reason is `ivy-resume`: for non-affiliated functions (i.e. `counsel-`, `swiper-`, `lispy-`), it's impossible. Ivy can remember the list of candidates and resume it, but it has no idea what should be done with the result. That information is never passed through the `completing-read-function` interface.

Yet another reason are <kbd>C-M-n</kbd> (`ivy-next-line-and-call`) and <kbd>C-M-p</kbd> (`ivy-previous-line-and-call`).  They can't work for non-affiliated functions. Try it for `counsel-describe-function`: you'll get a `*Help*` window each time without exiting the completion interface.

**Comment by bixuanzju** [comment]
@abo-abo That is cool! Thank you for your clarification. I just switched from `Helm` to `ivy` ;)
