### ISSUE TITLE
Hiding buffers by major-mode in ivy-switch-buffer?

### ISSUE THREAD

**Issue by dieggsy** [abo-abo/swiper#1206]
Is there a way to hide, for example, all `dired` buffers? This might be useful, though if it's too niche I'll take hints on how to do it myself :)

**Comment by abo-abo** [comment]
It's easy to hide `dired` buffers - just modify the collection, or pass `:predicate` to `ivy-read`; it's more interesting how to bring them back.

One nice option might be the one `counsel-find-file` uses to hide the files that start with a dot - they become visible if either the first char in the input is `.`.
It passes `:matcher #'counsel--find-file-matcher` to `ivy-read`. Here's the code of the matcher:

```elisp
(defun counsel--find-file-matcher (regexp candidates)
  "Return REGEXP matching CANDIDATES.
Skip some dotfiles unless `ivy-text' requires them."
  (let ((res (ivy--re-filter regexp candidates)))
    (if (or (null ivy-use-ignore)
            (null counsel-find-file-ignore-regexp)
            (string-match "\\`\\." ivy-text))
        res
      (or (cl-remove-if
           (lambda (x)
             (and
              (string-match counsel-find-file-ignore-regexp x)
              (not (member x ivy-extra-directories))))
           res)
          res))))
```

You can customize your matcher to e.g. skip dired buffers if the input starts with `-d`.

**Comment by dieggsy** [comment]
Taking inspiration from that, I came up with the following:

```emacs-lisp

(defun ivy--switch-buffer-matcher (regexp candidates)
  "Return REGEXP matching CANDIDATES.
Skip buffers that match `ivy-ignore-buffers'."
  (let ((res (ivy--re-filter regexp candidates)))
    (cond ((or (null ivy-use-ni?ignore)
               (null ivy-ignore-buffers))
           res)
          ((string-match "\\`\\." ivy-text)
           (cl-remove-if
            (lambda (buf)
              (or
               (cl-find-if
                (lambda (f-or-r)
                  (if (functionp f-or-r)
                      (funcall f-or-r buf)
                    (string-match-p f-or-r buf)))
                ivy-ignore-buffers)))
            res))
          (t
           (or (cl-remove-if
                (lambda (buf)
                  (or
                   (cl-find-if
                    (lambda (f-or-r)
                      (if (functionp f-or-r)
                          (funcall f-or-r buf)
                        (string-match-p f-or-r buf)))
                    ivy-ignore-buffers)
                   (and (get-buffer buf)
                        (with-current-buffer buf
                          (member major-mode '(dired-mode wdired-mode))))))
                res)
               (and (eq ivy-use-ignore t)
                    res))))))
```
However, if i change the `string-match` text to `-d` or almost anything else, the dired buffers don't show. It works with `.` okay, though it'd be nice if it was some other switch. I suspect that the reason `.` works well is because of the regex matching, but with `-d` no buffer actually matches that, so no results are shown. Is there a workaround for this, or am I going about that incorrectly.

**Comment by dieggsy** [comment]
I suppose I mean I'm trying to do the opposite, that is, only _show_ dired buffers when the input starts with `-d` or `+d` or whatever.

**Comment by amosbird** [comment]
Hi, how can I use " " as the text to review hided buffers? I tried " ", "\\ ", "\\` " and  "\\`\\ ". None of them work.

**Comment by abo-abo** [comment]
@amosbird What's your config?

**Comment by amosbird** [comment]
Hi, 
```
(push (lambda (buf) (and (get-buffer buf) (with-current-buffer buf (memq major-mode '(dired-mode wdired-mode))))) ivy-ignore-buffers)
(defun +amos*switch-buffer-matcher (regexp candidates)
  "Return REGEXP matching CANDIDATES.
Skip buffers that match `ivy-ignore-buffers'."
  (let ((res (ivy--re-filter regexp candidates)))
    (if (or (null ivy-use-ignore)
            (null ivy-ignore-buffers)
            (string-match "\\`\\." ivy-text))
        res
      (or (cl-remove-if
           (lambda (buf)
             (cl-find-if
              (lambda (f-or-r)
                (if (functionp f-or-r)
                    (funcall f-or-r buf)
                  (string-match-p f-or-r buf)))
              ivy-ignore-buffers))
           res)
          (and (eq ivy-use-ignore t)
               res)))))
(advice-add #'ivy--switch-buffer-matcher :override #'+amos*switch-buffer-matcher)
```

**Comment by dieggsy** [comment]
A satisfactory option I've found for this is the following:
```emacs-lisp
  (defun d/ignore-dired-buffers (buf)
    (when (get-buffer buf)
      (with-current-buffer buf
        (when (eq major-mode 'dired-mode)
          t))))

  (add-hook 'ivy-ignore-buffers 'd/ignore-dired-buffers)
```
This will make dired buffers hidden in the same way as buffers hidden by regexp, showing them if the search criteria matches the name of the dired buffer (and not the name of an open buffer).

**Comment by abo-abo** [comment]
@dieggsy If the issue is solved, please close. Maybe add your solution to the wiki if you have the time.

**Comment by dieggsy** [comment]
@abo-abo done, though how do i categorize under "Customzations"?

**Comment by basil-conto** [comment]
@dieggsy FWIW I would prefer to write

```el
(defun d/ignore-dired-buffers (str)
  "Return non-nil if STR names a Dired buffer.
This function is intended for use with `ivy-ignore-buffers'."
  (let ((buf (get-buffer str)))
    (and buf (eq (buffer-local-value 'major-mode buf) 'dired-mode))))

(add-to-list 'ivy-ignore-buffers #'d/ignore-dired-buffers)
```

In particular, I'm not sure it's advisable to use `add-hook` for modifying something that isn't a hook.

**Comment by dieggsy** [comment]
@basil-conto I like it. Agreed. (I don't usually use `add-hook` for modifying non-hook variables, I was mostly trying it cause I had seen the usage somewhere and wanted to see what it did, forgot to revise).
