### ISSUE TITLE
ivy-completing-read does not expose defaults through M-n

### ISSUE THREAD

**Issue by darkfeline** [abo-abo/swiper#1209]
``` emacs-lisp
(ivy-completing-read "test" '("foo" "bar") nil nil nil nil '("spam" "eggs"))
(completing-read-default "test" '("foo" "bar") nil nil nil nil '("spam" "eggs"))
```

In `completing-read-default`, DEF is "virtually" placed at the beginning of the history so that `M-n` traverses the list of defaults. ([Emacs Manual](https://www.gnu.org/software/emacs/manual/html_node/emacs/Minibuffer-History.html))

I see no reason from a UI standpoint that ivy can't support the same behavior.

**Comment by darkfeline** [comment]
https://github.com/abo-abo/swiper/issues/1208 should probably be fixed first

**Comment by abo-abo** [comment]
<kbd>M-n</kbd> inserts symbol at point into the minibuffer.

**Comment by darkfeline** [comment]
Oops, I didn't realize that was there.  `M-n` can still be used for that after the user browses all the defaults.

```
...
history item 2
history item 1
initial input/default value 1
default value 2
...
<insert text at point>
```

We can imagine a virtual history like this, with `M-n` and `M-p` traversing up and down.

This does change the behavior a little.  I don't know if there are any users who call a command with multiple default values, yet the user is accustomed to inserting text at point.  Presumably, the default values are there because they are desirable.  In this case `M-n` works as a "guess a good value", using the default values first and inserting text at point of those fail.

**Comment by darkfeline** [comment]
Actually, it seems like `ivy` does support defaults, you just have to press `M-p` first and then press `M-n` twice to get `ivy` into "history" mode and out of "insert text at point" mode.

I'll need a block of time to edebug through it.

**Comment by basil-conto** [comment]
Wasn't this fixed by #1049, in that DEF causes the corresponding candidate to be initially selected?

**Comment by yannvanhalewyn** [comment]
Current behavior will add only the first element when DEF is a list.

**Comment by basil-conto** [comment]
@yannvanhalewyn 

> Current behavior will add only the first element when DEF is a list.

This is in accordance with the `completing-read` API:

    If the input is null, `completing-read' returns DEF, or the first
    element of the list of default values, or an empty string if DEF is
    nil, regardless of the value of REQUIRE-MATCH.

**Comment by yannvanhalewyn** [comment]
👍 Sorry for my prying in.

**Comment by abo-abo** [comment]
Thanks all, closing this as fixed.
