### ISSUE TITLE
Swiper removes a cursor-type = nil setting

### ISSUE THREAD

**Issue by Alexander-Miller** [abo-abo/swiper#1211]
Steps to reproduce:

 * start emacs -q
 * load swiper
 * `(setq-local cursor-type nil)`
 * call swiper and go to any result
 * cursor is now visible again

There are packages where this behaviour is undesired, like ranger or my own treemacs.

I can reproduce this with both a self-compiled emacs 25 and a self-compiled emacs 26.

**Comment by abo-abo** [comment]
Thanks. Now `cursor-type` is not touched unless you use inline completion.
