### ISSUE TITLE
ivy-rotate-hydra matcher

### ISSUE THREAD

**Issue by wolfv6** [abo-abo/swiper#1213]
Select completion style from inside Ivy: C-o (hydra) m (matcher) should rotate three completion styles:
- ivy
- order
- fuzzy

Hydra matcher opens with the "order" option (ivy--regex-ignore-order) but it does not rotate.
Only "ivy" and "fuzzy" rotate.

Ivy Completion Styles with hydra code is at https://github.com/abo-abo/swiper/commit/ae438ff62fa3d9b98d899afc0e97c13be2148725

And described in http://oremacs.com/swiper/#completion-styles

I am using Emacs 25.2.1 with Evil Spacemacs and Ivy on Linux.

**Comment by neojski** [comment]
This is interesting: this works perfectly well for me when I run "make plain" but doesn't work in spacemacs, see: https://github.com/syl20bnr/spacemacs/issues/10008.

@wolfv6, are you using spacemacs?

**Comment by neojski** [comment]
By the way, I've just submitted PR to spacemacs (https://github.com/syl20bnr/spacemacs/pull/10009) so this should be fixed soon. As this is spacemacs specific problem, I think this issue can be closed. Ping @abo-abo.
Thank you!

**Comment by abo-abo** [comment]
Thanks, closing.
