### ISSUE TITLE
Quitting ivy-reverse-i-search leaves emacs in strange state

### ISSUE THREAD

**Issue by georgek** [abo-abo/swiper#1215]
If I do, say, a `C-s` (for swiper), then a `C-r` and then a `C-g` I am left inside a big minibuffer. I then have to quit that with another `C-g`. The main buffer can also be left in a strange state by swiper with the highlighting etc. I expect the `C-g` to return me to the swiper search, and another `C-g` to return everything back to normal.

One of the principles of emacs for me is that pressing a key in error doesn't break anything; you just have to do a `C-g` or an undo to get back to normal. This breaks that principle.

**Comment by abo-abo** [comment]
That's not what I experience: <kbd>C-s C-r C-g</kbd> results in me being in swiper's minibuffer, no weird highlights. One more <kbd>C-g</kbd> quits swiper.

Please try to reproduce the bug with `emacs -Q` and detailed steps.

**Comment by georgek** [comment]
Sorry for the delay. I just tried this with `emacs -Q`.

I have ivy 20170926.915 and counsel 20170911.1121 which were downloaded with package.el. I do the following:
*  `emacs -Q`,
* Add the directories containing ivy and counsel to `load-path`,
* `(require 'ivy)`,
* `(require 'swiper)`,
* <kbd>M-x</kbd> `swiper`, (optionally type anything), and then <kbd>C-r C-g</kbd>.

Point is left in a big minibuffer. If I had typed anything it would also leave the highlights in place and stuff.

**Comment by CeleritasCelery** [comment]
I can reproduce this issue as well.

**Comment by d125q** [comment]
Can also reproduce.  Adding
```lisp
(lambda () (ivy--reset-state (setq ivy-last old-last)))
```
to `ivy-read`'s `:unwind` seems to fix the issue.  Alternatively, I don't see why we just don't use `ivy-recursive-restore`' functionality?

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by CeleritasCelery** [comment]
Works for me
