### ISSUE TITLE
ivy does not work on directories/paths containing +

### ISSUE THREAD

**Issue by darkfeline** [abo-abo/swiper#1217]
Haven't debugged yet.

Repro:

1. Open a file in a directory path which contains `+`.
2. `C-x d` (`dired`)
3. Preselected value is `/home/bob/.../\+emacs/...`
4. Pressing `RET` to select the default value (`default-directory`) fails because the `\+` escaped with backslash isn't valid for `dired`.

**Comment by darkfeline** [comment]
https://github.com/abo-abo/swiper/blame/master/ivy.el#L1912

This is the culprit.  Why do we even do this?

**Comment by darkfeline** [comment]
https://github.com/abo-abo/swiper/commit/5269b799e1604c39495beaf7949a4547ef3afcf0

Is this even applicable any more?

**Comment by darkfeline** [comment]
Oh, I think this is directly related to https://github.com/abo-abo/swiper/issues/1156, i.e. that `:preselect` used to work as a regex.  Two bugs for the price of one.

**Comment by darkfeline** [comment]
Like #1156, this bug is fixed on master.  Since it seems like swiper/ivy does not release often enough to be useful, I'm now tracking melpa instead of melpa-stable.

**Comment by abo-abo** [comment]
> Since it seems like swiper/ivy does not release often enough to be useful

That's the trade-off between stable and trunk. Trunk is fresh, but stable has a higher chance of not being crazy broken, since I do some testing before a release and also let the code get used for some time by people tracking trunk.

**Comment by darkfeline** [comment]
I suppose I am spoiled by "release often" workflows.  If you release often, there's less change of dramatic breakage, and any large regressions can be easily caught and fixed (since there would fewer commits to look through).  It also encourages building proper continuous integration and testing and generally improves a project's health (at least from personal experience).

If you test and release on master, that means you'd have to freeze master for a period of time before a release. I'm not fond of that myself.

**Comment by abo-abo** [comment]
I'll release in the next few weeks. Closing the issue. If it's still relevant to `master`, please open a new issue.
