### ISSUE TITLE
counsel-find-file stops offering completions after /sudo::

### ISSUE THREAD

**Issue by diamond-lizard** [abo-abo/swiper#1219]
When I start `counsel-find-file` and type `//` to get the prompt to look like `(1/58) Find file: /` if I now type `sudo::` so the prompt now looks like `(1/0) Find file: /sudo::` from here on out `counsel-find-file` will no longer offer me any completions.

So I could now type, say `/` and the prompt changes to:  `(1/0) Find file: /sudo::/` and while I expect to see completion candidates from all the files and directories in the root filesystem, I don't see anything except the prompt.

Similarly, if I had typed `/etc` and the prompt changed to: `(1/0) Find file: /sudo::/etc` I'd expect to see completion candidates of all the files and directories in `/etc` but I don't see anything except the prompt.

**Comment by abo-abo** [comment]
I use it like this: <kbd>C-x C-f</kbd> `/sudo:` <kbd>RET</kbd>. This way, you get sudo in the current folder.

**Comment by diamond-lizard** [comment]
If I do that, then I get an error:

`tramp-file-name-handler: Host name must not match method "sudo"`

and I'm returned to the same `counsel-find-file` prompt I had before I typed `/sudo:` <kbd>RET</kbd> and if I use it to open any file, that file will be opened with my own privileges, not root's.  So it appears this method is not working for me.

If instead of <kbd>C-x C-f</kbd> `/sudo:` <kbd>RET</kbd> I type <kbd>C-x C-f</kbd> `/sudo::` <kbd>RET</kbd> then I get a dired buffer which I can use as usual to find the file I need and open it using elevated privileges.  This works, but it defeats the whole point of using `counsel-find-file`, whose completion I prefer to use instead of using dired.

**Comment by abo-abo** [comment]
Can you try to reproduce my typical use case.
From e.g. the home folder:

1. <kbd>C-x C-f</kbd> `//etc/` : now I'm in `/etc` with completion still open.
2. `/sudo::` <kbd>C-j</kbd> : now I'm in `/sudo::/etc/` with completion still open.

If this works for you, great - we have a common point of reference. If not, we have a bug.

Later, we can clarify if the above workflow works for you or not, and handle potential improvements.

**Comment by diamond-lizard** [comment]
With the newest version of swiper, this test case does work as you say, when I'm running `emacs -Q` with just counsel, ivy, and swiper installed.  Thank you.

**Comment by basil-conto** [comment]
What's the status on this issue?

**Comment by abo-abo** [comment]
Closing as fixed. If the problem reoccurs with the current code, please open a new issue.
