### ISSUE TITLE
Request for ivy-insert-org-entity

### ISSUE THREAD

**Issue by eflanigan00** [abo-abo/swiper#1220]
Not sure it makes sense in the repo or not but it seems like a useful function:

http://irreal.org/blog/?p=6623

**Comment by abo-abo** [comment]
It's up to @jkitchin if he wants to contribute it. I think it would fit into counsel.el.

**Comment by basil-conto** [comment]
+1 on the usefulness of such a function.

For anyone interested in an in-buffer variant, I can offer the following for inspiration:
```el
(define-advice pcomplete/org-mode/tex (:override () my-complete-entity)
  "Perform Org entity completion via `completion-in-region'.
Offer all entities found in `org-entities-user' and
`org-entities' except those multiples of en space."
  (when (equal "tex" (car-safe (org-thing-at-point)))
    (completion-in-region
     (save-excursion
       (skip-chars-backward "^\\\\")
       (point))
     (point)
     (sort (delq nil (mapcar #'car-safe (append org-entities-user org-entities)))
           #'string-lessp)
     (lambda (entity)
       (/= ?_ (string-to-char entity))))))
```

In this case I am overriding the corresponding `pcomplete` function provided by `org` in order to avail of `ivy` completion, but the core functionality can be used as a standalone function as well.

**Comment by jkitchin** [comment]
I have no objection to adding ivy-insert-org-entity to counsel. The code is currently at https://github.com/jkitchin/scimax/blob/280889aa2dcc0ce8926bcc402b6abb0312eb5c53/scimax-org.el#L815

Do you have any preferred place it might go?

**Comment by abo-abo** [comment]
@jkitchin Thanks. You can put it somewhere in `counsel.el`, there are already outlines there for `counsel-org-tag`, `counsel-org-file` and `counsel-org-capture`.

**Comment by eflanigan00** [comment]
Thank you @jkitchin, this is an awesome feature!!

**Comment by abo-abo** [comment]
@jkitchin Thanks again, closing the issue.
