### ISSUE TITLE
Async operations like 'counsel-ag/rg' block emacs using 26 (Release branch)

### ISSUE THREAD

**Issue by gilbertw1** [abo-abo/swiper#1222]
Hi,

First off I apologize if it's too early to make Emacs 26 related issues since it's not released yet, if so please feel free to leave a note and close this issue.

I've noticed that when running commands such as `counsel-rg` that Emacs is blocked while the command is actively running, and keystrokes only registered when the async filter is evaluated (or at least this is my impression). 

For example, if I run `counsel-rg` on a large directory and then type 't' and then press 'e' immediately afterwards, nothing happens for a few moments and the when the results are updated (with additional results from the 'rg' command) the 'e' keypress is registered. Again if I were to press a followup keybinding, it would not register immediately, only when the results in the ivy minibuffer are updated.

However, if I change `counsel-async-filter-update-time` to something extremely small:

    (setq counsel-async-filter-update-time 1000)

My keybindings are almost instantly evaluated while the results are being populated. Obviously this has a large affect on cpu usage and isn't ideal behavior as the results are being updated almost constantly. I'll try and do a little more research to figure out if what change was made in Emacs 26 that made this functionality start blocking.

**Comment by abo-abo** [comment]
If possible, please try to `git bisect` between 25 and 26 for this behavior. I use 25 on one machine, 26 (about a month stale) on the other; haven't noticed anything.

**Comment by gilbertw1** [comment]
Ah, it turns out that the configuration I am using was adding a def-advice around `counsel-ag` that I was unaware of and it is what is misbehaving on Emacs 26. Sorry to have wasted your time!

**Comment by abo-abo** [comment]
No problem:)

**Comment by abo-abo** [comment]
Thanks for the effort.

**Comment by gilbertw1** [comment]
Good news, I wrapped up the bisect and found the exact commit! 

The performance and responsiveness of the `counsel-rg/ag` commands tanked heavily after this commit: https://github.com/emacs-mirror/emacs/commit/c29071587c64efb30792bd72248d3c791abd9337

**Comment by gilbertw1** [comment]
After looking at the commit and doing some additional tests, it looks like this probably isn't a bug specific to ivy, but instead the new double buffering is killing rendering performance in Emacs. This being X11 specific will only occur on Linux.

If I make the Emacs window small, then the results are populated without issue and the prompt remains responsive. However, when emacs is full screen and results are populating in `counsel-rg` then Emacs experiences heavy lag spikes to the UI. It also locks anything else on the screen that I might be running such as glxgears. I guess that `counsel-rg` is the only thing that has surfaced this problem for me.

For reference, here's what it looks like
- before double buffering: http://drop.bryan.sh/YtUzfcSRp7.mp4
- after double buffering: http://drop.bryan.sh/UyRpSc4NyQ.mp4

Looks like this issue is probably better suited for the Emacs mailing list. I'll see about raising the problem there. Thanks for the patience!

**Comment by abo-abo** [comment]
That's a very serious issue. Thanks for following through with this.

**Comment by gilbertw1** [comment]
No problem, glad I was able to get to the bottom of it. The Emacs maintainers are aware of the problem, hopefully they'll be able to come to a good compromise with respects to double-buffering on linux.

Here's a link to the bug I created: https://debbugs.gnu.org/cgi/bugreport.cgi?bug=28695

If anyone else finds this issue and has the same problem, double-buffering can be disabled using:

    (add-to-list 'default-frame-alist '(inhibit-double-buffering . t))
