### ISSUE TITLE
counsel-git-stash assume shell-file-name is bash

### ISSUE THREAD

**Issue by co-dh** [abo-abo/swiper#1224]
It will fail when default shell is fish. Maybe hardcode sh here?

**Comment by abo-abo** [comment]
@mookid What do you think?

**Comment by mookid** [comment]
``` patch
   "Search through all available git stashes."
   (interactive)
   (setq counsel--git-dir (counsel-locate-git-root))
-  (let ((cands (split-string (shell-command-to-string
-                              "IFS=$'\n'
+  (let* ((shell-file-name "sh")
+         (cands (split-string (shell-command-to-string
+                               "IFS=$'\n'
 for i in `git stash list --format=\"%gd\"`; do
     git stash show -p $i | grep -H --label=\"$i\" \"$1\"
 done") "\n" t)))
```

solves it. However, should we do the same for each `shell-command-...` call? This may be the responsibility of the fish users to advice these commands as needed.

For them, it is just a matter of adding 
``` lisp
(defun wrap (orig-fun &rest args)
  (let ((shell-file-name "sh")) (apply orig-fun args)))
(advice-add 'shell-command-to-string :around 'wrap)
```

to their configuration.

**Comment by mookid** [comment]
The problem of the second solution above is that it breaks any non compatible `fish` script called with `shell-command-to-string`.

A third solution would be to replace any instance of `shell-command-to-string` in counsel.el with a custom function to be advised by the user, and to provide such advices separately.

**Comment by mookid** [comment]
Note: 
+ the obtained command can't be pasted to `shell-command`'s prompt: `{` `}` need to be escaped in fish, it seems... 
+ the script can be improved: shellcheck reports the following:
```
In toto.sh line 3:
IFS=$'\n'
    ^-- SC2039: In POSIX sh, $'..' is undefined.


In toto.sh line 4:
for i in `git stash list --format=\"%gd\"`; do
         ^-- SC2006: Use $(..) instead of legacy `..`.


In toto.sh line 5:
    git stash show -p $i | grep -H --label="$i" "$1"
                      ^-- SC2086: Double quote to prevent globbing and word splitting.

```

**Comment by abo-abo** [comment]
I think fish users should simply customize `shell-file-name` globally. That's the intention of that variable. Packages like counsel or functions like `shell-command-to-string` can simply depend on that var.
