### ISSUE TITLE
ivy-initial-inputs-alist not working for man command?

### ISSUE THREAD

**Issue by dieggsy** [abo-abo/swiper#1226]
Every other entry in the default `ivy-initial-input-alist` seems to take effect, except for `(man . "^")`, which doesn't work. I'm not sure what this is about, but it's inconvenient since I had actually set `ivy-initial-input-alist` to just `'((man . "^"))`.

**Comment by abo-abo** [comment]
Thanks, fixed.

It can be unreliable customizing things like `ivy-initial-inputs-alist` for commands that don't call `ivy-read` directly, because ivy can't identify the caller unambiguously.
This time, the command was identified by collection function (which has priority), not by `this-command`.
