### ISSUE TITLE
ivy find-file-at-point [Feature Request]

### ISSUE THREAD

**Issue by kaushalmodi** [abo-abo/swiper#123]
It would be nice for find-file-at-point to work with ivy.

If the point is on a file path and if I do `counsel-find-file`, it should pick up the path at point (but not open that file/dir directly) and then allow the user to edit the path as needed.

**Comment by abo-abo** [comment]
> It would be nice for find-file-at-point to work with ivy.

There was an issue with `find-file-at-point` and `ivy-mode`. It's fixed in the trunk.

> If the point is on a file path and if I do counsel-find-file, it should pick up the path at point (but not open that file/dir directly) and then allow the user to edit the path as needed.

This can be added via a defcustom.
