### ISSUE TITLE
Empty string at end of collection causes selection to start at end of list

### ISSUE THREAD

**Issue by jschaf** [abo-abo/swiper#1230]
Using a collection with an empty string causes ivy-read to position the initial cursor at the end of the list.

Minimal reproducible case:

```elisp
(defun ivy-bug-at-end-of-list ()
  (interactive)
  (ivy-read "Bug: "
            (list "1" "2" "3" "4" "5" "")
            :keymap ivy-minibuffer-map
            :action (lambda (x) (message "%s" x))))
```

Running that displays 1 through 5 in the minibuffer but not the empty string.  The cursor starts outside the visible portion on the empty string.

**Comment by abo-abo** [comment]
Thanks.
