### ISSUE TITLE
autocomplete duplicates prefix in shell mode & minibuffer

### ISSUE THREAD

**Issue by bergey** [abo-abo/swiper#1231]
After pressing TAB (`completion-at-point`) I expect `home`, but I see `/homhome/`.  Steps to reproduce:

```
emacs -q
(package-initialize)
(require 'ivy)
(ivy-mode)
M-x shell
cd /hom TAB # in emacs buffer *shell*
```

This occurs on MacOS with Emacs 25.2.1, but not on Debian with Emacs 24.5.1.  It does not occur without `ivy`.

A similar duplication occurs if I tab-complete in the minibuffer after `eval-expression`, iff there is only one completion candidate.

May be related to #1120.

**Comment by abo-abo** [comment]
Can't reproduce on Linux with emacs25 from git. I'll try tomorrow with some released versions that I have.
Any confirmed reproductions on Linux appreciated.

**Comment by manuel-uberti** [comment]
For what is worth, I can't reproduce this on Ubuntu 16.04.3, Emacs 27.0.50.

**Comment by articuluxe** [comment]
For what it's worth, I was seeing this a month ago or more, but subsequent updates fixed it for me. I wonder if the OP is using a stable release that hasn't caught up to master.

**Comment by bergey** [comment]
I have been using `ivy-20170901.329`.  Upgrading to `20171010.2323` seems to have fixed my problem.  Thanks for the help narrowing things down.
