### ISSUE TITLE
Magic slash not working for first directory with no input

### ISSUE THREAD

**Issue by dieggsy** [abo-abo/swiper#1234]
Usually, pressing `/` when the current candidate is a directory enters that directory - even with no input text. This is not the case when the current candidate is also the first - in that case, the slash seems to work just like entering text would, and ivy shows the trailing slash on every subdir as matched text. 

e.g. (`>` indicates current candidate, `|` indicates point) pressing slash in this case enters dir2
```
Find file: my/path/|
 dir1/
>dir2/
 file
```
pressing slash in the following case just narrows to directories and highlights the trailing slash as matching text
```
Find file: my/path/|
>dir1/
 dir2/
 file
```

**Comment by dieggsy** [comment]
@abo-abo any thoughts on this?

**Comment by abo-abo** [comment]
Did you customize `ivy-extra-directories`?

**Comment by dieggsy** [comment]
Yep, I set it to `nil` though ideally that wouldn't affect this behavior.

**Comment by abo-abo** [comment]
I've just looked at this, here's what I think: if I add the option to `cd` to a first directory with a single `/`, it's no longer possible to <kbd>C-x C-f</kbd> `/ssh:` or `/sudo:`. You'd have to keep pressing `/` until you get to a directory which no longer has subdirectories.

So I suggest having at least:

```elisp
(setq ivy-extra-directories '("./"))
```

**Comment by dieggsy** [comment]
That's actually a good point. I suppose I'll just have to live with it. Thanks!
