### ISSUE TITLE
counsel-rg no longer works

### ISSUE THREAD

**Issue by jeberger** [abo-abo/swiper#1236]
Since c9f86b5, `counsel-rg` does nothing.

**Comment by abo-abo** [comment]
Can't reproduce. The commit you cite looks harmless.

**Comment by jeberger** [comment]
I just double-checked with `emacs -Q`. It works with the default settings, but it stops working at that commit when I enable `ivy-auto-select-single-candidate`.

**Comment by abo-abo** [comment]
Pinging @fabacino, author of `ivy-auto-select-single-candidate`.

**Comment by abo-abo** [comment]
@jeberger Thanks, the change is now reverted for dynamic collections.

**Comment by jeberger** [comment]
Thanks for your reactivity

**Comment by fabacino** [comment]
I was on vacation a couple of weeks and did not see the ping until now. Sorry about that.
