### ISSUE TITLE
Introduce ivy-recentf

### ISSUE THREAD

**Issue by nsemrau** [abo-abo/swiper#124]
I currently use `helm-recentf` to quickly filter and select recent buffers. I would like to convert that to ivy. I'm aware of `ivy-use-virtual-buffers` but it mixes the list of live buffers with virtual/recent buffers in `ivy-switch-buffer`. I see the value and quickness in this approach but my aim is to continue to keep the lists separate and have a dedicated way to select a recent buffer via ivy.

Would you be willing to introduce a way in ivy to access solely the recentf-list, analogous to `helm-recentf` (plus comparable functions like `ido-open-recentf` or `recentf-open-file` :))?

**Comment by abo-abo** [comment]
> plus comparable functions like ido-open-recentf or recentf-open-file

I don't know what this means, I just added a basic function to open a file on `recentf-list`.

**Comment by nsemrau** [comment]
Sorry for the confusion, the additional functions I named were just there to further illustrate what kind of functionality I asked for. The function you added is exactly what I  meant. Thank you for the quick and positive response! :+1:
