### ISSUE TITLE
counsel-ag + ivy-occur bash error

### ISSUE THREAD

**Issue by SkySkimmer** [abo-abo/swiper#1240]
Reproduction:
- `counsel-ag`
- search for `a _b` (regardless of presence of matches) (in general string - space - string starting with underscore)
- `ivy-occur`

Result: occur buffer containing
```
-*- mode:grep; default-directory: "[redacted]" -*-


2 candidates:
.//bin/bash: -c: line 0: syntax error near unexpected token `('
.//bin/bash: -c: line 0: `ag --nocolor --nogroup (a).*?(_b)'
```
This doesn't seem to happen with counsel-grep.

**Comment by abo-abo** [comment]
Thanks.

**Comment by SkySkimmer** [comment]
There are still quoting issues, with `"` for ag and `'` for grep. Maybe use `shell-quote-argument` like `counsel-grep` does to pass the filename?

**Comment by abo-abo** [comment]
Thanks again. Please test, again.

**Comment by SkySkimmer** [comment]
Seems to work. Thanks!
