### ISSUE TITLE
Does ivy support feature like helm-persistent-action

### ISSUE THREAD

**Issue by amosbird** [abo-abo/swiper#1243]
I don't find a persistent action in `C-o` and `M-o` hydra menus. Does ivy provide such feature so that one can use to preview selections?

**Comment by abo-abo** [comment]
It's all there, please see the documentation: http://oremacs.com/swiper/#key-bindings-for-multiple-selections-and-actions-keep-minibuffer-open

**Comment by amosbird** [comment]
Thanks!
