### ISSUE TITLE
In-buffer filename completion broken

### ISSUE THREAD

**Issue by basil-conto** [abo-abo/swiper#1244]
Commit 55e34e887946690a5c8f05403f5fc352c31c3b8d introduced the following two behaviours:

##### Completion gets stuck

1) `make plain`
2) `M-x ielm RET`
3) `(find-file "t` `TAB` `TAB`
   * Expected result: In-buffer completion of files under `targets` directory
   * Actual result: Unselectable minibuffer with prompt `(targets/):`

##### Completion overwrites filename prefixes

This recipe assumes a typical Unix-like installation of Emacs, where `package-user-dir` is at `~/.emacs.d/elpa`.

1) `make plain`
2) `M-x ielm RET`
3) `(cd "~") RET`
4) `(find-file "~/.emacs.d` `TAB`
   * Expected result: `(find-file "~/.emacs.d/`
   * Actual result: `(find-file ".emacs.d/`
5) `elpa` `TAB`
   * Expected result: `(find-file "~/.emacs.d/elpa/`
   * Actual result: `(find-file "elpa/`

**Comment by abo-abo** [comment]
Thanks for the report. I can reproduce the issue, which is basically that `:initial-input` is e.g. "~/.e", while the candidates are `'(".emacs.d" ".emacs" ...)`. I'll fix this today.

**Comment by abo-abo** [comment]
Please test.

**Comment by basil-conto** [comment]
Thanks very much, that seems to have fixed it. :)
