### ISSUE TITLE
completion-at-point broken on IELM for small window heights

### ISSUE THREAD

**Issue by tmdmelo** [abo-abo/swiper#1247]
Similar to **completion gets stuck** on issue #1244.

**How to reproduce**

1. `M-x ielm RET`
2. Resize window to a minimum height (**13**, in my case) where completions are still shown in an overlay instead of the minibuffer 
3. `RET` until prompt is at the end of the window
4. Type something with a long enough completion list, e.g: `emac` `M-TAB`

**Observed behavior**

Prompt gets hidden and completion overlay is not shown:

![image](https://user-images.githubusercontent.com/30505656/31831594-5509af3e-b5c4-11e7-8985-93962de6f270.png)

**Expected behavior** 

Prompt stays visible and completion overlay is shown:

![image](https://user-images.githubusercontent.com/30505656/31831534-1f1457da-b5c4-11e7-9839-44a636606296.png)

**Tested with**
- Commit 897a39c83852ce7fbedff9a0a066f53d700f82a8
- Emacs `26.0.90` and `25.1`
- Default Emacs settings, no other packages installed
- Debian Stretch

Issue doesn't happen when running emacs on a terminal (`emacs -nw`), nor on `M-x shell`.

**Comment by abo-abo** [comment]
Can't reproduce, but if I understand correctly, it's an edge case: only height 13 is broken, heights 12 and 14 work.
So I add 1 more row to the window-height requirement. Please test.

**Comment by tmdmelo** [comment]
I found out this issue can be fixed by [setting the variable `scroll-conservatively` to a large value](https://www.gnu.org/software/emacs/manual/html_node/efaq/Scrolling-only-one-line.html). It's set to 0 by default.

You can revert the last commit. However, let me clarify that this issue actually happens over a range of window heights, and it also depends on `ivy-height`. For example, when `ivy-height` is set to 10, it happens from window height 13 to 17. Larger `ivy-height` values increase this range.

I'm closing this issue. Thanks for taking a look.
