### ISSUE TITLE
`ivy-currentomatch` face not applying to "directories"

### ISSUE THREAD

**Issue by paulbdavis** [abo-abo/swiper#1248]
I have customized the `ivy-current-match` face, but when I am doing a selection that involved any "directories" (meaning a directory in `counsel-find-file` or a dired buffer in `ivy-switch-buffer`) a different face seems to be used, and I can't figure out what it is to be able to customize it.

Shot with "directory" selected
![emacs1](https://user-images.githubusercontent.com/2730634/31902121-fc0429ae-b7e0-11e7-994c-6160da7fe674.jpg)

Shot with file selected
![emacs2](https://user-images.githubusercontent.com/2730634/31902118-f7cda4f0-b7e0-11e7-9695-7aa3281e70fa.jpg)

**Comment by abo-abo** [comment]
See the `ivy-subdir` face.

**Comment by rum2** [comment]
![ivy-subdir](https://user-images.githubusercontent.com/6720098/31904042-5b086bd8-b82a-11e7-9cee-4e2f01d6ef31.png)

**Comment by paulbdavis** [comment]
@abo-abo How is that used? I already customized that as well (see the blue text for the dirs in the screenshot) and it works when the dirs are not selected

**Comment by paulbdavis** [comment]
![emacs3](https://user-images.githubusercontent.com/2730634/31904090-72434982-b7e7-11e7-9814-b0a1d725c0c3.jpg)

**Comment by abo-abo** [comment]
![ivy-subdir](https://user-images.githubusercontent.com/2937359/31904098-85fd9066-b82a-11e7-901a-e19a71196699.png)
I just customized it, looks fine to me.

**Comment by paulbdavis** [comment]
I am talking about the selected dir though. In your screenshot, which face is making the selected dir show up with the red BG and white FG?

**Comment by abo-abo** [comment]
Your customization has very little contrast. `ivy-current-match` face is applied by blending. Try tweaking `colir-compose-method`.

**Comment by abo-abo** [comment]
> In your screenshot, which face is making the selected dir show up with the red BG and white FG?

This is the result of alpha-blending the orange color of directory with `ivy-current-match`.
The blend mode is customized via `colir-compose-method`.

**Comment by paulbdavis** [comment]
I have my `ivy-current-match` customized as well, including a box which is not showing up on a selected dir

![emacs4](https://user-images.githubusercontent.com/2730634/31904298-159d8e08-b7e8-11e7-8c4b-5999dafa361f.jpg)

I will check out the blending thing and see if I can get some colors that work for my theme

**Comment by paulbdavis** [comment]
Turns out setting `(set-face-attribute 'ivy-subdir nil :background nil)` fixed the issue of the box not applying

**Comment by abo-abo** [comment]
See `ivy--add-face` function. That's the main entry point for composing faces together.

If something doesn't work for you, it can be solved by extending that function.

One idea, for example: you could compose two faces not only with alpha blending (which is automatic but produces sub par results sometimes), but with additional table overrides (e.g. `face-1` + `face-2` = `face-3`).

**Comment by basil-conto** [comment]
Can this issue be closed, or is there some outstanding business?

**Comment by abo-abo** [comment]
Thanks for the reminder, closing.
