### ISSUE TITLE
[Feature request] Insert word at point with C-w

### ISSUE THREAD

**Issue by sewkokot** [abo-abo/swiper#125]
I'm used to pressing C-w in isearch-forward to insert word-at-point in the minibuffer. Would it be possible to do it with swiper?

**Comment by abo-abo** [comment]
You have to bind it yourself as:

```elisp
(define-key ivy-minibuffer-map (kbd "C-w") 'ivy-yank-word)
```

I prefer to have <kbd>C-w</kbd> call `kill-region`, as it does in other buffers.  Also try <kbd>C-s M-n</kbd> - the preferred method to search for thing-at-point.

**Comment by sewkokot** [comment]
Thank you for prompt response and implementation! Exactly what I wanted :)

**Comment by sewkokot** [comment]
My first tests were when I had point at the bol but then when the cursor is further the function ivy-yank-word yanks string from the beg of line to the point. I modified your function a bit to suit my need.
```
  (defun my-ivy-yank-word ()
  (interactive)
  (let (amend)
	(with-selected-window (ivy-state-window ivy-last)
	  (goto-char swiper--opoint)
	  (setq amend (thing-at-point 'symbol)))
	(when amend (insert amend))))
  (bind-key "C-w" 'my-ivy-yank-word ivy-minibuffer-map))
```

**Comment by abo-abo** [comment]
> My first tests were when I had point at the bol but then when the cursor is further the function ivy-yank-word yanks string from the beg of line to the point

Thanks for pointing that out, `swiper` should work better now. Your approach isn't optimal since it isn't possible to type in some input, <kbd>C-n</kbd> and then extend with <kbd>C-w</kbd>. It should be possible now with `ivy-yank-word`.
