### ISSUE TITLE
elisp-completion-at-point: args out of range

### ISSUE THREAD

**Issue by basil-conto** [abo-abo/swiper#1251]
Commit 87c1e4e0896550ab2c14d6337d0958e5377aa893 introduced the following error during in-buffer elisp completion:

1. `$ make plain`
2. `(let (x (temp-buffer-sh` <kbd>C-M-i</kbd>

gives the error

```
if: Args out of range: "temp-buffer-sh", -21, nil
```

and the attached [backtrace](https://github.com/abo-abo/swiper/files/1422811/backtrace.txt).

What I am trying to complete is the name of the variable `temp-buffer-show-function`. I cannot reproduce the issue without including a symbol (in this case `x`) in the `let` varlist.

Interestingly, bare Emacs sans `ivy` completes `temp-buffer-sh` to `temp-buffer-window-show`, i.e. it mistakes `(temp-buffer-sh` as starting a function call, rather than a variable's `let`-binding.

**Comment by abo-abo** [comment]
Thanks, please check.

**Comment by basil-conto** [comment]
Thanks for the quick fix, works now. :)
