### ISSUE TITLE
elisp-completion-at-point: disappearing sole match

### ISSUE THREAD

**Issue by basil-conto** [abo-abo/swiper#1252]
Commit 55e34e887946690a5c8f05403f5fc352c31c3b8d introduced the following behaviour when performing in-buffer elisp completion:

1. `$ make plain`
2. `(nconc` <kbd>C-M-i</kbd>
   * Expected result: unchanged buffer contents with message `Sole match` in echo area
   * Actual result: `nconc` is deleted with message `Sole match` in echo area

**Comment by abo-abo** [comment]
Thanks.

**Comment by basil-conto** [comment]
No, thank you. :)
