### ISSUE TITLE
Incorrect match face

### ISSUE THREAD

**Issue by Pitometsu** [abo-abo/swiper#1258]
<img width="832" alt="screen shot 2017-10-29 at 9 47 19 pm" src="https://user-images.githubusercontent.com/2434691/32147612-da043a26-bcf2-11e7-80be-46ff043f310c.png">

See:

> `:` `i` nherit

part. Both with `swiper-match-face-4`, but `i` with `swiper-match-face-2` should be.

**Comment by abo-abo** [comment]
This is expected behavior: when the match groups border each other in a result, they are merged together to have the same color.

This is mainly for the sake of `ivy--regex-fuzzy` re-builder: without merging groups the highlighting quickly gets very confusing.
