### ISSUE TITLE
immediately show results, or only after TAB

### ISSUE THREAD

**Issue by Pitometsu** [abo-abo/swiper#1259]
When I run `customize-face`, there are no swiper options, until I press `TAB`.
On other hand, when I run `swiper`, I see a lot of results with no input or `TAB` keystroke.

How can I switch this behavior: show results for `customize-face` immediately, and for `swiper` after some input and `TAB`?

**Comment by basil-conto** [comment]
One option is to use the command `counsel-faces`, followed by the `c` (customize face) [action](http://oremacs.com/swiper/#key-bindings-for-single-selection-action-then-exit-minibuffer).

**Comment by Pitometsu** [comment]
Good point. Added to setup:
```elisp
(global-set-key [remap describe-face]            'counsel-descbinds-face)
(global-set-key [remap list-faces-display]       'counsel-faces)
```

However, it more like describe, but here immediately auto-complete for customize needed.

**Comment by abo-abo** [comment]
@Pitometsu I consider this solved. I added your suggested rebind to `counsel-mode`.
@basil-conto Thanks for helping out.

**Comment by Pitometsu** [comment]
@abo-abo Original issue not solved yet. Even with `counsel-mode`, when I call `customize-face`, I have no list of options untill press `TAB`. But `customize-group`, for example, works as expected.

**Comment by abo-abo** [comment]
> Even with counsel-mode, when I call customize-face

`customize-face` isn't designed for `ivy`. You have to press <kbd>TAB</kbd>, because that's the design of `customize-face`.

In more detail, `customize-face` has:

    (read-face-name "Customize face" (or (face-at-point t t) "all faces") t)

While for immediate completion it should have:

    (read-face-name "Customize face" (or (face-at-point t t) "all faces") nil)

I can't change the code of `customize-face`. But `counsel-describe-face` is a good alternative.
