### ISSUE TITLE
counsel-describe-function and `...' quoted stuff

### ISSUE THREAD

**Issue by tsdh** [abo-abo/swiper#126]
I use `counsel-describe-function` and `counsel-describe-variable` as drop-in replacements for the standard commands.  However, there's one thing where the standard ones work better.

When point is somewhere in ``some-command-name'` and you do `C-h f`, then `some-command-name` is used as default value.  With the counsel variants, the quoting with ` and ' prevents that (actually, it's the trailing single quote which is the problem).

**Comment by abo-abo** [comment]
> When point is somewhere in `some-command-name' and you do C-h f, then some-command-name is used as default value.

I don't have this problem - it works as expected for me. Can you reproduce with emacs -Q?  Note that the function at point must be interned - that threw me off when I tested just now with emacs -Q. After interning the function, it worked fine.

**Comment by tsdh** [comment]
I just found out it is mode-specific (most probably syntax-table specific).

With emacs -Q in an elisp-mode buffer, it works as expected.
With emacs -Q in a message-mode-buffer, `(thing-at-point 'symbol)` somewhere inside ``insert'` results in `insert'` (note that the trailing ' is considered part of the symbol).  It's the same in text-mode.  So at least text- and message-mode give ' a word syntax.  That's probably for making `it's` a word which makes sense.

**Comment by abo-abo** [comment]
Thanks.
