### ISSUE TITLE
`counsel-shell-command-history` doesn't include candidates from `dired-shell-command-history`

### ISSUE THREAD

**Issue by danielmatz** [abo-abo/swiper#1261]
The history entries for `dired-do-shell-command` are stored in `dired-shell-command-history`.  Unfortunately, `counsel-shell-command-history` doesn't include those history entries as candidates.

I'm no Emacs Lisp expert, so I apologize if I am going down the wrong road here.  But it seems like the same mini buffer keymap is used for `shell-command` and `dired-do-shell-command`.  So if we added a `counsel-dired-shell-command-history` function, we couldn't have one key binding that did the right thing in the right context.  So then is it possible to have `counsel-shell-command-history` know which history variable to use, based on which shell command function was called?

Alternatively, perhaps `counsel-shell-command-history` could just combine the contents of the two history variables.

**Comment by danielmatz** [comment]
I didn't mean to imply there was one, only that perhaps that solution would be easier to implement.

The main issue is that when I am trying to enter a shell command for `dired-do-shell-command`, counsel doesn't allow me to look through the entries in `dired-shell-command-history`.

**Comment by abo-abo** [comment]
By usage scenario I mean just a few example key sequences that set up both histories and show that it's useful to have them be shared.
In my use, I rarely use anything except <kbd>M-x</kbd> `shell`, that's why I'm asking for a scenario.

**Comment by danielmatz** [comment]
Let me attempt a usage scenario for you:

1) Open up a `dired` buffer.
2) Run <kbd>M-x</kbd> `shell-command` (<kbd>M-!</kbd>), giving `echo banana` as the command.
3) Run <kbd>M-x</kbd> `dired-do-shell-command` (<kbd>!</kbd>), giving `echo apple` as the command.
4) Run <kbd>M-x</kbd> `dired-do-shell-command` again, and when prompted for a command, try to use <kbd>M-x</kbd> `counsel-shell-command-history`, which should only show you `echo banana` as an option.

What I really want is to be able to access the history entries in `dired-shell-command-history`.  I feel like I've confused things by mentioning combining the two history variables.  I would actually prefer for `counsel-shell-command-history` to know which history variable to use.  I only mentioned combining them, because if `counsel-shell-command-history` presented the superset of all shell command history, at least I would be able to get at the contents of `dired-shell-command-history` when running `dired-do-shell-command`.

I apologize for the confusion, I hope this explanation is clearer.

**Comment by abo-abo** [comment]
The way I reproduce it, the two histories are already merged:

1. `make plain`
2. <kbd>C-x d</kbd>
3. <kbd>M-!</kbd> `echo banana`.
4. <kbd>!</kbd> `cat`.
5. <kbd>C-r</kbd> - two items on history: `echo banana` and `cat`.

GNU/Linux, Emacs 26.0.90.

**Comment by danielmatz** [comment]
I launched emacs with `-Q` and tried your steps, and it does indeed work.  So there must be something in my configuration that is causing this issue.

Sorry for the noise, I appreciate your help.

**Comment by abo-abo** [comment]
No problem, you're welcome.

**Comment by danielmatz** [comment]
For the record, I think my problems were related to having `(require 'dired-x)` in my configuration, which binds <kbd>M-!</kbd>, originally `shell-command`, to `dired-smart-shell-command`.

**Comment by abo-abo** [comment]
Thanks.
