### ISSUE TITLE
No `M-x man` completions with ivy on FreeBSD

### ISSUE THREAD

**Issue by Jehops** [abo-abo/swiper#1262]
For this recipe, without ivy, completion works as expected.  That is, when text is entered at the prompt followed by `TAB` completions are presented.

1. `emacs -Q`
2. `(require 'man)`
3. `(completing-read "Manual: " 'Man-completion-table nil nil nil)`

For this recipe, completion does not work.  That is, the prompt looks like `0 Manual: ^` and that is it.  There is no list to narrow for completion.

1. `git clone https://github.com/abo-abo/swiper/`
2. `cd swiper && make plain`
3. `(require 'man)`
3. `(completing-read "Manual: " 'Man-completion-table nil nil nil)`

`M-x emacs-version` reports `GNU Emacs 25.3.1 (amd64-portbld-freebsd11.1, GTK+ Version 3.22.15) of 2017-09-29`

**Comment by Jehops** [comment]
FreeBSD switched to mandoc with version 11, and now `man -k ^` now longer returns a full list of man pages, but `man -k ~^` is required.  I am determining if this should be changed in FreeBSD to emulate the `grep` behaviour describe [here](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/man.html).  In any case, the problem is not with `ivy`.  Sorry for the noise.

**Comment by abo-abo** [comment]
No problem, thanks for documenting a solution.
