### ISSUE TITLE
counsel-fzf feedback

### ISSUE THREAD

**Issue by agsdot** [abo-abo/swiper#1263]
@jojojames and @abo-abo,

Thanks for incorporating fzf into counsel. It's nice to have the same/consistent UI with other counsel functions in using fzf. I was really glad to see PR #1151 recently go through.

After using counsel-fzf for a day or two, I couldn't help notice that it behaved slightly different than counsel-recentf.

The latter progressively displays the letters that one is typing, where for counsel-fzf the letters being typed are not highlighted?

Below are two screenshots to highlight the difference.

![recentf](https://user-images.githubusercontent.com/1510449/32207920-5f8e46ae-bdbc-11e7-9a8a-831d57d425b2.png)

![counsel-fzf](https://user-images.githubusercontent.com/1510449/32207925-65d31aee-bdbc-11e7-8bd2-a4b9c92dfd04.png)

counsel-recentf highlights "ihb" of other possible selections, whereas for counsel-fzf it doesn't highlight the "sgpgmelp" I typed in.

How can this consistency be ironed out so that counsel-fzf behaves and looks like other counsel functions like counsel-recentf?

Thanks!

**Comment by agsdot** [comment]
I realized "sgpgmelp" was a very narrow a item to search, searching for "sgpgmd" is a broader search.

Attached is a second screenshot of that broader search -- and still the same UI experience, no highlighting of characters that matched.

![counsel-fzf-2](https://user-images.githubusercontent.com/1510449/32208069-4d640b3e-bdbd-11e7-9111-fb644f8a936b.png)


The visual cues of what letters were typed in as in counsel-recentf is very helpful, and it would be awesome if it too were shown in counsel-fzf.

**Comment by jojojames** [comment]
Hmnn, I don't think it's possible. counsel-recentf probably matches and highlights the matches using flx or something. fzf under the hood is just using fzf -f to get a list back.

**Comment by agsdot** [comment]
Is it using flx?

https://github.com/abo-abo/swiper/blob/master/counsel.el#L1783
;;** `counsel-recentf'
(defvar recentf-list)
(declare-function recentf-mode "recentf")

;;;###autoload
(defun counsel-recentf ()
  "Find a file on `recentf-list'."
  (interactive)
  (require 'recentf)
  (recentf-mode)
  (ivy-read "Recentf: " (mapcar #'substring-no-properties recentf-list)
            :action (lambda (f)
                      (with-ivy-window
                       (find-file f)))
            :caller 'counsel-recentf))
(ivy-set-actions
 'counsel-recentf
 '(("j" find-file-other-window "other window")
   ("x" counsel-find-file-extern "open externally")))

I'm still wondering how the progressive pattern matching is done for counsel-recentf and not being done for counsel-fzf. Thanks @jojojames .

**Comment by abo-abo** [comment]
@agsdot @jojojames Thanks, please test.

**Comment by jojojames** [comment]
@agsdot I'm pretty sure counsel-recentf is just using the pattern matching through its own matcher.

Fzf has its own pattern matching so you won't be able to get highlighting out of it.

**Comment by agsdot** [comment]
Much better. Thanks @abo-abo.

![counsel-fzf-highlight](https://user-images.githubusercontent.com/1510449/32248858-4716e03a-be44-11e7-876d-61d16f3b6982.png)

**Comment by jojojames** [comment]
@agsdot Glad it's working for you. I do wonder how accurate the highlighting will be since it's using separate algorithms to get the list of matches/highlight.

Probably better than nothing/works in the 98% case.

Thanks @abo-abo.

**Comment by agsdot** [comment]
@jojojames. So far so good. Haven't used/tested it too much though.

The most important thing is/was the accuracy of the fzf results. Secondary is the highlight -- it's just a nice convenience.

Thanks @abo-abo and @jojojames for working on this.

**Comment by varmanishant** [comment]
Can we see only the git files some way? I did ask this in https://github.com/abo-abo/swiper/issues/1525.  I think it is a matter of changing in the input command. Anyone knows if this is configurable or a way to change that?

**Comment by jojojames** [comment]
@varmanishant You can use setenv.

(setenv "FZF_DEFAULT_COMMAND"
        (string-trim (shell-command-to-string ". ~/.zshrc; echo -n $FZF_DEFAULT_COMMAND")))
