### ISSUE TITLE
counsel-grep, counsel-ag occur broken for pattern starting with dash

### ISSUE THREAD

**Issue by SkySkimmer** [abo-abo/swiper#1266]
`counsel-grep` with pattern `-foo` => `error code 2`
`counsel-ag` with pattern `-foo` => works, but adding `ivy-occur` => `1 candidates: ./ERR: What do you want to search for?`

Probably other commands like `counsel-rg` are broken in similar ways, I didn't test (for instance I don't have rg installed).

**Comment by abo-abo** [comment]
Thanks.

> Probably other commands like counsel-rg are broken in similar ways, I didn't test (for instance I don't have rg installed).

They work for me, only `counsel-grep` didn't work.

**Comment by SkySkimmer** [comment]
For the other commands it's the ivy-occur step that breaks.
ie `M-x counsel-ag` `-foo` `C-c C-o` -> broken

**Comment by abo-abo** [comment]
Thanks again :)
