### ISSUE TITLE
completion-in-region: Overlay issues at BOB

### ISSUE THREAD

**Issue by basil-conto** [abo-abo/swiper#1267]
I see the following behaviour at the beginning of the buffer on latest `master` (96663b77945ab21e4e1b0aab690fc2e926f01f9c):

1. `make plain`
2. <kbd>C-x</kbd><kbd>h</kbd> <kbd>DEL</kbd>
3. `ivy`<kbd>C-M-i</kbd>
   - Expected result: overlay with list of completions for "ivy"
   - Actual result: no overlay and buffer contents are erased
4. Inputting `f` or similar results in
   `Error in post-command-hook (ivy--exhibit): (args-out-of-range 5 6)`
5. <kbd>C-g</kbg>
6. <kbd>M-:</kbd>`(setq ivy-display-functions-alist ())`<kbd>RET</kbd>
   - <kbd>C-M-i</kbd> works at BOB with minibuffer display function.

**Comment by abo-abo** [comment]
Thanks. Currently, I don't know if it's possible to make the overlay work at `point-min`. Minibuffer display will be used in this case.
