### ISSUE TITLE
ivy and mu4e adress completion

### ISSUE THREAD

**Issue by ardpp** [abo-abo/swiper#127]
Question: Is there a preferred way to use ivy for mu4e address completion. Something like that
http://emacs.stackexchange.com/questions/4209/using-ido-or-helm-to-auto-complete-email-addresses-in-mu4e 
with `ido-completing-read` replaced by  `ivy-completing-read` does work. 
Then, for instance I can use 
`(define-key mu4e-compose-mode-map "\C-c]" 'select-and-insert-contact)` 
for ivy style autocompletion. I wonder if there is a more generic way than that.

**Comment by abo-abo** [comment]
I'm not currently using mu4e, but generally this should be all you need:

```elisp
(setq mu4e-completing-read-function 'ivy-completing-read)
```

If it doesn't work, you should file a bug for mu4e.

**Comment by ardpp** [comment]
Thanks! When using `ivy-mode` setting
`(setq mu4e-completing-read-function 'completing-read)`
is actually enough for things like jupmping to folders etc. For adress completion it doesnt work as expected, but for my needs the function `select-and-insert-contact` from stackexchange (see above) and 
`(define-key message-mode-map (kbd "TAB") 'select-and-insert-contact)`
are enough.
