### ISSUE TITLE
Add option to ivy-wrap

### ISSUE THREAD

**Issue by DamienCassou** [abo-abo/swiper#1271]
> When `ivy-wrap` is non-nil, wrap around after the first and the last candidate.

Would it be possible to have the same kind of behavior than isearch? When isearch is at the end, the first call to "next" will indicate an error, the second call to "next" will wrap.

**Comment by abo-abo** [comment]
Well, there's `ivy-wrap` already. If that's not sufficient, we could extend it a bit to have a third state (in addition to `nil` and `t`).

But that's extra complexity (likely some code will have to check `last-command`, and that doesn't always work). I'm reluctant to add this unless many people really want this feature.

**Comment by DamienCassou** [comment]
I agree that the added complexity might not be worth it. You may close the ticket.

**Comment by abo-abo** [comment]
ok
