### ISSUE TITLE
counsel-find-file: strange behaviour upon ivy-alt-done with ivy-text being equal to a directory name in starting directory

### ISSUE THREAD

**Issue by Georgiy-Tugai** [abo-abo/swiper#1272]
Upon `ivy-alt-done` being called with completion input being equal to a directory name in the starting directory (`current-directory` **upon initial call to Ivy**, not `ivy--directory`!), Ivy appears to cd into that directory even if it does not exist as a subdir of `ivy--directory`. No completion candidates are displayed in the "directory", backing out works fine.

This occurs whether there are alternative matching candidates in `ivy--directory` or not.

I believe that adding `expand-file-name` calls to the two lines linked below will resolve this;
[Lines 732 and 733 in ivy.el (ivy--directory-done)](https://github.com/abo-abo/swiper/blob/master/ivy.el#L732-L733)
```elisp
(ignore-errors (file-exists-p ivy-text)))
(if (file-directory-p ivy-text)
```

Tested on Windows 10 with Emacs 25.3.1, Ivy 20170926.915 and Counsel 20171003.1138 from MELPA.

**Comment by abo-abo** [comment]
Please add a more concrete reproduction scenario, I don't full understand.
And if you can add a PR as well, even better:)

**Comment by abo-abo** [comment]
Closing a timed out issue. If it's still reproducible, please open a new one.
