### ISSUE TITLE
Eager macro-expansion failure

### ISSUE THREAD

**Issue by oantolin** [abo-abo/swiper#1277]
I see this error message when I load ivy:

Eager macro-expansion failure: (error "(ivy-state-initial-input ivy-last) is not a valid place expression")

It seems harmless, but I thought I'd report it anyway.

**Comment by abo-abo** [comment]
I think a reinstall and an Emacs restart should solve this. Can you check?

**Comment by oantolin** [comment]
I use Emacs on two computers. On one I have version 25.2 and there reinstalling ivy and restarting worked. On my office computer I'm stuck with Emacs 24.5 and there reinstalling and restarting didn't get rid of the message.

**Comment by abo-abo** [comment]
Do you use the same `*.elc` files on both computers? You shouldn't do that, since `*.elc` files are not compatible across Emacs versions.

When I run:

    emacs=emacs-24.5 make plain

I don't see any warning or error.

**Comment by oantolin** [comment]
I don't share the byte compiled files. To test this on Emacs 24.5 I just deleted my entire `.emacs.d/elpa` directory and restarted Emacs (my configuration uses `use-package` to install packages if necessary). That's what worked on 25.2. I'll look into this a little more.

**Comment by oantolin** [comment]
Oh, I figured out my problem (although I did not figure out why it doesn't happen in Emacs 25.2).

In my `init.el` I define a function that uses `(setf (ivy-state-initial-input ivy-last) ...)`:

```elisp
(defun reloading (cmd)
    (lambda (x)
      (funcall cmd x)
      (setf (ivy-state-initial-input ivy-last) (file-name-directory x))
      (ivy--reset-state ivy-last)))
```

I use this to create actions for `counsel-find-file`:

```elisp
(ivy-add-actions
   'counsel-find-file
   `(("c" ,(given-file #'copy-file "Copy") "copy file")
     ("d" ,(reloading #'confirm-delete-file) "delete file")
     ("m" ,(reloading (given-file #'rename-file "Move")) "move file")))
```

I load `ivy` (and almost everything) lazily, so it makes sense that I get an error from eager macro-expansion on the `(setf (ivy-state-initial-input ivy-last) ...)` form. Adding `(eval-when-compile (require 'ivy))` before the `defun` gets rid of the error, for example.

What I don't know is why this error doesn't appear when using Emacs 25.2. Do you know why?

At any rate, this a problem with my configuration and not with ivy, so you should close this issue.

**Comment by abo-abo** [comment]
> What I don't know is why this error doesn't appear when using Emacs 25.2. Do you know why?

No idea. Might be an intended change in Emacs core, might be a regression.

> At any rate, this a problem with my configuration and not with ivy, so you should close this issue.

OK.
