### ISSUE TITLE
ivy: Can only toggle between 1st and 2nd candidate using C-n

### ISSUE THREAD

**Issue by tsdh** [abo-abo/swiper#128]
Sometimes, when switching buffers with ivy-completion, I get a list of all buffers initially (not all shown of course) and immediately see that the buffer I want to switch is the third one.  So I want to hit `C-n` twice to select that, however the second `C-n` switches back to selecting the first candidate again.

I can kind of reproduce it with a buffer list where the top candidate buffers are Gnus buffers.  Here are two screenshots where this problem occured.

![screenshot from 2015-06-03 22-21-44](https://cloud.githubusercontent.com/assets/103854/7971399/d109ea00-0a44-11e5-9d47-63ea475b452d.png)
![screenshot from 2015-06-03 23-01-49](https://cloud.githubusercontent.com/assets/103854/7971404/da3cd0b0-0a44-11e5-94b5-1f03ab365a24.png)

Probably the culprit is that there are duplicates in the candidates.  However, I don't see in the code how that can be possible.  When I evaluate `(ivy--buffer-list "" nil)` in the situation where `C-x b` would show the candidates as above, the returned list doesn't contain duplicates.

**Comment by abo-abo** [comment]
Is this reproducible with `emacs -Q`? Can you give me `ivy--all-candidates` and `ivy-last` for when the bug happens?

**Comment by tsdh** [comment]
I can only reliably reproduce the problem with Gnus, and then I can't start with `emacs -Q`...

But here're the values of the two variables.  As you can see, the gnus summary buffer is the first and the third element in the list similar to the first screenshot above.

```elisp
("*Summary nnimap+Uni:INBOX*" "*unsent wide reply to Lucidchart*" "*Summary nnimap+Uni:INBOX*" "*Article nnimap+Uni:INBOX*" "*Group*" "*Popup Eshell*" "_region_.pdf" "diss.tex" "*scratch*" "*Messages*" "*helm*" "_region_.tex" "*~/Repos/uni/diss/_region_ output*" "*RefTeX Select*" "*rdictcc*" "*Help*" "*imap log*" "*nntp-log*" ".newsrc-dribble")
[cl-struct-ivy-state "Switch to buffer: " internal-complete-buffer nil nil nil nil "*Summary nnimap+Uni:INBOX*" nil nil nil #<window 3 on *unsent wide reply to Lucidchart*> ivy--switch-buffer-action nil nil nil nil]
```

**Comment by tsdh** [comment]
By the way: I found at least one more occurrence of a candidate list with duplicates.  When you attach a file to a gnus message-mode buffer using `C-c C-a` (`mml-attach-file`) then select some file, you'll be asked for a mime type.  The completion list of mime types contains lots of duplicates and thus exhibits the same issue, i.e., you cannot move past the first duplicate entry with `C-n`.

**Comment by abo-abo** [comment]
> By the way: I found at least one more occurrence of a candidate list with duplicates

There will always be a problem with duplicates unless I uniformly apply `delete-dups` to each collection.  I did improve `delete-dups` to use a hash table on the trunk, but 24.5 still has the version that is super-slow for collections of size ~ 30000, which e.g. `describe-function` has.

In my opinion, it's the responsibility of the caller to pass a unique list to the completion engine.  The caller knows the size of its collection and should know a viable way to make it unique.

Options are:

1. Patch `mml-attach-file`.
2. Provide `counsel-mml-attach-file`.
3. Apply `delete-dups` uniformly and accept the universal slow-down.
4. Apply `delete-dups` selectively, only possible in case a function (like `read-file-name-internal`) is passed as a collection.

Suggestions with other options welcome.

**Comment by tsdh** [comment]
I'd probably go with an optional arg `DONT-DELETE-DUPS` and use that when I know there can't be dups like in `counsel-describe-*`, so basically option 3 with reversed duplicate semantics, i.e., remove them by default but allow the caller to suppress that for performance reasons.

But I don't understand why there are duplicates at all when switching buffers.  At least `(all-completions "" #'internal-complete-buffer)` returns no dups.  Does `ivy` somehow prepend the current buffer to that list to create the candidate list?  At least in the above scenario, the ivy candidates list is basically `(cons (current-buffer) (all-completions "" #'internal-complete-buffer))`.

**Comment by tsdh** [comment]
The problem lies in the `(when preselect ..)` form in `ivy-read`.  The problem is the regex `re` with doesn't work for buffers with leading `*` in their name.  PR coming in a minute!
