### ISSUE TITLE
Strange behavior from C-c C-o (ivy-occur)

### ISSUE THREAD

**Issue by jwiegley** [abo-abo/swiper#1284]
I'm switching over to ivy/swiper/counsel from helm, and have run into some odd behavior with `C-c C-o`:

 1. I use `counsel-describe-function`
 2. Immediately press `C-c C-o`
 3. Hit `RET` on any candidate. First odd behavior: it replacing the current buffer with the help text, but then moves point to some *other* newly displayed buffer which is neither the candidate list, nor the `*Help*` text. It would be nice if it kept the candidate list, with my point in the candidate list, and just popped up the `*Help*` text in another buffer.
 4. Move point to the `*Help*` buffer and hit `q`
 5. Go back to the candidates list, move point to another line, and hit `RET` again

Because of (3), examining several items from the candidate list requires a rather large number of keystrokes, because the candidates list keeps disappearing, *and* you never have focus in the `*Help*` buffer unless you manually select it.

**Comment by abo-abo** [comment]
I tried to reproduce this, and the bug happens only sometimes. Depending on the frame size, calling `describe-function` will split the frame either horizontally or vertically:

- when it splits vertically, everything works as intended: <kbd>RET</kbd> puts the help buffer in focus, <kbd>f</kbd> keeps focus in the occur buffer.
- when it splits horizontally, the bug you describe occurs.

So far, I have no idea how to influence how `describe-function` splits the frame. I'll have to investigate further later.

**Comment by abo-abo** [comment]
Looks like once both the occur and the help buffers are in separate windows, <kbd>f</kbd> will not disturb the window layout further.

**Comment by manuel-uberti** [comment]
I can confirm with the horizontal split I have the same behaviour described by @jwiegley.

**Comment by mookid** [comment]
I confirm I can reproduce as well.

As I understand it, at (3) the window from which `counsel-describe-function` has been called get the focus if it is still visible, which happens for instance when at least 2 windows are visible to begin with.

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by manuel-uberti** [comment]
Now with horizontal split (after `counsel-describe-function`), hitting `RET` on a candidate in the `*ivy-occur counsel-describe-function "^counsel"*` buffer, point stays in this buffer, and I can see `*Help*` buffer correctly displayed.

Looks fixed to me. Thank you @abo-abo.
