### ISSUE TITLE
Make counsel-rg to use space as wildcard dot?

### ISSUE THREAD

**Issue by sandric** [abo-abo/swiper#1286]
I found strange behavior using `counsel-rg` - before, using `counsel-ag` I used to space as `match all` character, that results in error in `counsel-rg`. Strangely, trying to change that via customizing base rg command, I found out that using `ag` outside of emacs also does not treat space as wildcard - only `.`, just like rg does. So I'm trying to understand if that using space as a dot in `counsel-ag` implemented via swiper or thats ag base command option? Is there the same option for `counsel-rg` base command?

**Comment by abo-abo** [comment]
I'm using spaces as wildcards in `counsel-rg` without problem. The default value of `counsel-rg-base-command` should work, check if you have it customized.

How it works:

1. Ivy gets an input `"de fun"` and passes it to `counsel-ag-function`.
2. The regex `"(de).*?(fun)"` is produced by ivy.
3. Substitute:
  - Given the template `counsel-rg-base-command` equal to `"rg -i --no-heading --line-number --color never %s ."`
  - the regex is substituted to become: `"rg -i --no-heading --line-number --color never  -- \\(de\\).\\*\\?\\(fun\\) ."`
4. You can call `shell-command-to-string` on the above regex to check that it works, or you can `insert` it into a `*shell*` buffer.

**Comment by sandric** [comment]
Its my fault, it turns out I changed base function, reverted to ivy's default base and works like a charm. I gonna close that one, sorry.

**Comment by abo-abo** [comment]
No problem.
