### ISSUE TITLE
At the end of the search return back to the beginning

### ISSUE THREAD

**Issue by bricewge** [abo-abo/swiper#13]
When doing a search with a lot a of match, it would be nice to go back to the start after the last item is reached. And the same for going to the first one to the last match without strolling through the entire buffer first.

**Comment by abo-abo** [comment]
This is done on purpose.  I like to be able to scroll to the first or last match, instead of having
them all in a circle.

You can scroll to the first match with <kbd>M-&lj;</kbd> and to the
last match with <kbd>M-&gt;</kbd>.

**Comment by bricewge** [comment]
Okay, so I'll do like this now.
