### ISSUE TITLE
ivy virtual buffers usability: different files with equal names

### ISSUE THREAD

**Issue by tsdh** [abo-abo/swiper#130]
I think virtual buffers are really interesting.  Basically, my only use for Helm is to find files from the recentf (and locate) sources, so with ivy's virtual buffers feature I probably could drop helm altogether.

However, virtual buffers are displayed only by the simple name of the corresponding file, and there are probably 20 `Makefile` on my recentf list.  Because of that, only one of them is shown and I have no clue which one.  So it would be great if virtual buffers would display the full path of the corresponding file (maybe using `uniquify-buffer-name-style`/`uniquify-get-proposed-name`) and also display all recentf files as candidates, not just one per simple name.

**Comment by abo-abo** [comment]
> However, virtual buffers are displayed only by the simple name of the corresponding file, and there are probably 20 Makefile on my recentf list. Because of that, only one of them is shown and I have no clue which one. So it would be great if virtual buffers would display the full path of the corresponding file (maybe using uniquify-buffer-name-style/uniquify-get-proposed-name) and also display all recentf files as candidates, not just one per simple name.

Good point. I was planning to extend the approach in `counsel-load-library` to a generic `uniquify` utility.  Since the actual Emacs `uniquify` is very inflexible and hard to adapt to use by other packages.

**Comment by tsdh** [comment]
Hm, indeed.  I hoped that `uniquify-get-proposed-name` would always the uniquified name but it just returns the simple name in case there's no buffer with that name already...

**Comment by basil-conto** [comment]
Wasn't this issue fixed in #255?

**Comment by abo-abo** [comment]
Looks like #255 was never merged.

**Comment by basil-conto** [comment]
> Looks like #255 was never merged.

@abo-abo Indeed, I was referring to commit b06daca74bd7b09116b9d4f3bd9a93b2c11a5272 with which you closed #255.

**Comment by basil-conto** [comment]
@abo-abo Just pinging again in case I replied too soon and you didn't get a notification from GitHub.

Sorry in advance for the noise if you already saw this.

**Comment by abo-abo** [comment]
OK, marking this as tentatively fixed. @tsdh feel free to open a new one if there are more ideas for improvement.
