### ISSUE TITLE
counsel-M-x inhibits printing command messages to minibuffer

### ISSUE THREAD

**Issue by jwiegley** [abo-abo/swiper#1302]
When I use `counsel-M-x` and select `pwd`, I have to switch to the `*Messages*` buffer to see what was printed.

**Comment by abo-abo** [comment]
Do you use the latest version? This bug was introduced and fixed yesterday, I can't reproduce it now.

**Comment by jwiegley** [comment]
Must have just pulled at an unlucky time, I can't reproduce it now.

Thanks so much for ivy and swiper, they are fantastic! I'm fully switched from helm now. :)
