### ISSUE TITLE
ivy - it would be desirable to allow unordered search?

### ISSUE THREAD

**Issue by ahungry** [abo-abo/swiper#1303]
This seems possible in helm, and a common use case would be for me to search:

`lisp repo user`

to first match all file types of '.lisp' type, then narrow to repositories directory, and then finally choose the user.lisp file (so, the candidate should match a target such as `src/repository/user.lisp`).

I implemented a custom ivy--regex-unordered function (it will generate a regex for every possible combo of terms - obviously quite slow if run against the full obarray list) - if ivy-re-match were modified to accept a list of regexes instead of a single regex (joined via an 'and) this performs nearly as fast as any of the existing ivy search mechanisms.

So, ideally, my search list would be narrowed similar to:

```lisp
(remove-if-not (lambda (candidate) 
  (and (string-match-p "lisp" candidate)
           (string-match-p "repo" candidate)
           (string-match-p "user" candidate)) candidates)
```

Would a PR similar to that be desirable if it didn't break BC and relied on the user setting ivy-re-builders-alist to include a tuple with values similar to `(t . 'ivy--regex-list-build))` - a function that would return a list of regexes (so, listp type) vs a single regex string?

**Comment by abo-abo** [comment]
There is already ivy--regex-ignore-order that does what you describe

**Comment by ahungry** [comment]
Awesome, thanks, not sure how I missed this! (actually I do know how, it isn't mentioned in the docstring for `ivy-re-builders-alist` :smile: )

Should it be added?  Docstring reads as such:

```
Possible choices: ‘ivy--regex’, ‘regexp-quote’,
‘ivy--regex-plus’, ‘ivy--regex-fuzzy’.
```

**Comment by abo-abo** [comment]
Yes, please PR.

**Comment by ahungry** [comment]
Added https://github.com/abo-abo/swiper/pull/1308
