### ISSUE TITLE
Feature request: Add failed inputs to swiper's history

### ISSUE THREAD

**Issue by jwiegley** [abo-abo/swiper#1305]
I've found that I have a very common isearch usage pattern:

 1. Hit C-s, search for something in a file. Can't find it, hit C-g.
 2. Select another file.
 3. Hit C-s C-s to resume the search, looking for that string in the new file.

This doesn't work with swiper, because it only records successful search strings in the history. It would be great if there were a customization option to also record whatever was entered at the prompt when I hit C-g to abort a failed search, so that I could quickly retry the search in another place.

**Comment by manuel-uberti** [comment]
I didn't think this was a use case for me, but it just happened today. Would be a nice feature indeed.

**Comment by abo-abo** [comment]
Thanks.

**Comment by manuel-uberti** [comment]
Thanks for this one, just tested and I get the previous "error" with <kbd>M-p</kbd>.
