### ISSUE TITLE
C-c C-o goes directly to match instead of occur buffer in ivy-imenu-anywhere

### ISSUE THREAD

**Issue by unhammer** [abo-abo/swiper#1306]
If you do
```
git clone https://github.com/abo-abo/swiper/
cd swiper
make plain
```
and paste in something like
```
(defun once ())
(defun upon ())
(defun a ())
(defun time ())
```
then `M-x ivy-imenu-anywhere` and hit `C-c C-o`, it will go to the match instead of the occur buffer (the occur buffer is still opened, but "behind" the current buffer).

Tested with 5b270c6031cf43a165f3a53a0f15bb1782cdf585

**Comment by abo-abo** [comment]
Where's `ivy-imenu-everywhere` from?

**Comment by unhammer** [comment]
Oh, that's why I had to run package-initialize for it to appear … doh! Posted at [the right place](https://github.com/vspinu/imenu-anywhere/issues/40) now, I hope :) sorry for the noise
