### ISSUE TITLE
Candidate lines are wrapped when left margin > 0

### ISSUE THREAD

**Issue by amosbird** [abo-abo/swiper#1307]
```
Hide Ivy Truncate Lines: [Toggle]  on (non-nil)
   [ State ]: SAVED and set.
   Minibuffer setting for ‘truncate-lines’.
```

![img-2017-11-22-203552](https://user-images.githubusercontent.com/5085485/33127774-f030d540-cfc4-11e7-9177-849693b93a53.png)

**Comment by amosbird** [comment]
This fixes the issue.
```
(add-hook! 'minibuffer-setup-hook (setq-local truncate-lines t))
```

**Comment by danil** [comment]
@amosbird 
> This fixes the issue.
> (add-hook! 'minibuffer-setup-hook (setq-local truncate-lines t))

not work for me(

**Comment by basil-conto** [comment]
@danil Please be more specific. What have you tried? Can you reproduce with `emacs -Q`?

Note that `add-hook!` is not a function or macro that is built into Emacs.

**Comment by danil** [comment]
@basil-conto 
> Please be more specific. What have you tried? Can you reproduce with emacs -Q?
> Note that add-hook! is not a function or macro that is built into Emacs.

thanks for quick response!
i provide more specific details after workday end.
p.s. what is a `add-hook!` if this is not a function and is not a macros?

**Comment by basil-conto** [comment]
@danil 

> p.s. what is a `add-hook!` if this is not a function and is not a macros?

I didn't say it is neither a function nor a macro. Given the syntax of Elisp, it **has** to be either function or a macro. What I said is, it is not a function or macro **built into Emacs**, i.e. it is something defined in either the `user-init-file` of or some package used by @amosbird which is external to Emacs core.

In other words, if you don't explicitly define `add-hook!` yourself or use the same corresponding package which @amosbird uses, then you will not be able to evaluate a call to `add-hook!`.

**Comment by amosbird** [comment]
@danil here is the add-hook! source code

```
(defmacro add-hook! (&rest args)
  "A convenience macro for `add-hook'. Takes, in order:

  1. Optional properties :local and/or :append, which will make the hook
     buffer-local or append to the list of hooks (respectively),
  2. The hooks: either an unquoted major mode, an unquoted list of major-modes,
     a quoted hook variable or a quoted list of hook variables. If unquoted, the
     hooks will be resolved by appending -hook to each symbol.
  3. A function, list of functions, or body forms to be wrapped in a lambda.

Examples:
    (add-hook! 'some-mode-hook 'enable-something)
    (add-hook! some-mode '(enable-something and-another))
    (add-hook! '(one-mode-hook second-mode-hook) 'enable-something)
    (add-hook! (one-mode second-mode) 'enable-something)
    (add-hook! :append (one-mode second-mode) 'enable-something)
    (add-hook! :local (one-mode second-mode) 'enable-something)
    (add-hook! (one-mode second-mode) (setq v 5) (setq a 2))
    (add-hook! :append :local (one-mode second-mode) (setq v 5) (setq a 2))

Body forms can access the hook's arguments through the let-bound variable
`args'."
  (declare (indent defun) (debug t))
  (let ((hook-fn 'add-hook)
        append-p local-p)
    (while (keywordp (car args))
      (pcase (pop args)
        (:append (setq append-p t))
        (:local  (setq local-p t))
        (:remove (setq hook-fn 'remove-hook))))
    (let ((hooks (doom--resolve-hook-forms (pop args)))
          (funcs
           (let ((val (car args)))
             (if (memq (car-safe val) '(quote function))
                 (if (cdr-safe (cadr val))
                     (cadr val)
                   (list (cadr val)))
               (list args))))
          forms)
      (dolist (fn funcs)
        (setq fn (if (symbolp fn)
                     `(function ,fn)
                   `(lambda (&rest _) ,@args)))
        (dolist (hook hooks)
          (push (if (eq hook-fn 'remove-hook)
                    `(remove-hook ',hook ,fn ,local-p)
                  `(add-hook ',hook ,fn ,append-p ,local-p))
                forms)))
      `(progn ,@(nreverse forms)))))
```

**Comment by danil** [comment]
@amosbird , @basil-conto 

thank you!
i `require` the `https://github.com/hlissner/doom-emacs/blob/master/core/core-lib.el`
and `ivy-truncate-lines` now works)
