### ISSUE TITLE
$ unusable for directories (ivy--regex-plus)

### ISSUE THREAD

**Issue by neojski** [abo-abo/swiper#1316]
It's not currently possible to find directories ending with bar, i.e. <kbd>bar$</kbd>. This is because one should actually type <kbd>bar/$</kbd> because directories have trailing slashes (see also #1315). I think we could strip the slashes before applying regexps for directories.

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by neojski** [comment]
Seems to be working fine, thank you.
