### ISSUE TITLE
Discrepancy between describe-function and counsel-describe-function

### ISSUE THREAD

**Issue by jwiegley** [abo-abo/swiper#1330]
If my point is at the end of `(find-file "hello" |`, `describe-function` will describe the function, `find-file`; `counsel-describe-function` appears to select whatever function matches the regex given by the text of the word before point.

**Comment by basil-conto** [comment]
I think this is intentional; see https://github.com/abo-abo/swiper/issues/1088#issuecomment-312284598.

**Comment by basil-conto** [comment]
Having said that, it might be nice to make this configurable.

**Comment by jwiegley** [comment]
I discovered it because I rely on the `describe-function` behavior, to understand the meaning of the "next argument" I'm about to type. Having to move point to avoid typing the function name at the prompt is inefficient enough that I'll just go back to `describe-function`, which still has the ivy completion.

**Comment by abo-abo** [comment]
Thanks, it's customizable now: use `(setq counsel-describe-function-preselect 'ivy-function-called-at-point)` to test.

**Comment by jwiegley** [comment]
Great, @abo-abo, thank you!

**Comment by abo-abo** [comment]
You're welcome.

> I discovered it because I rely on the describe-function behavior, to understand the meaning of the "next argument" I'm about to type.

I see. I simply use <kbd>C-1</kbd> for this with `lispy`.

**Comment by jwiegley** [comment]
I only recently installed `lispy`, so I've yet to build this into muscle memory.

**Comment by basil-conto** [comment]
> it's customizable now

Awesome, thanks!
