### ISSUE TITLE
Calling wgrep from ivy-occur on non-file buffers won't work

### ISSUE THREAD

**Issue by DamienCassou** [abo-abo/swiper#1337]
1. open your *scratch* buffer
2. type some text
3. start swiper to search for something
4. type `C-c C-o` to open an ivy-occur buffer
5. in the ivy-occur buffer, type `C-x C-q` to call `ivy-wgrep-change-to-wgrep-mode`
6. change the buffer
7. type `C-x C-s` to call `wgrep-finish-edit`

Actual: your changes are not reflected in the *scratch buffer* and the echo area displays "(No changes to be performed)"

Expected: the *scratch* buffer contains the changes down at step 6.

/cc @mhayashi1120 as he is the author of wgrep.

**Comment by abo-abo** [comment]
Closed in #1343. Please open a new issue if `wgrep` gets support for file-less buffers.
