### ISSUE TITLE
feature request: ability to not select candidate when hitting TAB multiple times (i.e., TAB TAB)

### ISSUE THREAD

**Issue by seabadger** [abo-abo/swiper#1339]
I might be in the minority with this, but in my mind and muscle memory, TAB is firmly fixed to "complete as far as possible", and I expect to confirm my selection via a different key (e.g., Enter/M-j etc). Thus,  I am very frustrated by the fact that hitting TAB multiple times results in selecting the candidate w/o confirmation. I understand that this is by design, but I'd like to request to make this behavior configurable. This is probably the only thing that prevents me from really giving ivy and company a try and keeps me using ido :)

**Comment by abo-abo** [comment]
Easy to customize:

```elisp
(define-key ivy-minibuffer-map (kbd "TAB") 'ivy-partial)
```

**Comment by seabadger** [comment]
Thanks a bunch! This in combination with
 ```
 (setq ivy-on-del-error-function nil)
```
is perfect! Might be worth adding this to a wiki somewhere, in case someone else also likes hitting TAB and/or DEL repeatedly :)

**Comment by abo-abo** [comment]
Feel free to add it to the wiki: https://github.com/abo-abo/swiper/wiki, it's open for editing for everyone.
