### ISSUE TITLE
ivy and minibuffer-depth-indication-mode

### ISSUE THREAD

**Issue by tsdh** [abo-abo/swiper#134]
With `minibuffer-depth-indication-mode` enabled, the minibuffer prompts are displayed as `[n] Prompt: ` during recursive edits where `n` denotes the minibuffer depth.  It does so by hooking into `minibuffer-setup-hook`.

With `ivy-mode` enabled, `minibuffer-depth-indication-mode` doesn't seem to have any effect.  That's unfortunate because it's a nice feature for people who frequently work with recursive minibuffers.

**Comment by abo-abo** [comment]
Thanks. Let me know if you want a face for the minibuffer depth. I don't really want it, and it's a bit tricky to add.

**Comment by tsdh** [comment]
No, no extra face needed.
