### ISSUE TITLE
counsel-org-file should use org-attach-directory variable 

### ISSUE THREAD

**Issue by neurolit** [abo-abo/swiper#1340]
Hi!

`org-attach-directory` variable sets the directory where attachments are stored with Orgmode. It would be nice to use it in `counsel-org-files` function as well, instead of "./data/" directory.

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by neurolit** [comment]
Works perfectly for me! However, if `org-attach-directory` is not defined, I think it will break your implementation.

**Comment by abo-abo** [comment]
The default setting is `"data/"`, so it should still work.

**Comment by basil-conto** [comment]
@abo-abo 

> The default setting is `"data/"`, so it should still work.

I think what @neurolit is referring to is the use of `org-attach-directory` without first loading `org-attach.el`.

Another couple of issues I found with the current implementation is that it does not support `:ID:` properties indented past the first column and it disregards dotfile attachments (i.e. filenames beginning with a full-stop). Older Org versions ignored dotfiles as well, but this is no longer the case - see `org-attach-file-list` in `org-attach.el`.

I will open a PR which addresses all three of these issues.
