### ISSUE TITLE
Need help understanding ivy-switch-buffer ordering

### ISSUE THREAD

**Issue by jwiegley** [abo-abo/swiper#1344]
I have several files open right now, one of them is `init.el`.  I want to switch to this buffer by typing "in", as `ido-switch-buffer` would do, but instead ivy seems to be showing me every other buffer but this one.  Here a picture of what I'm seeing right now, including the value of `(buffer-list)`:

<img width="1131" alt="ivy-switch-buffer" src="https://user-images.githubusercontent.com/8460/33585346-97d37954-d918-11e7-8fec-9dc6763253a8.png">

Here's how I configure:

```el
(use-package ivy
  :load-path "site-lisp/swiper"
  :demand t
  :diminish
  :bind (("C-x b" . ivy-switch-buffer)
         ("C-x B" . ivy-switch-buffer-other-window)
         ("M-H"   . ivy-resume))
  :bind (:map ivy-minibuffer-map
              ("C-r" . ivy-previous-line-or-history)
              ("M-r" . ivy-reverse-i-search))
  :preface
  (defun my-ivy-completing-read (&rest args)
    (let ((ivy-sort-functions-alist '((t . nil))))
      (apply 'ivy-completing-read args)))
  :config
  (ivy-mode 1)
  (ivy-set-occur 'ivy-switch-buffer 'ivy-switch-buffer-occur))
```

And here are my customization settings:

```el
'(ivy-dynamic-exhibit-delay-ms 200)
'(ivy-height 10)
'(ivy-ignore-buffers
  (quote
   ("\\` " "\\`\\*git-monitor:" "\\`\\*magit-process:" "\\.elc$" "\\.CFUserTextEncoding" "\\`\\*Quail Completions\\*\\'" "\\`\\.newsrc-dribble\\'" "\\`\\.newsrc.eld\\'" "\\`\\*Org Agenda\\*\\'")))
'(ivy-initial-inputs-alist nil t)
'(ivy-re-builders-alist (quote ((t . ivy--regex-ignore-order))) t)
'(ivy-use-virtual-buffers t)
'(ivy-wrap t)
```

**Comment by dieggsy** [comment]
You could probably add `(ivy-switch-buffer . "^")` to `ivy-initial-inputs-alist` to get this behavior, as it uses regex matching to filter candidates.

**Comment by abo-abo** [comment]
> Need help understanding ivy-switch-buffer ordering

It's simple: Ivy doesn't sort the `buffer-list`. The buffers are given in the default order, which by recent access.

As you input text, Ivy will select the first matching candidate on the list. So the fix proposed by @dieggsy makes perfect sense: if you append `^` to the input, all non-prefix matches will no longer match, and Ivy will still select the first matching candidate - the most recently accessed buffer with a matching name.

**Comment by jwiegley** [comment]
@abo-abo That's actually why I created the bug: You can see from by `buffer-list` output that the buffer I want is the most recently accessed buffer containing the letters "in". Why is it not shown within even the first 10 candidates of ivy-switch-buffer?

**Comment by abo-abo** [comment]
Found the culprit:

```elisp
(defcustom ivy-sort-matches-functions-alist
  '((t . nil)
    (ivy-switch-buffer . ivy-sort-function-buffer)))
```

Reset it like this:

```elisp
(setq ivy-sort-matches-functions-alist '((t . nil)))
```

It's funny but the customization `ivy-sort-function-buffer` was introduced at a user's request to make `ivy-switch-buffer` sorting more usual, to imitate `switch-buffer`.

**Comment by abo-abo** [comment]
Perhaps `ivy-sort-function-buffer` also needs to be patched.

**Comment by jwiegley** [comment]
Thanks, @abo-abo!

**Comment by basil-conto** [comment]
> Perhaps `ivy-sort-function-buffer` also needs to be patched.

Does it? If not, can this issue be closed?

**Comment by abo-abo** [comment]
I think it's fine to close it. Thanks.
