### ISSUE TITLE
Rebinding a key only for ivy-switch-buffer?

### ISSUE THREAD

**Issue by jwiegley** [abo-abo/swiper#1347]
Hi @abo-abo,

Similar to ido, I'd like to rebind `C-k` when using `ivy-switch-buffer` to do the same as `C-M-o k`. Is this possible?

**Comment by mookid** [comment]
There are two issues:

+ rebinding for one completion:  you just need `(define-key ivy-switch-buffer-map (kbd "C-k") (kbd "C-M-o w"))` for that

+ accessing the action corresponding to `k`: more tricky given the current code.

**Comment by manuel-uberti** [comment]
I have this in my setup:
```
(defun mu-ivy-kill-buffer ()
    (interactive)
    (ivy-set-action 'kill-buffer)
    (ivy-done))

  (bind-key "C-k" #'mu-ivy-kill-buffer ivy-switch-buffer-map)
```
Although it closes the candidate list after <kbd>C-k</kbd>.

**Comment by abo-abo** [comment]
> This almost works as well as ido:

Thanks for the compliment :)

Here's some code to work with:

```elisp
(define-key ivy-switch-buffer-map (kbd "C-k") 'ivy-switch-buffer-kill)

(defun ivy-switch-buffer-kill ()
  (interactive)
  (let ((bn (ivy-state-current ivy-last)))
    (when (get-buffer bn)
      (kill-buffer bn))
    (unless (buffer-live-p (ivy-state-buffer ivy-last))
      (setf (ivy-state-buffer ivy-last)
            (with-ivy-window (current-buffer))))
    (setq ivy--all-candidates (delete bn ivy--all-candidates))
    (ivy--exhibit)))
```

Please test, let's iron out the flaws.

**Comment by manuel-uberti** [comment]
It works for me, thank you @abo-abo

**Comment by jwiegley** [comment]
For me it works and kill the buffer, but it doesn't update the buffer candidate list and keeps my selection on a now-non-existent buffer.

**Comment by abo-abo** [comment]
> For me it works and kill the buffer, but it doesn't update the buffer candidate list and keeps my selection on a now-non-existent buffer.

Same for me. I'll look at this later.

**Comment by abo-abo** [comment]
Thanks, all.

> ivy.el (ivy-switch-buffer-kill): Add and bind to "C-c C-k"

Please test.

**Comment by jwiegley** [comment]
@abo-abo Yay, works perfectly! Thanks so much.

**Comment by manuel-uberti** [comment]
Thanks, works good here too.

**Comment by jwiegley** [comment]
@abo-abo Just need one more addition: Refreshing the buffer list after killing.  If I have two buffers named `foo`, they get uniquely renamed to `foo<bar>` and `foo<baz>`. After hitting `C-k` to kill `foo<bar>`, however, the selected candidate becomes `foo<baz>` rather than `foo`, mean I can't kill it without exiting ivy and restarting to renew the candidate list.

**Comment by abo-abo** [comment]
@jwiegley Please open a new issue with some setup steps description.

**Comment by jwiegley** [comment]
Trying with a simple case works as expected, so I'll have to table this until I have more time to debug the times when it doesn't work in my environment.
