### ISSUE TITLE
counsel-org-capture matches on key, is it possible to also match on description

### ISSUE THREAD

**Issue by zeltak** [abo-abo/swiper#1349]
Hi

following your excellnt blog post (as always :)) i started using `counsel-org-capture` which is wonderful.

i noticed that unless im missing something it only matches on the key yet nor the description. Is it possible to also match on description?

ie in 

```
                   ("b" "Templates for marking stuff to buy")
```

match not just on 'b' when typing but also the `Templates for marking stuff to buy`

thx!

Z

**Comment by abo-abo** [comment]
You can just remove the initial `^` from the input to match the description.

Alternatively, customize:

    (assq-delete-all 'counsel-org-capture ivy-initial-inputs-alist)

**Comment by zeltak** [comment]
thx!

that worked

Z
