### ISSUE TITLE
`C-x k` with ivy-mode kills wrong buffer

### ISSUE THREAD

**Issue by tsdh** [abo-abo/swiper#135]
I'm just viewing an attachment of an email received with Gnus.  The buffer name is `" *mm*-469037"`.  Now I want to kill that buffer and do `C-x k`.  The prompt is `10 Kill buffer (default  *mm*-469037): ` but in the list of candidates, the selected buffer is the gnus summary buffer.  And indeed, when I confirm with `RET` what gets killed is the gnus summary buffer and not the ` *mm*-469037` buffer.  (Well, and having a discrepancy between default value and what's selected is strange anyhow.)

I guess the reason is that the ` *mm*-469037` buffer is a hidden buffer and thus isn't on the buffer candidate list by default when there's no input starting with a space.  If that's indeed the culprit, then basically you have to make sure that the current buffer is always in the list of candidates even though it might be hidden.

**Comment by abo-abo** [comment]
Thanks, but it seems to me that `kill-buffer` is at fault here, since it sets `require-match` but does not put the proposed `default` into `collection`.
Anyway, added a work-around.

**Comment by tsdh** [comment]
Oleh Krehel <notifications@github.com> writes:

> Thanks, but it seems to me that `kill-buffer` is at fault here, since
> it sets `require-match` but does not put the proposed `default` into
> `collection`.
> Anyway, added a work-around.

Indeed, that seems strange.  But it doesn't only apply to `kill-buffer`
but to all commands with "b" interactive spec I think.  At least
`kill-buffer` or rather its C subr `Fkill_buffer` doesn't read the
buffer itself but eventually that's the job of `Fcall_interactively`
which calls `Fread_buffer`.  And that uses completing read with the
given default and `internal-complete-buffer`, and the latter suggests
hidden buffers only when the search string has a space prefix.

Bye,
Tassilo
