### ISSUE TITLE
ivy-occur buffers "mixed up"

### ISSUE THREAD

**Issue by ekenberg** [abo-abo/swiper#1353]
When opening (ivy-occur) several search results, strange things can happen. Here is a simple example, with counsel-ag:

```
piano:~/tmp/swiper$ make plain
emacs --version
emacs -Q -l colir.el -l ivy-overlay.el -l ivy.el -l swiper.el -l counsel.el -l targets/plain.el
piano:~/tmp/swiper$ GNU Emacs 25.3.2
```
in emacs:
```
counsel-ag ;; type "defun" then C-c C-o
press 'n' and the first match appears in the top window.
counsel-ag ;; type "equal" then C-c C-o
```
the top window now has ivy-occur for 'equal', and below is ivy-occur for 'defun'.
```
Now press 'n' with focus in the 'equal' window.
```
Expected output is first match for 'equal', but point switches to the lower window and the next match for 'defun' is shown in the top window. Somehow the buffers seem to get mixed up. I've seen messier examples with different combinations of ivy-occur buffers mixing up and swapping windows around, but hopefully this is enough for debugging.

**Comment by abo-abo** [comment]
Thanks, fixed in #2257
