### ISSUE TITLE
Selecting files and ~/

### ISSUE THREAD

**Issue by jwiegley** [abo-abo/swiper#1355]
Hi @abo-abo, when entering file paths at vanilla Emacs prompts, I can say `~/` to ignore whatever I'd typed previously and just start back at the home directory.

With Ivy, it seems hitting just `~` resets me to home, and then typing `/` resets me to the root directory (although, I see no dynamic updating until after I've typed some text and another `/` character).

Would it be possible to have Ivy ignore a `/` character typed immediately after `~`?  I've been trying to train my muscle memory to stop typing `~/`, but it's proving difficult, since I'm used to `~text` meaning the home directory of `text`. Thanks.

**Comment by jwiegley** [comment]
The other thing that makes just `~` hard to adapt to is that it doesn't work in the shell, where I need `~/` to start completing directories within home...

**Comment by jwiegley** [comment]
A further tidbit: If you mistakenly type `~/foo/bar`, and the prompt is now `~//foo/bar`, you'll notice that editing the prompt is unable to re-activate candidate selection.  You now just have a plain edit box, with no dynamic behavior. I have to hit C-g and start selection over again to get Ivy to resume working.

**Comment by jwiegley** [comment]
Hah, `ivy-magic-tilde`.

**Comment by abo-abo** [comment]
> I've been trying to train my muscle memory to stop typing ~/, but it's proving difficult, since I'm used to ~text meaning the home directory of text.

I get that it's hard to re-train muscle memory. I've had trouble un-learning `ido-mode` <kbd>C-x C-f C-f</kbd> myself, although I've managed it by now.  However, after using only Linux for about 8 years I've never had more than one user in `/home/`: myself. The default behavior of <kbd>~</kbd> was implemented with that in mind.  It's still possible to do `~ DEL` to access `/home/`, but again, re-training muscle memory is hard.

> The other thing that makes just ~ hard to adapt to is that it doesn't work in the shell, where I need ~/ to start completing directories within home...

True. But my aim is trying to figure out a system that works well 95% of the time (saving an extra key: `/`), while having reasonable fall-backs in the other 5% of the cases. But even in the best case, this 95% use case is for me, not for all the users. So input from other users is appreciated, and I try to adapt Ivy to serve their needs. At the same time, the aim Ivy isn't to perfectly emulate the old approaches, it's to provide an interface that's 95% convenient, 100% reliable, and aims to decrease your mental overhead.

> A further tidbit: If you mistakenly type ~/foo/bar, and the prompt is now ~//foo/bar, you'll notice that editing the prompt is unable to re-activate candidate selection. You now just have a plain edit box, with no dynamic behavior. I have to hit C-g and start selection over again to get Ivy to resume working.

I don't get this, I can still do <kbd>C-b</kbd> or <kbd>C-a</kbd> or <kbd>C-k</kbd>. Can you elaborate?

**Comment by jwiegley** [comment]
Thanks for the clarification @abo-abo, but `ivy-magic-tilde` perfectly predicted my use case. After customization that to nil, Ivy behaves exactly as I'd hoped.
