### ISSUE TITLE
Delete duplicates in counsel-minibuffer-history?

### ISSUE THREAD

**Issue by danielmatz** [abo-abo/swiper#1358]
The new `counsel-minibuffer-history` variable was a great addition, thank you.

After using it for a while now, I think that it would be nice to have it copy the history variable and delete duplicates.  If, for example, I run the same shell command a lot, when I use `counsel-minibuffer-history` all of the visible matching completions can be the same command, which seems like a waste of space.

I'm aware of `history-delete-duplicates`, but that would change the contents of the history variable itself.  Perhaps a user would like the duplicates in the history, so that, for example, stepping backwards through shell commands would retain all the commands that were run.  But then when filtering the candidates with counsel, the ordering is no longer relevant, and removing duplicates would be more useful.

**Comment by abo-abo** [comment]
Thanks, please test.
