### ISSUE TITLE
Feature request: show key-binding when calling execute-extended-command with ivy enabled

### ISSUE THREAD

**Issue by brabalan** [abo-abo/swiper#136]
Ivy meets all my helm needs, while feeling faster, with one small exception: when I use `M-x` I don't see the binding of the command suggested. I have found this to be a great way to learn bindings … Would you consider adding this to ivy?

**Comment by abo-abo** [comment]
> Would you consider adding this to ivy?

Sure, just need to write a separate function `ivy-M-x`, similar to `helm-M-x`.  Right now, I'm using my fork of [smex](https://github.com/abo-abo/smex). I've sent the pull request ages ago, looks like it's not getting merged.

**Comment by brabalan** [comment]
Having an ivy-M-x would be great, but in the meantime I'll give your fork of smex a try. (A bit later). It's very nice indeed. I like how one can look-up key bindings, but it would be nice to see them displayed by default.

**Comment by abo-abo** [comment]
Have a look. Let me know what's missing.

**Comment by kaushalmodi** [comment]
Thanks for adding this.

Few comments from few minutes of trying it out:

- Can you sort the entries by last used instead of sorting the commands alpha-numerically? Currently the first command I see is `2C-associate-buffer` which I probably am never going to use. It would be nice to see commands in the order of most recently used to least recently used.
- Is there a plan to enable fuzzy searching for certain commands using `ivy`/`counsel`? IMO `counsel-M-x` would be the first candidate to fit the bill for fuzzy searching. The reason is that many times the commands are long and it is faster to just ram in few letters from that whole command instead of remembering to hit a space after every few letters. Example: It is faster to type `licdis` instead of `li c dis` to get to `list-colors-display`.

**Comment by kaushalmodi** [comment]
It would be awesome to make `C-.` and `C-,` in this command too (referring to your recent blog post: http://oremacs.com/2015/06/08/describe-variable-tip/).

**Comment by abo-abo** [comment]
Added smex sorting and extra bindings. I haven't looked to implementing own sorting so far, since it can be expensive to sort.

I'll look into fuzzy matching without a space soon.

**Comment by abo-abo** [comment]
Thanks, this fuzzy matcher isn't as slow as I thought it would be.
Actually it's as fast as the default for 8000 candidates.

**Comment by brabalan** [comment]
This is great, thanks a lot!

**Comment by abo-abo** [comment]
You're welcome.

**Comment by kaushalmodi** [comment]
The "recently used commands" cache stays stale until `smex` is called. No matter which command I execute using `counsel-M-x`, the first option in the command list stays the same, until I execute `smex`. So we also need to update the smex cache with each execution of `counsel-M-x`.

**Comment by kaushalmodi** [comment]
It was simply missing an `smex-rank` call:

```el
(defun counsel-M-x (&optional initial-input)
  "Ivy version of `execute-extended-command'.
Optional INITIAL-INPUT is the initial input in the minibuffer."
  (interactive)
  (unless initial-input
    (setq initial-input (cdr (assoc this-command
                                    ivy-initial-inputs-alist))))
  (let ((ivy-format-function #'counsel--format-function-M-x)
        (cands obarray)
        (pred 'commandp)
        (sort t))
    (when (or (featurep 'smex)
              (package-installed-p 'smex))
      (require 'smex)
      (unless smex-initialized-p
        (smex-initialize))
      (smex-detect-new-commands)
      (smex-update)
      (setq cands smex-ido-cache)
      (setq pred nil)
      (setq sort nil))
    (ivy-read "M-x " cands
              :predicate pred
              :require-match t
              :history 'extended-command-history
              :action (lambda (cmd)
                        (execute-extended-command current-prefix-arg cmd)
                        (smex-rank (intern cmd))) ; <-- FIX
              :sort sort
              :keymap counsel-describe-map
              :initial-input initial-input)))
```

**Comment by abo-abo** [comment]
@kaushalmodi, thanks. But I think intern isn't necessary.
