### ISSUE TITLE
counsel-yank-pop: ivy-height

### ISSUE THREAD

**Issue by jojojames** [abo-abo/swiper#1362]
Looking at 

```
(defun counsel-yank-pop ()
  "Ivy replacement for `yank-pop'."
  (interactive)
  (if (eq last-command 'yank)
      (progn
        (setq ivy-completion-end (point))
        (setq ivy-completion-beg
              (save-excursion
                (search-backward (car kill-ring))
                (point))))
    (setq ivy-completion-beg (point))
    (setq ivy-completion-end (point)))
  (let ((candidates
         (mapcar #'ivy-cleanup-string
                 (cl-remove-if
                  (lambda (s)
                    (string-match "\\`[\n[:blank:]]*\\'" s))
                  (delete-dups kill-ring)))))
    (let ((ivy-format-function #'counsel--yank-pop-format-function)
          (ivy-height 5))
      (ivy-read "kill-ring: " candidates
                :action 'counsel-yank-pop-action
                :caller 'counsel-yank-pop))))
```

Looks like the height is hardcoded to 5. I'm curious why that is and would you be open to a PR making this customizable? Something like counsel-yank-pop-ivy-height? Not sure how clean that'd be since there are other counsel functions with hardcoded heights to them.

**Comment by abo-abo** [comment]
> Something like counsel-yank-pop-ivy-height?

Sounds fine. 

The change of `ivy-height` is likely because each item gets an allowance of 3 lines, so the actual text height can be up to 3 times larger than 10 - the default height of ivy. Somehow, 5x3 was a nice compromise height.

**Comment by basil-conto** [comment]
> The change of ivy-height is likely because each item gets an allowance of 3 lines, so the actual text height can be up to 3 times larger than 10 - the default height of ivy. Somehow, 5x3 was a nice compromise height.

Yup, see https://github.com/abo-abo/swiper/issues/315#issuecomment-176276070

**Comment by abo-abo** [comment]
This is fixed now, thanks again.
