### ISSUE TITLE
Sometimes only a single tab should be needed

### ISSUE THREAD

**Issue by jwiegley** [abo-abo/swiper#1364]
I'm trying out `counsel-find-file` instead of `lusty-file-explorer`, and I've noticed just one thing that's curious:

If I type in letters to narrow the candidate list, like "foo", and then type `C-n` to select the candidate I want, pressing TAB sometimes does nothing at all if the other candidates have similar match text after `foo`.

I would expect, since I've just used `C-n` to manually select a candidate, that `TAB` would automatically accept that candidate and let me continue building my path. It seems odd to have to hit `TAB TAB` in these cases.

**Comment by basil-conto** [comment]
I think you're experiencing the difference between `C-j` (`ivy-alt-done`) and `TAB` (`ivy-partial-or-done`), which is, in a sense, "reversed" from other `TAB`-centric completion systems such as that in `bash`. Ivy has a bias for preferring `C-j` as the default completion key, which exhibits your desired behaviour. I personally don't like changing too many defaults, so I've trained my muscle memory to use `C-j`, but many users prefer to swap these two keybindings around. Note also that two `TAB` presses are equivalent to one `C-j`.

**Comment by basil-conto** [comment]
In case you haven't come across them, the relevant sections of the manual are [`(ivy) Key bindings for single selection action then exit minibuffer`](http://oremacs.com/swiper/#key-bindings-for-single-selection-action-then-exit-minibuffer) and [`(ivy) File Name Completion`](http://oremacs.com/swiper/#file-name-completion).

**Comment by jwiegley** [comment]
Thanks, it's really time for me to go through the manual thoroughly.

**Comment by jwiegley** [comment]
This bit did the track:

``` elisp
  :bind (:map ivy-mode-map
              ("<tab>" . ivy-alt-done)
              ("C-i" . ivy-partial-or-done))
```

**Comment by dieggsy** [comment]
Does that work? Shouldn't it be `ivy-minibuffer-map`? That's what I've always used.

**Comment by jwiegley** [comment]
Yes, just discovered that. :)

**Comment by abo-abo** [comment]
> pressing TAB sometimes does nothing at all

<kbd>TAB</kbd> will extend your current input as much as possible without changing your selection.

This is exactly how bash completion works. Given `foo-1.txt` and `foo-2.txt` in the current folder, and the input `cat f` in bash:

- first <kbd>TAB</kbd> will expand the input to `cat foo-` - as much as possible, without actually making a decision.
- second <kbd>TAB</kbd> will do nothing
- third <kbd>TAB</kbd> will show the completions list

@basil-conto is correct that Ivy has a bias for <kbd>C-j</kbd> (`ivy-alt-done`). In fact, for a long time <kbd>TAB</kbd> (`ivy-partial-or-done`) did not exist: it was added at a user's request.

Here's a remapping I do in my personal config:

    (define-key ivy-minibuffer-map (kbd "<return>") 'ivy-alt-done)

I only use `ivy-done` - <kbd>C-m</kbd> (physical `CAPS-m`), and `ivy-alt-done` - `return` (physical `;-v`), never `ivy-partial-or-done` - <kbd>TAB</kbd>.

The users can configure the bindings to their liking, and the defaults are reasonable enough.  Suggestions for improvement welcome.
