### ISSUE TITLE
Ivy-inhibit-action inhibiting more than just ivy-call

### ISSUE THREAD

**Issue by dieggsy** [abo-abo/swiper#1366]
Not sure if intended, but setting `ivy-inhibit-action` to `t` is also causing other actions set with `ivy-add-action` not to appear.

For example, I have the following in my settings:
```emacs-lisp
(ivy-add-actions
   'counsel-find-library
   '(("j"
      find-library-other-window
      "other window")))
```
But doing (as a kind of dumb example perhaps) this:
```emacs-lisp
(let ((ivy-inhibit-action t))
  (find-library-other-window (counsel-find-library)))
```
Doesn't show the 'j' action with either `ivy-dispatching-done` or `ivy-dispatching-done-hydra`. If this is intended, it's at least not documented in the docstring for `ivy-inhibit-action`. I think it's useful to show added actions though, in case someone _only_ want's to override the default `ivy-call` behavior.

**Comment by abo-abo** [comment]
> Not sure if intended, but setting ivy-inhibit-action to t is also causing other actions set with ivy-add-action not to appear.

This is a bug in `counsel-find-library`, its `:caller` parameter wasn't specified. Even without a let-binding `(counsel-find-library)` doesn't show the `j` action.

**Comment by abo-abo** [comment]
Fixed, thanks.

**Comment by dieggsy** [comment]
@abo-abo hmm, that fixed the issue with the actions not showing up, though now it seems I can't actually select the other actions. For example:
```emacs-lisp
(defun d/counsel-find-file-other-window ()
  (interactive)
  (let ((ivy-inhibit-action t))
    (find-file-other-window (counsel-find-file))))
```
Calling any action other than the default jus calls the default action in this case. The same happens for counsel-find-library.

**Comment by abo-abo** [comment]
This is expected behavior: if you bind `ivy-inhibit-action`, the only thing `ivy-read` does is return the candidate as a string. Imagine it did anything in your example - `find-file-other-window` would still be called, regardless.

Yes, you're losing out on many features of Ivy, but that's also the point of the variable.

**Comment by dieggsy** [comment]
Huh. Are there any plans to be able to change _just_ the default behavior of any given ivy command?

**Comment by abo-abo** [comment]
@dieggsy What's your use-case? I think `ivy-inhibit-action` should be avoided whenever possible, it cripples down `ivy-read` API down to `completing-read-function`. Its purpose is to be used for hacking incompatible APIs together, not for creating new things from scratch.

**Comment by dieggsy** [comment]
Well, for example, I'd like `counsel-find-file` and `counsel-find-library` to go to other window by default. A bunch of `other-window` variants could be added to counsel/ivy functions (I see `ivy-switch-buffer` already has one), or there could be a way to implement this at the user level.

**Comment by abo-abo** [comment]
I wanted for a long time to extend the `ivy-set-actions` / `ivy-add-actions` interface to let you override even the default action.

But this isn't a change to be taken lightly. It needs good planning and very careful implementation. It will come at some point, I don't know how soon.

In the meantime, you can advice the default actions with `advice-add`. It's Emacs, after all:)

**Comment by dieggsy** [comment]
Could you point me in a bit more specific a direction for that? All I can think of is just overriding the whole `counsel-find-file` function, for example.

**Comment by abo-abo** [comment]
Ah sorry. I didn't realize `counsel-find-file-action` did not exist. It's added now and you can advise or redefine it.

**Comment by dieggsy** [comment]
@abo-abo Oh, thanks. FWIW, `counsel-find-library-action` isn't a thing either... Though that function is simple enough to just advise directly, and I guess we could go down a deep rabbit hole if we worry about every `counsel-*-action` that doesn't exist.
