### ISSUE TITLE
counsel-describe-* and quoted stuff

### ISSUE THREAD

**Issue by tsdh** [abo-abo/swiper#137]
This is another instance of #126.

Say you have some code

```elisp
(customize-option 'TeX-view-program-list)
```

in an Gnus article buffer (or just some fundamental-mode or text-mode buffer).  `counsel-describe-variable` with point on `TeX-view-program-list` won't preselect that (AUCTeX) variable because `(thing-at-point 'symbol)` returns `'TeX-view-program-list`.

**Comment by abo-abo** [comment]
Thanks, should work better now.
