### ISSUE TITLE
Counsel-find-file and changing tramp remote

### ISSUE THREAD

**Issue by mahaarbo** [abo-abo/swiper#1377]
So I'm working on a remote file with tramp over ssh, and then I'd like to work on a file on my computer. But`counsel-find-file` doesn't let me backslash all the way back to the base `/` so that I can change to the local files.
Recreate:
1. `C-x C-f` into `/ssh:user@myplace:/myfile.txt`
2. work for a bit
3. `C-x C-f`
4. backslash to try to remove the `/ssh:user@myplace:/`

Package used: `swiper-20171217.334` from `melpa`. In `ido` I could always just press `C-f` to fallback to the standard `find-file`, and that could probably be a quick fix.

**Comment by abo-abo** [comment]
You can press:

- either <kbd>//</kbd> to go to your local root
- or <kbd>~</kbd> to go to your local home

**Comment by abo-abo** [comment]
Also:

- <kbd>M-o b</kbd> to cd to a bookmark
- <kbd>C-r</kbd> to go back to a previous location

**Comment by mahaarbo** [comment]
Oh, didn't notice, thanks! That fixes my whole workflow.

**Comment by CsBigDataHub** [comment]
I use Counsel-find-file. When I am in tramp mode and I want to find a file in local, I should be using` ~` or `//` to get back to local.



In my case if I use `~` it's taking me to _home directory of remote_ and when I use `//` it's taking me to _root directory of remote_.


How do I fix it.


Please note- C-x C-r works file to navigate recent file , which I am using as a work around to navigate to local file system.
