### ISSUE TITLE
Feature request: cache for past avy-goto-* commands

### ISSUE THREAD

**Issue by heikkil** [abo-abo/swiper#1383]
I find myself using repeatedly the same  character for avy-goto-word-1. Unless I am wrong, there is currently no way to respond to the 'char: ' prompt to use the previous character searched?

**Comment by abo-abo** [comment]
Already a feature:

```elisp
(global-set-key (kbd "C-c C-j") 'avy-resume)
```

Hmm, I just noticed that you opened an `avy` issue in the `swiper` repo. Anyway, I close the issue. I noticed that `avy-resume` is undocumented, I'll add something to the README.
