### ISSUE TITLE
Using either ag or rg on dos line-encoded files shows ^M characters at the buffer

### ISSUE THREAD

**Issue by r-darwish** [abo-abo/swiper#1384]
When using either `counsel-ag` or `counsel-rg` to search something in a DOS line-encoded project, `^M` characters appear in the buffer. When I press `C-c C-o` these characters also appear in the `ivy-occur` buffer. [wgrep](https://github.com/mhayashi1120/Emacs-wgrep) does not work as a result. Emacs `grep` command does not display the `^M` characters.

**Comment by abo-abo** [comment]
See `counsel-async-split-string-re`.

**Comment by whatacold** [comment]
Customization of the variable like below works for both unix and dos line endings for me:

```lisp
(setq counsel-async-split-string-re "\r?\n")
```

Thanks.
