### ISSUE TITLE
Complete any object

### ISSUE THREAD

**Issue by DamienCassou** [abo-abo/swiper#1387]
I would like to complete over any kind of object and to use `ivy-set-display-transformer` to choose how to render each. For example, I expect the following to work:

```emacs
(cl-defstruct struct1 name)

(ivy-read "Select: "
          (list (make-struct1 :name "1")
                (make-struct1 :name "2"))
          :caller 'ivy-structs)

(ivy-set-display-transformer 'ivy-structs #'struct1-name)
```

This does not work. My use case is to complete over artist and album names and get proper artist and albums as a result.

**Comment by abo-abo** [comment]
You can't call `ivy-read` directly as long as this doesn't work:

```elisp
(all-completions "" (list (make-struct1 :name "1") (make-struct1 :name "2")))
```

Here's the idiomatic way to write this:

```elisp
(cl-defstruct struct1 name)

(defvar albums (list (make-struct1 :name "1") (make-struct1 :name "2")))

(defun ivy-album ()
  (interactive)
  (let ((xs))
    (ivy-read "Select: "
              (mapcar (lambda (x) (cons (struct1-name x) x)) albums)
              :action 'ivy-album-action)))

(defun ivy-album-action (x)
  (message "%S" x))
```

See also e.g. `counsel-semantic` - it works along the lines of the above code.

**Comment by DamienCassou** [comment]
Thanks for your answer. I will try your approach.
