### ISSUE TITLE
Support regexp special characters during fuzzy search

### ISSUE THREAD

**Issue by kaushalmodi** [abo-abo/swiper#139]
I have this in my emacs init:

```el
    (setq ivy-re-builders-alist '((t . ivy--regex-fuzzy)))
```

1. I like the fuzzy search option and it works great but then the `^` and `$` regexp special characters do not work.

2. Also if I enter a search term as `tmux` would it be possible to show an entry called `tmux` first if available instead of showing `.*t.*m.*u.*x.*` entries first?
  
Below picture is what I get when I do `M-x man ^tmux$` with `ivy-mode` on.

![clipboard01](https://cloud.githubusercontent.com/assets/3578197/8133395/2405b70e-10f6-11e5-868e-88c89298cddd.png)

**Comment by abo-abo** [comment]
> I like the fuzzy search option and it works great but then the ^ and $ regexp special characters do not work.

Thanks, fixed.

> Also if I enter a search term as tmux would it be possible to show an entry called tmux first if available instead of showing .*t.*m.*u.*x.* entries first?

There's code in place that selects a string if the input is a perfect match.
So for the input "tmux", tmux will be selected. But for the input "^tmux", it might not be selected.

**Comment by abo-abo** [comment]
Also, neat `ivy-mode` indicator :).

**Comment by kaushalmodi** [comment]
> Also, neat ivy-mode indicator :).
Hah! You noticed that :) I couldn't find an ivy unicode so being content with maple leaf :)

**Comment by abo-abo** [comment]
Just found this one: [❧](http://www.fileformat.info/info/unicode/char/2767/index.htm), but it's too small unless you zoom in a lot.

**Comment by kaushalmodi** [comment]
Found a bunch of leaves using `counsel-unicode-char` :) 

![clipboard01](https://cloud.githubusercontent.com/assets/3578197/8134232/7462e578-10fb-11e5-99a5-056d354fb5a0.png)

**Comment by abo-abo** [comment]
All blanks for me. What's the font you're using? Is it possible to have DejaVu for standards, and another font for Unicode stuff?

**Comment by kaushalmodi** [comment]
I am using Symbola font; download/install the Symbola font (free) and then have something like [my setup](https://github.com/kaushalmodi/.emacs.d/blob/master/setup-files/setup-symbola.el) in your setup.

Then I use unicode fonts only if available on my system (as I use the same init on multiple systems): https://github.com/kaushalmodi/.emacs.d/blob/bf13a9c848fa02c8bdfb694f2f0cb7467735fe4a/setup-files/setup-mode-line.el#L123-L127

**Comment by abo-abo** [comment]
Can't make this work:

```elisp
(when (find-font (font-spec :name "Symbola Condensed"))
  ;; Manually choose a fallback font for Unicode
  ;; http://endlessparentheses.com/manually-choose-a-fallback-font-for-unicode.html
  (set-fontset-font "fontset-default" nil (font-spec :size 20 :name "Symbola Condensed"))
  (setq font-symbola-p t))
```

This works, but it changes all chars, not just Unicode:

    (set-frame-font "Symbola Condensed")

This goes back to normal, but some Unicode chars become bricks.

    (set-frame-font "DejaVu Sans Mono")

**Comment by kaushalmodi** [comment]
Hmm, I set my default emacs fonts using [`~/.Xdefaults`](https://github.com/kaushalmodi/dotfiles/blob/17ed198eeda03cacbce1bd707550426f38328293/.Xdefaults#L34-L35).

The only font change I do in my emacs init is for that Symbola font.

I am on RHEL 5.10.
