### ISSUE TITLE
Swiper history broken

### ISSUE THREAD

**Issue by xendk** [abo-abo/swiper#1391]
The history in `swiper` seems to forget all but the last entry. `swiper-history` seems fine, contains all history items, and other ivy commands like `counsel-find-file`s history works just without problem.

I've reproduced the error on https://github.com/abo-abo/swiper/commit/c2bc6ac92a6cea730d7887813a816bdf873f9b92 in a clean Emacs with nothing else loaded.

Pressing `M-p` selects the last history item, but subsequent `M-p` doesn't change the item. However, an equal number of `M-n` needs to be pressed to reach an empty line again.

**Comment by xendk** [comment]
Sorry, but it's still a bit odd. I have to press `M-p` twice to get the previous element most of the time?

**Comment by abo-abo** [comment]
Thanks again, please check.

**Comment by xendk** [comment]
:+1: 
Typing `M-n` at the end the history seems to pick up the word at point, but I think that's a feature? Apart from that it behaves as expected.

**Comment by abo-abo** [comment]
> Typing M-n at the end the history seems to pick up the word at point, but I think that's a feature?

Yes.

> Apart from that it behaves as expected.

Thanks for testing.
