### ISSUE TITLE
counsel-ag and counsel-rg no longer work when INITIAL-DIRECTORY is passed

### ISSUE THREAD

**Issue by ericdanan** [abo-abo/swiper#1392]
The issue just appeared with commit b8e5ba64cbf1adb75176e09a514544e5c1d58f14.

That commit decoupled `counsel-git-grep-action` from `counsel--git-dir`. But `counsel-ag` and `counsel-rg` use this latter function as action and work by binding `counsel--git-dir` to `INITIAL-DIRECTORY` if passed. The result is that `INITIAL-DIRECTORY` is no longer taken into account: hitting `RET` on a candidate systematically tries to open the corresponding filename relative to the current buffer's directory.

I'm willing to PR but not sure what's the best way to fix this. Perhaps add and an optional `INITIAL-DIRECTORY` argument to `counsel-git-grep-action`?

**Comment by abo-abo** [comment]
Thanks for the report. I'd like to make a comprehensive commit that replaces `counsel--git-dir` with `(ivy-state-directory ivy-last)` where appropriate. I'll do this in the evening.

**Comment by cpbotha** [comment]
Ran into the exact same issue.

As an emergency work-around, I replaced `(ivy-state-directory ivy-last)` with `counsel--git-dir` in `counsel-git-grep-action` as I constantly use `counsel-ag` with `INITIAL_DIR` for notes searching.

**Comment by ericdanan** [comment]
@abo-abo Thanks. Will it still be possible to pass an initial directory to `counsel-ag` and `counsel-rg`? (I'm interested in this for counsel-projectile.)

**Comment by abo-abo** [comment]
> Will it still be possible to pass an initial directory to counsel-ag and counsel-rg? (I'm interested in this for counsel-projectile.)

Yes, sure.

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by ericdanan** [comment]
Thanks, I tested `counsel-ag` and `counsel-rg` work fine for me.
