### ISSUE TITLE
Can I invoke another ivy session to select an prefix directory string for current ivy session?

### ISSUE THREAD

**Issue by amosbird** [abo-abo/swiper#1395]
When doing file saving actions, I often needs to navigate through directories in ivy file session. I'd like to call another ivy command so that I can select the directory from a predefined list of directories and insert it into the ivy file session.

**Comment by abo-abo** [comment]
You mean like <kbd>C-r</kbd>?

**Comment by amosbird** [comment]
Yup, but from my customized list instead of the builtin history.

**Comment by amosbird** [comment]
Thanks for mentioning `C-r`.
