### ISSUE TITLE
counsel-file-jump with custom directory

### ISSUE THREAD

**Issue by hisnawi** [abo-abo/swiper#1404]
I found an alternative to projectile-find-file which is counsel-file-jump, the only annoyance I have is that it doesn't take a directory to start the search in recursively, it only depends on the current directory, or the directory that the cursor points to.

Is there a way to make it take an argument (path) to start the search inside?

**Comment by abo-abo** [comment]
> Is there a way to make it take an argument (path) to start the search inside?

It already does that:

    (defun counsel-file-jump (&optional initial-input initial-directory)

You can input the directory interactively if you do <kbd>C-u</kbd> before the call.

**Comment by hisnawi** [comment]
That is brilliant!
Thank you so much. This is exactly what I was looking for.

One more thing, how can I bind a keyboard shortcut to the whole sequence "C-u counsel-file-jump"?

**Comment by basil-conto** [comment]
> how can I bind a keyboard shortcut to the whole sequence "C-u counsel-file-jump"?

The idea is to define your own [command](https://www.gnu.org/software/emacs/manual/html_node/elisp/Using-Interactive.html) which sets the [prefix argument](https://www.gnu.org/software/emacs/manual/html_node/elisp/Prefix-Command-Arguments.html) for the next command, i.e. `counsel-file-jump` in this case:

```el
(defun my-counsel-file-jump ()
  "Forward to `counsel-file-jump' with non-nil prefix argument."
  (interactive)
  (setq current-prefix-arg '(4))
  (call-interactively #'counsel-file-jump))
```

This example unconditionally sets the prefix argument. If you want `my-counsel-file-jump` to reverse the sense of the prefix argument in `counsel-file-jump`, you can write:

```el
(defun my-counsel-file-jump (&optional arg)
  "Forward to `counsel-file-jump'.
When prefix ARG is nil, pass non-nil prefix argument to
`counsel-file-jump'.  Otherwise, pass nil prefix argument."
  (interactive "P")
  (setq current-prefix-arg (and (not arg) '(4)))
  (call-interactively #'counsel-file-jump))
```

You can then bind this command to a key of your liking, as outlined in [`(emacs) Init Rebinding`](https://www.gnu.org/software/emacs/manual/html_node/emacs/Init-Rebinding.html).

**Comment by dieggsy** [comment]
@basil-conto does it matter if `current-prefix-arg` is `setq`'d as opposed to lexically bound with `let` or something?

**Comment by basil-conto** [comment]
@dieggsy In my experience as a user it doesn't matter, but I know very little about the command loop, prefix arguments, etc. so there could very well be some subtle difference / edge case. Might be interesting to check with Emacs SE or emacs-devel if no-one else knows.

**Comment by hisnawi** [comment]
Thank you basil-conto

**Comment by basil-conto** [comment]
@dieggsy I recently rediscovered the section in the Elisp manual which made me prefer `setq` over `let` when dealing with events and the command loop. From [`(elisp) Command Loop Info`](https://www.gnu.org/software/emacs/manual/html_node/elisp/Command-Loop-Info.html):

```
We do not bind ‘this-command’ with ‘let’ because that would restore the
old value in case of error—a feature of ‘let’ which in this case does
precisely what we want to avoid.
```

Clearly this does not apply to `current-prefix-arg`, but the habit/convention has stuck with me and I think that's a good thing.
