### ISSUE TITLE
swiper lists raw lines of PDF file in pdf-view-mode

### ISSUE THREAD

**Issue by rekado** [abo-abo/swiper#1407]
When displaying a PDF with `pdf-view-mode` (comes with `pdf-tools`) swiper displays not the text in the PDF but the raw lines of the PDF source file.  `isearch-forward`, on the other hand, allows me to search the text.

**Comment by abo-abo** [comment]
It's not the real `isearch-forward`. Last time I checked, `pdf-view-mode` overrides `isearch-forward` to give you something similar. PDFs are binaries after all, and the real `isearch-forward` only knows about text.

Nothing can be done in `swiper` to fix this, I think. Maybe it could be a feature request in `pdf-view-mode`.  Even then it's unlikely to work well. For example, open a book in evince and search for a word: it may take a few seconds to get all the results. Ivy can handle this type of delay in a collection (e.g. `counsel-locate` will wait for `locate` to finish and display results as they come in), but it won't have the same feeling as `swiper`.

**Comment by abo-abo** [comment]
I'm closing this issue since there's nothing can be done on my side, as far as I see.

If any actionable info arises, feel free to open a new issue.
