### ISSUE TITLE
Add command to replace input with current candidate

### ISSUE THREAD

**Issue by rootzlevel** [abo-abo/swiper#141]
Especially when renaming things or creating new things with similar names to old things, it would be useful to have a binding like <kbd>RET</kbd> that selects the current candidate, but instead of immediately returning, replaces the input with the candidate.

That would allow to first select the candidate and then modify it slightly to produce a new one.

**Comment by abo-abo** [comment]
Another good idea, thanks.

**Comment by rootzlevel** [comment]
This works nicely for files and other type of input, but I just tried it the first time on directories.

Unfortunately, since the directory ends with a slash, ivy immediately changes into that directory making it impossible to edit its name.

**Comment by rootzlevel** [comment]
Uh, and it seems broken in `master`: It currently always changes the directory to `~` and only then inserts the current candidate.
