### ISSUE TITLE
how to bind a key to non-default command in ivy

### ISSUE THREAD

**Issue by plantarum** [abo-abo/swiper#1411]
Hi,

Ivy allows direct access to the default action via `<return>`, i.e., `ivy-done`. If I want a non-default action, I have to call `M-o` and select from the menu. Is there a way to add a shortcut to directly select an action other than the default? That is, I want `<return>` to give me the default action as usual, `C-<return>` to give me a secondary default, and `M-o` to pull up the menu of all actions.

Can this be done through user config, or would it require a change to the ivy code itself?

**Comment by mookid** [comment]
Related: #1347

**Comment by abo-abo** [comment]
> Can this be done through user config, or would it require a change to the ivy code itself?

You can user-configure it without too much hassle:

```elisp
(defun ivy-call-second-action ()
  (interactive)
  (ivy-exit-with-action
   (cadr (nth 1 (cdr (ivy-state-action ivy-last))))))

(define-key ivy-minibuffer-map (kbd "<C-return>") 'ivy-call-second-action)
```

The issue is that it's a bit of a cat-in-the-bag situation. For example, `ivy-switch-buffer` has 7 actions; I never remember their order myself, so I press <kbd>M-o</kbd>.

**Comment by plantarum** [comment]
I don't follow. The use case I have is for ivy-bibtex. In this case, there are 12 options, but 99% of the time I only use 2 of them. The default is open pdf, bound to <return>. The other option I use frequently is 'cite', which I access via `M-o c`. That's what I want to bind to `C-<return>`.

I don't understand the code you're using to select the action for `ivy-exit-with-action`. I think what it is actually doing is inserting the current ivy-selection prompt into the buffer, and not doing any of the 12 actions available for `ivy-bibtex`.

it does the same thing in ivy-switch-buffer - C-<ret> inserts the name of the selected buffer at point, rather than execute any action.

The key binding is easy now that you've shown me which map to modify. How do I define a function to call a specific action?

Thanks for your time!

**Comment by abo-abo** [comment]
@plantarum Did you solve your issue? Any info needed from my side?

**Comment by plantarum** [comment]
Huh. I tried your code when you posted it, and it wasn't working. I thought I'd need some time to dig into it. But when I tried it again just now, it worked as expected. So I guess my earlier problem was something I messed up in my experimenting.

Thanks!
