### ISSUE TITLE
swiper's equivalent to dired-isearch-filenames dwim

### ISSUE THREAD

**Issue by rhymer** [abo-abo/swiper#1415]
Dired has a nice feature: only search for file names (ignore file attributes) by setting 
`(setq dired-isearch-filenames 'dwim)`.
Does `swiper` has that? Thanks.

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by robklg** [comment]
I think this change broke swiper for me. I hadn't set dired-isearch-filenames and got this error:

swiper--candidates: Symbol’s value as variable is void: dired-isearch-filenames [3 times]

After setting it, swiper worked again.

**Comment by basil-conto** [comment]
@abo-abo @robklg Yes, see https://github.com/abo-abo/swiper/commit/ac856a0b8ca30c55422a58f9f079f36fb476e57f#r27056380.

**Comment by abo-abo** [comment]
Thanks, please check.
