### ISSUE TITLE
Losing colors on call to swiper

### ISSUE THREAD

**Issue by dieggsy** [abo-abo/swiper#1416]
Not exactly sure what's going on here, but an example using [helpful](https://github.com/wilfred/helpful) is:

- `M-x helpful-function RET swiper RET`
- `M-x swiper`

The original colors in the buffer are now lost. This also seems to happen to me with a custom eshell prompt theme, for example (which can be found [here](https://github.com/dieggsy/dotfiles/blob/master/emacs.d/lisp/egp.el) if needed)

**Comment by dieggsy** [comment]
@abo-abo thanks, that works.

**Comment by basil-conto** [comment]
@dieggsy Why not open a PR to extend `swiper-font-lock-exclude` with this mode?

**Comment by dieggsy** [comment]
@basil-conto been procrastinating on getting the copyright assignment a while and think i need it at this point. good idea though.

If anyone wants to incorporate them before I get to it, it's `helpful-mode` and and `eshell-mode`.

**Comment by abo-abo** [comment]
Thanks.

**Comment by dieggsy** [comment]
@abo-abo  thank you!
