### ISSUE TITLE
Switch between fuzzy and non-fuzzy on the fly [Feature request]

### ISSUE THREAD

**Issue by kaushalmodi** [abo-abo/swiper#142]
It would be awesome to switch between fuzzy and non-fuzzy search modes on the fly. The echo area can show some indicator to let the user know if the search is happening in fuzzy mode.

**Comment by abo-abo** [comment]
Please try out the new hydra if you haven't yet. I'd like some feedback.

**Comment by wudixiaotie** [comment]
How to make fuzzy matcher as default? Everytime I search with Key <kbd>C</kbd>-<kbd>s</kbd>, I have to toggle to fuzzy matcher use key <kbd>C</kbd>-<kbd>o</kbd> <kbd>m</kbd>.
