### ISSUE TITLE
counsel-org-goto fails in the presence of empty headings

### ISSUE THREAD

**Issue by drquicksilver** [abo-abo/swiper#1422]
I've just installed ivy/counsel/swiper for the first time (version 0.10.0 from ELPA, using emacs 25.3.1)

Trying to use `counsel-org-goto` on my regular org files which are quite large (2-4 megabytes, tens of thousands of lines, thousands of org headings) just gives an error:

```
counsel-org-goto--add-face: Wrong type argument: stringp, nil
```

However opening rather small org files I have lying around which contain simple documents, presentations or whatever and it works perfectly. I haven't made any attempt to work out what property of the big files causes the issue but I'm very happy to do some digging if someone can point me towards what it might or might not be.

**Comment by basil-conto** [comment]
Can you please type <kbd>M-x</kbd>`toggle-debug-on-error`<kbd>RET</kbd> before the error occurs, and post the resulting error backtrace?

**Comment by drquicksilver** [comment]
```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  propertize(nil face minibuffer-prompt)
  counsel-org-goto--add-face(nil 2)
  counsel-org-goto--get-headlines()
  counsel-org-goto()
  funcall-interactively(counsel-org-goto)
  call-interactively(counsel-org-goto record nil)
  command-execute(counsel-org-goto record)
  #[257 "\304\305!\203\f\306\307!!\210\307!\211\310\307!\311\")\207" [current-prefix-arg prefix-arg this-command real-this-command featurep smex smex-rank intern command-execute record] 4 "\n\n(fn CMD)"]("counsel-org-goto")
  ivy-call()
  ivy-read("M-x " [:ARCHIVE_TIME org-table-export-default-format cperl-max-help-size shen-mode counsel--linux-apps-cached-files cperl-unreadable-ok caption-str debugger-previous-window lm-section-mark eieio-class-speedbar-menu org-lookup-all cperl-fix-line-spacing cperl-font-lock-fontify-region-function dired-kill-tree rcirc-menu orgtbl-ret :new cperl-inside-parens-p image-code org-rematch-and-replace org-table-current-line-types org-latex-image-default-option :texinfo-inactive-timestamp-format :filter-line-break horz epos ftnchek org-texinfo-line-break :mode org-latex-default-figure-position default-entry --cl-block-ivy-state-dynamic-collection-- to-dir org-texinfo-inline-src-block org-export-collect-tables cperl-facemenu-add-face-function :sitemap-filename op1 *orgtbl-llfmt* validation-link insertpos odir caml dired-read-shell-command isback Imenu with-latex-p ivy-recompute-index-zero org-html-superscript expert-prompt ...] :predicate commandp :require-match t :history counsel-M-x-history :action #[257 "\304\305!\203\f\306\307!!\210\307!\211\310\307!\311\")\207" [current-prefix-arg prefix-arg this-command real-this-command featurep smex smex-rank intern command-execute record] 4 "\n\n(fn CMD)"] :sort t :keymap (keymap (67108908 . counsel--info-lookup-symbol) (67108910 . counsel-find-symbol)) :initial-input nil :caller counsel-M-x)
  counsel-M-x()
  funcall-interactively(counsel-M-x)
  call-interactively(counsel-M-x nil nil)
  command-execute(counsel-M-x)
```

**Comment by drquicksilver** [comment]
Managed to reproduce it. It's caused by empty headings. Here is a small example which consistently errors for me:

```
* a
* 
* b
```

Hope that helps!

**Comment by fabacino** [comment]
I was not able to reproduce the issue with `make plain` and the org content mentioned above. The empty headings were passed as empty strings, not `nil`, into `counsel-org-goto--add-face`, which does not trigger any error.

@drquicksilver Can you reproduce the problem with `make plain` as well?

**Comment by drquicksilver** [comment]
I will try `make plain` later when I have some time but quick note - the space after the asterisk is required to provoke the error. `*` on a line doesn't provoke it but `*<SPC>` does.

**Comment by basil-conto** [comment]
@drquicksilver @fabacino It may also be useful to establish which Org version everyone is using, given the package's propensity to breaking API changes.

I, for example, cannot reproduce the error with `make plain` and `Org mode version 9.1.6 (9.1.6-33-g5b4a71-elpa @ /home/blc/.emacs.d/elpa/org-20180129/)`.

I have tried reproducing with the following buffer contents:

```
* foo
*
*\s
*\s\s
* bar
```

where `\s` stands for a space character as per Elisp syntax.

**Comment by fabacino** [comment]
I was using `Org mode version 9.1.3 (9.1.3-10-gadfbfd-elpa @ ~/.emacs.d/elpa/org-20171127/)`.

**Comment by drquicksilver** [comment]
I appear to be using the ancient 8.2.10 which comes with emacs 25.1.

I'll install a more recent org-mode and report back.

**Comment by drquicksilver** [comment]
I can confirm that with org-mode 9.1.6 I no longer see this error.

**Comment by basil-conto** [comment]
@drquicksilver Thanks for checking. You'll probably be better suited by newer Org versions in general, but as long as `counsel` supports Emacs versions as far back as 24 then it also ought to support Org versions as far back as 8.2.10, which which Emacs 24 shipped.
