### ISSUE TITLE
cannot open load file: ivy-hydra

### ISSUE THREAD

**Issue by bixuanzju** [abo-abo/swiper#143]
Seems `ivy-hydra.el` is not included in the `swiper` package? Any way I can install it from `melpa`?

**Comment by abo-abo** [comment]
You're right. I've sent a PR to MELPA to add this file.

**Comment by abo-abo** [comment]
Just to confirm, you got this error by pressing <kbd>C-o</kbd>, not doing general stuff?

**Comment by bixuanzju** [comment]
Yes! Now I can call `ivy-hydra` by pressing `C-o`.

**Comment by CsBigDataHub** [comment]
have the same issue even when I do M-x hydra-ivy

**Comment by abo-abo** [comment]
@CsBigDataHub The package is on MELPA: https://melpa.org/#/ivy-hydra
