### ISSUE TITLE
Could the ivy-read action depends on different keyblindings ?

### ISSUE THREAD

**Issue by LuhengStat** [abo-abo/swiper#1430]
I am using ivy-read to write an elsp function, and I came up with an idea that:
could the action parameter in ivy-read vary depends on our keyboard input. 
Such as in most situations we just enter "enter" and the ivy-read do an action,
I am wonder could we try to enter "C-enter" to do another action.
Since in some times, I use the swiper to find a file and want to do another action 
with the searched result. 

Now I must write two functions  to achieve this feature. I think with this feature I 
just need to write one function and use different keyblindings to do different actions.

I hope the description is clear. Thanks.

**Comment by abo-abo** [comment]
This is already solved by the multiple-action interface with key binding <kbd>M-o</kbd>. For example, using `ivy-switch-buffer`: <kbd>M-o j</kbd> will open the buffer in another window instead of the current one. See `doc/ivy.org` for more info.

**Comment by LuhengStat** [comment]
Thanks. I see.

**Comment by abo-abo** [comment]
There's a simple example in the manual: https://github.com/abo-abo/swiper/blob/master/doc/ivy.org#how-to-add-actions-to-a-specific-command.

You can also browse the `ivy-set-actions` statements in the source code.

You already have <kbd>M-o i</kbd> and <kbd>M-o w</kbd> for all `ivy-read` commands.

**Comment by LuhengStat** [comment]
Thanks. Best.
