### ISSUE TITLE
swiper-query-replace: unable to replace first match in buffer

### ISSUE THREAD

**Issue by zhaojiangbin** [abo-abo/swiper#144]
To reproduce:

1. In scratch buffer, enter a few lines of text containing a same word, say "foo".
2. Call `swiper`, input "foo" as pattern. Press `C-M-<` to select the first match.
3. Press `M-q` for query-replace.
4. Enter "bar" as replacement.
5. Hit `RET`. Notice the cursor moves to the second match and query-replace starts there, ignoring the first match.

It appears to be caused by that ivy places the cursor at the end of current match in buffer. When query-replace starts, it can only "look forward" for the match to replace. This has the consequence that `swiper-query-replace` is never able to replace the first match (or the only match) in buffer.

Verified with MELPA version 20150610.638 in Emacs 24.5.

**Comment by abo-abo** [comment]
Thanks.
