### ISSUE TITLE
Windows quote issue with sed in counsel-cmd-to-dired

### ISSUE THREAD

**Issue by glucas** [abo-abo/swiper#1441]
While trying out `counsel-find-file-occur` on Windows I was getting this error:

    sed: -e expression #1, char 0: no previous regular expression

After debugging a bit, the problem is with `counsel-cmd-to-dired` and its use of `sed`. If I replace the single quotes with escaped double-quotes then things work as expected:

            (full-cmd (format "%s %s | sed -e \"s/^/  /\""

Perhaps this is something that can be made platform-specific.

**Comment by glucas** [comment]
Ah, I also had to tweak the xargs delimiter in `counsel-find-file-occur` to get it working:

    (format "ls | grep -i -E '%s' | xargs -d '\\n' ls"

**Comment by abo-abo** [comment]
Thanks for the pointers. Your changes work for me on Linux. Let me know if this change fixes your issue.

**Comment by glucas** [comment]
Yes, the changes work for me. Thanks!
