### ISSUE TITLE
fallback for counsel-yank-pop in minibuffer

### ISSUE THREAD

**Issue by a13** [abo-abo/swiper#1444]
Calling `counsel-yank-pop` shortcut in minibuffer gives "ivy-read: Command attempted to use minibuffer while in minibuffer" error, I think we should check for 
 `(window-minibuffer-p)` and fallback to `(call-interactively #'yank-pop)` in that case.

**Comment by basil-conto** [comment]
Thanks, this has bugged me as well, because `enable-recursive-minibuffers` doesn't seem change anything. I'll look into it later today.

**Comment by basil-conto** [comment]
Ha, I thought I had `enable-recursive-minibuffers` enabled globally because `counsel-describe-variable` enables it. Enabling the setting fixes this issue.

**Comment by a13** [comment]
Hmm, I thought mine was set to t too :), thanks again!
