### ISSUE TITLE
First time TRAMP completion

### ISSUE THREAD

**Issue by rootzlevel** [abo-abo/swiper#145]
In a fresh emacs, where I haven't had any TRAMP connections open, remote file-name completion (and host-names and methods) doesn't work until I open at least one file or directory in tramp.

The same is true for `emacs -Q`, it also doesn't complete methods or host names the first time, BUT I can get filename completion by typing `ssh:host:./<TAB>` (the `./` is important, without it, it doesn't work).

Requiring TRAMP first seems to fix it (and also immediately provides completion for host names and methods), but I'd rather have it lazily loaded, like regular `find-file` seems to do it.

**Comment by abo-abo** [comment]
Thanks. Let me know if there's still some annoying stuff left.

**Comment by rootzlevel** [comment]
Ok, that didn't change anything for me and after digging into the code, I'm confused what the logic in `ivy-alt-done` should do anyway.

- The tramp specific cond branch `(string-match ...` never matched for me, since `ivy-text` does not start with a slash. Entering `/ssh:hpd@remote:` <kbd>C-j</kbd> calls `ivy-alt-done` with `ivy-text` being `ssh:hpd@remote:`.

- This `cond` condition also doesn't test `ivy-directory` and thus matches in every other completion (which may not be intended, but gave me a way to try it out).

- Entering `/ssh:hpd@remote:` <kbd>C-j</kbd> in some non-filename ivy prompt gives me a list of hostnames, even though I have already typed that hostname in.

Here is the default behaviour in emacs: On first startup, you don't get tramp completion until you enter the first colon. After that, methods and hostnames are completed, but `/hostname:` <kbd>TAB</kbd> doesn't complete files, yet. Only after you enter the first slash after the hostname. So you can get completion for the home directory by typing `./` <kbd>TAB</kbd>.

In `ivy`, without requiring TRAMP, I was unable to get completion at all. Typing a remote file name and <kbd>C-j</kbd> always directly finds that file.

When I require tramp first, I get method completion for `/`, which is useless because typing <kbd>C-j</kbd> on a method results in the message `byte-code: Host name must not match method "scp"`. Nothing else works, except curiously for typing *exactly* `/remote:`<kbd>C-j</kbd>. This defaults to ssh as method and my current login as username and shows me completions for files in the home directory on the remote computer.

**Comment by abo-abo** [comment]
> Entering /ssh:hpd@remote: C-j calls ivy-alt-done with ivy-text being ssh:hpd@remote:

You're entering `//ssh:hpd@remote: C-j`, aren't you? The intent is to enter `/ssh:hpd@remote: C-j`, without having `//` switch to the root directory.

**Comment by abo-abo** [comment]
> Here is the default behaviour in emacs: On first startup, you don't get tramp completion until you enter the first colon. After that, methods and hostnames are completed, but /hostname: TAB doesn't complete files, yet. Only after you enter the first slash after the hostname. So you can get completion for the home directory by typing ./ TAB.

Here's how I do it, without requiring tramp:

1. <kbd>C-x C-f</kbd> `/ssh:` <kbd>C-j</kbd>: I get the completion list of my remote history. Some of them already with a username.
2. I select a remote host and immediately get the directory listing for the home directory on the remote host.

That's all there is to it. It's also possible to <kbd>C-x C-f</kbd> `/ssh:oleh@` <kbd>C-j</kbd> to have the user fixed, but choose host.

**Comment by rootzlevel** [comment]
Ah, I see. I did in fact never try to input a single slash, because in my intuition, a tramp file name starts with a / (and not with `/some/directory//`).

This works very well (after enabling recursive minibuffers), but IMHO doesn't blend in with the rest of the interface. (For example, typing `/ssh:startofname` <kbd>C-j</kbd> throws away `startofname`, typing `/ssh:wholeservername:file` <kbd>C-j</kbd> also shows the host completion). Also, I usually don't even use the method part in tramp filenames, because ssh is the default anyway. So I really would like to just have to type `/remote:`<kbd>C-j</kbd> to get completion for my files. (Currently this does indeed work with requiring tramp first and typing `//remote:`<kbd>C-j</kbd>).

**Comment by abo-abo** [comment]
> Ah, I see. I did in fact never try to input a single slash, because in my intuition, a tramp file name starts with a / (and not with /some/directory//).

This was the case before, but since `//` is a destructive operation (brings you to root, you can't go back), I opted for `/ssh:` instead of `//ssh:`.

> This works very well (after enabling recursive minibuffers)

You mean it doesn't work if the user hasn't enabled recursive minibuffers?

> For example, typing /ssh:startofname C-j throws away startofname

Fixed.

> typing /ssh:wholeservername:file C-j also shows the host completion

I don't know if a user should go that far without completion. But I'll try to add a work-around anyway.

**Comment by rootzlevel** [comment]
> You mean it doesn't work if the user hasn't enabled recursive minibuffers?

Yes, I need to set `enable-recursive-minibuffers` to `t` for the hostname completion to work.

> I don't know if a user should go that far without completion. But I'll try to add a work-around anyway.

I think, completion should support the user whenever he needs it and in whatever state it is in. Muscle memory and fast typing can mean that it's sometimes easier to type things out than to complete. Especially when the completion has to be initiated manually and requires a context switch (such as <kbd>C-j</kbd> after the method name).

Btw, thanks again for your work. Ivy has never made me want to go back to helm, so far.

**Comment by abo-abo** [comment]
> Btw, thanks again for your work. Ivy has never made me want to go back to helm, so far.

Thanks to you too. Most of the improvements here are done through user feedback.  Just keep it coming, preferably in many small tractable improvements, rather than few large requests :)

**Comment by Ergus** [comment]
Hi:
I'm having more or less the same issue than here:
```
C-x C-f /ssh: 
```
Doesn't list anything most of the time. (I tried with ido and it is working fine). Maybe it has to do with the fact that I have TAB bind to ivy partial?
When I try C-j or TAB I only get a message:
```
ivy--directory-done: Args out of range: "", 0, 3
```
My ivy config actually is:
```
(use-package ivy :ensure t
  :diminish
  :demand
  :bind (("C-c i r" . ivy-resume)
		 :map ivy-minibuffer-map
			  ("TAB" . ivy-partial))
  :config
  (setq ivy-use-virtual-buffers t
		ivy-count-format "(%d/%d) "
		ivy-display-style 'fancy
		enable-recursive-minibuffers t)
  (ivy-mode t)

  (use-package ivy-rich :ensure t
	:config
	(ivy-rich-mode 1))

  (use-package swiper :ensure t
	:bind (("C-s" . swiper)
		   ("C-r" . swiper)
		   :map minibuffer-local-map ("C-r" . counsel-minibuffer-history)
		   :map read-expression-map ("C-r" . counsel-expression-history))))
```

**Comment by Ergus** [comment]
In some cases the completion works and not in others (specially in the beginning). Also when there are alias in the ~/.ssh/config that allows to connect using alias like /ssh:myserver: then the access there is only to the home directory. Putting a (message ...) inside counsel--find-file shows that the variable ivy-text is empty there in those cases. So there is a previous command filtering this. In other cases i tried something simpler like /ssh:myserver:/var (not expecting for completion) and ivy-text in those cases was "/var" only and it was completting with my local and not the remote /var content.
 
Related to this I see that the package counsel-tramp [https://github.com/masasam/emacs-counsel-tramp](url) pretty much does the completion work and the function counsel-tramp--candidates does all the completion work. But the point with this is to avoid the artificial call to counsel-tramp command (and/or require an extra keybind for it) instead of the default counsel-find-file to connect to tramp. Which fits better in the emacs workflow.

.
