### ISSUE TITLE
Setting require-match to nil in org-agenda-filter-by-tag

### ISSUE THREAD

**Issue by nixmaniack** [abo-abo/swiper#1454]
I wanted to select a tag which wasn't in the list but swiper/ivy complains about `match required`. How do I set `require-match` to `nil` when using `org-agenda-filter-by-tag`?

**Comment by abo-abo** [comment]
There's no way to do it: `org-agenda-filter-by-tag` specifically passes `require-match=t` to `completing-read`. If you want to change this for some reason, open a new ticket for Org-mode.

**Comment by nixmaniack** [comment]
Thanks for the clarification. 
Opening a ticket on org-mode isn't as simple as opening an issue on gitub I guess, I'll check on that.
