### ISSUE TITLE
ivy-initial-inputs-alist

### ISSUE THREAD

**Issue by mwfogleman** [abo-abo/swiper#1455]
AFAICT, by default, ivy prefixes "^" in many commands, and that this is configured in the ivy-initial-inputs-alist variable. I don't like this default behavior, and have configured ivy-initial-inputs-alist to be set to ```'()```. 

However, ivy still seems to prefix things a lot of the time with "^". Sometimes it does and sometimes it doesn't - I can't seem to make sense of it.

I would like to override this by default and am not sure if I'm configuring it in the wrong place or if there's a larger issue. :)

**Comment by basil-conto** [comment]
Setting `ivy-initial-inputs-alist` to `()` should suffice in removing the initially input `^` from all commands. I you can provide a reproducible recipe where this is not the case, then that would count as a bug.

**Comment by mwfogleman** [comment]
How do I create a reproducible recipe?

**Comment by basil-conto** [comment]
> How do I create a reproducible recipe?

This project includes a brief description in [CONTRIBUTING.org](https://github.com/abo-abo/swiper/blob/master/CONTRIBUTING.org#reporting-issues), but I think Sebastian Wiesner's writeup at https://swsnr.de/posts/reproduce-bugs-in-emacs-q may be a bit more helpful in general.

Basically, start Emacs without any of your configurations, e.g. via `emacs -Q` or by running `make plain` in a checkout of this repository, load Ivy, then evaluate

<kbd>M-:</kbd>`(setq ivy-initial-inputs-alist ())`<kbd>RET</kbd>

or some moral equivalent thereof (e.g. by using the `counsel-set-variable` command).

If you can find a command which adds `^` as an initial input despite the above configuration, then please report back with it.

If you can't find such a command, try experimenting with your setup (loading different files, running `package-initialize`, omitting the `-Q` flag, etc.) until you do. For example, it may turn out that you have another package installed which modifes `ivy-initial-inputs-alist` or something like that.

**Comment by basil-conto** [comment]
Long story short,

> However, ivy still seems to prefix things a lot of the time with "^". Sometimes it does and sometimes it doesn't - I can't seem to make sense of it.

gives this project's maintainers very little to go on, given that setting `ivy-initial-inputs-alist` seems to work fine for most people.

**Comment by nv2p** [comment]
I don't know if it's worth reopening, but it seems the issue wasn't solved and I may know why. I use `use-package` and counsel is set to be `:after ivy` (both with `:defer 1`). I noticed that when I `(setq ivy-initial-inputs-alist nil)` in my ivy `:config`, as soon as I call `counsel-M-x`, the value change. Same if I put it somewhere in my init.el or even in counsel `:custom`. Counsel actually seems to change the value of `ivy-initial-inputs-alist `, adding several "counsel-..." to the original value, which state become "CHANGED outside Customize". So my guess is that this erase previous customizations.

Maybe there is a way to recognize such customizations and not change them? And if not, a mention about this in the documentation would be nice. I'm alright now, but it's a bit confusing (the variable being the same for all and called "**ivy**-initial-inputs-alist") and it took me time to find out, so I wanted at least to share.

**Comment by basil-conto** [comment]
@nv2p That sounds like #2328 and #2442.

**Comment by nv2p** [comment]
@basil-conto I have to admit I didn't see those... It's exactly this. I actually solved the problem the same way [zdm0](https://github.com/abo-abo/swiper/issues/2442#issuecomment-583499321) did.
