### ISSUE TITLE
ivy-hydra: dismiss the hydra without exiting ivy

### ISSUE THREAD

**Issue by zhaojiangbin** [abo-abo/swiper#146]
Once activated, the hydra heads can obstruct editing the pattern when needed. The current exit heads, and `C-g`, also exit ivy completely.

**Comment by abo-abo** [comment]
What's the problem here? Doesn't <kbd>i</kbd> do that?

**Comment by zhaojiangbin** [comment]
It does. I was misled by the hint "insert" in the docstring. I thought that <kbd>i</kbd> is mapped to `ivy-insert-current`.

Closing the issue.

**Comment by abo-abo** [comment]
> I was misled by the hint "insert" in the docstring

I was going along the lines of Vim's normal/insert mode. But only because I really like the position of <kbd>i</kbd> and <kbd>o</kbd> keys for canceling.

**Comment by zhaojiangbin** [comment]
This now makes sense. It might deserve mentioned in the forthcoming release notes. :)

I have used Vim for many years and I still do. I like these keys once I know their functions.
