### ISSUE TITLE
C-c C-o ivy-occur doesn't show the same result for counsel-projectile-rg

### ISSUE THREAD

**Issue by kirill-gerasimenko** [abo-abo/swiper#1462]
Hi,

Steps to reproduce:
- make sure you are in the project and it has same word in files with different extensions
- invoke `cousel-projectile-rg` with prefix argument (C-u) 
- enter there additional glob filter to search in particular type of files (like I have in the attached gif: `-g "*.cs"`), hit enter to get to the search itself
- enter the word 

The search will correctly find in files with extension you specified in previous step, but if you do `C-c C-o` - the buffer will have different found items (seems like search was happening without additional glob filter). 

![ivy-occur-filter-not-working](https://user-images.githubusercontent.com/3036330/36355984-b7a1ed60-14eb-11e8-823f-3f46d1b55c49.gif)

I'm not sure if this is related to `ivy-occur` or `counsel-projectile-rg`.

I'm on Windows 10, Emacs: 0.300.0@26.0.90 (spacemacs).

If you need more information I'll be happy to provide it.

Thanks!

**Comment by abo-abo** [comment]
Please reopen the issue in https://github.com/ericdanan/counsel-projectile.
That's where `counsel-projectile-rg` is defined.

**Comment by kirill-gerasimenko** [comment]
Will do that, thanks!
