### ISSUE TITLE
counsel-git-grep does not work with tramp

### ISSUE THREAD

**Issue by proofit404** [abo-abo/swiper#1463]
Hi, I saw two opened issues on the same topic. Each of them has slightly different conditions and error messages. So I decide to report it as a separate issue. On the remote host, `counsel-git-grep` fails with following message:

    fatal: Not a git repository (or any of the parent directories): .git

But I can confirm that git itself is fully operational on this host. `magit` for example works without any problems.

Initially reported at https://github.com/ericdanan/counsel-projectile/issues/79

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by proofit404** [comment]
Hi, thanks for quick reply!

I have different errors now:

The first time I run `M-x counsel-git-grep RET`

    2    git grep: test_

    1 chars more

The second time I run it

    No buffer named  *counsel-gg-count*

without showing the prompt.

**Comment by abo-abo** [comment]
Can't reproduce. Works fine for me when connecting from Ubuntu 16 to Ubuntu 16 over TRAMP/ssh.

**Comment by proofit404** [comment]
I tested it with `docker-tramp` and localhost.

**Comment by abo-abo** [comment]
I'm not familiar with `docker-tramp`. Could you please outline a series of steps for me to install, configure it, and reproduce the bug?
