### ISSUE TITLE
counsel-find-file issue

### ISSUE THREAD

**Issue by matthewa150** [abo-abo/swiper#1466]
Updated my packages earlier today to find that `counsel-find-file` was no longer working. When I run it, after typing the first character (doesn't matter the char) it throws an error and the autocomplete for it breaks:
```Error in post-command-hook (ivy--exhibit): (wrong-type-argument stringp (("D" . t)))```

If needed I can dump a list of my layers and what not.

![hmmm](https://user-images.githubusercontent.com/15635573/36408576-dccb4dc6-15cb-11e8-8174-4b330a7396c2.gif)

**Comment by habamax** [comment]
I have slightly different error message:

    Error in post-command-hook (ivy--queue-exhibit): (wrong-type-argument stringp (("a" . t)))

First letter I try to input is in `stringp (("a" . t))` -- here it was 'a'.

After reopening `counsel-find-file` and pressing D:

    Error in post-command-hook (ivy--queue-exhibit): (wrong-type-argument stringp (("D" . t)))

PS
I have deleted all ivy/counsel/swiper stuff and reinstalled from melpa -- the same errors.

**Comment by abo-abo** [comment]
Can't reproduce with `make plain`. What's your Ivy config?

**Comment by abo-abo** [comment]
OK, I assume this config is relevant:

```elisp
(setq ivy-re-builders-alist
      '((t . ivy--regex-ignore-order)))
```

The other two re-builders seem to work fine.

**Comment by Atman50** [comment]
Yes that fixes the problem. Thanks! Any idea how to fix the issue? I like the unordered regexp

**Comment by matthewa150** [comment]
I added the `ivy--regex-ignore-order` and I don't think it did anything. As for my config it believe it is just the standard ivy install (though I am using the standard `dotspacemacs-distribution` if that changes anything`

I also noticed today that my swiper is giving my problems as well:

`swiper--add-overlays: Symbol’s function definition is void: ivy--case-fold-p`

Not sure if these two issues are related

**Comment by basil-conto** [comment]
@Atman50 @matthewa150 I think there's been a misunderstanding.

I'm pretty sure @abo-abo is saying that `ivy--regex-ignore-order` is the **culprit**, not the **fix**.

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by Atman50** [comment]
Yes I understood. Removing the ivy--regex-ignore-order from my
configuration fixes the problem.
I would like to get the capability back however.

**Comment by matthewa150** [comment]
@basil-conto @abo-abo Yeah... classic me, was a misunderstanding - I disabled it and everything seems to be working fine now, thanks for the help!

**Comment by matthewa150** [comment]
Well - I just noticed that disabling the `ivy--regex-ignore-order` seemed to cause my swiper to break. 
```Error in post-command-hook (ivy--queue-exhibit): (void-function nil)```
After some messing around I found that disabling the `spacemacs-completion` layer makes both the swiper and `counsel-find-file` work

**Comment by tsmithe** [comment]
Hi, I think I have encountered this issue when trying to use `ebib` with `counsel-find-file`. I have a very basic ebib config:

```
(use-package ebib
  :config
  ((global-set-key (kbd "C-c e") 'ebib)
   ))
```

but earlier in my config I also have

```
  (setq ivy-re-builders-alist
        '((ivy-bibtex . ivy--regex-ignore-order)
          (t . ivy--regex-plus)))
```

Can you help?
