### ISSUE TITLE
wgrep doesn't work in ivy-occur-grep-mode if the original line contains tabs

### ISSUE THREAD

**Issue by lbsx** [abo-abo/swiper#1468]
Sample file:

```
\tabc
```

Steps:

1. Call `swiper`
2. Type abc
3. Call `ivy-occur`
4. Call `ivy-wgrep-change-to-wgrep-mode`
5. Make some modification to the line
6. Call `wgrep-finish-edit`

Result:

The modification is not applied to the buffer.

I looked into the code and found in `swiper--line`, tabs are replaced with whitespaces. wgrep would complain "Buffer was changed after grep." in `wgrep-apply-change`.

I tried to remove the tab replacing code and wgrep works.

**Comment by lbsx** [comment]
Is this a problem, or do I miss something?

**Comment by abo-abo** [comment]
Thanks.
