### ISSUE TITLE
Ivy Action To create Directory

### ISSUE THREAD

**Issue by profhase** [abo-abo/swiper#1471]
Coming from ido I am quite used to search for file and if I need a directory in place press `M-m` which would create a directory inside the directory I am in.
What I have found so far is to enter the dired mode and create a directory from there.
Is there any on-the-fly action for that?

Thanks a lot (also for the great library)

**Comment by abo-abo** [comment]
Thanks. I was using <kbd>+</kbd> from `dired` until now. I just added <kbd>M-o d</kbd> to do it from `counsel-find-file`.
