### ISSUE TITLE
insert/copy from counsel-rg without filename/line number

### ISSUE THREAD

**Issue by aaronjensen** [abo-abo/swiper#1472]
Hi, I often search for a line of code I want to paste into another file using counsel-rg. Once I find it, I either `M-o w` or `M-o i`, but it inserts the file name and line number along w/ the line. Is there a way to control that so that it only inserts the matched text? Thanks!

**Comment by aaronjensen** [comment]
I just realized that these may be custom actions I added, oops. If that's the case then you can disregard this, or consider it a feature request to make these built-in as they're useful 😄 

```
  ;; Add i and w to ivy actions to insert/copy the selection
  (ivy-set-actions
   t
   '(("i" aj/ivy-insert "insert")
     ("w" aj/ivy-kill-new "copy")))
  (defun aj/ivy-insert (x)
    (insert
     (if (stringp x)
         x
       (car x))))
  (defun aj/ivy-kill-new (x)
    (kill-new
     (if (stringp x)
         x
       (car x))))
```

**Comment by abo-abo** [comment]
These actions are already used by default, see the code of ivy.el.

**Comment by aaronjensen** [comment]
Oh, not sure how I missed that, thanks!

I'm trying out stripping the line number/file name using:

```
  (defun aj/ivy-strip-file-and-line-number (str)
    (substring-no-properties
     (if-let* ((start (text-property-any 0 (length str) 'face 'compilation-line-number str))
               (end (text-property-not-all start (length str) 'face 'compilation-line-number str)))
         (substring str (+ end 1))
       str)))
  (defun aj/ivy-insert (x)
    (message "%S" x)
    (insert
     (aj/ivy-strip-file-and-line-number
      (if (stringp x)
          x
        (car x)))))
  (defun aj/ivy-kill-new (x)
    (kill-new
     (aj/ivy-strip-file-and-line-number
      (if (stringp x)
          x
        (car x)))))
```

Do you think that's something that you'd want built in to ivy?

**Comment by abo-abo** [comment]
What's the use case of having the line number? Line numbers in Emacs aren't as valuable as e.g. in Vim, since you have `compile` which makes line numbers into links that you can follow, instead of copying the numbers and moving manually.

**Comment by aaronjensen** [comment]
this strips out the line number from counsel-rg so when you insert or copy you just get the text w/o the 

`filename:35:`

**Comment by aaronjensen** [comment]
I'm running out the door, but if that didn't make sense I'd be happy to clarify later w/ some examples/screenshots.

**Comment by abo-abo** [comment]
Please clarify later when you get some time, no rush :)

**Comment by aaronjensen** [comment]
Normally, when using `M-o i`, the entire line from ivy is inserted. In the case of `counsel-rg`, this line includes the file name and line number. For example:

```elisp
custom.el:33: '(ivy-highlight-face ((t (:foreground "#A1EFE4"))))
```

I pretty much never am interested in the file name/line number, so I tend to manually delete it so it looks like:

```elisp
 '(ivy-highlight-face ((t (:foreground "#A1EFE4"))))
```

The same applies to `M-o w`, I typically want to copy the line w/o the file and line number.

The above function and its usage automatically remove the file name and line number (though they currently assume there's a line number, so it wouldn't remove just a file name). This works well for me and I was wondering if it'd be a good addition to ivy.

Here's an example of me using it:

![insert](https://user-images.githubusercontent.com/8588/36575095-d5e24b48-17fd-11e8-84a6-d47515c30c48.gif)

I hope that helps make it more clear, if not I'd be happy to elaborate. Thanks!

**Comment by basil-conto** [comment]
I can't comment on the inclusion of such a function (not my place, and also running out of the door), but IMO the inclusion of the file name and line number in the final candidate is ultimately a bug with `counsel-rg`. Other commands use filter functions to display pretty results during completion without modifying the candidate strings themselves.

**Comment by mookid** [comment]
@basil-conto I think it is debatable, as knowing in which file the match is actually a useful info in most of my use cases. So I think that this should be a feature rather than modifying the current behavior of counsel-rg.

**Comment by basil-conto** [comment]
@mookid I am not advocating the removal of the file and line number during completion, rather that they shouldn't be a physical part of the completion string. Are you saying they should be a physical part of the string? When would that be useful?

**Comment by aaronjensen** [comment]
I didn't know this was a thing--that does sound like the proper way to handle this assuming that upon `C-c C-o` the file name/line number would carry over to the occur buffer.

**Comment by mookid** [comment]
@basil-conto I misunderstood what you said. I only advocate for displaying the file location during completion.

**Comment by basil-conto** [comment]
@aaronjensen Yeah, that's the only aspect not currently supported I think, which is why I don't think it should block this issue.

**Comment by guibor** [comment]
Hi! I was wondering if there are there any plans to fix this? Perhaps a flag that determines whether insert/copy also applies to the line number and file name (itfeels a bit counter intuitive that this is the default)

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by aaronjensen** [comment]
This works well with rg for me, thank you!

**Comment by guibor** [comment]
Works great, thanks!!
