### ISSUE TITLE
Virtual buffers have higher priority than live buffers

### ISSUE THREAD

**Issue by fabacino** [abo-abo/swiper#1473]
Steps to reproduce:

* Open any virtual buffer with name X (not currently open)
* Open a new buffer Y at a different location but with the same name as X
* Kill buffer X
* Switch to buffer Y

Instead of switching to buffer Y, virtual buffer X gets openend again.

I think the bug was introduced with commit 37c69bcca76a73eb81ed88616ddf2dc0b0a3d2ad.
If I revert that commit, everything works as expected.

Please let me know if you need a more detailed reproducing scenario with `make plain`.

**Comment by abo-abo** [comment]
Thanks, I wasn't sure about 37c69bc when I added it, I'll just revert.

**Comment by ejmg** [comment]
Pretty sure this is my issue, too. Updating now, thanks for the quick work :slightly_smiling_face:
