### ISSUE TITLE
Error in post-command-hook (icomplete-post-command-hook): 

### ISSUE THREAD

**Issue by Davidbrcz** [abo-abo/swiper#148]
Hi.

I've been facing a bug when using ivy-swiper (which is great btw). When I try to open a file, I (sometime), get the following error 

```Error in post-command-hook (icomplete-post-command-hook): (invalid-function (#("scalability.tex" 0 15 (face completions-common-part dirp nil))))``` 

where scalability.tex is the file's name I'm trying to open.  The error is triggered when I''m pressing TAB to complete the file's name. The name is completed anyway.

This append with both ELPA and git version. 

David.

**Comment by abo-abo** [comment]
You need to disable `icomplete-mode` when you have `ivy-mode` on. You can have either one or the other, not both.
Somewhere in your config, you must have:

```
(icomplete-mode 1)
```

**Comment by Davidbrcz** [comment]
Indeed, my bad =/
