### ISSUE TITLE
automatically toggle input methods in swiper

### ISSUE THREAD

**Issue by capfredf** [abo-abo/swiper#1480]
[Racket-mode](https://github.com/greghendershott/racket-mode) provides an input method that facilitates typing greek symbols. For instance, typing "lambda" followed by the space key changes "lambda" into λ .  

But the input method appears turned off when I do search in swiper. 

Is there any decent way / hook to toggle input methods when swiper is used along with some major mode like racket-mode?

**Comment by abo-abo** [comment]
You mean it inserts an actual unicode λ?

**Comment by dieggsy** [comment]
FWIW swiper works with [emacs input methods](https://www.gnu.org/software/emacs/manual/html_node/emacs/Input-Methods.html), so if you're in swiper and have `enable-recursive-minibuffers` set to `t`, you can just `M-x set-input-method RET TeX RET` and type `\lambda`, and go back with `C-\`. Further if you set `default-input-method` to `"TeX"`, you can just `M-x swiper`, hit  `C-\` and type `\lambda`, again typing `C-\` to go back (saves you the awkward recursive edit).

**Comment by basil-conto** [comment]
@dieggsy Note that <kbd>C-\</kbd> also takes a prefix argument for selecting an input method with completion.

Although it is, of course, possible to switch input method after starting an Ivy/Swiper completion session, as @dieggsy points out, it's worth noting that Ivy in general ignores the `inherit-input-method` argument of minibuffer completion functions, such as `completing-read`.

**Comment by capfredf** [comment]
Sorry for the late response. 

@abo-abo Yes. Like this:
![demo](https://user-images.githubusercontent.com/512906/37041949-63f421f0-212b-11e8-819f-05b30e734b7d.gif)

@dieggsy Thanks for your input. Your approach is almost the same as mine now. The only difference is I use different input methods to input unicodes in Swiper for different major modes. For instance, I use the Racket input method in the racket-mode for programming in Racket, and Agda input method in the agda-mode for programming in Agda. I would like to automatically toggle the input method when I do a search in Swiper.

@basil-conto This may be a dumb question. I'm not quite familiar with elisp. How can I configure Swiper/Ivy so that it won't ignore the inherit-input-method argument?

**Comment by basil-conto** [comment]
@capfredf 
> How can I configure Swiper/Ivy so that it won't ignore the inherit-input-method argument?

Ivy ignores it unconditionally at the moment, so the best you can do is set your preferred input method on entry to the minibuffer. See https://emacs.stackexchange.com/a/38311/15748 for how to inherit the input method of the current buffer. If you want to activate an input method other than that of the current buffer, just replace `(buffer-local-value 'current-input-method buf)` in the linked answer with that input method. Note that this hook is global, i.e. not specific to Ivy.

**Comment by basil-conto** [comment]
@capfredf 
> Ivy ignores it unconditionally at the moment

Sorry, that's not *entirely* accurate. You can tell Ivy to heed `inherit-input-method`, but that requires adding a complete re-implementation of `ivy-completing-read` to `ivy-completing-read-handlers-alist`, and even then this approach won't work all the time because of the unreliability of `this-command`.

So, for all intensive porpoises, Ivy does not currently support `inherit-input-method`.

**Comment by capfredf** [comment]
@basil-conto thank you very much
