### ISSUE TITLE
counsel-ag in git repos

### ISSUE THREAD

**Issue by paulcam206** [abo-abo/swiper#1482]
I'm loving `counsel-ag`, but have a small problem: One of my repos is too large to search in a reasonable amount of time. Is there a way to selectively restrict the directory short of invoking with the universal argument?

I know I could write a little function to do it for me, but was wondering if there's a more built-in way...

**Comment by abo-abo** [comment]
If you do <kbd>C-u</kbd> before `counsel-ag`, it will prompt you for the starting directory.

I'm using `counsel-rg` myself, and recently I discovered that I can put an `.ignore` file in the base of the repository to ignore some file and directory patterns. Really speeds things up, probably `ag` has something similar too.

**Comment by paulcam206** [comment]
I ended up just writing my own little function to handle this, since I didn't want to have to interactively provide all of the arguments. Thanks!

```lisp
(defun pc-counsel-ag-current-dir ()
  "Runs `counsel-ag' against the current buffer's directory."
  (interactive)
  (counsel-ag "" (file-name-directory (buffer-file-name)) nil nil))
```

Thanks

**Comment by dieggsy** [comment]
@paulcam206 I think `default-directory` may be more desirable that `(file-name-directory (buffer-file-name))` since it will be set for most bufffers even if they don't have a file associated with them.

**Comment by paulcam206** [comment]
My elisp game is weak -- already great to get improvement suggestions. Thanks!

**Comment by basil-conto** [comment]
@paulcam206 You can also omit the two trailing `nil` arguments if you want, seeing as they are optional and thus default to `nil` anyway.
