### ISSUE TITLE
Should counsel-minibuffer-history replace the minibuffer entry instead of inserting?

### ISSUE THREAD

**Issue by danielmatz** [abo-abo/swiper#1484]
When I use <kbd>M-x</kbd> `compile`, there is always a pre-populated default command, and when I then go to call `counsel-minibuffer-history`, I end up appending the selected history entry to the default command.

Should `counsel-minibuffer-history` replace the minibuffer entry by default, instead of simply calling `insert`?

**Comment by abo-abo** [comment]
Sorry, I don't understand what you mean. Can you give a more detailed example with steps and expectations?

**Comment by danielmatz** [comment]
When I run <kbd>M-x</kbd> `compile`, the minibuffer will initially have:

```
Compile command: make -k|
```

Where `|` denotes where point is.

Then I launch `counsel-minibuffer-history`, and I go select an entry from the history, let's say I pick `make install`.  The minibuffer will end up looking like this:

```
Compile command: make -kmake install|
```

See how my selection just gets appended?  I was wondering if others thought that it would be a better if the default behavior were to replace the current contents of the minibuffer, such that I would instead have ended up with:

```
Compile command: make install
```

That is, the pre-populated `make -k` gets killed and my selection gets inserted.

Of course, I can just kill the pre-populated compile command before calling `counsel-minibuffer-history`, but for some reason it just seems awkward to me and I keep forgetting to do it.

**Comment by danielmatz** [comment]
Perhaps we could preserve the `insert` behavior by adding it to `ivy-dispatching-done` for `counsel-minibuffer-history`, just in case someone did want that?

**Comment by xenodium** [comment]
I often ran into the same compile scenario. Worked around it by re-mapping "C-r" to a version of `counsel-minibuffer-history` that clears the minibuffer prior to insertion. Seems to work well in other use-cases outside compilation, though I may not be considering the wider usage. If safe, it'd be nice to include in `counsel-minibuffer-history`.

    (use-package counsel
      :ensure t
      :bind (:map minibuffer-local-map
                  ("C-r" . ar/counsel-minibuffer-history))
      :config
      (defun ar/counsel-minibuffer-history ()
        "Like `counsel-minibuffer-history' but clears minibuffer on history item selection."
        (interactive)
        (let ((enable-recursive-minibuffers t))
          (ivy-read "History: " (ivy-history-contents minibuffer-history-variable)
                    :keymap ivy-reverse-i-search-map
                    :action (lambda (x)
                              (delete-minibuffer-contents)
                              (insert (substring-no-properties (car x))))
                    :caller 'counsel-minibuffer-history)))
      (counsel-mode +1))

**Comment by shitikanth** [comment]
I agree that this should be the default behaviour. Simply inserting the old minibuffer contents at point is incorrect/unexpected behaviour in most contexts.

**Comment by basil-conto** [comment]
Makes sense, so commit 7cdde66c95d5205287e88010bc7a3a978c931db0 now adds the required `delete-minibuffer-contents` incantation before inserting the history element.  I guess we'll find out sooner or later if other users complain...

The new version should be available on [GNU-devel ELPA](https://elpa.gnu.org/devel/counsel.html) within the next few hours.

Thanks.
