### ISSUE TITLE
`counsel-package` is very slow

### ISSUE THREAD

**Issue by seagle0128** [abo-abo/swiper#1485]
I found `counsel-package` is very slow to show the package list. I tested on GNU Emacs 26.0.91 (Windows 10, macOS 10.13.3) and 25.3.2 (Ubuntu 16.04LTS).

**Comment by abo-abo** [comment]
How slow is very slow? For me, it's less than 0.5s on Ubuntu. I use ELPA and MELPA.

**Comment by seagle0128** [comment]
@abo-abo I upgraded the `counsel` package, and retry `counsel-package`. It's fast now. Seems it's a intermittent issue. Closing it.

**Comment by seagle0128** [comment]
@abo-abo I have to reopen it since the issue appears again. I did profiling and attach the screenshot.

<img width="623" alt="screen shot 2018-04-17 at 1 24 03 am" src="https://user-images.githubusercontent.com/140797/38825198-449a9d06-41de-11e8-9a9e-118ab425a2fb.png">

**Comment by mookid** [comment]
did you byte-compile ivy.el and counsel.el?

**Comment by seagle0128** [comment]
@mookid Sure. I installed `ivy` and `counsel` via `use-package`.
Actually I found, if I did some actions for packages (e.g. install, delete), later `counsel-package` became very slow somehow.

**Comment by basil-conto** [comment]
@seagle0128 If you can reliably reproduce this, it might be worth <kbd>M-x</kbd>`report-emacs-bug`<kbd>RET</kbd>, as `counsel-package` can't do anything about a slow `package-built-in-p`.

I would sooner believe that there is something in your configuration causing the issue, however. Are you able to reproduce with `emacs -Q` or `make plain`?

**Comment by seagle0128** [comment]
I upgraded to Emacs 26.1, and it does work well. No issue so far. I'd like closing it.
