### ISSUE TITLE
swiper--add-overlays: Symbol’s function definition is void: ivy--case-fold-p

### ISSUE THREAD

**Issue by badbob** [abo-abo/swiper#1486]
I'm using GNU Emacs 25.2.2 on Linux. 
I just install ivy 20171224.842  and swiper 20180306.953. 
Here is my _~/.emacs_:
```
(ivy-mode 1)
```
And I just `M-x swiper` and see in _\*Messages\*_ buffer:
```
swiper--add-overlays: Symbol’s function definition is void: ivy--case-fold-p
```

**Comment by abo-abo** [comment]
Looks like a packaging problem. Try re-installing and restarting Emacs.

**Comment by badbob** [comment]
@abo-abo looks like you right. _\*Compile-Log\*_ buffer after installation of swiper 20180306.953:
```
In end of data:
swiper.el:1009:1:Warning: the function ‘ivy--case-fold-p’ is not known to be
    defined.
```

**Comment by badbob** [comment]
For some reason I was using outdated version of Ivy package (20171224.842) with updated swiper. I just install updated version of ivy package downloaded from MELPA manually and everything is OK now. Thanks for you rapid feedback and great project.
