### ISSUE TITLE
Scoped research 

### ISSUE THREAD

**Issue by Davidbrcz** [abo-abo/swiper#149]
Hi

Is there a way to scope the research on the current block / selected area ?

Thanks.
David

**Comment by abo-abo** [comment]
You mean to narrow the search to the active region? There's nothing extra, but you can use the built-in stuff, just like for `isearch`:

- <kbd>C-x nn</kbd> (`narrow-to-region`)
- <kbd>C-s</kbd> (`swiper`)
- <kbd>C-x nw</kbd> (`widen`)

There's also `lispy-occur` from [lispy](https://github.com/abo-abo/lispy): it searches only the current defun.  The same approach could be applied to a region, but try the standard approach first.

**Comment by Davidbrcz** [comment]
These functions were disabled. It works fine. Thanks
