### ISSUE TITLE
ivy-immediate-done (C-M-j) in dired add directory with trailing character

### ISSUE THREAD

**Issue by ramestica** [abo-abo/swiper#1493]
if in dired I try '+ foo C-M-j' then the name of the new directory is 'foo?/' instead of just 'foo'.

After typing C-M-j the mini-buffer says ' [No match]' to which I just hit 'enter', and then 'foo?/' is created.

Am I using C-M-j the wrong way?

**Comment by abo-abo** [comment]
Looks like a bug, I've never encountered this before. You're doing the right steps, maybe there's something in your config interfering; can you reproduce this with `make plain`?

**Comment by ramestica** [comment]
`make plain` works and in this case I never saw ' [No match]', This made search for that string in all elisp modules I have installed. Founded in helm and ido. After disabling ido now C-M-j works as expected! 

I should have disabled all my original ido configuration at the moment I switched to swiper. 

Thanks, and sorry for the unnecessary noise.
