### ISSUE TITLE
"ivy-alt-done" can complete to non-existent directory

### ISSUE THREAD

**Issue by muirrn** [abo-abo/swiper#1494]
Starting with file tree:

```
[muir@work-mb root]$ find .
.
./foo
./foo/foo_file.rb
./bar
./bar/start
./bar/foo
```

1. Open `bar/start`
2. Run `counsel-find-file`
3. Press backspace to go up to `/`
4. Type "foo" then `<C-j>` to complete into `foo/`
5. Type "foo" then `<C-j>` to attempt to open `foo_file.rb`

I expect it to open `foo_file.rb` since it is not a directory, but it navigates into non-existent `foo/foo` directory.

I reproduced using the `plain` make target.

**Comment by basil-conto** [comment]
What is your `emacs-version` and Swiper project version? I cannot reproduce this on `GNU Emacs 27.0.50 (build 16, x86_64-pc-linux-gnu, X toolkit, Xaw3d scroll bars) of 2018-03-19` starting from `make plain` with latest Swiper `master` of 2018-03-16, commit b53ba0be297a6bf22e0fab831eb1297c986bf774. The given steps correctly open the `foo/foo_file.rb` file.

**Comment by muirrn** [comment]
I am running `GNU Emacs 26.0.91`

```
[muir@work-mb swiper]$ git rev-parse HEAD
b53ba0be297a6bf22e0fab831eb1297c986bf774

[muir@work-mb swiper]$ emacs --version
GNU Emacs 26.0.91
Copyright (C) 2018 Free Software Foundation, Inc.
GNU Emacs comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of GNU Emacs
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.

[muir@work-mb swiper]$ emacs -Q -l colir.el -l ivy-overlay.el -l ivy.el -l swiper.el -l counsel.el -l targets/plain.el
```

**Comment by basil-conto** [comment]
I additionally cannot reproduce this on any one of Emacs 24, 25 or 26.

Can you please list your full `emacs-version`, i.e. <kbd>M-x</kbd>`emacs-version`<kbd>RET</kbd>, rather than just `emacs --version`?

From your hostname I assume your `system-type` is `darwin`, which potentially implicates [bug#30350](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=30350).

**Comment by basil-conto** [comment]
I'm not sure to what extent [this commit](http://git.savannah.gnu.org/cgit/emacs.git/commit/?id=5c414441ed73f1a302a2953dc493e83b98589262) solves the aforementioned Emacs bug, and have no way to test Swiper on macOS more generally.

**Comment by muirrn** [comment]
`emacs-version` is `GNU Emacs 26.0.91 (build 1, x86_64-apple-darwin13.4.0, NS appkit-1265.21 Version 10.9.5 (Build 13F1911)) of 2018-01-24`

I am not seeing the buggy behavior you linked to. Let me see if I can reproduce on non-darwin.

**Comment by muirrn** [comment]
I reproduced it on linux `GNU Emacs 24.5.1 (x86_64-pc-linux-gnu, GTK+ Version 3.18.9) of 2017-09-20 on lcy01-07, modified by Debian` under `make plain`.

Are you typing exactly "foo" before the final `<C-j>`? If you do "fo" or "foo_" for example, it won't reproduce.

**Comment by basil-conto** [comment]
> Are you typing exactly "foo" before the final `<C-j>`?

Yes, I am following your recipe verbatim:

1. `emacs=emacs24 make plain`
2. <kbd>M-x</kbd>`emacs-version`<kbd>RET</kbd> logs the following in `*Messages*`:
   `GNU Emacs 24.5.1 (x86_64-pc-linux-gnu, X toolkit, Xaw3d scroll bars) of 2017-09-12 on hullmann, modified by Debian`
3. ```el
   (let (;; New temporary directory
         (default-directory (file-name-as-directory (make-temp-file "" t)))
         (files '("bar/start" "foo/foo_file.rb" "bar/foo")))
     ;; Create sample directory tree
     (dolist (file files)
       (make-directory (file-name-directory file) t)
       (with-temp-file file))
     ;; Log directory structure
     (message "%s" (with-output-to-string
                     (call-process "tree" nil standard-output)))
     ;; Open `bar/start' via `counsel-find-file'
     (setq unread-command-events
           (nconc (listify-key-sequence (car files)) '(?\C-m)))
     (call-interactively #'counsel-find-file))
   ```
   <kbd>C-j</kbd> logs the following in `*Messages*`:
   ```
   .
   ├── bar
   │   ├── foo
   │   └── start
   └── foo
       └── foo_file.rb
   
   2 directories, 3 files
   ```
4. <kbd>C-x</kbd><kbd>C-f</kbd><kbd>DEL</kbd>`foo`<kbd>C-j</kbd>`foo`<kbd>C-j</kbd>
5. <kbd>M-:</kbd>`buffer-file-name`<kbd>RET</kbd> gives:
    ```el
   "/tmp/15823JdI/foo/foo_file.rb"
   ```

**Comment by muirrn** [comment]
Sorry, my steps are wrong/unclear due to the `find` output. `bar/foo` should be a directory. I changed your final file from `"bar/foo"` to `"bar/foo/baz"` to make `"bar/foo"` a directory and it reproduced the issue.

`(files '("bar/start" "foo/foo_file.rb" "bar/foo/baz"))`

**Comment by basil-conto** [comment]
Thanks, I can reproduce it in all Emacs versions between 24-27 now.

**Comment by basil-conto** [comment]
Does the following patch look right?

```diff
diff --git a/ivy.el b/ivy.el
index c48dc55..92b46c0 100644
--- a/ivy.el
+++ b/ivy.el
@@ -821,12 +821,13 @@ ivy--directory-done
         (setq dir (ivy-expand-file-if-directory (ivy-state-current ivy-last))))
        (ivy--cd dir)
        (ivy--exhibit))
-      ((and (not (string= ivy-text ""))
-            (ignore-errors (file-exists-p ivy-text)))
-       (if (file-directory-p ivy-text)
-           (ivy--cd (expand-file-name
-                     (file-name-as-directory ivy-text) ivy--directory))
-         (ivy-done)))
+      ((unless (string= ivy-text "")
+         (let ((file (expand-file-name ivy-text ivy--directory)))
+           (when (ignore-errors (file-exists-p file))
+             (if (file-directory-p file)
+                 (ivy--cd (file-name-as-directory file))
+               (ivy-done))
+             ivy-text))))
       ((or (and (equal ivy--directory "/")
                 (string-match "\\`[^/]+:.*:.*\\'" ivy-text))
            (string-match "\\`/[^/]+:.*:.*\\'" ivy-text))
```

**Comment by muirrn** [comment]
I can confirm that patch fixes it for me.

**Comment by abo-abo** [comment]
@basil-conto Thanks, please PR.
