### ISSUE TITLE
How can I jump to a predefined directory while in the ivy minibuffer?

### ISSUE THREAD

**Issue by bokwoon95** [abo-abo/swiper#1496]
My use case is like this: 

I open `counsel-find-file` with `C-x C-f`, but I opened it from some deeply nested directory e.g. `~/Desktop/FileA/FileB/FileC/FileD/FileE` and I want to access something in my home `~/` directory. The usual way would be to spam backspace until I'm at `~/`, then start typing.

Is it possible to create an `ivy-minibuffer-map` (for example `M-h`) such that it immediately takes the prompt to `Find File: ~/` no matter where I `C-x C-f` from? I've tried defining some functions but the problem is I keep getting the `Command attempted to use minibuffer while in minibuffer` error.

    ; Here's what I tried

    (define-key ivy-minibuffer-map (kbd "M-h") 'open-home)
    (defun open-home ()
      (interactive)
      (counsel-find-file "~/"))
    
    (define-key ivy-minibuffer-map (kbd "M-d M-r") 'open-dropbox)
    (defun open-dropbox ()
      (interactive)
      (counsel-find-file "~/Documents/Dropbox"))

I know I can make a command that calls `counsel-find-file` while I am outside the minibuffer, but I'd prefer to make it a minibuffer-specific keybind so that I don't pollute my keybind list outside the minibuffer.

**Comment by mookid** [comment]
What about `(let ((default-directory (getenv "HOME"))) (counsel-find-file))` ?

**Comment by mookid** [comment]
I think that
``` elisp
(defun ivy--cd-home ()
  (interactive)
  (ivy--cd (getenv "HOME")))

(define-key counsel-find-file-map (kbd "M-h") 'ivy--cd-home)
```

does the trick.

**Comment by bokwoon95** [comment]
> I think that
>
>     (defun ivy--cd-home ()
>       (interactive)
>       (ivy--cd (getenv "HOME")))
>
> (define-key counsel-find-file-map (kbd "M-h") 'ivy--cd-home)
> does the trick.

Sweet, that does exactly what I want! What's the difference between `ivy-minibuffer-map` and `counsel-find-file-map`? Both seem to work here.

**Comment by mookid** [comment]
`counsel-find-file-map` is only active when the command `counsel-find-file` is running (this is the argument `:keymap` of `ivy-read`).

**Comment by basil-conto** [comment]
There's no need for a custom command+binding; typing <kbd>~</kbd> during Ivy filename completion already restarts completion from the home directory. See [`(ivy) File Name Completion`](http://oremacs.com/swiper/#file-name-completion). This behaviour is controlled by the user option `ivy-magic-tilde`:

    ivy-magic-tilde is a variable defined in `ivy.el'.
    Its value is t

    Documentation:
    When non-nil, ~ will move home when selecting files.
    Otherwise, ~/ will move home.

Note also that there is seldom need for `(getenv "HOME")`, as Emacs knows how to expand `"~"` to the home directory of `user-login-name`; see [`(elisp) File Name Expansion`](https://www.gnu.org/software/emacs/manual/html_node/elisp/File-Name-Expansion.html).

**Comment by abo-abo** [comment]
Thanks all for chiming in.

@bokwoon95 
You can also use the built-in <kbd>M-o b</kbd> action to select a directory from your bookmarks.

**Comment by bokwoon95** [comment]
>  typing ~ during Ivy filename completion already restarts completion from the home directory

Oh that's neat. I don't have to define a custom command for the home directory then.

> You can also use the built-in M-o b action to select a directory from your bookmarks.

Well, I'll be. It's still a fair amount of keystrokes though, since I can't seem to search by the shortcut alphabets associated with them in `bookmark-bmenu-list`. Is it possible to include the shortcut alphabets in `M-o b`? And if possible, maybe also something like [`headlong`](https://github.com/abo-abo/headlong) where you don't have to hit RET and it automatically jumps when there's one completion entry left.

As an aside, none of my `ivy--cd-XXX` functions seem to be loaded in when I start emacs.

```elisp
    ;; Ivy minibuffer completion
    (defun ivy--cd-emacsd ()
      (interactive)
      (ivy--cd "~/.emacs.d/"))    
    (define-key counsel-find-file-map (kbd "M-e") 'ivy--cd-emacsd)
    
    (defun ivy--cd-dropbox-documents ()
      (interactive)
      (ivy--cd "~/Dropbox/Documents/"))    
    (define-key counsel-find-file-map (kbd "M-d M-d M-c") 'ivy--cd-dropbox-documents)
    
    (defun ivy--cd-documents ()
      (interactive)
      (ivy--cd "~/Documents/"))
    (define-key counsel-find-file-map (kbd "M-d M-o M-c") 'ivy--cd-documents)
```

Only the first function, `ivy--cd-emacsd` appears in the `M-x` list, and even then calling it via `M-e` results in the `Command attempted to use minibuffer while in minibuffer` error. It all works once I source my `init.el` once though. I don't mind doing it everytime since I bound `C-c l` to load my `init.el`, but what could be the reason they don't get sourced in the first place?

**Comment by abo-abo** [comment]
> As an aside, none of my ivy--cd-XXX functions seem to be loaded in when I start emacs.

Can't help with that, your code looks correct to me.

> Command attempted to use minibuffer while in minibuffer error.

To prevent this error:

```elisp
(setq enable-recursive-minibuffers t)
```

> what could be the reason they don't get sourced in the first place?

You can put in your `~/.emacs` a single line:

```elisp
(load "path/to/init.el")
```

Then your init.el is either loaded, or you'll get an error message on startup.

**Comment by mookid** [comment]
Turned into a wiki entry: https://github.com/abo-abo/swiper/wiki/Jump-to-a-predefined-directory-while-running-counsel-find-file

**Comment by abo-abo** [comment]
@mookid Thanks.
