### ISSUE TITLE
counsel-rg's extra arguments do not support additional paths to search from

### ISSUE THREAD

**Issue by rieje** [abo-abo/swiper#1498]
According to `man rg`, any paths as the last arguments to the command are paths to search from. However, using the universal argument `C-u counsel-rg` to prompt `counsel-rg` for extra arguments and specifying a path as an argument will result in `counsel-rg` not showing results from this path *and* from the initial/default path, so the search results will always have nothing.

Example: `C-u counsel-rg`, enter `~/bin` as initial directory to search for, enter `~/.emacs.d` as an argument when prompted, and any string you search will return 0 results even if that string is in `~/bin`. 

Saw this issue posted on /r/emacs, so might as well submit a GH issue.

**Comment by abo-abo** [comment]
Thanks for the report. Could you add the full command line that does what you want with `~/bin`?

**Comment by rieje** [comment]
It's very simple: `rg bash ~/bin ~/documentation` (`rg <pattern> [path...]`).

**Comment by abo-abo** [comment]
OK, here's how I made it work (no code changes needed):

- enter `~/bin` as the initial dir as you do already
- enter ` -- ~/.emacs.d` as the extra args

Let me know if it works for you.

**Comment by abo-abo** [comment]
Note the space before `--`.

**Comment by rieje** [comment]
Thanks, that works for me. Glad you mentioned the space before `--`, Github didn't show that. On reddit, you linked the [related issue](https://github.com/abo-abo/swiper/pull/1559)--I'm guessing that PR will solve this issue of needing to put a space before `--` or remove the need for using `--` altogether? You can decide whether to close this issue.

-------------------

I was playing around with `counsel-rg-base-command` and pretty sure I found another issue (not related).

With the setting `(setq counsel-rg-base-command "rg --smart-case --no-heading --line-number --no-ignore --color auto %s .")`, `M-x counsel-rg setq` shows no results, while the corresponding `rg` command `g --smart-case --no-heading --line-number --no-ignore --color auto setq .` in the directory `~/.dotfiles/arch/.emacs.d` shows expected results. 

Also, that `counsel-rg-base-command` setting without the `--no-ignore` setting will also show expected results. It's weird because `--no-ignore` should either return the same number of results or more results--I don't see a case where it returns less (and in this case, 0 results).

`~/.dotfiles/arch/.emacs.d/` is a symlink to `~/.emacs.d/` but I've tried both the symlink and the absolute path and they both yield consistent results described above. `~/.dotfiles` is a git repo, but even if I remove the `.gitignore` file, the base command with `--no-ignore` yields no results.

Going to submit this as a separate issue, just wanted to mention here.

**Comment by abo-abo** [comment]
Thanks, fixed. The extra initial space is no longer needed.
