### ISSUE TITLE
why `counsel-M-x` doesn't use `ivy-format-function`

### ISSUE THREAD

**Issue by bixuanzju** [abo-abo/swiper#150]
I have following lines in my config (stolen from your blog ;)

```elisp
  (setq ivy-format-function 'eh-ivy-format-function)

  (defun eh-ivy-format-function (cands)
    (let ((i -1))
      (mapconcat
       (lambda (s)
         (concat (if (eq (cl-incf i) ivy--index)
                     "> "
                   "  ")
                 s))
       cands "\n")))
```

I like this little arrow indicating which line i am on. But `counsel-M-x` seems ignoring this.

**Comment by abo-abo** [comment]
Thanks, fixed. I also updated `ivy-format-function-arrow` to the body of `eh-ivy-format-function`.
