### ISSUE TITLE
Interactive ivy-count

### ISSUE THREAD

**Issue by rchar01** [abo-abo/swiper#1509]
Hello,
I would like to define a function in my config to interactively enable/disable ivy-count e.g. in swiper.
Is it possible with current release?

Thanks for great Emacs modes.

**Comment by abo-abo** [comment]
Here's a solution you can use in your config:

```elisp
(defun my-ivy-toggle-count ()
  (interactive)
  (setq ivy-count-format
        (if (string= ivy-count-format "")
            "%-4d "
          ""))
  (setq ivy--prompt (ivy-add-prompt-count (ivy-state-prompt ivy-last))))
(define-key ivy-minibuffer-map (kbd "M-c") 'my-ivy-toggle-count)
```

I don't know if this is a feature many users want. Maybe it's worth including into ivy.el, but it's hard to find a good key binding for it.

**Comment by eflanigan00** [comment]
I am curious why you don't want the count?
Perhaps you want a less clutterrd screen?

**Comment by rchar01** [comment]
I thought I'd turn off the counting permanently and use a defined shortcut to turn it on/off when needed.

Maybe I asked the wrong question. I wanted to turn off the counting during `M-x`, ` describe-function` and `describe-variable`.

The question should be: Is it possible to 
- show counting only during certain actions e.g. `swiper`, `switch-to-buffer` and disable it for other functions?<br><br>or

- turn counting off during certain actions e.g. `M-x`, `describe-variable` and leave it (unchanged) for other functions?
