### ISSUE TITLE
font size and multiple line entries hide the current selection (org refiling with ivy)

### ISSUE THREAD

**Issue by brabalan** [abo-abo/swiper#151]
When refiling an entry with ivy, it seems that the font size is not taken into account, so the selection is at the very bottom of the window:
![screen shot 2015-06-18 at 09 44 01](https://cloud.githubusercontent.com/assets/1021637/8226418/e02791e4-159e-11e5-8587-a4844d5ea71b.png)
The problematic part is when the lines are too long, they can span more than one line (probably because of font size) and the selection disappears:
![screen shot 2015-06-18 at 09 43 16](https://cloud.githubusercontent.com/assets/1021637/8226424/f6f857c8-159e-11e5-8183-55b91a823edf.png)

This happens with the leuven theme. Is there a way to ensure the selection is in the middle of the window?

**Comment by abo-abo** [comment]
I'm still looking into this, but for now I've added a way to increase the minibuffer height dynamically.

**Comment by brabalan** [comment]
Thanks, this will be most useful.

**Comment by abo-abo** [comment]
Thanks, this should be fixed now. I've also fixed an issue regarding the selection not being highlighted.

**Comment by brabalan** [comment]
I really like your solution. It works great, thanks!
