### ISSUE TITLE
counsel-minibuffer-history in the running of counsel-find-file shows empty list

### ISSUE THREAD

**Issue by oracleyue** [abo-abo/swiper#1515]
Is the following a feature or a bug? (As a new user, not sure. It seems a bug)

I used your default configuration: `(define-key minibuffer-local-map (kbd "C-r") 'counsel-minibuffer-history)`. 
When I first open Emacs, if I run `counsel-find-file`, `C-r` gives empty list. It shows empty list, until I run `counsel-switch-buffer` (`C-x b`).  As long as running `C-x b` once, the `C-r` in `counsel-find-file` later works correctly (I mean, showing the list of files that recently opened.).

And if I run `M-x counsel-minibuffer-history`, it always shows empty list (I guess this is supposed to be, right?).

Info:
- Emacs: 25.3.1
- Ivy: 20180326.1231
- Counsel: 20180328.1326

**Comment by oracleyue** [comment]
Close since I cannot reproduce it on my Mac. It only appears on my Arch linux laptop.

**Comment by basil-conto** [comment]
Note that `counsel-find-file` has its own keymap `counsel-find-file-map` which is distinct from `minibuffer-local-map`. I wonder why `minibuffer-local-map` is suggested in the README and used by `counsel-mode` instead of `ivy-minibuffer-map`.

**Comment by oracleyue** [comment]
One may check if you can reproduce the same issue.

**Comment by basil-conto** [comment]
> Meanwhile, it seems reasonable to show nothing. Since I just started my Emacs, I didn't run any find-file commands before, and thus `Ivy/counsel` gives me none. I am not sure it is an issue any more.

Yes, `minibuffer-history-variable` will be empty in a fresh Emacs instance; this is expected and intended.

> I guess that's because we want `C-r` to show the history of every command, e.g. the find-file, or the `M-x`?

That is the job of `minibuffer-history-variable`, not `minibuffer-local-map`. How often is `minibuffer-local-map` actually active in the minibuffer when `ivy-mode` and `counsel-mode` are enabled?

**Comment by oracleyue** [comment]
> Yes, minibuffer-history-variable will be empty in a fresh Emacs instance; this is expected and intended.

Then it should stay empty until I really open some files, instead of showing recentf after I run =C-x b= once.

> How often is minibuffer-local-map actually active in the minibuffer when ivy-mode and counsel-mode are enabled?

No idea in general. For =counsel-find-file=, once I run =C-x b=, =C-r= starts showing recentf.

**Comment by basil-conto** [comment]
> > Yes, minibuffer-history-variable will be empty in a fresh Emacs instance; this is expected and intended.

> Then it should stay empty until I really open some files, instead of showing recentf after I run =C-x b= once.

I'm sorry, I don't follow your logic. Can you please describe more clearly which behaviour you expect and why, and how it differs from the current behaviour of Ivy/Swiper? If you don't want `recentf` entries, there are various ways of customising this, but they are specific to `recentf` and `ivy-use-virtual-buffers`, for example, not `counsel-minibuffer-history`. What I'm saying is, if you don't want a feature cluttering your minibuffer history, then either customise that feature, disable it, or bring the issue up with its maintainers. `counsel-minibuffer-history` just shows what's there (or at least it's supposed to).

**Comment by oracleyue** [comment]
@basil-conto Probably it's due my misunderstanding and it works as the author of Ivy expected. Here is the description:
1. Open Emacs firstly, run `counsel-find-file`, press `C-r`, it shows nothing (*correct*, as expected)
2. Run `ivy-switch-buffer` (note that `ivy-use-virtual-buffers` is `t`) once.
3. re-run `counsel-find-file`, `C-r` shows all the list of files that saved in `recentf` (that saves the historically opened files, before opening this Emacs process).

My logic is following:
- if `counsel-recentf` shows the history of that command (e.g. `C-x C-f`) since the opening of Emacs, then it should still shows nothing instead of showing the history saved in `recentf`;
- if `counsel-recentf` in `counsel-find-file` shows the `recentf`, it should work at the beginning instead of having to be triggered by `C-x b`.

However, this action also makes sense. The underlying running of `counsel-rencetf` or equivalent like `ivy-use-virtual-buffers` (triggered by `C-x b`) will update the history of command `counsel-find-files` by the history saved in `recentf` (that actually happened before we open this Emacs instance).

I would rather close this issue, which is more like a feature and depends on users' different understanding. It doesn't matter. At the beginning, I thought it were an issue, since I just migrated from helm and hadn't learned much.
Many thanks for your comments!

**Comment by basil-conto** [comment]
> if `counsel-minibuffer-history` shows the history of that command (e.g. `C-x C-f`) since the opening of Emacs, then it should still shows nothing instead of showing the history saved in `recentf`

`counsel-minibuffer-history` does not "show the history saved in `recentf`"; it just completes the contents of the current `minibuffer-history-variable`, which during `counsel-find-file` is `file-name-history`.

When `recentf` is enabled and `file-name-history` is empty, e.g. in a new Emacs session, then `recentf` populates `file-name-history` with the contents of `recentf-list`. If you want to disable this `recentf` (not `counsel`) feature, then set the user option `recentf-initialize-file-name-history` to `nil`.

> if `counsel-minibuffer-history` in `counsel-find-file` shows the `recentf`, it should work at the beginning instead of having to be triggered by `C-x b`.

Again, there is no such thing as "showing the `recentf`". If you want `recentf` to have populated `file-name-history` before you call `counsel-find-file`, then simply ensure that `recentf-mode` is previously enabled. For example, you could add `recentf-mode` to `ivy-mode-hook` or `counsel-mode-hook` or
```el
(with-eval-after-load 'counsel
  (recentf-mode))
```
or similar.

**Comment by oracleyue** [comment]
@basil-conto Many thanks!! It helps me to resolve many things. Now it has been perfectly clear to me, and I also got how to make it work as I expected from your comments. Thanks!

> "show the history saved in recentf"
FYI, I used it to refer to the list of files that also showed in `counsel-recentf`. Not sure it shows the `recentf` (I actually I don't how `recentf` works and saves what exactly.)

**Comment by basil-conto** [comment]
> FYI, I used it to refer to the list of files that also showed in `counsel-recentf`. Not sure it shows the `recentf`(I actually I don't how `recentf` works and saves what exactly.)

I have tried to be as explicit as possible in my wording to avoid confusion: `recentf` is a package; `recentf-mode` is the function provided by that package to toggle its operation; `recentf-list` is a variable used by that package to hold a list of recently visited files; `file-name-history` is a [history list](https://www.gnu.org/software/emacs/manual/html_node/elisp/Minibuffer-History.html) comprising filenames recently completed in the minibuffer.

As such, `counsel-minibuffer-history` and `counsel-recentf` operate on two quite distinct lists of candidates; it just so happens that one of the features of the `recentf` package that is enabled by `recentf-mode` by default is to populate `file-name-history` (which `counsel-minibuffer-history` **sometimes** operates on) with the contents of `recentf-list` (which `counsel-recentf` **always** operates on).

**Comment by oracleyue** [comment]
@basil-conto Sorry, the additional "FYI" seems confusing you. I just mentioned what I meant in previous comments. You second last has clarify everything quite clearly :)  Thanks a lot for your patient explanations!!!
