### ISSUE TITLE
Default value in file name completion

### ISSUE THREAD

**Issue by rootzlevel** [abo-abo/swiper#152]
Many file operations (such as `copy-file`, `delete-file` or even `find-file`) provide the current file as default value to completing-read, when called interactively. So copying the current file should only be a `M-x copy-file` <kbd>RET</kbd> <kbd>M-n</kbd> <kbd>RET</kbd> `new-file` <kbd>RET</kbd> away.

Unfortunately, <kbd>M-n</kbd> inserts the whole absolute file name in the minibuffer, which ivy can't handle. (It inserts `/current-directory/absolute/path/of/file`).

An option would be to detect if the history entry is an absolute path and in that case, replace the whole minibuffer content instead of only the part after the last slash.

**Comment by abo-abo** [comment]
Thanks for pointing this out. Please test this and give feedback. I think it looks OK, I didn't have an Ido behavior for a reference, since there's only `ido-find-file` and not `ido-copy-file`.

**Comment by rootzlevel** [comment]
works great so far, thanks!
