### ISSUE TITLE
completing-read argument DEF as a symbol breaks

### ISSUE THREAD

**Issue by yannvanhalewyn** [abo-abo/swiper#1526]
There's a difference between the default behavior of `completing-read`, and `ivy-completing-read` when de DEF argument is a symbol. It seems to lose the suggestions collection, and will not return said value upon "RET" with empty input.

``` el
(completing-read "Q: " '(one two) nil nil nil nil 'one)
;; => no suggestions and empty "" on RET
(completing-read-default "Q: " '(one two) nil nil nil nil 'one)
;; => Shows suggestions on tab and expected default value on RET
```

I've looked through open and closed issues and found some other issues about completing read, but not about this case so I opened a new one.

I couldn't find any specification of expected type in the default `completing-read` documentation, correct me if I'm wrong.

Tested on master  #https://github.com/abo-abo/swiper/commit/da4236cc1d090ffc3b6a61bca77e6ccd318ad7dc with `make plain`.

My personal issue with this was with clj-refactor when adding missing libspec has multiple options, see line: https://github.com/clojure-emacs/clj-refactor.el/blob/ab081b26b92f6a1c7ebe8fb7ff9803d46b07ae84/clj-refactor.el#L2182

EDIT: I had submitted issue by accident with the return key, finished specifying.

**Comment by yannvanhalewyn** [comment]
Not same, but related to https://github.com/abo-abo/swiper/issues/1208 and https://github.com/abo-abo/swiper/issues/1209

**Comment by basil-conto** [comment]
> when de DEF argument is a symbol

Note that vanilla `completing-read` returns DEF on empty input regardless of its type. For example,

```el
(progn
  (push ?\C-m unread-command-events)
  (completing-read "" (list "a" "b" "c") nil nil nil nil (current-buffer)))
```
returns a buffer object.

**Comment by yannvanhalewyn** [comment]
True! And with ivy enabled that returns an empty string, and has no completions. What especially matters in this issue IMO is the completions part.
