### ISSUE TITLE
feature request: per-command ivy-height customization

### ISSUE THREAD

**Issue by mookid** [abo-abo/swiper#1527]
Sometimes, depending on the command, you may want to increase the screen space devoted to completion.

An example of that: projectile-find-file.

You can do that with a advice around ivy-read (but what can't you do that way?) that dynamically binds the variable, but I feel like this should be better supported. 

Opinions?

**Comment by basil-conto** [comment]
Not the same issue, but just linking to #831 and #1146 for posterity.

**Comment by abo-abo** [comment]
> I feel like this should be better supported.

Agreed, I'll add this at some point. PRs welcome.

**Comment by mookid** [comment]
> Agreed, I'll add this at some point. PRs welcome.

I'll give it a try tonight.

**Comment by basil-conto** [comment]
Did #1531 address this issue?

**Comment by abo-abo** [comment]
Yes, thanks.
