### ISSUE TITLE
Minibuffer collapses to one line in terminal emacs

### ISSUE THREAD

**Issue by amosbird** [abo-abo/swiper#1528]
Hi,  when there is an active process-buffer in one frame, all other frames' ivy buffer collapse to one line. I've found a consitent way to reproduce.

Step to reproduce in terminal:

```lisp
make plain  (with -nw flag)
(add-hook 'minibuffer-setup-hook (lambda () (setq truncate-lines t)))
(make-process
 :name "foo"
 :connection-type 'pipe
 :coding 'no-conversion
 :command '("sleep" "100")
 :stderr "foostderr"
 :noquery t)
(make-frame-command)
(switch-to-buffer "foostderr")
press "C-x 5 o"
press "M-x"
```

![](https://la.wentropy.com/1S1o.png)

a somehow related issue https://github.com/abo-abo/swiper/issues/77

**Comment by basil-conto** [comment]
I sporadically see this under graphical Emacs, too, especially when performing Elisp completion in `eval-expression`. My usual workaround is to quit the current completion, invoke `counsel-M-x`, quit that, and go back to `eval-expression`.

**Comment by abo-abo** [comment]
> I sporadically see this under graphical Emacs

I think I saw it too. Would be nice to get a reproducible scenario.
