### ISSUE TITLE
counsel-M-x history issue

### ISSUE THREAD

**Issue by maximvl** [abo-abo/swiper#1530]
Hi, I have `counsel-M-x` set as my `M-x` action and it looks like this:
![](https://i.imgur.com/Sb5GqnT.png)

Now out of these functions:
`org-move-item-down` - I never used
`bmkp-autofile-all-tags-regexp-jump` - I never used
`magit-diff-popup` - I never used
`gnus-score-mode` - I never used
`desktop-save-in-desktop-dir` - I never used
`edebug-Trace-fast-mode` - I never used
`company-version` - I never used
`yas/about` - I never used
`bmkp-unlight-bookmark-here` - I never used.

So my question is it possible to adjust output to some functions I actually use based on usage history?

**Comment by abo-abo** [comment]
Yes. This will happen automatically if you have the `smex` package installed.

**Comment by maximvl** [comment]
@basil-conto yes, thanks to @abo-abo :)
