### ISSUE TITLE
case sensitivity difference between swiper and counsel-grep

### ISSUE THREAD

**Issue by shalin24** [abo-abo/swiper#1542]
Hi,

I use `counsel-grep-or-swiper` to be able to easily use `counsel-grep` for large files.
I like that by default `swiper` search is case-insensitive.

Why is `counsel-grep` case-sensitive by default?

**Comment by basil-conto** [comment]
> by default `swiper` search is case-insensitive

Not entirely; the default Ivy behaviour is to search case-insensitively only when the entire search string is lower-case. As soon as you enter upper-case letters, the search becomes case-sensitive. If you don't like this, you can customise the user option `ivy-case-fold-search-default`:

    ivy-case-fold-search-default is a variable defined in ‘ivy.el’.
    Its value is ‘auto’

    Documentation:
    The default value for ‘case-fold-search’ in Ivy operations.
    The special value ‘auto’ means case folding is performed so long
    as the entire input string comprises lower-case characters.  This
    corresponds to the default behaviour of most Emacs search
    functionality, e.g. as seen in ‘isearch’.

> Why is `counsel-grep` case-sensitive by default?

Because `grep` is. You can customise the user option `counsel-grep-base-command` to add the `-i` flag, but then all searches would unconditionally be case-insensitive. Perhaps `counsel-grep` can be changed to automatically add the `-i` flag when `ivy-case-fold-search-default` is either `t` or the input is entirely lower-case and `ivy-case-fold-search-default` is `auto`.

FWIW, what I do to get smart case folding with `counsel-grep` is use a command other than `grep`:
```el
(setq counsel-grep-base-command "ag --nocolor %s %s")
```

**Comment by basil-conto** [comment]
This issue made me notice something:

1. `make plain`
2. <kbd>C-x</kbd><kbd>C-f</kbd>`counsel.el`<kbd>RET</kbd>
3. <kbd>M-x</kbd>`counsel-grep`<kbd>RET</kbd>`regexp`
   ![plus](https://user-images.githubusercontent.com/9121222/39358562-6a9f78f4-4a0e-11e8-940f-feb3ab5d0b68.png)
   Note how `Regexp` (mixed-case) is highlighted in the search buffer but is not selectable as a candidate in the minibuffer.

**Comment by basil-conto** [comment]
Oh, this seems to be similar to #509. @abo-abo Should I report this there or create a new issue?

**Comment by shalin24** [comment]
> FWIW, what I do to get smart case folding with counsel-grep is use a command other than grep:
> 
> `(setq counsel-grep-base-command "ag --nocolor %s %s")`

Thanks @basil-conto, that works great!

**Comment by abo-abo** [comment]
@basil-conto Please create a new issue. I'm closing this one as resolved.

**Comment by Alexander-Shukaev** [comment]
```
  (define-advice counsel-grep-function
      (:around (function string) init)
    (if (ivy--case-fold-p string)
        (let ((counsel-grep-command (format counsel-grep-command "%s -i")))
          (funcall function string))
      (funcall function string)))
```

I think this suggestion better be implemented to have consistent behavior.

**Comment by basil-conto** [comment]
I wouldn't be against the addition of such a feature per se, but don't forget that Counsel's job is to provide a common and practical interface to various disparate tools such as `grep`, `ag`, `rg`, etc., not to bridge differences between these tools. Counsel gives users the freedom to choose their preferred tool and corresponding options, so the onus lies on the user to discover and configure the functionality they want, as was shown above.

**Comment by serycjon** [comment]
I have just encountered this inconvenience. Maybe it could be solved by (optionally) filtering the xyzgrep results with the ivy case sensitivity settings?

**Comment by abo-abo** [comment]
@serycjon Thanks, please test.

**Comment by serycjon** [comment]
@abo-abo Not what I meant, but this seems to work well for grep and solves the issue for me. Thanks! :)
