### ISSUE TITLE
match consecutive words

### ISSUE THREAD

**Issue by xin-jin** [abo-abo/swiper#1543]
Probably a silly question, but I couldn't find the answer. Say, if I swiper "no problem" in
"nothing whatever text is no problem"

The default matches the whole sentence, but I would like to match exactly the last two words. What is the proper way to do this? "no\b problem" could narrow the results, but it could still match something like 
"no nothing whatever text is no problem"

**Comment by dieggsy** [comment]
@xin-jin two spaces matches a literal space. type `no  problem` (two spaces between first o and p)

**Comment by basil-conto** [comment]
> two spaces matches a literal space

@xin-jin @dieggsy Note that this is currently specific to the default completion style [`ivy--regex-plus`](http://oremacs.com/swiper/#ivy--regex-plus) in [`ivy-re-builders-alist`](http://oremacs.com/swiper/#completion-styles). `ivy--regex-ignore-order`, for example, doesn't handle consecutive spaces specially.

> markdown doesn't seem to handle this properly

@dieggsy WDYM? Consecutive spaces are interpreted as a literal space under [`markdown-mode`](https://jblevins.org/projects/markdown-mode/) when starting from `make plain` for me.

**Comment by fabacino** [comment]
@basil-conto I think he was just refering to the fact that multiple spaces between two words are displayed as one within a github comment e.g. `seven       spaces`.

**Comment by basil-conto** [comment]
@fabacino Ah, right. Thanks and sorry about the noise.
