### ISSUE TITLE
Make counsel-fzf accept multiple search terms

### ISSUE THREAD

**Issue by niklascarlsson** [abo-abo/swiper#1544]
As an avid user of fzf in the terminal and vim I would love to see the possibility of counsel-fzf accepting multiple search terms.

As described on https://github.com/junegunn/fzf
"Unless otherwise specified, fzf starts in "extended-search mode" where you can type in multiple search terms delimited by spaces. e.g. ^music .mp3$ sbtrkt !fire "

This makes it possible to fuzzy match against multiple search terms and also specify match types such as ! for inverse exact match.

Currently counsel-fzf prints "error code 2" when multiple search terms are inserted with a space as delimiter.

**Comment by abo-abo** [comment]
Please give me a sample full command line input. I'm getting now:

    $ fzf -f foo bar
    unknown option: bar

**Comment by niklascarlsson** [comment]
If I make a directory that contains the following files:
```
foo # 1)
foo_bar # 2)
foo_bar_baz  # 3)
```
Then I can do the following searches
```sh
fzf -f "foo" #finds all three files
fzf -f "foo bar" # finds 2) and 3)
fzf -f "foo baz" # finds 3)
fzf -f "\!bar" # finds 1)
```
When using fzf without the -f flag, but instead through the default ctrl-t command then the exclamation doesn't need to be escaped, I don't know if that is possible to integrate in counsel-fzf, otherwise escaping it manually is not that hard :)

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by niklascarlsson** [comment]
Nice fix! Works like fzf in the terminal now, that's awesome :)
