### ISSUE TITLE
ivy-display-function-overlay conflicts with highlight-parentheses-mode

### ISSUE THREAD

**Issue by finalpatch** [abo-abo/swiper#1547]
If highlight-parentheses-mode is enabled and `point` is in parentheses,  ivy-display-function-overlay's pop up will have hl-paren-face.

To reproduce this, just install and enable highlight-parentheses-mode, then press C-M-i to complete a lisp function call.

In the linked image below, I was using default theme, so text color was supposed to be black, but everything looked red because highlight-parentheses-mode shows the inner most parentheses in red.

![Image of Yaktocat](https://zeupzw.ch.files.1drv.com/y4mHNfwXgrv8AkDYbnRbC_85dLhCo6-cCBavv9Q3JaO80Rw-aa4ubxealHRQnsd5OTV-9mip6RDSGSWn5VLPsAXOVMO5LtzfgkUic4xBluLsXh5Jvz6s4Y2aM37oBCliFWu2FuIyFSangeT9BMpJmvE64eRy1NaZwyTLkqzRzsEQyizKlBkzWYr48YJZwuVQP7vWFaK_SIgfAruIpWIPM9tRw?width=264&height=182&cropmode=none)

**Comment by basil-conto** [comment]
This looks similar to #1488.

**Comment by abo-abo** [comment]
Thanks, please test.
