### ISSUE TITLE
An interesting "issue" on font type in ivy-switch-buffer

### ISSUE THREAD

**Issue by oracleyue** [abo-abo/swiper#1549]
I enable `variable-pitch-mode` in my orgmode. Here is an interesting observation, in the list given by `ivy-switch-buffer`, it uses variable-width font for org files 😂 (I wish it keeps using the default monospace font, as everywhere in Ivy)

<img width="426" alt="screen shot 2018-05-01 at 21 47 39" src="https://user-images.githubusercontent.com/5046605/39490725-0816d586-4d8a-11e8-9e5d-f6cb9a4657b5.png">

**Comment by abo-abo** [comment]
Please provide some minimal code that can be loaded with `emacs -Q` to reproduce the issue.

**Comment by oracleyue** [comment]
@basil-conto  Ahh, got it, thanks!
