### ISSUE TITLE
swiper-helm not remembering last search

### ISSUE THREAD

**Issue by 098799** [abo-abo/swiper#1555]
After a search with `swiper` as my `C-s`, I can press `C-s` again to go back to the search, but can't do that with `swiper-helm` which forgets everything instantly.

Bug or feature?

**Comment by abo-abo** [comment]
Please re-open the issue with `swiper-helm`. Do note that `swiper-helm` is in maintenance mode unlike `swiper`. I have limited time and I don't use `swiper-helm`, so I only try to fix it if it's really broken and rely on PR for feature requests.
