### ISSUE TITLE
Amx support for counsel

### ISSUE THREAD

**Issue by Ergus** [abo-abo/swiper#1557]
I am wondering that smex is not actively maintained anymore and the new fork/substitution project is supposed to be amx that is very active right now.
Is it there any plan to support amx in a near/medium future? The interface is pretty much the same as I could see, so the implementation should be relatively simple.
Very thanks

**Comment by noctuid** [comment]
Amx supports using ivy already.

**Comment by Ergus** [comment]
Yes, but not counsel. Amx-mode can use Ivy by itself, but most if Ivy people are using counsel-M-x, which optionally uses smex to sort properly (calling smex functions internally out of the box). counsel-M-x checks if smex is installed, if so it calls the functions. Switching to avx is something barely simple, just change the prefixes in counsel.el (I tried) and it worked, but I don't feel confident enough in elisp programming to insert the support for both and make a pull request.

**Comment by abo-abo** [comment]
@Ergus 
If amx provides extra value compared to smex, I think it's a good idea to offer support for it. But keep in mind that, even though `smex` isn't actively maintained, it still does its job well.

> but I don't feel confident enough in elisp programming to insert the support for both and make a pull request

If a change in your config was enough to make it work, it's good enough for a PR. I'd be happy to review the code, give pointers for improvement and merge it. No pressure, of course.

**Comment by manuel-uberti** [comment]
@Ergus any update on this one? Looks really interesting :)

**Comment by Ergus** [comment]
Hi abo-abo sorry for the delay, I was too busy the last days. I just added a pull requests with the changes I did (rebasing master and cleaning up). Please, any suggestion/change/critic/comment will be very welcome, it is my first lisp code ever.
