### ISSUE TITLE
ivy-sort-functions-alist default does not have an effect?

### ISSUE THREAD

**Issue by raxod502** [abo-abo/swiper#1561]
The documentation of `ivy-sort-functions-alist` claims that the function associated with `t` is used for fall-through cases:

```elisp
(defcustom ivy-sort-functions-alist
  '((read-file-name-internal . ivy-sort-file-function-default)
    (internal-complete-buffer . nil)
    (counsel-git-grep-function . nil)
    (Man-goto-section . nil)
    (org-refile . nil)
    (t . string-lessp))
  "An alist of sorting functions for each collection function.
Interactive functions that call completion fit in here as well.

Nil means no sorting, which is useful to turn off the sorting for
functions that have candidates in the natural buffer order, like
`org-refile' or `Man-goto-section'.

A list can be used to associate multiple sorting functions with a
collection.  The car of the list is the current sort
function.  This list can be rotated with `ivy-rotate-sort'.

The entry associated with t is used for all fall-through cases.

See also `ivy-sort-max-size'.")
```

This does not seem to be the case. For example, with no specific customizations, the following code:

```elisp
(ivy-read "Select a letter: " '("b" "c" "a") :sort t)
```

presents a menu with candidates in the order:

```
b
c
a
```

when `ivy-sort-functions-alist` says that the candidates should be sorted using `string-lessp`, which would result in:

```
a
b
c
```

Is this expected behavior?

**Comment by raxod502** [comment]
Further testing reveals that the following code does not produce sorting either:

```elisp
(ivy-read "Select a letter: " '("b" "c" "a") :sort #'string-lessp)
```

**Comment by raxod502** [comment]
And apparently declaring the list as a "dynamic collection" makes the sorting work. What's going on?

```elisp
(ivy-read "Select a letter: " (lambda (_) (list "b" "c" "a"))
          :sort t
          :dynamic-collection t)
```

**Comment by raxod502** [comment]
Suggested fix: https://github.com/abo-abo/swiper/pull/1562

**Comment by basil-conto** [comment]
> Further testing reveals that the following code does not produce sorting either:

I'm not sure how `ivy--sort-maybe` (which is touched in #1562) comes into the picture, but `ivy--reset-state` unconditionally interprets the `:sort` keyword as a boolean, not a function.

**Comment by raxod502** [comment]
Yes, I noticed that whether `:sort` is a boolean or a function seems to depend on which part of the codebase you look at. It's only documented to act as a boolean, but it does act as a function for dynamic collections at least. Perhaps that's another point for improvement.
