### ISSUE TITLE
Ripgrep can't search for curly braces

### ISSUE THREAD

**Issue by fbkarsdorp** [abo-abo/swiper#1566]
I'm using `counsel-grep-or-swiper` with `"rg -i -M 120 --no-heading --line-number --color never %s %s"` as `counsel-grep-base-command`. Everythings appears to work smoothly, but any search which includes curly braces fails, returning no results. It appears to be something related to ripgrep, because replacing `counsel-grep-base-command` to search with ag using `"ag --nocolor --nogroup %s %s"` does work. Any thoughts on why this may be?

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by fbkarsdorp** [comment]
Yes, that appears to work. Thanks. However... it's still not possible to search for curly braces as part of a regular expression, e.g. `^\{.*?\}` fails with no results. And again, this _is_ possible with ag.
