### ISSUE TITLE
Question: how to select non-first match

### ISSUE THREAD

**Issue by bixuanzju** [abo-abo/swiper#158]
Hi, I am starting to replace `isearch` with `swiper`. One problem i encounter is how to select non-first match, for instance, in a line

> buffer buffer

search `buffer` would select the first match, but i have no way to jump to the second match in the same line.

**Comment by abo-abo** [comment]
You can press <kbd>C-'</kbd> to jump to a candidate with `avy`. I think this is the only way to select the second match on one line.
