### ISSUE TITLE
[Feature Request]  Add ivy-yank-char as ivy-yank-word. 

### ISSUE THREAD

**Issue by zw963** [abo-abo/swiper#1588]
Thanks

**Comment by basil-conto** [comment]
Maybe its just me, but I'm not sure I understand what you're asking. Can you please elaborate in more details? Are you asking for the addition of a command that is similar to `ivy-yank-word`, but which only yanks a single character, rather than a whole word?

**Comment by zw963** [comment]
> Are you asking for the addition of a command that is similar to ivy-yank-word, but which only yanks a single character, rather than a whole word?

Yes, as `isearch-yank-char` and `isearch-yank-word` in `isearch-mode`, we have latter, but missing former, i select current content will two command combinding.

**Comment by abo-abo** [comment]
Fixed now, closing.
