### ISSUE TITLE
implicit order of items in projectile-completition-system ivy mode

### ISSUE THREAD

**Issue by kacurez** [abo-abo/swiper#159]
I'm not sure whether this is an issue only of ivy/projectile but I will start asking here:
When I use default projectile completition system(`ido`) and execute e.g. `projectile-switch-project` it shows me ordered list according to the last items used(most recent projects), but when I use `ivy` it shows me list ordered alphabetically which is not desired behaviour. It looks like ivy implicitly sorts the list alphabetically on the beginning of any ivy completition command. I would like to have this list untouched unless I start typing(i.e. searching..)
I think the same applies to any other command using ivy as completition system(e.g. projectile-find-files).

Is it possible to suppress such behaviour if I don't want it?

**Comment by abo-abo** [comment]
> Is it possible to suppress such behaviour if I don't want it?

Sure, just use this to turn off the sorting:

```elisp
(add-to-list
 'ivy-sort-functions-alist
 '(projectile-switch-project . nil))
```

You can even use a custom sorting function instead of `nil`.

**Comment by kacurez** [comment]
great, it works! Even though I would personally prefer to have this ivy functionality(default alphabetical order) turned off by default for all commands, but it's hard to say what is preferred for others. Maybe there some use cases which I am not aware of but I assume there are more commands with their specific ordering and if a command does not have any it will(probably) return the list in alphabetical order by itself.

thank you!

**Comment by abo-abo** [comment]
> Even though I would personally prefer to have this ivy functionality(default alphabetical order) turned off by default for all commands, but it's hard to say what is preferred for others

I had a request from another user to enable sorting by default.  I actually like the sorting for example for `describe-function` and `describe-variable`: you can see the items related to your current candidate.

**Comment by abo-abo** [comment]
> thank you!

you're welcome :)
