### ISSUE TITLE
Next/Previous hostname when using find-file in ivy-mode

### ISSUE THREAD

**Issue by Toby-Haynes** [abo-abo/swiper#1590]
I often need to edit files in the same path on multiple hosts. 

e.g. 
/ssh:root@host105:/etc/hosts
/ssh:root@host106:/etc/hosts
/ssh:root@host107:/etc/hosts

The fastest way for me to do this right now is to generate a list of (find-file "/ssh:root@host105:/etc/hosts") statements in *scratch* and execute them in turn - not exactly very efficient.

Suggestions: add a mechanism to "rotate" to next/previous host names, either 
- ) automagically (i.e. identify non-numeric prefix and increment/decrement the numeric bit) or 
- ) via a customized list of hosts  (defcustom ).

**Comment by basil-conto** [comment]
> Suggestions: add a mechanism to "rotate" to next/previous host names

A simpler approach could also be to allow navigating and editing the current filepath being completed, as is possible in vanilla Emacs (I'm pretty sure there's an existing issue for that somewhere, but I'm not able to search at the moment).

**Comment by basil-conto** [comment]
See also #1424.

**Comment by abo-abo** [comment]
You can now paste the current path with <kbd>C-M-y</kbd>, so that it becomes editable. So I think we can close this.
