### ISSUE TITLE
`ivy-thing-at-point` cannot be extended or customized

### ISSUE THREAD

**Issue by FelipeLema** [abo-abo/swiper#1594]
Right now, I'd like to customize the behaviour of `ivy-thing-at-point` and I can't do it without changing/forking the original code.

My main concern with `ivy-thing-at-point` is that it captures the string in the `string-match` clause (in it's `cond` block) with text properties, whereas I'd like it to capture it **without** these properties. Perhaps have a `ivy-thing-at-point-getter` (customizable) variable.

I know performance is a main concern for @abo-abo, but this would be a one-time call at the start of an ivy command, so the earlier shouldn't impacted.

(thanks for doing a great job here, btw).

**Comment by basil-conto** [comment]
> Right now, I'd like to customize the behaviour of `ivy-thing-at-point` and I can't do it without changing/forking the original code.

If this is for your own purposes, then there's always function advice; see [`(elisp) Advising Functions`](https://www.gnu.org/software/emacs/manual/html_node/elisp/Advising-Functions.html). For example:

```el
(advice-add 'ivy-thing-at-point :filter-return #'substring-no-properties)
```

> My main concern with ivy-thing-at-point is that it captures the string in the string-match clause (in it's cond block) with text properties, whereas I'd like it to capture it without these properties.

Is there any significance to those text properties @abo-abo?

**Comment by abo-abo** [comment]
Thanks, the text properties are now stripped. I'm not opposed to making `ivy-thing-at-point` customizable. But only if needed, and your concern appears to be addressed now.

**Comment by FelipeLema** [comment]
it is. thanks
