### ISSUE TITLE
highlight color

### ISSUE THREAD

**Issue by lemon0910** [abo-abo/swiper#1596]
when I use ivy, there are too many highlight colos that sometimes I can't see world clearly. For example, I search "hellohi", I input "he hi", it will highlight 'he' and 'hi' using two different colors, how can I only use one hightlight colors? Is there some setting?

**Comment by manuel-uberti** [comment]
Can you post a screenshot? Just curious to understand if it's a specific theme problem.

**Comment by lemon0910** [comment]
![jietu20180525-144016](https://user-images.githubusercontent.com/3163925/40529995-a3b79a00-6029-11e8-8971-647a275dca07.jpg)
You can see, It use three color, I think one color is enough

**Comment by manuel-uberti** [comment]
Could you try the same with `emacs -Q`?

**Comment by lemon0910** [comment]
![jietu20180525-173556 2x](https://user-images.githubusercontent.com/3163925/40537690-23a666e8-6042-11e8-8996-b4d9484e0af8.jpg)
When I use helm, It all uses one color, this is what I want.

**Comment by Purring** [comment]
You can customize the colors with `M-x customize`  -> `ivy-faces` and look for `ivy minibuffer faces`

**Comment by basil-conto** [comment]
> You can customize the colors with `M-x customize` -> `ivy-faces` and look for `ivy minibuffer faces`

AKA

<kbd>M-x</kbd>`customize-group`<kbd>RET</kbd>`ivy-faces`<kbd>RET</kbd>

or, if you don't care about other faces,

<kbd>M-x</kbd>`customize-variable`<kbd>RET</kbd>`ivy-minibuffer-faces`<kbd>RET</kbd>.

**Comment by basil-conto** [comment]
Not entirely related (because this issue is about the number of colours used, not their blending), but see also #1533.
