### ISSUE TITLE
ivy-bibtex gives different hits depending on order of terms

### ISSUE THREAD

**Issue by eeenilsson** [abo-abo/swiper#1599]
Ivy-bibtex gives different hits depending on order of terms, ie "zhang hemoglobin" gives a different number of list items than "hemoglobin zhang".

I brought this up in tmalsburg/helm-bibtex#215. The problem seems to be inherited from Ivy and it was suggested I open an issue here.

Thanks for the good work!

**Comment by basil-conto** [comment]
Can you please post your value for `ivy-sort-functions-alist`? My crystal ball tells me you are using the default [completion style](http://oremacs.com/swiper/#completion-styles), namely [`ivy--regex-plus`](http://oremacs.com/swiper/#ivy--regex-plus), which is sensitive to the order of space-delimited search terms you input.

If you want order-insensitive search, you can use [`ivy--regex-ignore-order`](http://oremacs.com/swiper/#ivy--regex-ignore-order) instead, either globally:

```el
(with-eval-after-load 'ivy
  (setf (alist-get t ivy-re-builders-alist) #'ivy--regex-ignore-order))
```

locally (i.e. only for `ivy-bibtex`):

```el
(with-eval-after-load 'ivy
  (setf (alist-get 'ivy-bibtex ivy-re-builders-alist)
        #'ivy--regex-ignore-order))
```

or temporarily (i.e. for a single call of `ivy-bibtex`), by typing <kbd>C-o</kbd> during completion (requires the `ivy-hydra` package), followed by as many repetitions of <kbd>m</kbd> are needed until you see `m: matcher order`.

See also https://emacs.stackexchange.com/a/36748/15748 for a related explanation.

**Comment by eeenilsson** [comment]
Indeed, the variable ivy-re-builders-alist had the value ((t . ivy--regex-plus)), so that is likely the problem.

Thank you very much for the help!

**Comment by basil-conto** [comment]
If any of the suggestions above solves this issue, then please close it.

**Comment by eeenilsson** [comment]
Now tested a bit more. The above did not solve the issue specifically in ivy-bibtex where author name still had to come before other search terms (which could be in any order) to give hits.  Adding the the following did solve the problem:

```
(setq ivy-re-builders-alist
      '((ivy-bibtex . ivy--regex-ignore-order)
        (t . ivy--regex-plus)))
```
```
