### ISSUE TITLE
go to beginning of buffer

### ISSUE THREAD

**Issue by bixuanzju** [abo-abo/swiper#16]
First of all, thanks for the wonderful package.

One obtrusive thing I notice is that every time I call `swiper` command, it will first go to the beginning of the buffer. Is this some sort of intended feature?

Also it would be great if the search word can be read off at point.

**Comment by abo-abo** [comment]
> Is this some sort of intended feature?

No, it's just part of unimplemented code showing.  It should not happen for `helm` back end. I just
have to implement the anchoring algorithm for `ivy`, I've mentioned what still needs to be done
[in a post](http://oremacs.com/2015/03/13/introducing-ivy/). I'll try to fix this as soon as possible.

> Also it would be great if the search word can be read off at point.

That's easily achievable with this short code:

```cl
(swiper (thing-at-point 'symbol))
```

I'm not yet sure if it should be the default behavior of
<kbd>C-u</kbd> `swiper`, or if something like this should be bound
to <kbd>C-w</kbd> in `swiper` keymap, similar to `isearch`.

**Comment by dgutov** [comment]
> I'm not yet sure if it should be the default behavior of C-u swiper, or if something like this should be bound to C-w in swiper keymap, similar to isearch.

The last time a similar question was brought up, I've been told it's a good taste to set up a "virtual" history element the user can access by pressing `M-n`. Take a look at `minibuffer-default-add-function` usage in `read-file-name-default`.

Helm also has a similar behavior: https://github.com/emacs-helm/helm/wiki#51-yanking-text

**Comment by abo-abo** [comment]
@dgutov, thanks for the suggestion.  Although for some reason <kbd>M-n</kbd> will put the point on
the start of the input instead of at the end.

Also, the history saves the full candidates by default. Do you know how I could make it save only
the partial inputs instead of the full lines?

**Comment by dgutov** [comment]
Sorry, no ideas. This area is pretty new to me too.
