### ISSUE TITLE
Adding a new source (a list of file paths) to ivy-switch-buffer

### ISSUE THREAD

**Issue by sewkokot** [abo-abo/swiper#1603]
I would like to add a list of my frequently used files specified in my-files-list to ivy-switch-buffer similar to recentf virtual buffers. I do the following:
```
(setq my-files-list '("~/file-a.txt" "~/file-b.txt"))

(defun my-files-ivy ()
  my-files-list)

(ivy-set-sources
 'ivy-switch-buffer
 '((my-files-ivy)
   (original-source)))
```
However it does not work since those file-a.txt and file-b.txt files are not opened, instead new empty buffers with those names in my-files-list are created.
Any help to make it work?

**Comment by basil-conto** [comment]
Some suggestions off the top of my head, in order of increasing complexity:
1. * Set user option `ivy-use-virtual-buffers` to a non-`nil` value.
   * Save `~/file-a.txt` and `~/file-b.txt` as [`(emacs) Bookmarks`](https://www.gnu.org/software/emacs/manual/html_node/emacs/Bookmarks.html) (or ensure they are always in your `recentf-list`).
   These files will then show up as virtual buffers in `ivy-switch-buffer` completion.
2. ```diff
   diff --git a/ivy.el b/ivy.el
   index f357de3..c96359e 100644
   --- a/ivy.el
   +++ b/ivy.el
   @@ -3645,9 +3645,8 @@ ivy--switch-buffer-action
            (switch-to-buffer ivy-text nil 'force-same-window)
          (let ((virtual (assoc buffer ivy--virtual-buffers))
                (view (assoc buffer ivy-views)))
   -        (cond ((and virtual
   -                    (not (get-buffer buffer)))
   -               (find-file (cdr virtual)))
   +        (cond ((not (get-buffer buffer))
   +               (find-file (if virtual (cdr virtual) buffer)))
                  (view
                   (delete-other-windows)
                   (let (;; Silence "Directory has changed on disk".
   ```
   The problem with this is that contents of `my-files-list` will appear as-is in `ivy-switch-buffer` completion, i.e. with unexpanded paths and without the `ivy-virtual` face.
3. Add a user option specifying files to add to the `recentf` and bookmark results returned by `ivy--virtual-buffers`.
4. Rethink how Ivy sources interplay with buffer completion.

**Comment by sewkokot** [comment]
Thank you @basil-conto. For now I opt for the first solution. Just one line in my init.el file solves the problem:
```
  (setq recentf-list (delete-dups (append recentf-list my-files-list)))
```

**Comment by basil-conto** [comment]
Can this issue be closed then, or do you think Ivy should do something differently?

**Comment by sewkokot** [comment]
If someone else find the work-around solution unsatisfactory the issue can be reopen. For now the solution works for me so I close this issue.
