### ISSUE TITLE
counsel-up-directory inside counsel-file-jump?

### ISSUE THREAD

**Issue by zarybnicky** [abo-abo/swiper#1605]
Hi,

I'm trying to get the functionality of `counsel-up-directory` in `counsel-file-jump`. I've been trying to replicate the functionality of `flx-ido` for find-file in ivy/counsel (I've switched recently, and this is the only thing I really miss), but I haven't had any luck finding existing solutions. After trying to get fuzzy matching on files inside subdirectories with counsel-find-file and failing, I found counsel-file-jump which I'm now trying to pressure into doing what I want :)

I'm not very well versed in ELisp, but the easiest solution I see is to write `counsel-file-jump-up-directory` that restarts `counsel-file-jump` with `default-directory` set one higher. The other solution - one that I'll try to get used to in the meantime - is to use counsel-file-jump with initial-directory, or projectile-find-file.

**Comment by basil-conto** [comment]
A simple way of achieving this is via a custom [action](http://oremacs.com/swiper/#actions):

```el
(ivy-add-actions #'counsel-file-jump
                 '(("u" my-counsel-parent-jump "up directory")))

(defun my-counsel-parent-jump (_)
  "Restart `counsel-file-jump' from parent directory.
Current input is maintained."
  (counsel-file-jump ivy-text
                     (file-name-directory
                      (directory-file-name default-directory))))
```

This allows you to type <kbd>M-o</kbd><kbd>u</kbd> during `counsel-file-jump` completion to restart it from the parent directory. @abo-abo Thoughts on providing something like this by default?

**Comment by zarybnicky** [comment]
Thanks for the quick response. Yes, that answers my question - it's something (I hope) I'd have eventually gotten to after staring into the ivy source for a while :)

**Comment by abo-abo** [comment]
It appears that this issue can be closed. @basil-conto thanks for helping out. @zarybnicky have fun with Ivy:)
