### ISSUE TITLE
kill buffer during ivy-switch-buffer problem with uniquify

### ISSUE THREAD

**Issue by hyOzd** [abo-abo/swiper#1609]
I use uniquify package to manage conflicting buffer names from different projects. When I have two files opened from two different projects I have their buffer names like this:

```
filename.c | projectA
filename.c | projectB
```

I initiate buffer switching with `ivy-switch-buffer` but instead of selecting a buffer, first I kill one of the buffers with `C-c C-k`, buffer is killed and removed from the selection list as expected. Then I select the other one that is left. Instead of displaying the buffer contents I see an empty buffer! 

I think the problem is, when I kill the first buffer other buffers name changes (back to just `filename.c`) and ivy isn't aware of that until ivy-switch-buffer is triggered again. Because opened *empty* buffer still has the old *uniquified* name and when I try to switch again this time buffer is listed as `filename.c` and switching to it works fine.

Here is my uniquify configuration:
```elisp
(use-package uniquify
  :ensure nil ;; built-in
  :config
  (setq uniquify-buffer-name-style 'post-forward)
  (setq uniquify-separator "|")
  (setq uniquify-after-kill-buffer-p t))
```

**Comment by abo-abo** [comment]
Thanks for the report. From what I see, `uniquify-kill-buffer-function` is indeed run. The problem is that `ivy-switch-buffer-kill` uses the static list of buffers and just removes the existing buffer from it.

Doing something like this should fix the issue:

```elisp
(defun ivy-switch-buffer-kill ()
  "Kill the current buffer in `ivy-switch-buffer'."
  (interactive)
  (let ((bn (ivy-state-current ivy-last)))
    (when (get-buffer bn)
      (kill-buffer bn))
    (unless (buffer-live-p (ivy-state-buffer ivy-last))
      (setf (ivy-state-buffer ivy-last)
            (with-ivy-window (current-buffer))))
    (setf (ivy-state-preselect ivy-last) ivy--index)
    (setq ivy--old-re nil)
    ;; (setq ivy--all-candidates (delete bn ivy--all-candidates))
    (setq ivy--all-candidates (ivy--buffer-list "" ivy-use-virtual-buffers nil))
    (ivy--exhibit)))
```

@hyOzd Can you test this fix?

**Comment by hyOzd** [comment]
@abo-abo this works! When I kill the `buffer | proj A` I see that other buffers name is updated in the ivy list immediately. Thanks!

**Comment by hyOzd** [comment]
Sorry that `closed` was a misclick.

**Comment by ilohmar** [comment]
The code is refactored, but this fix is still necessary.  I'm gonna prepare a PR, soon, I hope.

**Comment by abo-abo** [comment]
Thanks.
