### ISSUE TITLE
Can I use `counsel-find-file` to open a file in another window?

### ISSUE THREAD

**Issue by mrbig033** [abo-abo/swiper#1610]
I have this functionality with `fzf` on Vim, and I wonder if I could do the same with Ivy. When I select a file to be opened, I have a binding to open it in vertical split, and another horizontal.

**Comment by basil-conto** [comment]
> Can I use `counsel-find-file` to open a file in another window?

Yes, when you have navigated to the file you want to visit, type <kbd>M-o</kbd><kbd>j</kbd>; see [`(ivy) Actions`](http://oremacs.com/swiper/#actions).

**Comment by mrbig033** [comment]
Thanks! Closing the issue.
