### ISSUE TITLE
counsel-rg "No matches found" when moving point past end of line

### ISSUE THREAD

**Issue by raxod502** [abo-abo/swiper#1622]
Starting from `emacs -Q`, if I run `M-x counsel-rg` and enter a query with some matches:

![image](https://user-images.githubusercontent.com/6559064/41389249-f54e90da-6f4c-11e8-9d36-c0e582e37e96.png)

and then I press `<right>` then I get this:

![image](https://user-images.githubusercontent.com/6559064/41389255-fd7c5f62-6f4c-11e8-9e13-96fc11229c53.png)

Pressing `<left>` gets me the correct list back.

**Comment by basil-conto** [comment]
Doesn't that happen with all Ivy completion? (I'm pretty sure I've seen this mentioned in a past issue/PR.)

**Comment by abo-abo** [comment]
Thanks.
