### ISSUE TITLE
ivy-alt-done confused by files with common prefix

### ISSUE THREAD

**Issue by basil-conto** [abo-abo/swiper#1623]
The following recipe is based on a report by @drrlvn in #1102:

1. `make plain`
2. <kbd>C-x</kbd><kbd>d</kbd>`//tmp`<kbd>RET</kbd>
3. <kbd>+</kbd>`foo`<kbd>RET</kbd>
4. <kbd>C-x</kbd><kbd>C-f</kbd>`foobar`<kbd>RET</kbd>
5. <kbd>C-x</kbd><kbd>C-s</kbd>
6. <kbd>C-x</kbd><kbd>k</kbd><kbd>RET</kbd>
7. <kbd>C-x</kbd><kbd>C-f</kbd>`foo`
8. <kbd>C-n</kbd><kbd>C-j</kbd>
   * Expected result: file `/tmp/foobar` is visited.
   * Actual result: file name completion continues in directory `/tmp/foo/`.

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by basil-conto** [comment]
Thanks, works for me.
