### ISSUE TITLE
counsel and swiper require emacs 24.4

### ISSUE THREAD

**Issue by JohnLunzer** [abo-abo/swiper#1629]
However, both counsel.el and swiper.el state that they require 24.1.

The culprit in both cases is the `string-trim-right` function called in only a few places. This is a very small function and it seems like a shame to give up a few minor versions of backward compatibility over a minor dependency. 

Anyway... I'm not advocating, just providing you information. I've provided the function below which I copied from the [emacs-mirror github page](https://github.com/emacs-mirror/emacs/blob/master/lisp/emacs-lisp/subr-x.el).

```emacs
(defsubst string-trim-right (string &optional regexp)
  "Trim STRING of trailing string matching REGEXP.
REGEXP defaults to  \"[ \\t\\n\\r]+\"."
  (if (string-match (concat "\\(?:" (or regexp "[ \t\n\r]+") "\\)\\'") string)
      (replace-match "" t t string)
    string))
```

**Comment by basil-conto** [comment]
See also #1579. I've already fixed the misuse of `subr-x`, just haven't created a coherent PR yet, FWIW.

**Comment by basil-conto** [comment]
Note also that `defsubst` should generally be avoided, as its pitfalls usually outweigh its benefits in new code, and that use of `replace-match` is less efficient than using `substring` (see my last patch here: https://lists.gnu.org/archive/html/emacs-devel/2018-06/msg00100.html).

**Comment by basil-conto** [comment]
> This is a very small function and it seems like a shame to give up a few minor versions of backward compatibility over a minor dependency.

Agreed. `subr-x` is too experimental or not generally useful enough to use in packages which aim to support Emacs 24 or earlier.

**Comment by abo-abo** [comment]
I vaguely remember trying to compile emacs-24.1 from sources on Ubuntu 16.04, and I could not manage to do it. I did manage to build emacs-24.3 just fine though.  And I think `emacs-24.3` is the version commonly provided by the `emacs24` package on Debian derivatives. So I think the way to go is to bump the minimum version to 24.3, which is already the case for counsel.el. Please correct me if I got it wrong somewhere.

**Comment by basil-conto** [comment]
I would be in favour of bumping the minimum required version, but I think `subr-x` can (and mostly should) be avoided regardless. Note that Debian Stable provides Emcas 24.5, OldStable provides Emacs 24.4, and `string-trim-{right,left}` were only added in Emacs 24.4.

**Comment by abo-abo** [comment]
> I think subr-x can (and mostly should) be avoided regardless

`string-trim-right` is a useful enough function. Why should we avoid using it?

**Comment by basil-conto** [comment]
Note also that, with any of the string manipulation functions, one saves **at most** 2 trivial lines of code.

**Comment by abo-abo** [comment]
> Note also that, with any of the string manipulation functions, one saves at most 2 trivial lines of the type of code (regexp matching) that the Swiper project already makes extensive use of.

Agreed. Although if we see those 2 trivial lines repeating all over the place, we might want to extract them into e.g. `swiper--string-trim`.

**Comment by basil-conto** [comment]
> if we see those 2 trivial lines repeating all over the place, we might want to extract them into e.g. `swiper--string-trim`

Oh, absolutely.
