### ISSUE TITLE
read-file-name ignores mustmatch

### ISSUE THREAD

**Issue by SkySkimmer** [abo-abo/swiper#1631]
In `emacs -Q` try `(read-file-name "fooba: " nil nil t)`, type some random characters and hit enter, it will not proceed and will complain.
Now enable ivy, it will proceed returning whatever you typed.

**Comment by basil-conto** [comment]
Looks like the `cond` fallthrough in `ivy-done` is a bit too eager. Another misbehaving example:

```el
(progn
  (setq unread-command-events '(?c ?\C-m))
  (completing-read "" '("a" "b") nil 'confirm))
```

This should have asked for confirmation before exiting with `"c"`.

By the way @abo-abo, why does `ivy-done` check that `confirm-nonexistent-file-or-buffer` is `t`? The user option's docstring says that any non-`nil` value, except for the special value 'after-completion`, should result in a confirmation request (`after-completion` is like the `confirm-after-completion` argument to `completing-read`, which makes the confirmation request subject to the way by which completion exited).
