### ISSUE TITLE
add-face-text-property requires emacs 24.4

### ISSUE THREAD

**Issue by JohnLunzer** [abo-abo/swiper#1634]
Similarly to previously reported issue, ivy.el uses `add-face-text-property` which was introduced in 24.4, but ivy.el currently states that it requires 24.1. 

I ran into an error when using ivy-rich's version of ivy-switch-buffer, when I type in a search pattern that doesn't exist. ivy-rich doesn't call `add-face-text-property`, so I believe ivy is the culprit. 

It looks like in a couple places in ivy.el that there is a check for `add-face-text-property` and using an alternative when appropriate but in`ivy--insert-prompt` it looks like it is being used without an alternative option. Though, I'm not entirely sure this is where I'm seeing my error.

Any advice on how I can eliminate all calls to `add-face-text-property`? the one in `ivy--insert-prompt` looks tricky because it says it's actually _removing_ some property so I'm not sure I can just drop in `font-lock-append-text-property` as is being done elsewhere.

**Comment by basil-conto** [comment]
As an aside, the docstring of `ivy-display-style` states:

    This setting depends on `add-face-text-property' - a C function
    available as of Emacs 24.5.  Fancy style will render poorly in
    earlier versions of Emacs.

and its default value is predicated on `(version< emacs-version "24.5")`, but `add-face-text-property` was actually added in Emacs 24.4; see <kbd>M-:</kbd>`(view-emacs-news "24.4")`<kbd>RET</kbd> and commit [708e05f6d1b39313a63e34a5b4e1a16ae809ae25](https://git.savannah.gnu.org/cgit/emacs.git/commit/?id=708e05f6d1b39313a63e34a5b4e1a16ae809ae25).

**Comment by JohnLunzer** [comment]
Well, against my better judgement I tried to modify the call to `add-face-text-property` inside `ivy--insert-prompt` to call `ivy-add-face-text-property` instead and **it seems to work**. My `ivy-switch-buffer` no longer breaks on no matches and recovers when I backspace to a matching string. 

My exact call is: 
```emacs
(ivy-add-face-text-property (minibuffer-prompt-end) (line-end-position) 'ivy-prompt-match (current-buffer))
```

If somebody could test this change to ensure I'm not just hiding the error I would appreciate it.

**Comment by basil-conto** [comment]
@JohnLunzer 

> I'm not entirely sure this is where I'm seeing my error.

You can get an error backtrace by first enabling <kbd>M-x</kbd>`toggle-debug-on-error`<kbd>RET</kbd>.

**Comment by basil-conto** [comment]
@abo-abo Another thing that's confusing me is the function `ivy--add-face`:

```el

(defun ivy--add-face (str face)
  "Propertize STR with FACE.
`font-lock-append-text-property' is used, since it's better than
`propertize' or `add-face-text-property' in this case."
  (require 'colir)
  (condition-case nil
      (progn
        (colir-blend-face-background 0 (length str) face str)
        (let ((foreground (face-foreground face)))
          (when foreground
            (add-face-text-property
             0 (length str)
             `(:foreground ,foreground)
             nil
             str))))
    (error
     (ignore-errors
       (font-lock-append-text-property 0 (length str) 'face face str))))
  str)
```

Its docstring claims that `font-lock-append-text-property` is preferred over `add-face-text-property` here, and yet the implementation uses the former only as a fall back for the latter. Which is correct, the docstring or the implementation?

**Comment by abo-abo** [comment]
Thanks

**Comment by abo-abo** [comment]
@basil-conto

> Its docstring claims that font-lock-append-text-property is preferred over add-face-text-property here, and yet the implementation uses the former only as a fallback for the latter. Which is correct, the docstring or the implementation?

It's kind of both, I think. `add-face-text-property` bit is only valid for faces with custom foregrounds, a rare case. And the docstring refers to using `font-lock-append-text-property` and not `add-face-text-property` again in the fallback case. Feel free to make the doc more clear, basically it says we should not try to call `add-face-text-property` twice instead of once. It's also possible to remove the confusing part of the doc altogether.

**Comment by basil-conto** [comment]
A follow-up question is, if `font-lock-append-text-property` is only intended to be used when `add-face-text-property` is not defined as a function, then why don't we use `ivy-add-face-text-property` here?

**Comment by abo-abo** [comment]
> The docstring says nothing about falling back on font-lock-append-text-property, but rather suggests that font-lock-append-text-property is the preferred function for propertising STR with FACE, for some reason.

I think the reason is the historical deterioration of the docstring. Initially, no color blending was available and `font-lock-append-text-property` was the whole body.

**Comment by basil-conto** [comment]
> I think the reason is the historical deterioration of the docstring. Initially, no color blending was available and `font-lock-append-text-property` was the whole body.

OK, so should that sentence be removed completely then? Why `font-lock-append-text-property` instead of `font-lock-prepend-text-property`, which AIUI is closer to what `add-face-text-property` does with an `APPEND` argument of `nil`?

**Comment by abo-abo** [comment]
> OK, so should that sentence be removed completely then?

Yes, seems like the best solution:)

> OK, so should that sentence be removed completely then? Why font-lock-append-text-property instead of font-lock-prepend-text-property, which AIUI is closer to what add-face-text-property does with an APPEND argument of nil?

Ivy tries to show the candidates in the minibuffer with their existing text properties while adding its own text properties to highlight matches. It's not clear if an append or a prepend is more appropriate, because it's not clear if the original text properties or the highlights are more important for the user.

**Comment by basil-conto** [comment]
> Yes, seems like the best solution:)

OK, I'll add that to a future cleanup PR if no-one changes it before then.

> Ivy tries to show the candidates in the minibuffer with their existing text properties while adding its own text properties to highlight matches. It's not clear if an append or a prepend is more appropriate, because it's not clear if the original text properties or the highlights are more important for the user.

OK, I'll leave it alone then. :)
