### ISSUE TITLE
Creating new files alongside existing files with similar name

### ISSUE THREAD

**Issue by nordlow** [abo-abo/swiper#1636]
If I have an existing file named `x.txt` in a directory how can I open a new file `yx.txt` in the same directory? The completion engine in my current settings is too forgiving and completes the new file opening of `yx.txt` to open the existing file `x.txt`.

**Comment by neojski** [comment]
See [ivy-immediate-done](http://oremacs.com/swiper/), i.e. press <kbd>C-M-j</kbd>.

**Comment by nordlow** [comment]
Ok, thanks. However, I would prefer to have an option that mimics the default Minibuffer completion settings of Vanilla Emacs so I don't have to remember yet another key binding. Is this possible?

**Comment by manuel-uberti** [comment]
Could this be of any help? https://github.com/abo-abo/swiper/wiki/ido-style-folder-navigation

**Comment by abo-abo** [comment]
See also `ivy-use-selectable-prompt`.

**Comment by manuel-uberti** [comment]
@nordlow is this solved for you?

**Comment by nordlow** [comment]
Change value of `ivy-use-selectable-prompt` from `t` to `nil` had no effect for me.

**Comment by abo-abo** [comment]
@nordlow

> Changing value of ivy-use-selectable-prompt from t to nil had no effect on the behaviour of return in minibuffer for the case described above.

How to use `ivy-use-selectable-prompt`:

1. `(setq ivy-use-selectable-prompt t)`
2. Enter a file name, press up or <kbd>C-p</kbd> to select the prompt and press <kbd>RET</kbd>.

> works only partially as expected when being used to Vanilla Emacs.

It's not Ivy's intention to emulate Vanilla Emacs. I mean it's nice when we can do it, but the primary goal is to provide a consistent and intuitive completion interface. With this goal, binding <kbd>RET</kbd> to `ivy-alt-done` is the only good option.

If you still want to make your customization, you should add some extra code:

```elisp
(define-key ivy-minibuffer-map (kbd "C-j") #'ivy-alt-done)
(define-key ivy-minibuffer-map (kbd "RET") #'my-ivy-immediate-done)
(defun my-ivy-immediate-done ()
  (interactive)
  (if (string= ivy-text "")
      (ivy-alt-done)
    (ivy-immediate-done)))
```

**Comment by nordlow** [comment]
Ok, thanks! Good for now!
