### ISSUE TITLE
Error in post-command-hook (ivy--queue-exhibit): (wrong-number-of-arguments (4 . 4) 3)

### ISSUE THREAD

**Issue by tszg** [abo-abo/swiper#1637]
I used emacs on the win10 system, and after I upgraded ivy, the error of counsel-find-file kept appearing
```text
Error in post-command-hook (ivy--queue-exhibit): (wrong-number-of-arguments (4 . 4) 3)

**Comment by basil-conto** [comment]
Is this fixed by #1635? If so, I think it's the same issue reported here: https://github.com/abo-abo/swiper/commit/bb73d649349b1010139874b028f929566b24a633#comments.

**Comment by AloisJanicek** [comment]
I am getting it too. Installing ivy/counsel from `:repo "basil-conto/swiper" :branch "blc/add-face"` fixed the issue.

**Comment by et2010** [comment]
I can confirm it is fixed by PR 1635

**Comment by sewkokot** [comment]
I have the latest ivy.el from melpa and get the same error as @tszg

**Comment by sewkokot** [comment]
I see now, we need to wait until the following PR is in melpa
https://github.com/abo-abo/swiper/pull/1635/commits/b8c51906ec7db27ed661179574392ea47d8af857

**Comment by abo-abo** [comment]
Closing since, #1635 is now merged. Sorry for the inconvenience. Thanks to @basil-conto for the prompt fix.
