### ISSUE TITLE
counsel-ag does not use the current file's parent folder to run ag command

### ISSUE THREAD

**Issue by hungptit** [abo-abo/swiper#1638]
I notice that counsel-ag does not use the parent folder of the current file to run ag command, it uses the git root folder instead. Is this an expected behavior?

**Comment by abo-abo** [comment]
Yes, this is expected. Use <kbd>C-u</kbd> to specify a custom directory.

**Comment by hungptit** [comment]
This actually bring up a usability design question. Let say if a user try
to execute counsel-ag command does it make sense if we assume that he/she
only only interested in files in the current folder. If we also assume that
users know what they are doing then this is a reasonable assumption. If
searching for all files in the root folder is desired (rarely happened)
then counsel-git-grep command or move to the root folder then run
counsel-ag can do the job. With this new behavior if someone try to look
for patterns in a big folder such as boost source code then he/she need to
some unnecessary extra work otherwise counsel-ag command is very slow and
it will generate a lot of noise or redundant information.

Hung

**Comment by abo-abo** [comment]
> If searching for all files in the root folder is desired (rarely happened)

Not the case of me. I always want to see all references of a symbol in the whole project.

If it's not the case for you, you can always define:

```elisp
(defun my-counsel-ag ()
  (interactive)
  (counsel-ag nil default-directory))
```

**Comment by hungptit** [comment]
This only makes sense if you work on small projects. If you work on a large
project with thousand of files (>100K in my situation) or has several large
sub-modules for example boost libraries then you will see how painful it
is. For your use cases, I think counsel-git-grep is a better solution. I
will try your workaround, however, I strongly believe someone will complain
about this new behavior in the future.

Hung

**Comment by abo-abo** [comment]
I have one project with 70k files, I still want to run the grep on the whole project. But even if I didn't, there are only so many 100k file projects you can have; all other ~100 projects that I have are <100 files.  So it makes sense to customize your workflow/setup for these huge projects without having 99% of the other projects having a sub-par experience.

See for instance `counsel-git-grep-projects-alist` on how per-project config could be implemented.

**Comment by hungptit** [comment]
I just want to close the loop. I confirm that your work around works well
for me. Thanks. Hung.
