### ISSUE TITLE
Delete file or kill buffer DWIM [Feature request]

### ISSUE THREAD

**Issue by kaushalmodi** [abo-abo/swiper#164]
I have switched to using counsel and ivy instead of ido and this is one of the features I miss from ido:

1. When doing `C-x C-f`, if the selection is on a file name that is not open in one of the buffers, `C-k` will delete (or trash, depending on `delete-by-moving-to-trash`) that file name.
2. When switching buffers, `C-k` will kill the selected buffer if open. If the buffer is already closed (virtual buffer) and if that buffer was associated to a file name, that file will be deleted (or trashed).

It will be nice to have these functionalities in `counsel-find-file` and `ivy-switch-buffer`.

Currently, I need to switch to that file/buffer and then delete/kill it.

**Comment by abo-abo** [comment]
You could add something like this to your config:

```elisp
(define-key
    ivy-switch-buffer-map
    (kbd "C-k")
  (lambda ()
    (interactive)
    (ivy-set-action 'kill-buffer)
    (ivy-done)))
```

I'm currently working on multiple actions for a single command. Similar to `counsel-describe-variable`, except the key bindings aren't hard coded.  Maybe that could solve your problem as well:

1. Call `ivy-switch-buffer`
2. <kbd>C-o</kbd> to open up options.
3. <kbd>w</kbd> / <kbd>s</kbd> to select the buffer kill action, instead of the default switch-to-buffer action.
4. Use <kbd>C-M-n</kbd> to kill a bunch of buffers, while skipping some with <kbd>C-n</kbd>.

**Comment by kaushalmodi** [comment]
Works great with `ivy-switch-buffer`. Would like to implement 'delete file' function in `counsel-find-file` in a similar fashion.

btw, why have the `ivy-` prefix for `ivy-switch-buffer` and `counsel-` for almost everything else?

**Comment by kaushalmodi** [comment]
```el
    (defun counsel-find-file ()
      "Forward to `find-file'."
      (interactive)
      (ivy-read "Find file: " 'read-file-name-internal
                :matcher #'counsel--find-file-matcher
                :action (cons
                         1
                         `(("default"
                            (lambda (x)
                              (find-file
                               (expand-file-name x ivy--directory))))
                           (,(propertize "delete"
                                         'face 'font-lock-warning-face)
                            (lambda (x)
                              (delete-file
                               (expand-file-name x ivy--directory))))))
                :preselect (when counsel-find-file-at-point
                             (require 'ffap)
                             (ffap-guesser))
                :require-match 'confirm-after-completion
                :history 'file-name-history
                :keymap counsel-find-file-map))
```

**Comment by abo-abo** [comment]
> btw, why have the ivy- prefix for ivy-switch-buffer and counsel- for almost everything else?

Because most of `ivy-switch-buffer` is in `ivy.el`, and it's part of `ivy-mode` via:

    (define-key map [remap switch-to-buffer] 'ivy-switch-buffer)

I tried remapping `counsel-find-file`, it didn't work for some reason.

**Comment by abo-abo** [comment]
> Would like to implement 'delete file' function in counsel-find-file in a similar fashion.

I'm afraid of deleting files by accident: by mashing <kbd>sc</kbd> you can delete a file by accident.  But I don't want to make you redefine `counsel-find-file` if you choose to have that functionality. Maybe I could add `ivy-extra-actions-alist` similar to `ivy-initial-inputs-alist`. What do you think?

**Comment by kaushalmodi** [comment]
> Maybe I could add `ivy-extra-actions-alist` similar to `ivy-initial-inputs-alist`.
I am fine redefining that function. But adding that variable would also mean easy customizability of any function using `ivy`; so go for it. Thanks! :)

 I also feared of accidental deletion and so I gave `font-lock-warning-face` to `delete` option. I can even go further and wrap the `delete-file` in `y-or-n-p`.

**Comment by abo-abo** [comment]
Added the new interface. Give it a try for your file-deleting application.

**Comment by kaushalmodi** [comment]
Works great! Thank you.

```el
    (ivy-set-actions
     'counsel-find-file
     `((,(propertize "delete" 'face 'font-lock-warning-face)
        (lambda (x) (delete-file (expand-file-name x ivy--directory))))))
```

**Comment by JohnLunzer** [comment]
I have a question regarding the switch-buffer kill, `(ivy-done)` closes the ivy minibuffer which is not desirable for me. I changed it to `(ivy-done)` to `(ivy-call)` and it performs the action but the ivy minibuffer doesn't update as I would have expected. 

What would I have to add to kill a buffer, keep the ivy minibuffer open, and update the ivy-minibuffer to get rid of the killed buffer? 

I'm also using ivy-rich, just in case you can't reproduce.

**Comment by abo-abo** [comment]
@JohnLunzer I think you're looking for <kbd>C-c C-k</kbd>.

**Comment by JohnLunzer** [comment]
You know... you just have the answer for everything don't you ;) That's great. With that command and Ivy-rich I feel like I can abandon `bs-show`

Out of curiosity, so I don't ask stupid questions in the future, what is the prescribed method for showing ivy-x-map keybindings while in an ivy minibuffer?

**Comment by abo-abo** [comment]
> Out of curiosity, so I don't ask stupid questions in the future, what is the prescribed method for showing ivy-x-map keybindings while in an ivy minibuffer?

Usually, `describe-mode` should work. But it doesn't show you the <kbd>C-c C-k</kbd> binding in this case. We'll need to improve the discoverability in the future.

**Comment by basil-conto** [comment]
> Usually, `describe-mode` should work. But it doesn't show you the <kbd>C-c</kbd><kbd>C-k</kbd> binding in this case. We'll need to improve the discoverability in the future.

What about <kbd>C-h</kbd><kbd>b</kbd>, AKA `describe-bindings` or, with `counsel-mode` enabled, `counsel-descbinds`?
