### ISSUE TITLE
counsel-grep-or-swiper failure

### ISSUE THREAD

**Issue by rnadler** [abo-abo/swiper#1644]
I have one particular org file (~1200 lines) that always fails (folded or unfolded) on `C-s` with:
>  Debugger entered--Lisp error: (wrong-type-argument stringp nil)
>      string-match("[ \f\011\n\015\013]+" nil 0)
>      split-string(nil)
>      counsel-grep(nil)
>      counsel-grep-or-swiper()
>      funcall-interactively(counsel-grep-or-swiper)
>      call-interactively(counsel-grep-or-swiper nil nil)
>      command-execute(counsel-grep-or-swiper)

I do not see this problem on any other files (org or otherwise). Does that particular org file have something toxic in it?

> counsel-20180625.634
> swiper-20180615.1400

Config:
```
(use-package counsel
  :diminish ivy-mode counsel-mode
  :bind (("C-s" . swiper)
         ...
         :map counsel-mode-map
         ([remap swiper] . counsel-grep-or-swiper)
         ...
```
> GNU Emacs 26.1.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 2.24.32) of 2018-05-29

**Comment by basil-conto** [comment]
What is your value of `counsel-grep-base-command`? Can you reproduce this from `emacs -Q`? Have you tried making a copy of the Org file in question, and recursively removing half of the file to pin point which part of it (if any) is causing `counsel-grep` to fail?

**Comment by basil-conto** [comment]
Instead of typing <kbd>C-s</kbd>, I suggest invoking either `swiper` or `counsel-grep` directly, to further reduce the number of variables in the equation (`counsel-grep-or-swiper` delegates to either one or the other subject to, amongst other things, buffer size). I also suggest recursively commenting-out parts of your configuration to rule out the possibility of some setting or package you use being guilty.

**Comment by rnadler** [comment]
counsel-grep-base-command = "grep -E -n -e %s %s"
`M-x swiper` works fine.
`M-x counsel-grep` and `M-x counsel-grep-or-swiper` both fail:
> Debugger entered--Lisp error: (wrong-type-argument stringp nil)
>   string-match("[ \f\011\n\015\013]+" nil 0)
>   split-string(nil)
>   counsel-grep()
>   funcall-interactively(counsel-grep)
>   call-interactively(counsel-grep record nil)
>   command-execute(counsel-grep record)
>   #f(compiled-function (cmd) #<bytecode 0xe962d5>)("counsel-grep")
>   ivy-call()

In the process of capturing the debug ouput I found a single line of text that causes the error. It's a 145K bytes long, but note that counsel-grep works fine if you are not in org mode. See attachment: [ivy-read.zip](https://github.com/abo-abo/swiper/files/2153355/ivy-read.zip)

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by rnadler** [comment]
Hmmm... updated to counsel-20180703.818, but the change is not there. Will the change be in a subsequent release?

**Comment by abo-abo** [comment]
I don't know if a new release was published already. Probably not, it takes at least 4 hours to publish all packages. But you can test with the `master` branch of this git repo.

**Comment by rnadler** [comment]
Got counsel.el from `master` with the changes, but it still fails in the same place for me. Will investigate as time allows.

**Comment by rnadler** [comment]
Error is occurring before ([counsel.el#L2653](https://github.com/abo-abo/swiper/blob/master/counsel.el#L2653)) the changes you added.
> (counsel-require-program (car (split-string counsel-grep-base-command)))

**Comment by basil-conto** [comment]
If that's the line that errors, then something is setting or binding `counsel-grep-base-command` to `nil` for some reason.

**Comment by basil-conto** [comment]
In that case, I suggest closing this issue and opening another one at https://github.com/seagle0128/.emacs.d

**Comment by seagle0128** [comment]
I just noticed this thread. Since I am using `rg`, I didn't encounter this issue. 
@rnadler I've fixed in the latest version. Please test.

**Comment by basil-conto** [comment]
Oops, sorry; I didn't notice this issue was already closed.

**Comment by rnadler** [comment]
@seagle0128, Fix works fine. Thanks!
