### ISSUE TITLE
ffap has stopped working

### ISSUE THREAD

**Issue by kaushalmodi** [abo-abo/swiper#165]
I have the below in my emacs setup:

```el
(setq counsel-find-file-at-point t)
```

and I have this in my scratch buffer

> ;; /home/kmodi/e/init.el

With the point on that path, `M-: (ffap-guesser)` works fine and returns the path in string form correctly.

But, with the point on that path, `M-x counsel-find-file` does not work; it does not preselect that path.

I also edebugged `counsel-find-file` and the `ffap-guesser` did its job fine; just that the preselect did not work.

**Comment by abo-abo** [comment]
Thanks.

**Comment by kaushalmodi** [comment]
Sorry, the issue is still not fixed for me.

This is what I see on calling `counsel-find-file`:
*The list still contains stuff from the `temp/` dir. That's alright though if the preselection had the exact file name under point (`$HOME/e/init.el`).*

![clipboard01](https://cloud.githubusercontent.com/assets/3578197/8454826/3b320b3a-1fce-11e5-8b8c-8616d717f1a6.png)

This is what I see on calling `ido-find-file`:
*The list still contains stuff from the dir in the path under point. This is more helpful as I can easily pick the file under point from the ido list.*

![clipboard01-2](https://cloud.githubusercontent.com/assets/3578197/8454831/45aeaafa-1fce-11e5-8768-e71d5fc9315d.png)

**Comment by abo-abo** [comment]
You're right, there was a bit of bad logic there. Please try my update.

**Comment by kaushalmodi** [comment]
Thanks! That fixes the counsel listing. Now may I request one enhancement which ido-find-file does not have?

- Now it lists the files/dirs correctly from `$HOME/e/`. But instead of preselecting some random file like `smex-items`, why not preselect the exact file under point (`init.el` in this case)?

![clipboard01](https://cloud.githubusercontent.com/assets/3578197/8455222/1286e2fc-1fd1-11e5-88f0-7524e8d020d9.png)

**Comment by abo-abo** [comment]
> why not preselect the exact file under point (init.el in this case)?

That's what it does on my machine. If it doesn't work for you, try to edebug `ivy--reset-state` up to `(setq ivy--index ...)`.

**Comment by kaushalmodi** [comment]
The `coll` is correct (contents of `e/` dir), `preselect` is `"init.el"` but `initial-input` is `nil`.

**Comment by abo-abo** [comment]
`initial-input` needs to be nil.

> I need to check if that is correct.

    (nth ivy--index ivy--all-candidates)

**Comment by kaushalmodi** [comment]
I'll need to revisit later today; will update you on my findings then. Thanks.

**Comment by kaushalmodi** [comment]
Found the culprit!

I have `counsel-find-file-ignore-regexp` set to a non-nil value:

```el
    (setq counsel-find-file-ignore-regexp
          (concat
           ;; file names beginning with # or .
           "\\(?:\\`[#.]\\)"
           ;; file names ending with # or ~
           ;; but still allow backup files named like abc.el~timestamp~
           "\\|\\(?:\\`[^~]+?[#~]\\'\\)"))
```
The `ivy--index` refers to the "pre-filtered" `coll`. The index needs to be recalculated once the list elements are filtered out based on the above regexp.

You probably have this regexp at its default value of `nil` and so this issue is not seen.

**Comment by abo-abo** [comment]
> You probably have this regexp at its default value of nil and so this issue is not seen.

I see. This requires a large rewrite, moving the logic from the matcher to `ivy--reset-state`.

**Comment by abo-abo** [comment]
Finally got around to fixing this. Please check.

I've also pushed the action interface change that I was delaying for a while: if you're using `ivy-set-actions` you should update.

**Comment by kaushalmodi** [comment]
I didn't understand what changed related to `ivy-set-actions`.

Currently I have this:

```el
(ivy-set-actions
     'counsel-find-file
     `((,(propertize "delete" 'face 'font-lock-warning-face)
        (lambda (x) (delete-file (expand-file-name x ivy--directory))))))
```

How should that be updated?

**Comment by abo-abo** [comment]
> How should that be updated?

The old format was `(doc cmd)`. The new format is `(key cmd doc)`, just like for hydra.

**Comment by kaushalmodi** [comment]
OK, but I am unable to figure out which commit introduced that action interface change. Or do you still have to push that commit?

**Comment by kaushalmodi** [comment]
Thanks, I confirm this fix.
