### ISSUE TITLE
Case sensitivity invoked by using an uppercase letter

### ISSUE THREAD

**Issue by ardpp** [abo-abo/swiper#166]
`isearch` has by default the nice property that a search becomes case sensitiv once an uppercase letter is used. It would be nice to have such behaviour in `swiper` as well.

**Comment by abo-abo** [comment]
Thanks.

**Comment by ardpp** [comment]
Don't know why, but it is not working as expected for me. I do have the newest version of swiper from melpa with the responsible line
``
(case-fold-search (string= name (downcase name)))
``

**Comment by abo-abo** [comment]
Try this one:

    (ivy-read "Prompt: " '("the" "The" "one" "two"))

`th` should match two candidates, while `Th` should match only one.

**Comment by ardpp** [comment]
When I evaluate this expression in the scratch buffer it does work as expected. But if I invoke swiper in a buffer that looks like that
```
the 
The
```
`th`  matches  two candidates and `Th` one. So this works also as expected (I was wrong before!). 
However in both cases both "the" and "The" are highlighted. That is why I got mistaken in the first place.

**Comment by abo-abo** [comment]
Yeah, the swiper highlighter is pretty naive at this point. If you set the matcher to fuzzy it still highlights in the old way. I'll have to fix that at some point, but it's not a small task.
