### ISSUE TITLE
Improvement request: Highlight all matches

### ISSUE THREAD

**Issue by wolfv6** [abo-abo/swiper#1662]
Please highlight all matches in counsel-recentf, not just the first occurrence in path.

For example, from counsel-recentf, enter "test" will list something like:
![Imgur](https://i.imgur.com/Vo4zR1t.png)

Would be nice if entering "test" highlighted all occurrences of "test" in path like this:
![Imgur](https://i.imgur.com/Mx04peE.png)
This would make it easier to see matching words without having to type the word twice, which is especially useful for longer words.

**Comment by mookid** [comment]
Here a similar scenario gives this:

![image](https://user-images.githubusercontent.com/7757342/46696894-9b7e7100-cc13-11e8-932c-0b1cc59d65e6.png)


can you still reproduce the issue?

**Comment by basil-conto** [comment]
Note that highlighting also depends on the value of `ivy-re-builders-alist`. `ivy--regex-plus` has better highlighting support than `ivy--regex-ignore-order`, for example. See [`(ivy) Completion Styles`](http://oremacs.com/swiper/#completion-styles).

**Comment by wolfv6** [comment]
I see where I went wrong:
```
ivy-re-builders-alist is a variable defined in ‘ivy.el’.
Its value is ((t . ivy--regex-ignore-order))
```
Thanks basil.
