### ISSUE TITLE
Add an option for length for `counsel-more-chars`?

### ISSUE THREAD

**Issue by whatacold** [abo-abo/swiper#1663]
Hi,

I use `counsel-ag`/`counsel-rg` quite a lot, for most of the time, it works really well.

But sometimes I do need to search for something which has only 2 or even 1 character as keyword,
then I can't figure out how to let them work.

Due to the hard coded length for `counsel-more-chars`, it seems there is no way to work, if I understand correctly:

    $ ag counsel-more-chars
    counsel.el
    48:(defun counsel-more-chars (n)
    1278:      (counsel-more-chars 3)
    1421:      (counsel-more-chars 3)
    1592:      (counsel-more-chars 3)
    2185:      (counsel-more-chars 3)
    2433:      (counsel-more-chars 3)
    2595:      (counsel-more-chars 2)
    2718:      (counsel-more-chars 3)

Would you like to add an option for this length?

Thanks.

**Comment by abo-abo** [comment]
Thanks, you can now use `counsel-more-chars-alist` to customize the amount of chars.

**Comment by whatacold** [comment]
Cool, thanks you very much.

**Comment by whatacold** [comment]
Please note that this option is now called `ivy-more-chars-alist`.
