### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by raxod502** [abo-abo/swiper#1664]
The last release of Ivy, version 0.10.0, was over seven months ago in November 2017. Since then, there have been 281 commits to master, including in particular several bug fixes which are necessary for my package [`ivy-prescient.el`](https://github.com/raxod502/prescient.el) to work at all with Ivy. With no release of Ivy which includes these bugfixes, it's impossible to use the stable version of `ivy-prescient.el` either.

Is a new release of Ivy scheduled anytime soon?

**Comment by abo-abo** [comment]
Thanks for the reminder, I'll try to make a release in the next weeks.

**Comment by sten0** [comment]
+1  The deadline for getting the new version into the next Debian release is January 2019.  I'm not sure when Ubuntu's last sync from Debian before releasing 18.10 will be, I'm guessing it's sometime in mid-August.  Oh, that reminds me, I never did submit a PR for installation instructions for Debian (and derivatives)...

**Comment by rekado** [comment]
I'd like to update the ivy package for Guix, so I also wonder if there will be a new release or if we should take any of the recent commits in lieu of a release.

Thank you for ivy!

**Comment by jellelicht** [comment]
Is there a possibility of taking a reasonably recent version of ivy, and just release it as 0.11?

**Comment by paulbdavis** [comment]
This would be helpful. The [`counsel-projectile` project is waiting](https://github.com/ericdanan/counsel-projectile/issues/120) for a new stable `ivy` release to be able to tag a release that works with the now stable `projectile` 2.0.0

**Comment by sten0** [comment]
@abo-abo, if you'd like Debian 10 (buster) and derivatives to have a version of Ivy/Counsel/Swiper newer than `0.10.0`, the deadline is at the end of January.  No pressure of course, 'just sharing the freeze/release plan for your information :-)  Strictly speaking 12 Feb is the last call, but I'll need time to prepare the Debian release and do DebCI regression testing with other packages, and I'm extremely pressed for time the next two months.  It's possible that I'll encounter resistance from the release team, but I maintain 2/3 of the dependant packages so I remain optimistic.  'hopefully they won't throw the book at us saying "you should have gotten this done by 12 jan"!  https://release.debian.org/buster/freeze_policy.html

**Comment by abo-abo** [comment]
I've made some progress on the Changelog today. Around 300 out of 570 commits for 0.11.0 are now documented. Once the Changelog is done, I can make the release.

**Comment by abo-abo** [comment]
The release 0.11.0 is now tagged. It will be on MELPA shortly. I'll publish to GNU ELPA tomorrow.

**Comment by sten0** [comment]
@abo-abo, thank you for the new release!  Also, thank you for taking the time to prepare a changelog; this is very much appreciated.
