### ISSUE TITLE
empty minibuffer with empty collection and ivy-add-newline-after-prompt

### ISSUE THREAD

**Issue by ericdanan** [abo-abo/swiper#1667]
Hello,

With `ivy-add-newline-after-prompt` set to `t`, when `ivy-read` is called with an empty collection (this happens e.g. if `org-read-property-value` is called for a property for which there is no value in the current buffer), then nothing is shown in the minibuffer (one empty line). As soon as I type a character, the display becomes correct (two lines: one with the prompt and one with the typed character). Not seeing the prompt is quite inconvenient.

This seems to come from the minibuffer resizing, but I don't how to solve the issue. My only workaround for now is to set `ivy-fixed-minibuffer-height` to `t`. Perhaps there is a way to make sure the minibuffer always has at least two lines when `ivy-use-newline-after-prompt` is `t`?

Thanks

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by ericdanan** [comment]
It works now, thanks!

Oleh Krehel writes:
