### ISSUE TITLE
Have anzu like #/total count be displayed in ivy [Feature request]

### ISSUE THREAD

**Issue by kaushalmodi** [abo-abo/swiper#167]
The `anzu` package shows which search item you are on on the bottom left when you are using `isearch`; `(1/2)` as shown in the below screenshot.

![clipboard01](https://cloud.githubusercontent.com/assets/3578197/8455304/a43c54d4-1fd1-11e5-8ba6-f9639a44f79d.png)

`swiper` (and `ivy` in general) shown only the total search hits (total number of items in list); `2` in this example.

![clipboard01](https://cloud.githubusercontent.com/assets/3578197/8455346/f3c79586-1fd1-11e5-92e7-71a2999f50d7.png)

It will be nice to have a user option to show a `#/total` count instead of just `total` count to the left of `pattern`.

**Comment by abo-abo** [comment]
I have considered this, but I thought that it would be too annoying, since it's almost redundant information that updates with each scroll. I can add it as an option though, it's not hard.

**Comment by abo-abo** [comment]
Try it out with:

    (setq ivy-count-format "(%d/%d)")

Hopefully I didn't break the old behavior (when `ivy-count-format` has only one `%d`).

**Comment by kaushalmodi** [comment]
I was wondering how we can make this evaluation each time `ivy--insert-prompt` is called:

```el
    (setq ivy-count-format (concat "%"
                                   (number-to-string
                                    (length `(number-to-string ,ivy--length)))
                                   "d/%d"))
```

**Comment by abo-abo** [comment]
> I was wondering how we can make this evaluation each time ivy--insert-prompt is called:

I considered this, but I don't know if there's a way to make it look nice.  Suppose the collection has size 9000. Then to keep the stuff aligned for all cases, since I find it extremely annoying when my input window is moving as I type:

    (format "(%-4d/%-4d)" 1 9000)
    ;; => "(1   /9000)"
    (format "(%-4d/%-4d)" 9000 9000)
    ;; => "(9000/9000)"

While the second one looks OK, the first one looks pretty ugly. Suggestions?

**Comment by kaushalmodi** [comment]
Currently I have set the format to 

```el
(setq ivy-count-format "%3d/%d")
``` 

and it looks nice. The count does not move around.

Instead of setting the index width to a static `3`, it would be even better if I can evaluate the below each time `ivy--insert-prompt` is called.

```el
 (setq ivy-count-format (concat "%"
                                   (number-to-string
                                    (length `(number-to-string ,ivy--length)))
                                   "d/%d"))
```

Things that make the index look good:

- no brackets
- right align the index (`%Nd` instead of `$%-Nd`)

![clipboard01](https://cloud.githubusercontent.com/assets/3578197/8478047/d64f8c2c-209c-11e5-8051-f95f7971bafe.png)

**Comment by abo-abo** [comment]
> right align the index

OK, but the length needs to be left-aligned. Here's what I get for <kbd>M-x</kbd>: `___1/1___ ^vi li mo`. Note the abundance of spaces: they are necessary, since it could be `8337/8337 ^` as well.

I guess it's bearable. Check out the last change with this setting:

    (setq ivy-count-format "%d/%d ")

**Comment by kaushalmodi** [comment]
Works for the few `ivy` powered functions, but not for swiper?

**Comment by kaushalmodi** [comment]
I updated swiper.el but I notice that just for swiper, there is an extra offset on the left
![clipboard01](https://cloud.githubusercontent.com/assets/3578197/8480756/8b297d3c-20ad-11e5-91ed-202b5aab01f0.png)

As the total hits is `4`, that `2` should have been flush to the left. On debugging, I noticed that `swiper--width` was being internally calculated as `3`.

**Comment by abo-abo** [comment]
Looks correct to me: `239/239 Swiper`. That one space should be there in case of max width.

**Comment by kaushalmodi** [comment]
It looks correct when there are 3 digits in the `w` in `s/w`. Try using swiper for something that has single digit hits (try swiping for the exact same thing as in the screenshot above).

**Comment by abo-abo** [comment]
> try swiping for the exact same thing as in the screenshot above

OK, I got the same result as you:

    __1/4___Swiper:
    154 123_|||||||

That one extra space is there always: it's 3 chars, `/`, 3 chars, `_`.

**Comment by kaushalmodi** [comment]
Right.. the issue is that the `swiper--width` is calculated based on the number of lines in the file, not based on the number of hits.

```el
  (let ((n-lines (count-lines (point-min) (point-max))))
    (unless (zerop n-lines)
      (setq swiper--width (1+ (floor (log n-lines 10))))
      (setq swiper--format-spec
            (format "%%-%dd %%s" swiper--width))
```

In the case of `swiper.el`, there are 363 lines ( 3 digit number) right now. So `swiper--format-spec` will always *incorrectly* be `"%-3d %s"`.

It would be nice to have `swiper--wdith` update with the number of search hits.

**Comment by kaushalmodi** [comment]
The problem gets even more pronounced as the total number of lines in a file increase:

![clipboard01](https://cloud.githubusercontent.com/assets/3578197/8481228/01ba96dc-20b0-11e5-9d53-4ffa1499e885.png)

**Comment by abo-abo** [comment]
> The problem gets even more pronounced as the total number of lines in a file increase:

It has to be done this way to prevent the input field from moving as you type. Just try it your way: replace `head` on line 1176 with `"%d/%d"`. The result isn't great.

**Comment by kaushalmodi** [comment]
> That one extra space is there always: it's 3 chars, /, 3 chars, _.

That extra space is not the problem. As shown in above screenshots, the issue is with how the number `3` is calculated; it should be 

    (1+ (floor (log NUM-SEARCH-HITS 10))) ; correct

not

    (1+ (floor (log NUM-LINES-IN-FILE 10))) ; incorrect

**Comment by abo-abo** [comment]
> (1+ (floor (log NUM-SEARCH-HITS 10))) ; correct

The input field will move with this approach.

**Comment by kaushalmodi** [comment]
> The input field will move with this approach.

Thanks, I see your point.
