### ISSUE TITLE
How to go a directory up in find-file with ivy-mode completion?

### ISSUE THREAD

**Issue by halloleo** [abo-abo/swiper#1670]
I've switched on `(ivy-mode 1)`, then issue `find-file`. 

Now in ivy I want to select/complete a file in the parent of the current directory. **How do I go up a directory?** Do I have to add a binding to `ivy-minibuffer-map`?

**Comment by halloleo** [comment]
Sorry, found it: *Backspace* does the job (though this is not obvious from reading through `ivy-minibuffer-map`.)

**Comment by basil-conto** [comment]
> (though this is not obvious from reading through ivy-minibuffer-map.)

It's documented under [`(ivy) File Name Completion`](https://oremacs.com/swiper/#file-name-completion).

**Comment by halloleo** [comment]
Thanks for the pointer. :-)

On 18 Jul 2018, at 14:55, Basil L. Contovounesios <notifications@github.com> wrote:

(though this is not obvious from reading through ivy-minibuffer-map.)

It's documented under (ivy) File Name Completion <https://oremacs.com/swiper/#file-name-completion>.
