### ISSUE TITLE
Binding swiper to C-r

### ISSUE THREAD

**Issue by vincentbernat** [abo-abo/swiper#1673]
Hey!

Would there be a way to make swiper search backward first? Invoking it on C-r would be useful.

Thanks!

**Comment by basil-conto** [comment]
See also #1172.

**Comment by basil-conto** [comment]
See also #299 and the sample bindings in #277.

**Comment by vincentbernat** [comment]
Thanks. I am closing this one as this is clearly a dupe of #1172.
