### ISSUE TITLE
[feature request] Show last used options on top

### ISSUE THREAD

**Issue by maximvl** [abo-abo/swiper#1674]
Hi guys, great stuff you are doing here, though I have an issue compared to other command completion tools - I can't make counsel show last used commands on top, which would be super useful for me.
Currently I always get a completely useless alphabetically sorted list:

![image](https://i.imgur.com/YEyQeLN.png)

Is it possible to enable such feature or does it require some development? Thanks!

**Comment by basil-conto** [comment]
It's mentioned in the FAQ: https://github.com/abo-abo/swiper/wiki/FAQ#sorting-commands-by-frequency

and also in the docstring of <kbd>C-h</kbd><kbd>f</kbd>`counsel-M-x`<kbd>RET</kbd>.

A lot of Counsel functionality can be better or more prominently documented, so I'm not sure this issue should be left open as a reminder for that. It's @abo-abo's call, though. Feel free to send PRs with documentation suggestions (I'm currently AFK).

**Comment by maximvl** [comment]
@basil-conto I was looking into these docs here: https://oremacs.com/swiper/

**Comment by maximvl** [comment]
@basil-conto sorry, I meant in the docs on `oremacs.com/swiper` there is no mention about `smex/amx` integration :)
