### ISSUE TITLE
Feature request: M-x show most frequently used commands at the top

### ISSUE THREAD

**Issue by rafaelgp** [abo-abo/swiper#168]
Hello,

Smex user here.
Something I really miss when I use ivy's M-x is that it doesn't show the most frequently used commands at the top.
For example, if I type
M-x find-file (just as an easy example) I get this:

![Ivy-find-file](http://clients.tourvista.co.uk/vt/zip/tmp/ivy-1.jpg)

Find-file is listed 6th.
If I type the same it again, it's listed 6th.
If I type it 20 times more, it's still listed 6th.
Smex on the other hand would list it higher and higher as it's been selected more and more. 

Thank you very much for your vision and all the hard work you're putting on Swipper!!!

**Comment by abo-abo** [comment]
You should try `counsel-M-x`: it actually depends on `smex` for command sorting, so it should be very close to `smex`.  In addition, it also shows the key binding for each bound command.

**Comment by rafaelgp** [comment]
I've installed the Counsel package (using package) but when I try to call 'counsel M-x' or 'counsel-find-file' but it returns:

'Symbol's function definition is void: ivy-set-actions'

Are there any special configuration I need to add?

**Comment by abo-abo** [comment]
> 'Symbol's function definition is void: ivy-set-actions'

Try to upgrade the counsel package and the ivy package. Or remove it and install it again. I just tried to install and, like you, got an outdated version without `ivy-set-actions`.  But after a re-install, I got a good version.

**Comment by rafaelgp** [comment]
Upgrade the packages made the trick.

Counsel-M-x is what I was looking for and a bit more.
I love that it shows the commands key! Just like Helm-M-x ;-)

Cheers
