### ISSUE TITLE
proced-filter-interactive not working with ivy-mode

### ISSUE THREAD

**Issue by dakra** [abo-abo/swiper#1687]
When in `proced` you can change the filter with `f` (`proced-filter-interactive`)
This reads `(completing-read "Filter: " proced-filter-alist nil t)`
which works when ivy-mode is disabled but breaks enabled (doesn't show any completion options).

(I'm using latest Emacs master)

**Comment by abo-abo** [comment]
Looks like an Emacs bug to me. Here's what gets passed to `completing-read-function`:

```elisp
((user (user . "\\`krehel\\'"))
 (user-running
  (user . "\\`krehel\\'")
  (state . "\\`[Rr]\\'"))
 (all)
 (all-running
  (state . "\\`[Rr]\\'"))
 (emacs
  (fun-all
   lambda (list)
   (proced-filter-children
    list
    5081))))
```

This is not compatible with the API of `completing-read`. From documentation of `completing-read`:

> COLLECTION can be a list of strings, an alist, an obarray or a hash table.

**Comment by dakra** [comment]
OK.
I filed a bug report: https://debbugs.gnu.org/cgi/bugreport.cgi?bug=32314

I'll leave this open until I get an answer there.
(Or you can close it already if you want of course)

**Comment by npostavs** [comment]
> This is not compatible with the API of `completing-read`. From documentation of `completing-read`:
> 
>     COLLECTION can be a list of strings, an alist, an obarray or a hash table.
> 

Looks like an alist to me. Why do you think it's wrong?

**Comment by basil-conto** [comment]
> This is not compatible with the API of `completing-read`.

It is, see [`(elisp) Basic Completion`](https://www.gnu.org/software/emacs/manual/html_node/elisp/Basic-Completion.html):

    If COLLECTION is a list, the permissible completions are specified
    by the elements of the list, each of which should be either a
    string, or a cons cell whose CAR is either a string or a symbol (a
    symbol is converted to a string using ‘symbol-name’).  If the list
    contains elements of any other type, those are ignored.

Funnily enough, `ivy-read` handles symbol alists just fine:

```el
(progn
  (setq unread-command-events '(?\C-m))
  (ivy-read "" '((a) (b) (c))))
  ;; => "a"
````

**Comment by dakra** [comment]
@abo-abo The fix works for me. thanks.
