### ISSUE TITLE
Is it possible to apply file masks to counsel search without modifying the base command?

### ISSUE THREAD

**Issue by ztlevi** [abo-abo/swiper#1688]
I am wondering if we have an existing feature supports file masks during searching using counsel. A similar example is rgrep.

I don't see any customizable options there for counsel file masks. But I feel like this is really useful.

**Comment by basil-conto** [comment]
Counsel is a library providing multiple search commands (e.g. `counsel-ag`), are you asking that they all provide a uniform interface to specifying tool-specific file-filtering flags? I think that this won't be worth implementing after #1559 lands. If that's not what you meant, can you please be more specific / provide more details of what exactly you envision, and how it will be used?

Note also that some (maybe all, I haven't checked) Counsel search commands already accept a prefix argument <kbd>C-u</kbd> which allows you to specify extra flags, such as file extension regexps, prior to completion.

**Comment by ztlevi** [comment]
This is exactly what I want. Since the args are passed via inputs, we can go back to the previous with `M-p` any time we want to. Thank you!

Do we have this feature documented somewhere? Cuz this is really helpful.

**Comment by basil-conto** [comment]
> Do we have this feature documented somewhere?

Which feature are you referring to? The prefix argument? If so, I don't think it's clearly documented anywhere (although you might be able to infer it from the optional arguments listed for commands like <kbd>C-h</kbd><kbd>f</kbd>`counsel-ag`<kbd>RET</kbd>).

Doc fix PRs are always welcome (as a mere user/contributor, I won't be personally inclined to improve documentation in this area until I have thought more about the wishlist redesign mentioned in #1408 and #1409).

**Comment by ztlevi** [comment]
Yes. That's what I mean.

But even the function args are documented like this:
```
(counsel-rg &optional INITIAL-INPUT INITIAL-DIRECTORY EXTRA-RG-ARGS RG-PROMPT)
```

We are not likely to know how to apply the extra args.

But it's alright. Useful tips like `M-n`, `M-p` are the hidden power of ivy. I also doubt extra args is documented in the [mannual](http://oremacs.com/swiper/#copying). But I would like to blog these features. 😂

**Comment by ztlevi** [comment]
I didn't test `counsel-ag` but `counsel-rg` doesn't work this way. But Spacemacs has `counsel-search` functions, and they can apply args via input. It's so weird. 
![image](https://user-images.githubusercontent.com/16655096/43494342-2bf0394e-94e7-11e8-91c5-c0d43afb37f3.png)

For `counsel-rg`, I have to define it in the function, e.g. `  (counsel-rg "list" "." "--type-add 'logs:*.{org}' -t logs")`.

**Comment by basil-conto** [comment]
> We are not likely to know how to apply the extra args.

Like I said:

> you **might** be able to infer it

;)

> Useful tips like `M-n`, `M-p` are the hidden power of ivy.

Actually, those are well-documented Emacs features that Ivy just adapts to its own needs; see [`(emacs) Minibuffer History`](https://www.gnu.org/software/emacs/manual/html_node/emacs/Minibuffer-History.html).

> I also doubt extra args is documented in the mannual.

The relevant search commands (`counsel-ag` et al.) are not documented in the manual, let alone their treatment of prefix arguments.

> I didn't test `counsel-ag` but `counsel-rg` doesn't work this way.

What way? Please try to be more specific when describing issues, it's not always clear what you're referring to.

If you're talking about prefix argument handling, then `counsel-rg` works just like `counsel-ag` for me, i.e. it first prompts for a working directory, then for extra command-line options, and finally starts a `ripgrep` completion session.

> But Spacemacs has `counsel-search` functions, and they can apply args via input.

Can you please elaborate? You mean the search term can be mixed together with extra command-line options, like in #1559?

> For `counsel-rg`, I have to define it in the function

What does "it" refer to? Again, please be more explicit when describing issues/scenarios and expected vs actual behaviour.

**Comment by ztlevi** [comment]
Oh, sorry. Let me fix my issue.

What I mean is `counsel-rg` cannot take extra command line options, like in https://github.com/abo-abo/swiper/pull/1559. Shown in the picture below. And I need to use functions to define extra prefix, e.g. `(counsel-rg "list" "." "--type-add 'logs:*.{org}' -t logs")`.

![image](https://user-images.githubusercontent.com/16655096/43536919-be3d95a4-9572-11e8-8394-30ed8f34c21a.png)

But `spacemacs/search-rg` can apply extra command line options. [Here](https://github.com/syl20bnr/spacemacs/blob/develop/layers/+completion/ivy/funcs.el#L68) is the function used in Spacemacs to genereate counsel-search functions.

![image](https://user-images.githubusercontent.com/16655096/43494342-2bf0394e-94e7-11e8-91c5-c0d43afb37f3.png)

Thank you!

**Comment by basil-conto** [comment]
> `counsel-rg` cannot take extra command line options, like in #1559.

That's to be expected, given that #1559 hasn't landed yet.

> And I need to use functions to define extra prefix

WDYM by "use functions" and "define extra prefix"? You can programmatically set a prefix argument by setting `prefix-arg` and calling `call-interactively`; see [`(elisp) Interactive Call`](https://www.gnu.org/software/emacs/manual/html_node/elisp/Interactive-Call.html) and [`(elisp) Prefix Command Arguments`](https://www.gnu.org/software/emacs/manual/html_node/elisp/Prefix-Command-Arguments.html).

> `(counsel-rg "list" "." "--type-add 'logs:*.{org}' -t logs")`

No need for `"."` in Elisp; either pass `nil` for this argument, or use `default-directory`.

> But `spacemacs/search-rg` can apply extra command line options.

Won't this also be possible with vanilla Counsel after #1559 lands?

If #1559 doesn't address all your voiced concerns, can you please clarify the purpose of this issue?

**Comment by ztlevi** [comment]
Oh, I don't have any issues anymore. Once https://github.com/abo-abo/swiper/pull/1559 is merged, we can apply the extra command line options in the input. But I'm fine to define my own custom counsel search function to do add the options.

Thanks a lot!
