### ISSUE TITLE
Closest match always listed 6th

### ISSUE THREAD

**Issue by rafaelgp** [abo-abo/swiper#169]
Hello,

I have a question regarding the way matches are listed.

When I type 'find-file', the 'find-file' command it's correctly highlighted as the closest match, but it's listed 6th in the list.

![Ivy-find-file](http://clients.tourvista.co.uk/vt/zip/tmp/ivy-1.jpg)

I think this is because Ivy list the commands alphabetically and then it vertically centres the closest match. Am I right?
There must be a reason behind this as this behaviour is always constant. 
If I type 'ibuffer' it's listed 6th too :-)

![Ivy-find-file](http://clients.tourvista.co.uk/vt/zip/tmp/ivy-2.jpg)

From my point of view it would be better put the closest match right at the top.

Many thanks!

**Comment by abo-abo** [comment]
> If I type 'ibuffer' it's listed 6th too :-)

This issue can also be "fixed" by using `counsel-M-x`. As for other commands, `ivy-mode` sorts the candidates with `string-lessp` by default.  You can customize that for some or all commands using `ivy-sort-functions-alist`.
