### ISSUE TITLE
swiper not woking ivy-alist-setting definition is void

### ISSUE THREAD

**Issue by DJJ88** [abo-abo/swiper#1690]
Hello,

I've installed ivy and swiper from melpa and when I call swiper  i get the following error
Symbol’s function definition is void: ivy-alist-setting

my emacs version is 
GNU Emacs 25.3.2 (x86_64-pc-linux-gnu, GTK+ Version 2.24.31) of 2018-01-12
swiper version is  20180731.1549,
ivy version is 20180731.1520

Best regards,

Jeremie

**Comment by abo-abo** [comment]
Please reinstall and restart; that should fix the issue.

**Comment by DJJ88** [comment]
many thanks the issue is fixed.
Best regards,

jeremie

**Comment by abo-abo** [comment]
You're welcome.
