### ISSUE TITLE
swiper--re-builder and start of line anchor

### ISSUE THREAD

**Issue by papercatlol** [abo-abo/swiper#1692]
Hello,
If any ivy-re-builder that returns a list of (re . match-p) pairs is used,
`swiper--re-builder` creates invalid regexps from strings that have a start of line anchor `^` :
```
ELISP> (let ((ivy-re-builders-alist '((t . ivy--regex-ignore-order))))
         (swiper--re-builder "^ foo bar"))
"^ ?\\(((foo . t) (bar . t))\\)"
```

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by papercatlol** [comment]
Works, thanks!
