### ISSUE TITLE
Is there a way to disable"mouse click selects"?

### ISSUE THREAD

**Issue by halloleo** [abo-abo/swiper#1693]
When I'm in an ivy selection, e.g. in `write-file` (with `ivy-mode` switched on), is there a way to disable "mouse click selects"? 

It confuses the hell out of me when I click with the mouse in the minibuffer area (because, say, I come from another app) and then the line I click on gets selected *and the minbuffer closes*...

**Comment by basil-conto** [comment]
You can disable left clicks during Ivy completion with the following setting:

```el
(with-eval-after-load 'ivy
  (define-key ivy-minibuffer-map [mouse-1] #'ignore))
```

**Comment by halloleo** [comment]
This works a treat. thanks a lot.

**Comment by joca-bt** [comment]
Shouldn't this be controlled by a proper customization?

**Comment by abo-abo** [comment]
Customizing `ivy-minibuffer-map` is pretty straightforward. You can go to the definition of the variable and see what's bound there already and disable it. I don't think adding a `defcustom` for a single key is productive in this case.

**Comment by basil-conto** [comment]
> Shouldn't this be controlled by a proper customization?

Can you please elaborate on what you mean by "proper" customisation? Are you referring to user options (`defcustom`)? In Emacs, global keymaps like `ivy-minibuffer-map` are intended for customisation just as much as user options, but each has a different scope/purpose. Trying to reflect the flexibility of a keymap in a simpler user option would be tantamount to providing another keymap, i.e. it would be redundant. Don't forget that everyone has different preferences when it comes to key bindings - providing user options for each user's preferences would be an exercise in futility. Like @abo-abo, I don't think this particular example is both popular and complex enough to warrant a dedicated user option.

**Comment by joca-bt** [comment]
I meant a `defcustom`. Sure, now is just unbinding `mouse-1` but if you add more mouse bindings in the future or other mouse functionality users will have to disable all of them, individually. I was suggesting whether having a specific `defcustom` to disable all mouse-related functionality would make sense.
