### ISSUE TITLE
How to select an entry, but keep the prompt open to edit the selection

### ISSUE THREAD

**Issue by halloleo** [abo-abo/swiper#1694]
I am struggling with using `ivy-mode` in `write-file`:

Let's say I have the files `my_text_file_with_a_long_name.txt` and `my_text_file.txt` in my working directiory and I want to write the current buffer as `my_text_file_with_a_long_name_NEW.txt`.

So I start typing `m` `y` `_` and sure the two files get listed for selection, but how can I select the first option *and* keep the prompt open to edit the selection? I tried `ivy-done`, `ivy-call`, `ivy-partial-or-done` to no avail...

**Comment by papercatlol** [comment]
Try `ivy-insert-current` - `M-i` by default.

**Comment by halloleo** [comment]
Cool. Thanks.
