### ISSUE TITLE
counsel version of lsp-ui-peek

### ISSUE THREAD

**Issue by Dickby** [abo-abo/swiper#1697]
the lsp-ui package has some peek functions, that let you look at symbols/references/implementations, and jump to it.
It has a nice way of displaying the peeks in an overlay that tries to look like the same feature in vscode.
While it is nice, i prefer the swiper/ivy way, lsp-ui displays the peek in an overlay in the middle of the buffer,
splitted vertically into two sections that are equivalent to the swiper/ivy minibuffer and the code buffer.
I would really like to have an counsel version of these lsp-ui-peek features to have a more consistent experience.
Another point is that the ivy way is much faster from what i can tell.
Please consider offering a counsel version of those features.
Thanks.

**Comment by abo-abo** [comment]
Nice suggestion, I'm not using `lsp-ui` yet though. I once tried it for C++, but it appeared to not be working. There are also alternative places of where this could be implemented: either in an independent package or as part of `lsp-ui`.

**Comment by Dickby** [comment]
I realized lsp-ui-peek provides a function and sets `xref-backends-function`. 
So i can use ivy-xref to display it instead of the peek function.
Closing this
