### ISSUE TITLE
kill-buffer command

### ISSUE THREAD

**Issue by Pitometsu** [abo-abo/swiper#1699]
Previously `C-x k` have open a `counsel` dialog to select buffer for deletion for me. After an upgrade from emacs 25 to 26, things changed, and somewhy counsel doesnt't work this way. Is something changed in settings?

**Comment by Pitometsu** [comment]
`counsel-mode` enabled for sure,
```
C-x k runs the command kill-buffer (found in global-map), which is an
interactive built-in function in ‘C source code’.
```
No advices/remappings here for now.

**Comment by Pitometsu** [comment]
`ido-everywhere` disabling is helped. Looks like, previously, `counsel` had override it.

**Comment by abo-abo** [comment]
Thanks for the info. There was a bug like this a long time ago, also solved by disabling `ido-everywhere`. Basically, you can say the two packages are not compatible.
