### ISSUE TITLE
Maybe you can have a nicer message when call it from empty buffer

### ISSUE THREAD

**Issue by enzochiau** [abo-abo/swiper#17]
I first installed this package and try to call it in a empty buffer (I know it is not designed for a empty buffer). I got an error message as below:

    swiper--candidates: Arithmetic range error: "floor", -1.0e+INF

I think maybe you can just ignore this call or send useful error message like "no candidates" or "empty buffer" , etc.

**Comment by abo-abo** [comment]
Thanks for noticing, should work better now.
