### ISSUE TITLE
Go with ivy in find-file to different directory and do completion there

### ISSUE THREAD

**Issue by halloleo** [abo-abo/swiper#1709]
With ivy mode switched on I issue find-file in the directory `/my/first/directory/path`. In the kill ring I have the *absolute* path `/my/2nd/directory/path` and want to select a  file in this directory. I cannot figure a way out how to do this easily, despite various attempts:

* I tried yanking the new path and issued `ivy-partial`, `ivy-partial-or-done` or `ivy-insert-current`, but none accepts the new path.

* A work around is `.` (dot) + Enter, because it opens the dired buffer of `/my/2nd/directory/path`, but I want to select a file in the directory not the directory itself!

Any idea what to do?

**Comment by halloleo** [comment]
I found that `ivy-alt-done` in this case does select  the new directory in ivy, but normally `ivy-alt-done` *exits* ivy, only in this case it doesn't. 

Is there any command that is safer and  *does* select the new path, but does *not*  exit ivy in other cases?

**Comment by basil-conto** [comment]
I found that `ivy-alt-done` in this case does select the new directory in ivy, but normally `ivy-alt-done` exits ivy, only in this case it doesn't.

`ivy-alt-done` only exits file name completion when invoked on a file, not a directory. Quoth [`(ivy) Key bindings for single selection action then exit minibuffer`](http://oremacs.com/swiper/#key-bindings-for-single-selection-action-then-exit-minibuffer):

    ‘C-j’ (‘ivy-alt-done’)
    ......................

         When completing file names, selects the current directory candidate
         and starts a new completion session there.  Otherwise, it is the
         same as ‘ivy-done’.

Having said that, I now see that the docstring of `ivy-alt-done` makes no mention of this.

> Is there any command that is safer

WDYM by "safer"?

AFAICT `ivy-alt-done` works as expected here and addresses your issue.

See also #1424 for other woes with editing file names during Ivy completion.

**Comment by basil-conto** [comment]
> Having said that, I now see that the docstring of `ivy-alt-done` makes no mention of this.

Now with PR: #1710

**Comment by halloleo** [comment]
Thanks. Makes sense. Like this it is certainly safe enough (even for use of ivy in `dired-do-copy`.)
