### ISSUE TITLE
Inhibit field text motion

### ISSUE THREAD

**Issue by jslip** [abo-abo/swiper#1713]
Certain buffers have text fields that inhibit motion. For exaple, the prompt in the slime repl and most comint repls are text fields such that `C-a` moves to the end of the prompt rather than the beginning of the line. A consequence of this is that on lines with the prompt, swiper fails to match search strings. A fix for this is to set `inhibit-field-text-motion` to `t` during the search.
Thans.

**Comment by abo-abo** [comment]
Thanks.
