### ISSUE TITLE
cannot run most counsel/projectile commands

### ISSUE THREAD

**Issue by mattsawyer77** [abo-abo/swiper#1714]
I'm not sure when this started happening (pretty recently), but I can no longer execute commands such as 

* `counsel-projectile`
* `counsel-projectile-find-file`
* `counsel-projectile-find-dir`
* `counsel-projectile-switch-to-buffer`
* `ivy-persp-switch-project`

They all result in the following error in the messages buffer.
```
byte-code: Wrong type argument: arrayp, nil
```

Interestingly, I can run other non-counsel projectile commands (e.g. `projectile-find-file-dwim`). I don't know much about elisp or how to troubleshoot further. I've removed any ivy-related customizations I had, but that didn't help. I'm running emacs 26.1 on macOS with Spacemacs, if that helps.

**Comment by basil-conto** [comment]
Did you update your version of Emacs by any chance? I remember hearing something about changes on MELPA recently, but I have no idea what issues they gave rise to or whether they bear any relation to this one.

In any case, the solution to this kind of problem is often just to reinstall the packages.

**Comment by mattsawyer77** [comment]
@basil-conto I just did a clean install of emacs-mac and all my packages. The problem still remains. Any advice on troubleshooting or providing relevant info?

**Comment by basil-conto** [comment]
> Any advice on troubleshooting or providing relevant info?

Does enabling <kbd>M-x</kbd>`toggle-debug-on-error`<kbd>RET</kbd> give an error backtrace?

> I'm running emacs 26.1 on macOS with Spacemacs, if that helps.

Is it possible to reinstall Spacemacs packages/layers/configurations? (I don't use Spacemacs and don't know how it works, other than that it boils down to a custom Emacs config.)

**Comment by mattsawyer77** [comment]
OK I tried toggling debug, and got this when attempting to run `counsel-projectile`:

```
Debugger entered--Lisp error: (wrong-type-argument arrayp nil)
  define-key((keymap) nil counsel-projectile-command-map)
  byte-code("\301 \302\001\010\303#\210\302\001\304\305#\210\302\001\306\307#\210\302\001\310\311#\210\302\001\312\313#\210\302\001\314\315#\210\302\001\316\317#\210\211\207" [projectile-keymap-prefix make-sparse-keymap define-key counsel-projectile-command-map [remap projectile-find-file] counsel-projectile-find-file [remap projectile-find-dir] counsel-projectile-find-dir [remap projectile-switch-to-buffer] counsel-projectile-switch-to-buffer [remap projectile-grep] counsel-projectile-grep [remap projectile-ag] counsel-projectile-ag [remap projectile-switch-project] counsel-projectile-switch-project] 5)
  (defvar counsel-projectile-mode-map (byte-code "\301 \302\001\010\303#\210\302\001\304\305#\210\302\001\306\307#\210\302\001\310\311#\210\302\001\312\313#\210\302\001\314\315#\210\302\001\316\317#\210\211\207" [projectile-keymap-prefix make-sparse-keymap define-key counsel-projectile-command-map [remap projectile-find-file] counsel-projectile-find-file [remap projectile-find-dir] counsel-projectile-find-dir [remap projectile-switch-to-buffer] counsel-projectile-switch-to-buffer [remap projectile-grep] counsel-projectile-grep [remap projectile-ag] counsel-projectile-ag [remap projectile-switch-project] counsel-projectile-switch-project] 5) ("/Users/sawyer/.emacs.d/elpa/26.1/develop/counsel-projectile-20180731.2305/counsel-projectile.elc" . 49114))
  autoload-do-load((autoload "counsel-projectile" "Jump to a buffer or file in the current project.\n\nWith a prefix ARG, invalidate the cache first.\n\nIf not inside a project, call `counsel-projectile-switch-project'.\n\n(fn &optional ARG)" t nil) counsel-projectile)
  command-execute(counsel-projectile)
```

**Comment by basil-conto** [comment]
> * `counsel-projectile`
> * `counsel-projectile-find-file`
> * `counsel-projectile-find-dir`
> * `counsel-projectile-switch-to-buffer`
> * `ivy-persp-switch-project`

[...]

> OK I tried toggling debug, and got this when attempting to run `counsel-projectile`:

None of these functions are defined in this project, so it sounds like a bug with `counsel-projectile` or the corresponding Spacemacs layer; I suggest you raise it with one of them.

Cc: @ericdanan

**Comment by basil-conto** [comment]
I think you can use the following test to rule out `counsel-projectile.el`:

<kbd>M-x</kbd>`eval-buffer`<kbd>RET</kbd> inside `counsel-projectile.el` before <kbd>M-x</kbd>`counsel-projectile<kbd>RET</kbd>

If this works, then either `counsel-projectile.elc` became stale for some reason and just needs to be re-byte-compiled, or there's a more serious bug in the Emacs byte-compiler/interpreter.

If this doesn't work, then there remains an issue somewhere in your configuration or (mis-)installed packages.

**Comment by manuel-uberti** [comment]
Seems linked to this: https://github.com/ericdanan/counsel-projectile/issues/91

**Comment by basil-conto** [comment]
Looks and sounds about right, thanks @manuel-uberti. So I think this issue can be closed.

(Good thing I bit the bullet and switched to Emacs' built-in but very WIP `project.el` a short while ago. ;)

http://git.savannah.gnu.org/cgit/emacs.git/tree/lisp/progmodes/project.el

**Comment by ericdanan** [comment]
Sorry for the late reply. The issue was a recent commit in projectile that broke counsel-projectile. Please update counsel-projectile and it should work now (if not please open an issue in counsel-projectile).

**Comment by mattsawyer77** [comment]
Thanks @ericdanan. I just got the latest counsel-projectile and all is well.
