### ISSUE TITLE
Prevent <TAB> from creating directory in counsel-find-file

### ISSUE THREAD

**Issue by ericdanan** [abo-abo/swiper#1716]
With `ivy-magic-slash-non-match-action` set to `ivy-magic-slash-non-match-create`, if I do the following:
1. call `counsel-find-file` from `~`
2. type `emacs` so that the only matching candidate is `.emacs.d/`
3. hit <kbd>TAB</kbd> (`ivy-partial-or-done`)

then the directory `~/emacs.d/` is created and switched to, whereas I would expect to switch to directory `~/.emacs.d/` instead (I would only expect the directory `~/emacs.d/` to be created if I type `emacs.d/`).

Is this intentional?

Thanks.

**Comment by abo-abo** [comment]
Sorry, can't reproduce. How is `ivy-magic-slash-non-match-action` (which I thought would be related to <kbd>/</kbd>) related to <kbd>TAB</kbd>?

And if the directory already exists (since it's a candidate), how is it created again?

**Comment by ericdanan** [comment]
Strange, I'm able to reproduce with a clean emacs (26.1) where I only setup MELPA, install counsel, and execute:
```emacs-lisp
(counsel-mode)
(setq ivy-magic-slash-non-match-action 'ivy-magic-slash-non-match-create)
```
Then I call `counsel-find-file` from `~/` in which I have a directory `.emacs.d/` but not `emacs.d/`. In the minibuffer I type `emacs` and the only matching candidate is `.emacs.d/`. And then I hit `TAB`, which I also don't think would be related to `ivy-magic-slash-non-match-action`, but it does create the directory `emacs.d/` and switches to it (to be sure, this directory `emacs.d/` did not already exist and was not a candidate).

If instead of typing `emacs` I type `mac` the the newly created directory is `macs.d/` instead.

My impression is that `TAB` completes as much as possible after the minibuffer text. Since the only matching candidate is `.emacs.d/`, it also completes the final slash and this seems to trigger `ivy-magic-slash-non-match-action`, although it shouldn't since there's a match. But I'm not sure.

Can I do anything else to understand why I get this behavior and you don't?

Thanks in advance

**Comment by abo-abo** [comment]
Thanks, I was able to reproduce after your explanation. Please test.

**Comment by ericdanan** [comment]
It works as expected now, thanks.
