### ISSUE TITLE
ivy-mode: unable to exit an auto-insert completing-read prompt

### ISSUE THREAD

**Issue by glucas** [abo-abo/swiper#172]
Not sure if this is just a peculiarity of `auto-insert`, or a more general mismatch between the behavior of `completing-read` and `ivy-completing-read` with REQUIRE-MATCH true.

Try the following with `ivy-mode` enabled:
- Create a new .el file
- Call `M-x auto-insert` to insert the emacs lisp file template
- When prompted, enter a short description.

The next prompt is to build up the list of keywords. When `ivy-mode` is enabled there appears to be no way to exit the read loop and continue filling out the template. (I can `keyboard-quit` but that quits out of `auto-insert` altogether). With `ivy-mode` off one can add keywords and then hit RET to finish with keywords and continue.

**Comment by abo-abo** [comment]
> appears to be no way to exit the read loop and continue filling out the template

You need to exit with an empty input. You can do that with <kbd>C-u C-j</kbd>.  <kbd>C-u C-j</kbd> is generally useful if you want to enter your own input instead of a candidate that it matches.  Same thing with `debbugs-`.

**Comment by glucas** [comment]
Aha! I figured there was a way to do it but didn't find it. Thanks.
