### ISSUE TITLE
Change ivy height to function of Emacs frame height

### ISSUE THREAD

**Issue by jthaman** [abo-abo/swiper#1722]
Hi, thanks for your great work on this Emacs package.

I would like to set ivy-height to some variable that depends on my monitor situation. Since I use monitors in portrait configuration when my laptop is docked, I like to have ivy-height set to about 30 or 40. When I'm plugged into a landscape monitor or undocked, 30 is too much, I have been manually lowering ivy-height to about 15.

Any tips on how to set ivy-height to about 1/3 of Emacs frame height so that I don't have to manually fiddle with this variable?

Thanks,

**Comment by abo-abo** [comment]
Thanks, this config should work now:

```elisp
(add-to-list 'ivy-height-alist
             (cons 'counsel-find-file
                   (lambda (_caller)
                     (/ (frame-height) 2))))
```

If you want it for all callers, use `t` as key:

```elisp
(setq ivy-height-alist
      '((t
         lambda (_caller)
         (/ (frame-height) 2))))
```

Let me know if it works as expected.
