### ISSUE TITLE
search using swiper from word at point

### ISSUE THREAD

**Issue by zeltak** [abo-abo/swiper#173]
Hi!

i just remembers from the days far ago when i used vim the * command (at least i think it was * :) ) that started a search based on the current word on point. can swiper do that? if not can i add a request for that ;-)

thx!

z

**Comment by abo-abo** [comment]
You can do it by pressing <kbd>M-n</kbd>.

**Comment by zeltak** [comment]
perfect, i am switching from isearch to swiper :)
one short followup, can i issue a direct swiper from poing, ie assign a hotkey to start a search directly (so instead of C-s M-n) just one key

thx

z

**Comment by abo-abo** [comment]
Try this:

```elisp
(defun swiper-at-point ()
  (interactive)
  (swiper (thing-at-point 'symbol)))
```

**Comment by zeltak** [comment]
amazing ,thx so much!
