### ISSUE TITLE
Python interactive buffer pops up when using find-file with ivy-mode on

### ISSUE THREAD

**Issue by Saltychtao** [abo-abo/swiper#1730]
When I edit a python file and use find-file or counsel-find-file to open another file with ivy-mode on, a python interactive buffer  will always popup, which is very annoying. If I turn off ivy-mode, everything seems   fine.
Environment : Ubuntu 16.04 LTS , Emacs 26.1

**Comment by basil-conto** [comment]
I cannot reproduce this from either `make plain` or `emacs -Q` with any Emacs version between 25-27 (inclusive). If you are able to reproduce this from `emacs -Q`, then please provide the precise steps needed to reproduce the issue, e.g. which keys you press, which modes you enable, which files you visit, etc. If you are not able to reproduce the issue from `make plain` or `emacs -Q`, it means there is something in your configuration or your installed packages causing the issue.
