### ISSUE TITLE
Cannot use ivy-set-prompt with some counsel functions

### ISSUE THREAD

**Issue by ericdanan** [abo-abo/swiper#1731]
The following functions don't obey `ivy-set-prompt`:
- `counsel-git`
- `counsel-git-grep`
- `counsel-fzf`
- `counsel-ag`

The reason seems to be that these functions contain the following form:
```el
(ivy-set-prompt 'counsel-git counsel-prompt-function)
```
(replacing `'counsel-git` for the other ones).

So the only way I could find to modify the prompt for these functions is to let-bind `counsel-prompt-function`. But this variable is obsolete.

Should this form be simply removed from these functions? Perhaps it was left there for people who customized `counsel-prompt-function` before it became obsolete? (in which case, a solution could perhaps be to make that variable default to nil and make the form conditional on the variable being non-nil?)

Let me know if you'd like me to PR.

(I found out this issue because in counsel-projectile I define a command `counsel-projectile-git-grep` that calls `counsel-git-grep` but prepends the project name to the prompt. So I had to let-bind `counsel-prompt-function` but this causes the byte-compiler to issue warnings about the obsolete variable.)

**Comment by abo-abo** [comment]
Thanks, I finally removed the obsolete var.
