### ISSUE TITLE
Why some extra tramp connection schema prefix not in completion candidates?

### ISSUE THREAD

**Issue by stardiviner** [abo-abo/swiper#1733]
https://emacs.stackexchange.com/questions/44290/why-some-extra-tramp-related-packages-does-not-show-url-schema-prefix/44330#44330

When I press [C-x C-f] , I got some TRAMP methods shown like ssh: , sshx:. But not get docker: when I installed package docker-tramp. Does docker-tramp.el provide this? If yes, then how to configure it? If no, then is it possible to add it? There are many other tramp related packages like kubernetes-tramp and vagrant-tramp and adb: for Android etc.

After (require 'docker-tramp), and disable ivy-mode and counsel-mode. I can complete /docker: in minibuffer now. I guess this is a bug in Ivy. I also tested ido-mode and helm-mode. Seems happens on them too.

**Comment by jyp** [comment]
This type of behaviour happened to me after moving to emacs 26. But then I am not getting *any* tramp connection method in avy.

**Comment by abo-abo** [comment]
> I also tested ido-mode and helm-mode. Seems happens on them too.

You mean completion works for them, or doesn't work for them?

**Comment by stardiviner** [comment]
I mean doesn't work for them neither.

**Comment by abo-abo** [comment]
> This type of behaviour happened to me after moving to emacs 26. But then I am not getting any tramp connection method in avy.

@jyp thanks for the info. I can confirm this as well.

**Comment by abo-abo** [comment]
@jyp The issue on Emacs26 should be fixed now - when you're in the root folder, you'll get completion for tramp methods if you loaded tramp beforehand. I moved the methods below the folders and the files though.

@stardiviner There's completion for the docker: method. When I tried it, it did offer me a running container id for completion. However, after selecting it some error happened and I got no dired buffer. Let me know if it works for you.

**Comment by stardiviner** [comment]
It works for me. I keep pressing `TAB`, it gives me `/docker:<running_docker>:/path_or_file`. Then I select it. It does open it in a Dired or a file buffer. @abo-abo

**Comment by stardiviner** [comment]
@abo-abo Sorry for comment on old issue. But it's related to this issue (I guess).
I found ivy (or counsel) will prefix "`@`" for TRAMP remote host. For example:
when I completing docker container names after `/docker:`, It will complete with candidates:
```
my host name
@container_name
```
I guess this works for remote SSH machine. But should not on other TRAMP schema. This could be manually inserted if can't be stick on SSH only.

**Comment by abo-abo** [comment]
@stardiviner Please open a new issue with detailed steps to reproduce it.
