### ISSUE TITLE
Add ivy-update-view

### ISSUE THREAD

**Issue by juan-leon** [abo-abo/swiper#1737]
I think it could be useful to have an interactive function called
`ivy-update-view` that when invoked allow you to select one of your existing
views (ideally with the last view that user switched to in the top) and do the
equivalent of a `ivy-push-view`.

For me, for instance, it could replace the need for a "workspace manager" (like
eyebrowse).  I never used any of those for more than a few hours (as they
involve too many new keybindings and/or are too opinionated), but I really like
the "ivy views" and a single keybinding could be enough for me to jump into the
idea of those.

(I would even configure `projectile-switch-project-action` to look for an ivy
view and switch to it if exists (else do `magit-status` or `projectile-dired`
depending on other things)

**Comment by abo-abo** [comment]
Nice idea, thanks. Please test.

**Comment by juan-leon** [comment]
Works like a charm, thanks.
