### ISSUE TITLE
The official recommended counsel-ag key binding is not very good

### ISSUE THREAD

**Issue by re-mx** [abo-abo/swiper#1738]
Hello:

See http://oremacs.com/swiper/#global-key-bindings

I think "C-c k" is easy to confuse with "C-x k".

Although I know this can be changed, but would you like to change the recommendation key binding?

Thanks.

**Comment by basil-conto** [comment]
FWIW, I'm more concerned with the wording "The recommended key bindings are". Shouldn't this read more like "Here are some useful commands, along with sample key bindings" or similar?

**Comment by re-mx** [comment]
@basil-conto 
You are right, but some people will only copy and paste this code into their own `init.el` -- at least I will.

So I think it is necessary to choose a more reasonable key binding to add to the description.
Although I don't know which key will be more reasonable. But I think a key that will be confused with `kill-buffer` is not so reasonable.

Sorry for my poor English.

**Comment by basil-conto** [comment]
Given that key sequences consisting of <kbd>C-c</kbd> (`mode-specific-map`) followed by a letter are reserved for users (see [`(emacs) Key Bindings`](https://www.gnu.org/software/emacs/manual/html_node/emacs/Key-Bindings.html), I'd say there are plenty of <kbd>C-c</kbd> bindings which are "close" to the corresponding <kbd>C-x</kbd> binding. IMO there's little, if at all, we can do about this in the general case.

Besides, `kill-buffer` prompts the user before doing anything, so accidental mistypes have a relatively low chance of breaking much.

**Comment by re-mx** [comment]
Indeed... I found that other key bindings are easy to conflict.
For example, <kbd>M-?</kbd>. This is the key binding for `counsel-ag` I am using now. But it conflicts with the key binding of xref.

**Comment by re-mx** [comment]
I think <kbd>M-s a</kbd> is good.

**Comment by basil-conto** [comment]
> I think <kbd>M-s</kbd><kbd>a</kbd> is good.

That's what I use in my configuration, in order to reuse [`search-map`](https://www.gnu.org/software/emacs/manual/html_node/elisp/Standard-Keymaps.html). :)

**Comment by abo-abo** [comment]
Thanks, I changed the wording a little bit.

> BTW What I don't understand is why it is k.

<kbd>C-c j</kbd> and <kbd>C-c k</kbd> are easy to press, since j/k are on the home row of your right hand.
