### ISSUE TITLE
How to disable searching in invisible text? (setq search-invisible nil) has no effect

### ISSUE THREAD

**Issue by QiangF** [abo-abo/swiper#1739]

**Comment by abo-abo** [comment]
Please give a use case of a buffer with half-invisible / half-visible text.

**Comment by QiangF** [comment]
I want to search for function names after outline-hide-sublevels. Also you can serach in org headings.

**Comment by abo-abo** [comment]
I don't think it's essential for `swiper` to have this feature.

There are better ways for getting completion for function names or outline headings, like e.g. `counsel-imenu` or `counsel-semantic`.

**Comment by QiangF** [comment]
The problem with counsel is that it uses the minibuffer, too small if the file is large, it always helps if you can see more.

**Comment by QiangF** [comment]
And there's more functions you can use in a folded buffer than in the counsel minibuffer. Moreover isearch has this functionality.

**Comment by QiangF** [comment]
It's can also be used in folded outline buffer (headings). The following enables outline for all program mode.

    (defun my-heading()
    "custom heading for all prog mode"
    (when (and (not (equal major-mode 'org-mode)) comment-start)
      (make-local-variable 'my-outline-regexp)
      (make-local-variable 'my-outline-max-level)
      (setq my-outline-max-level 8)
      (setq my-outline-regexp (concat (regexp-quote comment-start) " [*]\\{1,8\\}"))
      (setq outline-heading-alist '()) ;; make outline promote work
      (let ((level 0)
        (level-prefix (concat comment-start " ")))
        (while (< level my-outline-max-level)
        (setq outline-heading-alist (cons (cons level-prefix level) outline-heading-alist)
        level (1+ level)
        level-prefix (concat level-prefix "*")))
        (setq outline-heading-alist (nreverse outline-heading-alist)))
      (setq outline-regexp (concat my-outline-regexp "\\|" outline-regexp)
        outline-level (lambda()
         (let* ((data (match-data))
           (start (car data))
           (end (cadr data))
           (level (- end start)))
           (if (looking-at my-outline-regexp)
           (- level 2) ;; subtract two spaces
           (+ level my-outline-max-level));; 8 is the maximum custom heading levels)))))
    (add-hook 'outline-minor-mode-hook 'my-heading)

swiper will be much better than isearch

    (defun jmm/isearch-forward-visible ()
    "Just `isearch-forward` but don't match invisible text."
    (interactive)
    (let ((search-invisible nil))
        (isearch-forward)))

**Comment by abo-abo** [comment]
Sorry, it's still not clear for me. I can't get your code to work.

**Comment by QiangF** [comment]
It just customizes the outline regexp for heading, so for elisp mode you have heading like:

    ; * heading level 1
    ; ** heading level 2

for python mode it is:

    #  * heading level 1:
    #  * heading level 2:

If search-invisible is enabled, we can fold the outline and easily search in those headings.

**Comment by abo-abo** [comment]
Thanks, please test.
