### ISSUE TITLE
Why my highlighting is so "fancy"?

### ISSUE THREAD

**Issue by ChoppinBlockParty** [abo-abo/swiper#1746]
I am fuzzy completion with flx and here you can see fzf example. The highlighting obfuscates the result too much. Did I set something wrong?
![selection_014](https://user-images.githubusercontent.com/28957323/45259662-fbde8080-b3d1-11e8-9b86-ff6d6562815c.png)

**Comment by abo-abo** [comment]
The highlighting appears to work correctly. Try `customize-group` `ivy-faces`. Or check your theme.

**Comment by ChoppinBlockParty** [comment]
I could not figure out where the colors are coming, probably somewhere from the theme, because colors in `ivy.el` of the faces are different. However, change

    (custom-set-faces
      '(ivy-minibuffer-match-face-1 ((t (:background "dark orchid" :foreground "#eeeeee" :weight bold))))
      '(ivy-minibuffer-match-face-2 ((t (:background "dark orchid" :foreground "#eeeeee" :weight bold))))
      '(ivy-minibuffer-match-face-3 ((t (:background "dark orchid" :foreground "#eeeeee" :weight bold))))
      '(ivy-minibuffer-match-face-4 ((t (:background "dark orchid" :foreground "#eeeeee" :weight bold))))
      )

did the job, now it displays properly.
