### ISSUE TITLE
I can't search for things with '(' in them with counsel-rg

### ISSUE THREAD

**Issue by parbo** [abo-abo/swiper#1758]
It seems to be interpreted as regex group start. It works fine with '['. 

My regex-builders are:

```
  (setq ivy-re-builders-alist
        '((swiper . ivy--regex-plus)
          (read-file-name-internal . ivy--regex-fuzzy)
	  (counsel-git-grep . ivy--regex-plus)
	  (t . ivy--regex-plus)))
```

**Comment by abo-abo** [comment]
Can't reproduce on gnu/linux, Emacs 26.1, ripgrep 0.8.1.

My `ivy-re-builders-alist` setting is `((t . ivy--regex-plus))`, so it's same as yours wrt `counsel-rg`.

**Comment by abo-abo** [comment]
For instance, I get results for this repo with input text `(def`.

**Comment by parbo** [comment]
It seems to be because I'm on Windows and use git bash as my shell. 

I have this:

```
(if (equal system-type 'windows-nt)
    (progn (setq explicit-shell-file-name
                 "C:/Program Files/Git/bin/sh.exe")
           (setq shell-file-name "bash")
           (setq explicit-sh.exe-args '("--login" "-i"))
           (setenv "SHELL" shell-file-name)
           (add-hook 'comint-output-filter-functions 'comint-strip-ctrl-m)
           (add-to-list 'exec-path "C:/Program Files/Git/bin")
           (defadvice grep-compute-defaults (around grep-compute-defaults-advice-null-device)
             "Use cygwin's /dev/null as the null-device."
             (let ((null-device "/dev/null"))
               ad-do-it))
           (ad-activate 'grep-compute-defaults)))
```

If I remove that, `counsel-rg` works fine. So there's probably some argument quoting that gets messed up.

**Comment by abo-abo** [comment]
@parbo I don't have Windows, so I can't debug this myself. Try debugging `counsel-ag-function`, eval this bit:

```elisp
(counsel--format-ag-command
 switches
 (shell-quote-argument regex))
```

This is what gets passed to the shell. Then try pasting the command directly into the shell.

**Comment by parbo** [comment]
Output of:
```
(counsel--format-ag-command
 ""
 (shell-quote-argument "reg("))
```
executed in bash:
´´´
$ rg -S --no-heading --line-number --color never   reg\( .
Error parsing regex near 'reg(' at character offset 3: Unclosed parenthesis.
´´´

It seems like the problem is that `shell-quote-argument` quotes for cmd.exe even though I set the shell to bash. I'll see if I can configure things in another way.

**Comment by parbo** [comment]
No need fo you to fix anything then.
