### ISSUE TITLE
Window focus issue when using counsel-M-x

### ISSUE THREAD

**Issue by kaushalmodi** [abo-abo/swiper#176]
I recently noticed that I get window focus issue only when using `counsel-M-x`, not when using `smex` or `execute-extended-command`.

Here's an example:

If I do `M-x counsel-M-x calc RET`, the Calculator buffer opens but then the focus switches back to the window from where I executed that `M-x counsel-M-x`.

To test it out, do the below binding:

```el
(global-set-key (kbd "C-c :") #'counsel-M-x)
```

and then do `C-c : calc RET`.

This issue does not occur when I do  `M-x smex calc RET` or `M-x execute-extended-command calc RET`.

[[my counsel setup]][1]

[1]: https://github.com/kaushalmodi/.emacs.d/blob/e457bd18468b0151c65225f3f57a5c85c4694e61/setup-files/setup-counsel.el

**Comment by abo-abo** [comment]
Thanks, it's a very strange bug. I don't quite understand it: a combination of `with-selected-window` and `execute-extended-command` leads to failure.  I'm not sure it should.
