### ISSUE TITLE
Quiting ivy-reverse-i-search

### ISSUE THREAD

**Issue by ChoppinBlockParty** [abo-abo/swiper#1764]
How can I quit `ivy-revese-i-search` state back to the last ivy session? Invoking `ivy-done` does this, but it takes the selected result from `ivy-reverse-i-search`. `quit-minibuffer` invoked once does not quit i-search state, invoked twice it does quit the whole ivy-session. Is it a bug, it it relevant to #1215?

**Comment by basil-conto** [comment]
> Is it a bug, it it relevant to #1215?

Yes, it sounds like you're describing the same issue as in #1215 and #1235.

**Comment by ChoppinBlockParty** [comment]
Oh, yes, you are right, more than yeah ago. So this is a duplicate of #1235.
