### ISSUE TITLE
Match highlighting in ivy occur mode

### ISSUE THREAD

**Issue by ChoppinBlockParty** [abo-abo/swiper#1765]
Seems like match is not highlighted in ivy-occur mode, I found this to be true for all commands, but most importantly in `counsel-ag/rg`. Am I missing something, or this is currently unavailable in ivy?

**Comment by basil-conto** [comment]
Can you please provide an exact and reproducible set of steps, rather than a high-level description? This will make identifying the exact issue much easier.

**Comment by ChoppinBlockParty** [comment]
Yeah, sure, sorry for that.

![selection_015](https://user-images.githubusercontent.com/28957323/46015457-a3e29200-c0d2-11e8-9d27-80c06224dc94.png)

That is what I meant. Top is ivy-occur rg results, and bottom is rg-mode results. I am wondering if there is something that can enable highlight like in rg-mode.

**Comment by ChoppinBlockParty** [comment]
https://github.com/dajva/rg.el

**Comment by mookid** [comment]
@abo-abo I guess it can be closed?

**Comment by ChoppinBlockParty** [comment]
Sorry,  but I do not see difference, is there any options to enable it, otherwise occurrences are not highlighted.

**Comment by mookid** [comment]
Well, when I run counsel-rg followed by ivy-occur, I get the following kind of buffer:

![image](https://user-images.githubusercontent.com/7757342/49372210-323e4a00-f6fa-11e8-93b5-a00c5c8d176b.png)

What is your reproduction case?

**Comment by Alexander-Shukaev** [comment]
In my case, I have a different problem.  Initially the highlighting is indeed in place but if I `revert-buffer`, it disappears.

**Comment by abo-abo** [comment]
This is fixed now, closing.
