### ISSUE TITLE
ivy-switch-buffer: calling current-buffer soon afterward returns old buffer

### ISSUE THREAD

**Issue by mehw** [abo-abo/swiper#1766]
Hello.

Could someone confirm the following, please?

## Description #

Switching buffer from `A` to `B` via `ivy-switch-buffer` changes the buffer to `B` as expected, but calling `current-buffer` soon afterward returns `A` not `B`!

## Versions affected #

- ivy MELPA 20180917.2237
- https://github.com/abo-abo/swiper/tree/71b60a72d30cf110ed906ea744cbe273869130d2

## How to replicate #

Register the command `testme-ivy-switch-buffer` below, then run it via `M-x testme-ivy-switch-buffer`.  Then, try to switch to a different buffer and take note of the printed message.
```
(defun testme-ivy-switch-buffer ()
  (interactive)
  (ivy-switch-buffer)
  ;; NOTE: Delay `message' with `run-with-timer' to get proper results,
  ;; i.e. (run-with-timer 0.5 nil (lambda () (message ...))).  On my
  ;; system just 0.00005 seconds are enough to get proper results.
  (message "(current-buffer): %s | (window-buffer (selected-window)): %s"
           (current-buffer) (window-buffer (selected-window))))
```
Expected odd results:
- `(current-buffer)` returns the **old buffer**.
- `(window-buffer (selected-window))` returns the **buffer switched to**.

## Implementation notes #

There's a sort of oddity in `ivy-call`:
```
(with-current-buffer (ivy-state-buffer ivy-last)
  (unwind-protect (funcall action x)
    (ivy-recursive-restore)))
```
When `action` is `ivy--switch-buffer-action`, it switches buffer to `x`, but the wrapping `with-current-buffer` set it back to `ivy-last`'s registered `:buffer`... the old buffer.

## Proposed solution #

Excuse me for not opening a PR... my bad...

I pushed a commit on a new branch and there should be a [referenced solution](https://github.com/mehw/swiper/commit/ebd91cb66f908d9db90ecfe722bff3565ed84532) right here.

**Comment by basil-conto** [comment]
Ccing @raxod502 who had some insights on related code in #1607.

**Comment by basil-conto** [comment]
@mehw Can you please review #1767?

**Comment by basil-conto** [comment]
> the wrapping `with-current-buffer` set it back to `ivy-last`'s registered `:buffer`... the old buffer.

Which is why I think this `with-current-buffer` can/should be removed, though I'm not 100% sure.

**Comment by mehw** [comment]
> Ccing @raxod502 who had some insights on related code in #1607.

Please, also see @ericdanan [717\#issuecomment-321920963](https://github.com/abo-abo/swiper/issues/717#issuecomment-321920963).

> @mehw Can you please review #1767?

It seems to work. Thanks!

> Which is why I think this `with-current-buffer` can/should be removed, though I'm not 100% sure.

Peer reviews will be helpful... Please, kindly review #1767.

**Comment by abo-abo** [comment]
Thanks, all.
