### ISSUE TITLE
counsel-git-grep very slow on windows

### ISSUE THREAD

**Issue by NingyuShi** [abo-abo/swiper#1769]
Take 15s to start on a 3M line repo. Interactive search also very slow. I tried helm-git-grep, the speed is reasonable, so it's not a git/repo issue.

**Comment by basil-conto** [comment]
I evaluated the following in the [GNU Emacs sources](http://git.savannah.gnu.org/cgit/emacs.git/), which amount to 4+ million LoC according to https://stackoverflow.com/a/4822516/3084001, starting with both `make plain` and my own configuration.

```el
(benchmark-run 1 (counsel-git-grep nil "list"))
```

Typing <kbd>RET</kbd> when the first results appear in both cases gives ~0.7s.

I tried both with the latest Emacs development version:

    In GNU Emacs 27.0.50 (build 14, x86_64-pc-linux-gnu, X toolkit, Xaw3d scroll bars)
     of 2018-09-26 built on thunk
    Repository revision: f1aa21a5b25b9371b42c267ef9ec557fa75ec95a
    Windowing system distributor 'The X.Org Foundation', version 11.0.12001000
    System Description: Debian GNU/Linux buster/sid

    Configured using:
     'configure --config-cache --prefix=/home/blc/.local --with-mailutils
     --with-x-toolkit=lucid --with-modules --with-file-notification=yes
     --with-x 'CC=ccache gcc' 'CFLAGS=-O2 -march=native -pipe''

    Configured features:
    XAW3D XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS
    GLIB NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT
    ZLIB TOOLKIT_SCROLL_BARS LUCID X11 XDBE XIM MODULES THREADS LIBSYSTEMD
    JSON LCMS2 GMP

and with Debian's `emacs-lucid`:

    In GNU Emacs 25.2.1 (x86_64-pc-linux-gnu, X toolkit, Xaw3d scroll bars)
     of 2018-08-27, modified by Debian built on x86-csail-01
    Windowing system distributor 'The X.Org Foundation', version 11.0.12001000
    System Description: Debian GNU/Linux testing (buster)

    Configured using:
     'configure --build x86_64-linux-gnu --prefix=/usr
     --sharedstatedir=/var/lib --libexecdir=/usr/lib
     --localstatedir=/var/lib --infodir=/usr/share/info
     --mandir=/usr/share/man --with-pop=yes
     --enable-locallisppath=/etc/emacs:/usr/local/share/emacs/25.2/site-lisp:/usr/local/share/emacs/site-lisp:/usr/share/emacs/25.2/site-lisp:/usr/share/emacs/site-lisp
     --with-sound=alsa --without-gconf --build x86_64-linux-gnu
     --prefix=/usr --sharedstatedir=/var/lib --libexecdir=/usr/lib
     --localstatedir=/var/lib --infodir=/usr/share/info
     --mandir=/usr/share/man --with-pop=yes
     --enable-locallisppath=/etc/emacs:/usr/local/share/emacs/25.2/site-lisp:/usr/local/share/emacs/site-lisp:/usr/share/emacs/25.2/site-lisp:/usr/share/emacs/site-lisp
     --with-sound=alsa --without-gconf --with-x=yes --with-x-toolkit=lucid
     --with-toolkit-scroll-bars --without-gsettings 'CFLAGS=-g -O2
     -fdebug-prefix-map=/build/emacs-7bZ65w/emacs-25.2+1=. -fstack-protector-strong
     -Wformat -Werror=format-security -Wall' 'CPPFLAGS=-Wdate-time
     -D_FORTIFY_SOURCE=2' LDFLAGS=-Wl,-z,relro'

    Configured features:
    XAW3D XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS NOTIFY ACL
    LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB
    TOOLKIT_SCROLL_BARS LUCID X11

When reporting issues, please try to provide as much detail as possible. "It's slow for me" doesn't give much for others trying to help to go on.

Have you tried reproducing the slowdown starting from `emacs -Q` or `make plain`?

**Comment by basil-conto** [comment]
Oops, sorry, I only just noticed the mention of Windows in the issue title. I'm afraid I won't be able to help debug this much further then. I do, however, recall hearing about Git and shell performance issues on Windows. Maybe `helm-git-grep` works around these, e.g. by calling Git directly, rather than through the shell, as `counsel-git-grep` does.

**Comment by ChoppinBlockParty** [comment]
Can execute exactly the same grep query outside of Emacs, in shell? What time does it take? If it is about the same time, it is not counsel nor Emacs problem, but something more fundamental.

**Comment by basil-conto** [comment]
@NingyuShi My question re: reproducing from `emacs -Q` or `make plain` still stands. The slowdown is likely unrelated to your configuration, but it would be nice to eliminate this variable from the equation.

**Comment by NingyuShi** [comment]
@basil-conto I'll try and get back.

**Comment by basil-conto** [comment]
@NingyuShi Here's a simple benchmark you can run to quickly compare process, shell, and output performance:

```el
;;; my.el --- simple process invocation benchmark -*- lexical-binding: t -*-

;;; Commentary:

;; 0. Set `my-dir' to the directory in which you want to benchmark invocations
;;    of `my-program'.  The default is `source-directory'.
;; 1. Adapt search pattern in `my-switches' to your repository.
;;    The default is "hash-table".
;; 2. Byte-compile this file:
;;      emacs -batch -f batch-byte-compile my.el
;; 3. Benchmark `my-run':
;;      emacs -batch -l my.el -f my-run

;;; Code:

(defvar my-dir source-directory
  "Directory in which to run `my-program' benchmarks.")

(defvar my-program "git"
  "Name of executable to benchmark.")

(defvar my-switches '("grep" "-e" "hash-table")
  "List of arguments to pass `my-program'.")

(defun my--command ()
  "Quote `my-program' and `my-switches' as a shell command."
  (mapconcat #'shell-quote-argument (cons my-program my-switches) " "))

(defun my--sentinel (proc msg)
  "Kill PROC buffer on success; signal error with MSG otherwise."
  (cond ((eq (process-status proc) 'run))
        ((/= (process-exit-status proc) 0)
         (error "%s %s" (process-name proc) (substring msg 0 -1)))
        ((buffer-live-p (process-buffer proc))
         (kill-buffer (process-buffer proc)))))

(defun my--start (fn name &rest args)
  "Start a subprocess and wait for it to exit.
Call FN as (apply FN NAME BUF ARGS), where BUF is an internal
buffer name based on NAME."
  (let* ((process-connection-type nil)
         (proc (apply fn name (format " *%s*" name) args)))
    (set-process-sentinel proc #'my--sentinel)
    (while (eq (process-status proc) 'run)
      (accept-process-output proc))))

(defun my-call-proc ()
  "Invoke `my-program' using `call-process'."
  (with-temp-buffer
    (apply #'call-process my-program nil t nil my-switches)))

(defun my-call-proc-to-str ()
  "Like `my-call-proc', but return output as a string."
  (with-output-to-string
    (apply #'call-process my-program nil standard-output nil my-switches)))

(defun my-proc-lines ()
  "Invoke `my-program' using `process-lines'."
  (apply #'process-lines my-program my-switches))

(defun my-start-proc ()
  "Invoke `my-program' using `start-process'."
  (apply #'my--start #'start-process "my-start-proc"
         (cons my-program my-switches)))

(defun my-call-proc-shell ()
  "Invoke `my-program' using `call-process-shell-command'."
  (with-temp-buffer
    (call-process-shell-command (my--command) nil t nil)))

(defun my-start-proc-shell ()
  "Invoke `my-program' using `start-process-shell-command'."
  (my--start #'start-process-shell-command "my-start-proc-shell" (my--command)))

(defun my-shell-to-str ()
  "Invoke `my-program' using `shell-command-to-string'."
  (shell-command-to-string (my--command)))

(defun my-run ()
  "Benchmark `my-program' invocations."
  (let ((default-directory my-dir))
    (mapc (lambda (fn)
            (garbage-collect)
            (message "%-19s %s" fn
                     (benchmark-run 1
                       (funcall fn))))
          (list #'my-call-proc
                #'my-call-proc-to-str
                #'my-proc-lines
                #'my-start-proc
                #'my-call-proc-shell
                #'my-start-proc-shell
                #'my-shell-to-str))))

;;; my.el ends here
```

**Comment by basil-conto** [comment]
@abo-abo Could `:dynamic-collection` affect performance in any way?

**Comment by NingyuShi** [comment]
@basil-conto Here is the result for the benchmark

my-call-proc        (1.799747 0 0.0)
my-call-proc-to-str (1.795555 0 0.0)
my-proc-lines       (2.102363 1 0.009641000000000004)
my-start-proc       (7.722663 0 0.0)
my-call-proc-shell  (1.832599 0 0.0)
my-start-proc-shell (7.6909410000000005 0 0.0)
my-shell-to-str     (1.853261 0 0.0)

**Comment by basil-conto** [comment]
Looks like the culprit is not the shell, but slow reading of asynchronous output.

Does toggling the value of `process-adaptive-read-buffering` make any difference? What is your value of <kbd>M-x</kbd>`emacs-version`<kbd>RET</kbd>?

**Comment by NingyuShi** [comment]
Emacs version: GNU Emacs 27.0.50 (build 1, x86_64-w64-mingw32) of 2018-06-19

**Comment by NingyuShi** [comment]
I add
`(setq process-adaptive-read-buffering nil)` and run again, here is the result

my-call-proc        (1.7725849999999999 0 0.0)
my-call-proc-to-str (1.701768 0 0.0)
my-proc-lines       (1.7217470000000001 1 0.006274000000000002)
my-start-proc       (7.716476 0 0.0)
my-call-proc-shell  (1.93261 0 0.0)
my-start-proc-shell (7.679424 0 0.0)
my-shell-to-str     (2.23288 0 0.0)

**Comment by NingyuShi** [comment]
Moved to counsel-rg with no performance issue
