### ISSUE TITLE
Is it possible to have org-mode invoke counsel-org-tag instead of the default behavior?

### ISSUE THREAD

**Issue by bbigras** [abo-abo/swiper#1773]
Is it possible to have org-mode invoke counsel-org-tag when I do `C-c C-c` or `C-c C-q` on an headline instead of the default behavior?

**Comment by basil-conto** [comment]
What are your <kbd>M-x</kbd>`emacs-version`<kbd>RET</kbd> and <kbd>M-x</kbd>`org-version`<kbd>RET</kbd>?

Does the following advice have the desired effect?

```el
(define-advice org-set-tags (:around (fn &rest args) my-counsel-tags)
  "Forward to `counsel-org-tag' unless given non-nil arguments."
  (if (remq nil args)
      (apply fn args)
    (counsel-org-tag)))
```

**Comment by bbigras** [comment]
Thanks for the quick reply. Sorry it took me 1.5 years to reply...

It works with a minor change. Thank you very much.

```elisp
(define-advice org-set-tags-command (:around (fn &rest args) my-counsel-tags)
  "Forward to `counsel-org-tag' unless given non-nil arguments."
  (if (remq nil args)
      (apply fn args)
    (counsel-org-tag)))
```
