### ISSUE TITLE
swiper-avy misplaces character sequences

### ISSUE THREAD

**Issue by basil-conto** [abo-abo/swiper#1775]
From https://github.com/abo-abo/swiper/pull/1711#issuecomment-411910021, as requested in https://github.com/abo-abo/swiper/pull/1711#issuecomment-412059850:

1. `make plain`
2. <kbd>C-x</kbd><kbd>C-f</kbd>`swiper.el`<kbd>RET</kbd>
3. <kbd>M-x</kbd>`counsel-grep`<kbd>RET</kbd>`swiper`
4. <kbd>C-'</kbd>
   * Avy character sequences are displayed between line number digits:
     ![scrot0](https://user-images.githubusercontent.com/9121222/43927805-65f8dec8-9c37-11e8-88e2-1579138a7fcd.png)

**Comment by abo-abo** [comment]
Thanks.

**Comment by basil-conto** [comment]
Thanks, can confirm it works now.
