### ISSUE TITLE
ivy prefix @ before all TRAMP remote host even some TRAMP schema don't need

### ISSUE THREAD

**Issue by stardiviner** [abo-abo/swiper#1776]
I found ivy (or counsel) will prefix "@" for TRAMP remote host. For example:
when I completing docker container names after /docker:, It will complete with candidates:

my host name
@container_name

I guess this works for remote SSH machine. But should not on other TRAMP schema. This could be manually inserted if can't be stick on SSH only.

As a reference: https://github.com/abo-abo/swiper/issues/1733#issuecomment-427620027

**Comment by basil-conto** [comment]
Please try to include a detailed and reproducible recipe starting from `emacs -Q` or `make plain` listing what you type, what you expect it to do, and what actually happens. Please also include your <kbd>M-x</kbd>`emacs-version`<kbd>RET</kbd>.

**Comment by stardiviner** [comment]
- Emacs version: GNU Emacs 26.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.30) of 2018-07-05
I use `emacs -Q` to load `docker-tramp`, it complete container name is fine. Then I enable `ivy-mode`.
Then it gives out container names like this:

![image](https://user-images.githubusercontent.com/378699/46666532-7ed53f80-cbf9-11e8-91f3-c8483c4e1c10.png)

**Comment by stardiviner** [comment]
Any update on this issue?

**Comment by stardiviner** [comment]
General ping ....

**Comment by basil-conto** [comment]
Sorry, your recipe is missing a few steps.

What happens between

> I use emacs -Q to load docker-tramp

and

> it complete container name is fine

? And what happens between

> Then I enable `ivy-mode`.

and

> Then it gives out container names like this

? Please provide a step-by-step description of what you type and what you expect at each stage. How do you know this issue lies with Ivy completion and not with the `docker-tramp` package, which hasn't been updated in three years? Are you able to reproduce this issue with any other TRAMP method?

**Comment by carrete** [comment]
> How do you know this issue lies with Ivy completion and not with the `docker-tramp` package, which hasn't been updated in three years? How do you know the completion results you are seeing aren't intentional? Are you able to reproduce this issue with any other TRAMP method?

For whatever it's worth, I didn't encounter this error until I switched to ivy and counsel from ido. I eventually found https://github.com/masasam/emacs-counsel-tramp which works nicely and forgot about this issue. I just tried, and I can no longer reproduce this problem using the latest versions of ivy and counsel. FYI

**Comment by basil-conto** [comment]
> I didn't encounter this error until I switched to ivy and counsel from ido.

Was this with or without the `docker-tramp` package?

> I just tried, and I can no longer reproduce this problem using the latest versions of ivy and counsel.

Is this with `docker-tramp`, `emacs-counsel-tramp`, or neither of these packages?

Thanks.

**Comment by carrete** [comment]
> Was this with or without the `docker-tramp` package?

> Is this with `docker-tramp`, `emacs-counsel-tramp`, or neither of these packages?

I ran `emacs -Q` and installed docker-tramp - OK, then I also installed ivy and counsel - OK. Then I loaded my full setup and OK.

**Comment by basil-conto** [comment]
Thanks for the report. Let's wait to hear back from @stardiviner, and if we don't, the issue can be closed as fixed or unreproducible.

**Comment by stardiviner** [comment]
I confirmed the problem is gone. Might be fixed in some commit.

Here is the screenshot:

![image](https://user-images.githubusercontent.com/378699/80838476-b36d7980-8c2b-11ea-9977-c68db98239ab.png)
