### ISSUE TITLE
C-h-f, C-h-v inconsistently call helm buffer or swiper buffer, randomly?   

### ISSUE THREAD

**Issue by srustamo** [abo-abo/swiper#178]
I can't trace exactly when helm buffer is shown and when swiper buffer. But sometimes `C-h-v` raises `swiper` buffer consistently (when hitting `C-h-v`, cancelling, then hitting again) for some time. After awhile, the same keys raise helm buffer.

Actually some other commands also intermittently show one or the other buffers.

**Comment by abo-abo** [comment]
This might be an issue with your config. I've never encountered this behavior.

**Comment by srustamo** [comment]
I have `smex` bound to `M-x`. Hitting `tab` after `M-x` `(helm-select-action)`. This is to give you some more background to this issue.

What is your recommend (order `smex`, `helm`, `swiper` get loaded, for example) setup?
Since `swiper` uses `helm` as the backend, I assume `helm` must be installed?

**Comment by abo-abo** [comment]
> Since swiper uses helm as the backend, I assume helm must be installed?

Swiper doesn't use Helm at all. `swiper-helm` uses Helm, but it's in
no way related to <kbd>C-h f</kbd>.  This repository provides
`counsel-describe-function` with the recommended binding <kbd>C-h
f</kbd>. Helm isn't involved, unless you put something strange in your
config.

> I have smex bound to M-x

This repo also provides `counsel-M-x` with the recommended binding <kbd>M-x</kbd>. If you have `smex` installed, it will use `smex` for sorting.

**Comment by srustamo** [comment]
I must have something strange in my config, indeed :smile: 

>Swiper doesn't use Helm at all.

Can helm and swiper be used together without conflict? I rather like to have `helm-swoop` around, if nothing else from helm.

**Comment by abo-abo** [comment]
> Can helm and swiper be used together without conflict?

They should be. Show me your config and I can tell you what's wrong.

**Comment by srustamo** [comment]
I have uploaded my init files to a private gist (I'm not sure if I sanitized the private data completely). Is there any way to send you the link to this private gist?

**Comment by abo-abo** [comment]
> I have uploaded my init files to a private gist (I'm not sure if I sanitized the private data completely). Is there any way to send you the link to this private gist?

I don't know. But I only need to look at stuff related to swiper and helm, nothing else. It doesn't need to be the whole thing.

**Comment by srustamo** [comment]
[Here](https://gist.github.com/srustamo/6fbb277e337c14faebe8) is the gist with everything with `helm`, `ivy`, `swiper`, `smex` in my config.

**Comment by abo-abo** [comment]
OK, I see the problem: you can use either `helm-mode` or `ivy-mode` or `ido-mode` or `icomplete-mode`.  You can't have any two of them at once, since they mess with each other.

**Comment by abo-abo** [comment]
For example:

- either use `helm-mode` and `counsel-describe-function`: it's fine.
- or use `ivy-mode` and `helm-M-x`: also fine.
- but you can't have `helm-mode` and `ivy-mode` at once.

**Comment by srustamo** [comment]
Thank you. This was something I wanted to confirm for a long time for `ido` and `icomplete`.

Let me ask `counsel-M-x` related question, since you mentioned it this thread: why it prepends `^` to the input?

<img width="477" alt="screenshot" src="https://cloud.githubusercontent.com/assets/749813/8906010/4d23467c-3484-11e5-8b8b-35d60c68a8ba.png">

**Comment by abo-abo** [comment]
The `^` character indicates beginning of string in [Regexp](http://www.gnu.org/software/emacs/manual/html_node/emacs/Regexps.html).
This way:

- `^he` will match `helm`, but will not match `the`.
- `he` will match `helm` and also will match `the`.

Since very frequently you want to match from the start, `^` is auto-inserted.

**Comment by srustamo** [comment]
Thank you for your time.
