### ISSUE TITLE
Garbage collect unused ivy-occur buffers?

### ISSUE THREAD

**Issue by mookid** [abo-abo/swiper#1781]
I really enjoy navigating codebases using counsel-rg and ivy-occur to save intermediate searches, the visited matches etc.

The problem with that workflow is that such buffers accumulate over time; emacs sessions last very long, and working in one repo for one day means that I get tens of ivy-occur buffers.

Would the addition of a garbage collection of old such buffers welcome? The implementation could be as simple as: each time ivy-occur creates a buffer, it starts by pruning old ones. I already implemented something similar for indirect buffers.

**Comment by basil-conto** [comment]
Could you not configure the built-in `midnight-mode` to do this for you? See [`(emacs) Kill Buffer`](https://www.gnu.org/software/emacs/manual/html_node/emacs/Kill-Buffer.html).

**Comment by mookid** [comment]
You are probably right. Thanks @basil-conto !
