### ISSUE TITLE
counsel-fzf doesn't work with TRAMP

### ISSUE THREAD

**Issue by tttuuu888** [abo-abo/swiper#1782]
First of all, thank you for this great package.
counsel-fzf doesn't work with TRAMP. It only shows 'error code 127' on mini buffer.
Simple way to test this is `C-x d` `/scp:user@localhost:/` and `M-x counsel-fzf`
My emacs version is GNU Emacs 26.1 on Debian and counsel version is counsel-20181009.1743

**Comment by basil-conto** [comment]
I think there are many Counsel commands which do not currently support TRAMP.

**Comment by tttuuu888** [comment]
counsel-ag and counsel-git-grep both are working perfect on TRAMP, so I had expected counsel-fzf would work same.
I looked into the difference between counsel-ag and counsel-fzf and found out the problem was has to with environment variables.
When counsel-ag,git-grep,fzf all of those work on remote machine through TRAMP, it doesn't respect remote environment variables, especially PATH in this case. PATH variable showed only some default paths like /bin, /usr/bin .
Fzf is usually installed ~/.fzf/bin directory, which default PATH variable doesn't include.
So simple solution was adding `(add-to-list 'tramp-remote-path 'tramp-own-remote-path)`
After adding the setting, counsel-fzf on remote was working same as counsel-ag.

Hope this would be helpful for anyone who had same problem with me.
