### ISSUE TITLE
ivy switch buffer creates error: "Not bookmark format"

### ISSUE THREAD

**Issue by jarss** [abo-abo/swiper#1784]
Hey, 

I'm still starting out with emacs, and I do not have a programming background. 

My problem is that binding C-x b to Ivy switch buffer used to work until recently (I think there was an update), and now when I do that, it seems Emacs "overwrites" my key binding and does something else: "Upgrading bookmark format from 0 to 1..." which yields the above error. I don't use bookmarks and I don't upgrade them, why doesn't my binding work anymore?

**Comment by CeleritasCelery** [comment]
Can you give an example of your binding? Or has this been fixed now?

**Comment by jarss** [comment]
This is old and can be marked resolved. Issue I had was not related. Emacs bookmark file was corrupted, I deleted and created a new one, since then issue is fixed.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by abo-abo** [comment]
Thanks, closing.
