### ISSUE TITLE
ivy--kill-buffer-action does not preserve index

### ISSUE THREAD

**Issue by iquiw** [abo-abo/swiper#1787]
I am not sure the behavior is intentional.
I hope `ivy--kill-buffer-action` acts like `ivy-switch-buffer-kill` that preserve index after kill, but `ivy--kill-buffer-action` moves index to the last visited buffer (?).

**Comment by iquiw** [comment]
I tried to unify `ivy--kill-buffer-action` and `ivy-switch-buffer-kill` as follows.
https://github.com/iquiw/swiper/commit/566e77fc8189946c5e01baa354ac6e06b91838ca

As far as I can check, it works as expected.
@abo-abo Do you think it proper change?

**Comment by abo-abo** [comment]
Sounds OK. Please PR, I'll check again.

**Comment by iquiw** [comment]
Thank you! Sent PR.
