### ISSUE TITLE
ivy-completing-read-handlers-alist does not work as expected / rgrep

### ISSUE THREAD

**Issue by martin5233** [abo-abo/swiper#1788]
I switched to ivy recently and it mostly works very well. However, it does not play well together with rgrep, where it tries to present candidates for regexp patterns with paths, which does not make sense.
I tried to use 'ivy-completing-read-handlers-alist' with something like 'rgrep as as the key, but this does not work. While investigating this I found out, that the variable 'this-command' only contains functions like minibuffer-exit or ivy-done from the last call.
I looked at how helm solved this problem, as it has a similar exception list: They don't use 'this-command' immediately but a separate function 'helm-this-command' which scans the stack for relevant functions.
Can you advise on how to make rgrep work, such that it behaves without ivy enabled? I tried to define an advice around the rgrep function, which turns off ivy-mode, but for some reason this also didn't work.

**Comment by edkolev** [comment]
You could `(let ((completing-read-function'completing-read-default))...` which will make emacs not use ivy for the body of the let binding.

**Comment by oneness** [comment]
@martin5233 Can you post your solution here?

**Comment by abo-abo** [comment]
Something like this works:

```elisp
(defun advice-without-ivy (o &rest a)
  (ivy-mode -1)
  (prog1 (apply o a)
    (ivy-mode 1)))

(advice-add 'grep-read-files :around #'advice-without-ivy)
```

You could potentially reuse `advice-without-ivy` for other commands as well.

Personally, having `rgrep` work the way it does now doesn't bother me. It's still functional and even partially useful, since it gives a preview of the files in the current folder.
