### ISSUE TITLE
Make counsel-org-tag work during org-capture [Feature Request]

### ISSUE THREAD

**Issue by kaushalmodi** [abo-abo/swiper#179]
I had posted [a question on emacs.SE][1] on how to achieve ido-like completion when adding tags to a heading during org-capture.

I was delighted on seeing that you added `counsel-org-tag` but it does not work as expected during `org-capture` because when adding notes using capture, the buffer is in a narrowed view.

The feature request is to make `counsel-org-tag` list all the tags in the .org file (visible in the widened view, not just in the `org-capture` buffer.

Please also visit the linked emacs.SE question to get more clarity about my feature request (and post an answer there if you feel to :)).

[1]: http://emacs.stackexchange.com/q/13011/115

**Comment by abo-abo** [comment]
Actually, I checked just now, and it works well even during capture.
If it doesn't, please provide a minimal setup for which it doesn't work.

An issue that I faced: having `#+TAGS` in the file results in only those tags available for completion, and not all tags in a file.

**Comment by kaushalmodi** [comment]
I just created a new file for gathering capture notes and `counsel-org-tag` didn't work there too.

## Test capture template

```el
(setq org-capture-templates
      '(("t" "Test" entry ; `org-capture' binding + t
         (file+datetree (expand-file-name "test.org" org-directory))
         "\n* %?\n  Entered on %U")))
```
Assumptions:

- You have set the variable `org-directory` to something; `~/org/` in my case.
- You have a file `test.org` in `org-directory`.
- You have bound the recommended binding `C-c c` for `org-capture`. So you can add notes to the `test.org` using `C-c c t`.
 
Here is the first entry I made to it:

```
* 2015
** 2015-07 July
*** 2015-07-27 Monday
**** abcd                                                             :test1:
test1
  Entered on [2015-07-27 Mon 10:08]
```

Here I manually added the first tag `test1`.

Then I proceed to add a second note to the same file using `C-c c t`. But this is what I get when I do `M-x counsel-org-tag`. *I was expecting it to list `test1` as an available tag to insert.*

![clipboard01](https://cloud.githubusercontent.com/assets/3578197/8908314/6c14a4bc-3449-11e5-979c-1264feed4c9f.png)


**Update:** Actually the `test1` is not listed even when I do `counsel-org-tag` in the `test.org` file opened in full widened view by doing `C-x C-f`!

[[my org setup][1]] - *The first 100 lines or so sets various org variables and does some agenda setup.*

[1]: https://github.com/kaushalmodi/.emacs.d/blob/master/setup-files/setup-org.el

**Comment by abo-abo** [comment]
I'm getting the proper behavior with the setup that you describe. Did you update to the latest counsel.el?

**Comment by kaushalmodi** [comment]
Yes, I have the one with the counsel-recoll commit.

**Comment by abo-abo** [comment]
Your config, can I easily start it and check the bug?

**Comment by kaushalmodi** [comment]
Thanks for offering to help!

I just commented out everything in my org config except the capture template setup and still am facing the same problem.

If you meant to try finding this bug in my emacs setup, it should be pretty straightforward, hopefully:

- `curl` this script: `https://github.com/kaushalmodi/.emacs.d/blob/master/git_force_update.csh`
- `source git_force_update.csh ~/e-temp` *I had to write that script in csh as that's what we use at work, hopefully it works for you.*
- **IMP: Edit the `user-emacs-directory` and `org-directory` vars in [here][1] before starting emacs using this config**
- Start emacs with `~/e-temp/init.el` as its init.
- First start will take few minutes as it installs all packages.

[1]: https://github.com/kaushalmodi/.emacs.d/blob/d5c403a44cfc5ef6d7db68eadd1fce4fcfc94c2c/init.el#L8-L23

**Comment by abo-abo** [comment]
> IMP: Edit the user-emacs-directory and org-directory vars in here before starting emacs using this config

That's what I was missing.

Phew: found the error. Your code:

```elisp
(defun org-get-buffer-tags ()
  "Get a table of all tags used in the buffer, for completion."
  (let (tags)
    (save-excursion
      (goto-char (point-min))
      (while (re-search-forward
	      (org-re "[ \t]:\\([[:alnum:]_@#%:]+\\):[ \t\r\n]") nil t)
	(when (equal (char-after (point-at-bol 0)) ?*)
	  (mapc (lambda (x) (add-to-list 'tags x))
		(org-split-string (org-match-string-no-properties 1) ":")))))
    (mapc (lambda (s) (add-to-list 'tags s)) org-file-tags)
    (mapcar 'list tags)))
```

My code (newer Org):

```elisp
(defun org-get-buffer-tags ()
  "Get a table of all tags used in the buffer, for completion."
  (org-with-wide-buffer
   (goto-char (point-min))
   (let ((tag-re (concat org-outline-regexp-bol
			 "\\(?:.*?[ \t]\\)?"
			 (org-re ":\\([[:alnum:]_@#%:]+\\):[ \t]*$")))
	 tags)
     (while (re-search-forward tag-re nil t)
       (dolist (tag (org-split-string (org-match-string-no-properties 1) ":"))
	 (push tag tags)))
     (mapcar #'list (append org-file-tags (org-uniquify tags))))))
```

**Comment by abo-abo** [comment]
Also you might want to check out `org-complete-tags-always-offer-all-agenda-tags`, I just discovered it today.

**Comment by kaushalmodi** [comment]
@abo-abo Wow, thank you! Was it painful to startup emacs using my config other than those 2 vars you had to set? :)

I will try this out and update shortly.

**Comment by abo-abo** [comment]
The painful thing was <kbd>f1 k</kbd> not working:)

Side note: did you put a bunch of stuff in `post-command-hook` or something.  I turned on `lispy` in your config and it was soooooo slow, like 10 times slower than on my config.

**Comment by kaushalmodi** [comment]
It could be the aggressive-indent package. I bet it was slow only in setup-org.el and similar big files, right? It shouldn't be slow otherwise.

**Comment by abo-abo** [comment]
> It could be the aggressive-indent package. I bet it was slow only in setup-org.el and similar big files, right?

Yes, after disabling aggressive-indent, the navigation became much faster, although still not as fast as I have it: maybe the line numbering mode is to blame.
Also, if I press <kbd>jj</kbd> to move down two sexps, I'm getting a hydra :(

**Comment by kaushalmodi** [comment]
Does simply overriding the `org-get-buffer-tags` fix this issue? I did that and `counsel-org-tag` still doesn't list tags in narrowed or widened org buffer.

> if I press jj to move down two sexps, I'm getting a hydra :(

haha, sorry, I am "p/n" guy rather than "j/k" guy. So I never use those for navigation.

`jj` is a quick convenient key-chord for me as it's on the home row. It activating my commenting hydra.

**Comment by abo-abo** [comment]
> Does simply overriding the org-get-buffer-tags fix this issue? I did that and counsel-org-tag still doesn't list tags in narrowed or widened org buffer.

I think that a full update to the Org git master is needed.

**Comment by abo-abo** [comment]
> Does simply overriding the org-get-buffer-tags fix this issue? I did that and counsel-org-tag still doesn't list tags in narrowed or widened org buffer.
> 
> I think that a full update to the Org git master is needed.

Actually, evaluating the new `org-get-buffer-tags` was enough and I'm getting a proper behavior with your config.

**Comment by kaushalmodi** [comment]
Alright, I just updated to org-mode version from its git master and still no luck :(
*updated my config on git as well*

**Comment by abo-abo** [comment]
Did you issue a `make` in your Org directory?

Here's what I do with your config to get the proper behavior:

1. `emacs -Q -l init.el` (with two directories updated in init.el)
2. In scratch:

        (setq org-capture-templates
              '(("t" "Test" entry ; `org-capture' binding + t
                 (file+datetree (expand-file-name "test.org" org-directory))
                 "\n* %?\n  Entered on %U")))

3. <kbd>C-c c t</kbd> <kbd>M-x</kbd> `counsel-org-tag`.

**Comment by kaushalmodi** [comment]
Yes, I did do `make` (that simply compiles the .el files right?).

`C-h f org-get-buffer-tags C-.` (using `counsel-describe-function`) points to the correct version of that function.

Strange thing is that `counsel-org-tag` doesn't list tags even in a widened buffer (`C-x C-f ~/org/test.org`).

**Comment by kaushalmodi** [comment]
Finally fixed it!!

I had to change this line in `counsel.el`:

```el
(declare-function org-bound-and-true-p "org-macs") ; line 751
```

**Comment by kaushalmodi** [comment]
I am surprised why this didn't cause an issue for you.. Do you require all org files in the very beginning?

**Comment by abo-abo** [comment]
I have org lazy loaded on 3 second delay in my config. With your config, I did open an org buffer, so the function was loaded, I guess.

**Comment by abo-abo** [comment]
I've added an updated declare. Let me know if this fixes the issue.

**Comment by kaushalmodi** [comment]
This is very odd. It did not work at first. But it started working fine once I edebugged `counsel-org-tag` once. So obviously we didn't hit the root cause of the problem.

**Comment by abo-abo** [comment]
Some of the org-mode code is in a horrible style: dynamic variables galore, multivar setq instead of let* etc.

**Comment by kaushalmodi** [comment]
Woohoo! Finally! So that org-macs change I suggested wasn't required. It just happened that I had already edebugged yesterday and then tried changing that declare to point to org-macs.

That `defvar` was the key.

But the question still remains, why didn't this bug show up in your setup? Wouldn't you see the same if you try `counsel-org-tag` in a fresh emacs session?

**Comment by abo-abo** [comment]
> But the question still remains, why didn't this bug show up in your setup? Wouldn't you see the same if you try counsel-org-tag in a fresh emacs session?

counsel.el has `lexical-binding: t`, which means that unless e.g. `org-last-tags-completion-table` was declared as a defvar, it's treated like a useless lexical variable.

But, if org.el is loaded **before** counsel.el - it's all good. The error only happens when counsel.el is loaded before org.el.

**Comment by abo-abo** [comment]
Actually the byte compiler correctly warns against these problems. The thing is that I disable the compilation during large edits, since it takes too long (I have `auto-compile-mode` on).

**Comment by kaushalmodi** [comment]
Ah, and it does, in my case because I load packages alphabetically.

https://github.com/kaushalmodi/.emacs.d/blob/master/init.el#L203-244

**Comment by abo-abo** [comment]
> load packages alphabetically

lol, wouldn't auto-loading be better?

**Comment by kaushalmodi** [comment]
I require only my setup files in alphabetical order which basically contain one or more use-package forms. The use-package then requires directly, lazy loads or autoloads the packages as per my choice for different packages.

**Comment by abo-abo** [comment]
> The use-package then requires directly, lazy loads or autoloads the packages as per my choice for different packages

That's the major thing missing from use-package that package.el has: the automatic autoloading.  You have to specify `:commands` in order for use-package to lazy-load, but you have the update the `:commands` as the package is updated - it's not automatic.

**Comment by hisnawi** [comment]
Apologies if this is regarding an old post. But I am confused to whether this should work or not.

I have this template:
```
      (setq org-capture-templates
            `(
              ("l" "File Link" entry (file+headline ,(concat todo-org-directory "/todo.org")    "File links")
               "* TODO %? %^G \n %a \n" :prepend t)))
```

I am unable to get a tag counsel completion.
I even added this:

```
      (add-hook 'org-capture-mode-hook
                (lambda ()
                  (setq-local org-tag-alist (org-global-tags-completion-table))))
```

Am I still missing some setting?
