### ISSUE TITLE
Search for string "$in"

### ISSUE THREAD

**Issue by jasoncyu** [abo-abo/swiper#1790]
Hi there, trying to search for a string where there's a regexp character followed by some text without any spaces, i.e. the string "$in" or the string "$like".

If I search "\$in", then the minibuffer shows "error code 1".
If I search "\$ in", then I do find it, but it also matches lines like "$ asdf asdf in". 

Is there a way for me to do this search?

**Comment by basil-conto** [comment]
I cannot reproduce this starting from `make plain`. In a buffer with the following contents:
```
$in
$ foo bar in
$in foo
```
searching for `$in` using `swiper` matches the first and third lines but not the second. I have tried both with the default setting of `ivy-re-builders-alist` and after setting the default completion style to `ivy--regex-ignore-order` (see [`(ivy) Completion Styles`](http://oremacs.com/swiper/#completion-styles) for more on this).

Can you please provide a detailed and reproducible recipe starting from `emacs -Q` or `make plain` describing each command/key you invoke along with what you expect vs what actually happens at each step?

**Comment by mookid** [comment]
What search tool/ivy-read command are you using?

**Comment by basil-conto** [comment]
What's the status on this issue? Is the problem still present, or can this issue be closed?

**Comment by jasoncyu** [comment]
Yeah, we can close it
