### ISSUE TITLE
Semingly wrong results (?)

### ISSUE THREAD

**Issue by phikal** [abo-abo/swiper#1792]
Hi, I've been using Ivy for a while now and overall it's great, I much prefer it in general over ido or helm.

But I've been having a minor issue that has been a *major* frustration, and I couln't fix it myself, and assuming that others could have the same problem, I thought it would be good to mention it here.

It's been most striking in `Info-mode`. When I type `m`, `Info-menu` pops up, and I'd expect the following to happen:

1. All options are listed
2. I start typing the narrow the choices
3. When my input matches any option completely (ignoring case) it should be highlighted
4. By pressing `<return>` Info opens that page.

So for example, typing `emacs` should put the focus on `Emacs` _and not_ `Emacs GnuTLS`.

I thought that writing my own function to apply `downcase` on any input should help, but it turned out that it just became worse. And all the options I looked at didn't seem to help me either.

I hope I could make my issue and my reasoning understandable.

**Comment by basil-conto** [comment]
I cannot reproduce this with latest Ivy on Emacs versions 26 and 27 starting from either `emacs -Q` or `make plain`. The issue you describe sounds like what #1447 was meant to fix, so either there was a bug in that PR, or there is something in your configuration and/or installed packages interfering with Ivy's candidate index calculation.

1. Can you reproduce from `emacs -Q`?
2. What is your <kbd>M-x</kbd>`emacs-version`<kbd>RET</kbd>?
3. How recent is your version of Ivy?
4. What are your default values for variables `ivy-case-fold-search-default`, `search-upper-case`, and `case-fold-search`? Do you change their values anywhere in your configuration, e.g. in some custom hook?

**Comment by phikal** [comment]
1. Yes, after loading Ivy with `(package-initialize)`, `(require 'ivy)` and `(ivy-mode t)` the same result as above is produced
2. `GNU Emacs 25.1.1 (x86_64-pc-linux-gnu, X toolkit, Xaw3d scroll bars) of 2017-09-15, modified by Debian`, installed on a Debian stable machine
3. It's the default/newest version from Melpa Stable, `0.10.0`
4. [My configuration](https://zge.us.to/emacs.d.html#sec-3-1-2-1) only changes `ivy-case-fold-search-default` to `t` and nothing else.

So if you're fix is from February this year, and 0.10.0 was [released](https://github.com/abo-abo/swiper/releases/tag/0.10.0) November last year, that's the issue isn't it? So in other words, is there a chance that a newer stable version could be pinned?

**Comment by basil-conto** [comment]
> So if you're fix is from February this year, and 0.10.0 was released November last year, that's the issue isn't it?

Sounds like it, yes.

> is there a chance that a newer stable version could be pinned?

Only @abo-abo can answer that; see #1664.

**Comment by phikal** [comment]
Ok, I guess than this issue would be a duplicate, so I'll close it.

Thanks again for the help, I'll try to integrate your patch into my current setup until the stable version is updated.

**Comment by abo-abo** [comment]
> is there a chance that a newer stable version could be pinned?

I've been meaning to release 0.11.0 for a very long time. I'm in the middle of switching jobs and moving cities this week. Hopefully, soon I'll have enough free time to go through and document the changes in 425 commits since 0.10.0, and then pin the release.
