### ISSUE TITLE
prevent backspace from exiting minibuffer

### ISSUE THREAD

**Issue by jsomedon** [abo-abo/swiper#1799]
The default minibuffer doesn't exit on DEL, and I am trying to restore this behavior with ivy's minibuffer prompt. How to configure this?

**Comment by abo-abo** [comment]
See `ivy-on-del-error-function`:

```elisp
(setq ivy-on-del-error-function #'ignore)
```

It's also documented in <kbd>M-x</kbd> `customize-group` `ivy`.

**Comment by basil-conto** [comment]
> It's also documented in <kbd>M-x</kbd>`customize-group` `ivy`.

As well as [`(ivy) Defcustoms`](http://oremacs.com/swiper/#defcustoms), FWIW.
