### ISSUE TITLE
swiper-from-isearch to switch to swiper from isearch

### ISSUE THREAD

**Issue by glucas** [abo-abo/swiper#180]
For folks who don't bind swiper as a full isearch replacement it would be convenient to have a command that could be bound in the isearch-mode-map that switches to swiper using the current search string as the input. 

See for example iedit-mode-from-isearch: https://github.com/tsdh/iedit/blob/master/iedit.el#L358-L384

**Comment by abo-abo** [comment]
Cool, just had a PR with this change in abo-abo/swiper-helm#6 this week:)

I'll add one for swiper shortly.

**Comment by glucas** [comment]
Awesome! Thanks
