### ISSUE TITLE
Incorrect regex in ivy-occur for counsel

### ISSUE THREAD

**Issue by wedens** [abo-abo/swiper#1806]
Steps to reproduce:
- `counsel-git` 
- type ".zsh" 
- observe expected result
- press `C-c C-o`
- dired buffer opens as if I just opened dired in repository directory

Command counstructed by `counsel-git-occur`: `rg --files | grep -i -E '\.zsh\|\b\(\.\)\w*\W*\b\(z\)\w*\W*\b\(s\)\w*\W*\b\(h\)\w*' | xargs ls -alh | sed -e "s/^/  /"`. If I run this command in terminal, it ouputs the same thing as dired buffer (repository directory listing).

If I run it in terminal and remove `\|\b\(\.\)\w*\W*\b\(z\)\w*\W*\b\(s\)\w*\W*\b\(h\)\w*` part of the regex in grep subcommand, it outputs expected files.

ivy configuration:
```
  (setq ivy-height 15
        ivy-wrap t
        ivy-fixed-height-minibuffer t
        ;; Don't use ^ as initial input
        ivy-initial-inputs-alist nil
        ;; highlight til EOL
        ivy-format-function #'ivy-format-function-line
        ;; don't quit minibuffer on delete-error
        ivy-on-del-error-function nil
        ;; current input becomes selectable as a candidate. Press C-p
        ivy-use-selectable-prompt t))
```

counsel configuration:
```
  (setq counsel-git-cmd "rg --files")

  ;; Add smart-casing and compressed archive searching (-zS) to default
  ;; command arguments:
  (setq counsel-rg-base-command "rg -zS --no-heading --line-number --color never %s ."
        counsel-ag-base-command "ag -zS --nocolor --nogroup %s"
        counsel-pt-base-command "pt -zS --nocolor --nogroup -e %s"))
```

**Comment by wedens** [comment]
I have the same problem with `ivy-occur` in `counsel-find-file`.

Command: `ls -a | grep -i -E '\.zsh\|\b\(\.\)\w*\W*\b\(z\)\w*\W*\b\(s\)\w*\W*\b\(h\)\w*' | xargs -d '\n' ls -d --group-directories-first -alh | sed -e "s/^/  /"`.

Result is empty dired buffer and no results when ran in terminal.

If I run the command with removed `\|\b\(\.\)\w*\W*\b\(z\)\w*\W*\b\(s\)\w*\W*\b\(h\)\w*` part of the regex, it outputs expected result.

**Comment by abo-abo** [comment]
It has to be something in your config. When I run your `counsel-git` example, I get:

    rg --files | grep -i -E '.zsh' | xargs ls -alh | sed -e "s/^/  /"

Please try to reproduce with `make plain`.

**Comment by wedens** [comment]
Can't reproduce it anymore with the same config 🤷‍♂️
