### ISSUE TITLE
rainbow-delimiters-mode together with ivy-overlay uses face from delimiter

### ISSUE THREAD

**Issue by terlar** [abo-abo/swiper#1808]
When having `rainbow-delimiters-mode` enabled in an Emacs-Lisp file for example and having the cursor on a symbol/word that is directly after the parenthesis it will inherit the face from the parenthesis.

<img width="248" alt="ivy-first-word" src="https://user-images.githubusercontent.com/280235/48667047-f25a4e80-eacd-11e8-8426-fc2f4d6d156b.png">
<img width="393" alt="ivy-second-word" src="https://user-images.githubusercontent.com/280235/48667048-f2f2e500-eacd-11e8-9225-b5373d2cb5bd.png">

**Comment by basil-conto** [comment]
Could this be the same as #1016, #1488, and #1547?

**Comment by terlar** [comment]
Yeah, I think so, thanks for the info. I was searching for rainbow-delimiters-mode specifically so didn't find those issues, but definitely sound like the same issue. I will close this as a duplicate.

**Comment by basil-conto** [comment]
Does commit 7434a792c7b4ace1f138fe4256338e20f49981fc solve the issue for you?
