### ISSUE TITLE
Candidates hidden by prior wrapped long candidate under terminal

### ISSUE THREAD

**Issue by basil-conto** [abo-abo/swiper#1809]
1. `make emacs='emacs -nw' plain`
2. ```el
   (setq ivy-height 5
         resize-mini-windows t)
   ```
   <kbd>C-j</kbd>
3. ```el
   (ivy-read "prompt: " (nconc (mapcar #'number-to-string
                                       (number-sequence 0 (* ivy-height 2)))
                               (list (make-string (* (window-text-width) 2) ?w)
                                     "foo"
                                     "bar")))
   ```
   <kbd>C-j</kbd>
4. <kbd>M-></kbd>

   ![resize-4](https://user-images.githubusercontent.com/9121222/48668156-c1cee080-eade-11e8-9296-80538aba270f.png)
   Note that the last two candidates `foo` and `bar` are hidden by the previous multi-line candidate, and only two candidates are shown instead of four.

Tested in the following Emacs versions:

```
In GNU Emacs 25.2.1 (x86_64-pc-linux-gnu, X toolkit, Xaw3d scroll bars)
 of 2018-08-27, modified by Debian built on x86-csail-01
Windowing system distributor 'The X.Org Foundation', version 11.0.12003000
System Description:	Debian GNU/Linux testing (buster)

In GNU Emacs 26.1.50 (build 6, x86_64-pc-linux-gnu, X toolkit, Xaw3d scroll bars)
 of 2018-11-01 built on thunk
Repository revision: d53a2b65db9952580efcf5ffe75a313bcb49a99e
Windowing system distributor 'The X.Org Foundation', version 11.0.12003000
System Description:	Debian GNU/Linux testing (buster)

In GNU Emacs 27.0.50 (build 53, x86_64-pc-linux-gnu, X toolkit, Xaw3d scroll bars)
 of 2018-11-16 built on thunk
Repository revision: 644a308b4e1513e04be9360e1586e14b32ec0159
Repository branch: master
Windowing system distributor 'The X.Org Foundation', version 11.0.12003000
System Description: Debian GNU/Linux buster/sid
```

Re: #1807.

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by basil-conto** [comment]
Thanks, but unconditionally enabling `truncate-lines` doesn't really solve the problem, as it reintroduces the kind of minibuffer collapsing described in #77, #229, #237, and #1528. If you try the recipe in the OP you will see that the minibuffer window shows only the prompt and nothing else.

**Comment by abo-abo** [comment]
Ok, I see it now. We might have to go with a complex solution after all. Could we get away with recommending or setting this for non-graphical Emacs?

```elisp
(setq resize-mini-windows 'grow-only)
```

**Comment by basil-conto** [comment]
> Could we get away with recommending or setting this for non-graphical Emacs?

Documenting limitations such as that Emacs does not currently handle non-`nil` `truncate-lines` in the minibuffer very well (see e.g. [bug#5715](https://debbugs.gnu.org/5715) and [bug#9572](https://debbugs.gnu.org/9572)), and the combined effect this has with `resize-mini-windows`, is always a good thing. I think Ivy already recommends other settings as well, so the above would be a welcome addition.

What we can't get away with, though, is permanently changing the value of the user option `resize-mini-windows`; #1811 fixes this.
