### ISSUE TITLE
wgrep broken with occur buffers from counsel-ag, counsel-rg etc

### ISSUE THREAD

**Issue by purcell** [abo-abo/swiper#1813]
`wgrep` worked perfectly until very recently, but now fails as follows:

Steps to reproduce:

- Search with `counsel-ag` (or `counsel-rg` -- haven't tested others)
- Hit `C-c C-o` to jump to occur buffer
- `M-x wgrep-change-to-wgrep-mode`
- Edit hits
- Apply changes with `C-x C-s`

Expected result: a number of buffers get modified.

Actual result: `wgrep` reports `(no changes to be performed)`.

(As seen in https://github.com/purcell/emacs.d/issues/654)

**Comment by abo-abo** [comment]
Can't reproduce. Can you try to revert 810d77eb602e47e2684fa206c78abd13e3ba3b90 and see if the issue goes away?

I made that commit because I didn't want the occur output to look like this:

```
5 candidates:
././issues.org:147:(require 'package)
././issues.org:158:  (require 'use-package))
././doc/ivy.org:160:(require 'package)
././doc/ivy.texi:232:(require 'package)
././counsel.el:3361:  (require 'package)
```

Note the double `././`.

**Comment by oizhaolei** [comment]
I made a test.
With 31b5423, It reports `(no changes to be performed)`.
but aa45aa7 is doing well.

**Comment by abo-abo** [comment]
@oizhaolei Thanks. Could you tell me how to reproduce this test?

**Comment by purcell** [comment]
Yup. And even though @oizhaolei and I are using my [wrapper function](https://github.com/purcell/emacs.d/blob/138b603ed840e068720bdc7baec3ee493a4939b5/lisp/init-ivy.el#L50-L63) for `counsel-rg` etc., even calling `counsel-rg` directly (interactively) fails with this problem.

**Comment by purcell** [comment]
This does seem to be fixed as of 31b5423, so I'll close this. Guess the issue was the leading whitespace in the occur buffer. Thanks!

**Comment by abo-abo** [comment]
Thanks for the follow up.

**Comment by purcell** [comment]
> Thanks for the follow up.

Thanks for the tremendously useful code.
