### ISSUE TITLE
counsel-rg ivy-occur is broken on Windows

### ISSUE THREAD

**Issue by mookid** [abo-abo/swiper#1817]
At least on windows, jumping to a match does not work anymore on master.

To reproduce: 
in the swiper repo, searching for cl-delete yields the following ivy-occur buffer:
```
-*- mode:grep; default-directory: "~/src/swiper/" -*-


5 candidates:
    .\counsel.el:1610:              (or (cl-delete default-directory (counsel-git-worktree-list)
    .\counsel.el:3533:    (set sym (cl-delete-duplicates
    .\counsel.el:3534:              (cl-delete-if-not counsel-yank-pop-filter (symbol-value sym))
    .\counsel.el:3565:    (set sym (cl-delete s (symbol-value sym)
    .\ivy.el:280:                   (cl-delete-duplicates

```

As a consequence, pressing RET fails to jump to the match. 
A minimal patch to work around the issue is the following:

``` diff

--- a/ivy.el
+++ b/ivy.el
@@ -4119,7 +4119,7 @@ When `ivy-calling' isn't nil, call `ivy-occur-press'."
        highlight
        help-echo "mouse-1: call ivy-action")
      str)
-    (insert (if (string-prefix-p "./" str) "" "    ")
+    (insert (if (or (string-prefix-p "./" str) (string-prefix-p ".\\" str)) "" "     ")
             str ?\n))
   (goto-char (point-min))
   (forward-line 4)

```

**Comment by iquiw** [comment]
Does `--path-separator` option of `ripgrep` help?

```
        --path-separator <SEPARATOR>
            Set the path separator to use when printing file paths. This defaults to your
            platform's path separator, which is / on Unix and \ on Windows. This flag is
            intended for overriding the default when the environment demands it (e.g.,
            cygwin). A path separator is limited to a single byte.
```

**Comment by mookid** [comment]
> But this is looking increasingly brittle and hard-coded (platform-specific file name manipulation can and should be avoided!). Isn't there a more declarative way of achieving a similar effect?

I am not advocating for the inclusion of that patch, just saying that this fixes my issue.
For a proper fix, let somebody write a proper PR.

**Comment by mookid** [comment]
> Does `--path-separator` option of `ripgrep` help?

I am not sure that ripgrep is the only backend affected by this.

**Comment by iquiw** [comment]
https://github.com/abo-abo/swiper/blob/7b6765b957a4b5ec6bb498eda896374839f13760/ivy.el#L4126

Shouldn't it be `string-match-p` as in https://github.com/abo-abo/swiper/issues/1817#issuecomment-441229080 ?

**Comment by abo-abo** [comment]
@iquiw Thanks, fixed.
