### ISSUE TITLE
counsel-rg escaping issue

### ISSUE THREAD

**Issue by mookid** [abo-abo/swiper#1818]
There seem to be an issue with escape characters. For instance:

![image](https://user-images.githubusercontent.com/7757342/48954449-ca457200-ef49-11e8-949b-5c685add5288.png)

the matches in yellow are not supposed to be matched by the regexp, because the point is escaped; note that the parts matched by rg are not highlighted by emacs.

**Comment by abo-abo** [comment]
Can't reproduce with `make plain` on Emacs 26.1 / Linux.

**Comment by basil-conto** [comment]
> Can't reproduce with `make plain` on Emacs 26.1 / Linux.

Me neither.

Just a wild guess, but maybe this is a shell escaping issue? @mookid Have you tried variations of the search pattern, e.g. `"./"` and `"\\./"`? When reporting an issue, can you pretty please include a detailed set of reproduction steps, as well as your full <kbd>M-x</kbd>`emacs-version`<kbd>RET</kbd>?

**Comment by mookid** [comment]
Setup: windows 10 machine, for which bash = wsl. 

emacs-version is GNU Emacs 27.0.50 (build 1, x86_64-w64-mingw32) of 2018-05-04.

To reproduce: 
make plain
eval the following form:
```

(progn
  (setq shell-file-name "bash")
  (unless (string-match-p "rg.exe" counsel-rg-base-command)
    (setq counsel-rg-base-command
          (replace-regexp-in-string "rg" "rg.exe" counsel-rg-base-command)))
  (counsel-rg "\"\\./\"" ))

```

There are the 11 candidates in the previous screenshot.

**Comment by mookid** [comment]
> #1822 could potentially resolve that.

no it does not.

**Comment by Alexander-Shukaev** [comment]
I don't think any changes were propagated yet.

**Comment by mookid** [comment]
Can't reproduce any more, closing.
