### ISSUE TITLE
multi-occur like feature?

### ISSUE THREAD

**Issue by priyadarshan** [abo-abo/swiper#182]
I love swiper, also because it does not force the user to use helm, like for example helm-swoop.

I wish I could use it on multiple buffer/files. I could not find this feature in the code nor in any ticket yet: is it possible to use multi-occur like features with swiper, something like [this](https://github.com/ShingoFukuyama/helm-swoop#now-helm-swoop-has-several-ways)?

If not, may I submit a feature request, for your consideration?

Thank you for swiper!

**Comment by abo-abo** [comment]
Swiper doesn't do that yet, since I never actually got a use of multi-occur.  However this package provides `counsel-git-grep` and `counsel-ag`, which are great alternatives to multi-occur: there's no need to select a buffer list, since it's determined automatically.

I can add `swiper-multi-occur`, just to have it, but I think that the two commands that I mentioned above are superior in 95% of the cases.

**Comment by priyadarshan** [comment]
Thank you very much for considering that.

I tried to run `counsel-git-grep` or `counsel-ag`, but those commands do not come up with `M-x`. I just installed `swiper` from Melpa. When I run `M-x counsel-git-grep` I get 

`Debugger entered--Lisp error: (error "`counsel-git-grep' is not a valid command name")`

Command `swiper` runs fine, though.

**Comment by xuchunyang** [comment]
You need to install the `counsel` package.

**Comment by priyadarshan** [comment]
Thank you very much. Seeing `counsel.el` as part of the `swiper` package,  I was trying `(require 'counsel)`. I did not think it needed to be installed via `package`. Thank you for that.

I tried  `counsel-git-grep` and `counsel-ag`, which are excellent.

Once use case I use a lot, is to open multiple buffers (sometimes I use `helm-multi-files`), /not/ belonging to a current project source. In that case, `swiper-multi-occur` would be a real boon.

Thank you!

**Comment by abo-abo** [comment]
Please test. See the commit message for usage instructions, it's very similar to `counsel-org-tag`.

**Comment by priyadarshan** [comment]
:tada: Thank you so much, I shall test for a while aand report back.

**Comment by priyadarshan** [comment]
Thank you, it works. I could not find a way to add all buffers at once, something like `swiper-multi-buffers-all' to apply all buffers. That would be an excellent addition, for some future release.

With that it would be useful an option, something like `swiper-multi-buffers-all-ignore', that will allow to ignore listed buffers when `swiper-multi-buffers-all' is executed.

Thanks!

**Comment by s-kostyaev** [comment]
Is it possible to add editing (like in multi-occur) to swiper-all? Multi-occur with ivy is broken - I can't stop selecting buffers.

**Comment by abo-abo** [comment]
@s-kostyaev It's possible but has very little priority. Editing is already implemented for `counsel-git-grep` and `counsel-ag` via `wgrep`. Those two commands are better than `swiper-all`.

**Comment by s-kostyaev** [comment]
`counsel-ag` is great. Thanks.
