### ISSUE TITLE
ivy-mode: create directory when name of directory matches filename in current directory

### ISSUE THREAD

**Issue by makkus** [abo-abo/swiper#183]
This is most likely a stupid question, but: in dired, when using ivy-mode, how can I create a new folder  using dired-create-directory (say, called 'abc'), when there is a file that would match that new foldername (say, 'file-abc-def.txt)?

All I can do is select the existing file, and of course it doesn't let me create a folder with the same name. Which is not what I want anyway.

**Comment by abo-abo** [comment]
Added a second binding for this. It's possible to do it with both <kbd>C-u C-j</kbd> (old binding), and <kbd>C-M-j</kbd> (new binding).

**Comment by antismap** [comment]
Hello, 
First of all : awesome plugin !

I stumbled upon this Problem now. 
Simply using the "+" shortcut in dired doesn't work: the autocomplete is forces me to chose the matched name instead of creating a new one.

Both C-u C-j and C-M-j give me "Buffer is read only:" in the status bar without further effect.

**Comment by abo-abo** [comment]
@antismap Please open a new issue if you can reproduce the bug reliably.

**Comment by JRigotti** [comment]
@antismap did you create an issue about that?

I can reproduce the same behavior and the suggested keybindings from @abo-abo yields in fact the buffer is read-only message.

**Comment by abo-abo** [comment]
@JRigotti Please open a new issue with reproduction steps.

**Comment by haoyuan80s** [comment]
Hello @abo-abo
I am trying to create a file `~/x/y.txt`. But, there is already a `~/xx/` folder. If I type "`~/x/`", it is completed to "`~/xx/`". Is there a command to create such files inside some new folders?

**Comment by abo-abo** [comment]
@haoyuan80s

You can customize the behavior like this:

```elisp
(setq ivy-magic-slash-non-match-action 'ivy-magic-slash-non-match-cd-selected)
```

**Comment by haoyuan80s** [comment]
That Works. Thank you for the great package!
