### ISSUE TITLE
Minor issues with `ivy-occur` buffer

### ISSUE THREAD

**Issue by Alexander-Shukaev** [abo-abo/swiper#1830]
1.  When `counsel-rg` is followed by `ivy-occur`, the resulting occurrence buffer is still named after `counsel-ag` (perhaps a copy/paste bug).
2.  There are two unnecessary empty lines, e.g.:

```
-*- mode:grep; default-directory: "~/" -*-


22 candidates:
```

Not everyone has large monitors and/or uses large windows to waste two lines at the top of the search results, this does not scale.  I'd get rid of both empty lines.

**Comment by mookid** [comment]
This is the normal rgrep/find-grep behaviour in vanilla emacs.

If you want to get rid of that, I suggest either

- find a package that does exactly that. I think that some code in https://github.com/DamienCassou/beginend should do what you want

- add an advice that skips these lines for you. It's actually easy to write.

**Comment by Alexander-Shukaev** [comment]
What do you mean by skip?  I don't have a problem jumping over them directly to candidates, my problem is that they are visually impairing and wasting space on the screen.  That is I'd rather have it look like this:

```
-*- mode:grep; default-directory: "~/" -*-
22 candidates:
```

**Comment by mookid** [comment]
> What do you mean by skip?

I mean calling scroll-down.

**Comment by Alexander-Shukaev** [comment]
Also, is there any technical limitation or compelling reason why all the matches start with `././` (looks too verbose)?

**Comment by mookid** [comment]
Do you have a reproduction case for a search that would yield ././?

It used to be there but is supposed to have been fixed in 810d77eb602e47e2684fa206c78abd13e3ba3b90, os it would be a bug.

**Comment by mookid** [comment]
> ```
> 
> ```
> 
> Not everyone has large monitors and/or uses large windows to waste two lines at the top of the search results, this does not scale. I'd get rid of both empty lines.

also, note that these seems necessary for wgrep: https://github.com/abo-abo/swiper/blob/33d8e968a6d34b0721673845c2cfff1b39219eb4/counsel.el#L2465

**Comment by Alexander-Shukaev** [comment]
It would be interesting to employ folding in this case (similar to Magit's status buffer).  Scrolling up is a possibility but if you move your point it will still appear.

**Comment by abo-abo** [comment]
Just checking it right now:

- the buffer is correctly named after `counsel-rg`
- the extra two lines need to be there for `wgrep` to work; please file an issue there if you want to get rid of them.
