### ISSUE TITLE
Error on attempt to visit file from `ivy-occur` buffer when the original buffer from where the search was invoked was killed

### ISSUE THREAD

**Issue by Alexander-Shukaev** [abo-abo/swiper#1834]
1.  Go to one of your projects (i.e. open some buffer, let's call it `X`, which has a default directory inside of a corresponding `git` repo).
2.  `counsel-rg` and search for something.
3.  Do `ivy-occur`.
4.  Now kill that original buffer `X`.
5.  Now try to visit any of the matches in the occurrence buffer:

```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  string-match(".*" nil nil)
  display-buffer-assq-regexp(nil ((".*" display-buffer-same-window) (reusable-frames . t)) nil)
  display-buffer(#<killed buffer> display-buffer-pop-up-window)
  ivy--occur-press-update-window()
  ivy-occur-press()
  ivy-occur-press-and-switch()
  funcall-interactively(ivy-occur-press-and-switch)
  call-interactively(ivy-occur-press-and-switch nil nil)
  command-execute(ivy-occur-press-and-switch)
```

Most likely has nothing to do with `counsel` and is a general `ivy` issue.

**Comment by basil-conto** [comment]
Can you please try to reword the issue title so that it conveys more information at first glance, e.g. that `ivy-occur` tries and fails to display a killed buffer?

**Comment by mookid** [comment]
@abo-abo @basil-conto  is there anything better than improving error reporting in that case?

**Comment by Alexander-Shukaev** [comment]
It's not about reporting.  It's about

https://github.com/abo-abo/swiper/blob/86635fb8268c07b9fb534357e8e0940c23edeef7/ivy.el#L4251-L4253

where `ivy-state-buffer` somehow refers to the buffer from where the search was invoked originally (see my explanation for `X`) but that buffer is dead already.  I have no idea why there is a need to hold on to that buffer at all.

**Comment by mookid** [comment]
Indeed, I misunderstood the killed buffer. Indeed, I don't get why the code in `ivy--occur-press-update-window`.
