### ISSUE TITLE
`ivy-occur-press` does not respect `display-buffer-alist`

### ISSUE THREAD

**Issue by Alexander-Shukaev** [abo-abo/swiper#1838]
No idea how is this possible but with the following configuration:

```
  (setq-default
    display-buffer-alist     '((".*" . (display-buffer-reuse-window
                                        . ((reusable-frames . t))))
                               (".*" . (display-buffer-same-window)))
    even-window-heights      nil
    pop-up-frames            nil
    pop-up-windows           nil)
```

visiting any candidate in `ivy-occur` buffer (e.g. after `counsel-rg`) pops up the visited file in a new frame (super annoying).

**Comment by Alexander-Shukaev** [comment]
Curiously, invoking `(display-buffer (get-buffer "...") 'display-buffer-pop-up-window)` directly, works correctly.  So something is fishy about `ivy--occur-press-update-window` in particular and/or `ivy-occur-press-and-switch` in general.

**Comment by basil-conto** [comment]
Just a little hint: the simplest regexp which matches any string is the empty string `""`, not `".*"`.

**Comment by Alexander-Shukaev** [comment]
Cool, thanks.

**Comment by mookid** [comment]
> No idea how is this possible but with the following configuration:
> 
> ```
>   (setq-default
>     display-buffer-alist     '((".*" . (display-buffer-reuse-window
>                                         . ((reusable-frames . t))))
>                                (".*" . (display-buffer-same-window)))
>     even-window-heights      nil
>     pop-up-frames            nil
>     pop-up-windows           nil)
> ```
> visiting any candidate in `ivy-occur` buffer (e.g. after `counsel-rg`) pops up the visited file in a new frame (super annoying).

I am not super familiar with these config variables. What behaviour do you expect given these settings?

**Comment by Alexander-Shukaev** [comment]
1.  If a buffer is already displayed in one of the windows, regardless of whether it is in the current frame or another frame, raise that frame (don't spawn any new windows).
2.  Otherwise (buffer is not displayed by any window), display it in the current window (don't spawn any new windows).
3.  In general, don't pop (spawn) any new windows or frames (without me doing it manually).
