### ISSUE TITLE
Feature request: independent faces for ivy/swiper/counsel

### ISSUE THREAD

**Issue by diamond-lizard** [abo-abo/swiper#1839]
I'd like to request that ivy, counsel, and swiper always use their own faces rather than pre-existing faces, so that customizing how they look is possible without affecting the faces of other modes.

For instance, currently both ivy and swiper have the `compilation-info` face hardcoded in to them, and in addition swiper has the `compilation-line-number` face hardcoded in to it.  This makes it impossible to customize the way ivy and swiper look independently of how compilation-mode looks.

It would be great if ivy, counsel, and swiper used their own faces for all of these and any other faces they may need.

**Comment by mookid** [comment]
@diamond-lizard  do you think that this issue can be closed?

**Comment by diamond-lizard** [comment]
Yes.  Absolutely.  Thanks for your hard work!
