### ISSUE TITLE
dired:  ls illegal option  -- -

### ISSUE THREAD

**Issue by srustamo** [abo-abo/swiper#184]
Call `counsel-M-x`, select `dired`, select current directory gives this error:
`  /Users/s3:
  wildcard COPYING
  ls: illegal option -- -
usage: ls [-ABCFGHLOPRSTUWabcdefghiklmnopqrstuwx1] [file ...]`

Running `M-x dired` (not bound to counsel) on the same directory opens up the dired fine.

**Comment by srustamo** [comment]
Hitting `^` in the dired buffer showing the above error takes me to the parent dir, and from there things seem to work ok.

**Comment by abo-abo** [comment]
Evaluate this in `*scratch*`:

    (dired-read-dir-and-switches "")

And show me the result (for the buggy case).

**Comment by srustamo** [comment]
Evaluating this form asks for a directory, like on the screenshot.
<img width="275" alt="screenshot" src="https://cloud.githubusercontent.com/assets/749813/9002268/3a468b5a-377b-11e5-9893-3b70cbb25445.png">

Hitting `Ret` here produces this:
("/Users/s3/*message*-20150514-191413" nil)

**Comment by abo-abo** [comment]
Doesn't look like there's a problem, unless the selected directory somehow doesn't exist.

Evaluate the remainder of the `dired` code:

```elisp
(switch-to-buffer
 (dired-noselect
  "/Users/s3/message-20150514-191413" nil))
```

**Comment by srustamo** [comment]
I assume I needed to  evaluate this form:
`(dired-read-dir-and-switches "")
(switch-to-buffer
 (dired-noselect
  "/Users/s3/message-20150514-191413" nil))`

The result is:
 `  /Users/s3:
  wildcard message-20150514-191413
  ls: illegal option -- -
usage: ls [-ABCFGHLOPRSTUWabcdefghiklmnopqrstuwx1] [file ...]`

**Comment by abo-abo** [comment]
This is the code that causes the problem:

    (dired-noselect "/Users/s3/message-20150514-191413" nil)

Does that directory exist?

**Comment by srustamo** [comment]
Oh-boy, updated swiper et all, now get the swiper--update-input-ivy: Invalid function: with-ivy-window error. Dealing with this at the moment.

**Comment by abo-abo** [comment]
Just reinstall swiper and restart Emacs. It's a package.el problem.

**Comment by srustamo** [comment]
Yeah, had to re-install counsel.el, too. Back in business.
No, I call `counsel-M-x dired` on any directory, and get the same error. I'm not sure if `counsel-M-x dired' needs a file as final candidate to open. I can't select just a dir to open.

**Comment by srustamo** [comment]
This is how it looks when I call `counsel-M-x` just on the home dir.
<img width="348" alt="screenshot" src="https://cloud.githubusercontent.com/assets/749813/9004795/956423fa-3792-11e5-98fd-8b0da79c1b97.png">

Hitting `Ret` here raises the dired error.

**Comment by abo-abo** [comment]
What is the `*message*-...` file? Can you try to delete or move that file?  What are your configuration settings: you're not using the defaults.

**Comment by srustamo** [comment]
Deleted that file. Same effect with other files.
<img width="446" alt="screenshot" src="https://cloud.githubusercontent.com/assets/749813/9006629/162a9054-37a3-11e5-9f4b-275c8ce7e5aa.png">

**Comment by srustamo** [comment]
This is how ido  calls dired, and no error is shown on the same directory:
<img width="431" alt="screenshot" src="https://cloud.githubusercontent.com/assets/749813/9006670/82d5e88e-37a3-11e5-861c-e7847b519ca6.png">

**Comment by srustamo** [comment]
Moved `10-powerline-symbols.conf` too. Hitting `Ret` with pointer on `ASynk` dir does not open dired, but enters that dir and looks for files. When it finally finds a file, it raises the error.
<img width="359" alt="screenshot" src="https://cloud.githubusercontent.com/assets/749813/9006837/25499128-37a5-11e5-9a93-f4911200d550.png">

**Comment by srustamo** [comment]
<img width="568" alt="screenshot" src="https://cloud.githubusercontent.com/assets/749813/9006879/7dfab32e-37a5-11e5-8025-6a76b9535208.png">

**Comment by abo-abo** [comment]
Can you edebug the `dired` function with <kbd>C-u C-M-x</kbd> and tell me the argument list that it gets:

- when used with `counsel-M-x`
- when used with `ido`

**Comment by srustamo** [comment]
I toggled `debug-on-entry dired` here is the output:
`Debugger entered--entering a function:
* dired("/Users/s3/ASynK/README.org" nil)
  #<subr call-interactively>(dired record nil)
  ad-Advice-call-interactively(#<subr call-interactively> dired record nil)
  apply(ad-Advice-call-interactively #<subr call-interactively> (dired record nil))
  call-interactively(dired record nil)
  command-execute(dired record)
  #[257 "\302\303!\203\f\304\305!!\210\306\305!\307\")\207" [current-prefix-arg prefix-arg featurep smex smex-rank intern command-execute record] 4 "\n\n(fn CMD)"](#("dired" 0 5 (face ivy-current-match)))
  ivy-call()
  ivy-read("M-x " ("debug-on-entry" "edebug-defun" "toggle-fullscreen" "dired-vm" "package-list-packages" "eval-region" "counsel-org-tag" "helm-swoop" "menu-set-font" "customize-group" "customize-themes" "org-toodledo-sync" "magit-version" "sml/apply-theme" "eval-buffer" "org-pomodoro" "package-list-packages-no-fetch" "swoop" "orgstruct-mode" "linum-mode" "org-mac-grab-link" "counsel-ag" "flyspell-mode" "helm-M-x" "ace-window" "flyspell-buffer" "open-file-at-cursor" "ispell" "helm-mode" "counsel-org-tag-agenda" "helm-ag" "desktop-clear" "counsel-recoll" "exec-path-from-shell-copy-env" "exec-path-from-shell-initialize" "avy-isearch" "ivy-mode" "evil-mode" "magit-status" "openwith-mode" "whitespace-mode" "helm-firefox-bookmarks" "helm-list-elisp-packages-no-fetch" "diff" "smex" "set-frame-font" "sp-switch-space" "command-log-mode" "helm-show-kill-ring" "toggle-debug-on-error" ...) :predicate nil :require-match t :history extended-command-history :action #[257 "\302\303!\203\f\304\305!!\210\306\305!\307\")\207" [current-prefix-arg prefix-arg featurep smex smex-rank intern command-execute record] 4 "\n\n(fn CMD)"] :sort nil :keymap (keymap (67108908 . counsel--info-lookup-symbol) (67108910 . counsel-find-symbol)) :initial-input "^")
  counsel-M-x()
  #<subr call-interactively>(counsel-M-x nil nil)
  ad-Advice-call-interactively(#<subr call-interactively> counsel-M-x nil nil)
  apply(ad-Advice-call-interactively #<subr call-interactively> (counsel-M-x nil nil))
  call-interactively(counsel-M-x nil nil)
  command-execute(counsel-M-x)`

**Comment by srustamo** [comment]
The above was using counsel. I'm having trouble entering debug with `ido`, for some reason it does not enter debug.

**Comment by abo-abo** [comment]
I don't recommend using `debug-on-entry`. Instead:

1. Find the definition of `dired`.
2. Press <kbd>C-u C-M-x</kbd>.

Each time `dired` is called, you'll be in debugger. Press <kbd>SPC</kbd> to step and examine the arguments.
Press <kbd>q</kbd> to exit the debugger. Press <kbd>C-M-x</kbd> on `dired` to turn of `edebug`.

**Comment by srustamo** [comment]
I`m not sure what to look for stepping through the calls with `Space`. Anythings specific?

**Comment by srustamo** [comment]
Well, it finally showed the debug trace: for `counsel-M-x`
Debugger entered--entering a function:
* dired("/Users/s3/ASynK/README.org" nil)
  #<subr call-interactively>(dired record nil)
  ad-Advice-call-interactively(#<subr call-interactively> dired record nil)
  apply(ad-Advice-call-interactively #<subr call-interactively> (dired record nil))
  call-interactively(dired record nil)
  command-execute(dired record)
  #[257 "\302\303!\203\f\304\305!!\210\306\305!\307\")\207" [current-prefix-arg prefix-arg featurep smex smex-rank intern command-execute record] 4 "\n\n(fn CMD)"](#("dired" 0 5 (face ivy-current-match)))
  ivy-call()
  ivy-read("M-x " ("toggle-fullscreen" "debug-on-entry" "edebug-defun" "dired-vm" "package-list-packages" "eval-region" "counsel-org-tag" "helm-swoop" "menu-set-font" "customize-group" "customize-themes" "org-toodledo-sync" "magit-version" "sml/apply-theme" "eval-buffer" "org-pomodoro" "package-list-packages-no-fetch" "swoop" "orgstruct-mode" "linum-mode" "org-mac-grab-link" "counsel-ag" "flyspell-mode" "helm-M-x" "ace-window" "flyspell-buffer" "open-file-at-cursor" "ispell" "helm-mode" "counsel-org-tag-agenda" "helm-ag" "desktop-clear" "counsel-recoll" "exec-path-from-shell-copy-env" "exec-path-from-shell-initialize" "avy-isearch" "ivy-mode" "evil-mode" "magit-status" "openwith-mode" "whitespace-mode" "helm-firefox-bookmarks" "helm-list-elisp-packages-no-fetch" "diff" "smex" "set-frame-font" "sp-switch-space" "command-log-mode" "helm-show-kill-ring" "toggle-debug-on-error" ...) :predicate nil :require-match t :history extended-command-history :action #[257 "\302\303!\203\f\304\305!!\210\306\305!\307\")\207" [current-prefix-arg prefix-arg featurep smex smex-rank intern command-execute record] 4 "\n\n(fn CMD)"] :sort nil :keymap (keymap (67108908 . counsel--info-lookup-symbol) (67108910 . counsel-find-symbol)) :initial-input "^")
  counsel-M-x()
  #<subr call-interactively>(counsel-M-x nil nil)
  ad-Advice-call-interactively(#<subr call-interactively> counsel-M-x nil nil)
  apply(ad-Advice-call-interactively #<subr call-interactively> (counsel-M-x nil nil))
  call-interactively(counsel-M-x nil nil)
  command-execute(counsel-M-x)

**Comment by srustamo** [comment]
Although this looks like `debug-on-entry` output.

**Comment by abo-abo** [comment]
Yes, just see the values of `dirname` and `switches`.

**Comment by srustamo** [comment]
Are these values shown in *Messages* buffer?

I'm stepping through with Space, it shows lines in dired body, but not the
values.

**Comment by abo-abo** [comment]
> Are these values shown in *Messages* buffer?

Yes.

**Comment by abo-abo** [comment]
Any update on this? It seems like a strange problems, since no other OSX user has reported this yet.

**Comment by xuchunyang** [comment]
On OS X as well, but I don't come across this issue.  Emacs prefers the GNU version of `ls` by default, so Emacs will log a message (not an error) like you described only for the first time of using `dired` (or any other commands which require `ls`).  However, you can just tell Emacs to use the GNU `ls`, something like `(setq insert-directory-program "gls")`.

**Comment by srustamo** [comment]
I tried @xuchunyang, it did not work, raising error buffer. But I want to deal with @abo-abo suggested `edebug` first. Incidentally, I have the following on my PATH, which is where `ls` sourced from:
`bash-3.2$ which ls
/usr/local/opt/coreutils/libexec/gnubin/ls`

**Comment by srustamo** [comment]
Also, `M ! which ls` returns `/bin/ls`

**Comment by srustamo** [comment]
Then I set exec-path to current shell's PATH value with exec-path-from-shell package, the value of returned by `M ! which ls` is `/usr/local/opt/coreutils/libexec/gnubin/ls` and still the same ls error/warning.

**Comment by srustamo** [comment]
@abo-abo, with `edebug` on, I have trouble locating its message, because I get a long `popwerline` related errors. Any idea what this is about?

 Edebug: dired
Error during redisplay: (eval (let* ((active (powerline-selected-window-active)) (separator-left (intern (format "powerline-%s-%s" (powerline-current-separator) (car powerline-default-separator-dir)))) (separator-right (intern (format "powerline-%s-%s" (powerline-current-separator) (cdr powerline-default-separator-dir)))) (mode-line-face (if active (quote mode-line) (quote mode-line-inactive))) (visual-block (if (featurep (quote evil)) (and (evil-visual-state-p) (eq evil-visual-selection (quote block))) nil)) (visual-line (if (featurep (quote evil)) (and (evil-visual-state-p) (eq evil-visual-selection (quote line))) nil)) (current-evil-state-string (if (featurep (quote evil)) (upcase (concat (symbol-name evil-state) (cond (visual-block "-BLOCK") (visual-line "-LINE")))) nil)) (outer-face (if (powerline-selected-window-active) (if (featurep (quote evil)) (cond ((eq evil-state (intern "normal")) (quote airline-normal-outer)) ((eq evil-state (intern "insert")) (quote airline-insert-outer)) ((eq evil-state (intern "visual")) (quote airline-visual-outer)) ((eq evil-state (intern "replace")) (quote airline-replace-outer)) ((eq evil-state (intern "emacs")) (quote airline-emacs-outer)) (t (quote airline-normal-outer))) (quote airline-normal-outer)) (quote powerline-inactive1))) (inner-face (if (powerline-selected-window-active) (if (featurep (quote evil)) (cond ((eq evil-state (intern "normal")) (quote airline-normal-inner)) ((eq evil-state (intern "insert")) (quote airline-insert-inner)) ((eq evil-state (intern "visual")) (quote airline-visual-inner)) (t (quote airline-normal-inner))) (quote airline-normal-inner)) (quote powerline-inactive2))) (center-face (if (powerline-selected-window-active) (if (featurep (quote evil)) (cond ((eq evil-state (intern "normal")) (quote airline-normal-center)) ((eq evil-state (intern "insert")) (quote airline-insert-center)) ((eq evil-state (intern "visual")) (quote airline-visual-center)) (t (quote airline-normal-center))) (quote airline-normal-center)) (quote powerline-inactive2))) (lhs-mode (if (featurep (quote evil)) (list (powerline-raw (concat " " current-evil-state-string " ") outer-face) (funcall separator-left outer-face inner-face) (powerline-raw "%" inner-face (quote l))) (list (powerline-raw "%" outer-face (quote l)) (powerline-raw " " outer-face) (funcall separator-left outer-face inner-face)))) (lhs-rest (list (powerline-vc inner-face) (powerline-raw " " inner-face) (funcall separator-left inner-face center-face) (when (eq airline-display-directory (quote airline-directory-shortened)) (powerline-raw (shorten-directory default-directory 50) center-face (quote l))) (when (eq airline-display-directory (quote airline-directory-full)) (powerline-raw default-directory center-face (quote l))) (when (eq airline-display-directory nil) (powerline-raw " " center-face)) (powerline-raw "%b" center-face) (when (and (boundp (quote which-func-mode)) which-func-mode) (powerline-raw which-func-format center-face (quote l))) (when (boundp (quote erc-modified-channels-object)) (powerline-raw erc-modified-channels-object center-face (quote l))))) (lhs (append lhs-mode lhs-rest)) (rhs (list (powerline-raw global-mode-string center-face (quote r)) (powerline-minor-modes center-face (quote l)) (powerline-raw (char-to-string airline-utf-glyph-subseparator-right) center-face (quote l)) (powerline-major-mode center-face (quote l)) (powerline-process center-face) (powerline-raw " " center-face) (funcall separator-right center-face inner-face) (when powerline-display-buffer-size (powerline-buffer-size inner-face (quote l))) (when powerline-display-mule-info (powerline-raw mode-line-mule-info inner-face (quote l))) (powerline-raw " " inner-face) (funcall separator-right inner-face outer-face) (unless window-system (powerline-raw (char-to-string airline-utf-glyph-linenumber) outer-face (quote l))) (powerline-raw "%4l" outer-face (quote l)) (powerline-raw ":" outer-face (quote l)) (powerline-raw "%3c" outer-face (quote r)) (powerline-raw "%6p" outer-face (quote r)) (when powerline-display-hud (powerline-hud inner-face outer-face))))) (concat (powerline-render lhs) (powerline-fill center-face (powerline-width rhs)) (powerline-render rhs)))) signaled (args-out-of-range "" 0 1) [291 times]

**Comment by abo-abo** [comment]
Well, turn powerline off temporarily.

**Comment by srustamo** [comment]
Yeah, turned it off. 
Here's the output of `counsel-M-x dired` called from `dired.el` buffer.

Result: ("/usr/local/Cellar/emacs-mac/emacs-24.5-z-mac-5.7/share/emacs/24.5/lisp/COPYING" nil)
 [3 times]
Result: "/usr/local/Cellar/emacs-mac/emacs-24.5-z-mac-5.7/share/emacs/24.5/lisp/COPYING"

Result: nil

Result: #<buffer COPYING>

Result: #<buffer COPYING>

**Comment by abo-abo** [comment]
> Result: ("/usr/local/Cellar/emacs-mac/emacs-24.5-z-mac-5.7/share/emacs/24.5/lisp/COPYING" nil)

It looks like the proper parameters were passed to the `dired` function.
Basically if you evaluate this, it should do the right thing:

    (dired "/usr/local/Cellar/emacs-mac/emacs-24.5-z-mac-5.7/share/emacs/24.5/lisp/COPYING" nil)

Now check if you get different parameters if you call `dired` from a plain <kbd>M-x</kbd>.

**Comment by srustamo** [comment]
Well, there is no *still* error/warning using plain M-x. However, I don't think the right parameter is being passed for `counsel-M-x`. It still won't open dired buffer listing a *directory*, does not terminate the input at a directory, and keeps searching for file. 
<img width="767" alt="screenshot" src="https://cloud.githubusercontent.com/assets/749813/9061276/30ccb700-3ad4-11e5-8406-597d0c541810.png">

If you look at the screenshot above, you see that hitting Ret at the ..../lisp/ directory does not raise a dired buffer with all the files in that dir. Instead, only COPYING file is listed.

![screenshot](https://cloud.githubusercontent.com/assets/749813/9061846/e06e1782-3ad7-11e5-9b45-470b866618ab.jpg)

**Comment by abo-abo** [comment]
> that hitting Ret

That's your problem: <kbd>RET</kbd> enters directories, while <kbd>C-m</kbd> doesn't.
If you want to do it with <kbd>RET</kbd>, you have to select `./` which doesn't seem to be in your list of candidates for some reason.

**Comment by srustamo** [comment]
But ./ is in ido candidate list. 
<img width="399" alt="screenshot" src="https://cloud.githubusercontent.com/assets/749813/9062248/95620958-3ada-11e5-8455-57e5a2af904e.png">

Ignore the pixelation.

![screenshot](https://cloud.githubusercontent.com/assets/749813/9062209/5e113ff0-3ada-11e5-9d2f-55773bab66e1.jpg)

**Comment by abo-abo** [comment]
Did you touch `ivy-extra-directories`?

**Comment by srustamo** [comment]
ivy-extra-directories is a variable defined in `ivy.el'.
Its value is ("../" "./")

**Comment by abo-abo** [comment]
Evaluate this in a small directory:

    (all-completions "" 'read-file-name-internal)

**Comment by srustamo** [comment]
("Supplement_(Set_Theory).pdf" "Background_Reading.pdf" "../" "./")

**Comment by abo-abo** [comment]
OK, so these directories should be there. And you don't see them in `dired` or `find-file` completion?

**Comment by srustamo** [comment]
No.

**Comment by srustamo** [comment]
ido completion shows ./ in dired, but not in find-file. counel-M-x doesn't show for both.

**Comment by abo-abo** [comment]
The point is that it `counsel-M-x` should not matter. You're calling `dired` and it requests file completion.  If `ivy-mode` is on, it takes over and it should give you `./` and `../` candidates. In any case, can you just use <kbd>C-m</kbd> to select the directory?

**Comment by srustamo** [comment]
`C-m` enters the directory, and if there is a directory, it enters it - until it finds a file. Then it just lists the file.
<img width="442" alt="screenshot" src="https://cloud.githubusercontent.com/assets/749813/9063750/871cf256-3ae2-11e5-8329-9c19f480ced9.png">

**Comment by srustamo** [comment]
I noticed that `counsel-M-x dired` lists candidates, and dired is followed by a hint `(C-x-d)`. Hitting this command outside of minibuffer raises minibuffer with `./` present.

**Comment by abo-abo** [comment]
Try:

    (setq enable-recursive-minibuffers t)

Also make sure that you don't have `ido-mode` or `icomplete-mode` on at the same time with `ivy-mode`.

**Comment by srustamo** [comment]
Disabling `ido-mode` solved the problem.
 
Thank you.

I remember you mentioned not to have `helm-mode` and `ivy-mode` together, or `ido-mode` and `icomplete-mode` together.
