### ISSUE TITLE
counsel-M-x does not exclude obsolete functions

### ISSUE THREAD

**Issue by jabranham** [abo-abo/swiper#1843]
Built-in M-x (execute-extended-command) does not offer obsolete functions for completion, but counsel-M-x does. It would be nice to exclude these so we don't get offered e.g. both `which-func-mode` and `which-function-mode`

**Comment by basil-conto** [comment]
> Built-in M-x (execute-extended-command) does not offer obsolete functions for completion

For the record, this behaviour was added to `read-extended-command` in Emacs 25.1.

**Comment by jabranham** [comment]
Thanks! I didn't know it was so recent.
