### ISSUE TITLE
wgrep fails with swiper + ivy-occur in a narrowed buffer

### ISSUE THREAD

**Issue by whatacold** [abo-abo/swiper#1848]
Hi,

There are times that I edit texts in a narrowed buffer,
and I found that `wgrep` fails to work with the result of swiper occur.

For example, I have a `test-swiper-occur-wgrep-in-narrowed-buffer.txt` with a few lines:
```
foo
bar
baz
foobar
```

I narrow the buffer to the last two lines:
```
baz
foobar
```

And do an occur with `ivy-occur`:
```
-*- mode:grep; default-directory: "/home/hgw/test/" -*-


2 candidates:
./test-swiper-occur-wgrep-in-narrowed-buffer.txt:1:baz
./test-swiper-occur-wgrep-in-narrowed-buffer.txt:2:foobar
```

Activate `wgrep` in the buffer, editing some text and commit the changes with `wgrep-finish-edit`,
then `wgrep` complains:

> There is an unapplied change. (0 changed)

I suspect it's because the line number parts of the occur buffer are wrong when being narrowed.

I've verified that it exists with the latest version from melpa with a clean `emacs -Q` instance,
the versions are:
```
  swiper             20181120.1832
  wgrep              2.1.10
  ivy                20181129.2105
```

**Comment by CeleritasCelery** [comment]
> I suspect it's because the line number parts of the occur buffer are wrong when being narrowed.

that is correct. However I don't see an easy way to fix this because if we just get the real numbers it will prevent us from using "RET" to jump to that line, at least not without a lot of translation. 

If this is a big part of your workflow you can check out `helm-swoop` which handles this correctly.

**Comment by abo-abo** [comment]
Thanks, please test.
