### ISSUE TITLE
ivy-switch-buffer + ivy-occur yields empty buffer with no candidates

### ISSUE THREAD

**Issue by sbaig14** [abo-abo/swiper#1852]
As I understand it, if I use ivy-switch-buffer to narrow down the list of buffers to a few and then hit C-c C-o, I should get an ivy-occur buffer with those candidate buffers with the ability to manipulate them as I would in ibuffer. Unfortunately, I don't get this at all. Instead, I get an empty ivy-occur buffer in which only the "m" keybinding is active and gives mail functionality, which doesn't seem relevant.  

Is this feature broken? Perhaps I've got a misunderstanding?

**Comment by basil-conto** [comment]
There has been instability in certain `ivy-occur` features recently, but I can't reproduce what you describe from `make plain` on any of the following versions of Emacs:

```
In GNU Emacs 27.0.50 (build 80, x86_64-pc-linux-gnu, X toolkit, Xaw3d scroll bars)
 of 2018-12-11 built on thunk
Repository revision: 0054961acf319378a588bda1df7d32d2bc0f284d
Repository branch: master
Windowing system distributor 'The X.Org Foundation', version 11.0.12003000
System Description: Debian GNU/Linux buster/sid

In GNU Emacs 26.1.90 (build 1, x86_64-pc-linux-gnu, X toolkit, Xaw3d scroll bars)
 of 2018-11-19 built on thunk
Repository revision: 60457d7ae0cc560115d3e8c83bb308f015e7088d
Windowing system distributor 'The X.Org Foundation', version 11.0.12003000
System Description:	Debian GNU/Linux buster/sid

In GNU Emacs 25.2.1 (x86_64-pc-linux-gnu, X toolkit, Xaw3d scroll bars)
 of 2018-08-27, modified by Debian built on x86-csail-01
Windowing system distributor 'The X.Org Foundation', version 11.0.12003000
System Description:	Debian GNU/Linux buster/sid
```

Here's what I've tried:

1. `make plain` (this is like starting Emacs with the `-Q` switch and manually loading `ivy.el` et al.)
2. <kbd>C-x</kbd><kbd>C-f</kbd>`swiper.el`<kbd>RET</kbd>
3. <kbd>C-x</kbd><kbd>C-f</kbd>`counsel.el`<kbd>RET</kbd>
4. <kbd>C-x</kbd><kbd>C-f</kbd>`ivy.el`<kbd>RET</kbd>
5. <kbd>C-x</kbd><kbd>b</kbd><kbd>s</kbd><kbd>C-c</kbd><kbd>C-o</kbd>

Here's what that gives:

![occur](https://user-images.githubusercontent.com/9121222/49807231-757b6700-fd51-11e8-8225-16a3c3a212fa.png)

Can you please try to provide a minimal but detailed reproduction recipe? Are you able to reproduce the issue from `make plain` or `emacs -Q`?

**Comment by sbaig14** [comment]
This is so strange. It seems like the issue doesn’t exist when starting with emacs -Q. Perhaps there’s some conflict going on.

**Comment by basil-conto** [comment]
> It seems like the issue doesn’t exist when starting with emacs -Q. Perhaps there’s some conflict going on.

Like I said, this is probably due to something in your configuration or your installed packages. Try commenting out parts of your `user-init-file` or temporarily moving your `package-user-dir` somewhere else, perhaps that will help indicate the source of the problem.

**Comment by sbaig14** [comment]
Fixed, shackle was interfering with the ivy-occur buffer. So, I added a rule to allow pop-ups for ivy buffers in general and the problem went away.

**Comment by basil-conto** [comment]
Great, does that mean this issue can be closed?

**Comment by mookid** [comment]
@sbaig if you believe that your issue may affect someone else, please consider adding a wiki entry.
Thanks!

**Comment by sbaig14** [comment]
@mookid, I will consider doing so.

Thanks for your help, everyone! I'm closing this issue.
