### ISSUE TITLE
run-hooks: Symbol's value as variable is void: swiper--window

### ISSUE THREAD

**Issue by cg4242** [abo-abo/swiper#186]
Since the last update I get this error when I use swiper-helm. I use

GNU Emacs 24.5.1 (x86_64-apple-darwin13.4.0, NS apple-appkit-1265.21) of 2015-04-10 on builder10-9.porkrind.org

with prelude on OSX Yosemite.

**Comment by abo-abo** [comment]
Thanks, please check if it's fixed.

**Comment by cg4242** [comment]
Hi Oleh,

now I get

or: ivy-state-window accessing a non-ivy-state

when using swiper-helm.

Greetings, Christoph

**Comment by abo-abo** [comment]
Thanks, I've made another change. Please check again.
