### ISSUE TITLE
<C-u> (prefix argument) `counsel-rg` signals errors when called from an active `ivy-occur` buffer

### ISSUE THREAD

**Issue by Alexander-Shukaev** [abo-abo/swiper#1866]
`C-u` `M-x` `counsel-rg`:

- Choose a directory, e.g. `.emacs.d/`, `RET`;
- Empty `args`, `RET`;
- Type some valid pattern and see error occur while typing, nothing matched;
- In `*Messages*`: `Error in post-command-hook (ivy--queue-exhibit): (file-missing "Setting current directory" "No such file or directory" #(".emacs.d/" 0 9 (dirp t)))`.

**Comment by mookid** [comment]
I can't reproduce.

Can you please precise if the pattern is supposed to match?

**Comment by Alexander-Shukaev** [comment]
I think I know what the trigger is.  You should perform all these actions while `ivy-occur` buffer's window is current.

**Comment by basil-conto** [comment]
1. `make plain`
2. <kbd>C-c</kbd><kbd>k</kbd>`counsel-rg`<kbd>C-c</kbd><kbd>C-o</kbd>
3. <kbd>C-u</kbd><kbd>C-c</kbd><kbd>k</kbd>

   ![3](https://user-images.githubusercontent.com/9121222/50369298-b5391e80-059b-11e9-9f9e-e06d98f8e58e.png)

   Note how the current directory is not shown after the prompt.

4. <kbd>C-g</kbd>
5. <kbd>M-:</kbd>`(read-directory-name "")`<kbd>RET</kbd>

   ![5](https://user-images.githubusercontent.com/9121222/50369300-bff3b380-059b-11e9-9aaf-b7bb166ff182.png)

   Once again, note how the current directory is not shown after the prompt.

6. <kbd>C-g</kbd><kbd>C-x</kbd><kbd>o</kbd>
7. Repeat step 5.

   ![7](https://user-images.githubusercontent.com/9121222/50369302-c71ac180-059b-11e9-8134-48c354efd7b8.png)

   Note how the current directory is shown after the prompt.

8. Repeat step 6.
9. Repeat step 5.

   ![9](https://user-images.githubusercontent.com/9121222/50369303-d0a42980-059b-11e9-8e19-b095c44a06b4.png)

   Note how the current directory has magically appeared after the prompt this time.

**Comment by basil-conto** [comment]
> I think I know what the trigger is. You should perform all these actions while `ivy-occur` buffer's window is current.

Can the issue title please be updated accordingly? E.g. `counsel-rg with prefix arg in ivy-occur buffer signals error` or similar.
