### ISSUE TITLE
Disabling blink-cursor-mode makes counsel-rg behave oddly on OS X

### ISSUE THREAD

**Issue by raxod502** [abo-abo/swiper#1870]
Yeah, I know it sounds bizarre, but this is easily replicable across multiple machines independent of my configuration. Steps to reproduce:

1. Use OS X (I tested on 10.11.6 and 10.13.6). I tested and could not reproduce this on Arch Linux.
2. Install ripgrep (I tested using 0.10.0 from Homebrew).
3. Install Emacs (I tested using 26.1 from Homebrew `--with-cocoa`) and open a graphical frame (make sure to configure `PATH` correctly so Emacs can find ripgrep). I tested and could not reproduce this in the terminal.
4. Install the latest version of `counsel` (I tested using `package.el` and `straight.el`).
5. Run `M-x find-library RET counsel RET` to get to a file to search.
6. Run `M-x counsel-rg RET` and type `counsel`. Observe that the search completes very quickly.
7. Now run `M-x blink-cursor-mode` and repeat the above step. Observe the following three things:
    - Search completes much more slowly (taking up to five seconds in my tests, which is surprising given that the actual ripgrep command being executed completes in only 30 milliseconds).
    - If I press `C-g` while the results are still being accumulated, I frequently get the following behavior: The text `Quit` appears in the minibuffer, replacing its current contents, and remains for a few seconds before disappearing and allowing the minibuffer to revert to the results view. Apart from this, the `C-g` has no effect (the search is not aborted, nor is the minibuffer exited). The function `keyboard-quit` is not invoked when this happens, nor does the keypress appear in the lossage buffer (`C-h l`). Thus, the quit event is being generated in the C level somewhere.
    - Sometimes (although this is less reliable to reproduce), a keypress is dropped when I am typing `counsel`. If this happens when `debug-on-quit` is enabled, I get [this backtrace](https://gist.github.com/raxod502/463edb9f7125b754623deb284b790bd4). It seems likely, therefore, that the same underlying phenomenon is happening here (since a quit event is generated without my typing `C-g`).
8. Observe that running `M-x blink-cursor-mode` again "fixes" the above problems.

Here's a GIF demonstrating the behavior (first a fast search, then a slow search with `blink-cursor-mode` disabled, then a demonstration of the `Quit` bug):

![repro](https://user-images.githubusercontent.com/6559064/50376596-2e506a00-05cc-11e9-8a4a-4dc56ac6b44a.gif)

**Comment by basil-conto** [comment]
> I tested and could not reproduce this in the terminal.

This is reinforced by the docstring of `blink-cursor-mode`:
```
This command is effective only on graphical frames.  On text-only
terminals, cursor blinking is controlled by the terminal.
```

**Comment by basil-conto** [comment]
@raxod502 Hadn't you raised the issue of keys being dropped on `emacs-devel` in the last few months or so? I vaguely remember it having something to do with `while-no-input`, which is used by dynamic Ivy collections in `post-command-hook`, and a cursory glance of `blink-cursor-mode` indicates it, too, used `pre-command-hook` and `post-command-hook`. Coincidence?

**Comment by basil-conto** [comment]
Have you tried reproducing the problem with a build of Emacs `master`, in case any pertinent issues have since been resolved?

**Comment by raxod502** [comment]
The issue has apparently been resolved in Emacs `master`.

Now, for unrelated reasons, I had to upgrade to macOS Sierra in the last few days. Unfortunately, graphical frames for Emacs 26.1 are broken on that operating system, so I had to upgrade to Emacs `master` permanently. As a consequence, I can no longer reproduce the bug.

I don't think this is necessarily a full solution, as there are plenty of people who are using Emacs 26.1 on versions of macOS other than Mojave, but it no longer bothers me.

**Comment by basil-conto** [comment]
> I don't think this is necessarily a full solution

Sure, but what can Ivy do about an Emacs bug?

**Comment by raxod502** [comment]
If we figured out what part of Counsel's code causes the bug, we could install a workaround. On the other hand, if you would prefer to say "just update to `master`, or provide a pull request if you really want to use 26.1", then I suppose that's a fine position as well.

**Comment by raxod502** [comment]
Actually, I can confirm that this bug still occurs using Emacs `master` on Mojave.
