### ISSUE TITLE
Swiper-mc function doesn't add cursors just saves marks at every location

### ISSUE THREAD

**Issue by JSpenced** [abo-abo/swiper#1879]
I can't get swiper-mc working properly. It just seems to save marks at every location in the swiper search buffer but adds no cursors. For example the messages below are different searches that I completed with typing swiper-mc are the ones like :
`Mark saved where search started [6 times]` but cursors are never added.

Is there a way to debug this? I'd love this functionality.

```
Mark saved where search started [238 times]
mc/edit-lines: Mark a set of lines first
mc/restore-state-from-overlay: Wrong type argument: overlayp, nil
Mark saved where search started [6 times]
Mark set
next-line: End of buffer [3 times]
Mark set
Mark saved where search started [3 times]
mc/edit-lines: Mark a set of lines first
```

**Comment by JSpenced** [comment]
Nevermind #856 is a similar issue!

Just accidentally swiper-mc got added into the `mc/commands-to-run-all` so it wasn't working properly.

If you move over the command to, `mc/commands-to-run-once` it solved the issue.

**Comment by abo-abo** [comment]
Thanks, I've updated the docstring.
