### ISSUE TITLE
swiper go to next match

### ISSUE THREAD

**Issue by ivan-krukov** [abo-abo/swiper#1880]
Not an issue - but a question.

Context - I love `swiper`, and I was looking to streamline a thing that I do often.

Question - Is there a way to use `swiper` to jump to the next match without invoking the UI?
More specifically, I would like to be able to navigate the swiper search results a-la `occur`, but without having to open a new `occur` buffer. This would have a similar feel to `n` in `vim`.

Bonus: cycle to the next match if at the end of buffer.

Say I have the following buffer:
```
(hello)
(hello-there)
(hello-again)
```
Ideally, I would like to invoke `(swiper "hello")` (e.g. `C-s hello`) and then `(swiper-jump-to-next)` (e.g. `M-n`), which would set point at `(hello-there)` but without having to open the minibuffer or the `occur` buffer.

Here are some ways to achieve this behaviour, after the initial `C-s hello`:

- `C-s C-s C-n C-j` would open the swiper minibuffer, recall previous history item, go to the next, and then accept. This is okay, but requires 4 keystrokes to simply jump to the next match.

- `C-c C-r C-n C-j` where `C-c C-r` is bound to `ivy-resume`. This is also okay, but I would like to get back into the search even if some other `completing-read` has been done inbetween (so `M-x` would not interrupt this).

- `C-s C-o` would open the occur buffer, where I can navigate with `next-error` and `previous-error`, which can be bound to `M-n` and `M-p`. However, It's a little too much to have an extra buffer open for every new search.

Is there a way to script this? I've tried a few naive things, but I can't figure out how to evaluate within a `swiper` context. Are there any packages that implement this `go-to-next-match` behaviour?

Thank you very much.

**Comment by Alexander-Shukaev** [comment]
I don't follow:

> but without having to open the minibuffer or the occur buffer.

The point of swiper is to have a preview in minibuffer.  What you ask for is more like `isearch` or `evil-search`, jumping between matches, and is standard.  What exactly do you need from swiper here?

**Comment by ivan-krukov** [comment]
Fair enough, what I am describing certainly feels very `isearch`y.  

I suppose what I had in mind is using `swiper` for the initial search. 
The minibuffer is super helpful in filtering down to exactly the matches I want (which is impossible in a large file with `isearch`, since it wouldn't show a list of partial matches in the minibuffer). This is the main reason for using `swiper`, for me, at least.
Second, the `swiper` search is bidirectional - I don't have to worry about the current point position to search. 

I wouldn't want to give up the convenience of the minibuffer preview as I "build" my search query, but I'd like to navigate the results of the search in a quicker way.

**Comment by Alexander-Shukaev** [comment]
[`flx-isearch`](https://github.com/PythonNut/flx-isearch) by @PythonNut does fuzzy searching with `flx`.  I'm not sure whether space wildcard (`.*`) style (aka `ivy--regex-plus`) is also supported.  It certainly does not offer preview which you want, though I'm not sure that preview is actually needed.  What is your expectation from preview?  That is, as you narrow the match, you see the preview shrinking and how does it help you unless it shrinks to a number of matches less or equal maximum height of preview?  Wouldn't merely the number of matches (hypothetically, displayed somewhere as you narrow) be sufficient?

**Comment by ivan-krukov** [comment]
Thanks for the pointed to `flx-search`.

Here is an example of my expectation for the preview.

The minibuffer preview can be scrolled (`C-n`), so it's easy to navigate to the match? Say `(swiper "defvar swiper)` in the `swiper.el` source gives me 19 matches, which I can look through, then narrow to the provate variables by just hitting `-` one more time. Plus moving to the match advances the point to the location in the buffer, so I can see the context of the match. 

Say now I've finally narrowed down to see how `swiper--format-spec` is used in the code. I'd go to the first match (322), stare at it for a while, and then jump to the next (380). Would be nice if I didn't have to repeat the search invocation again, but just jump to it quickly.

**Comment by ivan-krukov** [comment]
Hey, @Alexander-Shukaev, thank you very much for the feedback. You've really helped me understand exactly the behaviour I've been looking for. Here is the simple version of what I've wanted:

```elisp
(global-set-key (kbd "M-n") (lambda () (interactive) (search-forward (car swiper-history))))
(global-set-key (kbd "M-p") (lambda () (interactive) (search-backward (car swiper-history))))
```

This allows me to use swiper as usual, and then `M-n` or `M-p` to move between the matches. Now I just have to figure out how to make it cycle through the buffer, and use `highlight-symbol-at-point`.

Thanks!

**Comment by Alexander-Shukaev** [comment]
By the way, in my case I solved this issue on both sides with

```emacs-lisp
(defvaralias 'swiper-history 'regexp-search-ring)
```

which causes `swiper` and other Emacs search tools (e.g. prominently `isearch`) to use the same history ring.  Cycling is not a problem for me as I use custom `evil`-like search module on top of `isearch` (see [`devil-isearch`](https://bitbucket.org/Alexander-Shukaev/emacs-configuration/src/master/.emacs.d/lisp/devil/devil-isearch.el) if interested).
