### ISSUE TITLE
How to override `isearch-complete1` so that it uses `ivy`?

### ISSUE THREAD

**Issue by Alexander-Shukaev** [abo-abo/swiper#1882]
```emacs-lisp
(defun isearch-complete1 ()
  ;; Helper for isearch-complete and isearch-complete-edit
  ;; Return t if completion OK, nil if no completion exists.
  (let* ((ring (if isearch-regexp regexp-search-ring search-ring))
         (completion-ignore-case case-fold-search)
         (completion (try-completion isearch-string ring)))
    (cond
     ((eq completion t)
      ;; isearch-string stays the same
      t)
     ((or completion ; not nil, must be a string
	  (= 0 (length isearch-string))) ; shouldn't have to say this
      (if (equal completion isearch-string)  ;; no extension?
	  (progn
	    (if completion-auto-help
		(with-output-to-temp-buffer "*Isearch completions*"
		  (display-completion-list
		   (all-completions isearch-string ring))))
	    t)
	(and completion
	     (setq isearch-string completion))))
     (t
      (message "No completion") ; waits a second if in minibuffer
      nil))))
```

Is there any way to advise or override it to filter candidates via `ivy` (similar to how `completion-at-point` does it)?

**Comment by abo-abo** [comment]
What are you trying to achieve? What's the sequence of keys and commands you use?

**Comment by Alexander-Shukaev** [comment]
One can do `isearch-forward`, then either `isearch-complete` or `isearch-edit-string` followed by `isearch-complete-edit`.  This would eventually trigger the function pasted above `isearch-complete1`.  That function of course does not behave in `ivy` flavor because this is yet to be implemented.  I'm looking for a way to do it in a manner consistent with how, e.g. `completion-at-point`, was given `ivy` flavor.

**Comment by abo-abo** [comment]
Please add a sequence of key bindings so I can experiment with it a bit.

**Comment by Alexander-Shukaev** [comment]
That's a bit tricky because I don't use standard Emacs key bindings at all.  But looking through the default keymaps, I see that <kbd>C-s</kbd><kbd>M-e</kbd><kbd>M-TAB</kbd> would get you to `isearch-complete-edit`.

**Comment by basil-conto** [comment]
> Is there any way to advise or override it to filter candidates via `ivy`

If you really want to you can advise `isearch-complete1` to temporarily advise `display-completion-list`, play around with `temp-buffer-show-function`, etc. Either way, I think your efforts would be better spent submitting an Emacs feature request for `isearch` to (re)use `completion-in-region` or similar.

**Comment by Alexander-Shukaev** [comment]
You're probably right.

**Comment by abo-abo** [comment]
I agree with @basil-conto here. Closing.

**Comment by Alexander-Shukaev** [comment]
See [bug#39015](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=39015).

**Comment by abo-abo** [comment]
@Alexander-Shukaev Thanks.
