### ISSUE TITLE
Allow ivy--kill-buffer-action to kill virtual buffers (remove from recentf)

### ISSUE THREAD

**Issue by glucas** [abo-abo/swiper#1888]
This was requested on [Emacs StackExchange](https://emacs.stackexchange.com/questions/36836/how-to-remove-files-from-recentf-ivy-virtual-buffers): Can the kill buffer action also apply to virtual buffers?

I've worked around this by registering my own kill action that checks if the buffer exists and if not tries to remove it from the recentf-list, but this seems like a generally useful capability. 

The equivalent is apparently provided for ido, `ido-kill-buffer-at-head`

**Comment by manuel-uberti** [comment]
I wonder: does `ivy-switch-buffer-kill` do what you are looking for? I've bound it to <kbd>C-k</kbd> in `ivy-switch-buffer-map`.

**Comment by manuel-uberti** [comment]
Understood. Then, @abo-abo is needed. :)

**Comment by abo-abo** [comment]
Thanks.

> ivy-switch-buffer-kill

This one was updated as well. I'm tempted to bind `ivy-switch-buffer-kill` to <kbd>C-k</kbd> by default, I don't know if many people are aware it exists.
