### ISSUE TITLE
Swiper search does not advance to next occurance in one line

### ISSUE THREAD

**Issue by oneness** [abo-abo/swiper#189]
If the text is on one line, repeating a word search does not advance to next occurance if the body of text is just one line.

**Comment by abo-abo** [comment]
This is by design, since `swiper` is line-based. However, if you have two candidates on one line and want to select the second one, use <kbd>C-'</kbd> (`swiper-avy`).

**Comment by oneness** [comment]
ah, did not know that. Thanks closing this.
