### ISSUE TITLE
Only run the directory portion of "ivy-alt-done"

### ISSUE THREAD

**Issue by mc10** [abo-abo/swiper#1891]
Is it possible to only run the "when the candidate is a directory, enter it" part of `ivy-alt-done`, and have nothing happen if a file or a non-existent path is selected? This action would essentially never exit the candidate minibuffer.

**Comment by abo-abo** [comment]
Thanks. Here's a sample config:

```elisp
(define-key counsel-find-file-map (kbd "<right>") 'counsel-down-directory)
(define-key counsel-find-file-map (kbd "<left>") 'counsel-up-directory)
```

Please test.

**Comment by mc10** [comment]
Looks good to me, thanks!
