### ISSUE TITLE
`counsel--async-command` and `counsel--call` reconciliation

### ISSUE THREAD

**Issue by Alexander-Shukaev** [abo-abo/swiper#1893]
After #1821 and #1828, I think we should reconcile and clean up the two interfaces a little bit:

- Names of functions should be more consistent, e.g.:
  - `counsel--async-command` and `counsel--command` or
  - `counsel--async-call` and `counsel--call` or
  - `counsel--async-process` and `counsel--process` or
  - `counsel--start-process` and `counsel--process` or
  - `counsel--start-process` and `counsel--call-process`.  
    I mean the problem is really consistent naming with the rest of Emacs as well, there are at least: `async-start-process`, `start-process`, `start-file-process`, `call-process`, `process-file`, `async-shell-command`, `shell-command`.  I would give names which reflect the best which of these routines are used in the implementation of the two.
- Names of arguments and their accepted values, e.g.:
  - `cmd` allowing both list and string in one case, and
  - `command` being list anyway only.
- Documentation strings need to be more consistent and use similar wording.
- Implementation, e.g.:
  - one goes via shell if `cmd` is string, while
  - another one does not even offer an option.

Last but not least, I think we should move away from `cmd` being string (and thus making shell invocations) everywhere (and perhaps even remove that possibility afterwards or warn about it being an obsolete utilization of API).

**Comment by abo-abo** [comment]
Agreed.

> counsel--async-call and counsel--call

I prefer this one, I guess. I'm not a big fan of updating names willy-nilly, but I don't mind it if someone does the work in a PR, with proper deprecation warnings, and preferably with some analysis of whether any published packages use the function in question.

> Documentation strings need to be more consistent and use similar wording.

Sounds good, please PR.

> Last but not least, I think we should move away from cmd being string (and thus making shell invocations) everywhere

Every command needs to be tested to still work after the change. Then I'm fine with it.

**Comment by basil-conto** [comment]
> I'm not a big fan of updating names willy-nilly, but I don't mind it if someone does the work in a PR, with proper deprecation warnings, and preferably with some analysis of whether any published packages use the function in question.

In general, yes. We don't have to worry about deprecation or backward compatibility in this case, though, because these are internal functions.

**Comment by abo-abo** [comment]
Thanks.
