### ISSUE TITLE
counsel-org-tag fails with inherited tags: "Tag alignment failed"

### ISSUE THREAD

**Issue by hpdeifel** [abo-abo/swiper#1896]
Given the following org-mode file with `org-use-tag-inheritance`:

```org
* Test1                                                                 :foo:
** Test2
```

Putting point on the `Test2` headline and invoking `counsel-org-tag`, it shows "(foo)" as the previous tag for this headline. Trying to add a new tag subsequently fails with "Tag alignment failed", because `counsel-org-change-tags` doesn't find the regex for ":foo:" on the current line.

It works fine without inherited tags.

This is probably due to a change in Org mode version 9.2:

> Function org-get-tags used to return local tags to the current headline. It now returns all the inherited tags in addition to the local tags. In order to get the old behaviour back, you can use:
> 
> (org-get-tags nil t)

---

counsel: Commit 201c5d78c
Emacs: GNU Emacs 26.1
Org: Org mode version 9.2 (9.2-elpaplus @ /somewhere/elpa/org-plus-contrib-20181230/)

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by hpdeifel** [comment]
Works beautifully, thanks!
