### ISSUE TITLE
Ivy and Umlaute/Acents

### ISSUE THREAD

**Issue by phikal** [abo-abo/swiper#1899]
I've just discovered `counsel-org-goto-all` today, and it's exactly what I've been looking for, for quite a while. My only issue is that, since some of my org files are in German, despite me not having a QWERTZ  keyboard, I have Umlaute in some of my headings, which I can't match. 

The easy solution is for example to just skip them, so when wanting to match `übung` I'd type `bung` but that seems counter-intuitive. Could there be a system to overcome this issue, such as doing something with the current input-method, or other fixed transformations (an alist listing rules, like every `u` matches `u` and `ue`, or `ue` is converted to `ü`).

If there is such a mechanism already, I apologize upfront that I couldn't find it.

**Comment by abo-abo** [comment]
You can use `toggle-input-method`, I use it all the time everywhere in Emacs to toggle between English and Ukrainian.

Here's the customization I use:

```elisp
(setq default-input-method "ukrainian-computer")
```

If you set it to `"german"`, e.g. the key next to "p" becomes "ü". The default key binding is `C-\`, it's a toggle, so you switch back by pressing it again.

**Comment by phikal** [comment]
Yes, I use that from time to time (specifically with `perman-postfix`), what I was wondering about was if this could be activated _automatically_ on a per-function basis (like `ivy-re-builders-alist`).

If not, or if this is not something there's interest in doing, just close this issue.

**Comment by abo-abo** [comment]
> could be activated automatically on a per-function basis

Thanks, this is now possible via `ivy-hooks-alist`. Please test.

**Comment by basil-conto** [comment]
> If there is such a mechanism already, I apologize upfront that I couldn't find it.

Vanilla Emacs calls this mechanism "character folding", and it is documented under [`(emacs) Lax Search`](https://www.gnu.org/software/emacs/manual/html_node/emacs/Lax-Search.html). It can be enabled either by default by setting `search-default-mode` to the function `char-fold-to-regexp`, or by interactively typing <kbd>M-s</kbd><kbd>'</kbd> (`isearch-toggle-char-fold`) within an Isearch session.

Swiper does not currently have a command or key to toggle character folding like Isearch does, but Swiper does behave as expected when `search-default-mode` is set to `char-fold-to-regexp`.

**Comment by phikal** [comment]
Thanks for the note! I tried it out and it seems to work, at least with isearch and swiper, but sadly not with `counsel-org-goto-all`...

**Comment by basil-conto** [comment]
Right. A feature request in its own right, perhaps.
