### ISSUE TITLE
highlight bug?

### ISSUE THREAD

**Issue by jag2** [abo-abo/swiper#19]
Swiper erased all highlights in the ```*Package*``` buffer immediately after pressing ```M-x swiper```. The same happened in the ```*EMMS playlist*``` buffer. Any ideas?

**Comment by abo-abo** [comment]
Swiper calls `font-lock-ensure` (or `font-lock-fontify-buffer` for older Emacs) to have the
selection candidates highlighted. It should be OK to call these functions for any buffer that has
`font-lock-mode` on.

I think it's a problem of the corresponding mode if it bugs out after a call to `font-lock-ensure`.
I could add some workarounds though. What are the values of `major-mode` for the problematic buffers?

**Comment by jag2** [comment]
I wasn't aware that this was the expected behavior. Would it be possible to revert the buffer to normal once the selection has been made?

**Comment by abo-abo** [comment]
> Would it be possible to revert the buffer to normal once the selection has been made?

It's possible not to call `font-lock-ensure` for problematic `major-mode`s.
I've already added all modes derived from `magit-mode` to this list.
I just need a list of `major-mode`s which are problematic for you.

Just use <kbd>M-:</kbd> (`eval-expression`) to see what the value of `major-mode` is.

**Comment by jag2** [comment]
One is `package-menu-mode` and the other is `emms-playlist-mode`.

**Comment by abo-abo** [comment]
See if the last commit solves your issue.

**Comment by jag2** [comment]
It didn't solve. I replaced the swiper.el file with the most recent one and restarted emacs. Is there something else I need to do?

**Comment by abo-abo** [comment]
What's your Emacs version? Maybe you could also add a screenshot of the erased highlights in the
package menu.

**Comment by jag2** [comment]
Updating via melpa fixed the problem. I'll be replacing Isearch with swiper and see how it goes. Thanks for this!

**Comment by abo-abo** [comment]
You're welcome. If the same problem comes up for another mode, just reopen this issue.

**Comment by jagrg** [comment]
I think `org-agenda-mode` also needs to be fixed.

**Comment by abo-abo** [comment]
Thanks!

**Comment by jagrg** [comment]
Could you also add `mu4e-view-mode` and `mu4e-headers-mode`?

**Comment by abo-abo** [comment]
Thanks.

**Comment by daimrod** [comment]
`w3m-mode` and `elfeed-show-mode` also have problem with `font-lock-fontified`, could you add them?

Also, given the large number of mode impacted, wouldn't it make sense not to use `font-lock-ensure`? Why does swipe need it and isearch doesn't? What problem does it fix? If it's more often a problem than not, wouldn't it be easier to set when `font-lock-ensure` should be ran instead of when not ran it?

**Comment by abo-abo** [comment]
@daimrod The issue is that for all modes where `font-lock-ensure` does something weird, it's the fault of that mode: they use font-lock without properly defining the syntax.  So the buffer may be fontified only once and can't be refreshed.

I think it's good to keep a list of these faulty modes - it may be easier to fix them in the future.  For now, I'll just add `w3m-mode` and `elfeed-show-mode` to the list.

**Comment by daimrod** [comment]
Ok.

Thanks for the fix and the explanation.

**Comment by momomo5717** [comment]
When `font-lock-fontify-buffer` was called at `emms-stream-mode`, this issue occurred.

I'm unfamiliar with `font-lock` and `text-property`,
but it seems all `'face` of `text-property` was set to `nil`
after running `font-lock-fontify-buffer-function` bound to `font-lock-default-fontify-buffer` as a local variable,
and `(font-lock-unfontify-region (point-min) (point-max))` caused this issue.

I searched for information about `font-lock-fontify-buffer-function`,
and found the setting example:
```emacs-lisp
(set-default 'font-lock-fontify-buffer-function 'jit-lock-refontify)
```
It works fine. But I'm not sure it is correct setting.

Thank you.

**Comment by abo-abo** [comment]
@momomo5717 Thanks, I excluded `emms-stream-mode` from the fontify list.

**Comment by momomo5717** [comment]
Thank you for adding it!

**Comment by sshbio** [comment]
It seems that I found some more:

- `occur-mode`, for which <kbd>g</kbd> restore the highlight (but also update the content of the buffer);
- `occur-edit-mode`
- `bongo-mode`

I'm on 24.5.1.  Thank you.

**Comment by abo-abo** [comment]
@sshbio Thanks, updated.

**Comment by sshbio** [comment]
You are welcome.

I think `eww-mode` is also one of those.  Thank you for bthe improvements.

**Comment by sshbio** [comment]
I found one more: `vc-dir-mode`.

We are building a list that may be useful for other package writers as well.

Again, thank you for improving swiper it.

**Comment by sshbio** [comment]
`bongo-playlist-mode` and `bongo-playlist-mode` buffers also loose their pretty colors.

Thank you for your previous additions.  Hopefully I will get a copyright assignment, and will be able to submit pull requests.

**Comment by sshbio** [comment]
This list may become pretty long! `sauron-mode` also seems to be one of them.

**Comment by fuxialexander** [comment]
Would you please add `notmuch-tree-mode` and `notmuch-search-mode` to the list?
