### ISSUE TITLE
Help: last used command first in M-x?

### ISSUE THREAD

**Issue by alex-glv** [abo-abo/swiper#190]
Hi! 

Both helm and ido (afaik?) suggest last used commands first.
If I opened multi-term, next time I open M-x multi-term is recommended.

Is there a way to do that with ivy?

Thanks

**Comment by abo-abo** [comment]
Yes, just use `counsel-M-x` from the counsel package in MELPA (the code is in this repository). When you have `smex` package installed, `counsel-M-x` will use smex's ranking algorithm for sorting.

**Comment by alex-glv** [comment]
Oh, this is great. I have seen counsel references in blog posts but wasn't sure what it was.
Thanks!
