### ISSUE TITLE
Add counsel-man

### ISSUE THREAD

**Issue by drrlvn** [abo-abo/swiper#1901]
The `man` command has no completion for man pages so a `counsel-man` command would be useful.

**Comment by manuel-uberti** [comment]
I also use `woman` with `ivy-mode` on and it's fine. @drrlvn do you think a dedicated counsel command could improve on this?

**Comment by drrlvn** [comment]
I don't like `woman` since its formatting looks much worse that `man` for me. I do like its completion with `ivy` though.

I could try opening a PR tomorrow if you like or you can just close this if you think it's redundant, both are fine.

**Comment by drrlvn** [comment]
That's weird, even with `emacs -Q` I don't get any completion for `man` but I still do for `woman`. Nothing with `make plain` either obviously.

That rules out anything wrong with my config but where else could the problem be?

Well, it's not your job to debug my distro so if `man` has completion and it doesn't work only for me then feel free to close this and I'm sorry.

**Comment by abo-abo** [comment]
> Well, it's not your job to debug my distro so if man has completion and it doesn't work only for me then feel free to close this and I'm sorry.

No problem, thanks for the report.

**Comment by ardpp** [comment]
Just tried it on my system and strangely enough I do get `man` completion with `emacs -Q` but not with `make plain`.
I'm on Archlinux and using `GNU Emacs 27.0.50`

**Comment by abo-abo** [comment]
@ardpp Can you examine your `load-path` in both cases?

**Comment by ardpp** [comment]
You mean `M-x describe-variable RET load-path`? They are exactly the same in both cases.

**Comment by ardpp** [comment]
I do actually get `man` pages in both cases actually, sorry! I have to remove the leading `^` when using `make plain`. I do not get the same completion as is shown in screenshots by @basil-conto though.

**Comment by drrlvn** [comment]
Turns out that in Arch the service that builds the mandb is not enabled by default. Even `man -k open` didn't work.

After running `systemctl enable --now man-db.timer` and `systemctl start man-db.server` (to run it now) everything is OK now.

Really sorry for spamming you with this, hope it at least helps someone else.

**Comment by basil-conto** [comment]
No worries, thanks for reporting back; glad it works. Hopefully your insights will also solve the issue for @ardpp.

**Comment by drrlvn** [comment]
Whoops, of course. I meant `man-db.service` the second time.
