### ISSUE TITLE
counsel-ag not narrowing results

### ISSUE THREAD

**Issue by paulbdavis** [abo-abo/swiper#1907]
Using `counsel-ag` in version `0.11.0` does not narrow any results. No matter the search string I enter, all of the lines in the directory show up in search. Before the update to `0.11.0` it worked fine.

Using `counsel-git-grep` does narrow as expected and just running `ag` returns a buffer with the matching lines as expected.

EDIT: tried to add a screenshot, but the button to do that seems to be gone... (how do I drag without a file manager Microsoft!?!)

EDIT2: Oh, you click the text... nice UI design..

Here is the screenshot

![counsel-bug](https://user-images.githubusercontent.com/2730634/51873554-e33c1c00-231a-11e9-9c80-79da88e5a8fa.jpg)

**Comment by abo-abo** [comment]
Can't reproduce on GNU/Linux and Emacs 26.1. I assume you're on Windows. What's your `ag --version`?

**Comment by abo-abo** [comment]
Also, what's your setting of `counsel-ag-base-command`. And what does e.g. "ag --vimgrep ivy" produce from `M-x shell`?

**Comment by abo-abo** [comment]
I have `ag 2.1.0`, but I don't think that should matter. Can you reproduce by cloning this repo and running `make plain` and `M-x counsel-ag`?

**Comment by paulbdavis** [comment]
Upon firther investigation, it seems that setting `(setq ivy-re-builders-alist '((t . ivy--regex-fuzzy))` is the cause of the issue. Setting it back to `ivy--regex-plus` fixes the issue

**Comment by paulbdavis** [comment]
```elisp
  (setq ivy-re-builders-alist '((counsel-ag . ivy--regex-plus)
                                (t . ivy--regex-fuzzy)))
```

Using these settings seems to fix it while keeping fuzzy matching everywhere else

**Comment by abo-abo** [comment]
Thanks. The recent improvements to `ivy--regex-fuzzy` and `ag`'s interpretation of what "[^a]" should match resulted in this bug. It should be fixed now, you can now use `ivy--regex-fuzzy` for ag once more.

This problem doesn't happend with `ripgrep`, because it thinks (and I agree) that "[^a]" should not match a newline. See the commit message for details.

**Comment by paulbdavis** [comment]
any chance it will get tagged as `0.11.1`? I am trying to keep as many of my packages on stable versions as possible

**Comment by paulbdavis** [comment]
Fair enough. Thanks again for all of the work you do

**Comment by abo-abo** [comment]
You're welcome.
