### ISSUE TITLE
counsel-grep-function not working as documented

### ISSUE THREAD

**Issue by jcmdln** [abo-abo/swiper#1909]
### Synopsis
Is there a `grep` equivalent of `counsel-ag` where it searches the current directory? I'm aware of `counsel-git-grep` but `counsel-ag` didn't require being within a git directory, which is the behavior I would like with a `grep` equivalent. `counsel-grep-function` is described as doing this but it doesn't appear to be working. Is there something I'm misunderstanding?

### Background
I was originally using `ag` via `counsel-ag` though I'm wanting to remove a dependency and switch to using `grep` despite it being slower. I came across `counsel-grep-function` which defines itself as follows:

``` elisp
(defun counsel-grep-function (string)
 "Grep in the current directory for STRING."
...
```

This seemed to be exactly what I needed, though when attempting to bind this function in place of `counsel-ag` I receive the following error:

``` elisp
Wrong type argument: commandp, counsel-grep-function
```

Thinking this was an issue with my configuration, i reinstalled all of my packages with no luck. I then started GNU/Emacs with `-Q -q` and ran the following in a scratch buffer:

``` elisp
(require 'ivy)
(ivy-mode 1)
(setq ivy-use-virtual-buffers t)
(setq enable-recursive-minibuffers t)
(global-set-key (kbd "C-c k") 'counsel-grep-function)
```

Unfortunately I received the same error message. Any suggestions on correcting this or should I return to using `counsel-ag`?

**Comment by abo-abo** [comment]
> Wrong type argument: commandp, counsel-grep-function

This means (for any Emacs function) that it was not intended to be used as a command. You can make key bindings only for commands, i.e. functions that you see in e.g. `counsel-M-x`.

You can probably customize `counsel-grep-base-command` to do what you want: use a combination of `ls`, `xargs` and `grep`. Although I don't recommend it: tools like `ag` or `rg` solve this in a much better way.

**Comment by jcmdln** [comment]
Ah, thank you for the clarification!

I'll see about making a similar command for `grep`, though `ag` has been in every linux/unix package manager I've personally encountered so I really should use it or `rg`.
