### ISSUE TITLE
How do I use counsel-fzf-cmd?

### ISSUE THREAD

**Issue by kshenoy** [abo-abo/swiper#1911]
In shell, I run the following bash function to open files from a perforce repository:

````
fzf-find-file-p4() {
    p4 have $REPO_PATH/... | awk '{print $3}' | fzf -m
}
````

I'm not able to figure out how to do the same with counsel-fzf and counsel-fzf-cmd. I see that it's being processed like this:

    (let ((fzf-basename (car (split-string counsel-fzf-cmd))))
      (counsel-require-program fzf-basename)

which means that the first word of counsel-fzf-cmd has to be `fzf` as `counsel-require-program` only returns non-nil for executables.

**Comment by abo-abo** [comment]
Within Emacs, you can use `fzf` only in non-interactive filter mode: `fzf -f <text>`.

Try it from the shell like this:

    ls | fzf -f el

Try if it works with your command:

    p4 have $REPO_PATH/... | awk '{print $3}' | fzf -f <search-string>

Finally, if it works, do:

```elisp
(defun my-counsel-p4 ()
  (interactive)
  (let ((counsel-fzf-cmd "p4 have $REPO_PATH/... | awk '{print $3}' | fzf -f \"%s\""))
    (counsel-fzf)))
```

**Comment by abo-abo** [comment]
Please test if it works for you.
