### ISSUE TITLE
ivy-toggle-fuzzy doesn't take effect

### ISSUE THREAD

**Issue by zijianyue** [abo-abo/swiper#1913]
The value of ivy--regex-function is always ivy--regex-plus.
I tried below methods, but can't modify it to ivy--regex-fuzzy.

(ivy-toggle-fuzzy) 
(setq-default ivy--regex-function 'ivy--regex-fuzzy)

**Comment by abo-abo** [comment]
`ivy-toggle-fuzzy` is intended to be used only via <kbd>C-o m</kbd>.

If you want to customize the regex builder, use:

```elisp
(setq ivy-re-builders-alist
      '((t . ivy--regex-fuzzy)))
```
