### ISSUE TITLE
Search History Mess and Proposal

### ISSUE THREAD

**Issue by Alexander-Shukaev** [abo-abo/swiper#1914]
Apart from `counsel`, I frequently use `isearch` and I like those sharing history.  For example, I recently did

```
(defvaralias 'swiper-history 'regexp-search-ring)
```

and it proved to be very useful.  However, since I use `counsel-grep-or-swiper`, it turned out that `counsel-grep` is writing history to `counsel-git-grep-history`.  First question then, why is it `counsel-git-grep-history` and not something like `counsel-grep-history`?  Shouldn't those be separate?  Also `counsel-grep-history` feels like a less misleading and a more general name.

Secondly, why also not write to the already existing `grep-regexp-history` for the same sharing purposes?  I can't imagine my life without `rgrep` at times.

This brings me to the following proposal to tidy things up a bit in this space.

1.  For consistency and flexibility reasons, every search command should definitely write its own history.  That is the case with `counsel-grep` and `counsel-git-grep-history` definitely needs to be sorted out by adding `counsel-grep-history`.
2.  All the `ivy` search-related commands should in addition write a common history, e.g. `ivy-search-history`.  It would make it easier to redirect/merge the whole search history from `ivy`-derived packages with `isearch`, for example:

    ```
    (defvaralias 'ivy-isearch-history 'regexp-search-ring)
    ```

3.  Let's teach the `:history` keyword-related functionality to be customizable and apart from each command writing its own private history, to also consider some `defcustom` `ivy-search-history-variables-alist`, where each `cdr` would be a list of additional custom variables, where to write history to for a particular command.  That is one could then selectively choose particular set of commands to write their history to `regexp-search-ring` and/or `grep-regexp-history` and/or whatever other history variables.

**Comment by abo-abo** [comment]
Thanks. I've added `counsel-grep-history` since it solves the immediate problem.

I'm not sure about messing with `grep-regexp-history`. Also not sure about the grand unified customizable history design. Of course we could make it, but to what purpose? I prefer that the user just says `(require 'counsel)` rather than having to define all kinds of aliases for history variables.

We can still pick this up as part of a feature that lets the user customize any arguments to `ivy-read` per-caller.

**Comment by Alexander-Shukaev** [comment]
But how would `(require 'counsel)` solve my initial requirement that I want `ivy` search commands to share history with `grep` and `isearch` and potentially others in future?  At the moment, `defvaralias` hack is the only solution.

**Comment by abo-abo** [comment]
What I meant here is that the user that doesn't want to do extra config should just `(require 'counsel)` and have all grep-like history shared automatically, like `counsel-rg` and `counsel-git-grep` already do.
If we have individual history for every single command, than it's up to either us or the user to group them together via `defvaralias` (which is not a hack in any bad meaning of the word, I think).

**Comment by Alexander-Shukaev** [comment]
`counsel-*g` and `counsel-recoll` still use `counsel-git-grep-history`.  They should either have separate histories or at least `counsel-grep-history`.
