### ISSUE TITLE
dired buffer in ivy-mode: C command problem

### ISSUE THREAD

**Issue by srustamo** [abo-abo/swiper#192]
In dired buffer, in `ivy-mode` selecting a line with with a file, hitting `C` to copy raises the minibuffer with candidates. However, it is problematic to name the file with a new name, not in the list. 

Is it possible already and I am missing some command to do so?

**Comment by abo-abo** [comment]
> Is it possible already and I am missing some command to do so?

Just enter the new name and press <kbd>C-m</kbd> or <kbd>C-j</kbd>. If the new name matches at least one candidate, press <kbd>C-M-j</kbd> or <kbd>C-u C-j</kbd> to ignore the matched candidate and use only the entered text.

**Comment by srustamo** [comment]
Thank you.
