### ISSUE TITLE
tramp and counsel-find-file hangs with 'Blocking call to accept-process-output with quit inhibited!!' 

### ISSUE THREAD

**Issue by Jehops** [abo-abo/swiper#1920]
Hello,

To reproduce the issue, I cloned the repository and did `counsel-find-file`.  When the supplied path is of the form `ssh:host:/dir1/dir2...`, when changing directories (enter `/`), there is usually a short hang and `Blocking call to accept-process-output with quit inhibited!!` is reported in the minibuffer.  There is a caveat; this is with master-branch Emacs (94245b9 from 2019-02-01).

Regards,

Joseph

**Comment by Jehops** [comment]
Update: I submitted an Emacs bug, since it's unclear (to me) where the source of the problem is.
https://debbugs.gnu.org/cgi/bugreport.cgi?bug=34297

**Comment by basil-conto** [comment]
Aaand Michael's latest commit seems to have fixed the issue for me: http://git.savannah.gnu.org/cgit/emacs.git/commit/?id=b32ac17c32486d8fce0fb9ecd5e09fe324448d3d

@Jehops do you still run into the warning with latest `master`?

**Comment by basil-conto** [comment]
Hm, reverting that commit doesn't reintroduce the warning for me, so I don't know what made it go away.

**Comment by Jehops** [comment]
I can confirm that updating to `b32ac17` stops the hangs/warnings here as well.

**Comment by basil-conto** [comment]
Can this issue be closed then?

**Comment by Jehops** [comment]
I think so. Thank you for your feedback. If I hear something worth reporting here, I will do so.

**Comment by basil-conto** [comment]
Thanks, please do.
