### ISSUE TITLE
counsel replace bookmark ?

### ISSUE THREAD

**Issue by pseudomyne** [abo-abo/swiper#1922]
I'd like to replace an existing bookmark without having to delete it first from the `edit-bookmark` buffer. 
Is there a way to achieve that ? 
Would be nice, IMO, to call some `counsel-replace-bookmark` with a `C-return` shortcut on an existing bookmark.

**Comment by abo-abo** [comment]
You can use <kbd>M-o e</kbd> to rename the selected bookmark.

**Comment by pseudomyne** [comment]
Oh I wasn't aware of these functions. Thanks :)
