### ISSUE TITLE
ivy-set-actions usage (error: invalid-function ";")

### ISSUE THREAD

**Issue by avocadoras** [abo-abo/swiper#1925]
I'm on Emacs 26.01 (macOS mojave).

I'm trying to set an ivy-action during swiper that would allow me to `comment-line` candidate through the ivy-dispatcher. 

When I declare these two functions
```elisp

(defun ivy-comment-line-action (x)
  (comment-line x))

(ivy-set-actions
 t
 (";" ivy-comment-line-action "comment line"))
```
and I evaluate the functions (in written order) I get an error back that the `";"` character is not a valid function .
(*Backtrace* buffer)
```
Debugger entered--Lisp error: (invalid-function ";")
  (";" ivy-comment-line-action "comment line")
  (ivy-set-actions t (";" ivy-comment-line-action "comment line"))
  eval((ivy-set-actions t (";" ivy-comment-line-action "comment line")) nil)
  elisp--eval-last-sexp(nil)
  eval-last-sexp(nil)
  funcall-interactively(eval-last-sexp nil)
  call-interactively(eval-last-sexp nil nil)
  command-execute(eval-last-sexp)
```

 From what I unsertand, the` ";"` key binds the function `ivy-comment-line-action` which becomes available via `ivy-set-actions` in the ivy-dispatcher. Previously, I had this version of the code lack above:
```elisp

(defun ivy-comment-line-action (x)
  (comment-line x))

(ivy-set-actions
 'swiper
 (";" ivy-comment-line-action "comment line"))
```
which tried to call the custom action when calling swiper, but then swiper would not work.

What am I doing wrong here? are ivy-set-actions only valid from ivy group functions ?

**Comment by basil-conto** [comment]
> What am I doing wrong here?

Looks like you're missing a quote: `'(";" ...)` instead of `(";" ...)`.

**Comment by avocadoras** [comment]
@basil-conto fair enough. I just tested this function
```elisp
(ivy-set-actions
 'swiper
 '(";" ivy-comment-line-action "comment line"))
```
and got back `Wrong type argument: listp ";"` in the echo area right after calling my binded swiper key with `C-s`.

**Comment by basil-conto** [comment]
> and got back `Wrong type argument: listp ";"` in the echo area right after calling my binded swiper key with `C-s`.

That is because both `ivy-set-actions` and `ivy-add-actions` expect an alist as their second argument, not a flat list, as suggested by their plural names. Note that `ivy-set-actions` completely overwrites the action alist for a particular command. If you only want to modify or add action bindings, you should use `ivy-add-actions` instead.

> Interestingly, I tried to unload the function by evaluating `(ivy-set-actions t nil)` and I still cannot call swiper with `C-s`. Not even after evaluating and reverting the buffer.

This is because you are resetting the action alist for `t`, not `swiper`. Try `(ivy-set-actions 'swiper ())`.

A couple more notes:
* Your custom action function should not have the prefix `ivy-` in its name, as it risks overwriting an existing Ivy function.
* `comment-line` expects a number relative to the current line, not a string. It also moves point, I think.

How about the following instead:

```el
(defun my-comment-line-action (_line)
  "Comment or uncomment selected LINE.
This function is intended as a `swiper' action."
  (comment-or-uncomment-region (line-beginning-position)
                               (line-end-position)))
```

Disclaimer: guaranteed 100% untested, and I think `comment-or-uncomment-region` also probably does some point moving & restoring tricks.

**Comment by avocadoras** [comment]
>Note that `ivy-set-actions` completely overwrites the action alist for a particular command

Ah, thank you. I did see somewhere `ivy-add-actions`. I think that could probably also be in the manual in addition to the `ivy-set-actions` example. 
>This is because you are resetting the action alist for `t`, not `swiper`. Try `(ivy-set-actions 'swiper ())`.

Ok, I understand now how the function works. I will close this issue given that my problem was that I was not clear how `ivy-set-actions` worked. Thank you very much.

**Comment by avocadoras** [comment]
confirming that 
```elisp
(defun my-comment-line-action (_line)
  "Comment or uncomment currently selected LINE.
This function is intended as a `swiper' action."
  (comment-or-uncomment-region (line-beginning-position)
                               (line-end-position)))
```
works as expected.

**Comment by basil-conto** [comment]
Thanks for reporting back!
