### ISSUE TITLE
Add action to `projectile-find-file`

### ISSUE THREAD

**Issue by explainlikeimfive** [abo-abo/swiper#1927]
I have added an action "open externally" to `projectile-find-file` as follows:

`(ivy-set-actions
 'projectile-find-file
 '(("x" counsel-find-file-extern "open externally")))
`

When I select this action, it opens file with xdg-open as expected. But it still trying to open the file in emacs. How can I avoid this?

**Comment by manuel-uberti** [comment]
FWIW, this is how `counsel-projectile` does something similar, if you want to have a look at it: https://github.com/ericdanan/counsel-projectile/blob/master/counsel-projectile.el#L293
