### ISSUE TITLE
ivy-switch-buffer Doesn't Show Recent Files on Fresh Start

### ISSUE THREAD

**Issue by kevinjfoley** [abo-abo/swiper#1936]
When I start a new emacs process `ivy-switch-buffer`  with `ivy-use-virtual-buffers` set to `t` only shows *scratch* *Messages* and *Warnings*.

`(buffer-list)` and `(all-completions "" #'internal-complete-buffer)` only show those buffers, however `recentf-list` has a list of my recent files.

After using `counsel-find-file` the recent file show up in `ivy-switch-buffer`.  I'm using the latest `counsel` from the master branch and have tested with `emacs -q`.

**Comment by abo-abo** [comment]
Can't reproduce. I used:

- `make plain`
- evaluate `(setq ivy-use-virtual-buffers t)`
- <kbd>C-x b</kbd>

**Comment by kevinjfoley** [comment]
This made me look at my config again and realize that setting `ivy-use-virtual-buffers` to `t` was being deferred until counsel was loaded which is why things weren't working.  Thank you for taking a look!
