### ISSUE TITLE
Error with counsel-locate when using zsh as login shell

### ISSUE THREAD

**Issue by makkus** [abo-abo/swiper#194]
As per title, counsel-locate prints "Error" as soon as a regex is created. I.e. "abc" as input is fine, but not "abc abc". 
I think it's because of how one needs to escape most characters in zsh ('.', '*', '?', ...), and those are used in counsel-locate when a regex is created, in addition to '(' and ')', which are escaped as far as I could see.
Might be overlooking something here, but wouldn't just enclose the regex between ' be enough?

**Comment by abo-abo** [comment]
Here's the shell command that is run for `abc abc`:

    locate -i --regex \\(abc\\).*?\\(abc\\)

I've now changed it to:

    locate -i --regex '(abc).*?(abc)'

Please check if it works fine for you.

**Comment by makkus** [comment]
Yup, that works. First one errors out with: 

$ locate -i --regex \\(abc\\).*?\\(abc\\)
zsh: number expected

Second one returns some results.
