### ISSUE TITLE
[Question] How to use ivy--regex-fuzzy with magit-builtin-completing-read

### ISSUE THREAD

**Issue by yqrashawn** [abo-abo/swiper#1945]
(setq ivy-re-builders-alist
        '((projector-run-command-buffer-prompt . ivy--regex-fuzzy)
          (spacemacs/counsel-search . spacemacs/ivy--regex-plus)
          (spacemacs/search-auto . spacemacs/ivy--regex-plus)
          (t . ivy--regex-plus)))
https://github.com/magit/magit/blob/3e73ff19d342bdebf9b91ec78f03d24aa0dbe771/lisp/magit-utils.el#L483

**Comment by basil-conto** [comment]
Can this be closed in favour of #1946?

**Comment by yqrashawn** [comment]
Oh. Really sorry for this.
