### ISSUE TITLE
Display counsel-rg candidates in the main buffer

### ISSUE THREAD

**Issue by rememberYou** [abo-abo/swiper#1949]
Hey,

First of all, I thank you for your outstanding work for the community. 

Recently, I tested `counsel-rg`, which is great. However, I would like to be able to have my main buffer that displays this candidate as I review the list of candidates.

In addition, if a candidate is selected, then the main buffer should becomes the candidate. Otherwise, if `counsel-rg` is left, then the buffer return to his previous state before `counsel-rg` is called.

I find this behaviour ergonomic, but I don't know if there is already a way to achieve this result, or if this could be an idea that could improve `counsel-rg`.

What do you think of this possibly feature?

**Comment by basil-conto** [comment]
Maybe I've misunderstood you, but I think you can achieve what you're describing by enabling `ivy-calling`. The easiest way to do this is to ensure the `ivy-hydra` package is installed, and then invoke <kbd>C-o</kbd><kbd>c</kbd> during a `counsel-rg` completion session. Alternatively, you can bind `ivy-toggle-calling` to a key of your choosing. Here are the precise steps:

1. <kbd>M-x</kbd>`counsel-rg`<kbd>RET</kbd>
2. -enter search string-
3. <kbd>C-o</kbd><kbd>c</kbd>
4. <kbd>C-o</kbd> (optional)
5. <kbd>C-n</kbd> or <kbd>C-p</kbd> (repeat as many times as you wish)
6. <kbd>C-g</kbd> (to restore original buffer from which completion was invoked)

This is briefly mentioned under [`(ivy) Hydra in the minibuffer`](http://oremacs.com/swiper/#hydra-in-the-minibuffer).

**Comment by rememberYou** [comment]
That exactly what I needed, thank you for the fast reply.
