### ISSUE TITLE
No candidates in gnus-summary-move-article

### ISSUE THREAD

**Issue by oscarperpinan** [abo-abo/swiper#195]
Hi,

I would appreciate your help to use `ivy-mode` in `gnus`. It works correctly, for example, to complete groups when using `gnus-group-jump-to-group`. However, it shows no candidates with `gnus-summary-move-article`. I have tried to assign `ivy-completing-read` to `gnus-completing-read-function` but I get:

```
ivy-read: Wrong type argument: stringp, gnus-group-history
```

Thanks in advance.

Oscar.

**Comment by abo-abo** [comment]
What's your Emacs version? I'm on 24.5.2 and have no trouble, except that I get zero matches for the initial input of gnus.  But when I delete the minibuffer contents with <kbd>C-k</kbd>, I see the matches.

**Comment by oscarperpinan** [comment]
I'm on 24.5.1. Ok, after `C-k` I get the matches. Is it possible to avoid this step?

**Comment by xuchunyang** [comment]
The issue seems to apply to `unload-feature` and `describe-face` as well. (on Emacs 24.5.1)

**Comment by abo-abo** [comment]
Thanks for these, I didn't notice them before.

> describe-face

This uses `completing-read-multiple`, which is an interface different from `completing-read`. Hence `ivy-mode` isn't involved here (yet). I did some work on multiple candidates with `counsel-org-tag`, but it's not yet in a state to work in a generic way.

> unload-feature

This is a bug in Emacs, I believe. According to the doc of `completing-read`, the collection can be a list of strings or function or alist or obarray. However, `read-feature` calls `completing-read` with a list of symbols, which should be a list of strings instead.  Here's how to patch it right now to work with or without `ivy-mode`:

```elisp
(defun read-feature (prompt &optional loaded-p)
  "Read feature name from the minibuffer, prompting with string PROMPT.
If optional second arg LOADED-P is non-nil, the feature must be loaded
from a file."
  (intern (completing-read prompt
			   (mapcar 'symbol-name features)
			   (and loaded-p #'feature-file)
			   loaded-p)))
```

I can apply this patch in Emacs master, but it will take a while before it makes it to the new Emacs release.

**Comment by abo-abo** [comment]
> I'm on 24.5.1. Ok, after C-k I get the matches. Is it possible to avoid this step?

I found the cause of the problem: the initial input contains `+`, which is interpreted as a regex construct.  If you escape the plus with `\`, it will work as intended. I've added the code to make this automatically, please check.

**Comment by oscarperpinan** [comment]
Thanks. It works perfectly.

**Comment by ngleb** [comment]
It doesn't work anymore on Emacs 25.3 and Gnus 5.13. No candidates until I remove \ from the the initial input which is "nnimap\+fm:"

So when I have "nnimap+fm:", everything works as expected. Is there anything that can be done?

**Comment by abo-abo** [comment]
@ngleb You can turn of ivy selectively with `ivy-completing-read-handlers-alist`.
