### ISSUE TITLE
[Feature request] add option to never use line-move

### ISSUE THREAD

**Issue by haji-ali** [abo-abo/swiper#1952]
I know that `line-move` is the reason for slowing down of `swiper` when `visual-line-mode` is on. On my machine I am experiencing this issue with buffers with 200 lines, but I still like the `visual-line-mode`. It would be great if I can prevent `swiper` from calling `line-move`, I don't mind the worse search experience for my long lines (I usually have very few).

I thought I could use `swiper-use-visual-line`, but it seems to be reset inside `swiper--candidates` depending on some conditions.  Maybe have `swiper-use-visual-line` be a function that I can redefine or set instead of a variable?

**Comment by abo-abo** [comment]
Thanks, please test.

You can use:

```elisp
(setq swiper-use-visual-line-p (lambda (_) t))
```

**Comment by haji-ali** [comment]
Tested. Working as expected. The code I used is

```
(setq swiper-use-visual-line-p (lambda (_) nil))
```

To disable `line-move` completely and keep swiper fast!

**Comment by basil-conto** [comment]
> `(setq swiper-use-visual-line-p (lambda (_) nil))`

AKA `(setq swiper-use-visual-line-p #'ignore)`.
