### ISSUE TITLE
ivy-make-magic-action prevents documentation

### ISSUE THREAD

**Issue by DamienCassou** [abo-abo/swiper#1956]
The [new `ivy-make-magit-action`](https://github.com/abo-abo/swiper/commit/51c5874c75c0f5d0d1c6ce2cce9517aa7d5a5894#diff-fb788f1f3b47b493f0eb3eb62cde17b3R2858) prevents understanding what is happening because no docstring or even command name is attached to the bindings. I suggest passing at least a docstring and maybe a name to the function:

```emacs
(define-key map (kbd "`") (ivy-make-magic-action "b" "Reset find-file starting from a bookmark" 'cd-bookmark)
```

Another solution could be for `ivy-make-magic-action` to get the docstring and command name automatically by searching a provided keymap for the given key. But this might be a bit too magical.

I can have a look at implementing one of these if you agree.

Nevertheless, I would suggest not abusing this feature because each time you define a command like that, we loose the ability to name files starting with the chosen character.

**Comment by abo-abo** [comment]
Fixed, thanks.

> we loose the ability to name files starting with the chosen character.

`counsel-find-file-map` is still exposed to customization by the user.
