### ISSUE TITLE
Error in post-command-hook (ivy--queue-exhibit): (invalid-function with-connection-local-variables)

### ISSUE THREAD

**Issue by nordlow** [abo-abo/swiper#1961]
All my Counsel/Ivy commands has recently (about a day ago) started to fail with Emacs master as

```
Error in post-command-hook (ivy--queue-exhibit): (invalid-function with-connection-local-variables)
```

The definition of `with-connection-local-variables` in Emacs master currently looks as

```
(defmacro with-connection-local-variables (&rest body)
  "Apply connection-local variables according to `default-directory'.
Execute BODY, and unwind connection-local variables."
  (declare (debug t))
  `(if (file-remote-p default-directory)
       (let ((enable-connection-local-variables t)
             (old-buffer-local-variables (buffer-local-variables))
	     connection-local-variables-alist)
	 (hack-connection-local-variables-apply
	  (connection-local-criteria-for-default-directory))
	 (unwind-protect
             (progn ,@body)
	   ;; Cleanup.
	   (dolist (variable connection-local-variables-alist)
	     (let ((elt (assq (car variable) old-buffer-local-variables)))
	       (if elt
		   (set (make-local-variable (car elt)) (cdr elt))
		 (kill-local-variable (car variable)))))))
     ;; No connection-local variables to apply.
     ,@body))
```

I can't find any references to `with-connection-local-variables` in any of my currently activate Emacs modules. Is the problem that `with-connection-local-variables` has changed from being a function to being a macro?

And activating "Enter Debugger on Error" doesn't have any effect here.

What's wrong?

**Comment by avocadoras** [comment]
I get a similar error. This happens when I try to search with `M-x`. In my case, I'm trying to search for a function in `sly` (`sly-mode-map`)
![Screen Shot 2019-03-11 at 9 02 17 AM](https://user-images.githubusercontent.com/36335687/54134022-ccd6b500-43dc-11e9-81b5-e9a9b4531c86.png)

**Comment by terlar** [comment]
I haven't investigated this, but I can confirm I get the same error as the original post mentions, running the latest Emacs master version. I get it when I try to use `counsel-rg`.

**Comment by basil-conto** [comment]
This looks like a bug with Emacs `master`, not Swiper:
* https://debbugs.gnu.org/34808
* https://lists.gnu.org/archive/html/emacs-devel/2019-03/msg00337.html

**Comment by terlar** [comment]
I suspected this was the case, thank you for the information. I have updated the Emacs version and can confirm that the issue is resolved.

**Comment by nordlow** [comment]
Are you saying trying the latest Emacs master will solve my problem?

**Comment by abo-abo** [comment]
@nordlow

I can confirm that ivy still works fine on 26.1, the latest stable version. And also on 24.3, the oldest supported version.

As far as I understand, the problem was caused by using an outdated trunk version of Emacs, which can be fixed by updating to the latest trunk version of Emacs.

Would adding `(require 'files-x)` somewhere in ivy.el solve the problem? In that case, please PR.

**Comment by nordlow** [comment]
The problem goes away on latest Emacs master. I'm closing this and reopen if the problem reoccurs.

**Comment by basil-conto** [comment]
@nordlow 

> I can't find any entry in git log that refers to a solution.

As mentioned in the `bug-gnu-emacs` and `emacs-devel` threads I linked above, the issue was with a stale `lisp/ldefs-boot.el` file and was fixed in https://git.savannah.gnu.org/cgit/emacs.git/commit/?id=89082c823c738b8e3b436e4af1307eefe193eac9

No need for `files-x` magic.

**Comment by Ergus** [comment]
Hi:
I am using the emacs master branch and I am getting the same error again since yesterday.

**Comment by nanounanue** [comment]
Hi

After refreshing* `ivy` yesterday I am getting the (similar) error:

```
Error in post-command-hook (ivy--queue-exhibit): (wrong-type-argument sequencep 74995)
```

* pullied from master using `straight-pull-package`

**Comment by mbarton98** [comment]
> Hi
> 
> After refreshing* `ivy` yesterday I am getting the (similar) error:
> 
> ```
> Error in post-command-hook (ivy--queue-exhibit): (wrong-type-argument sequencep 74995)
> ```
> 
> * pullied from master using `straight-pull-package`

I found if I comment out ivy-prescient I don't get that error. I'm not sure why yet, but I had noticed prescient had done some performance updates last week.

**Comment by nanounanue** [comment]
Hi!

I can confirm that, if I comment `ivy-prescient` the search works again

Also there is this related issue #2414 (`prescient` is the problem there too)


> > Hi
> > After refreshing* `ivy` yesterday I am getting the (similar) error:
> > ```
> > Error in post-command-hook (ivy--queue-exhibit): (wrong-type-argument sequencep 74995)
> > ```
> > 
> > 
> > 
> > * pullied from master using `straight-pull-package`
> 
> I found if I comment out ivy-prescient I don't get that error. I'm not sure why yet, but I had noticed prescient had done some performance updates last week.

**Comment by mindlike** [comment]
I have this issue with and without `prescient`. Please re-open.

**Comment by basil-conto** [comment]
> I have this issue with and without `prescient`.

Which issue exactly? Three completely different error messages, likely caused by three separate issues, have been mentioned in this issue thread so far.

If you are running into an error please submit a new bug report with as much detail as possible, and ideally with a reproducible recipe starting from `make plain` or `emacs -Q`. Thanks.

**Comment by mindlike** [comment]
For me, the error message in the title "Error in post-command-hook
(ivy--queue-exhibit): (invalid-function with-connection-local-variables)"
was crashing Doom's `+ivy/project-search` command.

On Sunday I rebuilt master Emacs and master Doom from scratch, then
recompiled all packages. The error disappeared.

Will edit this message with the relevant version info soon (I'm mobile).
