### ISSUE TITLE
update counsel-rg error

### ISSUE THREAD

**Issue by jia0zi** [abo-abo/swiper#1964]
When I update to the latest version, use counsel-rg error: 
`counsel–find-project-root: Wrong type argument: stringp, nil`

**It can be used normally before.** 

**System:** Windows 7
**Version:** 25.3.1

![a55185ad4fb01c8061b7155e732adfe222ce66f4](https://user-images.githubusercontent.com/34630069/54260751-d14dca00-45a4-11e9-9c38-37b227e2aa7c.png)

**Comment by basil-conto** [comment]
I think #1963 fixes this.

**Comment by stsquad** [comment]
I've tested the current master and I think this can be closed now.

**Comment by jia0zi** [comment]
@basil-conto @stsquad thks
