### ISSUE TITLE
[question] is it possible to show ivy candidate in normal buffer rather than minibuffer?

### ISSUE THREAD

**Issue by BooAA** [abo-abo/swiper#1967]
My workflow is splitting a frame into two windows side by side, left one for source code, right one for some references or other source in the project I'm not focusing on. 

I want whenever I call swiper or counsel-* command, the candidates can be displayed at the right one (maybe a little bit like helm I think) which can reduce the interference of focusing on the origin buffer. I know ivy can display candidates with other things like lv, popup by overriding the original ivy-display-function, but I don't know whether it's easy to implement my idea and whether we need to rewrite lots of commands which was originally designed for minibuffer.

**Comment by CeleritasCelery** [comment]
https://github.com/abo-abo/swiper/wiki/ivy-display-function#display-candidates-with-window

also check out https://github.com/tumashu/ivy-posframe

**Comment by otadmor** [comment]
I personally bind ivy-occur to a key and use it when i want to see all candidates in a buffer which is not the minibuffer.

**Comment by BooAA** [comment]
> https://github.com/abo-abo/swiper/wiki/ivy-display-function#display-candidates-with-window
> 
> also check out https://github.com/tumashu/ivy-posframe

Thanks, that helps.



> I personally bind ivy-occur to a key and use it when i want to see all candidates in a buffer which is not the minibuffer.

I will try that in my workflow.

I think we can close the issue since my question has been answered by the wiki.

**Comment by CeleritasCelery** [comment]
You can close it

**Comment by abo-abo** [comment]
Thanks, closing.
