### ISSUE TITLE
Inserting all entries from a counsel match list into a text buffer?

### ISSUE THREAD

**Issue by drorbemet** [abo-abo/swiper#197]
Using counsel e.g counsel-el I would find it useful to insert all matches into current text buffer at point by hitting something like M-RET instead of RET for instance.
That way I could insert lists of search results making resources from emacs even more available in text files.
Does that feature already exist and I just didn't find it? 
What do you think about it?

**Comment by abo-abo** [comment]
This feature isn't hard to implement, but I can't think of a good binding for it. Here's the code to do it:

```elisp
(define-key ivy-minibuffer-map (kbd "C-M-i")
  (lambda ()
    (interactive)
    (with-ivy-window
      (insert
       (mapconcat
        #'identity
        ivy--old-cands
        "\n")))))
```

I'm not yet sure about the binding or the usability yet. Maybe it should put the text on the kill ring instead. I'll think about it more tomorrow.

**Comment by drorbemet** [comment]
Thank you very much this one is very useful for me.

**Comment by abo-abo** [comment]
You can now press <kbd>M-w</kbd> to store all current candidates into the kill ring. Then yank it where you want. If the region is active in the minibuffer, a regular kill ring save will be done.
