### ISSUE TITLE
Question: combine counsel-git and recentf

### ISSUE THREAD

**Issue by terlar** [abo-abo/swiper#1970]
Is there a way to combine counsel-git with recentf.

Right now my most common pattern is to use `counsel-recentf` and then if a file is not found, I fallback to `counsel-git`. Instead of having to run these two commands, I would like to combine the outputs like `switch-to-buffer` does. So kind of a recursive/(project specific) `switch-to-buffer`.

Is there such a feature built-in?

I saw the ticket #347 and looked quickly at the `switch-to-buffer`, but couldn't see on a quick inspection how it combined with recentf.

**Comment by Alexander-Shukaev** [comment]
I don't think there is an easy way right now.  Most probably, it would be a hack.  In general, I find the example you provided very useful and generalizable.  In fact, there could be a super command for finding files, which could be customized via a `defcustom`, where you would list the different sources of populating candidates, in the order you want.  Those sources could come from any other compatible command returning file candidates, e.g. `counsel-recentf` or any other.  Unfortunately, such generalization and clean approach might require considerable amount of effort.

**Comment by CeleritasCelery** [comment]
> I saw the ticket #347 and looked quickly at the switch-to-buffer, but couldn't see on a quick inspection how it combined with recentf.

`(setq ivy-use-virtual-buffers t)`

**Comment by Alexander-Shukaev** [comment]
He wants to run one command but get a list of candidates consisting of both `counsel-recentf` and `counsel-git` (presumably if he's in a repo at all), preferably in a customizable order.  I'm saying that this would be too specific to implement exactly that.  There should rather be a more general "super" function for searching files, which could take candidates from different "sources" that can be customized (very similar to how `company` fetches completion candidates from different sources/back ends).

**Comment by CeleritasCelery** [comment]
You could build this in ivy but it really doesn’t have a concept of multiple sources. This is one of the things helm is great at. You can just pass it a list of sources and it takes care of them all in one matcher.

**Comment by Alexander-Shukaev** [comment]
Yes and it's some nice feature for `ivy` to have in future.

**Comment by jixiuf** [comment]
try this snippet
```
(setq ivy-use-virtual-buffers t)

(defadvice ivy--virtual-buffers (around counsel-git activate)
  "Append git files as virtual buffer"
  (let ((recentf-list recentf-list )list
        (default-directory default-directory)
        counsel--git-dir)
    (setq counsel--git-dir (locate-dominating-file default-directory ".git"))
    (when counsel--git-dir
      (setq counsel--git-dir (expand-file-name counsel--git-dir))
      (setq default-directory counsel--git-dir)
      (setq list (split-string (shell-command-to-string (format "git ls-files --full-name --|grep -v /snippets/|sed \"s|^|%s/|g\"|head -n 3000" default-directory)) "\n" t))
      (setq recentf-list (append recentf-list list))
      ;; (when (< (length list) 5000)
      ;; (dolist (c list)
      ;;   (setq c (expand-file-name c default-directory))
      ;;   (add-to-list 'recentf-list c))
      ;; )
      )
    ad-do-it))
```

**Comment by abo-abo** [comment]
> I don't think there is an easy way right now

There is a way to do it, although it's a little obscure:

```elisp
(ivy-set-sources
 'counsel-recentf
 '((original-source)
   (counsel-git-expanded-cands)))

(defun counsel-git-expanded-cands ()
  (let ((root (counsel--git-root)))
    (when root
      (mapcar
       (lambda (f) (expand-file-name f root))
       (counsel-git-cands)))))
```

Please test if it works as expected, and close the issue in that case.

**Comment by terlar** [comment]
Nice, seems to work! Thanks, I will use this for a while and get back if I see some issues.

The only thing I noticed which isn't a big thing is that the git source files have the prefix `/home/user/...` instead of `~/user/...`, not sure why it is different between git and recentf.

Thanks :+1:
