### ISSUE TITLE
Question: counsel-find-file history in multiple directories

### ISSUE THREAD

**Issue by dolmens** [abo-abo/swiper#1974]
Currently, counsel-find-file shows the last opened directory on the top of the candidates buffer, so far so good. But when I try to switch to another recently opened directory, like /usr/local/include, there is no help in the path /usr and /usr/local. Any ideas?

**Comment by CeleritasCelery** [comment]
Are you looking for `C-r` (history search) in `counsel-find-file`? Your question is not very clear.

**Comment by basil-conto** [comment]
Is this still an issue?

**Comment by abo-abo** [comment]
Closing the issue as there's no clear question.
