### ISSUE TITLE
character classes unrecognized

### ISSUE THREAD

**Issue by joaocortes** [abo-abo/swiper#1977]
Calling swiper from a buffer that contains
 ``ab``

, I cannot search for the regexp `a[b]`. (Swiper refuses to accept the input, complaining with a `match required` warning).

My configuration,

``` elisp 
(use-package avy)    
(avy-setup-default)
     (global-set-key (kbd "C-c C-j") 'avy-resume)
     (global-set-key (kbd "C-'") 'avy-goto-char-2)
(use-package counsel
  :init (ivy-mode 1)
  (setq ivy-use-virtual-buffers t)
  (setq ivy-count-format "(%d/%d) "))
(global-set-key (kbd "C-s") 'swiper)
```

**Comment by basil-conto** [comment]
Sorry, I can't reproduce this. Can you please try to provide a minimal but detailed step-by-step reproduction recipe? (By "minimal" I mean: using the fewest possible settings deviating from `emacs -Q` or `make plain`.)

Here is what I tried:

1. `emacs -Q`
2. <kbd>M-x</kbd>`package-initialize`<kbd>RET</kbd>
3. `(avy-setup-default)` <kbd>C-j</kbd>
4. `(setq ivy-count-format "(%d/%d) ")` <kbd>C-j</kbd>
5. `ab`
6. <kbd>M-x</kbd>`swiper`<kbd>RET</kbd>
7. `a[b]`

   ![ab](https://user-images.githubusercontent.com/9121222/54763727-64fb4800-4bee-11e9-9e1f-423a7a917a51.png)

Granted, there's a brief but undesirable delay between typing `a[b]` and the match showing up, but it ultimately works.

**Comment by joaocortes** [comment]
I found the issue.

I usually search portuguese text, with a lot of characters like ç and ã.
To have emacs search modulus accent marks, I have

```elisp 
(setq search-default-mode #'char-fold-to-regexp) 

in my init file.

So now the issue is making swiper search modulus accent marks

**Comment by abo-abo** [comment]
Mentioned this in README. Thanks.
