### ISSUE TITLE
ivy: last result becomes partially invisible with non-zero line-spacing

### ISSUE THREAD

**Issue by fjl** [abo-abo/swiper#198]
The minibuffer sizing doesn't seem to take `line-spacing` into account.
I use Cocoa emacs and *something* (not my config) sets `line-spacing` to 0.1 globally.
However it is set, a non-zero value makes the last minibuffer result partially invisible.
This could also be bug in emacs.

<img width="147" alt="bad-line-space" src="https://cloud.githubusercontent.com/assets/6915/9308218/1ffaa494-4503-11e5-82e7-167ce1df1e51.png">

If I locally set `line-spacing` to 0 in `ivy--minibuffer-setup`, it works.

<img width="142" alt="good-line-spacing" src="https://cloud.githubusercontent.com/assets/6915/9308252/4befbaa8-4503-11e5-8f32-ef286d04bff3.png">

This is similar to #161. Maybe [`window-text-pixel-size`](https://www.gnu.org/software/emacs/manual/html_node/elisp/Size-of-Displayed-Text.html) could be useful for solving this issue?

**Comment by abo-abo** [comment]
Thanks, please check if it's solved.

**Comment by fjl** [comment]
It does work, but I'd prefer a solution that keeps the `line-spacing`.

**Comment by abo-abo** [comment]
There isn't a good API for calculating window height pixel-wise, as far as I know. In any case, it should be an automatic Emacs feature to re-size the minibuffer based on the text that's in it. So not much I can do here except set line-spacing to 0.
