### ISSUE TITLE
Question: deactivate ivy temporarily in minibuffer Magit

### ISSUE THREAD

**Issue by avocadoras** [abo-abo/swiper#1981]
I'm trying to ignore a pattern in Magit but `RET` enters the first candidate's path and ignores my input pattern. 

Specifically, I'm trying to ignore a python virtual environment directory. The problem is that when I enter `venv/*`, Magit enters the first candidate. Therefore, I have to ignore all the files one by one.

How can I overcome this? Looked in the manual under the minibuffer key bindings and cannot find what I'm looking for.

**Comment by abo-abo** [comment]
You can either:

- Press <kbd>C-M-j</kbd>
- Press <kbd>C-u C-j</kbd>
- Customize `(ivy-use-selectable-prompt t)` and select the prompt with <kbd>C-p RET</kbd>.

**Comment by avocadoras** [comment]
Thanks for the options. Settling with `C-M-j`. Solved.
