### ISSUE TITLE
 Exact string space match with counsel-rg

### ISSUE THREAD

**Issue by nordlow** [abo-abo/swiper#1982]
AFAICT, `counsel-rg` does approximate matching by default.

For instance, `X Y Z` is converted to a fuzzy match using a regexp `X.*Y.*Z`.

Is there a way to force exact match for, in this case, space?

I'm guessing `X Y Z` gets converted to `X.*.Y.*Z` before being passed to `rg`, right? If so, I believe we should a flag to control this behaviour and probably also two versions of `counsel-rg` one for exact match and one for Emacs-style regexp match.

**Comment by basil-conto** [comment]
> Is there a way to force exact match for, in this case, space?

The default [regexp builder](http://oremacs.com/swiper/#completion-styles), `ivy--regex-plus`, interprets two consecutive spaces as one literal space.

`ivy--regex-ignore-order`, OTOH, escapes literal spaces with a backslash: `X\ Y`

**Comment by nordlow** [comment]
I see, great. Thanks!
