### ISSUE TITLE
Feature request: `swiper-all` twice should insert last search string

### ISSUE THREAD

**Issue by paxperscientiam** [abo-abo/swiper#1985]
Hello!

Executing `swiper` function  twice causes that last term to be "swiped" to be searched again. Could not this be done with `swiper-all` as well?

Currently, executing `swiper-all` a second time yields the error "Command attempted to use minibuffer while in minibuffer" as the pointer is in the minibuffer.

I'm not sure what a solution would look like tbh.

**Comment by abo-abo** [comment]
> Executing swiper function twice causes that last term to be "swiped" to be searched again. Could not this be done with swiper-all as well?

Actually it happens when you press <kbd>C-s</kbd> or <kbd>M-p</kbd> after calling `swiper`. The same will happen when you press <kbd>C-s</kbd> or <kbd>M-p</kbd> after calling `swiper-all`.


> Currently, executing swiper-all a second time yields the error "Command attempted to use minibuffer while in minibuffer" as the pointer is in the minibuffer.

Use `(setq enable-recursive-minibuffers t)`.

**Comment by paxperscientiam** [comment]
Ohh, great. Thank you @abo-abo
