### ISSUE TITLE
Very slow interaction/responsiveness in ivy-switch-buffer + tramp

### ISSUE THREAD

**Issue by Ergus** [abo-abo/swiper#1986]
Hi:
I have observed a very slow responsiveness when using ivy-switch-buffer + tramp.
When opening one file it is fine, but with 2 or more remote files open it freezes and produces very long pauses (2-4 seconds) for a simple ivy-next-line.

In the ibuffer or counsel-find-file  there is not such issue

I ran a profile (just C-x b and some C-n or C-p ) and the output was as you can see in the image:

![Screenshot_2019-03-28_12-01-40](https://user-images.githubusercontent.com/6975176/55152751-4d254600-5151-11e9-83f5-2f7765952a6a.png)

![Screenshot_2019-03-28_11-42-11](https://user-images.githubusercontent.com/6975176/55151915-8fe61e80-514f-11e9-9376-1b5400d63172.png)

**Comment by abo-abo** [comment]
Please transfer this issue to `ivy-rich`.
