### ISSUE TITLE
RFC: counsel command to toggle minor mode

### ISSUE THREAD

**Issue by iquiw** [abo-abo/swiper#1987]
Hi, I wrote `counsel-minor`, which toggles minor mode with completion.

**EDIT: The description and screenshots below are obsoleted.** See https://github.com/abo-abo/swiper/issues/1987#issuecomment-477970468

More precisely,

* List enabled minor modes, disable the selected one.
* List disabled minor modes, enable the selected one.
* Switch the above 2 by <kbd>!</kbd>.

I wonder if it is worth adding it to `counsel.el`.

Code is [here](https://github.com/iquiw/counsel-minor/blob/master/counsel-minor.el).

And screenshots,
![](https://raw.githubusercontent.com/iquiw/counsel-minor/master/images/enabled-modes.png)
![](https://raw.githubusercontent.com/iquiw/counsel-minor/master/images/disabled-modes.png)

**Comment by abo-abo** [comment]
Nice idea. But it could use a few improvements:

- Make sure the given completions are buffer-local, right now I'm getting `TeX-PDF-mode ""` while in an Elisp buffer.
- Get rid of the prefix/non-prefix arg and instead rely on input for enabling/disabling. Like `counsel-package` does it.

If those issue are fixed, and you have an Emacs CA, I'd gladly merge this.

**Comment by iquiw** [comment]
Thank you for the comments!

> * Make sure the given completions are buffer-local, right now I'm getting TeX-PDF-mode "" while in an Elisp buffer.

I am not sure what should be done for it.
I do not use `auctex`, just installed. `TeX-PDF-mode` seems enabled in Elisp buffer, doesn't it?

> * Get rid of the prefix/non-prefix arg and instead rely on input for enabling/disabling. Like counsel-package does it.

I will change to use `+ ` and `- ` to represent enabled and disabled minor mode.

**Comment by iquiw** [comment]
Updated for the 2nd point.

![](https://raw.githubusercontent.com/iquiw/counsel-minor/master/images/plusminus.png)

**Comment by abo-abo** [comment]
Looks good. Please PR.

**Comment by iquiw** [comment]
Closed by #2000
