### ISSUE TITLE
counsel-grep-or-swiper and which-function-mode

### ISSUE THREAD

**Issue by ramestica** [abo-abo/swiper#1989]
Hi,

when stepping through the candidates in the swiper buffer then the the highlighted line in the file buffer will move accordingly, follwoing each candidate. But the which-func-format entry in my mode-line will not update reflecting the function at point while searching across the buffer.

Is there a way to make which-function-mode to update everytime the highlighted line has moved?

Thanks,
 Rodrigo

**Comment by otadmor** [comment]
The update function of which-function-mode should be executed on the update function.
see this as example:
https://github.com/otadmor/emacs-conf/commit/64267246162cdec885e4a813c96d78447e40fc69

**Comment by abo-abo** [comment]
You can use advice:

```elisp
(defun swiper-which-function-update ()
  (with-ivy-window
    (which-func-update)))

(advice-add 'swiper--update-input-ivy :after #'swiper-which-function-update)
```

**Comment by ramestica** [comment]
I tried the advice approach and that works well. Thanks for that.

@otadmor, I looked into your 'swiper--update-input-ivy' example and I think that the advice way or your explicit modification of the function do the same. I prefer the advice approach because I can restrict the change to my emacs configuration file alone.

Many thanks.

**Comment by otadmor** [comment]
Old versions of which-func-update are updating the function name for all of the windows. You might want to consider using which-func-update-1 to update only the ivy-window.
