### ISSUE TITLE
Error in counsel-dired-jump

### ISSUE THREAD

**Issue by seagle0128** [abo-abo/swiper#1990]
On macOS Mojave, I got this error while  using `counsel-dired-jump` with GNU Emacs 26.1.

```shell
find: illegal option -- n
usage: find [-H | -L | -P] [-EXdsx] [-f path] path ... [expression]
       find [-H | -L | -P] [-EXdsx] -f path [path ...] [expression]
```

![image](https://user-images.githubusercontent.com/140797/55252612-4b14d180-528e-11e9-8154-55def5bed201.png)

`find -name dir` returns the same error, but `find . -name dir` works fine.

**Comment by manuel-uberti** [comment]
I am not able to reproduce this. Have you tried from `emacs -Q`?

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by seagle0128** [comment]
It does work well, Thanks you!
