### ISSUE TITLE
ivy-switch-buffer has behavior not like with built-in switch-buffer

### ISSUE THREAD

**Issue by TxGVNN** [abo-abo/swiper#1991]
Hi Oleh Krehel,

The first, a big thank to the great package.

I'm using `perspective.el` to manage my workspaces. Did you know that package?
And I discovered that `ivy-switch-buffer` behave differently with builtin `switch-buffer`.
The builtin `switch-buffer` will lists all buffers in the current workspace, and  `ivy-switch-buffer` lists all of buffers in all of the workspaces. `ibuffer` also provides this feature.

I think `ivy-switch-buffer` should behave as builtin `switch-buffer` will be better for people to use  `perspective.el` as me. I used helm, it has `helm-buffers-list` that behave as builtin `switch-buffer`.

Hope you can have a look and consider this issue. Thank you again.

**Comment by TxGVNN** [comment]
I already have overridden ivy-switch-buffer to work with perspective.

`(ivy-read "Switch to buffer: " (remove nil (mapcar 'buffer-name (persp-buffers (persp-curr))))`

But, I'm looking for the right way, ivy install to switch-buffer, so it shouldn't change the purpose of built-in switch-buffer.
Because not only `perspective` package use `switch-buffer`, any package can use `switch-buffer`. We cannot require they provide the compatible-ivy version.

I saw the problem is ivy-switch-buffer is using `internal-complete-buffer` to list buffer. It should be related to `internal-complete-buffer-except`. I still don't know how to fix it yet :P

**Comment by abo-abo** [comment]
`perspective.el` directly advises `switch-to-buffer` in order to work:

> (defadvice switch-to-buffer (after persp-add-buffer-adv)

If you want it to work with `ivy-switch-buffer`, add a similar advice to your config. No change is needed in `ivy.el`.

**Comment by TxGVNN** [comment]
Thank you very much, you gave me the right direction. Now, I know more about advice, the advices won't affect the function was remapped.

**Comment by TxGVNN** [comment]
Hi @abo-abo, could you help me to config ivy with perspective.el
I updated `(defadvice switch-to-buffer (after persp-add-buffer-adv)...` by change to `ivy-switch-buffer`, but it didn't work.
