### ISSUE TITLE
counsel-git in wrong directory

### ISSUE THREAD

**Issue by stardiviner** [abo-abo/swiper#1992]
After upgrade, I found `counsel-git` does not pass correct default-directory anymore. The wrong result is `/home/stardiviner/.emacs.d/init/Emacs/init/programming/project/`. But it supposed to be `/home/stardiviner/.emacs.d/init/programming/project/`. From the result, I can see that `counsel-git` use current buffer directory as default-directory instead of Git project root.

Then I dive into source code of `counsel-git`. The function `counsel-git-action`'s code line `(ivy-state-directory ivy-last)` return wrong. I can't debug deeper.

**Comment by CeleritasCelery** [comment]
This is fixed with 05763aed5dc6b1264a318eb69c14da1d54f172ba

**Comment by stardiviner** [comment]
Confirmed fixed. Thanks.
