### ISSUE TITLE
counsel-dired

### ISSUE THREAD

**Issue by seagle0128** [abo-abo/swiper#1993]
Maybe I was missing something. I am just wondering why there is no implementation for `dired`. It's easy to implement, but I don't know if there is any side-effects or other issues?

If NO, I'd happy to make a PR.

```elisp
(defun counsel-dired (&optional initial-input)
  "Forward to `dired'.
When INITIAL-INPUT is non-nil, use it in the minibuffer during completion."
  (interactive)
  (ivy-read "Dired (directory): " #'read-file-name-internal
            :matcher #'counsel--find-file-matcher
            :initial-input initial-input
            :action (lambda (d) (dired (expand-file-name d)))
            :preselect (counsel--preselect-file)
            :require-match 'confirm-after-completion
            :history 'file-name-history
            :keymap counsel-find-file-map
            :caller 'counsel-dired))
```

**Comment by jixiuf** [comment]
try https://github.com/jixiuf/ivy-dired-history
it is integrated with `dired` `dired-do-copy` and `dired-do-rename`. when you press C (copy) or R (rename) , it  allow users to select a directory from the recent dired history .

**Comment by seagle0128** [comment]
@jixiuf Thank you! But I don't think they have the same purpose.

**Comment by CeleritasCelery** [comment]
rather then creating a new ivy function, why not just add the dired actions to the `counsel-find-file` action list.

**Comment by seagle0128** [comment]
@CeleritasCelery that's fine. But how to remap `C-x d`?

**Comment by CeleritasCelery** [comment]
Are you asking how to map `counsel-find-file` to `C-x d`?

**Comment by seagle0128** [comment]
@CeleritasCelery `find-file` is different from `dired`, right?

**Comment by CeleritasCelery** [comment]
Right, but if you navigate to a directory it opens it in dired. So seems to serve the same purpose. Unless I misunderstood something.

**Comment by seagle0128** [comment]
@CeleritasCelery Yes, for directory `.`, `..` they have the same functionality. But for others, they are different. You should think about it: why vanilla Emacs has `find-file` and `dired`?

**Comment by abo-abo** [comment]
I think it might be useful to have it. Please PR.
