### ISSUE TITLE
Is `counsel-ag` supposed to simply display matches and nothing else?

### ISSUE THREAD

**Issue by mrbig033** [abo-abo/swiper#1996]
#### Runtime Environment

- MX Linux 18
- GNU Emacs 27.0.50
- counsel-20190329.920

#### Question

I'm confused about this command. Is it possible for it to automatically take me to the file/line of the match at all?

**Comment by CeleritasCelery** [comment]
if you use hit RET it will take you to the file and line. If you are having an issue with that, you will need to add more detail so others can reproduce.

**Comment by abo-abo** [comment]
You can do so by using <kbd>C-M-n</kbd> in place of <kbd>C-n</kbd>. Also with <kbd>C-o cjjj</kbd>.

**Comment by mrbig033** [comment]
I'm really sorry, I had added `--group` instead of `--nogroup` to `counsel-ag-base-command`. Changing it back fixed it, now it works in the intended way @CeleritasCelery referred to. Totally my fault.

**Comment by abo-abo** [comment]
No problem.
