### ISSUE TITLE
odd behavior with (swiper initial-pattern) 

### ISSUE THREAD

**Issue by zhaojiangbin** [abo-abo/swiper#20]
It's hard to describe so I am giving steps to reproduce:

* Add following lines in the scratch buffer. Notice the empty line. It is important:
```
foo 1

foo 2
foo 3
foo 4
foo 5
```
* Move point to "foo 2", then evaluate `(swiper "foo")`.
* Note how "foo 3" is highlighted as the current match.
* Insert one more empty line in between "foo 1" and "foo 2":
```
foo 1


foo 2
foo 3
foo 4
foo 5
```
* Move point to "foo 2" again and eval `(swiper "foo")`.
* Note that now "foo 4" is highlighted as the current match.
* Insert an empty line between "foo 2" and "foo 3", and add "foo 6" and "foo 7" following "foo 5":
```
foo 1


foo 2

foo 3
foo 4
foo 5
foo 6
foo 7
```
* Move point to "foo 3" then evaluate `(swiper "foo")`.
* Note "foo 6" now becomes the current match.
* If all the empty lines are removed, evaluating `(swiper "foo")` in any line just selects the current line as the current match.

So it appears that the number of empty lines prior to the original point decides how swiper selects the current match.

**Comment by abo-abo** [comment]
Thanks a lot for such a detailed and well written issue!
