### ISSUE TITLE
invalid-regexp error by counsel-yank-pop

### ISSUE THREAD

**Issue by iquiw** [abo-abo/swiper#2002]
Starting from `make plain`,

1. Eval the following.

   ```emacs-lisp
   (kill-new "[")
   (kill-new "a")
   (counsel-yank-pop)
   ```
2. Type any 2 chars (e.g. <kbd>x</kbd><kbd>x</kbd>)

Error is thrown from [here](https://github.com/abo-abo/swiper/blob/1e38ed4897381b575375ed8041b09cb8b81f98f2/ivy.el#L3269).

In addition to that, there is another invalid regexp error by the following.
I am not sure whether this one is bug or not.

```emacs-lisp
(ivy-read "test: " '("a") :preselect "[")
```

**Comment by basil-conto** [comment]
> I am not sure whether this one is bug or not.

It is definitely a bug, since Ivy is trying to use an arbitrary string as a regexp. #2004 should fix this and also document the behaviour of `:preselect` properly.

**Comment by iquiw** [comment]
@basil-conto Thanks!
