### ISSUE TITLE
Calling ivy-occur from counsel-rg doesn't carry over extra-rg-args

### ISSUE THREAD

**Issue by jonEbird** [abo-abo/swiper#2003]
I'm calling `counsel-rg` within another function and am passing `extra-rg-args` as "-S -U" which is working but as soon as I want to send the results to an occur buffer via `C-c C-o`, it seems the options are lost. 

I say this because I'll get a complaint about `\n` not being allowed which is why I added the `-U` in the extra args. I haven't dug in much yet but I suspect options aren't being passed along.

Here is the full function I've got wired up:
```lisp
(defun jsm/projectile-counsel-rg ()
  "Run counsel-rg within projectile root while ignoring git submodule paths."
  (interactive)
  (let ((default-directory (projectile-project-root))
        (ignore-cmd "git config --file .gitmodules --get-regexp path | awk '{ print $2 }' > .ignore"))
    (shell-command ignore-cmd nil nil)
    (counsel-rg (thing-at-point 'symbol) default-directory "-S -U")))
```
When running and using a pattern like `line one\n.*on second line` it works but again once I try to pop it into an `ivy-occur` buffer I get the error message from `rg`:
> ./the literal '"\n"' is not allowed in a regex

**Comment by abo-abo** [comment]
Can't reproduce. I verified that `"-S -U"` are passed `counsel-grep-like-occur` and it works as expected.

Please try to reproduce with `emacs -Q`.

**Comment by jonEbird** [comment]
Sorry, I was on an older swiper release and older projectile too... after updating both I too can not reproduce. Sorry for the noise.
