### ISSUE TITLE
Counsel-M-x and  ivy-display-function

### ISSUE THREAD

**Issue by tumashu** [abo-abo/swiper#2008]
Any way can let the below command work well with counsel-M-x?
```
(defun test()
  (interactive)
  (setq ivy-display-function #'ivy-posframe-display-at-frame-center)
```

**Comment by abo-abo** [comment]
What exactly are you trying to achieve? Why not just use `ivy-display-functions-alist`?

```elisp
(setq ivy-display-functions-alist
      '((ivy-completion-in-region . ivy-display-function-overlay)
        (t . ivy-posframe-display-at-frame-center)))
```

**Comment by tumashu** [comment]
I just want to write a command to config ivy-posframe,  setq ivy-display-function is the simpliest way :-)

**Comment by abo-abo** [comment]
This is enough for me to configure it:

```elisp
(require 'ivy-posframe)
(setq ivy-display-function #'ivy-posframe-display-at-window-center)
```

**Comment by tumashu** [comment]
I will use ivy-display-functions-alist instead, thanks for help:-)
