### ISSUE TITLE
counsel-org-tag: tag list candidate population is a bit slow - is caching possible?

### ISSUE THREAD

**Issue by srustamo** [abo-abo/swiper#201]
Is caching tag candidates possible for faster minibuffer candidate population?

`counsel-org-tag` does an excellent job. However, it is a bit slow. I suppose this depends on the number of tags and if the `org-complete-tags-always-offer-all-agenda-tags` is set to `t`.

I'm not sure if `counsel-org-tag` re-uses org provided functions related to tagging. If yes, then I guess nothing much can be done.

**Comment by abo-abo** [comment]
Yes it just uses the org stuff. And org can be slow if you have a lot of files. So a solution is either to reduce the number of files or get an SSD.

**Comment by srustamo** [comment]
`swiper` seems to already provide means to copy the candidate list with `M-w`, a very handy function. 
The tags list doesn't change often, so copying the candidates list into a temp file, or better yet provide an option to save such file, would address the speed. 
And Ctrl-P (vim) style cache update function would take care of those rare new tags or deleted tags.

**Comment by abo-abo** [comment]
`counsel-org-tag` is slow because `org-agenda-set-tags` is slow. If caching is implemented for `org-agenda-set-tags`, I'd use it in `counsel-org-tag`.  Bring it up with Org's mailing list if you want.
