### ISSUE TITLE
`counsel-find-file` can't open file which filename contains `$`

### ISSUE THREAD

**Issue by cireu** [abo-abo/swiper#2012]
Reproduce recipe
1. `echo "I am here." > "$" && make plain`
2. <kbd>C-x C-f</kbd>

find `$$` instead of `$`

ivy ver. https://github.com/abo-abo/swiper/commit/5458f93acf1aa8e908eb2690b96058e53bbad01e
Emacs 26.1

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by cireu** [comment]
Thanks for your work

**Comment by basil-conto** [comment]
See also #3060.
