### ISSUE TITLE
ivy-ignore-buffers no longer respected?

### ISSUE THREAD

**Issue by dieggsy** [abo-abo/swiper#2013]
With the repo checked out at https://github.com/abo-abo/swiper/commit/7e735808e966d70340b5a2cef0430f913151d9b6,  if I run `make-plain`, and evaluate 

```emacs-lisp
(setq ivy-ignore-buffers "\\*scratch\\*")
```
then `C-x b`, `*scratch*` still appears in the list.

**Comment by abo-abo** [comment]
Thanks. It works again, with this setting:

```elisp
(setq ivy-ignore-buffers '("\\` "
                           "\\`\\*scratch\\*"))
```

**Comment by dieggsy** [comment]
Thanks! unfortunately this seems to have caused a different problem. I've opened a new issue for that.
