### ISSUE TITLE
got problems with swiper-isearch

### ISSUE THREAD

**Issue by pengpengxp** [abo-abo/swiper#2014]
1. swiper-isearch slow when use or regexp:
for example, I want to search foo and bar both. I input foo\|bar. When I type |, sometimes emacs just stuck! While, swiper works good for this.

2. ivy--regex-ignore-order does not work for swiper-isearch, I add such thing in my config:
```
(setq ivy-re-builders-alist
      '((ivy-switch-buffer . ivy--regex-ignore-order)
        (swiper-isearch . ivy--regex-ignore-order)
        (t . re-builder-pinyin)))
```
ignore order does not work .

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by pengpengxp** [comment]
Thanks.

Problem 1 is solved.

Problem 2 is still there. When I set swiper-isearch to ivy--regex-ignore-order match. It doesn't work.
Even in normal ordered input, it match something that should not belongs to.

**Comment by abo-abo** [comment]
`swiper-isearch` will not work with `ivy--regex-ignore-order`. You can re-write `swiper-isearch-function` if you really want it to work.
