### ISSUE TITLE
"!" in swiper-isearch make emacs stuck

### ISSUE THREAD

**Issue by pengpengxp** [abo-abo/swiper#2017]
When I use swiper-isearch to exclude something in the buffer using char "!", emacs just stuck.

**Comment by abo-abo** [comment]
Excluding something doesn't make sense with `swiper-isearch`, since it's not line based.

**Comment by pengpengxp** [comment]
Got it. Thank you very much. I'll close this issue.

**Comment by basil-conto** [comment]
> Excluding something doesn't make sense with `swiper-isearch`, since it's not line based.

Sure, but that doesn't mean it should hang, if that's what's actually happening.

**Comment by abo-abo** [comment]
@basil-conto I agree, this should be fixed.
