### ISSUE TITLE
swiper-isearch starts at wrong hit when multiple hits on line

### ISSUE THREAD

**Issue by Lenbok** [abo-abo/swiper#2025]
I just started to use `swiper-isearch` and it's very nice. One minor problem I noticed is that when I invoke `swiper-isearch` starting on a line containing two occurrences of the search term, swiper initially matches the first occurrence of the match on the line, even if the initial invocation position was to the right of that first occurrence.

In my case, I had actually initiated the search from the second occurrence via `swiper-isearch` followed by `ivy-yank-word`, which made it even more jarring as I went to do `ivy-yank-word` a second time to further refine the search, but it pulled in the word following the first occurrence on the line, not the one I started from!

(In fact it has nothing to do with whether there are multiple occurrences on the line, `swiper-isearch` should just start from the *next* match if the initial invocation position is to the right of the first match on the line)

**Comment by flatwhatson** [comment]
I have included a fix in #2029

**Comment by abo-abo** [comment]
OK, took me some minutes to figure out the reason why it works the way it does right now:

The original logic:

```elisp
(setq swiper--isearch-point-history
        (list
         (cons "" (point))))
```

The current logic:

```elisp
(setq swiper--isearch-point-history
        (list
         (cons "" (if executing-kbd-macro
                      (point)
                    (line-beginning-position)))))
```

Suppose we revert to the original logic. Move the point here:

```
(def|un swiper-isearch-action (x)

...

(defun swiper-isearch ...)
```

Press <kbd>C-s M-n</kbd> to search for symbol-at-point. The point will not stay at the current `defun` as expected, but will move to the next one.  This is correct, but not convenient.

Maybe a better solution would be to modify only the <kbd>M-n</kbd> logic, and keep the original `swiper--isearch-point-history` logic.

**Comment by abo-abo** [comment]
Thanks, please test.
