### ISSUE TITLE
Hooks for previews.

### ISSUE THREAD

**Issue by lambdadelta34** [abo-abo/swiper#2028]
Hi, I don't know much about emacs ecosystem yet, but I'd like to customize counsel search to show me some similar to dired/ranger file preview. I don't know where to start or what way would be right, but though of some after hooks when listing through occurrences. Is this possible?

**Comment by basil-conto** [comment]
Counsel (via Ivy) is aimed at being used in the minibuffer, so I'd be pleasantly surprised if it worked well in `special-mode` buffers. That said, there's `ivy-display-function`, `ivy-display-functions-alist`, and `ivy-display-functions-props` for customising how completion is displayed.

**Comment by lambdadelta34** [comment]
@basil-conto Thank you for suggestion, but that is not the case. I want to preview file when visiting candidates. It is such a helpful thing, when you want to know exactly what match to visit.
Here is image of something i'd like to have, but in vim.
![preview](https://user-images.githubusercontent.com/12697325/56372706-2d40e980-6208-11e9-8898-98ee3aa54399.png)

**Comment by basil-conto** [comment]
If I've understood you correctly, this feature already exists, and is called `ivy-calling`. Please read through the discussion in #2020, where this came up recently.

**Comment by lambdadelta34** [comment]
Oh, yes. Thank you, missed that from the doc. I used another functions without `and-call` postfix.
