### ISSUE TITLE
Sorting for Info-complete-menu-item

### ISSUE THREAD

**Issue by dieggsy** [abo-abo/swiper#2032]
I'm trying to get 'natural buffer order' sorting for e.g. `Info-menu` and `Info-goto-node` - as far as I'm aware, this would be controlled by the entry for `Info-complete-menu-item` in `ivy-sort-functions-alist`. However, when I add `(Info-complete-menu-item)` to `ivy-sort-functions-alist`, the list appears to be in reverse order. What's the proper way to go about this?

**Comment by basil-conto** [comment]
> However, when I add (`Info-complete-menu-item`) to `ivy-sort-functions-alist`, the list appears to be in reverse order. What's the proper way to go about this?

If no sorting results in the reverse order, then you want the opposite - reverse sorting:

```el
(defun my-sort-reverse (_x _y)
  "Predicate that the order of X and Y should be swapped."
  t)

(with-eval-after-load 'ivy
  (setf (alist-get #'Info-complete-menu-item ivy-sort-functions-alist)
        #'my-sort-reverse))
```

Of course, even better would be to change `Info-complete-menu-item` to return candidates in their natural order.

**Comment by dieggsy** [comment]
Sorry for the late reply and thanks - I think this solves my issue.
