### ISSUE TITLE
counsel command for registers

### ISSUE THREAD

**Issue by mnewt** [abo-abo/swiper#2037]
Are you interested in adding something like this?

```emacs-lisp
(defvar counsel-register-history nil
  "History for `counsel-register'.")

(defun counsel-register-action (s)
  "Default action for `counsel-register'.

Do what I mean for each type of register."
  (let* ((k (string-to-char s))
         (v (get-register k)))
    (if (or (stringp v) (numberp v))
        (insert (format "%s" v))
      (jump-to-register k))))

(defun counsel-register ()
  "Interactively choose a register and perform a default action
on it."
  (interactive)
  (ivy-read "Register: "
            (cl-loop for (k . v) in register-alist
                     collect (concat (key-description (list k))
                                     " => "
                                     (if (or (stringp v) (numberp v))
                                         (format "%s" v)
                                       (format "[%s] %s"
                                               (symbol-name (car v))
                                               (cdr v)))))
            :preselect 0
            :history 'counsel-register-history
            :action #'counsel-register-action))
```

If so, do whatever you like with that code or I can submit a pull request.

**Comment by dunkarooftop** [comment]
There is 'counsel-yank-pop' and 'counsel-evil-register' already, it serve as same function is't it?

**Comment by basil-conto** [comment]
> There is 'counsel-yank-pop' and 'counsel-evil-register' already, it serve as same function is't it?

`counsel-yank-pop` is not related to registers.

**Comment by mnewt** [comment]
> There is 'counsel-yank-pop' and 'counsel-evil-register' already, it serve as same function is't it?
`counsel-evil-register` requires `evil` and also it only lists a subset of registers.

**Comment by abo-abo** [comment]
@dunkarooftop Looks good, please PR. I would replace `" => "` with `": "` so that it's easy to select e.g. "a:" or "b:".

Do you have an Emacs CA?

**Comment by mnewt** [comment]
Closing in favor of the PR. Yes, the FSF have my Emacs CA on file.
