### ISSUE TITLE
swiper-isearch does not honor ivy-case-fold-search-default

### ISSUE THREAD

**Issue by jeberger** [abo-abo/swiper#2039]
I have `ivy-case-fold-search-default` set to the default `auto` value. When I call `swiper`, it honors the case fold mode: it allows mixed case search if I type in lower case, but it enforces strict case if I have one upper-case character. However `swiper-isearch` always allows mixed case. Ie. searching for `This` finds `this`.

Tried with `emacs -Q`.

Emacs 26.1
Ivy 20190412.840
Swiper 20190412.1718

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by jeberger** [comment]
Verified: works with swiper 20190507.1413.
Thanks for the fix.
