### ISSUE TITLE
multiple cursors don't work with counsel-M-x

### ISSUE THREAD

**Issue by alex-glv** [abo-abo/swiper#204]
Using multiple-cursors package, I want to set cursors for region using mc/mark-all-like-this
I select region, press M-x, choose mc/mark-all-like-this.

Expected behavior:
All occurrences of the region have cursors placed at them.

Actual behavior:
Buffer contents is replaced with mc/mark-all-like-this.
When undoing, old content is reversed, error buffer pops up with a lot of errors like:
```Warning (emacs): Encountered (#<marker in no buffer> . -5453) entry in undo list with no matching (TEXT . POS) entry```

When mc/mark-all-like this is bound to a key combo, the behavior is correct. When I call smex first and then choose the command, the behavior is correct as well, which makes me think there's a bug in counsel-M-x

Hope that's enough information.

**Comment by abo-abo** [comment]
That's a multiple-cursors config issue. Make sure `ivy-done` isn't in the `mc/cmds-to-run-for-all` list.

**Comment by alex-glv** [comment]
... yes, yes.
Removed it, it works. Thanks for the tip!
