### ISSUE TITLE
Hydra key behaviors do not match the Hydra menu in Spacemacs.

### ISSUE THREAD

**Issue by wolfv6** [abo-abo/swiper#2041]
Hydra menu appears as expected on Spacemacs:
    see screen shot at https://i.stack.imgur.com/uRqpA.png
But some of the Emacs \*help\* hydra-ivy/body functions and Hydra key behaviors do not match the Hydra menu.  Four examples follow.

1) Hydra menu says:

        [f] case-fold: auto

    Pressing 'f' toggles between 'nil' and 'auto'.
    In the help, hydra-ivy/body says:

        "f": ‘ivy-alt-done &optional’
        Exit the minibuffer with the selected candidate.

2) Hydra menu says:

        [TAB] alt done

    Pressing TAB opens \*ivy-occur counsel-find-file ""\*<2>:
        see screen shot at https://i.stack.imgur.com/jIzon.png
    In the help, hydra-ivy/body does not mention "TAB".

3) Hydra menu says:

        [c] & cont

    Pressing 'c' opens \*ivy-occur counsel-find-file ""\*<2>.
    In the help, hydra-ivy/body says:

        "c":    ‘ivy-toggle-calling’

4) Hydra menu says:

        [o]  occur

    In the help, hydra-ivy/body says:

        "o": ‘keyboard-escape-quit’

    Pressing 'o' opens \*ivy-occur counsel-find-file ""\*<2>

This code at the end of my .spacemacs file might be relevant:
```
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(ivy-preferred-re-builders
   (quote
    ((ivy--regex-plus . "ivy")
     (ivy--regex-ignore-order . "order"))))
```

Related links:
https://emacs.stackexchange.com/questions/49101/how-to-select-a-rotating-hydra-option
https://github.com/abo-abo/swiper/issues/1213

**Comment by basil-conto** [comment]
Is this not a bug with how Spacemacs defines the hydra? Because the one in the screenshot is not the default hydra.

**Comment by wolfv6** [comment]
I submitted the issue at https://github.com/syl20bnr/spacemacs/issues/12231
