### ISSUE TITLE
When `counsel-yank-pop` treats multiline text in kill-ring, counsel buffer is expanded but not shrinked.

### ISSUE THREAD

**Issue by yonta** [abo-abo/swiper#2044]
# how to

1. killing multiline texts.
1. killing one line texts.
1. call a `counsel-yank-pop`. (figure 1)
1. move the cursor to muliline killing texts. (figure 2)
    - expanding mini buffer.
1. return the cursor to one line killing textx. (figure 3)
    - not shrinking mini buffer, and remaining empty line.

- figure 1
![image](https://user-images.githubusercontent.com/849256/56865739-60575a00-6a0c-11e9-8ffb-ab1f2a061f3a.png)
- figure 2
![image](https://user-images.githubusercontent.com/849256/56865745-6c431c00-6a0c-11e9-9fee-43a0f01f8614.png)
- figure 3
![image](https://user-images.githubusercontent.com/849256/56865747-736a2a00-6a0c-11e9-92ea-470540161ad5.png)

**Comment by basil-conto** [comment]
I think this is a duplicate of #649, which is a known problem with `ivy.el` and has nothing to do with `counsel-yank-pop`. See also #1807, #1809, and #1811 for some more precedent.

**Comment by yonta** [comment]
Oh, I'm sorry for making duplicate issue.
Thanks your guide!
