### ISSUE TITLE
counsel-rg over the list files

### ISSUE THREAD

**Issue by Pfedj** [abo-abo/swiper#2045]
Hello, I would like to use `counsel-rg` for  interactive search in my personal knowledge base, it is a plain text in single directory. Suppose I have tags/meta-information with the help of wich I filter my data preliminarily for narrowing the search range. Finally I have list of the files `note-list` in directory. I would like to use this list for interactive search with `counsel-rg`. 

What is the best way to do it? 

UPDATE: 
It seem's to solved. I have concated my `note-list` with  `counsel-rg-base-command`:
```        (setq counsel-rg-base-command  
             (concat "rg -S --no-heading --line-number --color never %s ."
               (replace-regexp-in-string "\n" " " note-list)))

**Comment by abo-abo** [comment]
I suggest using `shell-quote-argument`, but otherwise it's a good solution. Closing.
