### ISSUE TITLE
C-s with word under cursor

### ISSUE THREAD

**Issue by codesuki** [abo-abo/swiper#2047]
Is there a way to do a swiper search starting with the word under the cursor? 
I searched in the issues but couldn't find anything.

Behavior would be like `M-s .`. But that doesn't start swiper for me.

**Comment by basil-conto** [comment]
Try invoking `swiper`, followed by <kbd>M-n</kbd> (`ivy-next-history-element`).

**Comment by basil-conto** [comment]
If you want more fine-grained control, you can always call `next-history-element` directly, or call `swiper` with a custom `initial-input` argument, such as the result of a call to `word-at-point`.

**Comment by codesuki** [comment]
> Try invoking `swiper`, followed by M-n (`ivy-next-history-element`).

That worked well! I didn't know about M-n :)
Thank you.
