### ISSUE TITLE
boxquote doesn't work with ivy-mode

### ISSUE THREAD

**Issue by tsdh** [abo-abo/swiper#205]
`boxquote.el`¹ provides many commands to put some text into a nice ASCII art box with a title.  For example, there is `boxquote-describe-function` which queries for a function name and then inserts a box with the function's docstring and a title showing `C-h f <the-function>`.  There's also `boxquote-describe-variable` for boxquoting variable descriptions.

However, the title generation doesn't work for ivy-mode users because `boxquote.el` assumes that the name of the function or variable being boxquoted is the `car` of `minibuffer-history` but ivy doesn't populate that.

So could ivy add the chosen candidates to `minibuffer-history` in addition to `ivy-history`?

¹ http://www.davep.org/emacs/boxquote.el

**Comment by abo-abo** [comment]
I don't think using `minibuffer-history` is a good idea, according to its doc:

> Default minibuffer history list.
> This is used for all minibuffer input
> except when an alternate history list is specified.

I think that `boxquote` should use this standard code inside `describe-function`, instead of re-using it:

    (setq val (completing-read (if fn
				    (format "Describe function (default %s): " fn)
				  "Describe function: ")
				obarray 'fboundp t nil nil
				(and fn (symbol-name fn))))

Here `val` would be the car of `minibuffer-history` if `describe-function` had no history.  Since `boxquote` is [here](https://github.com/davep/boxquote.el), maybe it's possible to update its code.

**Comment by tsdh** [comment]
`boxquote` calls `describe-*` using `call-interactively` so that it is also added to `command-history`. I think this is intentional, and you cannot call a command interactively and still provide arguments which you've read in previously.

Well, but I think I agree that it would be better to change `boxquote` than `ivy`.  Adding every completion result in `minibuffer-history` just for `boxquote`s sake would be a bit awkward.

**Comment by abo-abo** [comment]
Boxquote is a pretty old code, maybe `completing-read` wasn't available at that time. Nowadays, `completing-read` is the recommended way to handle these situations, since any new completion system will automatically work in that case.

**Comment by tsdh** [comment]
Well, yes.  But still you couldn't call `describe-*` interactively and provide the function/variable at the same time.  But AFAICS, the `describe-*` functions always return the description text, too (on both Emacs and XEmacs), so simply taking the first word of that string would also do the trick (although it is only quoted in some emacs versions).

As a workaround for the time being, I use these two advices:

```elisp
(advice-add 'describe-variable :after (lambda (sym)
					"Add SYM to minibuffer-history."
					(let ((sn (symbol-name sym)))
					  (unless (string= sn (car minibuffer-history))
					    (push sn minibuffer-history)))))
(advice-add 'describe-function :after (lambda (sym)
					"Add SYM to minibuffer-history."
					(let ((sn (symbol-name sym)))
					  (unless (string= sn (car minibuffer-history))
					    (push sn minibuffer-history)))))
```

**Comment by tsdh** [comment]
Ok, I've added a boxquote issue right now: https://github.com/davep/boxquote.el/issues/3
