### ISSUE TITLE
ivy-display-function-overlay doesn't work with counsel-company

### ISSUE THREAD

**Issue by AmaiKinono** [abo-abo/swiper#2051]
I did this:

``` emacs-lisp
(add-to-list 'ivy-display-functions-alist '(counsel-company . ivy-display-function-overlay))
```

It doesn't work. The candidates are still displayed in the minibuffer. But it works if I replace `counsel-company` with `counsel-M-x` or `counsel-find-file`. So I assume the problem is with `counsel-company`.

**Comment by abo-abo** [comment]
Thanks.
