### ISSUE TITLE
Doing M-w inside C-x C-f copies all lines instead of selected one

### ISSUE THREAD

**Issue by codesuki** [abo-abo/swiper#2052]
Is this expected behavior? 
I guess I could narrow down until only one item is left and copy then.

The docs say
```
M-w (ivy-kill-ring-save)
Copies selected candidates to the kill ring.

Copies the region if the region is active.
```

I don't know how to make a region inside the minibuffer so I am probably not doing that. Not sure though. 😅

**Comment by basil-conto** [comment]
> Doing M-w inside C-x C-f copies all lines instead of selected one

> Is this expected behavior?

Yes. When the docstring says "selected candidates", it means all current candidates. If it is confusing, the docstring could be rephrased to make that clearer.

> I don't know how to make a region inside the minibuffer

It works the same way as in normal buffers, it's just that several of the usual key bindings aren't available by default. One standard key binding that survives during Ivy completion is <kbd>C-x</kbd><kbd>h</kbd> (`mark-whole-buffer`). This will mark all currently visible candidates. You can play around with other mark commands and their bindings in the minibuffer, and even write your own marking command.

**Comment by basil-conto** [comment]
Here is how you could rebind <kbd>M-w</kbd> to kill the currently selected candidate instead of all candidates, for example:

```el
(defun my-ivy-kill-current ()
  "Save current Ivy candidate to the `kill-ring'."
  (interactive)
  (kill-new (ivy-state-current ivy-last)))

(with-eval-after-load 'ivy
  (define-key ivy-minibuffer-map (kbd "M-w") #'my-ivy-kill-current))
```
```

**Comment by codesuki** [comment]
Thanks for the trick! So from your answer I conclude that the behavior is normal.
I'll add your snippet :) Super useful for doing things like `import "<C-p f><M-w><C-y>"`

**Comment by basil-conto** [comment]
> So from your answer I conclude that the behavior is normal.

Thanks, does that mean this issue can be closed?
