### ISSUE TITLE
swiper-mc not working with swiper-isearch

### ISSUE THREAD

**Issue by Ergus** [abo-abo/swiper#2058]
Hi I am trying to set the cursors with swiper-mc in terminal mode and it is not working. 
1) The bind C-7 in my systems sends C-_ which is undo.
2) After rebinding it to something else it works fine from swiper.
But if I am in swiper-isearch it doesn't work, I just get a message in the minibuffer with the message: Lisp expresion:

**Comment by basil-conto** [comment]
> The bind C-7

Have you tried <kbd>M-7</kbd> or <kbd>C-u</kbd><kbd>7</kbd>?

**Comment by Ergus** [comment]
Yes, they don't work for me either. I tried both actually but the command is bind to C-7 itself.

**Comment by abo-abo** [comment]
Thanks, please test.

The default binding for `swiper-mc` works fine in graphical Emacs, I prefer not to change it. But maybe we could bind it to something like <kbd>C-c C-m</kbd>.
