### ISSUE TITLE
Direct switching one completion to another

### ISSUE THREAD

**Issue by umkiwon** [abo-abo/swiper#206]
Thank you for your cool tools for emacs! I've just tried ivy-mode; and it is really convenient.

One functionality I'm really missing is to switch from one completion to another; for example, in ido-mode we can call switch-to-buffer using C-x b and then switch to find-file using C-f. We can further turn off the completion in find-file using one more C-f.

Does ivy-mode have similar functionalities? Thanks!

**Comment by abo-abo** [comment]
It's possible, but I don't think it's that efficient (I mean canceling one command from another - <kbd>C-g</kbd> is universal). Customize your Emacs like this:

```elisp
(ivy-set-actions
 'ivy-switch-buffer
 '(
   ;; ("k"
   ;;  (lambda (x)
   ;;    (kill-buffer x)
   ;;    (ivy--reset-state ivy-last))
   ;;  "kill")
   ;; ("j"
   ;;  ivy--switch-buffer-other-window-action
   ;;  "other")
   ("f"
    (lambda (x)
      (counsel-find-file))
    "file")))
```

The other two parts are there by default, you can use them too if you like.  After <kbd>C-x b</kbd>, press <kbd>M-o f</kbd> to switch to `find-file` instead.  The other two are <kbd>M-o k</kbd> to kill the buffer, and <kbd>M-o j</kbd> to switch in other window.

**Comment by umkiwon** [comment]
Cool! I think the consistent key strokes for the same (or similar) functionalities make people to easily switch one to another. :) The middle stroke `M-o` is little bothering me because I've already gotten familiar with the ido-mode's keys. ;) Thank you very much!

**Comment by abo-abo** [comment]
Well, Ivy is consistent in a different way: <kbd>C-f</kbd> is `forward-char`, <kbd>C-w</kbd> is `kill-region` etc.

**Comment by umkiwon** [comment]
Yep, I hope Ivy becomes a part of the next Emacs release like Ido. :) Many people, then, will first get familiar with Ivy strokes. Thanks!
