### ISSUE TITLE
Use Ivy with ledger-mode?

### ISSUE THREAD

**Issue by glasser** [abo-abo/swiper#2060]
Has anybody tried to use Ivy with [ledger-mode](https://github.com/ledger/ledger-mode)? Specifically, TAB is bound to ledger-magic-tab which calls ledger-pcomplete, which seems to be hardcoded to pcomplete. Anybody figured out an easy way to make it call Ivy instead?

See also https://github.com/ledger/ledger-mode/issues/171.

**Comment by basil-conto** [comment]
> Has anybody tried to use Ivy with ledger-mode?

Yes.

> Specifically, TAB is bound to ledger-magic-tab which calls ledger-pcomplete, which seems to be hardcoded to pcomplete. Anybody figured out an easy way to make it call Ivy instead?

This is what I do:

```el
(define-advice ledger-pcomplete (:override (&rest _) my-completion-at-point)
  "Use default inline completion."
  (completion-at-point))
```

**Comment by glasser** [comment]
Hmm. Looks like that doesn't end up tying into `ledger-complete-at-point` at all, so a lot of the things I'm used to being able to complete (eg, dates) don't work? Do you have some other setting that puts that back in?

**Comment by basil-conto** [comment]
I'm not sure what you mean, can you please give an example?

**Comment by glasser** [comment]
Type `5/7` at the beginning of a line and hit TAB. I got `completion--some: Wrong type argument: sequencep, 50`.

**Comment by basil-conto** [comment]
Ah, I never use that. Perhaps it's possible to tweak the advice to make it work, but it would be more worthwhile to work on moving `ledger-mode` away from `pcomplete` to standard in-buffer completion. 

Either way, I don't think this issue should be duplicated in the issue trackers of both Ivy and `ledger-mode`. There's not much Ivy can do about this, unless you're asking for Counsel replacements for `ledger-mode` completion commands.
