### ISSUE TITLE
swiper-isearch-toggle

### ISSUE THREAD

**Issue by Ergus** [abo-abo/swiper#2061]
Hi:

I was trying to write a function to toggle between isearch and swiper-isearch. This can be added to swiper-map and to isearch-mode-map with the same binding in order to toggle between swiper and isearch.
```
(defun swiper-isearch-toggle ()
  "Invoke `swiper-isearch' -> isearch toggle."
  (interactive)
  (if isearch-mode
      (let ((query (if isearch-regexp
                       isearch-string
                     (regexp-quote isearch-string))))
        (isearch-exit)
        (swiper-isearch query))
    (ivy-exit-with-action
     (lambda (_)
       (isearch-mode t nil nil nil 'isearch-symbol-regexp)
       (unless (string= ivy-text "")
	 (isearch-yank-string ivy-text))))))
```

The only drawback I see in this implementation is that the point moves to the next candidate when toggling. But if anyone can improve this a little bit, I think it will be a good addition to swiper.

**Comment by abo-abo** [comment]
Can you describe a use case for this? `swiper-isearch` aims to be an `isearch` replacement, if something's still missing, we can add it.

**Comment by Ergus** [comment]
There is nothing missing in swiper or swiper-isearch. It is the opposite. I still use isearch sometimes because sometimes I don't want to have the ivy minibuffer opening. Or I just want to see what is in my current screen, but swiper produces some scrolling opening or closing ivy.

**Comment by Ergus** [comment]
There is nothing missing in swiper or swiper-isearch. It is the opposite. I still use isearch sometimes because sometimes I don't want to have the ivy minibuffer opening. Or I just want to see what is in my current screen, but swiper produces some scrolling opening or closing ivy.

**Comment by abo-abo** [comment]
Thanks. I fixed the point move issue. Please test.

**Comment by Ergus** [comment]
Hi Abo-abo: 
It works pretty fine for me, thanks!

Any way.
Sometimes there is a jump to a different candidate when going from isearch to swiper (sometimes there is a scroll to go there). It doesn't happen always, but it is something very frequent for me. I have not found yet how to reproduce it or a pattern for when it happens. But it you give a look it will be very nice if this small issue goes away. (in the mean time I can live with it, so I won't complain (or create an issue) to no bother you too much).

Any way, again very thanks for that.

**Comment by abo-abo** [comment]
I think the only thing where something could be broken is `(isearch-exit) (goto-char (match-beginning 0))`. Here we have to go to the beginning of the match. We assume that the match data from `isearch` is still valid. Which it is in all the times I tested.
