### ISSUE TITLE
Question: Persist search highlights

### ISSUE THREAD

**Issue by binaryplease** [abo-abo/swiper#2064]
I'll ask here, since I've looked around and coudn't find the solution:

Is it possible to keep all search matches highligted when searching in a buffer with swiper?
I'm using swiper with evil-mode. I also set in my config:
```
    (setq lazy-highlight-cleanup nil)
```
The above line works fine for the default `isearch` but not for swiper. I'd like to replace the default vim-style search (`/`) in evil-mode with swiper. This means mostly: 
- Persist the search highlights until manually cleared (e.g. with `:noh`)
- make the `n` and `N` keys work after seaching (next and previous match)

Is this possible?
Thanks for any help!

**Comment by abo-abo** [comment]
Should be easy with a bit of custom code:

```elisp
(setq lazy-highlight-cleanup nil)

(defun swiper--cleanup ()
  "Clean up the overlays."
  (interactive)
  (when (or lazy-highlight-cleanup
            (called-interactively-p 'any))
    (while swiper--overlays
      (delete-overlay (pop swiper--overlays)))
    (save-excursion
      (goto-char (point-min))
      (isearch-clean-overlays))))
```

**Comment by binaryplease** [comment]
Hi @abo-abo, thanks for the response!
This seems to work partly. The text ist marked in two ways it seems (yellow and blue here), but also some kind of blue selection appear across some lines. It's really hard do discribe, so I made a small video of how it looks. 

This is what I do in the clip:
- I ran first my normal setup with swiper. 
- Search with swiper
- Run the code you posted above
- Search again

You can see there is a difference, but something is wrong. I hope you can see what is happening, it's a bit blurry...


![peek](https://user-images.githubusercontent.com/1719781/57867264-1b4f6800-7801-11e9-88da-9e7a47e12534.gif)

**Comment by abo-abo** [comment]
Thanks, please test.

No custom code is necessary, just set `(setq lazy-highlight-cleanup nil)`. You can use <kbd>M-x</kbd> `lazy-highlight-cleanup` to clean up the overlays manually.

**Comment by binaryplease** [comment]
Ok will test it out. I've currently installed ivy via melpa, I guess I need the github-version to test it?

**Comment by abo-abo** [comment]
The github version makes it to MELPA after a few hours. But it's easier to just test the Git clone.

**Comment by kohnish** [comment]
Hey @abo-abo 

`lazy-highlight-cleanup nil` works as designed, I think highlighting all visible area, so it won't include areas hidden by the minibuffer and such.  

Any tips on somehow extending to match for every occurrence in the current buffer?  

There is a workaround for isearch which works partly, and it persists even in the second isearch call. I'm struggling to port to swiper. 
https://stackoverflow.com/questions/3779855/how-can-i-get-emacs-to-keep-my-isearch-strings-highlighted
