### ISSUE TITLE
Emacs hung by swiper-regex-replace

### ISSUE THREAD

**Issue by seagle0128** [abo-abo/swiper#2066]
- Env:
  - GNU Emacs 26.1
  - macOS Mojave
- Steps:
1. `emacs -Q`
1. Install and load `swiper`.
1. `M-x swiper` (input nothing in prompt)
1. `M-q` or `M-x swiper-regexp-replace`.
- Results:
  Emacs is hung (CPU usage is 100%).

**Comment by abo-abo** [comment]
Thanks.

**Comment by seagle0128** [comment]
Thank you for the so quick fixing!!!
