### ISSUE TITLE
ivy-switch-buffer-other-window ignores recentf

### ISSUE THREAD

**Issue by franburstall** [abo-abo/swiper#2067]
I have `(setq ivy-use-virtual-buffers t)` in my init and it has been working fine for me since forever.  However, very recently, while `ivy-switch-buffer` works as usual (currently offers 482 candidates at the start), `ivy-switch-buffer-other-window` no longer offers the buffers from recentf (so I get 27 candidates).  A regression?

**Comment by abo-abo** [comment]
Thanks, the regression should be fixed now.
