### ISSUE TITLE
Support marking multiple files and opening multiple files in ivy-hydra.

### ISSUE THREAD

**Issue by jayhanjaelee** [abo-abo/swiper#2068]
In `ivy-hydra`, I makred multiple files I want to open and opened the files by pressing `r o` which means opening buffer in other window.

As a result,  It's not working because emacs recognize file name as '>' marking flag followed. 

For example, I open `Makefile` file then emacs open `>Makefile` NOT `Makefile` 

I want it to be worked correctly So I open this issue.
Additionally, It's working in `counsel-projectile-find-file` But It's not working in `counsel-find-file` as it is intended.

**Comment by abo-abo** [comment]
Thanks. Please test. Here's how I tested it:

- Open `*scratch*` and split it into 4 windows, so that the frame has 4 windows with `*scratch*`,
- `counsel-find-file`, select a directory, and 4 files there,
- <kbd>rj</kbd>.

As the result, the 4 files were opened in each of the 4 windows.

**Comment by basil-conto** [comment]
Why require action functions to have an argument with a special name rather than exposing `ivy-marked-candidates` dynamically? There could be another way for a caller to tell Ivy whether the action should be called on one or all marked candidates, e.g. an `ivy-read` keyword or a variable such as `ivy-calling`. This would allow more dynamic behaviour going forward.

Also, I don't think it's right to refer to the action function as `ivy-action`, as the only symbol with that name is a face.

**Comment by abo-abo** [comment]
@basil-conto I think the original intention was to have action functions that are `ivy`-agnostic.

But you're right that exposing `ivy-marked-candidates` is a better approach.

One other approach could be to have two functions that are `ivy`-agnostic:

```elisp
(ivy-read "prompt: " collection
          :action (lambda (x) (insert (concat ":" x ":")))
          :multi-action (lambda (xs) (insert ":" (mapconcat #'identity xs ":") ":")))
```

**Comment by basil-conto** [comment]
> One other approach could be to have two functions that are `ivy`-agnostic:

Yeah, that's what I meant by adding another `ivy-read` keyword.

**Comment by abo-abo** [comment]
@basil-conto Thanks, added a new keyword.

**Comment by CeleritasCelery** [comment]
@abo-abo @basil-conto 
So unless I am missing something, this change removes the ability to define multi-actions via `ivy-add-actions`. Previous it checked the size of the argument list and if it had an additional argument it added the marked candidates as a list. However with this new change The only way to add multi actions is to redefine the `ivy-read` with `:multi-action`. And you can only have one multi-action per completion. Am I missing something here? Is there a way to get back the old functionality?

**Comment by abo-abo** [comment]
@CeleritasCelery Yes, it looks like the functionality was reduced by this simplification. Please open a new issue where we can discuss which functionality we want and how to best implement it.
