### ISSUE TITLE
counsel-company messes up the text when all candidates have same beginnings

### ISSUE THREAD

**Issue by AmaiKinono** [abo-abo/swiper#2071]
Please see this:
![Peek 2019-05-20 02-08](https://user-images.githubusercontent.com/28714352/57986177-38579580-7aa4-11e9-814b-62f93bc2d126.gif)
When all the candidates have same beginnings, the common part is completed when calling `counsel-company`. Then, after pressing `RET`, the text is messed up.

Maybe related to https://github.com/abo-abo/swiper/issues/2054.

By the way, I would like not have `counsel-company` complete the common part for me, but didn't figure out how to do it. Could someone tell me how to do this? Thanks!

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by AmaiKinono** [comment]
It works. Thanks!
