### ISSUE TITLE
Wrong highlighting/fontification of matches in `ivy-occur` buffer on top of `grep`-like `counsel-*` search functions

### ISSUE THREAD

**Issue by Alexander-Shukaev** [abo-abo/swiper#2073]
For example, I `counsel-git-grep` for `solarized dark` and get:

```
./.emacs.d/init/init-solarized-theme.el:42:    (when (memq theme '(solarized-dark solarized-light))
./.emacs.d/init/init-solarized-theme.el:71:  (load-theme 'solarized-dark :no-confirm)
./.emacs.d/init/init-solarized-theme.el:82:            (variant (cond ((eq theme 'solarized-dark ) 'dark )
```

In minibuffer the highlighting/fontification of matches is correct, namely only matches in the content are highlighted/fontified.  However, if I do `ivy-occur`, the highlighting/fontification of matches changes.  In particular, the `solarized` match gets highlighted/fontified on the names of files (just by accident most probably because it's also present there) and not in the actual content anymore, while `dark` is still correctly highlighted/fontified.  From theoretical standpoint, I would have expected highlighting/fontification algorithms to be the same for both minibuffer and `ivy-occur` buffer, and if it's not the case yet, maybe it's worth considering it if it's not too tricky.

**Comment by abo-abo** [comment]
Thanks, please test.
