### ISSUE TITLE
counsel-company doesn't use ivy interface with "substring" completion style, in elisp mode.

### ISSUE THREAD

**Issue by AmaiKinono** [abo-abo/swiper#2074]
Run emacs using `$ make plain`, and evaluate the following expressions:

``` emacs-lisp
(add-to-list 'load-path "~/.emacs.d/straight/build/company")
(require 'company)

(setq completion-styles '(substring basic partial-completion emacs22))
```

Then, type something like `(def`, call `counsel-company`, the company overlay shows, rather than minibuffer popping out.

This problem should only shows up in emacs-lisp-mode and lisp-interaction-mode. I tried c-mode and fundamental-mode, they work well.

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by AmaiKinono** [comment]
Thanks, this works! Now counsel-company is just so smooth :heart:
