### ISSUE TITLE
ivy-occur: cannot edit content

### ISSUE THREAD

**Issue by manuel-uberti** [abo-abo/swiper#2076]
Hi,

I am using latest `ivy/counsel` from MELPA. (I upgraded my packages an hour ago.)

If I do this:

- `emacs -Q`
- <kbd>M-x package-initialize</kbd>
- <kbd>C-x d ~/.emacs.d/ RET</kbd>
- <kbd>M-x counsel-rg RET use-pac RET</kbd>
- <kbd>C-c C-o</kbd>
- <kbd>w</kbd>

I cannot edit the `ivy-occur` buffer. I get a message saying: `Text is read-only`.

These are some details on my system, in case they can help:
```
GNU Emacs 27.0.50 (build 1, x86_64-debian-linux-gnu, GTK+ Version 3.22.30)
 of 2019-05-23

Repository revision: 38564f8a664347c42f7614d9c91e0d49e4a073e8
Configured using:
--host=x86_64-debian-linux-gnu --with-modules

Emacs uptime: 1 hour, 12 minutes, 59 seconds
Colour theme: zenburn
Operating system: Ubuntu 18.04.2 LTS
Window system: x11
Desktop environment: GNOME Shell 3.28.3
```

**Comment by abo-abo** [comment]
Thanks. Sorry for the regression.

**Comment by manuel-uberti** [comment]
Thank you as always for the quick fix. It works as expected now.
