### ISSUE TITLE
ivy multi-action exit: using ivy-set-actions with counsel-ag

### ISSUE THREAD

**Issue by drorbemet** [abo-abo/swiper#208]
After reading on ivy multi-action with curiosity I would like to try it on full text search results.
I prepared a action to test adding it to counsel-ag.
What do I need to do to enable multi-action exit for counsel-ag?

````elisp
(ivy-set-actions
 'counsel-ag
 `(("a"
    (lambda (x) (progn (counsel-git-grep-action x)
                       ;; todo: the following example command doesn't take effect
                       ;; in the buffer returned by counsel-git-grep-action
                       (mark-word)))
    "mark word")))
```

**Comment by abo-abo** [comment]
Use `with-ivy-window`:

```elisp
(ivy-set-actions
 'counsel-ag
 '(("a"
    (lambda (x) (with-ivy-window
             (counsel-git-grep-action x)
             (mark-word)))
    "mark word")))
```

**Comment by drorbemet** [comment]
Ah, ok, thanks.

**Comment by drorbemet** [comment]
Ah, wait a minute, I tried your exact code sample and it did not mark the word. 
I tried the following and it set the major mode of my recent current buffer but not the new current buffer opened by ```(counsel-git-grep-action x)```

```elisp
(ivy-set-actions
 'counsel-ag
 `(("a"
    (lambda (x) (with-ivy-window
                  (text-mode)
                  (counsel-git-grep-action x)
                  (beginning-of-line)))
    "beginning of line")))
```

**Comment by abo-abo** [comment]
Of course, if you look at the code of `counsel-git-grep-action`, it has `find-file`. Just move your `text-mode` after.

**Comment by mis3sifhbdk** [comment]
Actually ```with-ivy-window ``` doesn't seem to be what I need.
I want to execute BODY in the window that ```counsel-git-grep-action``` opened the window showing the file the match was found in not the window from which `ivy-read' was called.

**Comment by drorbemet** [comment]
Actually ```with-ivy-window ``` doesn't seem to be what I need.
I want to execute BODY in the window that ```counsel-git-grep-action``` opened the window showing the file the match was found in not the window from which `ivy-read' was called.

**Comment by abo-abo** [comment]
Those two should usually be the same. Remove `with-ivy-window` if necessary. The only reason it's there is to prevent from running commands in the minibuffer.

**Comment by drorbemet** [comment]
Here is a new try to find out how to reach a new buffer opended during the evaluation of an action started from an ivy-buffer.

At the beginning when calling counsel-ag the current buffer is *scratch*.
Then the new current-buffer should be the buffer of the file of the search result but in my emacs instance it is at the moment still *scratch* and the string is inserted into scratch not into the opened file.

```elisp
(ivy-set-actions
 'counsel-ag
 `(("a"
    (lambda (x) (with-ivy-window
                  (counsel-git-grep-action x)
                  (insert (format "insert current buffer's name: %s" (current-buffer)))
                  (message "the current buffer is: %s" (current-buffer))))
    "name of current buffer")))
```

**Comment by abo-abo** [comment]
Try this:

```elisp
(ivy-set-actions
 'counsel-ag
 '(("a"
    (lambda (x)
      (counsel-git-grep-action x)
      (with-ivy-window
        (insert (format "insert current buffer's name: %s" (current-buffer)))
        (message "the current buffer is: %s" (current-buffer))))
    "name of current buffer")))
```

**Comment by drorbemet** [comment]
Thanks this was the reason. Now it works well. I will test it to see if it changes my editing workflow for the better.
