### ISSUE TITLE
Ivy sets `org-hide-emphasis-markers` globally

### ISSUE THREAD

**Issue by sebastianpoeplau** [abo-abo/swiper#2085]
When Ivy displays its help, it [sets](https://github.com/abo-abo/swiper/blob/7e8622f60487fc3a91540755103358a5cd599d12/ivy.el#L4659) `org-hide-emphasis-markers` to `t`, a feature introduced in commit 6ec11269fa4fe704165aeafbfe21187dd394d1e5. In doing so, it changes the appearance of all of the user's org-mode buffers because the variable doesn't become buffer local automatically. May I suggest to use `setq-local` instead of `setq` in order to confine the change to the one buffer owned by Ivy?

(One could argue whether the variable should be automatically buffer local, but for now setting it locally seems to be the right thing.)

**Comment by basil-conto** [comment]
Thanks for catching this!

> (One could argue whether the variable should be automatically buffer local, but for now setting it locally seems to be the right thing.)

It's a user option intended to be set globally in user configurations, and Emacs packages should strive to not affect user options, so in this case `setq-local` is the best middle ground.

**Comment by sebastianpoeplau** [comment]
Thanks for fixing it so quickly!
