### ISSUE TITLE
Symbol's function definition is void: ivy-make-magic-action

### ISSUE THREAD

**Issue by zhangjie2012** [abo-abo/swiper#2087]
package install ivy, `C-x f` or `M-x` will throw `Symbol's function definition is void: ivy-make-magic-action`.

same config in MacOS is right. but on Ubuntu 18.04 will wrong.

the strange problem is: when ivy start with emacs will throw that error message, but manual execute `M-x ivy-mode` will right.

version info: 

```
counsel-20190527.1406
ivy-0.11.0
swiper-0.11.0
```

**Comment by basil-conto** [comment]
> counsel-20190527.1406
> ivy-0.11.0
> swiper-0.11.0

Here's the problem: You have the stable versions of Ivy and Swiper installed, presumably from [GNU ELPA](https://elpa.gnu.org/), but the unstable version of Counsel, presumably from [MELPA](https://melpa.org/#/). Counsel calls the function `ivy-make-magic-action` at top-level, so the error happens as soon as the library is loaded, but this function was added only in (the unreleased) Ivy 0.12.0.

The easiest solution for you would be to install all three packages from MELPA. This would ensure that their versions are always in sync. Alternatively, you could add the following in your `user-init-file` (make sure it's evaluated before Counsel is loaded).

```el
(define-advice ivy-make-magic-action (:override (&rest _) my-shim)
  "Compatibility shim for `ivy-make-magic-action'."
  nil)
```

Finally, on the Counsel side, the following protective measure could be taken:

```diff
diff --git a/counsel.el b/counsel.el
index 86e5264..0bb8abc 100644
--- a/counsel.el
+++ b/counsel.el
@@ -1690,7 +1690,8 @@ counsel-find-file-map
     (define-key map (kbd "C-DEL") 'counsel-up-directory)
     (define-key map (kbd "C-<backspace>") 'counsel-up-directory)
     (define-key map (kbd "C-M-y") 'counsel-yank-directory)
-    (define-key map (kbd "`") (ivy-make-magic-action 'counsel-find-file "b"))
+    (when (fboundp 'ivy-make-magic-action)
+      (define-key map (kbd "`") (ivy-make-magic-action 'counsel-find-file "b")))
     map))
 
 (defun counsel-yank-directory ()
```

@abo-abo Thoughts? BTW, why is Counsel not available through GNU ELPA?

**Comment by zhangjie2012** [comment]
@basil-conto Yes, My config file like this:

        ("gnu" . "https://elpa.gnu.org/packages/")                                                                             
        ("melpa" . "https://melpa.org/packages/")                                                                              
        ("melpa-stable" . "https://stable.melpa.org/packages/") 

I comment `gnu` and `melpa`, just use `melpa-stable` fix this problem. thanks. new version info:

```
counsel-0.11.0
ivy-0.11.0
swiper-0.11.0
```

**Comment by abo-abo** [comment]
> BTW, why is Counsel not available through GNU ELPA?

On GNU ELPA, all 3 packages are packaged into a single package `ivy`. MELPA makes it easy to split one repo into 3 packages, GELPA does not.

**Comment by basil-conto** [comment]
Ah, okay. Wonder how the frankensetup came to be then...
