### ISSUE TITLE
ivy multi-action exit: move point to current file buffer

### ISSUE THREAD

**Issue by drorbemet** [abo-abo/swiper#209]
How do I move focus to the current file buffer during evaluation of the action from an ivy-buffer?

````elisp
(ivy-set-actions
 'counsel-locate
 `(("i"
    (lambda (x)
      ;; todo: how to get current file buffer instead of the ivy buffer
      (insert-file x)
      (ivy--reset-state ivy-last))
    "insert file")))
```

**Comment by abo-abo** [comment]
Again, use `with-ivy-window`. And no need to call `ivy--reset-state` in this case: that is only useful for updating the candidates in case the completion hasn't exited, e.g. in case when killing several buffers at once.
