### ISSUE TITLE
Does counsel has a command like 'helm-show-kill-ring' ？

### ISSUE THREAD

**Issue by zhangjie2012** [abo-abo/swiper#2090]
Recently，I migrate helm to ivy. all features can cover ivy except `helm-show-kill-ring`, `kill-ring` is a common feature for me.

Does counsel has a command like 'helm-show-kill-ring' ？

**Comment by manuel-uberti** [comment]
Does `counsel-yank-pop` cover your need?

**Comment by zhangjie2012** [comment]
@manuel-uberti Yeah, thanks.
