### ISSUE TITLE
counsel-descbinds-function fo Helpful integration

### ISSUE THREAD

**Issue by ema2159** [abo-abo/swiper#2091]
I noticed that there exist a `counsel-describe-function-function` and a `counsel-describe-variable-function` so I'm able to call Helpful using counsel like doing for example `(setq counsel-describe-function-function #'helpful-callable)` and that's awesome, however, there's no `counsel-descbinds-function`, so I'm unable to call Helpful from counsel when describing a key. 
Could this feature be implemented in a near future?

**Comment by Alexander-Shukaev** [comment]
Duplicate of #1876 (it's not a big deal to implement by the way, PR is always welcome).

**Comment by abo-abo** [comment]
Added, thanks.

**Comment by ema2159** [comment]
Awesome man, thanks!
