### ISSUE TITLE
C-M-y Behavior for write-file?

### ISSUE THREAD

**Issue by draxil** [abo-abo/swiper#2092]
I love ivy, but sometimes it's behaviour isn't ideal for every situation. Thankfully in "find-file" I can hit C-M-y and edit the full path. However, this doesn't work for "write-file". And actually I often wish to do things like modify the middle of a path, an action which can be cumbersome in ivy.

Use case, I have a file at:
 /x/foo/fancylib/c/x.c
I want to write it to 
 /x/bar/fancylib/c/d.c
This task is much easier if I can use the vanilla emacs style of editing the path.

So, how difficult would to be to have the same C-M-y behaviour in write-file?

**Comment by abo-abo** [comment]
Thanks, <kbd>C-M-y</kbd> will now work with `write-file`.
