### ISSUE TITLE
swiper-isearch does not honor char-folding

### ISSUE THREAD

**Issue by gusbrs** [abo-abo/swiper#2095]
I've been trying out and really enjoying `swiper-isearch`, thank you. One thing I miss though is that it doesn't seem to honor the setting `(setq search-default-mode #'char-fold-to-regexp)`, while `swiper` does.

Environment: Emacs 26.2, `emacs -Q`, Ivy 20190613.1539, Swiper 20190611.858.

**Comment by abo-abo** [comment]
Thanks, this should work now.

**Comment by gusbrs** [comment]
I've tested it here, and it looks great. Thank **you**!
