### ISSUE TITLE
How to use elisp expression when using swiper-query-replace?

### ISSUE THREAD

**Issue by AmaiKinono** [abo-abo/swiper#2096]
When using `query-replace-regexp`, `\,(some-elisp-expression)` can be used. e.g. `\,(format "\n")` can be used to represent a newline character, `\,(1+ \#)` is an incrementor from 1 (although I don't know exactly what `\#` is). But when using `swiper-query-replace`, these does not work. So how to use them?

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by AmaiKinono** [comment]
It works!
