### ISSUE TITLE
Feature request: specify files to be searched by `git grep`

### ISSUE THREAD

**Issue by dandavison** [abo-abo/swiper#2099]
As far as I can see, `counsel-git-grep` currently provides no control over the set of files searched. In a large project I think that one does want this. For example:
1. You know ahead of time that you are looking for something in a certain file or subtree.
2. Faced with many search hits, you want to filter them by source file.

Git itself provides the fairly powerful [pathspec](https://git-scm.com/docs/gitglossary#Documentation/gitglossary.txt-aiddefpathspecapathspec) mini-language for specifying file paths. If I'm right that counsel doesn't yet make it easy to specify the file paths then the next question is the UI. Some possibilities could be:

1. When there are multiple space-separated input patterns, interpret the first as a pathspec.
2. Introduce some special syntax to distinguish the pathspec from the regexes, e.g. by using a colon separated by spaces: `<pathspec> : first_search_pattern second_search_pattern`
3. Two stage search: User specifies search paths in first stage then proceeds to the usual `counsel-git-grep` UI.

I worry that (3) would be clunky, and that one would want to alter the file search path dynamically in the course of using the UI.

**Comment by dandavison** [comment]
Here's a quick implementation of (1) that seems to work.

```emacs-lisp
(defun counsel-git-grep-cmd-function-with-files-glob (str)
  "If there are multiple input patterns, interpret the first as a
glob constraining the files searched by `git grep`. Note that git
supports ** glob syntax."
  (let* ((parts (split-string str " " t))
         (files-glob (if (> (length parts) 1)
                         (car parts) ""))
         (regex (ivy--regex (if (> (length parts) 1)
                                (string-join (cdr parts) " ") (car parts)) t)))
    (setq ivy--old-re regex)
    (format "%s %s" (format counsel-git-grep-cmd regex) files-glob)))

(setq counsel-git-grep-cmd-function #'counsel-git-grep-cmd-function-with-files-glob)
```

**Comment by dandavison** [comment]
@abo-abo Here's what I have so far. It allows you to use ` : ` to separate the regexes from a path specification for `git grep`.  I haven't tried doing something similar for `counsel-rg` yet. I'd be interested to hear your thoughts on what the best direction is, and whether you'd consider a PR for a feature like this. (Here's a question from a user asking for something similar: [emacs.stackexchange.com:37247](https://emacs.stackexchange.com/questions/37247/specifying-filetype-when-using-counsel-git-grep)).

```emacs-lisp
(defun counsel-git-grep-cmd-with-pathspec-function (str)
  "Git grep with control over file paths searched.

To use, set `counsel-git-grep-cmd-function' equal to this function.

The behaviour is the same as default `counsel-git-grep', but you
may optionally use a single ':' character, surrounded by spaces,
to separate the pathspec (to the left) from the regular
expressions (to the right).

For pathspec syntax see `man gitglossary` or
https://git-scm.com/docs/gitglossary#Documentation/gitglossary.txt-aiddefpathspecapathspec

A simple example is:
**/somedir/* : regex1 regex2 ...

A more complex example is:
**/somedir/* :(exclude)*/tests/* : regex1 regex2 ...
"
  (let* ((cmd "git --no-pager grep --full-name -n --no-color -i -I -e %s")
         (parts (split-string str " " t))
         (separator-pos (position ":" parts :test #'equal))
         (pathspec (subseq parts 0 (or separator-pos 0)))
         (regexes (subseq parts (if separator-pos (1+ separator-pos) 0)))
         (regex (ivy--regex (string-join regexes " ") t))
         (git-grep-cmd-without-pathspec (split-string (format cmd regex) " " t)))
    (setq ivy--old-re regex)
    (append git-grep-cmd-without-pathspec pathspec)))

(setq counsel-git-grep-cmd-function #'counsel-git-grep-cmd-with-pathspec-function)
```

**Comment by abo-abo** [comment]
There's an interface for supplying custom grep commands to `counsel-git-grep`. I use it to grep not only my config, but also all packages on which it depends.

The interface is:

```elisp
(setq counsel-git-grep-projects-alist
      '(("project-directory-1" . "custom-cmd-1 '%s' ...")
        ("project-directory-2" . "custom-cmd-1 '%s' ...")))
```

When you call <kbd>C-u</kbd> `counsel-git-grep` and an entry on `counsel-git-grep-projects-alist` is detected, it will be used in place of `counsel-git-grep-cmd-default`. If there's no entry, you get completion for git-grep command.

But I like your variant as well.

`counsel-rg` already has a similar interface:

- look for `ivy`: `ivy` in all files
- look for `ivy` in the current directory: `-g/* -- ivy`
- look for `ivy` in the `doc/` directory: `-gdoc/* -- ivy`

Could you please make a PR where the delimiter is `--` to have a similar interface to `counsel-rg`.

**Comment by dandavison** [comment]
@abo-abo thanks! I will get to this.

**Comment by dandavison** [comment]
@abo-abo I might not do any more work on this, since I started using `counsel-rg` instead (motivated by your [blog post](https://oremacs.com/2018/03/05/grep-exclude/), the `.ignore` feature is very convenient when one already has a versioned `.gitignore`.) So I would not be offended if you closed this :) OTOH the feature probably does make sense.

**Comment by basil-conto** [comment]
FWIW, `counsel-git-grep` allows modifying the `git grep` command on the fly via <kbd>C-c</kbd><kbd>C-m</kbd> (`counsel-git-grep-switch-cmd`) and switching root directory on the fly via <kbd>C-x</kbd><kbd>C-d</kbd> (`counsel-cd`).

**Comment by abo-abo** [comment]
I think we can close this issue.
