### ISSUE TITLE
Repeating previous searches

### ISSUE THREAD

**Issue by johnmastro** [abo-abo/swiper#21]
Is there a way to cycle through previous searches?  I tried `M-p` but it seems to cycle through full lines of the `ivy` buffer (including line numbers) rather than just the query text.

As a special case of this, the only thing I've really missed from `isearch` while using `swiper` so far is the ability to quickly repeat the last search (i.e. `C-s C-s` in `isearch`).

**Comment by johnmastro** [comment]
Oops, I just noticed that this issue is mentioned briefly in issue #16.

I'll leave it open for now in case you want a separate issue open for it.

**Comment by abo-abo** [comment]
The history access with <kbd>M-n</kbd> and <kbd>M-p</kbd> should work better now.
Let me know if it works fine for you.

**Comment by johnmastro** [comment]
It does, thanks!

I left a comment on the commit (cb26121) with couple ideas for your consideration.
