### ISSUE TITLE
completions for `man` are garbled

### ISSUE THREAD

**Issue by freesteph** [abo-abo/swiper#2100]
When I try and find an entry with `M-x man`, I get a lot of strange characters (think they might be colour codes) in the output. I also need to remove the leading `^` as the completion command seems to interpret it literally. Once that's done I have this:

<img width="355" alt="Screen Shot 2019-06-20 at 10 44 07" src="https://user-images.githubusercontent.com/107635/59839317-5dac1d80-9348-11e9-8ef5-12f0be83cf25.png">

Selecting any of these fails, as the `man` command also get that garbled input literally, and the only way to get a page to show correctly is:

1. type command, say `lsof`;
2. remove leading `^`;
3. use `C-M-j` to send the current candidate as opposed to garbled input.

When I rely on `woman`, everything works fine (no life lesson here). I appreciate the problem might not lie with `ivy` but if you have any pointers I'll happily take them.

**Comment by abo-abo** [comment]
Can't reproduce. I suggest you first try reproducing with `make plain` in this repository. And if you can't reproduce it, bisect your config.

**Comment by freesteph** [comment]
Turns out it's a problem with my shell. If I remove my custom prompt (`$PS1`) then system `man` prints normal output and so does ivy. Cheers!

**Comment by abo-abo** [comment]
Thanks for the follow up.
