### ISSUE TITLE
counsel-find-file TAB gets stuck on certain paths with spaces

### ISSUE THREAD

**Issue by gusbrs** [abo-abo/swiper#2103]
I found a corner case in the workings of `counsel-find-file` which was pulling my leg for some time, but I had never stopped to try to understand what was really going on. Today I did, and report.

Steps followed:

```
$ emacs -Q
M-x package-initialize RET
M-x counsel-mode RET
```

Let’s say we have the following directory structure:

```
~/foo/
    barbazi/
    barbazii/
        goal.txt
```

Now we try to navigate the tree:

```
"C-x C-f" foo TAB (we are inside "~/foo/")
"C-n" "C-n" "C-n" TAB TAB (we are inside "barbazii/")
"C-n" "C-n" TAB TAB
```

And we reached `goal.txt`.

Now we add two things:

```
M-: (setq ivy-extra-directories nil) RET
```

and spaces in the directory tree:

```
~/foo/
    bar baz i/
    bar baz ii/
        goal.txt
```

And try it again:

```
"C-x C-f" foo TAB (we are inside "~/foo/")
"C-n" TAB TAB TAB TAB "C-p" TAB TAB TAB TAB
```

And we get stuck. ("C-j" does work though).

Now if there is another arbitrary directory there:

```
~/foo/
    bar baz i/
    bar baz ii/
        goal.txt
    foo sub/
```

then we can reach "goal.txt" again.

So, as far as I can tell, the situation arises when all candidates share a common initial string up to a space.

Indeed, the fontification suggests that the TAB completion gets stuck in the first space after the common part in the names of the two directories.

Either the default value of `ivy-extra-directories` or an arbitrary third directory breaks this condition, and TAB TAB works as expected.

Environment: Emacs 26.2, counsel-20190619.512, ivy-20190613.1539, Linux Mint 19.1 Cinnamon

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by gusbrs** [comment]
@abo-abo Thank you very much for looking into this.

I had to wait a little for the fix to get propagated through MELPA, but it got here now. It does indeed succeed in the example I initially provided. But I could still generate the problem with a slightly different directory structure. Namely:

```
~/foo/
    bar baz (abc)/
    bar baz i/
    bar baz ii/
        goal.txt
```

Furthermore, in testing again I did observe another non expected behavior in this scenario. I don't know if it was there before, as I hadn't noticed. Anyway, while navigating this directory structure according to the procedure initially reported, we will get the tab completion to go up to `~/foo/bar baz`, and get stuck there. Now, at this point, if we decide to go back one level with DEL (backspace), it won't work as usual and go back to `~/foo/` with a single keypress, but `bar baz` will be deleted letter by letter.

**Comment by gusbrs** [comment]
@abo-abo If I may gently ping you on this one, in case this got lost in the issue overflow. (If this was not the case, please disregard, with my apologies).

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by gusbrs** [comment]
It's working nicely indeed now. Thank you very much!
