### ISSUE TITLE
search pattern in arbitrary directory recursively using counsel-ag

### ISSUE THREAD

**Issue by drorbemet** [abo-abo/swiper#211]
After using counsel for a while I am still missing support for the following use case in my workflow:
search "there" for "pattern" using counsel-ag with added actions using ivy-set-actions

How could counsel-ag be extendet seemlessly with a parameter for its working directory?
What would it take to implement it?
I tried changing ```counsel--git-grep-dir``` but this didn't seem to take effect ... I don't quite understand the code yet.

**Comment by abo-abo** [comment]
The base directory for `counsel-ag` is the directory of the current file. So you first open a file in the directory that you're interested in, then call `counsel-ag`.

**Comment by drorbemet** [comment]
Right, I am doing that until now. Now my use case looks like this:
After searching for this "pattern" "somwhere in the system" I want to call an action like:
insert "some text near match in matching file" here at point in current buffer
This way I can for instance pull in arbitrary snippets of text from all over the file system into current editing buffer. If I go to the source directory first by opening an other buffer then I am missing the target position in the editing buffer at which a am currently looking and working at.
The point is I think, that untill now I am hesitating to use symlinks for each search scope or to copy larger amounts of files with possible matches into current directory each time.
I think I want to try something like autocompletion but with arbitrary text sources.
What do you think about that?

**Comment by drorbemet** [comment]
My feature request might in fact not be necessary indeed. I settled with the following solution:
1. I make a sparce copy of text files to search into current dir using rsync with filter or a similar command
2. then start searching using counsel-ag and processing using elisp functions
3. optionally I can use git to keep track of processed text if I delete it from the files, this actually convinced me to do it this way around
