### ISSUE TITLE
swiper-isearch and outlines

### ISSUE THREAD

**Issue by gusbrs** [abo-abo/swiper#2119]
`swiper-isearch` does not currently play well with outlines, either in `org-mode` or `outline-minor-mode`.  `swiper`, on the other hand, handles this quite gracefully, by which I mean:

- after being run, it respects the previous folding state of the buffer, with the exception of an eventual selected candidate
- as one navigates through the list of candidates, the current candidate is always shown on the buffer unfolded (temporarily, unless selected)

Neither of these properties is exhibited by `swiper-isearch`, however.

I set a somewhat arbitrary case for this, but which enables one to reproduce the mentioned behaviors.

Start with `emacs -Q`, then evaluate:

```emacs-lisp
(package-initialize)
(ivy-mode)
(find-library "simple")
(outline-minor-mode)
(outline-hide-body)
```

Now, start `swiper-isearch` and search for the string "let"

> M-x swiper-isearch RET let

and navigate through the list of candidates, with "C-n" or equivalent.

Notice that some candidates will fail to be shown in the buffer (I assume they are still in folded regions, but I’m not really sure).  Not all candidates will be hidden, actually most of them will be shown, and some exceptions not.

Furthermore, from this point, consider two possible actions.  First, cancel the search with "C-g".  This will let the folding state of the buffer quite disturbed, if you had navigated through any considerable number of candidates.  Second case, select one candidate.  The selection will work as expected, but yet again, the folding state of the buffer will be quite disrupted in sections which are not the one of the selected candidate.

The same general behavior happens for Org files.

It would be really nice if `swiper-isearch` played better with outlines, specially as `swiper` already does a great job in this respect.

Environment: Emacs 26.2; swiper-20190627.1944; ivy-20190701.1140; counsel-20190629.1203.

PS: I hope it is as promised.  :)

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by gusbrs** [comment]
Thank you very very much.
And, wow! that was fast!

I did test it here in the different environments I use some sort of outlining (Org, emacs-lisp, LaTeX), and it is working beautifully.

With this, the things I really missed from `swiper` I also get in `swiper-isearch`. Plus its benefits, of course.   :-)
I still have some residual use cases for `isearch` itself, but that's another matter. Anyway, most of the lifting here is already done by Ivy & friends. It is very much appreciated. Thank you.

**Comment by abo-abo** [comment]
You're welcome. Thanks for the report.
