### ISSUE TITLE
Highlight the portion of the line that matches the current query

### ISSUE THREAD

**Issue by Wilfred** [abo-abo/swiper#212]
![swiper](https://cloud.githubusercontent.com/assets/70800/9551999/c38174d8-4dac-11e5-8bd1-1973a8dc5f03.png)

In this picture, my second line actually matches my search term twice. However, because the line is quite long, it's easy not to notice.

I think swiper should highlight the matching part of the line, so it's clear that there are multiple matches on the current line.

**Comment by abo-abo** [comment]
You mean in the minibuffer? Because it already highlights it in the main buffer.

**Comment by Wilfred** [comment]
Yep, in the minibuffer. The results currently visible in the minibuffer are not necessarily all visible in the buffer (depending on how close together the results are).

I thought I'd file a bug because this caught me out today when looking through a large buffer code.

**Comment by abo-abo** [comment]
Thanks, please test the new feature with:

    (setq ivy-display-style 'fancy)

**Comment by Wilfred** [comment]
Works perfectly. Thank you :)
