### ISSUE TITLE
Question on integrating color-rg with swiper

### ISSUE THREAD

**Issue by QiangF** [abo-abo/swiper#2122]
color-rg is a search and refactoring tool based on ripgrep, it
has a handy function for isearch, the function uses the current
search string so the user doens't need to type it twice.

1. How do we get the user input in swiper 
2. How to quit swiper after the switch to color-rg

    (defun isearch-toggle-color-rg ()
        (interactive)
        (color-rg-search-input isearch-string)
        (isearch-exit))

color-rg is hosted at
https://github.com/manateelazycat/color-rg

**Comment by abo-abo** [comment]
Have a look at `swiper-isearch-toggle`.

**Comment by QiangF** [comment]
Thank you so much!

    (defun swiper-toggle-color-rg ()
        (interactive)
        (ivy-exit-with-action
        (lambda (_)
        (when (looking-back ivy--old-re (line-beginning-position))
            (goto-char (match-beginning 0)))
        (unless (string= ivy-text "")
            (color-rg-search-input ivy-text)))))
