### ISSUE TITLE
use executable-find for counsel-fzf-cmd

### ISSUE THREAD

**Issue by baron** [abo-abo/swiper#2123]
This might be MacOS specific or just a quirk with my environment but I was unable to use counsel-fzf until setting the counsel-fzf-cmd to include the full path to my fzf binary.

I've added the following to my init file in order to avoid the issue on restart.

```
  (setq counsel-fzf-cmd (concat (executable-find "fzf") " -f \"%s\""))
```

**Comment by abo-abo** [comment]
I think you should have a look at how you set up the `PATH` environment variable. Because if `(executable-find "fzf")` returns something, it means it's in your `PATH`. And if it's in your path, it can be called by `fzf` anyway.

**Comment by baron** [comment]
I use an external package or custom elisp for setting the PATH since it didn't reflect my shell env. Not sure why I can't use counsel-fzf without setting it to the full path but I'll close this issue since it seems specific to my init file.
