### ISSUE TITLE
swiper-isearch candidate fontification with char-folding

### ISSUE THREAD

**Issue by gusbrs** [abo-abo/swiper#2124]
`swiper-isearch` was recently improved to honor char-folding in its searches (https://github.com/abo-abo/swiper/issues/2095).  While the search works nicely, the fontification of candidates when char-folding occurs is not done in the buffer. (Sorry to have missed that when I tested it then.)

Steps to reproduce:

Start `emacs -Q`.

Run `M-x package-initialize RET`.

Start `M-x ivy-mode RET`

Eval `(setq search-default-mode #'char-fold-to-regexp)`

Consider a buffer with the following content:

```
Foo bar báz foo bâr bãz foó Bar Baz
```

And search for either "foo", "bar" or "baz". Notice the candidate fontification occurs in the minibuffer for all candidates, but not in the buffer itself, where it works when no char-folding is taking place (including when case-folding is happening) but not when an accented character comes into play.

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by gusbrs** [comment]
Tested here with swiper-20190708.1101. Shinning, as usual. Thank you very much.
