### ISSUE TITLE
ivy-cd recently broke tramp

### ISSUE THREAD

**Issue by kensanata** [abo-abo/swiper#2127]
I recently updated my packages and now ivy-cd breaks Tramp:

I use `C-x C-f`to find a *directory*. I use `C-r ssh` to search for a previous remote file I was editing. I pick `/ssh:sibirocobombus:~/.emacs.d/` from the matches offered and use `RET` to select it. Previously, it would offer edit the path I selected and another `RET` would the open the file or directory. Now, however, I am returned to the prompt "Reverse-i-search: " with the first entry selected (and that has nothing to do with `/ssh:sibirocobombus:~/.emacs.d/`). When I hit `RET` then that entry gets opened.

Let's try again.

I use `C-x C-f`to find a *file*. I use `C-r ssh` to search for a previous remote file I was editing. I pick `/ssh:sibirocobombus:~/bin/time-grouping` from the matches offered and use `RET` to select it. I'm returned to the prompt "Reverse-i-search: " with "time-grouping" being the answer and the candidates being `/ssh:sibirocobombus:~/bin/time-grouping` and `/ssh:sibirocobombus:/home/alex/bin/time-grouping`. When I hit `RET` again, the dialogue ends and no file gets opened.

Let's disable `ivy-mode`.

I use `C-x C-f`to find a *file*. I use `C-r ssh` to search for a previous remote file I was editing. This is not the correct file so I keep hitting `C-r`  few time until I'm presented with `/ssh:sibirocobombus:/home/alex/bin/time-grouping` and use `RET` to select it. I'm returned to the prompt "I-search backwards: " with "/ssh:sibirocobombus:/home/alex/bin/time-grouping" being the answer. When I hit `RET` again, I'm returned to the prompt "File find: " with "/ssh:sibirocobombus:/home/alex/bin/time-grouping" being the answer. When I hit `RET` again, the dialogue ends and the file does get opened.

**Comment by abo-abo** [comment]
> Previously, it would offer edit the path I selected and another RET would the open the file or directory.

This is still the behavior that I see. I tried a few times, but I can't reproduce the bug.

**Comment by kensanata** [comment]
You are right. After struggling with this all day yesterday I can no longer reproduce it.
