### ISSUE TITLE
Call `isearch-mode-end-hook` or create Swiper equivalent

### ISSUE THREAD

**Issue by sebasmonia** [abo-abo/swiper#2128]
I set a mark in the local ring when I exit a search, with this code:

```
(add-hook 'isearch-mode-end-hook 'hoagie-isearch-end-push-mark)
(defun hoagie-isearch-end-push-mark ()
  "Push the mark -without activating- when exiting isearch."
  (unless isearch-mode-end-hook-quit
    (push-mark-no-activate)))
```
I can live without it because Swiper is giving me so much more :) but I still think it would be nice to provide an equivalent hook or simply call the isearch one.

**Comment by abo-abo** [comment]
Here's how you can use `advice-add` in place of a hook:

```elisp
(defun hoagie-isearch-end-push-mark (&rest _)
  "Push the mark -without activating- when exiting isearch."
  (unless isearch-mode-end-hook-quit
    (push-mark-no-activate)))

(advice-add 'swiper--action :after 'hoagie-isearch-end-push-mark)
(advice-add 'swiper-isearch-action :after 'hoagie-isearch-end-push-mark)
```

It's equivalent in what it does and also in the amount of code. But this way, I don't have to introduce code that only a few users will use.

**Comment by sebasmonia** [comment]
Will use the advice. Thank you!
