### ISSUE TITLE
`ivy-resume` does not display `counsel-git-log` output correctly

### ISSUE THREAD

**Issue by leungbk** [abo-abo/swiper#2133]
After using `counsel-git-log` and getting some results, attempting to `ivy-resume` causes the results to be displayed line by line. This seems to be because `ivy-resume` does not set `counsel-async-split-string-re` to the desired `\ncommit ` as `counsel-git-log` does.

Should `counsel-async-ignore-re` and `counsel-async-split-string-re` be made into alists keyed by async `counsel-` commands?

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by leungbk** [comment]
Thanks!
