### ISSUE TITLE
Error when exiting swiper-isearch with swiper-avy

### ISSUE THREAD

**Issue by tam17aki** [abo-abo/swiper#2134]
The `swiper-avy` works well when using `swiper`. However, when using `swiper-isearch`, it does not work; raising "wrong type argument sequencep". 

I wish `swiper-isearch-avy` which has similar functionality to `swiper-avy` will implemented in future.

Thank you for the package. I love this package.

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by tam17aki** [comment]
Works fine. Thank you very much.
