### ISSUE TITLE
`:group' property for many `deffaces` not set. 

### ISSUE THREAD

**Issue by emacksnotes** [abo-abo/swiper#2135]
### `:group` property of many `deffaces` not defined properly. 

When I do `M-x customize-group RET ivy-faces RET` I see only one face (i.e. `Counsel Variable Documentation face`)  

But doing an `M-x occur RET defface RET` on `ivy.el` throws up the following matches

```
22 matches for "defface" in buffer: ivy.el
     57:(defface ivy-current-match
     64:(defface ivy-minibuffer-match-highlight
     68:(defface ivy-minibuffer-match-face-1
     75:(defface ivy-minibuffer-match-face-2
     82:(defface ivy-minibuffer-match-face-3
     89:(defface ivy-minibuffer-match-face-4
     96:(defface ivy-confirm-face
    100:(defface ivy-match-required-face
    104:(defface ivy-subdir
    108:(defface ivy-org
    112:(defface ivy-modified-buffer
    116:(defface ivy-modified-outside-buffer
    120:(defface ivy-remote
    127:(defface ivy-virtual
    131:(defface ivy-action
    135:(defface ivy-highlight-face
    139:(defface ivy-prompt-match
    143:(defface ivy-separator
    147:(defface ivy-grep-info
    151:(defface ivy-grep-line-number
    155:(defface ivy-completions-annotations
    159:(defface ivy-yanked-word
```

**Comment by skangas** [comment]
In recent years, the :group attribute is not necessary. From Emacs Lisp Reference Manual:

‘:group GROUP’
     Put this customization item in group GROUP.  If this keyword is
     missing from a customization item, it’ll be placed in the same
     group that was last defined (in the current file).

What version of Emacs are you using?

**Comment by abo-abo** [comment]
@skangas is correct, there's no need to put a :group for faces in ivy.el. I've added a :group for the other faces.
@emacksnotes Please check that `customize-group ivy-faces` indeed works by running `make plain` from this repo.

**Comment by emacksnotes** [comment]
> Please check that customize-group ivy-faces indeed works by running make plain from this repo.

Thanks for the fix.  It is working.  So, closing this issue.
