### ISSUE TITLE
Should custom sorting function has higher priority than `ivy--flx-sort`?

### ISSUE THREAD

**Issue by cireu** [abo-abo/swiper#2136]
I'm testing a new fuzzy matching algorithm and I want to use it with ivy, but I found `ivy--sort-flx` will has highest priority in sorting functions when flx is installed and regex function is `ivy--regex-fuzzy`

https://github.com/abo-abo/swiper/blob/master/ivy.el#L3285

Maybe allow custom sorting function to override `ivy--sort-flx` is better.

**Comment by abo-abo** [comment]
Thanks, please test.
