### ISSUE TITLE
Improper candidate for make-directory if ivy-extra-directories is nil

### ISSUE THREAD

**Issue by iquiw** [abo-abo/swiper#2139]
1. `make plain`
2. Eval `(setq ivy-extra-directories nil)`.
3. Find file (`C-x C-f`) a file under non-existent directory (e.g. `/tmp/foo/bar`)
4. `M-x make-directory`.

Then `/tmp/foo` (not just `foo`) is listed as the first and default candidate. And selecting it does not create `/tmp/foo` directory.

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by iquiw** [comment]
I could create `/tmp/foo` with the above steps. Thank you!!
