### ISSUE TITLE
toggle text alight right/left in ivy buffer

### ISSUE THREAD

**Issue by drorbemet** [abo-abo/swiper#214]
Maybe the following feature could be interesting and helpful in the future.
Sometimes the interesting parts of a match in an ivy buffer is hidden on the right side of the window.
How about toggling text align left/right for the list of ivy search results in ivy buffer?
- The options panel could be used to provide the toggle switch just like m: matcher ivy/fuzzy.

#### example
*align left:*
/home/userprofile/long-folder-name/fi ... (interesting part hidden)
*align right:*
(root part hidden) ... ng-folder-name/file-name.ext

**Comment by abo-abo** [comment]
Thanks. I've instead added an option to toggle truncation on/off. I think that should be better than truncating on the right/left, since there's never a part in the middle that gets omitted.
