### ISSUE TITLE
Remap C-k in ivy-switch-buffer?

### ISSUE THREAD

**Issue by yankcrime** [abo-abo/swiper#2141]
Since [this commit](https://github.com/abo-abo/swiper/commit/d52c176e3cca6a6e533e26d577b0aa9ce352d8af) I no longer seem to be able to remap `C-k` to the function I want (`ivy-previous-line`).  Previously I was using:

```
  (define-key ivy-minibuffer-map (kbd "C-j") 'ivy-next-line)
  (define-key ivy-minibuffer-map (kbd "C-k") 'ivy-previous-line)
```

Regardless of what I try now though, my binding seems to be overridden.  How can I fix this when using `ivy-switch-buffer`?

**Comment by abo-abo** [comment]
You can customize `ivy-switch-buffer-map`, which has priority over `ivy-minibuffer-map` for this command.

**Comment by yankcrime** [comment]
Ah, missed that - thanks @abo-abo!

**Comment by foosinn** [comment]
Thanks so much @abo-abo
