### ISSUE TITLE
Counsel-find-file does not behave as intended in Tramp mode 

### ISSUE THREAD

**Issue by CsBigDataHub** [abo-abo/swiper#2142]
I use Counsel-find-file. When I am in tramp mode and I want to find a file in local, I should be using `~` or `//` to get back to local.

reference - https://github.com/abo-abo/swiper/issues/1377

In my case if I use `~` it's taking me to _home directory of remote_ and when I use `//` it's taking me to _root directory of remote_.

Emacs version - 26.2
Local Os - MacOs
Remote server OS(Tramp) - RHEL
Swiper version -  20190708.1101

Please note- C-x C-r works file to navigate recent file , which I am using as a work around to navigate to local file system.

**Comment by articuluxe** [comment]
This is a feature!  Though I sometimes wish I could dynamically choose among the two variants.

**Comment by CsBigDataHub** [comment]
> This is a feature! Though I sometimes wish I could dynamically choose among the two variants.
> […](#)
> On Jul 15, 2019, at 5:51 PM, CsBigDataHub ***@***.***> wrote: I use Counsel-find-file. When I am in tramp mode and I want to find a file in local, I should be using ~ or // to get back to local. reference - #1377 In my case if I use ~ it's taking me to home directory of remote and when I use // it's taking me to root directory of remote. Emacs version - 26.2 Local Os - MacOs Remote server OS(Tramp) - RHEL Please note- C-x C-r works file to navigate recent file , which I am using as a work around to navigate to local file system. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by CsBigDataHub** [comment]
> This is a feature! Though I sometimes wish I could dynamically choose among the two variants.
> […](#)
> On Jul 15, 2019, at 5:51 PM, CsBigDataHub ***@***.***> wrote: I use Counsel-find-file. When I am in tramp mode and I want to find a file in local, I should be using ~ or // to get back to local. reference - #1377 In my case if I use ~ it's taking me to home directory of remote and when I use // it's taking me to root directory of remote. Emacs version - 26.2 Local Os - MacOs Remote server OS(Tramp) - RHEL Please note- C-x C-r works file to navigate recent file , which I am using as a work around to navigate to local file system. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

Was this a new feature?

Issue #1337 says different.

**Comment by abo-abo** [comment]
@CsBigDataHub The behavior was changed as an intended feature in relation to #1487.

- documentation node: https://oremacs.com/swiper/#using-tramp
- documentation commit: 2d22e05932b6e0478689049f33257bd0c0b4f65f.

In short:

- from remote, select the local root with <kbd>/ RET</kbd>

**Comment by CsBigDataHub** [comment]
Thanks @abo-abo .

**Comment by kleinschmidt** [comment]
Only `/ C-j` works for me, `/ RET` goes to the remote root.

**Comment by dhull** [comment]
To get to my local home directory, typing `~` once takes me to the home directory on the remote machine, and typing `~` a second time takes my to home directory on the local machine.
