### ISSUE TITLE
/ RET doesn't work as documented

### ISSUE THREAD

**Issue by dieggsy** [abo-abo/swiper#2143]
on 59603dfe145d0d329a81ef9e78ef991bc7c211c, with `make plain`, the documentation states that `/ RET` should move to the local root. This isn't the case - `/ C_j` does that. `/ RET` opens the local root directory in dired.

**Comment by abo-abo** [comment]
Thanks. I have in my config:

```elisp
(define-key ivy-minibuffer-map (kbd "<return>") 'ivy-alt-done)
```

And additionally I mistook `<return>` for `RET`.
