### ISSUE TITLE
Setting ivy-re-builders-alist for amx not having desired effect

### ISSUE THREAD

**Issue by svend** [abo-abo/swiper#2144]
I am attempting to use fuzzy matching for `amx` completions via the following setting:

```
  (setq ivy-re-builders-alist '((amx . ivy--regex-fuzzy)
                                (t . ivy--regex-plus))
```

However, `amx` does not use fuzzy completion, it uses the default regex-plus completion. I'm not sure how to troubleshoot this.

Here are my package versions:

```
amx                20190418.2030
ivy                20190605.537
swiper             20190604.308
counsel            0.11.0
```

**Comment by abo-abo** [comment]
Looks like you need to use `amx-completing-read-ivy`:

```elisp
(setq ivy-re-builders-alist
      '((amx-completing-read-ivy . ivy--regex-fuzzy)
        (t . ivy--regex-plus)))
```

To find this info, I looked in `amx.el` for a call to `ivy-read`. Relevant line:

    :caller 'amx-completing-read-ivy

**Comment by svend** [comment]
That worked @abo-abo. Thanks for explaining how you figured out what function to use. There was a change to amx which added that caller line: https://github.com/DarwinAwardWinner/amx/commit/7d83b752c907f0d73f3bdc02de4e0afb96309453
