### ISSUE TITLE
`swiper-query-replace` does not accept an empty string

### ISSUE THREAD

**Issue by t-suwa** [abo-abo/swiper#2145]
Can not specify an empty string for the replacement by just
entering `<RET>`.

Because the event `<RET>` select the default candidate `\,(concat
\&)`
provided by `swiper-query-replace` instead of making an
empty string.

This prevents us to do so-called "search and delete".

Also, can not specify any substring of the default candidate as
the replacement(e.g. "cat").

Any suggestions?

Package-Version: 20190717.1741

**Comment by abo-abo** [comment]
You can press <kbd>C-M-j</kbd>, see also: https://github.com/abo-abo/swiper#frequently-asked-questions.

**Comment by t-suwa** [comment]
Oh I see. Thanks.
