### ISSUE TITLE
center swiper-isearch result in buffer

### ISSUE THREAD

**Issue by CDitzel** [abo-abo/swiper#2146]
After successfully using Swiper to find something in the current buffer, i hit Return to confirm the position change. How can I ensure, that the line with the search result in the actual buffer becomes the center line of the current buffer? That would be both helpful and more intuitive

**Comment by manuel-uberti** [comment]
Does setting `swiper-action-recenter` to `t` work for you?

**Comment by CDitzel** [comment]
unfortunately it does not. My config always has been

```
(use-package swiper
  :bind (("C-s" . swiper-isearch)
         :map swiper-map
         ("M-%" . swiper-query-replace))
  :custom
  (swiper-action-recenter t))
```

**Comment by manuel-uberti** [comment]
`swiper-action-recenter` works for regular `swiper`, not for `swiper-isearch`.

**Comment by CDitzel** [comment]
mh thanks, is there some work around?

**Comment by manuel-uberti** [comment]
Not that I'm aware of. I'd suggest to rename the issue title mentioning you're using `swiper-isearch`, just to make it clearer for @abo-abo at a quick glance.

**Comment by abo-abo** [comment]
Should work now. Thanks.

**Comment by abo-abo** [comment]
@CDitzel Please make sure you reload/recompile. I reproduce the correct behavior with `make plain`.

**Comment by CDitzel** [comment]
how do I do that?

I did straight-pull-package swiper and straight-rebuild-all but it does not work

**Comment by abo-abo** [comment]
@CDitzel

```sh
git clone https://github.com/abo-abo/swiper
cd swiper
make plain
```
