### ISSUE TITLE
Fancy display style unreadable for the selected match

### ISSUE THREAD

**Issue by tsdh** [abo-abo/swiper#215]
With `emacs -Q` and then initializing `ivy` and `(setq ivy-display-style 'fancy)` the default highlighting of the matching groups is kinda broken for the selected candidate.

![screenshot from 2015-09-06 08-24-31](https://cloud.githubusercontent.com/assets/103854/9702905/d05a7ad6-5470-11e5-8386-924036e05630.png)

1. The substring matched by the first search group is not readable because the contrast between background and foreground is almost non-existing.
2. There is no highlighting of the other two match groups.

I didn't look into the code but I think that's something easy to fix.  Probably the selected candidate overlay mixes badly with the match group overlays and it's enough to give it a lower priority.

**Comment by abo-abo** [comment]
I've added some defaults for light and dark backgrounds. Please test, and feel free to improve (especially the dark one).

**Comment by tsdh** [comment]
Looks very nice, thank you!
