### ISSUE TITLE
swiper-isearch doesn't work w/ multi part regexes

### ISSUE THREAD

**Issue by muirrn** [abo-abo/swiper#2155]
When using `ivy--regex-plus`, `swiper-isearch` ignores the negation `! ...` part of regex. Similarly, when using `ivy--regex-ignore-order` `swiper-isearch` ignores all but the first space separated part.

`swiper--isearch-function` calls `ivy-re-to-str` which discards all but the first regex part. Can `swiper-isearch` support these regex builders fully, or does something about its approach make it difficult?

**Comment by abo-abo** [comment]
It's not easy, but I've made some refactors to get this working eventually.

**Comment by abo-abo** [comment]
Thanks. Please test. The in-buffer highlights are a bit wrong. But the search works fine in my tests.

Please note that the support for `ivy--regex-ignore-order` has lower priority that `ivy--regex-plus`, since I always use `ivy--regex-plus`. But any bug reports regarding `ivy--regex-ignore-order`, and especially PRs are welcome.

**Comment by muirrn** [comment]
Thanks, works now, except `ivy--regex-ignore-order` uses the first match face for all matches. I think I know what you are going to say, though 😄

**Comment by muirrn** [comment]
Also probably related: with `ivy--regex-ignore-order` each match is advanced individually rather than as a group:

1. Set regex mode to `ivy--regex-ignore-order`
1. Insert `foo bar foo bar`
1. swiper-isearch for `foo bar`
1. Press `C-s` (`ivy-next-line-or-history`) and notice highlight advances from `<foo> bar foo bar` to `foo <bar> foo bar`. With `ivy--regex-plus` it advances from `<foo bar> foo bar` to `foo bar <foo bar>`.

**Comment by abo-abo** [comment]
> Also probably related: with `ivy--regex-ignore-order` each match is advanced individually rather than as a group

I thought of this more as a feature than a bug. This behavior can be modified in `swiper--isearch-filter-ignore-order`.
