### ISSUE TITLE
Ivy-occur edit mode doesn't affect original file

### ISSUE THREAD

**Issue by Opioid** [abo-abo/swiper#2156]
I make a swiper search and type _C-c C-o_ to open Ivy-occur buffer. With _M-x occur-edit-mode_ I make the buffer editable and do some changes. Then I commit by typing _C-c C-c_. But nothing gets reflected in the original file. The built-in _occur_ command plus _e_ works like that, so I assumed it would be similar with Ivy-occur. Is the workflow different?

**Comment by leungbk** [comment]
`C-x C-q` in the `ivy-occur` buffer puts you into the editing mode, and after making your edits, `C-x C-s` should commit the changes.

**Comment by Opioid** [comment]
Ah, thanks! I saw wgrep in the help text but didn't think it is the thing I want, so never tried...

**Comment by Opioid** [comment]
I just tried it on a different machine. After editing the occur buffer and typing `C-x C-s`, I get the message "There are X unapplied changes. (0 changed)". Nothing changes in the original file. I don't know why it worked on one machine, but not the other. I don't remember having done anything differently.

**Comment by abo-abo** [comment]
@Opioid

Please test on your other machine by using `make plain`.

**Comment by Opioid** [comment]
I'm sorry, but I searched and couldn't find what `make plain` means. Is it some command I should run?

**Comment by abo-abo** [comment]
Yes, it's basically Emacs without any config, except ivy:

```sh
git clone https://github.com/abo-abo/swiper/
cd swiper
make plain
```

You do need to have `wgrep` though, so do:

```elisp
(add-to-list 'load-path "...wgrep")
(require 'wgrep)
```

**Comment by Opioid** [comment]
OK, I finally managed to do this. The result however still is: `There are X unapplied changes. (0 changed)`

**Comment by abo-abo** [comment]
Please add more info: a sample buffer contents, and a sequence of commands that you called.

**Comment by Opioid** [comment]
Sample buffer:
`asoiernkvxc patter nas;oiukdlnf
er906jkdlfgkn pattern adsfl;xcbnopd
;lkdfukdcn pattern xvcoidrtkl`

1. Put cursor on between the tt of patter in first line
2. `M-x swiper-thing-at-point`
3. `C-c C-o`
4. `C-x C-q`
5. Edit each line
6. `C-x C-s`
7. There are X unapplied changes. (0 changed)

**Comment by abo-abo** [comment]
Thanks, I can reproduce.

**Comment by abo-abo** [comment]
Seems that `swiper-isearch-thing-at-point` doesn't have this problem.

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by abo-abo** [comment]
We now have an automated test that check this behavior.

**Comment by Opioid** [comment]
It works now, thanks!

**Comment by allenryb** [comment]
I come across the same problem under the latest swiper and wgrep. 

`M-x swiper` and `M-x swiper-thing-at-point` will lead unapplied changes after `wgrep-finish-edit` in `ivy-occur`.
But `swiper-isearch-thing-at-point` works fine.

**Comment by abo-abo** [comment]
@allenryb Can't reproduce it. If you can reliably reproduce it, please open a new issue.

**Comment by allenryb** [comment]
@abo-abo Thanks for your reply!

It's strange for me that all things are fine today.

**Comment by shoukei** [comment]
I had the same problem. In my case I found out that it didn't commit changes if the buffer was in "Visual Line mode". Changing it to "Truncate Long Lines" or "Wrap at Window Edge" solved the problem. Hope that this helps.

**Comment by TheSirC** [comment]
> I had the same problem. In my case I found out that it didn't commit changes if the buffer was in "Visual Line mode". Changing it to "Truncate Long Lines" or "Wrap at Window Edge" solved the problem. Hope that this helps.

I could not understand how to change this behavior and now I can reproduce this *systematically* : this is a bug.
