### ISSUE TITLE
swiper-thing-at-point moves focus to last search result

### ISSUE THREAD

**Issue by Opioid** [abo-abo/swiper#2157]
When using _swiper-thing-at-point_ the last search result will be selected in the mini-buffer and focus in the main buffer will also move there. (This is different from using swiper and typing whatever is at point, wich will not move the focus and also select the result that is closest to cursor.)
Is there a setting so that _swiper-thing-at-point_ will mark the current cursor position as the first result?

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by Opioid** [comment]
Works for me!
