### ISSUE TITLE
swiper-isearch directon change

### ISSUE THREAD

**Issue by Ergus** [abo-abo/swiper#2158]
Hi:
This is not really an issue, but more like a question. When I am searching with swiper and I want to go back actually I use `C-p`/`C-n`, but I want to bind also C-r.

The question is:
1) The cursor does not move to the other extreme of the candidate (like in isearch) when inverting the candidate; is it possible to enable that somehow?
2) The previous point 1) could be solved toggling between `swiper-isearch` <-> `swiper-isearch-backward`. But when I set `C-r` as `swiper-isearch-backward` in the swiper map the prompt opens empty so maybe I am missing something.
3) My actual workaround is to bind `C-r` to `ivy-previous-line-or-history` but this keeps the point one and maybe should be commented in the documentation.

Is it there a better recommended way to solve this?

Thanks in advance,
Ergus

**Comment by abo-abo** [comment]
Thanks. This should work now:

```elisp
(define-key swiper-isearch-map (kbd "C-r") 'ivy-previous-line-or-history)
```
