### ISSUE TITLE
ivy action to insert ag match into current buffer at point

### ISSUE THREAD

**Issue by drorbemet** [abo-abo/swiper#216]
This is more of an emacs lisp programming question I think. Anyway maybe it could serve as a helpful example for using ivy-set-action with counsel-ag.

I am trying to implement the following operation:
1. being in a editable text buffer at this-point I call counsel-ag and select a match in ivy-buffer
2. then I call insert-matching-sexp (my new action provided by ivy-set-action)
3. The sexp sourrounding the match is inserted before this-point (maybe with an additional newline).
4. The file buffer containing the match is other-buffer (optionally) or closed or not shown (temp-buffer?)

I am uncertain about the way to implement this. 
How to handle multiple buffers their points and how to copy a region over to an other buffer (not appending but inserting preserving all other content of the buffer). 
Should I pull the text into current buffer or send it to an other buffer?
Should I use a temp-buffer in a with-current-buffer?
Should I use the kill-ring and keep the text in kill-ring for just in case I might need it?

Here is the preparation for my first draft looking for a generic and adaptable implementation for this kind of operation.
```elisp
(ivy-set-actions
 'counsel-ag
 `(("i"
    (lambda (x)
;; I could do this in a temp buffer I don't want to open the match in an editable buffer.
;; alternatively it would be usefull to open the match in other-buffer but keeping focus at this-point
      (counsel-git-grep-action x)
      (with-ivy-window
        (beginning-of-defun)
        (narrow-to-defun)
        (mark-sexp)
        ;; How to copy the region and yank it into text buffer before this-point?
        (insert-befor-this-point region-with-sexp-sourrounding-ag-match)))
    "insert sexp")))
```

**Comment by abo-abo** [comment]
The code is straightforward (while what it implements may not be): just extract stuff from `counsel-git-grep-action`, use `with-temp-buffer` and `thing-at-point`.

```elisp
(ivy-set-actions
 'counsel-ag
 `(("i"
    (lambda (x)
      (when (string-match "\\`\\(.*?\\):\\([0-9]+\\):\\(.*\\)\\'" x)
        (let* ((file-name (match-string-no-properties 1 x))
               (line-number (match-string-no-properties 2 x))
               (str (with-temp-buffer
                      (insert-file-contents
                       (expand-file-name
                        file-name
                        counsel--git-grep-dir))
                      (goto-char (point-min))
                      (forward-line
                       (1- (string-to-number line-number)))
                      (substring-no-properties
                       (thing-at-point 'defun)))))
          (with-ivy-window
            (insert str))
          (unless (eq ivy-exit 'done)
            (swiper--cleanup)
            (swiper--add-overlays
             (ivy--regex ivy-text))))))
    "insert sexp")))
```

**Comment by drorbemet** [comment]
Thanks a lot for this template.
