### ISSUE TITLE
"ivy-immediate-done" returning empty string

### ISSUE THREAD

**Issue by muirrn** [abo-abo/swiper#2165]
1. `emacs -Q -L . -l ivy.el` in "swiper" project directory
1. `(ivy-mode t)`
1. `(message "dir %s" (read-directory-name "Test: "))`
1. select some directory and run `ivy-immediate-done` (i.e. `C-M-j`)

For me this prints "dir " instead of "dir /whatever/you/picked".

**Comment by abo-abo** [comment]
Thanks. Please test and review the commit message for context.

**Comment by muirrn** [comment]
Thanks for looking. That change always returns the default directory instead of the current input. Using the above example (assuming you are in swiper project), navigate to "swiper/targets" then run `ivy-immediate-done`. It returns "swiper/" instead of "swiper/targets".

**Comment by abo-abo** [comment]
Thanks for testing. I have now added an automated test for this.

**Comment by muirrn** [comment]
Seems to work now, thanks.

**Comment by muirrn** [comment]
I've realized this still doesn't work when you remove directories from the path instead of adding them. For example:

1. Run `(message "dir %s" (read-directory-name "Test: "))` in "foo/bar"
1. Run `ivy-backward-delete-char` to remove "bar" from the path.
1. Run `ivy-immediate-done` and notice it produces "foo/bar" instead of "foo/".
