### ISSUE TITLE
swiper-minibuffer-faces used but not defined in ivy.el

### ISSUE THREAD

**Issue by joostkremers** [abo-abo/swiper#217]
Just installed swiper / ivy as a replacement for ido and I'm running into an issue. When I start Emacs and then try to find a file with `C-x C-f`, completion does not work properly. In the `*Messages*` buffer, the following error appears:

```
Error in post-command-hook (ivy--exhibit): (void-variable swiper-minibuffer-faces)
```

I noticed that `swiper-minibuffer-faces` is used in `ivy.el`, but `ivy.el` does not depend on `swiper.el` (rather it's the other way around).

Putting `(require 'swiper)` in my `init.el` file solves the issue, but the README doesn't say this is necessary.

**Comment by abo-abo** [comment]
Thanks, my mistake not to notice the circular dependency.
