### ISSUE TITLE
Bad behavior when input "/" with counsel-find-file?

### ISSUE THREAD

**Issue by honmaple** [abo-abo/swiper#2171]
According to [Changelog](https://github.com/abo-abo/swiper/blob/36045f71e0057d52ff4994cad8147f906f3327c0/doc/Changelog.org) `Add magic slash that changes the directory`

This is very strange, I want to create a new directory, but it will auto enter an exist directory when I input `list/`
![ivy](https://user-images.githubusercontent.com/12235570/61970369-3a435500-b00f-11e9-8447-2a213283bd78.png)

This behavior should be disabled by default

**Comment by abo-abo** [comment]
I think the current behavior is useful. Likely many people are used to it. Any ideas to improve the behavior are welcome.

But customizing it in your config is the essence of Emacs, and it's really easy to do.

**Comment by honmaple** [comment]
How can I customize it? 

If I want to enter exist directory, just using `tab` rather than `/`. I will keep my suggestion this is very strange behavior.

**Comment by abo-abo** [comment]
```elisp
(setq ivy-magic-slash-non-match-action nil)
```

You can alternatively use `counsel-set-variable`. Search for "ivy slash", select the "Do Nothing nil" option.

**Comment by honmaple** [comment]
Thank you.
