### ISSUE TITLE
Double slash stopped working with ediff

### ISSUE THREAD

**Issue by drot** [abo-abo/swiper#2175]
With <kbd>M-x</kbd> `ediff` I cannot use the double slash anymore to get back to the root directory.

Tested with `GNU Emacs 27.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.10, cairo version 1.16.0) of 2019-07-30`, `ivy-20190726.2134`

**Comment by karstenpatzwaldt** [comment]
Same for me, independent of ediff. Cannot access tramp anymore after updating ivy.

Same ivy version (ivy-20190726.2134), emacs built fresh from master.

**Comment by abo-abo** [comment]
I can't reproduce on my machine. What's your config? Can you reproduce with `make plain`? Can you try it on 26.2?

**Comment by drot** [comment]
Tested with `make plain`, Emacs 27 and 26.2:

![slash](https://user-images.githubusercontent.com/85483/62229258-97e4f200-b3bf-11e9-9bae-03da4a69456e.png)

The prompt gets greyed out for some reason after typing `//`

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by drot** [comment]
Working fine now, thanks!
