### ISSUE TITLE
Selecting with cursor up/down keys from actions

### ISSUE THREAD

**Issue by nerton** [abo-abo/swiper#2176]
I'm testing ivy/counsel after using Helm for a long time and one of my issues is that I can't use the cursor keys to select from the actions list like in Helm.

Yes, the actions have associated keys, but if I don't use a particular action list too often then I don't know the relevant keys, so I have to look for that key on the keyboard, though my fingers are already near the cursor keys, so it would be very convenient to simply select from the list with the cursor keys and enter.

Could we also have cursor key and enter selection in the actions list, besides the current method of pressing a particular key? Thanks.

**Comment by nerton** [comment]
Other also have this problem and think it's one of the things which helm does better:

https://www.reddit.com/r/emacs/comments/5txzfd/is_it_just_me_or_is_counselivy_way_way_better/ddq05rb/

It would be great if the helm way could also be incorporated into ivy, beside the current one.

**Comment by abo-abo** [comment]
Thanks. Please test.

**Comment by nerton** [comment]
I upgraded ivy, restarted emacs, tried counsel-M-x, pressed M-o for the actions list, pressed cursor down and it threw this error:

`ivy-read-action-by-key: Wrong type argument: characterp, down`

So it's the same as before. Cursor keys cannot be used for selection in the action list.

**Comment by abo-abo** [comment]
You need to set this variable:

```elisp
(setq ivy-read-action-function 'ivy-read-action-ivy)
```

**Comment by nerton** [comment]
Ah, yes. It's working well with that. Thanks for the quick implementation.
