### ISSUE TITLE
swiper-isearch-thing-at-point in swiper and swiper-isearch with char-folding returns no candidates

### ISSUE THREAD

**Issue by gusbrs** [abo-abo/swiper#2177]
When `search-default-mode` is set to `char-fold-to-regexp`, and we make a search with either swiper or swiper-isearch and call `swiper-isearch-thing-at-point` (bound to "M-n") with point on a symbol, the symbol is inserted with symbol regex markers `\_<...\_>` (which is expected), resulting in no matches (which is not expected).

Steps to reproduce. Start `emacs -Q` and do a basic setup:

```emacs-lisp
(package-initialize)
(ivy-mode)
(setq search-default-mode (quote char-fold-to-regexp))
```

Now, find your preferred library, let's say "ivy". Go to any symbol, let's say `ivy-display-style` and place point there. Start swiper or swiper-isearch, and call `swiper-isearch-thing-at-point` with "M-n". The search will be filled with `\_<ivy-display-style\_>`, and no candidates are available/matched, not even the symbol-at-point.

Environment: Emacs 26.2, ivy-20190726.2134, swiper-20190726.1746.

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by gusbrs** [comment]
Working neatly, as usual. Thank you very much!

**Comment by jjnilton** [comment]
I'm having this issue in Emacs 27.1 with swiper-20220430.2247 and ivy-20220406.1052. It seems to happen when using `lsp-mode` and the thing in point is something that the language-server can use a "jump to".
