### ISSUE TITLE
counsel-rg adds leading ./ to results

### ISSUE THREAD

**Issue by ambihelical** [abo-abo/swiper#2180]
Due to a trailing "." on the default counsel-rg-base-command, the results from counsel-rg have a leading "./".  This is different than the output of counsel-ag, and also causes issues with other packages which do not expect relative paths in this format.  For example projectile will consider a file with the leading "./" to be different than a file that it has already indexed without that prefix and consequently cache both. 

The period was added in #795 as a workaround for windows and an old version of ripgrep.  I don't know if it is still needed.  Workaround is easy of course, but this smells like something that should be done with special case code for windows if it is still needed there.

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by ambihelical** [comment]
Works fine under Ubuntu, someone else will have to test Windows, I don't use it.
