### ISSUE TITLE
counsel-find-file does not obey file-name-at-point-functions

### ISSUE THREAD

**Issue by clemera** [abo-abo/swiper#2181]
Hi,

When pressing `M-n` in normal `find-file` the suggested candidates include those from `file-name-at-point-functions`. 

I guess this could be added to `counsel-find-file` by changing how `ivy--minibuffer-setup` sets `minibuffer-default-add-function`. Normal `find-file` uses the items as returned by `read-file-name--defaults`. If there are no objections I will give it a try and make a PR.

Any additional suggestions or input is welcome!

**Comment by abo-abo** [comment]
Please PR. Thanks in advance.

**Comment by clemera** [comment]
After reading the code I believe the best place for the change was in `ivy-thing-at-point`, see the PR. Let me know if anything is missing.
