### ISSUE TITLE
Ivy-switch-buffer path display

### ISSUE THREAD

**Issue by CDitzel** [abo-abo/swiper#2186]
I am using ivy-switch-buffer and all-the-icons-ivy to switch between buffers. However, I noticed that the font size differs from entry to entry and also some buffers are shown with their absolute paths while for others only the buffer name is shown.

![emacs](https://user-images.githubusercontent.com/22954412/62600230-a4e97000-b8ee-11e9-88bd-7185ea980c1e.png)

Why is that and how can I fix that? Also what do the red entries mean?

**Comment by abo-abo** [comment]
Sorry, no idea. Please forward this issue to `all-the-icons-ivy`.

**Comment by CDitzel** [comment]
it seems indeed to be an issue of all-the-icons-ivy, so this can be closed. Thank you!
