### ISSUE TITLE
Please allow counsel-find-file-with-.* tests to run without network access

### ISSUE THREAD

**Issue by sten0** [abo-abo/swiper#2187]
Hi!

Thank you for maintaining Ivy, and thank you for this new release :-)

I've had to use `ert-skip` on the following tests in the Debian package of Ivy/Counsel/Swiper, because network access for building package and for our CI is forbidden: counsel-find-file-with-dollars, counsel-find-file-with-dotfiles, counsel-find-file-with-spaces.

As far as I can tell this could be solved by bundling the tests into the release tarball using a release hook (I think this happens on the github side); this especially seems to makes sense as `counsel--setup-test-files` hard-codes a specific commit.  That branch and its history are fairly small I'm not sure if it necessary to remove `.git`...this is usually removed from a release tarball, but if these three tests require a git repo than I think there might be an argument to be made about how actual history is more valuable for reproducible builds than a dummy recreated history that would have random commit hashes.

Cheers,
Nicholas

**Comment by abo-abo** [comment]
Thanks.

**Comment by sten0** [comment]
Oleh Krehel <notifications@github.com> writes:

> Thanks.

Thank you for accommodating the request of a Debian packager :-) BTW,
would you be willing to answer a few questions about building the HTML
docs from ivy.org in another issue?  The objective is to provide and
option for offline documentation to Debian (and derivatives such as
Ubuntu) users.

**Comment by abo-abo** [comment]
Sure. Ask your question :)

**Comment by sten0** [comment]
Oleh Krehel <notifications@github.com> writes:

> Sure. Ask your question :)
>

Thanks! :-)

Are jquery, bootstrap, and the theme from
https://github.com/fniessen/org-html-themes all the web things that are
needed?  (the copy I build must function offline)   Do you export or
publish directly from the org file, or generate the HTML docs from the
texinfo (which has been generated from the org file)?

Also, would it be possible to change the documentation license?  I
didn't ask before, because I assumed you wouldn't want to.

In a nutshell the GFDL front and back cover invariant sections block
inclusion into the Debian archive; at this point in time I'm working on
the package for inclusion into the "non-free" section, but many users
do not enable this section.  For the documentation to be available to
all users, one of the following changes is needed:

The most desirable option from a Debian perspective is GPL-3+, but
GFDL-NIV-1.3+ works too.  To make it NIV (no invariants), the
restriction on front and back texts must be dropped, along with any
other invariant sections.


Sincerely,
Nicholas

**Comment by sten0** [comment]
A slightly longer explanation of the problem and fix: https://wiki.debian.org/qa.debian.org/gfdlinvariant

**Comment by abo-abo** [comment]
> Are jquery, bootstrap, and the theme from https://github.com/fniessen/org-html-themes all the web things that are needed? (the copy I build must function offline)

Yes.

> Do you export or publish directly from the org file, or generate the HTML docs from the texinfo (which has been generated from the org file)?

I export like this:

    cd swiper
    git clone -b gh-pages https://github.com/abo-abo/swiper gh-pages
    cd gh-pages
    make index.html

> Also, would it be possible to change the documentation license? I didn't ask before, because I
> assumed you wouldn't want to. In a nutshell the GFDL front and back cover invariant sections block
> inclusion into the Debian archive; at this point in time I'm working on the package for inclusion
> into the "non-free" section, but many users do not enable this section. For the documentation to
> be available to all users, one of the following changes is needed: The most desirable option from
> a Debian perspective is GPL-3+, but GFDL-NIV-1.3+ works too. To make it NIV (no invariants), the
> restriction on front and back texts must be dropped, along with any other invariant sections.

OK, I copied the "Good license" variant.
