### ISSUE TITLE
counsel-imenu: jump to definition on candidate select

### ISSUE THREAD

**Issue by rgtk** [abo-abo/swiper#2188]
With `swiper`, selecting a candidate temporarily moves buffer to its location for a preview.
`counsel-imenu` which shares the same interface does not have this behavior.

Updating buffer location on candidate selection is very valuable as it gives context while searching desired target.
`counsel-imenu` users would benefit with it.

Does anyone have an idea if that would be easy to implement and maybe give some tips?

**Comment by abo-abo** [comment]
You can press <kbd>C-M-n</kbd> in place of <kbd>C-n</kbd> to move. This applies to any Ivy commands.

**Comment by rgtk** [comment]
The behavior I have in mind is doing it anytime new candidate is selected, just as in `swiper`.

**Comment by abo-abo** [comment]
Thanks. You can now configure:

```elisp
(ivy-configure 'counsel-imenu
  :update-fn 'auto)
```

**Comment by manuel-uberti** [comment]
Doesn't seem to work on my `init.el`:
```
Error in post-command-hook (ivy--queue-exhibit): (wrong-type-argument listp #("Variables: mu-initial-file-name-handler-alist" 0 9 (idx 0 face ivy-grep-info) 9 45 (idx 0)))
```

**Comment by abo-abo** [comment]
@manuel-uberti Thanks, please test.

**Comment by manuel-uberti** [comment]
A different error this time. `counsel-imenu` starts, but as soon as I start typing I get:
```
Error in post-command-hook (ivy--queue-exhibit): (wrong-type-argument integer-or-marker-p nil)
```

**Comment by abo-abo** [comment]
@manuel-uberti Thanks again. Please test. Again :)

**Comment by manuel-uberti** [comment]
No error this time, but there is no movement in the buffer while I type. I mean, it is behaving like it was behaving before, but I think OP wanted a sort of live movement similar to Swiper/Isearch.

**Comment by abo-abo** [comment]
@manuel-uberti Did you do this config?

```elisp
(ivy-configure 'counsel-imenu
  :update-fn 'auto)
```

It's not on by default.

**Comment by manuel-uberti** [comment]
Had to restart Emacs. Now it is working. Fantastic, thank you!

**Comment by atanasj** [comment]
I know this issues is closed, but where do I add the below to by config?

```emacs-lisp
(ivy-configure 'counsel-imenu
  :update-fn 'auto)
```

I tried to just paste it in, or add it in but I get an error and it wont load it... Any help is greatly appreciated. Thanks in advance.

**Comment by abo-abo** [comment]
@atanasj I've just tested and the code still works. Here's what I did:

In this repo, add this code to `targets/plain.el`:

```elisp
(ivy-configure 'counsel-imenu
  :update-fn 'auto)
(global-set-key (kbd "C-c i") 'counsel-imenu)
```

Run `make plain`. Open e.g. `ivy.el` and <kbd>C-c i C-n</kbd>. Works as expected.
