### ISSUE TITLE
Ivy candidates wrapping past end of line

### ISSUE THREAD

**Issue by sooheon** [abo-abo/swiper#219]
Same as this: https://github.com/abo-abo/lispy/issues/117 

<img width="690" alt="screen shot 2015-09-10 at 11 38 24 am" src="https://cloud.githubusercontent.com/assets/302945/9778810/770622c6-57b0-11e5-998a-8ff224bb9cf1.png">

This occurs with all matches that are too long, M-x candidates, file names, search results, etc.

**Comment by abo-abo** [comment]
Thanks, I haven't tested it for `(fringe-mode 0)`, should work fine now.
