### ISSUE TITLE
`ivy-call` (C-M-m etc.) does not work with `describe-function`, `describe-variable`

### ISSUE THREAD

**Issue by stepnem** [abo-abo/swiper#2191]
emacs -Q

M-x ivy-mode

C-h f

C-M-m

;;;=> nothing happens

The problem is not limited to C-M-m; actions don't work in ivy-occur either.

Tested with Emacs 26 and 27 and ivy from current master, but the
problem has been there as far as I can remember (months/years).

**Comment by abo-abo** [comment]
This is a known limitation of built-in Emacs functions, for which there's no work-around.

But if you use `counsel-describe-function`, actions and occur work as expected.

You can also use `counsel-mode` to set up upgrades for many built-in functions.

**Comment by abo-abo** [comment]
Closing the issue as resolved.
