### ISSUE TITLE
ivy-yank-word should respect case folding

### ISSUE THREAD

**Issue by raundn** [abo-abo/swiper#2194]
Hey!

I've noticed the following annoyance when using `C-s M-j`: it doesn't respect case folding.

In general, swiper does work with case folding: searching for "firstname" finds both "firstname" and "FirstName", while searching for "FirstName" only finds "FirstName".

Thus, if I place the point at the beginning of text "FirstName", type 'C-s f' (to start searching for 'f') and then press `M-j`, I expect to yank "irstname", not "irstName" (which is what happens).

As it is now, pressing 'C-s f M-j' results in searching for "firstName", which finds neither "firstname" nor "FirstName". 

And yes, `C-s C-w` (i.e. `isearch-yank-word-or-char`) does respect case folding.

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by raundn** [comment]
Works great, thanks!

**Comment by basil-conto** [comment]
> `ivy-yank-word` should respect case folding

And ideally, the user option `search-upper-case` which also affects yanking.
