### ISSUE TITLE
ivy-hydra, ivy-resume and ivy-dispatching-done

### ISSUE THREAD

**Issue by gusbrs** [abo-abo/swiper#2195]
When adding a new action to an Ivy command, and when using `ivy-hydra`, calling `ivy-resume` will set the last selected action in `ivy-dispatching-done` as default action.

Start with `emacs -Q`, and perform some basic setup:

```emacs-lisp
(package-initialize)
(require 'ivy-hydra)
(ivy-mode)
(ivy-add-actions
 'ivy-switch-buffer
 '(("n"
    (lambda (x)
      (message "Oh, man!"))
    "do nothing")))
(global-set-key (kbd "C-c C-r") 'ivy-resume)
```

Call `ivy-switch-buffer` with "C-x C-b", call `ivy-dispatching-done` with "M-o". The hydra is then:

![Selection_001](https://user-images.githubusercontent.com/19410606/62822254-48d55480-bb57-11e9-932e-4ce3f0281ebe.png)

Select action "n", to "do nothing". Now call `ivy-resume` with "C-c C-r", and then again `ivy-dispatching-done` with "M-o". As shown, the new action is set as the default action, in this case. Hitting "n" works, and hitting "o" will perform "do nothing".

![Selection_002](https://user-images.githubusercontent.com/19410606/62822255-4f63cc00-bb57-11e9-8f8c-2cadcfdb91c7.png)

I’m not really sure this is not expected behavior. I can indeed rationalize it as `ivy-resume` also "resuming" the last action, similar to `ivy-dispatching-call`. But, the same behavior does not occur when `ivy-hydra` is not in use. In this case, calling "do nothing", then `ivy-resume` and then calling "M-o o" will switch to the selected buffer, and not "do nothing". So, this behavior might be unexpected, thus the report. If it is expected, just close this.

Note: I wrote this assuming the effect resulted from my custom action. Further testing showed me it also happens for the default actions in `ivy-switch-buffer` (I haven’t tested, but possibly in other ivy commands). But the replication steps are already circumscribed enough for you to isolate the described behavior, I think.

Environment: Emacs 26.2, ivy-20190809.1551, ivy-hydra-20190731.1602.

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by gusbrs** [comment]
Tested, and it's working nicely. Thank you very much.

**Comment by gusbrs** [comment]
@abo-abo Let check one thing with you about this issue. I was not sure about what the expected behavior was for `ivy-resume` regarding the default action. (I didn't find anything explicit in the docs, but I might well have missed it). However, the resolution you gave here suggests the default action should not be restored when calling `ivy-resume`.

If this presumption is correct, this is working fine, as reported, for `ivy-dispatching-done`, with or without `ivy-hydra`.

However, the behavior of `ivy-done` ("RET") still uses a changed default action, when calling `ivy-resume`. So that when calling `ivy-resume` "RET" behaves differently of "M-o o". Is this expected? If not, would you prefer I extend the report here, or open a new issue?

**Comment by abo-abo** [comment]
I think it's working fine right now. One major application of `ivy-resume` is to fix typos, e.g. you select not the candidate you meant but the one really close. So you do <kbd>C-c C-r C-n RET</kbd> to fix.

The same applies when you select a wrong candidate with an action different than default. It's more ergonomic to fix it with <kbd>C-c C-r C-n RET</kbd> than to choose the same action again via <kbd>M-o</kbd>.

Finally, supposing you really want to change the action in `ivy-resume`, you can do it with <kbd>M-o</kbd>.

**Comment by gusbrs** [comment]
I see. It does make sense indeed. Considering this the main envisaged use case, I get including why `ivy-done` keeps the previous action after `ivy-resume` while `ivy-dispatching-done` does not, the latter being equivalent of the behavior of `ivy-dispatching-call` for which the current action reverts to the default one after it's called. Thank you for considering and answering. Cheers!
