### ISSUE TITLE
Can't get fd working with counsel-file-jump

### ISSUE THREAD

**Issue by andreyorst** [abo-abo/swiper#2196]
Not related to #1926.

I've set my `find-program` to `fd` like this:

```emacs-lisp
(setq find-program "fd"))
```

After that I've set up `counsel-file-jump-args`:

```emacs-lisp
(setq counsel-file-jump-args (split-string "-L --type f --hidden")))
```

And when I use `counsel-file-jump` I get truncated names:

![image](https://user-images.githubusercontent.com/19470159/62853417-ef0a9100-bcf4-11e9-9055-5140c967f590.png)
those are `.bashrc`, `.zshrc`, and `.gitconfig`.

I've inspected the code and saw that ` counsel--find-return-list` truncates the line by 2 characters:

https://github.com/abo-abo/swiper/blob/20d604c139b82d98010aabbbc00ad487438bdf8e/counsel.el#L2611-L2612

Assuming that input was `./.bashrc`, `./.zshrc`, and `./.gitconfig` truncating will result to proper file names. However `fd` omits `./` in the beginning of the path, which leads to my problem.

How should I migrate this?

**Comment by andreyorst** [comment]
I can get it working with ripgrep but since `counsel-file-jump-args` is now a list, how do I specify `--glob '!.git/` argument for `rg`?

All of these isn't working:

```emacs-lisp
'("." "--files" "--glob '!.git/'")
'("." "--files" "--glob" "'!.git/'")
'("." "--files" "--glob" "\\'!.git/\\'")
'("." "--files" "--glob" "\"!.git/\"")
```

**Comment by abo-abo** [comment]
Thanks, please test. The "./" issue should be gone now. If there's still something missing, please open a new issue.

**Comment by andreyorst** [comment]
Yes, everything works as expected now
