### ISSUE TITLE
completion ignores candidates other than the 1st directory while find-file

### ISSUE THREAD

**Issue by flying-foozy** [abo-abo/swiper#2199]
Completion by TAB key while `find-file` does not work as expected in the case below.

1. completion by TAB causes expansion
2. there are some candidates, even after expansion
3. the 1st candidate is directory

Then, the 1st candidate is automatically selected, even though there is at least one another candidate.
By default, `ivy-sort-file-function-default` is used while `find-file`, and it lists up directories before files. Therefore, this unexpected selection easily occurs.
For example, if there are directory "barfoo" and file "foobar" while `find-file`:

- "f" (or "fo") + TAB causes selecting "barfoo", but
- "foo" + TAB does not

On the other hand, "f" + TAB, "fo" + TAB, and "foo" + TAB cause same result ("foo" is completed, but any one is not yet selected) in cases below:

- if both "barfoo" and "foobar" are file (exactly speaking, "if they are not directory or symlink to directory")
- if sorting makes a file the 1st of candidates (e.g. file "barfoo" comes before directory "foobar", by using `ivy-string<` as sort function for `read-file-name-internal`)

AFAIK, both `ivy-partial-or-done` and `ivy-partial` cause same result.

Is this intentional behavior ? And if so, how can I avoid this automatic selection ?

My environment is:

- ivy 0.12.0, installed via MELPA
- Emacs 25.2.2 on Ubuntu 18.04.3

I can reproduce this behavior after evaluation lisp code below on emacs invoked with `-Q`.

```
(package-initialize)
(ivy-mode 1)
```

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by flying-foozy** [comment]
I confirmed that completion at `find-file` works as expected even in previously problematic case! Thanks!
