### ISSUE TITLE
Support Emacs 24.3: might be as simple as removing one use of window-text-pixel-size

### ISSUE THREAD

**Issue by oantolin** [abo-abo/swiper#220]
It seems to me that removing the unique usage of `window-text-pixel-size` would render ivy usable on Emacs 24.3. I think redefining `ivy--resize-minibuffer-to-fit` as follows works:

```elisp
(defun ivy--resize-minibuffer-to-fit ()
  "Resize the minibuffer window so it has enough space to display
all of the text contained in the minibuffer."
  (with-selected-window (minibuffer-window)
    (fit-window-to-buffer)))
```

**Comment by abo-abo** [comment]
Thanks, I've added a check if the function is bound before using it. Let me know if it works.

**Comment by oantolin** [comment]
Mmh. It doesn't work on Emacs 24.3: before this change, of course, Emacs 24.3 complained about `window-text-pixel-size` being undefined; now, of course, it doesn't have that complaint, but in graphical Emacs 24.3 the minibuffer never gets resized! Which means that you can't see any candidates, only the input line (that also contains the number of matches). On the other hand in text mode Emacs 24.3 `ivy` seems to work just fine.

**Comment by oantolin** [comment]
OK, so I don't fully understand the logic of resizing the minibuffer in ivy in graphical mode vs text mode, but I got ivy to work in Emacs 24.3 by redefining `ivy--resize-minibuffer-to-fit` as follows:

```elisp
(defun ivy--resize-minibuffer-to-fit ()
   "Resize the minibuffer window so it has enough space to display
all of the text contained in the minibuffer."
  (with-selected-window (minibuffer-window)
	(let ((text-height (count-screen-lines))
	      (body-height (window-body-height)))
	  (when (> text-height body-height)
	    (window-resize nil (- text-height body-height) nil t)))))
```

If I understand correctly this is simply a linewise version of the pixelwise version currently in `ivy`. I guess this means that for lines of varying sizes this version won't look as pretty, but so be it. It would be nice to have `ivy` simply use the text mode resizing logic for both text and graphical mode in Emacs 24.3, but I don't know how to make that change yet.

**Comment by oantolin** [comment]
Also, on the topic of supporting Emacs 24.3: for some reason `help-function-arglist` is not autoloaded in 24.3; `ivy` uses that function, but I hadn't noticed because I guess I had always used `ivy` after using some help function. To make `ivy` usable before I call any help function, I used `(autoload 'help-function-arglist "help-fns")`.

**Comment by abo-abo** [comment]
Thanks for the code. It should work fine now.
