### ISSUE TITLE
Document that ivy-read's action function does not necessarily take a string argument

### ISSUE THREAD

**Issue by alphapapa** [abo-abo/swiper#2201]
The docstring and manual for `ivy-read` say that its action argument is a function that takes a string as its argument, e.g.:

```
ACTION is a function to call after selecting a candidate.
It takes the candidate, which is a string, as its only argument.
```

But if the collection is an alist, the action function receives the entire cons as its argument, not only the key string.

This is misleading, but it's also a minor barrier to entry.  For example, I thought that I would have to do the assoc myself based on the string, while Ivy actually handles that itself.

**Comment by abo-abo** [comment]
Thanks.
