### ISSUE TITLE
counsel-rg uses smart-case by default, making case sensitive requires non-obvious configuration

### ISSUE THREAD

**Issue by ideasman42** [abo-abo/swiper#2204]
Currently `counsel-rg` uses smart-case by default `-S`,  One might imagine this can be changed by switching the `-S` for `-s`. eg:

    (setq counsel-rg-base-command
      (replace-regexp-in-string " -S " " -s " counsel-rg-base-command))

Surprisingly, this doesn't work.

After some investigation, it turns out `counsel-rg` calls into `counsel-ag`, specifically 
`counsel-ag-function` is checking `ivy--case-fold-p` and adding `-i` to the end, overriding previously set case settings.

The confusing part of this is - setting only `ivy-case-fold-search-default` or `counsel-rg-base-command` isn't enough, both need to be set, which I don't think is a good state of affairs.

I'd suggest not to default to smart-case, instead, default to being case sensitive, which may be overridden by `ivy-case-fold-search` (which is on by default).

Or alternately, the `counsel-ag` command could be used in a way that doesn't adjust arguments for `counsel-rg`.

**Comment by abo-abo** [comment]
Thanks.
