### ISSUE TITLE
counsel-find-file does not work as intended in Tramp when M-x dired-do-copy or M-x copy-file is triggered. It does not go to local when `\ C-j` is pressed. File path stays in the same directory

### ISSUE THREAD

**Issue by CsBigDataHub** [abo-abo/swiper#2205]
I am using `dired-do-copy` to copy a file from remote using tramp to local. 
When Copy file to path is promted. I used `/ C-j` to go to local path but the path stays in the same directory , does not go to local root from remote.

I have also tried `M-x copy-file` , `M-x gnus-copy-file` and I have having the same issue as above.

Emacs version - 26.2
Local Os - MacOs
Remote server OS(Tramp) - RHEL
Swiper version - 20190708.1110

Steps to replicate -

1.  Login to a remote using tramp
2. Open a directory in remote using dired.
3. Mark a file to copy, and run `M-x dired-do-copy`.
4. Swiper will prompt the path.
5. Type '/ C-j' to go to local.
6. The path stays the same.
7.  same thing happens to `M-x copy-file` in tramp mode too.

Trying to implement this functionality - https://superuser.com/questions/445564/how-do-you-copy-files-from-a-remote-server-to-a-local-folder-in-emacs-using-dire/445568

**Also is there a way to disable counsel-find-file/IVY when dired-do-copy is triggered.**

![2019-08-20_10-26-49](https://user-images.githubusercontent.com/23665525/63363207-d0317d80-c338-11e9-8115-6dba56c7c9c0.png)

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by CsBigDataHub** [comment]
@abo-abo Thanks . It's working now.

**Comment by LauraBMo** [comment]
Just for the record, `C-j` is `ivy-alt-done`
