### ISSUE TITLE
Please include full-text copies of GPL-3+ and GFDL-1.3+

### ISSUE THREAD

**Issue by sten0** [abo-abo/swiper#2206]
Hi,

Thanks again for maintaining Ivy/Swiper/Counsel! :-)  While packaging the info page for Debian (must be distributed in a separate package in our non-free section because of front-cover and back-cover modification restriction), I noticed that `doc/ivy.org` doesn't include the required full-text copy of the GFDL-1.3+, and also that a GPL-3+ full text also isn't provided.  Would you please add both of these files somewhere in your repository?

For your convenience, here are links:
https://www.gnu.org/licenses/gpl-3.0.txt
https://www.gnu.org/licenses/fdl-1.3.txt

Thanks!
Nicholas

**Comment by abo-abo** [comment]
Thanks.

**Comment by sten0** [comment]
Oleh Krehel <notifications@github.com> writes:

> Thanks.
>

You're welcome :-)  Thank you for the quick fix!
