### ISSUE TITLE
Allow user to customize prompts

### ISSUE THREAD

**Issue by chiply** [abo-abo/swiper#2208]
For example, with swiper, it would be nice to change the prompt from Swiper to something else -ideally an icon.  I've modified the source on my machine and have gotten this to work.  PRs welcome?

**Comment by abo-abo** [comment]
This functionality is already available:

```elisp
(ivy-set-prompt 'swiper (lambda () (format-time-string "%H:%M swiper: ")))
```

**Comment by chiply** [comment]
Got it - closing this issue.  Thanks!
