### ISSUE TITLE
Use :update-fn with current match

### ISSUE THREAD

**Issue by ema2159** [abo-abo/swiper#2210]
I'm creating a custom `counsel-load-theme` and want to preview the currently matched theme. How can I do this?

**Comment by ema2159** [comment]
Done, I did `:update-fn (lambda() (counsel-load-theme-action (ivy-state-current ivy-last)))`

**Comment by abo-abo** [comment]
Note that `:update-fn 'auto` serves exactly the same purpose.

**Comment by ema2159** [comment]
@abo-abo, is there something like a timer? The theme loading it's a little bit slow so it's undesired to load a theme each time I type something. It would be very nice if it had an idle timer option like `company` that makes the function take effect after a certain amount of idle time.

**Comment by abo-abo** [comment]
Changing a theme is a synchronous action, it will block the input until it's done.

A quick improvement would be to check if the "new" theme is actually the current one and do nothing in that case.

You can also add timers afterwards, see for example how `swiper--delayed-add-overlays` works.
