### ISSUE TITLE
After last changes I can't use counsel-rg

### ISSUE THREAD

**Issue by Ergus** [abo-abo/swiper#2212]
It is not giving any candidate and when I try to paste a string I only get this message:

Error in post-command-hook (ivy--queue-exhibit): (invalid-function with-connection-local-variables)

**Comment by manuel-uberti** [comment]
I just upgraded it from MELPA and it's working for me. Could you try updating or provide a recipe to reproduce the problem from `emacs -Q`?

**Comment by Ergus** [comment]
Hi:
I just tried with the `make plain` command in the swiper repo and I get the same error. So the problem could be in ivy or in the actual master branch of emacs.
I just try M-x counsel-rg RET candidate.

And I get nothing.

**Comment by abo-abo** [comment]
@Ergus

> with-connection-local-variables

This function is not used anywhere in Ivy.

> I just tried with the make plain command in the swiper repo and I get the same error

Can't reproduce with the latest build of Emacs master, commit df20cbe075. ripgrep 0.10.0 (rev 8a7db1a918).

**Comment by Ergus** [comment]
This seems to be related with:

https://debbugs.gnu.org/34808

and with ivy this issue was exposed before.
