### ISSUE TITLE
Feature Request - Add mark toggling functions

### ISSUE THREAD

**Issue by ambihelical** [abo-abo/swiper#2214]
I discovered only by accident that ivy has candidate marking functionality.  There are no bindings as far as I can tell and it doesn't seem to be very well documented.  However, I think the defined functions are suboptimal.  

It would be useful if there is a function that toggles the mark and moves to the next line.  This really is the only function that should be bound since it provides the functionality of mark and unmark.  Once you've marked a candidate there's no reason to stay on the same candidate since your action will apply to it anyway, so there's no need for a toggle mark without the convenience of moving to the next candidate.

**Comment by abo-abo** [comment]
> There are no bindings as far as I can tell and it doesn't seem to be very well documented. However, I think the defined functions are suboptimal.

The marking is now documented in the manual. The marking model is made after `dired`, so it's very familiar to users.

> It would be useful if there is a function that toggles the mark and moves to the next line

You mean outside `ivy-hydra`? What key binding to you suggest for that? All the good ones are already taken.

**Comment by ambihelical** [comment]
Thanks for the doc update.  I'm not sure about the utility of using dired as a model, but I think dired could also benefit from a mark and next line functionality, marking a sequence of files isn't an uncommon thing to do.  But that monster already has enough bindings. 

I don't know what a good binding would be because I'm an evil user and have  changed many of the ivy bindings so they work better for me.  But for a default binding, I'm surprised that there is no useful emacs keybinding that you can overload because it doesn't make sense in the minibuffer environment.  I use C-SPC for my personal config implementation of the feature, but that might interfere with non-evil editing, I don't know.  No binding would be fine by me, the function itself could be useful to others, if there's no default binding they can bind it if they want it. 

I have tried ivy-hydra, and it was useful as a crutch, but in the end found a way to have which-key show me ivy bindings when I forget (basically I duplicate all but the basic ones on the C-c prefix key), and this helps me learn key bindings over time.  Ivy-hydra actually prevents this learning process.

**Comment by abo-abo** [comment]
> Thanks for the doc update. I'm not sure about the utility of using dired as a model, but I think dired could also benefit from a mark and next line functionality, marking a sequence of files isn't an uncommon thing to do. But that monster already has enough bindings.

It's built-in: <kbd>m</kbd> calls `dired-mark`.

> I have tried ivy-hydra, and it was useful as a crutch, but in the end found a way to have
> which-key show me ivy bindings when I forget (basically I duplicate all but the basic ones on the
> C-c prefix key), and this helps me learn key bindings over time. Ivy-hydra actually prevents this
> learning process.

Ivy-hydra is a key prefix, a modal state if you will. It's not there to duplicate functionality, it's there for bindings that don't fit into the main prefix.

In any case, the command you wanted already exists, you can bind it if you like:

```elisp
(define-key ivy-minibuffer-map (kbd "C-SPC") 'ivy-mark)
```

I think this can be closed now.

**Comment by abo-abo** [comment]
No problem, now you have it.

**Comment by abo-abo** [comment]
No offense taken, I just want to have an extra command in `ivy.el` if it's not bound to anything: these cause me more work when refactoring since I have to look up the reason why they're there. And `ivy-mark` serves just as well as `ivy-toggle-mark-and-next-line`, in my opinion.
