### ISSUE TITLE
Correct way to redefine ivy-current-match face?

### ISSUE THREAD

**Issue by sooheon** [abo-abo/swiper#222]
I am trying to redefine `ivy-current-match` to two colors depending on the background. I've found this SO answer: http://emacs.stackexchange.com/a/9604

What would be the correct place to place add this `face-remap` function as an advice? I can't seem to find the right counterpart to the example in the lispy source.

**Comment by abo-abo** [comment]
This setting should just work, no need for anything fancy:

```elisp
(custom-set-faces
 '(ivy-current-match
   ((((class color) (background light))
     :background "red" :foreground "white")
    (((class color) (background dark))
     :background "blue" :foreground "black"))))
```

The setting above should work for all themes. You can also update those faces in a particular theme.

**Comment by sooheon** [comment]
Thanks. Don't know why the SO answer gets so complex :)
