### ISSUE TITLE
counsel-evil-registers-height unused (and unnecessary maybe)?

### ISSUE THREAD

**Issue by MoHKale** [abo-abo/swiper#2221]
I'll be honest, I found this kind of funny 😄😄😄. In counsel, `counsel-evil-registers-height` is a variable, distinct from `ivy-height` which sets up the height of ivy when the `counsel-evil-registers-height` function is called.

```elisp
(defcustom counsel-evil-registers-height 5
  "The `ivy-height' of `counsel-evil-registers'."
  :type 'integer)
```

I'm not really sure why it's its own unique variable, I'd argue if you really need this kind of functionality, `advice-add` would be a better way to go about it. (apologies in advance for the indentation)

```elisp
(defvar ivy-small-height 5
  "desired height for ivy when using a small potential candidate list")

(advice-add 'counsel-evil-registers-height :around (lambda (func &rest args)
                                                     (let ((ivy-height ivy-small-height))
                                                       (apply func args))))
```

but I'll leave that debate for another time, the problem here is the variable isn't actually used by the function. There's a hardcoded value of 5 in place for that. 

```elisp
(add-to-list 'ivy-height-alist '(counsel-evil-registers . 5))
```

so the height of counsel-evil-registers will always be 5. An easy workaround would be to simply add `(push (cons 'counsel-evil-registers ivy-height) ivy-height-alist)` to your config, after counsels been loaded. 

That said, this still merits fixing. It seems like a small change so I'm willing to make a pull request for it, but should I delete the variable (frankly it seems unecessary) or update the above line so it's actual value is used, instead of the hardcoded 5?

**Comment by MoHKale** [comment]
I opted to keep it around, in case anybody still uses it. 😄.

**Comment by abo-abo** [comment]
Thanks, I removed the variable. It was supposed to be removed when this was added:

```elisp
(add-to-list 'ivy-height-alist '(counsel-evil-registers . 5))
```

The user can override the "5" in their own config.
