### ISSUE TITLE
Action echo area shows only two actions

### ISSUE THREAD

**Issue by halloleo** [abo-abo/swiper#2222]
In `counsel-find-file` when I hit `M-o` the action echo area at the bottom of the frame show two actions ("m - move" and "d - mkdir"):

![ivy-action-area](https://user-images.githubusercontent.com/1521852/64154323-f2b4b200-ce73-11e9-9ee8-36c1fd637fa6.PNG)

However  there are more actions available (e.g. "c - copy"). How can I increase the height of this area to accommodate all actions?

**Comment by abo-abo** [comment]
Can't reproduce. Can you reproduce with `make plain` from this repo?

**Comment by halloleo** [comment]
I found the reason: I had set `max-mini-window-height` to 3, which is obeyed when listing the actions via `M-o`.

Strange thing though is that e.g. the candidate list in `ivy`/`swiper` is not affected by this variable. (That's why I had totally forgotten about `max-mini-window-height`.)
