### ISSUE TITLE
Feature parity between helm-company and counsel-company

### ISSUE THREAD

**Issue by jjzmajic** [abo-abo/swiper#2223]
This is the only reason I still keep helm around now. `counsel-company` only shows completion candidates, while `helm-company` shows candidates, arguments, and types. Are there any plans to add this to counsel?

**Comment by MoHKale** [comment]
could you add a screenshot of the differences? That'd make deciding what to include and how to format it a lot easier.

**Comment by jjzmajic** [comment]
![helm-company](https://user-images.githubusercontent.com/24733181/65812827-b15bbc00-e1ff-11e9-9102-555391cf3669.png)

**Comment by abo-abo** [comment]
@jjzmajic This is what I get with `helm-company`:

![swiper-issues-2223](https://user-images.githubusercontent.com/2937359/66384349-e36adc00-e9be-11e9-8d5e-e1727f0a650a.png)

What kind of config are you using to show the arguments list?

**Comment by jjzmajic** [comment]
Sorry for the delay. Exams. I'm using `lsp-mode` with the accompanying company-backend.

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by jjzmajic** [comment]
Thank @abo-abo. The issue is though that CAPF do not include snippet support and are blocking, hence the inclusion of packages like helm-company even though helm takes over complete-symbol by default.

**Comment by abo-abo** [comment]
@jjzmajic Since `counsel-company` has annotations now, can we close this?

**Comment by jjzmajic** [comment]
Aye, aye! Sorry for the delay
