### ISSUE TITLE
Altering the behaviour of tab (ivy-partial-or-done)

### ISSUE THREAD

**Issue by rburchell** [abo-abo/swiper#2225]
Ivy seems to be very capable and well put together, but there's one small thing that I have trouble adjusting to.

When completing a very small list of items, I have a habit (from other software) of just bashing my way through it with tab, and hitting ret to select.

This of course doesn't work due to the use of ivy-partial-or-done.

I'm not sure what the right way to do this is, so thought I'd open an issue to ask. I wonder if there's a way to allow optional tab cycling, maybe through looking at the completion-cycle-threshold var I stumbled across while trying to figure out what sort of things were involved in this?

**Comment by abo-abo** [comment]
Thanks, please test.
