### ISSUE TITLE
When `ivy-case-fold-search-default` is `auto`, the highlight is always case-insensitive

### ISSUE THREAD

**Issue by xuhdev** [abo-abo/swiper#2226]
Make sure `ivy-case-fold-search-default` is `auto`. Open a buffer and paste in the following:

```
abc ABC
abc abc
ABC ABC
```

Now run `swiper`, and type `ABC`. The second line is not shown in the minibuffer, which is correct. But the first `abc` in the first line is incorrectly highlighted.

**Comment by abo-abo** [comment]
Thanks, please test.
