### ISSUE TITLE
Impossible to create tag with name as existing tag beginning

### ISSUE THREAD

**Issue by tdivis** [abo-abo/swiper#2228]
I have already created release candidate tag `1.0.0-rc1`.

Then I want to create final tag `1.0.0`, in magit-status I pres `t t` and write `1.0.0` and press return to confirm it and then again return to have it on a master branch. Then I get message `tag '1.0.0-rc1' already exists ...`.

Problem is, that tag naming step uses ivy (or  swiper?) to search in existing tag, which is OK to see what tags are there, but not OK for creating new tag, especially in case above.

Vanilla magit doesn't have this problem as it only let you write new tag name.

**Comment by articuluxe** [comment]
Control-Alt-J allows you to accept the precise input you’ve entered, regardless of what it matches.

**Comment by tdivis** [comment]
Oh, OK, didn't know that. It's kinda hard to figure out..

**Comment by abo-abo** [comment]
@tdivis See also `ivy-use-selectable-prompt`. If you set it, you can select the prompt with <kbd>C-p</kbd> and press <kbd>RET</kbd>.
