### ISSUE TITLE
counsel--py-action: make insertion of trailing parens optional, or remove it altogether

### ISSUE THREAD

**Issue by igorhub** [abo-abo/swiper#2229]
After completing a python function, a pair of parens is appended to the end. Most of the time it makes sense, but occasionally it doesn't, forcing the user to remove them by hand.

In my opinion, the benefits of sparing the user two keystrokes (pure muscle memory) in outweighted by the flow-breaking annoyance of having to clean up after wrongful code generation.

The most common case of erroneous parens insertion is, in my experience, completing a function which is passed by value to a higher-order function. Less common one is substituting a similar function that already has a list of arguments.

**Comment by abo-abo** [comment]
Fixed, thanks. By the way, lately I use Python a lot and never use `counsel-jedi`. Instead I use `completion-at-point` after adding `lispy-python-completion-at-point` to `completion-at-point-functions`.

**Comment by igorhub** [comment]
Thank you for your advice. It never occurred to me that I can use lispy for non-sexp languages such as Python. I think I’ll try it some time in the future.
