### ISSUE TITLE
running from a terminal without x cant find fringe mode

### ISSUE THREAD

**Issue by gregnwosu** [abo-abo/swiper#223]
when i try to use swiper it halts says, Symbols value as variable is void: fringe-mode

**Comment by abo-abo** [comment]
Thanks, I've added a check for `fringe-mode` being bound. Let me know if it fixes it; works fine on my end.

**Comment by gregnwosu** [comment]
can i update via melpa?

**Comment by abo-abo** [comment]
Yes, the update should now be in melpa.
