### ISSUE TITLE
Ivy completion buffer is broken when created with active `y-or-n-p` prompt

### ISSUE THREAD

**Issue by kurnevsky** [abo-abo/swiper#2230]
Try to execute the following example:

```elisp
(progn
  (run-with-timer 1 nil (lambda () (ivy-completing-read "b" '("a" "b"))))
  (y-or-n-p "a"))
```

When ivy buffer popups it can't accept any input - all keys are undefined.

**Comment by abo-abo** [comment]
Thanks, please test.

I think the situation is quite rare, so the "fix" is to cancel `y-or-n-p`. Unfortunately, `ivy-read` has to be restarted manually.
