### ISSUE TITLE
Can I use counsel-find-file with read-only mode ?

### ISSUE THREAD

**Issue by ry3s** [abo-abo/swiper#2236]

**Comment by abo-abo** [comment]
Please explain. It's not clear what you're asking.

**Comment by ry3s** [comment]
Is there any cousel's function corresponding to emacs's function `find-file-read-only` ?

**Comment by abo-abo** [comment]
Thanks, you can now use <kbd>M-o R</kbd> to open a file in `read-only-mode`.

**Comment by ry3s** [comment]
Thank you for answering my question!
