### ISSUE TITLE
Searching for numbers matches line numbers in swiper buffer

### ISSUE THREAD

**Issue by joostkremers** [abo-abo/swiper#224]
When searching for a string of digits, swiper will match not only the occurrences of the digits in the buffer you're searching, but also all occurrences in the swiper buffer, i.e., the lines that have a line number containing the digits.

**Comment by abo-abo** [comment]
The previous behavior was the result of a bit of simplification.  The new way, while more user-friendly will have problems for buffers with identical lines. Also some minor errors might pop up, please test.

**Comment by joostkremers** [comment]
The problem with matching the line numbers has disappeared. If I run into any other problems, I'll let you know. Thanks!
