### ISSUE TITLE
counsel-imenu is broken on Emacs 27 master

### ISSUE THREAD

**Issue by mnewt** [abo-abo/swiper#2241]
This is the change that did it:

https://git.savannah.gnu.org/cgit/emacs.git/commit/?id=8635147ccba1fc8e1010010da8c3f8e467562f76

Removing the let-bind in `counsel-imenu` for `imenu-auto-rescan` appears to fix the issue, and indeed, with that variable set to `t`, `imenu--make-index-alist` will never return any results. But I don't understand why that binding was there in the first place so I have trouble saying this is a fix.

What's the proper fix for this?

**Comment by mnewt** [comment]
Update: I sent an email to bug-gnu-emacs since this might be an Emacs bug. See the discussion for bug#30449. I'll update here when I receive a response.

**Comment by mnewt** [comment]
Closing this because the issue is fixed upstream. I tested it and it works for me. See the commit:

https://git.savannah.gnu.org/cgit/emacs.git/commit/?id=8b1af4a0bf82a92374d4e8205057880f7d28ede9

**Comment by abo-abo** [comment]
Thanks for the report and the follow up.
