### ISSUE TITLE
counsel-git-grep to ivy-occur not working with fuzzy matching

### ISSUE THREAD

**Issue by knusprjg** [abo-abo/swiper#2243]
counsel-git-grep with ivy--regex-fuzzy is working as expected. Howevery something goes wrong when trying to channel the results from the minibuffer to ivy-occur. Example:

```
counsel-projectile-grep for "test" -> ivy-occur results:

-*- mode:grep; default-directory: "~/.emacs.d/" -*-

1 candidates:
./fatal: -e option, '\(t\)[^e?': Unmatched [ or [^
```
I guess this is an issue of escapping the regular expression used for fuzzy matching. swiper/counsel-find-file et al seem to do it properly.

(Initially I thought this was an issue of counsel-projectile-git-grep, which turned out to be wrong: https://github.com/ericdanan/counsel-projectile/issues/134.)

**Comment by abo-abo** [comment]
Thanks, please test.
