### ISSUE TITLE
Completion broken with package-menu-filter

### ISSUE THREAD

**Issue by skangas** [abo-abo/swiper#2244]
Steps to reproduce:
1. M-x list-packages RET
2. Hit "f" for package-menu-filter
3. Press TAB to show completions

Result:
The completion list shows an unsorted list with duplicates

Expected result:
There is a sorted list without duplicates

I can reproduce this with ivy 0.11.0, and goes away if I don't use that package.

**Comment by abo-abo** [comment]
Thanks, it seems to be due to a bug in built-in `crm--collection-fn`. I've added a work-around.

**Comment by skangas** [comment]
Thanks for fixing it.
