### ISSUE TITLE
counsel-find-file double slash '//' should always take to '/', even on windows?

### ISSUE THREAD

**Issue by mohkale** [abo-abo/swiper#2248]
On windows, entering a double slash on `counsel-find-file` is inconsistently annoying. Sometimes the prompt is changed to a windows style `c:/` other times it's shown as a literal unix style `/`. 

# Analysis
For example if I start ivy from a path under my home directory, such as `~/.emacs.d/`. running counsel find file shows a prompt of `~/.emacs.d/`. if I enter a double slash now, the prompt changes to `/`. If I switch to a folder not under my home directory, such as `c:/Program Files` (by typing `c:/`, followed by Program Files) and then type double slash, the prompt changes to `c:/`. More peculiarly, if I now enter '~' to return to my home directory (current prompt is `~/`), and then once again type double slash the prompt is now always shown as `c:/` and there's no way to return to the unix style singular `/`.

This only happens if I encounter a path prefixed with `c:/` during the current ivy session, which is something that's not always under my control. If I change my buffers cwd to somewhere under `c:/Program Files` (by opening a dired buffer at that path) & then run `counsel-find-file` again, because the default prompt begins with a `c:/` there's no way ~~that I know of~~ to reach a unix style `/` at all. 

I can cancel the current session, return to a buffer with a cwd under my home directory, run counsel find file and entering a double slash will prompt a unix style `/` until I enter a path which explicitly includes `c:/`.

# The Meaningful Consequence
The inconsistency here is jarring, but tolerable, however the real problem lies in the fact that tramp autocompletion only work from the unix style path (root begins at `/`) not the windows style. What I mean by this is the protocol options for tramp only show when entering from a unix style root path and they're completely non existant when entering from a windows style path. This means in some cases you won't get any completion help for hostnames (parsed from your ssh config) either, because they only show after you select a protocol. The following images describe this affect (I've used a regex of `:$` to match them):

![Capture](https://user-images.githubusercontent.com/23294780/65811434-28696400-e1b0-11e9-8471-9ad288cb1e5e.PNG)
![Capture2](https://user-images.githubusercontent.com/23294780/65811436-2a332780-e1b0-11e9-9463-906023bc1e79.PNG)

What this means that in some cases, to access tramp, you need to cancel you're current find file session and switch to buffer with a cwd under your home directory (or use it to first goto a file under your home directory) and then restart `counsel-find-file` and then double slash and then finally you get reasonable autocompletion for tramp.

# An Easy Fix
So my suggestion, just have `//` when entered at the end of a path, always take you to a unix style `/` root. The mount/drive in question which you're taken to should be the mount of whatever file you were looking at prior. Entering `d:/` should have the same behaviour as now and show a prompt of `d:/`, but entering `//` from this prompt should revert you to a unix style path instead of keeping you on `d:/`.

so here's what entering a double slash on the following paths should do:

* `/` -> `/`
* `c:/` -> `/`
* `~/foo/bar/c:` -> `c:/` (actually only needs a single slash).

if nothing else, I think this'll be a lot less frustrating. At the start I kept wondering why tramp completion wasn't working until it did start working... and then didn't... and that went on until I figured out why? This should make that figuring out part a lot easier (for most people) than it was for me.

**Comment by abo-abo** [comment]
>Thanks, seems reasonable. Can you make a PR?

Emacs on Windows is a mystery to me, since I never use it. I tried to reproduce entering <kbd>//</kbd> in multiple directories, but it always brings me to `c:/`.

    I tried to use TRAMP, but it says "Pseudo-terminal will not be allocated because stdin is not a terminal".
    ssh_askpass: exec(/usr/sbin/ssh-askpass): No such file or directory

What's your setup?

**Comment by MoHKale** [comment]
I'm running on cygwin (not recommended). I'm willing to make a PR... but I'll wait until I've cleared the FSF licensing thing. Might take a while. Sorry 😭😭😭.

**Comment by abo-abo** [comment]
No problem. And thanks in advance :)

**Comment by MoHKale** [comment]
also, probably worth noting, the `//` taking to `/` doesn't seem to work anymore, regardless of where you are. I can only surmise someone fixed the idiosyncracy in another pull request (or something else). Sad thing is... now I can't get completion for tramp at all 😢😭😢.

**Comment by abo-abo** [comment]
It still works fine for me on GNU Linux. Please try to reproduce with `emacs -Q`, maybe bisect to find the commit that broke it.

**Comment by MoHKale** [comment]
I meant on windows. sorry again. I'm sure it still works on linux. 

Update: Tested it on WSL, yeah it still works on linux.

**Comment by MoHKale** [comment]
okay... this might be kind of dumb, but 

```elisp
(defun ivy--magic-file-doubleslash-directory ()
  "Return an appropriate directory for when two slashes are entered."
  (let (remote)
    (cond
      ;; Windows
      ;; ((string-match "\\`[[:alpha:]]:/" ivy--directory)
      ;;  (match-string 0 ivy--directory))
      ;; Remote root if on remote
      ((setq remote (file-remote-p ivy--directory))
       (concat remote "/"))
      ;; Local root
      (t
       "/"))))
```

commenting out the windows condition in this method basically implements what I said above. Entering `//` takes you to the root windows drive (because of what I can only surmise is emacs magic translating `/` to `c:/` in the c code base) but the key point is it shows a unix style `/`. 

Entering a drive letter followed by a slash eg: `c:/mohkale/blarg/hello/e:/` will take you to the `e:/` drive and show `e:/` on the prompt (because of another condition handling such a case in `ivy--magic-file-slash`). entering `/` again now will take you to the default windows drive `c:/` and display a unis style `/`.

I can't think of how we can implement staying in `e:/` when entering a double slash, but showing a unix style prompt without creating two seperate path variables. One for the actual directory and another for the displayed directory... and seeing as the two would be identicle on all systems aside from windows I can't imagine doing that would be worth it.

If this is a good enough fix for you, should I make a pull request for it?

**Comment by mohkale** [comment]
@abo-abo I'm just alerting you about this again, in case the last comment got lost somewhere in your notifications.

**Comment by abo-abo** [comment]
The code that you want to comment out was added in #155 to address #115. Since it looks like the drive switching will still work afterwards, please open a PR. I don't have a Windows machine right now, so I can't make tests.

**Comment by mohkale** [comment]
It's definitely working for me, though I'm not sure how I would test it. I'll open a pull request commenting it out for now.
