### ISSUE TITLE
Is it possible to use flx matching mechanism with this package? 

### ISSUE THREAD

**Issue by hatschipuh** [abo-abo/swiper#226]
Hi,
I'm considering switching to Ivy as my completion framework. I'm curious if it is possible to use the flx matching mechanism for fuzzy completion, which I really like.

**Comment by abo-abo** [comment]
There was some success of integrating flx by #bling in #207. So it's possible, but it's a lot of work to do it right, so it might take a while before the feature is ready.

**Comment by hatschipuh** [comment]
Ok thanks I will join the issue over there if I have something to add.
