### ISSUE TITLE
Insert line with swiper

### ISSUE THREAD

**Issue by JadeSnail** [abo-abo/swiper#2260]
I'd like to find a line with swiper and insert it where my point was.

If I call `swiper`, find a line, then call `ivy-dispatching-done` and select the default insert action, it inserts the line, right where the line is, instead of where my point was, which isn't so useful.

Is this intended behavior ? Any easy way to do what I'd like ?

**Comment by abo-abo** [comment]
You can now use <kbd>M-o w</kbd>, and then <kbd>C-y</kbd>.

**Comment by JadeSnail** [comment]
Thanks
