### ISSUE TITLE
Error in post-command-hook (ivy--queue-exhibit): (error "Attempt to modify read-only object" "auto-composition-mode")

### ISSUE THREAD

**Issue by akoppela** [abo-abo/swiper#2262]
I just upgraded to Emac 26.3 from 26.1 and I get this error everytime I type `au` in `M-x`. I'm using `counsel-M-x`. Please let me know if I should provide more info and which info to provide. Thanks in advance.

**Comment by bymoz089** [comment]
Same here but with: typing `M-x org` from an `org-mode` buffer (this happens **only** when I `M-x` from an org-mode buffer). Using emacs version 25.1..      
Error message: 

    Error in post-command-hook (ivy--queue-exhibit): (error "Attempt to modify read-only object" "org-mode")

This seems to be a bug recently introduced with `ivy/counsel`

**Comment by abo-abo** [comment]
Thanks, please test. @bymoz089 thanks for the pointer.

**Comment by bymoz089** [comment]
Thanks for the lightning fast fix. It works.

**Comment by akoppela** [comment]
I’m very new to Emacs. Could you please point me how could I test the new change? Thanks in advance?

**Comment by akoppela** [comment]
I just upgraded swiper and I can confirm that the issue is gone for me.
