### ISSUE TITLE
Clarification of counsel-mode

### ISSUE THREAD

**Issue by jkroes** [abo-abo/swiper#2264]
(ivy-mode-1) and (counsel-mode 1) utilizes ivy searches for common built-in commands. I assumed this meant that invoking switch-to-buffer invoked the full counsel command; however, invoking counsel-switch-buffer from 'M-x' shows a preview of the buffers that is not available with the built-in command. 

The behavior was surprising, even after reading the ivy/counsel/swiper manual. Looking back, however, I realize counsel-switch-buffer is not listed as one of the remapped commands for counsel-mode. I had assumed it was one of the remapped commands. I wonder why it isn't included by default.

**Comment by abo-abo** [comment]
Ivy/Swiper/Counsel have "emergent architecture" :).

It's a valid architecture choice, with advantages and drawbacks. The advantages are ease of contributions and exploration of ideas. For instance, `counsel-switch-buffer` is a contributed, maybe even experimental command, which many users have grown to like.

The disadvantage is that many things are not in their best place. Ideally, `ivy-switch-buffer` should have been renamed to `counsel-switch-buffer`, similarly to `counsel-find-file`. And the current `counsel-switch-buffer` functionality of selecting buffers as you filter should have been a boolean custom variable.

However, `ivy-mode` and `counsel-mode` actually do have some design philosophy behind them. The idea is to hold commands that are straight upgrades over alternatives:

- `ivy-switch-buffer` is a straight upgrade over a `switch-buffer`
- `counsel-describe-function` is a straight upgrade over `describe-function`

I can't say that `counsel-switch-buffer` is a straight upgrade over `ivy-switch-buffer`. So the current situation remains.

Perhaps we should move towards merging of `ivy-switch-buffer` and `counsel-switch-buffer` into a single `counsel-switch-buffer`. But I don't want to break the users' configs and the existing documentation on the Internet. Have to think about it.

**Comment by jkroes** [comment]
Thanks for the thoughtful response! It was easy enough to configure to use the counsel command instead of the ivy command. Overall, I use the ivy command when I need faster switching, so I can see a use case for both commands. Closing out.

**Comment by SkydiveMike** [comment]
> I can't say that `counsel-switch-buffer` is a straight upgrade over `ivy-switch-buffer`. So the current situation remains.
> 
> Perhaps we should move towards merging of `ivy-switch-buffer` and `counsel-switch-buffer` into a single `counsel-switch-buffer`. But I don't want to break the users' configs and the existing documentation on the Internet. Have to think about it.

Or, is there something compelling and different that exists in `counsel-switch-buffer` (or could be added) that does make it a straight upgrade over `ivy-switch-buffer`? That way existing configurations and documentation for `ivy-switch-buffer` don't need to change and the documentation for the “new and improved” `counsel-switch-buffer` could describe the upgrade.
