### ISSUE TITLE
candidate selection loop when used as evil-mode command-line argument completer

### ISSUE THREAD

**Issue by ctechols** [abo-abo/swiper#2266]
I'm trying to improve the integration between evil-mode's Ex commands and ivy.  Ex commands (such as :e) have programmable completion for their arguments, and that completion can be customized using the `evil-ex-define-argument-type` macro, like this:

```(evil-ex-define-argument-type file :collection read-file-internal)```

The first argument is the type of thing you are completing, (file, buffer, etc).  The value for the `:collection` keyword is anything that can be accepted as the second argument of `all-completions`.

The following is all pared down in attempt to give you a minimal reproduction.  I've written the following code that implements customized completion for files:

```
(defun my/evil-complete-from-ivy-read-collection (string predicate flag)
    (let ((choice (list (ivy-read "Prompt: " (list "value1" "value2")))))
        choice))

(evil-ex-define-argument-type file :collection my/evil-complete-from-ivy-read-collection)
```

Now, with evil-mode enabled, if I type
```:e <TAB>```

I get an active ivy completion session with the "value1" and "value2" strings as candidates.  However, when I select one and hit `<Enter>`, the selected candidate is not inserted as a completion for the `:e` command.  Instead, I get another instance of the ivy session with the same candidates.

The following code does not use ivy, but has the same function contract.  It cooperates with evil in the way I'd expect.

```
(defun my/evil-complete-one-string (string predicate flag)
    (list "str1"))

(evil-ex-define-argument-type file :collection my/evil-complete-one-string)
```

My assumption is that I need to do something to clean up after Ivy so that it knows it doesn't own the minibuffer any longer.  I'm an elisp novice, but it does seem like ivy-read is attempting to clean up after itself properly.  I've tried using no-ops for ivy-read's :action parameter, and using different types cleanup code before returning the result of ivy-read.  Everything I tried either seemed to have no effect, or would exit both the ivy session and the evil-mode comand-line.

**Comment by ctechols** [comment]
I do run with `ivy-mode` enabled.

Your suggestion works, but when completing _files_ it's missing some features.  The "~", "/", ".." keys do not work as expected, for example.

The following code enables the missing features, but it suffers from the looping behavior:

```elisp
(defun my/evil-complete-from-ivy-read (string predicate flag)
    (let ((choice (list (ivy-read "Prompt: " #'read-file-name-internal))))
        choice))

(evil-ex-define-argument-type file :collection my/evil-complete-from-ivy-read)
```

I also noticed this morning that the selection loop isn't infinite.  If I complete the selection process 3 times, the loop ends and the selected candidate is placed on the evil command line as expected.

**Comment by abo-abo** [comment]
You can define your collection like this:

```elisp
(defun my/evil-complete-from-ivy-read (string predicate flag)
  (when (eq flag t)
    (let ((ivy-inhibit-action t))
      (list (counsel-find-file)))))

(evil-ex-define-argument-type file :collection my/evil-complete-from-ivy-read)
```

Due to `my/evil-complete-from-ivy-read` being a collection, it will be called 3 times, with the flag argument being:

- `t`
- `metadata`
- `(boundaries . "")`

See the doc of `all-completions` for more info.

**Comment by ctechols** [comment]
This works perfectly.

I'm sure you're aware, but I discovered the `my/evil-complete-one-string` function above was also called 3 times.  I just didn't notice because it wasn't interactive.

`ivy-inhibit-action` is a neat trick too.  I'll be sure and remember it.

Thank you for your help.  It's very appreciated.
