### ISSUE TITLE
ivy-pop-view is not restoring the view

### ISSUE THREAD

**Issue by manuel-uberti** [abo-abo/swiper#2268]
This is a minimal recipe to reproduce the issue:

- `git clone https://github.com/abo-abo/swiper/`
- `cd swiper`
- `make plain`
- <kbd>C-x C-f</kbd> swiper.el <kbd>RET</kbd>
- <kbd>C-x 3</kbd>
- <kbd>C-x C-f</kbd> counsel.el <kbd>RET</kbd>
- <kbd>M-x ivy-push-view RET RET</kbd>
- <kbd>C-x 0</kbd>
- <kbd>C-x C-f</kbd> ~/.emacs.d/init.el <kbd>RET</kbd>
- <kbd>M-x ivy-pop-view RET</kbd>

The previously pushed view is not getting restored.

This is all tested on GNU Emacs 27.0.50 (build 1, x86_64-debian-linux-gnu, GTK+ Version 3.22.30) of 2019-10-10.

**Comment by abo-abo** [comment]
I think you have confused `ivy-pop-view` and `ivy-switch-view`:

- `ivy-pop-view` is the opposite of `ivy-push-view`: while push-view adds to the list of views, pop-view simply removes the view from the list,
- `ivy-switch-view` gives completion for your list of views.

**Comment by abo-abo** [comment]
No problem :)
