### ISSUE TITLE
counsel-find-symbol no longer works

### ISSUE THREAD

**Issue by rgrinberg** [abo-abo/swiper#2270]
I get the following error:

```
Debugger entered--Lisp error: (no-catch exit nil)
  throw(exit nil)
  exit-minibuffer()
  ivy-exit-with-action(counsel--find-symbol)
  counsel-find-symbol()
  funcall-interactively(counsel-find-symbol)
  call-interactively(counsel-find-symbol nil nil)
  command-execute(counsel-find-symbol)
```

**Comment by abo-abo** [comment]
`counsel-find-symbol` is not supposed to be called from <kbd>M-x</kbd>. You should call it via <kbd>C-.</kbd> from `counsel-describe-function` or `counsel-describe-variable`.

**Comment by rgrinberg** [comment]
I see. Well I wound why it's interactive then. It seemed like it worked for me before.

**Comment by abo-abo** [comment]
It's `interactive` because it's bound to <kbd>C-.</kbd>. You need `interactive` to bind a function to a key. Unfortunately, there's no way currently to remove it from <kbd>M-x</kbd> list.

**Comment by rgrinberg** [comment]
I see. Thanks for your patience. Perhaps it would make sense to improve the
error message so that the use is aware of this. If that’s possible at all
of course

**Comment by abo-abo** [comment]
Thanks, `counsel-find-symbol` is now removed from the `counsel-M-x` list.
It's not removed from `execute-extended-command` though.
