### ISSUE TITLE
counsel-mark-ring with "unsorted" candidates?

### ISSUE THREAD

**Issue by haicnguyen** [abo-abo/swiper#2272]
Thanks for the awesome swiper.el.

I wonder if "counsel-mark-ring" can have an optional argument "nosort", so that it can not only returns line-based sorted candidates (as it currently does) but also time-based candidates (ie. the original order of elements in the mark-ring)?

**Comment by abo-abo** [comment]
Do you want to use it both ways, or only one way?

**Comment by haicnguyen** [comment]
At the moment, I am using it in only one way (no-sort) and I have yet had the need with sorted candidates yet.
I mention both ways because adding the "nosort" option should not change the code original behavior, just adding an extra feature to it, so it might get considered.

**Comment by abo-abo** [comment]
You can configure it with sorting:

```elisp
(ivy-configure 'counsel-mark-ring
  :sort-fn #'ivy-string<)
```

Or without sorting:

```elisp
(ivy-configure 'counsel-mark-ring
  :sort-fn #'ignore)
```

Currently, there's no way to dynamically figure out if you want sorting or not.

**Comment by abo-abo** [comment]
Actually, disregard that. You can configure it like this:

```elisp
(ivy-configure 'counsel-mark-ring
  :sort-fn '(ivy-string< ignore))
```

When you press <kbd>C-c C-s</kbd>, it will cycle the sorting between "on" (`ivy-string<`) and "off" (`ignore`).

**Comment by haicnguyen** [comment]
Somehow my system could not find `ivy-configure'. I am using swiper-20190528.1333, counsel-20190830.1557, and ivy-20190528.1334.

**Comment by abo-abo** [comment]
> ivy-20190528.1334

That's from 5 months ago, `ivy-configure` was added 2 days ago :)

**Comment by haicnguyen** [comment]
So true :D.
Worked like a charm now. Thank you!
