### ISSUE TITLE
counsel-find-file and dired doesn't use current directory?

### ISSUE THREAD

**Issue by MoHKale** [abo-abo/swiper#2274]
sorry for the weird title, I couldn't really think of a nice way to word it. 

In dired, you have the ability to insert directories into the same dired buffer `dired-maybe-insert-subdir`. I do this quite often. When you do this, the `default-directory` doesn't change, so if you're at one of these inserted directories, `counsel-find-file` will use the `default-directory` of the entire buffer, instead of the dired directory you're `(point)` is currently at. I'd prefer if in this case, `counsel-find-file` was smart enough to detect which directory you mean to be at and work from there. This is how **helm** works in dired buffers and having to navigate down to a directory first in dired and then again in `counsel-find-file` is inconvenient. 

For example:

say I'm in a dired directory like this:

```
|   .gitignore
|   LICENSE
|   README.md
|   requirements.txt
|   setup.py
|
\---my_module
    |   decorators.py
    |   __main__.py
    |   __init__.py
```

I insert the *my_module* directory into my dired buffer. Now I decide I want to create a new file at *my_module/foo.py*. I navigate down to where I inserted that directory (assuming I'm not already there) and then `counsel-find-file`. `counsel-find-file` begins not at *my_module*, it begins at the parent directory of *my_module*, now I have to navigate to *my_module* again and then type out *foo.py* to create it.

In the mean time, you can use this to get around this issue, but I'd prefer a built in solution:

```elisp
  (defun counsel-find-file--adjust-for-dired (func &rest args)
    (if (not (provided-mode-derived-p major-mode 'dired-mode))
        (apply func args)
      (let ((default-directory (dired-current-directory)))
        (apply func args))))

  (advice-add 'counsel-find-file :around #'counsel-find-file--adjust-for-dired)
```

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by MoHKale** [comment]
seems to be working fine. Thnx for the prompt response. 😄.
