### ISSUE TITLE
Double tilde doesn't work with /sudo: tramp method

### ISSUE THREAD

**Issue by dieggsy** [abo-abo/swiper#2276]
Repro: 

- `make plain`
- `C-x C-f RET /sudo::/path/to/dir/`
- type `~~`

Expected outcome: Should return to user directory 
Actual outcome: Returns to root directory on first `~`, second does nothing.

This works fine with remote directories using the `ssh` method for example.

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by dieggsy** [comment]
@abo-abo thanks! that seems to have taken care of it
