### ISSUE TITLE
Results ought to respect scroll limits

### ISSUE THREAD

**Issue by emacswatcher** [abo-abo/swiper#228]
When navigating to a result, if the result is not visible in the window, the result will either be the first or last line in the window depending on whether the result's position is before or after the current position in the buffer.

I propose that the the result should ideally either respect the scroll margins or recenter point.

**Comment by abo-abo** [comment]
This isn't the behavior that I'm experiencing: `recenter` is already called in an appropriate place. See if you can reproduce with `emacs -Q`.

**Comment by abo-abo** [comment]
Closing to reduce the amount of hanging issues. Feel free to reopen if you can attach a reproducible bug.

**Comment by yzprofile** [comment]
I think it's `(setq scroll-conservatively 100000)` makes it broken.

**Comment by abo-abo** [comment]
@yzprofile might be the case, but then it's not a `swiper` problem.
