### ISSUE TITLE
counsel-google error handling poor when request package not installed

### ISSUE THREAD

**Issue by ambihelical** [abo-abo/swiper#2281]
Using counsel-google without request package being installed doesn't show any matches, and the only indication that anything is wrong is in the *Messages* buffer.

`Error in post-command-hook (ivy--queue-exhibit): (file-missing "Cannot open load file" "No such file or directory" "request")
`

This message doesn't show up anyway because counsel-google has the minibuffer active. 

It would be better if counsel-google printed a useful message before trying to run instead of just not showing any results.

**Comment by abo-abo** [comment]
Thanks, please test. The command was renamed to `counsel-search`, since it now supports DDG in addition to Google.

**Comment by ambihelical** [comment]
Thanks, that's better error behavior.  Just a heads up though, I'm not getting results for either google or duckduckgo (google was working for counsel-google version).  This may be user/config error on my part though, since I'm sure it works on your end, but I don't have any time to look at it at the moment.  Will update soon.

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by ambihelical** [comment]
Latest fix does work, but I'm still not seeing it in the melpa version.  I removed ivy,counsel and swiper from my elpa directory. When the packages are refreshed the version of counsel previous to the latest fix is downloaded.
