### ISSUE TITLE
Doubts on ivy-read-action-function

### ISSUE THREAD

**Issue by iquiw** [abo-abo/swiper#2284]
I have a few doubts on ` ivy-read-action-function`.

1. `ivy-read-action-function` has an option `ivy-read-action-hydra`, but the function seems not defined.
2. In [ivy-hydra.el](https://github.com/abo-abo/swiper/blob/32c097a07c6691751d6c9efd8dff6c3dfce545bc/ivy-hydra.el#L129), `ivy-read-action-function` is overridden.
   But I think user customizable option should not be overridden?

And maybe due to point 2, once *ivy-hydra.el* is loaded, `ivy-dispatching-call` does not work (i.e. acts like `ivy-dispatching-done`).

**Comment by abo-abo** [comment]
You're right. It's not in a good state. This should be fixed eventually.

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by iquiw** [comment]
Thank you!

Confirmed the issues were solved.

However, when setting `ivy-read-action-function` to `ivy-hydra-read-action`, pressing key after `ivy-dispatching-call` seems to do nothing.
