### ISSUE TITLE
swiper-query-replace show matched groups in substitution preview

### ISSUE THREAD

**Issue by MoHKale** [abo-abo/swiper#2289]
expanding on the point shown [here](https://www.reddit.com/r/emacs/comments/8gc6ih/regex_search_and_replace/dybchzq/) `swiper-query-replace` doesn't expand matched groups when showing the substitutions, instead showing the literal string used for the substitution (eg. *\1*) which is misleading for someone just trying to guess how swiper would do the substitution. 

This is how swiper would show the substitution:

![Capture](https://user-images.githubusercontent.com/23294780/67148774-1f455180-f29b-11e9-9439-5d9684bbaa66.PNG)

whereas this is the kind of affect I would prefer (as shown by evil in this case):

![Capture2](https://user-images.githubusercontent.com/23294780/67148784-3be18980-f29b-11e9-9987-06035f9c445f.png)

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by MoHKale** [comment]
I can't seem to get it to work. Still just looks like the first image.

**Comment by abo-abo** [comment]
Works fine for me. I test with this code

```c
#include <linux/export.h>
#include <linux/mm.h>
```

It's important to use this search string:

    #include  <linux/\(.*\)

And to use this replacement string:

    #include <test/\1

**Comment by MoHKale** [comment]
Okay... this is weird. Now I'm getting replacement hints but it's only showing for the first matching line. Here's what it looks like while searching.

![01](https://user-images.githubusercontent.com/23294780/68040337-0ccd0e00-fcc6-11e9-9ad1-034c2ebed811.PNG)

if I start a substitution from the first match, it shows up... but only for the first match.

![02](https://user-images.githubusercontent.com/23294780/68040452-41d96080-fcc6-11e9-91dd-fcd75e49a07a.PNG)

If I start it from the second match, it just doesn't show anything. 

![03](https://user-images.githubusercontent.com/23294780/68040566-79480d00-fcc6-11e9-93a3-ff68683a7a25.PNG)


I think it might be because that's the last line of the buffer, so I moved the end of the buffer one line below and it works for that line now, but not for the first line.

![04](https://user-images.githubusercontent.com/23294780/68040693-bd3b1200-fcc6-11e9-95e0-199207380f61.PNG)

Also, just out of curiosity, is there a way to get swiper to not highlight searched lines. In my theme it does it all orange like, but seeing as the line number is changed and highlighted anyways, I don't really need any more highlighting.

**Comment by MoHKale** [comment]
oh, okay, I'm steadily working this out. 

Looks like if you start a substitution, it only substitutes from the current match down. Which explains the last case (not sure if it's intentional though). So the only bug here, is that if the last line of a buffer isn't an empty line, swiper replace doesn't show a substitution for it; which was the case in the first 3 examples. 

![05](https://user-images.githubusercontent.com/23294780/68041092-b19c1b00-fcc7-11e9-933d-8e9dcd66ce34.PNG)

swiper does query for the last substitution, it just doesn't show a replacement before hand.

**Comment by abo-abo** [comment]
> Which explains the last case (not sure if it's intentional though)

This is intentional.

The highlight at the end of the buffer should now work as well. Please test.

**Comment by MoHKale** [comment]
Yep, everything seems to be working as expected. Stellar work as always. Thank you 😄.
