### ISSUE TITLE
ivy starts by showing a single line

### ISSUE THREAD

**Issue by brabalan** [abo-abo/swiper#229]
Since last update, each time I use ivy I only see a single minibuffer line until I start typing something. The problem is that I don’t know what is currently selected, so I cannot just hit enter to use it.

Here are a couple screenshots.

`counsel-M-x`
![screen shot 2015-09-15 at 08 32 39](https://cloud.githubusercontent.com/assets/1021637/9869461/68bbddc8-5b84-11e5-86ba-de81fd6cd852.png)

switching buffers
![screen shot 2015-09-15 at 08 33 40](https://cloud.githubusercontent.com/assets/1021637/9869475/7d71ddc6-5b84-11e5-8402-32155504cd3d.png)

Is there an option that has changed for the initial minibuffer size?

**Comment by abo-abo** [comment]
Can't reproduce. Please update to the latest MELPA version, and test with various Emacs versions if you can.

**Comment by brabalan** [comment]
I’m using the current MELPA version.

I was able to reproduce it with a “minimal” configuration (using `package-initialize`): this seems to happen only when a second frame has been created.

This is what I did. With this init.el:
``` emacs-lisp
(setq emacsd-dir "/Users/schmitta/.emacs.d/")
(setq package-user-dir (concat emacsd-dir "elpa"))
(package-initialize)
```
I start emacs
```
% open /Applications/Emacs.app -n --args -Q -l ~/tmp/init.el
```
I then do `M-x ivy-mode`, `C-x 5 2`, `M-x` and I observe the problem.

**Comment by abo-abo** [comment]
Thanks, I was able to reproduce with many frames (I always use just one).  I don't know the reason for this strange behavior, I only added a work-around that checks the number of frames.
