### ISSUE TITLE
counsel-ack doesn't work

### ISSUE THREAD

**Issue by danlei** [abo-abo/swiper#2295]
`M-x counsel-ack` yields `if: Wrong type argument: stringp, counsel-ack`, because the optional arguments in `counsel-ag` eat up its keyword argument `caller` when called from `counsel-ack`. (`:caller` and `counsel-ack` end up in `initial-directory` and `extra-ag-args`, respectively.)

Mixing optional and keyword args is probably a bad idea in general.

**Comment by abo-abo** [comment]
Thanks.

> Mixing optional and keyword args is probably a bad idea in general.

Agreed.
