### ISSUE TITLE
Question: How to exit the minibuffer with non-default action?

### ISSUE THREAD

**Issue by haqle314** [abo-abo/swiper#2296]
I'd like to define bindings for commonly used actions. How do I go about defining the command to do this?
For example, I want to open a file as root in `counsel-find-file`. The default binding to do this is `M-o` `r`. How do I bind `M-r` to do the same thing? Currently, I defined a command to modify the index of the default action before calling `ivy-done`. This seems incredibly hacky and fragile so I'm wondering if there's a better way to achieve this.
```elisp
(defun counsel:ff-as-root ()
  (interactive)
  (when-let ((actions (ivy-state-action ivy-last))
             (idx (1+ (cl-position
                       #'counsel-find-file-as-root
                       (cdr actions)
                       :key #'second))))
    (setcar actions idx)
    (ivy-set-action actions)
    (ivy-done)))
```

**Comment by abo-abo** [comment]
You can do it like this:

```elisp
(defun counsel-ff-as-root ()
  (interactive)
  (ivy-exit-with-action #'counsel-find-file-as-root))
(define-key counsel-find-file-map (kbd "M-r") 'counsel-ff-as-root)
```

**Comment by haqle314** [comment]
Thanks a lot, that does the trick.
