### ISSUE TITLE
`counsel-cd' displays output from `git-grep' or `ag' after running `C-x C-d'

### ISSUE THREAD

**Issue by xuhdev** [abo-abo/swiper#2297]
In a relatively large repository, if searching results haven't finished printing all results, entering `counsel-cd` does not stop the search results from printing.

For example, go to Emacs git repo and open any file in Emacs. Run `counsel-git-grep`, type `emacs`. A lot of results are printing to the minibuffer. Type `C-x C-d` immediately. The results are now printing to the directory switching minibuffer. Can also be reproduced for `counsel-ag'.

**Comment by abo-abo** [comment]
Thanks, please test.
