### ISSUE TITLE
ivy slow to prepare large number of candidates initiallly

### ISSUE THREAD

**Issue by zhaojiangbin** [abo-abo/swiper#23]
Sorry if this is the wrong place to report this issue. I found it with the ivy projectile completion system.

I have a relative large project managed with git. `git ls-files | wc -l` gives 6220.
```
$ time sh -c 'git ls-files | wc -l'
    6220

real	0m0.014s
user	0m0.010s
sys	0m0.006s
```

Using the ivy backend, `projectile-find-file` feels like having to take a few seconds to prepare the initial list of candidates before it's ready to read input. The helm backend, in comparison, feels much faster (like less than 1 second) to get ready.

There isn't conceivable difference once the initial candidate list is shown. Both are able to narrow down the candidate list quickly with the read pattern.

**Comment by zhaojiangbin** [comment]
By the way, I am using the git version of swiper d2b2813b7e1, and MELPA version of projectile 20150316.1130.

**Comment by abo-abo** [comment]
I think I know where the issue comes from.
Here's the code in projectile.el:

```cl
(ivy-read
 prompt
 (cl-delete-duplicates
  choices :test #'equal)
 initial-input)
```

I've added `cl-delete-duplicates` since I noticed that sometimes `projectile`
would pass a non-unique list as `choices`, e.g. `("1" "1" "2" "2")`.
This doesn't really make sense and I don't see value in adapting `ivy-read`
to the possibility of having non-unique candidates.
`cl-delete-duplicates` is probably an O(N^2) operation, which can turn quite slow.

Can you try to replace the code above with:

```cl
(ivy-read prompt choices initial-input)
```

and see if the issue is resolved?

**Comment by zhaojiangbin** [comment]
First, Helm is only listing the first 100 candidates. I cannot believe that I did not notice this in my previous tests. I haven't found how to lift this limit for helm. So the comparison wasn't fair at all. :) I'd imagine that ivy would be sure not slower with listing only 100 candidates initially.

Second, I tried the suggested change. It does make a big difference. The candidate list now shows up almost immediately.

By the way, unlike in swiper, ivy does not show the number of candidates in projectile. And when the input pattern is empty, either initially or after editing, I cannot scroll the candidate list - <kbd>C-n</kbd> and <kbd>C-p</kbd> seem to be scrolling the pattern history instead. Both give the error "Beginning of history; no preceding item".

**Comment by abo-abo** [comment]
> First, Helm is only listing the first 100 candidates. I cannot believe that I did not notice this
> in my previous tests. I haven't found how to lift this limit for helm. So the comparison wasn't
> fair at all. :) I'd imagine that ivy would be sure not slower with listing only 100 candidates
> initially.

You can do it with helm by setting:

```cl
(setq helm-candidate-number-limit nil)
```
> Second, I tried the suggested change. It does make a big difference. The candidate list now shows
> up almost immediately.

OK, I'll request a change for it in projectile. Then the files listed multiply will be a projectile
issue that could be fixed at some point.

> By the way, unlike in swiper, ivy does not show the number of candidates in projectile.

This can be changed as well. Although maybe users would like to customize whether they want the
number of candidates or not. At the moment, it's decided by the `prompt` argument of `ivy-read`.

> And when the input pattern is empty, either initially or after editing, I cannot scroll the
> candidate list - C-n and C-p seem to be scrolling the pattern history instead. Both give the error
> "Beginning of history; no preceding item".

Yes, that can be annoying at times. I've put that feature in to make swiper more similar to isearch,
e.g. you get the last history candidate with <kbd>C-s C-s</kbd> or <kbd>C-r C-r</kbd>.  When you
want to scroll with empty input, just input a single `.`, it matches any string, and the input isn't
empty anymore.

**Comment by abo-abo** [comment]
The pull request for `projectile` update was sent.
The number of candidates will now show up always, unless you customize it away.

For the last thing about <kbd>C-n</kbd> and <kbd>C-p</kbd> you can open in another issue, possibly
with a suggestion fix. I don't yet know what a good fix might be, but I don't want to lose <kbd>C-s C-s</kbd> bringing up the previous history element for `swiper`.

Maybe <kbd>C-n</kbd> and <kbd>C-p</kbd> should behave differently from <kbd>C-s</kbd> and
<kbd>C-r</kbd> just in the case of an empty input.

**Comment by zhaojiangbin** [comment]
Thanks for the scrolling support update. For me ivy is now able to replace helm as the projectile completion system.

By the way, the helm backend is fast, too. When `(setq helm-candidate-number-limit nil)`, the candidate list shows up without noticeable delay. Perhaps the default limit of 100 is for when the source is really slow producing the choices, such as plain find.
