### ISSUE TITLE
displayed candidate is not the current candidate when scrolling

### ISSUE THREAD

**Issue by QiangF** [abo-abo/swiper#2300]
This happens to counsel-yank-pop if:
1. multiple items (at least 3?) in the completion list
2. each has  a height greater than the completion window height

**Comment by QiangF** [comment]
An possible solution is to keep the current selected candidate be the first displayed in the minibuffer.

**Comment by abo-abo** [comment]
Sorry, can't reproduce. Can you try to reproduce with `emacs -Q`?

**Comment by QiangF** [comment]
Sorry, it 's indeed caused by some other package, I found a quick workaround for now :

    (defun my-prepare-candidate-fit-into-screen (s)
        (let* ((w (frame-width))
                ;; display kill ring item in one line
                (key (replace-regexp-in-string "[ \t]*[\n\r]+[ \t]*" " ## " s)))
        ;; strip the whitespace
        (setq key (replace-regexp-in-string "^[ \t]+" "" key))
        ;; fit to the minibuffer width
        (if (> (length key) w)
            (setq key (concat (substring key 0 (- w 4)) "...")))
        (cons key s)))

    (defun counsel--yank-pop-format-function (cand-pairs)
        "Transform CAND-PAIRS into a string for `counsel-yank-pop'."
        (ivy--format-function-generic
        (lambda (str)
            (mapconcat
            (lambda (s)
            (ivy--add-face s 'ivy-current-match))
            (split-string
            (counsel--yank-pop-truncate str) "\n" t)
            "\n"))
        (lambda (str)
            (car (my-prepare-candidate-fit-into-screen str)))
        cand-pairs
        (propertize counsel-yank-pop-separator 'face 'ivy-separator)))
