### ISSUE TITLE
Arithmetic error when calling ivy-occur from counsel-rg and counsel-git-grep

### ISSUE THREAD

**Issue by andreyorst** [abo-abo/swiper#2301]
I'm on Emacs 27 (commit `372c4ebf6d3c7d39cc5b1e04e7f228543fec107d`) and when I do <kbd>C-c</kbd><kbd>C-o</kbd> to call `ivy-occur` I get `[Arithmetic error]` message:

![image](https://user-images.githubusercontent.com/19470159/67578816-e64e2680-f74b-11e9-9683-4e92b120cc34.png)

**Comment by abo-abo** [comment]
Is this reproducible on Emacs 26.3?

**Comment by andreyorst** [comment]
yes

**Comment by abo-abo** [comment]
Tested with Emacs 26.3 on GNU Linux. I grepped for `config` using `counsel-rg` and used `ivy-occur`. Everything worked fine.

Is the bug consistently reproducible for you? For any repo? Which `rg` version are you using?

**Comment by andreyorst** [comment]
Hmm. I've tested with `emacs -q` and wasn't able to repro. So I've inspected my config, and found that setting `ivy-minibuffer-faces` to `nil` (which I was successfully using for about a year now) causes this error.

**Comment by abo-abo** [comment]
Maybe you can customize it like this:

```elisp
(setq ivy-minibuffer-faces '(default default default default))
```

**Comment by andreyorst** [comment]
Thanks, it works
