### ISSUE TITLE
Proposal: more consistent override for counsel file name filtering

### ISSUE THREAD

**Issue by ilohmar** [abo-abo/swiper#2304]
Currently, `counsel--{file-name-filter,find-file-matcher}` both check `ivy-text` for the regexp "\\`\\.", and if it matches, no filtering takes place.

This seems logical only if one uses `counsel-find-file-ignore-regexp` to filter out *dot-files*.  If, in contrast, one uses this var to filter out, say, both the suffixes from `completion-ignored-extensions` *and* temporary and lock files, the shortcut does not work (because some of these files do not start with a dot), and even if it worked, it would be a shortcut that has got nothing to do with the filter setting.

That being said, how about simply replacing the regexp "\\`\\." by `counsel-find-file-ignore-regexp`?  This is a simple and straightforward logic with any setting of the custom var --- "filter out anything matching the regexp, except if what I enter already matches it as well".  I tried this and it works very nicely with my custom setting (I described it above).

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by ilohmar** [comment]
Excellent, thank you!
