### ISSUE TITLE
counsel-git-grep to ivy-occur doesn't preserve matches.

### ISSUE THREAD

**Issue by flamingbear** [abo-abo/swiper#2309]
Hi, 
I might be using it wrong, and maybe it's always worked this way and maybe it's related to this #1542 

When I use counsel-git-grep and type an all lowercase string the minibuffer shows me case insensitive results.  (yay)

But when I use `C-c C-o` for `ivy-occur`, only all lowercase results appear. (boo)

so if I have a file with 

```
testClass
```
counsel-git-grep for `testclass` shows one result, and then `ivy-occur` shows 0.
but counsel-git-grep for `test lass` shows one result and `ivy-occur` also yields that result.

I don't know if this is new, or desired behavior, I would like to know how to modify this behavior if it is expected.

Thanks
Matt

counsel-20191026.922
ivy-20191021.1017

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by flamingbear** [comment]
👍 Thanks for the fast response 🙇
