### ISSUE TITLE
Find file / dired try to ping domain name at point by default (and likely hang)

### ISSUE THREAD

**Issue by winny-** [abo-abo/swiper#2311]
# Tested against

- GNU Emacs 26.3 with ivy 0.13.0 from elpa.gnu.org
- GNU Emacs 26.3 with ivy 20191030.1538 from melpa.org

# Steps to reproduce

1. Set up fresh Emacs config (Perhaps: `docker run -ti --rm silex/emacs`)
2. `M-x package-install RET ivy RET`
3. `C-x C-f /tmp/dummy.txt`
4. Type `not.existant.com`, (note spelling) move point back onto that text.
5. Ensure `C-x C-f` and `C-x d` both work without ivy enabled.
6. `M-x ivy-mode RET`
7. Notice how `C-x C-f` and `C-x d` will hang

# Possible workaround

Set `ffap-machine-known-p` to `'reject`.

# Explanation

It appears ivy will try to complete based off point, which means it will also try to complete machine names (hostnames) by default.

# Demo

https://asciinema.org/a/278513

**Comment by abo-abo** [comment]
Thanks.
