### ISSUE TITLE
Please don't overwrite describe-mode keybinding or at least don't enable it by default

### ISSUE THREAD

**Issue by hrehfeld** [abo-abo/swiper#2313]
This is just against emacs convention. At any point do I want to see my current keybindings/modes.

ivy.el:460
```
    (define-key map [remap describe-mode] 'ivy-help)
```
If you really want think overwriting describe-mode is a good idea, make it something that needs to be enabled -- otherwise confusion will happen.

(I just spent a bunch of time because of that.)

For the record, users can disable it with something like:

```
	;; don't let ivy overwrite describe mode
	(define-key ivy-minibuffer-map [remap describe-mode] nil)
```

**Comment by abo-abo** [comment]
> This is just against emacs convention

I have to disagree here. Since Ivy is taking over the minibuffer, it's free to remap any binding it wishes.

And `ivy-help` provides better info than `describe-mode`, in my opinion. What info were you missing?

**Comment by hrehfeld** [comment]
I was trying to find out how to navigate upwards in `counsel-find-file` -- turns out that the binding is `C-DEL` or `C-BACKSPACE`, which is neither described in `ivy-help` nor https://oremacs.com/swiper/#key-bindings. The problem of both of these is that they're not autogenerated from the actual internals anymore. This is very un-emacsy in my mind. Why throw away power that we already have?

However, now that I double check, for some reason `describe-mode` does not have info about either `counsel-find-file-map` nor the actual keybinding, what's happening there? Usually it just does what you want when you don't know about a key in the minibuffer.

(because the binding was broken, i actually checked `counsel-find-file-map` manually)

**Comment by mookid** [comment]
One alternative is just not to enable ivy-mode (which I do).

**Comment by abo-abo** [comment]
> The problem of both of these is that they're not autogenerated from the actual internals anymore

We can implement it. I think adding an extra outline with auto-generated info is a better approach.

**Comment by abo-abo** [comment]
Thanks, please test.

@hrehfeld `counsel-find-file-map` is not picked up by `describe-mode`. However, `counsel-descbinds` does see it.

My config:

```elisp
(setq enable-recursive-minibuffers t)
(global-set-key (kbd "C-c d") 'counsel-descbinds)
```

<kbd>C-x C-f C-c d</kbd> `up dir` shows me the relevant bindings.
