### ISSUE TITLE
Get the buffer in which the first `ivy-read' call is initiated

### ISSUE THREAD

**Issue by xuhdev** [abo-abo/swiper#2318]
When calling `ivy-read` recursively from another `ivy-read` minibuffer, is there a way to obtain info about the buffer in which `ivy-read` is first called? The following code does not work:

```emacs-lisp
(with-ivy-window (with-ivy-window (buffer-name)))
```

**Comment by abo-abo** [comment]
Try `(ivy-state-buffer ivy-last)`.

**Comment by xuhdev** [comment]
It only prints the minibuffer that made the second `ivy-read` call

**Comment by abo-abo** [comment]
OK, try this:

```elisp
(ivy-set-actions
 'ivy-reverse-i-search
 '(("b" my-ivy-test "test")))

(defun my-ivy-test (_)
  (message "%S" (ivy-state-buffer ivy-recursive-last)))
```

And <kbd>C-x C-f C-r M-o b</kbd>.

**Comment by xuhdev** [comment]
This works. Thanks!
