### ISSUE TITLE
option for <left> and <right> to move point

### ISSUE THREAD

**Issue by PythonNut** [abo-abo/swiper#232]
Right now <kbd>&lt;left&gt;</kbd> and <kbd>&lt;right&gt;</kbd> simply move to the first and last candidates.  It would be great if we had the option to use those keys to move the point instead. True, we could use <kbd>C-f</kbd> and <kbd>C-b</kbd>, but I suspect that those keys are not really in common usage these days.

**Comment by abo-abo** [comment]
You mean move the point in the minibuffer? That does make sense, since I want Ivy's minibuffer to behave like a 1-line fundamental-mode buffer, as much as possible.

But I always use <kbd>C-f</kbd> and <kbd>C-b</kbd>, so I forgot that you could move the point with physical arrows too.

**Comment by PythonNut** [comment]
> You mean move the point in the minibuffer?

Yes, I do.

I know the arrow keys are generally bad practice, but I prefer them to <kbd>C-f</kbd> and <kbd>C-b</kbd> because they require no modifiers.

**Comment by PythonNut** [comment]
> You mean move the point in the minibuffer?

Yes, I do.

I know the arrow keys are generally bad practice, but I prefer them to <kbd>C-f</kbd> and <kbd>C-b</kbd> because they require no modifiers.

**Comment by abo-abo** [comment]
Thanks for the suggestion.
