### ISSUE TITLE
read-file-name default does not match that with ivy-mode off

### ISSUE THREAD

**Issue by xuhdev** [abo-abo/swiper#2327]
Run `emacs -Q` (in which `insert-default-directory=t`), open `~/tmp/test.el`. Evaluate the following line, and press enter in the minibuffer:

    (read-file-name "prompt: ")

The full path to `test.el` is returned.

Now start Emacs with ivy-mode on. Repeat the above steps. The path to `~/tmp/` is returned.

**Comment by abo-abo** [comment]
It does match in case <kbd>C-M-j</kbd> is used.

The confusion is that the default completion blurs the two cases when there is input and there is no input. In Ivy, those are separate:

- <kbd>RET</kbd> means we want to select the current candidate, in this case `./`.
- <kbd>C-M-j</kbd> means we want to proceed with no input.

So I think we can close this issue.

**Comment by xuhdev** [comment]
Sounds good. Thanks!
