### ISSUE TITLE
Customizing `ivy-initial-inputs-alist` has no lasting effect

### ISSUE THREAD

**Issue by DevJac** [abo-abo/swiper#2328]
After I customize `ivy-initial-inputs-alist`, the customization takes effect, but only until I restart Emacs. After I restart Emacs the change has no effect, and I have "^" as my initial input once again.

I created a repo with the minimal contents of my `~/.emacs.d/` and steps to reproduce the problem at: https://github.com/DevJac/emacs.d/tree/ivy-initial-inputs-alist-bug-demo

The TL;DR steps:
1. Start with the minimal `init.el` shown below.
2. Install the `counsel` package.
3. Do some customizations.
4. Observe that customizations do not take effect after restarting Emacs.

Ultimately, I end up with the following in my `init.el` after running the customize.
```elisp
; The following line is a workaround for Emacs 26.2.
(setq gnutls-algorithm-priority "NORMAL:-VERS-TLS1.3")

(package-initialize)
(setq package-archives '(("gnu" . "https://elpa.gnu.org/packages/")
			 ("melpa" . "https://melpa.org/packages/")))

(setq package-selected-packages '(counsel))

(ivy-mode 1)
(global-set-key (kbd "M-x") 'counsel-M-x)

; The following is added automatically after performing the customization.
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(ivy-initial-inputs-alist
   (quote
    ((counsel-minor . "^+")
     (counsel-package . "^+")
     (counsel-org-capture . "^")
     (counsel-M-x . "")
     (counsel-describe-function . "^")
     (counsel-describe-variable . "^")
     (org-refile . "^")
     (org-agenda-refile . "^")
     (org-capture-refile . "^")
     (Man-completion-table . "^")
     (woman . "^")))))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )
```

With the above as my `init.el`, `counsel-M-x` will have "^" as its initial input, which is unexpected and is a bug I believe.

**Comment by manuel-uberti** [comment]
I don't know if this could be of any help, because it may be too tight to my own setup, but since I was facing a similar problem recently, let me share my findings. 

To have `ivy-initial-inputs-alist` set as I want I load `counsel-mode` after `ivy-mode` (with a hook, to be more specific) and set `ivy-initial-inputs-alist` in the `:config` section of my `use-package counsel` snippet. 

Something like this (I removed other `counsel` settings I use in order to highlight the interesting bits):

```emacs-lisp
(use-package counsel
  :hook (ivy-mode . counsel-mode)
  :config (setq ivy-initial-inputs-alist nil))
```

**Comment by DevJac** [comment]
Well, at the very least I didn't know `counsel-mode` was a thing, but it saves me a few lines in my config (so far). I was just using `ivy-mode` before.

**Comment by DevJac** [comment]
Furthermore, enabling `counsel-mode` fixed my original problem, my customizations work now! :smile:
