### ISSUE TITLE
regression in ivy--magic-tilde-directory

### ISSUE THREAD

**Issue by bymoz089** [abo-abo/swiper#2329]
Commit https://github.com/abo-abo/swiper/commit/388e0d415f013cea48d92d1ac0cfd73ddbab173f brought an regression to Emacs v25.x and older, because function `file-local-name` does not exist.

With above commit, typing `~` at an `counsel-find-file` promt leads to following error message:

> Error in post-command-hook (ivy--queue-exhibit): (void-function file-local-name)

*Remark:* Sorry for comming up with old emacs versions. Maybe its time to mark `swiper` to support only emacs v26 and newer. But I still need to stay with that old emacs version for some time.

**Comment by bymoz089** [comment]
Since function `file-local-name` is just a one liner, it is easy to **workaround this issue** for emacs v25 users.  Simply put the following source code in your init.el:

    (unless (fboundp 'file-local-name)
      (defun file-local-name (file)
        "backport from emacs v26, Return the local name component of FILE.
    This function removes from FILE the specification of the remote host
    and the method of accessing the host, leaving only the part that
    identifies FILE locally on the remote system.
    The returned file name can be used directly as argument of
    `process-file', `start-file-process', or `shell-command'."
        (or (file-remote-p file 'localname) file)))

**Comment by abo-abo** [comment]
Thanks, this workaround is fine by me.
