### ISSUE TITLE
Suggestion: Rename buffer with M-o r

### ISSUE THREAD

**Issue by sshbio** [abo-abo/swiper#233]
While browsing ivy-switch-buffer, M-o r could actually rename the buffer.

It is usefull while browsing eww or to open multiple *eshell* buffers.

I suggest this because I use Ivy a lot: Thank you for ivy (and hydra, and swiper, and counsel, and avy, and the others).

**Comment by abo-abo** [comment]
Thanks, let me know if it works fine. I wonder if it should switch to buffer in addition to the rename.

**Comment by sshbio** [comment]
That was fast.

Is it not yet on melpa. I'm installing my packages from it.

I will try to install from git source.

**Comment by abo-abo** [comment]
Yes, MELPA builds are hourly, as far as I know. I keep Git copies for a lot packages I keep track of - it's faster and it's easy to catch up on the new changes.

**Comment by sshbio** [comment]
I got the melpa package (not comfortable enough with .emacs.d yet). And everything seems to work without issue !

Thank you for the support and enhancements!
