### ISSUE TITLE
`ivy-next-line` behavior in `swiper-isearch`

### ISSUE THREAD

**Issue by ThibautVerron** [abo-abo/swiper#2330]
Hello,

First off, thanks for writing `swiper-isearch`, for me it was the missing piece for using `ivy` for everything.

It is very far from a major inconvenience, but the behavior of `ivy-next-line` in `swiper-isearch` is not really intuitive: it moves to the next match, even if this match is on the same line. If we are using it to browse through the occur-like mini-buffer, it makes the scrolling sometimes pause when there are several matches on the same line.

On the other hand, `swiper` highlights all matches and jumps from line to line, but does not offer a way to jump to the same match within a line.

Is there an easy way to get both behaviors in `swiper-isearch`, i.e., a function which always goes to the next/previous matching line (think `C-n`), and a function which always goes to the next/previous match (think `C-s`) ?

**Comment by abo-abo** [comment]
I think this should be fixed in your config.

The reason is that there's a shortage of nice short bindings for the Ivy minibuffer.  I don't think we can afford to bind <kbd>C-s</kbd> and <kbd>C-r</kbd> to a slightly different version of <kbd>C-n</kbd> and <kbd>C-p</kbd>.  Besides, <kbd>C-r</kbd> is already taken up by `ivy-reverse-i-search`.

Here's how you can make the version of <kbd>C-n</kbd> that you requested:

```elisp
(defun my-ivy-next-line (&optional arg)
  "Move cursor vertically down ARG candidates."
  (interactive "p")
  (setq arg (or arg 1))
  (if (eq (ivy-state-caller ivy-last) 'swiper-isearch)
      (let ((index (+ ivy--index arg)))
        (while (and (< index (1- ivy--length))
                    (with-ivy-window
                      (= 1 (count-lines
                            (nth ivy--index ivy--all-candidates)
                            (nth index ivy--all-candidates)))))
          (cl-incf index))
        (ivy-set-index index))
    (ivy-next-line arg)))
(define-key ivy-minibuffer-map (kbd "C-n") 'my-ivy-next-line)
```

**Comment by ThibautVerron** [comment]
I was not suggesting a rebind (in general I'm of the opinion that binds belong in each user's config), but it's nice that the function can be done. Thanks!

If `ivy-reverse-i-search` is a reverse-i-search in the history of previous searches, I can definitely live without it in `swiper-map`.

**Comment by abo-abo** [comment]
OK. I'm closing this. If you need some refactor in Ivy to make it easier to implement this in your config, let me know.
