### ISSUE TITLE
ivy-partial-or-done fails with wrong-type-argument when completion-cycle-threshold is t

### ISSUE THREAD

**Issue by Deewiant** [abo-abo/swiper#2333]
The change made for #2225, commit 64c0804cc5c3c75d72b549a285bfb6ba1ac3cb67, didn't account for the possibility that `completion-cycle-threshold` can be set to `t`, so the `<` fails.

Easily reproduced by `(setq completion-cycle-threshold t)` and then e.g. `M-x counsel-find-file` followed by `TAB`.

**Comment by abo-abo** [comment]
Thanks.
