### ISSUE TITLE
counsel-find-file very slow

### ISSUE THREAD

**Issue by kevindragon** [abo-abo/swiper#2338]
`counsel-find-file` call takes more than 1 minutes when first time.

My Emacs env:

```
GNU Emacs 27.0.50 (build 1, x86_64-w64-mingw32)
 of 2019-11-12
```

**Comment by abo-abo** [comment]
Likely an issue with your config. Can you reproduce with `make plain`?

**Comment by kevindragon** [comment]
This is my config about ivy and counsel:

```elisp
;;; use ivy
(use-package ivy
  :init (ivy-mode 1)
  :config
  (setq ivy-use-virtual-buffers t)
  (setq ivy-count-format "(%d/%d) ")
  :diminish (ivy-mode . ""))

(use-package swiper
  :bind ("C-s" . swiper-isearch))

(use-package counsel
  :bind (("C-x C-f" . counsel-find-file)
         ("M-x" . counsel-M-x)))
```

**Comment by kevindragon** [comment]
Is it possibile related to remote files or check remote something?

**Comment by abo-abo** [comment]
My point was that it's some part of your config interfering with Ivy. We can confirm it with `make plain`. And then you can comment out bits of your config to see if the bug disappears.

**Comment by Alexander-Shukaev** [comment]
You can also try `toggle-debug-on-quit`, then `counsel-find-file`, wait a few seconds, then `C-g`.  The backtrace will most likely reveal what's slow.

**Comment by abo-abo** [comment]
Closing this issue since it's stale and could not be reproduced.
