### ISSUE TITLE
swiper with spacemacs

### ISSUE THREAD

**Issue by drorbemet** [abo-abo/swiper#234]
I got kind of addicted to swiper and counsel and now I am thinking about moving from prelude config to spacemacs.
Is there anything I should be aware of using swiper and counsel in spacemacs?

I didn't used helm that much untill now because it looked so huge.
But with spacemacs helm ships preconfigured ...
What will I probably miss in helm that I get with swiper?

**Comment by abo-abo** [comment]
Helm and swiper are orthogonal, you can use them both at once. The only thing is that you have to decide if you want `helm-mode` or `ivy-mode` on: they're exclusive. These modes decide the completion method used for generic completion, e.g. for `package-install` or `describe-variable`, but not for specific completion like `helm-buffers-list` or `counsel-M-x`.

I've used Helm extensively for years before I wrote Ivy. I don't really miss anything major currently.  Helm has this concept of multiple sources for a single completion - it's pretty cool, but I can do without it fine.

**Comment by tsdh** [comment]
@abo-abo Same story for me.  However, for files I really miss the multiple sources.  Right now, I use a hydra with a head for recent files and another head for `counsel-locate`.  If those two could be merged, that would be awesome.  Looking at the code, I assume that could be doable with a different async sentinel which doesn't `setq` `ivy--all-candidates` but merges the current list and the new completions from the async process.

**Comment by abo-abo** [comment]
@tsdh Multiple sources should be added eventually. I'd like them to be customizable, so you could have all combinations like `locate` and `recentf` on the user side.  Probably this should be done with an alist based on `this-command`, just like many of the other customizations. There would be a main source of candidates - hard-coded, and additional ones that you can add in your config. Would that work for you?

**Comment by tsdh** [comment]
Yes, that would work fine.

**Comment by sooheon** [comment]
Another use case is something like `helm-multi-swoop-all`, which is essentially `swiper`, but on all open buffers. While I much prefer the swiper ux, I do miss this kind of function.

**Comment by abo-abo** [comment]
@sooheon Just added `swiper-all`. It can be OK if you don't have a lot of buffers. Otherwise, it can take 10 seconds or more to build a list.

See also `swiper-multi`: it allows to first select the buffers that you're interested in; use <kbd>C-M-m</kbd> to mark all but last buffers and <kbd>C-m</kbd> to mark the last one.

**Comment by justbur** [comment]
FYI https://github.com/syl20bnr/spacemacs/pull/4332

**Comment by abo-abo** [comment]
@justbur  Very nice. I have Spacemacs around for fixing Spacemacs-specific issues in my other packages. It would be cool to be able to quickly switch to ivy from helm.

**Comment by justbur** [comment]
@abo-abo I think some new ivy/counsel functions will come out of it as I port some helm stuff. If you want I can contribute them back here.

**Comment by abo-abo** [comment]
Sure. Just keep in mind that contributions larger than 15 lines require an Emacs Copyright Assignment.

**Comment by syl20bnr** [comment]
https://github.com/syl20bnr/spacemacs/pull/4332 has been merged and Ivy is available in develop branch, to use it add `spacemacs-ivy` layer to the dotfile and restart Emacs, Helm will be replaced by Ivy.

I'm really happy that Spacemacs now supports Ivy and I wish the best things for both projects working together. 

That's a great way to start 2016! :-)

**Comment by abo-abo** [comment]
@justbur  @syl20bnr Thanks!
