### ISSUE TITLE
Error in post-command-hook found in swiper after an recent update

### ISSUE THREAD

**Issue by xiangsheng** [abo-abo/swiper#2343]
After a recent (perhaps in the most recent month? not very sure) update, if I input in swiper or cousel-M-x two consecutive backslashes, i.e. `\\`, I always encounter the error `Error in post-command-hook (ivy--queue-exhibit): (args-out-of-range "\\\\" 2)`. 

I've tried on emacs with no initial file only loading the ivy and counsel packages. But the error is still there.

**Comment by xavierr** [comment]
Hello,

I can confirm this problem.

PS : thank's for this very nice package and the work you put in it!

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by xiangsheng** [comment]
The bug is fixed. Good job!

**Comment by xavierr** [comment]
Thank you very much.
