### ISSUE TITLE
ivy-completion-in-region-action should pass 'finished to exit function if no further completion possible

### ISSUE THREAD

**Issue by non-Jedi** [abo-abo/swiper#2345]
```
‘:exit-function’: Function to run after completion is performed.

   The function must accept two arguments, STRING and STATUS.
   STRING is the text to which the field was completed, and
   STATUS indicates what kind of operation happened:
     ‘finished’ - text is now complete
     ‘sole’     - text cannot be further completed but
                  completion is not finished
     ‘exact’    - text is a valid completion but may be further
                  completed.
```

Use-case: current PR to julia-mode to use :exit-function when completion is finished to replace the latex string (`\alpha`) with the unicode character (`ɑ`):

https://github.com/JuliaEditorSupport/julia-emacs/pull/82

I haven't investigated completely yet, but I don't believe company does this correctly either.

**Comment by abo-abo** [comment]
Ivy does call `:exit-function` here's a test for it:

```elisp
(defun completion-test-1-exitfn (s status)
  (backward-delete-char 1)
  (insert ": " (pcase s
                 ("1" "one")
                 ("2" "two")
                 ("3" "three"))))

(defun completion-test-1 ()
  (when (looking-back "count" (line-beginning-position))
    (list (point) (point)
          '("1" "2" "3")
          :exit-function #'completion-test-1-exitfn)))
(add-to-list 'completion-at-point-functions 'completion-test-1)
```

Eval this in `*scratch*`, insert `count` and do <kbd>C-M-i</kbd>. If you select "1", `completion-test-1-exitfn` will be called and will insert ": one" instead. Please test if this works as I described for you.

**Comment by non-Jedi** [comment]
The issue isn't that `:exit-function` isn't called but that it's called with a value of `'exact` rather than `'finished` even when completion is finished.

**Comment by tpapp** [comment]
Friendly ping, we are close to merging JuliaEditorSupport/julia-emacs#100 and fixing this would allow seamless integration for ivy users instead of disabled functionality as a workaround.
