### ISSUE TITLE
frecency support

### ISSUE THREAD

**Issue by Silex** [abo-abo/swiper#2348]
Hello,

I see that counsel has support for recentf.

I think it'd be nice to consider https://github.com/alphapapa/frecency.el, which gives better results than recentf.

https://launchpad.net/frecentf.el is an implementation like recentf that uses frecency.

That said, it's not obvious how to support it, because recentf is kinda hardcoded. I think I can make a PR that implements `counsel-frecentf` easily, but I'm not sure how to adapt the rest. Should we first create some wrappers that can use recentf or frecentf interchangeably in its implementation?

**Comment by Alexander-Shukaev** [comment]
Looked only briefly at `frecentf` and it appears suspiciously too compact compared to `recentf`.  There is also additional `sync-recentf` functionality for synchronization probably missing.

**Comment by Silex** [comment]
Well most of frecentf is done by frecency, but yeah it's probably less featureful than recentf. It is much better at showing you the right file tho.

**Comment by Silex** [comment]
Closing because not enough time/interest to develop this feature.
