### ISSUE TITLE
`counsel-find-file` does not support wildcards (`*`)

### ISSUE THREAD

**Issue by Alexander-Shukaev** [abo-abo/swiper#2350]
Stock `find-file` supports wildcards (`*`).  To be a replacement of it, `counsel-find-file` could support them as well.

**Comment by MoHKale** [comment]
how would this interact with the existing regexp matching? and I'm pretty sure by default ivy substitutes space with '.*' which is essentially the same as this... unless I'm misunderstanding something 😕 ❓

**Comment by Alexander-Shukaev** [comment]
Does not have to interact with that.  Simply support typing something like `/xxx/*` and then `ivy-immediate-done`.  I encourage you to try something that already works like that with `ivy` to see what I mean: `rgrep`, pattern, and then when choosing paths, just type `*` and `ivy-immediate-done`.

**Comment by CeleritasCelery** [comment]
In place of wild cards, you can use `M-a` to mark all the files and then open them.

**Comment by abo-abo** [comment]
I think the solution by @CeleritasCelery should be the recommended one.
