### ISSUE TITLE
how to run a function when ivy-read is cancelled?

### ISSUE THREAD

**Issue by mohkale** [abo-abo/swiper#2352]
I've got a function to jump to a bookmarks directory from a find-file session.

```elisp
(defun counsel-find-file--jump-to-bookmark ()
  "jump to a bookmark directory from a `counsel-find-file' session"
  (interactive)
  (require 'bookmark)
  (let ((last-directory ivy--directory))
    (ivy-quit-and-run
      (ivy-read "Jump to bookmark: "
                (counsel-bookmarked-directory--candidates)
                :caller 'counsel-find-file--jump-to-bookmark
                :action (lambda (dir)
                          (counsel-find-file (if (string-empty-p dir)
                                                 last-directory
                                               dir)))))))
```

if the user decides to cancel the jump (hit C-g), I'd like to revert to the existing find-file session they were running, but I'm not really sure how to do this. Is there any way we can give `ivy-read` a `:cancelled-action` parameter which is run if the user tries to cancel an ivy session.

**Comment by CeleritasCelery** [comment]
There is an property `:unwind-fn` that is a function that will be run before exiting.

**Comment by mohkale** [comment]
Thnx, is there any way to tell whether the last ivy sessions was cancelled  (or completed sucesfully) inside of the unwind function.

**Comment by CeleritasCelery** [comment]
You can check the value of `ivy-exit`. Will be `'done` if completed successfully and `nil` otherwise.

**Comment by mohkale** [comment]
thnx, that's all I'll need for this particular case. 😄.

**Comment by abo-abo** [comment]
@CeleritasCelery Thanks for the help.
