### ISSUE TITLE
Allow passing extra arguments to counsel-rg at the end of the input

### ISSUE THREAD

**Issue by nmk** [abo-abo/swiper#2356]
One can pass extra arguments to counsel-rg by separating them from the search string with `--` like this:
```-truby -- foobar```
to search only in Ruby files. A common use case for me is filtering by file type *after* I have entered the search string. I would search a project for "foobar" and realize I would like to filter by file type. Right now I have to `C-a -truby -- ` to add the filter. It would be nice if I could add `-- -truby` to the *end* of the input string and have counsel-rg interpret anything *after* `--` as extra arguments. I would be happy to have a crack at this if pointed to where to start.

**Comment by CeleritasCelery** [comment]
I would like this as well. Take a look at `counsel--split-command-args`. Nice thing is since this function just takes a string you can iterate quickly without the need to run ivy.

**Comment by ambihelical** [comment]
Probably counsel-rg should be rewritten to not depend on counsel-ag, and then some of the rg specific interface can be exposed easier.  It would be nice for example to be able to pass multiple directories to rg to search, which ag does not support.  I had a hack to pass these via extra-rg-args, but that hack is broken at the moment, which is why I found this bug.

**Comment by abo-abo** [comment]
@nmk @CeleritasCelery The splitting works now in the suggested way, thanks.
@ambihelical Please open a new issue.

**Comment by ambihelical** [comment]
@abo-abo The change for this issue seems to allow extra directories to be added by passing them to extra-rg-args after " -- ", e.g.  " -- ~/dir1 ~/dir2 ", so it's good enough for my purposes.

**Comment by SterlingHooten** [comment]
Could we add something to the docstring that makes this form of argument for multiple directories more obvious? The ability to grep over multiple directories is really obfuscated by the presence of the argument "INITIAL-DIRECTORY" (which can't be a list of directories), and the usage of " -- ", although a POSIX convention, is still somewhat exotic.

The example usage from @ambihelical would have been helpful.

**Comment by NightMachinery** [comment]
Here is the wrapper function I use, you might adapt some parts of it:
```lisp
(cl-defun night/search-dir
    (&key
     (dir nil)
     (dir-extras nil)
     (args "")
     (query "")
     (prompt "> "))
  "Conduct a text search in files under the given folder."
  (interactive)
  (let* ((default-directory (or dir
                                ;; (counsel--git-root)
                                default-directory))
         (dir default-directory)
         (args
          (if dir-extras
              ;; https://github.com/abo-abo/swiper/issues/2356#issuecomment-596277828
              (concat args " -- "
                      (s-join " " (cons dir dir-extras)))
            args)))
    (progn
      (setq ivy-calling-tmp ivy-calling)
      (setq-default ivy-calling t)
      (unwind-protect
          (counsel-rg query dir args prompt)
        (setq-default ivy-calling ivy-calling-tmp)))))
```

**Comment by ambihelical** [comment]
@SterlingHooten I'm using a different completion framework now, but I can dig up stuff from my git history.  What were you looking for, it's not very clear what else would be needed beyond my last comment.

**Comment by SterlingHooten** [comment]
My wording was ambiguous. I meant that the comment you wrote was sufficient instruction and something like it would be useful as an example in the docstring.
