### ISSUE TITLE
Compatibility with minibuffer API

### ISSUE THREAD

**Issue by clemera** [abo-abo/swiper#2357]
Hi, I'm playing with minibuffer setup and noticed some problems. Given the following:

    (minibuffer-with-setup-hook 
          (lambda ()
            ;; add some adhoc value to front
            (push "1" minibuffer-default)
            ;; when reached  the end of the values above
            ;; more can be dynamically added with minibuffer-default-add-function
            (setq-local minibuffer-default-add-function
                        (lambda ()
                          ;; can also be called mutliple times
                          ;; when it resets minibuffer-default-add-done 
                          (append minibuffer-default
                                  (list "4" "5")))))
        (read-from-minibuffer "Test: " nil nil nil nil (list "2" "3"))
        ;; compare with: (ivy-read "Test: " '("some" "data") :def '("2" "3"))
        )

I can navigate the items with `M-n` and get: 1, 2, 3, 4, 5. However with `ivy-read` I get: 1,1,4,5. 
Items 2 and 3 are prepended to the completions so this is probably intended to just show the default values as first items. But why the double 1?

**Comment by clemera** [comment]
Never mind I have to investigate a bit more.

**Comment by mjkramer** [comment]
With regard to #2444, I was able to restore the old behavior of `ivy-dispatching-done` by binding `set-message-function` to `nil` in the `let*` form at the top of `ivy-read-action-by-key`. See [this Emacs commit](http://git.savannah.gnu.org/cgit/emacs.git/commit/?id=485b423e8f0df2711a850be7f254665f64ab0bdb) from Dec 22.
