### ISSUE TITLE
[Question] Quit ivy without stopping the execution.

### ISSUE THREAD

**Issue by jcs090218** [abo-abo/swiper#2359]
I know there is `ivy-quit-and-run` and `exit-minibuffer` functions that can quit `ivy`. But after these two functions the execution stops. Is there a way so that I can stop ivy but doesn't stop the rest of the execution? This is something that I am trying to do.

```el
...
(call-interactively #'counsel-find-file)   ; I want to call the exit function during this phase.
...  ; Continue executing
```

Thanks.

**Comment by abo-abo** [comment]
What exactly are you trying to implement? You can put any lambda into `ivy-quit-and-run`.

**Comment by jcs090218** [comment]
I'm trying create the file selector. If there is already one function that does that, then that is great! :D So I am expecting things like.

```el
(message "selected file: %s" (counsel-select-file))  ; This function returns the path.
```

If not then I just need one function that does exit ivy and does not break the execution process. Base how I implement this function are not allow using `lambda`.

I know `ivy-immediate-done` is the function I need but this line is hampering me from doing this.
https://github.com/abo-abo/swiper/blob/41bd9886a5206d24f31cc3c4e33f5c5d72bff408/ivy.el#L1198

Hence I have this whole function (`jcs-ivy-immediate-done`) inside my config and with this line commented out.
https://github.com/jcs090218/jcs-emacs-init/blob/d0f7c122bde2b81b654a9d7b68b45c8b52887ac9/.emacs.jcs/func/jcs-ivy-func.el#L32

Any idea?

**Comment by abo-abo** [comment]
I think you want:

```elisp
(message
 "selected file: %s"
 (let ((ivy-inhibit-action t))
   (counsel-find-file)))
```

**Comment by jcs090218** [comment]
Thanks! This work as charm! :D
