### ISSUE TITLE
 swiper-isearch highlighting

### ISSUE THREAD

**Issue by lxg208** [abo-abo/swiper#2362]
Could you please add an option to make the highighting for swiper-isearch to be similiar to swiper?

For swiper, current line stands out, non-current lines are subdued:
![image](https://user-images.githubusercontent.com/20833310/70578951-25e0ad00-1bea-11ea-9406-248c2a29e705.png)

For swiper-isearch, current line is difficult to tell, the current word is the same as others, and the highlights for non-current words are too strong and are the same as in main buffer:

![image](https://user-images.githubusercontent.com/20833310/70579061-76f0a100-1bea-11ea-8aaf-a437e27ab23d.png)

Also, when searching for several words with fuzzy on, swiper has more contrast, the first two words of swiper-isearch are difficult to tell apart:

Swiper:
![image](https://user-images.githubusercontent.com/20833310/70579340-3fcebf80-1beb-11ea-8647-2dc0287d0d4e.png)
Swiper-isearch:
![image](https://user-images.githubusercontent.com/20833310/70579521-e31fd480-1beb-11ea-9df9-6bcd1e6b2860.png)

Thanks.

**Comment by abo-abo** [comment]
You can customize it like this:

```elisp
(setq swiper-faces
      '(ivy-minibuffer-match-face-1
        ivy-minibuffer-match-face-2
        ivy-minibuffer-match-face-3
        ivy-minibuffer-match-face-4))
(setq swiper-background-faces
      '(ivy-minibuffer-match-face-1
        ivy-minibuffer-match-face-2
        ivy-minibuffer-match-face-3
        ivy-minibuffer-match-face-4))
```

You can also customize `swiper-line-face`.

**Comment by lxg208** [comment]
Thanks, this works.
