### ISSUE TITLE
How do I get counsel-recentf in chronological order?

### ISSUE THREAD

**Issue by e190** [abo-abo/swiper#2363]
![3a1c60e0ec4f0a54ad17759ee3ff6f3e050bbc5f_2_690x137](https://user-images.githubusercontent.com/39932163/70675282-b939e100-1cc3-11ea-99f1-f4a3a67d65cd.png)
How do I arrange it in chronological order when I'm using counsel-buffer-or-or-recentf?

**Comment by abo-abo** [comment]
I don't know what code you're using to show the time stamps; `counsel-recentf` uses the `recentf-list` variable, which does not have time stamp data.  Neither does `~/.emacs.d/recentf`.
