### ISSUE TITLE
DEF argument to completing read shows partial completions.

### ISSUE THREAD

**Issue by equwal** [abo-abo/swiper#2369]
The DEF argument will show the previous completion, and it will even fill in partial completions from last time. [This image](https://spensertruex.com/static/bogus.png) shows two interactions with a program doing this.

João Távora provides this code example to try out https://github.com/joaotavora/sly/pull/298:
```common-lisp
(defvar bla-history '("foo"))
(completing-read "bla? " '("foo" "bar" "baz") nil 'require-match nil
                 'bla-history (car bla-history))
```
So if you type `fo RET` then the next call of this thing will allow completion on `fo`, which is annoying.

**Comment by abo-abo** [comment]
Ivy acts in accordance with the `completing-read` API here: if the `DEF` argument is supplied, and <kbd>RET</kbd> is pressed, `DEF` should be returned.

I suggest rewriting the code to:

```elisp
(completing-read "bla? " '("foo" "bar" "baz") nil 'require-match nil
                 'bla-history)
```

**Comment by equwal** [comment]
@abo-abo 
Are you sure that the intended behaviour of a true `def` argument is to store a partial completion? 

https://github.com/joaotavora/sly/issues/295

**Comment by basil-conto** [comment]
> if the `DEF` argument is supplied, and `RET` is pressed, `DEF` should be returned.

That's not the issue here, as `fo` is typed before pressing <kbd>RET</kbd>, so `DEF` should not be returned.

With `emacs -Q`:

```el
(progn
  (defvar my-history ())
  (setq unread-command-events (listify-key-sequence "fo\C-m"))
  (completing-read "" '("foo" "bar") nil t nil 'my-history)
  my-history)
;; => ("foo")
```

With `make plain`:

```el
(progn
  (defvar my-history ())
  (setq unread-command-events (listify-key-sequence "fo\C-m"))
  (completing-read "" '("foo" "bar") nil t nil 'my-history)
  my-history)
;; => (#("fo" 0 2 (ivy-index 0)) "foo")
```

This happens even with `ivy-read` and when `REQUIRE-MATCH` is `nil`. With `emacs -Q`:

```el
(progn
  (defvar my-history ())
  (setq unread-command-events (listify-key-sequence "fo\C-m"))
  (completing-read "" '("foo" "bar") nil nil nil 'my-history)
  my-history)
;; => ("fo")
```

With `make plain`:

```el
(progn
  (defvar my-history ())
  (setq unread-command-events (listify-key-sequence "fo\C-m"))
  (ivy-read "" '("foo" "bar") :history 'my-history)
  my-history)
;; => (#("fo" 0 2 (ivy-index 0)) "foo")
```

So there's definitely a bug here.

**Comment by abo-abo** [comment]
@basil-conto I don't know how we can make it work like `completing-read-default` without compromising Ivy functionality.

Here's a use case to have things work the way they do:

- `swiper` for "def ivy", <kbd>RET</kbd>.

If we do `swiper` <kbd>M-p</kbd>, having "def ivy" come up in place of e.g. "(defvar ivy--virtual-buffers nil" is much better.

Same thing for <kbd>M-x</kbd> `forward-` <kbd>RET</kbd>. We want to save the query to the history, not the selected candidate.

The one way I see of solving this is to have Ivy use its own separate history variables for all commands to record searches, and then handle the passed history variables the way `completing-read-default` does.

**Comment by basil-conto** [comment]
> The one way I see of solving this is to have Ivy use its own separate history variables

That's one way. Another way would be to have `ivy-completing-read` behave more like `completing-read-default` than `ivy-read`.

**Comment by abo-abo** [comment]
@basil-conto Thanks for the suggestion. Please test.
