### ISSUE TITLE
Add counsel-web to counsel?

### ISSUE THREAD

**Issue by mnewt** [abo-abo/swiper#2371]
Would you like me to contribute counsel-web to counsel itself? I originally thought it was a little big but I noticed it duplicates the search suggestion functionality of counsel-search. It also displays the search results in the minibuffer, which would be the added value.

If you do want it, I can of course create a PR to integrate the functionality in whatever way is deemed appropriate.

No pressure, I'm happy either way. Just offering in case you think it would be a good addition.

https://github.com/mnewt/counsel-web

**Comment by mnewt** [comment]
Closing in favor of https://github.com/melpa/melpa/pull/6687. Cheers!

**Comment by abo-abo** [comment]
Thanks.
