### ISSUE TITLE
ivy-resume doesn't go back to swiper--opoint when quiting swiper-isearch

### ISSUE THREAD

**Issue by amosbird** [abo-abo/swiper#2378]
current point is restored at https://github.com/abo-abo/swiper/blob/master/swiper.el#L1660

but ivy-resume doesn't have that logic https://github.com/abo-abo/swiper/blob/master/ivy.el#L1206

**Comment by alexpeits** [comment]
I am using this advice until the issue is resolved:
```
(defadvice swiper-isearch-action
      (after advice-for-swiper-isearch-action activate)
    (push-mark swiper--opoint t))
```

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by basil-conto** [comment]
> I am using this advice until the issue is resolved:

FWIW, you may be interested in using the new advice system that was added in Emacs 24.4 and makes `defadvice` & friends obsolete. The main entry points are `define-advice` and `advice-add`. See [`(info "(elisp) Advising Named Functions")`](https://www.gnu.org/software/emacs/manual/html_node/elisp/Advising-Named-Functions.html) and [`(info "(elisp) Porting Old Advice")`](https://www.gnu.org/software/emacs/manual/html_node/elisp/Porting-old-advice.html) for more.
