### ISSUE TITLE
counsel-company the company popup breaks text insertion

### ISSUE THREAD

**Issue by mohkale** [abo-abo/swiper#2385]
I have this weird issue where if I call `counsel-company` whilst the company popup is active, the substituted text doesn't get inserted properly.

![broken](https://user-images.githubusercontent.com/23294780/71527344-df21d100-28d2-11ea-8ff6-979cd8da9c27.gif)

In this case 8 characters before the point where I started `counsel-company` got erased 😭.

If I move the point back (causing the popup to hide itself) then the problems resolved.

![working](https://user-images.githubusercontent.com/23294780/71527349-e34dee80-28d2-11ea-8b16-b2f390d4f39e.gif)

for now, the following code block fixes the issue:

```elisp
(advice-add 'counsel-company
            :before
            (defun counsel-company--hide-popup (&rest args)
              (company-cancel)))
```

but it also fully completes any partial matches... so `disp` get's turned to `display-` automatically because all candidates begin with `display-`. I'd rather it didn't do this.

**Comment by AndreaOrru** [comment]
I can confirm the exact same issue.

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by AndreaOrru** [comment]
Works for me. Thanks!
