### ISSUE TITLE
Improve completion in region corrections

### ISSUE THREAD

**Issue by clemera** [abo-abo/swiper#2391]
I just read [this](https://github.com/emacs-helm/helm/issues/2165#issuecomment-507049062) comment:

> With last Helm, now completion behave like this:
    - Prefix is highlighted and read-only
    - When trying to delete backward char prefix helm is completing against, a message is sent on first   hit on DEL and second hit delete the last char of what you have at point in current-buffer quitting helm at the same time, letting user correct its initial input and hitting TAB again to start a new completion.

Which sounds convenient and something ivy completion in region could adopt.

**Comment by basil-conto** [comment]
I don't think there's much benefit in complicating the interface like that. One of two things should happen IMO:

1. The prefix should be read-only. To edit it, type <kbd>C-g</kbd> to exit Ivy completion and edit the prefix directly in the buffer before trying completion again.

2. The prefix is not read-only and the candidate list is updated on the fly as the prefix changes.

By contrast, here's what currently happens:

1. `make plain`
2. `(mess` <kbd>C-M-i</kbd>

   ![2020-05-03-143131_1600x900_scrot](https://user-images.githubusercontent.com/9121222/80915604-4ea94080-8d4b-11ea-912a-c430e18a44c8.png)

3. <kbd>DEL</kbd><kbd>DEL</kbd><kbd>DEL</kbd>

   ![2020-05-03-143150_1600x900_scrot](https://user-images.githubusercontent.com/9121222/80915615-5ec12000-8d4b-11ea-905c-76a158bae40e.png)

4. `ap`

   ![2020-05-03-143158_1600x900_scrot](https://user-images.githubusercontent.com/9121222/80917130-eb241080-8d54-11ea-8ade-d0533209537d.png)

5. <kbd>C-g</kbd>

   ![2020-05-03-143202_1600x900_scrot](https://user-images.githubusercontent.com/9121222/80917134-f1b28800-8d54-11ea-95a1-bd3937830aba.png)

**Comment by clemera** [comment]
Okay, I have also lost interest in this for various reasons, will close this, thanks!

**Comment by basil-conto** [comment]
Reopening because I think the current behaviour is inferior to either of the two options I described.

**Comment by clemera** [comment]
Oops, sorry, of course keep it open if you like I misunderstood.

**Comment by abo-abo** [comment]
Thanks. Please test.
@basil-conto I like the second option more. We have to add "^" to the initial input so that the UX is similar to what we had before.

**Comment by basil-conto** [comment]
Thanks, works fine. Is there a way to have the `^` implicitly added, so that it doesn't temporarily appear in the buffer? E.g. with some matcher property?

**Comment by kiennq** [comment]
This changes seems break [`evil`](https://github.com/emacs-evil/evil).
1. `make plain`, eval `(package-initialize)` and `(evil-mode)`.
2. `:ivy<TAB>`
Before this change
![image](https://user-images.githubusercontent.com/2631472/81724326-26de7900-94bf-11ea-8cc9-723dc0032b0f.png)

After this change
![image](https://user-images.githubusercontent.com/2631472/81724468-6311d980-94bf-11ea-98be-851ecbcc52b6.png)
