### ISSUE TITLE
Customize flag for case insensitive search?

### ISSUE THREAD

**Issue by jgarvin** [abo-abo/swiper#2392]
I've customized base command to use pt instead of ag. But pt doesn't have a `-s` flag, so when I try to mix case it fails.

pt does have a `-S` flag with the full ivy behavior of smart matching (only be case sensitive once there is an uppercase letter). If I could customize to use the `-S` flag just instead of `-s` or being able to specify always to use `-S` without inserting `-i` or `-s`, I think it would give the desired behavior.

**Comment by abo-abo** [comment]
Thanks, please test.
