### ISSUE TITLE
Can't search blank lines by ^$

### ISSUE THREAD

**Issue by AmaiKinono** [abo-abo/swiper#2395]
Search for `^$` using swiper doesn't show any results in a buffer with blank lines.

This works with `isearch-forward-regexp`. Don't know if it's related with https://github.com/abo-abo/swiper/issues/2232.

**Comment by abo-abo** [comment]
Thanks,  please test.

**Comment by AmaiKinono** [comment]
Now it can search blank lines, but still can't replace them.

**Comment by basil-conto** [comment]
What do you mean by replace them?
