### ISSUE TITLE
counsel-switch-to-buffer doesn't support marking buffer candidates

### ISSUE THREAD

**Issue by mohkale** [abo-abo/swiper#2398]
In my case, if I mark a buffer, such as `*scratch*` counsel previews a buffer with one less character and every time I move down to the next candidate it keeps stripping a character. In the end I recieve a buffer list like this.

![capture](https://user-images.githubusercontent.com/23294780/71696383-bf941800-2dac-11ea-8667-444cc201b452.png)

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by mohkale** [comment]
yep, everything seems fine. thnx for the stellar work 😄.
