### ISSUE TITLE
refactor swiper-all into swiper-batch

### ISSUE THREAD

**Issue by mohkale** [abo-abo/swiper#2399]
I've recently fallen in love with swiper and have been using it quite extensively in my emacs configuration. One issue I've had with it however is that I can either run swiper on the current buffer... or every buffer. I believe there should be a middle ground where you can select a bunch of buffers and run swiper on them... such as `swiper-projectile-buffers` to run swiper on all buffers in your current project... or you can goto `ibuffer`/`Buffer-menu` mark a bunch of buffers and then run swiper on the marked `buffers`. 

The default behaviour of `swiper-multibuffer` would prompt you with an interface like `counsel-switch-to-buffer` (where you're shown a buffer list and selecting a candidate previews it). you can mark a bunch of buffers or simply exit with a single buffer and then run swiper on them. If you're in `ibuffer`/`Buffer-menu` mode `swiper-multibuffer` should have a **DWIM** (**D**o **W**hat **I** **M**ean) behaviour and select the buffers to be searched for in a smart way.

I tried implementing something like this, but faced some issues with creating a `counsel-switch-to-buffer` like interface for it... in the end I got this monstrosity somewhat working:

```elisp
(defun swiper-multibuffer (&optional initial-input)
  "use `swiper-all' on a subset of active buffers"
  (interactive)
  (cl-letf* (((symbol-function 'swiper-all-buffer-p)
              (if swiper-multibuffer-respect-filter
                  (symbol-function 'swiper-all-buffer-p)
                (lambda (&rest args) t)))
             ((symbol-function 'actual-buffer-list)
              (symbol-function 'buffer-list))
             ((symbol-function 'ivy-choose-buffers)
              (lambda ()
                (let ((current-buffer (current-buffer))
                      (current-window (selected-window))
                      chosen-buffers)
                  ;; dumb implementation of counsel-switch-to-buffer, but
                  ;; doesn't actually switch, simply shows preview.
                  (ivy-read "Choose buffers: " #'internal-complete-buffer
                            :keymap ivy-switch-buffer-map
                            :preselect (buffer-name (other-buffer current-buffer))
                            :action (lambda (_) (push _ chosen-buffers))
                            :matcher #'ivy--switch-buffer-matcher
                            :update-fn (lambda ()
                                         (with-selected-window current-window
                                           (let ((cand (nth ivy--index ivy--all-candidates)))
                                             (switch-to-buffer (if (ivy--marked-p)
                                                                   (substring cand 1)
                                                                 cand)))))
                            :unwind (lambda () (switch-to-buffer current-buffer))
                            :require-match t
                            :caller 'swiper-multibuffer)
                  chosen-buffers)))
             ((symbol-function 'buffer-list)
              (let ((buffers
                     (mapcar #'get-buffer
                             (cond
                              ((eq major-mode 'ibuffer-mode)
                               (or (ibuffer-get-marked-buffers)
                                   (ivy-choose-buffers)))
                              ((eq major-mode 'Buffer-menu-mode)
                               (or (Buffer-menu-marked-buffers)
                                   (ivy-choose-buffers)))
                              (t (ivy-choose-buffers))))))
                (lambda () buffers)))) ;; keep in closure
    (swiper-all initial-input)))
```

this should give some idea as to what I mean... though it requires some **heavy** refactoring.

Ideally I'd like to change the interface so `swiper-multibuffer` is defined as `(swiper-multibuffer &optional buffer-list initial-input)` and then `swiper-all` is just: 

```elisp
(defun swiper-all (initial-input)
  (swiper-mutlibuffer (buffer-list) initial-input))
```

**UPDATE**: If we're going to implement this, I actually suggest an identifier `swiper-batch` over `swiper-multibuffer`. It's shorter and simpler.

**Comment by abo-abo** [comment]
There's already `swiper-multi` implemented. Use `C-M-m` to select many buffers, then search.

**Comment by mohkale** [comment]
Oh wow, amazing, not sure how that slipped past me. thnx.
