### ISSUE TITLE
Suggestions may scroll too far to the left

### ISSUE THREAD

**Issue by brabalan** [abo-abo/swiper#240]
The following happened as I tried to org-refile a task:
![screen shot 2015-09-25 at 08 39 56](https://cloud.githubusercontent.com/assets/1021637/10094548/44c6caba-6361-11e5-831e-72a49eb1049a.png)

The problem is that the default suggestion is too long and makes every suggestion below scroll to the left. Could it be possible to anchor the suggestions to be able to see their beginning, or alternatively to have a way to scroll them horizontally?

**Comment by abo-abo** [comment]
Thanks.

**Comment by brabalan** [comment]
I’m sorry, but I’m still having an issue. I updated to the latest Melpa version, and I still see text truncated to the left although there is much space on the right:
![screen shot 2015-09-30 at 10 25 43](https://cloud.githubusercontent.com/assets/1021637/10188235/00be80d2-675e-11e5-813c-448d809304a0.png)

The problem is that, as I type too many characters, there is not enough space for the prompt and the entered text to fit. The prompt is then truncated on the left, which is fine, but all the suggestions below also are truncated.

**Comment by abo-abo** [comment]
Should be a bit better now.

**Comment by brabalan** [comment]
Thanks, I confirm it’s much better.
