### ISSUE TITLE
Error occurs after setting  ivy-format-functions-alist

### ISSUE THREAD

**Issue by seagle0128** [abo-abo/swiper#2405]
- Env
  - GNU Emacs 26.3, 27.0.60, 28.0.50
  - macOS Catalina, Mint Linux 19.2
  - ivy-20200105.1946, counsel-20200105.1947, swiper-20200105.1958
- Steps
  1. `emacs -Q`
  1. Install `ivy`, `swiper` and `counsel`.
  1. `M-x ivy-mode`, `M-x counsel-mode`.
  1. Open a file and search via `swiper-isearch`.
  1. Eval `(setq ivy-format-functions-alist '((t . ivy-format-function-default)))`.
  1. Search via `swiper-isearch` again.

Errors occur:
```elisp
Error in post-command-hook (ivy--queue-exhibit): (wrong-type-argument sequencep 5)
```

If using `(setf (alist-get 't ivy-format-functions-alist) #'ivy-format-function-default)`, no errors occur. `swiper` works fine in this scenario.

**Comment by abo-abo** [comment]
This is expected. You should at least have:

```elisp
(setq ivy-format-functions-alist
      '((swiper-isearch . swiper-isearch-format-function)
        (t . ivy-format-function-default)))
```

since `swiper-isearch` will only work with `swiper-isearch-format-function`.

**Comment by seagle0128** [comment]
Thanks for the update! Close it.
