### ISSUE TITLE
Can counsel-imenu not prefix items with "Functions: "?

### ISSUE THREAD

**Issue by hmelman** [abo-abo/swiper#2407]
I'm using the standard emacs `python-mode` from python.el. I have `imenu-create-index-function`set to `python-imenu-create-flat-index`. When I use `counsel-imenu` every item is prefixed with "Functions: ".

1. It should probably be "Function: " (not plural)
2. I'd rather it not be there, so I'd like a customizable option to disable it (and I don't see one).

It doesn't do this if `imenu-create-index-function`is set to `python-imenu-create-index` so it seems   `counsel-imenu-categorize-functions` or its caller distinguishes between  imenu alists with a subalist. Regardless, in this case the labeling is inaccurate because some of the items are classes and not functions. 

In all honesty I don't see the point of this labeling at all. If every item is going to be prefixed with the same string, why have it?

**Comment by CeleritasCelery** [comment]
This behavior is defined in `counsel-imenu-categorize-functions`. You can change it there.

**Comment by hmelman** [comment]
Yes, I know, I mentioned that function. I've worked around it with a version of `counsel--imenu-candidates` that doesn't call `counsel-imenu-categorize-functions`. Regardless there isn't a user option to change this, you have to replace the function which isn't a great idea when getting new versions of counsel.

**Comment by CeleritasCelery** [comment]
Touche. I did not see that. My take would be that this is too trivial to warrant adding another customization. Especially since you already solved it. But others may feel differently.

**Comment by abo-abo** [comment]
`counsel-imenu` does nothing for me in `python-mode`. How can I set it up?

I use `lpy-goto` for `python-mode` by the way.

**Comment by hmelman** [comment]
This did it for me in an emacs -Q:

    (package-initialize)

    (defun my-hook ()
      (setq imenu-create-index-function 'python-imenu-create-flat-index))
    (add-hook 'python-mode-hook 'my-hook)

Then open a python file and run `M-x counsel-imenu`.

**Comment by abo-abo** [comment]
I don't think there's a point in refining `counsel-imenu`. We're just re-using what `imenu` gives us. So `imenu` should be customized instead.

And besides, a better alternative to `counsel-imenu` is `counsel-semantic`.

**Comment by hmelman** [comment]
But you're not just reusing what imenu gives you. `counsel-imenu-categorize-functions` is prefixing the string "Functions" to every item. I'm asking for `counsel-imenu` to simply re-use what imenu gives you.

**Comment by CeleritasCelery** [comment]
It only prefixes "Functions" to imenu items that are uncategorized. If they have a category, it will use that.

**Comment by abo-abo** [comment]
Looking back at when `counsel-imenu-categorize-functions` was introduced, the intention was to have it for Elisp. Since Imenu already gives many categories to Elisp items. So makes sense to restrict it only to Elisp. And it also solves your issue for Python.

**Comment by hmelman** [comment]
Thank you.
