### ISSUE TITLE
counsel-ag does not work

### ISSUE THREAD

**Issue by asberk** [abo-abo/swiper#2408]
# Issue
When I run `M-x counsel-ag` I get 

> user-error: Required program "ag" not found in your path

# Expected Behaviour
The expected behaviour is a working `counsel-ag` command. 😉 

# Further details

I have made sure that `ag` should be findable by packages in emacs: AFAIK it should be sufficient that `/usr/local/bin` is in my path. For the record, it is, via:
```elisp
(setenv "PATH" (concat "/usr/local/bin:" (getenv "PATH")))
``` 
I note this, because `which ag` in my terminal returns `/usr/local/bin/ag`, and so `ag` should be findable by emacs. This is corroborated by the following three items:
1. The `ag.el` package works in emacs (I can use `ag-regexp` and `ag-project-at-point` just fine). 
2. `M-x eshell RET man ag` returns the documentation for `ag`. 
3. `projectile-ag` also works fine when I am in a folder with a `.projectile` file (I haven't tried it outside of this case). 

So why isn't `counsel-ag` able to find the binary? 😕

**Comment by CeleritasCelery** [comment]
what is the output of `(shell-command-to-string "which ag")`?

**Comment by CeleritasCelery** [comment]
Sorry I read the code wrong. The issue is that counsel is getting the ag executable from `exec-path`, not `$PATH`. You can see this with `(executable-find "ag")`. You need to add this missing path to `exec-path`, which is a list.

**Comment by asberk** [comment]
Ah, of course! If only I had dug a little deeper… 
I did as you said (using `M-x eval-region`), and/but had to restart emacs before it took effect as intended. It now works as expected. Thank you! 😸
