### ISSUE TITLE
TRAMP completion support

### ISSUE THREAD

**Issue by PythonNut** [abo-abo/swiper#241]
Asynchronous completion of remote files is one of those super awesome feature of `helm` (even though https://github.com/emacs-helm/helm/issues/981 was closed as `wontfix`). 

Unfortunately, adding this functionality myself is completely out-of-my depth, hence an issue and not a PR.

I'd say this is probably not a big priority, but it would be very cool to see in the future.

**Comment by abo-abo** [comment]
> Asynchronous completion of remote files

I have no idea what this is supposed to be. Can you describe in more detail?

**Comment by PythonNut** [comment]
Say, for example, I type in `/ssh:pythonnut@raspberrypi:/` this is a remote path to the root directory on my Raspberry Pi. `helm` will prompt me for the SSH password, and proceed to complete `/ssh:pythonnut@raspberrypi:/boot`, `/ssh:pythonnut@raspberrypi:/dev` etc. 

Remote paths are a builtin part of `find-file`, which is provided by `tramp`.

Because remote interaction can be slow, it's handy for the completion to be asynchronous so it will not block the event loop.

**Comment by abo-abo** [comment]
> Because remote interaction can be slow, it's handy for the completion to be asynchronous so it will not block the event loop.

I see. So the current level of remote completion is sufficient, it just needs to be async, right?

**Comment by PythonNut** [comment]
Actually, it doesn't look like remote completion is done in `ivy` at all.

**Comment by abo-abo** [comment]
Of course it is: both `find-file` and `counsel-find-file` offer remote file names with ssh access using tramp.

**Comment by PythonNut** [comment]
@abo-abo ah. I see I need to press <kbd>TAB></kbd> <kbd>TAB></kbd> at the root before `ivy` will prompt for the password to proceed with completion. (Strangely, it also seems to popup a dired buffer of the root directory when I do enter the password)

`helm` prompts as soon as a valid TRAMP filename is types.

**Comment by abo-abo** [comment]
I type `/ssh:` <kbd>C-j</kbd> from any directory to get a completion list of all my previous ssh history.

**Comment by PythonNut** [comment]
Ah, very neat. I still get the `dired` buffer popping up. Is that intentional?

**Comment by abo-abo** [comment]
This is the default behavior of `find-file`: if you select a directory `dired` is opened.

**Comment by PythonNut** [comment]
Hm... learn something new every day, I suppose. What do I do if the host is not in my history?

**Comment by abo-abo** [comment]
> When I try to do this, it both opens a dired buffer and tries to continue completion.

This should not happen: <kbd>C-m</kbd> on a directory should exit completion and open `dired`, <kbd>C-j</kbd> on directory should continue completion and not open `dired`.

> What do I do if the host is not in my history?

Just type the host without completion. It will be available next time.

**Comment by PythonNut** [comment]
1. `emacs24.5 -nw -Q`
2. <kbd>M-x</kbd> `package-initialize` <kbd>RET</kbd>
3. <kbd>M-x</kbd> `ivy-mode` <kbd>RET</kbd>
4. <kbd>C-x</kbd> <kbd>C-f</kbd> `//ssh:pi@192.168.0.136:`

For me, 

* <kbd>C-j</kbd> opens a `dired` buffer. That's it.
* <kbd>C-m</kbd> opens a `dired` buffer. That's it.
* <kbd>RET</kbd> opens a `dired` buffer. That's it.
* <kbd>TAB</kbd> prompts for the password and then opens the `*Completions*` buffer above the minibuffer with the completions. No completions are shown in `ivy`.
* Continuing to type does not have completion (how could it? It didn't prompt for the password)
*

**Comment by abo-abo** [comment]
My sequence is: <kbd>C-x C-f</kbd> `/ssh:` <kbd>C-j</kbd>. At this step, domain completion should be offered.
If the domain isn't present, enter it like so: `pi@192.168.0.136` (note no trailing `:`), <kbd>C-j</kbd>.
At this point, completion should be offered for your home directory. If you want to move up, <kbd>DEL</kbd> should work as usual.

**Comment by PythonNut** [comment]
1. `emacs24.5 -Q`
2. <kbd>C-x</kbd> <kbd>C-f</kbd>
3. `//ssh:` <kbd>C-j</kbd>

For some reason, all this seems to do is clear all of the contents of the minibuffer.

**Comment by abo-abo** [comment]
It should be `/ssh:`, not `//ssh:`. Double `//` *always* brings you to the file system root. So `///ssh:` would work as well.

**Comment by PythonNut** [comment]
Ah, I see. All is working now. I that intentionally non-standard? I always remembered TRAMP paths starting with a single slash.

**Comment by abo-abo** [comment]
Well, the path is always e.g. `/foo/`. But <kbd>//</kbd> goes to the root directory. So `/foo//ssh:` is the only middle ground. If you overshoot with <kbd>/</kbd>, <kbd>///ssh:</kbd> will still work though.

And doing `/foo/ssh:` is unreasonable, since it could be that a file named `ssh:` exists in the directory `foo/`.

**Comment by PythonNut** [comment]
No, I mean that `^/ssh:.*$`, as in you can't just put the `//ssh:` anywhere, it' _has_ to be at the start of the path. That's why I do `//` to get to the root, so I can make the minibuffer match `^/ssh:`

**Comment by abo-abo** [comment]
Doing <kbd>C-x C-f /ssh: C-j</kbd> (from any buffer) should give you a prompt. Is that the case for you?

**Comment by PythonNut** [comment]
Yes, it does, and it works great. I'm just not used to starting TRAMP paths at non-root locations. 

I can probably get used to it. I'll close this, and see if there's anything that still could be tweaked.
