### ISSUE TITLE
ivy-set-actions doesn't seem to support keybindings with modifiers

### ISSUE THREAD

**Issue by nixmaniack** [abo-abo/swiper#2411]
If I use following, it doesn't correctly translate to `Ctrl+d`.
```elisp
(ivy-set-actions 'some-cmd '(("C-d" some-action "action")))
```

If I use `(kbd "C-d")` instead of just `C-d` for the key, it doesn't work. 
But if I use evaluated value of `(kbd "C-d")`, it does work as expected.

I was expecting that the given key gets passed through `kbd`. Is that not the case? What is the issue here? 
Or, is it the intended behaviour to not allow modifier keys? If so, what's the rationale?

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by nixmaniack** [comment]
Thanks, it works now.

After this change, `"C-d"` works but change isn't backward compatible i.e. eval'ed `(kbd "C-d")` isn't recognized. I think I'm OK with that - just wanted to point that out. 

May I know the reasoning for not accepting `(kbd "C-d")`?

**Comment by abo-abo** [comment]
> May I know the reasoning for not accepting (kbd "C-d")?

To keep things simple. `read-key-sequence` in `ivy-read-action-by-key` doesn't quite work with <kbd>ESC</kbd>, so we have our own logic with `read-key`, and don't want to do complex stuff with `kbd`.
