### ISSUE TITLE
ivy-format-function-line broken on Emacs 27

### ISSUE THREAD

**Issue by joca-bt** [abo-abo/swiper#2412]
I think there are some issues with `ivy-format-function-line` on Emacs 27.

Given the following `init.el`:
```
(require 'ivy)
(setq ivy-format-functions-alist '((t . ivy-format-function-line)))
(ivy-mode t)
```

We get this (Emacs 26 on the left, Emacs 27 on the right):
![bug](https://user-images.githubusercontent.com/1297942/72096444-80207b00-331a-11ea-8fe7-2deb6bc62b81.png)

It looks like `ivy-format-function-line` is no longer extending to the entire line and looks similar to the default `ivy-format-function-default` (it just has an additional space after the candidate).

(The `init.el` for Emacs 26 has an extra `(package-initialize)`.)

**Comment by mookid** [comment]
This bas nothing to do with ivy. You have the same thing for region-face for instance.

**Comment by joca-bt** [comment]
This is a change in Emacs 27, here's the entry from the `NEWS` file:

```
** New face attribute ':extend' to control face extension at EOL.
The new face attribute ':extend' controls whether to use the face for
displaying the empty space beyond end of line (EOL) till the edge of
the window.  By default, this attribute is non-nil only for a small
number of faces, notably, 'region'; any other face that crosses end of
line will not affect the display of the empty space at EOL.  This is
to make Emacs behave more like other GUI applications with respect to
displaying faces that cross line boundaries.

This attribute behaves specially when theme definitions are applied:
if the theme doesn't specify an explicit value of this attribute for a
face, the value from the original face definition is inherited.
Consequently, a theme generally shouldn't specify this attribute
unless it has a good reason to do so.
```

I would suggest as a minimum to add some documentation about this, maybe in the next release notes, so that users using `ivy-format-function-line` don't get surprised when they upgrade to Emacs 27. They need to add `:extend t` to `ivy-current-match`.

**Comment by abo-abo** [comment]
Thanks. It's documented now. And `ivy-current-match` already has `:extend t` by default.
