### ISSUE TITLE
Swiper begining of line regexp

### ISSUE THREAD

**Issue by CeleritasCelery** [abo-abo/swiper#2418]
I am trying to understand the reasoning for this code in `swiper--re-builder`.

https://github.com/abo-abo/swiper/blob/3fa1677993190ec9b5b637c9dface34fb67ae77f/swiper.el#L740-L757

I understand that there needs to be a space after a `^` to work with swiper, but the current implementation has several draw backs. 

1. Can only use `^` on the first pattern
2. Out of order matching is broken if using `^`
3. Negated patterns are disgarded if using `^`

I tried replacing that code with some code that will just add a space after the `^` in each pattern, and it fixes all the issues above.
```elisp
((string-match-p "\\(^\\| \\)\\^" str)
 (let ((re (funcall re-builder str)))
   (mapcar (lambda (x)
             (let ((regex (car x))
                   (matchp (cdr x)))
               (if (= (aref regex 0) ?^)
                   (cons (concat "^ " (substring regex 1)) matchp)
                 x)))
           re)))
```

Though given the intentionality of this code, I feel like I am missing something here. Why is this code handled the way it is?

**Comment by abo-abo** [comment]
This particular code was written step by step to support some basic features, i.e. not planned way ahead.

Please make a PR with your change.

**Comment by noctuid** [comment]
@CeleritasCelery  This change causes incredibly poor performance for `swiper-isearch` but not `swiper` when using `orderless-ivy-re-builder` (see [orderless](https://github.com/oantolin/orderless)). It's not immediately obvious to me why especially since only `swiper-isearch` is affected.

**Comment by CeleritasCelery** [comment]
That is odd. What leads you to believe it is this specific commit that caused the performance issue? I tried running the following code before and after the change:

```lisp
(cl-letf ((ivy-re-builders-alist '((t . orderless-ivy-re-builder)))
          ((ivy-state-caller ivy-last) 'swiper-isearch))
  (swiper--re-builder "foo bar baz"))
```

It returns the same regex both times, which is expected. For `swiper-isearch` there is no transformations done to the regex (unless `search-default-mode` is set) so I don't see how this could be impacting performance.

**Comment by noctuid** [comment]
Yeah, I got the same regexp too. Did you try calling `swiper-isearch` though?

> That is odd. What leads you to believe it is this specific commit that caused the performance issue?

I bisected to find it. The commit immediately before does not have any performance issues. I'll have to look into it further.

**Comment by abo-abo** [comment]
> I bisected to find it. The commit immediately before does not have any performance issues. I'll have to look into it further.

Thanks. `swiper-isearch` might have problems for regexes that don't advance the point. Could that be the case?

**Comment by mohkale** [comment]
@noctuid 

I'm still experiencing a pretty awful slowdown with orderless and `swiper-isearch`. Did you ever figure out how to fix it?

**Comment by noctuid** [comment]
I didn't have time to look into it further. I've just locked swiper to before that commit for now.
