### ISSUE TITLE
Delete duplicates in the result when using ivy-set-sources 

### ISSUE THREAD

**Issue by terlar** [abo-abo/swiper#2419]
I think it would be nice to either always remove duplicates (in the result) when using `ivy-set-sources` or perhaps provide an option for it if there is a case where you would not want to remove the duplicates.

**Comment by CeleritasCelery** [comment]
Are you saying in the circumstance where multiple sources return the same candidate?

**Comment by terlar** [comment]
Yes, that is correct, for example I have a combination of recentf and files in the current vcs, without de-duplication, I will have two candidates for the same file. I am assuming we could run something like `delete-dups` on the final results, like some other functions do?

**Comment by abo-abo** [comment]
@terlar Please check if this patch fixes your problem:

```elisp
(defun ivy--set-candidates (x)
  "Update `ivy--all-candidates' with X."
  (let (res)
    (dolist (source ivy--extra-candidates)
      (if (equal source '(original-source))
          (if (null res)
              (setq res x)
            (setq res (append x res)))
        (setq ivy--old-re nil)
        (setq res (append
                   (ivy--filter ivy-text (cadr source))
                   res))))
    (setq ivy--all-candidates (delete-dups res))))
```

The `delete-dups` call might cost us if `res` is very big.

**Comment by terlar** [comment]
@abo-abo Thank you, this seems to work well, even on a candidate list of 50000. But if you want to integrate this, perhaps it should be configurable in case someone have a huge `res`.

**Comment by abo-abo** [comment]
Thanks. I've enabled this by default. If there's an issue where it's slow, we'll customize it.
