### ISSUE TITLE
ivy-backward-kill-word doesn't kill-word?

### ISSUE THREAD

**Issue by mohkale** [abo-abo/swiper#2422]
not sure if this is intentional or not, but `ivy-backward-kill-word` actually deletes the last word instead of adding it to the kill ring. it's on [this](https://github.com/abo-abo/swiper/blob/master/ivy.el#L1678) line.

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by mohkale** [comment]
yep it's working, great work as always 😄.
