### ISSUE TITLE
ivy-occur edit does not work with windows encoded files

### ISSUE THREAD

**Issue by dinkonin** [abo-abo/swiper#2424]
When I edit a ivy-occur buffer (generated by counsel-rg) that has windows CRLF line endings (^M), wgrep-finish-edit always displays There are XX unapplied changes. and it does nothing. It works If I convert it to unix LF with set-buffer-file-coding-system and save it.

Tried it with helm-rg and it's working. I'm not sure this bug report  belongs here so I also posted it to the Emacs-wgrep repo.

Using emacs 26.3 on Arch linux.

**Comment by dinkonin** [comment]
Problem disappeared in emacs 27

**Comment by abo-abo** [comment]
Thanks for the info.
