### ISSUE TITLE
Byte compile warning: tramp-completion-mode

### ISSUE THREAD

**Issue by sergeyklay** [abo-abo/swiper#2428]
Hello, 

There is a warning related to unused `tramp-completion-mode` variable.

```
ivy.el:1042:1: Warning: Unused lexical variable ‘tramp-completion-mode’
```

Is this expected? Can this be fixed?

**Comment by abo-abo** [comment]
Strange, since it's wrapped in a `with-no-warnings` block. And I don't get this warning when I run `make compile` from the git repo.

What do you use to compile?

**Comment by sergeyklay** [comment]
I received this in `*Messages*` buffer while update packages

**Comment by abo-abo** [comment]
Seems we can't reproduce the problem. Doing either `make compile` or using <kbd>B</kbd> from `make plain` produces no warning for me.

**Comment by sergeyklay** [comment]
Well, let's close this for now. I'll ping you again in case of any news. Btw, this variable is obsolete since Emacs 26.1. I use Emacs 27 (compiled from source). Can this be the root of the problem?

**Comment by basil-conto** [comment]
> I use Emacs 27 (compiled from source). Can this be the root of the problem?

Yes, because `tramp-completion-mode` was removed in what will be Emacs 28. Commit 1b426e1215242cef61b65ee6a1d07840e22d4bce silences the warning.

**Comment by sergeyklay** [comment]
Thank you!
