### ISSUE TITLE
swiper-avy: show prompts in minibuffer

### ISSUE THREAD

**Issue by PythonNut** [abo-abo/swiper#243]
I generally keep my eyes on the minibuffer when using `swiper`. Showing `avy` hints in the minibuffer yields the following advantages:

* You don't need to look up to the buffer contents, you can select by keeping your eyes on the minibuffer.
* The minibuffer often shows more matches than can fit in the buffer, when the matches are widely spaced. Showing hints in the minibuffer would allow you to jump to them, even though they are not visible.

I propose that replacing the line numbers in the minibuffer with the hints would work particularly well.

Of course my proposed modifications are rather complex (they would require `swiper` specific implementations for some `avy` functions at the very least). Do you think the benefit would outweight the increased code complexity?

If you don't have time to implement this, but would accept at PR, I'd be open to working on it. (Can't guarantee, I'm persistent, but no lisp expert).

**Comment by PythonNut** [comment]
Ooh, I just stumbled across `ace-jump-helm-line` (which uses `avy`), and it's awesome. I wonder if a generalized `ivy-avy` could be made as well.

**Comment by abo-abo** [comment]
> If you don't have time to implement this, but would accept at PR, I'd be open to working on it. (Can't guarantee, I'm persistent, but no lisp expert).

Great idea. And I saw a bunch of your commits in ELPA recently, so I assume you have the copyright assignment.  Give it a try, I might work on the feature myself, but I don't have too much time lately.

> I wonder if a generalized ivy-avy could be made as well.

I think this is a way to go. Basically, `swiper-avy` already almost works like you want if you remove `with-ivy-window`. It only remains to debug it a bit.

**Comment by PythonNut** [comment]
> Great idea. And I saw a bunch of your commits in ELPA recently, so I assume you have the copyright assignment. Give it a try, I might work on the feature myself, but I don't have too much time lately.

Yup, I have my Copyright assignment. I'll see what I can do!

**Comment by PythonNut** [comment]
@abo-abo for some reason, I can't seem to get my function to select the current candidate and exit.

When I do `(execute-kbd-macro (kbd "<return>"))` it selects the current candidate and exits as if I had pressed <kbd>&lt;return&gt;</kbd>, but calling `(ivy-done)` seem to exit `ivy` without executing the action.

I'd rather not hardcode the keybinding, so how can I programatically act on the current candidate and exit?

**Comment by abo-abo** [comment]
The easy way:

```elisp
(ivy-quit-and-run
 (with-ivy-window
   (foo ivy--current)))
```

In a different way, like this:

```elisp
(defun counsel-find-symbol ()
  "Jump to the definition of the current symbol."
  (interactive)
  (ivy-set-action #'counsel--find-symbol)
  (ivy-done))
```

**Comment by PythonNut** [comment]
Is there any way I can do this generically for any `ivy` command?

**Comment by abo-abo** [comment]
Without changing the original code, you can use `ivy-set-actions`. This works for any command.
For some others that use a map, bind commands to that map.

**Comment by PythonNut** [comment]
I do believe this has been resolved. :)
