### ISSUE TITLE
ivy-read-action-ivy doesn't do action on the marked candidates

### ISSUE THREAD

**Issue by BooAA** [abo-abo/swiper#2430]
Emacs version : 28.0.50
commit : f42d57c7dbd571b449270c8899a67e537561c2b2

How to reproduce (testing with counsel-find-file) : 

step 0. ```(setq ivy-read-action-function 'ivy-read-action-ivy)```

step 1.  for a directory **test** containing 3 files: test1.txt, test2.txt, test3.txt, mark all of them with **ivy-mark**
![Screenshot from 2020-01-25 19-43-45](https://user-images.githubusercontent.com/32809182/73120723-751d4a00-3fac-11ea-9d4f-b6785ba1ee16.png)

step 2.  pressing M-o, select the default action (open file), and press Enter
![Screenshot from 2020-01-25 19-45-49](https://user-images.githubusercontent.com/32809182/73120596-58344700-3fab-11ea-900c-b5f7b68a0e8d.png)

expected result : all 3 files should be opened

actual result : Emacs create a new buffer called **>test2.txt**

I have also tested with the default ivy-read-action-by-key, the result is fine (except the issue in https://github.com/abo-abo/swiper/issues/2397)

**Comment by abo-abo** [comment]
I can reproduce the issue.

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by BooAA** [comment]
Thanks, that works great!
