### ISSUE TITLE
C-i messes my search! What action C-i does?

### ISSUE THREAD

**Issue by Godnyx** [abo-abo/swiper#2432]
I'll try to explain my problem as quick as possible! I use C-i to go to previous line (global-set-key (kbd "C-i") 'previous-line) and C-k to go to next line (global-set-key (kbd "C-k") 'next-line).

When it comes to swiper tho it seems that for search and find-file it uses your personal next-line and previous-line global keybindings and not the default ones. I figured that out cause if I change the keybindings in my global-map, the keybindings in swiper will also change!

But when is comes to C-i, it doesn't work! C-k normally goes to the next-line but C-i doesn't goes to the previous-line! This happens for both search and find-file. What does the C-i does in swiper and how can I change that?

P.S. I know that you can't totally mark this as an error but it can somehow be if you think that it messed me up and it may mess up other people too! You may also wanna add more instructions after this! So please help me and don't hate me! :)

**Comment by gusbrs** [comment]
For the record, this is a support request which was cross-posted at Reddit, and has been solved there: https://www.reddit.com/r/emacs/comments/evlhkj/swiper_ci_messes_my_search_what_action_ci_does/ffwn3vc/

**Comment by Godnyx** [comment]
I know man! Check my name! I just wrote this there to solve the problem as fast as possible! Thanks to you I did! Thanks again man!!!!!
