### ISSUE TITLE
ivy 0.13.0 ivy-avy command fails in list-packages buffer (as example)

### ISSUE THREAD

**Issue by rswgnu** [abo-abo/swiper#2438]
Latest release of ivy as of today on Emacs 27.0.50 on MacOS:

Do the following to trigger the error:
M-x list-packages RET
M-x ivy-avy RET
kl
------
Then this error pops up:

Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  substring-no-properties(nil)
  ivy--avy-action(9699)
  ivy-avy()
  funcall-interactively(ivy-avy)
  call-interactively(ivy-avy record nil)
  command-execute(ivy-avy record)
  #f(compiled-function (cmd) #<bytecode 0x40d6c1a7>)("ivy-avy")
  ivy-call()
  ivy-read("M-x " [## connection-failed ...
  counsel-M-x()
  funcall-interactively(counsel-M-x)
  call-interactively(counsel-M-x nil nil)
  command-execute(counsel-M-x)
----
On the other hand, avy-goto-line works fine and seems to do the same thing when called interactively, so I will use that as I always have with a key binding.

**Comment by abo-abo** [comment]
Thanks for the report. I've added a clarification to the code, since `ivy-avy` is not meant for <kbd>M-x</kbd>. We have to keep it `(interactive)` so that it can be bound to a key.
