### ISSUE TITLE
Open files via ssh doesn't work anymore

### ISSUE THREAD

**Issue by kurnevsky** [abo-abo/swiper#2439]
After entering host it doesn't go remotely and doesn't show candidates. When hitting entering path manually and hitting `/` it goes back to local file system.

Checked one revision from the past e22c8dfd28ab1874b71b68628666c22e1112495f - works there.

**Comment by abo-abo** [comment]
Please be more specific. Which command doesn't work for you? Is it `counsel-find-file`? What is your sequence of inputs?

**Comment by kurnevsky** [comment]
I'm trying it via `find-file` choosing `/ssh:`. It asks for server to use and after I choose it it doesn't go to this server.

**Comment by CsBigDataHub** [comment]
@abo-abo Yes, Counsel-find-file does not work anymore. I think one of the recent commit to `counsel.el` broke it. I tried it with remote servers and docker container with [docker-tramp.el](https://github.com/emacs-pe/docker-tramp.el) . Both instances counsel-file-find failed to tramp.

**Comment by CsBigDataHub** [comment]
@kurnevsky , Do you have any luck on your side after updating to `counsel-20200206.1816`. `Tramp` via `ssh or docker` not working to be yet from `counsel-find-file`.

@abo-abo , Sorry to bug you but any pointers on how to work around this issue and get `tramp` working from  `counsel-find-file` ?

**Comment by abo-abo** [comment]
Please try to reproduce the issue like this:

```sh
git clone https://github.com/abo-abo/swiper/
cd swiper
make plain
```

<kbd>C-x C-f /ssh: C-j</kbd>. For me, everything works as expected on GNU/Linux and Emacs 26.3.

**Comment by kurnevsky** [comment]
@abo-abo you are right, it works with default config but stops with `(setq ivy-re-builders-alist '((t . ivy--regex-fuzzy)))`.

**Comment by CsBigDataHub** [comment]
@abo-abo , @kurnevsky , yes its working  after emacs restart and disabling

```
;; https://oremacs.com/2016/01/06/ivy-flx/
    ;;(setq ivy-re-builders-alist
    ;;      '((ivy-switch-buffer . ivy--regex-plus)
    ;;        (t . ivy--regex-fuzzy)))
```

**Comment by abo-abo** [comment]
Thanks, please test with `ivy--regex-fuzzy`. It works for me.

**Comment by kurnevsky** [comment]
@abo-abo thanks, works now. But there is one thing it still fails - when you type `/ssh C-j user@server C-j` you get to the user's home directory. And if I remember correctly when after that I typed `/` it went to the `/` on remote server, but now it doesn't. I'm not sure that it's the case since it work consistency with and without `ivy--regex-fuzzy`.
