### ISSUE TITLE
counsel-git-grep - please add more control

### ISSUE THREAD

**Issue by jferguson-gnubio** [abo-abo/swiper#244]
Counsel-git-grep is very nice, but it would be much better if you could edit some of the grep options, perhaps via a hydra?  

e.g. you could toggle flags etc., much like with magit (-i, -w etc.)

or define a file match pattern - *.js, *.py etc. - very useful on large mixed language repos

**Comment by PythonNut** [comment]
Would it be okay to just prompt for the command line to run instead of making an interface that necessarily cannot express the full spectrum of options you could choose?

**Comment by jferguson-gnubio** [comment]
That probably would work fine, yes.

**Comment by abo-abo** [comment]
Thanks. This is useful for grepping in only certain files.
What I do now, given `counsel-git-grep` is bound to <kbd>C-c j</kbd>: <kbd>C-u C-c j M-i</kbd> ` -- '*.cc'` <kbd>C-m</kbd>.
Afterwards, this query will be available until Emacs restart.

**Comment by jferguson-gnubio** [comment]
That's excellent - thank you.  I much appreciate your work.  I've just switched to ivy/swiper/counsel from helm after I still found helm awkward and unintuitive at times after 8 months of trying.  I'm much preferring your lighter touch.
