### ISSUE TITLE
counsel-git-grep not giving expected results

### ISSUE THREAD

**Issue by bimbiltu** [abo-abo/swiper#2441]
I have a git repository with a file containing the text `this.$store.state`. When searching the repo with `counsel-git-grep` I noticed that entering `this.$store.st` shows 1 result as expected. Entering any more text, such as another "a" bringing the search to `this.$store.sta`, gives 0 results. If I escape the `$` with a `\` then I will always see the 1 result I am expecting.

Is this behavior expected? Running `git grep 'this.$store.sta'` on the command line still gives 1 result but I am pretty sure that counsel does not necessarily pass what I am typing to `git grep` verbatim.

Edit: not sure if its relevant here, but I'm using git 2.21.1 and the latest version of counsel

**Comment by abo-abo** [comment]
This is expected behavior. You should enter `this.\$store.st` in your search, since we're searching by regex.

> am pretty sure that counsel does not necessarily pass what I am typing to git grep verbatim.

This is true. If the input is `blah blah`, counsel will pass `blah.*blah` to git.

**Comment by bimbiltu** [comment]
> If the input is blah blah, counsel will pass blah.*blah to git

Are there any other changes, like to the `.` and `$` characters? My search does not have any spaces, so I'm still confused about the result discrepancy between `counsel-git-grep` and `git grep` command line. Either way, this isn't really a big deal for me since escaping the `$` works and is probably a good habit to get into anyways 😄
