### ISSUE TITLE
ivy-dispatching-done doesn't display any options

### ISSUE THREAD

**Issue by d12frosted** [abo-abo/swiper#2444]
Hello,

`M-o` (`ivy-dispatching-done`) doesn't show any options (thought they are accessible). Here are some screenshots.

<img width="991" alt="image" src="https://user-images.githubusercontent.com/6507913/73956403-9582c800-490d-11ea-8ba8-a39e8fb5a83e.png">

After hitting `M-o`:

<img width="991" alt="image" src="https://user-images.githubusercontent.com/6507913/73956438-a2072080-490d-11ea-9203-9186eb4fb10d.png">

I expect it to show possible actions:

<img width="1057" alt="image" src="https://user-images.githubusercontent.com/6507913/73956730-07f3a800-490e-11ea-9cdb-ce14fa6c97f2.png">

Reproduces on the latest master when running with `make plain` (this is so cool to have it!).

What's interesting, the bug reproduces only on the latest Emacs (GNU Emacs 28.0.50). In Emacs 26.3 everything works perfectly. So this issue might be not directly related to `swiper`.

P. S. Reproducible on Arch Linux as well (so it's not something macOS specific).

**Comment by Ergus** [comment]
Hi:
I am facing this same issue.  With emacs master branch and arch linux.
Any progress on this??

**Comment by abo-abo** [comment]
> Any progress on this??

The current workaround is to set `ivy-read-action-function` to either `ivy-read-action-ivy` or `ivy-hydra-read-action`.

You can use <kbd>M-x</kbd> `report-emacs-bug` to make the Emacs devs aware of the issue.

**Comment by Ergus** [comment]
Hi @abo-abo:

I can't report this as it to emacs developers as ivy is not a core emacs package. Have you an idea about what is failing inside emacs? So I could report that issue directly?

**Comment by abo-abo** [comment]
This is not an Ivy bug, it's a regression in Emacs that causes `read-key` function to not display the prompt if called from `read-from-minibuffer`. This should be good enough for a report.

```elisp
(let ((map (make-sparse-keymap)))
  (define-key map (kbd "C-f") (lambda ()
                                (interactive)
                                (message "%S" (read-key "line1\nline2\nline3\nTest2: "))
                                (minibuffer-keyboard-quit)))
  (read-from-minibuffer "Test1: " nil map))
```

**Comment by Ergus** [comment]
Reported to emacs developers:

https://debbugs.gnu.org/cgi/bugreport.cgi?bug=39564

**Comment by abo-abo** [comment]
Closing this as it's similar to #2357. Let's follow up there.
