### ISSUE TITLE
ivy-immediate-done with M-x

### ISSUE THREAD

**Issue by mcfarljm** [abo-abo/swiper#2448]
It appears that trying to use `ivy-immediate-done` for function name completion (e.g., under counsel-M-x or describe-function) produces an error: `wrong type argument, commandp`.  Is there some other way to use current input instead of current candidate for function names?  Otherwise, the completion can really get in the way in certain situations.

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by mcfarljm** [comment]
Testing with 6a902b5, but now I get an error using `M-x`, regardless of whether I use `ivy-immediate-done` or just accept the current candidate.  Either way, I get the error:
```
symbol's function definition is void: string-trim-left
```

To recreate:
```
make plain
M-x switch-to-buffer <return>
```
I'm using emacs 26.3.

**Comment by mcfarljm** [comment]
On 82331ed, the above `string-trim-left` error is resolved, but I still get the original error when using `ivy-immediate-done`.

Here are the steps:
```
make plain
M-x switch to buffer <C-M-j>
```
Note: I am typing out `switch to buffer` using spaces (not dashes).  I noticed that `ivy-immediate-done` will work if I explicitly type out dashes.

This may actually raise a larger issue of what the intended behavior is, as it seems spaces have a special meaning in ivy completion, whereas normally within `M-x`, spaces are simply replaced with dashes.  I think it would be ideal if `ivy-immediate-done` did work for function completion with spaces.  Otherwise, I'm wondering if there is another workflow that I am missing?  Is there a better way of achieving something like `ivy-immediate-done` within `M-x`?  I find that I frequently encounter a situation where after typing the full function name (using spaces), the highlighted candidate is not the literal entry, and I need to manually select the desired entry using `C-n`.

**Comment by abo-abo** [comment]
OK, I see the issue now. You should be using <kbd>RET</kbd> (`ivy-done`) or <kbd>C-j</kbd> (`ivy-alt-done`).

The functionality of <kbd>C-M-j</kbd> `ivy-immediate-done` is to return the exact minibuffer contents. The main use case is to create a file `foo` when a file `foobar` already exists. As `ivy-done` would simply select `foobar` with the input `foo`.

**Comment by mcfarljm** [comment]
Yes, but I I'm trying to say that there seems to be also use cases for `ivy-immediate-done` with function name completion from either `M-x` or `C-h f`.  For example, try to run the command `ediff-buffers`.  With ivy, this requires either typing the dash character (which I don't think is how function names are normally entered interactively), or the following workflow:
1. `M-x ediff buffers`
2.  Maybe hit enter and then realize after the fact that you're actually running `ediff-buffers3` because that is the first candidate, even though the full name of the function was typed.  At this point, quit, and go back to step 1.
3.  Pause and look at the resulting candidate list.  Navigate to desired selection using C-n (`ivy-next-line`).

I may poke around in the code and see if I can come up with a patch to submit.  It seems that in principle all that is needed is to have `ivy-immediate-done` replace spaces with dashes prior to dispatching when doing function name completion.

**Comment by mcfarljm** [comment]
Another thing that I just noticed is that the order of the candidate list is different with `M-x` and `C-h f`.  Here are examples when using the input `^ediff buffers`.  With `C-h f`, the expected item shows up first, but not with `M-x` in this case.

![m-x](https://user-images.githubusercontent.com/626029/74394766-20166c00-4dd3-11ea-9938-41f2eac38556.png)
![describe](https://user-images.githubusercontent.com/626029/74394780-2a386a80-4dd3-11ea-8101-a49202a024d9.png)

**Comment by abo-abo** [comment]
> Another thing that I just noticed is that the order of the candidate list is different with `M-x` and `C-h f`

This is due to `smex` or `amx`. For `counsel-M-x` the most recent candidates will be sorted first.
