### ISSUE TITLE
ivy-hydra not showing up

### ISSUE THREAD

**Issue by paulbdavis** [abo-abo/swiper#2449]
Since I updated my init to using straight.el whenever I invoke a hydra while using ivy it no longer shows up. Instead the minibuffer shrinks down to just the top line of the ivy selection (the header line?). All of the commmands still work, for example I have `M-o v` wired in my hands when picking a project with projectile and it's still working, I just don't actually see the hydra anymore. This also presents when I invoke the regular hydra when switching buffers or opening files.

I tested a regular hydra and it works as expected. I also tested on a stripped down config that just sets up straight and installs the counsel packages and hydra and it was still happening.

Emacs version: `GNU Emacs 27.0.60 (build 4, x86_64-pc-linux-gnu, GTK+ Version 3.24.13, cairo version 1.17.3) of 2020-02-08`

EDIT: Tried emacs 26 and the hydra shows up in ivy, but it's not formatted, just shows up in one big column (regular hydras are formatted correctly)

EDIT2: Checked out the `0.13.0` tag and it's all working again, so this must have been introduced since then on master

**Comment by CsBigDataHub** [comment]
ivy-hydra is shipped as a separate package in Melpa. 

Add this to your configuration - 

```
(use-package ivy-hydra
      :ensure t)
```

**Comment by abo-abo** [comment]
Interesting. But it would be difficult to reproduce your config. Could you please bisect the issue further to a commit where it goes wrong?

**Comment by angerborn** [comment]
I *think* that this is where the issue was introduced

https://github.com/abo-abo/swiper/commit/1ad457d8e76c431783d2efb866ef51b8c14e7c82#diff-59c8f3240a0249f3809ead0286a450b7L129

Previously the hydra was used as default but now it'll default to use `ivy-read-action-by-key` instead.

**Comment by abo-abo** [comment]
So is this a fix?

```elisp
(setq ivy-read-action-function #'ivy-hydra-read-action)
```

**Comment by angerborn** [comment]
Yes, at least it is for me.

**Comment by abo-abo** [comment]
OK, closing.
