### ISSUE TITLE
ivy-resume after swiper goes back to the first result

### ISSUE THREAD

**Issue by brabalan** [abo-abo/swiper#245]
When I use `ivy-resume` after a `swiper` search, the highlighted result is the first one. Is it possible to resume at the same place where swiper was exit?

(To put this in context, I'm trying to understand how to do the same thing than `C-s C-s` using swiper.)

**Comment by abo-abo** [comment]
Thanks.

**Comment by brabalan** [comment]
I just realized I did not report that this works great now. Thanks!

**Comment by cruegge** [comment]
For some reason, this still does not work for me. It seems as if `ivy--preselect-index` indeed returns the proper index, but the search still restarts at the top. Minimal example to reproduce the problem is `emacs -Q`, and then putting

```
(setf package-load-list '((swiper t))
(package-initialize)
(global-set-key (kbd "C-c s") #'swiper)
(global-set-key (kbd "C-c h") #'ivy-resume)
```

into the scratch buffer and `eval`ing it.

**Comment by abo-abo** [comment]
@cruegge Thanks, should be fixed now.

**Comment by cruegge** [comment]
Thanks, works perfectly now.
