### ISSUE TITLE
commit 2229801 trim left ^, breaks compatibility with emacs 25.x

### ISSUE THREAD

**Issue by bymoz089** [abo-abo/swiper#2452]
Recent commit https://github.com/abo-abo/swiper/commit/222980158915e87e3ae15d47cd79dc9c042e85ab breaks compatibility with emacs versions 25.x.

Within emacs 25.x `string-trim-left` accepts only one parameter `(string-trim-left STRING)`. and only removes whitespace.
The optional RegEx parameter first occured in emacs v26.1.

 ----

This is severe for users of Emacs v25.x because all calls with `counsel-M-x` result in an error message: 

    counsel-M-x-action: Wrong number of arguments: (1 . 1), 2

 ----

Quickfix for users of emacs 25.x, put this in your config file and eval it after loading of `subr-x.el`:

      (when (version< emacs-version "26.1")
        (defsubst string-trim-left (string &optional regexp)
          "Trim STRING of leading string matching REGEXP.
    REGEXP defaults to \"[ \\t\\n\\r]+\"."
          (if (string-match (concat "\\`\\(?:" (or regexp "[ \t\n\r]+") "\\)") string)
              (substring string (match-end 0))
            string)))

**Comment by abo-abo** [comment]
Thanks.
