### ISSUE TITLE
swiper with empty entry fails

### ISSUE THREAD

**Issue by Ergus** [abo-abo/swiper#2453]
Hi:

When C-s C-s instead of using the last search string is starts a nested swiper inside swiper and C-s again creates another nested swiper and so on. 

here is an attached image using make plain (adding -nw in the makefile)

![image](https://user-images.githubusercontent.com/6975176/74233827-bd867880-4ccb-11ea-9b57-580c7bebc33c.png)

![image](https://user-images.githubusercontent.com/6975176/74233878-dd1da100-4ccb-11ea-

This started with commit: 27b2ae5175678e41b4dca3c60712bf72696f8501

**Comment by Ergus** [comment]
Reverting that commit fixed the issue for me.

**Comment by BooAA** [comment]
Having same issue here, I also fix it but reverting that commit.

**Comment by abo-abo** [comment]
Thanks. Reverted the commit for now.
