### ISSUE TITLE
Error when calling counsel functions

### ISSUE THREAD

**Issue by sati-bodhi** [abo-abo/swiper#2455]
I run into this error when running `counsel-find-file`. Other counsel functions are also affected by it. 

> Debugger entered--Lisp error: (void-function ivy-configure)
>   (ivy-configure (quote counsel-el) :height 7)
>   autoload-do-load((autoload "counsel" "Forward to `find-file'.\nWhen INITIAL-INPUT is non-nil, use it in the minibuffer during completion.\n\n(fn &optional INITIAL-INPUT)" t nil) counsel-find-file)
>

**Comment by abo-abo** [comment]
This may be a package.el install issue. Please try to re-install ivy/counsel and restart Emacs.

**Comment by sati-bodhi** [comment]
Reinstalling `ivy` and restarting emacs worked. Thanks!
