### ISSUE TITLE
swiper-isearch shows empty results sepcial buffers

### ISSUE THREAD

**Issue by CSRaghunandan** [abo-abo/swiper#2456]
`swiper` works fine on special buffers  like `treemacs` or `dired` or `help`, whereas `swiper-isearch` shows no results when I invoke it.

I only recently noticed this as I started using `swiper-isearch` instead of `swiper`

**Comment by bymoz089** [comment]
I can **not** confirm.

`swiper-isearch` is working in `dired` and `help` buffers within my setup. Latest ivy, swiper, counsel with Emacs 25.x on Linux.

Did not test with `treemacs`, because it is not installed on my system.

**Comment by abo-abo** [comment]
Same for me. Please try to reproduce with `make plain`.

**Comment by CSRaghunandan** [comment]
> Same for me. Please try to reproduce with `make plain`.

How do I do that ? Please provide me with instructions?

Also, I tried this with `emacs -Q` and I could reproduce the same issue.

**Comment by CSRaghunandan** [comment]
> I can **not** confirm.
> 
> `swiper-isearch` is working in `dired` and `help` buffers within my setup. Latest ivy, swiper, counsel with Emacs 25.x on Linux.
> 
> Did not test with `treemacs`, because it is not installed on my system.

I see, maybe this is an isolated issue with emacs 27 or emacs 28? Not sure at this stage

**Comment by abo-abo** [comment]
> How do I do that ? Please provide me with instructions?

```sh
git clone https://github.com/abo-abo/swiper/
cd swiper
make plain
```

**Comment by CSRaghunandan** [comment]
> > How do I do that ? Please provide me with instructions?
> 
> ```shell
> git clone https://github.com/abo-abo/swiper/
> cd swiper
> make plain
> ```

I can reproduce the same issue with `make plain`. `swiper-isearch` returns an empty list for any non-file visitng buffers.

Here is my emacs environment:

```
Emacs version: GNU Emacs 28.0.50 (build 5, x86_64-pc-linux-gnu, GTK+ Version 3.24.13, cairo version 1.17.3)
 of 2020-02-17, built using commit 556cc727e5076d590f8286406e4f46cff3cee41e.

./configure options:
  --with-modules --with-rsvg --with-dbus --with-imagemagick --without-pop --with-xft --with-x-toolkit=gtk3 --with-libotf --with-xml2

Features:
  XPM JPEG TIFF GIF PNG RSVG CAIRO IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP
```

**Comment by abo-abo** [comment]
Can't reproduce with the latest emacs master (734eb7e457da8a9b2c91798d591c03285c6967ce):

    emacs=~/git/gnu-emacs/src/emacs make plain

<kbd>M-x</kbd> `swiper-isearch` in the `*scratch*` buffer works as expected.

**Comment by CSRaghunandan** [comment]
> Can't reproduce with the latest emacs master (734eb7e457da8a9b2c91798d591c03285c6967ce):
> 
> ```
> emacs=~/git/gnu-emacs/src/emacs make plain
> ```
> 
> M-x `swiper-isearch` in the `*scratch*` buffer works as expected.

I'll try compiling emacs from latest master branch and report if it works.

Besides that, is there anyway I could debug this issue?

**Comment by CSRaghunandan** [comment]
> > Can't reproduce with the latest emacs master (734eb7e457da8a9b2c91798d591c03285c6967ce):
> > ```
> > emacs=~/git/gnu-emacs/src/emacs make plain
> > ```
> > 
> > 
> > M-x `swiper-isearch` in the `*scratch*` buffer works as expected.
> 
> I'll try compiling emacs from latest master branch and report if it works.
> 
> Besides that, is there anyway I could debug this issue?

Okay, I'm still facing the same issue. I even tried reinstalling swiper, but still running into the same issue

**Comment by CSRaghunandan** [comment]
I sound really stupid, but looks like I really didn't understand how `swiper-isearch` works.

`swiper`, when you first begin the search, displays a list of candidates and narrows it down as you type and `swiper-isearch` has an empty list when invoked and when you start typing, it populates the results.

I thought `swiper-isearch` was supposed to work like `swiper`, and when it didn't show any results when I invoked it, I thought wasn't working. Oops, my bad

**Comment by abo-abo** [comment]
No problem)
