### ISSUE TITLE
swiper-isearch in org-mode does not fold back

### ISSUE THREAD

**Issue by ilautar** [abo-abo/swiper#2457]
Scenario:
1) have `org-mode` with folded trees (with content below those trees)
2) start `swiper-isearch` and search for something that matches what is INSIDE tree (ie., case where first match matches text on top lvl works fine)
3) first match will unfold tree that matches in searched buffer
4) pressing `C-g` will cancel search, return cursor where it was before search, but will NOT fold the newly unfolded (by `swiper-isearch` first match) tree

The same behaviour is also for any match, not just first one, if you `C-n` to it to show in original buffer and then press `C-g`.

Test case:
1) use the following content for org file, fold all items
```
* HEADING 1
** test1
* HEADING 2
** test2
* HEADING 3
** test3
```
2) `swiper-isearch` for "test"
3) `C-g`
4) HEADING 1 stays unfolded

Environment: Mac OSX 10.11.6, Emacs -Q, Emacs 26.3, swiper 20200122.1153, ivy 20200211.1338

**Comment by abo-abo** [comment]
Hi. I can't reproduce the bug with `swiper-isearch` when using `make plain` from this repo. But I could reproduce it for `swiper`, and it should now be fixed.

Please check with `make plain` and with your config.

**Comment by basil-conto** [comment]
Is this still an issue?

**Comment by ilautar** [comment]
Works now. Swiper version 5f1d9ce04599c52818244c2cb8cb066a601610b8 (from git repo by doom emacs).
