### ISSUE TITLE
Command like grep only for subdirectories?

### ISSUE THREAD

**Issue by Ergus** [abo-abo/swiper#2458]
Hi:

This is not an issue, but a question.  If we have a project with many subdirectories and files inside them; and I want to do a grep search withing one of the directories (like M-x grep or M-x rgrep) with the actual counsel-rg (and similars) it tends to search all the occurences in the whole project not only in the actual directory and/or the subdirectories. Do we have a command to do a local search only in "this" directory in counsel??

**Comment by abo-abo** [comment]
You can use <kbd>C-x C-d</kbd> `counsel-cd` to change the current directory of the grep. The current directory defaults to the git root of the project.

If the current buffer is in the project, its directory will be pre-selected for `counsel-cd`.
