### ISSUE TITLE
Mini-buffer to display one matching sentence at a time for Chinese texts

### ISSUE THREAD

**Issue by sati-bodhi** [abo-abo/swiper#2461]
This is not a bug, just a personal question to tweak swiper in my own `init.el` file. 

I use org-mode to process Chinese texts, which often have paragraphs spanning over a single line. This makes the swiper display not as user-friendly as it is meant to be. 

![圖片](https://user-images.githubusercontent.com/7592695/74750720-214e0a00-52a7-11ea-85a8-04cdb9d0b039.png)

Is it trivial to tweak the code so that the mini-buffer only displays a single sentence (between two `。`s) with a matching pattern at a time? 

I would appreciate your guidance to work on the tweak, if possible.

**Comment by abo-abo** [comment]
Try using `ivy-format-functions-alist`:

```elisp
(defun swiper--format (cands)
  (ivy--format-function-generic
   (lambda (sel-str)
     (ivy--add-face (substring sel-str 0 (min (length sel-str) 10)) 'ivy-current-match))
   (lambda (oth-str)
     (substring oth-str 0 (min (length oth-str) 10)))
   cands
   "\n"))

(setq ivy-format-functions-alist
      '((swiper . swiper--format)
        (t . ivy-format-function-default)))
```

**Comment by sati-bodhi** [comment]
The code doesn't work as expected. Besides shortening the sub-string, we actually need to focus on the matching points on each line, in between two `。`s. 

![圖片](https://user-images.githubusercontent.com/7592695/74933521-21711580-541f-11ea-9572-78e385da0e10.png)

**Comment by abo-abo** [comment]
The code is only to show how `ivy-format-functions-alist`, not the full solution.

You can code up the full solution by updating the two lambda functions to do a `string-match`. See also `ivy-text` and `ivy-regex`.

**Comment by sati-bodhi** [comment]
Okay, thanks! I will try working out with the code and see how it goes.
