### ISSUE TITLE
Counsel-find-file with "other window" action will not work if the path is changed

### ISSUE THREAD

**Issue by BooAA** [abo-abo/swiper#2464]
Emacs version : emacs28 with commit 52dbd70f0ed6896c3524d14834b489cef8584ada
How to reproduce : 

1. C-x C-f (counsel-find-file) 
2. change path to other directory 
3. M-o, select the "other window" action

Expected result: the selected file should be open in other window
Actual result: A new buffer having same name with the selected file is created

GIF:
![Peek 2020-02-20 22-23](https://user-images.githubusercontent.com/32809182/74943748-dad7e700-542f-11ea-9211-b47282bf4e3a.gif)

If the path hasn't been changed (e.g. the same as where counsel-find-file was invoked, the result is correct)

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by BooAA** [comment]
Works great, thanks.
