### ISSUE TITLE
Swiper does not honor search-default-mode set to nil?

### ISSUE THREAD

**Issue by ThibautVerron** [abo-abo/swiper#2465]
Hello,

I am a bit confused, and to be honest it is very possible that I am missing something. I noticed the suggested setting

```
(setq search-default-mode #'char-fold-to-regexp)
```

in the README, so `swiper` must examine this variable somehow... but is it correct that it does not obey the more basic (and default) setting of `nil`? Essentially, is it either `t` or a custom function?

It turns out that `char-fold-to-regexp` also escapes backslashes, so it basically emulates the `nil` setting, plus char folding. Is there an option for having literal search, without char folding and without regexp, like `isearch` does by default, but with the fuzzy or magic space matching added by ivy?

I imagined that setting `search-default-mode` to `regexp-quote` would work, but it doesn't.

My use-case is that I edit a lot of LaTeX code, which makes heavy use of backslashes, which I don't want to escape every time I search. I could also imagine that such an option would be convenient for users searching for regexp fragments...

**Comment by ThibautVerron** [comment]
After looking at the code, it looks like `swiper` is set to only obey the specific value `char-fold-to-regexp` of `search-default-mode`, so it is not surprising that setting it to `regexp-quote` did not work.

Is there a good reason why it can't apply any "string-to-regexp" function in the same way?

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by ThibautVerron** [comment]
Thanks, it seems to be working.

**Comment by ThibautVerron** [comment]
For the record, `#'regexp-quote` seems to be an illegal value for `search-default-mode` with `isearch`.
