### ISSUE TITLE
accessing the last input in an ivy action

### ISSUE THREAD

**Issue by drorbemet** [abo-abo/swiper#2467]
Which is the idiomatic way for every ivy-read application to access the last state of the query input of an ivy minibuffer in a subsequently called ivy action function even if input is empty?

The specific history of an ivy-read application e.g. counsel-git-grep doesn't tell me if the last input was empty.

Given some action function e.g. :action #'counsel-git-grep-action

```elisp
(ivy-inhibit-action t)
(ignore-errors (counsel-git-grep))
(car counsel-git-grep-history) 
```
=> Returns the last non-empty input, but what was the last input?

Calling from an ivy-minibuffer-key-map the following works. 
But this too returns the selected candidate if input is empty.

```elisp
(defun counsel-insert-input ()
  "Insert the current ivy input at point."
  (interactive)
  (setq ivy--input-current (ivy--input))
  (ivy-exit-with-action
   (lambda (x) (with-ivy-window
                 (insert ivy--input-current)))))
```

What is the idiomatic way to query the ivy state for the current state of input in any ivy action function?

**Comment by abo-abo** [comment]
You can look at `ivy-text`.

**Comment by drorbemet** [comment]
Ah, there it was! Thanks.
