### ISSUE TITLE
can't set default action for command.

### ISSUE THREAD

**Issue by mohkale** [abo-abo/swiper#2468]
I'm unable to change the default action for a command. 

eg.

```elisp
(ivy-set-actions 'counsel-fonts
                 '(("o" describe-font "describe-font")))
```

setting this and then invoking `counsel-fonts` just runs the default action (as specified by the call to `ivy-read`). Calling `ivy-dispatching-done` while running `counsel-fonts` shows "o" being bound to both the default actions, and the one I've specified.

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by mohkale** [comment]
yep, works great 😄, only issue is in the dispatch menu the command is still named "default". Not sure if that's a design choice or a bug, but shouldn't it use the specified name (in this case "describe-font") when it's offered?

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by mohkale** [comment]
Yep, works perfectly 😄.
