### ISSUE TITLE
ivy-read-action broken (in Emacs >= 27) 

### ISSUE THREAD

**Issue by agzam** [abo-abo/swiper#2469]
For some reason ivy-read-action no longer works. 

if I set:

    (define-key ivy-minibuffer-map (kbd "M-o") 'ivy-read-action)
    
and then pressing `<M-o>` doesn't show actions, it just hides Ivy buffer.

![ivy-bug](https://user-images.githubusercontent.com/1091022/75490844-c03eca00-5969-11ea-984e-48dbbb52b85a.gif)

**Comment by abo-abo** [comment]
There are some problems on Emacs-28 with the default setting. Should still work fine with 26.3.

It's recommended to customize `ivy-read-action-function` to either `ivy-read-action-ivy` or `ivy-hydra-read-action` for Emacs-28.

**Comment by agzam** [comment]
Oh... alright. That does the trick! Thanks a lot @abo-abo

I guess I'm gonna keep the issue open for a while, so people can find it.

**Comment by BooAA** [comment]
> I guess I'm gonna keep the issue open for a while, so people can find it.

Actually there are already 2 similar issues opened already. #2444  #2397

**Comment by agzam** [comment]
Speaking of actions, can someone teach me how to bind "open-in-other-window" action to a key in ivy-minibuffer-map. Thank you.

**Comment by abo-abo** [comment]
@BooAA Thanks for the links. Will close this issue in favor of #2397.
@agzam You can use this code:

```elisp
(define-key ivy-minibuffer-map
    (kbd "M-J")
  (lambda () (interactive)
     (execute-kbd-macro (kbd "M-o j"))))
```
