### ISSUE TITLE
Visual line mode breaks avy

### ISSUE THREAD

**Issue by PythonNut** [abo-abo/swiper#247]
Steps:

1. `emacs24.5 -Q`
2. <kbd>M-x</kbd> `visual-line-mode` <kbd>RET</kbd>
3. <kbd>M-x</kbd> `package-initialize` <kbd>RET</kbd>
4. <kbd>a</kbd> (insert into the last line of `*scratch*`)
4. <kbd>M-x</kbd> `swiper` <kbd>RET</kbd>

All that happens is the following in the minibuffer:

> End of buffer

**Comment by abo-abo** [comment]
Thanks.
