### ISSUE TITLE
Error `ivy--dynamic-collection-cands: Wrong type argument: sequencep, 0`

### ISSUE THREAD

**Issue by sarg** [abo-abo/swiper#2472]
Seems that the fix in #2355 have introduced breaking change for those clients who return numeric value from COLLECTION function. One such case is [counsel-spotify](https://github.com/Lautaro-Garcia/counsel-spotify/blob/53af9a650d22214ea917f621e02ffd5731f5fad5/counsel-spotify.el#L304).

With latest ivy I get `ivy--dynamic-collection-cands: Wrong type argument: sequencep, 0`
I couldn't find from documentation whether the usage of `ivy-read` is somehow wrong from counsel-spotify side, so I'm opening an issue here.

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by sarg** [comment]
It works, thanks  a lot!
