### ISSUE TITLE
How do I search for a regular regex in swiper?

### ISSUE THREAD

**Issue by haji-ali** [abo-abo/swiper#2474]
This is probably a basic question, but I couldn't find an answer in the manual.

Is it possible to search for a regular regex in swiper? 
So that (temporarily) fuzzy matching is disabled?

**Comment by abo-abo** [comment]
There's <kbd>M-r</kbd> for `regexp-quote`. This could be extended to use `identity` instead of `regexp-quote`.

There's also `swiper-isearch-toggle`.

**Comment by haji-ali** [comment]
Thanks, that's exactly what I was looking for!
In case someone else want this functionality, I implemented this with

```
(defvar ivy--identity #'identity
  "Store the identity state.")
(advice-add 'ivy--reset-state :before (lambda (&rest r) (setq ivy--identity #'identity)))

(defun ivy-toggle-regexp-quote ()
  "Toggle the regexp quoting."
  (interactive)
  (setq ivy--old-re nil)
  (cl-rotatef ivy--regex-function ivy--regexp-quote ivy--identity)
  (setq ivy-regex (funcall ivy--regex-function ivy-text)))
)
```

**Comment by hongyi-zhao** [comment]
But how to enable the regexp search support for `dap-mode`, say, in its locals buffer, as shown below:

![image](https://user-images.githubusercontent.com/11155854/136699111-75f8fc83-f540-47cd-b3bd-d1266383e104.png)

**Comment by basil-conto** [comment]
> But how to enable the regexp search support for dap-mode, say, in its Locals buffer, as shown below:

Looks like this was already answered in https://github.com/emacs-lsp/dap-mode/issues/525#issuecomment-939494301.
