### ISSUE TITLE
Ripgrep without pcre2 enabled isn't detected with counsel-rg

### ISSUE THREAD

**Issue by ambihelical** [abo-abo/swiper#2478]
If I build ripgrep without pcre2 (the default with cargo), then counsel-rg will error out with more then one term is given.  By error out, I mean there are no results except the string "error code 2". 

If I print the output of counsel-format-ag-command, using the following change:

```
(defun counsel--format-ag-command (extra-args needle)
  "Construct a complete `counsel-ag-command' as a string.
EXTRA-ARGS is a string of the additional arguments.
NEEDLE is the search string."
  (let ((output
         (format counsel-ag-command
                 (if (string-match " \\(--\\) " extra-args)
                     (replace-match needle t t extra-args 1)
                   (concat extra-args " " needle)))))
    (message "output is %s" output)
    output))
```

I get the following output for the input "foo bar"

`output is rg --with-filename --no-heading --line-number --color never   --pcre2  -i  \^\(\?\=.\*foo\)\(\?\=.\*bar\)
`

Running this with rg from cargo, which is the one in the path emacs is using:

```
▶ \rg --with-filename --no-heading --line-number --color never   --pcre2  -i  \^\(\?\=.\*foo\)\(\?\=.\*bar\)
PCRE2 is not available in this build of ripgrep
▶ echo $?
2
▶ which \rg
/home/work/.cargo/bin/rg
```
If I run the test that it looks like the code uses, I get this.  I guessing this should also return 2, but it does not.
```
▶ \rg --pcre2 --version
ripgrep 11.0.2
-SIMD -AVX (compiled)
+SIMD -AVX (runtime)
▶ echo $?
0
```

**Comment by abo-abo** [comment]
PRs welcome to fix this. I assume most people use a pcre2-enabled version of `rg`. I'm using `rg 0.10.0` provided by the `ripgrep` Debian package.

**Comment by ambihelical** [comment]
Done.  Not tested under Windows or Mac as I have neither.

**Comment by CeleritasCelery** [comment]
@ambihelical looks like this can be closed
