### ISSUE TITLE
Using swiper alters help-mode text highlighting

### ISSUE THREAD

**Issue by frostidaho** [abo-abo/swiper#248]
If you use swiper on a help-mode buffer which contains the " character it will be subsequently highlighted like a literal string.

 An example of this behavior is given [here](http://gfycat.com/MatureNegligibleIndianrockpython).

I did a quick [test](http://gfycat.com/SpanishReasonableBrownbutterfly) and this behavior doesn't occur when the buffer is in text-mode, only when it is in help-mode.

**Comment by abo-abo** [comment]
Thanks.
