### ISSUE TITLE
Slow counsel-rg when searching in files with long lines

### ISSUE THREAD

**Issue by sebastiansturm** [abo-abo/swiper#2482]
when searching in directories containing minified JavaScript or other files with excessively long lines, `counsel-rg` can slow down to a crawl (`ivy-occur` even more so when invoked on the resulting list of candidates). What do you think about adding `'--max-columns 200'` and `'--max-columns-preview'` to the default arguments passed to `rg`?

**Comment by abo-abo** [comment]
Thanks.

**Comment by ambihelical** [comment]
Is there a reason why --max-columns-preview wasn't added when this was added?  Without it ANY long lines greater than 120 show` [Omitted long line with # matches]` only. While with it ripgrep shows the part of the match < 120 chars and the rest is `[... # more matches]`, which seems much preferable.

**Comment by sherrman** [comment]
@abo-abo This change breaks using `wgrep` because the contents are no longer there to edit.

**Comment by jdelStrother** [comment]
If the aim is to fix performance issues with minified javascript, surely that's looking for lines that are several kb in length?  120 seems an extremely low cutoff.
And shouldn't those files be gitignored, anyway?  `rg` doesn't search those files at all for me.

**Comment by sebastiansturm** [comment]
> If the aim is to fix performance issues with minified javascript, surely that's looking for lines that are several kb in length? 120 seems an extremely low cutoff.

yes, 120 is pretty aggressive; something like 500 would probably do the job just as well

> And shouldn't those files be gitignored, anyway? `rg` doesn't search those sort of files at all for me.

gitignored, maybe. rgignored, probably. But that's a bit beside the point IMO because sometimes you're navigating other people's projects and I wouldn't want to have to patch up their project-local config files just to help out my editor

**Comment by jdelStrother** [comment]
> gitignored, maybe. rgignored, probably. But that's a bit beside the point IMO because sometimes you're navigating other people's projects and I wouldn't want to have to patch up their project-local config files just to help out my editor

fair enough.

In case anyone ends up here googling for those `Omitted long line` messages, I fixed it locally with:

```emacs-lisp
(setq counsel-rg-base-command
  "rg --max-columns 500 --with-filename --no-heading --line-number --color never %s")
```

**Comment by abo-abo** [comment]
> Is there a reason why --max-columns-preview wasn't added when this was added?

@ambihelical I can't seem to get `--max-columns-preview` to work. Can you give an example?

**Comment by ambihelical** [comment]
I've been using --max-columns 500 without the preview, but I tried it again like this in a use-package block:
```
  :custom
  (counsel-search-engine 'google)
  (counsel-rg-base-command "rg --max-columns 80 --max-columns-preview --with-filename --no-heading --line-number --color never %s")
```
With this it shows any matches greater than 80 columns with `[ ... omitted end of long line ]` at the end of the string in ivy.

Maybe this is a feature that got added after --max-columns?  I'm using version 11.0.2.

**Comment by abo-abo** [comment]
Indeed, I don't have that feature in version 0.10.0.
