### ISSUE TITLE
Feature proposal (incl. example): implement gnome-tracker functionality/search

### ISSUE THREAD

**Issue by dalanicolai** [abo-abo/swiper#2484]
Hi,

In gnome nautilus, while visiting the home directory, one can just type the name of any file located in any subdirectory of the home directory and nautilus will find it almost instantly using gnome-tracker.
Therefore I do not first have to jump to the correct directory to find/open a file from there as I have to in counsel-find-file. In counsel, a similar behavior is found using e.g. `counsel-recentf`, but it only shows files contained in recentf. (I would be interested if you have better ways to find files, I am already aware of the fasd and recoll features but those are still not ideal). The following animation shows how the function that is given below adds similar behavior to Ivy 

![Screencast-from-03-14-2020-05_48_57-AM](https://user-images.githubusercontent.com/18429791/76675345-7801e780-65b8-11ea-8d75-16e638f72427.gif)

The animation shows how I directly find a file in some deep subdirectory without first navigating into that directory

Anyway, with the following function the behavior of nautilus can be implemented in counsel. Of course this function [can be tweaked in many ways](https://wiki.gnome.org/Projects/Tracker/Documentation/Examples/SPARQL/General) and, as I read somewhere you are on linux, I hoped maybe you can try it and you might have a suggestion how to best implement tracker into counsel.

Indeed there was a request for this feature already 4 years ago b.t.w., see issue #681 (see the last sentence of the last message in that issue)

If you have [gnome-tracker](https://wiki.gnome.org/Projects/Tracker) running on your machine you maybe would like to try the following function to find any file (well, at least the files tracked by gnome tracker) in your home directory.
(If you are on kde then a similar functionality probably is provided by the [`balooctl` command](https://community.kde.org/Baloo)

```
(defun counsel-tracker ()
  (interactive)
  (ivy-read "open: "
            (split-string
             (shell-command-to-string
              "tracker sparql -q \"SELECT ?url WHERE { ?s a nfo:FileDataObject ; nie:url ?url . FILTER (STRSTARTS (?url, 'file://$HOME/')) .}\"")
             "\n")
            :action (lambda (x)
                      (find-file
                       (s-replace-all '(("%20" . " "))
                                      (substring x 9))))))

```

I think it would be great if counsel could integrate more of gnome-tracker functionality. In my opinion gnome-tracker is a great idea. Of course recoll or docfetcher could also be used to quickly list all files in the home folder, but gnome-tracker is used already by default for this functionality by gnome.

**Comment by dalanicolai** [comment]
related issue #681

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by basil-conto** [comment]
> I would be interested if you have better ways to find files

There exist also `counsel-file-jump`, `counsel-dired-jump`, and `counsel-locate`, FWIW.

**Comment by dalanicolai** [comment]
@basil-conto Ah yes, great. Thanks... indeed I discovered them by now...
