### ISSUE TITLE
No way to cancel `ivy-read-action-by-key`

### ISSUE THREAD

**Issue by zhangpj** [abo-abo/swiper#2485]
Hi,

I am using the default `ivy-read-action-by-key` function for reading actions. I wonder if there is a way to cancel it? `C-g` prints a `C-g is not bound` message which is a bit annoying.

From the definition:

https://github.com/abo-abo/swiper/blob/5f1d9ce04599c52818244c2cb8cb066a601610b8/ivy.el#L959-L963

it seems that we can use an empty character to quit, but I have no idea what key that is.

Thank you!

**Comment by mohkale** [comment]
I mentioned this in a different [issue](https://github.com/abo-abo/swiper/issues/2397#issuecomment-574896379) a while back... but then forgot about it.

It's still an issue.
