### ISSUE TITLE
Opening a file from local disk while in tramp mode

### ISSUE THREAD

**Issue by bienchen** [abo-abo/swiper#2488]
Hello,

I'm totally new to ivy and could not find another place (e.g. mailing list) to ask a question.
So I'm in a buffer showing a file in tramp mode, if I want to open a file from local disk, after `C-x C-f` I have something like this in my minibuffer: `/ssh:foo:/a/b/c`. I can get rid of `/a/b/c` but not of `/ssh:/foo:` preventing me from opening a local buffer.

Any help?

Cheers,

B

**Comment by abo-abo** [comment]
You can press `/ C-j`, or `~ //`.

**Comment by bienchen** [comment]
Thanks, that works!
