### ISSUE TITLE
ivy-occur: next-error jumps to wrong location

### ISSUE THREAD

**Issue by martinxyz** [abo-abo/swiper#2492]
### Description

Using `next-error` to cycle through ~20 grep hits of an `*ivy-occur ...*` buffer works fine within that buffer. Outside of that buffer (while keeping `*ivy-occur ...*` visible in another window) it behaves erratically: (tested in spacemacs)

- The first time it always navigates to the correct match.
- The cursor in the `*ivy-occur ...*` window does *not* update to reflect the current match.
- It may work a few more times, but soon it will jump back to an earlier match instead of the next match, preventing you from cycling through all matches.

### Analysis

In `ivy-occur-next-error` (and in `ivy-occur-next-line`), the current match is tracked by updating the point of the `*ivy-occur ...*` buffer. However, the window's point overrides the buffer's point whenever the window is displayed, according to [this answer](https://emacs.stackexchange.com/a/21478/12292) on emacs.stackexchange. Not sure what exactly triggers the redisplay, but it seems considered normal that this happens often.

(Note: `grep-mode` does not have this problem, and in addition it displays a neat arrow to mark the location. Not sure how they solved it, but it looked quite involved at a first glance.)

### Proposed Fix

Update the point in all windows showing the  `*ivy-occur ...*` buffer. Doing this in `ivy-occur-next-error`, assuming that's the only place likely called from another window. Here is the change that works for me: https://github.com/martinxyz/swiper/commit/bb300e81c

I can make a PR if you prefer, but I'm not sure if it's the best place to fix it.

**Comment by abo-abo** [comment]
Please PR.
