### ISSUE TITLE
ivy-occur shows inconsistent results for counsel-find-file

### ISSUE THREAD

**Issue by hamhock** [abo-abo/swiper#2493]
`C-x C-f `  ^lspci  `C-c C-o`
successfuly identifies file
`ls -a | perl -ne '/(^lspci.*)/i && print "$1\n";' | xargs -d '\n' ls -d --group-directories-first -alh | sed -e "s/^/  /"`
  -rw-r--r-- 1 richard users 8.2K May 19  2019 lspci.txt

whereas
`C-x C-f `  txt$ `C-c C-o`
is unsuccessful
`ls -a | perl -ne '/(txt$.*)/i && print "$1\n";' | xargs -d '\n' ls -d --group-directories-first -alh | sed -e "s/^/  /"
`
ls: cannot access 'txt': No such file or directory

i've tried many iterations of the regexp to no avail.

thank you.

**Comment by abo-abo** [comment]
Works fine for me, since I have `ag` installed:

    ls -a | ag -i '^(?!.*\(?:^\(?:\.|__\)|elc|pyc$\))(?=.*txt$)' | xargs -d '\n' ls -d --group-directories-first -alh | sed -e "s/^/  /"

Your system does not have `ag` installed, so going down in `counsel-file-name-filter-alist` makes it use perl:

    ls -a | perl -ne '/(txt$.*)/i && print "$1\n";'              | xargs -d '\n' ls -d --group-directories-first -alh | sed -e "s/^/ /"

I tested that this command works:

    ls -a | perl -ne '/(.*txt$.*)/i && print "$1\n";'              | xargs -d '\n' ls -d --group-directories-first -alh | sed -e "s/^/ /"

So I will modify `counsel-file-name-filter-alist` accordingly. Please test.

**Comment by hamhock** [comment]
works - thank you!
