### ISSUE TITLE
rgrep 2nd completion shouldn't use ivy with choice of files

### ISSUE THREAD

**Issue by jamienicol** [abo-abo/swiper#250]
In rgrep, or vc-git-grep, and probably others, completion is a bit strange.

The first thing you enter is the text to search for. This doesn't use ivy, you just enter the text and it works fine.
The third thing you enter is the directory to search in, which uses ivy as expected.
But the second thing you enter is a pattern of files to search in. eg "\*" or "\*.cpp". With ivy-mode enabled it tries to use ivy to complete this as if it was a file you are entering. This feels very wrong. entering "/*" (ivy won't let you delete the first "/") works but looks a little bit weird.

**Comment by abo-abo** [comment]
> But the second thing you enter is a pattern of files to search in. eg "*" or "*.cpp".

This is the issue of `rgrep` using `(completing-read "Search for \"\" in files (default *.gz): " 'read-file-name-internal)`.  Nothing I can do here. But it should still work fine: just enter the pattern manually and press <kbd>C-M-j</kbd> (`ivy-immediate-done`).  You can also use the default pattern with <kbd>M-i C-M-j</kbd>.

**Comment by jamienicol** [comment]
That's a shame it looks weird but I suppose it working is more important. C-M-j was exactly what I was looking for, for this and other commands too. Thanks!

**Comment by abo-abo** [comment]
You're welcome.
