### ISSUE TITLE
File name completion issues when current directory is wider than window

### ISSUE THREAD

**Issue by jcs090218** [abo-abo/swiper#2501]
I have tested this with `-q` on `Windows 10`. I think this occurs when the path is longer than the Emacs' window and require to display it on the next line. But once I have type something, then everything goes back to normal like in the second image.

#### Something went wrong.
![qaq](https://user-images.githubusercontent.com/8685505/78248531-5f358380-751f-11ea-8a71-73154c94bec0.png)

#### Goes back to normal
![qaqq](https://user-images.githubusercontent.com/8685505/78248786-d79c4480-751f-11ea-8a75-ef73f12c83e5.png)

**Comment by TomCox01** [comment]
Hi, for problems concerning path too long issues, I 

suggest you to try the new long path tool. This can 

help you with all kinds of path too long cases,

**Comment by jcs090218** [comment]
I think is not about the path too long, is about the path goes above the `window-width`. Sorry for the confusion in the title. Once, I switch to a smaller font, the issue resolves. I think this is more of the handling multiple lines issue. Any idea? :confused:

**Comment by basil-conto** [comment]
I didn't notice any issues when using `counsel-find-file` to descend into a deep directory tree:

![output-2020-05-02-16:23:28](https://user-images.githubusercontent.com/9121222/80868290-8489ee80-8c91-11ea-9679-93f111f42bc7.gif)

When reporting an issue, please try to provide a step-by-step reproducible recipe, or at least as much information as you can: what you typed, what you saw after each step, etc. Ideally the recipe will not be affected by your own configuration and packages, i.e. please try to reproduce the issue starting from `make plain` (from within this repository) or `emacs -Q`.

**Comment by jcs090218** [comment]
Okay, I think this is default action for ivy. I thought the cursor should always behind the path.

There is also another issue when the path is too long. If you enter a directory that has `6` files it won't show all the files when you have `ivy-auto-shrink-minibuffer` on. It will be offset by `2` because of input path is showing on top.

> When reporting an issue, please try to provide a step-by-step reproducible recipe, or at least as much information as you can: what you typed, what you saw after each step, etc. Ideally the recipe will not be affected by your own configuration and packages, i.e. please try to reproduce the issue starting from make plain (from within this repository) or emacs -Q.

Thanks for the advice, I did it actually. Yet I will provide the steps next time!

**Comment by jcs090218** [comment]
To reproduce the not all files showing issue.

1. config `(setq ivy-height 15)` and `(setq ivy-auto-shrink-minibuffer '((t . t)))`.
2. eval it.
3. Goto the deep in directory that has files lower than `15`. (not sure, mine is `6` files)

Then you should that not all the files are showing as a candidates even though the height is lower than 15. I think is the miscalculation of the auto shrink!

**Comment by basil-conto** [comment]
Thanks for the information; I'll defer to @abo-abo's expertise.

**Comment by jcs090218** [comment]
Is this issue reproducible? Just want to know if there is any progress on this! Thanks!

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by jcs090218** [comment]
It works! Appreciated! :)

**Comment by jcs090218** [comment]
> ![qaq](https://user-images.githubusercontent.com/8685505/78248531-5f358380-751f-11ea-8a71-73154c94bec0.png)

Oh, another question here. Is there a way to make the read-only text to the first line, so it does not consume another newline? And the highlighting seems to be broken? Thanks!

**Comment by abo-abo** [comment]
> Oh, another question here. Is there a way to make the read-only text to the first line, so it does not consume another newline?

That's where the input cursor is. I don't want there to be a jump when new input appears.

> And the highlighting seems to be broken? Thanks!

Please clarify what this means.

**Comment by jcs090218** [comment]
> That's where the input cursor is. I don't want there to be a jump when new input appears.

Got you! Thanks! :)

> Please clarify what this means.

In the image, next line after `[3:12] Find file: ` (line 1). It should also highlight the path `c:/DataBase_.../.../`. I actually don't know why this isn't working on my PC yet I have not configure any faces to `ivy`.
