### ISSUE TITLE
counsel-fzf sometimes insert the key that triggered it

### ISSUE THREAD

**Issue by phaazon** [abo-abo/swiper#2506]
Hello,

I have no idea how to reproduce that as it’s a bit stochastic, but sometimes, `counsel-fzf` inserts in the search input the key I use to trigger it. I use `SPC-f` and sometimes I get this:
![img_040920_193541](https://user-images.githubusercontent.com/506592/78923973-57cf2680-7a99-11ea-9ae8-b7e39ee61461.png)

It’s not a biiiiiiig problem but it’s a bit annoying. Any idea what’s happening? I thought it was due to my key repeat, but it’s not that short to allow to type the character twice.

**Comment by abo-abo** [comment]
In my opinion, the bug is not in `counsel-fzf`. Could it be that you enter `SPC-f f` from time to time?

My key binding is <kbd>C-c n</kbd> and I've never had this problem.

**Comment by phaazon** [comment]
I have the same problem with `SPC SPC` :( How can I check that? I remember people talked about something to display the keypresses in a specific window. Maybe that would give me more hindsight.

I’ll try that and come back to you.

**Comment by basil-conto** [comment]
Do you use Evil/Spacemacs? Can you reproduce this with a minimal or no configuration, ideally from `emacs -Q`? There could be a bug in the packages you use or in your configuration.

**Comment by phaazon** [comment]
Vanilla emacs with evil-mode, yes. I’m not using `emacs` anymore though — I kept being upset at the slow and stuttering cursor moves. I haven’t erased my configuration though, it’s available [here](https://github.com/phaazon/config/tree/master/emacs).

**Comment by basil-conto** [comment]
> I kept being upset at the slow and stuttering cursor moves

FWIW, that's usually a bug in a particular package. The curse that comes with Emacs' power is a large number of low quality third-party packages, but the core packages that ship with Emacs itself generally achieve a high code qualiy average, to the point where I haven't noticed cursor hangs or stutters in years.

> I haven’t erased my configuration though, it’s available here.

Sorry, I don't think anyone's going to go through your configuration to see if they can reproduce the issue in the OP, so I'm closing this issue until further notice.
