### ISSUE TITLE
Unexpected regex matching

### ISSUE THREAD

**Issue by RenWenshan** [abo-abo/swiper#2507]
How do I compose a ivy regex to match "ac" or "ad" or "bc" or "bd" only?

`(ivy--regex-plus "[ab][cd]")` returns:
```
"\\([ab]\\).*?\\([cd]\\)"
```

which matches strings such as "aXXXc"

**Comment by CeleritasCelery** [comment]
For some reason I can't figure out, there is code specifically to split patterns on brackets with `ivy--match-regex-brackets` in `ivy--regex-plus`. I would be interested to understand why. 

However in the meantime you can use a better rebuilder like `ivy--regex-ignore-order` which will handle this correctly.

**Comment by abo-abo** [comment]
Thanks, please test.
