### ISSUE TITLE
Problem searching org-mode files

### ISSUE THREAD

**Issue by jagrg** [abo-abo/swiper#251]
The problem seems to be with org-mode properties drawer. Swiper opens a huge minibuffer window (not the default 10 height) and is very slow to start. Try this:

1. Create an org-mode file and add this test heading

```
** TODO test
   SCHEDULED: <2015-10-08 Thu .+3d/4d>
:PROPERTIES:
:STYLE: habit
:Effort:   0:25
:LAST_REPEAT: [2015-10-05 Mon 14:13]
:END:
   :LOGBOOK:  
   - State "DONE"       from "TODO"       [2015-10-05 Mon 14:13]
   - State "DONE"       from "TODO"       [2015-10-01 Thu 15:56]
   - State "DONE"       from "TODO"       [2015-09-28 Mon 14:31]
   - State "DONE"       from "TODO"       [2015-09-24 Thu 23:44]
   - State "DONE"       from "TODO"       [2015-09-21 Mon 12:29]
   - State "DONE"       from "TODO"       [2015-09-17 Thu 12:22]
   - State "DONE"       from "TODO"       [2015-09-13 Sun 12:24]
   - State "DONE"       from "TODO"       [2015-09-10 Thu 11:36]
   - State "DONE"       from "TODO"       [2015-09-07 Mon 22:09]
   - State "DONE"       from "TODO"       [2015-09-03 Thu 16:32]
   - State "DONE"       from "TODO"       [2015-08-31 Mon 22:19]
   - State "DONE"       from "TODO"       [2015-08-27 Thu 16:06]
   - State "DONE"       from "TODO"       [2015-08-24 Mon 07:27]
   - State "DONE"       from "TODO"       [2015-08-20 Thu 12:30]
   - State "DONE"       from "TODO"       [2015-08-17 Mon 17:57]
   - State "DONE"       from "TODO"       [2015-08-13 Thu 10:10]
   - State "DONE"       from "TODO"       [2015-08-10 Mon 17:49]
   - State "DONE"       from "TODO"       [2015-08-03 Mon 15:48]
   :END:      
```
2. Now type M-x swiper and see if the problem shows up.

swiper-20151004.957
Emacs 24.5.1 
Org mode 8.3.2

**Comment by abo-abo** [comment]
This is an issue with the recent `visual-line-mode` functionality. Disabling `visual-line-mode` should make `swiper` work fine again.

**Comment by jagrg** [comment]
I need `visual-line-mode` on. Is there a workaround solution? Maybe a hook that disables `visual-line-mode` when `swiper` is called and then enables it again once the search is complete.

**Comment by abo-abo** [comment]
I've currently disabled the visual line mode interaction in `org-mode` buffers. So your bug should be gone now.
The reason is that visual-line doesn't work nicely with hidden text like in org-mode.
Additionally, the visual line interaction will only work for small (<20K) buffers, since it's inefficient for larger buffers.

> Maybe a hook that disables visual-line-mode when swiper is called and then enables it again once the search is complete.

What I described above is essentially the same.
