### ISSUE TITLE
killing a modified buffer in ivy-switch-buffer-kill doesn't work

### ISSUE THREAD

**Issue by dylancant** [abo-abo/swiper#2513]
when I try to kill a modified buffer it simply says "command attempted to use minibuffer while in minibuffer."

in ido-mode (which also uses the minibuffer) it successfully prompts me whether I want to save the modified buffer.

**Comment by dylancant** [comment]
I should have mentioned, 

I use the keybinding C-k to run ivy-switch-buffer-kill
Also M-o k does work, it successfully prompts me if I want to save the buffer

**Comment by abo-abo** [comment]
I can't reproduce with `make plain` on Emacs 26.3.

Can you try:

```sh
git clone https://github.com/abo-abo/swiper/
cd swiper && make plain
```

Then, for instance, <kbd>C-x C-f</kbd> `ivy.el` <kbd>RET</kbd>, make a modification, <kbd>C-x b C-p C-k</kbd> results in a yes/no prompt.

**Comment by kurnevsky** [comment]
I don't have exactly this issue but related - when I kill current buffer with `C-k` and switch to another buffer it just writes `Selecting deleted buffer` and doesn't switch.

**Comment by abo-abo** [comment]
@kurnevsky I haven't encountered it in my use. Please open a new issue with a reproducible scenario.

**Comment by dylancant** [comment]
Thanks for the reply!

After I to evaluated this 
(setq enable-recursive-minibuffers t)
it works perfectly.

It seems like it was set to nil by default (on my system)
