### ISSUE TITLE
Enter a non-existing directory with ivy

### ISSUE THREAD

**Issue by vincentbernat** [abo-abo/swiper#2514]
Hey!

Suppose I have a path with `not-fuzzy/` as a directory. Now, I want to create a new file which will be located in `fuzzy/` neighbor directory which does not exist yet. I think, this is not possible with Ivy enabled. Without Ivy, I would just type `fuzzy/myfile.txt` and Emacs will create the directory when saving. With Ivy, if I type `fuzzy/`, it gets completed to `not-fuzzy/` when hitting `/`.

Even the ability to temporarily disable Ivy would be useful to handle this case, but it seems it's not available either.

Thanks.

**Comment by abo-abo** [comment]
Thanks for the question. Here's how it can be done: `fuzzy` <kbd>C-M-o d</kbd> `1.txt` <kbd>RET</kbd>.

This worked only for:

```elisp
(setq ivy-read-action-function 'ivy-read-action-by-key)
```

I've fixed it to work for `ivy-read-action-ivy` and `ivy-hydra-read-action` in the referenced commits. Please test.

**Comment by vincentbernat** [comment]
I was using `ivy-read-action-by-key`, so this works for me. Thanks!
