### ISSUE TITLE
Conflict with emacs-mini-modeline

### ISSUE THREAD

**Issue by haqle314** [abo-abo/swiper#2515]
When I have `mini-modeline-mode` enabled, the minibuffer doesn't expand
properly. More specifically, once the minibuffer window shrinks down to a single
line (no matching candidates), it won't expand again. I think the culprit is in
`ivy--resize-minibuffer-to-fit`. 

```elisp
(defun ivy--resize-minibuffer-to-fit ()
  ...
  (cond (;; replacing > with >= seems to fix it
         (> text-height body-height)
         ...))
  ...)
```

@kiennq I think this is related to kiennq/emacs-mini-modeline#12.

**Comment by kiennq** [comment]
I think kiennq/emacs-mini-modeline#12 is fixed. Do you have repro steps for this?

**Comment by haqle314** [comment]
I'm able to reproduce this with `emacs -Q` following these steps:
```
M-: (setq resize-mini-windows t)
M-x package-initialize
M-x counsel-mode
M-x mini-modeline-mode
```
These are the version of the packages that I'm using:
```
GNU Emacs 27.0.90 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.13, cairo version 1.16.0) of 2020-04-03
mini-modeline-20200408.729
counsel-20200422.1208
```

**Comment by kiennq** [comment]
Can you post which counsel command you invoke and type? I've tried with `swiper` but can never get the minibuffer shrink down while swiper is active.

**Comment by haqle314** [comment]
After those steps, I just press M-x (or C-x C-f) and type random characters
to make sure that there's no match.

**Comment by kiennq** [comment]
I think this https://github.com/kiennq/emacs-mini-modeline/commit/4f1dce78916cccd2e7066345ae2be3394a675c46 can fix the issue. Can you test with that?

**Comment by kiennq** [comment]
@haqle314 Did you issue resolved?

**Comment by haqle314** [comment]
@kiennq I apologize for the late response. With the commit you linked, I guess you could say it's resolved. Because with `resize-mini-windows` set to `grow-only`. the minibuffer window doesn't shrink when I have only a few candidates. Though it's not that important and I'm not sure how much trouble it would be to make sure that the minibuffer window grow & shrink properly.

**Comment by abo-abo** [comment]
Thanks. Since this seems to be fixed, I'm closing the issue.
