### ISSUE TITLE
Feature Request: ivy-auto-shrink-minibuffer-alist

### ISSUE THREAD

**Issue by TatriX** [abo-abo/swiper#2516]
It may be nice to be able to set `ivy-auto-shrink-minibuffer` per `:caller`.
I would like to have static height for `counsel-find-file` but auto-shrink behavior for `swiper-isearch`.
Thank you!

**Comment by abo-abo** [comment]
Thanks. Please test.

**Comment by TatriX** [comment]
Setting `ivy-auto-shrink-minibuffer` to an alist works, but `ivy-auto-shrink-minibuffer-alist` is ignored.

**Comment by basil-conto** [comment]
> Setting `ivy-auto-shrink-minibuffer` to an alist works

Don't do that. `ivy-auto-shrink-minibuffer` is a boolean and now obsolete. Use `ivy-auto-shrink-minibuffer-alist` directly. See also #2540.

**Comment by TatriX** [comment]
Well, as I said it doesn't work. It seems that `ivy-auto-shrink-minibuffer-alist` is ignored, as it's only used in `defcustom` and `make-obsolete-variable`, though I'm unfamiliar with the codebase so I can't really tell.

**Comment by basil-conto** [comment]
Ugh, it was a typo in my last commit for #2540. Should be fixed in commit 6eda8faa7370be141dda61f23b8de83b2915be07. Sorry about that and thanks for catching it.
