### ISSUE TITLE
ivy-switch-buffer can't switch buffer after killing an active one

### ISSUE THREAD

**Issue by kurnevsky** [abo-abo/swiper#2518]
I mentioned the issue here https://github.com/abo-abo/swiper/issues/2513#issuecomment-617866294

It can be reproduced with `make plain`:
- execute several times `(generate-new-buffer "untitled")`
- switch to one of these `untitled` buffers
- execute `ivy-switch-buffer`
- kill current active buffer at the top using `C-k`
- select another `untitled` buffer to switch

It will write `if: Selecting deleted buffer` and won't switch

**Comment by abo-abo** [comment]
Thanks, please test.
