### ISSUE TITLE
Saving a file from gnus: the destination folder is not shown

### ISSUE THREAD

**Issue by brabalan** [abo-abo/swiper#252]
Here is a screenshot as I was saving a file from gnus, navigating to `~/Documents/Inbox`:
![screen shot 2015-10-06 at 14 38 18](https://cloud.githubusercontent.com/assets/1021637/10308750/2da32e16-6c38-11e5-9e02-51788400a10d.png)

As I see no part of the path, it's very difficult to see if I did not make a mistake when navigating to that folder.

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by brabalan** [comment]
I just updated and I find things are worse. Upon saving a file with a long name, I get this
![screen shot 2015-10-06 at 16 21 13](https://cloud.githubusercontent.com/assets/1021637/10311322/7dba7126-6c46-11e5-9627-39e8d0721e50.png)
If I start typing Documents I get this
![screen shot 2015-10-06 at 16 21 48](https://cloud.githubusercontent.com/assets/1021637/10311334/85cd9cbc-6c46-11e5-8dc9-4fb46a53c54c.png)
but when I `<tab>` to enter the directory I get this
![screen shot 2015-10-06 at 16 22 23](https://cloud.githubusercontent.com/assets/1021637/10311338/8b14e536-6c46-11e5-8600-1121f18e056d.png)
There is no information as to where I currently am.

**Comment by abo-abo** [comment]
Try restarting Emacs. I've removed all code that inserts "...", so these should not be present.

**Comment by brabalan** [comment]
It works great, thanks. Even with long completions, it goes to the next line, which is very nice.

And thanks for all the great work you're doing on swiper, counsel, and ivy. I file many bugs, but I'm very grateful for them!
