### ISSUE TITLE
Select same item with first item in history from ivy-read actually deletes the history

### ISSUE THREAD

**Issue by kiennq** [abo-abo/swiper#2524]
Eval this and select `c` from candidates by pressing <kbd>Enter</kbd>
``` elisp
(setq hist '("c" "b" "a"))
(ivy-read "Test: " '("c" "d" "e") :history 'hist)
```
Expected:
- Value of `hist` should be `("c" "b" "a")`

Actual
- Value of `hist` became `("b" "a")`

This happens since `ivy-text` **is not containing the value of selection**, and the history added by `read-from-minibuffer` has already poped away.

**Comment by abo-abo** [comment]
Thanks.
