### ISSUE TITLE
Warning: the function ‘libxml-parse-xml-region’ is not known to be defined.

### ISSUE THREAD

**Issue by tam17aki** [abo-abo/swiper#2527]
my byte-compiler says:

counsel.el:6718:1:Warning: the function ‘libxml-parse-xml-region’ is not
    known to be defined.

my environment is "GNU Emacs 26.3 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.22.30) of 2019-09-24".

I am not sure how to fix the code to surpress the warning.

**Comment by basil-conto** [comment]
Thanks for reporting that.  Please check whether PR #2528 fixes the issue.

**Comment by tam17aki** [comment]
Now It works well, the warning disappeared.

Thank you very much,
Akira
