### ISSUE TITLE
Swiper misplaces point and previous history contains whole line

### ISSUE THREAD

**Issue by basil-conto** [abo-abo/swiper#2533]
1. `make plain`
2. <kbd>C-s</kbd>`this`<kbd>RET</kbd>
   Expected: point left after "this" on line 1
   Actual: point left at end of line 1
3. <kbd>C-s</kbd><kbd>M-p</kbd>
   Expected: `this` inserted as current search text
   Actual: entire line 1 inserted as current search text

This regression was caused by commit 829cf8a55007df6318b1d34d150fc9aac6cc2f8a in PR #2526 fixing issue #2524.

Cc: @kiennq

**Comment by kiennq** [comment]
I'm not really sure how to fix this one. As I notice, `C-s` invoke `swiper` which is line based selection, thus the whole line is selected and insert into history.
It seems to be fine with `swiper-isearch` though.

**Comment by abo-abo** [comment]
Thanks. `swiper` should now work. The test for #2524 still passes. Sorry for the regression.

**Comment by kiennq** [comment]
Thanks for your quick response

**Comment by basil-conto** [comment]
Thanks for working on this @abo-abo, but <kbd>M-p</kbd> during `swiper` still inserts the entire line previously selected, as per the recipe I provided. Unless this is the new intended behaviour, there's still a regression.

**Comment by abo-abo** [comment]
@basil-conto Thanks, should be fixed now.

**Comment by kiennq** [comment]
@abo-abo I think the newer fix will broke the case like this
``` elisp
(progn
  (setq h '("cdef" "b" "a"))
  (ivy-with '(ivy-read "test: " '("cdef" "g") :history 'h) "cd RET")
  h)
```
`h` will be evaluated to `("cd" "b" "a")` which delete a history item even though we choose `"cdef"` from candidates

**Comment by abo-abo** [comment]
@kiennq

I think this is fine, since this behavior is more useful:

```elisp
(progn
  (setq h '("cdef" "b" "a"))
  (ivy-with '(ivy-read "test: " '("cdef1" "cdef2" "g") :history 'h) "cd RET")
  (ivy-with '(ivy-read "test: " '("cdef1" "cdef2" "g") :history 'h) "M-p RET"))
;; => "cdef1"

(progn
  (setq h '("cdef" "b" "a"))
  (ivy-with '(ivy-read "test: " '("cdef1" "cdef2" "g") :history 'h) "cd RET")
  (ivy-with '(ivy-read "test: " '("cdef1" "cdef2" "g") :history 'h) "M-p C-n RET"))
;; => "cdef2"
```

**Comment by kiennq** [comment]
@abo-abo Your example is fine.
But the problem is that **if the first item in the collection is the same with the first item in the history**, an history item will be lost/replaced with `ivy-text`.

It's destructive behavior as the long typed query for a search (sometimes valuable) can be easily lost and being replaced with no meaningful version.

Can't we do this in a way that at least preserve the history?

**Comment by abo-abo** [comment]
@kiennq Thanks, I understand it now. I've fixed it and added a new test. Please test.

**Comment by kiennq** [comment]
Thanks, it works great now
