### ISSUE TITLE
[Feature request] Resume to another ivy session instead of the last one.

### ISSUE THREAD

**Issue by kiennq** [abo-abo/swiper#2536]
`Helm` has a nice feature of being able to chose to resume from multiple session https://github.com/emacs-helm/helm/wiki/Resume.
Which is very helpful, especially when we have to deal with multi session.
For example: find files, grep in file and switch back to find files session.

Do `ivy` already supports the same thing?

I think this can be easily implemented by define a new parameter (`session`) for `ivy-read` and save the new `ivy-last` to an alist of `((session . ivy-last))`.
Then `C-u M-x ivy-resume` can be as easy as `let` bind `ivy-last` to the selected session `ivy-last`.

Just wonder if we have a same thing already.

**Comment by basil-conto** [comment]
I wonder whether this would complicate turning `ivy-last` or similar into a stack.

**Comment by kiennq** [comment]
I think this is provided now. Close.
