### ISSUE TITLE
Using ivy-read like counsel-find-file

### ISSUE THREAD

**Issue by haji-ali** [abo-abo/swiper#2544]
In `counsel-find-file` which uses `ivy-read`, the current path is printed and pressing `backspace` on the the directory path navigates to the parent directory (also typing `/` and `~` navigates to root and home directories). 

I want to implement a similar list but where the completion list is not the current files in the directory but something different (I want to use `fzf` or `ripgrep` in the current directory).

What is the best way to go about this? I am happy to dig through the code of ivy or counsel if someone can give me some pointers.

**Comment by abo-abo** [comment]
You can look into `ivy-set-prompt` to modify the prompt, and add a `:keymap` argument to `ivy-read` to modify/extend the keyboard bindings.

Small example:

```elisp
(defun test ()
  (interactive)
  (ivy-read "Test: " '("1" "2" "3")
            :caller 'test))

(ivy-set-prompt 'test #'test-prompt)

(defun test-prompt ()
  (concat default-directory ": "))
```

**Comment by haji-ali** [comment]
Thanks! I didn't know about `ivy-set-prompt`.
I looked through the source code of `ivy-backward-delete-char` and saw that it uses `ivy--directory` for navigating the path so I was hoping to use the functionality that `ivy` has already implemented for path navigation.

I take it that you don't recommend that route?

**Comment by abo-abo** [comment]
You should not rely on `ivy--directory`, it's an internal implementation detail.

Here's an example implementation of something like `counsel-find-file` <kbd>C-j</kbd>:

```elisp
(defvar my-directory "~")

(defun test-collection (str)
  (directory-files my-directory nil str))

(defvar test-map
  (let ((map (make-sparse-keymap)))
    (define-key map (kbd "C-j") 'test-directory-enter)
    map))

(defun test ()
  (interactive)
  (setq my-directory "~")
  (ivy-read "Test: " #'test-collection
            :caller 'test
            :keymap test-map
            :dynamic-collection t))

(ivy-set-prompt 'test #'test-prompt)

(defun test-prompt ()
  (concat my-directory ": "))

(defun test-directory-enter ()
  (interactive)
  (setq my-directory (expand-file-name (ivy-state-current ivy-last) my-directory))
  (ivy-set-text "")
  (delete-minibuffer-contents))
```

**Comment by haji-ali** [comment]
Thank you very much!
I did not realize how easy it is to get what I want with just `ivy-read`. It has a really well-thought out interface.
