### ISSUE TITLE
Running counsel-git-grep on files matching a pattern only

### ISSUE THREAD

**Issue by leoalekseyev** [abo-abo/swiper#2546]
I would like to use counsel to run a search like `git grep $PATTERN -- "*.go"`. Is there no option for this or am I just not finding one?

**Comment by basil-conto** [comment]
You can modify the `git-grep` command on the fly by calling `counsel-git-grep-switch-cmd`, which is bound to <kbd>C-c</kbd><kbd>C-m</kbd> by default.

![output-2020-05-05-23:35:26](https://user-images.githubusercontent.com/9121222/81122616-25460b80-8f29-11ea-96f4-ef2884bb4901.gif)

**Comment by leoalekseyev** [comment]
@basil-conto this is brilliant! I can modify the default command by examining `counsel-git-grep-cmd-default` and create my own wrapper, e.g. 
```
(defun lva/counsel-git-grep-tabs ()
  "Looks for tabs in Go and Python files"
  (interactive)
  (counsel-git-grep "^\\t" nil "git --no-pager grep -n --no-color -I -P -e \"%s\" -- \"*.go\" \"*.py\""))
```
