### ISSUE TITLE
Enable counsel-rg's to configure arguments vs query order

### ISSUE THREAD

**Issue by xenodium** [abo-abo/swiper#2547]
Consider enabling counsel-rg to configure its argument order.

**Query first (current behavior)** `defun -- --file-search-regex 'ivy.org'` For users keen to first input a search string and only append command args when needed.

**Arguments first (potentially enabled using config variable)** `--file-search-regex 'ivi.org' -- defun` Supported up to 328da1f95ce5f3386b63b28ca41a48bd88cf4144. For users keen to set default switches untouched for typical searches. Switches are only tweaked when needed.

For example:

`(push '(counsel-ag . "--file-search-regex '' -- ") ivy-initial-inputs-alist)`

The cursor would always show up after "--file-search-regex '' -- " in the minibuffer:

`ag: --file-search-regex '' -- ▮`

![tu](https://user-images.githubusercontent.com/8107219/81221175-62b6a180-8fda-11ea-8f3d-2aaf18a67089.gif)

Although in **query first** order it is still possible to use default switches, an additional key-binding is necessary C-a (move to beginning of line) to input a query in every search.

![td](https://user-images.githubusercontent.com/8107219/81221940-71518880-8fdb-11ea-86f6-64ad673afac2.gif)

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by xenodium** [comment]
Thanks Oleh. Works well.
