### ISSUE TITLE
M-x cd no longer works with Ivy

### ISSUE THREAD

**Issue by basil-conto** [abo-abo/swiper#2549]
The following regression was introduced by commit 57c7d7c425956038e22f94441017fa3191829691 as part of PR #2375:

1. `make plain`
2. <kbd>M-x</kbd>`cd`<kbd>RET</kbd>
3. `~/`<kbd>C-M-j</kbd>
4. <kbd>M-:</kbd>`default-directory`<kbd>RET</kbd>

This returns `"/path/to/swiper/sources"` rather than `"~/"` as it should.

Cc: @clemera

**Comment by clemera** [comment]
Oh yes, let binding the `default-directory` around the action calls means no command can set it intentionally, too.

**Comment by abo-abo** [comment]
Thanks, please test.
