### ISSUE TITLE
Customize Path width?

### ISSUE THREAD

**Issue by Macavirus** [abo-abo/swiper#2551]
Example, using ivy-switch-buffer, (or many other ivy commands) there is no way to tell which buffer is which when they share the first part of the path name. However, there is wasted space on the right side of the screen.

Using Ivy Version: 0.13.0

![2020-05-08_13-04](https://user-images.githubusercontent.com/18612573/81375960-c4872080-912c-11ea-9a7a-6fa337bcd70c.png)

Is there any way to:
- Force ivy to use full path width?
- Set minumum percentages for each element of the popup table?
- Force ivy to use full width of screen for all elements of the popup table?

Tried the following, neither setting helps:
```
(setq ivy-truncate-lines nil)
(setq swiper-window-width #'frame-width)
```

**Comment by basil-conto** [comment]
> Using Ivy Version: 0.13.0

That does not look like the output of `ivy-switch-buffer`. Are you using some other package?

Here's what `ivy-switch-buffer` looks like in latest vanilla Ivy:

![2020-05-08-125403_1600x900_scrot](https://user-images.githubusercontent.com/9121222/81403363-1fb81380-912b-11ea-9356-07e457a37264.png)

**Comment by articuluxe** [comment]
It looks like ivy-rich-buffer.

**Comment by basil-conto** [comment]
So is this an issue with `ivy` or with `ivy-rich`? They are two different packages.

**Comment by Macavirus** [comment]
I realized I am using ivy-rich to trigger this, so that may be overriding the width somehow.
