### ISSUE TITLE
Modify ivy-switch-buffer to show additional information

### ISSUE THREAD

**Issue by frostidaho** [abo-abo/swiper#256]
![modified ivy-switch-buffer](https://cloud.githubusercontent.com/assets/8061555/10379981/52117dfe-6ddf-11e5-8943-5ffc75c48a6b.png)

I've written some [code](https://gist.github.com/frostidaho/bc3a7b1be32f916dc65d) to show additional information about the buffers listed in ivy-switch-buffer, and to align this information in columns. Right now it shows the major-mode and the file path (if it exists); however, it's pretty easy to extend to other buffer metrics and spruce it up in general.

Are you interested in integrating something like this into ivy-switch-buffer? If so, I'd be happy to make it user customizable.

**Comment by abo-abo** [comment]
Sure, it seems cool to give users this customization.

Do you have an Emacs copyright assignment? Since Ivy is in GNU ELPA, you need the assignment to contribute more than 15 lines.  It's not hard to get, and then you can contribute to any Emacs project (core, ELPA packages, Org-mode).

**Comment by frostidaho** [comment]
I don't have copyright assignment right now, but I'll look into getting it. I've worked on it some today and customization can be done as shown in the picture below. The picture shows how to add a readout for the number of lines in a buffer. I also updated the [code](https://gist.github.com/frostidaho/bc3a7b1be32f916dc65d), although I haven't written any docstrings yet.

![Customizing find buffer](https://cloud.githubusercontent.com/assets/8061555/10410053/7df9316c-6f03-11e5-9fc3-57617c42056b.png)


Do you have any suggestions/questions/comments?

**Comment by abo-abo** [comment]
> Do you have any suggestions/questions/comments?

I think it looks really cool. While I prefer to see less info rather than more info, I'm sure many users will use and appreciate this customization.

So I'd like to merge the code as soon as you have the CA, and then let the users give feedback on the UX side of things.

As for the code, one comment I have is that alists are preferred to hash tables, since they're easier to view, and a lot of Emacs customization is using alists.

**Comment by PythonNut** [comment]
This looks pretty cool, but maybe it could become `counsel-find-file`? `ivy` functions seem relatively barebones, and the more helm-like functionality is saved for `counsel`.

**Comment by frostidaho** [comment]
> prefer to see less info rather than more info

We could have the default be how it is now
![Simple Default](https://cloud.githubusercontent.com/assets/8061555/10413668/a40834de-6f80-11e5-9ddc-174012b74bb4.png)

> So I'd like to merge the code as soon as you have the CA, and then let the users give feedback on the UX side of things.

I contacted assign@gnu.org, so hopefully I can get that taken care of relatively soon.

> As for the code, one comment I have is that alists are preferred to hash tables, since they're easier to view, and a lot of Emacs customization is using alists.

Sure I'll look into that.

> maybe it could become counsel-find-file? ivy functions seem relatively barebones, and the more helm-like functionality is saved for counsel.

As far as the user experience goes if we use `(setq ivy-switch-buffer-show-info '("%s" "buffer-name"))`
by default, the interface will be the same as it is today.

This change also doesn't add any additional actions to ivy-switch-buffer. It just gives the user the option to display additional information. I guess I added these changes to ivy-switch-buffer instead of naming it something else, as it doesn't actually *do* anything different from the current ivy-switch-buffer.

If you're more talking about the code itself as opposed to its use, I can see what you mean. I'm sure there's some refactoring that can be done to simplify / streamline the code. I'd personally vote against putting it in counsel, as there would be a fair bit of duplicate code in ivy.el and counsel.el which would perform essentially the same function.

**Comment by frostidaho** [comment]
I sent an email like a month ago about giving the FSF copyright assignment, but I haven't heard back. I'll follow up on that.

A few weeks ago it was rewritten, in order to separate some of the more general-purpose formatting functions (the ivy--format- functions), and its now uploaded to the gist. I've been using this updated version since then and haven't run into any issues.

https://gist.github.com/frostidaho/bc3a7b1be32f916dc65d

**Comment by abo-abo** [comment]
> I sent an email like a month ago about giving the FSF copyright assignment, but I haven't heard back. I'll follow up on that.

Thanks. It's a good idea to follow up. AFAIK, there's only one clerk checking that email, for all GNU projects. He might miss some stuff, so I suggest to contact him more, at least until he sends you a PDF to sign.

**Comment by AlejandroCatalina** [comment]
Is there any update on this? It looks really nice!

**Comment by sooheon** [comment]
Looks great. As a small UI critique, I think the explicit `|` separators are not needed given the different faces and the alignment. This custom ui in spacemacs for example looks good:
<img width="677" alt="screen shot 2016-02-27 at 6 11 46 pm" src="https://cloud.githubusercontent.com/assets/302945/13372167/ae689af2-dd7d-11e5-9669-a27b869014d7.png">

**Comment by zeltak** [comment]
Hi! has this been merged yet to swiper? looks really cool.

**Comment by frostidaho** [comment]
No it hasn't. I haven't had time to figure out the FSF copyright assignment. (Although I'm open to it being incorporated without this assignment, but I think @abo-abo wants all contributors to have it.)

In any event I made a modification yesterday, so that it works with the new way ivy-call handles alists.
See [this gist](https://gist.github.com/frostidaho/bc3a7b1be32f916dc65d) for the updated version.

**Comment by sooheon** [comment]
@frostidaho I'm trying out the gist, by default the first column with the buffer name is 80 chars wide, so I don't see anything new if using a small screen. Your screen caps show more info in a narrower space. What should I customise for this?

**Comment by frostidaho** [comment]
@sooheon are you using the most recent version of the gist?
Below I've posted a screenshot of how the most recent version looks on my machine. The lines of asterisks (*) in the screenshot are 80 characters wide. Can you post a screenshot so I can see what you mean?

![screenshot-20160701-023341](https://cloud.githubusercontent.com/assets/8061555/16513666/8057e6f4-3f34-11e6-9a95-f8444c6b64ea.png)

**Comment by sooheon** [comment]
Yep, using the latest gist. It looks like this:

<img width="688" alt="screen shot 2016-07-01 at 4 07 03 pm" src="https://cloud.githubusercontent.com/assets/302945/16514290/dea89516-3fa5-11e6-925c-af09423f96be.png">

<img width="1440" alt="screen shot 2016-07-01 at 4 07 36 pm" src="https://cloud.githubusercontent.com/assets/302945/16514301/f01afb5e-3fa5-11e6-8cbb-0e8fd14d1754.png">

**Comment by sooheon** [comment]
Ok, I've scrolled through and found that I had a buffer with one hugely long title that was making that happen. We could use a maximum width for the first column, I guess, either in columns or %.

**Comment by frostidaho** [comment]
@sooheon Thanks for telling me about this. I've updated the [gist](https://gist.github.com/frostidaho/bc3a7b1be32f916dc65d/revisions) to add an option to truncate the buffer-name display length. By default it's set to 50 characters, but you can set it with
`(setq ivy-buffer-max-buffer-display-length 50)`

Below is a picture of how it looks on my machine. It shows a buffer that's named eeee... (80 e's), but
in the minibuffer this name in truncated to 50 characters.
![screenshot-20160701-130934](https://cloud.githubusercontent.com/assets/8061555/16528818/262f8476-3f8d-11e6-95c4-37a24090e331.png)

**Comment by zeltak** [comment]
very nice. hope this gets incorporated soon!

thx!

Z

**Comment by romildo** [comment]
> By default it's set to 50 characters, but you can set it with
`(setq ivy-buffer-max-buffer-display-length 50)`

Maybe a good idea is to set dynamically using a percentage of the window width.

**Comment by frostidaho** [comment]
@romildo Could you expand on what you'd like to see?

I think a simple percentage of window width wouldn't work well for small windows. e.g., `(/ (frame-width) 3)`.
But you could also do some percentage of a frame width within some shortest and longest lengths.

**Comment by ninrod** [comment]
hi, any update on this? thanks.

**Comment by frostidaho** [comment]
No progress getting it merged. You can try it out by downloading the [ivy_buffer_extend.el](https://gist.github.com/frostidaho/bc3a7b1be32f916dc65d) to your emacs module search path, and loading it `(require 'ivy_buffer_extend)`

**Comment by Yevgnen** [comment]
@frostidaho That's really awesome!

**Comment by ninrod** [comment]
@frostidaho this did not work for me: here's the code I'm using:

```elisp
  (use-package ivy
    :ensure t
    :config
      (setq ivy-use-virtual-buffers t)
      (setq ivy-count-format "(%d/%d) ")
      (ivy-mode 1)

      (use-package counsel :ensure t)
      (use-package ivy_buffer_extend :load-path "~/.emacs.d/lisp/ivy_buffer_extend.el"))
```

**Comment by Yevgnen** [comment]
Another quick and dirty [way](https://gist.github.com/Yevgnen/9067fcc025caa084d2fa7ae1d65315af) .

**Comment by ninrod** [comment]
I see what you did there.

**Comment by abo-abo** [comment]
@frostidaho If you're still having trouble getting a CA, maybe you could put the code into its own repository and release it on MELPA?

**Comment by abo-abo** [comment]
I just randomly stumbled upon `ivy-rich`. I guess I missed it when it was released. It works well, and is already on MELPA. So I'm closing this issue.
@Yevgnen good job!

**Comment by casouri** [comment]
For anyone who cares, I made a customizable `ivy-rich` and it's on its way to melpa.

![](https://github.com/casouri/ivy-filthy-rich/raw/master/function.png)

https://github.com/casouri/ivy-filthy-rich

**Comment by dieggsy** [comment]
@casouri why not just PR ivy-rich with more features?

**Comment by casouri** [comment]
@dieggsy I didn’t think too much into that because the two approach are pretty different in the core logic/implementation
