### ISSUE TITLE
Prevent buffer scrolling on when opening ivy

### ISSUE THREAD

**Issue by AnthonyDiGirolamo** [abo-abo/swiper#2560]
Apologies if this has been asked before, I'm having a hard time searching for a workaround. This doesn't seem like an ivy issue and probably applies to anything that changes the minibuffer height. 

Is there a way to prevent emacs from scrolling the current buffer when ivy is opened? If the cursor is at the top of the buffer then no scrolling occurs (and the buffer doesn't visually shift on the screen). If the cursor is close enough to the bottom when ivy is opened then emacs seems to shove the whole buffer up so the cursor stays in view. Here is an example:

![output-2020-05-12-10:44:34](https://user-images.githubusercontent.com/37681/81728103-c60f5c00-943e-11ea-9027-90342276ea88.gif)

With the cursor on `:custom` or above no scrolling/shifting happens. But if I move the cursor below and open ivy all the text shifts upwards depending on how close to the bottom of the window I am.

If possible I would like the text to not shift but don't know how to implement this. Is there an ivy or emacs setting/hook I can use? Maybe just move the cursor to the top of the window before opening ivy and restore the position on close? 

Here is an example with multiple window splits open:

![output-2020-05-12-11:00:56](https://user-images.githubusercontent.com/37681/81728889-fc99a680-943f-11ea-953b-ab26e54a022e.gif)

In this case the height of the bottom window split remains fixed and the top window is resized to make room for the minibuffer. If resizing the top window would overlap the cursor the window contents are again shifted to keep the cursor visible. In this case it would be ideal if the positions of the window splits stay fixed and the bottom window is shrunk to make room for the minibuffer (assuming it's tall enough). Ideally the topmost visible line of each window does not move.

This is reproduceable in `emacs -Q` with only ivy installed. But like I mentioned I don't believe this is ivy specific. If I can find a nice solution I'll author a PR. Thanks for taking a look! :smile:

**Comment by abo-abo** [comment]
Would be nice if someone figured out the Emacs window handling code when a minibuffer is being opened.

In the meantime, we have [ivy-display-function](https://github.com/abo-abo/swiper/wiki/ivy-display-function).
You can set it to `posframe`, or use the `lv` example on the wiki.

**Comment by AnthonyDiGirolamo** [comment]
Thanks! I tried out ivy-posframe and was able to get it working the way I wanted. Mainly having it popup where the minibuffer would normally appear and overlapping any windows. [Here's the change for that](https://github.com/AnthonyDiGirolamo/dot-all/commit/9e718709b595ce0117825ee0e16df6e5fc8e276c) if anyone is interested. It's great for gui emacs but I am often in the terminal so may dig into the emacs source if I have time. Thanks for the suggestion!
