### ISSUE TITLE
Helm-swoop

### ISSUE THREAD

**Issue by AtomicNess123** [abo-abo/swiper#2561]
What is the difference with helm-swoop? Thanks!

**Comment by basil-conto** [comment]
One of the first questions ever asked on this issue tracker. :) See issue #3.

**Comment by Gahamelas** [comment]
Thanks. I want to try it out. However, I am getting this error:

`eval-buffer: Cannot open load file: No such file or directory, pcre2el`

My init.el is as follows:
```
(add-to-list 'load-path "~/.emacs.d/other/swoop")
(require 'swoop)
```
Anything else I must add?
Thanks!

**Comment by abo-abo** [comment]
You can use <kbd>M-x</kbd> `package-install` `swiper`.

**Comment by basil-conto** [comment]
> My init.el is as follows:

The package name is `swiper`, not `swoop`. As @abo-abo suggests you need to install it first via `package-install` before you can use it.

Closing this as a local configuration issue for now.
