### ISSUE TITLE
filesystem path completion seems to be broken

### ISSUE THREAD

**Issue by skat-kurt** [abo-abo/swiper#2562]
When in a specific working directory in shell mode, eg. `~/aaa/bbb/ccc/ddd` and typing (at the prompt) `cd ../../` and then TAB, no completion options are given for directories and files under `bbb` (such as `ccc`). Only `./` and `../` are given and `^` is added in front.

**Comment by ak-coram** [comment]
I'm having the same issue when using inline completion (`completion-at-point`) with various modes (Cider for example). Reverting to 84efa3a seems to fix the issue.

**Comment by skat-kurt** [comment]
Same problem here in cider.

**Comment by basil-conto** [comment]
Bisected to commit edccbd70dde7f41590c3ef8f452467c197cee97c addressing feature request #2391, which seems to have also messed with `evil-mode` somehow.

Steps to reproduce:
1. `make plain`
2. <kbd>M-x</kbd>`ielm`<kbd>RET</kbd>
3. `"../`<kbd>TAB</kbd>

Expected: file name completion in parent directory.

![2020-05-14-123215_1600x900_scrot](https://user-images.githubusercontent.com/9121222/81929552-1f15f600-95df-11ea-9d5b-af14171131d7.png)

Observed: file name completion in current directory.

![2020-05-14-123150_1600x900_scrot](https://user-images.githubusercontent.com/9121222/81929584-2c32e500-95df-11ea-86bb-e661adbbfaea.png)

**Comment by abo-abo** [comment]
Thanks. Please test.

**Comment by kiennq** [comment]
It fixes my issue now
