### ISSUE TITLE
ivy-previous/next-history-element behavior

### ISSUE THREAD

**Issue by Nathoufresh** [abo-abo/swiper#2565]
To open \~/.emacs.d/init.el I do counsel-find-file then type ".emac TAB" then "init TAB" and I'm in init.el.
Now if I counsel-find-file again the minibuffer displays: "\~/.emacs.d/" with candidates, if I ivy-previous-history-element it displays :"\~/.emacs.d/init.el" then a second time "\~/.emacs.d/init". Shouldn't it only display file names instead of the string entered?

If I was previously working on a file \~/Documents/cool_project.c and I'm in .emacs.d then counsel-find-file and then call ivy-previous-history-element many times it will display "\~/.emacs.d/cool_project.c" which does not exist.

Is this an expected behavior? Is there a way to save only existing files in counsel-find-files history?
Not sure if I explain well.

**Comment by abo-abo** [comment]
This is not the expected behavior. With <kbd>M-p</kbd>, you should see `~/.emacs.d/` as a read only part, and `init.el` as the editable part.

Please try to reproduce it with `make plain`. I tested it and it works as expected.

**Comment by Nathoufresh** [comment]
Reproduced with make plain.

![swiper-issue2565](https://user-images.githubusercontent.com/39437515/82146605-bc756200-984b-11ea-84a5-ad19f3095848.gif)

I'm using emacs27-git from AUR
Version         : 27.0.90.140235

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by Nathoufresh** [comment]
Works perfectly! Thanks for the support and the great work.
