### ISSUE TITLE
[help?] replace match with empty string

### ISSUE THREAD

**Issue by Inc0ns1st3nt** [abo-abo/swiper#2566]
I remember used to be able replace matches with empty string, effectively deleting them.
Is there any configurations that I am missing?

Thanks.
swiper version: 0.13.0
emacs version: 26.3

**Comment by abo-abo** [comment]
I just tested that it still works. Please try to reproduce with `make plain`.

**Comment by Inc0ns1st3nt** [comment]
hmm, i am actually using [redguardtoo/emacs.d](https://github.com/redguardtoo/emacs.d)'s configuration, could there be some configuration switches? 
Anyhow, I shall redirect this question to that place instead ....

**Comment by Inc0ns1st3nt** [comment]
Hi, I would like to get some of your help again.
I figured, the behavior is a result of set default hint placeholder for `swiper-query-replace`:
![2020-05-18-161111_969x257_scrot](https://user-images.githubusercontent.com/33980911/82230955-57da0600-9924-11ea-9e3d-7b8f5aa16b15.png)
I could not quite find the docs on this configuration myself, could you please lead me into the right direction?
PS, the above set hint will be evaluated to the searched text, effectively disables replacement with empty string without some cumbersome maneuvers.

**Comment by abo-abo** [comment]
@Inc0ns1st3nt I recommend using <kbd>C-M-j</kbd> to return an empty string.

**Comment by Inc0ns1st3nt** [comment]
Thanks! this works around the hinting issue.
`C-M-j` maps to `ivy-immediate-done` while swiper is active.

**Comment by isolet** [comment]
May I ask what does the line `\,(concat \&)` mean?

**Comment by basil-conto** [comment]
@isolet It's a regexp replacement; see [`(info "(emacs) Regexp Replace")`](https://www.gnu.org/software/emacs/manual/html_node/emacs/Regexp-Replace.html) and [`(info "(emacs) Query Replace")`](https://www.gnu.org/software/emacs/manual/html_node/emacs/Query-Replace.html).

`\&` refers to the entire match being replaced, and `\,` evaluates the following Lisp expression and interpolates the result into the replacement.
