### ISSUE TITLE
Action on marked candidates fails with alist collection

### ISSUE THREAD

**Issue by franburstall** [abo-abo/swiper#2568]
I evaluate

    (ivy-read "Enter key: "
	           '(("Key 1" . "Data 1") ("Key 2" . "Data 2"))
	          :action (lambda (x) (message "Got %s" (cdr  x))))

and mark all candidates with`C-o mm`.

What I expect: see two messages in the ***Messages*** buffer.

What I get:

    lispy--eval-elisp: Wrong type argument: listp, #("Key 1" 0 5 (idx 0))

Commentary: the action is applied to the list of keys in `ivy-match-candidates` not a list of corresponding cons cells.

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by franburstall** [comment]
Thanks.  That fixes the issue unless we have a `multi-action` defined:

    (let (res)
      (ivy-read "Enter key: "
	        '(("Key 1" . "Data 1") ("Key 2" . "Data 2"))
	        :action (lambda (x) (push x res))
	        :multi-action (lambda (xs) (setq res xs)))
      res)

I would expect this to return a list of candidates (cons cells) but I get a list of (propertized) keys:

    (#("Key 1" 0 5 (idx 0)) #("Key 2" 0 5 (idx 1)))

**Comment by sewkokot** [comment]
I don't know if this is related to this bug, but even after updating ivy-20200518.946 (from melpa), I still have a problem. For example when selecting latex environments with ivy, I get the following error:

```
Debugger entered--Lisp error: (wrong-type-argument plistp ivy-completing-read)
  plist-put(ivy-completing-read :ivy-data (:all-candidates (#("code" 0 4 (idx 0)) #("list" 0 4 (idx 1)) #("math" 0 4 (idx 2)) #("align" 0 5 (idx 3)) #("array" 0 5 (idx 4)) #("cases" 0 5 (idx 5)) #("quote" 0 5 (idx 6)) #("slide" 0 5 (idx 7)) #("split" 0 5 (idx 8)) #("table" 0 5 (idx 9)) #("verse" 0 5 (idx 10)) #("align*" 0 6 (idx 11)) #("cases*" 0 6 (idx 12)) #("center" 0 6 (idx 13)) #("dcases" 0 6 (idx 14)) #("figure" 0 6 (idx 15)) #("gather" 0 6 (idx 16)) #("matrix" 0 6 (idx 17)) #("psclip" 0 6 (idx 18)) #("rcases" 0 6 (idx 19)) #("table*" 0 6 (idx 20)) #("Bmatrix" 0 7 (idx 22)) #("Vmatrix" 0 7 (idx 23)) #("alignat" 0 7 (idx 24)) #("aligned" 0 7 (idx 25)) #("bmatrix" 0 7 (idx 26)) #("dcases*" 0 7 (idx 27)) #("drcases" 0 7 (idx 28)) #("figure*" 0 7 (idx 29)) #("flalign" 0 7 (idx 30)) #("gather*" 0 7 (idx 31)) #("itemize" 0 7 (idx 32)) #("matrix*" 0 7 (idx 33)) #("picture" 0 7 (idx 34)) #("pmatrix" 0 7 (idx 35)) #("rcases*" 0 7 (idx 36)) #("tabbing" 0 7 (idx 37)) #("tabular" 0 7 (idx 38)) #("vardesc" 0 7 (idx 39)) #("vmatrix" 0 7 (idx 40))  #("Bmatrix*" 0 8 (idx 43)) #("Vmatrix*" 0 8 (idx 44)) #("alignat*" 0 8 (idx 45)) #("bmatrix*" 0 8 (idx 46)) #("document" 0 8 (idx 47)) #("drcases*" 0 8 (idx 48)) #("eqnarray" 0 8 (idx 49)) ...) :text ""))
  #f(compiled-function () #<bytecode -0x121840d1a68a5e03>)()
```

**Comment by abo-abo** [comment]
> For example when selecting latex environments with ivy

Please list the steps you take, and check if it's reproducible with `emacs -Q`. `LaTeX-environment` works fine for me.

**Comment by sewkokot** [comment]
It seems this is related to ivy-prescient. If I comment ivy-prescient then I get no error. There is also an issue reported here:
https://github.com/raxod502/prescient.el/issues/60#issuecomment-630242774

**Comment by franburstall** [comment]
Did the `multi-action` part of the issue get lost in the mix?  Should I raise a separate issue?  Sorry to hassle: not sure of the etiquette!

**Comment by basil-conto** [comment]
> Did the `multi-action` part of the issue get lost in the mix?

Looks like it, yes. Sorry about that.

> Should I raise a separate issue?

I think this ticket is still fresh and relevant to the valid issue you reported, so I'll reopen this one.

> Sorry to hassle: not sure of the etiquette!

There is none. ;)

**Comment by abo-abo** [comment]
Thanks, pleaset test.

**Comment by franburstall** [comment]
Yup, works for me!  Many thanks.
