### ISSUE TITLE
File path not shown in counsel-find-file

### ISSUE THREAD

**Issue by PythonNut** [abo-abo/swiper#257]
`counsel-find-file` and the regular `find-file` do not show the current path in the minibuffer. This is confusing as the path is really handy for:

1. Locating where I am currently
2. Quickly navigating up the FS tree

**Comment by abo-abo** [comment]
Do you mean that you want this:

```elisp
(defun counsel-find-file ()
  "Forward to `find-file'."
  (interactive)
  (ivy-read (format "Find file (%S): " default-directory) 'read-file-name-internal
            :matcher #'counsel--find-file-matcher
            :action
            (lambda (x)
              (with-ivy-window
                (find-file (expand-file-name x ivy--directory))))
            :preselect (when counsel-find-file-at-point
                         (require 'ffap)
                         (ffap-guesser))
            :require-match 'confirm-after-completion
            :history 'file-name-history
            :keymap counsel-find-file-map))
```

Seems like excessive duplication of info to me. Also, the standard `find-file` doesn't show the current path.

**Comment by thwg** [comment]
I believe they're referring to the full path being displayed with find-file as they are locating a file.   Not the CWD where the command was initiated.  Emacs' default find-file has this behavior, as do the Helm and ido versions.

In this case you are able to view and manually edit the full path name in the minibuffer.

If this is correct, I would also be interested in this feature.

**Comment by abo-abo** [comment]
> Emacs' default find-file has this behavior, as do the Helm and ido versions.

Ivy behaves like Ido in this case: the base path is read-only (but still visible), while you select the files and directories in the base path.

I see what you mean with `helm-find-files`, it allows to manually edit the full path. I don't think this behavior is very useful, while it allows for more ways to bring the path into an invalid state.

> In this case you are able to view and manually edit the full path name in the minibuffer.
> 
> If this is correct, I would also be interested in this feature.

I'd like to keep it the way it is. I think the current behavior is a nice abstraction of `cd PATH && ls PATH`, where `PATH` is guaranteed to be a directory. The full path approach would remove this guarantee.

However, here's an implementation for a one-way fallback to basic `find-file`, just like in `ido-find-file`:

```elisp
(define-key counsel-find-file-map (kbd "C-x C-f")
  (lambda ()
    (interactive)
    (ivy-set-action
     (lambda (_x)
       (let ((completing-read-function 'completing-read-default))
         (call-interactively 'find-file))))
    (ivy-done)))
```

If you're happy with it, I can add the above code.

**Comment by thwg** [comment]
> Ivy behaves like Ido in this case: the base path is read-only (but still visible), while you select the files and directories in the base path.

Ah. I didn't realize that.  That works well enough for me.

I double checked my settings and I have `ivy-count-format' set to disabled which apparently also disables this feature.  I thought it only removed the counter.  Is this a bug? Perhaps @PythonNut has this set as well.

**Comment by abo-abo** [comment]
> I double checked my settings and I have `ivy-count-format' set to disabled which apparently also disables this feature.

Aha! That's a nasty bug. I'll try to fix this soon.

**Comment by abo-abo** [comment]
Make that `ivy-count-format` is a string (`""` now serves as nil before).
@PythonNut let me know if this fixes your issue.

**Comment by PythonNut** [comment]
@thwg Indeed, I did have `(setq ivy-count-format nil)`. Thanks for fixing this, despite my pathetic problem-reporting skills.
