### ISSUE TITLE
^ inserted on aborting completion in region

### ISSUE THREAD

**Issue by basil-conto** [abo-abo/swiper#2572]
Commit d52ee0a3f0024bf7065f77497285b1e69dbbdb9f reverted the fix in #2563 for the following issue:

1. `make plain`
2. `(mess`<kbd>C-M-i</kbd>
3. <kbd>C-g</kbd>

Expected contents preceding point: `(mess`
Actual contents preceding point: `(^mess`

**Comment by xavierr** [comment]
I have a similar issue
1. `(def C-M-i`

Expected: a list of completion (which includes `defun`)
Get : `(^def`    and no completion is proposed

**Comment by basil-conto** [comment]
@xavierr I can't reproduce your issue:

1. `make plain`
2. `(def` <kbd>C-M-i</kbd>

This gives me the following:

![2020-05-25-155944_1600x900_scrot](https://user-images.githubusercontent.com/9121222/82824219-d7c21c00-9ea0-11ea-9e27-9c37092244bd.png)

Can you reproduce your issue starting from `emacs -Q` or `make plain`?

**Comment by abo-abo** [comment]
Thanks.

**Comment by xavierr** [comment]
The problem occurs if I use the following setting for the `ivy-re-builders-alist`
```
(setq ivy-re-builders-alist
      '((ivy-completion-in-region . regexp-quote)
        (t . ivy--regex-plus)))
```

Then, when typing 

`(def C-M-i`

Expected: a list of completion (which includes defun)
Get : (^def and no completion is proposed

I do not remember why I changed this setting in the first place, so I will switched back to default which behaves as expected.

**Comment by basil-conto** [comment]
@xavierr `regexp-quote` is documented as a valid value for `ivy-re-builders-alist`, so if the leading `^` anchor breaks that use case then that's a regression; please open a new issue for that.
