### ISSUE TITLE
Why does 'make plain' load elpa.el?

### ISSUE THREAD

**Issue by basil-conto** [abo-abo/swiper#2573]
Loading `elpa.el` overwrites the default value of `package-user-dir`, which means that `make plain` cannot find packages such as `hydra` installed in the default location. Why is this done? Is it possible to avoid this?

**Comment by abo-abo** [comment]
There's missing code that installs dependencies [here](https://github.com/abo-abo/lispy/blob/master/targets/install-deps.el). I'd like to integrate it into this repo at some point.

The intention of `elpa.el` is to pin the dependencies to their latest version, and not to disturb the user's real ELPA directory.

**Comment by basil-conto** [comment]
Wouldn't it be easier to leave `package-user-dir` alone and leave its setting up to the user/developer?

**Comment by abo-abo** [comment]
I think it's better to have our own `package-user-dir`:

- `make deps` doesn't touch the user's `package-user-dir`
- the user can `rm -rf ~/.emacs.d/elpa` safely to re-install the deps
- Travis CI can do the deps in the same way

I close the issue since I think the advantages of this approach outweigh the disadvantages. But suggestions for improvement are very welcome.

**Comment by basil-conto** [comment]
> I think it's better to have our own `package-user-dir`

If that's what you want to do, then I suggest keeping it under the source repository rather than under the user's home directory. I know `make` commands can be run with a custom environment, e.g. `HOME=foo`, but by default a package should be as unintrusive as possible, even for its developers.

**Comment by abo-abo** [comment]
I wanted to keep the dependencies separate so they don't get synced by Dropbox/Nextcloud.

Also that's the approach of Maven (`~/.m2`) and Pip (`~/.local/lib/python3.6/site-packages`).

The advantage is the development dependencies can be re-used between packages, so I don't have e.g. many `avy` folders on my computer.
