### ISSUE TITLE
counsel-yank-pop does not respect ivy-height-alist set via Customization

### ISSUE THREAD

**Issue by yuezhu** [abo-abo/swiper#2578]
I set `ivy-height-alist` via Customization to allow `counsel-yank-pop` to occupy at most half of the frame like below:
```elisp
 '(ivy-height-alist
   '((counsel-yank-pop lambda
                       (_caller)
                       (/
                        (frame-height)
                        2))
     (counsel-git-log . 4)
     (counsel-evil-registers . 5)
     (counsel-ag lambda
                 (_caller)
                 (/
                  (frame-height)
                  2))))
```
However,  no matter what value I set for `ivy-height-alist` via customization, it will be reverted to `5`, which is the value specified by [ivy-configure](https://github.com/abo-abo/swiper/blob/0b5c08a6496a141f456132ba4a908d4a53ece7e7/counsel.el#L4471-L4473):
```elisp
((counsel-yank-pop . 5)
 (counsel-git-log . 4)
 (counsel-evil-registers . 5)
 (counsel-ag lambda
             (_caller)
             (/
              (frame-height)
              2)))
```
It looks like as long as `height` is specified in `ivy-configure`, the customized value would be overridden by it. For those `ivy-configure`'s without `height`, eg., [`counsel-ag`](https://github.com/abo-abo/swiper/blob/0b5c08a6496a141f456132ba4a908d4a53ece7e7/counsel.el#L3001-L3006), the customized value can be preserved. So, should the `height` be removed from `ivy-configure` in favor of Customization?

**Comment by basil-conto** [comment]
Is this a duplicate of issue #2442?

**Comment by yuezhu** [comment]
Ah, yes. https://github.com/abo-abo/swiper/issues/2442 is a generic description for this issue. So, I will have to not use customization but modify `ivy-height-alist` after `ivy` is loaded.

Close as duplicate.
