### ISSUE TITLE
[Question] Find file other window.

### ISSUE THREAD

**Issue by jcs090218** [abo-abo/swiper#2580]
This question may be stupid, but how do you find file on another window? I want to bind it to another key! Might expect something like `counsel-find-file-other-window`, etc.

Thanks! 😕

**Comment by abo-abo** [comment]
You can read in the code of `counsel.el` that we do this:

```elisp
(ivy-set-actions
 'counsel-find-file
 '(("j" find-file-other-window "other window")
   ("f" find-file-other-frame "other frame")
   ("b" counsel-find-file-cd-bookmark-action "cd bookmark")
   ("x" counsel-find-file-extern "open externally")
   ("r" counsel-find-file-as-root "open as root")
   ("R" find-file-read-only "read only")
   ("l" find-file-literally "open literally")
   ("k" counsel-find-file-delete "delete")
   ("c" counsel-find-file-copy "copy file")
   ("m" counsel-find-file-move "move or rename")
   ("d" counsel-find-file-mkdir-action "mkdir")))
```

So you can press <kbd>M-o j</kbd> to call `find-file-other-window`.

**Comment by jcs090218** [comment]
Is there a way so I can call it as a command and not having to press the `M-o j` after `counsel-find-file`?  Thanks! 😄

**Comment by abo-abo** [comment]
You could call `find-file-other-window` with `ivy-mode` enabled. Anything wrong with that?

**Comment by jcs090218** [comment]
Oh, okay. I see. I guess I was confused what you meant. Thanks! 😄  Close this issue/question now!

**Comment by jcs090218** [comment]
I think I have another that when you use `find-file-other-window` the preselect won't work as expected. Do you want me to open on another issue? 😕

**Comment by abo-abo** [comment]
Yes, you can open a new issue for that.
