### ISSUE TITLE
Is there an option to choose a buffer via a number in the buffer list when invoking ivy-switch-buffer?

### ISSUE THREAD

**Issue by jivanmukti** [abo-abo/swiper#2582]
Currently to switch to a different buffer, I press C-x b, which calls ivy-switch-buffer. It shows a list of open buffers along with the quantity of buffers. This works fine when the buffers have different files open, but if there are similarly titled files such as 

#hello.txt#
hello.txt
##hello.txt##

Then I have to scroll to the correct one. Is there a way I can select a buffer by pressing a number similar to how zsh can show a list of directories and go to it with a number?

1 #hello.txt#
2 hello.txt
3 ##hello.txt##

So I would press 3 and it would open ##hello.txt##.

Thank you!

**Comment by basil-conto** [comment]
The command `ivy-avy`, which can be found in the file `ivy-avy.el` and is bound to <kbd>C-'</kbd> by default, leverages the [`avy`](https://github.com/abo-abo/avy) package to allow random access of candidates:

![2020-05-27-214311_2650x1680_scrot](https://user-images.githubusercontent.com/9121222/83070323-3800bb80-a063-11ea-93a7-ce2d85a3aaf7.png)

**Comment by basil-conto** [comment]
Technically every key you type issues another command. ;)

Calling `ivy-avy` involves only one additional keystroke.

The only other solutions I know of are:

(a) to pass a numeric prefix argument to <kbd>C-n</kbd>/<kbd>C-p</kbd> (`ivy-next-line`/`ivy-previous-line`) before selecting the resulting candidate; or

(b) to select a candidate relative to the current candidate by passing a numeric prefix argument to <kbd>C-M-n</kbd>/<kbd>C-M-p</kbd> (`ivy-next-line-and-call`/`ivy-previous-line-and-call`).

**Comment by jasonmj** [comment]
This will let you use M-1, M-2, M-3, etc for the accessing the candidates with a single command: 

`(defun ivy-call-number (n)
  (interactive
   (list (let* ((type (event-basic-type last-command-event))
                (char (if (characterp type)
                          ;; Number on the main row.
                          type
                        ;; Keypad number, if bound directly.
                        (car (last (string-to-list (symbol-name type))))))
                (n (- char ?0)))
           (if (zerop n) 10 n))))
  (ivy-set-index (1- n))
  (ivy--exhibit)
  (ivy-done))

(dotimes (i 10)
      (define-key ivy-minibuffer-map (read-kbd-macro (format "M-%d" i)) 'ivy-call-number))`

One thing I haven't figured out is how to display numbers in the list of candidates. If anyone has suggestions for that, I welcome your input. Thanks!

**Comment by basil-conto** [comment]
> One thing I haven't figured out is how to display numbers in the list of candidates.

Have you tried customising `ivy-format-functions-alist`?
