### ISSUE TITLE
swiper is very slow to load on small Python file with visual "visual-line-mode = true"

### ISSUE THREAD

**Issue by mrbig033** [abo-abo/swiper#2588]
swiper was taking more than 1 second to load on a 100 lines Python file. Disabling `visual-line-mode` worked, but I don't think swiper should have issues with such a small file anyway.

I'm using Elpy on Doom Emacs on macOS.

Emacs version is `GNU Emacs 27.0.91 (build 1, x86_64-apple-darwin18.7.0, NS appkit-1671.60 Version 10.14.6 (Build 18G103)) of 2020-05-14`.

**Comment by abo-abo** [comment]
Can you reproduce with `make plain` from this repo?

Does this affect `swiper-isearch`?

Can you provide a sample Python file?

**Comment by mrbig033** [comment]
> Can you reproduce with make plain from this repo?

I don't know what that means.

> Does this affect swiper-isearch?

No.

> Can you provide a sample Python file?

[Yes](https://gist.github.com/mrbig033/78aa8e23437eb904b564946a3ff6b18a).

**Comment by abo-abo** [comment]
Thanks. Here are the results of the profiler:

```
swiper--candidates                   1           0.318950527   0.318950527
line-move                            120         0.2974743639  0.0024789530
swiper--line                         118         0.0252123910  0.0002136643
swiper--update-input-ivy             1           0.002149154   0.002149154
swiper--maybe-recenter               1           0.000976939   0.000976939
swiper-match-usable-p                118         0.0002103689  1.782...e-06
swiper--add-overlays                 1           0.000183263   0.000183263
swiper--add-line-overlay             1           0.000151695   0.000151695
swiper-font-lock-ensure              1           0.000129346   0.000129346
swiper--re-builder                   3           2.235e-05     7.450...e-06
swiper--cleanup                      2           1.6483e-05    8.2415e-06
swiper-font-lock-ensure-p            1           1.6482e-05    1.6482e-05
swiper--normalize-regex              3           6.984e-06     2.328e-06
swiper--recenter-p                   3           4.749e-06     1.583e-06
swiper--init                         1           2.514e-06     2.514e-06
swiper--make-overlay                 1           2.235e-06     2.235e-06
swiper--line-number                  1           1.676e-06     1.676e-06
swiper--positive-regexps             1           1.396e-06     1.396e-06
swiper                               1           0.0           0.0
```

As you can see, most of the 0.31 second start-up time was spent on 120 calls to `line-move`, which took 0.29 seconds. `line-move` becomes very slow when `visual-line-mode` is on.

I suggest either switching to `swiper-isearch` or using this customization:

```elisp
(setq swiper-use-visual-line-p (lambda (n-lines) nil))
```

**Comment by mrbig033** [comment]
I see. `(setq swiper-use-visual-line-p (lambda (n-lines) nil))` seems to be working fine. Does it have any disavantages? If not, why not make it default?

**Comment by abo-abo** [comment]
The disadvantage is that the visual lines are not split into candidates, and candidates are thus real lines. If the buffer was one huge line, there would be only one swiper candidate.

**Comment by basil-conto** [comment]
> `(setq swiper-use-visual-line-p (lambda (n-lines) nil))`

AKA `(setq swiper-use-visual-line-p #'ignore)`.

**Comment by mrbig033** [comment]
I see. That looks better. Thanks. I'll close this issue since my request was resolved, but I'd like to suggest adding this fix to the README/documentation, or maybe automate this change for certain kinds of file. I suspect this option was the reason for performance issues I had before, in different environments and situations. Especially because this situation is probably rare:

>  If the buffer was one huge line, there would be only one swiper candidate.

@abo-abo and @basil-conto: thanks your for answering and for the great package!
