### ISSUE TITLE
Feature request: ability to toggle case fold in swiper

### ISSUE THREAD

**Issue by oantolin** [abo-abo/swiper#259]
As far as I can tell, whether or not to toggle case fold in swiper is *not* configurable: if your query is all lowercase you *always* get case folding; if it is not all lowercase, you *never* get case folding. Very rarely I want to do a case sensitive search for a lowercase query with swiper, is there any way of getting that now? If not, how about adding that feature?

**Comment by abo-abo** [comment]
Thanks, you can now have case-fold off for all lower case input with <kbd>C-o C</kbd>.
