### ISSUE TITLE
counsel-rg grab visual highlight

### ISSUE THREAD

**Issue by cmorgan** [abo-abo/swiper#2592]
I'm using https://github.com/bling/evil-visualstar to "shift + 8" to search within a document.
It would be awesome if pressing "/" which is bound to counsel-rg grabbed the highlighted term and searched using ripgrep in the project. 
Could someone provide a pointer on how to go about this?

**Comment by abo-abo** [comment]
I suggest moving this issue to [evil-visualstar](https://github.com/bling/evil-visualstar/issues). Since it already calls `counsel-rg`, it only remains to call it with the `initial-input` argument.
