### ISSUE TITLE
counsel complete entry vs accept directory

### ISSUE THREAD

**Issue by haji-ali** [abo-abo/swiper#2594]
In `counsel-find-file`, I use `M-i` to auto-complete an entry (like I would do in a terminal). I then press `RET` to accept it. I prefer this double step approach because I tend to accidentally open files otherwise.
This is OK, but it also means that when I navigate a path I have to auto-complete a directory name and then press return on every directory. So I was wondering if there's a way to have directories accepted in counsel, while filenames inserted in the mini-buffer. 

So in other words, a single key would call `ivy-alt-done` on directories but `ivy-insert-current` on files.

I know I can just call `ivy-alt-done` on all entries but then I often accidentally open files without meaning to, so I prefer to have the separate behaviours for files and directories. The rationale is that directory acceptance is easy to undo if it was a mistake (I just press backspace), but file acceptance is much more disruptive since it opens a file and closes counsel.

**Comment by abo-abo** [comment]
You can configure it like this:

```elisp
(advice-add
 'ivy-insert-current :after
 (defun my-ivy-insert-current-patch ()
   (when (and ivy--directory
              (directory-name-p (ivy-state-current ivy-last)))
     (ivy-alt-done))))
```

**Comment by abo-abo** [comment]
Please test if it works fine. I don't think it makes sense to add a custom setting for this, but if more people need it, we can add it.

**Comment by basil-conto** [comment]
> You can configure it like this:

AKA:

```el
(defun my-ivy-insert-current-patch ()
  (when (and ivy--directory
             (directory-name-p (ivy-state-current ivy-last)))
    (ivy-alt-done)))

(advice-add 'ivy-insert-current :after #'my-ivy-insert-current-patch)
```

or, since Emacs 25:

```el
(define-advice ivy-insert-current (:after () my-insert-current-patch)
  (when (and ivy--directory
             (directory-name-p (ivy-state-current ivy-last)))
    (ivy-alt-done)))
```

The point being that the return value of `defun` is explicitly documented as being undefined.

**Comment by haji-ali** [comment]
@abo-abo, Thanks! This works nicely.

However, at the moment, when I (honestly, accidentally) press `Alt-i` on the entry `.` the current directory is opened (with `dired` in my setup). Is there a way to just simply ignore that action?

I tried, 
```elisp
(define-advice ivy-go-or-insert (:after () my-insert-current-patch)
  (when (and ivy--directory
             (let ((path (ivy-state-current ivy-last)))
               (and (not (equal path "./"))
                    (directory-name-p path)))
             (ivy-alt-done))))
```
which almost works, however it does mean that `.` is added to mini-buffer. Is there a way to prevent this?

I am not sure if other people would want this option (though it seems natural to me). Personally, rather than advice `ivy-insert-current` I will probably implement this as a separate function and assign it to a different key (probably `tab`).

**Comment by haji-ali** [comment]
Ah, looking at the source of `ivy-insert-current` I implemented an alternative like this

```elisp
(defun ivy-go-or-insert ()
  (interactive)
  (delete-minibuffer-contents)
  (let* ((end (and ivy--directory
                   (ivy--dirname-p (ivy-state-current ivy-last))
                   -1))
         (path (ivy-state-current ivy-last)))

    (when (not (equal path "./"))
      (insert (substring-no-properties path 0 end))
      (when (and ivy--directory
                 (directory-name-p path))
        (ivy-alt-done)))))
```

which I think does everything I want.
