### ISSUE TITLE
counsel-find-file with ivy-partial does not descend into directory if its name is a suffix of other directory

### ISSUE THREAD

**Issue by Rogach** [abo-abo/swiper#2596]
The directory structure is as follows:
```
test
├── [4.0K]  a
│   └── [ 361]  file_in_a.txt
└── [4.0K]  ba
    └── [ 218]  file_in_ba.txt

2 directories, 2 files
```

I start clean emacs with ivy-mode and counsel-mode with `make plain`, and execute `(define-key ivy-minibuffer-map (kbd "TAB") 'ivy-partial)`.

Now when I try to navigate `test/a/`. I type `C-x C-f ~ test C-j a TAB` and see the following:

![test_a](https://user-images.githubusercontent.com/898831/83788987-bf22e480-a69e-11ea-8357-5afad3c6ffcd.png)

Notice how it doesn't descend into directory.

If I try to navigate to `test/ba` everything works as expected. I type `C-x C-f ~ test C-j ba TAB` and see the files in target directory:

![test_b](https://user-images.githubusercontent.com/898831/83789175-08733400-a69f-11ea-997e-0ebae4ee82b4.png)

If it may help - in my real config I had a custom sort function `ivy-sort-matches-functions-alist`, I added some debugging to it and it reported that in such cases "a" became a symbol instead of string.

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by Rogach** [comment]
It works without issues now. Thank you!
