### ISSUE TITLE
Selected non-default action fails on marked candidates if default multi-action present

### ISSUE THREAD

**Issue by franburstall** [abo-abo/swiper#2598]
I run this:
```elisp
(ivy-add-actions 'test-ivy
		 '(("a" (lambda (x) (message "Action-a: %s" x)) "Action-a")))

(ivy-read "Choose: " '("x" "y")
	    :action (lambda (x) (message "Default: %s" x))
	    :multi-action (lambda (xs) (message "Default: %S" xs))
	    :caller 'test-ivy)
```
I mark both candidates with M-a, call `ivy-dispatching-done` with M-o and select `a`.

What I expect: two lines in the Messages buffer:
```
Action-a: x
Action-a: y
```
What I get: one line in the Messages buffer:
```
Default: ("x" "y")
```
Commentary: when the default multi-action is not present, I get the behaviour I expect: the selected action is called on each marked candidate in turn.  However, in the present case, the selected action is ignored in favour of the default multi-action.

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by franburstall** [comment]
Unfortunately, this fixes the issue but causes another.  Try this:
```elisp
(let ((res))
  (ivy-add-actions 'ivy-demo
		   '(("a" (lambda (x) (push (format "Action-a: %s" x) res)) "Action-a"
		     (lambda (xs) (push (format "Action-a-multi: %S" xs) res)) )))
  (ivy-read "Choose: " '("x" "y")
	    :action (lambda (x) (push (format "Default action: %s" x) res))
	    :multi-action (lambda (xs) (push (format "Default action: %S" xs) res))
	    :caller 'ivy-demo)
  res)
```
Here I have used the (not very documented) possibility to declare a multi-action version of action-a.

I do `M-a M-o a`.  

What I expect: `res` should be of the form `("Action-a-multi: ...)`.

What I get: `res` is `("Action-a: y" "Action-a: x")`.

Commentary: I think the correct sequence of events when dealing with marked candidates should be: see if there is a multi-action associated with the chosen action, default or otherwise, and if there is, apply that.  Otherwise apply the chosen action to each marked candidate in turn.

**Comment by abo-abo** [comment]
Thanks, please test again.

**Comment by franburstall** [comment]
Perfect.  Many thanks.
