### ISSUE TITLE
counsel-yank-pop: confusing format

### ISSUE THREAD

**Issue by sorawee** [abo-abo/swiper#2603]
`counsel-yank-pop`'s items could be multiple lines. As there's no separator between items, I'm unable to tell what each item is exactly unless I move to that item to highlight it. Note that a newline as a separator doesn't quite work because items could also have newlines in them.

Also, the highlight does not extend to the whole line, which looks weird, but this is simply an aesthetic issue.

<img width="69" alt="Screen Shot 2020-06-10 at 02 44 16" src="https://user-images.githubusercontent.com/9099577/84253325-a95d5700-aac4-11ea-8cf7-5e8ffcea6082.png">

Currently, I overrode `counsel--yank-pop-format-function` as follows.

```
(defun add-prompt (str)
    (concat
     ">"
     (substring
      (mapconcat
       (lambda (s) (concat "  " s))
       (split-string str "\n")
       "\n")
      1)
     "\n"))
(defun counsel--yank-pop-format-function (cand-pairs)
    "Transform CAND-PAIRS into a string for `counsel-yank-pop'."
    (ivy--format-function-generic
     (lambda (str)
       (ivy--add-face
        (add-prompt (counsel--yank-pop-truncate str)) 'ivy-current-match))
     (lambda (str) (add-prompt (counsel--yank-pop-truncate str)))
     cand-pairs
     ""))
```

which produces:

<img width="69" alt="Screen Shot 2020-06-10 at 02 50 13" src="https://user-images.githubusercontent.com/9099577/84253781-32748e00-aac5-11ea-9010-6be0630e1e95.png">

Is this an improvement that `counsel-yank-pop` should provide by default? If so, I am happy to submit a PR.

**Comment by basil-conto** [comment]
> counsel-yank-pop`'s items could be multiple lines. As there's no separator between items, I'm unable to tell what each item is exactly unless I move to that item to highlight it. Note that a newline as a separator doesn't quite work because items could also have newlines in them.

Have you tried customising `counsel-yank-pop-truncate-radius` or `counsel-yank-pop-separator`? One of the suggested values for the latter is `"\n----\n"`.

> Currently, I overrode `counsel--yank-pop-format-function` as follows.

Note that instead of overriding you could also:

```el
(with-eval-after-load 'counsel
  (ivy-configure #'counsel-yank-pop :format-fn #'my-format-fn))
```

> Is this an improvement that `counsel-yank-pop` should provide by default? If so, I am happy to submit a PR.

Note that formatting multiline candidates is a general issue with Ivy, not just limited to `counsel-yank-pop`.
