### ISSUE TITLE
Why does buffer completion include current buffer?

### ISSUE THREAD

**Issue by mcfarljm** [abo-abo/swiper#2607]
Unlike emacs default completion, buffer completion with ivy includes the current buffer.  This is one way in which I find ivy more difficult to use than emacs default.  For example, open buffers `ivy.el` and `counsel.el` and start with `counsel.el`.  Suppose I want to switch to `ivy.el`.  I run `C-x b` and type "el" to narrow the selection (perhaps I have lots of other buffers open and know that I want to switch to the other "el" buffer).  Not only is the current buffer (`counsel.el`) part of the completion list (why?), but frustratingly it gets highlighted when I type "el".

![buffer](https://user-images.githubusercontent.com/626029/84332143-cc821800-ab51-11ea-84fa-ff86954c85ca.png)

**Comment by mcfarljm** [comment]
Not sure whether inclusion of the current buffer is intended behavior, but I was able to work around it using:
```elisp
(add-to-list 'ivy-ignore-buffers (lambda (buf) (equal (buffer-name (current-buffer)) buf)))
```

**Comment by abo-abo** [comment]
The inclusion of the current buffer is intended, that's what the default completion does too. But your code with `ivy-ignore-buffers` is fine as well.
