### ISSUE TITLE
[rfc] solution to failing self-tests when the source tree is not a git repo

### ISSUE THREAD

**Issue by sten0** [abo-abo/swiper#2608]
Hi @abo-abo,

Sorry for the huge delay getting 0.13 into Debian.  Until now the delay has been 100% wgrep-related.

The following self-tests are failing with "Not in a Git repository":
6 unexpected results:
   FAILED  counsel-find-file-with-dollars
   FAILED  counsel-find-file-with-dotfiles
   FAILED  counsel-find-file-with-spaces
   FAILED  ivy-counsel-read-directory-name
   FAILED  ivy-read-directory-name
   FAILED  ivy-read-file-name-make-directory

What do you think of a helper/setup function that checks for the existence of `.git`, and if it's not found flips a boolean toggle, and `git init ; git add * ; git commit -m 'create git repo for tests'`?  The toggle indicates if `.git` was created solely for tests, indicating that it is safe to remove it during a post-ert-tests cleanup.

This is for Debian's CI, btw.  The boolean var isn't necessary in this context, because I can use Debian tooling to do the cleanup.  I'd be happy to take a stab at the problem but can't provide an ETA, because life has been busy recently.

Thanks again!
Nicholas

**Comment by basil-conto** [comment]
Better yet would be to remove the call to `(counsel-locate-git-root)` from `ivy-with`, as it can assume that it's at the top-level of the source checkout.

**Comment by abo-abo** [comment]
@basil-conto Thanks for the pointer.
@sten0 Thanks for your work. I think you can rebase the patch db5a894 on top of `0.13.0` to fix the tests.

**Comment by sten0** [comment]
@basil-conto, agreed, and if `counsel-locate-git-root` needs coverage than it can have its own ert test added.

@abo-abo thank you very much for the quick fix :-)  db5a894 was an easy cherry pick on top of 0.13, but unfortunately this combination (no other patches or custom config) bizarrely appears to trigger a regression in the following:
```
Test ivy--lazy-load-ffap--ffap-url-p backtrace:
  signal(ert-test-failed (((should (not (fboundp (quote ffap-url-p))))
  ert-fail(((should (not (fboundp (quote ffap-url-p)))) :form (not t) 
  (if (unwind-protect (setq value-7 (apply fn-5 args-6)) (setq form-de
  (let (form-description-9) (if (unwind-protect (setq value-7 (apply f
  (let ((value-7 (quote ert-form-evaluation-aborted-8))) (let (form-de
  (let* ((fn-5 (function not)) (args-6 (condition-case err (let ((sign
  (closure (t) nil (let* ((fn-0 (function not)) (args-1 (condition-cas
  ert--run-test-internal(#s(ert--test-execution-info :test #s(ert-test
  ert-run-test(#s(ert-test :name ivy--lazy-load-ffap--ffap-url-p :docu
  ert-run-or-rerun-test(#s(ert--stats :selector t :tests [#s(ert-test 
  ert-run-tests(t #f(compiled-function (event-type &rest event-args) #
  ert-run-tests-batch(nil)
  ert-run-tests-batch-and-exit()
  eval((ert-run-tests-batch-and-exit))
  command-line-1(("-l" "package" "--eval" "(add-to-list 'package-direc
  command-line()
  normal-top-level()
Test ivy--lazy-load-ffap--ffap-url-p condition:
    (ert-test-failed
     ((should
       (not
        (fboundp ...)))
      :form
      (not t)
      :value nil))
   FAILED  14/56  ivy--lazy-load-ffap--ffap-url-p
```
[emacs-ivy_0.13.0-1_without_db5a894.build.txt](https://github.com/abo-abo/swiper/files/4767971/emacs-ivy_0.13.0-1_without_db5a894.build.txt)
[emacs-ivy_0.13.0-1_with_db5a894.build.txt](https://github.com/abo-abo/swiper/files/4767973/emacs-ivy_0.13.0-1_with_db5a894.build.txt)

**Comment by basil-conto** [comment]
I think `(should (not (fboundp 'ffap-url-p)))` and `(should (fboundp 'ffap-url-p))` can be removed from that test, because they assume too much about the environment and have nothing to do with Ivy.

If it were up to me, I'd remove the entire test `ivy--lazy-load-ffap--ffap-url-p`, because checking whether Ivy causes another package to be loaded is not something suitable for Emacs regression tests or even that useful/practical.

**Comment by sten0** [comment]
Sorry for the belated reply!  I just wanted to say thank you for the help, and report that 0.13.0 was finally uploaded to Debian 24 July 2020.  I decided to `ert-skip` ivy--lazy-load-ffap--ffap-url-p as @basil-conto suggested.  @abo-abo, if you don't want to keep this issue open as a reminder then this issue can probably be closed :-)

**Comment by basil-conto** [comment]
Thanks for your work with Debian!

**Comment by abo-abo** [comment]
Thanks, all.
