### ISSUE TITLE
Sensible rules for completing magit?

### ISSUE THREAD

**Issue by pcn** [abo-abo/swiper#261]
I'm running across ivy completing the remote branch name in a way that slows me down - it just orders the list of remote branches lexicographically, instead of something expected, e.g.:

1. The name of the remote that this is setup to track OR
2.  <name of the remote>/the-name-of-the-local-branch if the above doesn't exist/isn't set yet.

How/where could I be doing this with ivy?

**Comment by abo-abo** [comment]
Which Magit function are you calling, exactly?
Based on that function, you can customize `ivy-sort-functions-alist`.

**Comment by pcn** [comment]
To date I've been more of a user; i.e. using magit-status and typing "P P".  My interaction has been using ivy-completing-read per the documentation.

I'll take a look at ```ivy-sort-functions-alist``` and see if I can figure that out.  I must say that you've got great docstrings, so I'm hopeful.

**Comment by pcn** [comment]
It seems like it's easier for me to copy ```ivy-completing-read``` and modify it like so:

```elisp
(defun my-ivy-completing-read (prompt collection
                            &optional predicate require-match initial-input
                              history def _inherit-input-method)
  (ivy-read (replace-regexp-in-string "%" "%%" prompt)
            collection
            :predicate predicate
            :require-match require-match
            :initial-input (if (consp initial-input)
                               (car initial-input)
                             (if (and (stringp initial-input)
                                      (string-match "\\+" initial-input))
                                 (replace-regexp-in-string
                                  "\\+" "\\\\+" initial-input)
                               initial-input))
            :preselect (if (listp def) (car def) def)
            :history history
            :keymap nil
            :sort nil))
```

Trying to understand how to get ```ivy-sort-functions-alist``` to match to magit ended up being pure guesswork - I tried using ```add-to-list``` with ```'(magit-push-current . nil)``` and it didn't seem to have the desired effect, though I'm not sure if I'm even close.

**Comment by abo-abo** [comment]
The above (turning sorting off completely) can be achieved this way:

```elisp
(setq ivy-sort-functions-alist '((t . nil)))
```

I've checked Magit source, specifically the calls to `magit-completing-read`.  There are many such calls and they all pass only a list of strings as a collection (and not a function like `internal-complete-buffer`). So `ivy-sort-functions-alist` customization won't work.  You can still try to customize through `this-command`, but it's very hard.

**Comment by pcn** [comment]
I should mention that I'm binding it this way:

```(setq magit-completing-read-function 'my-ivy-completing-read)```

so it's only disabled for magit.

**Comment by abo-abo** [comment]
I see. Then maybe this can work as well:

```elisp
(defun my-ivy-completing-read (&rest args)
  (let ((ivy-sort-functions-alist '((t . nil))))
    (apply 'ivy-completing-read args)))
```

**Comment by pcn** [comment]
Ah, that works.  Thanks!
