### ISSUE TITLE
line-based navigation for swiper-isearch?

### ISSUE THREAD

**Issue by jgarvin** [abo-abo/swiper#2611]
Pressing the down arrow with swiper goes to the next matching line, but swiper-isearch goes to the next match even if it's on the same line. Any way to get this behavior with swiper-isearch? Sometimes it's nice to do one or the other, but most of the time line navigation is more efficient because often the same variable is mentioned multiple times on the same line of code.

**Comment by mohkale** [comment]
Why would you use `swiper-isearch` for line-based navigation when `swiper` does that by itself? Is there some reason you prefer using `swiper-isearch`? To the best of my understanding `swiper-isearch` was designed to be `swiper` but not line based (see it's docstring `A ‘swiper’ that’s not line-based.`).

**Comment by abo-abo** [comment]
@jgarvin I think it's possible to implement your request like this:

```elisp
(defvar swiper-isearch-map
  (let ((map (make-sparse-keymap)))
    (set-keymap-parent map swiper-map)
    (define-key map (kbd "M-n") 'swiper-isearch-thing-at-point)
    (define-key map (kbd "<down>") 'swiper-isearch-next-line)
    map)
  "Keymap for `swiper-isearch'.")

(defun swiper-isearch-next-line ()
  (interactive)
  (let ((shift 1))
    (with-ivy-window
      (let ((ln (line-number-at-pos (ivy-state-current ivy-last))))
        (while (and (< (+ ivy--index shift) ivy--length)
                    (= ln (line-number-at-pos (nth (+ ivy--index shift) ivy--all-candidates))))
          (cl-incf shift))))
    (ivy-next-line shift)))
```

However, I think it's not worthwhile to add a whole new command and key binding for such a narrow use case. If you think it's worthwhile, feel free to adapt this in your config.

**Comment by jgarvin** [comment]
@abo-abo thanks, I use this version, just tweaked to not redefine the whole keymap:

```
(defun swiper-isearch-next-line ()
  (interactive)
  (let ((shift 1))
    (with-ivy-window
      (let ((ln (line-number-at-pos (ivy-state-current ivy-last))))
        (while (and (< (+ ivy--index shift) ivy--length)
                    (= ln (line-number-at-pos (nth (+ ivy--index shift) ivy--all-candidates))))
          (cl-incf shift))))
    (ivy-next-line shift)))

(define-key swiper-isearch-map (kbd "<down>") #'swiper-isearch-next-line)

```

**Comment by mohkale** [comment]
@jgarvin Just worth pointing out your previous line solution is buggy for me. You seem to be judging the distance to the next line when deciding how far to go back to go to the previous line. This works for me.

```lisp
(defun swiper-isearch-prev-line ()
  (interactive)
  (let ((shift 1))
    (with-ivy-window
      (let ((ln (line-number-at-pos (ivy-state-current ivy-last))))
        (while (and (>= (- ivy--index shift) 0)
                    (= ln (line-number-at-pos (nth (- ivy--index shift) ivy--all-candidates))))
          (cl-incf shift))))
    (ivy-previous-line shift)))
```

**Comment by jgarvin** [comment]
@mohkale I mostly use next line so I hadn't noticed that the behavior isn't right, you are correct, thanks!
