### ISSUE TITLE
ivy-occur errors when shrinking window

### ISSUE THREAD

**Issue by franburstall** [abo-abo/swiper#2614]
Starting from `make plain` (and ignoring the complaint about `avy` not being found), I split the window vertically (`C-x 3`) so that two windows are visible, fire `ivy-read`, for example
```elisp
(ivy-read "Choose: " '("x" "y")
	    :action (lambda (x) (message "Default: %s" x))
	    :multi-action (lambda (xs) (message "Default: %S" xs))
	    :caller 'test-ivy)
```
and then call `ivy-occur` with `C-c C-o`.  The `*ivy-occur*` buffer appears in the right hand window.  I hit `a` to read an action and hit 'i' to choose one.

What I expect: I should see nothing but the chosen action will be applied when I hit next `RET`.

What I get: an error of the form ` Cannot resize window #<window 67 on *...`

Commentary: you get a similar error if the `*ivy-occur*` buffer is the only window in the frame (`Cannot resize root window...`).  It is because `ivy-occur-read-action` eventually calls `ivy-shrink-after-dispatching` though this does not seem to be the Right Thing to do in such a buffer, perhaps.

**Comment by abo-abo** [comment]
Thanks for the report. Now `ivy-shrink-after-dispatching` will only shrink when in the minibuffer. Does that fix your issue?

**Comment by franburstall** [comment]
Yup, that fixes it!

Many thanks!
