### ISSUE TITLE
Unable to search for numbers + Error in post-command-hook (ivy-exhibit)

### ISSUE THREAD

**Issue by kaushalmodi** [abo-abo/swiper#262]
This could be a result of 2 "bugs"?

Below is the sample buffer:

```
1.0000000000	-0.0182692729	0.0000000000	0.0000000000	0.2656975641	-0.2656975641
1.0000000000	0.9817307271	0.0000000000	0.0000000000	1.0907167978	-1.0907167978
0.0000000000	1.0000000000	1.0000000000	-0.0028513199	1.6019972951	-1.6019972951
0.0000000000	1.0000000000	1.0000000000	0.9971486801	2.5404951468	-2.5404951468
0.0000000000	0.0000000000	0.0000000000	1.0000000000	1.0000000000	0.0000000000
```

I wanted to search for `^[10]` to search for all lines that begin with either number `1` or `0`.

Surprisingly that did not work.

**Bug 1:** Swiper does not work when searching for numbers.

Then when I tried to delete the typed regexp expression, I hit **Bug 2** that gave this "Error in post-command-hook" error.

Enabling debug on error did not help; I did not get any backtrace. I don't know why.

Below is a GIF of shows both the bugs:

![ivy-exhibit-error](https://cloud.githubusercontent.com/assets/3578197/10489731/344aa052-726c-11e5-8ac5-c5a31cfb8fb2.gif)

**Comment by kaushalmodi** [comment]
**UPDATE**

This bug is actually not specific to numbers.

Even if I have a buffer without numbers like below:

```
abc
def
azy
```

I cannot search for `^a` using swiper.

**Comment by abo-abo** [comment]
Thanks, please test. And make sure to restart Emacs after updating to the latest version.

**Comment by kaushalmodi** [comment]
Thank! This fixes the Bug 1 I referenced in the first post of this thread.

Bug 2 is still there; I think it happens whenever I use `^` in the search string.

Here's how to recreate it:

1. Put put in a \*scratch\* buffer.
 
 ```
abc
def
azy
```
2. `M-x swiper` and search for `^a`.
3. This search will work fine because of the fix in https://github.com/abo-abo/swiper/commit/9cc75eb095ba158b31fc1fcf771a613c7a5fd908.
4. But now when you hit Backspace, you should get `Error in post-command-hook (ivy--exhibit): (wrong-type-argument integer-or-marker-p nil)`.

**Comment by abo-abo** [comment]
Thanks for the recipe. Please test again.

**Comment by kaushalmodi** [comment]
Thank you! It's fixed now :).
