### ISSUE TITLE
Calling ivy-occur from counsel-projectile-ag fails

### ISSUE THREAD

**Issue by alecvn** [abo-abo/swiper#2623]
I used to be able to call `ivy-occur` on `counsel-projectile-ag` search results and get a results buffer to work on.  After upgrading `projectile`, `projectile-rails`, `counsel`, `ivy` and `swiper` to their latest versions I now get the following error in the scenario outlined above:

`Symbol's function definition is void: swiper--occur-insert-lines`

**Comment by abo-abo** [comment]
What's the version of `swiper.el` on your system? Which packaging solution do you use? Have you tried to re-install and restart Emacs?

**Comment by alecvn** [comment]
Hey man, I wasn't using the latest version of `swiper.el`.  My apologies!

**Comment by abo-abo** [comment]
No problem.
