### ISSUE TITLE
Ivy: symbol at point should not stick after typing

### ISSUE THREAD

**Issue by PythonNut** [abo-abo/swiper#263]
#231 is back, it seems. I don't know how to write a test for this, but if the point is over a symbol, and you do `counsel-M-x` the symbol at point remains selected (even if it's not the highest ranked) even after the user starts typing.

**Comment by abo-abo** [comment]
Isn't that a good thing? If a string is passed as `:preselect`, it should have the highest priority, as long as it matches.

**Comment by PythonNut** [comment]
To my mind, typing indicates that you're not interested in the preselected candidate. If you were, you could have just typed <kbd>&lt;return&gt;</kbd>.

As is stands, queries like `csa` will match pa**c**kage-li**s**t-pack**a**ges, instead of something like **c**ompany-**s**earch-**a**bort.

**Comment by abo-abo** [comment]
I've turned off this behavior only for the case when flx is working.

Otherwise, this should work:

```elisp
(should (equal (ivy-with '(ivy-read "test" '("cand1" "cand2" "cand3"))
                         "C-n C-n cand C-m")
               "cand3"))
```

I think it would be frustrating for the user to select something with <kbd>C-n</kbd> only to have the selection reset by typing one more char.

**Comment by PythonNut** [comment]
Okay, fair enough.
