### ISSUE TITLE
Swiper 0.13.1 on melpa-stable is broken

### ISSUE THREAD

**Issue by manphiz** [abo-abo/swiper#2633]
Swiper 0.13.1 installed from melpa-stable is missing several critical files (probably packaging issue?):

counsel.el
ivy-autoloads.el
swiper.el

Now all counsel*, swiper*, and ivy* commands are undefined, making ivy completely unusable.  Please help fix.  Thanks!

**Comment by aadcg** [comment]
I think you need to install swiper, counsel and ivy from melpa-stable. I think before it would suffice to install counsel from melpa (not melpa-stable) to get the 3 of them.

**Comment by manphiz** [comment]
Indeed, installing counsel pulls in all required packages.  Thanks @aadcg !
