### ISSUE TITLE
ivy-occur from swiper and counsel-rg is failing with an error

### ISSUE THREAD

**Issue by CSRaghunandan** [abo-abo/swiper#2635]
Error when running `ivy-occur` on `swiper`: `[Args out of range: 0, 1]`

Error when running `ivy-occur` on `counsel-rg`: `[Wrong type argument: sequencep, 32]`

My emacs environment:
```
Emacs version: GNU Emacs 28.0.50 (build 3, x86_64-pc-linux-gnu, GTK+ Version 3.24.21, cairo version 1.17.3)
 of 2020-07-01, built using commit e98ddd6fc1626a7417a76a4ce51c4591731d1c26.

./configure options:
  --with-modules --with-rsvg --with-dbus --with-imagemagick --without-pop --with-xft --with-xml2 --with-libotf --with-mailutils

Features:
  XPM JPEG TIFF GIF PNG RSVG CAIRO IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2 GMP
```

**Comment by CSRaghunandan** [comment]
Updating emacs packages seems to have fixed this issue. Closing the issue

**Comment by CSRaghunandan** [comment]
> Updating emacs packages seems to have fixed this issue. Closing the issue

So, this error still persists.
I just did not run into it previously when I made this comment

To reproduce this error, I have to search like this: `word1 word2`, whereas if i just search for `word1` it will work without any issues.

Is there any workaround to fix this :( `counsel-rg` and `ivy-occur` are a vital part of my workflow

**Comment by basil-conto** [comment]
Sorry, I'm not familiar with and don't understand the Occur code.

**Comment by CSRaghunandan** [comment]
Okay, so this seems to be happening only when the completion style is set to `ivy--regex-ignore-order`

for now, I will use a different completion style.

**Comment by rymndhng** [comment]
I've run into this issue as well. There seems to be an issue with `ivy-occur` which incorrectly encodes the flag `--pcre2` as `32 45 45 112 99 114 101 50 32`.
