### ISSUE TITLE
Searching string fails by counsel-rg when dired-mode is on

### ISSUE THREAD

**Issue by templateK** [abo-abo/swiper#2641]
On dired mode, if we evaluate `(counsel-rg "foo" default-directory)`, the search will fail
even though there are "foo" string exists unless the cursor is on the file or the user marked files
which contains the search string .

this is caused by internal function `counsel--rg-targets` is unconditionally using 
the `dired-mode-get-marked-files` for search targets when major-mode is `dired-mode`.

**Comment by templateK** [comment]
stale activity. closing issue.

**Comment by basil-conto** [comment]
FWIW, I cannot reproduce the issue: `counsel-rg` works as expected even when no files are marked in Dired.
