### ISSUE TITLE
In ivy mode, commands that have input as prefix of their name should be presented first

### ISSUE THREAD

**Issue by rudi** [abo-abo/swiper#265]
Using standard completion or icomplete-mode, `M-x man RET` executes the `man` command.  When turning on `ivy-mode`, man is somewhere on the 8th screen.  (Entering `^man` on the prompt helps a bit, but once the library is loaded, various commands starting with uppercase `"Man-"` prefix are presented before `man` even in that case.)  Other commands have the same problem, e.g., `gnus` is presented after `diary-from-outlook-gnus` when typing `M-x gnus`.

Would it be possible to sort the list of completions so that prefix matches of the input string come before other possibilities?

**Comment by abo-abo** [comment]
You should use a dedicated command for <kbd>M-x</kbd>:

```elisp
(global-set-key (kbd "M-x") 'counsel-M-x)
```

It already comes with `^` as the initial input, so the issue disappears.

Alternatively, you can rely on `flx` to do the prefix sorting:

```elisp
(setq ivy-re-builders-alist
      '((t . ivy--regex-fuzzy)))
```

**Comment by abo-abo** [comment]
Use:

```elisp
(setq ivy-prefix-sort t)
```

to turn on the new behavior. It's off by default, because it can be potentially more time-consuming.
If it turns out to be fast enough, `ivy-prefix-sort` will be made on by default.

**Comment by abo-abo** [comment]
I reconsidered the customization interface because of #269.  You should now use:

```elisp
(setq ivy-sort-matches-functions-alist
      '((t . ivy--prefix-sort)))
```

to turn on the prefix sorting. It's more flexible, since it allows to turn on extra sorting only for some commands if you want.
