### ISSUE TITLE
Propose new command

### ISSUE THREAD

**Issue by Ergus** [abo-abo/swiper#2651]
Hi:

I find the following command very usefull as a substitution for `highlight-thing-at-point`:

```
(defun ivy-highlight-thing-at-point ()
  "Highlight thing at point or region."
  (interactive)
  (require 'hi-lock nil)
  (let ((thing (ivy-thing-at-point))
	(face (hi-lock-read-face-name)))
    (or (facep face) (setq face 'hi-yellow))
    (unless hi-lock-mode (hi-lock-mode 1))
    (when (use-region-p)
      (deactivate-mark))
    (hi-lock-set-pattern (regexp-quote thing) face)))
```

The main advantage (in my opinion) is how it manages the active region thanks to `ivy-thing-at-point`. So I share it in case you want to add it to ivy||counsel

**Comment by abo-abo** [comment]
Thanks. You can now highlight using <kbd>M-o h</kbd> from `counsel-faces`.

**Comment by Ergus** [comment]
Hi Abo-Abo:

This command can be bind to `M-s h .` in counsel-mode as a substitution for `highlight-symbol-at-point`because it brings the same functionality but improved.

**Comment by abo-abo** [comment]
I don't think it's the same functionality, since <kbd>M-s h .</kbd> does not use completion.
