### ISSUE TITLE
When :preselect has an effect?

### ISSUE THREAD

**Issue by zbelial** [abo-abo/swiper#2657]
I want to use ivy-read to list pdf's tocs and jump among them, and I want to preselect the toc item just after what I'm reading. 
Here is the code:
```elisp
            (defun pdf-outline ()
                (interactive)
                (let ((tocs (TOCS_OF_CURRENT_DOCUMENT))
                      (page-number (CURRENT_PAGE_NUM))
                      (preselect 0))

                  (dolist (toc tocs)
                    (when (<= (toc's PAGE NUMBER) page-number)
                      (setq preselect (1+ preselect)))
                    )

                  (ivy-read "Table of contents: " tocs
                            :preselect preselect
                            :action '(1
                                      ("o" pdf-outline-jump "jump to content")
                                      )
                            :caller 'pdf-outline
                            )))
```

The issue I have is the first candidate but not the item specified by :preselect is preselected. 

Could you point out the errors in my code?  Thanks.

**Comment by basil-conto** [comment]
Works for me, starting from `emacs -Q` or `make plain`:

```el
(defun my-tocs ()
  (list (list "front"  :page  1)
        (list "first"  :page  3)
        (list "second" :page  6)
        (list "third"  :page 10)
        (list "back"   :page 13)))

(defun my-toc-page (toc)
  (plist-get (cdr toc) :page))

(defun my-read-toc ()
  (interactive)
  (let* ((tocs (my-tocs))
         (page 9)
         (preselect (1- (cl-position-if (lambda (toc-page) (> toc-page page))
                                        tocs :key #'my-toc-page))))
    (ivy-read "Table of contents: " tocs
              :preselect preselect
              :action '(1 ("i" ignore "ignore"))
              :caller 'my-read-toc)))
```

Invoking `my-read-toc` preselects `"second"`, as I'd expect.

Please try stepping through your code to see if it's behaving as expected, and/or try reproducing the issue starting from `emacs -Q` or `make plain`, describing in detail the steps you take, what you observe, and what you expected.

**Comment by zbelial** [comment]
Thanks for your quick reply.
I found what caused the problem:
```elisp
(add-to-list 'ivy-re-builders-alist '(pdf-outline . ivy-regex-pinyin))  
```
`ivy-regex-pinyin` uses Chinese pinyin to filter the candidate.

If I comment this line, then `pdf-outline` works as expected. I haven't found the root cause, but I'll try, and if necessary, I'll open a new issue.
