### ISSUE TITLE
error in process filter: Wrong type argument: stringp, (require . info)

### ISSUE THREAD

**Issue by XO39** [abo-abo/swiper#2659]
After upgrading Emacs to v27.1, whenever I try to update packages, as soon as I go to `M-x list-packages` I get the following error:

```
error in process filter: Wrong type argument: stringp, (require . info)
```

I traced the error, and found out it only when using **Ivy**, I even tried with vanilla Emacs, with only Ivy installed, before installing Ivy there is no error, after installing Ivy, this error appears.

I'm using Emacs v27.1 (9.0) on macOS Catalina 10.15.6

This error forced me to switch *temporary* to helm despite the fact that I don't really like it, as this error prevents me from updating or installing packages!

Hope to have a fix soon.

**Comment by XO39** [comment]
Sorry, it looks like it was a bug in the last version of Emacs and the fix  just released, closing this issue

**Comment by basil-conto** [comment]
Sounds like magnars/dash.el#343.
