### ISSUE TITLE
Multiple (non exiting) completion is only a feature of ivy (and not plain completing-read)?

### ISSUE THREAD

**Issue by TRSx80** [abo-abo/swiper#2668]
Apologies if this is a very dumb and/or basic question.  But I have been using ivy/swiper/counsel almost since the very beginning of my Emacs journey some years ago.  Now I am at the point of writing my own first little package, and looking to do some multi-selection on a list of tags.  I would like to do this without leaving the selection dialog, the same way that `counsel-org-tag` works for instance.

In the course of researching/implementing this, I think I suddenly realized that something I perhaps took for granted all along is in fact only a feature of `ivy`, and not `completing-read` itself.  Have I got that correct?

Due to (overly broad by their nature? poor on my part?) search terms involved, I could not seem to directly confirm this, although [this](https://github.com/abo-abo/swiper/issues/120) thread gets pretty close and [this](https://github.com/abo-abo/swiper/issues/177) one perhaps does in fact confirm that it looks like this functionality was added on 2015-07-24 in ae77d93.  But it is possible that issue was only about `counsel-org-tag` and I was hoping to positively confirm (or not) in the general case.

My testing would seem to confirm it, but I suppose I was looking for additional confirmation before making `ivy` a dependency of my new package.  So far, I had been trying to write my interface with plain `completing-read` so as to work with whatever user's choice of completion framework might be, however I think this is enough of an important functionality to my package to require it.

**Comment by basil-conto** [comment]
Sorry, what exactly is the question?

If you're looking for a built-in way to read an arbitrary number of strings without exiting completion, there's `completing-read-multiple`.

**Comment by TRSx80** [comment]
That answers it!  Thanks a lot Basil for the fast reply.  And sorry for idiotic ramblings!  :smile: 

I guess my next step will be to play with `completing-read-multiple` vs. `ivy` to see if they are interchangeable the same way that `ivy-completing-read` is with regular `completing-read`.  After a brief look at the source commentary of `completing-read-multiple`, I'm not so sure.

**Comment by basil-conto** [comment]
Whether they're interchangeable depends on what you want them to do. There are some features supported by `completing-read` and `completing-read-multiple`, such as [programmed completion](https://www.gnu.org/software/emacs/manual/html_node/elisp/Programmed-Completion.html), which Ivy either doesn't support or doesn't support well. And then there are many features that Ivy provides which you can't get with vanilla completion. YMMV.

**Comment by TRSx80** [comment]
Thanks for the feedback, Basil.

What I wanted was something in the style of `counsel-org-tag` where you have a vertical `completing-read` style interface, but can press some key (i.e., `C-M-m`) to do "non-exiting" addition/removal of the selected candidate to/from some other multiple value list.  In my case, that "other list" are values of an Orgmode Property, instead of Orgmode tags on the headline (as with `counsel-org-tag`).

Perhaps this *can* be done with `completing-read-multiple` but as I am unfamiliar with it, I could not figure it out.  In fairness I didn't spent much time.  I am a lot more familiar with `ivy` and so I implemented it that way, for now, mostly out of expediency.

However I suppose I am still curious if such a thing is even possible with `completing-read-multiple`, if for nothing other than my own edification.

`completing-read-multiple`, to me, seems more oriented towards in-buffer `completion-at-point` type editing of lists.  In other words, grab the whole list, edit, replace whole list.  Which I guess could work, now that I think about it more.  Or maybe I am misunderstanding.

However I ended up using `ivy` and the Orgmode [Property API](https://orgmode.org/manual/Using-the-Property-API.html) to add/remove values one by one from the list, by way of a function I wrote which is called by `:action` in my `ivy-read` statement.  Works a treat.  I suppose just two different approaches to the same problem.

**Comment by basil-conto** [comment]
Here's a sample `completing-read-multiple` session with `ivy-mode`, FWIW:

1. `(completing-read-multiple "Properties: " '("foo" "foobar" "bar" "baz"))`

2. <kbd>C-x</kbd><kbd>C-e</kbd>

   ![2020-09-05-185352_1920x1080_scrot](https://user-images.githubusercontent.com/9121222/92310791-89e1a780-efa9-11ea-9698-3fbedef44f1d.png)

3. <kbd>TAB</kbd>

   ![2020-09-05-185454_1920x1080_scrot](https://user-images.githubusercontent.com/9121222/92310797-9403a600-efa9-11ea-8318-4327988645f5.png)

4. <kbd>C-j</kbd>

   ![2020-09-05-185457_1920x1080_scrot](https://user-images.githubusercontent.com/9121222/92311401-93214300-efae-11ea-99b3-1ac01dd79758.png)

5. `,`<kbd>TAB</kbd>`bar`<kbd>C-j</kbd>

   ![2020-09-05-185517_1920x1080_scrot](https://user-images.githubusercontent.com/9121222/92311412-b5b35c00-efae-11ea-9da9-135cbacd5b20.png)

6. <kbd>RET</kbd>

   ![2020-09-05-185526_1920x1080_scrot](https://user-images.githubusercontent.com/9121222/92311419-be0b9700-efae-11ea-8888-2a1f8acf9ae7.png)

**Comment by TRSx80** [comment]
I really appreciate you taking the time to post such a thorough example, Basil.

I think I must have "Ivy brain", in other words I am just so used to Ivy that, even with your lovely examples, I still had to re-visit this a couple times to get my head around it.

Maybe it is just familiarity, but I find Ivy's way of doing it much more intuitive (once you figure out C-M-m, anyway).  I find the `completing-read-multiple` way of going about it very awkward, even if I *could* probably accomplish the same thing.

Moreover, it does seem to return the whole list at once, instead of executing actions on one submitted candidate at a time the way that Ivy does.  So I also think Ivy is superior in that respect.

I don't want to put the cart before the horse, but if #2676 comes to fruition, it looks like Ivy may eventually end up in vanilla anyway.

For my purposes, in the meantime, I am just going to make Ivy a hard dependency of my package.  And therefore closing this issue.

Thanks again for the help Basil, and for all you do on an ongoing basis.  It is greatly appreciated.

Cheers!  :beers:

**Comment by basil-conto** [comment]
Thanks for reporting back @TRSx80, and for the sentiment. Of course different tools service different needs, to each their own, YMMV, etc. :) Patches, feature requests, and bug reports are always welcome both here and on the Emacs mailing lists, e.g. via `M-x report-emacs-bug`.
