### ISSUE TITLE
counsel-M-x doesn't use fzf.el

### ISSUE THREAD

**Issue by NightMachinary** [abo-abo/swiper#2670]
It'd be great if this was supported, as M-x is probably the most used part of Emacs. Finding commands with the current fuzzy mode is hard, because you need to guess the correct order of the words:
![image](https://user-images.githubusercontent.com/36224762/92312144-456b0180-efd3-11ea-9649-e516aa469e80.png)

![image](https://user-images.githubusercontent.com/36224762/92312145-49971f00-efd3-11ea-9432-396e067353e0.png)

Related: I had opened a general [issue](https://github.com/abo-abo/swiper/issues/2575) on using fzf everywhere when I didn't know about `counsel-fzf` and `fzf.el`. I guess that is not easily possible, so just having fzf in the most important counsel functions is the next best thing.

**Comment by mohkale** [comment]
Not a solution to this specific problem, but if all you want is to allow `M-x` to be order independent. You can change the re-builder used by it.

```lisp
(push (cons 'counsel-M-x #'ivy--regex-ignore-order) ivy-re-builders-alist)
```

There's a list of builders, including a fuzzy builder (NOTE: performance takes a pretty big hit when using this).

**Comment by NightMachinary** [comment]
I [implemented](https://github.com/NightMachinary/fzf.el/blob/master/counsel-fzf.el) this myself.
