### ISSUE TITLE
How to search for the whole word using swiper?

### ISSUE THREAD

**Issue by c02y** [abo-abo/swiper#2671]
I need to search for the whole word using swiper like `grep -w`, I got the solution like this:
```
  (defun swiper-whole-word ()
    "Search the whole word using swiper-isearch"
    (interactive)
    (let ((input (read-string "Search whole word: ")))
      (swiper-isearch (concat "\\_<" "\\_>"))))
```
So I input the word first, and let swiper-isearch search the pattern `\_<word\_>` directly.

This works OK, but what if I don't want to use `read-string` first before using swiper? Such as execute `swiper-isearch` with `\_<\_>` in the prompt but my point is in the middle `\_<\_>`, and I need to input a word manually in the middle of `\_<\_>`, as I type, swiper will start search directly(without hitting `Enter`), just like you `M-x swiper-isearch`, and type `\_<\_>`, and move cursor to the middle `\_<\_>` and start typing the word, how can I do that?

**Comment by basil-conto** [comment]
Note that `\_<` and `\_>` are beginning and end of symbol, respectively. Beginning and end of word are `\<` and `\>`, respectively.

Here's one way to do what you're asking:

```el
(let ((unread-command-events '(?\C-b ?\C-b)))
  (swiper-isearch "\\<\\>"))
```

**Comment by c02y** [comment]
That's OK, symbol includes word, right? I'll just use `\_<\_>`.

Thanks.

**Comment by basil-conto** [comment]
> symbol includes word, right?

Not necessarily; I think it depends on the current syntax table.

**Comment by c02y** [comment]
I'll just use `\_<\_>`, when I want to search the word `def` in the buffer, using `\<def\>` will list the result containing `abc_def`, this is not what I want.
