### ISSUE TITLE
Make compatible with evil-jumper

### ISSUE THREAD

**Issue by sooheon** [abo-abo/swiper#268]
If using helm-swoop, after finding and moving point to a result, I can easily go back to my point before helm-swoop was called with `evil-jumper/backward`. With swiper, the previous point is not saved onto the evil-jumper "stack", and I have to go back by mark. Would it be possible to add this support?

**Comment by abo-abo** [comment]
I'm not familiar with `evil-jumper`.

Here's the only part of `helm-swoop` to include "evil".

```elisp
;; Receive word from evil search ---------------
(defun helm-swoop-from-evil-search ()
  "Invoke `helm-swoop' from evil isearch"
  (interactive)
  (if (string-match "\\(isearch-\\|evil.*search\\)" (symbol-name real-last-command))
      (helm-swoop :$query (if isearch-regexp
                              isearch-string
                            (regexp-quote isearch-string)))
    (helm-swoop)))
;; When doing evil-search, hand the word over to helm-swoop
;; (define-key evil-motion-state-map (kbd "M-i") 'helm-swoop-from-evil-search)
```

Can you explain what exactly you want me to do? Even better, a patch would be welcome.

**Comment by abo-abo** [comment]
Please test. It seems to work, at least with evil-mode off.

**Comment by sooheon** [comment]
Confirmed work with evil-mode as well. Thanks.

**Comment by srustamo** [comment]
[evil-jumper is OBSOLETE. evil-jumper has been merged into upstream evil-mode; therefore this functionality is already available by default.](https://github.com/bling/evil-jumper).

So, the jump list does not get updated. 

Perhaps testing for the `evil-mode` instead of `evil-jumper-mode` would help?

**Comment by srustamo** [comment]
On a closer look, `evil-mode` requires `evil-jumps` package, which defines

```
(defun evil-set-jump (&optional pos)
  "Set jump point at POS.
POS defaults to point."
  (unless (or (region-active-p) (evil-visual-state-p))
    (push-mark pos t))

  (unless evil--jumps-jumping
    ;; clear out intermediary jumps when a new one is set
    (let* ((struct (evil--jumps-get-current))
           (target-list (evil--jumps-get-jumps struct))
           (idx (evil-jumps-struct-idx struct)))
      (cl-loop repeat idx
               do (ring-remove target-list))
      (setf (evil-jumps-struct-idx struct) -1))
    (evil--jumps-push)))
```

**Comment by srustamo** [comment]
I'm not sure what is your stance on people commenting closed tickets, but I think keeping related stuff threaded helps other people find related stuff quicker.

Let me know if you prefer separate tickets instead.

**Comment by abo-abo** [comment]
@srustamo Please open a new issue. I don't like reading messages from ages ago just to get a context of how it applies to the new message.

Regarding the change in `evil-jumper`, please consider submitting a PR.
