### ISSUE TITLE
Documentation: no example in swiper of update-fn usage

### ISSUE THREAD

**Issue by TRSx80** [abo-abo/swiper#2685]
In [9.2 Optional arguments for ivy-read](https://oremacs.com/swiper/#optional-arguments-for-ivy-read), for `update-fn` it says:

> See swiper for an example usage.

However, looking in `swiper.el`, I don't see any such thing?

The least I could do would be to help out and submit a PR, but unfortunately I don't know enough about the inner workings to suggest any alternative (well, that's why I was reading the docs in the first place, now i'nit? :wink:  ).

**Comment by basil-conto** [comment]
> However, looking in `swiper.el`, I don't see any such thing?

Which version do you have?  Searching for `update-fn` in the latest `swiper.el` gives me four results:

```el
(ivy-configure 'swiper-query-replace
  :update-fn #'swiper--query-replace-updatefn)

(ivy-configure 'swiper
  :occur #'swiper-occur
  :update-fn #'swiper--update-input-ivy
  :unwind-fn #'swiper--cleanup
  :index-fn #'ivy-recompute-index-swiper)

(ivy-configure 'swiper-all
  :update-fn 'auto
  :unwind-fn #'swiper--cleanup
  :format-fn #'swiper--all-format-function)

(ivy-configure 'swiper-isearch
  :occur #'swiper-occur
  :init-fn #'swiper--isearch-init
  :update-fn 'auto
  :unwind-fn #'swiper--isearch-unwind
  :format-fn #'swiper-isearch-format-function)
```

That said, the docs are indeed in need of much love.

**Comment by TRSx80** [comment]
Well it looks like even on `swiper-0.13.0` that I have here, I do get more or less the same results as you show there when I open `swiper.el` and search.

Therefore I am not sure what the hell I was looking for at first, and thank you for clearing up my confusion.  I am sure this will be a good entry point for study the next time I get into this.  Closing the issue.

Thanks again Basil for the support.  It is greatly appreciated.

Cheers!  :beers:

**Comment by basil-conto** [comment]
Thanks for reporting back and confirming.
