### ISSUE TITLE
ivy.el: assignment to free variable in mwheel-scroll-up-function and mwheel-scroll-down-function

### ISSUE THREAD

**Issue by diamond-lizard** [abo-abo/swiper#2686]
When I type ```make compile```, I get these warnings:
```
In ivy--minibuffer-setup:
ivy.el:2938:42:Warning: assignment to free variable
    ‘mwheel-scroll-up-function’
ivy.el:2939:44:Warning: assignment to free variable
    ‘mwheel-scroll-down-function’
```

**Comment by basil-conto** [comment]
Please provide more information about your Emacs, specifically the output collected by `M-x report-emacs-bug` (including version, features that Emacs was compiled with, etc.).

Based on these warnings, I'm guessing you're seeing these warnings in a `--without-x` (aka `emacs-nox`) build?

**Comment by diamond-lizard** [comment]
My emacs was in fact compiled ```without-x```, as I only use emacs from the terminal and have no need for X support.

Here is the output of ```M-x report-emacs-bug```


```
In GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu)
 of 2020-09-22 built on localhost
System Description: Gentoo/Linux


Configured using:
 'configure --prefix=/usr --build=x86_64-pc-linux-gnu --host=x86_64-pc-linux-gnu --mandir=/usr/share/man --infodir=/usr/share/info --datadir=/usr/share --sysconfdir=/etc --localstatedir=/var/lib --disable-silent-rules --docdir=/usr/share/doc/emacs-27.1-r1 --htmldir=/usr/share/doc/emacs-27.1-r1/html --libdir=/usr/lib64 --program-suffix=-emacs-27 --includedir=/usr/include/emacs-27 --infodir=/usr/share/info/emacs-27 --localstatedir=/var --enable-locallisppath=/etc/emacs:/usr/share/emacs/site-lisp --without-compress-install --without-hesiod --without-pop --with-dumping=pdumper --with-file-notification=inotify --enable-acl --without-dbus --with-modules --without-gameuser --with-libgmp --without-gpm --with-json --without-kerberos --without-kerberos5 --without-lcms2 --with-xml2 --without-mailutils --without-selinux --with-gnutls --without-libsystemd --with-threads --without-wide-int --with-zlib --with-sound=alsa --without-x --without-ns 'CFLAGS=-O2 -march=native -pipe' CPPFLAGS= 'LDFLAGS=-Wl,-O1 -Wl,--as-needed''
```

**Comment by basil-conto** [comment]
Thanks for confirming.

Apart from the byte-compiler warnings, do you see any other negative effects on Emacs built `--without-x`?

If not, I claim that this as an upstream bug, because I too have run into `mwheel.el` issues on Emacsen built `--without-x`, such as the inability to enable `mouse-wheel-mode` without first initialising the eponymous variable.

**Comment by diamond-lizard** [comment]
I have run in to some issues with 27.1, like emacs freezing while editing source code blocks in dedicated editing buffers from org-mode, and backtraces overwiting buffer contents instead of outputting backtraces to the dedicated backtrace buffer as they normally would.

However, I have no reason to suspect that these have anything to do with emacs being compiled ```--without-x``` or not having mouse wheel functionality.

But just in case, at some point I might recompile emacs with x support and see if I can reproduce these issues.

**Comment by basil-conto** [comment]
> However, I have no reason to suspect that these have anything to do with emacs being compiled `--without-x` or not having mouse wheel functionality.

Or, crucially for the thread at hand, have anything to do with Ivy (until proven otherwise).

**Comment by diamond-lizard** [comment]
> Or, crucially for the thread at hand, have anything to do with Ivy (until proven otherwise).

Yes, sorry, I should have made that clear.

I have no reason to suspect they have anything to do with Ivy, but they are things that *may* have to do with compiling emacs ```--without-x``` (though, again, no reason to suspect that either).

As the compiler warnings that this issue was opened about don't seem to have any adverse effect on Ivy, I am happy to close this issue.

And if you think they're upstream bugs, that's good enough for me.
