### ISSUE TITLE
Allow user-specified candidate sorting

### ISSUE THREAD

**Issue by AnOctopus** [abo-abo/swiper#269]
(Possibly related to #213 )

It would be very nice to have the ability to specify a sorting function to be applied to the candidates after filtering. In particular, I would like to be able to use flx sorting with the normal regex filter (currently achievable only by ivy--filter directly), but it would be nice to have generally.

**Comment by abo-abo** [comment]
Thanks.

For example, you can now use:

```elisp
(setq ivy-sort-matches-functions-alist
      '((t . ivy--prefix-sort)))
```
