### ISSUE TITLE
ivy: Default candidate with perfect match

### ISSUE THREAD

**Issue by joostkremers** [abo-abo/swiper#270]
A few updates ago, if the text you had typed was a perfect match for one of the candidates, that candidate would be the default. It seems that this functionality was lost in a recent update, however. Is there some way to bring this back?

**Comment by abo-abo** [comment]
Thanks for noticing. It should be back now.

**Comment by abo-abo** [comment]
Added a test so that the bug doesn't come back:)

**Comment by joostkremers** [comment]
Great, thanks!
