### ISSUE TITLE
glob option causes no results in counsel-rg

### ISSUE THREAD

**Issue by jaza-syed** [abo-abo/swiper#2700]
Running `C-u C-u counsel-rg` and provided `-g '*.sh'` as the `rg-args` causes no results to appear. I've tested the same command in the same directory in a terminal and ripgrep works fine there. I've tested in a vanilla emacs with just ivy installed, so I don't think it's a config issue.

**Comment by basil-conto** [comment]
By default, `counsel-rg` now calls `rg` directly, rather than through the shell, so there's no need for single quote escapes - just try `-g *.sh` directly.

**Comment by jaza-syed** [comment]
That solves my issues. Thanks a lot!
