### ISSUE TITLE
[Q] How do I feed a string as stdin of `counsel--async-command`?

### ISSUE THREAD

**Issue by NightMachinary** [abo-abo/swiper#2702]
The input I want to pass the command is too big to fit in a commandline, so I can't use `echo ... | ...`. I have tried:
```
(defun counsel--async-command-1 (cmd &optional sentinel filter name)
  "Start and return new counsel process by calling CMD.
CMD can be either a shell command as a string, or a list of the
program name to be called directly, followed by its arguments.
If the default counsel process or one with NAME already exists,
kill it and its associated buffer before starting a new one.
Give the process the functions SENTINEL and FILTER, which default
to `counsel--async-sentinel' and `counsel--async-filter',
respectively."
  (counsel-delete-process name)
  (setq name (or name " *counsel*"))
  (when (get-buffer name)
    (kill-buffer name))
  (setq counsel--async-last-command cmd)
  (let* ((buf (get-buffer-create name))
         (proc (if (listp cmd)
                   (apply #'start-file-process name buf cmd)
                 (start-file-process-shell-command name buf cmd)
                 )))
    (when t ;; (boundp 'night/counsel--stdin)
      (progn
        (message "DBG: %s, %s" buf proc)
        ;; (process-send-string buf (or night/counsel--stdin "EMPTY STDIN"))
```
```
        (process-send-string proc (or "EMPTY STDIN"))
        (process-send-eof proc)
```
```
        ))
    (setq counsel--async-time (current-time))
    (setq counsel--async-start counsel--async-time)
    (set-process-sentinel proc (or sentinel #'counsel--async-sentinel))
    (set-process-filter proc (or filter #'counsel--async-filter))
    proc))
```

But the process does not receive the stdin ...

**Comment by basil-conto** [comment]
Evaluating the following:

```el
(let* ((process-connection-type nil)
       (filt #'internal-default-process-filter)
       (sent (lambda (proc _str)
               (and (not (process-live-p proc))
                    (buffer-live-p (process-buffer proc))
                    (with-current-buffer (process-buffer proc)
                      (message ">>> received stdin: `%s'" (buffer-string)))
                    (kill-buffer (process-buffer proc)))))
       (proc (counsel--async-command-1 '("cat" "-") sent filt "my-proc")))
  (process-send-string proc "hello, world")
  (process-send-eof proc))
```

gives me:

```
>>> received stdin: `hello, world'
```

I'm guessing you were missing the binding for `process-connection-type`.

**Comment by NightMachinary** [comment]
[**@basil-conto**](https://github.com/basil-conto) commented on [Oct 21, 2020, 7:39 PM GMT+3:30](https://github.com/abo-abo/swiper/issues/2702#issuecomment-713687125 "2020-10-21T16:09:08Z - Replied by Github Reply Comments"):
> Evaluating the following:
> 
> ```emacs
> (let* ((process-connection-type nil)
>        (filt #'internal-default-process-filter)
>        (sent (lambda (proc _str)
>                (and (not (process-live-p proc))
>                     (buffer-live-p (process-buffer proc))
>                     (with-current-buffer (process-buffer proc)
>                       (message ">>> received stdin: `%s'" (buffer-string)))
>                     (kill-buffer (process-buffer proc)))))
>        (proc (counsel--async-command-1 '("cat" "-") sent filt "my-proc")))
>   (process-send-string proc "hello, world")
>   (process-send-eof proc))
> ```
> 
> gives me:
> 
> ```
> >>> received stdin: `hello, world'
> ```
> 
> I'm guessing you were missing the binding for `process-connection-type`.

Thanks. I used a temporary file in the end, but you're probably right, as my `process-connection-type` is `t` by default which means it uses a `pty`, not a `pipe`. (I don't understand how that creates problems though, which is why I did not change it in the first place ...)

**Comment by NightMachinary** [comment]
I tried it, and it worked. Thanks! Strangely, my temporary file workaround was faster than feeding the data with `process-send-string`.
