### ISSUE TITLE
ivy-completion-in-region should not pre-filter collection

### ISSUE THREAD

**Issue by tarsius** [abo-abo/swiper#2705]
Say I want to send an email to my brother Linus and I type `lim TAB`, at which point I notice that I typed `m` instead of `n`. With regular `completion--in-region` I could just delete the `m` and be on my way but with Ivy this does not work because it pre-filters the collection and neither the name nor email of my brother contains an `m` anywhere. So I have to abort completion, delete the `m` and then restart completion.

Please change `ivy-completion-in-region` so that it behaves like default completion with regards to this. The first step appears to be to pass `""` literally to `completion-all-completions`. Some other code that deals with `start` and `end` also needs to be adjusted but I could not quite figure this part out and ended up with the initial input always being duplicated in the buffer.

**Comment by basil-conto** [comment]
See also #2391 (and possibly somewhere else that I can't remember).

**Comment by tarsius** [comment]
In case someone else runs into this...

After looking around a bit more, I am now applying this patch:

```diff
diff --git a/ivy.el b/ivy.el
index ed5f6aa..c3cfd51 100644
--- a/ivy.el
+++ b/ivy.el
@@ -2590,7 +2590,8 @@ (defun ivy-completion-in-region (start end collection &optional predicate)
                  (setq predicate nil)
                  (setq collection comps))
                (unless (derived-mode-p #'emacs-lisp-mode)
-                 (setq collection comps)
+                 ;; See https://github.com/abo-abo/swiper/issues/2705.
+                 ;; (setq collection comps)
                  (setq predicate nil))
                (ivy-read (format "(%s): " str) collection
                          :predicate predicate
```

**Comment by tarsius** [comment]
By the way, I'm thinking that the `^` injection should not be hard-coded. Wouldn't it be better to use a buffer-local variable to control this?

**Comment by basil-conto** [comment]
> By the way, I'm thinking that the `^` injection should not be hard-coded. Wouldn't it be better to use a buffer-local variable to control this?

Anything that doesn't hard-code it would be better. ;)

**Comment by tarsius** [comment]
@basil-conto Do you think you could tackle this soonish? Pretty please :hugs:

**Comment by basil-conto** [comment]
Sorry @tarsius, but I have no idea what this code is, or is meant to be, doing.  Too many ad-hoc moving parts and band-aids (and not enough Flex Tape®) have been added and removed over time for me to be able to maintain it.  Hopefully @abo-abo can have a look soon.

**Comment by tarsius** [comment]
I don't use `ivy` anymore. Can we close this? (I don't know if the issue still exist and if so whether it is likely that it will be addressed in the future.)

**Comment by basil-conto** [comment]
I doubt the underlying problem has been fixed, but feel free to close this issue if you are no longer interested in it. If and when someone becomes interested in this again, we can always create reopen or create a new issue. Thanks.
