### ISSUE TITLE
hi, this package so cool, can u add this future.

### ISSUE THREAD

**Issue by gangd0n** [abo-abo/swiper#271]
When i use "C-s" search, don't copy all result, before i seacrh sometime use "C-o", like this:
(define-key isearch-mode-map (kbd "C-o") 'isearch-occur)
I not found swiper have this future, can u add this future? And i send email for u, in email described in more detail. thks, i love this package.

**Comment by abo-abo** [comment]
The `ivy-occur` feature is in progress. If you wish only to copy all selected candidates, you can already do it with <kbd>M-w</kbd>.

**Comment by gangd0n** [comment]
Thanks, it's well done.   :)

**Comment by gangd0n** [comment]
Wow, haha. very love this package, can u make a video tutorial for swiper  again, if you have some time?

**Comment by abo-abo** [comment]
Yes, I'll make a new video at some point. In the meantime, the documentation is on [the wiki](https://github.com/abo-abo/swiper/wiki).

**Comment by gangd0n** [comment]
thanks :)
