### ISSUE TITLE
How to open in new window?

### ISSUE THREAD

**Issue by kujohn** [abo-abo/swiper#2710]
I have `projectile-find-file` getting evoked, how does one open a file in a new window?

**Comment by basil-conto** [comment]
If you're on Emacs 28, you have two built-in options:
1. `C-x 4 p` (`project-other-window-command`) followed by `f` (`project-find-file`)
   (see [bug#42210](https://debbugs.gnu.org/42210))
2. `C-x 4 4` (`other-window-prefix`) followed by `C-x p f` (`project-find-file`)

Both `project-other-window-command` and `other-window-prefix` have corresponding "other frame" and "other tab" counterparts.

On older versions of Emacs, you'll have to install `project >= 0.5.1` from https://elpa.gnu.org, or write a custom command.

Either way, unless you're asking for a Counsel wrapper (what would it provide over the built-in defaults?), I don't see the relevance to Ivy.

**Comment by basil-conto** [comment]
Oops sorry, I misread your question. I thought you were talking about the built-in `project.el` (which I recommend over `projectile`, if it addresses your needs), not `projectile`.

For `projectile` integration, there is a separate third-party package [`counsel-projectile`](https://github.com/ericdanan/counsel-projectile).
