### ISSUE TITLE
counsel-fzf wrong type argument

### ISSUE THREAD

**Issue by veridiam** [abo-abo/swiper#2711]
when calling counsel-fzf i get this error message:

`find-file-noselect: Wrong type argument: stringp, nil`

any ideas? nothing crazy in my init.el. using Emacs 27.1, Windows

**Comment by yuanchen-zhu** [comment]
I am experiencing the same thing on Emacs 29.3 on Windows. Could we reopen the issue? (Why is it closed in the first place?) Here is the call stack.

```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  expand-file-name(nil)
  find-file-noselect(nil nil nil nil)
  find-file(nil)
  counsel-fzf-action(nil)
  ivy-call()
  ivy-read("fzf: " counsel-fzf-function :initial-input nil :re-builder ivy--regex-fuzzy :dynamic-collection t :action counsel-fzf-action :caller counsel-fzf)
  counsel-fzf(nil nil)
  funcall-interactively(counsel-fzf nil nil)
  command-execute(counsel-fzf record)
  counsel-M-x-action("counsel-fzf")
  ivy-call()
  ivy-read("M-x " ("toggle-debug-on-error" "counsel-faces" "counsel-mark-ring" "counsel-recentf" "yz/hardwrap-config" "customize-option" "list-packages" "grep" "customize-group" "compilation-mode" "comment-region" "load-theme" "set-frame-font" "kill-emacs" "ispell-buffer" "occur" "flyspell-mode" "revert-buffer" "auto-fill-mode" "prettify-symbols-mode" "customize-themes" "customize-face" "shell" "font-lock-fontify-buffer" "company-bibtex" "text-mode" "markdown-mode" "customize-variable" "set-variable" "LaTeX-mode" "fill-region" "company-mode" "recover-this-file" "visual-line-mode" "delete-trailing-whitespace" "align-current" "org-indent-mode" "package-autoremove" "rst-mode" "toggle-truncate-lines" "wc-mode" "grep-find" "glasses-mode" "ispell-region" "toggle-menu-bar-mode-from-frame" "hide-other" "indent-region" "org-mode" "refill-mode" "clang-format-buffer" ...) :predicate counsel--M-x-externs-predicate :require-match t :history counsel-M-x-history :action counsel-M-x-action :keymap (keymap (67108908 . counsel--info-lookup-symbol) (67108910 . counsel-find-symbol)) :initial-input nil :caller counsel-M-x)
  counsel-M-x()
  funcall-interactively(counsel-M-x)
  command-execute(counsel-M-x)
```

**Comment by basil-conto** [comment]
How does `counsel-fzf-action` end up getting a `nil` argument?
On my GNU/Linux system, I tried in an empty directory, and with subdirectories for which I don't have the required permissions, and I can't seem to get a `nil` candidate.
I also tried selecting a candidate without exiting completion.

Perhaps you can describe in more detail the steps you take that lead to the error: what precise keys/commands do you invoke, and what do you see at each point.
Could you run the same `fzf` command in the shell (without going through `counsel-fzf`), and compare its output and exit code?  Are any errors or warnings apparent?

> Could we reopen the issue? (Why is it closed in the first place?)

Feel free to open a new issue.
