### ISSUE TITLE
Add action for open counsel candidate in other window

### ISSUE THREAD

**Issue by dam5h** [abo-abo/swiper#2712]
I have been trying to create this myself by piecing together a couple existing methods but don't think I know enough of the implementation to pull it off correctly and I know very little elisp.   Overall I am really liking `Ivy` coming from `Helm` but there is one use case that is still missing for me.

Simple use case.  I would like to use `counsel-rg` or `grep` , `ag` , etc. to find a match but then instead of opening the candidate in the current window, I would like to open it in `other-window`.  There is already an action for this on related to finding files and buffers which is bound to `M-o` `j`.  But there is nothing that exists as far as I can tell to do this when searching text within files, such as `counsel-rg`.

I added this to my config, but of course it doesn't work as it takes the whole candidate text as the buffer name, so it goes to `other-window` and opens a file that's name is the full `ivy-text`.

```
  (ivy-set-actions
   'counsel-rg
   '(("j"
      ivy--switch-buffer-other-window-action
      "other window")))
```
I can see from this code that this method doesn't call `string-match` to get the filename out, you need to already have the filename.
```
(defun ivy--switch-buffer-other-window-action (buffer)
  "Switch to BUFFER in other window.
BUFFER may be a string or nil."
  (if (zerop (length buffer))
      (switch-to-buffer-other-window ivy-text)
    (let ((virtual (assoc buffer ivy--virtual-buffers)))
      (if (and virtual
               (not (get-buffer buffer)))
          (find-file-other-window (cdr virtual))
        (switch-to-buffer-other-window buffer)))))
```
I then went looking for the method used to strip the filename out of the candidate string and open said file:
```

(defun counsel-grep-action (x)
  "Go to candidate X."
  (with-ivy-window
    (swiper--cleanup)
    (let ((default-directory
           (file-name-directory
            (ivy-state-directory ivy-last)))
          file-name line-number)
      (when (cond ((string-match "\\`\\([0-9]+\\):\\(.*\\)\\'" x)
                   (setq file-name (buffer-file-name (ivy-state-buffer ivy-last)))
                   (setq line-number (match-string-no-properties 1 x)))
                  ((string-match "\\`\\([^:]+\\):\\([0-9]+\\):\\(.*\\)\\'" x)
                   (setq file-name (match-string-no-properties 1 x))
                   (setq line-number (match-string-no-properties 2 x))))
        ;; If the file buffer is already open, just get it. Prevent doing
        ;; `find-file', as that file could have already been opened using
        ;; `find-file-literally'.
        (with-current-buffer (or (get-file-buffer file-name)
                                 (find-file file-name))
          (setq line-number (string-to-number line-number))
          (if (and counsel--grep-last-pos (= (point) (car counsel--grep-last-pos)))
              (forward-line (- line-number (cdr counsel--grep-last-pos)))
            (goto-char (point-min))
            (forward-line (1- line-number)))
          (setq counsel--grep-last-pos (cons (point) line-number))
          (when (re-search-forward (ivy--regex ivy-text t) (line-end-position) t)
            (when swiper-goto-start-of-match
              (goto-char (match-beginning 0))))
          (run-hooks 'counsel-grep-post-action-hook)
          (if (eq ivy-exit 'done)
              (swiper--ensure-visible)
            (isearch-range-invisible (line-beginning-position)
                                     (line-end-position))
            (swiper--add-overlays (ivy--regex ivy-text))))))))
```
Given that I want to open the buffer in the other window, but also go directly to the candidate, I don't think this is abstracted enough to just combine these functions and I need a new one with pieces of both.  Given I know next to no elisp and this is a somewhat useful workflow I figured I would come here to seek advice.  Thanks!

**Comment by dalanicolai** [comment]
Well if you `counsel-rg` then using `C-h C-f counsel-rg` you will see it uses `counsel-ag`. Then checking `counsel-ag` you will see its action is `counsel-git-grep-action`. So in that function you can just change `find-file` to `find-file-other-window`. And add it as an action to `counsel-rg`:
```
(defun counsel-git-grep-action-other-window (x)
  "Go to occurrence X in current Git repository."
  (when (string-match "\\`\\(.*?\\):\\([0-9]+\\):\\(.*\\)\\'" x)
    (let ((file-name (match-string-no-properties 1 x))
          (line-number (match-string-no-properties 2 x)))
      (find-file-other-window (expand-file-name
                  file-name
                  (ivy-state-directory ivy-last)))
      (goto-char (point-min))
      (forward-line (1- (string-to-number line-number)))
      (when (re-search-forward (ivy--regex ivy-text t) (line-end-position) t)
        (when swiper-goto-start-of-match
          (goto-char (match-beginning 0))))
      (swiper--ensure-visible)
      (run-hooks 'counsel-grep-post-action-hook)
      (unless (eq ivy-exit 'done)
        (swiper--cleanup)
        (swiper--add-overlays (ivy--regex ivy-text))))))

(ivy-set-actions
 'counsel-rg
 '(("j" counsel-git-grep-action-other-window "other-window")))
```

**Comment by basil-conto** [comment]
> instead of copying the function code and replacing `find-file` you could also just advice the function:

Make sure to clean up invasive advice like this in case of error/quit using `unwind-protect`, and name your functions such that they won't clash with other packages, e.g. using the `my-` prefix.

More importantly, you don't need advice at all, since `find-file` obeys the `display-buffer` system; see [`(info "(emacs) Displaying Buffers")`](https://www.gnu.org/software/emacs/manual/html_node/emacs/Displaying-Buffers.html) and its subnodes. For example:

```el
(defun my-counsel-git-grep-action (x)
  "Like `counsel-git-grep-action', but use another window."
  (let ((display-buffer-overriding-action '(() (inhibit-same-window . t))))
    (counsel-git-grep-action x)))

(ivy-set-actions
 'counsel-rg
 '(("j" my-counsel-git-grep-action "other window")))
```

**Comment by dam5h** [comment]
Awesome!  Thank you both!  I did not know about this `advice` concept or the `display-buffer` system.  I added the most recent action and I can say that it does exactly what I want.  This was the last thing I missed from Helm, overall I much prefer Ivy, it seems way snappier and is a more pleasant experience imho.  Nice work!
