### ISSUE TITLE
Pasting windows dir to minbuffer jumps to root

### ISSUE THREAD

**Issue by swhahn** [abo-abo/swiper#272]
If pasting a windows like path, e.g. d:/dir1/dir2/, into ivy (perhaps if using ivy for find-file),
then ivy switches to d:/ and empties minibuffer.

My use case is having a dired open, trying to copy or move a file to another directory. Having
the destination directory in kill-ring, I want yank it into minibuffer (with ivy dialog).

Following change will work:

```
diff --git a/ivy.el b/ivy.el
index ead3742..dbee5e2 100644
--- a/ivy.el
+++ b/ivy.el
@@ -1479,7 +1479,7 @@ (defun ivy--exhibit ()
                               (string-match "\\`[[:alpha:]]:/" default-directory))
                          (ivy--cd (match-string 0 default-directory))
                        (ivy--cd "/")))
-                   (when (string-match "[[:alpha:]]:/" ivy-text)
+                   (when (string-match "[[:alpha:]]:/$" ivy-text)
                      (let ((drive-root (match-string 0 ivy-text)))
                        (when (file-exists-p drive-root)
                          (ivy--cd drive-root)))))
```

With this, pasting d:/dir1/dir2/ to ivy switches to d:/dir1/dir2/.
Inserting d:/ switches as before to d:/.

**Comment by abo-abo** [comment]
Thanks.

@glucas could you check this change?

**Comment by glucas** [comment]
Just updated and tried this out -- things look good.
