### ISSUE TITLE
finding files with ivy, '~' shouldn't insert '/', should allow other usernames

### ISSUE THREAD

**Issue by jferguson-gnubio** [abo-abo/swiper#273]
Ivy doesn't allow the form '~otheruser/foo/bar', not least because it auto-inserts the '/' after '~'.

I think it would be much better if it did not auto-insert '/', and it accepted the '~user/' form.

Thanks!

**Comment by abo-abo** [comment]
> I think it would be much better if it did not auto-insert '/', and it accepted the '~user/' form.

This is a rather obscure feature - I had no idea it existed in bash. Also `ido-mode` doesn't support it.

What you want to do can be accomplished with <kbd>~ DEL</kbd>.

I can make a customization that would have <kbd>~</kbd> behave as <kbd>~ DEL</kbd>, but I think that would ultimately hamper your productivity, as long as you want your own home directory >50% of the time.

For now, try changing `(expand-file-name "~/")` to `(expand-file-name "~/../")` in ivy.el. If that's the setting that you like, I can make it customizable.

**Comment by abo-abo** [comment]
Closing a timed out issue. In the current state, no changes are warranted to the code.
