### ISSUE TITLE
How to make (counsel-switch-buffer) to only show specific buffers in a tab-bar-mode frame?

### ISSUE THREAD

**Issue by grolongo** [abo-abo/swiper#2733]
Hello, I use this function in my init.el to connect to an IRC server in a specific tab:

```elisp
(defun my/freenode-erc ()
  "Create a new tab and connect to Freenode using TLS."
  (interactive)
  (tab-new)
  (tab-rename "ERC: Freenode")
  (erc-tls :server "irc.freenode.net" :port 7070 :nick "grolongo"))
```

How can I make it so when I'm under this tab and do `C-x b` to switch buffers, it only shows buffers of channels related to the IRC server I'm connected to, instead of presenting all the buffers of the Emacs session like it is by default?

**Comment by grolongo** [comment]
After thinking about it a bit more, an easiest way of doing this would be to automatically start filtering #channels buffers by adding a hashtag at the input line when using counsel-switch-buffer when I'm under an ERC tab, and hide all ERC #channels when I'm not under any ERC tab. Hope that makes sense.

**Comment by grolongo** [comment]
Alright, after some searching and tweaking I figured it out thanks to @basil-conto in this reply from 2017: https://github.com/abo-abo/swiper/issues/1206#issuecomment-345455888

```elisp
(defun my/ignore-erc-buffers (str)
  "Return non-nil if STR names an ERC buffer.
This function is intended for use with `ivy-ignore-buffers'."
  (if (not (eq major-mode 'erc-mode))
      (let ((buf (get-buffer str)))
        (and buf (eq (buffer-local-value 'major-mode buf) 'erc-mode)))))

(defun my/ignore-all-but-erc-buffers (str)
  "Return non-nil if STR names anything but an ERC buffer.
This function is intended for use with `ivy-ignore-buffers'."
  (if (eq major-mode 'erc-mode)
      (let ((buf (get-buffer str)))
        (and buf (not (eq (buffer-local-value 'major-mode buf) 'erc-mode))))))

(with-eval-after-load 'ivy
  (add-to-list 'ivy-ignore-buffers #'my/ignore-erc-buffers)
  (add-to-list 'ivy-ignore-buffers #'my/ignore-all-but-erc-buffers))
```

To resume what this does:
First function hides all ERC buffers in the `(counsel-switch-buffer)` list, if the current buffer major mode is not `erc-mode`.
Second function hides all buffers in the `(counsel-switch-buffer)` list that don't have `erc-mode` as their major mode, only if called from a current buffer with `erc-mode` as it's major mode.

This is all I wanted.

I'll keep this issue open 2-3 days more in case someone has a better solution or some suggestion then I will close.

**Comment by basil-conto** [comment]
I think you can simplify the duplication across two predicates into one:

```el
(defun my/ignore-erc-buffers (str)
  "Return non-nil if STR names a buffer that should be ignored.
Ignored buffers are those in `erc-mode' when the current buffer
is also in `erc-mode'.  Intended for use with
`ivy-ignore-buffers'."
  (let ((buf (get-buffer str)))
    (and buf (xor (eq major-mode 'erc-mode)
                  (eq (buffer-local-value 'major-mode buf) 'erc-mode)))))

(with-eval-after-load 'ivy
  (add-to-list 'ivy-ignore-buffers #'my/ignore-erc-buffers))
```

If you are on an Emacs version older than 27, you will also need:

```el
;; For Emacs versions < 27
(autoload 'xor "array")
```

**Comment by grolongo** [comment]
Shorter and works as fine. Thank you.
