### ISSUE TITLE
Swiper preselect wrong with ivy-initial-inputs-alist

### ISSUE THREAD

**Issue by wykurz** [abo-abo/swiper#2737]
I'm using the solution proposed [here](https://github.com/abo-abo/swiper/issues/1068):
```lisp
(defun ivy-with-thing-at-point (cmd)
  (let ((ivy-initial-inputs-alist
         (list
          (cons cmd (thing-at-point 'symbol)))))
    (funcall cmd)))

(defun swiper-thing-at-point ()
  (interactive)
  (ivy-with-thing-at-point 'swiper))

(global-set-key (kbd "M-s") 'swiper-thing-at-point)
```

This used to work great for me but recently it has an issue that swiper-thing-at-point always takes me to the last thing found in the searched file. E.g.:

file:
```
1. foo
2. foo # <- cursor here
3. foo
4. foo
5. foo 
```
Repro:
- Press `M-s` 
- This take me from line 2 to `foo` at line 5!

My emacs version is 26.3, I'm using swiper version 0.13.

**Comment by wykurz** [comment]
Just tested with emacs 27.1 and swiper 20200503.1102 and it's still the same...

**Comment by basil-conto** [comment]
Thanks, but I can't reproduce this (see version info at the end).  Here's what I tried:

1. `emacs -Q`
2. `M-x package-initialize RET`
3. ```el
   (defun ivy-with-thing-at-point (cmd)
     (let ((ivy-initial-inputs-alist
            (list
             (cons cmd (thing-at-point 'symbol)))))
       (funcall cmd)))

   (defun swiper-thing-at-point ()
     (interactive)
     (ivy-with-thing-at-point 'swiper))

   (global-set-key (kbd "M-s") 'swiper-thing-at-point)
   ```
4. `M-x eval-buffer RET`
5. `C-x b foo RET`
6. `F3 foo RET F4 M-4 F4`
7. `M-g g 2 RET`
8. `M-s RET M-s RET`

In both invocations of `M-s`, point remains on line 2.  What am I missing?  Can you try a more recent version of Swiper?

---

`swiper-20201002`

---

In GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, X toolkit, cairo version 1.16.0, Xaw3d scroll bars)
 of 2020-11-29 built on thunk
Repository revision: 41c338474dd1e086494337fd18ec8828cef1a75c
Repository branch: master
Windowing system distributor 'The X.Org Foundation', version 11.0.12008000
System Description: Debian GNU/Linux bullseye/sid

Configured using:
 'configure 'CC=ccache gcc' 'CFLAGS=-O2 -march=native' --config-cache
 --prefix=/home/blc/.local --with-x-toolkit=lucid
 --with-file-notification=yes --with-x'

Configured features:
XAW3D XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB
NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT
LIBOTF ZLIB TOOLKIT_SCROLL_BARS LUCID X11 XDBE XIM MODULES THREADS
LIBSYSTEMD JSON PDUMPER LCMS2

Important settings:
  value of $LANG: en_IE.UTF-8
  value of $XMODIFIERS: @im=ibus
  locale-coding-system: utf-8-unix

---

In GNU Emacs 27.1.50 (build 7, x86_64-pc-linux-gnu, X toolkit, cairo version 1.16.0, Xaw3d scroll bars)
 of 2020-12-01 built on thunk
Repository revision: 3e6525d69f0de68fe2305f8e2102c8a5ce42f671
Repository branch: emacs-27
Windowing system distributor 'The X.Org Foundation', version 11.0.12008000
System Description: Debian GNU/Linux bullseye/sid

Configured using:
 'configure 'CC=ccache gcc' 'CFLAGS=-O0 -g3 -ggdb -gdwarf-4'
 --config-cache --prefix=/home/blc/.local --program-suffix=27
 --enable-checking=yes,glyphs --enable-check-lisp-object-type
 --with-x-toolkit=lucid --with-file-notification=yes --with-x
 --with-cairo'

Configured features:
XAW3D XPM JPEG TIFF GIF PNG RSVG CAIRO SOUND GPM DBUS GSETTINGS GLIB
NOTIFY INOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT
LIBOTF ZLIB TOOLKIT_SCROLL_BARS LUCID X11 XDBE XIM MODULES THREADS
LIBSYSTEMD JSON PDUMPER LCMS2 GMP

Important settings:
  value of $LANG: en_IE.UTF-8
  value of $XMODIFIERS: @im=ibus
  locale-coding-system: utf-8-unix

---

In GNU Emacs 26.3 (build 1, x86_64-pc-linux-gnu, X toolkit, Xaw3d scroll bars)
 of 2020-04-26 built on thunk
Windowing system distributor 'The X.Org Foundation', version 11.0.12008000
System Description:	Debian GNU/Linux bullseye/sid

Configured using:
 'configure 'CFLAGS=-O2 -march=native' --prefix=/home/blc/.local
 --program-suffix=26 --with-x-toolkit=lucid --with-file-notification=yes
 --with-x --with-modules'

Configured features:
XAW3D XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS
GLIB NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT
ZLIB TOOLKIT_SCROLL_BARS LUCID X11 XDBE XIM MODULES THREADS LIBSYSTEMD
LCMS2

Important settings:
  value of $LANG: en_IE.UTF-8
  value of $XMODIFIERS: @im=ibus
  locale-coding-system: utf-8-unix

**Comment by wykurz** [comment]
Hi @basil-conto , I thank you for looking into it!

It looks like my repro wasn't good, apologies for that! I should have verified it works. Somehow this behavior appears to depend on the contents of the file! However it is triggered very easily for anything that is not completely artificial, like my example was.

Anyway, here is a more complex (but still simple) example where this fails: 
```rust
struct Args {
    #[structopt(parse(from_os_str))]
    out_dir: std::path::PathBuf,

    #[structopt()]
    path: String,

    #[structopt()]
    datetime_start: String,

    #[structopt()]
    datetime_end: String,

    #[structopt(long = "name-format", default_value = "%Y%m%d.%H")]
    name_format: String,

    #[structopt(long = "suffix", default_value = ".json.gz")]
    suffix: String,
}
```

Then put the cursor on the first `String` and for me it then goes all the way to the last one.

I experimented with editing this file and seeing what triggers this behavior - it looks to be related to how close to the beginning of the file the first occurrence of the searched string happens. Specifically - if the first `foo` is on line 3 then my cursor will be shifted by 3 places down. See this example:
```
bar
bar
bar
bar
foo
foo
foo
foo
foo
foo
foo
```

Then place the cursor on the first `foo` and `M-s` - this takes me to the 4th `foo`.

I have also experimented with reducing my .emacs file to just the IVY set but I'm still seeing the same behavior. I also tried with the most recent swiper I could get from Melpa but had the same issue.

Could you please try the new repro and let me know if you see this issue? Thank you!

**Comment by basil-conto** [comment]
Thanks, I can reproduce it now.

> I experimented with editing this file and seeing what triggers this behavior - it looks to be related to how close to the beginning of the file the first occurrence of the searched string happens. Specifically - if the first `foo` is on line 3 then my cursor will be shifted by 3 places down.

Yes, that's because `swiper` is calling `ivy-read` with a `:preselect` index corresponding to the current line number. The bug here is that this index is used on the filtered candidate list (using the `initial-input`), rather than the complete list (see `ivy--filter`).

The easy workaround is to pass the `initial-input` to `swiper` directly, rather than putting it on `ivy-initial-inputs-alist`:

```el
(defun my-swiper-symbol-at-point ()
  (interactive)
  (swiper (thing-at-point 'symbol)))

(global-set-key (kbd "M-s") 'my-swiper-symbol-at-point)
```

The hard solution involves you, @abo-abo, or someone else looking into this bug, because the interplay between Ivy and Swiper is a tangled mess and I value my sanity, or what little of it is left. ;)

**Comment by wykurz** [comment]
Awesome, thank you!

When trying your solution I accidentally mistyped the name of your function and had my key-binding for the "old one", and it worked! This made me realize swiper now implements this exact functionality natively - see [here](https://github.com/abo-abo/swiper/blob/master/swiper.el#L578)!

Sorry, I feel bad now for raising this, however I didn't see news of this being done mentioned anywhere. I'll update the other discussion we had with this info so others can use it too.

Thank you for your help, much appreciated!

**Comment by wykurz** [comment]
This is working now.

**Comment by basil-conto** [comment]
> Sorry, I feel bad now for raising this

You shouldn't, because as far as I'm concerned there's still a bug here - that `swiper` cannot be customised via `ivy-initial-inputs-alist`.  So I would be inclined to reopen this or submit a new bug report.
