### ISSUE TITLE
bug: counsel-org-files does not show attachments

### ISSUE THREAD

**Issue by snowman** [abo-abo/swiper#2742]
https://github.com/abo-abo/swiper/blob/066ed7bd1f6d6070258e1b1d703350bc23286057/counsel.el#L3789-L3808

The regexp pattern `"^:\\(ATTACH_DIR\\|ID\\):[\t ]+\\(.*\\)$"` does not match below:

```org
* attachments demo                                                                            :ATTACH:
  :PROPERTIES:
  :ID:       ac752e7f-2529-4447-83a0-560ee585e061
  :END:
```

**Comment by basil-conto** [comment]
Thanks. Could you please check whether PR #2745 fixes the issue?

**Comment by snowman** [comment]
I download the latest `counsel.el` file and then `eval-buffer`, it works!

**Comment by basil-conto** [comment]
Does that mean the fix in #2745 is not needed?

**Comment by snowman** [comment]
not, it's needed. :), I was thinking it solves the problem, then I should close this issue.

**Comment by basil-conto** [comment]
No bother, thanks for confirming.
