### ISSUE TITLE
ivy-immediate-done discards directory path

### ISSUE THREAD

**Issue by rudolfochrist** [abo-abo/swiper#275]
Hi there,

I think i found a bug in that `ivy-immediate-done` discards the directory path. The following concrete example should clarify my problem:

I have my newsrc file under `~/Dropbox/dotfiles/newsrc`. In `dired` I'd like to create a symlink for my newsrc file under `~/.newsrc`. What I've done was typing <kbd>S</kbd> to create a symlink in `dired`. In the minibuffer I typed `~` for my home directory (`ivy` feature) and entered `.newsrc` as the symlink's name. However, I've already got `~/.newsrc.eld` and this get presented as candidate by `ivy`. When I now press <kbd>C-u C-j</kbd> for `ivy-immediate-done` the symlink gets created in the current directory (in the concrete case `~/Dropbox/dotfiles`) instead of being created in my home directory.  

Somewhere inbetween of `ivy` and `dired` the directory path gets lost.

Best wishes,

-- Sebastian

**Comment by abo-abo** [comment]
Good catch. Thanks a lot.

**Comment by rudolfochrist** [comment]
That was fast. You're awesome. Thank you for fixing this. :+1:
