### ISSUE TITLE
counsel-ag restrict to file types doesn't work anymore

### ISSUE THREAD

**Issue by bbo2adwuff** [abo-abo/swiper#2753]
Limiting ag to certain file types seems to be broken.

### Expected behaviour:
When using `C-u` `counsel-ag` I used to be able to just type ag's file types restrictions.

### How to reproduce:
1. `C-u` `counsel-ag`
2. Select folder by `<RET>`
3. Now search term can be entered.

As you can see only location can be selected but not file type filter.

**Comment by basil-conto** [comment]
You should now be able to include the file type filter as part of the search string. From a checkout of this repo:

1. `C-u M-x counsel-ag RET`
2. `doc RET`
3. `--elisp -- ivy`

This returns results for "ivy" only from `doc/ivy-ox.el`.

**Comment by bbo2adwuff** [comment]
Ah perfect! Thanks!
Couldn't find it in the help of `counsel-ag`.
Nice that it also works with other arguments, like `--ignore` etc.
