### ISSUE TITLE
ivy-read-action hydra doesn't exit after calling ivy-done, it hides itself and continues to trap user input

### ISSUE THREAD

**Issue by AloisJanicek** [abo-abo/swiper#2759]
When setting `(setq ivy-read-action-format-function #'ivy-hydra-read-action)`

**Steps to reproduce:**
1. call `counsel-recentf`
2. `M-o` on the desired candidate
3. chose `j` "other window" action on desired candidate
4. [files opens, hydra disappears, user input remains trapped]
5. pressing `j` to navigate one line down in newly opened file leads to **complete buffer content deletion** with an error:
```
ivy--done: No catch for tag: exit, nil
```
6. pressing any other key which is not listed in the teal ivy-actions hydra leads to:
```
An amaranth Hydra can only exit through a blue head
```

Unless user press some of the keys specified in `ivy-dispatching-done-hydra-exit-keys` or some of the head keys, user input remains trapped while hydra is nowhere to see. This is very confusing.

I verified this behavior on vanilla-ish ([init.el](https://gist.github.com/AloisJanicek/24db14e72fa59937bdd43b24615e724e)) emacs 27.1 setup.

**Comment by basil-conto** [comment]
Any chance of a reproduction recipe starting from `emacs -Q` or `make plain`? Is the bug specific to `counsel-recentf`, or can you also reproduce it with e.g. `counsel-find-file`, which also has `find-file-other-window` bound to the `j` action?

I tried the following:
1. `emacs -Q`
2. `(setq ivy-read-action-format-function #'ivy-read-action-format-columns) C-j`
3. `M-x package-initialize RET`
4. `M-x counsel-find-file RET ~/.emacs.d/init.el M-o j C-n`

This visits my `user-init-file` in a second window without issue. So more details would be welcome. TIA.

**Comment by AloisJanicek** [comment]
Oh sorry for misleading you, of course I meant `ivy-hydra-read-action`.
`ivy-read-action-format-columns` is working fine.

I am able to reproduce it with `counsel-find-file` and `j` other window action in `HOME=/tmp/asdf emacs -Q` session **if** I enable MELPA and install `counsel`, `hydra` and `ivy-hydra` from there. If I stay with ELPA, issues doesn't occur. Interesting.

**Comment by basil-conto** [comment]
> `(setq ivy-read-action-format-function #'ivy-hydra-read-action)`

Shouldn't you be setting `ivy-read-action-function` instead?

**Comment by AloisJanicek** [comment]
> Shouldn't you be setting `ivy-read-action-function` instead?

Of course I should!
I apologize again for the confusion.
Thank you for your help, it works now.

```
(setq ivy-read-action-function #'ivy-hydra-read-action)
(setq ivy-read-action-format-function #'ivy-read-action-format-columns)
```

**Comment by basil-conto** [comment]
No worries! Thanks for confirming.
