### ISSUE TITLE
ivy matches are highlighted incorrectly when swiper isn't loaded

### ISSUE THREAD

**Issue by fjl** [abo-abo/swiper#276]
Ever since the fancy display style was introduced and made the default,
I noticed that highlighting the current line didn't work sometimes.  Most of my editing sessions
begin by typing <kbd>C-x b</kbd> to switch to a (virtual) buffer that I was working
on the day before. Just today I noticed that highlighting starts working as soon as
swiper.el is (auto) loaded. 

It does seem to work out of the box (without swiper loaded) when the default theme is
used. In my config, I set colors using a theme and that seems to trigger the bug.

There are a couple of ways to fix this, but I'm not sure what the right one would be;

* Rename all `swiper-minibuffer-match-face*` to `ivy-match-face*` and move them to ivy.el.
  This feels like the right thing to do because ivy depending on swiper is, ahem, a bit circular anyway.
* Move the `defface` forms into a new file, swiper-faces.el, which is then `require`d by both swiper.el and ivy.el.
* Just move them to ivy.el.

**Comment by abo-abo** [comment]
Thanks.

**Comment by fjl** [comment]
Thank you too! Can confirm that the fix works.
