### ISSUE TITLE
sorting function and strings

### ISSUE THREAD

**Issue by seblemaguer** [abo-abo/swiper#2763]
Hello,

I am currently facing the issue described in https://github.com/raxod502/prescient.el/issues/73

As it causes me a lot of trouble lately, I would like to try to fix this. However, before I go further, I would like to know what is your approach concerning the items: should I consider that items passed to the sorting function should be strings or can be anything?

Thanks

**Comment by basil-conto** [comment]
Unfortunately, third-party completion "frontends" (including Ivy) seem to define their own notions of sorting.

The standard means of sorting completion candidates are the metadata `display-sort-function` and `cycle-sort-function` (see [`(info "(elisp) Programmed Completion")`](https://www.gnu.org/software/emacs/manual/html_node/elisp/Programmed-Completion.html)), each of which accepts a list of completion strings. But I don't even know how well Ivy handles these, let alone other completion frontends.

Ivy provides two user options for customising sorting: `ivy-sort-functions-alist` and `ivy-sort-matches-functions-alist`. Sorting functions in the former take two arguments (as with the built-in `sort` function) and return `nil` or non-`nil` depending on which argument should come first. Functions in the latter take a string and a list of candidates containing that string and return the list of candidates in the desired order.

Functions in `ivy-sort-functions-alist` have to support the different types of completion collections they might be used for. For example, the default Ivy sort function `ivy-string<` is like `string<` but handles both strings and cons cells as arguments.

I don't know what Prescient does, so without a backtrace of the error you run into, I can't say more. HTH.

**Comment by seblemaguer** [comment]
I see. Thanks for the answer. I have a look to see if I can get something minimal which makes sense as I am not sure that the current backtrace will be useful.

**Comment by seblemaguer** [comment]
I actually switch to something else. So I won't have time to deal with this issue. I close it for now but if someone else wants to solve it I am interested in the solution
