### ISSUE TITLE
(ivy-mode nil) resets completing-read-function

### ISSUE THREAD

**Issue by aspiers** [abo-abo/swiper#2765]
Currently I like to use ivy for some things and selectrum for others; however I have spotted an instance where they don't play nice together:

`(selectrum-mode 1)` sets `completing-read-function` to `selectrum-completing-read`, which is required for selectrum to work properly.  Unfortunately `(ivy-mode nil)` will reset `completing-read-function` to `completing-read-default`, which breaks selectrum or any other selection package which relies on altering `completing-read-function`.

selectrum actually takes great care not to stomp over global variables when disabling itself, by saving any values before overwriting them when enabling its minor mode, and then restoring them when disabling:

```elisp
  (define-minor-mode selectrum-mode
    "Minor mode to use Selectrum for `completing-read'."
    :global t
    (if selectrum-mode
        (progn
          ;; Make sure not to blow away saved variable values if mode
          ;; is enabled again when already on.
          (selectrum-mode -1)
          (setq selectrum-mode t)
          (setq selectrum--old-completing-read-function
                (default-value 'completing-read-function))
          (setq-default completing-read-function
                        #'selectrum-completing-read)
          (setq selectrum--old-read-buffer-function
                (default-value 'read-buffer-function))
          (setq-default read-buffer-function
                        #'selectrum-read-buffer)
          (setq selectrum--old-read-file-name-function
                (default-value 'read-file-name-function))
          (setq-default read-file-name-function
                        #'selectrum-read-file-name)
          (setq selectrum--old-completion-in-region-function
                (default-value 'completion-in-region-function))
          (when selectrum-complete-in-buffer
            (setq-default completion-in-region-function
                          #'selectrum-completion-in-region))
          ...
```

I think it would be helpful if ivy extended the same courtesy.

**Comment by basil-conto** [comment]
>  Unfortunately `(ivy-mode nil)` will reset `completing-read-function` to `completing-read-default`

That can't be right. All well-behaved major and minor modes interpret their optional argument (which defaults to `nil`) as meaning to enable the mode.  Indeed, if you call `(ivy-mode nil)`, which is identical to `(ivy-mode)`, starting from `emacs -Q`, this will result in `ivy-mode` being enabled.

I'm therefore guessing that you're using some Customize feature instead.

> selectrum actually takes great care not to stomp over global variables when disabling itself, by saving any values before overwriting them when enabling its minor mode, and then restoring them when disabling

I don't think this works in all cases (since `completing-read-function` & co. can legitimately be changed in-between enabling and disabling a given mode, but maybe it's indeed better than what Ivy currently does.

I still find it strange to expect different modes that modify the same global variables to be enabled at the same time, though, in particular with a frontend as invasive as Ivy in every other aspect.

**Comment by aspiers** [comment]
[**@basil-conto**](https://github.com/basil-conto) commented on [December 17, 2020 12:41 AM](https://github.com/abo-abo/swiper/issues/2765#issuecomment-747128867 "2020-12-17T00:41:59Z - Replied by Github Reply Comments"):
> > Unfortunately `(ivy-mode nil)` will reset `completing-read-function` to `completing-read-default`
> 
> That can't be right. All well-behaved major and minor modes interpret their optional argument (which defaults to `nil`) as meaning to enable the mode, not disable it. Indeed, if you call `(ivy-mode nil)`, which is identical to `(ivy-mode)`, starting from `emacs -Q`, this will result in `ivy-mode` being enabled.
> 
> I'm therefore guessing that you're using some Customize feature instead.

Sorry, I meant `(ivy-mode -1)`.  Yes you're right, I had `'(ivy-mode nil)` in my custom variables, and incorrectly assumed that that translated verbatim to the function call.
 
> > selectrum actually takes great care not to stomp over global variables when disabling itself, by saving any values before overwriting them when enabling its minor mode, and then restoring them when disabling
> 
> I don't think this works in all cases (since `completing-read-function` & co. can legitimately be changed in-between enabling and disabling a given mode), but maybe it's indeed better than what Ivy currently does.

Good point, and agreed that while not perfect it's better than not trying at all.

> I still find it strange to expect different modes that modify the same global variables to be enabled at the same time, though, in particular with a frontend as invasive as Ivy in most respects.

Ah OK, thank you for helping me clarify my thoughts.  I agree that it probably does not make sense to expect the following sequence to do something sane:

- `M-x ivy-mode` (switching ivy on)
- `M-x selectrum-mode` (switching selectrum on)
- `M-x ivy-mode` (switching ivy off)

However the problem I saw was that the mere presence of `'(ivy-mode nil)` in my `custom.el` broke the config I had elsewhere to enable selectrum, by reverting `completing-read-function` to `completing-read-default`.

**Comment by basil-conto** [comment]
Could you please check whether commit 721a3b7980897b6a8ade7b91a2daceefd3e04f8d improves the situation?

**Comment by aspiers** [comment]
Yes it does, thanks very much indeed!
