### ISSUE TITLE
customize db path used by counsel-locate

### ISSUE THREAD

**Issue by kfiz** [abo-abo/swiper#2766]
When calling `counsel-locate` I need to specify a custom location for `locate` to look for its db. Currently as far as I know the only option to customize the call to locate as initiated by `counsel-locate` is to select different executables, i.e. mdfind, es or whether regex are used or not. I think an extra option like `locate-make-command-line` from `locate.el` would help unless there is some other way, that I'm currently not aware of. Setting `counsel-locate-db-path` doesn't really help either, because this doesn't affect the database selection of `locate`.

**Comment by basil-conto** [comment]
> Currently as far as I know the only option to customize the call to locate as initiated by `counsel-locate` is to select different executables, i.e. mdfind, es or whether regex are used or not.

You can customise `counsel-locate-cmd` to a custom function, no? I've now made this more explicit in commit c76d79715f8bb3dd6308e4d2538c8fde149d28d4.

**Comment by kfiz** [comment]
Ok. Now that you mention it, i can see it. It is also mentioned in the doc string. Thanks for the hint. But I have to admit it clearly wasn't obvious to me that I could provide my own function that specifies the call and set(q) `counsel-locate-cmd` to that function.  I think the commit you referenced helps indeed.

**Comment by basil-conto** [comment]
Thanks for confirming, does that mean this issue can be closed?

**Comment by kfiz** [comment]
Yes. This can be closed. Thanks.
