### ISSUE TITLE
how to config swiper case insensitive

### ISSUE THREAD

**Issue by cryoguy** [abo-abo/swiper#2767]
I know there are a few tickets related to this.  I can not sort out an solution.   Is there a way to config swiper to be case sensitive, or otherwise? such as `C-s` for case sensitive search, and `C-S-s` for case insensitive search?

**Comment by basil-conto** [comment]
Have you tried customising `ivy-case-fold-search-default`?

**Comment by cryoguy** [comment]
`(setq ivy-case-fold-search-default t)` takes cares of it now. Thank you @basil-conto.
