### ISSUE TITLE
How to get the number of currently displayed candidates

### ISSUE THREAD

**Issue by thomasheartman** [abo-abo/swiper#2778]
Hi,

I was wondering whether it's possible to access (or calculate yourself) the number of currently displayed candidates for any ivy-buffer. I have looked through the documentation and the code and found that the `ivy-read` function adds this somehow (using the `ivy-add-prompt-count`), but I wasn't quite able to follow how it calculates the number of matching candidates.

In short, what I'd like to know is how do I know how many matches are currently available in the minibuffer of an ivy/counsel invocation, whether that be for M-x, switching buffers, or whatever.

The background for this is that I'm working with ivy-posframe, which seems to have an issue with correctly setting the min-height of the ivy-frame (I'm opening an issue there next). So what I'd like to do is to set the posframe's min-height of the frame to be the number of candidates plus one. If it seems like I'm going about this the entirely wrong way, I'm happy to hear that too, as long as you can point me in the right direction :relaxed:

**Comment by basil-conto** [comment]
Are you interested in the total number of completion candidates, or the number of completion candidates that are currently displayed?

**Comment by thomasheartman** [comment]
The number of completion candidates that are currently being displayed. From what I gather, `ivy--all-candidates` lists all the candidates, but I'd like to know how many are currently displayed.

**Comment by basil-conto** [comment]
`ivy-height` and `ivy-height-alist` are one indication of how many (single-line) candidates there are. I don't know whether that also covers the case of multi-line candidates.

**Comment by thomasheartman** [comment]
Does ivy-height do that? I’ve tried inspecting it with a varying number of candidates, but it never seems to change from 10. Maybe I’m doing something wrong. I don’t have a computer handy to check right now, but I’ll try and see some time tomorrow, probably. Thanks!

**Comment by abo-abo** [comment]
Have a look at `(length ivy--old-cands)`. Is that what you wanted?

**Comment by thomasheartman** [comment]
@abo-abo Yes, that is exactly what I was looking for; thanks :D

**Comment by basil-conto** [comment]
Note that `ivy--old-cands` is marked as an internal definition by the double hyphens, so be warned of possible future breakage.

**Comment by thomasheartman** [comment]
@basil-conto Yeah, I thought that might be the case. Thanks for the heads-up! But it seems that's the only way to get that number right now, if I understand correctly? If that's so, then I'll just stick with it for now and then take care of it if it breaks. If there is a more stable option, then that'd obviously be preferable. Cheers!
