### ISSUE TITLE
swiper/ivy: Make background blending optional

### ISSUE THREAD

**Issue by tsdh** [abo-abo/swiper#278]
Right now, swiper and ivy blend the background colors of the different match groups with the background color defined for the current selection.  With that blending, the background colors I have defined for the groups are hardly recognizable at all:

![screenshot from 2015-10-30 09-36-16](https://cloud.githubusercontent.com/assets/103854/10841644/a592ad78-7eeb-11e5-96fc-5aa5f355921c.png)

Would it be possible to make that blending optional so that the match group backgrounds are always taken literally?

Of course, that has one problem.  When you have many equal candidates and your input matches the complete candidates, then you can't know what's the currently selected one.  In that case, you should define `ivy-current-match` so that it differs from the match group faces in something else than just background, e.g., have it underlined.

**Comment by tsdh** [comment]
Or alternatively, the blending could just be improved.  Maybe it just doesn't work nicely for dark backgrounds right now...

**Comment by abo-abo** [comment]
> When you have many equal candidates and your input matches the complete candidates, then you can't know what's the currently selected one.

Exactly, that's an issue I kept running into, until I added blending. Also keep in mind that a program is free to pass propertized strings with custom backgrounds to `ivy-read`, e.g. like `lispy-goto` or `moo-jump-local` does.

> Or alternatively, the blending could just be improved. Maybe it just doesn't work nicely for dark backgrounds right now...

This is the direction to go, I think. Which specific theme do you have in mind?

In any case, do try `(setq colir-compose-method 'colir-compose-soft-light)`. I think it works pretty well for dark themes.

Then it's just a matter to patch `colir-blend` to conditionally use `'colir-compose-soft-light` when the current theme is dark:

```elisp
(defun colir-blend (c1 c2)
  "Blend the two colors C1 and C2 using `colir-compose-method'.
C1 and C2 are triples of floats in [0.0 1.0] range."
  (apply #'color-rgb-to-hex
         (cl-mapcar
          colir-compose-method
          c1 c2)))
```

Do you know how to make `current-theme-dark-p` predicate?

**Comment by tsdh** [comment]
Oleh Krehel <notifications@github.com> writes:

>> Or alternatively, the blending could just be improved. Maybe it just
>> doesn't work nicely for dark backgrounds right now...
>
> This is the direction to go, I think. Which specific theme do you have
> in mind?

My tsdh-dark-theme.el which ships with emacs.  But I think the problem
is there with any reasonably dark theme.

> In any case, do try `(setq colir-compose-method
> 'colir-compose-soft-light)`. I think it works pretty well for dark
> themes.

Oh, yes, that works!

> Then it's just a matter to patch `colir-blend` to conditionally use
> `'colir-compose-soft-light` when the current theme is dark:
>
> ```elisp
> (defun colir-blend (c1 c2)
>   "Blend the two colors C1 and C2 using `colir-compose-method'.
> C1 and C2 are triples of floats in [0.0 1.0] range."
>   (apply #'color-rgb-to-hex
>          (cl-mapcar
>           colir-compose-method
>           c1 c2)))
> ```
>
> Do you know how to make `current-theme-dark-p` predicate?

Yes.

```elisp
(frame-parameter nil 'background-mode)
;=> dark
```

The value is either the symbol `dark` or the symbol `light`.

,----[ (info "(elisp)Font and Color Parameters") ]
| ‘background-mode’
|      This parameter is either ‘dark’ or ‘light’, according to whether
|      the background color is a light one or a dark one.
`----

Bye,
Tassilo

**Comment by abo-abo** [comment]
Thanks. I've made the change to use `'colir-compose-soft-light` for dark themes.  Looks nice in tango-dark, misterioso, flatland etc. Except looks weird in tsdh-dark, with your recent update. But that's up to you:)

**Comment by tsdh** [comment]
:+1:
