### ISSUE TITLE
Marginalia annotation support in Ivy

### ISSUE THREAD

**Issue by minad** [abo-abo/swiper#2780]
There is the [Marginalia package](https://github.com/minad/marginalia/) which adds annotations to existing commands via the Emacs `annotation-function`/`affixation-function`, written by @oantolin and me. The package is comparable to ivy-rich but is more general in the sense that it does not rely on Ivy and has the capability to augment existing commands like `find-file` and `switch-to-buffer`. Marginalia works will other completion systems too, like default completion, icomplete-vertical, and Selectrum.

After some [Reddit discussion](https://www.reddit.com/r/emacs/comments/kqutap/selectrum_prescient_consult_embark_getting_started/gi7wy3t/?context=3) @abo-abo implemented initial support in 71c59aecf669142ebe264fac8ff7b440c0c71712. (**Update**: due to some breakage this commit has been reverted in the meantime by @basil-conto, see
764b978759e68cd3bd42eb69ed4698e2948c7d4e).

I tried this Ivy version and there are still a few minor issues for full annotation support:

* Annotations are not shown for `switch-buffer` and `find-file`. They are probably special cased in Ivy, and should query the annotation function too.
* The annotation faces are overwritten. This is probably desired, but maybe not the best default for rich colorful annotators.
* `describe-face` does not show annotations
* If possible it would be better to access the `affixation-function`, see #2732. Affixation functions work also in Emacs 27, only the default completion system will not use them.
* Some commands which report their category via completion metadata seem not to work. See this buffer example:

~~~ elisp
(completing-read "Buffer: "
                 (lambda (string pred action)
                   (if (eq action 'metadata)
                       '(metadata (category . buffer))
                     (complete-with-action action (mapcar #'buffer-name (buffer-list)) string pred))))
~~~

It may be the case that not all of the points from above are the fault of Ivy, but rather a result of how Marginalia hooks into the completion metadata infrastructure. Marginalia advises `completion-metadata-get`, see https://github.com/minad/marginalia/blob/d38a27867bcec0bafa43e8d1bd3fd96a32b15d31/marginalia.el#L686. If the completion metadata is accessed by other means, Marginalia will not have an effect.

**Comment by nbfalcon** [comment]
@basil-conto  I think @abo-abo's commit can be used if in `(let ((ivy--completion-extra-props ...)))` `...` is wrapped in `(unless (ivy-state-dynamic-collection ivy-last) ...)`.

**Comment by basil-conto** [comment]
@nbfalcon Thanks, but what is `ivy--completion-extra-props`? Did you mean `ivy--minibuffer-metadata`?

**Comment by basil-conto** [comment]
I've now gone with your suggestion @nbfalcon, thanks.
