### ISSUE TITLE
counsel-load-theme and use-package theme

### ISSUE THREAD

**Issue by gusbrs** [abo-abo/swiper#2782]
A PR for `use-package` was recently merged making use-package's `:custom` keyword rely on a new dedicated theme to set the variables customized by `use-package`: https://github.com/jwiegley/use-package/pull/881

Previously, `use-package` used other mechanisms for this. Fist `customize-set-variable`, which made the customizations be part of the "inner" `user` theme. Then, for a while, with `custom-set` or `set-default`, so that the variables were part of no theme. The mentioned PR changes this, and `use-package` will be a theme which, as far as I understand, will appear in `custom-enabled-themes`.

But, `counsel-load-theme-action` does the following before loading the selected theme:

```emacs-lisp
(mapc #'disable-theme custom-enabled-themes)
```
Likely under the presumption that anything in `custom-enabled-themes` will be a "color theme" we want to disable before loading another "color theme". But this new `use-package`'s theme is hardly something we would like to disable when "(color) theme hopping", so I think some sort of provision, or at least some checking for this, would be advisable.

**Comment by basil-conto** [comment]
Indeed, this is a more general issue: nothing in the name or docstring of `counsel-load-theme` suggests that it by default disables all other themes, which I find overly intrusive and not a good default.

In fact, the docstring implies the opposite: that it "forwards to `load-theme`", but `load-theme` explicitly states in its docstring that it does not disable other themes. So you could even argue that this is a bug.

**Comment by gusbrs** [comment]
Hi, @basil-conto 

I agree. On the other hand, disabling the themes is pretty much all `counsel-load-theme` does that `load-theme` doesn't (ok, `powerline-reset` too). So, if that's not done, `counsel-load-theme` sort of loses its "raison d'être", doesn't it?

Well, I'm not arguing for any course of action, I just reported the change, because what was previously a convenience has just become potentially disrupting, and may trip a number of users, who will be baffled about it.

**Comment by basil-conto** [comment]
> So, if that's not done, `counsel-load-theme` sort of loses its "raison d'être", doesn't it?

I think the usual argument for a lot of seemingly trivial Counsel stuff is that it calls `ivy-read` directly, thus supporting all Ivy-specific customisation options, such as sorting, display transformation, etc.

> Well, I'm not arguing for any course of action, I just reported the change, because what was previously a convenience has just become potentially disrupting, and may trip a number of users, who will be baffled about it.

Makes sense, thanks.

**Comment by gusbrs** [comment]
> I think the usual argument for a lot of seemingly trivial Counsel stuff is that it calls ivy-read directly, thus supporting all Ivy-specific customisation options, such as sorting, display transformation, etc.

I've been an user for quite some time, and have pestered this issue tracker's keepers numerous times, and it had not yet dawned on me that calling `ivy-read` directly was different from calling it through `completing-read`. So, I've just learned something today. Thanks!  ;-)

**Comment by basil-conto** [comment]
> What am I missing?

Probably support for functions that don't call `load-theme` interactively? Can you also attach custom actions to `load-theme`?  I don't know, I've always preferred built-in solutions over third-party ones :).

**Comment by gusbrs** [comment]
> Probably support for functions that don't call load-theme interactively?

I wouldn't be surprised if you know something I don't here, but I fail to see why the difference between `ivy-read` and `completing-read-default` would matter in a non-interactive call.

> Can you also attach custom actions to load-theme?

I had never tried, but it seems we can:

```emacs-lisp
(ivy-add-actions
 'load-theme
 '(("g" (lambda (_) (message "Hi Basil!")) "Greet Basil")))
```

That given, and processing the insight you provided, as far as I can tell, only those arguments in `ivy-read` which are not handled by `ivy-configure` would be critical for a `counsel` command to have to actually call `ivy-read` directly. But they do exist. For example, I'd love to, in some cases, to be able to filter the candidates list, but that implies redefining/patching. That's what I do with `counsel-bookmarks`, as one case at hand.

>  I don't know, I've always preferred built-in solutions over third-party ones :).

I'm a relatively new user (in Emacs terms, though I can now already say that I started "in the past decade" :), and the more I learn, the less packages I use. So I take it as a wise preference of yours.

Anyway, I'm probably pushing this thread off-topic already: back to it. It is indeed my view that `counsel-load-theme` brings little to the table besides disabling other themes before forwarding to `load-theme`. That's certainly why I use it myself. But, even if this assessment were a fair one, it would not be a big deal, and we can take little from it about what to do.

Some ideas (again, I'm not arguing for any of those, just brainstorming):

- create a `defcustom` such as `counsel-load-theme-protected-themes` or `counsel-load-theme-noncolor-themes`, add `use-package` there, and skip disabling those when mapping through `custom-enabled-themes`.
- instead of disabling all themes, offer completion again (or before), for the user to choose *one* theme to disable from the set of candidates in `custom-enabled-themes`

In either case, possibly `counsel-switch-theme` would be a more apt name (it would also be so for the current state of things).

**Comment by basil-conto** [comment]
>> Probably support for functions that don't call load-theme interactively?

> I wouldn't be surprised if you know something I don't here, but I fail to see why the difference between `ivy-read` and `completing-read-default` would matter in a non-interactive call.

The difference is that, when calling `ivy-read` directly, you can specify an explicit `:caller`, which is the symbol that all customisations are based on. Otherwise, `ivy-read` (via `ivy-completing-read`) has to use heuristics based on `this-command`, the current completion collection, etc. to determine what the current completion session is all about, and which customisations to apply. This may change in Emacs 28+ if #2768 is addressed.

> I'm a relatively new user (in Emacs terms, though I can now already say that I started "in the past decade" :)

Same here ;).

> and the more I learn, the less packages I use

The more I learnt, the more I became involved with upstream Emacs development - why invest in myriads of third-party packages of varying quality and upkeep, often by authors who didn't know any better and were just scratching an itch, when one can collaborate with the expert Emacs devs on improving Emacs for everyone and all downstream packages ;).

> In either case, possibly `counsel-switch-theme` would be a more apt name (it would also be so for the current state of things).

I'm not sure if this minor discrepancy is worth changing a command name over (with obsolete aliases and all), since the issue can be solved in the default (or a new) action. Either way, the docs definitely need fixing, and it's @abo-abo's call.

**Comment by gusbrs** [comment]
@basil-conto  and @abo-abo  Just a follow up on this.

It seems `use-package` did go with the theme in the end but: i) it made the theme usage configurable; and ii) excluded the use-package theme from `custom-enabled-themes`. I think the relevant commit is https://github.com/jwiegley/use-package/commit/e6b4bf8458f94227ed64df6e8e873d147e42916f

Thus, it seems clear at this point that there is no pressing issue for `counsel-load-theme` to solve from `use-package`'s side. I leave it to you guys to decide if this should be just closed, or if there is something "non-pressing" you still want to discuss or keep track of in this regard.

**Comment by basil-conto** [comment]
> I leave it to you guys to decide if this should be just closed, or if there is something "non-pressing" you still want to discuss or keep track of in this regard.

Well if the titular issue is no longer an issue, then I suggest we close this issue.

We can open new and more focused issues/PRs when someone feels motivated to improve `counsel-load-theme`.

Unless I'm forgetting/misunderstanding something?

**Comment by gusbrs** [comment]
> Unless I'm forgetting/misunderstanding something?

Not at all. It is just that, on the one hand, I don't know if the question of whether disabling all enable themes is something you want to still pursue and, on the other, I tend to feel impolite for me to close an issue "just because I'm the OP" and that this is usually something for maintainers/collaborators to decide.

I just meant to bring the up to date information on the issue. And "as far as the OP can tell" this is up for closing. So, feel free to do so, if that's also your opinion.

**Comment by basil-conto** [comment]
> I don't know if the question of whether disabling all enable themes is something you want to still pursue

I don't think the command's documentation is perfect, or that this behaviour is necessarily ideal in all circumstances, but that's what the command has done since day 1.  Users are free to use built-in or custom commands instead ;).

Patches and suggestions for improving it are always welcome, but it's not something I'm pressed to pursue personally any time soon.

> And "as far as the OP can tell" this is up for closing. So, feel free to do so, if that's also your opinion.

Since potential improvements for `counsel-load-theme` arose almost tangentially to this discussion, I'm closing this issue for now.

Whenever someone decides to polish `counsel-load-theme` in the future, we can open more focused issues/PRs.

Thanks!

**Comment by gusbrs** [comment]
Agreed. And, considering none other than `use-package` adjusted for this on its side, I think we are going to keep seeing `(mapc #'disable-theme custom-enabled-themes)` or equivalent forms around for long still. I, for one, use `counsel-load-theme` instead of `load-theme` precisely because it does that.

Thank you!
