### ISSUE TITLE
counsel-bookmark does not show the bookmark names but only filenames

### ISSUE THREAD

**Issue by dimitar-petrov** [abo-abo/swiper#2784]
Hi,

can someone point my where is the configuration to set counsel-bookmark to list the bookmark names instead of file.

![image](https://user-images.githubusercontent.com/4025446/104156565-01a95e00-53f2-11eb-8f67-7fbcc35b7eb7.png)

Thanks

**Comment by basil-conto** [comment]
Is this the same issue as #2739?

**Comment by basil-conto** [comment]
Closing as duplicate until further notice.  If that's not the case, feel free to reopen.
