### ISSUE TITLE
[Feature request] Make ivy-rotate-sort rotate the fall-through case

### ISSUE THREAD

**Issue by kisaragi-hiu** [abo-abo/swiper#2786]
It would be useful if `ivy-rotate-sort` is able to rotate the fall-through case, so that when a user wants to specify multiple sort functions (one for recency, one for alphabetical...) they don't have to specify it for every single command they use. Something like:

```elisp
(setq ivy-sort-functions-alist '((t . (ivy-prescient-sort-function ivy-string<))))
```

and have `ivy-rotate-sort` work even when the current collection isn't referenced explicitly in there.

Specifically, I wish these lines in `ivy-rotate-sort` also tries to get the value associated with `t`:

https://github.com/abo-abo/swiper/blob/e43141df8a92995336585b401eb550a375349759/ivy.el#L1771-L1772

**Comment by basil-conto** [comment]
Thanks for the suggestion, I agree that's the right thing to do. Let me know if there's anything wrong with the fix I pushed.
