### ISSUE TITLE
Do not show current, previous directories in the find-file list

### ISSUE THREAD

**Issue by ChoppinBlockParty** [abo-abo/swiper#2787]
![Selection_001](https://user-images.githubusercontent.com/28957323/104845440-70445b00-58cd-11eb-98d9-6e308a86c695.png)

Maybe there is already a way to do this, I just missed it. Otherwise would be nice to not have those '.', '..' every time.

**Comment by basil-conto** [comment]
You can set `ivy-extra-directories` to `nil`; see the manual [`(info "(ivy) File Name Completion")`](https://oremacs.com/swiper/#file-name-completion).
