### ISSUE TITLE
`ivy-configure` does not work for `:display-fn` after loading `counsel`

### ISSUE THREAD

**Issue by kunhtkun** [abo-abo/swiper#2789]
After running the following snippet:

```emacs-lisp
(require 'counsel)
(ivy-configure 'counsel-find-file
  :display-fn #'ivy-display-function-overlay)
```

`ivy-display-functions-alist` does not contain the new item. Here is its value:

```
((counsel-irony . ivy-display-function-overlay)
 (ivy-completion-in-region . ivy-display-function-overlay)
 (t))
```

If `counsel` is not loaded it works as expected. I think it is due to this line:

https://github.com/abo-abo/swiper/blob/cbce9ce71429c98c67bd76ef15d049ecced042f7/counsel.el#L425

It modifies the variable without using `ivy-configure` so the checks in `ivy--alist-set` prevents adding the new value:

https://github.com/abo-abo/swiper/blob/cbce9ce71429c98c67bd76ef15d049ecced042f7/ivy.el#L1869-L1874

However, I do not quite understand the `ivy--alist-set` function so I am not sure if it is really the cause.

Thank you!

**Comment by basil-conto** [comment]
> After running the following snippet `ivy-display-functions-alist` does not contain the new item

How are you running that snippet? The only case in which that shouldn't work is if `ivy-display-functions-alist` has been modified by the Customize interface.  Could you please provide a reproducible step-by-step recipe, ideally starting from `emacs -Q` or `make plain`?

**Comment by kunhtkun** [comment]
Sorry I forgot to include the recipe. Here is what I did:

- Run `emacs -Q`;
- Evaluate the snippet in the scratch buffer:

```emacs-lisp
(package-initialize)
(require 'counsel)
(ivy-configure 'counsel-find-file
  :display-fn #'ivy-display-function-overlay)
```

- Check the value of `ivy-display-functions-alist`.

It seems that `ivy--alist-set` not only checks value by Customize interface but also compares and sets the "standard-value".

https://github.com/abo-abo/swiper/blob/cbce9ce71429c98c67bd76ef15d049ecced042f7/ivy.el#L1862-L1877

**Comment by basil-conto** [comment]
Thanks for the repro!  IMO this is the same bug as #2442, or at least a symptom of it, but I guess we're stuck with `ivy-configure` and `ivy--alist-set` now ;).
