### ISSUE TITLE
Set case-fold-search to nil for file rename

### ISSUE THREAD

**Issue by sooheon** [abo-abo/swiper#279]
When calling rename-file the ivy completion should default to case-fold nil, reason being that you often rename files with just a case change, and you would not want ivy to match the old name. Or if it should be user config, how would one set this?

e: I guess the real question is how to set default values for ivy settings?

**Comment by abo-abo** [comment]
> When calling rename-file the ivy completion should default to case-fold nil, reason being that you often rename files with just a case change, and you would not want ivy to match the old name. Or if it should be user config, how would one set this?

The case fold starts out at `'auto` which is a very reasonable setting. You only get a conflict when you want to rename a file with upcase chars into full downcase.  Even then, you can just use <kbd>C-M-j</kbd> or <kbd>C-u C-j</kbd> (both call `ivy-immediate-done`) to ignore the suggested candidates.

It's also possible to set the case fold to nil for current completion with <kbd>C-o C</kbd>.  But using `ivy-immediate-done` is probably faster, and it's a very useful command in its own right.

> e: I guess the real question is how to set default values for ivy settings?

There are a few alists that you can customize:

    defvar ivy-sort-functions-alist
    defvar ivy-index-functions-alist
    defvar ivy-re-builders-alist
    defvar ivy-initial-inputs-alist

I can add `ivy-case-fold-search-alist` if you really want, but try the <kbd>C-M-j</kbd> approach - it's simpler.

If you're more confident with Elisp, you can just advice e.g. `ivy--filter` to do what you want:

```elisp
(defadvice ivy--filter (around ivy-rename-file activate)
  (let ((ivy-case-fold-search
         (if ivy--directory
             nil
           ivy-case-fold-search)))
    ad-do-it))
```

**Comment by sooheon** [comment]
I agree `auto` is a sensible default value for most cases, but I've come across this for renaming files a couple of times. Thanks for the `C-M-j` tip, it's good enough for me. I only knew about `C-m` and `C-j`, and it's another nice action that helm afaik doesn't seem to have.
