### ISSUE TITLE
Can we use use-package in docs?

### ISSUE THREAD

**Issue by utkarsh181** [abo-abo/swiper#2791]
First thanks for swiper!

Existing version:

```
(ivy-mode 1)
(setq ivy-use-virtual-buffers t)
(setq enable-recursive-minibuffers t)
;; (setq search-default-mode #'char-fold-to-regexp)
(global-set-key "\C-s" 'swiper)
(global-set-key (kbd "C-c C-r") 'ivy-resume)
(global-set-key (kbd "<f6>") 'ivy-resume)
(global-set-key (kbd "M-x") 'counsel-M-x)
(global-set-key (kbd "C-x C-f") 'counsel-find-file)
(global-set-key (kbd "<f1> f") 'counsel-describe-function)
(global-set-key (kbd "<f1> v") 'counsel-describe-variable)
(global-set-key (kbd "<f1> o") 'counsel-describe-symbol)
(global-set-key (kbd "<f1> l") 'counsel-find-library)
(global-set-key (kbd "<f2> i") 'counsel-info-lookup-symbol)
(global-set-key (kbd "<f2> u") 'counsel-unicode-char)
(global-set-key (kbd "C-c g") 'counsel-git)
(global-set-key (kbd "C-c j") 'counsel-git-grep)
(global-set-key (kbd "C-c k") 'counsel-ag)
(global-set-key (kbd "C-x l") 'counsel-locate)
(global-set-key (kbd "C-S-o") 'counsel-rhythmbox)
(define-key minibuffer-local-map (kbd "C-r") 'counsel-minibuffer-history)
```

Use-package variant:

```
(use-package swiper
  :init
  (ivy-mode 1)
  :custom
  (ivy-use-virtual-buffer t)
  (enable-recursive-minibuffers t)
  ;; enable this if you want `swiper' to use it
  ;; (search-default-mode #'char-fold-to-regexp)
  :bind (("C-s" . swiper)
	 ("C-c C-r" . ivy-resume)
	 ("<f6>" . ivy-resume)
	 ("M-x" . counsel-M-x)
	 ("C-x C-f" . counsel-find-file)
	 ("<f1> f" . counsel-describe-function)
	 ("<f1> v" . counsel-describe-variable)
	 ("<f1> o" . counsel-describe-symbol)
	 ("<f1> l" . counsel-find-library)
	 ("<f2> i" . counsel-info-lookup-symbol)
	 ("<f2> u" . counsel-unicode-char)
	 ("C-c g" . counsel-git)
	 ("C-c j" . counsel-git-grep)
	 ("C-c k" . counsel-ag)
	 ("C-x l" . counsel-locate)
	 ("C-S-o" . counsel-rhythmbox)
	 :map minibuffer-local-map
	 ("C-r" . counsel-minor-history)))
```

If you also like to use counsel-mode:

```
(use-package swiper
  :init
  (ivy-mode 1)
  (counsel-mode 1)  ; Type C-h f counsel-mode RET
  :custom
  (ivy-use-virtual-buffer t)
  (enable-recursive-minibuffers t)
  ;; enable this if you want `swiper' to use it
  ;;(search-default-mode #'char-fold-to-regexp)
  :bind (("C-s" . swiper)
	 ("C-c C-r" . ivy-resume)
	 ("<f6>" . ivy-resume)
	 ("<f1> l" . counsel-find-library)
	 ("<f2> u" . counsel-unicode-char)
	 ("C-c g" . counsel-git)
	 ("C-c j" . counsel-git-grep)
	 ("C-c k" . counsel-ag)
	 ("C-x l" . counsel-locate)
	 ("C-S-o" . counsel-rhythmbox)
	 :map minibuffer-local-map
	 ("C-r" . counsel-minor-history)))
```

If you like this than I will create a PR.

**Comment by basil-conto** [comment]
Some thoughts:
* Docs shouldn't assume users are using particular packages.
* It should be trivial for users of `use-package` to translate these examples to equivalent `use-package` stanzas.
* It's not a package's job to document and give examples of every possible way to write a `user-init-file` - the idea is to say where the package is available, and give a summary of how it might be used.  The rest applies to all packages equally.
* For more extensive community examples, there's always the Wiki.

So, my suggestion would be to either keep the current vanilla example, or give examples of both, though I'd personally find the latter quite redundant.

**Comment by utkarsh181** [comment]
"Basil L. Contovounesios" <notifications@github.com> writes:

> Some thoughts:
> * Docs shouldn't assume users are using particular packages.
> * It should be trivial for users of `use-package` to translate these examples to equivalent `use-package` stanzas.
> * It's not a package's job to document and give examples of every possible way to write a `user-init-file` - the idea is to say where the package is available, and give a summary of how it might be used.  The rest applies to all packages equally.
> * For more extensive community examples, there's always the Wiki.
>
> So, my suggestion would be to either keep the current vanilla example, or give examples of both, though I'd personally find the latter quite redundant.
>
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/abo-abo/swiper/issues/2791#issuecomment-764611576

I am really sorry for my complete ignorance on the topic of use-package
and it being de facto standard for user-init file.  As a relatively new
user I find example config in non-use-package way very confusing.  But I
thinks you are right it's not package job to help setup package is the
most convenient way.
-- 
Utkarsh Singh
