### ISSUE TITLE
Setting `ivy-calling` to t breaks swiper

### ISSUE THREAD

**Issue by anonimitoraf** [abo-abo/swiper#2792]
When I set
`(setq-default ivy-calling t)`

Then I try to use Swiper, I get this error:
```
Error in post-command-hook (ivy--queue-exhibit): (error "Lisp nesting exceeds ‘max-lisp-eval-depth’")
```

`max-lisp-eval-depth` is set to 1600

**Comment by basil-conto** [comment]
Sorry, I can't reproduce this based only on the information you've provided. Could you please elaborate? What are your Emacs, Ivy, and Swiper versions, can you reproduce the issue from `emacs -Q` or `make plain`, what are the precise steps to reproduce the error, etc.

**Comment by anonimitoraf** [comment]
Ah, sorry for the vague Issue details.
It seems like it only happens in doom-emacs (maybe doom's using an ivy version that's too old). I tried with a plain init.el file with the bare minimum (counsel + ivy) and I don't see the problem. So I'll dig around a bit more

**Comment by basil-conto** [comment]
Thanks.
