### ISSUE TITLE
Is it possible to let ivy do autocompletion base on a specified file?

### ISSUE THREAD

**Issue by BaoshanPang** [abo-abo/swiper#2797]
Say I am working on a shell script A, and it would use some functions defiend in shell script B, but in A there is no information about B. 
So for such case, is there a command that can tell IVY to lookup functions in B?

**Comment by basil-conto** [comment]
In theory, yes - you can complete anything in Emacs/Ivy.

In practice, you need to populate the [completion table](https://gnu.org/software/emacs/manual/html_node/elisp/Basic-Completion.html#index-completion-table) somehow, either by using existing commands/packages, or by writing it yourself, and that is highly file-specific.  For example, how are you going to detect which functions are present in `B`?  Using the [`imenu`](https://gnu.org/software/emacs/manual/html_node/elisp/Imenu.html) integration (or some other support) provided by `sh-mode`?

**Comment by BaoshanPang** [comment]
>> For example, how are you going to detect which functions are present in B? 
I am not sure how to do it at this point. I will check if imenu have the answer for me. Thanks for the information.

**Comment by basil-conto** [comment]
Okay, then since this is a pretty open-ended topic, I'll close the issue for now.  If you later come across any specific problems or requests to do with Ivy/Counsel, you can always reopen it.
