### ISSUE TITLE
ivy-call not doing anything

### ISSUE THREAD

**Issue by Joshuao95** [abo-abo/swiper#2798]
Hi,

Sorry for the bad report, but I'm not seeing the desired behaviour when using `ivy-call` (bound by default to `M-RET`).

I can see it is indeed bound (I've not modified any settings, so that makes sense)

And if I set `debug-on-entry` I can see that it is indeed being called, but I'm unsure what to provide for a diagnosis.

Reproduction
1. Call `describe-variable`
2. Hit `M-RET` on a candidate
3. Watch as nothing happens

**Comment by basil-conto** [comment]
I could be wrong, but I think `ivy-call` is only supported with completion commands that use `ivy-read` directly, such as `counsel-describe-variable`.

**Comment by Joshuao95** [comment]
Ah, okay thanks for that basil-conto.

I am indeed not using counsel, and just ivy alone for now (I'm just getting started with Emacs, and want to get a feel for the builtins before using overhauls like Counsel)

Should I expect the online documentation to not make a distinction between Ivy specific commands, and ones that require Counsel/Swiper?

**Comment by basil-conto** [comment]
> Should I expect the online documentation to not make a distinction between Ivy specific commands, and ones that require Counsel/Swiper?

I'm not sure what you mean.  Ivy does two things: provide replacements for the default values of `completing-read-function` & friends (which constitute the vanilla Emacs completion API), and provide `ivy-read` (as an alternative completion API). Counsel is a library built on the `ivy-read` API.

This is actually already mentioned briefly in the `README.md` and in slightly more detail in the manual at [`(info "(ivy) Counsel commands")`](https://oremacs.com/swiper/#counsel-commands).

So unless you'd like to suggest/submit improvements for the documentation, is there anything else to be done here?

**Comment by Joshuao95** [comment]
Hi,

I mean to say, that my expectation was :  If I read the Ivy manual, and use the keybindings therein (especially those that are prefixed ivy-*), I expected them to work with Ivy alone.

As it stands, I'm not sure which keybindings/functions from the manual will do anything for me, given that I don't use Counsel.

I won't lie, I am not willing to lend a hand and rewrite the documentation, so I don't think there's anything more to be done here.

My only suggestion is, if decoupling is a goal you'd like to keep, I would appreciate being able to read something just about "Ivy" rather than "Ivy/Counsel/Swiper".  
Maybe a short term solution is to mention that functions in section 5.2.3 rely on the underlying candidate list using the API, and as such won't work for Emacs builtins?

**Comment by basil-conto** [comment]
> I mean to say, that my expectation was : If I read the Ivy manual, and use the keybindings therein (especially those that are prefixed ivy-*), I expected them to work with Ivy alone.

Again, it depends on what you mean by "Ivy alone".  Ivy provides `ivy-read`, and anything that targets `ivy-read` by extension works with `ivy-call` & friends.  The issue that you've brought up is that some of the bells and whistles that `ivy-read` provides aren't supported by the built-in Emacs completion API.  But this makes sense, and is the justification for `ivy-read` in the first place.  In fact, `ivy-call` is as "Ivy-specific" as it gets.

> As it stands, I'm not sure which keybindings/functions from the manual will do anything for me, given that I don't use Counsel.

Fair enough.

> I won't lie, I am not willing to lend a hand and rewrite the documentation, so I don't think there's anything more to be done here.

I feel the same ;).

> My only suggestion is, if decoupling is a goal you'd like to keep, I would appreciate being able to read something just about "Ivy" rather than "Ivy/Counsel/Swiper".

I think the ship of "keeping" any decoupling has long sailed, unfortunately :).

> Maybe a short term solution is to mention that functions in section 5.2.3 rely on the underlying candidate list using the API, and as such won't work for Emacs builtins?

Makes sense; done in commit 68ce6e6517b20c37d5abab1f511b1aae81534ddb.  Thanks.
