### ISSUE TITLE
`swiper-from-isearch` does not refresh on typing from an empty `isearch`

### ISSUE THREAD

**Issue by lepieru** [abo-abo/swiper#2799]
`swiper-from-isearch` seems not work as expected coming from an empty query.

I like to call `swiper-from-isearch` even when my `isearch` query is still empty.

In this situation, `swiper` does not refresh on typing. I had to type enter first, and then I can make my search.

**Comment by basil-conto** [comment]
Thanks, should be fixed in commit e0374dc0bbcd8ab0ec24baf308d331251d4f9c49.

**Comment by lepieru** [comment]
Yes, it is. Thank you!
