### ISSUE TITLE
ivy fails on ERC buffers

### ISSUE THREAD

**Issue by qdot** [abo-abo/swiper#28]
Turned swiper on globally, then tried to search in an ERC buffer. Got the error message:

Error in post-command-hook (ivy--exhibit): (text-read-only)

And lost all syntax coloration on buffer. Search doesn't work, and trying to hit enter just gets a "Text is read-only" error. Unfortunately don't have a backtrace to share yet, but repro should be pretty easy.

**Comment by abo-abo** [comment]
Thanks. I haven't used ERC before. Could you give me a step-by-step to install ERC (which package?),
start it up and select the window that causes the error?

**Comment by qdot** [comment]
Well, you're in luck that ERC comes with emacs, at least, so nothing new to install. Just

- M-x erc
- use "irc.freenode.net" for the server
- use 6667 for port
- whatever you want for nick, no password
- once it's connected, join a channel (/j #emacs), which will bring up a channel window
- Run swiper

This should bring up the error.

**Comment by abo-abo** [comment]
Quite a brain-teaser, thanks:)
