### ISSUE TITLE
[suggestion] Unsaved buffer face in ivy-switch-buffer

### ISSUE THREAD

**Issue by thwg** [abo-abo/swiper#280]
Sometimes when I switch buffers with ivy, I would find it helpful to quickly differentiate between modified buffers with unsaved changes, and those which are already saved.

Could an additional custom face be added to represent the buffers with unsaved modification?

**Comment by abo-abo** [comment]
Thanks. I've added `'ivy-modified-buffer` face, but it's blank by default.

You can customize it like this:

```elisp
(custom-set-faces
     '(ivy-modified-buffer ((t (:background "#ff7777")))))
```

**Comment by thwg** [comment]
Awesome, works great.  Thank you!
