### ISSUE TITLE
Add initial-input for `counsel-search` command

### ISSUE THREAD

**Issue by dalanicolai** [abo-abo/swiper#2803]
It would be great if we could just search selected text from a buffer directly.
I am happy to make a PR, but I see that the `counsel-search` command takes input already.
So maybe there is a reason why the interactive form does not read preselected text/symbol at point.
So let me know if I should make a PR here, or maybe you will add something like the following to the interactive form
```
(list (if (use-region-p)
          (buffer-substring-no-properties (region-beginning) (region-end))
        (thing-at-point 'symbol)))

```
or maybe I should create an `external` function for Spacemacs.

**Comment by basil-conto** [comment]
Have you tried invoking `ivy-next-history-element` (bound to `M-n` by default) after starting `counsel-search` completion? That should insert either the active region or the word at point.

**Comment by dalanicolai** [comment]
Haha, no had not tried that. I did not expect this kind of implementation. Well this is a perfect alternative of course. Thanks, as usual!

**Comment by basil-conto** [comment]
> I did not expect this kind of implementation.

It's how most vanilla Emacs commands that read from the minibuffer work: `M-n` is meant to cycle through sensible defaults.  See [`(info "(emacs) Minibuffer History")`](https://www.gnu.org/software/emacs/manual/html_node/emacs/Minibuffer-History.html#index-M_002dn-_0028minibuffer-history_0029).
