### ISSUE TITLE
Is there a way to add/customize a command keymap with ivy?

### ISSUE THREAD

**Issue by jkitchin** [abo-abo/swiper#2804]
I want to customize the keymap for `org-set-tags-command`. As far as I know, this command uses the "automatic" completion with ivy, i.e from something like completing read, and it isn't a native ivy command with a keymap.

What I would like to do is make the key ";" insert the selected tag and prompt for a new tag, but only when called through `org-set-tags-command`.  is that possible?

**Comment by basil-conto** [comment]
Have you tried enabling your custom keymap using an `ivy-init-fns-alist` or `ivy-hooks-alist` entry?

**Comment by jkitchin** [comment]
I don't know how that would work exactly. I guess I was looking for something like `(ivy-configure 'org-set-tags-command :keymap map)` but that doesn't seem to be an option.

**Comment by basil-conto** [comment]
> I don't know how that would work exactly.

For example:

```el
(defun my-ivy-semicolon ()
  "Bind \";\" during Ivy completion."
  (local-set-key ";" (lambda () (interactive) (message "hi"))))

(with-eval-after-load 'ivy
  (setf (alist-get #'org-tags-completion-function ivy-hooks-alist)
        #'my-ivy-semicolon))
```

> I guess I was looking for something like `(ivy-configure 'org-set-tags-command :keymap map)` but that doesn't seem to be an option.

Probably because sacrificing a self-inserting key during completion is more intrusive and less popular than defining a custom [action key](https://oremacs.com/swiper/#actions).
