### ISSUE TITLE
counsel-company does not do company's post-completion operation, why?

### ISSUE THREAD

**Issue by dwang20151005** [abo-abo/swiper#2805]
Hi,  thanks for this fantastic software.  A small issue:

I cannot get `counsel-company` to perform the `post-completion`
operation offered by my company backend. Looking at the code, it looks
like we only call out to company for the candidates. Insertion of the
chosen candidate is done by `ivy-completion-in-region-action`, which
has no mention of company `post-completion`.

Would it be possible to add this support?  I have a company backend
that does completon over a sexp-based domain specific language.  I use
the `post-completion` to close parens introduced during completion.

Here's a reproduction:

1. Run this script:

       cat > /tmp/test-counsel-company.el <<EOF
       (require 'company)
       (require 'counsel)

       (defun my-company-backend (operation &rest args)
         (interactive '(interactive))
         (cl-case operation
           (interactive (company-begin-backend 'my-company-backend))
           (prefix (company-grab-symbol))
           (candidates (list "foo" "bar"))
           (post-completion (insert "inserted by post-completion"))))

       (add-to-list 'company-backends 'my-company-backend)
       (company-mode)
       (define-key global-map (kbd "TAB") 'my-company-backend)
       EOF
       emacs -q --no-site-file --no-site-lisp --no-splash --no-x-resources \
             -L ~/.emacs.d/elpa/27.1/develop/swiper-20201208.1419/ \
             -L ~/.emacs.d/elpa/27.1/develop/ivy-20210114.1859/ \
             -L ~/.emacs.d/elpa/27.1/develop/counsel-20210109.1641/ \
             -L ~/.emacs.d/elpa/27.1/develop/company-20210114.35/ \
             /tmp/test-counsel-company.el

2. `M-x eval-buffer RET`
3. `M-x counsel-company RET f RET`
4. Observe that only "foo" is inserted.
5. `TAB f TAB`
6. Observe that "fooinserted by post-completion" is inserted, as expected.

Can you reproduce?

Is it possible to add company `post-completion` support?

**Comment by basil-conto** [comment]
> Would it be possible to add this support?

I've yet to look into Company, but patches welcome :).

**Comment by basil-conto** [comment]
> Can you reproduce?

Almost: in step 5, when I type `f`, `Matching input is required` is printed to the `*Messages*` buffer, and I need to type `RET` to get `barinserted by post-completion` inserted in the buffer.  This is with Emacs 28 and Company `20210122`.

**Comment by dwang20151005** [comment]
Sadly, I have only ever programmed emacs through the dynamic modules support. Unless you are willing to add an OCaml dependency,  I doubt you will be interested in any patch I can provide.

Thanks for confirming that the issue is in company, rather than between keyboard and chair.  We will work around it locally.  You should feel free to close this issue, if that is your workflow.

**Comment by basil-conto** [comment]
> Thanks for confirming that the issue is in company

Did I? :)

> You should feel free to close this issue, if that is your workflow.

I don't know enough about Company to decide; I was under the impression that this was a feature request for `counsel-company`.

Unfortunately I won't be working on this any time soon, so feel free to do with this issue as you like.

**Comment by dwang20151005** [comment]
I'm fuzzy on the boundaries between these project.  All I meant was, thanks for confirming that I wasn't doing something wrong with the existing code.

This is a feature request, but I understand you won't be implementing it any time soon.  I don't know whether your practice is to close the issue (maybe you track todo items elsewhere?) or leave it open until you have a chance to work on it.

**Comment by basil-conto** [comment]
>  I don't know whether your practice is to close the issue

Only if it's done or inapplicable; see the list of open issues ;).

> or leave it open until you have a chance to work on it.

Or someone else does ;).

**Comment by nbfalcon** [comment]
Changing
```emacs-lisp
                :action #'ivy-completion-in-region-action
```
```emacs-lisp
                :action (lambda (cand)
                          (delete-region ivy-completion-beg ivy-completion-end)
                          (company-finish cand))
```
should fix this, since `company-finish` is responsible for running hooks etc. I don't know why `delete-region` is necessary, though. For some reason, the prefix isn't stripped when invoking `company-finish`.

Disclaimer: I don't use `counsel-company`.
