### ISSUE TITLE
auto select a single candidate

### ISSUE THREAD

**Issue by haji-ali** [abo-abo/swiper#2806]
Is there a way to configure `ivy-completing-read` so that when the user narrows down the list to a single candidate that candidate is automatically accepted?
I know of `ivy-auto-select-single-candidate` but it seems to be restricted to the case when the candidate list has a single item (before the user narrows it down).

**Comment by haji-ali** [comment]
I tried this solution

```
(defun my/matcher (re candidates)
  (let ((match-cand (ivy--re-filter re candidates)))
    (if (not (eq 1 (length match-cand)))
        match-cand
      (ivy-set-text (car match-cand))
      (ivy-done))))

(ivy-read "Rewrap: " '("111" "121" "131" "132")
          :matcher 'my/matcher)
```

This "works" in the sense that the single candidate is automatically selected but the text replaces the content of current buffer! I imagine calling `ivy-done` within the matcher is not advisable.

**Comment by basil-conto** [comment]
Why not use `:update-fn` instead of `:matcher`?

**Comment by haji-ali** [comment]
Good point. Thanks for this. I thought about using `matcher` to access the list of current candidates. But looking through the source code, ivy seems to store that in `ivy--old-cands`. Using this, I came up with this solution which seems to work

```elisp
(ivy-read "Rewrap: " '("111" "121" "131" "132")
          :update-fn (lambda nil
                       (when (eq 1 (length ivy--old-cands))
                         (ivy-done))))
```

**Comment by basil-conto** [comment]
To avoid having `length` traverse the entire length of `ivy--old-cands` each time, you can use the following equivalent condition instead:

```el
(lambda ()
  (and ivy--old-cands
       (null (cdr ivy--old-cands))
       (ivy-done)))
```

or, in Emacs 28:

```el
(lambda ()
  (when (length= ivy--old-cands 1)
    (ivy-done)))
```
