### ISSUE TITLE
Disable substring for a particular ivy-completing-read

### ISSUE THREAD

**Issue by haji-ali** [abo-abo/swiper#2807]
I want to use `ivy-completing-read` to display a list of candidates so I can choose one. However, I don't want the narrowing of candidates to be done in a fuzzy or substring fashion. Is there a way to configure the call to `ivy-completing-read` so that only the beginning of the candidates' string is matched?

**Comment by basil-conto** [comment]
You could anchor the regexp to the start of the candidate by starting it with `^`. This is already the default for some commands; see `ivy-initial-inputs-alist` and `ivy-hooks-alist`.

If this is not sufficient, for whatever reason, then you'd probably need a custom entry in `ivy-re-builders-alist`, but I could be wrong.

**Comment by haji-ali** [comment]
Thanks! After looking at `ivy-re-builders-alist` I found that `ivy-read` takes an `:re-builder` argument which I was able to use to preprend the search text with `^`.

**Comment by basil-conto** [comment]
If all you want to do is prepend `^`, then why aren't you using `ivy-initial-inputs-alist` or the `:initial-input` argument?

**Comment by haji-ali** [comment]
Because then I can then (accidentally) delete the `^` and I want to avoid that.
