### ISSUE TITLE
counsel-rg hide the results with prompts [Omitted long matching line]

### ISSUE THREAD

**Issue by AbstProcDo** [abo-abo/swiper#2809]
Counsel-rg hide the details of searching results by prompting [Omitted long matching line].

I search thorough the entire repository but get no such a prompt within source code.

How could get results displayed no matter how long the lines?

**Comment by basil-conto** [comment]
Have you tried removing the default `-M 240` from `counsel-rg-base-command`?

**Comment by AbstProcDo** [comment]
Thank you, I locate the problem to remove "-M 240" from counsel-rg-base-command.

only with some intricacies in doom emacs which manage package with straight.el.

**Comment by basil-conto** [comment]
Great, does that mean this issue can be closed?

**Comment by AbstProcDo** [comment]
ty, please close it.
