### ISSUE TITLE
swiper-mc not working as expected

### ISSUE THREAD

**Issue by ardpp** [abo-abo/swiper#281]
Maybe I'm missing something but on my version of emacs 25.0.50.1, swiper-mc is not working as described here http://oremacs.com/2015/10/14/swiper-mc/

I tried with my normal configuration as well as using 
`emacs -Q`

Then evaluating 
```
(add-to-list 'load-path "/path/to/swiper")
(add-to-list 'load-path "/path/to/multiple-cursors")
(require 'multiple-cursors)
(require 'swiper)
```
Then running `M-x swiper` followed by `;; C-7 DEL DEL C-d C-g` on the following buffer 
```
(progn
  ;; (check-1)
  (foo)
  ;; (check-2)
  (bar)
  ;; (check-3)
  (baz))
```
gives me this 
```
(progn
  (check-1)
  (foo)
  ;; (check-2)
  (bar)
  ;; (check-3)
  (baz))
```

**Comment by abo-abo** [comment]
> emacs -Q
> (add-to-list 'load-path "/path/to/swiper") (add-to-list 'load-path "/path/to/multiple-cursors") (require 'multiple-cursors) (require 'swiper)

Just tried this on Emacs 25, it works as expected. What happens after you press <kbd>C-7</kbd>, do you get 2 extra cursors?

**Comment by ardpp** [comment]
I do get two extra cursors, but they seem (somehow) inactive and disappear after a short period of time.

**Comment by abo-abo** [comment]
Any information in `*Messages*`? Are both packages up to date?

**Comment by ardpp** [comment]
In `*Messages*` it says `Mark saved where search started [3 times]`. Packages as well as emacs are up to date.

**Comment by ardpp** [comment]
Tried to delete my elpa-directory so that all packages are reinstalled after a restart of emacs. Same behavior. Can I provide some more information?

**Comment by abo-abo** [comment]
Try this with `emacs -Q`:

```elisp
(setq package-archives
      '(("melpa" . "http://melpa.milkbox.net/packages/")))
```

<kbd>M-x</kbd> `package-install` both `swiper` and `multiple-cursors`.

Don't eval this:

```elisp
(require 'multiple-cursors)
(require 'swiper)
```

Swiper is auto-loaded, so you can use <kbd>M-x</kbd> `swiper`. This has worked for me, starting from an empty ELPA directory.

If it still doesn't work, delete `swiper.elc` file and restart Emacs.

**Comment by ardpp** [comment]
Hmm. Did exactly that and have still the same behaviour as described above. Can this depend on the system? Maybe someone running emacs on Arch Linux can test this?

**Comment by abo-abo** [comment]
One more thing to try. Reload swiper with `eval-buffer`. And do <kbd>M-x</kbd> `toggle-debug-on-error`.

**Comment by ardpp** [comment]
The same as before happens and no error occurs.  
Here is a short video of how it looks like https://dpp.owncube.com/index.php/s/dyorUdre4GATS0p
(I will edit this post and remove the link to the video after you had a look)

**Comment by abo-abo** [comment]
Clone the swiper repo and add the following lines to ivy-test.el:

```elisp
(require 'swiper)
(add-to-list 'load-path "~/Dropbox/source/site-lisp/elpa/multiple-cursors-20150710.456")

(ert-deftest issue-281 ()
  (should (string=
           (let ((temp-buffer (generate-new-buffer " *temp*")))
             (save-window-excursion
               (unwind-protect
                    (progn
                      (switch-to-buffer temp-buffer)
                      (emacs-lisp-mode)
                      (insert "(progn\n  ;; (check-1)\n  (foo)\n  ;; (check-2)\n  (bar)\n  ;; (check-3)\n  (baz))")
                      (goto-char 10)
                      (ivy-with '(swiper ";;") "C-7")
                      (execute-kbd-macro (kbd "DEL DEL C-d C-g"))
                      (buffer-substring-no-properties (point-min)
                                                      (point-max)))
                 (and (buffer-name temp-buffer)
                      (kill-buffer temp-buffer)))))
           "(progn\n  (check-1)\n  (foo)\n  (check-2)\n  (bar)\n  (check-3)\n  (baz))")))
```

Just modify the path for multiple-cursors properly. Then type `make test` into the shell. All tests should pass.

**Comment by ardpp** [comment]
The test doesn't pass for some reasons. The output of `make test` on my laptop with emacs 25.0.50.1 is 
```
emacs -batch -l colir.el -l ivy.el -l swiper.el -l ivy-test.el -f ert-run-tests-batch-and-exit
Running 7 tests (2015-11-03 22:37:37+0100)
Mark saved where search started
Mark saved where search started
Mark saved where search started
```
and then it hangs. Pressing `Control-C` gives 
```
Makefile:10: recipe for target 'test' failed
make: *** [test] Error 2
```

The same happens on my sons computer with emacs  24.5.1. Both use Arch Linux.

**Comment by ardpp** [comment]
Now `make test` gives me the following
```
Running 7 tests (2015-11-05 12:07:45+0100)
Test issue-281 backtrace:
  (progn (add-hook (quote minibuffer-setup-hook) setup-hook) (let* ((h
  (unwind-protect (progn (add-hook (quote minibuffer-setup-hook) setup
  (let ((fun (function ivy--minibuffer-setup)) setup-hook) (setq setup
  (unwind-protect (let ((fun (function ivy--minibuffer-setup)) setup-h
  (prog1 (unwind-protect (let ((fun (function ivy--minibuffer-setup)) 
  (let ((recursive-ivy-last (and (window-minibuffer-p) ivy-last))) (se
  (progn (let ((extra-actions (plist-get ivy--actions-list this-comman
  (progn (let ((--cl-keys-- --cl-rest--)) (while --cl-keys-- (cond ((m
  (let* ((predicate (car (cdr (plist-member --cl-rest-- (quote :predic
  ivy-read("Swiper: " (#(" (progn" 0 1 (display "1 ") 2 7 (face font-l
  (unwind-protect (ivy-read "Swiper: " candidates :initial-input initi
  (let ((candidates (swiper--candidates)) (preselect (buffer-substring
  swiper--ivy(";;")
  swiper(";;")
  eval((swiper ";;"))
  (setq ivy-result (eval ivy-expr))
  ivy-eval()
  funcall-interactively(ivy-eval)
  call-interactively(ivy-eval nil nil)
  command-execute(ivy-eval)
  execute-kbd-macro([3 101 67108919])
  (let ((ivy-expr expr)) (execute-kbd-macro (vconcat (kbd "C-c e") (kb
  ivy-with((swiper ";;") "C-7")
  (progn (switch-to-buffer temp-buffer) (emacs-lisp-mode) (insert "(pr
  (unwind-protect (progn (switch-to-buffer temp-buffer) (emacs-lisp-mo
  (progn (unwind-protect (progn (switch-to-buffer temp-buffer) (emacs-
  (unwind-protect (progn (unwind-protect (progn (switch-to-buffer temp
  (let ((wconfig (current-window-configuration))) (unwind-protect (pro
  (let ((temp-buffer (generate-new-buffer " *temp*"))) (let ((wconfig 
  (list (let ((temp-buffer (generate-new-buffer " *temp*"))) (let ((wc
  (let ((fn-120 (function string=)) (args-121 (list (let ((temp-buffer
  (lambda nil (let ((fn-120 (function string=)) (args-121 (list (let (
  ert--run-test-internal([cl-struct-ert--test-execution-info [cl-struc
  ert-run-test([cl-struct-ert-test issue-281 nil (lambda nil (let ((fn
  ert-run-or-rerun-test([cl-struct-ert--stats t [[cl-struct-ert-test i
  ert-run-tests(t #[385 "\306\307\"\203G\211\211G\310U\203\211@\20
  ert-run-tests-batch(nil)
  ert-run-tests-batch-and-exit()
  command-line-1(("-l" "colir.el" "-l" "ivy.el" "-l" "swiper.el" "-l" 
  command-line()
  normal-top-level()
Test issue-281 condition:
    (quit)
     QUIT  1/7  issue-281
   passed  2/7  ivy--filter
   passed  3/7  ivy--format
   passed  4/7  ivy--regex-fuzzy
   passed  5/7  ivy--split
   passed  6/7  ivy-read
   passed  7/7  swiper--re-builder

Ran 7 tests, 6 results as expected (2015-11-05 12:07:45+0100)
```

**Comment by abo-abo** [comment]
Yes, the test won't work any more. Has anything changed in normal Emacs?

**Comment by ardpp** [comment]
On emacs 25 it started to work. I think that your commit referenced above did the trick but it also seems important to delete the file `.mc-lists.el` which is generated by `multiple-cursors`. When I'm at home I'll check if the same works on my sons laptop with emacs 24.5.

**Comment by abo-abo** [comment]
> important to delete the file .mc-lists.el which is generated by multiple-cursors

Yes, this file can be quite annoying at times. I should have mentioned it, since it should usually be checked any time problems with `multiple-cursors` happen.  It's not necessary to delete it, just check where `swiper-mc` is in those lists and make sure it's on `mc/cmds-to-run-once` and not on `mc/cmds-to-run-for-all`.

**Comment by ardpp** [comment]
Thanks! It is working also with emacs 24.5.
