### ISSUE TITLE
Swiper: minibuffer asks "Highlight user face:"

### ISSUE THREAD

**Issue by veronikazaglotova** [abo-abo/swiper#2811]
![screenshot](https://user-images.githubusercontent.com/52463107/107880105-f2dd2c00-6f06-11eb-9980-a96b6243b764.png)

**Comment by basil-conto** [comment]
> Swiper: minibuffer asks "Highlight user face:"

You haven't said how this happened.  Can you reproduce from `emacs -Q` or `make plain`?

Please try to narrow down which part of your config and which precise steps lead to the issue.

Thanks.

**Comment by veronikazaglotova** [comment]
I can't reproduce the issue with Emacs -Q :(

https://user-images.githubusercontent.com/52463107/107883979-748b8480-6f1c-11eb-9004-182a268f706f.mp4

Here's how it looks like, if it helps

**Comment by veronikazaglotova** [comment]
Here's my init.el
https://github.com/veronikazaglotova/nuemacs/blob/master/init.el

**Comment by basil-conto** [comment]
Sorry, I don't make a habit of (or have the time for) running or trawling through others' init files :).
(Especially when the issue looks completely unrelated to Ivy/Swiper/Counsel.)

Could you please try narrowing down the parts of your config which give rise to the issue, by consecutively commenting out parts of it that make no difference?  Thanks.

**Comment by veronikazaglotova** [comment]
This is also a boon issue.
