### ISSUE TITLE
Explain in documentation how to disable `ivy-on-del-error-function`

### ISSUE THREAD

**Issue by Sir4ur0n** [abo-abo/swiper#2812]
Hi,

I think it would be great to improve the documentation (both in `C-h v ivy-on-del-error-function` and in [Defcustoms doc](http://oremacs.com/swiper/#defcustoms)) to explain how to disable this feature (as in https://github.com/abo-abo/swiper/issues/1799):
```elisp
(setq ivy-on-del-error-function #'ignore)
```

What do you think?

**Comment by basil-conto** [comment]
Isn't it already "documented"? :)

1. `emacs -Q`
2. `M-x package-initialize RET`
3. `M-x load-library RET ivy RET`
4. `M-x customize-variable RET ivy-on-del-error-function RET`
5. `C-s value RET RET`

   This gives the following prompt:

   ```
   Available choices:

   0 = Exit completion
   1 = Do nothing
   2 = Custom function
   ```

If, like me, you don't use the Customize interface, and look at the user option's definition:

```el
(defcustom ivy-on-del-error-function #'abort-recursive-edit
  "Function to call when deletion fails during completion.
The usual reason for `ivy-backward-delete-char' to fail is when
there is no text left to delete, i.e., when it is called at the
beginning of the minibuffer.
The default setting provides a quick exit from completion."
  :type '(choice
          (const :tag "Exit completion" abort-recursive-edit)
          (const :tag "Do nothing" ignore)
          (function :tag "Custom function")))
```

You'll similarly see the hint about using `ignore`.  Since it's a well-known "no-op" function all over Emacs, I'm not sure it's worth explicitly mentioning everywhere.  Do you disagree?  Thanks.

**Comment by Sir4ur0n** [comment]
Thanks for the reply!

I am still young on Emacs so I'm not sure my problem/issue is valid :sweat_smile: 

But the way I found this (lack of) documentation is by looking at the `ivy-on-del-error-function` **variable** documentation, not the "defcustom" definition. (Note: as I use Spacemacs, I think using Customisation directly is not recommended so I got used to read function/variable documentation directly)

If my workflow is invalid/dumb, feel free to close this issue, I won't bother ^^'

**Comment by basil-conto** [comment]
> If my workflow is invalid/dumb

It's neither invalid nor dumb - that's the standard way to look up and set variables, and I appreciate that it's not immediately obvious to everyone that `ignore` can be used as a no-op function everywhere.

My concern was more along the lines of: if `ivy-on-del-error-function` should explicitly document `ignore` as a suitable candidate for a user option that takes on a function value, then shouldn't all similar user options do the same?

Anyway, I've now extended the docstring.  Let me know if it's still unclear.
