### ISSUE TITLE
Case sensitive highlighting in buffer

### ISSUE THREAD

**Issue by fakedrake** [abo-abo/swiper#2814]
Results are matched and are highlighted correctly in the minibuffer but not in the buffer being searched.

![image](https://user-images.githubusercontent.com/408231/108376432-e86aad00-71fa-11eb-8b8a-0be06bd51d43.png)

**Comment by basil-conto** [comment]
I can't reproduce this based on the little information you provided. Please list exactly which steps (keys, commands, ...) you took, ideally starting from `emacs -Q` or `make plain`.

For example, here's what I tried on Emacs versions 24.5, 25.3, 26.3, 27.1, and 28.0:

1. `make plain`
2. `C-x h DEL`
3. ```
   hello
   Hello
   hElLo
   ```
4. `C-s hello`

![2021-02-20-122709_261x337_scrot](https://user-images.githubusercontent.com/9121222/108595377-6f449480-7377-11eb-8f2e-de9a3003dabd.png)

The same happens with the following steps:

1. `emacs -Q`
2. `M-x package-initialize RET`
3. `C-x h DEL`
4. ```
   hello
   Hello
   hElLo
   ```
5. `M-x swiper RET hello`

If you can't reproduce it from `emacs -Q`, then please bisect your `user-init-file` to narrow down the culprit. TIA.

**Comment by fakedrake** [comment]
You are right, it turns out it was `ivy-prescient` that causes the problem. I will take it up with them. Thanks!

**Comment by basil-conto** [comment]
Thanks for confirming!
