### ISSUE TITLE
Using General with ivy gives the following error: Error (use-package): ivy/:init: Wrong type argument: listp, swiper

### ISSUE THREAD

**Issue by aliawan01** [abo-abo/swiper#2828]
Hi, I was trying to use general to set some keybindings which were conflicting with evil mode

I wrote down the following in my config:

```
(use-package ivy
  :after (general evil)
  :diminish

  :init
  (general-define-key 
   :states ''motion
   ("C-s" . swiper)
   :keymaps 'ivy-minibuffer-map
            "TAB"  'ivy-alt-done	
            "C-l"  'ivy-alt-done
            "C-j"  'ivy-next-line
            "C-k"  'ivy-previous-line

   :keymaps 'ivy-switch-buffer-map
            "C-k"  'ivy-previous-line
            "C-l"  'ivy-done
            "C-d"  'ivy-switch-buffer-kill
  
   :keymaps 'ivy-reverse-i-search-map
            "C-k"  'ivy-previous-line
            "C-d"  'ivy-reverse-i-search-kill)

  :config
  (setq ivy-initial-inputs-alist nil)
  (ivy-mode 1))
```

Whenever I try to run this emacs always gives me this same error which i do not know how to solve:

``Error (use-package): ivy/:init: Wrong type argument: listp, swiper
``

I also have counsel and swiper installed if you are wondering.

**Comment by basil-conto** [comment]
I don't use `general.el`, but I just scrolled through its README: https://github.com/noctuid/general.el#evil-examples

It looks like it expects the following syntax:

```el
(general-define-key
 :states 'motion
 "C-s" 'swiper
 ...)
```

Does that solve the problem?  If not, please add `(setq debug-on-error t)` to the start of your `user-init-file` and/or customise `use-package-verbose`, and post the resulting backtrace.

Either way, this doesn't look to me like an issue with `ivy`/`swiper`/`counsel`.

**Comment by aliawan01** [comment]
I tried this and at first it fixed the problem. However once I restart emacs I got this instead:

``
Warning (initialization): An error occurred while loading ‘c:/Users/User/AppData/Roaming/.emacs.d/init.el’:

End of file during parsing: c:/Users/User/AppData/Roaming/.emacs.d/init.el

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the ‘--debug-init’ option to view a complete error backtrace.
``

I also added `(setq debug-on-error t)` at the start of my config file, however I still got the same error.

**Comment by basil-conto** [comment]
> End of file during parsing

That means you're missing a parenthesis somewhere.

**Comment by aliawan01** [comment]
Ok thanks I will check and let you know.

**Comment by aliawan01** [comment]
It ends up I was missing a parenthesis somewhere, I added it and restarted emacs it I do not get any errors. However, the keybindings I set do not work anymore (e..g C-s will not longer open up swiper).

**Comment by basil-conto** [comment]
> It ends up I was missing a parenthesis somewhere, I added it and restarted emacs it I do not get any errors

Thanks for confirming.

> However, the keybindings I set do not work anymore (e.g C-s will not longer open up swiper).

That probably means that you're not using `general.el` correctly (like I said earlier, I don't use it, so my first suggestion was only a guess and after skimming through its README, and based on the error you saw).

For support with using `general.el`, I suggest you read its documentation, and then ask a question on their issue tracker if something is still unclear: https://github.com/noctuid/general.el/issues

Another place to ask specific questions is at https://emacs.stackexchange.com/.

In any case, this issue is about configuring `general.el`, so I'm closing this report on the `swiper` issue tracker for now.
