### ISSUE TITLE
ivy TRAMP navigation from arbitrary directory

### ISSUE THREAD

**Issue by thwg** [abo-abo/swiper#283]
When using `find-file` or `counsel-find-file` to navigate through TRAMP-supported protocols, ivy doesn't seem to bring up any completion matches for filesystem navigation, unless I start at `/` on my local machine.

To reproduce (with `/etc` as current working directory):  `C-x C-f` `<backspace>` `sudo::/` `<tab>`
Additionally (any other directory than `/` as cwd): `C-x C-f` `//sudo::/` `<tab>`

The above displays no matches.  An additional `<tab>` will result in navigation to the dired buffer for `/` (as `root@machine`).  `C-j` and `C-m` do the same.

The following works (with `/` as the current working directory): `C-x C-f` `sudo::/` `<tab>`

I see issue #241, which seems to be similar, but I don't see a solution that works for me there.  I do get completion by using the single `/` or three slash prefix `///` mentioned there, but it comes up in a separate \*Completions\* buffer instead of through ivy for some reason.

**Comment by abo-abo** [comment]
Thanks for noticing, the behavior broke 2 weeks ago.  You can get into TRAMP from any directory with `/ssh:` followed by <kbd>RET</kbd> or <kbd>C-m</kbd>.  You also can get into sudo from any directory with `/sudo:` or `/sudo::` followed by <kbd>RET</kbd> or <kbd>C-m</kbd>.  I think the behavior for `/sudo::` can be improved to move you to the current directory instead of root's home directory. I'll make that change shortly.

**Comment by thwg** [comment]
Aha, I'm starting to see what it is doing.  The additional slash in ivy is required to indicate a TRAMP path.  Your solution does work from any directory.

This works for me, but there's possibly two things that might be better:

`C-x C-f` `/sudo::/` `<tab>` shouldn't pop up a \*Completions\* window.

Backspacing to the root directory `/` or navigating with `//` shouldn't list "sudo:" and others as possible completions.  That made it confusing seeing as how normal Emacs works that way, and then ivy was listing them as possibilities, but not having the expected behavior.

**Comment by abo-abo** [comment]
> Backspacing to the root directory / or navigating with // shouldn't list "sudo:" and others as possible completions.

They are listed by Emacs itself, I don't want to interfere. The problem is that Ivy doesn't have proper handlers for every item of <kbd>//</kbd> yet.  They can be added in the future, eventually.

**Comment by thwg** [comment]
> The problem is that Ivy doesn't have proper handlers for every item of // yet. They can be added in the future, eventually.

Hmm.. I'm not seeing why those two cases should be treated differently though.  ivy should pass the same value in both cases.

Bad (from /etc): `C-x C-f` `<backspace>` `sudo::/` `<tab>` `<tab>`
Good (from /): `C-x C-f` `sudo::/` `<tab>` `<tab>`

I looked through the code and this might be incorrect. Based on the next expression, it looks like `file-directory-p` was supposed to wrap around (I'm thinking it could be a paredit-style typo?):

```emacs-lisp
(and
 (not (equal ivy-text ""))
 (file-directory-p ivy-text)
 (ignore-errors
   (file-directory-p ivy-text))
 (setq dir (expand-file-name
            ivy-text ivy--directory)))
```

And what is actually wanted is:

```emacs-lisp
(and
 (not (equal ivy-text ""))
 (file-directory-p
  (setq dir (expand-file-name
             ivy-text ivy--directory))))
```

Otherwise file-directory-p is just based on the CWD and `ivy-text` instead of `ivy--directory` -- which explains why it only works in `/` for me.

Not sure if I've misevaluated or if it causes other bugs, since I'm not very familiar with the codebase, but basic testing seems to work for both the above cases.  `//` to jump to root and then use tramp also works now based on the suggested completions (without any special cases needed for `//`).

**Comment by abo-abo** [comment]
> Bad (from /etc): C-x C-f <backspace> sudo::/ <tab> <tab>

You're using the compatibility bindings here, left just in case the recommended method breaks.

The recommended method is

- for sudo: <kbd>C-x C-f</kbd> `/sudo::` <kbd>C-j</kbd>.
- for ssh: <kbd>C-x C-f</kbd> `/ssh:` <kbd>C-j</kbd>.

What I meant by <kbd>//</kbd> not working is e.g. <kbd>C-x C-f //</kbd> `sud` <kbd>C-j</kbd>.

In any case, if there's something still missing in your opinion, send a PR, it's easier to look at the code.

**Comment by thwg** [comment]
>> Bad (from /etc): C-x C-f sudo::/

Not sure if that's a mistyping, but I don't mean sudo::/ in the /etc directory.  I mean accessing the qualified "/sudo::/" while the current working directory is /etc.  It happens that you can construct this path quickly with `//` in ivy though.  Or a bunch of backspaces.  I'm not sure if it's a compatibility mode, but it's the one I always ran before.

> What I meant by // not working is e.g. C-x C-f // sud C-j.

This does work at the moment, but your current working directory has to be `/`.

Went ahead and submitted a PR with the proposed change.

**Comment by PythonNut** [comment]
Hi all. I'm was basically asking about the following:

<kbd>C-x</kbd> <kbd>C-f</kbd> `//ssh:user@host:` <kbd>C-j</kbd> seems to prompt for the password and open a `dired` buffer on the remote host. From the description, I expected it to prompt for the password and continue completion.

**Comment by abo-abo** [comment]
@PythonNut If I understood correctly, what you want to do is *not* to open a `dired` buffer, but continue with completion by pressing <kbd>C-j</kbd>.
This *is* the default behavior, or at least it should be; if you have any other behavior report a bug.

What you need to type is <kbd>C-x C-f</kbd> `/ssh:user@host:` <kbd>C-j</kbd>. Note the absence of the leading slash before `ssh`.  What I usually do is just <kbd>C-x C-f</kbd> `/ssh:` <kbd>C-j</kbd>, since then I get host completion.

**Comment by thwg** [comment]
Hey, submitted a PR (#285) with better TRAMP support for `/protocol:` as well as `/path/to//protocol:`.  From what I can tell, they should now support the same features, including host completion.

> C-x C-f //ssh:user@host: C-j seems to prompt for the password and open a dired buffer on the remote host (which is what vanilla emacs would do). From the description, I expected it to prompt for the password and continue completion.

That should be fixed in https://github.com/abo-abo/swiper/commit/6666cf8c863f02d9a81715a7801d7345ed45d942 above. The problem was that it was resolving the directory relative to the CWD, instead of what you had typed in the minibuffer.  This was causing it to fail a conditional and go to the catch-all `(ivy-done)` at the bottom.

I can perform your key sequence and get the correct result with the version in MELPA.  Does your sequence work as expected for you?
