### ISSUE TITLE
[FR] Make `counsel-fzf` sort the entries it feeds to `fzf` by MRU

### ISSUE THREAD

**Issue by NightMachinary** [abo-abo/swiper#2832]
It would be good if `counsel-fzf` sorted the initial data it fed to `fzf` by most recently used.

**Comment by basil-conto** [comment]
> the initial data it fed to `fzf`

What is this referring to?  AFAICT `counsel-fzf` by default only specifies the `--filter=STR` option.

**Comment by NightMachinary** [comment]
[**@basil-conto**](https://github.com/basil-conto) commented on [Mar 27, 2021, 1:26 AM GMT+4:30](https://github.com/abo-abo/swiper/issues/2832#issuecomment-808503267 "2021-03-26T20:56:04Z - Replied by Github Reply Comments"):
> > the initial data it fed to `fzf`
> 
> What is this referring to? AFAICT `counsel-fzf` by default only specifies the `--filter=STR` option.

I thought counsel feeds the file listings to fzf. It seems counsel just uses `FZF_DEFAULT_COMMAND`? Adding MRU necessitates that counsel evals `FZF_DEFAULT_COMMAND` itself, and feed the modified data to `fzf`. Perhaps that's too invasive a change. Feel free to close this issue.

**Comment by basil-conto** [comment]
> It seems counsel just uses `FZF_DEFAULT_COMMAND`?

No, it calls the shell command specified by the user option `counsel-fzf-cmd`.

> Adding MRU necessitates that counsel evals `FZF_DEFAULT_COMMAND` itself, and feed the modified data to `fzf`.

I'm not very familiar with `fzf`, but FWIW `FZF_DEFAULT_COMMAND` is empty in my shell.

> Perhaps that's too invasive a change.

Not necessarily; but I'd have to see it to judge ;).

> Feel free to close this issue.

Okay, closing for now.  If you or anyone else wants to pick this up in the future, we can reopen.  Thanks.
