### ISSUE TITLE
`counsel-switch-buffer-preview-virtual-buffers` do not work as mentioned in the docstring

### ISSUE THREAD

**Issue by swarnendubiswas** [abo-abo/swiper#2833]
Previewing buffers, especially remote, can be a bottleneck with `counsel-switch-buffer`. It seems  from the docstring that one can turn it off with `counsel-switch-buffer-preview-virtual-buffers`. However, setting the variable to `nil` does not work for me. 

I am using Emacs 28 snapshot, and `ivy` and `counsel` are the latest from `melpa`.

**Comment by basil-conto** [comment]
> It seems from the docstring that one can turn it off with `counsel-switch-buffer-preview-virtual-buffers`. However, setting the variable to `nil` does not work for me.

I think "virtual buffers" refers to bookmarked files that are not (yet) being visited, e.g. those in the `recentf` or bookmarks lists.  So this option does not apply to remote buffers specifically.

> Previewing buffers, especially remote, can be a bottleneck with `counsel-switch-buffer`.

Can you please elaborate on where exactly the "bottleneck" occurs, and as a result of which actions exactly?  Can you reproduce the same bottleneck from `emacs -Q` or `make plain`?

FWIW, `ivy-switch-buffer` is like `counsel-switch-buffer`, but without the preview.  If `counsel-switch-buffer` is too slow for your workflow, perhaps you should use that instead, e.g. with minibuffer commands that don't exit completion.

**Comment by swarnendubiswas** [comment]
Ok, that helps. I use `ivy-switch-buffer` instead of `counsel-switch-buffer` for better performance. 

The issue with `counsel-switch-buffer` comes when I am cycling among open buffers and one of them is remote. That introduces a lag in the cycle operation.
