### ISSUE TITLE
M-x man takes too long to provide completions

### ISSUE THREAD

**Issue by iostapyshyn** [abo-abo/swiper#2836]
`M-x man RET` freezes my emacs for around 5-7 seconds on my system to build the completion list every time I invoke it with ivy enabled.

I've used `(add-to-list 'ivy-completing-read-handlers-alist '(man . completing-read-default))` as temporary workaround. I figured it would be a good idea to create an issue anyway.

Here's the profiler report:
```
- command-execute                                                 344  96%
 - call-interactively                                             344  96%
  - funcall-interactively                                         344  96%
   - counsel-M-x                                                  344  96%
    - ivy-read                                                    316  89%
     - ivy-call                                                   144  40%
      - counsel-M-x-action                                        144  40%
       - command-execute                                          144  40%
        - call-interactively                                      130  36%
         - byte-code                                              130  36%
          - completing-read                                       130  36%
           - ivy-completing-read                                  130  36%
            - ivy-read                                            130  36%
             - ivy--reset-state                                    67  18%
              - all-completions                                    66  18%
               - Man-completion-table                              66  18%
                  Man-parse-man-k                                  36  10%
              + ivy-thing-at-point                                  1   0%
             + read-from-minibuffer                                17   4%
        + autoload-do-load                                         14   3%
     + read-from-minibuffer                                        32   9%
     + ivy--reset-state                                             2   0%
    + counsel--M-x-externs                                         28   7%
+ ...                                                               9   2%
+ redisplay_internal (C function)                                   1   0%
+ #<compiled 0x44db5c35>                                            1   0%
```

GNU Emacs 27.2 (build 1, x86_64-apple-darwin18.7.0, Carbon Version 158 AppKit 1671.6) of 2021-03-27
ivy-20210311.1638

**Comment by basil-conto** [comment]
> `M-x man RET` freezes my emacs for around 5-7 seconds on my system to build the completion list every time I invoke it with ivy enabled.

Does this happen if you remove all of your customisations, except plain Emacs+Ivy? For example:

1. `make plain`
2. `M-x man RET`

Alternatively:

1. `emacs -Q`
2. `M-x package-initialize RET`
3. `M-x ivy-mode RET`
4. `M-x man RET`

How do these compare in latency to:

1. `emacs -Q`
2. `M-x man RET TAB`

And:

1. `emacs -Q`
2. `M-x load-library RET man RET`
3. `(benchmark-run 1 (all-completions "" #'Man-completion-table))`
4. `C-j`

On my side, all of these complete in less than a second, barely noticeable:

1. `make plain`
2. ```el
   (progn
     ;; man ls
     (setq unread-command-events (listify-key-sequence "ls\C-m"))
     (profiler-start 'cpu)
     (unwind-protect
         (call-interactively #'man)
       (profiler-report)
       (profiler-stop)
       (profiler-reset)))
   ```
3. `C-x C-e`

This gives the following profile:

```
          36  66% - ...
          36  66%    Automatic GC
          18  33% - command-execute
          18  33%  - call-interactively
          18  33%   - funcall-interactively
          18  33%    - eval-last-sexp
          18  33%     - elisp--eval-last-sexp
          18  33%      - eval
          18  33%       - progn
          18  33%        - progn
          18  33%         - unwind-protect
          17  31%          - call-interactively
          16  29%           - byte-code
          16  29%            - completing-read
          16  29%             - ivy-completing-read
          16  29%              - ivy-read
          14  25%               - ivy--reset-state
          13  24%                - all-completions
          13  24%                 - Man-completion-table
           9  16%                    Man-parse-man-k
           1   1%                - ivy--filter
           1   1%                 - ivy--re-filter
           1   1%                  - cl-remove
           1   1%                     #<compiled 0x12792e003914e66a>
           2   3%               - read-from-minibuffer
           2   3%                - ivy--queue-exhibit
           2   3%                 - ivy--exhibit
           2   3%                  - ivy--update-minibuffer
           1   1%                   - ivy--format
           1   1%                    - cl-subseq
           1   1%                       seq-subseq
           1   1%                   - ivy--filter
           1   1%                    - ivy--re-filter
           1   1%                     - cl-remove
           1   1%                        apply
```

If I replace `make plain` with `emacs -Q` and `ls\C-m` with `\C-ils\C-m`, the profile is actually worse in some ways:

```
         102  97% - ...
          72  68%    Automatic GC
          30  28%  - completing-read-default
          30  28%   - read-from-minibuffer
          30  28%    - command-execute
          30  28%     - call-interactively
          30  28%      - funcall-interactively
          30  28%       - minibuffer-complete
          30  28%        - completion-in-region
          30  28%         - completion--in-region
          30  28%          - #<compiled -0xf07753b79998e2>
          30  28%           - apply
          30  28%            - #<compiled 0x1e0baf29166ecac8>
          30  28%             - completion--in-region-1
          30  28%              - completion--do-completion
          16  15%               - minibuffer-completion-help
          12  11%                - temp-buffer-window-show
          12  11%                 - display-buffer
          12  11%                  - display-buffer-at-bottom
          11  10%                   - window--display-buffer
          11  10%                    - #<compiled -0xb72d9145d4b0825>
          10   9%                     - display-completion-list
           7   6%                      - completion--insert-strings
           2   1%                       - mapcar
           2   1%                          #<compiled 0x663700a687826f3>
           1   0%                   - walk-window-tree
           1   0%                    - walk-window-tree-1
           1   0%                     - #<compiled -0x7e15e0665bc5022>
           1   0%                        window-in-direction
           4   3%                - completion-all-completions
           4   3%                 - completion--nth-completion
           4   3%                  - completion--some
           4   3%                   - #<compiled -0x7463c2702c71862>
           4   3%                    - completion-basic-all-completions
           2   1%                     - completion-hilit-commonality
           2   1%                      - mapcar
           2   1%                       - #<compiled 0x1244e6d4617b3b59>
           1   0%                        - font-lock-prepend-text-property
           1   0%                           font-lock--add-text-property
           1   0%                     - completion-pcm--all-completions
           1   0%                      - all-completions
           1   0%                       - Man-completion-table
           1   0%                          complete-with-action
          14  13%               - completion--field-metadata
          14  13%                - completion-metadata
          14  13%                 - Man-completion-table
           8   7%                    Man-parse-man-k
           3   2% - command-execute
           3   2%  - call-interactively
           3   2%   - funcall-interactively
           3   2%    - eval-last-sexp
           3   2%     - elisp--eval-last-sexp
           3   2%      - eval
           3   2%       - progn
           3   2%        - progn
           2   1%         - unwind-protect
           1   0%            call-interactively
           1   0%            profiler-report
           1   0%           profiler-start
```

Could the latency you see (or part thereof) be macOS-specific?

---

```
ivy-0.13.4.0.20210311.164315
counsel-0.13.4.0.20210322.2839

In GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, X toolkit, cairo version 1.16.0, Xaw3d scroll bars)
 of 2021-03-30 built on tia
Repository revision: 4bfcfdb41638f37c89c0db8f297707773c677656
Repository branch: master
Windowing system distributor 'The X.Org Foundation', version 11.0.12010000
System Description: Debian GNU/Linux bullseye/sid

Configured using:
 'configure 'CC=ccache gcc' 'CFLAGS=-O2 -march=native' --config-cache
 --prefix=/home/blc/.local --enable-checking=structs
 --with-x-toolkit=lucid --with-file-notification=yes --with-x'

Configured features:
ACL CAIRO DBUS FREETYPE GIF GLIB GMP GNUTLS GPM GSETTINGS HARFBUZZ JPEG
JSON LCMS2 LIBOTF LIBSELINUX LIBSYSTEMD LIBXML2 M17N_FLT MODULES NOTIFY
INOTIFY PDUMPER PNG RSVG SOUND THREADS TIFF TOOLKIT_SCROLL_BARS X11
XAW3D XDBE XIM XPM LUCID ZLIB

Important settings:
  value of $LANG: en_IE.UTF-8
  value of $XMODIFIERS: @im=ibus
  locale-coding-system: utf-8-unix
```

**Comment by iostapyshyn** [comment]
Thank you for looking into this!

I tried all of the above and the results stay similar throughout - clear delay of 5-7 seconds, with or without ivy.

1. `emacs -Q`
2. `M-x load-library RET man RET`
3. `(benchmark-run 1 (all-completions "" #'Man-completion-table))`
4. `C-j`

yields `(6.977849 11 0.0979500000000001)`

```
(progn
  ;; man ls
  (setq unread-command-events (listify-key-sequence "ls\C-m"))
  (profiler-start 'cpu)
  (unwind-protect
      (call-interactively #'man)
    (profiler-report)
    (profiler-stop)
    (profiler-reset)))
```

yields
```
- command-execute                                                 114  73%
 - call-interactively                                             114  73%
  - funcall-interactively                                         114  73%
   - eval-last-sexp                                               114  73%
    - elisp--eval-last-sexp                                       114  73%
     - eval                                                       114  73%
      - progn                                                     114  73%
       - progn                                                    114  73%
        - unwind-protect                                          113  72%
         - call-interactively                                     107  69%
          - byte-code                                              96  61%
           - completing-read                                       88  56%
            - ivy-completing-read                                  88  56%
             - ivy-read                                            88  56%
              - ivy--reset-state                                   83  53%
               - all-completions                                   83  53%
                - Man-completion-table                             83  53%
                   Man-parse-man-k                                 43  27%
                   complete-with-action                             1   0%
              - read-from-minibuffer                                4   2%
               - ivy--queue-exhibit                                 4   2%
                - ivy--exhibit                                      4   2%
                 - ivy--insert-minibuffer                           2   1%
                    ivy--resize-minibuffer-to-fit                   2   1%
                 - ivy--update-minibuffer                           2   1%
                  - ivy--filter                                     2   1%
                   - ivy--re-filter                                 2   1%
                    - cl-remove                                     2   1%
                     - apply                                        2   1%
                        cl-delete                                   1   0%
             require                                                1   0%
           - custom-declare-variable                                1   0%
            - custom-initialize-reset                               1   0%
             - eval                                                 1   0%
              - funcall                                             1   0%
                 #<compiled 0x1feac56e59f1>                         1   0%
          - funcall-interactively                                   8   5%
           - man                                                    8   5%
            - Man-getpage-in-background                             8   5%
             - Man-mode                                             4   2%
                imenu-add-to-menubar                                1   0%
             - start-process                                        2   1%
                apply                                               2   1%
           profiler-report                                          2   1%
          profiler-start                                            1   0%
- ...                                                              41  26%
   Automatic GC                                                    40  25%
 + regexp-opt-group                                                 1   0%
```

> Could the latency you see (or part thereof) be macOS-specific?

I don't think I have any other system around to test, but I did try it in the official source tree as opposed to [emacs-mac fork](https://bitbucket.org/mituharu/emacs-mac/src/master/), which I normally use. The results were more or less the same.

```
In GNU Emacs 27.2 (build 1, x86_64-apple-darwin20.3.0, Carbon Version 164 AppKit 2022.3)
 of 2021-04-01 built on mbp2018.local
Windowing system distributor 'Apple Inc.', version 11.2.3
System Description:  macOS 11.2.3

Configured using:
 'configure --enable-locallisppath=/usr/local/share/emacs/site-lisp
 --infodir=/usr/local/Cellar/emacs-mac/emacs-27.2-mac-8.2/share/info/emacs
 --prefix=/usr/local/Cellar/emacs-mac/emacs-27.2-mac-8.2 --with-mac
 --enable-mac-app=/usr/local/Cellar/emacs-mac/emacs-27.2-mac-8.2
 --with-gnutls --with-modules --with-mac-metal'

Configured features:
NOTIFY KQUEUE ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS XIM MODULES
THREADS JSON PDUMPER GMP
```

**Comment by basil-conto** [comment]
> I tried all of the above and the results stay similar throughout - clear delay of 5-7 seconds, with or without ivy.
> 
> 1. `emacs -Q`
> 2. `M-x load-library RET man RET`
> 3. `(benchmark-run 1 (all-completions "" #'Man-completion-table))`
> 4. `C-j`
> 
> yields `(6.977849 11 0.0979500000000001)`

Then there's not much Ivy can do about this latency with the built-in completion table.  If you think this can be sped up on macOS, then please consider saying so upstream via `M-x report-emacs-bug RET`.

Out of curiosity, what does evaluating the following give you?

```el
(progn
  (require 'man)
  (length (all-completions "" #'Man-completion-table)))
```

On my system it's just shy of 15K.

Anyway, realistically I can think of only two ways to avoid the latency on your system:
1. Use caching.

   The built-in `man` command disables `Man-completion-cache` before calling `Man-completion-table`.  Perhaps if we called `Man-completion-table` directly we could avoid some latency in subsequent calls.

   Alternatively, we could try caching results on our end using `lazy-completion-table`.

   The assumption being that your list of manpages doesn't change frequently.

2. Reimplement `Man-completion-table`, maybe as a `:dynamic-collection`. No idea how feasible this is.

**Comment by iostapyshyn** [comment]
I have found a solution for this. The default Mac man program doesn't seem to cache anything, and invoking man -k is what really was taking all the time, since I suppose it was searching the directories:
```
$ time (man -k emacs > /dev/null)
real	0m6.621s
user	0m0.573s
sys	0m2.858s
```

Luckily Homebrew provides `man-db`, which is the implementation used on most linux systems. It uses a cache which is built by running `mandb`. Building that cache and setting `manual-program` to `gman` results in instant completion. Looks like the cache has to be rebuilt manually after installing new pages though.

**Comment by basil-conto** [comment]
Thanks for reporting back.

> Looks like the cache has to be rebuilt manually after installing new pages though.

I know for sure that on my Debian system it runs automatically whenever a package installs new manuals.  Perhaps you could set up a cronjob if that doesn't happen automatically on macOS.

**Comment by mizlan** [comment]
@iostapyshyn it seems like gman reports much fewer results than man on macOS however...? Did you experience that?
