### ISSUE TITLE
Feature Request: Add minimum query length option to Counsel-rg

### ISSUE THREAD

**Issue by JordanAnthonyKing** [abo-abo/swiper#2850]
I'm running doom on gccemacs on Ubuntu.

Counsel-rg only requires a single character to begin searching. I've not been able to find a setting to increase this minimum to a more sane 2. When I perform a search the first character gets entered, then emacs hangs for a short while as the query executes. Once the initial query has executed the rest of my typed query will be populated and search will be performant. This also has the added side effect that the initial character will get entered twice, requiring me to go back and delete it.

This experience is not the most preferable.

**Comment by basil-conto** [comment]
> Counsel-rg only requires a single character to begin searching.

That's not what happens by default. For example, with `counsel` installed in `package-user-dir`:

1. `emacs -Q`
2. `M-x package-initialize RET`
3. `M-x counsel-rg RET`

   ![2021-04-17-193044_1920x1080_scrot](https://user-images.githubusercontent.com/9121222/115123225-f6973880-9fb3-11eb-9724-6e9872bb2b0c.png)

4. `co`

   ![2021-04-17-193046_1920x1080_scrot](https://user-images.githubusercontent.com/9121222/115123242-00b93700-9fb4-11eb-8207-77548f481dee.png)

5. `unsel`

   ![2021-04-17-193051_1920x1080_scrot](https://user-images.githubusercontent.com/9121222/115123257-0c0c6280-9fb4-11eb-8657-599c3a8bc91e.png)

This is controlled by the user option `ivy-more-chars-alist`, which by default requires 3 characters for all asynchronous search commands, except `counsel-grep`, which by default requires 2 characters.

In my personal session, I customise this variable to require only 2 characters of input for `counsel-rg`:

![output-2021-04-17-19:42:11](https://user-images.githubusercontent.com/9121222/115123483-25fa7500-9fb5-11eb-867d-37ecd3760fff.gif)

Are you sure you don't have a modified `ivy-more-chars-alist` in your configuration? Can you reproduce the issue from `emacs -Q` or `make plain`?

**Comment by JordanAnthonyKing** [comment]
Thanks for this, I'm using doom-emacs, who seem to have modified it to:
```
((counsel-rg . 1)
 (counsel-search . 2)
 (t . 3))
```
Adding `(add-to-list 'ivy-more-chars-alist '(counsel-rg . 2))` to my config solved the issue for me.

**Comment by basil-conto** [comment]
Thanks for confirming.
