### ISSUE TITLE
Using rgrep with ivy prepends file mask with path

### ISSUE THREAD

**Issue by alex-glv** [abo-abo/swiper#286]
When invoking rgrep there are three step to complete search:
 - Search for string
 - File mask
 - Path

On second step when setting file mask, the mask is prepended with current path

Steps to reproduce:
 - invoke rgrep
 - insert search string
Second step is shown with prefix:
``` 27   Search for "xxxx" in files (default *.c): ~/dir ```
The completion list contains directories list.

Is it a configuration issue?

Thanks.

**Comment by abo-abo** [comment]
> The completion list contains directories list.

This is the way `rgrep` wants it to be (it specifically requests file completion), nothing I can do here. The intent is that you can either enter a pattern, like `*.c`, or select a single file.  In any case, if you enter `*.c` it still works, right?

**Comment by alex-glv** [comment]
Yes, it does work in fact! thanks.
