### ISSUE TITLE
[feature request] counsel-org-goto-all option to make long results show as wrapped multi line?

### ISSUE THREAD

**Issue by rieje** [abo-abo/swiper#2863]
I have quite a few headlines that are lengthy and/or have many children (breadth-wise and/or depth-wise). That means these headlines will surpass the width of the Emacs window and there appear to be many of the same results unless I narrow the search further (which is difficult without more context from the results). A way to deal with this might be to make result entries that extend past the width of the Emacs wrapped multi-line.

**Comment by basil-conto** [comment]
Does setting `ivy-truncate-lines` to `nil` make any difference?

**Comment by rieje** [comment]
Ahh yes, that's what I'm looking for. I suppose it applies to all commands including swiper and it's not possible to disable it just for swiper (where I prefer single lines), right? Thanks.

**Comment by basil-conto** [comment]
> I suppose it applies to all commands

By default, yes.

> it's not possible to disable it just for swiper

You could try modifying for specific commands using e.g. `ivy-hooks-alist` or function advice.
