### ISSUE TITLE
[Q] How to reuse counsel-M-x with different initial inputs?

### ISSUE THREAD

**Issue by introom** [abo-abo/swiper#2866]
I'd like to define several commands, for example, command-a, command-b, command-c, which when invoked, will have the initial inputs as: ^a, ^b, and ^c.  All other things are equal to counsel-M-x.

The dedicated commands for ^a, ^b, ^c help to limit the search scope.

**Comment by basil-conto** [comment]
What about something like this:

```el
(defun my-command-a ()
  "Start `counsel-M-x' with initial input \"^a\"."
  (interactive)
  (counsel-M-x "^a"))

(defun my-command-b ()
  "Start `counsel-M-x' with initial input \"^b\"."
  (interactive)
  (counsel-M-x "^b"))

(defun my-command-c ()
  "Start `counsel-M-x' with initial input \"^c\"."
  (interactive)
  (counsel-M-x "^c"))
```

You can also customise initial inputs per-command via `ivy-initial-inputs-alist` and `ivy-hooks-alist`.

**Comment by introom** [comment]
Great. Thanks.
