### ISSUE TITLE
Bug with swiper-avy

### ISSUE THREAD

**Issue by dionisos2** [abo-abo/swiper#2867]
Hi,
When I run emacs -Q
then I evaluate :
```elisp
(add-to-list 'load-path "/home/dionisos/.emacs.d/elpa/ivy-20210506.2157/")
(add-to-list 'load-path "/home/dionisos/.emacs.d/elpa/swiper-20210509.1535/")
(add-to-list 'load-path "/home/dionisos/.emacs.d/elpa/avy-20201226.1734/")

(setq debug-on-error 2)
(require 'avy)
(require 'ivy)
(require 'swiper)
```

After this I run swiper-isearch and then I enter just "u" in the minibuffer, and I do C-' (to call swiper-avy) I get this error 

```elisp
Debugger entered--Lisp error: (wrong-type-argument sequencep 11)
  swiper--update-input-ivy()
  swiper-avy()
  funcall-interactively(swiper-avy)
  call-interactively(swiper-avy nil nil)
  command-execute(swiper-avy)
  read-from-minibuffer("Swiper: " nil (keymap (keymap (18 . swiper-isearch-C-r) (27 keymap (110 . swiper-isearch-thing-at-point)) keymap (3 keymap (6 . swiper-toggle-face-matching)) (67108919 . swiper-mc) (67108903 . swiper-avy) (12 . swiper-recenter-top-bottom) (27 keymap (113 . swiper-query-replace)) (19 . swiper-C-s)) keymap (36 . ivy-magic-read-file-env) (3 keymap (19 . ivy-rotate-sort) (1 . ivy-toggle-ignore) (15 . ivy-occur)) (33554464 . ivy-restrict-to-matches) (15 . hydra-ivy/body) (22 . ivy-scroll-up-command) (prior . ivy-scroll-down-command) (next . ivy-scroll-up-command) (7 . minibuffer-keyboard-quit) (right . ivy-forward-char) (32 . self-insert-command) (18 . ivy-reverse-i-search) (remap keymap (describe-mode . ivy-help) (kill-ring-save . ivy-kill-ring-save) (kill-whole-line . ivy-kill-whole-line) (kill-line . ivy-kill-line) (scroll-down-command . ivy-scroll-down-command) (scroll-up-command . ivy-scroll-up-command) (end-of-buffer . ivy-end-of-buffer) (beginning-of-buffer . ivy-beginning-of-buffer) (kill-word . ivy-kill-word) (forward-char . ivy-forward-char) (delete-char . ivy-delete-char) (backward-kill-word . ivy-backward-kill-word) (backward-delete-char-untabify . ivy-backward-delete-char) (delete-backward-char . ivy-backward-delete-char) (previous-line . ivy-previous-line) (next-line . ivy-next-line)) (9 . ivy-partial-or-done) (10 . ivy-alt-done) (27 keymap (1 . ivy-read-action) (15 . ivy-dispatching-call) (111 . ivy-dispatching-done) (25 . ivy-insert-current-full) (105 . ivy-insert-current) (106 . ivy-yank-word) (114 . ivy-toggle-regexp-quote) (97 . ivy-toggle-marks) (16 . ivy-previous-line-and-call) (14 . ivy-next-line-and-call) (118 . ivy-scroll-down-command) (112 . ivy-previous-history-element) (110 . ivy-next-history-element) (10 . ivy-immediate-done) (13 . ivy-call)) (mouse-3 . ivy-mouse-dispatching-done) (mouse-1 . ivy-mouse-done) (down-mouse-1 . ignore) (13 . ivy-done)) nil swiper-history)
  ivy-read("Swiper: " swiper-isearch-function :initial-input nil :keymap (keymap (18 . swiper-isearch-C-r) (27 keymap (110 . swiper-isearch-thing-at-point)) keymap (3 keymap (6 . swiper-toggle-face-matching)) (67108919 . swiper-mc) (67108903 . swiper-avy) (12 . swiper-recenter-top-bottom) (27 keymap (113 . swiper-query-replace)) (19 . swiper-C-s)) :dynamic-collection t :require-match t :action swiper-isearch-action :re-builder swiper--re-builder :history swiper-history :extra-props (:fname nil) :caller swiper-isearch)
  swiper-isearch()
  funcall-interactively(swiper-isearch)
  call-interactively(swiper-isearch record nil)
  command-execute(swiper-isearch record)
  execute-extended-command(nil "swiper-isearch" nil)
  funcall-interactively(execute-extended-command nil "swiper-isearch" nil)
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)
```

I can’t reproduce it with the "make plain" functionality. (I tried to investigate but my elisp is way to poor)

I also have a problem with the wrong line being sectioned, but it is harder to reproduce and I hope both problems are linked.

My version of emacs is : GNU Emacs 27.2

**Comment by dionisos2** [comment]
> > I can’t reproduce it with the "make plain" functionality.
> 
> It's the same story:
> 
>     1. `make plain`
> 
>     2. `(setq debug-on-error t) C-x C-e`
> 
>     3. `M-x swiper-isearch RET u C-'`
> 
> 
> > I also have a problem with the wrong line being sectioned
> 
> Yeah it's a mess :(.

Oh this is strange, I tried what you wrote and I got the bug, but before this, I don’t know exactly what I did, but it worked without a bug with "make plain". (this is why I said I can’t reproduce with this, I should have tried exactly the same thing on both)

**Comment by basil-conto** [comment]
> It is probably not helpful, but I tried a bisect and the bug is here since at least [commit](https://github.com/abo-abo/swiper/commit/704b1de38ce202ecec307f244ff46d071bbe02ee)
> Before this I could not test because it was requiring avy.

Thanks.

I haven't done any further debugging or bisecting, but my crystal ball says the issue started around commit 4d40f88b0ececeda831faaa0e997387373b7579a, because that's when `swiper-isearch` candidates changed from being buffer substrings to being buffer positions (the error you see happens because `swiper--update-input-ivy`, which was written for `swiper`, expects the current candidate to be a string, but in `swiper-isearch` candidates are numbers).

**Comment by dionisos2** [comment]
Hi,
I am trying bounty hunter, and I put a [bounty](https://www.bountysource.com/issues/98425467-bug-with-swiper-avy) on this issue.

**Comment by basil-conto** [comment]
> I haven't done any further debugging or bisecting, but my crystal ball says the issue started around commit [4d40f88](https://github.com/abo-abo/swiper/commit/4d40f88b0ececeda831faaa0e997387373b7579a), because that's when `swiper-isearch` candidates changed from being buffer substrings to being buffer positions

PR #2873 should hopefully avoid the error, but I'm still dissatisfied with the state of `swiper-avy`.

With a single character of input, selecting one of the `swiper-avy` candidates displayed in the minibuffer leaves point at the wrong line (in-buffer candidates should work fine though).  I don't understand the line calculations in `swiper--avy-goto` and am afraid to change them.  Hopefully someone else understands better.

But for now, please let me know if #2873 makes things a bit better without breaking anything.

Thanks.

**Comment by dionisos2** [comment]
> PR #2873 should hopefully avoid the error, but I'm still dissatisfied with the state of `swiper-avy`.

Thanks, you can claim the bounty if you want.

> With a single character of input, selecting one of the `swiper-avy` candidates displayed in the minibuffer leaves point at the wrong line (in-buffer candidates should work fine though). I don't understand the line calculations in `swiper--avy-goto` and am afraid to change them. Hopefully someone else understands better.

I discovered something by doing some tests, by example if I try to go on the 6th line with swiper-avy, it go on the 6th occurrence found (so if there are many occurrences by line, it goes on the wrong line).

> In the meantime, please let me know if #2873 makes things a bit better without breaking anything.
> 
> Thanks.

I didn’t test it extensively but it seems to work, thanks.

**Comment by basil-conto** [comment]
> I discovered something by doing some tests, by example if I try to go on the 6th line with swiper-avy, it go on the 6th occurrence found (so if there are many occurrences by line, it goes on the wrong line).

Thanks, that helped me find what feels like a kludge but that seems to work.

Can you please confirm whether `swiper-avy` works properly with `swiper`/`swiper-isearch` in the updated PR #2873, and that I'm not just imagining it?

**Comment by basil-conto** [comment]
> Thanks, you can claim the bounty if you want.

Thanks, it's a nice gesture, but I'd rather not do this for money :).

**Comment by dionisos2** [comment]
> Thanks, that helped me find what feels like a kludge but that seems to work.
> 
> Can you please confirm whether `swiper-avy` works properly with `swiper`/`swiper-isearch` in the updated PR #2873, and that I'm not just imagining it?

I did some tests and it seems to work :-)
Thanks, I find this functionality pretty useful, I think I will try to activate it by default each time I did a swiper search.

> Thanks, it's a nice gesture, but I'd rather not do this for money :)

Take it more like a gift to thanks you for your help on this project (I see you answer to a lot of issues).
If you want obviously. (anyway I already sent the money on bounty source to create the bounty).

**Comment by basil-conto** [comment]
> I did some tests and it seems to work :-)

Great, thanks for confirming!  I've now pushed the fix to [GNU-devel ELPA](https://elpa.gnu.org/devel/swiper.html) where it should hopefully appear within a few hours.

> Take it more like a gift to thanks you for your help on this project (I see you answer to a lot of issues).
If you want obviously. (anyway I already sent the money on bounty source to create the bounty).

Hm okay I'll oblige and take the burden off your hands ;).  I'm having some issues registering with Bountysource though, so it may take a while.  Thanks again for your help and support for this project!
