### ISSUE TITLE
counsel-find-file,when file path too long,sometimes minibuffer file items hidden.

### ISSUE THREAD

**Issue by doneself** [abo-abo/swiper#2869]
![https://emacs-china.org/uploads/default/optimized/2X/d/d214d5a73996da8953b9f9e0f3176a1a86a94c7b_2_1033x289.jpeg](https://emacs-china.org/uploads/default/optimized/2X/d/d214d5a73996da8953b9f9e0f3176a1a86a94c7b_2_1033x289.jpeg)

**Comment by basil-conto** [comment]
Any chance of a precise recipe for reproducing this? What's your version of Emacs, Ivy, and Counsel?

I only ever see the first line wrap around to a second line.

**Comment by doneself** [comment]
Windows 10
Emacs 27.1
counsel-20210509.830
ivy-20210114.1859

I think maybe my file path contain some Chinese characters , so cause that issue.

my path similar to this:
d:/Tom/Job/不定向通用平台资源网站/Codes/sexxxxx-cccccccc-portal/sexxxxx-encccccccc-admin/src/views/modules/citydoor/arcccccccc.vue

**Comment by basil-conto** [comment]
Thanks, I think commit e8ac2e23ffccb23600c5a3883805560927a54202 should address the horizontal scrolling, could you please check?

I'm still not happy with the manual line breaking further on though:

https://github.com/abo-abo/swiper/blob/e8ac2e23ffccb23600c5a3883805560927a54202/ivy.el#L3125-L3132

This manually inserts a newline every `window-width` characters, which is a terrible way of breaking lines as it does not take the characters or the display engine into account.  Unless someone beats me to it, I'll try to have a look when I find more time.

**Comment by doneself** [comment]
I tried, and it seemed to work well, thanks.

**Comment by basil-conto** [comment]
> I tried, and it seemed to work well, thanks.

Thanks for confirming.

> This manually inserts a newline every `window-width` characters, which is a terrible way of breaking lines as it does not take the characters or the display engine into account. It can result in parts of the directory name being truncated. Unless someone beats me to it, I'll try to have a look when I find more time.

I tried improving this in commit 7c5d49f84f0919bbf00c53a9db48630adf8b2fbe (also pushed to [GNU-devel ELPA](https://elpa.gnu.org/devel/ivy.html)).

Let me know if you find any issues with it.
