### ISSUE TITLE
Cycling swiper results

### ISSUE THREAD

**Issue by wiz21b** [abo-abo/swiper#2878]
Hello,

I noticed that when I use regular emacs search-forward, it cycles to the topmost search result when it reaches the last result of the buffer. Swiper seems to not do that. I looked at the defcustom (and the issues) but found nothing that seems to enable that behavior. Is there a reason why that cycling is not supported ? I may have time to do it myself but before diving I wanted to know if there were showstoppers or if I'd just missed something obvious.

Thx for that cool package !

**Comment by basil-conto** [comment]
Have you tried enabling `ivy-wrap`?

**Comment by wiz21b** [comment]
Argh, my mistake. I leraned about swiper on the web, but I didn't understand that swiper is part of something bigger.. Now I see the options I wanted. Thanks for pointing out !

**Comment by basil-conto** [comment]
No problem, glad that's what you were looking for.
