### ISSUE TITLE
switch to another command without losing what you have typed

### ISSUE THREAD

**Issue by jkitchin** [abo-abo/swiper#2884]
Is there something analogous to https://github.com/oantolin/embark#switching-to-a-different-command-without-losing-what-youve-typed with ivy?

The idea is you start a command and type some things in, but realize you need to use that input for another command. There is a nice example in that link of the use where you start witching to a buffer, but realize the file isn't open and want to pass the input to find-file for example.

Another example would be starting swiper, not finding anything in the current buffer, and then passing the input to swiper-all or counsel-grep.

 For me it is often I run `counsel-describe-function` (C-h f) start typing something, and realize it should have been `counsel-describe-variable` (C-h v). I guess by analogy the key presses might look like this:

C-h f ivy-text M-o B C-h v

any ideas? Thanks.

Update:

This is close to what I want:

```
(defun switch-command (&optional &rest _args)
  (interactive)
  (let* ((input ivy-text)
	 (cmd (intern (first (last (split-string  (describe-key-briefly (help--read-key-sequence 'no-mouse-movement)))))))
	 (ivy-initial-inputs-alist `((,cmd . ,input))))
    (keyboard-escape-quit)
    (call-interactively cmd)))
```

Then I add this as an action with ivy-set-actions bound to "B". I have swiper-all bound to H-s

Suppose I start swiper and type in "test", with no hits. Then, with this, I type M-o B H-s and it transfers the text "test" to a new swiper-all completion. It isn't ideal, `describe-key-briefly` prompts for a key that isn't exactly what I would like, but it is faster than trying to use counsel-M-x to find the command you want. If there is a quicker way to go from a key sequence to command it might be better, and if there was a way to take either M-x command or key sequence it might be better still. I think it would be better still if I could avoid M-o and just do something like M-B in the minibuffer, but I didn't make that work too well.

**Comment by basil-conto** [comment]
> If there is a quicker way to go from a key sequence to command it might be better

Quicker in what way?  I would have written something like the following for looking up the command bound to a key sequence:

```el
(key-binding (read-key-sequence "Switch to key sequence: ") t)
```

> if there was a way to take either M-x command or key sequence it might be better still

How do you envision that UI? Try reading a key sequence first, and if that fails (e.g. in case of `C-g`), invoke `read-command` instead?

> I think it would be better still if I could avoid M-o and just do something like M-B in the minibuffer, but I didn't make that work too well.

What did you try, and what didn't work well?

In general, you can:

- bind any custom command you want in `ivy-minibuffer-map` (to avoid going through `M-o`)
- use `ivy-quit-and-run` to quit the current completion session and do something else, like starting a new completion session with a different command
- use `ivy-hooks-alist` instead of `ivy-initial-inputs-alist` if you want to add a function that e.g. inserts some initial text and then removes itself from the hook, so that it only takes effect once
- use `minibuffer-with-setup-hook` to insert some initial text in the minibuffer for arbitrary commands, not just Ivy-backed ones.

HTH, and with more details I can also give more concrete suggestions/examples.

**Comment by jkitchin** [comment]
Thanks, that was very helpful! I am currently doing this now (mostly thanks to your excellent suggestions above):

```
    (defun scimax-ivy-become (&rest _args)
      (interactive) 
      (ivy-quit-and-run
	(let* ((cmd (key-binding (read-key-sequence "Switch to key sequence: ") t))
	       (transfer-input `(lambda ()
				  (insert ,ivy-text))))
	  (minibuffer-with-setup-hook
	      (:append transfer-input)
	    (call-interactively cmd)))))

    (define-key ivy-minibuffer-map (kbd "C-M-b") 'scimax-ivy-become)
```

Now, suppose I start swiper (C-s) and type a few chars, realize it should be swiper-all (bound to H-s), then I just type `C-M-b H-s` and I get a new completion with swiper-all, and if I do `C-M-b H-p ss` then it switches with that input to projectile-ag (which H-p ss is bound to) or if I do `C-M-b M-x` I get counsel-M-x with that input. 

The only think I am not crazy about is emacs beeps when I run the C-M-b command, like it does with keyboard-quit (C-g), but it is also a little reminder to enter a new key.

I think I can close this now.

**Comment by basil-conto** [comment]
> I am currently doing this now

I recommend capturing state outside of the timer function that `ivy-quit-and-run` uses, as well as using a proper closure rather than a quoted `lambda` list:

```el
(defun scimax-ivy-become ()
  (interactive)
  (let* ((input ivy-text)
         (transfer-input (lambda () (insert input)))
         (cmd (key-binding (read-key-sequence "Switch to key sequence: ") t)))
    (ivy-quit-and-run
      (minibuffer-with-setup-hook
	  (:append transfer-input)
	(call-interactively cmd)))))
```

> The only think I am not crazy about is emacs beeps when I run the C-M-b command, like it does with keyboard-quit (C-g), but it is also a little reminder to enter a new key.

But that also happened with `keyboard-escape-quit`, right?  Does binding `ring-bell-function` to `ignore` around `ivy-quit-and-run` make any difference?

**Comment by jkitchin** [comment]
That function gives me an error `(void-variable transfer-input)`.  I couldn't tell that let-binding ring-bell-function made a difference, I still hear the bell.

**Comment by basil-conto** [comment]
> That function gives me an error `(void-variable transfer-input)`

That just means you're evaluating the function with `lexical-binding` disabled, e.g. in `*scratch*` with `eval-buffer`.

If you're on Emacs 27+, `*scratch*` uses `lexical-binding` by default, so just evaluate the function with `C-x C-e` or `C-j` instead.

On older Emacs versions, you have to first enable `lexical-binding` in `*scratch*`, e.g. via `(setq lexical-binding t)`.

If the code in question is in a `.el` file, then please immediately as a matter of national safety and for the sanity of everyone involved add a

```el
;; -*- lexical-binding: t -*-
```
cookie to the first line in the file and then try again, thanks :).

[I'm being facetious, but I do think `lexical-binding` should be the default in general.]

>  I couldn't tell that let-binding ring-bell-function made a difference, I still hear the bell.

Sorry, it was a shot in the dark. I don't know which code beeps on quit, and always disable audible bells.

**Comment by jkitchin** [comment]
Wonderful, I should have figured that was the problem, thanks! I have that setting in many files, but not the one I was working in.

**Comment by jkitchin** [comment]
ok, here is my final version (I think) that does not have the bell sound

```
    (defun scimax-ivy-become ()
      "Change the command and reuse the current input.
    You will be prompted to enter a new key sequence which can be a
    shortcut or M-x. Then it will put the current input in the
    minibuffer for the command.

    Applications:
    1. start with swiper, C-M-b H-s to transfer the current input to swiper-all
    2. C-xC -b to switch-buffer, C-M-b C-x C-f to transfer input to find-file."
      (interactive)
      (let* ((input ivy-text)
             (transfer-input (lambda () (insert input))))
	(ivy-exit-with-action
	 (lambda (x)
	   (minibuffer-with-setup-hook
	       (:append transfer-input)
	     (call-interactively (key-binding (read-key-sequence "Switch to key sequence: ") t)))))))
```
