### ISSUE TITLE
Counsel: Find files only in the specific folder and all subfolders?

### ISSUE THREAD

**Issue by alexei-28** [abo-abo/swiper#2885]
`CentOS 7, Emacs 27.2, Ivy, Swiper, Counsel package.`

In **Temp** folder I has different files. I want to find by `counsel_locate` all text files only in this folder.

I try this:
![s1](https://user-images.githubusercontent.com/303539/121135477-39032600-c83d-11eb-939e-1cc86e650206.png)
![s2](https://user-images.githubusercontent.com/303539/121135499-3e607080-c83d-11eb-94ee-237554441afa.png)
![s3](https://user-images.githubusercontent.com/303539/121135523-428c8e00-c83d-11eb-913f-b4688a8e9f76.png)

As you can see I use command `M-x counsel-locate .txt `but the counsel find **ALL** text files in whole HDD. But I need to find all text files **ONLY** in the folder **Temp** and all subfolders.

Is it possible by package **counsel** ?

**Comment by basil-conto** [comment]
Please don't double-post on Emacs SE and this issue tracker.

Quoting my answer from https://emacs.stackexchange.com/a/66216/15748 :

---

`counsel-locate` essentially just calls the system `locate` command (see [`man 1 locate`](https://man7.org/linux/man-pages/man1/locate.1.html)).

You can control which executable is called by customising the user option `locate-command` from the built-in package `locate.el`.

You can further control the exact command that `counsel-locate` issues by customising the user option `counsel-locate-cmd`.

On GNU/Linux, the default command issued by `counsel-locate` is:

```sh
locate -i --regex REGEXP
```

where `REGEXP` is the user input interpreted as a [regular expression](https://www.gnu.org/software/emacs/manual/html_node/emacs/Regexps.html).

So, to find any `.txt` files under any directory called `Temp`, you need an input like `Temp \.txt\'` or `Temp.*\.txt\'` (note that the literal full stop `.` has to be escaped, that `\'` anchors the file extension at the end of the file name, and that Ivy translates the first pattern into something equivalent to the second pattern by default).

To find any `.txt` files under a specific directory called `Temp`, you need an input like
```
\`/home/alexeij/Temp \.txt\'
```
or
```
\`/home/alexeij/Temp.*\.txt\'
```
Where the
```
\`
```
anchors the search at the start of the file name.

Finally, to start every `counsel-locate` search in the current directory, you can write a custom command like the following based on [adl's answer](https://emacs.stackexchange.com/a/66212/15748):


```el
(defun my-counsel-locate-here ()
  "Start `counsel-locate' anchored at `default-directory'."
  (interactive)
  (counsel-locate (rx bos (literal (file-truename default-directory)) ?\s)))
```

Then you can issue e.g. `M-x my-counsel-locate-here RET \.txt\'` to find all `.txt` files under the current directory.

A more direct (but sometimes slower) way of achieving the same thing is `M-x counsel-file-jump RET \.txt\'`.

For a fuzzy search analogue, there's also e.g. `M-x counsel-fzf RET .txt`.
