### ISSUE TITLE
ivy-restrict-to-matches is broken with counsel-rg

### ISSUE THREAD

**Issue by ambihelical** [abo-abo/swiper#2893]
The output seems to depend on whether I use the git repo or melpa. 

Here is the output for current melpa:

`Error in post-command-hook (ivy--queue-exhibit): (wrong-number-of-arguments (1 . 1) 3)`

Here is the output for repo master:

`Error in post-command-hook (ivy--queue-exhibit): (wrong-number-of-arguments ((locate-command bookmark-alist counsel-yank-pop-truncate-radius smex-ido-cache smex-initialized-p amx-cache info-lookup-mode t) (string) "Grep in the current directory for STRING." (let* ((command-args (counsel--split-command-args string)) (search-term (cdr command-args))) (or (let ((ivy-text search-term)) (ivy-more-chars)) (let* ((default-directory (progn (or (and (memq (type-of ivy-last) cl-struct-ivy-state-tags) t) (signal 'wrong-type-argument (list 'ivy-state ivy-last))) (aref ivy-last 21))) (regex (counsel--grep-regex search-term)) (switches (concat (if (ivy--case-fold-p string) " -i " " -s ") (counsel--ag-extra-switches regex) (car command-args)))) (counsel--async-command (counsel--format-ag-command switches (funcall (if (listp counsel-ag-command) #'identity #'shell-quote-argument) regex))) nil)))) 3)
`

 Below is the output with the bisected commit used (looks like the same as above, but I haven't checked):

`Error in post-command-hook (ivy--queue-exhibit): (wrong-number-of-arguments ((locate-command bookmark-alist counsel-yank-pop-truncate-radius smex-ido-cache smex-initialized-p amx-cache info-lookup-mode t) (string) "Grep in the current directory for STRING." (let* ((command-args (counsel--split-command-args string)) (search-term (cdr command-args))) (or (let ((ivy-text search-term)) (ivy-more-chars)) (let* ((default-directory (progn (or (and (memq (type-of ivy-last) cl-struct-ivy-state-tags) t) (signal 'wrong-type-argument (list 'ivy-state ivy-last))) (aref ivy-last 21))) (regex (counsel--grep-regex search-term)) (switches (concat (if (ivy--case-fold-p string) " -i " " -s ") (counsel--ag-extra-switches regex) (car command-args)))) (counsel--async-command (counsel--format-ag-command switches (funcall (if (listp counsel-ag-command) #'identity #'shell-quote-argument) regex))) nil)))) 3)
`

I bisected it to this commit:

4dd6acf35ee7360ef5a27bc652bf6837a9408eba is the first bad commit
commit 4dd6acf35ee7360ef5a27bc652bf6837a9408eba
Author: Eder Elorriaga <gexplorer8@gmail.com>
Date:   Thu May 20 14:19:40 2021 +0200

    Make sure completion-metadata is fetched when formatting candidates

I realize my config might be affecting things, but I haven't cut it down to just ivy and counsel.  If necessary I can do this. I am hoping this is easily reproduced, and I won't have to.

**Comment by basil-conto** [comment]
Yes, I can reproduce this:

1. `make plain`
2. `C-c k restrict S-SPC`

> Error in post-command-hook (ivy--queue-exhibit): (wrong-number-of-arguments (1 . 1) 3)

Here's what seems to be happening: `ivy--wnd-cands-to-str` checks `ivy-state-dynamic-collection` before using `minibuffer-completion-table`.

But `ivy-restrict-to-matches` sets `ivy-state-dynamic-collection` to `nil`.

Meanwhile, the dynamic binding of `minibuffer-completion-table` still refers to the dynamic collection `counsel-ag-function`.

So quite a mess, as usual.

Updating `minibuffer-completion-table` in `ivy-restrict-to-matches` seems to work around this.  See PR #2894. @gexplorer, does that look right to you? @ambihelical does it make the problem go away without breaking other stuff? Thanks.

**Comment by ambihelical** [comment]
I won't be able to test it out thoroughly until the weekend, but I will make it a point to check.  Thanks for jumping on this so quickly.

**Comment by basil-conto** [comment]
No rush, and TIA.

**Comment by ambihelical** [comment]
The only thing I found issues with was counsel-search with the google search engine configured, the list clears completely.  However on checking, this didn't work before the trouble commit, so lgtm.

**Comment by basil-conto** [comment]
Great, thanks for confirming! I'll merge that for now and see if there's any further fallout later.

I'd be grateful if you would report (or fix ;) the separate `counsel-search` issue as well. Thanks.
