### ISSUE TITLE
Return list of selected candidates

### ISSUE THREAD

**Issue by jsilve24** [abo-abo/swiper#2897]
First off, thank you for creating such an awesome package. 

I fell like this should be simple but I can't seem to figure it out, google searchers and reading documentation and code has been unrevealing. 

Lets say I have a list of candidates `candidates` from which I want to select between 1 and the total length of the candidates list. I would like to use ivy to return a list of the marked candidates.

I have no problem returning just a single candidate, ivy seems to do that no matter what I do. But returning multiple selected candidates as a list is eluding me. 

In fact, I would even be happy returning a concatenated string with the names of the selected candidates, but I can't seem to figure out that either. 

Is this possible? Am I missing something?

**Comment by basil-conto** [comment]
Have you tried using `:multi-action`?  Quoth `C-h f ivy-read RET`:

```
MULTI-ACTION, when non-nil, is called instead of ACTION when
there are marked candidates. It takes the list of candidates as
its only argument. When it's nil, ACTION is called on each marked
candidate.
```

For example (with `ivy-hydra` installed for the predefined `C-o m` binding):

1. ```el
   (let (result)
     (ivy-read "Prompt: " '("a" "b" "c" "d")
               :multi-action (lambda (x) (setq result x)))
     result)
   ```
2. `C-j`
3. `C-o m m RET` (this marks the first two candidates using the `ivy-hydra` menu)
4. Result:
   ```el
   ("a" "b")
   ```

**Comment by jsilve24** [comment]
Thank you. Will try this. 

I had tried multi-action but figured setting a global variable as a side-effect may be poor form with unintended complications. But I am new to Elisp

**Comment by basil-conto** [comment]
> setting a global variable as a side-effect may be poor form with unintended complications

The `result` variable in my example is local, not global (at least under `lexical-binding`), but either way I only used it to illustrate what `:multi-action` receives as argument.  It's up to the caller to decide how to use the multi-selection.

Does that address your query, or is there something left for Ivy to do here before closing the issue? Thanks.

**Comment by jsilve24** [comment]
you can close.

Also thank you for teaching me about variable scoping -- sounds like I have some reading to do because I am missunderstanding how setq works.

Either way, thank you!

**Comment by basil-conto** [comment]
Great, thanks for confirming!
