### ISSUE TITLE
Swiper doesn't work as the way shown in document.

### ISSUE THREAD

**Issue by hongyi-zhao** [abo-abo/swiper#2899]
On Ubuntu 20.04, I'm using git master version of Emacs, and I've installed swiper with the following configuration through straight and use-package:

```emacs-lisp
(use-package swiper
  :straight (swiper :type git :host github :repo "abo-abo/swiper"
              :pre-build (
                          ;https://github.com/abo-abo/swiper/issues/2886#issuecomment-860605327
                          ("make" "deps")
                          ("make" "compile")
                         ))
  :bind (("C-s" . swiper)))
```
Then I hit `C-s` to test `swiper` when I'm in scratch buffer, as shown below:

![image](https://user-images.githubusercontent.com/11155854/127592425-1d6d6d71-6013-451d-8509-7884820f0a6d.png)

As you can see, there is nothing to match. So I'm very confused: why can't I get a similar effect as the screenshot shown [in the document](https://github.com/abo-abo/swiper#screenshots)

Regards,
HY

**Comment by basil-conto** [comment]
Sorry, I can't reproduce this. (I don't use `use-pacakge` or `straight`, but I can't imagine how those would cause the issue anyway.)

Are you able to reproduce the issue starting from `emacs -Q`?  If not, can you try adding/removing things from your `user-init-file` to help narrow down which parts might be interfering with `swiper`? Thanks.

**Comment by hongyi-zhao** [comment]
Really. I confirm that the problem can not be reproduced with the following minimum initialization file, `~/.emacs.d/init.swiper`:

```emacs-lisp
;$ emacs -Q --load ~/.emacs.d/init.swiper

;;Bootstrap straight
(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 5))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))
(straight-use-package 'use-package)
(setq straight-use-package-by-default t)


(use-package swiper
  :straight (swiper :type git :host github :repo "abo-abo/swiper"
              :pre-build (
                          ;https://github.com/abo-abo/swiper/issues/2886#issuecomment-860605327
                          ("make" "deps")
                          ("make" "compile")
                         ))
  :bind (("C-s" . swiper)))
```
![image](https://user-images.githubusercontent.com/11155854/127665936-2cde57f8-f360-4baa-907e-104528a99757.png)

There should be some configuration that interferes with `swiper` and causes this problem.

**Comment by basil-conto** [comment]
> There should be some configuration on my side that interferes with `swiper` and causes this problem.

Thanks for confirming.  Hopefully by incrementally adding parts of your configuration back, you can narrow down the culprit.

> BTW, I use `helm` and `swiper` at the same time, and I don't know whether they interfere with each other.

It's not impossible, but I'd be surprised.

**Comment by hongyi-zhao** [comment]
Got it. The culprit is the following configuration in my `~/.emacs.d/init.el`:

```emacs-lisp
(use-package ivy-prescient
  :after prescient
  :init (setq prescient-filter-method '(literal fuzzy regexp initialism))
  :config (ivy-prescient-mode t))
```

According to the documentation [here](https://github.com/raxod502/prescient.el#ivy-specific), changing the above the configuration into the following will fix the problem reported here:

```emacs-lisp
(use-package ivy-prescient
  :after prescient
  :init (setq prescient-filter-method '(literal fuzzy regexp initialism)
              ;https://github.com/raxod502/prescient.el#ivy-specific
              ivy-prescient-enable-filtering nil)
  :config (ivy-prescient-mode t))
```

**Comment by basil-conto** [comment]
Great, I'm glad you figured out it. Thanks for confirming.
