### ISSUE TITLE
swiper: point jumps to the first line of that the current line is a substring

### ISSUE THREAD

**Issue by zhaojiangbin** [abo-abo/swiper#290]
When in buffer there is another line of which the current line is a sub-string, running `swiper` (<kbd>C-s</kbd>) makes the cursor jumping to that line, instead of staying in the current one.

To reproduce in the scratch buffer:
1. Enter the following 10 lines, note the leading spaces in the last two lines:
```
zero
one two three
one
two
one two
three
one two three
one three
  two
 two
```
2. Move the cursor to any of the 3rd, 4th, 5th, 6th and 7th line.
3. Press <kbd>C-s</kbd> anywhere on that line. Watch the cursor jumping to column 0 of the 2nd line.
4. Move the cursor to the 8th line.
5. Press <kbd>C-s</kbd> anywhere on that line. The cursor does not move.
6. The most interesting part happens when the cursor is in the 9th line, press <kbd>C-s</kbd> makes the cursor jumping to the 10th line.
7. Press <kbd>RET</kbd> to select the 10th line and exit from `swiper`.
8. Then press <kbd>C-s</kbd> when in 10th line, watch the cursor jumping to the 4th line.

**Comment by abo-abo** [comment]
Thanks, this annoyance should be gone now.

**Comment by zhaojiangbin** [comment]
Verified. Thanks.
