### ISSUE TITLE
Let `swiper` search `dired` buffer recursively.

### ISSUE THREAD

**Issue by hongyi-zhao** [abo-abo/swiper#2904]
When searching under the top-level directory opened in the `dired` buffer, can I let `swiper` dig into the subdirectories recursively?

Regards,
HY

**Comment by basil-conto** [comment]
`swiper` and its variants are designed to work on live buffers.  See, for example, `swiper-all` and `swiper-multi`.

For searching files and file trees that are not yet visited in the current Emacs session, there are commands like `counsel-git-grep` (for Git repositories), `counsel-ag` (if you have the "silver searcher" `ag` installed), `counsel-pt` (if you have the "platinum searcher" `pt` installed), `counsel-ack` (if you have `ack` installed), and `counsel-rg` (if you have `ripgrep` installed).

Do you have a use-case not already covered by these existing tools?

**Comment by hongyi-zhao** [comment]
>  See, for example, `swiper-all` and `swiper-multi`.

Where are `swiper-all` and `swiper-multi`? What's differences among them?

> Do you have a use-case not already covered by these existing tools?

Based on you above comments, it seems that `counsel-*` tools you mentioned above are my friends to solve the problems discussed at present.

**Comment by basil-conto** [comment]
> Where are `swiper-all` and `swiper-multi`? What are differences among them?

1. `C-h f swiper-all RET`
   ```
   swiper-all is an interactive compiled Lisp function in `swiper.el'.

   (swiper-all &optional INITIAL-INPUT)

   Run `swiper' for all open buffers.
   ```
2. `C-h f swiper-multi RET`
   ```
   swiper-multi is an interactive compiled Lisp function in `swiper.el'.

   (swiper-multi)

   Select one or more buffers.
   Run `swiper' for those buffers.
   ```
