### ISSUE TITLE
counsel-ibuffer cannot create new, empty buffers

### ISSUE THREAD

**Issue by lechner** [abo-abo/swiper#2905]
Hi, following a recommendation in [Emacs from Scratch](https://youtu.be/IspAZtNTslY?t=1894), I remapped **C-x b** to  `counsel-ibuffer` but typing a new name no longer creates a new, empty buffer. How can I do that now, please?

The error is `wrong type argument: listp, ${filename}`.

With the kind help of dale on `Libera:#emacs`, we figured out out that it may be a bug in `counsel`. Evaluating the code below solves the issue. Thanks!
```
(defun my-counsel-ibuffer-switch-to-new-buffer (args)
  (if (stringp (car args))
      (cons (cons nil (car args)) (cdr args))
    args))

(advice-add 'counsel-ibuffer-visit-buffer :filter-args
            'my-counsel-ibuffer-switch-to-new-buffer)
```

**Comment by basil-conto** [comment]
Thanks!  The fix should be live on [GNU-devel ELPA](https://elpa.gnu.org/devel/counsel.html) within the next few hours.  Please let me know if anything remains amiss with this.

> we figured out out that it may be a bug

Arguably `counsel-ibuffer` never claimed to support this use-case, so not strictly a bug ;). Nevertheless, I think the behaviour you describe makes sense, and either way `counsel-ibuffer` should not signal an error in this scenario.
