### ISSUE TITLE
Put point at the current opened file when using counsel-find-file

### ISSUE THREAD

**Issue by c02y** [abo-abo/swiper#2908]
This may be related to the issue https://github.com/abo-abo/swiper/issues/1034.

When I need to open and edit files in one directory one by one, after finishing editing, I use `counsel-find-file` to open the next file in the directory, but the point of the cursor after `counsel-find-file` is always at the first line of the list which is `.`, I have to scroll the point to the specific file manually or typing for the file.

When I `counsel-find-file`, if it points to the opened file automatically, it would save a lot work. (if no file is open, such as when you in `*Help*` page, it points to the first line of the list)

**Comment by basil-conto** [comment]
Have you tried setting the user option `counsel-preselect-current-file` to a non-`nil` value?

**Comment by c02y** [comment]
Yes, thank you. This is exactly what I need.
