### ISSUE TITLE
Is there an `ivy-save-view`? (part 2)

### ISSUE THREAD

**Issue by midas0441** [abo-abo/swiper#2909]
I am resurrecting an issue (#1079) that was closed several years ago. The original post (@paul-xie-rs) was: 

> I use ivy-push-view to save the windows layout. It's very useful for me. But when I restart my Emacs. The views are all lost. Can I do something to save the views to file and load them again when restart Emacs?

It was [suggested](https://github.com/abo-abo/swiper/issues/1079#issuecomment-310734041) (@abo-abo) that:

> You can save the current state of the `ivy-views` variable to your config.

I tried this by attempting to save to a file in my `~/.emacs.d`. I have 4 buffers split horizontally across a single window. After `ivy-push-view`, I looked at the `ivy-views` variable. Here is what it shows: `(("{} some name" #<window-configuration>))`. It is an object that has no read syntax. How do I save the object `#<window-configuration>` to my config? The command `prin1` will only provide a readable representation of the object.

**Comment by basil-conto** [comment]
> I am resurrecting an issue (#1079) that was closed several years ago.

Maybe we should close this issue, reopen #1079, and continue the discussion there?
