### ISSUE TITLE
swiper-isearch action doesn't go to the target

### ISSUE THREAD

**Issue by allenryb** [abo-abo/swiper#2913]
For example, I have the following code

![image](https://user-images.githubusercontent.com/6965371/133361241-9b5889b9-9717-4183-880a-f832d2b5abd4.png)

I search `aaa` by `swiper-isearch` and then type `M-o w` -- `swiper-action-copy`.
The `aaa` doesn't go to kill ring, but the `bbb` does, see

![image](https://user-images.githubusercontent.com/6965371/133361387-b6f69503-bfea-4a63-b110-580ac265a565.png)

The point hasn't  jumped to the target `aaa` and stayed in the original position.
This problem of `swiper-isearch` also holds for other custom actions.

But it is fine for `swiper` command.

**Comment by basil-conto** [comment]
> The point hasn't jumped to the target `aaa` and stayed in the original position.

Yeah, the shared code and discrepancies between `swiper` and `swiper-isearch` are a mess :(.

> This problem of `swiper-isearch` also holds for other custom actions.

What do you mean? Can you list these actions, or give an example thereof?

By "custom", do you mean action functions that you've written yourself?  If so, then that sounds like a bug in the custom functions, not `swiper-isearch`.  No?

In any case, could you please test whether PR #2914 improves the situation without introducing any new issues?

Thanks.

**Comment by allenryb** [comment]
The bug has been fixed. I will fix my custom function. Thanks!

**Comment by basil-conto** [comment]
> The bug has been fixed.

Do you mean with or without PR #2914?  Thanks.

**Comment by allenryb** [comment]
> > The bug has been fixed.
> 
> Do you mean with or without PR #2914? Thanks.

Yes

**Comment by basil-conto** [comment]
> > > The bug has been fixed.
> > 
> > Do you mean with or without PR #2914? Thanks.
> 
> Yes

I walked into that one :).

I'm going to assume that you fixed your issues on your end, and that #2914 fixes some of the issues I ran into without making things worse, and call it a day.  Those fixes should appear on [GNU-devel ELPA](https://elpa.gnu.org/devel/swiper.html) in the next few hours.  Thanks again.
