### ISSUE TITLE
counsel-bookmark: Add rename action

### ISSUE THREAD

**Issue by Hugo-Heagren** [abo-abo/swiper#2916]
I occasionally need to rename my bookmarks, and I tend to use `counsel-bookmark` as an interface for them. I think this should be a pretty simple feature to add. <kbd>n</kbd> is free in the actions list and seems a reasonable choice I think?

**Comment by basil-conto** [comment]
I don't use `counsel-bookmark`, but isn't bookmark renaming already supported under `"e"`?

https://github.com/abo-abo/swiper/blob/c9fdec4e79bea7b15c3e35a984e45c9579fe7cdc/counsel.el#L2491-L2500

**Comment by Hugo-Heagren** [comment]
So it is, sorry! I hadn't made the link between `edit` and renaming, but now you point it out its obvious.
