### ISSUE TITLE
swiper: with initial-input, a match other than the current line is selected

### ISSUE THREAD

**Issue by zhaojiangbin** [abo-abo/swiper#292]
I have a wrapper around `swiper`. On <kbd>C-s</kbd> it picks up the "thing" (a symbol for example) at point as the initial input to `swiper`. When it works, it is better than using `swiper` directly with `ivy-yank-word` because I don't have to ensure that the point is at beginning of a word, and I don't have to press <kbd>C-w</kbd> multiple times for picking up the whole symbol.

But it does not work well when there are many matches in the buffer. Often a match that is not the current line gets selected by `swiper` in the candidate list. This moves the point away from where `swiper` starts, sometimes too far for me to find the way back.

Also, in my opinion, this behavior is inconsistent with `ivy-yank-word` which selects the current line.

It is easy to reproduce in a buffer with just the following:
```
zero
one
two
one
```
1. Place the point in the 2nd line where the first "one" is.
2. Eval `(swiper "one")` with <kbd>M-:</kbd>.
3. Watch the 4th line being selected.

**Comment by abo-abo** [comment]
Thanks, please test.

Also, <kbd>C-s M-n</kbd> approach is recommended instead. It picks up the symbol or URL at point.

**Comment by zhaojiangbin** [comment]
Thanks for the fix.

Isn't <kbd>M-n</kbd> bound to function `ivy-next-history-element` in `ivy-minibuffer-map`? Or did you mean something else?

**Comment by abo-abo** [comment]
> Isn't M-n bound to function ivy-next-history-element in ivy-minibuffer-map?

Yes. But the recommended Emacs behavior is that `next-history-element` inserts thing-at-point, in case that it's a first history command; i.e. there's no next history element at the moment so might as well do something else useful.

**Comment by zhaojiangbin** [comment]
Ah, I didn't know of this behavior. Neat.

**Comment by zhaojiangbin** [comment]
It seems that this problem has made a comeback. MELPA version 20151122.501 works fine. It's broken in 20151127.1421, and a previous one 20151126 (unfortunately I didn't write down the exact MELPA version of this).

**Comment by abo-abo** [comment]
Thanks.
