### ISSUE TITLE
`C-s ... M-q` will show garbage codes.

### ISSUE THREAD

**Issue by hongyi-zhao** [abo-abo/swiper#2925]
I installed `swiper` with the following configuration:
```emacs-lisp
(use-package swiper
  :bind ("C-s" . swiper))
```
When I try `C-s buffer RET M-q ...` in scratch buffer, I'll see the following garbage codes:

![image](https://user-images.githubusercontent.com/11155854/136719119-d923578d-7ae6-43c1-81f1-5ec6c45497ed.png)

Any hints for this problem?

Regards,
HZ

**Comment by basil-conto** [comment]
> the following garbage codes

It's not (complete) garbage, it's a regexp, probably the result of your `search-default-mode` setting. Is your value of the user option `search-default-mode` the function `char-fold-to-regexp` by any chance?

Ideally this wouldn't take up so much of the minibuffer though...

**Comment by hongyi-zhao** [comment]
> Is your value of the user option `search-default-mode` the function `char-fold-to-regexp` by any chance?

Yes. As shown below:

![image](https://user-images.githubusercontent.com/11155854/161945579-d8526d8f-f6d7-4dc8-84ef-abfeb5e27463.png)

**Comment by basil-conto** [comment]
In that case this is working as expected, no?

**Comment by hongyi-zhao** [comment]
But the problem reported here doesn't appear currently by running `C-s buffer RET M-q`:

![image](https://user-images.githubusercontent.com/11155854/161948139-575b1be8-3b25-4249-8b44-458fc1a7e0b8.png)

**Comment by basil-conto** [comment]
I'll close this issue for now then.  If further information comes up, we can always reopen.  Thanks.
