### ISSUE TITLE
Error in post-command-hook together with ivy-mode

### ISSUE THREAD

**Issue by swhahn** [abo-abo/swiper#293]
Hello,
I came to a problem together with ivy-mode which was investigated as bug#16274, but not solved.

startup.el:
```emacs-lisp
(add-to-list 'load-path "~/.emacs.d/git/swiper/")
(require 'ivy)
(ivy-mode)
(icomplete-mode)
```

emacs -Q -l startup.el

Then
- load a file which is alone in a directory.
- write-file (C-x C-w)
- M-n (sometimes also makes the error with M-p)

gives error:
Error in post-command-hook (icomplete-post-command-hook): (cl-assertion-failed (functionp table))

because ivy-mode together with icomplete-mode have completion-metadata which contains
'(completion--unquote-requote . t). This leads to the cl-assert in completion--nth-completion
in minibuffer.el. (The cl-assert was inserted by Stefan Monnier because of the bug report.)

I cannot reproduce this without ivy-mode.
Perhaps you have deeper knowledge of minibuffer internals and can imagine why ivy-mode
triggers this problem.

I run 
emacs commit 70f1fda as 64 bit on Linux
swiper commit 85bd44.

With kind regards,
Stefan

**Comment by abo-abo** [comment]
The problem here is that `ivy-mode` and `icomplete-mode` are exclusive: you can't have them both on at once.

At some point, `ivy-mode` should completely upgrade `icomplete-mode`. If there's some feature in `icomplete-mode` that you're missing in `ivy-mode` I can try to provide it. Otherwise, I don't see what else I could do.

**Comment by swhahn** [comment]
Thanks. I wasn't aware of this. (There is also no hint in the documentation.) I searched how icomplete could be enabled and I found a left over customization of it. So I switched it off and everything is ok.
Also I don't think that I need it. This issue can be closed.
Thanks very much.
Stefan
