### ISSUE TITLE
Sort function for commands (`M-x`)?

### ISSUE THREAD

**Issue by ZelphirKaltstahl** [abo-abo/swiper#2987]
I have written my own sort function for `find-file`, but could so far not find information about what the name is of the function for sorting command candidates. Is there such a function? How would I modify it?

**Comment by abo-abo** [comment]
See `counsel--M-x-externs`. We integrate either with `smex` or `amx`.

**Comment by ZelphirKaltstahl** [comment]
@abo-abo Hi and sorry for writing in this closed issue again. I was searching today again and found my own issue again. I noticed, that I was quite light on details. Perhaps it would help, if I posted some code I use for `find-file` and then you could tell me, whether `smex` or `amx` or `counsel--M-x-externs` is really the answer.

```elisp
(defun string-length= (a b)
  (= (length a)
     (length b)))


(defun string-length< (a b)
  (= (length a)
     (length b)))


(defun xiaolong/ivy--files-sort-by-length (x y)
  "Sort given filenames X and Y according to string length.
However, give directories priority."
  (let ((cleaned-x (if (string-suffix-p "/" x) (substring x 0 -1) x))
        (cleaned-y (if (string-suffix-p "/" y) (substring y 0 -1) y)))
    (let* ((length-equal? (string-length= cleaned-x cleaned-y))
           (x-shorter? (string-length< cleaned-x cleaned-y))
           (x-wins t)
           (y-wins nil))
      (let ((result
             ;; compare
             (if (file-directory-p cleaned-x)
                 (if (file-directory-p cleaned-y)
                     ;; If both are a directory, and of same length, let the
                     ;; default comparison function decide.
                     (if length-equal?
                         (ivy-sort-file-function-default x y)
                       ;; If not of same length, then check if x is shorter and
                       ;; prefer x if it is shorter.
                       x-shorter?)
                   ;; Prefer x if y is not a directory.
                   x-wins)
               (if (file-directory-p cleaned-y)
                   y-wins
                 ;; If both are a directory, and of same length, let the
                 ;; default comparison function decide.
                 (if length-equal?
                     (ivy-sort-file-function-default x y)
                   ;; If not of same length, then check if x is shorter and
                   ;; prefer x if it is shorter.
                   x-shorter?)))))
        result))))
```

This I use in `use-package` expression:

```elisp
(use-package counsel
  :ensure t
  :bind
  (("C-x C-f" . #'counsel-find-file)
   ("C-x f" . #'counsel-find-file)
   ("M-x" . #'counsel-M-x)
   ("C-x b" . #'counsel-switch-buffer))
  :config
  (ivy-mode 1)
  ;; Add our own sort function to the association list of sort functions.
  (add-to-list 'ivy-sort-functions-alist
               '(read-file-name-internal . xiaolong/ivy--files-sort-by-length)))
```

Now I have already written the following for commands:

```elisp
;; TODO: Finish implementing this function. "...default..." stands for the not yet inserted default function coming from ivy itself. Probably could not find it last time I searched.
(defun xiaolong/ivy--commands-sort-by-length (x y)
  "Sort given filenames X and Y according to string length.
However, give directories priority."
  (let* ((length-equal? (string-length= x y))
         (x-shorter? (string-length< x y)))
    (let ((result
           (if length-equal?
               (...default... x y)  ; <-- How to use the default function here? What name to use?
             ;; If not of same length, then check if x is shorter and
             ;; prefer x if it is shorter.
             x-shorter?)))
      result)))
```

Does this change the picture, or is the answer still:

> See counsel--M-x-externs. We integrate either with smex or amx.

?

**Comment by ZelphirKaltstahl** [comment]
Update: I checked the help of `counsel--M-x-externs`:

> counsel--M-x-externs is a Lisp closure in ‘counsel.el’.
>
> (counsel--M-x-externs)
>
> Return ‘counsel-M-x’ candidates from external packages.
> The return value is a list of strings.  The currently supported
> packages are, in order of precedence, ‘amx’ and ‘smex’.

Sounds like what I need. But it does not take any arguments. I think it might be a complete replacement for my `xiaolong/ivy--commands-sort-by-length`?

**Comment by basil-conto** [comment]
> I think it might be a complete replacement for my `xiaolong/ivy--commands-sort-by-length`?

Not exactly:`amx` and `smex` are external packages which as far as I know (disclaimer: haven't used them) try to keep track of your most used commands, and offer those before less used ones during `M-x` completion.

If you would like to sort `M-x` candidates according to your own sort function, then indeed `ivy-sort-functions-alist` is the right place (in general, not just for `counsel-M-x`.

**Comment by ZelphirKaltstahl** [comment]
Thanks for the info. I will need to further consider and try things out. Maybe even implement something myself again, with string edit distance or so. If I get to a good result, I hope I will remember to post it in this issue.
