### ISSUE TITLE
I wrote a small counsel function for switching tabs: should I submit it upstream?

### ISSUE THREAD

**Issue by enzuru** [abo-abo/swiper#2989]
I wrote a small counsel function for switching tabs: https://github.com/enzuru/counsel-tabs/blob/main/counsel-tabs.el

Should I submit it upstream to `counsel.el` or maintain it as a separate package? Thanks!

**Comment by abo-abo** [comment]
Looks good! I think a separate package makes more sense. The new package would then have `tabbar` and `ivy` as dependencies.

**Comment by basil-conto** [comment]
> The new package would then have `tabbar` and `ivy` as dependencies.

There's no dependency on `tabbar` AFAICT - just native Emacs 27 tab bar functions.

The only problem is that `tab-bar--tabs-recent` and `tab-bar--tab-index-by-name` are internal definitions that are prone to being changed or removed, so Counsel should avoid using them.

**Comment by enzuru** [comment]
@basil-conto I have updated my package to have imported permanent versions of those functions. Is this something I should now work to submit upstream to `swiper` in a function that can be executed on Emacs 27+?

**Comment by enzuru** [comment]
I think I have found another approach for now. Thanks for everything.
