### ISSUE TITLE
feature request: option to make swiper to start at point forward or backward

### ISSUE THREAD

**Issue by zhaojiangbin** [abo-abo/swiper#299]
Speed of `swiper` is more than enough for source code files and org documents. However, lags start showing up in log files that have a few hundreds of thousands of lines or more. In such workflow, what usually matters more is the matches either before or after the current line, not all of them in the whole file. I didn't profile it but I feel that the lags are in collecting candidates from the whole buffer.

Would it be possible to add a second optional parameter to `swiper` that makes it to start with the current line and go either forward or backward? This should, in average, be able to cut half of the time spent in collecting candidates in large buffers.

An even better approach in my opinion would be to collect candidates incrementally. For example, initially only collect candidates in the vicinities of the current line, say a few "screens" up and down. As `ivy-next-line` or `ivy-previous-line` reaching either end of the candidate list, start collecting again on that direction. This, of course, might require a lot more changes.

I know that `isearch` is perhaps more suitable for large buffers because it does not have to build the candidate list. It would be awesome for `swiper` to be more usable there, too.

**Comment by abo-abo** [comment]
> However, lags start showing up in log files that have a few hundreds of thousands of lines or more

In that case, I suggest to use `counsel-git-grep` or `counsel-ag`. They're very similar to `swiper` but work for all files in a Git repository or a directory.  They call the shell in async, so they're pretty fast. The results show up 0.2 seconds after the last key press for the Emacs git repository, and 1.5 seconds for the full Linux repository. So they should be pretty fast for log files.

> This should, in average, be able to cut half of the time spent in collecting candidates in large buffers.

You can cut the time by more than half with the above approach, depending to the size of your file(s).

**Comment by zhaojiangbin** [comment]
Interesting idea but does not work for me.

To use `counsel-git-grep`, I'd have to initialize a git repo and stage the log files at least.

While `counsel-ag` works with files in just a directory, there are a few problems (which I believe `counsel-git-grep` would have, too):
1. In minibuffer, candidates are shown from the beginning and the selection starts at the first candidate. That can be far away from the "point of interests" (i.e. where the point is in the file buffer).
2. If in the same directory I have multiple log files from different test runs to inspect, all matches from all files are put in the same candidate list. This can push the point of interests even further down in the candidate lists.

I know that I am asking for perhaps what `swiper` is not intended for. Feel free to close the issue if you see it not "compatible" with `swiper`'s direction.

**Comment by abo-abo** [comment]
> I know that I am asking for perhaps what swiper is not intended for. Feel free to close the issue if you see it not "compatible" with swiper's direction.

I never had to deal with large log files, the largest one that I use for testing is org.el. Send me an example file, and I'll see what I can do. My guess is that to make it work, an external shell tool would have to be used (git, ag, grep, or something else), since Elisp isn't fast enough to produce all matches in a large file.

**Comment by zhaojiangbin** [comment]
Unfortunately those log files are work related. I am afraid that I cannot send it out for this purpose.

But you can imagine that such a log file weighs between 2 to 10M bytes, 30K to 150K lines. In such a file, there are clusters of log messages repeated over and over, driven by external input (many pairs of HTTP requests and responses and each pair can cause a burst of thousands of log messages).

Perhaps you can concatenate org.el to itself a few times to simulate? Otherwise no need to spend more time on the issue if you don't have a place to start with.

**Comment by abo-abo** [comment]
Please test. Eventually, you could have:

```elisp
(defun my-swiper ()
  (interactive)
  (if (> (buffer-size) 1e6)
      (counsel-grep)
    (swiper)))
```

**Comment by zhaojiangbin** [comment]
I am not able to get `counsel-grep` to work.

As I type in the "Grep: " prompt character by character, the "3 chars more" message becomes "2 chars more", then "1 chars more" and stays unchanged, no matter how many more characters I have typed. No candidate shows up.

`counsel-ag` works fine. `M-x grep` works fine, too, with commands such as `grep -nH -e "pattern phrase" filename.txt`. I am running the prebuilt Emacs version 24.5.3, the "Emacs Mac Port", on Mac OS X 10.10.

**Comment by zhaojiangbin** [comment]
By the way, can you please add support to `counsel-grep` for optional initial input, too?

**Comment by abo-abo** [comment]
Try this command in shell:

    grep -nP --ignore-case 'defvar' counsel.el

This is what `counsel-grep` calls. Maybe your `grep` doesn't support the switches.

**Comment by zhaojiangbin** [comment]
It looks like that Apple's `grep` does not support the `-P` switch for Perl-like regex syntax. It does have `-n` for showing line numbers, and `--ignore-case` or `-i` for, well, ignoring case.

What specific Perl-like regex syntax do you need?
