### ISSUE TITLE
python-mode.el imenu issues

### ISSUE THREAD

**Issue by murcake** [abo-abo/swiper#2992]
There is an emacs builtin python-mode and [another one](https://gitlab.com/python-mode-devs/python-mode). I use the latter, in particular, because it supports the python-3.10 match-case construction (indentation, highlighting etc).

However, there is a [hard-coded](https://github.com/abo-abo/swiper/blob/e9c0fb953db9f6a23018a52441f3cd775710472c/counsel.el#L4708) call to `python-imenu-create-flat-index` function in counsel. This function exists in the former, builtin, python-mode and doesn't exist in the mode that I use. Thus, when using `counsel-imenu`, I get an error. The usual `imenu` works fine. 

If you can point me to the best way to solve this, I can try it.

**Comment by basil-conto** [comment]
> If you can point me to the best way to solve this, I can try it.

In `counsel--imenu-candidates`, the call to `python-imenu-create-flat-index` is guarded by `(eq major-mode 'python-mode)`.

But this guard is insufficient, because both modes are called `python-mode`.

So, in addition to checking that the buffer is in `python-mode`, we also want to check that `python-imenu-create-flat-index` is `fboundp` before calling it.

Note that, if we call `fboundp`, then the call to `(declare-function python-imenu-create-flat-index "python")` earlier in the file will no longer be needed to suppress byte-compiler warnings.

Thanks.

**Comment by murcake** [comment]
> > If you can point me to the best way to solve this, I can try it.
> 
> In `counsel--imenu-candidates`, the call to `python-imenu-create-flat-index` is guarded by `(eq major-mode 'python-mode)`.
> 
> But this guard is insufficient, because both modes are called `python-mode`.
> 
> So, in addition to checking that the buffer is in `python-mode`, we also want to check that `python-imenu-create-flat-index` is `fboundp` before calling it.
> 
> Note that, if we call `fboundp`, then the call to `(declare-function python-imenu-create-flat-index "python")` earlier in the file will no longer be needed to suppress byte-compiler warnings.
> 
> Thanks.

I will do that. If you have time though, I would be glad to know why we need to special-case `python-mode`? Shouldn't counsel-imenu respect the value of `imenu-create-index-function`?

**Comment by basil-conto** [comment]
> I will do that.

Thanks.

> If you have time though, I would be glad to know why we need to special-case `python-mode`? Shouldn't counsel-imenu respect the value of `imenu-create-index-function`?

I don't know, @abo-abo made that change recently.  I'm guessing it's because the format returned by the default `imenu-create-index-function` in `python.el` is not in as convenient for Counsel as that returned by `python-imenu-create-flat-index`.

**Comment by murcake** [comment]
I've tried to track it back and it seems that it all started because of the fact that swiper was categorizing all otherwise uncategorized items as «Functions».
But that might be incorrect/imprecise and having no way to assess the impact of trying to fix the underlying problem, I took the simple approach that you've described.
