### ISSUE TITLE
Swiper interaction with Restructured Text mode

### ISSUE THREAD

**Issue by Balooga** [abo-abo/swiper#300]
Not sure if these are Swiper issues, or rst mode issues.

* Swiper tends to take at least 3 seconds to start a search when editing a file in rst mode.

* Using Swiper, rst mode and visual-line-mode; Swiper does return results for wrapped lines when a search query spans the line wrap (i.e. the first word is prior to the wrap and the second after the wrap.)

Not sure if the two issues are related.

**Comment by abo-abo** [comment]
> Swiper tends to take at least 3 seconds to start a search when editing a file in rst mode.

Is it any file or just large files? Large files are slow for `visual-line-mode`.  With `visual-line-mode` off, I have 1 second startup for 1MB org.el, which is pretty large for a text file.

> Using Swiper, rst mode and visual-line-mode; Swiper does return results for wrapped lines when a search query spans the line wrap (i.e. the first word is prior to the wrap and the second after the wrap.)

You'll have to provide a concrete example, with file contents, point position and window width. Otherwise, I don't see what you mean here.

**Comment by Balooga** [comment]
> Is it any file or just large files? Large files are slow for visual-line-mode. With visual-line-mode off, I have 1 second startup for 1MB org.el, which is pretty large for a text file.

No, the file is already loaded and open.  I just do the C-s to initiate the search which takes a couple seconds.   The size of the file is only a couple KB.

**Comment by Balooga** [comment]
> You'll have to provide a concrete example, with file contents, point position and window width. Otherwise, I don't see what you mean here.

![swiper-issue-1](https://cloud.githubusercontent.com/assets/167243/11431182/5484b8c4-9447-11e5-931d-359c2e9a8035.png)

The above capture shows the line wrapped at the end of the frame.  Swiper shows the match.

![swiper-issue-2](https://cloud.githubusercontent.com/assets/167243/11431183/5738957c-9447-11e5-9435-0dc71d94b3a0.png)

Swiper does not match the following wrapped word.

**Comment by abo-abo** [comment]
I still need a text file to test.

The first screenshot looks OK.

The second screenshot also looks OK: if you have `visual-line-mode` on, your long line is split into two candidates.
You can't match them both at once, unless you disable `visual-line-mode`.

**Comment by Balooga** [comment]
> The second screenshot also looks OK: if you have visual-line-mode on, your long line is split into two candidates.
> You can't match them both at once, unless you disable visual-line-mode.

Actually this is the answer.  Swiper doesn't support multiple candidates; for example where a line is split using `visual-line-mode`.

**Comment by abo-abo** [comment]
If there's nothing else to be done, I'm closing this issue. Swiper has to be line-based, the candidates are either real or visual lines; it can't match input in two different candidates.
