### ISSUE TITLE
ivy: open dired in other frame lists files, not just directories, as choices

### ISSUE THREAD

**Issue by danrharms** [abo-abo/swiper#301]

**Comment by abo-abo** [comment]
This is the behavior of the default completion in Emacs.  Since Ivy highlights directories with their own face, and the directories are listed ahead of the files, I don't think it's a big deal.  Some user somewhere might even want to open `dired` for a single file. Maybe.

**Comment by danrharms** [comment]
OK, thank you. It just seemed a little strange.
