### ISSUE TITLE
ivy-resume does not validate that buffer is same as original

### ISSUE THREAD

**Issue by danrharms** [abo-abo/swiper#302]
Use swiper to search for a string that is present in file
There is a list of matches
Change to a different buffer
Execute ivy-resume
Swiper result set is the same one, though it no longer applies

**Comment by abo-abo** [comment]
Thanks. It's tricky, since for most other commands, like `describe-function`, changing the buffer isn't the right thing to do.  So I added an exception specifically for `swiper`.
