### ISSUE TITLE
Using `sort` instead `cl-sort` in "swiper.el"

### ISSUE THREAD

**Issue by med-merchise** [abo-abo/swiper#3038]
Maybe it should be `cl-sort` instead of a simple `sort` on line 291.

https://github.com/abo-abo/swiper/blob/5b8436ef7d44abab1dca688ea4cb094af2653b2e/swiper.el#L289C1-L293C1

This will avoid getting:
```In swiper--avy-candidates:
swiper.el:291:16: Warning: ‘sort’ called with 5 arguments, but accepts only 2
```

**Comment by basil-conto** [comment]
1. What is your `emacs -version`?
2. How exactly are you compiling `swiper.el`?
3. Have you first updated and recompiled `ivy.el` (which `swiper.el` depends on)?

Emacs 30 added a new macro `static-if` which allows conditional compilation of one or its other branches based on a compile-time condition, such as the current Emacs version.

`ivy.el` now checks if `static-if` is defined, and if not polyfills it itself, in accordance with the docs of `static-if` under `(info "(elisp) Conditional Compilation")`:

>    To use this facility for an older version of Emacs, copy the source
> for ‘static-if’ from the Emacs source file ‘lisp/subr.el’ into your
> package.

Emacs 30 also gained a new calling convention for the built-in `sort` function.  Here's the `etc/NEWS` entry:

```
** New polymorphic comparison function 'value<'.
This function returns non-nil if the first argument is less than the
second.  It works for any two values of the same type with reasonable
ordering for numbers, strings, symbols, bool-vectors, markers, buffers
and processes.  Conses, lists, vectors and records are ordered
lexicographically.
It is intended as a convenient ordering predicate for sorting, and is
likely to be faster than hand-written Lisp functions.

** New 'sort' arguments and features.
The 'sort' function can now be called using the signature

    (sort SEQ &rest KEYWORD-ARGUMENTS)

where arguments after the first are keyword/value pairs, all optional:
':key' specifies a function that produces the sorting key from an element,
':lessp' specifies the ordering predicate, defaulting to 'value<',
':reverse' is used to reverse the sorting order,
':in-place is used for in-place sorting, as the default is now to
sort a copy of the input.

The new signature is less error-prone and reduces the need to write
ordering predicates by hand.  We recommend that you use the ':key'
argument instead of ':lessp' unless a suitable ordering predicate is
already available.  This can also be used for multi-key sorting:

    (sort seq :key (lambda (x) (list (age x) (size x) (cost x))))

sorts by the return value of 'age', then by 'size', then by 'cost'.

The old signature, '(sort SEQ PREDICATE)', can still be used and sorts
its input in-place as before.
```

> Maybe it should be `cl-sort` instead of a simple `sort` on line 291.
> 
> https://github.com/abo-abo/swiper/blob/5b8436ef7d44abab1dca688ea4cb094af2653b2e/swiper.el#L289C1-L293C1

So AFAICS this code should work fine.

> This will avoid getting:
> 
> ```
> swiper.el:291:16: Warning: ‘sort’ called with 5 arguments, but accepts only 2
> ```

And indeed I cannot reproduce this warning on any of the following Emacs versions: 24.5, 25.3, 26.3, 27.2, 28.2, 29.3, 29.3.50, 30.0.50. Here's how I'm testing:
```console
make emacs="$e -Q" clean compile test
```
for each Emacs version `$e`.

**Comment by basil-conto** [comment]
Thanks for the quick report!  I hope to have fixed the warnings now.

> And indeed I cannot reproduce this warning on any of the following Emacs versions: 24.5, 25.3, 26.3, 27.2, 28.2, 29.3, 29.3.50, 30.0.50. Here's how I'm testing:
> 
> ```
> make emacs="$e -Q" clean compile test
> ```
> 
> for each Emacs version `$e`.

I also reworked the `Makefile` to be more hygienic, so that these warnings actually come up when working in the repository.
