### ISSUE TITLE
counsel--project-current should use project-root

### ISSUE THREAD

**Issue by leahneukirchen** [abo-abo/swiper#3041]
At some point `project-current` started to return longer lists such as `(vc Git "/tmp/myrepo")`, so `counsel--project-current` should not simply call `cdr` but `project-root` to get the directory out of this.

**Comment by basil-conto** [comment]
> At some point `project-current` started to return longer lists such as `(vc Git "/tmp/myrepo")`, so `counsel--project-current` should not simply call `cdr`

Thanks for reporting this!  A fix was already proposed in PR #3003, but...

> but `project-root` to get the directory out of this.

...I hope to have addressed the issue in a more general way now, which does not assume `project-root` (before it, there was only `project-roots`, and before that, there was no `project.el`!).

**Comment by leahneukirchen** [comment]
I worry that this breaks if `(project-current)` returns nil.

**Comment by basil-conto** [comment]
> I worry that this breaks if `(project-current)` returns nil.

Oops, your worry is justified.  Sorry about that, and thanks for catching it.
