### ISSUE TITLE
counsel-M-x starts with ^ character

### ISSUE THREAD

**Issue by patrickaldis** [abo-abo/swiper#3042]
With minimal config:
```lisp
(use-package counsel 
  :config
  (counsel-mode)
  (setcdr (assq t ivy-format-functions-alist) #'ivy-format-function-line)
  :bind (:map ivy-minibuffer-map
	("C-j" . ivy-next-line)
	("C-k" . ivy-previous-line))
)
```

Whenever I counsel-M-x the prompt always starts with a ^ character:
![image](https://github.com/abo-abo/swiper/assets/46719614/e2e449dc-b55d-44d3-8184-e13a676f9423)

On emacs 29.2 latest counsel

Is this the normal behaviour?

**Comment by basil-conto** [comment]
> Is this the normal behaviour?

Yes, it's the default behaviour.
You can configure it via the user options `ivy-initial-inputs-alist` or `ivy-hooks-alist`.
