### ISSUE TITLE
Way to show EXWM buffers from all frames during counsel-switch-buffer?

### ISSUE THREAD

**Issue by anoopemacs** [abo-abo/swiper#3058]
I am running emacs with more than one frame.
**Is there a builtin way to switch to a buffer in any frame.**
ie
C-x b: (The completion list should show candidates from all frames)

I dont want to create any new frames. Hence, the builtin `switch-to-buffer-other-frame` isnt suitable.

Here's my attempt at adding an advice around` counsel-switch-buffer`:-

```
(defun my/counsel-switch-to-buffer-other-frame (buffer)
  "Switch to BUFFER, even if it's displayed in another frame."
  (let* ((wind (get-buffer-window buffer t))
         (frame (window-frame wind)))
    (if wind
        (progn
          (select-frame-set-input-focus frame)
          (select-window wind))
      (switch-to-buffer buffer))))

(defun my/counsel-switch-buffer-advice (orig-fun &rest args)
  "Advice function for `counsel-switch-buffer' to switch across frames."
  (let ((ivy-update-fn
         (lambda ()
           (ivy-update-candidates
            (mapcar #'buffer-name (buffer-list))))))
    (ivy-read "Switch to buffer: "
              #'ivy-update-fn
              :action #'my/counsel-switch-to-buffer-other-frame
              :caller 'counsel-switch-buffer)))

(advice-add 'counsel-switch-buffer :around #'my/counsel-switch-buffer-advice)
```

PS: wonderful package, soo snappy when compared to helm!

**Comment by basil-conto** [comment]
> **Is there a builtin way to switch to a buffer in any frame.**
> ie
> C-x b: (The completion list should show candidates from all frames)

Just to be clear, this is exactly what `counsel-switch-buffer` does: it offers as completion candidates all applicable buffers, regardless of whether they're being displayed on the current frame, a different frame, or indeed no live frame at all.

> I dont want to create any new frames. Hence, the builtin `switch-to-buffer-other-frame` isnt suitable.

So am I correct in understanding that what you want is exactly `switch-to-buffer-other-frame`, except that the selected frame should be reused in the case that the buffer is not already displayed somewhere?

If so, I would suggest looking at some of the buffer display actions under [`(elisp) Displaying Buffers`](https://gnu.org/s/emacs/manual/html_node/elisp/Displaying-Buffers.html): e.g. `display-buffer-reuse-window`, `display-buffer-use-some-frame`, `reusable-frames`, `pop-up-frames`, etc.

For example, you could bind `display-buffer-overriding-action` around the call to `counsel-switch-buffer` or its action.
