### ISSUE TITLE
It is impossible (or unclear, how exactly) to use the swiper from within itself.

### ISSUE THREAD

**Issue by paul-alkhimov** [abo-abo/swiper#309]
The initial problem is the keybindings of the *swiper*.
I want to make the shortcuts completely same to *isearch* so that I use my muscle memory without learning any new key combinations for same functionality. You know, like pressing `C-s` repeatedly would go to the next found and `C-r` would go to the previous one and so on.
Now, the problem is that if I use *isearch* and during the search I call help for some reason (say, I pressed `C-h b` and check the current key maps), I can use the *isearch* again inside that help buffer. This feature is extremely important. In fact, I only use help with support of *isearch*. With *swiper* I cannot do it though. If I try, it falls back to the initial search. Can anything be done to fix this in the sense that I have another *swiper* for help and then could return to the initial one without losing the search string?

(And related question: is it possible to limit the minibuffer so that it pops up not in complete window but inside the related buffer only? But this question is minor.)

**Comment by abo-abo** [comment]
Thanks, it should now be possible to `swiper` another buffer.  Just set `(setq enable-recursive-minibuffers t)`.

> (And related question: is it possible to limit the minibuffer so that it pops up not in complete window but inside the related buffer only? But this question is minor.

It's impossible. An Emacs limitation.

**Comment by paul-alkhimov** [comment]
When will it go to ELPA? (I use the standard facilities and do not pull from the github directly)

**Comment by abo-abo** [comment]
MELPA builds every 4 hours. A 0.7.0 release is coming to GNU ELPA this week (new release every few months).
