### ISSUE TITLE
Unable to do query-replace in swiper

### ISSUE THREAD

**Issue by zhaojiangbin** [abo-abo/swiper#31]
This is really weird to me. I have not been able to use the new query-replace feature. I always get the error "Command attempted to use minibuffer while in minibuffer" when pressing <kbd>M-q</kbd> inside swiper, regardless of the pattern, matching or not.

I reduced my `~/.emacs` file to this minimum:
```elisp
(require 'cl)
(add-to-list 'load-path "~/.emacs.d/elpa/ivy-20150326.627")
(add-to-list 'load-path "~/.emacs.d/elpa/swiper-20150325.1136")
(load "ivy")
(load "swiper")
(setq swiper-completion-method 'ivy)
```
This is the output of <kbd>C-h v</kbd>`swiper-map`:
```
swiper-map is a variable defined in `swiper.el'.
Its value is (keymap (27 keymap (113 . swiper-query-replace)))

  This variable may be risky if used as a file-local variable.

Documentation:
Keymap for swiper.
```
This is what the *Messages* buffer had for a whole Emacs session:
```
Loading ivy...done
Loading swiper...done
For information about GNU Emacs and the GNU system, type C-h C-a. [2 times]
query-replace-read-to: Command attempted to use minibuffer while in minibuffer
Quit
query-replace-read-to: Command attempted to use minibuffer while in minibuffer [2 times]
Quit
Type C-x 1 to delete the help window.
Library is file ~/.emacs.d/elpa/ivy-20150326.627/ivy.elc
Library is file ~/.emacs.d/elpa/swiper-20150325.1136/swiper.elc
```
I have tested it with different versions/builds of Emacs. They all give me the same error.

* GNU Emacs 24.4.4 (x86_64-apple-darwin13.4.0, Carbon Version 157 AppKit 1265.21)
 of 2014-11-21 on Atago.local
* GNU Emacs 24.4.91.1 (x86_64-apple-darwin13.4.0, Carbon Version 157 AppKit 1265.21)
 of 2015-03-15 on Atago.local
* GNU Emacs 24.4.1 (x86_64-apple-darwin13.4.0, NS apple-appkit-1265.21)
 of 2014-10-20 on builder10-9.porkrind.org
* GNU Emacs 24.4.91.1 (x86_64-apple-darwin13.4.0, NS apple-appkit-1265.21)
 of 2015-03-08 on builder10-9.porkrind.org

**Comment by abo-abo** [comment]
Try:

```cl
(setq enable-recursive-minibuffers t)
```

It's a really popular setting.

**Comment by zhaojiangbin** [comment]
Oh, palm meets face time again. I should have thought about recursive editing in minibuffer.
