### ISSUE TITLE
Weird behavior of swiper within twittering-mode

### ISSUE THREAD

**Issue by gnuvince** [abo-abo/swiper#310]
When doing a swiper query within the twittering timeline, matches are found only when the number of entered characters is odd.  For example:

        M-x swiper   ;; Empty listing
        e            ;; Shows entries containing an 'e'
        m            ;; Empty listing
        a            ;; Shows entries containing the substring "ema"
        c            ;; Empty listing
        s            ;; Shows entries containing the substring "emacs"

If the whole timeline buffer is copied and pasted in a fundamental-mode buffer, swiper behaves normally (no intermediate empty listings)

- GNU Emacs 24.5.1 (x86_64-unknown-linux-gnu, GTK+ Version 2.24.25)
- twittering-mode-vHEAD
- swiper 0.6.0 (obtained through MELPA)

gnuvince

**Comment by abo-abo** [comment]
Thanks, should be fixed now.
