### ISSUE TITLE
not able to move point via swiper 

### ISSUE THREAD

**Issue by ardpp** [abo-abo/swiper#311]
After `emacs -Q`, `package-initialize` do `M-x swiper` and search for `ff` with `[]` denoting the point below 

```
;; This buffer is for notes you don’t want to save, and for Lisp evaluation.
;; If you want to create a file, visit that file with C-x C-f,
;; then enter the text in that file’s own bu[]ffer.
```
I am not able to go to `ff` in the first line because the point stays where it was. The message is ` Mark saved where search started`.

**Comment by abo-abo** [comment]
Thanks, the bug was introduced by today's commit. Should be fixed now.
