### ISSUE TITLE
Search results are not complete

### ISSUE THREAD

**Issue by ReanGD** [abo-abo/swiper#313]
Error reproduction:
1) Find "def"
2) Go to a next line
3) Find

Gif with error:
![image-2015-11-29t18-16-28](https://cloud.githubusercontent.com/assets/1151286/11457868/9a63102c-96c5-11e5-9872-5f48e3429821.gif)

**Comment by abo-abo** [comment]
Thanks.

My suggestion is to try to avoid `visual-line-mode`. It's slow and not very well debugged.
The mentioned bug doesn't happen with `visual-line-mode` off.

**Comment by Balooga** [comment]
> My suggestion is to try to avoid visual-line-mode. It's slow and not very well debugged. The mentioned bug doesn't happen with visual-line-mode off.

visual-line-mode is a necessity I think when working with documentation having large paragraphs of text.  Unless there is an alternative?

**Comment by abo-abo** [comment]
> Unless there is an alternative?

A paragraph is AFAIK a body of text separated by *two* newlines. You *can* have single newlines within that body of text and have it still be a paragraph.

This applies to both plain text and LaTeX. The notion of not using newlines within a paragraph is very strange, I've only ever encountered it withing Github's poor Markdown renderer - all other Markdown renderers don't care about single newlines.

The alternative is to use <kbd>M-q</kbd> (`fill-paragraph`) - a built-in command.
And if you ever want to un-fill use:

```elisp
(global-set-key (kbd "C-M-q") 'ora-unfill-paragraph)
(defun ora-unfill-paragraph ()
  "Transform a paragraph into a single line."
  (interactive)
  (let ((fill-column (point-max)))
    (fill-paragraph nil t)))
```

**Comment by Balooga** [comment]
But splitting the sentence in effect hides it from swiper if the search criteria are split across a line break.  

> This would seem to make swiper somewhat problematic as a general search tool for documents.

Swiper will match "for documents" above.

> This would seem to make swiper somewhat problematic as a general search tool for 
> documents.

Swiper will not match "for documents".

So when I search for a string and zero results are returned, I have to realize that perhaps there is a line-break somewhere in there and change my search to either "for" or "documents".  I have experienced this on several occasions.

**Comment by Balooga** [comment]
This is a hard problem, I know.  helm-swoop has the same behaviour as swiper in this regard.
