### ISSUE TITLE
swiper: ivy-yank-word less useful when there are multiple matches in the current line

### ISSUE THREAD

**Issue by zhaojiangbin** [abo-abo/swiper#314]
Reproduction:
1- In scratch buffer enter the following line:
```
Some_type v = Some_func();
```
2- Place the cursor on the second 'S' - one that following the '='.
3- Run swiper, press `C-w` to yank the word "Some" (or type in the word "Some").
4- Watch the point jumping to the first occurrence of "Some".
5- It is now unable to yank the word "_func".

With case folded, this can happen even more often in C and C++ code. 

There is a workaround: at the prompt type "_f", instead of pressing `C-w` again in step 5. It is less convenient though.

**Comment by abo-abo** [comment]
Thanks.

**Comment by zhaojiangbin** [comment]
Well, the change does fix the issue for <kbd>M-j</kbd> (or whatever key that `ivy-yank-word` is mapped to) .

But the point still jumps to the first match when either the pattern "Some" is entered manually on prompt or `swiper` is called with a non-nil initial input such as <kbd>M-:</kbd>`(swiper "Some")`. Subsequently, `ivy-yank-word` is made unable to pick up the wanted word.

**Comment by abo-abo** [comment]
Thanks, please test. In the future, if you find that I closed an issue opened by you, and the issue isn't solved, please re-open it.  If the issue isn't tracked by Github, I'll likely forget about it.

**Comment by zhaojiangbin** [comment]
Fixed. Thanks very much.

I don't have the privilege of re-opening closed issues even opened by myself. :) In the future I can open a new issue and refer the old one in it.
