### ISSUE TITLE
Ivy interferes with default tmm-menubar behavior

### ISSUE THREAD

**Issue by jonEbird** [abo-abo/swiper#316]
While running without the toolbar or menubar enabled, I will occasionally use `tmm-menubar`  via ``(M-`)`` to access the menu items but navigating the menu options is problematic with ivy-mode enabled. To get it to work, I have to clear the text and then use the arrow keys to select the item and repeat for sub-menu items.

I could be missing a configuration but I believe this is a unique issue. I am wondering if a reimplementation of `tmm-prompt` is in order when using `ivy-mode`?

**Comment by abo-abo** [comment]
> I am wondering if a reimplementation of tmm-prompt is in order when using ivy-mode?

Added `counsel-tmm`. I also added a work-around for the original `tmm-menubar`.

**Comment by jonEbird** [comment]
Thanks for the quick workaround fix! 

Is there a particular way I should use `counsel-tmm`? I'm getting `(void-variable tmm-table-undef)` when calling it interactively.
