### ISSUE TITLE
Additional features on swiper

### ISSUE THREAD

**Issue by emacsuser123** [abo-abo/swiper#319]
Hi.

First of all, thanks for this package. I think it is really useful. The space-based regular expression matching is very handy at any time.
I use swiper in place of the native search system in emacs.

However, there's a couple of features that I miss:

- Search should be made cyclic.  Once you have reached the end of the list of occurrences, the user should be notified with something like "end of list" and, if the user keeps pressing C-s or C-n, the app should take her back to the first occurrence.
This is applicable to both forward-searches and backward-searches.

- Backward searching seems a bit counter-intuitive.  Let's say that the point is at the very end of the document. If you try to search backwards, it performs a forward search, instead, and starting the search at the very beginning of the document. 

I think these two features are quite important, since that is the native behavior of the emacs search system, and I believe it helps users a lot.

Thanks.
-Bob

**Comment by abo-abo** [comment]
> Search should be made cyclic

Use `(setq ivy-wrap t)`.

> Backward searching seems a bit counter-intuitive.

There's no backward or forward searching implemented: the search is in the whole document at once.

**Comment by emacsuser123** [comment]
Hi.

Thanks for the promp response.

With regard to the cyclic behavior:
OK, I have set the ivy-wrap flag to true, and now the search is cyclic. Thanks a lot.

With respect to the backward search ... 
understood.  Are there any plans to implement it?

Thanks a lot.
-Bob

**Comment by abo-abo** [comment]
> Are there any plans to implement it?

There's nothing to implement, as far as I see. The current approach works as intended.

**Comment by sshbio** [comment]
It seems that forward/backward are done with <kbd>C-n</kbd> <kbd>C-p</kbd>, so a call to swiper (<kbd>C-s</kbd>) then <kbd>C-p</kbd> would select the same element as <kbd>C-r</kbd> did?

**Comment by abo-abo** [comment]
Thanks, I finally understood what you meant by the "backward" search.
