### ISSUE TITLE
Errors running M-x ivy-occur

### ISSUE THREAD

**Issue by gnuvince** [abo-abo/swiper#320]
GNU Emacs 24.5.1
Swiper 0.7 (bug also present with latest version from MELPA)

After opening GNU Emacs and visiting a file (my init.el in this case), running ivy-occur gives the following error message:

    exit-minibuffer: No catch for tag: exit, nil

A buffer called `*ivy-occur "init"*` is created (ivy-occur-mode) and it contains the following text:

        1 candidates:
            /home/vince/.emacs.d/init.el

My configuration for Swiper and ivy:

    ;; Ivy
    (use-package swiper
      :demand t
      :diminish ivy-mode
      :bind (("M-x"   . counsel-M-x)
             ("M-1 r" . ivy-recentf)
             ("M-1 s" . swiper)
             ("M-1 o" . ivy-occur))
      :config
      (setq ivy-display-style 'plain)
      (ivy-mode 1))

**Comment by abo-abo** [comment]
It seems you've misunderstood how `ivy-occur` works:

> Stop completion and put the current matches into a new buffer.
> 
> The new buffer remembers current action(s).

First you have to start a completion session, e.g. `swiper` or `counsel-git-grep`, then exit that session with <kbd>C-c C-o</kbd>.

**Comment by gnuvince** [comment]
Oh, sorry!  I assumed it was similar to helm-occur.  Thanks for clearing that up!

**Comment by abo-abo** [comment]
No problem:)
