### ISSUE TITLE
Make / behave like in ido

### ISSUE THREAD

**Issue by piranha** [abo-abo/swiper#321]
So in ido, when you press `/` during find-file, it effectively "opens" the directory: you still can choose between directories, but if you start typing, currently chosen directory is assumed and after that you search inside of it.

I wonder if it's possible to make `counsel-find-file` behave somewhat like that? I think I can live with just slash choosing a directory during finding files (but not in other completion contexts). Is there a way I can do that?

**Comment by abo-abo** [comment]
You can use this in your config:

```elisp
(define-key counsel-find-file-map "/" 'ivy-alt-done)
```

This is too surprising to be on by default, in my opinion. In addition, you would lose the ability to quickly go to the root directory and to `/ssh:` from the current directory.

**Comment by piranha** [comment]
Yeah, in case of ido you can press slash twice and you'll get to root directory...

**Comment by abo-abo** [comment]
I've just checked how <kbd>/</kbd> works in `ido-mode`: it doesn't select the item always, only when it's the only choice available. I can add that behavior, only I expect it to be quite frustrating if you want to select one item, and there's another one that's very close to it: you'd have to pretty much type out the whole thing until only one item matches. Using <kbd>C-n</kbd> and <kbd>C-j</kbd> would be a lot faster in that case.

**Comment by piranha** [comment]
Ok, I'll try adapting to what ivy does. :)

**Comment by abo-abo** [comment]
Please test the new functionality, let me know if anything's weird.

**Comment by piranha** [comment]
Works nicely! Except in one case: if I type `~/`, instead of switching to my home directory, it is opened.

**Comment by abo-abo** [comment]
> Except in one case: if I type ~/, instead of switching to my home directory, it is opened.

By default, `~` should switch you to home, and the following `/` would simply self-insert. Do you have any custom config?

**Comment by piranha** [comment]
Ah right! Thanks a lot, works like a charm.
