### ISSUE TITLE
ivy-reverse-i-search not working properly (or I missed something)

### ISSUE THREAD

**Issue by swhahn** [abo-abo/swiper#323]
Hello,

when using C-r (ivy-reverse-i-search) from within counsel-find-file I get:

- no change if choosing a directory
- just the filename in current dir if choosing a different path with file.

Example:
C-x C-f (counsel-find-file) in dir ~/.emacs.d/ gets

> Find file: ~/.emacs.d/

C-r gets a list of dirs/files: e.g. /usr/src/file.test

Selecting this with C-m, I get:

> Find file: ~/.emacs.d/file.test

What I expected is to get:

> Find file: /usr/src/file.test

Selecting a dir without file changes nothing. For this I would expected to
get a listing for the coosen dir.

I'm using commit 706349fcfae297ee285552af9246bc0cf00d9b7f (tag: 0.7.0).

With kind regards,
Stefan

**Comment by abo-abo** [comment]
Thanks, now it should work again.
