### ISSUE TITLE
Redundant warning on compilation when installing swiper

### ISSUE THREAD

**Issue by asampal** [abo-abo/swiper#324]
I'm using Windows 10 64 bit, Emacs 24.5

When installing swiper, `Compile-Log` shows the following warning. I suppose the functions referred to used to be needed only in `swiper.el`, but are now used elsewhere. Maybe the names could be changed to reflect their current use. Not sure if that would eliminate the warning.

```
Compiling file d:/dev/msys64/home/adi/.emacs.d/elpa/swiper-20151217.235/ivy.el at Thu Dec 17 19:31:07 2015

In end of data:
ivy.el:2462:1:Warning: the following functions are not known to be defined:
    swiper--cleanup, swiper--add-overlays,
    pulse-momentary-highlight-one-line
```

**Comment by abo-abo** [comment]
Thanks.

**Comment by asampal** [comment]
Looks good for the first two, but there is still a warning about `pulse-momentary-highlight-one-line`.

**Comment by asampal** [comment]
I guess in a stable version you'd have probably cleaned these kinds of things up. Do you want me to stop reporting similar things if I'm loading non-stable?

**Comment by abo-abo** [comment]
Please report the warnings if you catch them. I didn't see this one because I had a bug in my Makefile, so `make compile` was producing no warnings.
