### ISSUE TITLE
jump to selected case?

### ISSUE THREAD

**Issue by yitang** [abo-abo/swiper#325]
Hi, Thanks for writing `ivy` and `swiper`, I am trying these two packages and hopefully they can replace helm for my usage. 

I must miss something here. When I use `swiper` to search and type Enter to choose the selected case, it brings me back to the point where I started swiper... What went wrong?

**Comment by abo-abo** [comment]
Can you give a more precise example, with buffer text and enabled modes. This is a simplest feature that should work always, yet no one else has reported a similar bug.

**Comment by yitang** [comment]
I am surprised that it don't works for me as well. 

![screen shot 2015-12-20 at 12 13 21](https://cloud.githubusercontent.com/assets/6054101/11917927/162706b6-a713-11e5-9d57-7ec71963ad90.png)
here is an demo: 

The content of the buffer: 

![screen shot 2015-12-20 at 12 04 47](https://cloud.githubusercontent.com/assets/6054101/11917888/f6c129ce-a711-11e5-94a2-9da71a2d31f6.png)

Use swiper to search **you**: 

![screen shot 2015-12-20 at 12 06 42](https://cloud.githubusercontent.com/assets/6054101/11917894/28c3ab36-a712-11e5-85c4-1cec53221315.png)

Press Enter to choose the first occurrence. The current point don't change. Note the echo area shows `'Mark saved where search started` 

here is a list of enabled models. 

![screen shot 2015-12-20 at 12 13 21](https://cloud.githubusercontent.com/assets/6054101/11917929/2cd83cfe-a713-11e5-9a46-cf8cc1f9d303.png)

**Comment by abo-abo** [comment]
Your third screenshot looks to be correct. After you press <kbd>RET</kbd>, the point shouldn't change, since it's already in the correct position.

**Comment by yitang** [comment]
After I press RET, the point moved back to where I started 'swiper', in this example, it is the end of line 5. Should the correct point be the 'you' at line 1?

**Comment by yitang** [comment]
Sorry, I messed with the screenshots... Do you understand my problem now? or could you wanna the correct screenshots?

**Comment by abo-abo** [comment]
> Should the correct point be the 'you' at line 1?

Yes, of course.

You should debug your Emacs configuration. First, verify that swiper works correctly by opening a shell in `swiper/` directory and running:

    emacs -Q -l ivy.el -l colir.el -l swiper.el

<kbd>M-x</kbd> `swiper` should work fine in that case.

Second, turn off the packages in your config, one by one and see which one makes the bug appear/disappear.

**Comment by yitang** [comment]
I've updated all the Emacs packages, and the problem is gone. Thanks.

**Comment by abo-abo** [comment]
OK, glad it's resolved.
