### ISSUE TITLE
Rebinding ivy keys

### ISSUE THREAD

**Issue by rsuhada** [abo-abo/swiper#327]
Could you please help me understand how to correctly rebind some of the keys: I'd like M-u and M-e to be ivy-previous-line and ivy-next-line when in swiper.

This is my attempt:

    (use-package ivy
      :diminish ivy-mode
      :init
      (setq ivy-use-virtual-buffers t)
      (ivy-mode 1)
      :config
      (setq ivy-wrap t)
      (define-key ivy-minibuffer-map (kbd "M-e") 'ivy-next-line)
      (define-key ivy-minibuffer-map (kbd "M-u") 'ivy-previous-line)
      )
    
    (use-package swiper
      :ensure t
      :bind ("\C-f" . swiper)
      ("C-S-f" . swiper-multi)
      :config
      )

Up to now I only use swiper. Would like to use my keys instead of C-n / C-p. Neither rebinding for ivy-minibuffer-map nor ivy-map helped though, I think I'm misunderstanding something.... 

Thank you for the fantastic work! I'm learning now ivy/swiper and hydra will be next!

**Comment by abo-abo** [comment]
> (define-key ivy-minibuffer-map (kbd "M-e") 'ivy-next-line)
> (define-key ivy-minibuffer-map (kbd "M-u") 'ivy-previous-line)

Might be an issue with `use-package` or something else, because the code above is correct for what you want to do.

Try this:

```
(require 'ivy)
(define-key ivy-minibuffer-map (kbd "M-e") 'ivy-next-line)
(define-key ivy-minibuffer-map (kbd "M-u") 'ivy-previous-line)
```

and restart Emacs.

**Comment by rsuhada** [comment]
Thank you Oleh. I've experimented and found out that the problem is not with use-package. I define my keys in a minor mode:

    (defvar rsk-minor-mode-map (make-keymap) "rsk-minor-mode keymap.")
    (define-key rsk-minor-mode-map (kbd "M-u") 'previous-line) 
    (define-key rsk-minor-mode-map (kbd "M-e") 'next-line)
    
    (define-minor-mode rsk-minor-mode
      "A minor mode so that my key settings override annoying major modes."
      t "" 'rsk-minor-mode-map)
    (rsk-minor-mode 1)

And I think this clashes with the ivy-minibuffer-map. Do you happen to know how to achieve that if and only if ivy search is active the bindings switch to ivy-next-line / ivy-previous-line and stay my two commands elsewhere.

Thank you very much!

**Comment by abo-abo** [comment]
Have a look here: http://www.emacswiki.org/emacs/minor-mode-hack.el.
All minor modes are in a list of priority, you need to raise `ivy-mode` above `rsk-minor-mode`.

**Comment by rsuhada** [comment]
Unfortunately it didn't help... I've tried to both raise/lower the priorities, but no help. The curse of a Colemak keyboard!

Oddly, I've tested both ido and helm for the same keys and there it worked...
I like Swiper's interface so I think I'll just have get used to the keys...

**Comment by abo-abo** [comment]
Try this, in addition to your minor mode:

```elisp
(global-set-key (kbd "M-u") 'previous-line)
(global-set-key (kbd "M-e") 'next-line)
```

The minibuffer should obey the global bindings, and `ivy-minibuffer-map` doesn't override <kbd>M-u</kbd> and <kbd>M-e</kbd> yet.

**Comment by rsuhada** [comment]
That's a good idea! Thank you Oleh, for taking time to think about it!

Have a nice Christmas holiday season!

**Comment by ichirika** [comment]
emmm. obviously..im more wilful than you..
i want to bind C-x in ivy-minibuffer-map, lol..
