### ISSUE TITLE
Possibility of something like ido-grid-mode

### ISSUE THREAD

**Issue by stormbr** [abo-abo/swiper#328]
First my thanks for your work.
I want to show completions of ivy in a grid a la ido-grid-mode. Is it possible?

Thanks

**Comment by abo-abo** [comment]
It's possible, but I don't recommend it. Try this code:

```elisp
(defun ivy--split-rows (list rows)
  (let ((r1 nil)
        (r2 nil)
        (i 0)
        el)
    (while (setq el (pop list))
      (push el r2)
      (when (>= (cl-incf i) rows)
        (setq i 0)
        (push (nreverse r2) r1)
        (setq r2 nil)))
    (when r2
      (push (nreverse r2) r1))
    (nreverse r1)))

(defun ivy-format-function-grid (cand-pairs)
  "Transform CAND-PAIRS into a string for minibuffer."
  (let* ((w (1+ (apply #'max (mapcar (lambda (x) (length (car x))) cand-pairs))))
         (fmt-col (format "%%- %ds" w)))
    (setf (car (nth ivy--index cand-pairs))
          (ivy--add-face
           (car (nth ivy--index cand-pairs))
           'ivy-current-match))
    (concat
     (mapconcat #'identity
                (apply #'cl-mapcar
                       (lambda (&rest lst)
                         (mapconcat (lambda (x) (format fmt-col (if x (car x) ""))) lst " "))
                       (ivy--split-rows cand-pairs (/ (length cand-pairs) 3)))
                "\n")
     "\n")))
(setq ivy-format-function 'ivy-format-function-grid)
```

This approach suffers from bad scrolling - the matrix gets scrolled each time the current candidate changes. Even if this was solved, there's still the issue of formatting uneven strings into columns and the overall readability of it all. Seems more trouble that it's worth, but you can still hack on it if you like.

**Comment by stormbr** [comment]
thanks for your prompt reply. I will hack at it,

**Comment by abo-abo** [comment]
If you want to have proper scrolling, you might want to re-define `ivy--format`: this function gets the full list of strings that match and returns a single string to insert into the minibuffer.
