### ISSUE TITLE
Could ivy-completing-read pass :caller this-command to ivy-read?

### ISSUE THREAD

**Issue by ilohmar** [abo-abo/swiper#330]
I am trying to replace my fine-tuned ido (+ addons) setup with ivy, and in most respects, it's a step forward!  One issue I have is this, however: I would like to use `ivy-completing-read` as a drop-in replacement for as many things as possible, but I still want to set the completion style as per `ivy-re-builders-alist` for some of these commands.

Are there any downsides to passing `:caller this-command` where `ivy-completing-read` calls `ivy-read`?

This is what I've done to get non-flx completion for `org-refile` (while I use flx completion everywhere else), and so far that works fine.

**Comment by abo-abo** [comment]
Thanks, please test.

> Are there any downsides to passing :caller this-command where ivy-completing-read calls ivy-read?

The downside is that it's impossible to tell whether the :caller was explicit of passed via ivy-completing-read.  Removes granularity.  Also, `this-command` can be manipulated. Still, I put `this-command` on priority list of keys behind `:caller`. So your case should work fine now.

**Comment by ilohmar** [comment]
Works nicely.  Thanks a lot!
