### ISSUE TITLE
counsel-at-point for generic completion at point

### ISSUE THREAD

**Issue by sshbio** [abo-abo/swiper#331]
I reconstituted these snippets from [your dotfiles](https://github.com/abo-abo/oremacs/search?utf8=%E2%9C%93&q=counsel&type=Code).  Are these right?

```
(require 'python)
(define-key python-mode-map (kbd "C-M-i") 'counsel-jedi)
```
```
(require 'lisp-mode)
(define-key lisp-mode-map (kbd "C-M-i") 'counsel-cl)
```
```
(require 'clojure-mode)
(define-key clojure-mode-map (kbd "C-M-i") 'counsel-clj)
```
```
(define-key lisp-mode-shared-map "C-M-i" 'counsel-el)
;; or maybe
(define-key emacs-lisp-mode-map "C-M-i" 'counsel-el)
```

And maybe as well
```
(define-key org-mode-map (kbd "C-c C-q") 'counsel-org-tag)
```

Such snippets could either be added to the wiki or the readme snippet.  But what would be really great would be a generic completion method, like [ido-at-point](https://github.com/katspaugh/ido-at-point/blob/master/ido-at-point.el#L35), which would complete symbol at point with ivy using built-in completion system or the counsel-* completions functions if dependencies are available.

It may not require much changes to this package, since using it and re-defining this function worked for me:

```
(defun ido-at-point-read (comps common)
  (completing-read "" comps nil t common))

(ido-at-point-mode 1)
```

`ivy-completing-read` worked as well.

Thank you for your attention and awesome completion system!

[EDIT] Oh, and no hurry of course, this is a suggestion and not a request!

**Comment by abo-abo** [comment]
Thanks, I'll work on this in the future. I've been meaning to write a `completion-in-region-function` for some time now.

**Comment by sshbio** [comment]
Glad to hear it!

**Comment by abo-abo** [comment]
OK, `ivy-mode` now does in addition what `ido-at-point` does.

So `counsel-el` can be replaced with `completion-at-point` when `ivy-mode` is active.

However, I haven't yet figured out how to hook e.g. `counsel-jedi` into `completion-at-point`. Probably it should be the responsibility of `(jedi:setup)`.

**Comment by sshbio** [comment]
Oh, that is great news, thank you!
Ivy is amazing: with 20 more lines, I can remove a package!

I do not know how jedi is usually integrated with complenion systems.

Maybe [company]() and [autocomplete](https://github.com/syohex/emacs-company-jedi/blob/master/company-jedi.el) implementations could help.

Both seems to use [jedi-core](https://github.com/tkf/emacs-jedi/blob/master/jedi-core.el) as a basis.

Maybe you have seen all of this already.

**Comment by sshbio** [comment]
Yes, by looking at the sources, you are already aware of it! ^^

**Comment by s-kostyaev** [comment]
What do you think about `counsel-company`? Counsel may be very good frontend for company like `helm-company`.

**Comment by abo-abo** [comment]
@s-kostyaev Have a look.

**Comment by s-kostyaev** [comment]
@abo-abo Thanks. Looks good. Can you also add action for showing docs for candidates? I don't know how it works in company, but `helm-company` can't do this. Wait for new melpa build.

**Comment by s-kostyaev** [comment]
@abo-abo for me very useful something like this:
```elisp
(defun counsel-company ()
  "Complete using `company-candidates'."
  (interactive)
  (unless company-candidates
    (company-complete))
  (when company-point
    (company-complete-common)
    (when (looking-back company-common (line-beginning-position))
      (setq ivy-completion-beg (match-beginning 0))
      (setq ivy-completion-end (match-end 0)))
    (ivy-read "company cand: " (mapcar (lambda (x)
                                         (concat
                                          x
                                          "\t\t"
                                          (company-call-backend 'annotation x)))
                                       company-candidates)
              :action (lambda (x)
                        (ivy-completion-in-region-action
                         (replace-regexp-in-string "\t\t\.*" "" x))
                        (run-at-time 0.01 nil 'company-pseudo-tooltip-hide)))))
```
But I think that annotation should have another face. May be need some defcustom for customize that.

**Comment by s-kostyaev** [comment]
I think adding annotations (with correct face) must be done by transformer, but my transformer does not work for now:
```elisp
(defun counsel-company-transformer (str)
  "Add highlighted annotation into STR."
  (let ((annotation (company-call-backend 'annotation str))
    (set-text-properties 0 (length annotation) '(face success) annotation)
    (concat str "\t\t" annotation))))

(ivy-set-display-transformer 'counsel-company 'counsel-company-transformer)
```

**Comment by abo-abo** [comment]
@s-kostyaev Could you please open a new issue with the above two code snippets? I don't have time right now to deal with them, but I don't want to forget about it. An open issue helps to track it, but I don't want to re-open this one.

**Comment by s-kostyaev** [comment]
@abo-abo done.

**Comment by NightMachinary** [comment]
@s-kostyaev Where is the new issue you opened about showing docs with `counsel-company`?
