### ISSUE TITLE
counsel-describe-prefix-bindings ?

### ISSUE THREAD

**Issue by sshbio** [abo-abo/swiper#332]
I found this feature for ido: [ido-describe-prefix-bindings.el](https://github.com/larkery/ido-describe-prefix-bindings.el).

Here is what it gives with [ido-grid-mode.el](https://github.com/larkery/ido-grid-mode.el) (which may worth having a look by the way) after pressing <kbd>C-x</kbd> <kbd>C-h</kbd>:

[![](https://raw.githubusercontent.com/larkery/ido-grid-mode.el/master/pictures/vertical-example.gif)](https://github.com/larkery/ido-grid-mode.el)

This does not work with ido (not be comptible with emacs 24.5 or 25.1.50?), but I think this feature would be great for ivy.

Maybe this could also fit to hydra: complete next possible commands (those bound to keys in the hydra) with a completion system such as ivy.

Another possibility for hydra would be creating a hydra after any key (<kbd>C-x</kbd>) with <kbd>C-h</kbd>, with next possible commands as either commands to execute (<kbd>C-x</kbd>, <kbd>C-u</kbd>...) or hydras to call (<kbd>r</kbd>, <kbd>n</kbd>...).
<kbd>r</kbd>, <kbd>n</kbd>...).

Maybe I can talk about it to the [author](https://github.com/justbur/) of [which-key](https://github.com/justbur/emacs-which-key) as well.

Again, I'm sharing my thoughts, and not making a request.

**Comment by sshbio** [comment]
I'm closing the issue, since @lakery made its version using `completing-read` (instead of `ido-...`), which uses to ivy when `ivy-mode` is activated.

So now I have got this while typing <kbd>C-x</kbd> <kbd>C-h</kbd>

![2016-01-12-131524_1366x768_scrot](https://cloud.githubusercontent.com/assets/7250745/12263335/81b8372e-b92e-11e5-861b-98871d92db1f.png)

**Comment by abo-abo** [comment]
Have a look at `counsel-descbinds`.

**Comment by sshbio** [comment]
Oh it is great, thank you!  I will bind it to some key.

**Comment by dgutov** [comment]
:fireworks:

Helm goes bye-bye from my Emacs.
