### ISSUE TITLE
adding more than one word to a query brings counsel-git-grep to a halt

### ISSUE THREAD

**Issue by vkz** [abo-abo/swiper#334]
in a pretty big Java project (but not a Linux kernel big) `counsel-git-grep` is pretty snappy with a single word query like
>git grep: must

but adding another word like
>git grep: must be

stalls it for several minutes. To compare this query from command line `git grep "must be"` is instantaneous, but the above one or comparable to the command line:
>git grep: must\\\ be

again either takes minutes or renders counsel completely unusable.

Am I doing something wrong here or is this expected?

PS tested off of your oremacs repo as of this commit https://github.com/abo-abo/oremacs/commit/32098a154a6bc226d0b5af95e865ee76d2179ffd

**Comment by abo-abo** [comment]
Just tried `must be` on the Linux kernel, got 17681 results after a usual ~0.5 second delay. The delay was the same as after `must`.  Are you using `ivy--regex-plus` (the standard one)?

**Comment by abo-abo** [comment]
I'm closing this one to keep the issue list smaller. If you can offer a reproduction of the bug, open a new issue referencing this one.
