### ISSUE TITLE
Swiper regex issue?

### ISSUE THREAD

**Issue by unmanbearpig** [abo-abo/swiper#34]
Hi! 
I'm not sure if it's a Swiper issue or a problem with something else, can you point me to a direction where to look?

I've tried searching for ^I regex to find all lines where I is the first symbol, it highlighted the I in one of the lines but it haven't displayed any matched lines.

![screen shot 2015-04-05 at 01 04 53](https://cloud.githubusercontent.com/assets/399865/6994867/be1d2e68-db30-11e4-85c9-ea3957d9d731.png)

Thanks!

**Comment by abo-abo** [comment]
> I've tried searching for ^I regex to find all lines where I is the first symbol, it highlighted
> the I in one of the lines but it haven't displayed any matched lines.

The thing is that `" I ac-c-headers"` does not match `"^I"`, since it has a leading space.
You can instead search for `"\bI\b"`. That one will give you just one match.
