### ISSUE TITLE
possible new feature: append candidates periodically

### ISSUE THREAD

**Issue by justbur** [abo-abo/swiper#340]
Using `counsel-ag`, if I type a string that's pretty common (~5k-10k candidates maybe) I see the collected notice at the bottom for a few seconds and then the minibuffer fills with candidates when the process is done. Obviously, I need to refine my search. I know that I need to refine it once that counter starts getting large, but I think it would be helpful to see the types of matches I'm getting right away. 

So what I was thinking is what if you could configure `ivy-read` to collect all of the candidates but to start showing them as soon as you reach some number (I don't know 500 or so). That way you get visual feedback right away showing all of the bad matches you're getting and you can start thinking about how you want to refine the search immediately. 

This question is inspired by how helm-ag works. Somehow helm-ag shows matches immediately, but keeps collecting remaining ones in the background.

**Comment by myrjola** [comment]
I second this proposal. `ag` can take quite a while to search larger projects e.g. the Linux kernel, so showing some intermediate results would be very helpful.

**Comment by zilongshanren** [comment]
+1 for the proposal

**Comment by abo-abo** [comment]
Please check. The candidate list should refresh every 0.5s and display `++` next to the number of candidates.

**Comment by myrjola** [comment]
Wonderful work @abo-abo! Works like a charm.

**Comment by justbur** [comment]
Thanks @abo-abo I haven't played with it too much, but it's not as smooth as I would have hoped on my computer. 

My first thought for an alternative was something like this. 

```elisp
(defvar counsel--async-lines 0)
(defvar counsel--async-line-threshold 1000)

(defun counsel--async-filter (process str)
  "Receive from PROCESS the output STR."
  (when (< counsel--async-lines counsel--async-line-threshold)
    (let (size)
      (with-current-buffer (process-buffer process)
        (insert str)
        (setq counsel--async-lines
              (count-matches "\n" (point-min) (point-max)))
        (when (< counsel--async-lines counsel--async-line-threshold)
          (goto-char (point-min))
          (setq size (- (buffer-size) (forward-line (buffer-size))))
          (setq ivy--all-candidates
                (split-string (buffer-string) "\n" t))))
      (let ((ivy--prompt (format "%d++ ag:" size)))
        (ivy--insert-minibuffer
         (ivy--format ivy--all-candidates))))))
```

I know I need to do the paperwork now.
