### ISSUE TITLE
Some issues with the new point completion

### ISSUE THREAD

**Issue by thwg** [abo-abo/swiper#341]
I upgraded my swiper install and found the new ivy point completion features.  I really like the idea, but am running into a couple bugs with this feature, and have disabled it for myself at the moment:

Too aggressive replacement:

I spawn bash shells using `shell`.  When using `cd` and hitting tab to get completion, ivy will complete the term as well as replace the starting input.  This is good for replacing uncompleted content, but not always the whole term used for completion.

Example:

```bash
$ cd pat<tab>
$ cd path/to/dir<tab>
$ cd directory/
```

Expected behavior would be to replace `pat` in the first, then `dir` in the second.  `path/to/dir` is replaced in the second, resulting in an invalid directory.

---

Completion doesn't work from within the minibuffer.  I receive a recursive minibuffer error, since ivy handles it in the minibuffer as opposed to the `*Completions*` buffer.

Example: <kbd>M-x</kbd> `customize-face` `def` <kbd>TAB</kbd>

---

This is minor, but is there a reason for binding `ivy-count-format` in https://github.com/abo-abo/swiper/commit/569c11e9a4b1734594ac5c7a29fb607b259a4911 with the compact value?  I usually keep mine disabled, and it is re-enabled for the point completion.

**Comment by abo-abo** [comment]
Thanks, please test. All your concerns have been addressed. Please try to file separate issues for independent concerns.

**Comment by thwg** [comment]
Thanks for the fixes, I've just now got the opportunity to re-enable and test in my Emacs.

The first two cases work great now, but the `ivy-count-format` should check empty string rather than nil.  I've opened #349 for the special cases needed with empty `ivy-count-format` in `ivy-completion-in-region`.

> Please try to file separate issues for independent concerns.

Will do in the future.
