### ISSUE TITLE
combine switch-to-buffer, recentf, bookmarks together

### ISSUE THREAD

**Issue by stardiviner** [abo-abo/swiper#347]
I wish ivy(counsel) can provide a function to combine `switch-to-buffer`, `recentf`, `bookmark` together.
I want this function because I always open files, I don't know whether I closed buffer (it's in recentf), or not opened still in bookmark list. I want a union entry to access all of them despiting their state difference.
I like the behavior of `helm-mini`. It provide user to put resources into entry.

**Comment by abo-abo** [comment]
`ivy-switch-buffer` already combines `switch-to-buffer` and `recentf`. I can add an option for bookmarks, but it's probably better to have them separate: bookmarks are for quick access and change rarely; aggregating them into `ivy-switch-buffer` would mean that either they would be dead weight increasing the number of candidates for no reason, or `bookmark-jump` would become obsolete although it's faster for having less candidates and changing the candidate list rarely.

**Comment by stardiviner** [comment]
I see.
If you think combine them together is un-necessary in official repository.
I can accept define a user custom function in my init file.
Can you provide the code to do this? Thanks.

**Comment by abo-abo** [comment]
```elisp
(setq ivy-use-virtual-buffers t)
```

Makes `ivy-switch-buffer` use bookmarks and recentf. Such an old feature that I forgot that it did bookmarks too.

**Comment by abo-abo** [comment]
By the way, this customization is also shown in `(Info-goto-node "(ivy)")`.

**Comment by stardiviner** [comment]
I tried option `ivy-use-virtual-buffers`. It includes `recentf`. But does not have `bookmarks`.

**Comment by abo-abo** [comment]
It completes off `bookmarks-alist`. Do you have that variable configured properly (should be the case if you didn't touch it)?

**Comment by stardiviner** [comment]
I check out `bookmark-alist`, but it is nil. I tested with `emacs -q`. It is fine.
I will debug my configs. Thanks.

**Comment by stardiviner** [comment]
I found ivy switch buffers shows candidates does not match with my bookmarks result. (I also tested with `emacs -q`.)
Here are steps I use in `emacs -q`:
1. `package-initialize`
2. `(require 'bookmark)`
3.
``` lisp
;; load bookmarks from file.
(with-eval-after-load 'bookmark
  (setq-default bookmark-default-file
                (expand-file-name "bookmarks.el" user-emacs-directory))
  (bookmark-maybe-load-default-file))
```
4. `(require 'swiper)`
5. 
```lisp
(setq ivy-use-virtual-buffers t ; treat recentf, bookmarks as virtual buffers.
        ivy-height 5
        ivy-display-style 'fancy
        ivy-count-format "(%d/%d) "
        ivy-initial-inputs-alist nil ; remove initial ^ input.
        ivy-extra-directories nil ; remove . and .. directory.
        ivy-wrap nil
        )
(ivy-mode 1)
```
6. `(global-set-key [remap switch-to-buffer] 'ivy-switch-buffer)`

Here are two screenshots. one is using bookmark list, and another is using ivy-switch-buffer.

<blockquote class="imgur-embed-pub" lang="en" data-id="T3Hga"><a href="//imgur.com/T3Hga">View post on imgur.com</a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>

**Comment by abo-abo** [comment]
Eval:

```elisp
(mapcar (lambda (bookmark)
          (cdr (assoc 'filename bookmark)))
        bookmark-alist)
```

Should return a list of strings.

**Comment by stardiviner** [comment]
This returned list of strings is correct with `bookmark-bmenu-list` result.

**Comment by abo-abo** [comment]
Have a look at:

```elisp
(progn
  (ivy--virtual-buffers)
  ivy--virtual-buffers)
```

Maybe bisect your config until the return result becomes correct.

**Comment by stardiviner** [comment]
After evaluating upper code, the returned result is wrong.
I will bisect my init files.
Thanks for your help.

**Comment by stardiviner** [comment]
I got different candidates result after setting `ivy-virtual-abbreviate` to `'full`. The `'full` value result is correct.

**Comment by stardiviner** [comment]
I know why now, because `ivy-virtual-abbreviate 'name` (uniquify) is enabled, makes bookmarks which has same `file-name-nondirectory`. They are combined to one candidate.

**Comment by abo-abo** [comment]
I've been using `'name` for a very long time, with no problems. Other people prefer `'full`.  Something like `'uniquify` is in the works, but it's boring to debug and release.

**Comment by stardiviner** [comment]
with uniquify.
The bookmarks which has file path to the same filename like bellowing:
```
#("/home/stardiviner/Org/Wiki/Computer/Programming/Programming Languages/Python/Data/Packages/Packages.org" 0 103
   (face ivy-virtual))
 #("/home/stardiviner/Org/Wiki/Computer/Programming/Programming Languages/JavaScript/Data/Packages/Packages.org" 0 107
   (face ivy-virtual))
 #("/home/stardiviner/Org/Wiki/Computer/Programming/Programming Languages/TeX/Data/Macro Packages/Macro Packages.org" 0 112
   (face ivy-virtual))
 #("/home/stardiviner/Org/Wiki/Computer/Programming/Programming Languages/Julia/Data/Packages/Packages.org" 0 102
   (face ivy-virtual))
```

I think ivy should not use bookmark filename path value as candidate, should use bookmark name instead. This can avoid `uniquify` like this issue.

**Comment by abo-abo** [comment]
Nothing says that the bookmark names are unique wrt buffer names.

**Comment by stardiviner** [comment]
Emm, right.

**Comment by stardiviner** [comment]
I will `'full` as the value.
