### ISSUE TITLE
replace directory . and .. with keybinding

### ISSUE THREAD

**Issue by stardiviner** [abo-abo/swiper#348]
I found command `counsel-find-file` will display `.` and `..` to represent current directory and upper directory. It will make user navigate in candidates two more steps. I think this should be put in keybindings (more easier)

**Comment by abo-abo** [comment]
Navigating upwards (`..`) is already bound to <kbd>DEL</kbd>, and selecting the directory (`.`) is already bound to <kbd>C-m</kbd>.

You can customize this further in your own config if you wish, use `counsel-find-file-map` and `ivy-extra-directories`.
