### ISSUE TITLE
Swiper doesn't support search wrap?

### ISSUE THREAD

**Issue by andyque** [abo-abo/swiper#35]
When I hit `C-s` to issue swiper to search, when the search goes to the end of the buffer, it doesn't research from the beginning of the buffer.

Could I do some configuration to enable this behavior?

Thanks.

**Comment by abo-abo** [comment]
You need to set this:

    (setq ivy-wrap t)

The default non-wrapping behavior is there to give you a feeling when you've reached the start or the end. You can use <kbd>M-&lt;</kbd> and <kbd>M-&gt;</kbd> as well.
