### ISSUE TITLE
Electric help package for `counsel-describe-*`

### ISSUE THREAD

**Issue by sshbio** [abo-abo/swiper#355]
I discovered the ehelp package built-in emacs.  It displays help windows in an adapted size buffer and switch to them so that a simple <kbd>q<kbd> quits the window.

It has different multiple replacement functions, starting by `electric-` and the name of the function it replaces.

It is usually enabled by binding <kbd>C-h</kbd>, <kbd>f11</kbd> and <kbd>help</kbd> to `ehelp-command`, and hence, the `counsel-describe-*` functions do not use the ehelp buffer while it is "enabled".

Are you interested in using ehelp by default or in a custom variable to enable it?

Thank you for your attention!

**Comment by abo-abo** [comment]
I don't understand what I need to do here. If you want to use `ehelp`, try to redefine it in your config from:

```elisp
(defun electric-describe-function ()
  (interactive)
  (electric-helpify 'describe-function))
```

to:

```elisp
(defun electric-describe-function ()
  (interactive)
  (electric-helpify 'counsel-describe-function))
```

The code of ehelp looks obscure, borderline obsolete (just look at the signature of `electric-describe-function`), so I'm not interested in using it.

**Comment by sshbio** [comment]
I do not know why, the email I sent do not appear here...  Here it is:

> I thought this was not possible to do this without modifying counsel but I was wrong.  Thank you for the tip.

> I had a look at the commits, and there are nearly only documentation and licence updates.

> I thought it was like ibuffer that is much usefull even if net enabled by default.

> No need for support of this kind of packages, of course.

> I wish I could contribute instead of always opening issues.  I will ask a second time for a copyright assignment.  Your comment will help:  https://github.com/abo-abo/avy#copyright-assignment
