### ISSUE TITLE
add a counsel-* function for kill Emacs processes

### ISSUE THREAD

**Issue by stardiviner** [abo-abo/swiper#357]
For example, some inferior process will try to start a process. (the process can be listed with command `process-list`)

Helm has support for this.
I usually need to kill a specific process, to stop or restart process again.

**Comment by abo-abo** [comment]
> Helm has support for this.

Command name?

**Comment by stardiviner** [comment]
Helm command is `helm-list-emacs-process`.

**Comment by abo-abo** [comment]
Thanks, have a look.

**Comment by stardiviner** [comment]
It's ok.
