### ISSUE TITLE
Place point at the beginning of the match after M-x swiper ?

### ISSUE THREAD

**Issue by opsound** [abo-abo/swiper#359]
Is there a way to have the point go to the beginning of the match after selecting the match (i.e. like vim's ``/``)?

**Comment by abo-abo** [comment]
This can be solved in a generic way that's not specific to `swiper` (like `isearch-forward` etc):

```elisp
(defun move-to-match-beginning ()
  "When the match start is on this line, move there."
  (interactive)
  (let ((mb (match-beginning 0)))
    (if (and mb
             (= (line-number-at-pos mb)
                (line-number-at-pos (point))))
        (goto-char mb)
      (message "the previous command wasn't a search"))))

(global-set-key (kbd "C-/") 'move-to-match-beginning)
```

Press <kbd>C-/</kbd> after the search to move to match start. This can work even a few commands after the search, as long as these commands don't touch the match data.

**Comment by opsound** [comment]
Thanks for the response abo-abo!  That looks perfect.  Is there something analogous to ``isearch-mode-end-hook`` to which I can bind ``move-to-match-beginning``, so that it happens automatically?
```
 (add-hook 'swiper-mode-end-hook 'move-to-match-beginning)
```

**Comment by abo-abo** [comment]
You can use `advice-add`:

```elisp
(advice-add
 'swiper--action
 :after
 (defun move-to-match-beginning* (_)
   (goto-char (match-beginning 0))))
```

**Comment by opsound** [comment]
Works perfectly.  Thanks!
