### ISSUE TITLE
Feature request: ivy-switch-buffer-other-window

### ISSUE THREAD

**Issue by franburstall** [abo-abo/swiper#361]
It would be really nice to have ivy-switch-buffer-other-window exist and bound to C-x 4 b when ivy-mode is active.  Currently, C-x 4 b fails on virtual buffers.

I understand I can do the switch with C-x b followed by M-o j but my muscles don't know that!

---Fran

**Comment by abo-abo** [comment]
Thanks, the new command should be automatically bound.

**Comment by franburstall** [comment]
So quick!  Many thanks.

---Fran
