### ISSUE TITLE
Is there something like `ido-ignore-buffers` for Ivy?

### ISSUE THREAD

**Issue by mrkkrp** [abo-abo/swiper#366]
I'm trying to switch from IDO to these wonderful packages. The only (admittedly minor) problem I have is that when I switch buffers with Ivy, there are too many buffers, i.e. it includes buffers that I usually don't want to switch to, so they are effectively some sort of noise.

With IDO, I could filter some buffers like this:

```emacs-lisp
(dolist (buffer '("^\\*Backtrace\\*$"
                  "^\\*Compile-Log\\*$"
                  "^\\*.+Completions\\*$"
                  "^\\*Flycheck error messages\\*$"
                  "^\\*Help\\*$"
                  "^\\*Ibuffer\\*$"
                  "^\\*Messages\\*$"
                  "^\\*inferior-lisp\\*$"
                  "^\\*scratch\\*$"
                  "^\\*slime-compilation\\*$"
                  "^\\*slime-description\\*$"
                  "^\\*slime-events\\*$"))
  (add-to-list 'ido-ignore-buffers buffer))
```

Could you please add something like this to `ivy-switch-buffer`? I guess it's trivial to implement.

**Comment by abo-abo** [comment]
> I guess it's trivial to implement.

It's pretty easy, although merging a PR is easier still :)

By the way, I don't see you on the Emacs copyright assignment list. Do note that you'll need it if you ever plan to contribute to anything in GNU ELPA.

**Comment by mrkkrp** [comment]
Yes I know. After some thinking, I decided that is rather slowing down progress, because it's a bit harder to merge PR from arbitrary person after putting something on ELPA… From pragmatic point of view, it's not possible to use ELPA alone, so why bother… I've seen a good PR for Avy is haging because of this. This is the reason I haven't put my Vimish Fold and other packages on ELPA.

That is just my personal opinion at the moment. To contribute to cool packages like yours, maybe I will sign the papers, in principle I have nothing against it. Thanks for the quick response.

**Comment by abo-abo** [comment]
> From pragmatic point of view, it's not possible to use ELPA alone, so why bother

As I see it, there's only ELPA and MELPA. And if something happens to the latter (like to Marmalade), ELPA is all we've got.

Additionally, ELPA sort-of offers to co-maintain the packages posted there. So if I ever get tired of maintaining my stuff, at least it will be sort-of maintained at ELPA, which is a lot better than nothing.

So using ELPA (in addition to MELPA) is my pragmatic choice. And I think it's worth the trade-off of bothering the contributors to get an assignment (only once, though).

**Comment by mrkkrp** [comment]
I see, @abo-abo.
