### ISSUE TITLE
`counsel-find-file-ignore-regexp` does not seem to work

### ISSUE THREAD

**Issue by mrkkrp** [abo-abo/swiper#368]
I'm trying to remove `./` and `../` entries when I'm searching for file, because well, they are completely useless. It may be even better to remove them by default. I've found the `counsel-find-file-ignore-regexp` setting and it seems like it should do the trick, but it does not work (or I don't understand something).

What I've tried:

```emacs-lisp
(setq counsel-find-file-ignore-regexp (regexp-opt '("." "..")))
```

…and

```emacs-lisp
(setq counsel-find-file-ignore-regexp (regexp-opt '("./" "../")))
```

These do not work.

**Comment by abo-abo** [comment]
Works fine for me. Do note that this defcustom affects only `counsel-find-file` and not `find-file`.

**Comment by mrkkrp** [comment]
I used `find-file`. That's probably because all these completing things are patched the same way (probably advice of some sort), so it's hard to make this work only for `find-file` (although I haven't seen source yet). Closing.

**Comment by Ps-Pencil** [comment]
@mrkkrp This seems to be because counsel checks for `ivy-extra-directories` at the same time it checks for ignore-regexp. You could delete that variable content (if this is still relevant).
