### ISSUE TITLE
ivy-mode: How do I complete the selected directory candidate?

### ISSUE THREAD

**Issue by tsdh** [abo-abo/swiper#37]
I just tried out swiper (awesome!) and then also tried out `(ivy-mode 1)`.  For buffers, variables, and commands, it is nice.  But when finding a file using `C-x C-f`, how on earth do I complete a path component?

For example, I entered `~/.em` and it shows the completions `~/.emacs` and `~/.emacs.d/`.  I want to find `~/.emacs.d/elpa/swiper-VERSION/ivy.el`, so I do `C-n` so that `~/.emacs.d/` is highlighted, and then what?  `TAB` inserts just a tab, and `RET` finds the directory in dired.  But how do I complete the directory, and then the next, and so on?

**Comment by abo-abo** [comment]
You need <kbd>C-j</kbd>. It will select a directory without finishing the completion.

If you'd like to know more, just look at the source of ivy.el,
specifically at the `ivy-minibuffer-map` variable.  Here's how it
looks like currently:

```elisp
(defvar ivy-minibuffer-map
  (let ((map (make-sparse-keymap)))
    (define-key map (kbd "C-m") 'ivy-done)
    (define-key map (kbd "C-j") 'ivy-alt-done)
    (define-key map (kbd "C-n") 'ivy-next-line)
    (define-key map (kbd "C-p") 'ivy-previous-line)
    (define-key map (kbd "C-s") 'ivy-next-line-or-history)
    (define-key map (kbd "C-r") 'ivy-previous-line-or-history)
    (define-key map (kbd "SPC") 'self-insert-command)
    (define-key map (kbd "DEL") 'ivy-backward-delete-char)
    (define-key map (kbd "M-<") 'ivy-beginning-of-buffer)
    (define-key map (kbd "M->") 'ivy-end-of-buffer)
    (define-key map (kbd "M-n") 'ivy-next-history-element)
    (define-key map (kbd "M-p") 'ivy-previous-history-element)
    (define-key map (kbd "C-g") 'minibuffer-keyboard-quit)
    map)
  "Keymap used in the minibuffer.")
```

I'll add a keymap description to the output of <kbd>C-h m</kbd> as
well, I don't know if anyone uses that though.

**Comment by tsdh** [comment]
Yes, I've looked there and found no command that did that.  `ivy-alt-done` doesn't complete the currently selected directory here.  When I press it, `[Incomplete]` is shown shortly, and that's it.  That happens even when I type `.emacs.d` so that `.emacs.d/` is the only candidate left.

BTW: Behind the last candidate (no matter if file-completion or matches in swiper) the string `(no matches)` is printed as if that was part of the last candidate.  I guess that's not as intended.

**Comment by abo-abo** [comment]
> Yes, I've looked there and found no command that did that. ivy-alt-done doesn't complete the currently selected directory here. When I press it, [Incomplete] is shown shortly, and that's it. That happens even when I type .emacs.d so that .emacs.d/ is the only candidate left.
> 
> BTW: Behind the last candidate (no matter if file-completion or matches in swiper) the string (no matches) is printed as if that was part of the last candidate. I guess that's not as intended.

Both cases look like interference from another package, either `ido-mode` or `icomplete-mode`.
Do you have any of them enabled?

When there are no matches, swiper minibuffer should look like this:

> **0 pattern:** foobar

**Comment by tsdh** [comment]
@abo-abo Ah, you are correct.  Both the `C-j` doesn't work issue as well as the `[Incomplete]`/`(no matches)` issues are interferences with `icomplete-mode`.
