### ISSUE TITLE
ivy-inhibit-action for counsel-git-grep counsel-ag and swiper

### ISSUE THREAD

**Issue by drorbemet** [abo-abo/swiper#370]
Would ivy-inhibit-action be an improvement for one or all of these?
Having:
counsel-git-grep 
counsel-ag 
swiper
and similar?

Return: 
point AND (buffer OR full filepath)

As far as I understand ivy-inhibit-action would improve / generalize the interface for text search in a similar way it did  for file search.

**Comment by abo-abo** [comment]
All these functions do very non-very-destructive things like changing point and buffer. They can easily be wrapped:

```elisp
(setq x (save-excursion
          (swiper)))
```
