### ISSUE TITLE
prepending a custom list of paths to counsel-locate results list

### ISSUE THREAD

**Issue by drorbemet** [abo-abo/swiper#373]
I would like to prepend a list of special files to the results of counsel-locate each time just before it is called. So that they are up to date and included and filtered by the entered search pattern and appear at the top if they match.
How would a proper recipe for that look like?

I found something about virtual-buffers [here](https://github.com/abo-abo/swiper/issues/347) but I am still not sure how to go about this in general.

**Comment by abo-abo** [comment]
Thanks, have a look at commit msg for description of use.

**Comment by drorbemet** [comment]
Great, this is what I had in mind. Thanks.

**Comment by abo-abo** [comment]
Feel free to add a comment to the wiki if you have the time.
