### ISSUE TITLE
support git stash with a counsel-git-grep-stash

### ISSUE THREAD

**Issue by drorbemet** [abo-abo/swiper#374]
I didn't find support for git grep stash in magit.
At the moment I feel like that a **counsel-git-grep-stash** would help to quickly look up stashed notes and temp files. But I havn't decided about a sensible default action yet.
Maybe I should learn how to write a provider for ivy counsel myself. 
Does a general recipe for that exist already? What do I have to consider if I just copy and adapt counsel-git-grep for that?

```bash
#!/bin/bash
IFS=$'\n'
for i in `git stash list --format="%gd"`; do
    git stash show -p $i | grep -H --label="$i" "$1"
done
``

**Comment by abo-abo** [comment]
> Does a general recipe for that exist already? 

The recipe is to find a similar function and copy it.

> What do I have to consider if I just copy and adapt counsel-git-grep for that?

`counsel-git-grep` is a complex async command, I'd suggest looking at `counsel-locate` for a simple async command.  But in this case, a simple non-async command can suffice - just a combination of `ivy-read` and `shell-command-to-string`, see the commit.

> But I havn't decided about a sensible default action yet

I added an action that copies a command to apply a stash to the kill ring.

**Comment by basil-conto** [comment]
>     git stash show -p $i | grep -H --label="$i" "$1"

Note that `"$1"` is equivalent to `''` when used like this in `counsel-git-stash`, since the shell command is not called with any positional arguments.

The same thing can therefore be written as `git stash show -p --line-prefix="$i:" "$i"`.
I'm working on a patch that includes this clarification.
