### ISSUE TITLE
Can `counsel-M-x` keep region selected?

### ISSUE THREAD

**Issue by jonathanchu** [abo-abo/swiper#377]
Is it possible when invoking `counsel-M-x` to keep the region selected?  For example, I sometimes mark an active region of text and then would invoke `counsel-M-x` to run some other command, like [github-browse-file-blame](https://github.com/osener/github-browse-file), which takes input of the marked region as an argument.  I'm not sure if this is possible with counsel to keep the region selected when it opens the m-x prompt.

I recently switched over to `counsel-M-x` from `smex`, which does keep the marked region active.  I couldn't figure out how this was done though, so thought I'd ask if this was possible at all in counsel.

Thanks for your time and all your great work on swiper, counsel, and ivy! :smiley_cat:

**Comment by abo-abo** [comment]
Thanks, I forgot why I deactivated the region there.

**Comment by abo-abo** [comment]
Also the active region can be yanked into the ivy minibuffer with <kbd>M-n</kbd>, in case you didn't know yet.

**Comment by jonathanchu** [comment]
Oh awesome, I was looking in the wrong place :)  Thanks so much for the quick fix and great work on this!

And hat tip for letting me know that the active region can be yanked with M-n, very useful!
