### ISSUE TITLE
doc buffer is not downloaded when installing swiper from elpa

### ISSUE THREAD

**Issue by ardpp** [abo-abo/swiper#379]
In one of the recent issues `C-h m` was mentioned to call `ivy-help`. I have tried that and got the message that the file `/home/ardpp/.emacs.d/elpa/swiper-20160204.637/doc/ivy-help.org` is not found. Actually there is no `doc` directory in there at all. I install `swiper` frome elpa. Any idea what is going wrong?

**Comment by abo-abo** [comment]
https://github.com/milkypostman/melpa/pull/3559

**Comment by abo-abo** [comment]
Should work now, please check.

**Comment by drot** [comment]
Something strange going on, even though the MELPA recipe is updated.

```ivy-help: Opening input file: No such file or directory, /home/drot/.emacs.d/elpa/swiper-20160205.1224/doc/ivy-help.org```

**Comment by abo-abo** [comment]
Thanks, it should work now. MELPA puts it in `./ivy-help.org` instead of `./doc/ivy-help.org` as I thought before.

**Comment by ardpp** [comment]
It works, thank you!
