### ISSUE TITLE
when ivy is enabled, vc-ediff is unable to select default current source 

### ISSUE THREAD

**Issue by xwl** [abo-abo/swiper#383]
If i want to compare git version for current buffer between HEAD~ and current buffer. 

C-u M-x vc-ediff
HEAD~ C-j
C-j

Now when ivy is enabled, the last step will always select some version, instead of using current buffer directly:

<img width="335" alt="screen shot 2016-02-09 at 17 45 35" src="https://cloud.githubusercontent.com/assets/173505/12923231/36b59964-cf55-11e5-85c1-3d62b1b18fe7.png">

**Comment by abo-abo** [comment]
There's a bit of confusion from ediff's side: it put `nil` as the default and expects you to enter an empty input in order to get the default value on the second read.

Simply press <kbd>C-M-j</kbd> (`ivy-immediate-done`) - this function exits with the current input, instead of the current candidate. See http://oremacs.com/swiper/#minibuffer-key-bindings

**Comment by xwl** [comment]
It's a bit inconvenient that it doesn't work the same way as ido or plain completing-read.

Can we make it the same way?

- RET: alt-done
- C-j: ivy-immediate-done
- C-M-j: ivy-alt-done // doc says it's quite similar to alt-done, so maybe not that important than ivy-immediate-done?

**Comment by abo-abo** [comment]
Plain completing-read doesn't have a concept of a candidate - it only has input.

Putting `ivy-immediate-done` on <kbd>C-j</kbd> would be bad: it does the wrong thing in 95% cases. So it should be on a longer shortcut.

On the other hand, I like to have both <kbd>C-j</kbd> and <kbd>C-m</kbd> the way they are when completing file names, which I do a lot.

**Comment by xwl** [comment]
well, i may be too used to ido way. But these two keys usually have different bindings, e.g, in my org buffer with evil mode, by default i have:

- RET runs the command evil-ret
- C-j runs the command org-return-indent

**Comment by abo-abo** [comment]
Yes, but the key bindings in the minibuffer have their own map. 

Anyway, I'll close this one since the problem appears to be solved. Try to stick with the defaults for a while, if they don't make sense it's easy to rebind them in your config.
