### ISSUE TITLE
ignore contiguous spaces in ivy input?

### ISSUE THREAD

**Issue by xwl** [abo-abo/swiper#384]
Sometimes when separating substring in mini buffer, accidentally  i put more than one space there, then ivy usually finds nothing.  Can we treat multiple contiguous spaces as one space...

**Comment by abo-abo** [comment]
It's find the way it is: to get literal spaces input 1+ the amount of the literal spaces that you want to match.

Otherwise, there would be no way to match literal spaces.

**Comment by xwl** [comment]
use a quote for literal space? "\ "

**Comment by abo-abo** [comment]
Too cumbersome.
