### ISSUE TITLE
Patch: Modify counsel-imenu to use symbol at point for initial input

### ISSUE THREAD

**Issue by sKolar42** [abo-abo/swiper#388]
Helm does this, and I have found it to be helpful, so I thought someone else might.

[counsel.el.diff.txt](https://github.com/abo-abo/swiper/files/137975/counsel.el.diff.txt)

**Comment by abo-abo** [comment]
Thanks for the suggestion.

The use of `:initial-input` is discouraged in favor of `:preselect`.
