### ISSUE TITLE
Put all the faces in the ivy-faces group (and also faces)

### ISSUE THREAD

**Issue by hmelman** [abo-abo/swiper#389]
Because of the line
```elisp
    (setcdr (assoc load-file-name custom-current-group-alist) 'ivy)
```
four of the ivy faces are listed in the ivy custom group rather than the ivy-faces group.
This seems wrong to me, shouldn't all the faces be in ivy-faces?
Also, I think the ivy-faces group should also be in the faces group.

So I'd first do the defgroup for ivy, then list all non-face defcustoms
Then define as follows:

```elisp
	(defgroup ivy-faces nil
	  "Faces for `ivy."
	  :group ivy
	  :group 'faces)
```

and then list all the deffaces.

**Comment by abo-abo** [comment]
Thanks, it looks like I started doing it to get things more organized, but didn't finish.
