### ISSUE TITLE
Ivy insert insert completion with * in name

### ISSUE THREAD

**Issue by noaham** [abo-abo/swiper#391]
Hi. I'm not sure exactly how to solve this but I have the following issue. I edit latex documents with auctex a lot so this is where the example comes from. I call the function `LaTeX-environment` and ivy brings up a list of latex environments for me to insert into my document. Many latex environments come with "starred" versions. Eg there is an environment `equation` and `equation*`. However, when I try and type `equation*`, ivy will only match `equation` and insert this. Is there a way to override ivy and insert exactly what I have entered?

**Comment by noaham** [comment]
I have figured out the answer: `ivy-immediate-done` which is bound to `C-M-j` by default does exactly what I want. 

Sorry to open an issue only to close it immediately. I will leave the answer here incase anyone else finds it useful. Cheers, thanks for the fantastic package.

**Comment by abo-abo** [comment]
No problem:)

Here's a tip: since ivy's input is interpreted a regex, you can match all starred environments with the input `\*$`.  For me, the input `ta \*` matches `tabular*` and `table*`.  Accidentally, `ta *` also works, but keep in mind that it's best to quote when you want a literal star.

**Comment by noaham** [comment]
Cheers. Absolutely, you are right but there is still a problem when a particular completion isn't in the list of defaults already.

**Comment by abo-abo** [comment]
If it's not in defaults, just enter it full and press `C-m`. It should work.

**Comment by noaham** [comment]
Ah, even quicker than C-M-j. Thanks!
