### ISSUE TITLE
Is there a face like swiper-line-face for the minibuffer?

### ISSUE THREAD

**Issue by otijhuis** [abo-abo/swiper#392]
By default the currently selected match/line in the minibuffer only highlights a line up to the end of the text. This means the highlight constantly changes length when navigating through the results. 

Is it currently possible to do something like `swiper-line-face` but in the minibuffer? (or `helm-swoop`, which does the same thing)

**Comment by abo-abo** [comment]
The face is called `ivy-current`, but if you want to highlight until the end of the text you need:

    (setq ivy-format-function 'ivy-format-function-line)
    
See `ivy-format-function` for more info.

**Comment by otijhuis** [comment]
Thanks! I'll check it out right away.

**Comment by otijhuis** [comment]
Works perfectly.
