### ISSUE TITLE
counsel--async-sentinel misses errors

### ISSUE THREAD

**Issue by hmelman** [abo-abo/swiper#394]
I've been working on a `counsel-zgrep` that looks in the current directory since many things I have don't use git (e.g., the lisp directory of my emacs installation). I was getting very frustrated that some grep strings were working and some weren't, though I knew they matched some files, they just showed no results in ivy.. 

Following the example in the manual I was using `counsel--async-command` and I ultimately found the issue in `counsel--async-sentinel`. It misses any errors other than exit code 1 (and zgrep was exiting with 2).

I think `counsel--async-sentinel` should catch the other errors and include the exit code in the displayed error message or at least print it with `(message)` so I would have caught this much sooner.

It would also be nice if there was a way to specify a different sentinel for `counsel--async-command.`

**Comment by abo-abo** [comment]
Thanks, fixed. The API is updated a little as well.
