### ISSUE TITLE
Add command to use `find` like `counsel-locate`

### ISSUE THREAD

**Issue by stardiviner** [abo-abo/swiper#396]
I found counsel have command `counsel-locate` which use `locate`.
I'm find a way to use shell command `find` in Emacs to search only filename in a specific directory (so, not using `ag` or `grep`).
I hope counsel can add command for `find` just like `locate`.

**Comment by abo-abo** [comment]
There's already `counsel-git` and [find-file-in-project](https://github.com/technomancy/find-file-in-project).

**Comment by stardiviner** [comment]
This is great. Thanks for your tip.
