### ISSUE TITLE
`insert-default-directory` seems to be ignored when reading file names.

### ISSUE THREAD

**Issue by joostkremers** [abo-abo/swiper#397]
In stock Emacs, when I do:

    (let ((insert-default-directory nil))
      (read-file-name "File: "))

there is no initial input in the minibuffer, but I do get file name completion starting from the current buffer's `default-directory`. The return value is a relative file name. With `ivy`, however, the default directory *is* inserted into the minibuffer and after selecting a file, the file name is absolute.

It'd be nice if `ivy` would respect the value of `insert-default-directory`, since there are instances where setting it to `nil` is useful.

**Comment by abo-abo** [comment]
It looks to me that `insert-default-directory` is an artifact of `completing-read-default` and not really applicable to `ivy-read`.

> With ivy, however, the default directory is inserted into the minibuffer and after selecting a file, the file name is absolute.

It's not really inserted into the minibuffer, it's appended to the prompt. You can't touch or edit it.

> It'd be nice if ivy would respect the value of insert-default-directory, since there are instances where setting it to nil is useful.

I don't see value in not showing which directory you're in - that's always useful information. Unless you want to forbid switching directories, in which case you could use:

    (completing-read "File: " (directory-files default-directory))

> and after selecting a file, the file name is absolute.

`file-name-nondirectory` is idempotent, just apply it to the result of `completing-read` if you want a relative file name.

**Comment by joostkremers** [comment]
> I don't see value in not showing which directory you're in - that's always useful information. 

Yes, but there are times when you don't want that information to be part of the value returned by `read-file-name`.

My particular use case is a front-end for a document converter (`pandoc`, to be precise). The user can add paths to e.g., css files to the `pandoc` command, and these file paths will usually be relative paths.

> > and after selecting a file, the file name is absolute.
> file-name-nondirectory is idempotent, just apply it to the result of completing-read if you want a relative file name.

No, because setting `insert-default-directory` to `nil` allows you to still descend into a subdirectory and get that subdir as part of the return value. Using `file-name-nondirectory` only returns the file name.

I just found the function `file-relative-name`, which I can probably use for my purpose. Still, I would argue it's a bug when a snippet such as 

    (let ((insert-default-directory nil))
      (read-file-name "File: "))

returns different values depending on the completion mechanism the user happens to use.

**Comment by abo-abo** [comment]
Try this code:

```elisp
(let* ((directory-abbrev-alist
        (list (cons (expand-file-name default-directory) "./")
              (cons default-directory "./")))
       (file (read-file-name "File: ")))
  (abbreviate-file-name file))
```

> returns different values depending on the completion mechanism the user happens to use.

I agree that consistency is nice to have. On the other hand I don't see much value in trying to emulate every small thing of the default completion in `ivy`.

Here's how I see the completion interface: the input is a collection - a set of candidates, the output is a candidate - a member of this set.  By definition of a set, no two candidates are the same, each candidate is uniquely identifiable.

During file name completion, the completion interface has to operate on absolute file name, otherwise the collection is no longer a set. And it makes sense for the completion system not to transform the returned candidate. So `completing-read-default` not returning an absolute path is a mistake in my opinion.

**Comment by joostkremers** [comment]
> Try this code:

> ```emacs-lisp
> (let* ((directory-abbrev-alist
>         (list (cons (expand-file-name default-directory) "./")
>               (cons default-directory "./")))
>        (file (read-file-name "File: ")))
>   (abbreviate-file-name file))
> ```

> returns different values depending on the completion mechanism the user happens to use.

I'd have to use it without the initial `"./"` it produces, but that's doable. Still, for my purpose, `file-relative-name` seems to suffice.

> During file name completion, the completion interface has to operate on absolute file name, otherwise the collection is no longer a set. 

Relative file names are also unique when the directory from which they start out is known, which is the case during completion through the DIR argument of `read-file-name`. The return value doesn't contain this information, of course, but at that time, completion has ended.

> And it makes sense for the completion system not to transform the returned candidate. So completing-read-default not returning an absolute path is a mistake in my opinion.

I see your point, though I still tend to disagree. :-)

Thanks for the quick reply, though. Good to know about  `abbreviate-file-name` and `file-relative-name`, which are probably more robust anyway.

**Comment by joostkremers** [comment]
Just noticed that `insert-default-directory` isn't entirely ignored. If it's set to `nil`, the first candidate, which IIUC normally reflects the `DIR` argument, is not there.
