### ISSUE TITLE
Patch: Fix for counsel-list-processes-action-switch

### ISSUE THREAD

**Issue by sKolar42** [abo-abo/swiper#398]
I noticed that counsel-list-processes-action-switch doesn't work, as it's attempting to use the process name as a buffer.  Example: A shell process will have a buffer titled *shell* (or *shell*<2>, etc.), but the process name is "shell".  The included patch fixes this.
[counsel.el.diff.txt](https://github.com/abo-abo/swiper/files/143319/counsel.el.diff.txt)

**Comment by abo-abo** [comment]
Thanks. If you prefer attaching diffs rather than opening a PR, please use `git format-patch`.
