### ISSUE TITLE
Navigating/selecting candidates

### ISSUE THREAD

**Issue by jdahm** [abo-abo/swiper#40]
A few observations about my experience with swiper so far:

1) Sometimes I still hit `<up>` and `<down>` out of habit and that seems to confuse ivy-read. Would be nice to define actions for these as well.
2) I also find myself hitting `<TAB>` occasionally, and this seems to insert spaces instead of doing something more sane, like some sort of completion or `C-j`-like action.

**Comment by abo-abo** [comment]
You seem to have missed to specify the keys that you're hitting. Can you clarify?

**Comment by jdahm** [comment]
Github's markdown-syntax got rid of text inside `< >`s. Updated!

**Comment by tsdh** [comment]
:+1: 

I'd also agree with @jdahm that `<tab>` should be bound to `ivy-alt-done` or something similar.  (I've bound it to `jvy-alt-done` locally, and while I like that for reading file names, I'd prefer something that requires one more confirmation for e.g. `M-x` completion...)

**Comment by abo-abo** [comment]
@tsdh, I was thinking of <kbd>TAB</kbd> doing partial completion (if the input is simple) followed by `ivy-alt-done` on the second <kbd>TAB</kbd> while the input hasn't changed.
But partial completion with a potential regex is tricky, so I've been putting off this feature so far.

**Comment by tsdh** [comment]
@abo-abo Sounds very good to me.
