### ISSUE TITLE
swiper fails if font-lock mode is disabled

### ISSUE THREAD

**Issue by thisch** [abo-abo/swiper#400]
For large buffers sometimes it makes sense to disable ``font-lock-mode``. Searching in such buffers with does not work with swiper (``wrong type of argument: number-or-marker-p: nil``)

**Comment by abo-abo** [comment]
Thanks. Check out `counsel-grep`: it's a `swiper` variant designed for huge buffers.

**Comment by thisch** [comment]
thx for the info
