### ISSUE TITLE
ivy-read-action with small minibuffer visually truncates action choice list

### ISSUE THREAD

**Issue by DWgit** [abo-abo/swiper#402]
Scenario:

1. User does an ivy search (e.g., ivy-locate) that returns a small number of candidates, so the minibuffer doesn't grow
1. User calls ivy-read-action, which wants to display more actions than the minibuffer size
1. Small minibuffer visually truncates the action list, and user doesn't see all the choices.

**Comment by abo-abo** [comment]
Thanks.

**Comment by DWgit** [comment]
Thanks for the super-fast turnaround and for ivy!

David
