### ISSUE TITLE
counsel-recoll can overwrite current-buffer

### ISSUE THREAD

**Issue by DWgit** [abo-abo/swiper#403]
Under nondeterministic conditions, counsel-recoll can overwrite the current buffer. It's easy to recreate and easy to fix.

1. Create a junk buffer and make it current
1. Launch counsel-recoll with a long-running query that returns lots of candidates
1. While counsel-recoll is running, hit C-g

The junk buffer should contain some raw recoll output.

To fix: In counsel-recoll, add an :unwind clause:
           :unwind #'counsel-delete-process

**Comment by abo-abo** [comment]
Thanks.
