### ISSUE TITLE
(void-function ivy-set-display-transformer)

### ISSUE THREAD

**Issue by manuel-uberti** [abo-abo/swiper#404]
Hi,

I've just upgraded `counsel` from MELPA. When using `counsel-M-x` this is what I get:
```
Debugger entered--Lisp error: (void-function ivy-set-display-transformer)
  ivy-set-display-transformer(counsel-M-x counsel-M-x-transformer)
  byte-code("\300\301\302\"\210\303\301\304\"\207" [ivy-set-actions counsel-M-x (("d" counsel--find-symbol "definition")) ivy-set-display-transformer counsel-M-x-transformer] 3)
  autoload-do-load((autoload "counsel" "Ivy version of `execute-extended-command'.\nOptional INITIAL-INPUT is the initial input in the minibuffer.\n\n(fn &optional INITIAL-INPUT)" t nil) counsel-M-x)
  command-execute(counsel-M-x)
```
If you need me to help with more informations to debug the problem, please feel free to ask.
Could it be related to this piece of code in `counsel.el`?
```
;;** `counsel-M-x'
(ivy-set-actions
 'counsel-M-x
 '(("d" counsel--find-symbol "definition")))

(ivy-set-display-transformer
 'counsel-M-x
 'counsel-M-x-transformer)
```

**Comment by abo-abo** [comment]
I'm starting to think it's an issue with `package.el`. Since `counsel.el` clearly depends on `ivy.el`, which was also updated. However, for some reason while `counsel.el` was reloaded, `ivy.el` wasn't reloaded previously.

An Emacs restart always fixes this issue though.

**Comment by abo-abo** [comment]
Or if you don't want to restart, locate the package and reload the new `ivy.el`, then the new `counsel.el`.

But really, this should be the package manager's job.

**Comment by manuel-uberti** [comment]
I restarted Emacs, but I still got the error.

**Comment by thwg** [comment]
Just ran into this as well when updating.

I think MELPA built and is serving the latest counsel (dated today) but not the latest swiper package (dated yesterday).  It looks like it is still building, so it may resolve itself within a couple hours.

**Comment by abo-abo** [comment]
I see. I pushed the updates to both ivy.el and counsel.el at once. Then it's MELPA's fault for serving update in the dependent package without first checking if any dependencies need to be updated.  Anyway the problem will be solved when the build is finished, so it's not a big deal.

**Comment by manuel-uberti** [comment]
I can confirm everything works now that `swiper` is up to date on MELPA.
