### ISSUE TITLE
Using ivy-mode overrides M-x

### ISSUE THREAD

**Issue by jojojames** [abo-abo/swiper#407]
Using either
`(require 'swiper)
(ivy-mode 1)`

or
`(use-package swiper
  :ensure counsel
  :config
  (ivy-mode 1)
  (define-key ivy-mode-map [escape] 'minibuffer-keyboard-quit)
  (setq ivy-use-virtual-buffers t)
  (setq ivy-height 10))`

overrides M-x as well as C-x C-b.

The config at https://github.com/abo-abo/swiper makes it seem like the bind is optional.

If I disable Ivy-Mode and just map ivy binds separately, ivy-mode-map is not defined, so binding [escape] the normal way doesn't work.

`(define-key ivy-mode-map [escape] 'minibuffer-keyboard-quit)`

**Comment by abo-abo** [comment]
> overrides M-x as well as C-x C-b.

<kbd>M-x</kbd> is not overridden - you probably still have it bound to `execute-extended-command`. I recommend to bind <kbd>M-x</kbd> to `counsel-M-x` instead.

<kbd>C-x C-b</kbd> is overridden, since it a straightforward upgrade over `switch-to-buffer`.

> (define-key ivy-mode-map [escape] 'minibuffer-keyboard-quit)

Seems this is what you want:

    (global-set-key [escape] 'minibuffer-keyboard-quit)
    
since Ivy doesn't touch <kbd>[escape]</kbd>.

**Comment by jojojames** [comment]
It's bounded to execute-extended-command, but the ivy mode M-x shows up instead of the regular M-x if ivy-mode is enabled. 

The specific package is swiper-20160228.822 from melpa/marmalade if this is unexpected behavior.

For the second use case, ivy mode is disabled.

For example,

M-x (regular M-x) counsel-M-x

Pressing [escape] won't leave counsel-M-x.

Here is my config for [escape].
`(global-set-key [escape] 'minibuffer-keyboard-quit)
(use-package swiper
  :ensure counsel
  :config
  ;(ivy-mode 1)
  (setq ivy-use-virtual-buffers t)
  (setq ivy-height 10))
(defun minibuffer-keyboard-quit ()
  "Abort recursive edit.
In Delete Selection mode, if the mark is active, just deactivate it;
then it takes a second \\[keyboard-quit] to abort the minibuffer."
  (interactive)
  (if (and delete-selection-mode transient-mark-mode mark-active)
      (setq deactivate-mark  t)
    (when (get-buffer "*Completions*") (delete-windows-on "*Completions*"))
    (abort-recursive-edit)))

(define-key evil-normal-state-map [escape] 'keyboard-quit)
(define-key evil-visual-state-map [escape] 'keyboard-quit)
(define-key minibuffer-local-map [escape] 'minibuffer-keyboard-quit)
(define-key minibuffer-local-ns-map [escape] 'minibuffer-keyboard-quit)
(define-key minibuffer-local-completion-map [escape] 'minibuffer-keyboard-quit)
(define-key minibuffer-local-must-match-map [escape] 'minibuffer-keyboard-quit)
(define-key minibuffer-local-isearch-map [escape] 'minibuffer-keyboard-quit)
(global-set-key [escape] 'evil-exit-emacs-state)`

**Comment by abo-abo** [comment]
> It's bounded to execute-extended-command, but the ivy mode M-x shows up instead of the regular M-x if ivy-mode is enabled.

This is supposed to happen, that's the very definition of `ivy-mode`: to offer completion when it's requested.

> (defun minibuffer-keyboard-quit ()

You probably should not redefine a built-in function.

> Pressing [escape] won't leave counsel-M-x.

It leaves it for me. Check your config for bugs.
