### ISSUE TITLE
Ignore directories from completion using ivy

### ISSUE THREAD

**Issue by swarnendubiswas** [abo-abo/swiper#408]
I want to ignore directories like ".dropbox*" under my home directory while completing with ivy. When I type d (small case, easier to type) with `counsel-find-file`, the completion list lists installation directories like ".dropbox*" before "Dropbox", which is not what I want. Note that I have the following: `(setq case-fold-search t ivy-case-fold-search t)`.

I get the desired behavior (list Dropbox first) with ido by using `ido-ignore-directories`. Is there an equivalent in ivy? Otherwise, it might be an useful addition.

**Comment by abo-abo** [comment]
Use:

    (setq counsel-find-file-ignore-regexp "\\`\\.dropbox")

and `counsel-find-file`, instead of regular `find-file`.

**Comment by swarnendubiswas** [comment]
That works, thanks.
