### ISSUE TITLE
ivy-mode doesn't work with Emacs-25 (Compile from source)

### ISSUE THREAD

**Issue by enzochiau** [abo-abo/swiper#41]
After I enabled `ivy-mode`, I got error when I try `M-x`:

    Debugger entered--Lisp error: (error "Function as a collection unsupported")
      signal(error ("Function as a collection unsupported"))
      error("Function as a collection unsupported")
      ivy-completing-read("M-x " #[771 "\211\301>\203\302\303\304\305\306\"\307\"\310\311%\202\312$\207" [obarray (nil t) make-byte-code 257 "\301!\205\300\302!\232\206\211\303N?\207" vconcat vector [symbol-name byte-obsolete-info] 4 "\n\n(fn SYM)" complete-with-action] 10 "\n\n(fn STRING PRED ACTION)"] commandp t nil extended-command-history nil nil)
      completing-read("M-x " #[771 "\211\301>\203\302\303\304\305\306\"\307\"\310\311%\202\312$\207" [obarray (nil t) make-byte-code 257 "\301!\205\300\302!\232\206\211\303N?\207" vconcat vector [symbol-name byte-obsolete-info] 4 "\n\n(fn SYM)" complete-with-action] 10 "\n\n(fn STRING PRED ACTION)"] commandp t nil extended-command-history)
      read-extended-command()
      byte-code("\302	\303 E)\207" [execute-extended-command--last-typed current-prefix-arg nil read-extended-command] 3)
      call-interactively(execute-extended-command nil nil)
      command-execute(execute-extended-command)

**Comment by enzochiau** [comment]
Sorry, just update to the latest version. it works fine now.

**Comment by abo-abo** [comment]
It's kind of my fault. Recently, I've merged ivy.el into the swiper package, so all people that were
using ivy before need to delete their ivy package, and keep only swiper.
