### ISSUE TITLE
Use ivy-switch-buffer without ivy mode enabled.

### ISSUE THREAD

**Issue by jojojames** [abo-abo/swiper#410]
I'd like to use ivy-switch-buffer without ivy mode enabled. It seems like when ivy mode is disabled, ivy-switch-buffer uses the regular readline buffer. 

My use case would be to use ivy mode specifically as the completion backend for other packages (magit, projectile, etc) without explictly enabling it.

The other commands like swiper, counsel-find-file, etc seem to open up the ivy-like prompt even without ivy mode enabled.

**Comment by abo-abo** [comment]
Thanks.
