### ISSUE TITLE
counsel-describe-function does not default to symbol at point

### ISSUE THREAD

**Issue by wbolster** [abo-abo/swiper#411]
...unlike the built-in describe-function. this makes it harder to use counsel-describe-function as a complete substitute for `C-h f`.

**Comment by abo-abo** [comment]
Please try to reproduce with `emacs -Q`, since using symbol-at-point is the intended behavior. It works right now for me.

**Comment by manuel-uberti** [comment]
I can confirm it is working fine for me too.

**Comment by wbolster** [comment]
my config was probably not correct at the time; it works now. sorry for the noise.
