### ISSUE TITLE
`ivy-reverse-i-search' inside swiper

### ISSUE THREAD

**Issue by jdahm** [abo-abo/swiper#412]
You suggest binding `C-s' to `swiper', but from muscle memory leftover from using plain isearch I occasionally hit `C-r' while in swiper expecting something like the `C-p' behavior `ivy-previous-line'.

I understand the idea behind this: selecting matches should follow the `previous-line' and `next-line' keymap, and that in the bash shell C-r gives a list of the past commands. However, I do keep hitting this, and since you suggest binding swiper to `C-s' I wonder if there is a more fitting binding for `ivy-reverse-i-search' to make swiper easier for others to adopt.

Just a suggestion, so feel free to completely disregard it. I should probably just get over it and learn to `C-p'.

**Comment by abo-abo** [comment]
<kbd>C-r</kbd> is a consistent and useful binding across all completion.  I could also remove <kbd>C-s</kbd> from `swiper`, but it's not really used anywhere else, so it stays.

But you can always customize `ivy-minibuffer-map` to your liking.

**Comment by ThibautVerron** [comment]
... or rather `swiper-map`.

With the same usecase in mind, I wonder how hard it would be to define a `swiper-backward` function?It would behave just like `swiper`, except that the first candidate would be the last one before point, instead of the first one after point. 

From what I can see in `swiper--ivy`, it is about changing the `preselect` parameter in the call to `ivy-read`, but this doesn't seem easy...

**Comment by abo-abo** [comment]
@ThibautVerron It's not about `preselect`, that thing is only responsible for the initial selection when there is no input.

If you want to emulate `isearch-backward` you need to redefine the entry in `ivy-index-functions-alist`.

**Comment by ThibautVerron** [comment]
Oh thanks for the pointer.

The following seems to be working (in a user config), but there's a lot of duplicate code of course (I could probably do with less but at least here I trust that it won't break with a subsequent update... at least as long as the syntax for calls to `ivy-read` doesn't change).

```
(defun tv/ivy-recompute-index-swiper-backward (_re-str cands)
  (- (ivy-recompute-index-swiper _re-str cands) 1))

(push (cons 'tv/swiper-backward 'tv/ivy-recompute-index-swiper-backward)
      ivy-index-functions-alist)

(defun tv/swiper-backward--ivy (candidates &optional initial-input)
  (interactive)
  (swiper--init)
  (setq swiper-invocation-face
        (plist-get (text-properties-at (point)) 'face))
  (let ((preselect
         (if swiper-use-visual-line
             (count-screen-lines
              (point-min)
              (save-excursion (beginning-of-visual-line) (point)))
           (1- (line-number-at-pos))))
        (minibuffer-allow-text-properties t)
        res)
    (unwind-protect
        (and
         (setq res
               (ivy-read
                "Swiper: "
                candidates
                :initial-input initial-input
                :keymap swiper-map
                :preselect preselect
                :require-match t
                :update-fn #'swiper--update-input-ivy
                :unwind #'swiper--cleanup
                :action #'swiper--action
                :re-builder #'swiper--re-builder
                :history 'swiper-history
                :caller 'tv/swiper-backward))
         (point))
      (unless res
        (goto-char swiper--opoint)))))

(defun tv/swiper-backward (&optional initial-input)
  (interactive)
  (tv/swiper-backward--ivy (swiper--candidates) initial-input)
  )

```

If integrating this feature in the package is acceptable, I'd suggest adding an optional flag to `swiper--ivy` in case we want to start searching backwards, and changing the caller name based on that flag and I can create a pull request.

I don't think that it interferes with any current workflows, but on the other hand I'm not sure that it would be a valuable addition for users users `C-r` for history searching in swiper, so maybe it should really stay in user configs.

**Comment by abo-abo** [comment]
Why not simply let-bind `ivy-index-functions-alist` and call `swiper` inside `tv/swiper-backward--ivy`. Doable in 5 lines.

**Comment by ThibautVerron** [comment]
Something like that?

```
(defun tv/swiper-backward (&optional initial-input)
  (interactive)
  (let ((ivy-index-functions-alist
         (cons (cons 'swiper 'tv/ivy-recompute-index-swiper-backward)
               (cdr ivy-index-functions-alist))))
    (swiper--ivy (swiper--candidates) initial-input)))

```

That appears to work too, but that doesn't look very robust, in particular it relies on `swiper` being the first element in `ivy-index-functions-alist`.  I guess it's possible to do cleaner using properties of association lists...

Or I could just flet `ivy-recompute-index-swiper`, I guess that would work as well. 

Thanks again for the help, how to go from 0 working solutions to at least 2 in 1h.

**Comment by abo-abo** [comment]
Simpler:

```elisp
(defun tv/swiper-backward (&optional initial-input)
  (interactive)
  (let ((ivy-index-functions-alist
         '((swiper . tv/ivy-recompute-index-swiper-backward))))
    (swiper initial-input)))
```

`swiper` is the only key in `ivy-index-functions-alist` that matters for the purposes of `swiper`.

**Comment by ThibautVerron** [comment]
Oh yes indeed, thanks!

**Comment by braham-snyder** [comment]
thanks @abo-abo and @ThibautVerron for `swiper-backward` -- for posterity: one additionally needs to add `tv/ivy-recompute-index-swiper-backward` in `ivy--filter`'s definition alongside where `ivy-recompute-index-swiper` appears

also for posterity: just some search-engine keywords (granted, IIUC, hyphens are poorly-handled by many search engines, but hopefully this will still show up a bit more readily on google and/or github's search?): swiper-reverse swiper-backwards swiper-up swiper-upwards

**Comment by abo-abo** [comment]
@braham-snyder Thanks.

**Comment by vspinu** [comment]
Shouldn't `swiper-backward` really be part of swiper proper? Leaving `C-r` with plain isearch is a half-job done.

**Comment by abo-abo** [comment]
@vspinu `swiper` does not assume that it will get bound to <kbd>C-s</kbd>. And like I said above, <kbd>C-r</kbd> for `ivy-reverse-i-search` is used consistently for all completion.

As an example, in my config:

- <kbd>C-s</kbd> is `counsel-grep-or-swiper`, which actually uses `ripgrep`.
- <kbd>C-r</kbd> is `swiper`.
- <kbd>C-c s</kbd> is `isearch-forward-regexp`.

**Comment by vspinu** [comment]
> does not assume that it will get bound to C-s. 

Sure, but I didn't propose to bind it to C-r, just to have it part of swiper proper. Using C-s and C-r as with default isearch is a common use pattern and I would definitely like to have that. 

> And like I said above, C-r for ivy-reverse-i-search is used consistently for all completion.

I am using `M-r` for that purpose including readline. Don't really remember how I ended up with that but well, now C-r is free for me.

Could someone pls post a fully working sample of this? The above definitions start from the last match in the buffer, not from the current position.

**Comment by braham-snyder** [comment]
@vspinu 

```
;;; source:
;;; https://github.com/abo-abo/swiper/issues/412

(defun brds/ivy-recompute-index-swiper-backward (_re-str cands)
  ;; still unsure how I feel about the oddness of `1-'
  (1- (ivy-recompute-index-swiper _re-str cands)))

(defun brds/swiper-backward (&optional initial-input)
  (interactive)
  (let ((ivy-index-functions-alist
         '((swiper . brds/ivy-recompute-index-swiper-backward))))
    (swiper initial-input))
  (when (and (bound-and-true-p evil-mode)
             (eq evil-search-module 'evil-search))
    (setq evil-ex-search-direction 'backward)))

;; also requires the additon of `brds/ivy-recompute-index-swiper-backward'
;; to this function alongside `ivy-recompute-index-swiper' and -asnyc
(defun ivy--filter (name candidates)
  "Return all items that match NAME in CANDIDATES.
CANDIDATES are assumed to be static."
  (let ((re (funcall ivy--regex-function name)))
    (if (and (equal re ivy--old-re)
             ivy--old-cands)
        ;; quick caching for "C-n", "C-p" etc.
        ivy--old-cands
      (let* ((re-str (if (listp re) (caar re) re))
             (matcher (ivy-state-matcher ivy-last))
             (case-fold-search
              (and ivy-case-fold-search
                   (or (eq ivy-case-fold-search 'always)
                       (string= name (downcase name)))))
             (cands (cond
                     (matcher
                      (funcall matcher re candidates))
                     ((and ivy--old-re
                           (stringp re)
                           (stringp ivy--old-re)
                           (not (string-match "\\\\" ivy--old-re))
                           (not (equal ivy--old-re ""))
                           (memq (cl-search
                                  (if (string-match "\\\\)\\'" ivy--old-re)
                                      (substring ivy--old-re 0 -2)
                                    ivy--old-re)
                                  re)
                                 '(0 2)))
                      (ignore-errors
                        (cl-remove-if-not
                         (lambda (x) (string-match re x))
                         ivy--old-cands)))
                     (t
                      (ivy--re-filter re candidates)))))
        (if (memq (cdr (assoc (ivy-state-caller ivy-last)
                              ivy-index-functions-alist))
                  '(brds/ivy-recompute-index-swiper-backward
                    ivy-recompute-index-swiper
                    ivy-recompute-index-swiper-async))
            (progn
              (ivy--recompute-index name re-str cands)
              (setq ivy--old-cands (ivy--sort name cands)))
          (setq ivy--old-cands (ivy--sort name cands))
          (ivy--recompute-index name re-str ivy--old-cands))
        (setq ivy--old-re
              (if (eq ivy--highlight-function 'ivy--highlight-ignore-order)
                  re
                (if ivy--old-cands
                    re-str
                  "")))
        ivy--old-cands))))
```

**Comment by vspinu** [comment]
@braham-snyder, thanks! This works.

**Comment by vspinu** [comment]
> This works.

Well, with one caveat. It doesn't pick the previous search. With isearch and swiper you can do a search, select, then on next invocation it will continue with the same input.

**Comment by braham-snyder** [comment]
I'm not quite sure I follow -- that said, I use the `evil-search` `evil-search-module` (which, rather confusingly, defaults to `isearch`), so there's a good chance I won't be able to help you much there

**Comment by vspinu** [comment]
Say you call `swiper` with input "foo" and select a candidate. Next time you call `swiper` (C-s) and immediately invoke `ivy-next-line-or-history` (C-s) it should pick up previous input automatically, so that you can continue with your isearch forward. This is how default isearch works. 

If I bind C-r to `swiper-backward` then C-r to `ivy-previous-line-or-history` it doesn't work as expected (doesn't pick the previous search). This might be `ivy` issue though.

**Comment by vspinu** [comment]
The discussion of `swiper-backward` is somewhat orthogonal to the original issue, so I am opening a new issue (#1172) for this.
