### ISSUE TITLE
counsel-ag always throws error 1

### ISSUE THREAD

**Issue by jojojames** [abo-abo/swiper#413]
Sequence of actions:
M-x counsel-ag
ag: popup that shows a string '3 chars more'
After typing 3 characters, it shows error code 1

I have ag and projectile packaged installed and projectile-ag works as expected.

My next step will be trying to run swiper/counsel standalone to see if my config is the issue. (Not sure why projectile-ag would work then and not counsel-ag)

**Comment by manuel-uberti** [comment]
It's working for me here. Could you try with `emacs -Q` and see if you have the same issue?

**Comment by jojojames** [comment]
I went ahead and removed my .emacs.d folder into another location so I can get a fresh emacs.

Upon launching emacs, I did package-install swiper.

Then M-x ivy-mode

After that, M-x counsel-ag, same issue, except the error message is only 'Error' this time.

ag --version returns 0.21.0 on OSX

**Comment by justbur** [comment]
Looks like your version of ag is too old. counsel-ag uses the --vimgrep option which I think came after 0.21.0

You can either upgrade ag or change the options used through counsel-ag-base-command

**Comment by jojojames** [comment]
Thanks, that was it.
