### ISSUE TITLE
Add an option to toggle recenter selected line on swiper quit?

### ISSUE THREAD

**Issue by qizhihere** [abo-abo/swiper#419]
Currently swiper just exits with cursor at the selected line and doesn't recenter the line, so i have to do it manually(i use evil, so have to press C-l). How about add an option to toggle automatically recenter line after swiper finish?

Screencast here: http://7sbq2s.com1.z0.glb.clouddn.com/img_links/github/swiper-issue-1.gif

For example:
```emacs-lisp
(when (bound-and-true-p swiper-recenter-line)
  (recenter))
(point)
```
https://github.com/abo-abo/swiper/blob/master/swiper.el#L436

**Comment by abo-abo** [comment]
Try this:

    (advice-add 'swiper--action :after 'recenter)

**Comment by qizhihere** [comment]
Eh...it doesn't work as expected after i add an advice to `swiper--action`. It seems to be because `swiper-action` passes an argument to `recenter`.
If i use this it will works well:
```emacs-lisp
(defun my:swiper-recenter(&rest args)
  (recenter))
(advice-add 'swiper--action :after 'my:swiper-recenter)
```

**Comment by abo-abo** [comment]
Problem solved then.
