### ISSUE TITLE
Wrong number of arguments

### ISSUE THREAD

**Issue by darrylhebbes** [abo-abo/swiper#42]
Hi,
I get this error on the latest version of swiper.

```
swiper--ivy: Wrong number of arguments: (2 . 6), 7
```

This is my setup, using "use-package":

```
(use-package swiper
  :ensure t
  :bind ("C-s" . swiper)
  :config (progn
    (setq recenter-positions '(top middle bottom))))

```

**Comment by darrylhebbes** [comment]
Version swiper-20150419.1428

**Comment by abo-abo** [comment]
You need to remove both `ivy` and `swiper` packages from your system.
Then install `swiper`. The `ivy` package is part of `swiper`, so it's no longer available for install.

**Comment by darrylhebbes** [comment]
ok thanks. yes the ivy package I had installed separately at some point.
