### ISSUE TITLE
Recent escaping change in counsel-ag break searching "abc def"

### ISSUE THREAD

**Issue by kaushalmodi** [abo-abo/swiper#427]
Earlier searching for "abc def" in counsel-ag searched for "abc.*def".

That is not working any more after this commit: https://github.com/abo-abo/swiper/commit/79f9cdab81526246018642421b3b0f144991b1d6

**Comment by kaushalmodi** [comment]
Searching for "abc.*def" also does not work:

Here is how the regex variable looks inside `counsel-ag-function` without shell quoting (working case) and with shell quoting (not working) as I type <kbd>a</kbd>, <kbd>b</kbd>, <kbd>c</kbd>, <kbd>SPC</kbd>, <kbd>d</kbd>, <kbd>e</kbd>, <kbd>f</kbd>. And it is obvious why shell-quoting is messing up the regex.

```
regex: abc           regex-with-shell-quoting: abc [2 times]
regex: (abc).*?(d)   regex-with-shell-quoting: \(abc\).\*\?\(d\)
regex: (abc).*?(de)  regex-with-shell-quoting: \(abc\).\*\?\(de\)
regex: (abc).*?(def) regex-with-shell-quoting: \(abc\).\*\?\(def\)
```


And here is how the same looks as I type <kbd>a</kbd>, <kbd>b</kbd>, <kbd>c</kbd>, <kbd>.</kbd>, <kbd>*</kbd>, <kbd>d</kbd>, <kbd>e</kbd>, <kbd>f</kbd>. And it is obvious again why shell-quoting is messing up the regex.

```
regex: abc           regex-with-shell-quoting: abc 
regex: abc.          regex-with-shell-quoting: abc.
regex: abc.*         regex-with-shell-quoting: abc.\*
regex: abc.*d        regex-with-shell-quoting: abc.\*d
regex: abc.*de       regex-with-shell-quoting: abc.\*de
regex: abc.*def      regex-with-shell-quoting: abc.\*def
```

**Comment by justbur** [comment]
I get a different result. The command I get is
`ag --vimgrep "(abc).*?(def)"`

which works fine

**Comment by justbur** [comment]
@kaushalmodi you're not customizing `counsel-ag-base-command` are you?

**Comment by kaushalmodi** [comment]
Of course! I had `"%S"` instead of `"%s"` in my custom `counsel-ag-base-command`. 

Sorry for the noise.
