### ISSUE TITLE
counsel-find-file does not treat input / as smart to root directory.

### ISSUE THREAD

**Issue by stardiviner** [abo-abo/swiper#428]
I bind `[C-x C-f]` like this:
```elisp
(global-set-key [remap find-file] 'counsel-find-file)
```
But when in press `[C-x C-f]`, then input `/`, it does not smart treat it as root directory juts like `~` home directory.

**Comment by abo-abo** [comment]
This is the intended behavior:

- root dir is on `//`.
- ssh from current dir is on `/ssh:` <kbd>RET</kbd>.
- sudo from current dir is on `/sudo::` <kbd>RET</kbd>.

**Comment by stardiviner** [comment]
Thanks.
