### ISSUE TITLE
counsel-ag: change directory

### ISSUE THREAD

**Issue by manuel-uberti** [abo-abo/swiper#429]
Question: is it possible, maybe via `C-u` like `ag.el` used to do, to make `counsel-ag` use a different directory?

**Comment by abo-abo** [comment]
Answer: it's possible now:)

**Comment by manuel-uberti** [comment]
:-D oh man, you're really too fast! Thank you very much.

**Comment by manuel-uberti** [comment]
Just upgraded: works fine! Thanks again.

**Comment by abo-abo** [comment]
You're welcome. Feel free to suggest PRs for things like this, provided you have the will and the Emacs Copyright Assignment :).

**Comment by manuel-uberti** [comment]
No problem about the CA, just have to fill it out.
