### ISSUE TITLE
[ivy-mode issue] C-j in find-file says symbols function definition is void: plusp

### ISSUE THREAD

**Issue by hariharanr5** [abo-abo/swiper#43]
I've installed swiper and enabled ivy-mode.
After that i've invoked find-file (C-x C-f).
when i type .emacs.d, the only possible completion it shows is .emacs.d directory which is correct.
To complete that if i press C-j, it throws "symbols function definition is void: plusp"

**Comment by abo-abo** [comment]
Please try again, see if this fixes it. Also, what's your Emacs version?

**Comment by hariharanr5** [comment]
Thanks for the quick fix. I'm using Emacs 24.4. Also it would be nice if pressing `TAB` could do the same as C-j. But pressing TAB inserts TAB in the minibuffer.

**Comment by hariharanr5** [comment]
Works now. Thanks. The mini buffer size is still large when there is only one file that matches the given file name, you can add auto resize mode like helm does.

**Comment by abo-abo** [comment]
> Also it would be nice if pressing TAB could do the same as C-j

You can customize this for yourself with:

```elisp
(define-key ivy-minibuffer-map (kbd "TAB") 'ivy-alt-done)
```

I plan to assign partial completion to <kbd>TAB</kbd> in the future, but it's not trivial.

> you can add auto resize mode like helm does

This you actually be quite annoying, in my opinion. If you find that the window is too large, set the `ivy-height` to a smaller value (10 is the default one).
I can add this a bit later, I'm working on something else right now.

**Comment by hariharanr5** [comment]
Thanks for the suggestions. Nice package.
