### ISSUE TITLE
When ivy-count-format is empty string ivy--prompt-extra is not appended to prompt

### ISSUE THREAD

**Issue by otijhuis** [abo-abo/swiper#431]
I've created a function which uses `ivy-read` with `require-match` set to `t`.
`ivy-count-format` is set to an empty string.

I call my function and enter some text which doesn't match. Then I try to complete the selection.
It should append `(match required)` to the prompt but it doesn't.

When I reset `ivy-count-format` to `"(%d/%d) "` the above works and `(match required)` is added to the prompt like expected.

Looks like `ivy--prompt-extra` is not appended to the prompt when `ivy-count-format` is empty.

**Comment by abo-abo** [comment]
Thanks.
