### ISSUE TITLE
Bad interaction between swiper and ess packages

### ISSUE THREAD

**Issue by stevenbagley** [abo-abo/swiper#433]
ess is a package for using R, the statistics programming language. When the bug is activated, the symptom is that the swiper candidates always come from the M-x execute-extended-command list, not the correct list of candidates. 

Minimal example:
```
(require 'package)
(require 'locate)
(setq locate-command "mdfind")          ;for OSX
(add-to-list 'load-path "/Users/sbagley/.emacs.d/elpa/swiper-20160307.1239/")
(add-to-list 'load-path "/Users/sbagley/.emacs.d/elpa/ess-20160305.530/lisp/")
(require 'swiper)
(ivy-mode 1)
(require 'ess-site)
```
At this point, `M-x locate` works. Then:
```
(ess-noweb-mode 1)
```
Now things are as described above. The root problem is that `ess-noweb-mode` ends up calling `make-variable-buffer-local` on `post-command-hook`, which breaks swiper.

**Comment by abo-abo** [comment]
> Now things are as described above. The root problem is that ess-noweb-mode ends up calling make-variable-buffer-local on post-command-hook, which breaks swiper.

So it's a huge bug in ESS. It breaks a whole lot of stuff, not just Ivy.

No package should do what `ess-noweb-make-variable-permanent-local` does to `post-command-hook`.

Report the bug in ESS, and in the meantime:

```elisp
(advice-add
 'ess-noweb-mode
 :after
 (lambda (_)
   (put 'post-command-hook 'permanent-local nil)))
```
