### ISSUE TITLE
Occur for ivy-switch-buffer

### ISSUE THREAD

**Issue by justbur** [abo-abo/swiper#438]
What do you think about using `ibuffer` for `ivy-switch-buffer`'s "occur" function?

**Comment by abo-abo** [comment]
Would be more useful than it is now. Go ahead if you like.

**Comment by justbur** [comment]
ok, I don't have time at the moment, but I'll get to it soon. It would be
nice if it somehow filtered the buffers to the current candidates, no?

**Comment by abo-abo** [comment]
Yes, of course. That's the idea.
