### ISSUE TITLE
counsel helper for recursively finding a file

### ISSUE THREAD

**Issue by wbolster** [abo-abo/swiper#439]
i did not really think this through completely, but anyway...

a helper to recursively find a file in `counsel-find-file` style would be awesome. the find-file functionality in `ido` allows for automatic expansion in case no matches are found, which is really useful to find files in "sibling" directories (or even a few levels further up/down the tree).

a swiper style `find ! -type d` would be a start, but proper integration with `counsel-find-file` would be much better.

**Comment by abo-abo** [comment]
Have a look at `find-file-in-project` and `counsel-locate`.

By the way, I really disliked that Ido feature. It took me quite a while to figure out how to turn it off.

**Comment by wbolster** [comment]
thanks for the pointers; i've settled on `projectile` and nice `hydra` for it to call `projectile-find-file` and some other `projectile` functions.

**Comment by abo-abo** [comment]
You're welcome.
