### ISSUE TITLE
ivy-read-action is not passed to ivy-occur

### ISSUE THREAD

**Issue by ardpp** [abo-abo/swiper#443]
In Example 4 on http://oremacs.com/2015/11/04/ivy-occur/
you explain how to use `ivy-occur` to get a list of some functions and then to jump to definitions instead of description. It used to work for me but now it doesn't (also using `emacs -Q`). 

Somehow `ivy-read-action` seems to be reset to default on the way to `ivy-occur`

**Comment by abo-abo** [comment]
Fixed, thanks.

**Comment by abo-abo** [comment]
You can still change the action in the occur buffer with <kbd>a</kbd>.
