### ISSUE TITLE
global ivy transformer 

### ISSUE THREAD

**Issue by justbur** [abo-abo/swiper#447]
This isn't really a feature request as much as a question about what you would do. 

Re: https://github.com/tmalsburg/helm-bibtex/pull/102

Helm has a "transformer" option that only formats visible candidates apparently. The issue in this case is that formatting goes through all of the candidates to determine what to do and for helm-bibtex the total number of candidates can be large. So with the helm option you just repeatedly format the visible ones and performance is fine. You can format all of the candidates at the beginning but this might be slow. The ivy transformer option only "knows" about individual candidates at a time, so it seems harder to use this. 

What would you do in this case? Lots of candidates to be formatted, but you somehow need to know at least all of the visible candidates (to line up the columns I guess). I guess one response is don't use columns, but what if you wanted to?

**Comment by abo-abo** [comment]
The way to reformat only the visible candidates in Ivy is to let-bind `ivy-format-function`. Currently, the only remaining example of that is `counsel-yank-pop`.

**Comment by justbur** [comment]
Thanks for the pointer
