### ISSUE TITLE
ivy--directory-done not always respecting selection

### ISSUE THREAD

**Issue by justbur** [abo-abo/swiper#448]
This is an example I ran into after calling ivy-alt-done from counsel-find-file

1. After typing "helm", I have three candidates
  - helm 
  - helm-bibtex
  - emacs-helm-ag
2. helm is selected with that text, which is correct. 
3. Now select another candidate like helm-bibtex and call ivy-alt-done (`C-j`).
4. I'm in the helm directory

In playing with this briefly, it seems that it has to do with the text "helm" matching one of the options exactly, even though I selected something else. I can debug further if need be.

**Comment by abo-abo** [comment]
Thanks.

**Comment by justbur** [comment]
Thanks for the quick fix

**Comment by abo-abo** [comment]
You're welcome. This was some sort of old ad-hoc code with a non-obvious edge case.

I should try to add some integration tests for file handling. So far, only simple stuff like `ivy-read` for a list of strings is covered.

**Comment by justbur** [comment]
> I should try to add some integration tests for file handling. So far, only simple stuff like ivy-read for a list of strings is covered.

I can try to help, although I don't have a lot of experience creating good tests

**Comment by abo-abo** [comment]
Thanks, I don't yet know what the best way to stub the file system in the tests.

Might be good enough to just have a `test/` directory with a couple empty files. Then do `ivy-read` combined with e.g. `(kbd "helm C-j")` to simulate the input that you described. Then check the selected buffer.

Or maybe this directory structure should be created and deleted during the test.
