### ISSUE TITLE
Finding file finds it in $HOME if candidate is selected without any pattern

### ISSUE THREAD

**Issue by tsdh** [abo-abo/swiper#45]
When finding a file with `ivy-mode` in some directory `~/some/dir/` and ivy shows the files in there, when you select `foo.txt` without giving a pattern (so just selecting it with `ivy-next-line` and friends and confirming with `C-j` or `RET`), in fact `~/foo.txt` will be found where it should have been `~/some/dir/foo.txt`.

Detailed recipe with `emacs -Q`:

  1. `M-x package-initialize RET` to load swiper/ivy
  2. `M-x ivy-mode RET`
  3. `C-x C-f some/dirC-j` so that the files in `~/some/dir/` are listed
  4. Select some arbitrary file (e.g., `foo.txt.`) using only `C-n` and `C-p`.
  5. Confirm selection with `C-j` or `RET`.

Now you have a buffer `foo.txt` (which is most likely empty) associated with the file `~/foo.txt` whereas it should actually show `~/some/dir/foo.txt`.

**Comment by abo-abo** [comment]
Nice catch, thanks.

**Comment by tsdh** [comment]
You're welcome!

**Comment by abo-abo** [comment]
Now I remember why that case wasn't directory-expanded in the first place.
I've made it so that file names with `*` in them won't be directory-expanded. But they are rare, so it
should not intersect with your use-case.
