### ISSUE TITLE
Error running counsel commands: Symbol’s function definition is void: dbus-call-method

### ISSUE THREAD

**Issue by glucas** [abo-abo/swiper#450]
I'm running Emacs 25 pretest on Windows and the latest swiper/counsel update has broken things for me. I believe my emacs is compiled without dbus support, which is now assumed to be present by counsel?

I'm getting this error from counsel-M-x, counsel-find-file, etc.

**Comment by glucas** [comment]
Well.. I'm not exactly sure why but after messing around with un/re-installing packages I'm not seeing this error. I'll close this issue for now and re-open if I find anything reproducible.

**Comment by abo-abo** [comment]
> I believe my emacs is compiled without dbus support, which is now assumed to be present by counsel?

dbus is only necessary for `counsel-rhythmbox`. I've noticed lately some reports for many packages across the board that are solved by reinstalling.  Maybe it's an issue of people using 24.5/25 intermittently with the same ELPA dir.
