### ISSUE TITLE
ispell/flyspell candidates via counsel

### ISSUE THREAD

**Issue by manuel-uberti** [abo-abo/swiper#455]
This is more of a feature request than a bug: would it be possible to let counsel take care of ispell/flyspell candidates?

Something similar to [helm-flyspell](https://github.com/pronobis/helm-flyspell), for instance.

**Comment by abo-abo** [comment]
Interesting, never thought of doing it that way. I'm using `ace-popup-mode` currently.

**Comment by manuel-uberti** [comment]
Oh, that's nice too. I guess I would like an ivy/counsel approach because I was used to `helm-flyspell`.

**Comment by abo-abo** [comment]
I'd suggest you make a PR to `helm-flyspell` to also have Ivy as a completion option.
The diff is one line:

    -(helm-flyspell (third poss) word)
    +(ivy-read "Correction: " (third poss) :preselect word)
    
Or add this to your config:

    (defun my-ivy-flyspell (fn candidates word)
      (ivy-read "Correction: " candidates
                :preselect word))
    (advice-add 'helm-flyspell :around 'my-ivy-flyspell)
    
and simply keep using the `helm-flyspell-correct` command.

**Comment by manuel-uberti** [comment]
That means I have to install `helm`, though, which I'm not that eager to do since your work took me away from it. :-)

**Comment by abo-abo** [comment]
Well, `helm-flyspell` doesn't really need a strict dependency on `helm`. It could even get away with calling `completing-read` in `helm-mode`.

I don't like the idea of taking 50 lines of `helm-flyspell`, changing 1 line and pasting it into counsel.el.

**Comment by manuel-uberti** [comment]
No problem, I see your point and you know I agree with you about `completing-read`. I'll adapt it in my configuration.

**Comment by d12frosted** [comment]
@manuel-uberti I also wanted something similar to `helm-flyspell` but with ivy as front-end. So I've created package [flyspell-correct](https://github.com/d12frosted/flyspell-correct) that allows you to chose any interface (predefined are helm, ivy and popup). 

The only thing that I can't figure out - is how to implement saving functionality. With `helm` and `popup-menu` I can return either string or alist of `cmd` and `word`, so I can apply `cmd` later on. But looks like `ivy-read` returns the selected string. Documentation says that collection can be either a list of strings, an alist, a function or a hash table. So I thought that when you pass alist, `ivy-read` completes using list of cars and returns corresponding cdr. Didn't find any information in documentation on collection type, so I am here asking for help with implementation. :)

Currently I have following implementation:

```
(defun flyspell-correct-ivy (candidates word)
  "Run ivy for the given CANDIDATES given by flyspell for the WORD.
Return a selected word to use as a replacement."
  (ivy-read (format "Suggestions for \"%s\" in dictionary \"%s\": "
                    word (or ispell-local-dictionary
                             ispell-dictionary
                             "Default"))
            (append
             (mapcar (lambda (x) (cons x x)) candidates)
             (list (cons (format "Save \"%s\"" word) (cons 'save word))
                   (cons (format "Accept (session) \"%s\"" word) (cons 'session word))
                   (cons (format "Accept (buffer) \"%s\"" word) (cons 'buffer word))))))
```

And when I complete something it returns car. Is it possible to return cdr instead? 

P. S. I know that there are actions, but I would like to reuse as much code as possible.

**Comment by manuel-uberti** [comment]
Thanks for the package. Let's wait for @abo-abo here, I'm sure he has got some suggestions. :)

**Comment by abo-abo** [comment]
> P. S. I know that there are actions, but I would like to reuse as much code as possible.

Here's how to get a non-string result with `ivy-read`:

```elisp
(let* (result
       (action (lambda (x) (setq result x))))
  (ivy-read "test: " '(("foo" 1 foo)
                       ("bar" 2 bar))
            :action action)
  result)
```

This is currently the only way.

**Comment by d12frosted** [comment]
Wow, that works ideally. Thank you so much for such helpful and quick response!

**Comment by manuel-uberti** [comment]
@d12frosted wouldn't actions make it more consistent to how ivy and counsel work elsewhere. IMHO, it takes little time to get used to actions, and having the actions separate from the candidates lead to less confusion.

**Comment by d12frosted** [comment]
Yeah, I understand that using actions would be more consistent (and actually I like this idea more than inserting commands to candidates), but I wanted to keep first implementation simple. If you wish to implement it - PRs are welcome :)
