### ISSUE TITLE
el-get could not build swiper

### ISSUE THREAD

**Issue by mrapogee** [abo-abo/swiper#457]
I'm on OS X 10.11.4 in iTerm2 and I'm getting these errors when trying to install swiper via el-get.

```
...
doc/ivy.texi:938: Unknown command `indentedblock'.                   
doc/ivy.texi:941: Unmatched `@end'.                                                                               
doc/ivy.texi:943: Unknown command `indentedblock'.                                                             
doc/ivy.texi:962: Unmatched `@end'.         
...             
```
Any clue what's going on?

**Comment by syohex** [comment]
I suppose you use old `makeinfo`. Please upgrade and retry after upgrading texinfo package. If you use homebrew, you can upgrade it by following steps.

```
% brew install texinfo
% brew link texinfo --force
```

**Comment by mrapogee** [comment]
Thanks. I got after switching from using el-get

**Comment by wbolster** [comment]
this issue can be closed, it seems

**Comment by abo-abo** [comment]
OK.
