### ISSUE TITLE
Issues with ivy and the history

### ISSUE THREAD

**Issue by tsdh** [abo-abo/swiper#46]
I have some issues with ivy and the history.

1. The history doesn't save the eventually chosen candidate but instead saves the current pattern the user specified at the prompt.  Thus, after executing `whitespace-cleanup` using `M-x whi cl<return>`, pressing `M-p` at the next ivy completion prompt inserts `whi cl` again.  I had expected that it inserts `whitespace-cleanup`.
Ok, in this case the current behavior is harmless because with the pattern `whi cl` `whitespace-cleanup` is the first of two matches and thus pre-selected.  But if you have chosen some other candidate using `C-p`/`C-n` or the arrow keys, you cannot simply re-execute one of the last few commands using `M-x <repeatedly M-p> RET` but you have to manually select again.

2. The history seems to be shared by all completion modes.  I'd very much prefer to have separate histories for the different completion kinds (variable, command, function, file, buffer, some predefined collection used by some command).

**Comment by abo-abo** [comment]
Thanks for the summary, it's all do-able and should be done soon.
As for <kbd>M-x</kbd>, you might be interested in [this M-x replacement](https://github.com/abo-abo/smex).
This is my fork that can use either `ivy` or `ido` (the main one uses `ido`). It keeps track of the most used commands, giving them the sorting priority. Very neat.

**Comment by tsdh** [comment]
@abo-abo Great, good news it should be done soon.

With respect to (your version of) smex, it bothers me not enough to use yet another package in the meantime.  But it reminds me that I'd prefer if I could customize the sorting order on a per-category (file, buffer, function, variable, etc.) basis in ivy mode.

I'm thinking of something like

```elisp
(setq ivy-candidates-sorting-functions '((files string-collate-lessp)
                                         (buffers ivy-buffer-more-recent-p)
                                         (default string-lessp))
```

which would supersede individual variables.  I think, there's currently only `ivy-sort-file-function`.

**Comment by abo-abo** [comment]
I would prefer not to sort the candidates at all, unless I know that there are very few.
For instance, `describe-function` gives 30000 candidates, while `counsel-git-grep` can give 3000000 candidates for the Emacs repo.
But I guess it's totally fine to sort files and buffers, I can implement that.
Just hoping that `internal-complete-buffer` and `read-file-name-internal` don't change names.

**Comment by abo-abo** [comment]
But I guess it takes only 0.03s to sort 30000 candidates, and it kind of looks nicer sorted.
Maybe I should do it by default unless the collection is larger than say 30000.

**Comment by tsdh** [comment]
I don't think those will change names.  I guess you are not the only one relying on them.

And yes, some threshold would be pragmatic.  And maybe one could defer sorting until the user has typed enough to restrict the remaining matches to be less than this threshold.  E.g., when `counsel-git-grep` returns 3000000 candidates initially, after the user typed `foo bar` only might be 1000 left, and then this filtered list could be sorted.  Of course, one has to switch back to the original unsorted list of candidates when the user deletes parts of his pattern.

**Comment by zhaojiangbin** [comment]
I'd vote for splitting ivy history by completion kinds.

**Comment by tsdh** [comment]
Just as a reference: the custom sorting depending on completion type has already been implemented with commit https://github.com/abo-abo/swiper/commit/bb89c9db51dc1aee7c824f1e95224d79b29651a8.

**Comment by abo-abo** [comment]
Part 2 is now fixed.

I don't know how to fix part 1 in a good way, since I actually like the partial matches being stored. Storing the full candidate means that there's no longer any context.

On the other hand, storing partial input + index isn't the regular history variable format. And index will mess up if the candidates change, which is very possible for <kbd>M-x</kbd>.

A good solution that works for me is [smex](https://github.com/abo-abo/smex), since it sorts the <kbd>M-x</kbd> commands by the usage history. Ivy-mode doesn't re-sort this list so it works quite well.

**Comment by tsdh** [comment]
Partial input plus index can be encoded as `(propertize partial-input 'ivy-index index)` but you are correct in that the candidates might change and invalidate the index.

What do you mean with there is no context when the full candidate was saved to the history?

**Comment by abo-abo** [comment]
> What do you mean with there is no context when the full candidate was saved to the history?

I mean that usually there will be only a single candidate, instead of a few similar candidates.
I like to see the related candidates, because sometimes it's them I want when I scroll history.

**Comment by tsdh** [comment]
What about storing partial input plus full candidate using the `propertize` trick? Then you can preselect the full candidate if it is still there and do something else otherwise.

**Comment by abo-abo** [comment]
This can work. I'll try it.

**Comment by abo-abo** [comment]
I've tested it for `counsel-describe-variable`, it seems to work.
There might be issues for different commands sharing the same history.
