### ISSUE TITLE
allow grep style keybindings for `counsel-ag`

### ISSUE THREAD

**Issue by wbolster** [abo-abo/swiper#462]
is there a reason that `counsel-ag` does not define `:keymap counsel-git-grep-map`? it would allow `C-l` to recenter (i.e. display buffer at right location) during search. this works for `counsel-grep` but not for `counsel-ag`, and adding this line seems to work fine.

**Comment by abo-abo** [comment]
Thanks.

**Comment by abo-abo** [comment]
You can now also use <kbd>M-q</kbd> in `counsel-ag`.
