### ISSUE TITLE
Use non-greedy regexps (`ivy--regex`)

### ISSUE THREAD

**Issue by tsdh** [abo-abo/swiper#47]
Currently, a swiper/ivy pattern `foo bar` is converted to a regexp `\\(foo\\).*\\(bar\\)` and that is used to filter the candidates.  I'd like to suggest that you use a non-greedy pattern, e.g., `\\(foo\\).*?\\(bar\\)` which would visualize the shortest rather than the longest match in swiper.  Currently, you get this highlighting:

    This is a sentence with foo and bar where bar is foo and bar.
                            G1                               G2

As you see, there is only one match.  With the suggested non-greedy regexp, you'd get:

    This is a sentence with foo and bar where bar is foo and bar.
                            G1      G2               G1      G2

Now there are two matches visualized which seems more useful to me.  And matches which are narrower are probably more likely the thing the user intended to match.

**Comment by abo-abo** [comment]
Thanks, it looks better. Is there any disadvantage of using non-greedy regex (performance / other problems)?

**Comment by tsdh** [comment]
@abo-abo I've tested on a large TeX English prose buffer searching for all occurrences of "\\\\(a\\\\).*\\\\(the\\\\)" (2960 matches) and "\\\\(a\\\\).*?\\\\(the\\\\)" (3688 matches).  The former takes 0.87 seconds, the latter 1.05 seconds.  So I think it doesn't make a big difference for the matching/searching part of it.  The latter is only a bit slower because there are more matches and thus `re-search-forward` gets called more often.

Of course, more matches also means more overlays.  With the former regexp, there could be at most one match with its group-overlays per line.  Now that's bounded only by the length of the line.  In theory, there can be N overlays per line if the line is N chars long.  Thus in a buffer with very long lines and a pattern that matches almost anything, there can be an overlay explosion.  I think the worst-case user input is `. .` which causes every char in the buffer to have its own group-1 or group-2 overlay.
