### ISSUE TITLE
ivy-views: question about usage with bookmark-jump

### ISSUE THREAD

**Issue by manuel-uberti** [abo-abo/swiper#472]
Hi,

this is what I'm trying to do:
```
(setq ivy-views '(("desktop + ba-server [–]"
                     (vert
                      (buffer (bookmark-jump "desktop"))
                      (buffer (bookmark-jump "ba-server"))))
                    ("boccaperta + ba-server [–]"
                     (vert
                      (buffer (bookmark-jump "boccaperta"))
                      (buffer (bookmark-jump "ba-server"))))))
```
I can now see both entries when I issue `ivy-switch-buffer`, but when I hit RET on one of them I get this error:
```
window-normalize-buffer-to-switch-to: Wrong type argument: stringp, (bookmark-jump "desktop")
```
I'm pretty sure I'm setting `ivy-views` in the wrong way.

**Comment by abo-abo** [comment]
Thanks for the feedback. You should now use:

```elisp
(setq ivy-views '(("desktop + ba-server [–]"
                   (vert
                    (sexp (bookmark-jump "desktop"))
                    (sexp (bookmark-jump "ba-server"))))
                  ("boccaperta + ba-server [–]"
                   (vert
                    (sexp (bookmark-jump "boccaperta"))
                    (sexp (bookmark-jump "ba-server"))))))
```

The buffer option simply takes a string and opens a buffer (pre-existing or not) with that name:

```elisp
(setq ivy-views '(("desktop + ba-server [–]"
                   (vert
                    (buffer "desktop")
                    (buffer "ba-server")))
                  ("boccaperta + ba-server [–]"
                   (vert
                    (buffer "boccaperta")
                    (buffer "ba-server")))))
```

**Comment by manuel-uberti** [comment]
Thank you for the prompt fix. It works and it is great.

**Comment by manuel-uberti** [comment]
I restarted Emacs. This doesn't work unless I issue `bookmark-jump` once without `ivy-views`. 

I tried it with `emacs -Q` as well, but if use `ivy-switch-buffer` and select one of my views, I get this:
```
bookmark-get-bookmark: Invalid bookmark desktop
```
Only after I opened that same bookmark through with `bookmark-jump` (bound to `C-x r b`), I can use `ivy-switch-buffer` to open the view.

**Comment by abo-abo** [comment]
Here's my bookmark setup

    (require 'bookmark)
    (setq bookmark-completion-ignore-case nil)
    (bookmark-maybe-load-default-file)
    
I think the above should be enough for `bookmark-jump` to work.

**Comment by manuel-uberti** [comment]
Yes, that fixed it. Thanks again! 

Blog post coming soon...;)
