### ISSUE TITLE
Automatically enable and disable visual-line-mode when using swiper

### ISSUE THREAD

**Issue by swarnendubiswas** [abo-abo/swiper#474]
I read about issues with long lines in the swiper buffer and your support for visual-line-mode. 

Personally I do not use visual-line-mode, but it seems useful to enable it while searching with swiper for buffers that have long lines. To avoid enabling and disabling it manually, it would be good if one could enable it automatically only for the swiper buffer upon invocation and turn it off after the search. Is this functionality already supported within swiper? Or could there be swiper-related hooks to do this?

**Comment by abo-abo** [comment]
There's no need for hooks, just wrap swiper in your own defun.

Enabling/disabling `visual-line-mode` is out of scope of `swiper`, I think. If a user keeps a bunch of long lines in files, which I really don't recommend, then it's up to the users to enable `visual-line-mode`.

**Comment by pseudomyne** [comment]
hi,
i've just turned from isearch to swiper, and wow, it really seems what I was looking for. The only thing is, results in the swiper/mini buffer are not "wrapped" (sometimes, matching words are hidden behind the tiny arrow on the right) . I’ve read this thread, but I’m unsure i’m at the right place. In any case, abo-abo's answer doesn’t help, for I’m not a lisper. i'm using emacs to read and write literary texts (where "lines" can be long). Is there something i could switch somewhere on to get this wrapping ? Or maybe, abo-abo, could you be a bit more explicit when saying "just wrap swiper in your own defun" ? 
thanks

**Comment by abo-abo** [comment]
@pseudomyne <kbd>M-x</kbd> `global-visual-line-mode` should probably be fine for you.

**Comment by swarnendubiswas** [comment]
You could try this, and bind the function to some sequence of keys. I admit this is not perfect.

```
  (defun dotemacs-swiper-with-visual-line-mode ()
    "Long lines are truncated at the right without visual line"
    (interactive)
    (visual-line-mode 1)
    (swiper)
    (visual-line-mode -1))
```

**Comment by pseudomyne** [comment]
Weird, none of your tips work here. Still got right arrows on almost everyline ; `global-visual-mode` is on.  Will check my dotemacs a bit deeper. thank you anyway ! you've been so quick !!

**Comment by pseudomyne** [comment]
I've found something. When i'm _inside_ the Swiper window, M-x visual-line-mode works... (need to disable it and then re-enable it).............
