### ISSUE TITLE
yasnippet has wrong path for new created snippet

### ISSUE THREAD

**Issue by stardiviner** [abo-abo/swiper#475]
When I create a new snippet for a mode with `[C-c & C-n]`.
And try to save the new created snippet with `[C-c C-c]`.
Then ivy prompt like this:
```
File name to create in /home/stardiviner/.emacs.d/snippets/org-mode? ~/Org/Projects/
...
...
```

The `~/Org/Projects/` should not be here.

I tested with `emacs -q`. When not enable `ivy-mode`, yasnippet works correctly. After enable ivy-mode with `(ivy-mode 1)`. The appears this issue.

I think this might be introduced by this PR: https://github.com/abo-abo/swiper/pull/461

**Comment by abo-abo** [comment]
Thanks. Please check.

**Comment by stardiviner** [comment]
Fixed, thanks
