### ISSUE TITLE
ivy-ignore-buffers: question about behaviour

### ISSUE THREAD

**Issue by manuel-uberti** [abo-abo/swiper#477]
Hi,

I set this in my setup:
```
(setq ivy-ignore-buffers '("company-statistics-cache.el"))
```
From what I understood in [this page](https://www.emacswiki.org/emacs/RegularExpression), it should be the right regexp to refer to `company-statistics-cache.el` alone.

When I call `ivy-switch-buffer` now I'm not seeing `company-statistics-cache.el` in the list of buffers, which is what I am expecting.

However, if I type `compa`, `company-statistics-cache.el` appears:

![2016-04-18-083904_867x211_scrot](https://cloud.githubusercontent.com/assets/8199224/14595605/e4aa7dd4-0540-11e6-856b-3440f81676bd.png)

Is this the expected behaviour?

**Comment by abo-abo** [comment]
> Is this the expected behaviour?

It is the programmed behavior. I'm not sure if I programmed it, but it makes some sense: if no buffer at all matches the current input, when taking `ivy-ignore-buffers` into account, ivy will try again with `ivy-ignore-buffers` disabled.

If it's not OK with you, propose a different behavior. For instance setting `ivy-use-ignore` to `'always` could display 0 buffers, even if some buffers on `ivy-ignore-buffers` match.

**Comment by manuel-uberti** [comment]
I see, thanks for the explanation. Actually, I guess your example with `'always` would be the best solution (for my use case, anyway).

But if the current behaviour makes sense, leave it as it is. I don't want to make things more complicated.

**Comment by abo-abo** [comment]
Have a look, you should now be able to do what you described.

**Comment by manuel-uberti** [comment]
You're too kind and quick, thank you. It works!
