### ISSUE TITLE
swiper-all/swiper--multi-candidates throws wrong-type-argument wholenump

### ISSUE THREAD

**Issue by DWgit** [abo-abo/swiper#481]
If a buffer contains a long line with escaped characters (e.g., \230 or ^e), then swiper--multi-candidates throws wrong-type-argument because the subtraction below produces a negative number.

`                      (make-string
                        (- ww (string-width s) (length (buffer-name)) 3)`

To replicate:

Open a new emacs session with badbuf.txt (attached), and do a swiper-all.

Contrast with goodbuf.txt, which is identical except for lacking escaped characters.

[badbuf.txt](https://github.com/abo-abo/swiper/files/230037/badbuf.txt)
[goodbuf.txt](https://github.com/abo-abo/swiper/files/230038/goodbuf.txt)

**Comment by abo-abo** [comment]
Thanks.

**Comment by DWgit** [comment]
Thanks!
