### ISSUE TITLE
counsel-git-grep highlights matches in filenames

### ISSUE THREAD

**Issue by hmelman** [abo-abo/swiper#483]
`counsel-git-grep` lists matching lines prefixed with the filename and line number (as it should). It also highlights the matching strings in the lines shown (I believe via `ivy--format-minibuffer-line`). However it might also highlight part of the filename if it matches the regexp. I don't think it should highlight the filename (or line number) part of the line because that wasn't why the line is considered to match the regexp.

I assume similar functions such as `counsel-ag` and `counsel-pt` have the same problem.

This came from my work in #395 but I never came up with a good solution.

**Comment by abo-abo** [comment]
Thanks.

**Comment by hmelman** [comment]
Thanks for speedy fix but it seems rather specific. Does it work for anything else? Rather than checking if the caller was counsel-git-grep could there be an optional argument that could be passed in with a regexp or a function defining which part of the line to highlight?

**Comment by abo-abo** [comment]
I don't want to be changing the arglists too much, checking `:caller` is the way to go for now. Just remains to add `counsel-ag` to that list.

**Comment by hmelman** [comment]
and `counsel-pt` :) Would be nice for users to be able to add to that list too, maybe a defcustom? 

It seems wrong to have a check for a counsel-level command in ivy.el, but I see it's not the only one. `ivy-occur-revert-buffer` has a check for `(memq caller '(counsel-git-grep counsel-grep counsel-ag))`. It seems `counsel-pt` should be added to that list and it's docstring is mistaken. Maybe it's that counsel.el should have a defcustom for `counsel-grep-like-commands` and ivy could check for that. At least that way, adding a new command could be limited to changes in counsel.el.

**Comment by abo-abo** [comment]
I'll think about adding an API for this at some point. But I'm not sure anyone would want to deal with the logic: you have to pretty much replace `ivy--format-minibuffer-line` with something just as complex in a user-level `ivy-read` call.

On the other hand, it's just a str->str mapping, not rocket science. And helm has as similar API for this, if I recall correctly.
