### ISSUE TITLE
Error installing 0.8.0

### ISSUE THREAD

**Issue by andschwa** [abo-abo/swiper#485]
```
M-x package-install
swiper
```

`package-compute-transaction: Package ‘ivy-0.8.0’ is unavailable`.

I've cleared my elpa folder and tried several times.

I can't find `ivy` on MELPA manually; is it not being published?

**Comment by abo-abo** [comment]
> is it not being published?

Please see https://github.com/melpa/melpa/pull/3811. Also, `ivy-0.8.0` should be available on GNU ELPA soon, I've pushed the update 7 hours ago: http://git.savannah.gnu.org/cgit/emacs/elpa.git/commit/?id=39a458ed74ecb2015e933438a547846abed973a0.

**Comment by rprimus** [comment]
Mon Apr 25 19:57:35 BST 2016

Having just experienced this,  I am now completely confused about:

1. the functionality differences between ```ivy``` (main package),  ```swiper``` and ```councel``` (dependencies on ```ivy```
2.  Why packages both appear on GELPA (0.7.0) and MELPA (20160425.307) - with differing versions?

Issue #463 did shed some light on the ```swiper```/```ivy``` naming issue.

**Comment by abo-abo** [comment]
> Having just experienced this, I am now completely confused about:

No need for confusion.

> 1

The dependency graph is ivy <- swiper <- counsel. With each tier, you get more functionality. Some people are OK with less functionality, they might want to use only `ivy`.

> 2

The versions on GELPA are `swiper-0.7.0` (the latest one 4 months). `ivy-0.8.0` is supposed to replace it in a few hours.

As a third point, the plan for now is to have the three packages split in MELPA.

**Comment by andschwa** [comment]
Ah, so this was just a distribution problem. Got to love package feeds.
