### ISSUE TITLE
can I search for a literal exclamation mark?

### ISSUE THREAD

**Issue by glasserc** [abo-abo/swiper#486]
Since swiper treats exclamation mark separately to invert the meaning of a regular expression, it seems like the answer is no. The trick of doubling the character to get a literal one like you can do with spaces doesn't seem to work.

**Comment by manuel-uberti** [comment]
True, I'm not able to look for an exclamation mark either.

**Comment by dieggsy** [comment]
@abo-abo  I _think_ this can be closed, seems I can search for a literal exclamation mark with `\!`.

**Comment by abo-abo** [comment]
Thanks, closing.
