### ISSUE TITLE
MELPA in README: should be GNU ELPA now?

### ISSUE THREAD

**Issue by xuhdev** [abo-abo/swiper#488]
In README:

> After installing from MELPA, the manual is also available through the (ivy) Info node.

**Comment by manuel-uberti** [comment]
The package is in both repos: http://oremacs.com/2016/04/26/ivy-0.8.0/

**Comment by abo-abo** [comment]
Exactly. GNU ELPA contains a very stable version, with release notes and all, new release every few months. While MELPA is cutting-edge, with updates almost every day.
