### ISSUE TITLE
counsel-find-files: insert file names into the buffer?

### ISSUE THREAD

**Issue by xuhdev** [abo-abo/swiper#489]
Is it possible to do so? In helm, this can be done by running `C-c i` after choosing the file after calling `helm-find-files`.

**Comment by manuel-uberti** [comment]
You can add this to your setup:
```
(defun ivy-insert-action (x)
  (with-ivy-window
    (insert x)))

(ivy-set-actions
 t
 '(("I" ivy-insert-action "insert")))
```
And then press `M-o I` on the candidate you're looking for to have the path inserted in your current buffer. See: http://oremacs.com/2016/04/26/ivy-0.8.0/

**Comment by abo-abo** [comment]
@manuel-uberti Thanks for the example.

@xuhdev Does that solve your issue?

**Comment by xuhdev** [comment]
@manuel-uberti Yes, the setup can be used to insert a file path, but I'm looking for a more general solution to complete the partial file name which the cursor is placed.

For example, if there is a file `foo.txt` in the current directory, and `fo` is before the cursor, it would be nice that `C-x C-f` can complete the full file name instead of insert `foo.txt` after `fo`.

**Comment by xuhdev** [comment]
@abo-abo Also, does ivy support something like `ivy-add-actions` to add additional actions instead of overriding all existing actions? Thanks!

**Comment by abo-abo** [comment]
> For example, if there is a file foo.txt in the current directory, and fo is before the cursor, it would be nice that C-x C-f can complete the full file name instead of insert foo.txt after fo.

In Emacs this functionality is handled by `complete-symbol` and `completion-at-point`. Both should work fine with `ivy-mode` on. For example, open <kbd>M-x</kbd> `shell` and enter `cd D`. If I press <kbd>TAB</kbd> (`completion-at-point`), I'll get candidates `Documents`, `Downloads` etc, and they will be appropriately inserted into the buffer when I press <kbd>RET</kbd>.

**Comment by abo-abo** [comment]
I think this is solved, closing.
