### ISSUE TITLE
find-file with ivy doesn't do anything if the current directory contains only one file and ivy-extra-directories is nil

### ISSUE THREAD

**Issue by tsdh** [abo-abo/swiper#49]
With `emacs -Q` and `(setq ivy-extra-directories nil)` visit a file `/tmp/test/testfile.txt` where this file is the only one in the directory.  Then do `C-x C-f`.  It won't do anything visible.

What I expect of course is that it prompts me for a file and the completion starts in the current directory `/tmp/test/`.

**Comment by abo-abo** [comment]
Do you prefer `("./" "../")` or `("" "")` to be returned in this case (I chose the latter for now)?

**Comment by tsdh** [comment]
What is the meaning of the latter?

**Comment by abo-abo** [comment]
`ivy-read` immediately returns if there's 1 or less candidates.
The latter is just a list of empty strings to make `ivy-read` not return.

**Comment by tsdh** [comment]
I see.  Is that the right thing to do anyway?  I mean, even if there's just one candidate, isn't the user supposed to see and confirm that, too?

**Comment by abo-abo** [comment]
I don't know, it made sense at the time when I added that logic. Now I can't remember why.
I'll probably update it to follow `require-match`, which wasn't in the initial signature.
