### ISSUE TITLE
swiper style imenu selection

### ISSUE THREAD

**Issue by wbolster** [abo-abo/swiper#490]
`imenu` offers a "summary" of the current file, e.g. class and function definitions for code, and headings for text (depending on the format of course). it would be great to have swiper style navigation for this.

`counsel-imenu` shows the items, but i would like to see the actual line of the file (and not the text generated by `imenu`), and have a "follow mode" so that moving up and down actually moves the relevant buffer portion into view, just like swiper does.

alternatively, i would appreciate any pointers to achieve something similar. ;)

**Comment by abo-abo** [comment]
> alternatively, i would appreciate any pointers to achieve something similar. ;)

For LISP dialects, I use `lispy-goto` from `lispy`. It uses Semantic and works much better than `imenu`, since it understands the syntax better.

For C++ and C, `moo-jump-local` from `function-args` is also good.

For general purpose, `helm-semantic` is OK. I could make a version of it if necessary.

**Comment by gperaza** [comment]
It would be nice to have counsel-semantic. Helm-semantic is the only helm feature I still use.

**Comment by abo-abo** [comment]
Have a look at `counsel-semantic`. 

But do note that it's much less pretty and informative than `lispy-goto` or `moo-jump-local`.  Those commands are better because they specialize in their own language. The generic solution doesn't understand and show everything.
