### ISSUE TITLE
Counsel-M-x issue with multiple-cursor functions

### ISSUE THREAD

**Issue by shanavas786** [abo-abo/swiper#495]
With counsel-m-x, some functions in multiple-cursors replaces the buffer content with function name.
![test](https://cloud.githubusercontent.com/assets/5337197/14955065/d284789a-107f-11e6-9d3c-403a0a4a4d04.gif)

**Comment by abo-abo** [comment]
Please cite the code you used as text.

**Comment by shanavas786** [comment]
I did the following to re-generate the issue. started a pure emacs session (emacs -Q) and evaluated the following line by line to initialize the packages
```
(package-initialize)
(require 'multiple-cursors)
(require 'ivy)
(ivy-mode 1)
(global-set-key (kbd "M-x") 'counsel-M-x)
```
Then when a region in selected and say `M-x mc/edit-lines` is run (be it in scratch of other buffers), the buffer content gets replaced with command. The same happens with `M-x counsel-M-x mc/edit-lines` without binding `counsel-M-x` to `M-x`

**Comment by abo-abo** [comment]
Works fine for me. Just make sure that `ivy-done` and `ivy-alt-done` are on `mc/cmds-to-run-once` and not on `mc/cmds-to-run-for-all`.

The above two vars are in your `~/.emacs.d/.mc-lists.el`. Edit them accordingly and use `eval-buffer` or `eval-last-sexp`.

**Comment by shanavas786** [comment]
Thats it !!. Thanks :)
