### ISSUE TITLE
ivy-switch-buffer: wrong default selection?

### ISSUE THREAD

**Issue by manuel-uberti** [abo-abo/swiper#496]
Is there a reason the default highlighted candidate is never the first find? I mean, before hitting either `C-p` or `C-n`.

![2016-05-02-162317_972x162_scrot](https://cloud.githubusercontent.com/assets/8199224/14956866/3899717e-1082-11e6-9526-de98810c42ff.png)

![2016-05-02-162430_956x217_scrot](https://cloud.githubusercontent.com/assets/8199224/14956868/3e015190-1082-11e6-9116-1e427c4faa7f.png)

I am using latest Ivy/Counsel from MELPA.

**Comment by abo-abo** [comment]
Of course there's a reason:). It matches the default behavior of `switch-to-buffer`: the initial selection is always the next buffer.

See this code from `read-buffer-to-switch`:

> (read-buffer prompt (other-buffer (current-buffer))
>             (confirm-nonexistent-file-or-buffer))

So even with `ivy-mode` on, I can still cycle the last two buffers with <kbd>C-x b RET</kbd>, just like it's possible by default.

**Comment by manuel-uberti** [comment]
Perfect, thanks for the explanation.
