### ISSUE TITLE
swiper-query-replace replaces just the last occurence

### ISSUE THREAD

**Issue by drorbemet** [abo-abo/swiper#499]
Can the following be reproduced?:

1.  In a text buffer with multiple occurences of "foo" in text.
2.  Call swiper, input "foo" as pattern.
3.  Press M-q for query-replace.
4.  Enter "bar" as replacement.
5.  Hit RET. Notice the cursor moves to the last match and query-replace starts there, ignoring all but the last match.

**Comment by manuel-uberti** [comment]
Yes, I can reproduced this in `emacs -Q`.

**Comment by abo-abo** [comment]
Can't reproduce, the replacement always starts from the selected candidate for me.

**Comment by manuel-uberti** [comment]
This is what I am doing:

- `emacs -Q`
- `M-x package-initialize`
- enter this text (where `|` is point):
```
foo
foo
bar
foo
bar|
```
- `M-x swiper RET foo`
- `M-q`
- this is what I am seeing:

![2016-05-04-172618_729x171_scrot](https://cloud.githubusercontent.com/assets/8199224/15019179/3a988126-121d-11e6-82dc-ff343f16151c.png)

- then I press `!` and this happens:

![2016-05-04-172727_729x588_scrot](https://cloud.githubusercontent.com/assets/8199224/15019203/5909ece4-121d-11e6-8853-4e6aa4bef6b3.png)

**Comment by abo-abo** [comment]
You have the third (and last) occurrence of `foo` selected when you press <kbd>M-q</kbd>, right? That means that the third and all following (none in this case) candidates are passed to `query-replace`.

If you want to replace them all, do `M-< M-q`. The current behavior is similar to what the original `query-replace` does.

**Comment by manuel-uberti** [comment]
Fantastic, it works perfect for me that way. Thank you.

**Comment by manuel-uberti** [comment]
@drorbemet does it work for you like @abo-abo explained?

**Comment by drorbemet** [comment]
Yes, it works for me. Thanks for the hint. But I found this one hard to find in the docs even after knowing the answer M-< M-q. 
Besides having to think about the position of the cursor, doesn't feel intuitive for me.
Rather I prefere to rely on scm based operations like reverting hunks with magit status to fix unintentionally changes.
I remember having to hit just M-q and ! only to replace everything independent of cursor position. But I may be mistaken about that. 

a general note on my current editing experience:
After trying to use keybinding based access to editing functionality in emacs for multiple years now I find myself preferring persistent and evolving native lisp forms in a repl more and more over keybindings on ephemeral command calls. Ad hoc parametrization and adaptation of a copy of a command to a use case feels easier then having to search for keybindings in addition to the search for a functionality.

That said, I find fast feedback about the result of an operation and integration of multiple resources very effective for any workflow.
That's what modes like swiper and counsel but magit also provide for text editing. 
For all of which I am very thankfull! :-).

**Comment by abo-abo** [comment]
@drorbemet Here's what I did before `swiper`: `M-< M-%`. There's value in having the flexibility to replace not all candidates at once, but all candidates starting from a certain one. Since the built-in Emacs commands provide this value, I don't want `swiper` to lose it.

That said, documentation patches are always welcome. A defcustom that turn's on global replace would be fine as well.
