### ISSUE TITLE
Verbatim selection and candidate ordering

### ISSUE THREAD

**Issue by jdahm** [abo-abo/swiper#50]
Excellent job with ivy-mode! Just some additional related issues I've noticed. In both cases I'm probably just missing something...

### Case 1
Touch files a and ab and go to rename file a to b. Go into dired mode; press R on a; enter b. The completion selects ab and afaik there's no way to revert to just a minibuffer input without completion (this was bound to C-f in ido).

### Case 2
I can't seem to find a minimal test case for this but here's the situation:

I have directories 2014.12.04_x and x, I'm calling ``find-file'` to open x/a in a buffer, and from muscle memory I type `x C-j a`. When these dirs are both inside a parent dir with many other files/folders, it seems to select 2014.12.04_x when typing `x C-j` instead of the full completion x, so I keep opening 2014.12.04_x/a instead of x/a. When trying to create a minimal test case for this, and these were the only two dirs in the parent, the completion seemed to do the correct thing and select x.

**Comment by jdahm** [comment]
Excellent! Thanks for the quick work.

**Comment by abo-abo** [comment]
Case 1 can now be solved by:

1. type whatever input you wish, doesn't matter if it matches a candidate.
2. type <kbd>C-u C-j</kbd> to exit ignoring candidates, i.e. with your precise input.

You can also bind `ivy-immediate-done` to something else if you want.

**Comment by abo-abo** [comment]
I don't know about Case 2, maybe we'll wait until there's a recipe to reproduce.

**Comment by jdahm** [comment]
My minimal test involved files, which turns out not to have the issue.

Just now I tried it with directories and I could indeed reproduce the bug with the directories a_x and x. If you enter x, the completion incorrectly orders a_x before x.

**Comment by abo-abo** [comment]
OK, should work better now. <kbd>/</kbd> also works if the directory match is perfect.

**Comment by abo-abo** [comment]
I think that this is solved now. Correct me if I'm wrong.
