### ISSUE TITLE
Document relationship between ivy, swiper, and counsel

### ISSUE THREAD

**Issue by kprav33n** [abo-abo/swiper#500]
I recently moved from helm based workflow to ivy/swiper. It is not obvious what is what with respect to ivy, swiper, and counsel. All three seem to work in tandem. Some kind of explanation, or pointer would be a nice to have.

**Comment by abo-abo** [comment]
`counsel` depends on `swiper` and `swiper` depends on `ivy`. That's all there is to it. Use the commands that you need, everything is automatic.

**Comment by kprav33n** [comment]
Thanks for the answer @abo-abo Does `ivy-resume` work with counsel sessions as well? When I use `ivy-resume`, I sometimes get that the last session was not compatible with `ivy-resume`. My workflow heavily used `helm-resume`, and I'm trying to find the equivalent here.

**Comment by abo-abo** [comment]
Yes, `ivy-resume` should work for all counsel functions.

**Comment by manuel-uberti** [comment]
I can confirm it works with counsel functions. Is there a function in particular that doesn't work, @kprav33n?

**Comment by Wilfred** [comment]
I think #579 clarified the relationship. It should be clearer now.

**Comment by abo-abo** [comment]
@Wilfred thanks, I close the issue then.
