### ISSUE TITLE
counsel-imenu for repeat candidates

### ISSUE THREAD

**Issue by zalky** [abo-abo/swiper#501]
I'm using `counsel-imenu` to navigate clojure files. The issue I'm experiencing is that in situations where there are multiple functions with the same name (this happens a lot with clojure multimethods), `counsel-imenu` always navigates to the first candidate no matter which one you select, even though `(imenu--make-index-alist t)` seems to return more than one candidate. For whatever reason counsel always defaults to the first.

**Comment by abo-abo** [comment]
`ivy-read` isn't suited for duplicate strings. This means that in order for this to work, the strings must be unique. I suggest looking at `clojure-semantic` instead of `imenu`.
