### ISSUE TITLE
isearch-yank-string equivalence?

### ISSUE THREAD

**Issue by futurist** [abo-abo/swiper#502]
when using isearch, there's a handy func `isearch-yank-string`, which I can push string into isearch minibuffer, can add this in swiper/ivy ?

**Comment by abo-abo** [comment]
Press <kbd>M-j</kbd>, it's all in the manual.

**Comment by futurist** [comment]
need `buffer-string-from-region`, which I've marked before trigger swiper, e.g. 2 words selected in region, then after trigger swiper, `isearch-yank-string` will push that 2 words into swiper.

**Comment by abo-abo** [comment]
Ah, that thing is <kbd>M-n</kbd>, of course: puts symbol at point or region into the minibuffer.

**Comment by futurist** [comment]
Very good thing! But I think `M-n` and `M-p` is used for next/prev keyword in `isearch`. Is there any equivalent in swiper?

**Comment by abo-abo** [comment]
> But I think M-n and M-p is used for next/prev keyword in isearch. Is there any equivalent in swiper?

I have no idea what you mean here.

**Comment by glucas** [comment]
`M-n` and `M-p` move forward and backward in the search history. I believe isearch and swiper behave the same here, except that in swiper when you go forward (`M-n`) when there are no more history entries it instead grabs the symbol/region at point. 

This is consistent with Emacs recommendations. From the manual: "If you type M-n in the minibuffer when there are no later entries in the minibuffer history (e.g., if you haven’t previously typed M-p), Emacs tries fetching from a list of default arguments: values that you are likely to enter. You can think of this as moving through the “future history” list."

**Comment by futurist** [comment]
I see, you are right.
