### ISSUE TITLE
ivy recent file?

### ISSUE THREAD

**Issue by futurist** [abo-abo/swiper#503]
I cannot leave Ido for it's storing recent file. Can ivy add this?

**Comment by abo-abo** [comment]
It's all there, just set `ivy-virtual-buffers`.

**Comment by omajid** [comment]
Would it be possible to add recent files to find-file, instead of switch-buffer? Or maybe an option to toggle that? Using `ido`, that's where I was looking for recent files.

**Comment by abo-abo** [comment]
@omajid Currently there's no plan for that. You can easily hack something up with `ivy-set-sources` though.
