### ISSUE TITLE
Strange behavior on directory creation

### ISSUE THREAD

**Issue by mrkkrp** [abo-abo/swiper#504]
When I create a directory from Dired, and something beginning with name of the directory already exists, I need to press <kbd>C-q C-j</kbd> before pressing <kbd>C-j</kbd> or <kbd>C-m</kbd> to finish entering name of new directory. I've noticed recently that directories created in such a way now contain newline character at the end, at least they are displayed this way in Dired (with empty line after directory entry). Can you look into this?

**Comment by abo-abo** [comment]
<kbd>C-q C-j</kbd> means "insert literal newline". This is the default Emacs behavior.

> something beginning with name of the directory already exists

This case is handled in all completion cases by `ivy-immediate-done`, bound to both <kbd>C-M-j</kbd> and <kbd>C-u C-j</kbd>.

**Comment by mrkkrp** [comment]
Oh, I remember now that one should use <kbd>C-u C-j</kbd> with Iny. Somehow I thought that <kbd>C-q C-j</kbd> has this effect after some time of not using <kbd>C-u C-j</kbd>. Thanks for your response, closing!

**Comment by mrkkrp** [comment]
BTW, is there an option to disable Ivy for some commands? For example it does not make sense to use it with 'dired-create-directory`, because we just cannot create directory with name that is already is use.

I used to have a hook that temprorily bound `read-file-name-function` to `read-file-name-default` to selectively disable IDO, but it seems Ivy works differently and it does not touch `read-file-name-function` at all.

**Comment by abo-abo** [comment]
It uses only `completing-read-function`. It's possible to disable it that way.

**Comment by mrkkrp** [comment]
Great, that works!
