### ISSUE TITLE
different "other window" keys in `counsel-find-file` and `ivy-switch-buffer`

### ISSUE THREAD

**Issue by ericdanan** [abo-abo/swiper#505]
By default, the former uses <kbd>f</kbd> whereas the latter uses <kbd>j</kbd>.

Is there is a particular reason for that?

See https://github.com/ericdanan/counsel-projectile/pull/3

Thanks

**Comment by abo-abo** [comment]
Thanks, I've made both <kbd>M-o j</kbd> now.

**Comment by ericdanan** [comment]
OK, I will use the same key in `counsel-projectile` then.
