### ISSUE TITLE
Add separator marks in counsel-yank-pop

### ISSUE THREAD

**Issue by swarnendubiswas** [abo-abo/swiper#507]
`counsel-yank-pop` shows all history entries in subsequent new lines. This might make it difficult to distinguish different entries from multiline entries. Therefore, it might be good to add an option (or make it the default) to provide a visual demarcator or separator (e.g., multiple blank lines or dashed lines) similar to browse-kill-ring or helm-show-kill-ring.

**Comment by manuel-uberti** [comment]
I'd prefer to have it optional, because current candidate is already highlighted on my setup so I just need to `C-p` and `C-n` to  "get" multiline candidates properly.

**Comment by swarnendubiswas** [comment]
Okay, so we now can get this done with `counsel-yank-pop-separator`. Thanks @tumashu and @abo-abo.
