### ISSUE TITLE
counsel-up-directory

### ISSUE THREAD

**Issue by jtamagnan** [abo-abo/swiper#508]
Hi, I was wondering about what you thought about a minor change to `counsel-up-directory`. When using `counsel-find-file` I often want to open a file from the same directory as the last file I opened. To do that I hit `M-p`. I then try to hit `C-<backspace>`, in hopes of clearing the input of the currently selected file, but instead it sends me back a directory. I know I can hit `C-k` but that is less intuitive because I'm already at the end of the string. Anyways I feel like `counsel-up-directory` should work differently if `ivy-text` is not empty. It should either clear the whole string or delete the last word, as it does in any other ivy completion session.

Hopefully what I mean is clear, I can try to rephrase otherwise. I would also be willing to make the change myself and push it if you would be willing to accept it. I have filled out the fsf paperwork.

**Comment by abo-abo** [comment]
> Anyways I feel like counsel-up-directory should work differently if ivy-text is not empty.

The main (and I think the only) function of this command is going up directory when `ivy-text` is not empty.  Otherwise, you could just press <kbd>DEL</kbd> to go up directory.

And like you said, there's already <kbd>C-k</kbd>. I don't want <kbd>C-DEL</kbd> to be simply an alias for <kbd>C-k</kbd>.

**Comment by abo-abo** [comment]
If you want, add a boolean defcustom that decides if `counsel-up-directory` will erase in case `ivy-text` isn't empty.

**Comment by manuel-uberti** [comment]
Correct me if I'm wrong, but <kbd>M-DEL</kbd> should do what you're looking for.

**Comment by jtamagnan** [comment]
Instead of making the change for all I made the change to my config file which is fine for me. I removed `counsel-up-directory` from the keymap to have it be like other ivy sessions.

@manuel-uberti I think that <kbd> M-DEL</kbd> only deletes to the previous period
