### ISSUE TITLE
ivy cause read-file-name bug

### ISSUE THREAD

**Issue by zilongshanren** [abo-abo/swiper#514]
when call `read-file-name` without a `chosen` parameter, ivy still use `default-directory` as the input which is weird

**Comment by abo-abo** [comment]
A minimal example, please.

**Comment by zilongshanren** [comment]
At first, turn ivy-mode on, open any file and press `M-S-:` to execute the command `(read-file-name "~/.emacs.d")`,

it will list the current file's directory rather than the files in "~/.emacs.d" directory.

**Comment by zilongshanren** [comment]
@abo-abo 
If I give a extra 2nd parameter to the `read-file-name` function, it will give me the correct file lists.

**Comment by abo-abo** [comment]
That's because the first arg is `prompt` and the second is `dir`.
This works:

```elisp
(read-file-name "test: " "~/.emacs.d")
```

**Comment by zilongshanren** [comment]
@abo-abo 
sorry,  my mistake, `(read-file-name "test: " "~/.emacs.d")` is still not working...

**Comment by zilongshanren** [comment]
@abo-abo  if I call `(read-file-name "test: " "~/.emacs.d")` in scratch buffer , then the result is correct, but it's not working when I open any files in my disk...

**Comment by abo-abo** [comment]
Read the doc of `read-file-name`:

> DIR is the directory to use for completing relative file names.
> It should be an absolute directory name, or nil (which means the
> current buffer's value of `default-directory').

You must use an absolute path.

**Comment by zilongshanren** [comment]
@abo-abo 
```elisp
(read-file-name "Load perspectives from a file: "
                                       "/Users/guanghui/.emacs.d/")
```

`/Users/guanghui` is my HOME directory, am I wrong here?

Thanks.

**Comment by abo-abo** [comment]
Please check.

**Comment by zilongshanren** [comment]
@abo-abo  👍  thanks, problem solved.
