### ISSUE TITLE
ivy-partial: text properties should be removed in some context

### ISSUE THREAD

**Issue by qizhihere** [abo-abo/swiper#517]
I notice that `ivy-partial` keeps text's properties after completion. It will make the inserted text look strange in some circumstances.

For example:

![x](http://7sbq2s.com1.z0.glb.clouddn.com/img-links/github/ivy-partial-issue-0.png)

It might be better to toggle preserving completion text properties by a variable so that we can inhibit it in some contexts such as `find-file`.

**Comment by abo-abo** [comment]
Thanks, please test.
