### ISSUE TITLE
Counsel Bookmark

### ISSUE THREAD

**Issue by rgtk** [abo-abo/swiper#519]
Emacs bookmarks can be really handy. With `counsel-ag`/`counsel-git-grep`, swiper and it's friends can completly replace projectile in my workflow. Although, ivy provides `ivy-use-virtual-buffers` custom with ability to add bookmarks to `ivy-switch-buffer`, I find it unpractical for users who have a lot of bookmarks.
Having ivy interface for jumping to bookmark would be really great.

I will add it as pull request.

**Comment by manuel-uberti** [comment]
Doesn't `bookmark-jump` already use Ivy when `ivy-mode` is on?

**Comment by rgtk** [comment]
I tried and it didn't. Installed using package.el, without any further configuration.

**Comment by manuel-uberti** [comment]
Let's wait for @abo-abo here, but this is working for me:

- `emacs -Q`
- `M-x package-initialize`
- `M-x ivy-mode`
- <kbd>C-x r b</kbd>

![2016-05-25-092603_677x557_scrot](https://cloud.githubusercontent.com/assets/8199224/15531410/8e3fc7ce-225a-11e6-82c4-5cf8055f79fc.png)

**Comment by abo-abo** [comment]
@manuel-uberti 

> Doesn't bookmark-jump already use Ivy when ivy-mode is on? It does for me, at least. :)

Although this works, the following doesn't:

- ivy-next-line-and-call
- ivy-resume
- ivy-occur

All of the above work with `counsel-bookmark`, since it uses `(ivy-read ... :action ...)`.

**Comment by manuel-uberti** [comment]
Thanks for the explanation. Time to rebind `bookmark-jump` then. :)
