### ISSUE TITLE
No prompt with perspective switch

### ISSUE THREAD

**Issue by nlamirault** [abo-abo/swiper#52]
When i make a <kbd>C-x x s</kbd> (persp-switch), i've got this prompt : 

```el
Perspective name: [main]
```

Using ivy-mode, i haven't got any prompt.

**Comment by abo-abo** [comment]
Can you please try again with the latest code.
I think I fixed this earlier today because I had the same problem with org-mode capture.

**Comment by nlamirault** [comment]
With last version, i've got a prompt : 

```el
Perspective name: 
main
```

I try to enter a new name "foo". Then i've got another time the same prompt.
Then i enter again the new name : "foo".
Now a new perspective is created with name "nil".

**Comment by abo-abo** [comment]
Can't reproduce on 24.5.2. Everything works fine. What's your Emacs version?

**Comment by abo-abo** [comment]
The issue is a bit dated, and I'm pretty sure it's fixed.  Feel free to reopen if you're still getting problems.

**Comment by nlamirault** [comment]
Ok. I will try tout update my Emacs version. Thanks
