### ISSUE TITLE
swiper and gforth.el

### ISSUE THREAD

**Issue by arkrost** [abo-abo/swiper#526]
Hi!

I have problems with [forth-mode](https://github.com/forthy42/gforth/blob/master/gforth.el). It turned out that i use search using `swiper` in *forth-mode* code highlighting get broken. 

I'm not sure if it's swiper issue because after calling `(run-hook 'forth-mode-hook)` highlighting works properly.

I would appreciate if you can point what goes wrong.

**Comment by abo-abo** [comment]
Please check if this fixes it.

**Comment by arkrost** [comment]
Yeah, it works fine for me. But please add `forth-block-mode` to swiper-font-lock-exclude.
