### ISSUE TITLE
Weird interaction with ivy-mode and js-mode

### ISSUE THREAD

**Issue by bsuh** [abo-abo/swiper#528]
Here's a video of it https://youtu.be/1l9FWjP6ass

1) Download this Javascript file https://code.jquery.com/jquery-1.12.4.js
2) Install ivy
3) Enable ivy-mode
4) Open jquery file
5) Start a Lisp eval and type in "(setq-default js-indent-le", press TAB, it completes correctly to js-indent-level
6) Scroll down
7) Start a Lisp eval and type in "(setq-default js-indent-le", press TAB, it completes incorrectly to js-indent-lejs-indent-level

**Comment by abo-abo** [comment]
I can't reproduce on Emacs 25. What's your Emacs version?

**Comment by bsuh** [comment]
```
GNU Emacs 24.5.1 (x86_64-apple-darwin15.4.0, Carbon Version 157 AppKit 1404.46)
 of 2016-05-08 on Brians-MacBook-Pro.local
```

**Comment by abo-abo** [comment]
Can you reliably reproduce this bug each time? I recall getting it a few times on extremely slow hardware (shared remote system, huge ping). But I don't remember this happening on any reasonably fast system.

**Comment by bsuh** [comment]
![image](https://cloud.githubusercontent.com/assets/47231/15753544/7195d218-28a8-11e6-9a5b-da5f7bb21252.png)

I reproduce it 100% after scrolling. The file is on my local filesystem.

**Comment by bsuh** [comment]
Interestingly enough I can't reproduce on emacs 24.5.1 running on Ubuntu.

**Comment by abo-abo** [comment]
Thanks for the detailed report. For some reason, I could not reproduce it on my config. But with `emacs-24.5 -Q` indeed I was able to reproduce. Please check.

**Comment by bsuh** [comment]
It is working correctly for me now. Thanks for the quick fix. :)

**Comment by thwg** [comment]
The fix for this issue removes the prefix on completion:

In `M-x shell`:

```
$ tree
.
└── directory
    └── file

2 directories, 1 file
$ ls directory/fi<TAB>    (->)
$ ls file
```

I'm not able to reproduce the original issue here, so not sure what a better fix might be.

**Comment by abo-abo** [comment]
@thwg, thanks. I'm reverting the previous commit.

@bsuh, please test the new fix.

**Comment by bsuh** [comment]
@abo-abo The new fix is still working correctly for me.

**Comment by bsuh** [comment]
@abo-abo Ran into another bug now.

1) Open emacs
2) Start Lisp eval and type in `(setq-local tab-indent` and then press TAB
3) Completes to `(setqtab-always-indent`
