### ISSUE TITLE
Symbol's function definetion is void: string-trim-right

### ISSUE THREAD

**Issue by tadegenban** [abo-abo/swiper#529]
I upgrate from 0.7 to 0.8 today and got this when use 'ivy-occur' in a 'swiper' search buffer

**Comment by syohex** [comment]
NOTE: It is defined in `subr-x.el` which was introduced at Emacs 24.4. You can avoid this issue by load it(ex `(require 'subr-x)`) if you use Emacs 24.4 or higher versions.

**Comment by tadegenban** [comment]
(require 'subr-x)
this worked for me, thanks @syohex

**Comment by abo-abo** [comment]
Thank.

**Comment by basil-conto** [comment]
Note that all definitions in `subr-x` are either macros or inline functions, so you can write `(eval-when-compile (require 'subr-x))` rather than `(require 'subr-x)`.
