### ISSUE TITLE
counsel-grep-or-swiper can't show the correct match line

### ISSUE THREAD

**Issue by tadegenban** [abo-abo/swiper#530]
update from 0.7 to 0.8,and using the suggested new command 'counsel-grep-or-swiper for big file
it's really fast.
my problem is, after I type some keywords in the mini-buffer, it'll highlight the matched line in the text buffer(as swiper do), but if I type 'Enter' or 'Up', 'Down' key to explore the matched result, the highlight line will go back to the first line of the buffer and not indicate the matched line. 
hope my description is clear

**Comment by abo-abo** [comment]
It seems like the command doesn't work at all. Can you reproduce with `emacs -Q`?

**Comment by tadegenban** [comment]
after a few time's debug, I found the root cause is there's one line in my conig

>  (global-pointback-mode)

if I comment it out, it'll worked fine

**Comment by abo-abo** [comment]
OK, then the issue can be closed.
