### ISSUE TITLE
quick jump to bookmarks in counsel-find-file?

### ISSUE THREAD

**Issue by zeltak** [abo-abo/swiper#531]
Hi 

i thought it would be cool to have an option in counsel-find-file to quick jump to either the emacs bookmarks or per-defined bookmarks (maybe from a hydra?). is that possible in anyway? if not what do you think of the idea?

thx alot!

Z

**Comment by abo-abo** [comment]
This can be configured in a user config:

    (ivy-set-actions
     'counsel-find-file
     '(("j" find-file-other-window "other window")
       ("b" (lambda (_) (interactive) (counsel-bookmark)) "bookmark")))
       
Press <kbd>M-o b</kbd> to get completion for bookmarks. I don't think it's useful to have the above code in this repository.

**Comment by zeltak** [comment]
thx for the quick reply abo-abo!

i think i may have not explained particularly well :) 

what i would want is not to launch the bookmarked file/dired buffer from within the counsel-find-file session (which works well with the code you showed above) but to change the current counsel-find-file path to a bookmarked path/predefined path. 

For example when i launch counsel-find-file at ~/Downloads but want to open a file at ``/media/NAS/folder1/folder2/subfolfer2/`` i need to traverse the whole file system. if i could within counsel-find-file quick jump to ``/media/NAS/folder1/folder2/subfolfer2/`` in a few key stokes i think that could be cool. Does that make any sense :) perhaps there is already a clever way to do so?

best

Z

**Comment by zeltak** [comment]
any thoughts on this :D?

thx

Z

**Comment by abo-abo** [comment]
Please test. The new key binding is <kbd>M-o b</kbd>. Offers you the directories of bookmarks and recentf.

**Comment by glucas** [comment]
Works for me - this is pretty convenient!

**Comment by zeltak** [comment]
thx so much, i just tested  it and works great! very handy :dancer: 
thx again so much

Z
