### ISSUE TITLE
counsel-find-file: use left-right to traverse directories (like 'diredp-up-directory-reuse-dir-buffer)

### ISSUE THREAD

**Issue by zeltak** [abo-abo/swiper#532]
Hi again 

I was wondering if one could use keybinds for left/right to move forward/backwards in directories when in counsel-find file mode.
I do so in dired with great success with these commands:

```
(define-key dired-mode-map (kbd "<left>") 'diredp-up-directory-reuse-dir-buffer )
(define-key dired-mode-map (kbd "<right>") 'diredp-find-file-reuse-dir-buffer )
```

and thought it could work great in counsel-find-file mode

thx!

Z

**Comment by zeltak** [comment]
hmmm what i ended up doing is using a bind like this

```
(define-key ivy-minibuffer-map (kbd "<left>") 'ivy-backward-delete-char)
```

is that a bad idea ;-)

**Comment by abo-abo** [comment]
This should be better:

```elisp
(define-key ivy-minibuffer-map (kbd "<left>") 'counsel-up-directory)
(define-key ivy-minibuffer-map (kbd "<right>") 'ivy-alt-done)
```

**Comment by zeltak** [comment]
perfect!

thx so much!

**Comment by mihaiolteanu** [comment]
I think that should be:

`(define-key counsel-find-file-map (kbd "<left>") 'counsel-up-directory)`
`(define-key counsel-find-file-map (kbd "<right>") 'ivy-alt-done)`

otherwise `counsel-up-directory` can be called even in scenarios which wouldn't make sense (i.e. it would give an error).

**Comment by abo-abo** [comment]
@mihaiolteanu You're right, thanks for the correction.

**Comment by zeltak** [comment]
hmm thx but for me using that code as opposed to what @abo-abo posted makes entering a directory to show now files..is that normal?
