### ISSUE TITLE
auto set swiper-map after swiper is loaded

### ISSUE THREAD

**Issue by jamieabc** [abo-abo/swiper#534]
Hi, swiper is really a awesome package.

Currently I want to have a function that can auto search word under cursor, and I found a code snippet from internet that will set swiper-map for `C-.` and 'M-.` as follows:

`
(define-key swiper-map (kbd "C-.")
   (lambda () (interactive) (insert (format "\\<%s\\>" (with-ivy-window (thing-at-point 'symbol))))))
 (define-key swiper-map (kbd "M-.")
   (lambda () (interactive) (insert (format "\\<%s\\>" (with-ivy-window (thing-at-point 'word))))))
`

However, since I only start swiper when used, so at when emacs start, `swiper-map` is not set. My question is about how to auto set `swiper-map` when swiper is loaded?

**Comment by abo-abo** [comment]
> Hi, swiper is really a awesome package.

Thanks.
> 
> Currently I want to have a function that can auto search word under cursor, and I found a code snippet from internet that will set swiper-map for C-. and 'M-.` as follows:

Interesting, can I get a link?

> However, since I only start swiper when used, so at when emacs start, swiper-map is not set. My question is about how to auto set swiper-map when swiper is loaded?

This is the standard way of doing it in Emacs:

```elisp
(eval-after-load 'swiper
  '(progn
    (define-key swiper-map (kbd "C-.")
     (lambda ()
       (interactive)
       (insert
        (format
         "\\<%s\\>"
         (with-ivy-window
           (thing-at-point 'symbol))))))
    (define-key swiper-map (kbd "M-.")
     (lambda ()
       (interactive)
       (insert
        (format
         "\\<%s\\>"
         (with-ivy-window
           (thing-at-point 'word))))))))
```

In the above code, note two things:

- `'swiper` is the name of the feature. It matches `(provide 'swiper)` in swiper.el.
- The code needs to be quoted, i.e. `'(progn` instead of `(progn`. Otherwise, it will be called immediately at that place.

**Comment by jamieabc** [comment]
the search at point is same as yours, it's found from [here](https://www.emacswiki.org/emacs/SearchAtPoint#toc8)

thanks a lot, your code works perfectly
