### ISSUE TITLE
not able to scroll in swiper mode

### ISSUE THREAD

**Issue by jamieabc** [abo-abo/swiper#535]
As I use 'C-v' & 'M-v' in swiper mode, it has no response, no scroll up/down

**Comment by abo-abo** [comment]
Thanks, please check.

**Comment by jamieabc** [comment]
thanks a lot, it's been fixed after i update the package

**Comment by cauchycai** [comment]
Meet this issue again. My ivy is installed from melpa and the package folder is named: ivy-20170202.233

**Comment by abo-abo** [comment]
@cauchycai should work now, thanks.

**Comment by cauchycai** [comment]
@abo-abo , it works now. Thank you for the quick fix.
