### ISSUE TITLE
counsel-grep-or-swiper and compressed files

### ISSUE THREAD

**Issue by LemonBoy** [abo-abo/swiper#536]
Some packages ship the source code in form of a `.el.gz` file which gets auto-decompressed by emacs. On the other hand `counsel-grep-or-swiper` doesn't know about this and if the file's big enough tries to use grep on it, giving some disappointing results.

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by LemonBoy** [comment]
Works great, thanks for the quick response :)
