### ISSUE TITLE
Preselect previous result

### ISSUE THREAD

**Issue by ptpt** [abo-abo/swiper#538]
Just switch from smex to ivy. One feature I really miss in smex is that it can remember last selected item. For example, If I execute `M-x butterfly`, next time I press `M-x`, `butterfly` will be the first candidate, I just need to hit enter to repeat this command. This is very neat. Would be great ivy can do the same!

**Comment by manuel-uberti** [comment]
You can use smex with counsel/ivy too. If smex is installed, it is automatically used by `counsel-M-x`.

**Comment by ptpt** [comment]
Thanks @manuel-uberti it works!

Just confused with ido and smex
