### ISSUE TITLE
feeding a set of shell calls into counsel base command

### ISSUE THREAD

**Issue by drorbemet** [abo-abo/swiper#539]
I am looking for the point in counsel where a map on multiple shell calls can be inserted.
Is it already there? I remember extending counsel-locate with an additional list of results.
What would the prefered way to implement a set of counsel-x-base-commands?
Here is an example for a use case that triggered this question:
```
(defun counsel-git-grep-refs (&optional initial-input)
  "Preparation to grep a set of git refs using multiple async shell calls."
  (interactive)
  (let* ((one-ref "master")
         (multiple-refs (magit-list-refs))
         (counsel-ag-base-command
          (s-concat "git grep -i --full-name -G %s " one-ref))
         (counsel-ag-base-command-set
          (--map (s-concat "git grep -i --full-name -G %s " it)
                 multiple-refs))
         (ivy-inhibit-action t)
         (grep-result (counsel-ag initial-input))
         (ivy-inhibit-action nil))
    (with-ivy-window (insert grep-result))))

(counsel-git-grep-refs "defun")
```

Is this a case for a counsel-locate-function? It would collect and concat the set of shell-call-results. But how would it look like to concat intermediate results of multiple channels? The order of results would not be relevant at first. Maybe there is already an example for that in elisp somewhere? 
At command line I am using parallel for that.
I would like to stay in elisp for that because it's more expressive for generating the shell-commands.

**Comment by abo-abo** [comment]
Currently, it's only possible to add an unlimited amount of sync sources to either one async source, or one sync source via `ivy-set-sources`.

Your best bet right now is to join the results in the shell call. In my experience, it's a lot faster than doing it in Elisp.  See `counsel-git-grep` for some shell magic: `git-grep` doesn't support limiting the output and it's unbearably slow to pipe 1Mb of output into Emacs from any shell call, so the limiting is done using shell tools, via `head -n 200`.

**Comment by drorbemet** [comment]
Thanks for the hints. I solved this for me by generating a shell script for each call and passing it to gnu parallel.
