### ISSUE TITLE
Shortcut to select word at point

### ISSUE THREAD

**Issue by ptpt** [abo-abo/swiper#540]
The native `isearch` has a nice feature: when you want search the word at the point, you just press `C-s` followed by `C-w` (select the current word), and then you can keep pressing `C-s` to navigate. Would be great swiper can do the same thing.

**Comment by manuel-uberti** [comment]
You can just press `C-n` after you issued `M-x swiper`.

**Comment by ptpt** [comment]
Thanks for the quick reply @manuel-uberti 

My question was how to quick select the word at point (like via a shortcut C-w in isearch)

**Comment by ardpp** [comment]
Use `M-j`

**Comment by ptpt** [comment]
@ardpp Thank you! That's exactly what I need.

I should read manual more carefully

**Comment by abo-abo** [comment]
> With point on the word you're looking for, you can just press C-n after you issued M-x swiper.

*`M-n`. I've even found situations where `M-n M-j` is useful.

**Comment by ptpt** [comment]
@abo-abo Would you consider change it to `C-w`? That would make it a seamless experience for users like me switching from a long-term use of `isearch`

**Comment by abo-abo** [comment]
@ptpt, No the shortcut `C-w` is already bound to `kill-region`. Not all things about `isearch` are perfect, not everything should be copied.

For example, did you know that you can <kbd>C-x o</kbd> from `swiper`, copy something from a buffer, switch back to swiper and paste there? And vice versa. Such a simple thing doesn't work with isearch.

**Comment by manuel-uberti** [comment]
@abo-abo yep, sorry, typo. `C-n` does a different thing. And `M-n M-j` is useful too.

@ptpt tbh I like the default Swiper bindings. Can't you remap `ivy-yank-word` to `C-w`?

**Comment by ptpt** [comment]
I see.

Appreciate your work on this awesome package!

**Comment by ptpt** [comment]
@abo-abo I see.

Appreciate your work on this awesome package!
