### ISSUE TITLE
ivy-set-action

### ISSUE THREAD

**Issue by jtamagnan** [abo-abo/swiper#542]
In your [post](http://oremacs.com/2016/04/26/ivy-0.8.0/) on your website about ivy 0.8.0 you mention the following code:

``` elisp
(defun ivy-insert-action (x)
  (with-ivy-window
    (insert x)))

(ivy-set-actions
 t
 '(("I" ivy-insert-action "insert")))
```
It seems like this code has issues with a certain number of functions. For certain functions (I think the issue is functions that do not use `ivy-read`) it seems to call the default action as well as insert the selection when I type <kbd> M-o I </kbd>.

For example I have `describe-symbol` bound to <kbd> C-h o </kbd>. So if I type <kbd>C-h o M-o I </kbd> it will bring up the documentation as well as insert the symbol into the buffer. This issue also happens with projectile functions but does not happen with any of the counsel functions.

**Comment by abo-abo** [comment]
This is a limitation that I can't do anything about. Here's the gist of the difference:

```elisp
(defun foo-1 ()
  (fun1)
  (fun2 (ivy-read "test" '("a" "b"))))

(defun foo-2 ()
  (fun1)
  (ivy-read "test" '("a" "b")
            :action fun2))
```

With `foo-1` there's nothing `ivy-read` can do to avoid calling `fun2`.

On the other hand, in `foo-2`, the callback `fun2` is passed into `ivy-read`, which can decide whether to call it or call something else (a different action).

As far as I can see, there's no way to solve the problem in a straightforward way. If you want actions, use `ivy-read` with `:action`, there's no getting around that.

**Comment by jtamagnan** [comment]
That makes sense, thank you
