### ISSUE TITLE
Add support for multiple cursors to counsel-company

### ISSUE THREAD

**Issue by s-kostyaev** [abo-abo/swiper#547]
Multiple cursors are great. But with this package does not work any autocompletion. I fix it for counsel-company. I can do PR for this feature, but you can do my code better I think. This is working code:

```elisp
(defvar-local my-counsel-company-prefix nil
  "Company prefix for use counsel-company with multiple-cursors.")
(defun my-counsel-company ()
  "Complete using `company-candidates'."
  (interactive)
  (mc/enable-minor-mode 'company-mode)
  (company-cancel)
  (unless company-candidates
    (company-complete))
  (when company-point
    (setq my-counsel-company-prefix company-prefix)
    (company--fetch-candidates my-counsel-company-prefix)
    (when (looking-back company-common (line-beginning-position))
      (setq ivy-completion-beg (match-beginning 0))
      (setq ivy-completion-end (match-end 0)))
    (ivy-read "company cand: " (mapcar (lambda (x)
                                         (let ((annotation
                                                (company-call-backend 'annotation x)))
                                           (if (> (length annotation) 0)
                                               (progn
                                                 (set-text-properties
                                                  0 (length annotation)
                                                  '(face success) annotation)
                                                 (concat x "\t\t" annotation))
                                             x)))
                                       company-candidates)
              :action (lambda (x)
                        (company-cancel)
                        (ivy-completion-in-region-action
                         (replace-regexp-in-string "\t\t\.*" "" x))
                        (let
                            ((insertion (s-chop-prefix my-counsel-company-prefix
                                                       (replace-regexp-in-string "\t\t\.*" "" x))))
                          (mc/execute-command-for-all-fake-cursors
                           (lambda ()
                             (interactive)
                             (insert insertion))))))))
```

**Comment by s-kostyaev** [comment]
This code also include annotations from #523

**Comment by abo-abo** [comment]
I don't get it, what is it supposed to do with multiple-cursors? Also, I can't get the annotations to work either.

**Comment by s-kostyaev** [comment]
> what is it supposed to do with multiple-cursors?

Insert completion for all cursors.

> I can't get the annotations to work either.

Try it with irony-mode for example.

**Comment by s-kostyaev** [comment]
But there is the bug with this: https://github.com/magnars/multiple-cursors.el/issues/255

**Comment by s-kostyaev** [comment]
![mc-completion](https://cloud.githubusercontent.com/assets/8576745/15968760/f2db6fe8-2f4e-11e6-9743-d37a6342d6ff.gif)

**Comment by abo-abo** [comment]
I've added a more generic solution to `ivy-completion-in-region-action`. So <kbd>C-M-i</kbd> (`complete-symbol`) should work fine with multiple-cursors. Since `counsel-company` uses the same function, it should also work. Please test.

**Comment by s-kostyaev** [comment]
Add `(mc/enable-minor-mode 'company-mode)` at `counsel-company` begining please. `complete-symbol` work with multiple cursors but I think that more correct select candidate once and insert it for all cursors. Also `counsel-company` not work with multiple cursors even after enabling `company-mode` for mc: It insert candidate only for original cursor.

**Comment by s-kostyaev** [comment]
@abo-abo `consel-company` still broken. I can create PR with working code or create small melpa package `ivy-company` if you wontfix it.

**Comment by abo-abo** [comment]
Seems to work fine for me. Let's try with the PR. But the package is fine as well, if you prefer.
