### ISSUE TITLE
crazy idea (ill explain!.. ;-): swiper in hydra menus? :)

### ISSUE THREAD

**Issue by zeltak** [abo-abo/swiper#548]
Hi!

ok so this maybe a very specific use case for me but ill ask anyway :)

i use hydras _extensively_ :) i have many hydras that can be with ~ 60-70 entries (ie all my dired stuff).
Many time i forget which key is what and where the hint is. i always think that having swiper available to quick search in the hydra menu could be very cool. is that a)crazy? and b)possible?
use case i have a hydra with many org-agenda view. one of them is name "shopping". i can launch my org hydra>swiper>enter "shop" and voila i quickly see where the hint is and its key.
this isnt meant to be used each time you launch the hydra just when you forget the key :)
an alternative approach perhaps would be to use some special key to filter the view based on keys or something similar.

thx again 

Z

**Comment by abo-abo** [comment]
Try this code:

```elisp
(defun counsel-hydra-heads ()
  (interactive)
  (let* ((base (substring
                (prin1-to-string hydra-curr-body-fn)
                0 -4))
         (heads (eval (intern (concat base "heads"))))
         (keymap (eval (intern (concat base "keymap"))))
         (head-names
          (mapcar (lambda (x)
                    (cons
                     (if (nth 2 x)
                         (format "%S [%s]" (nth 1 x) (nth 2 x))
                       (format "%S" (nth 1 x)))
                     (lookup-key keymap (kbd (nth 0 x)))))
                  heads)))
    (ivy-read "head: " head-names
              :action #'call-interactively)
    (hydra-keyboard-quit)))
(global-set-key (kbd "C-M-y") 'counsel-hydra-heads)
```

**Comment by zeltak** [comment]
very cool thx!

any chance the actual hydra key can be shown in the counsel list? right now i think the name and function description is shown

best

z

**Comment by abo-abo** [comment]
See my edit.

**Comment by zeltak** [comment]
thx so much perfect!

**Comment by zeltak** [comment]
smallish bug i found today, when running ```counsel-hydra-heads``` and choosing a hydra as opposed to an emacs function it seems to do nothing. 

example 2 scenarios in config:

```
( "9" hydra-window-main/body ) ; this dosent work
("\\" helm-mini ) ;works

````

thx

Z

**Comment by abo-abo** [comment]
The idea is that `counsel-hydra-heads` will hide the current (last) hydra. So your selected hydra gets hidden immediately.
But if I remove the hiding, it won't work for regular functions as well.

**Comment by zeltak** [comment]
i see no big deal :)
