### ISSUE TITLE
Ivy incompatible with rgrep

### ISSUE THREAD

**Issue by tsdh** [abo-abo/swiper#55]
`rgrep` doesn't work with `ivy-mode` enabled.  The problem is that `rgrep` queries for the globbing pattern (e.g., `*.el`) using file completion (concretely, it does `(completing-read prompt 'read-file-name-internal ...)`).  Thus, `ivy` inserts the path of the current directory at the prompt, and there is no way to delete it completely, i.e., the `/` is always there.  Thus the globbing pattern will always be `<path><glob-pattern>` where the path is at minimum `/`.

**Comment by abo-abo** [comment]
Are you using the latest version? I've fixed this issue earlier today.

**Comment by tsdh** [comment]
I use 20150422.858 which is the latest available on MELPA.  I'll try again tomorrow and report back.

**Comment by tsdh** [comment]
No upgrades available from MELPA so I guess that's the most recent version.

Hm, now testing with `emacs -Q`.  Oh, indeed, there I can delete also the initial `~/` from the `Search for "foo" in files (default all): ` prompt although I get two errors when doing so:

```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  file-name-all-completions("" nil)
  completion-file-name-table("" nil t)
  all-completions("" completion-file-name-table nil)
  completion--file-name-table("" nil t)
  complete-with-action(t completion--file-name-table "" nil)
  #[257 "\303\302\300\301$\207" ["" nil t complete-with-action] 6 "\n\n(fn TABLE)"](completion--file-name-table)
  completion--some(#[257 "\303\302\300\301$\207" ["" nil t complete-with-action] 6 "\n\n(fn TABLE)"] (completion--embedded-envvar-table completion--file-name-table))
  read-file-name-internal("" nil t)
  all-completions("" read-file-name-internal)
  ivy--sorted-files(nil)
  ivy--cd(nil)
  ivy-backward-delete-char()
  funcall-interactively(ivy-backward-delete-char)
  call-interactively(ivy-backward-delete-char nil nil)
  command-execute(ivy-backward-delete-char)
  read-from-minibuffer("Search for \"foo\" in files (default all): " nil (keymap keymap (22 . ivy-scroll-up-command) (7 . minibuffer-keyboard-quit) (right . ivy-end-of-buffer) (left . ivy-beginning-of-buffer) (27 keymap (113 . ivy-toggle-regexp-quote) (16 . ivy-previous-line-and-call) (14 . ivy-next-line-and-call) (118 . ivy-scroll-down-command) (112 . ivy-previous-history-element) (110 . ivy-next-history-element) (62 . ivy-end-of-buffer) (60 . ivy-beginning-of-buffer)) (127 . ivy-backward-delete-char) (32 . self-insert-command) (18 . ivy-previous-line-or-history) (19 . ivy-next-line-or-history) (up . ivy-previous-line) (down . ivy-next-line) (16 . ivy-previous-line) (14 . ivy-next-line) (10 . ivy-alt-done) (13 . ivy-done)) nil grep-files-history)
  ivy-read("Search for \"foo\" in files (default all): " read-file-name-internal :predicate nil :require-match nil :initial-input nil :preselect "all" :history grep-files-history :keymap nil :sort t)
  ivy-completing-read("Search for \"foo\" in files (default all): " read-file-name-internal nil nil nil grep-files-history ("all" "el" "ch" "c" "cc" "cchh" "hh" "h" "l" "m" "tex" "texi" "asm") nil)
  completing-read("Search for \"foo\" in files (default all): " read-file-name-internal nil nil nil grep-files-history ("all" "el" "ch" "c" "cc" "cchh" "hh" "h" "l" "m" "tex" "texi" "asm"))
  grep-read-files("foo")
  byte-code("\304 \210\203	\305\232\203\306\307\310\211\311%C\207\n\204\312\313!\207\314 \315!\316\317\310\320$	\321\232F\207" [grep-find-command current-prefix-arg grep-find-template default-directory grep-compute-defaults (16) read-from-minibuffer "Run: " nil grep-find-history error "grep.el: No `grep-find-template' available" grep-read-regexp grep-read-files read-directory-name "Base directory: " t (4)] 8)
  call-interactively(rgrep record nil)
  command-execute(rgrep record)
  execute-extended-command(nil "rgrep" #("rgr\nautoarg-kp-mode\nautoarg-mode\nchange-log-merge\ncomint-insert-previous-argument\ndebbugs-org\ndebbugs-org-bugs\ndebbugs-org-mode\ndebbugs-org-search\ndecrease-left-margin" 3 4 (read-only nil) 4 19 (face (ivy-current-match) read-only nil) 19 167 (read-only nil)))
  funcall-interactively(execute-extended-command nil "rgrep" #("rgr\nautoarg-kp-mode\nautoarg-mode\nchange-log-merge\ncomint-insert-previous-argument\ndebbugs-org\ndebbugs-org-bugs\ndebbugs-org-mode\ndebbugs-org-search\ndecrease-left-margin" 3 4 (read-only nil) 4 19 (face (ivy-current-match) read-only nil) 19 167 (read-only nil)))
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)
```

and then when I continue with `c` in the debugger, I get

```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  signal(wrong-type-argument (stringp nil))
  completion--some(#[257 "\303\302\300\301$\207" ["" nil t complete-with-action] 6 "\n\n(fn TABLE)"] (completion--embedded-envvar-table completion--file-name-table))
  read-file-name-internal("" nil t)
  all-completions("" read-file-name-internal)
  ivy--sorted-files(nil)
  ivy--cd(nil)
  ivy-backward-delete-char()
  funcall-interactively(ivy-backward-delete-char)
  call-interactively(ivy-backward-delete-char nil nil)
  command-execute(ivy-backward-delete-char)
  read-from-minibuffer("Search for \"foo\" in files (default all): " nil (keymap keymap (22 . ivy-scroll-up-command) (7 . minibuffer-keyboard-quit) (right . ivy-end-of-buffer) (left . ivy-beginning-of-buffer) (27 keymap (113 . ivy-toggle-regexp-quote) (16 . ivy-previous-line-and-call) (14 . ivy-next-line-and-call) (118 . ivy-scroll-down-command) (112 . ivy-previous-history-element) (110 . ivy-next-history-element) (62 . ivy-end-of-buffer) (60 . ivy-beginning-of-buffer)) (127 . ivy-backward-delete-char) (32 . self-insert-command) (18 . ivy-previous-line-or-history) (19 . ivy-next-line-or-history) (up . ivy-previous-line) (down . ivy-next-line) (16 . ivy-previous-line) (14 . ivy-next-line) (10 . ivy-alt-done) (13 . ivy-done)) nil grep-files-history)
  ivy-read("Search for \"foo\" in files (default all): " read-file-name-internal :predicate nil :require-match nil :initial-input nil :preselect "all" :history grep-files-history :keymap nil :sort t)
  ivy-completing-read("Search for \"foo\" in files (default all): " read-file-name-internal nil nil nil grep-files-history ("all" "el" "ch" "c" "cc" "cchh" "hh" "h" "l" "m" "tex" "texi" "asm") nil)
  completing-read("Search for \"foo\" in files (default all): " read-file-name-internal nil nil nil grep-files-history ("all" "el" "ch" "c" "cc" "cchh" "hh" "h" "l" "m" "tex" "texi" "asm"))
  grep-read-files("foo")
  byte-code("\304 \210\203	\305\232\203\306\307\310\211\311%C\207\n\204\312\313!\207\314 \315!\316\317\310\320$	\321\232F\207" [grep-find-command current-prefix-arg grep-find-template default-directory grep-compute-defaults (16) read-from-minibuffer "Run: " nil grep-find-history error "grep.el: No `grep-find-template' available" grep-read-regexp grep-read-files read-directory-name "Base directory: " t (4)] 8)
  call-interactively(rgrep record nil)
  command-execute(rgrep record)
  execute-extended-command(nil "rgrep" #("rgr\nautoarg-kp-mode\nautoarg-mode\nchange-log-merge\ncomint-insert-previous-argument\ndebbugs-org\ndebbugs-org-bugs\ndebbugs-org-mode\ndebbugs-org-search\ndecrease-left-margin" 3 4 (read-only nil) 4 19 (face (ivy-current-match) read-only nil) 19 167 (read-only nil)))
  funcall-interactively(execute-extended-command nil "rgrep" #("rgr\nautoarg-kp-mode\nautoarg-mode\nchange-log-merge\ncomint-insert-previous-argument\ndebbugs-org\ndebbugs-org-bugs\ndebbugs-org-mode\ndebbugs-org-search\ndecrease-left-margin" 3 4 (read-only nil) 4 19 (face (ivy-current-match) read-only nil) 19 167 (read-only nil)))
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)
```

and then continuing again, the input is indeed cleared so that I can state my input pattern without leading stuff.

I have to figure out what prevents that in my configured emacs.  One notable difference between `emacs` and `emacs -Q` is that `DEL` when the current input is `~/` behaves differently:

  - with my configured emacs, I get the errors as above and then the empty input

  - with `emacs -Q` the first `DEL` changes the input to `/home/`, the next `DEL` changes it to `/`, and then any additional `DEL` doesn't do anything anymore.  There are also no errors.

**Comment by tsdh** [comment]
This is really strange.  With `emacs -Q` I get the behavior described above.  `C-h k DEL` when in ivy completion tells me that this is bound to `ivy-backward-delete-char`.  As soon as I edebug that function, I get the very same behavior as I get in my configured emacs, i.e., repeated `DEL` in file completion gives `~/`, `/home/`, and then `/` which cannot be deleted.

How can edebugging a function change its behavior?  The only thing I can imagine is some timing stuff but I don't see how that code requires any specific timing...

**Comment by tsdh** [comment]
By the way, when looking at `ivy-backward-delete-char` the behavior I get when edebugging or in my configured emacs is actually the behavior that conforms with its code.  I have no clue what's wrong with `emacs -Q`, `M-x package-initialize`, `M-x ivy-mode`.

Ah, I found it!  When a non-byte-compiled version of `ivy-backward-delete-char` is called, I get the `emacs -Q` behavior (I had modified ivy.el a bit and thus the el was newer than the elc.  emacs -Q prefers the elc whereas I've taught my normal emacs to prefer whatever is newer).  With a byte-compiled version, I get the edebug behavior.  Probably some dynamic vs. lexical binding issue?

**Comment by abo-abo** [comment]
Please check if this would fix it.

**Comment by tsdh** [comment]
No, I get into the (zerop ivy--length) case when I delete everything except for the undeletable /, and I get into the t case when I don't delete everything. And the first cond test assures (string= ivy-text "") so (string-match "\\*" ivy-text) in the same cond clause can never succeed.

BTW, I'm not sure what you are trying to do. But isn't the right fix to allow that I can delete the complete initial input, eg, when with a file prompt I get initially ~/.emacs.d/, shouldn't I be allowed to delete everything of that? The current definition of ivy-delete-backward-char' ensures that when the current dir is/` I'll stay there, or rather the code cds from / to / again infinitely.

BTW2, can you reproduce the different behaviors when running from byte-compiled code versus interpreted code? That seems worth its own investigation especially it seems the code works only as intended in the interpreted case, and if you install from MELPA you'll run from byte-compiled code.

**Comment by abo-abo** [comment]
> No, I get into the (zerop ivy--length) case when I delete everything except for the undeletable /, and I get into the t case when I don't delete everything. And the first cond test assures (string= ivy-text "") so (string-match "\*" ivy-text) in the same cond clause can never succeed.

I don't understand why you need to delete stuff. For the part when you can enter a glob, just enter it in the current dir.
You'll be prompted for a dir by rgrep later.

> BTW2, can you reproduce the different behaviors when running from byte-compiled code versus interpreted code? That seems worth its own investigation especially it seems the code works only as intended in the interpreted case, and if you install from MELPA you'll run from byte-compiled code.

There's too much stuff in the thread. Can you state a recipe to get a bug?

**Comment by tsdh** [comment]
In a freshly started emacs with ivy enabled, I do `M-x rgrep RET foo RET *.el RET ~/Repos/el/emacs/lisp/` in *scratch* where the current directory is `~/`.  Then the *grep* output buffer shows:

```
-*- mode: grep; default-directory: "~/Repos/el/emacs/lisp/" -*-
Grep started at Thu Apr 23 11:50:38

find . -type d \( -path \*/SCCS -o -path \*/RCS -o -path \*/CVS -o -path \*/MCVS -o -path \*/.src -o -path \*/.svn -o -path \*/.git -o -path \*/.hg -o -path \*/.bzr -o -path \*/_MTN -o -path \*/_darcs -o -path \*/\{arch\} \) -prune -o \! -type d \( -name .\#\* -o -name \*.log -o -name \*.out -o -name \*.synctex.gz -o -name \*.hi -o -name \*.o -o -name \*\~ -o -name \*.bin -o -name \*.lbin -o -name \*.so -o -name \*.a -o -name \*.ln -o -name \*.blg -o -name \*.bbl -o -name \*.elc -o -name \*.lof -o -name \*.glo -o -name \*.idx -o -name \*.lot -o -name \*.fmt -o -name \*.tfm -o -name \*.class -o -name \*.fas -o -name \*.lib -o -name \*.mem -o -name \*.x86f -o -name \*.sparcf -o -name \*.dfsl -o -name \*.pfsl -o -name \*.d64fsl -o -name \*.p64fsl -o -name \*.lx64fsl -o -name \*.lx32fsl -o -name \*.dx64fsl -o -name \*.dx32fsl -o -name \*.fx64fsl -o -name \*.fx32fsl -o -name \*.sx64fsl -o -name \*.sx32fsl -o -name \*.wx64fsl -o -name \*.wx32fsl -o -name \*.fasl -o -name \*.ufsl -o -name \*.fsl -o -name \*.dxl -o -name \*.lo -o -name \*.la -o -name \*.gmo -o -name \*.mo -o -name \*.toc -o -name \*.aux -o -name \*.cp -o -name \*.fn -o -name \*.ky -o -name \*.pg -o -name \*.tp -o -name \*.vr -o -name \*.cps -o -name \*.fns -o -name \*.kys -o -name \*.pgs -o -name \*.tps -o -name \*.vrs -o -name \*.pyc -o -name \*.pyo \) -prune -o  -type f \( -iname /home/horn/\*.el \) -exec grep -i --color -nH -e foo {} +
find: warning: Unix filenames usually don't contain slashes (though pathnames do).  That means that '-iname `/home/horn/*.el'' will probably evaluate to false all the time on this system.  You might find the '-wholename' test more useful, or perhaps '-samefile'.  Alternatively, if you are using GNU grep, you could use 'find ... -print0 | grep -FzZ `/home/horn/*.el''.

Grep finished (matches found) at Thu Apr 23 11:50:38
```

So you see, `/home/horn/*.el` has been passed as grep pattern.  At the prompt, it looked like `~/*.el` where `~/` was the initial input.

And yes, I'll open another issue for the byte-compile stuff.

**Comment by tsdh** [comment]
The other issue is #57 now.

**Comment by abo-abo** [comment]
> So you see, /home/horn/*.el has been passed as grep pattern. At the prompt, it looked like ~/*.el where ~/ was the initial input.
> 
> And yes, I'll open another issue for the byte-compile stuff.

OK, I'm getting no error because I use <kbd>C-j</kbd> instead of <kbd>RET</kbd> in your recipe.
If I use <kbd>RET</kbd> though, the error occurs.

**Comment by tsdh** [comment]
When I use <kbd>C-j</kbd> to confirm the grep file pattern, grep still searches with `/home/horn/\*.el`.

**Comment by abo-abo** [comment]
The behavior with <kbd>C-j</kbd> is strange, since it just forwards to <kbd>C-m</kbd> in that case.
I don't know why it worked.

Anyway, try the new update.

**Comment by tsdh** [comment]
@abo-abo It works at least for `*.el` or `d*.el` with `rgrep`.  But note that there doesn't need to be a `*` in globbing patterns.  I could also specify `?.el` (matches any lisp file whose basename is just one char long) or `[a-zA-Z][a-zA-Z].el` (matches lisp files whose basename is 2 alphabetic chars long).

In addition, **now we have a new bug!**  Now you cannot find files containing an asterisk anymore except they are in the current directory.  Example:

  1. My current buffer is visiting `/home/horn/.emacs.d/elpa/swiper-20150423.413/ivy.el`
  2. `C-x C-f DEL test*.el RET`

Now `buffer-file-name` in the new `test*.el` buffer is `/home/horn/.emacs.d/elpa/swiper-20150423.413/test*.el` whereas I expect it to be `/home/horn/.emacs.d/elpa/test*.el` because the `DEL` above changed directory to `/home/horn/.emacs.d/elpa/`.

Hm, now I tried `ido-mode` plus `ido-everywhere` because I suspected that this would have similar issues with `rgrep`.  However, when using that, the globbing pattern is not queried with ido-completion but the base directory is.

Ah, I see why that is.  ido sets only `read-file-name-function` and `read-buffer-function` to its own functions whereas you set the more general `completing-read-function`.

Honestly, I don't see how to get that right.  IMHO, you should remove all these fiddly heuristics about what a read file name might actually mean and simply provide a way to delete the complete initial input from the file prompt.  As said, right now you can only delete until there's only an undeletable `/`  left.  Another `DEL` should delete that, too.  And a command `ivy-clear-input` with a nice binding would help in such scenarios like `rgrep`, too.

**Comment by abo-abo** [comment]
There already is a way to do this. Just type <kbd>C-u C-j</kbd> to exit with the current input ignoring candidates.

**Comment by tsdh** [comment]
Indeed, that does work. I've now bound that to <kbd>C-return</kbd> so that it's more convenient to type.

Problem solved!  But I'd still suggest you delete that heuristic for glob recognition so that one can handle files whose name really contains a `*` again.

**Comment by baerrach** [comment]
@tsdh how did you bind this to <kbd>C-return</kbd>?

The steps to rgrep are
1. Search for
2. in files matching wildcard
3. Base Directory

If I want to search all files in step 2 I use `*` but that will have selected the default glob (normally `*.(file-name-extension (buffer-name))`)

I need to use <kbd>C-u C-j</kbd> to ignore candidates.

Is there an easier way to tell get rgrep and ivy to always ignore candidates?

**Comment by winny-** [comment]
@baerrach 

This works, but only in graphical mode, [because of terminal emulator limitations](https://stackoverflow.com/questions/15869029/bind-command-to-c-ret-in-emacs). (Try `C-h k` then Control-Return in both your GUI and terminal Emacs to see what they map to.)

```elisp
(require 'ivy)
(define-key ivy-minibuffer-map (kbd "<C-return>")
  (lambda ()
    (interactive)
    (ivy-alt-done t)))
```

**Comment by baerrach** [comment]
I just switched to `the silver searcher (ag)` and replaced using grep.
This avoids this problem.
