### ISSUE TITLE
Trouble understanding sorting #1

### ISSUE THREAD

**Issue by jkitchin** [abo-abo/swiper#553]
1. If I run this, and type C-M-m, or C-M-o o the candidates are sorted, but reduced in number by 1 (I lose "a"). Interestingly if I exit and then ivy-resume, they are all there. Is this not the right way to sort the candidates?

```
#+BEGIN_SRC emacs-lisp
(ivy-read "string: " '("b" "a" "d" "c")
	  :action '(1
		    ("o"
		     (lambda (x)		       
		       (setf (ivy-state-collection ivy-last)
			     (setq ivy--all-candidates
				   (sort ivy--all-candidates 'string-lessp))))
		     "sort a-z")))
#+END_SRC
```

**Comment by abo-abo** [comment]
This code behaves fine for me:

```elisp
(ivy-read "string: " '("b" "a" "d" "c")
          :action '(1
                    ("o"
                     (lambda (x)
                       (setf (ivy-state-collection ivy-last)
                             (setq ivy--all-candidates
                                   (cl-sort ivy--all-candidates 'string-lessp)))
                       (setq ivy--old-cands nil))
                     "sort a-z")))
```

Here, `ivy--old-cands` acts as a sort of cache to reduce the number of calculations - it is `ivy--all-candidates` filtered by the current input. When you change the candidates, you should invalidate the cache.

I could add some API function for this, e.g.:

```elisp
(defun ivy-reset-collection (string-list)
  (setq ivy--old-cands nil)
  (setf (ivy-state-collection ivy-last)
        (setq ivy--all-candidates string-list)))
```

Would `ivy-reset-collection` be fine for you? Any remarks etc?

**Comment by jkitchin** [comment]
This looks pretty good. Is there a way to preserve the current candidate? e.g. if the current selection is on b, and you type "C-M-o o", the candidates are sorted, and the current selection is still on b?

the ivy-reset-collection doesn't look right to me. It would work for collections of strings, where (ivy-state-collection ivy-last) and ivy--all-candidates are the same, but not when (ivy-state-collection ivy-last) is a list of cons cells, or lists right?

This is what I mean:
```
#+BEGIN_SRC emacs-lisp 
(defvar input '(("b 1" . 1) ("a 2" . 2) ("d 0" . 0) ("c 5" . 5)))

(ivy-read "string: " input
          :action
          '(1
            ("o" (lambda (x) 
                   (setq res (list (ivy-state-collection ivy-last) ivy--all-candidates))))))

res
#+END_SRC
#+RESULTS:
| (d 0 . 0) | (c 5 . 5) | (b 1 . 1) | (a 2 . 2) |
| d 0       | c 5       | b 1       | a 2       |

```

ivy--all-candidates are the strings, and (ivy-state-collection ivy-last) is the cons cells. Won't ivy-reset-collection like above clobber the cons cells?

**Comment by abo-abo** [comment]
OK, I see. How about this code:

```elisp
(defvar input '(("b 1" . 1) ("a 2" . 2) ("d 0" . 0) ("c 5" . 5)))

(defun isn (a b)
  (< (cdr a) (cdr b)))

(ivy-read "string: " input
          :action
          '(1
            ("o" (lambda (x)
                   (ivy-reset-collection
                    (cl-sort (copy-sequence (ivy-state-collection ivy-last)) 'isn))))))

(defun ivy-reset-collection (collection)
  (setf (ivy-state-collection ivy-last) collection)
  (setf (ivy-state-preselect ivy-last) ivy--current)
  (ivy--reset-state ivy-last))
```

This should work fine with alists. And keeps the currently selected candidate as well.

**Comment by jkitchin** [comment]
That looks pretty awesome. Check out this. It lets me fine tune the
order with arrow keys!

Where would this be great?
1. in org-ref to fine-tune the order of selected references before
inserting them.
2. in my ivy-contacts function to fine-tune the order of selected
contacts before doing some action on all of them.

+1 for this.

```
(defvar input '(("b 1" . 1) ("a 2" . 2) ("d 0" . 0) ("c 5" . 5)))

(defun ivy-reset-collection (collection)
  (setf (ivy-state-collection ivy-last) collection)
  (setf (ivy-state-preselect ivy-last) ivy--current)
  (ivy--reset-state ivy-last))

(defun swap (i j lst)
  "Swap index I and J in the list LST."
  (let ((tempi (nth i lst)))
    (setf (nth i lst) (nth j lst))
    (setf (nth j lst) tempi))
  lst)

(defun move-up ()
  (interactive)
  (ivy-reset-collection
   (swap ivy--index (1- ivy--index) (ivy-state-collection ivy-last))))

(defun move-down ()
  (interactive)
  (ivy-reset-collection
   (swap ivy--index (1+ ivy--index) (ivy-state-collection ivy-last))))

(define-key ivy-minibuffer-map (kbd "C-<up>") 'move-up)
(define-key ivy-minibuffer-map (kbd "C-<down>") 'move-down)

(ivy-read "string: " input)
```


Oleh Krehel writes:

> OK, I see. How about this code:
>
> ```elisp
> (defvar input '(("b 1" . 1) ("a 2" . 2) ("d 0" . 0) ("c 5" . 5)))
>
> (defun isn (a b)
>   (< (cdr a) (cdr b)))
>
> (ivy-read "string: " input
>           :action
>           '(1
>             ("o" (lambda (x)
>                    (ivy-reset-collection
>                     (cl-sort (copy-sequence (ivy-state-collection ivy-last)) 'isn))))))
>
> (defun ivy-reset-collection (collection)
>   (setf (ivy-state-collection ivy-last) collection)
>   (setf (ivy-state-preselect ivy-last) ivy--current)
>   (ivy--reset-state ivy-last))
> ```
>
> This should work fine with alists. And keeps the currently selected candidate as well.
>
>
> ---
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/abo-abo/swiper/issues/553#issuecomment-225631443


-- 
Professor John Kitchin
Doherty Hall A207F
Department of Chemical Engineering
Carnegie Mellon University
Pittsburgh, PA 15213
412-268-7803
@johnkitchin
http://kitchingroup.cheme.cmu.edu

**Comment by jkitchin** [comment]
This looks closed for me.

**Comment by abo-abo** [comment]
> Should (setq ivy--old-cands nil) go in the ivy-reset-collection function?

This is done in `ivy--reset-state`. I think adding `ivy-reset-collection` might not be necessary. Promoting the use of `ivy--reset-state` e.g. in the manual would be fine, since it's more flexible.

**Comment by jkitchin** [comment]
I think I agree. It wasn't too bad without it here: http://kitchingroup.cheme.cmu.edu/blog/2016/06/13/Dynamic-sorting-with-ivy/.

Thanks for your help!
