### ISSUE TITLE
Sorting like in counsel-list-processes-action-delete

### ISSUE THREAD

**Issue by jkitchin** [abo-abo/swiper#555]
You suggested I look at counsel-list-processes-action-delete for updating the candidates. It is here for reference.

```
(defun counsel-list-processes-action-delete (x)
  (delete-process x)
  (setf (ivy-state-collection ivy-last)
        (setq ivy--all-candidates
              (delete x ivy--all-candidates))))
```

I tried to follow this for this example, but it doesn't look like it will directly translated. 
This example shows that (ivy-state-collection ivy-last) and ivy--all-candidates aren't the same.
```
(ivy-read "string: " '(("b 1" . 1) ("a 2" . 2) ("d 0" . 0) ("c 5" . 5))
	  :action
	  '(1
	    ("o" (lambda (x)
		   (message-box "%S \n %S"
				(ivy-state-collection ivy-last)
				ivy--all-candidates)))))
```

I adapted the idea like this to sort candidates on the number in the cons cells

```
(ivy-read "string: " '(("b 1" . 1) ("a 2" . 2) ("d 0" . 0) ("c 5" . 5))
	  :action
	  '(1
	    ("o" (lambda (x)
		   (setf (ivy-state-collection ivy-last)
			 (sort (ivy-state-collection ivy-last)
			       (lambda (a b)
				 (> (cdr a) (cdr b)))))))))
```

This does seem to update the collection, but it is not reflected in the minibuffer. is there a way to "refresh" it?

**Comment by abo-abo** [comment]
This code works for me:

```elisp
(defvar input '(("b 1" . 1) ("a 2" . 2) ("d 0" . 0) ("c 5" . 5)))

(ivy-read "string: " input
          :action
          '(1
            ("o" (lambda (x)
                   (setq ivy--all-candidates
                         (mapcar
                          #'car
                          (setf (ivy-state-collection ivy-last)
                                (sort (copy-sequence (ivy-state-collection ivy-last))
                                      (lambda (a b)
                                        (> (cdr a) (cdr b)))))))
                   (setq ivy--old-cands nil)))))
```

Take note of `copy-sequence` before sorting, since `sort` is a destructive function.

**Comment by jkitchin** [comment]
Perfect! I figured I was getting bitten by sort, but I didn't have
better luck with -sort either. This works great.

Oleh Krehel writes:

> This code works for me:
>
> ```elisp
> (defvar input '(("b 1" . 1) ("a 2" . 2) ("d 0" . 0) ("c 5" . 5)))
>
> (ivy-read "string: " input
>           :action
>           '(1
>             ("o" (lambda (x)
>                    (setq ivy--all-candidates
>                          (mapcar
>                           #'car
>                           (setf (ivy-state-collection ivy-last)
>                                 (sort (copy-sequence (ivy-state-collection ivy-last))
>                                       (lambda (a b)
>                                         (> (cdr a) (cdr b)))))))
>                    (setq ivy--old-cands nil)))))
> ```
>
> Take note of `copy-sequence` before sorting, since `sort` is a destructive function.
>
>
> ---
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/abo-abo/swiper/issues/555#issuecomment-225572599


-- 
Professor John Kitchin
Doherty Hall A207F
Department of Chemical Engineering
Carnegie Mellon University
Pittsburgh, PA 15213
412-268-7803
@johnkitchin
http://kitchingroup.cheme.cmu.edu
