### ISSUE TITLE
ivy-read is broken in projectile-find-file if projectile-completion-system is 'ivy

### ISSUE THREAD

**Issue by zhaojiangbin** [abo-abo/swiper#56]
I got this error:
```
(error "Keyword argument nil not one of (:predicate :require-match :initial-input :history :preselect :keymap :update-fn :sort)")
```
Looks like the calling code not updated with the latest function signature?

I work around it by setting `projectile-completion-system` to `'default`. Because I am using ivy-mode in `find-file` so this happens to be able to connect `projectile-find-file` to `ivy-read` eventually.

I am running projectile MELPA version 20150416.1401 and swiper MELPA version 20150422.858.

**Comment by abo-abo** [comment]
Just waiting for bbatsov/projectile#722 to get merged.

**Comment by abo-abo** [comment]
OK, merged now.
