### ISSUE TITLE
propertized candidate strings?

### ISSUE THREAD

**Issue by jkitchin** [abo-abo/swiper#560]
Is it possible to have some propertized strings as candidates to ivy-read? e.g. colored text, or different backgrounds?

**Comment by abo-abo** [comment]
Yes, of course. For example, `swiper` or `lispy-goto` already do this.  It's also possible to propertize strings during the completion, see e.g. `counsel-M-x-transformer`.

**Comment by jkitchin** [comment]
Cool thanks for the tip. I got the marked candidates to show in red here: https://github.com/jkitchin/org-ref/blob/master/org-ref-ivy-cite.el#L277

It was surprisingly tricky to get it to toggle in real time, but I think it is working!

Thanks for all the help!

**Comment by abo-abo** [comment]
I think you overdid it a bit. The strings in `ivy--old-cands` are the same object as the strings in `ivy-state-collection`:

```elisp
(progn
  (ivy-with '(ivy-read "test" (list a b)) "a C-m")
  (eq (car ivy--old-cands) a))
```

Note above `eq` is used and not `equal` proving it's the same object. So if you modify (by `propertize`) a string in one place, it gets modified in the other place.

**Comment by abo-abo** [comment]
Oops, I meant the destructive `set-text-properties`, not the non-destructive `propertize`.

```elisp
(progn
  (setq s "abc")
  (propertize s 'foo 'bar)
  s)
;; => "abc"

(progn
  (setq s "abc")
  (set-text-properties 0 1 '(foo bar) s)
  s)
;; =>
;; #("abc" 0 1 (foo bar))
```

**Comment by jkitchin** [comment]
You are right. I figured out how to use the transformer to do this. I was doing all that stuff before to "refresh" the display strings. It works more nicely now.
