### ISSUE TITLE
Error when searching for !<letter>

### ISSUE THREAD

**Issue by chumpage** [abo-abo/swiper#565]
I get the following error when using swiper to search for !a (or !<any-letter>):

Error in post-command-hook (ivy--exhibit): (wrong-type-argument stringp (("" . t) ("a")))

This isn't going to work the way I want because #486 anyway, but this shouldn't result in an error.

Ivy melpa version: 20160621.207
Swiper melpa version: 20160617.30

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by chumpage** [comment]
Fixed, thanks!
