### ISSUE TITLE
Ivy's M-q shortcut shadowed by Swiper

### ISSUE THREAD

**Issue by chumpage** [abo-abo/swiper#566]
In ivy-minibuffer-map M-q is bound to ivy-toggle-regexp-quote, which toggles regex vs literal search, but this is shadowed (I'm guessing unintentionally) in swiper-map, which defines M-q as swiper-query-replace. The result is the shortcut for switching to a literal search isn't available from Swiper.

Ivy melpa version: 20160621.207
Swiper melpa version: 20160617.30

**Comment by abo-abo** [comment]
Thanks.
