### ISSUE TITLE
ivy-switch-buffer: not all bookmarks appearing in the list

### ISSUE THREAD

**Issue by zeltak** [abo-abo/swiper#567]
Hi!

i started using the excellent org-bookmark-heading ( https://github.com/alphapapa/org-bookmark-heading). 

The bookmarks work very well with bk+ and appear (and can be launched) with helm bookmarks. yet the wont appear in ivy-switch-buffer. in addition i noticed other bookmarks are missing from the list.
Any clue why?

thx!

Z

**Comment by abo-abo** [comment]
If you look at the code of org-bookmark-heading, you'll see that it works with Helm because it has specific code support for Helm. I suggest that you ask the package maintainer to add either Ivy support or generic completion support.

**Comment by alphapapa** [comment]
Hey just FYI, I think this is actually a problem with Ivy.  From a quick glance at the code, it appears that Ivy doesn't use Emacs bookmark handlers, so it will only work with plain file bookmarks.  Instead, when switching to a bookmark, it should check the bookmark record's `handler` property and call it if necessary.  This way it will work with all bookmark types, like ones made with Gnus, etc.

**Comment by abo-abo** [comment]
@alphapapa There's a difference between virtual buffers and `counsel-bookmark`. Not all bookmarks are suitable for virtual buffers, for instance I have `gnus` and `magit-status` bookmarked. But `counsel-bookmark` deals properly with the `handler` property.

**Comment by alphapapa** [comment]
Hm, well, I guess, for some reason, bookmarks made with org-bookmark-heading aren't considered suitable for virtual buffers...?

**Comment by abo-abo** [comment]
@alphapapa They aren't. The concept is inherited from Ido, which also doesn't support org-bookmark-heading (I think).

A PR to add support is welcome.

**Comment by alphapapa** [comment]
These bookmarks are made correctly with the Emacs API, and they work with other packages that have no special support for them, like Bookmarks+ and Helm.  If swiper/ivy doesn't support the Emacs bookmarks API correctly, that seems like a bug to be fixed.  But it's up to you.  :)

**Comment by abo-abo** [comment]
@alphapapa Both `ivy--virtual-buffers` and `counsel-bookmark` support the bookmark api correctly.

And while `counsel-bookmark` can jump to any type of bookmarks, `ivy--virtual-buffers` restricts itself to files and will not call the `handler` property of the bookmark.  This a choice that I make at this point and not a bug. For the purposes of virtual buffers, only the `filename` property of a bookmark is considered, all other info is discarded.

**Comment by alphapapa** [comment]
> ivy--virtual-buffers restricts itself to files and will not call the handler property of the bookmark. This a choice that I make at this point and not a bug

Fair enough, that's your design decision to make.  :)  If it's not documented, you might want to consider doing that, to prevent confusion in cases like this.

**Comment by zeltak** [comment]
abo-abo i see what you mean now, wasnt aware of `counsel-bookmark` for some reason and now that i launch that i see it shows all bookmark. helm (which these days i prefer not to use since i love swiper/ivy) has a combined view of bookmarks, recentf and buffers. any thing close to that in ivy (i can live reluctantly without virtual buffers)

thx

Z
