### ISSUE TITLE
[suggestion] color ivy-switch-buffer entries by type?

### ISSUE THREAD

**Issue by zeltak** [abo-abo/swiper#568]
Hi 

I was wondering on your thoughts of assigning faces/colors (user defined?) per file type in ivy-switch-buffer? ie a dired buffer would get a blue color, a orgmode buffer a green and so on? i think it would make usability a bit nicer 

also a bit related, can one perhaps use the great A-o option menu to jump to a dired only view, org only view etc?

best

Z

**Comment by abo-abo** [comment]
Thanks for the suggestion. You can now customize faces per mode:

```elisp
(setq ivy-switch-buffer-faces-alist
      '((emacs-lisp-mode . swiper-match-face-1)
        (dired-mode . ivy-subdir)
        (org-mode . org-level-4)))
```

also a bit related, can one perhaps use the great A-o option menu to jump to a dired only view, org only view etc?

**Comment by zeltak** [comment]
thx for color support!

for the 2nd question sorry about not being clear. basically i meant launching ivy-switch-buffer pre filtered to just *.org or dired buffers. so i can assign a key that launches only dired buffers in ivy-switch-buffer view

thx

Z
