### ISSUE TITLE
ivy-set-actions across all ivy/counsel functions?

### ISSUE THREAD

**Issue by zeltak** [abo-abo/swiper#569]
Hi

i currently have this code in my init

```
(ivy-set-actions
 'counsel-find-file
 '(("j" find-file-other-window "other window")
   ("i" ivy-insert-action "insert current command into buffer")
   ("s" ivy-sudo-edit-action "open as root")
   ("b" (lambda (_) (interactive) (counsel-bookmark)) "bookmark")))

(ivy-set-actions
 'ivy-switch-buffer
 '(("j" find-file-other-window "other window")
   ("i" ivy-insert-action "insert current command into buffer")
   ("s" ivy-sudo-edit-action "open as root")
   ("b" (lambda (_) (interactive) (counsel-bookmark)) "bookmark")))

(ivy-set-actions
 'counsel-M-x
 '(("j" find-file-other-window "other window")
   ("i" ivy-insert-action "insert current command into buffer")
   ("s" ivy-sudo-edit-action "open as root")
   ("b" (lambda (_) (interactive) (counsel-bookmark)) "bookmark")))
```
this dosent seem to work (it just seems to work for `ivy-switch-buffer`) .Is there a way to have the `ivy-set-actions` be available across ***all***  ivy/counsel possible functions, so that M-o will present the same menu across all functions?

thx!

Z

**Comment by abo-abo** [comment]
```elisp
(ivy-set-actions
 t
 '(("j" find-file-other-window "other window")
   ("i" ivy-insert-action "insert current command into buffer")
   ("s" ivy-sudo-edit-action "open as root")
   ("b" (lambda (_) (interactive) (counsel-bookmark)) "bookmark")))
```

**Comment by zeltak** [comment]
perfect!

btw there are many little cool tips like this that are hard to find. if you would like i dont mind helping out and try to document all of these! do you want me to add this to the wiki? i am very un-technical but love all your packages and would love to help out!

best

Z

**Comment by abo-abo** [comment]
> do you want me to add this to the wiki? i am very un-technical but love all your packages and would love to help out!

Yes, this would be helpful. Thanks in advance.

Try to cross-reference with [the manual](http://oremacs.com/swiper/). And if you find something outdated either on the wiki or in the manual do let me know.

**Comment by zeltak** [comment]
ok sure. so just to be clear you prefer i add the tips/code snips to the wiki on github or to the manual? or just send/paste here things you would add?

best

Z

**Comment by abo-abo** [comment]
> i add the tips/code snips to the wiki on github or to the manual?

You have free access to the wiki, just like everyone else. Since Ivy is in GNU ELPA, I think you'd need an Emacs Copyright Assignment to modify the manual. It's not very hard to get, just takes time. But contributing only to the wiki is perfectly fine.
