### ISSUE TITLE
Behavioral difference in ivy when being byte-compiled or not

### ISSUE THREAD

**Issue by tsdh** [abo-abo/swiper#57]
I use the MELPA swiper package, currently version swiper-20150422.858.

When I do

  1. `emacs -Q`
  2. `M-x package-initialize`
  3. `M-x ivy-mode`
  4. `C-x C-f DEL`

i.e., I delete the initial input `~/` of the find file prompt, I get the error `completion--some: Wrong type argument: stringp, nil`.  After the error, I'm still at the prompt and the initial input is gone, i.e., the prompt is just `157  Find file: ` and the contents of my home directory are still shown as candidates.

The full backtrace is this:

```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  file-name-all-completions("" nil)
  completion-file-name-table("" nil t)
  all-completions("" completion-file-name-table nil)
  completion--file-name-table("" nil t)
  complete-with-action(t completion--file-name-table "" nil)
  #[257 "\303\302�\300\301$\207" ["" nil t complete-with-action] 6 "\n\n(fn TABLE)"](completion--file-name-table)
  completion--some(#[257 "\303\302�\300\301$\207" ["" nil t complete-with-action] 6 "\n\n(fn TABLE)"] (completion--embedded-envvar-table completion--file-name-table))
  read-file-name-internal("" nil t)
  all-completions("" read-file-name-internal)
  ivy--sorted-files(nil)
  ivy--cd(nil)
  ivy-backward-delete-char()
  funcall-interactively(ivy-backward-delete-char)
  call-interactively(ivy-backward-delete-char nil nil)
  command-execute(ivy-backward-delete-char)
  read-from-minibuffer("Search for \"foo\" in files (default all): " nil (keymap keymap (22 . ivy-scroll-up-command) (7 . minibuffer-keyboard-quit) (right . ivy-end-of-buffer) (left . ivy-beginning-of-buffer) (27 keymap (113 . ivy-toggle-regexp-quote) (16 . ivy-previous-line-and-call) (14 . ivy-next-line-and-call) (118 . ivy-scroll-down-command) (112 . ivy-previous-history-element) (110 . ivy-next-history-element) (62 . ivy-end-of-buffer) (60 . ivy-beginning-of-buffer)) (127 . ivy-backward-delete-char) (32 . self-insert-command) (18 . ivy-previous-line-or-history) (19 . ivy-next-line-or-history) (up . ivy-previous-line) (down . ivy-next-line) (16 . ivy-previous-line) (14 . ivy-next-line) (10 . ivy-alt-done) (13 . ivy-done)) nil grep-files-history)
  ivy-read("Search for \"foo\" in files (default all): " read-file-name-internal :predicate nil :require-match nil :initial-input nil :preselect "all" :history grep-files-history :keymap nil :sort t)
  ivy-completing-read("Search for \"foo\" in files (default all): " read-file-name-internal nil nil nil grep-files-history ("all" "el" "ch" "c" "cc" "cchh" "hh" "h" "l" "m" "tex" "texi" "asm") nil)
  completing-read("Search for \"foo\" in files (default all): " read-file-name-internal nil nil nil grep-files-history ("all" "el" "ch" "c" "cc" "cchh" "hh" "h" "l" "m" "tex" "texi" "asm"))
  grep-read-files("foo")
  byte-code("\304 \210�\203�� \305\232\203��\306\307�\310\211\311%C\207\n\204��\312\313!\207\314 \315�!\316\317\310�\320$ \321\232����F\207" [grep-find-command current-prefix-arg grep-find-template default-directory grep-compute-defaults (16) read-from-minibuffer "Run: " nil grep-find-history error "grep.el: No `grep-find-template' available" grep-read-regexp grep-read-files read-directory-name "Base directory: " t (4)] 8)
  call-interactively(rgrep record nil)
  command-execute(rgrep record)
  execute-extended-command(nil "rgrep" #("rgr\nautoarg-kp-mode\nautoarg-mode\nchange-log-merge\ncomint-insert-previous-argument\ndebbugs-org\ndebbugs-org-bugs\ndebbugs-org-mode\ndebbugs-org-search\ndecrease-left-margin" 3 4 (read-only nil) 4 19 (face (ivy-current-match) read-only nil) 19 167 (read-only nil)))
  funcall-interactively(execute-extended-command nil "rgrep" #("rgr\nautoarg-kp-mode\nautoarg-mode\nchange-log-merge\ncomint-insert-previous-argument\ndebbugs-org\ndebbugs-org-bugs\ndebbugs-org-mode\ndebbugs-org-search\ndecrease-left-margin" 3 4 (read-only nil) 4 19 (face (ivy-current-match) read-only nil) 19 167 (read-only nil)))
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)
```

When I delete `ivy.elc` in the ELPA directory and restart emacs, or just visit `ivy.el` and do `M-x eval-buffer RET` so that the ivy code is run in interpreted mode, the behavior at step 4 from above is different.  Then, `C-x C-f DEL` changes the initial input `~/` to `/home/`.  With another `DEL`, it is changed to `/`, and from then on, `DEL` has no effect anymore, that is, the initial input stays `/` without being able to get rid of it.

`DEL` is `ivy-backward-delete-char`.  Looking at that, I wonder how `(file-name-directory (directory-file-name ivy--directory))` can become `nil`.  If `ivy-directory` was `nil`, you would get a different error.  But `ivy-directory` being the empty string `""` causes the form to be `nil`.

Indeed, when adding a `(message "ivy--directory = '%s'" ivy--directory)` before the `(ivy--cd ...)` `ivy--directory` is never `""` when ivy runs in interpreted mode.  Then I byte-compiled `ivy.el` anew and restarted emacs.  Now, I don't get the error from above anymore, and the message also shows that `ivy--directory` doesn't become `""` anymore.  The behavior in compiled and interpreted mode seems to be completely the same.

However, the behavior I have with the `(message ...)` is different to the original compiled scenario, too.  Where `DEL` used to change `~/` to `/home/`, now `DEL` on `~/` simply deletes that so that the input is empty thereafter.

I really have no clue where the problem is.  That a message makes a big difference suggests some weird timing issues or something alike. :-(

**Comment by abo-abo** [comment]
I suspect that this should be fixed now. Can you check and close the issue?

**Comment by tsdh** [comment]
I haven't been able to reproduce it even with the previous melpa package, so I close it. I'm still interested what caused the different behavior between compiled and interpreted code. Could be an emacs bug...
