### ISSUE TITLE
Swiper in dired: auto enter dir when selected?

### ISSUE THREAD

**Issue by zeltak** [abo-abo/swiper#571]
Hi again
Can swiper be/is mode aware and know its launched in a dired mode buffer? 
i think it could be very cool if swiper could auto enter the directory chosen in swiper when filtering while in dired mode. that would make it 1.more inline with many file managers 2.save an extra key stroke (yes we are lazy..:)

as an example when in `~/` in dired one would launch swiper, filter to `Downloads` and press the `ivy-done` keybind (enter)  but instead of the point finishing at `Downloads` it would auto enter the `Downloads` directory

any thoughts on that guys?

best

Z

**Comment by abo-abo** [comment]
There are plenty of uses of `swiper` in `dired-mode` without the intention of opening the file.

You can simply use this code, it's even a key less:

```elisp
(define-key dired-mode-map "i" 'counsel-find-file)
```

**Comment by zeltak** [comment]
yup that can work :)

thx for the tip!

btw would appreciate any dired tips you have, love using dired :)

best

z
