### ISSUE TITLE
Document how to use -> to highlight the current selection

### ISSUE THREAD

**Issue by Wilfred** [abo-abo/swiper#577]
The docs at http://oremacs.com/swiper/#introduction say:

> For example, adding a custom display function that points to a selected candidate with ->, instead of highlighting

However, I can't find any documentation for how to do this. I've found `ivy-set-display-transformer`, should I be using this? Is there sample code somewhere? The `->` from ido-vertical is one of the very few things I miss when using ivy.

**Comment by abo-abo** [comment]
Use:

    (setq ivy-format-function 'ivy-format-function-arrow)

**Comment by Wilfred** [comment]
Thanks. Should I submit a PR for the docs, or does this belong elsewhere?

**Comment by abo-abo** [comment]
Editing the docs is better, especially since you have a CA. But putting more info on the wiki is always welcome as well.

**Comment by Wilfred** [comment]
> especially since you have a CA.

I do indeed! :) Is that public information somewhere, or have I said so at some point?

**Comment by abo-abo** [comment]
> I do indeed! :) Is that public information somewhere, or have I said so at some point?

It's available to GNU devs via a file on GNU fencepost computer.
