### ISSUE TITLE
No candidates after `ivy-backward-delete-char` when completing files

### ISSUE THREAD

**Issue by tsdh** [abo-abo/swiper#58]
When I do `C-x C-f` in *scratch* with `ivy-mode` enabled, I get the prompt `155  Find file: ~/`.  When I hit <kbd>DEL</kbd>, the prompt changes to `0 Find file: /home/` and there are no candidates shown.  But actually the `/home/` directory contains `horn/` and `test/`.

I can reproduce that with any directory, e.g., <kbd>C-x C-f .emacs.d C-j DEL</kbd> also shows zero candidates although there are 155 files & directories in `~/`.

**Comment by abo-abo** [comment]
Was this always the issue? I can't reproduce it neither on trunk nor on 24.5.2.
Can you get this with `emacs -Q`?

**Comment by tsdh** [comment]
Hm, let me see...

Ah, it happens only with `emacs -Q -l ivy-init.el` where the latter contains:

```elisp
(add-to-list 'load-path "~/Repos/el/swiper")
(require 'ivy)
(setq ivy-re-builders-alist '((read-file-name-internal . (lambda (x)
							   (concat "^" (regexp-quote x))))
			      (t . ivy--regex)))

(ivy-mode)
```

I think the problem is in [this cond clause](https://github.com/abo-abo/swiper/blob/master/ivy.el#L729) which has a special case testing if the old regexp was `""` which is the result of `ivy--regex` on empty input.  My re-builder function doesn't satisfy this assumption; if the input is empty, the regex is `"^"`.

**Comment by tsdh** [comment]
Yes, that fixes the issue.  Thanks.
