### ISSUE TITLE
any swiper/counsel way to browse mark/global mark ring visually?

### ISSUE THREAD

**Issue by zeltak** [abo-abo/swiper#582]
hi all

anyone know if there is a way to use swiper/counsel  to browse mark/global mark ring visually?

best

Z

**Comment by abo-abo** [comment]
Never thought about it. Is there already some implementation available in another package?

**Comment by darrylhebbes** [comment]
Helm has a way of doing this - perhaps this implementation could help:

[helm-ring.el](https://github.com/emacs-helm/helm/blob/master/helm-ring.el)

**Comment by madand** [comment]
@abo-abo since you have implemented `counsel-yank-pop`, this issue can be closed.

**Comment by abo-abo** [comment]
@madand Thanks.

**Comment by nidrissi** [comment]
@madand @abo-abo The mark ring is not the kill ring!

**Comment by basil-conto** [comment]
Right, Counsel currently has a command for the local mark ring but not the global one.

**Comment by abo-abo** [comment]
Right, we have `counsel-mark-ring`. If there's a need to extend it, please open a new issue.

**Comment by triplc** [comment]
1. Please order the list in `counsel-mark-ring` in last-first order, not in line number order. The purpose of the ring is to go back to previous place, like `C-u C-SPC`.
2. Please add a feature, like `counsel-evil-mark-ring` which is the "bookmark" of `evil-mode` (type ex-command `:marks`). `evil mark` is a similar to `emacs bookmark`.

**Comment by abo-abo** [comment]
@triplc Please open a new issue / PR. This issue is already resolved.
