### ISSUE TITLE
Can counsel-ag work as counsel-git-grep?

### ISSUE THREAD

**Issue by goofansu** [abo-abo/swiper#583]
`counsel-git-grep` know the project `.git` folder while `counsel-ag` only search current folder.

Can I easily add the git ability to `counsel-ag` to become something like `counsel-git-ag`?

Thanks

**Comment by abo-abo** [comment]
You get set a folder in `counsel-ag` by calling it with a prefix arg. I'm not an expect in `ag`, so I can't say if it has a way to detect a project automatically.

**Comment by goofansu** [comment]
Ok, this is a way. Thank you.

**Comment by goofansu** [comment]
@abo-abo Hi, I'm using projectile, so I use defadvice to achieve my target:

```
(defun counsel-git-ag-advice (args)
  (list nil (projectile-project-root)))
(advice-add 'counsel-ag :filter-args #'counsel-git-ag-advice)
```

I should replace the second arg of `args` with `projectile-project-root`, but don't know how to do it.

**Comment by goofansu** [comment]
I make it:

```
(defun counsel-ag-advice (args)
  "Make counsel-ag aware of project root directory,
modify INITIAL-DIRECTORY to projectile-project-root."
  (setcar (nthcdr 1 args) '(projectile-project-root)))
(advice-add 'counsel-ag :filter-args #'counsel-ag-advice)
```
