### ISSUE TITLE
ivy-push-view with three or more windows fails

### ISSUE THREAD

**Issue by alfaromurillo** [abo-abo/swiper#584]
I suppose that this is not implemented yet?

**Comment by abo-abo** [comment]
It's implemented and works fine for me. Please give a scenario to reproduce the bug.

**Comment by alfaromurillo** [comment]
I start emacs with emacs -q

M-: (add-to-list 'load-path "path/to/swiper")
M-: (require 'ivy)
M-x ivy-mode
C-x 3 C-x 3 C-x 3
M-x ivy-push-view <enter> <enter>
C-x 1
C-x b { <enter>

The name of the view is right, it has the three windows, but M-: ivy-views shows only one horz division with two buffers.
My emacs is from about a month ago (c803af7), and swiper is the latest commit (07813be).

Thanks for your help and for this great package!

**Comment by abo-abo** [comment]
> The name of the view is right, it has the three windows, but M-: ivy-views shows only one horz division with two buffers.

Thanks, I see the problem now.

**Comment by abo-abo** [comment]
Please test.

**Comment by alfaromurillo** [comment]
Oleh Krehel writes:

> Please test.

Thanks it is working now. The only problem is that the size of the 
windows is not the same as before. I know that it is not 
implemented yet, but maybe you can run balance-windows right after 
restoring the view, so that at least they are the same size.

Thanks again,
-- 
Jorge.

**Comment by abo-abo** [comment]
I don't have time right now to implement it properly, the window position API is not full clear to me. Patches welcome.
