### ISSUE TITLE
Counsel-M-x command start prompt with "^" symbol

### ISSUE THREAD

**Issue by sandric** [abo-abo/swiper#588]
If I invoke `counsel-M-x` command - minibuffer prompt starts with character "^". If I enter command name with it at beginning everything works fine. The same way if I remove this symbol - all ok. It just little distracting for me and I would like to remove it. I don't know if this is a bug or its how it is supposed to be (I found in docs that ivy can parse with regexp special symbols), but I would like to find out if I can open prompt without it, is there a way? Thx.

**Comment by abo-abo** [comment]
See `ivy-initial-inputs-alist`.

**Comment by sandric** [comment]
Oh, great, thanks! I should better read docks)
