### ISSUE TITLE
Start ivy-occur with wgrep mode by default?

### ISSUE THREAD

**Issue by sandric** [abo-abo/swiper#589]
I wish I could start `ivy-occur-mode` automatically with `ivy-wgrep-change-to-wgrep-mode` executed. I want it because I'm using swiper to replace found occurrences. And I like to replace those seeing them all at once - using occur mode. The problem is that right now to replace occurrence I need to type twice after I found occurrences with swiper - once to open ivy-occur mode and other to change it to wgrep mode. I tried to fix that with this:

```elisp
(advice-add 'ivy-occur :after #'ivy-wgrep-change-to-wgrep-mode)
```

But it made nothing. I also tried to add similar after advice on `ivy-exit-with-action` function - but that it complains on `ivy--exhibit` function. As I understood - `ivy-wgrep-change-to-wgrep-mode` can not be called with ivy minibuffer opened, or am I wrong?

So, is there a way for ivy-occur to switch to wgrep automatially without need of typing additional shortcut? Thx.

**Comment by abo-abo** [comment]
Try advising `ivy-occur-grep-mode`.

**Comment by sandric** [comment]
Thx a lot, I tried this and now its successfully starting wgrep mod:
```elisp
(advice-add 'ivy-occur-grep-mode :after #'ivy-wgrep-change-to-wgrep-mode)
```
But now the problem is that after made changes and tried to commit them its not saved with message throwing `(No changes to be performed)` and no green highlighting when you start editing.

**Comment by abo-abo** [comment]
I have no idea why this doesn't work. I tried using `ivy-occur-grep-mode-hook`, that doesn't work as well. It's a wgrep issue.

**Comment by sandric** [comment]
It looks like I figured out how to make it work. Its not the right solution, but it works for me. Here's my function to open occur with wgrep mode by default:
```elisp
(defun sandric/swiper-replace ()
  "Swiper replace with mc selction."
  (interactive)
  (run-at-time nil nil (lambda ()
                         (ivy-wgrep-change-to-wgrep-mode)))
  (ivy-occur))

(define-key ivy-minibuffer-map (kbd "s-f") 'sandric/swiper-replace)
```
As you can see I used your own [article](http://oremacs.com/2015/07/16/callback-quit/)! (Thanks a lot for it). If anyone was interested in such behavior of occur mode - it should work now.

My workflow now works just as I wanted - my swiper global key first checks if there's selection - and if yes it starts swiper to search text from it - so after selecting some text all I have to do is type twice `s-f` and it opens me wgrep mode with mc marked all occurences, here's full version (just in case anyone will like that):

```elisp
(defun sandric/swiper-replace ()
  "Swiper replace with mc selction."
  (interactive)
  (run-at-time nil nil (lambda ()
                         (ivy-wgrep-change-to-wgrep-mode)
                         (mc/mark-all-in-region (point-min) (point-max) ivy-text)
                         ))
  (ivy-occur))

(global-set-key (kbd "s-f") 'sandric/swiper-or-region)
(define-key ivy-minibuffer-map (kbd "s-f") 'sandric/swiper-replace)
```

**Comment by abo-abo** [comment]
I'm glad you figured it out. If you have the time, please put your workflow on https://github.com/abo-abo/swiper/wiki, it's more visible than a closed issue.

**Comment by snippins** [comment]
Just want to check in and note that the above works for swiper but hangs emacs when calling within counsel-rg, so it's better to use swiper-map instead of ivy-minibuffer-map.
