### ISSUE TITLE
remember `default-directory` of ivy-read for ivy-resume

### ISSUE THREAD

**Issue by redguardtoo** [abo-abo/swiper#591]
When I use `ivy-read` to grep/find files, I use path relative to `default-directory`.

In this case, I want `ivy-last` remember the the value of `default-directory`, so later `ivy-resume` can re-use it.

**Comment by abo-abo** [comment]
Thanks. Let me know if this works.

**Comment by redguardtoo** [comment]
works like a charm. Thank you. The only issue is I only use stable.melpa.org. When will you release a stable version?

**Comment by abo-abo** [comment]
Soon, hopefully.
