### ISSUE TITLE
Have partial completion divide text into words using hyphens/spaces and complete each word separately

### ISSUE THREAD

**Issue by d125q** [abo-abo/swiper#592]
Is it possible to have ivy emulate the default [partial completion style](https://www.gnu.org/software/emacs/manual/html_node/emacs/Completion-Styles.html) which splits the text into words based on hyphens/spaces and completes each word separately?

**Comment by abo-abo** [comment]
Ivy already splits the text into words based on spaces and completes each word separately. This is all done by default.

Think about it this way: you have 10 candidates, and your (partial) input is 3 words. You could complete each word as much as possible, but the number of candidates would still be 10. So having bigger input is not very useful.

The way I like to use Ivy is to enter 2-3 words that I think are unique enough among the candidates, then select the one I want. An important distinction from the built-in completion is that the input is usually irrelevant, it won't be used later. The only purpose of the input is to narrow the cands.

**Comment by d125q** [comment]
Thank you very much.  The issue is that I didn't have a look through the source code and wanted to use hyphens rather than spaces.
