### ISSUE TITLE
counsel-imenu error "imenu: Unknown imenu item: #<marker at 94 in aa.c>"

### ISSUE THREAD

**Issue by seudut** [abo-abo/swiper#594]
I am now switching `ido` to 'counsel-', but when run `counsel-imenu`,  it cannot jump to the tag, but output this error in echo area

    imenu: Unknown imenu item: #<marker at 94 in aa.c>

While, it works if run `imenu`.

**Comment by abo-abo** [comment]
Please provide the example file.

**Comment by seudut** [comment]
Hi @abo-abo , here is the `.c` file

    #include<stdio.h>

    void foo ()
    {
        printf ("this is foo\n");
    }

    // this is  comment
    int main()
    {
        prfintf("hello, world\n");
        return 1;
    }

**Comment by abo-abo** [comment]
Works find for me, although the include is strangely sorted to the bottom. What's your Emacs version?

Also, `moo-jump-local` from `function-args` is superior to `counsel-imenu` for C, in my opinion.

**Comment by seudut** [comment]
emacs version 

    GNU Emacs 25.0.95.1 (x86_64-apple-darwin15.4.0, NS appkit-1404.46 Version 10.11.4 (Build 15E65)) of 2016-06-23

and the `counsel` is `counsel-20160708.1107`.  It not only doesn't work for C file, but also for other programming file, such as `elisp` and `org-mode`.

It indeed looks strange. but I tried start emacs as `emacs -q` and only load the `counsel`, `swiper` and `ivy` manually.  the `counsel-imenu` still cann't work, but `imenu` works

**Comment by abo-abo** [comment]
> It indeed looks strange. but I tried start emacs as emacs -q and only load the counsel, swiper and ivy manually. the counsel-imenu still cann't work, but imenu works

There's a difference between `emacs -Q` and `emacs -q`. Try to clone this repo and type:

    make plain

Then test `counsel-imenu`.

**Comment by seudut** [comment]
I tried your suggestion. clone the repo and test `counsel-imenu`. It works. so it looks not the issue of `counsel`, it this right?

I deleted my `elpa` directory, and start init.el file to re-install all my packages. now the issue is gone. `counsel-imenu` works well.

**Comment by abo-abo** [comment]
> I tried your suggestion. clone the repo and test counsel-imenu. It works. so it looks not the issue of counsel, it this right?

Seems like it. I'm closing this issue then.
