### ISSUE TITLE
Skip * by default in special buffers

### ISSUE THREAD

**Issue by justbur** [abo-abo/swiper#595]
I'm asking as an issue because I'm not sure how you would do this, but I'm consistently annoyed when I want to switch to `*scratch*` for instance and I type `sc` and get some file from the virtual buffer list that starts with `sc`. The issue of course is that the regex is prioritizing the match to the first two characters which is fine, but I think of `*scratch*` as starting with `sc`. Of course I could enter `*s` and get there quickly, but I was thinking it would be nice to have he option to ignore the `*` for the purpose of matching buffers. What do you think?

**Comment by abo-abo** [comment]
I think it can be handled pretty well with `ivy-sort-matches-functions-alist`. Just write a custom function that sorts e.g. `*scratch*` on top of `misc`. It could be quite simple: prioritize the prefix matches and discard the leading star. It would be nice to have such a function available for customization as well.

**Comment by justbur** [comment]
Looks good. Thanks
