### ISSUE TITLE
ivy custom completion-style 

### ISSUE THREAD

**Issue by Dickby** [abo-abo/swiper#597]
Hi,
I'm coming from Helm and use ivy for a few weeks now.
I had Helm customized in a way that it uses fuzzy matching as long as no space is in the search string, otherwise it uses something similar to ivy--regex-plus.
I tried to build this behaivior in ivy with this custom completion style function:

`
(defun ivy--regex-both (str)
  (if(string-match ".*? .*?" str)
      (ivy--regex-plus str)
    (ivy--regex-fuzzy str)))
`

and it works, but if there is no space in the search string, the order of the candidates is different to the original order of ivy---regex-fuzzy function.

**Comment by abo-abo** [comment]
> if there is no space in the search string, the order of the candidates is different to the original order of ivy---regex-fuzzy function.

I assume this the problem. I suspect this is related to `ivy--regex-fuzzy` using `flx` for sorting. Try to uninstall `flx`.

**Comment by Dickby** [comment]
You're right.
It's the same order if i uninstall flx, unfortunately the order of ivy--regex-fuzzy changes to the behavior of my custom function, but I wanted my custom function to have the order of ivy--regex-fuzzy.
Is there a way to make it like that?
If not feel free to close this issue.
Thanks for the nice Package anyway!

**Comment by abo-abo** [comment]
> I wanted my custom function to have the order of ivy--regex-fuzzy

This would require a lot of work, `ivy--regex-fuzzy` relies on `flx` for sorting, and `flx` relies on the specific way of building the regex.

It would be cool to have this feature sometime in the future, but I really don't have time to make it. So I'll close the issue for now.
