### ISSUE TITLE
Make `ivy-backward-kill-word' go up in directory structure only when current input is a directory

### ISSUE THREAD

**Issue by d125q** [abo-abo/swiper#598]
Assume I execute `C-x C-f` and type `.ema`.  I get the following completion entries:
```
~/.emacs.d
~/.emacs
```
Now, if I am to call `ivy-backward-kill-word`, it would go to
```
/home/
```
In my opinion, it would be more logical and user friendly if it went to `~/` and only after a second execution to up to `/home/`.

**Comment by abo-abo** [comment]
That's not the way it works for me. Mine goes:

```
~/.ema
~/.
~/
/home/
```

That's the way it works with `emacs -Q` as well, so there must be something in your config that makes the bug happen.

**Comment by d125q** [comment]
Yes, I am sorry.  I did not realize `C-DEL` is bound to `counsel-up-directory`, not to `ivy-backward-kill-word`.  I am not, however, sure how intuitive this default is.  Deleting words can be quite useful when finding files.

**Comment by abo-abo** [comment]
`ivy-backward-word` is on `M-DEL`.

**Comment by d125q** [comment]
Indeed.  Sorry -- I am very sleepy.
