### ISSUE TITLE
[BUG] hydra: after emacs restart the bmkp-jump-dired/bmkp-jump wont work in hydra before visiting buffers.

### ISSUE THREAD

**Issue by zeltak** [abo-abo/swiper#599]
Hi

so this is a weird bug. i have a hydra that uses bmkp-dired-jump to quick jump to bookmarks
```
("e"  (bmkp-dired-jump "d.emacs.d" ) "emacs.d" )
```

now when i launch emacs using the hydra command wont work until i physically visit the bookmark. after that all following jumps do work.
this is the error in the message buffer
```
Invalid face reference: quote [9 times]
bmkp-jump-1: No bookmark specified
Error in post-command-hook (elmacro-process-latest-command): (wrong-type-argument symbolp (lambda nil (interactive) (bmkp-dired-jump "d.emacs.d")))
```

i will mention the using both counsel-bookmark and helm-bookmark after restart works fine

thx!

Z

**Comment by abo-abo** [comment]
> Error in post-command-hook (elmacro-process-latest-command)

There's your problem. It's a bug in `elmacro-process-latest-command`, whatever that is. Just disable that or report a bug for elmacro.

**Comment by zeltak** [comment]
thx abo-abo, but i dont think that was the issue. 
i disabled el macro and restarted emacs but still the same issue

```
.emacs.d/settings.el: (lambda (filename) ...) quoted with ' rather than with #'
.emacs.d/settings.el: (lambda (obj) ...) quoted with ' rather than with #'
Loading /home/zeltak/.emacs.d/abbrv/personal_abbrv.txt...done
Loading /home/zeltak/.emacs.d/abbrv/common_abbrv.txt...done
Loading /home/zeltak/.emacs.d/abbrv/misc_abbrv.txt...done
Loading /home/zeltak/.emacs.d/settings.el (source)...done
Loaded /home/zeltak/.emacs.d/settings.el
For information about GNU Emacs and the GNU system, type C-h C-a.
Invalid face reference: quote [24 times]
bmkp-jump-1: No bookmark specified
```

any clue?

**Comment by abo-abo** [comment]
Try `(require 'dired)` maybe. In the end, it's a `bookmark+` issue. You can ask for a solution here: http://emacs.stackexchange.com/questions.
