### ISSUE TITLE
Performance issue with small regexps and '*'

### ISSUE THREAD

**Issue by agumonkey** [abo-abo/swiper#6]
Brilliant extension, but here's a weird case:
Starting with `arch.*` works fine, then removing the `.` searching for `a*` results in unresponsive Emacs. Ran emacs -Q, then evaluated the two forms below:

```
(package-initialize)
(require 'swiper)
```

Buffer contents is the result of C-u M-! ls RET (70 lines total)

Under Archlinux, GNU Emacs 24.4.1 (x86_64-unknown-linux-gnu, GTK+ Version 3.14.7)
 of 2015-01-17 on bisson

**Comment by abo-abo** [comment]
Thanks for noticing, should be fixed now.
