### ISSUE TITLE
Ivy should confirm-nonexistent-file-or-buffer

### ISSUE THREAD

**Issue by tsdh** [abo-abo/swiper#60]
It frequently occurs to me that I'm typing too fast and erroneous at file or buffer prompts which leads to the creation of new buffers or buffers for files that don't exist (and I haven't intended to create them).

Emacs has the customize option `confirm-nonexistent-file-or-buffer`.  If that's set to `t`, when I do `C-x C-f nonexistentfile RET` I get visual feedback in that the prompt looks like `Find file: ~/nonexistentfile [confirm]` and I have to confirm by hitting `RET` another time.

I'd really appreciate if `ivy-mode` could honor this variable so that I don't accidentally find files/create buffers any longer.

**Comment by abo-abo** [comment]
Check if this works.

**Comment by tsdh** [comment]
It's a start.  When I do <kbd>C-x C-f .emcas RET</kbd> (note the typo) the prompt gets a `confirm` added, and if I really want to open that file I have to hit return again.

What's not optimal is this:

1. If the next command after entering "confirmation mode" is not `last-command`, then I should be back in "normal mode" again.
2. `ivy-alt-done' should honor it, too.

The result of point 1, i. e., that you stay in "confirmation mode" currently, is that once I edited `.emcas` to `.emasc` (which has another typo now) opens that immediately without having me to re-confirm again.

**Comment by tsdh** [comment]
Awesome!

One minor point: the two new faces should inherit the `minibuffer-prompt` face.  I've configured that to have a bold font, custom colors, and having a box around the text.  Thus, the `(confirm)` in green-on-white, with no box, and default weight looks pretty awkward here.

**Comment by tsdh** [comment]
Perfect now!
