### ISSUE TITLE
auto-insert does not work with ivy-mode

### ISSUE THREAD

**Issue by Wilfred** [abo-abo/swiper#600]
If I create a new elisp file `foo.el`, then call `M-x auto-insert`, I get the following:

```lisp
;;; foo.el --- does some foo                         -*- lexical-binding: t; -*-

;; Copyright (C) 2016  

;; Author:  <wilfred@localhost>
;; Keywords: 
```

However, `auto-insert` (via `auto-insert-alist`) then prompts me for `(1/36) Keyword, C-h:` in an infinite loop. I can't see any way of saying "I'm done with keywords" without pressing C-g, but that just terminates the whole skeleton insertion.

Have I missed something?

**Comment by abo-abo** [comment]
> Have I missed something?

Use <kbd>C-M-j</kbd> to enter `""` as input. `auto-insert` will interpret it as the end of input and do its thing.

The difference is:

- <kbd>C-j</kbd> selects the current candidate.
- <kbd>C-M-j</kbd> selects the current input.
