### ISSUE TITLE
Highlight the entire line with `ivy-current-match'

### ISSUE THREAD

**Issue by d125q** [abo-abo/swiper#603]
Do you not think it would be better if the entire line was highlighted using `ivy-current-match`, rather than just the match itself?  That would make it easier to notice what the current match in when, for example, I have typed `.emacs` and Ivy lists
```
~/.emacs.d
~/.emacs
```
as possible completions.

**Comment by abo-abo** [comment]
This is a feature for a long time already:

```elisp
(setq ivy-format-function 'ivy-format-function-line)
```
Try to explore <kbd>M-x</kbd> `customize-group` `ivy` more.

**Comment by d125q** [comment]
I am sorry.

**Comment by abo-abo** [comment]
No problem. Sometimes it's hard to find the relevant info right away. If it's hard to find elsewhere, everyone is welcome to ask here.
