### ISSUE TITLE
ivy-switch-buffer error when typing

### ISSUE THREAD

**Issue by habamax** [abo-abo/swiper#608]
In the recent version I get

     Error in post-command-hook (ivy--exhibit): (wrong-type-argument characterp ("m" . t))

whenever I try to switch buffers

version in package.el

  ivy                20160729.521  installed             Incremental Vertical completYon

**Comment by abo-abo** [comment]
Does this solve your problem?

    (setq ivy-sort-matches-functions-alist nil)

**Comment by habamax** [comment]
yep, it solves.

Is it intended?

**Comment by abo-abo** [comment]
> Is it intended?

Of course not. Please check is the issue is solved.
