### ISSUE TITLE
Feature request: highlight remote buffers in ivy-mode for switch-to-buffer.

### ISSUE THREAD

**Issue by zhaojiangbin** [abo-abo/swiper#61]
In ivy-mode, subdirs are highlighted in the `ivy-subdir` face for `find-file`. We can make use of another face to highlight remote buffers (i.e. as tested by `file-remote-p`) for `switch-to-buffer`.

**Comment by abo-abo** [comment]
Nice idea, thanks.

**Comment by zhaojiangbin** [comment]
Awesome.
