### ISSUE TITLE
Option to not to center screen on search

### ISSUE THREAD

**Issue by rsuhada** [abo-abo/swiper#611]
Dear abo-abo,

I really like swiper, but despite several attempts I didn't manage to jump over as my main search function. 

I have a feature suggestion that maybe other users could find useful - don't center the screen on the match, but rather use the same gradual scrolling behavior as isearch-forward / backward.

Reason: say I'm somewhere on top and want "search-jump" to "XYZ" in the bottom third of the screen, and there are a few instances of "XYZ" visible on screen. With isearch I focus my eyes on the instance I want to reach, then hit C-s a few times (without moving my eyes) until I land there. This is all very fast and automatic for me.

With swiper, the screen recenters immediately with the first search and I loose track where I wanted to land.

I understand that 1) some users might prefer the centering 2) movement by search can be accomplished by avy jumps (which I use too) - but sometimes move by search is faster than avy jump. 

If it is not hard to implement, I'd suggest to have a customizable variable to disable centering. 

Thank you very much!

**Comment by abo-abo** [comment]
The recenter is off by default, see `swiper-action-recenter`. Did you turn it on by mistake?

**Comment by rsuhada** [comment]
Thanks - I now see what's the problem: this is actually not a swiper issue
but swiper-helm. In swiper there is no recentering, but swiper-helm does
recenter even though swipe-action-recenter is nil.
Is it possible that swiper-helm ignores the variable?

In any case for me it's fine - I just switch to full swiper now :)

Thank you very much!

**Comment by abo-abo** [comment]
> In any case for me it's fine - I just switch to full swiper now :)

OK, I'll close this issue then. I'm not very eager to dig around swiper-helm.

> Thank you very much!

You're welcome.
