### ISSUE TITLE
Unreadable characters in counsel-grep buffer

### ISSUE THREAD

**Issue by swarnendubiswas** [abo-abo/swiper#612]
I get unreadable characters in `counsel-grep` buffer, please check the screen shot. Note that `grep` works fine. 

![screenshot-1](https://cloud.githubusercontent.com/assets/7343807/17301888/650d6c5e-57e7-11e6-84e8-fda2e494bf3b.png)

**Comment by abo-abo** [comment]
Can't really do much without looking at the file that you're grepping.

**Comment by abo-abo** [comment]
You can drag and drop files to attach them to an issue comment.

**Comment by swarnendubiswas** [comment]
No problem, here it is.
[counsel-grep-test.txt](https://github.com/abo-abo/swiper/files/394468/counsel-grep-test.txt)

**Comment by abo-abo** [comment]
Can't reproduce. Emacs 25, GNU grep 2.16.

**Comment by swarnendubiswas** [comment]
I reproduced it in my environment, Emacs 24.5.2, GNU grep 2.20. I am on an RHEL 6.8 machine. Here are is the snippet I used with `emacs -Q`.

```
(require 'package)
(setq package-user-dir (expand-file-name "~/.emacs.d/elpa/")
      package-enable-at-startup nil)
(add-to-list 'package-archives
             '("melpa" . "https://melpa.org/packages/") t)
(package-initialize)

(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))
(eval-when-compile
  (require 'use-package))

(use-package swiper ; Performs poorly if there are a large number of matches
  :ensure t
  :config
  (setq swiper-use-visual-line t
        swiper-action-recenter t))

(use-package counsel
  :ensure t
  :config (counsel-mode 1)
  :diminish counsel-mode)
```
The first one is with `counsel-grep` while the second one is with `grep`.
![screenshot-1](https://cloud.githubusercontent.com/assets/7343807/17305883/f1c25caa-57fa-11e6-861f-36f7ba9aed0e.png)

![screenshot-2](https://cloud.githubusercontent.com/assets/7343807/17305908/1679e40a-57fb-11e6-9d10-1058a4089f1f.png)

**Comment by abo-abo** [comment]
Try:

    $ grep -nE "bound" counsel-grep-test.txt > out.txt
    
The contents of the text file is what `counsel-grep` displays.

**Comment by swarnendubiswas** [comment]
`grep` from the command line works fine. I just reproduced the issue on another machine with `emacs -Q` and with the same set of files. The specs are Emacs 25, GNU grep 2.25.

**Comment by abo-abo** [comment]
Eval:

    (shell-command-to-string "grep -nE \"bound\" counsel-grep-test.txt")
    
After that, I'm out if ideas.

**Comment by swarnendubiswas** [comment]
This works. :)

**Comment by abo-abo** [comment]
I still can't reproduce with your config and file. Neither on 24.5.1 or 25. I suggest you try different versions of Emacs or grep.

**Comment by swarnendubiswas** [comment]
Hmm, I tried on yet another machine, a Google VM this time, with Ubuntu 16.04. Emacs is 24.5 and grep is 2.25. I couldn't reproduce the issue. Maybe it has possibly something to do with my Emacs installation, I had built and installed Emacs from the source.

**Comment by swarnendubiswas** [comment]
This could be one possible reason: http://www.joshstaiger.org/archives/2005/07/fixing_garbage.html.

**Comment by swarnendubiswas** [comment]
The tip mentioned in the previous link solved my problem. Thanks for helping me out.
