### ISSUE TITLE
swiper and ivy--regex-fuzzy

### ISSUE THREAD

**Issue by habamax** [abo-abo/swiper#613]
Hi, I have set up fuzzy with

    (setq ivy-re-builders-alist '((t . ivy--regex-fuzzy))))

And it generally works (for find-file, M-x, etc) but swiper still uses space separated search.

Is it possible to apply fuzzy to swiper?

BTW, thanks for ivy and counsel!

**Comment by abo-abo** [comment]
Works for me with this setting:

```elisp
(setq ivy-re-builders-alist
      '((swiper . ivy--regex-fuzzy)
        (t . ivy--regex-plus)))
```

Please test.

**Comment by habamax** [comment]
thx. I will check it as soon as it is on melpa

**Comment by habamax** [comment]
It works, thx a lot!
