### ISSUE TITLE
counsel-find-file how to unselect and create a new file

### ISSUE THREAD

**Issue by QiangF** [abo-abo/swiper#614]
Hello everyone,
The current behavior is when there is no match, it create a file with the search term, but when there is a partial match, I can't find a way to cancel the selection and create a new file. In helm find file, I can use 'C-j' to accept the typed file name so far. How about making counsel behave the same?

**Comment by ardpp** [comment]
Use `C-M-j`

**Comment by abo-abo** [comment]
This is addressed in [FAQ](https://github.com/abo-abo/swiper#frequently-asked-questions). You're not the first person to ask, probably not the last:)
