### ISSUE TITLE
could you tell me  counsel-git-grep-query-replace doing what

### ISSUE THREAD

**Issue by chengyi** [abo-abo/swiper#615]
I was trying to read the code to understand the function of counsel-git-grep-query-replace 
I find it will filter item with regular expression, then replace them, but I don't know  which 
sence the text will match the  regular expression.

could you help me ?

**Comment by abo-abo** [comment]
For example, the input "de tom" is interpreted as "\\bde.*tom\\b", so it will match `defcustom`.
Basically all the matches you see in the minibuffer, highlighted with background faces will be replaced by the same word.

**Comment by chengyi** [comment]
thanks . I see it will only match the `defcustom`.
But I thik the `counsel-git-grep-query-replace` function name seems a little bit strange. Because it can not work on general data.

Plus, there is a bug, the regular expression seems doesn't match the `defcustom`
e.g.:
`
(defcustom doxymacs-doxygen-style
  "JavaDoc"
  "The style of comments to insert into code.
See http://www.stack.nl/~dimitri/doxygen/docblocks.html#docblocks for examples
of the various styles.

Must be one of \"JavaDoc\", \"Qt\" or \"C++\". Setting this variable
to anything else will generate errors."
  :type '(radio (const :tag "JavaDoc" "JavaDoc")
		(const :tag "Qt" "Qt")
		(const :tag "C++" "C++"))
  :group 'doxymacs)
`

**Comment by abo-abo** [comment]
> But I think the counsel-git-grep-query-replace function name seems a little bit strange. Because it can not work on general data.

Works fine for me. Are you by any chance calling it with <kbd>M-x</kbd>? It's only supposed to be called with <kbd>M-q</kbd> from `counsel-git-grep`.

**Comment by chengyi** [comment]
@abo-abo thanks a lot! :+1: I got it. It's really a cool function.
