### ISSUE TITLE
Cannot use multi-* commands with ivy

### ISSUE THREAD

**Issue by d125q** [abo-abo/swiper#619]
Certain commands such as `multi-isearch-buffers` and `multi-occur` ask you to provide a list of buffer names to process and `RET` to terminate said list.  However, when using ivy, it is not possible to use `RET` for that purpose.  Is there any workaround?

**Comment by abo-abo** [comment]
See the first (and currently only) [question](https://github.com/abo-abo/swiper#frequently-asked-questions) in FAQ. The answer is to use <kbd>C-M-j</kbd> to select the current input instead of the current text.

**Comment by bradyt** [comment]
It's unfortunate that users will see the `(RET to end):` at prompt and conclude that something is broken.

**Comment by abo-abo** [comment]
@bradyt Good point. The prompt will now say `(C-M-j to end)`. Thanks.
