### ISSUE TITLE
Feature request: exclusions in ivy-mode pattern

### ISSUE THREAD

**Issue by zhaojiangbin** [abo-abo/swiper#62]
Imagine a project organized as following:

1. Source code were divided in sub-directories, some rather deep: "long/long/path/test/", "long/long/path/io/", "long/long/path/ui/", "longer/path/ui/", "longer/path/io/", ...
2. In "ui/" there were files named "one.cc", "one.h", "two.cc", "two.h", ..., and many more.
3. In "io/" there were files named "one.cc", "one.h", "two.cc", "two.h", ...
4. In "test/" there were "ui/one-test1.cc", "ui/one-test2.cc", "ui/two-test1.cc", "io/one-test1.cc", ..., and many many more.

Let's say that I needed to find some file in "ui/" in `projectile-find-file` using ivy-mode, and I didn't really think of typing "long/long/path/ui/" at the prompt to start with. So I just typed "ui/". Then the many candidates from "long/long/path/test/ui/", and possibly other directories with "ui/" in their paths, showed up first.

At this point, I would have these options:
a) Scroll all the way down until I see candidates starting with "long/long/path/ui/", or
b) Change the pattern to "long/long/path/ui/", or
c) Guess what the target file name could look like and attempt to refine the match.

Note that with option c), even if I guessed a substring, say "one", in the target file name, there could  still be too many entries from other directories left to reveal the target.

I think a fourth option that allows exclusions in the pattern would work a lot better. Supposing that the syntax was to use "!" to lead exclusion sub-patterns, I could simply add " !test/" to the pattern (i.e. the pattern would become "ui/ !test/" at the prompt) to remove candidates that contains "test/".

This is assuming that ivy-mode refines the match by folding through the sub-patterns. Therefore, it would not be too difficult to turn one or some of the folding steps into negation.

This example is actually not completely contrived. I recently started working on a project of more than 8000 files organized in a similar way.

**Comment by tsdh** [comment]
I think something like this is already doable using a custom regex builder for the relevant kind of completion in `ivy-re-builders-alist`.  It might look like this (untested):

```elisp
(defun th/ivy--regex-with-forbidden-words (input)
  (let* (fws
         (input
          (with-temp-buffer
            (insert input)
            (goto-char (point-min))
            (while (re-search-forward "\\(!\\([[:word:]]+\\)\\)" nil t)
              (cl-pushnew (match-string 2) fws)
              (replace-match ""))
            (buffer-substring (point-min) (point-max))))
         (splits (split-string input " +"))
         (frx (if fws
                  (concat "\\(?:"
                          (mapconcat (lambda (fw)
                                       (mapconcat (lambda (s)
                                                    (concat "[^" (regexp-quote s) "]"))
                                                  (split-string fw "" t) ""))
                                     fws "\\|")
                          "\\)*")
                ".*?")))
    (concat "^" frx (replace-regexp-in-string
                     "\\.\\*\\?" frx (ivy--regex input) t t)
            frx "$")))
```

Basically, with that you should be able to type the input `foo bar !test !src-gen` and get candidates that match `foo.*?bar` but neither `test` nor `src-gen` must occur anywhere.

**Comment by tsdh** [comment]
Ah, no, that won't work correctly. What I can think of is allowing a regex builder function to return a cons `(must-match-re . must-not-match-re)`. On top of that, you could build exclusions.

**Comment by abo-abo** [comment]
> This example is actually not completely contrived. I recently started working on a project of more than 8000 files organized in a similar way.

I can appreciate that it's not completely contrived.  And I'm very interested in improving the interface for selecting files.

Would you be willing to generate a reasonable mock-up example that we could use together?  Like a Makefile with a bunch of `mkdir` and `touch` statements that generates this complex directory structure?  Or a git repository that I could clone?

It would be more productive if we had access to the exact same directory structure.  Much easier to specify recipes and debug stuff that way.

**Comment by zhaojiangbin** [comment]
I don't own the said project and it is not open source so I cannot really share it.

In this project, to make the proprietary build system to work, a module "foo" in "product/src/foo" can have a corresponding directory "product/src/bar/include/foo" that is full of symlinks to the C/C++ headers from "foo". You can imagine that `projectile-find-file` lists the symlinks from "product/src/bar/include/foo" ahead of the real files from "product/src/foo" when the pattern is just "foo/".

You can use the boost C++ libraries from www.boost.org for reproduction and testing:
1. Download the boost release archive (current version 1.58) and extract its content.
2. Import it into a git repo (so you don't have to enable the "native" indexing method for projectile).
3. Open a file in the project root to let projectile in.
4. Now suppose you want to find a file in the "utility" module, call `projectile-find-file` and type "utility/" at the prompt. Because "utility" is such a common name, many other modules have a sub-directory called "utility", and files from these sub-directories are often listed first.

**Comment by zhaojiangbin** [comment]
I know, the case with boost isn't exactly the same as the proprietary product one. In the proprietary project,

**Comment by zhaojiangbin** [comment]
Sorry, accidentally closed the issue. Reopen it.

**Comment by abo-abo** [comment]
OK, I got boost v1.58. When I type "utility", I get 234 candidates. What's next?

I would prefer to not do a multi-tier look up, as your "!test" suggestion requires, since it's complex and may fail in unexpected ways. However, if I can reproduce the problem on my machine and see no other way than to go multi-tier, it's possible to implement.

**Comment by tsdh** [comment]
@abo-abo What do you mean with multi-tier lookup?

**Comment by abo-abo** [comment]
> What do you mean with multi-tier lookup?

I mean that it's impossible to build a single regex for "foo !bar".  Instead, two passes of `string-match` would be needed.  The current logic is well-suited for using a single regex, so I want to try to avoid multi-tier.

**Comment by tsdh** [comment]
Ok, got it.  Yes, you need to match twice with exclusions.  But I don't see why that's a big deal.  For the forbidden regexp you can use `string-match-p` which won't alter your match data if that's your problem.

**Comment by abo-abo** [comment]
> that's your problem

That isn't a problem, actually. I'm thinking more of escaping stuff.  I still haven't configured a way to escape single spaces. Now, I would have to add "!" to my escape TODO-list.

One more thing that I'm thinking about is efficiency, but it shouldn't be a big deal, especially if the user arranges the query in a way that the first regex would filter out most of the stuff.

**Comment by tsdh** [comment]
IMHO, you should only define the base architecture for exclusions and then user's can make use of that using `ivy-re-builders-alist` and decide on their own if they want to give ! or !! or something else a special meaning.

**Comment by abo-abo** [comment]
Yes, something like your comment could work. I'm thinking maybe:

```elisp
'(("match1" . t) ("match2" . t) ("match3" . nil))
```

where `t` means it should match, and `nil` means it shouldn't match. The filtering would be done in a sequence, with the first regex being the main one for the purpose of extra faces etc.

**Comment by tsdh** [comment]
Sounds good to me.

**Comment by tsdh** [comment]
Nice.  This should have some documentation in `ivy-re-builders-alist`, i.e., that the re-builders may also return an alist of the form `((pattern1 . t) (pattern2 . t) (pattern3 . nil)...)`.

**Comment by zhaojiangbin** [comment]
I tried the fix today. Am I understanding it correctly that there can be only one exclusion?

Using `projectile-find-file` in boost for example, if the pattern is `utility/ !log/`, the candidates are every file name that contains "utility/" and does not contain "log/". This is what I would expect.

But if I want to exclude more, such as "spirit/", changing the pattern to `utility/ !log/ !spirit/` does not work. And this `Error in post-command-hook (ivy--exhibit): (error "Unexpected: use only one !")` breaks ivy mode (I am going to open a new issue for this breakage and it is easy to reproduce for yourself.)

**Comment by tsdh** [comment]
The syntax is `utility/ ! log/ spirit/`, I.e., the exclamation mark separates the patterns that must match from those that must not match.

**Comment by abo-abo** [comment]
> (error "Unexpected: use only one !")

Yeah, that's me sending the error because you used more than one `!`.
I didn't want to turn the input into a bunch of complex rules that need parsing.
So for the current approach:

- the stuff that you want is space-separated on the left of `!`
- the stuff that you don't want is space-separated on the right of `!`

**Comment by zhaojiangbin** [comment]
> The syntax is utility/ ! log/ spirit/, I.e., the exclamation mark separates the patterns that must match from those that must not match.

Hmm, this does not work for me though. I have a project with following files: "src/output/main.cpp", "src/merge/main.cpp", "src/fab/main.cpp", "src/print/main.cpp" and a bunch others .cpp files under each directory. With input `src main ! fab`, I get `src/{output,merge,print}/main.cpp` in the candidate list. But once I append a space and any non-space character (like `src main ! fab m` or even `src main ! fab x`), the entry "src/fab/main.cpp" is added back to the candidate list.

**Comment by abo-abo** [comment]
> But once I append a space and any non-space character (like src main ! fab m or even src main ! fab x), the entry "src/fab/main.cpp" is added back to the candidate list.

You're right, it's a bug.
