### ISSUE TITLE
swiper-all does not work with ivy--regex-ignore-order

### ISSUE THREAD

**Issue by Wilfred** [abo-abo/swiper#620]
From `emacs -q`, I loaded ivy.el, swiper.el, counsel.el and colir.el from git (commit 83f7ae6).

I then configured ivy to use `ivy--regex-ignore-order` with:

```emacs-lisp
(setq ivy-re-builders-alist
      '((t . ivy--regex-ignore-order)))
```

My second search term is ignored with `swiper-all`.

![swiper_all](https://cloud.githubusercontent.com/assets/70800/17539326/41c4c400-5e7b-11e6-9d4c-b2d365ac358f.png)

As pictured, swiper has narrowed to `defun`, but the `counsel` has been ignored.

**Comment by abo-abo** [comment]
Thanks, please test. If you have time, patches for making `swiper--add-overlays` work with `ivy--regex-ignore-order` are welcome.

**Comment by Wilfred** [comment]
Works well, thank you :)
