### ISSUE TITLE
With org-indent-mode and visual-line-mode, swiper goes to wrong line

### ISSUE THREAD

**Issue by sooheon** [abo-abo/swiper#621]
I can reproduce this with the following file: https://gist.github.com/sooheon/bb1dac96827fefd4f47115e742f2723a

With major-mode Org, when both `org-indent-mode` and `visual-line-mode` on, search for `chebyshev` with swiper. The wrong line is highlighted, and C-j takes you to the wrong line.

**Comment by abo-abo** [comment]
Can't reproduce. Please try reproduce with:

    $ make plain
    
from this repository's root.

**Comment by sooheon** [comment]
Can you try in a 80x24 window? I can reproduce it using the above steps if the window is small (i.e. lines wrap).

**Comment by abo-abo** [comment]
Still works fine. GNU Emacs 25.1.50.6.

**Comment by abo-abo** [comment]
24.5.2 works fine as well.

**Comment by sooheon** [comment]
I'm on emacs 25.1.1 and Org 8.2.10

I'll try with different versions as well.

**Comment by sooheon** [comment]
Can't reproduce it in regular compiled emacs, may be an interaction with emacs-mac port, dunno the exact reason. I've just decided not to use org-indent and visual-line though.
