### ISSUE TITLE
ivy-recentf should be called counsel-recentf?

### ISSUE THREAD

**Issue by hmelman** [abo-abo/swiper#624]
I just learned about `ivy-recentf`. It's a minor point, but it seems to me this is more properly called `counsel-recentf`. 

I feel the same about  `ivy-switch-buffer` and  `ivy-switch-buffer-other-window`. Every other command at this level (replacing an existing emacs command as opposed to implementing `ivy-mode`) seems to be in counsel.

I get that renaming them at this point could be an issue for some (though the package is still young), perhaps just an alias that calls through as a transition period would help.

**Comment by abo-abo** [comment]
I don't mind renaming to `counsel-recentf`. However, `ivy-switch-buffer` is part of `ivy-mode` and should stay there.
