### ISSUE TITLE
Warning when using counsel-find-file in conjunction with diff-hl

### ISSUE THREAD

**Issue by drot** [abo-abo/swiper#627]
`GNU Emacs 25.1.1 (x86_64-unknown-linux-gnu, X toolkit, Xaw scroll bars) of 2016-07-24`

Enabling the following modes:

`(global-diff-hl-mode 1)`
`(counsel-mode 1)`

I get the following warning on the first file I visit after Emacs has started (init.el in this example):
`Making find-file-hook local to init.el while let-bound!`

The warning only displays once, after that I can visit other files and it will not display again.

**Comment by abo-abo** [comment]
This is OK, just a regular Emacs message. What happens here, is that `counsel-find-file` temporarily sets `find-file-hook` to nil for remote files. This should result in a remote file opening faster.

If you don't like this behavior, you can disable it with:

```elisp
(setq counsel-find-file-speedup-remote nil)
```

**Comment by drot** [comment]
Thank you for the clarification, though the warning still appears after setting `counsel-find-file-speedup-remote` to nil.

**Comment by abo-abo** [comment]
I can't reproduce your issue actually. It has to be something in your config.

**Comment by drot** [comment]
This is all I have in my init file started from scratch with a blank file:

```
(package-initialize)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/"))

(global-diff-hl-mode 1)
(counsel-mode 1)
(setq counsel-find-file-speedup-remote nil)

(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(package-selected-packages (quote (diff-hl counsel))))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )
```

**Comment by abo-abo** [comment]
I see the problem now: even with `counsel-find-file-speedup-remote` off, `counsel-find-file` let-binds `find-file-hook` to itself.

And `diff-hl-mode` has this code:

```elisp
(add-hook (if vc-mode
                      ;; Defer until the end of this hook, so that its
                      ;; elements can modify the update behavior.
                      'diff-hl-mode-on-hook
                    ;; If we're only opening the file now,
                    ;; `vc-find-file-hook' likely hasn't run yet, so
                    ;; let's wait until the state information is
                    ;; saved, in order not to fetch it twice.
                    'find-file-hook)
                  'diff-hl-update t t)
```

Which means that it locally sets `find-file-hook` if the file isn't version controlled. Which is pretty weird, if you ask me. I suggest you report this as an issue vs `diff-hl`.

**Comment by drot** [comment]
Thank you for the pointers once again, I will file an issue for `diff-hl`.

**Comment by dgutov** [comment]
> Which is pretty weird, if you ask me. I suggest you report this as an issue vs diff-hl.

I'm within my rights to do that, and it serves a purpose. What makes you say it's a bug?

**Comment by abo-abo** [comment]
@dgutov It seems strange for the minor mode to locally set `find-file-hook`: the file was already opened, why bother setting the hook locally for the exact same file? It won't be called again.  It becomes weirder when globalized.

I would suggest for the globalized mode to set `find-file-hook` not in a buffer-local way, and for the plain minor mode to not touch it at all.

**Comment by dgutov** [comment]
If `vc-mode` is nil, we're in the process of running `find-file-hook`, and `vc-refresh-state` hasn't been called yet.

**Comment by drot** [comment]
Same warning happens also when using the` git-gutter` package.
