### ISSUE TITLE
How to: use custom regex builder for `Counsel-M-x`

### ISSUE THREAD

**Issue by srustamo** [abo-abo/swiper#628]
The manual shows one example of custom regexp builders so:
``` 
(setq ivy-re-builders-alist
      '((read-file-name-internal . ivy--regex-fuzzy)
        (t . ivy--regex-plus)))
```
How to achieve the same for `counsel-M-x` function? Is there a list of arguments accepted by `completing-read` function?

My goal is to use `ivy--regex-plus` for <kbd>C-s</kbd> and `ivy--regex-fuzzy` for <kbd>M-x</kbd>.

**Comment by abo-abo** [comment]
Like this:

```elisp
(setq ivy-re-builders-alist
      '((read-file-name-internal . ivy--regex-fuzzy)
        (counsel-M-x . ivy--regex-fuzzy)
        (t . ivy--regex-plus)))
```

**Comment by srustamo** [comment]
Thank you.
