### ISSUE TITLE
counsel-M-x: is it possible sort commands by recent used?

### ISSUE THREAD

**Issue by tumashu** [abo-abo/swiper#629]
smex seem to stop developing, this feature should building swiper instead of require smex

**Comment by abo-abo** [comment]
The feature is already there for a long time. If you have `smex` installed, `counsel-M-x` will automatically use it.

**Comment by tumashu** [comment]
Is this feature  not depend this: https://github.com/nonsequitur/smex/pull/51 ?

**Comment by abo-abo** [comment]
No. That PR is just for the `smex` function, `counsel-M-x` does more than `smex` with that PR.

**Comment by tumashu** [comment]
ok，thanks!
