### ISSUE TITLE
How to: start `ivy-occur-mode` buffer in Emacs mode from `evil` major mode

### ISSUE THREAD

**Issue by srustamo** [abo-abo/swiper#630]
I mostly spend my time in `evil` mode, and once in a while it seems it is better to have the "in-built" mode, like `ivy-occur-mode`, which offers its own key-bindings quite similar to `evil`, but adds some more.

`evil` has a var `evil-emacs-state-modes`, where I include the names of the modes I want `evil` off. I tried to put `(ivy-occur-mode)` in it, but `ivy-occur-mode` still opens a buffer in `evil` mode. 

Interestingly, putting `(ivy-mode)` into the above var works, but of course, all buffers where `ivy-mode` is active (pretty much everywhere) disable `evil`.

In past I had to play a bit with the name of the mode, to get it right. Sometimes the mode name is not what is listed in <kbd>C-h-m</kbd>. Perhaps this is one of those cases?

**Comment by abo-abo** [comment]
There's `ivy-occur-mode` and `ivy-occur-grep-mode`.

**Comment by srustamo** [comment]
Thanks, adding `ivy-occur-grep-mode` fixed the issue.
