### ISSUE TITLE
Possible problem with ivy-partial-or-done and tramp

### ISSUE THREAD

**Issue by justbur** [abo-abo/swiper#633]
Steps:
1. counsel-find-file
2. //sud
3. TAB TAB (ivy-partial-done twice)
Weird Result

```
sudo:root@
sudo:localhostname:
sudo:sudo:
```

Continuing to select `sudo:root@` for example leads to a weird state that I need to exit. The following alternative works fine.
Steps:
1. counsel-find-file
2. //sud
3. ivy-alt-done
Result

```
root@sudo
root@localhostname
root@localhost
...
```

**Comment by abo-abo** [comment]
Thanks, I can reproduce. Will try to fix later.

Another good method that works:

1. counsel-find-file
2. /sudo:: (note the single slash)
3. ivy-alt-done

Opens sudo in the current directory.

**Comment by justbur** [comment]
Thanks. That third method is the best of the three.

**Comment by basil-conto** [comment]
I can no longer reproduce this recipe. After either step (3), a new buffer called `sud` is created visiting write-protected file `/sud`.

What does invoke TRAMP completion is `//sudo:`<kbd>TAB</kbd><kbd>TAB</kbd>, but I never seem to get into a weird state.

Any chance of a new recipe for this?

**Comment by justbur** [comment]
I can't either, and I'm seeing the same behavior as you @basil-conto
