### ISSUE TITLE
Automatic buffer scroll to candidate on `j` `f` press in `ivy-occur` buffer

### ISSUE THREAD

**Issue by srustamo** [abo-abo/swiper#635]
I sometime see such automatic scroll, sometime I don't. What does it depend on?

**Comment by abo-abo** [comment]
Pressing <kbd>c</kbd> toggles the auto-scroll.

**Comment by srustamo** [comment]
Is there an option to set auto-scroll default value?

**Comment by abo-abo** [comment]
What do you mean by that? Set it to on by default? You can probably do it by modifying `ivy-occur-mode-hook` or `ivy-occur-grep-mode-hook`.

**Comment by srustamo** [comment]
Thanks.
