### ISSUE TITLE
counsel-describe-foo functions do not respect help-window-select variable

### ISSUE THREAD

**Issue by sooheon** [abo-abo/swiper#639]
`help-window-select` controls whether Help-mode buffers are auto selected or not. If you set this to `t`, help buffers spawned by `C-h v` `C-h f` etc. should be selected, to quit with `q`. But the counsel equivalents, `counsel-descbinds`, `counsel-decribe-function`, etc., do not follow this selection behavior. It appears to be a recent regression, about a week ago these were working for me.

**Comment by abo-abo** [comment]
Thanks, this is indeed due to a recent change. I'm trying to phase out the need for using `with-ivy-window` in the action functions. This can cause a few regressions, but I think it's worth it in the end.

**Comment by sooheon** [comment]
Thanks for the quick fix and context.
