### ISSUE TITLE
ivy-mode: default in prompt not updated as input killed to empty

### ISSUE THREAD

**Issue by zhaojiangbin** [abo-abo/swiper#64]
Problem seen obvious in `switch-to-buffer` and `kill-buffer`.

Use `switch-to-buffer` as example:
1. Start Emacs.
2. Open "/tmp/a.txt", confirm if non-existent.
3. Open "/tmp/b.txt", confirm if non-existent.
4. Open "/tmp/c.txt", confirm if non-existent.
5. Call `switch-to-buffer`. Notice the prompt says "(default b.txt)" and ivy selects "b.txt" as well. At this point, pressing <kbd>RET</kbd> visits buffer "b.txt", as expected.
6. Input "a.t" at the prompt, then <kbd>C-a C-k</kbd>, or <kbd>DEL</kbd> three times.
7. Now the prompt string still says "(default b.txt)" but ivy keeps selecting "a.txt". At this point, pressing <kbd>RET</kbd> visits "a.txt". This is arguably not as expected.

**Comment by zhaojiangbin** [comment]
For different commands, it might not be always possible to update their default in the prompt string once ivy has changed the current selection. In such case, ivy probably should go back to where it started - select the default again when the input is empty.

**Comment by abo-abo** [comment]
Thanks, should be fixed now.
