### ISSUE TITLE
`ivy-last-filtered`  and `ivy-resume-filtered`

### ISSUE THREAD

**Issue by redguardtoo** [abo-abo/swiper#640]
`ivy-last-filtered` is the filtered candidates before execution of the `:action` part of `ivy-read`

`ivy-resume-filtered` basically runs `ivy-read`  with `ivy-last-filterred` as collection and initial-input is empty.

Use case is like I need manually check all the files containing string "helloworld", I want to run `M-x counsel-git-grep` and input `helloworld` only once.

**Comment by abo-abo** [comment]
Please elaborate on what you want, it's not clear to me.

**Comment by redguardtoo** [comment]
Looks it's my osx is not upgraded to latest ivy, forget this issue.
