### ISSUE TITLE
swiper--candidates: Symbol’s function definition is void: ivy-cleanup-string

### ISSUE THREAD

**Issue by jkitchin** [abo-abo/swiper#641]
For a while I have been getting this error:
swiper--candidates: Symbol’s function definition is void: ivy-cleanup-string

when using counsel-grep-or-swiper

As far as I know, I am using these packages from MELPA
counsel-20160825.238
ivy-20160818.708  
swiper-20160825.329

oddly, it doesn't seem to happen all the time. In some buffers it seems to magically work again, and then stops working. Any ideas on what might be happening?

**Comment by abo-abo** [comment]
`ivy-cleanup-string` is defined in ivy.el.

Try to use `find-library` `ivy`. Or `counsel-load-library` `ivy` with <kbd>C-.</kbd> instead of <kbd>RET</kbd>.

**Comment by jkitchin** [comment]
That is probably it. I found an old ivy installed in a .emacs.d folder. After deleting it, things seem to work now. Thanks!
