### ISSUE TITLE
"Smart" recenter after swiper finishes

### ISSUE THREAD

**Issue by ddovod** [abo-abo/swiper#642]
Hi.
First, thank you very much for ivy and swiper! These packages are really cool and handy.
But I'm experiencing some pain when using swiper. While swiper is launched (I mean it is searching at this time), my cursor has some position on the screen (vertical position). After I finish with swiper and press "enter", the cursor change its vertical position to some other. If I enable "recenter", my cursor position is always at the middle of the buffer. But It's were very good if the cursor will not change its "relative" position (I don't want buffer to be scrolled at all) after I finish searching, so I should not find it on the screen again (I mean exactly the same position, with respect of minibuffer size and other stuff). Is there a way to achieve such behavior? Thank you again!

**Comment by thwg** [comment]
I noticed this as well when recently starting to use swiper.  Since I had `scroll-conservatively` set, it was causing the selection to jump to the top or bottom of the window after making my selection.

I submitted a patch above, could you check and see if it resolves the problem for you as well?

**Comment by ddovod** [comment]
Yes, that's exactly what I'm looking for! Thank you a lot!
