### ISSUE TITLE
Way to hide some buffers from ivy-switch-buffer?

### ISSUE THREAD

**Issue by erreina** [abo-abo/swiper#644]
How can we hide temporary buffers which are enclosed with \* in `ivy-switch-buffer`? 

I tried writing `^[^*]` and it remove them but mark the start character as matched so, for example, if I have the buffer "init-ivy.el" typing init discards that buffer.

I have the same issue with `counsel-find-file` when typing `^[^.]`.

Any hint of how I can achieve that?

OT: wonderful package, I start using ti two days ago and I love it!

**Comment by abo-abo** [comment]
In Emacs, temporary buffers start with a space and are already hidden by default in `ivy-switch-buffer`.
Buffers with `*` are not temporary, the asterisks usually denote that the buffer does not have a file: for instance, `*scratch*`.

But your request is possible:

    (setq ivy-ignore-buffers '("\\` " "\\`\\*"))

**Comment by erreina** [comment]
Thank you for the quick response and pointing me out to ```ivy-ignore-buffers```. However, I don't want to ignore them all the time. I think I can create a function that modify ```ivy-ignore-buffers```, but how I tell ivy to refresh the candidate list?

**Comment by erreina** [comment]
In ```counsel-find-file``` when using ```(setq counsel-find-file-ignore-regexp "\\`\\.")``` we can access the dotfiles if the input starts with a dot. I think it would be nice to have the same behaviour in ```ivy-switch-buffer``` but with the star.

**Comment by alphor** [comment]
hey erreina, if you want to create personalized buffer listings, so that for example you can bind them to keys, you can use this:

``` elisp
(defun my-ivy-switch-buffer (regex-list)
  (let ((ivy-ignore-buffers regex-list))
    (ivy-switch-buffer)))

(defun my-show-only-irc-buffers ()
  (interactive)
  (my-ivy-switch-buffer '("^[^#]")))

(defun my-also-ignore-star-buffers ()
  "ignore everything starting with a star along with whatever ivy's defaults are"
  (interactive)
  (my-ivy-switch-buffer (append ivy-ignore-buffers `("^\*"))))

(global-set-key (kbd "C-c i") `my-also-ignore-star-buffers)
```

**Comment by shackra** [comment]
I would specify which buffers I would ignore, there are some I will never look at them, using something general as `^[^*]` is indeed bad idea.

**Comment by tautologyclub** [comment]
Just as a friendly tip to those that MOST OF THE TIME wants to ignore star buffers but not always:

Use (setq ivy-ignore-buffers '("\\` " "\\`\\*")) and whenever you want to un-ignore the star buffers inside of Ivy, just press C-c C-a to run "toggle user-defined filters" or whatever it's called.

**Comment by basil-conto** [comment]
> just press C-c C-a to run "toggle user-defined filters" or whatever it's called.

`ivy-toggle-ignore`.

What's the status on this issue?

**Comment by abo-abo** [comment]
@basil-conto I think it can be closed. <kbd>C-c C-a</kbd> with customization should be sufficient.
