### ISSUE TITLE
Install counsel, get an error: need swiper

### ISSUE THREAD

**Issue by Trevoke** [abo-abo/swiper#645]
I installed counsel through package-list-packages and I got the following error:

> counsel.el:36:1:Error: Cannot open load file: No such file or directory, swiper

This should probably be marked as a dependency so swiper gets pulled in automatically?

**Comment by abo-abo** [comment]
This is likely a MELPA hiccup. Just restart Emacs and try to reinstall.

**Comment by dieggsy** [comment]
@Trevoke I assume this is resolved?

@abo-abo In any case, this doesn't sound like an actual issue with swiper, so it should be ok to close?

**Comment by Trevoke** [comment]
Oh man. This is so old. Yeah, I haven't had this error in forever. Sorry I didn't close it before, closing it now.
