### ISSUE TITLE
How to use the full path in kill-ring while using counsel-find-file?

### ISSUE THREAD

**Issue by kaushalmodi** [abo-abo/swiper#647]
As the question says, I am wondering if there is a convenient way to use the full path that I would have copied to the kill-ring.

Let's say that I have copied a path `/some/absolute/path/to/file.el` and I want to open that file.

I have bound `C-x C-f` to `counsel-find-file`. When I paste a path in there, I cannot find a way to completely replace the initial input. So if the initial input is `~/.emacs.d/`, pasting the kill-ring content makes it `~/.emacs.d//some/absolute/path/to/file.el`.

Do you have a way to make `counsel-find-file` behave as the default `find-file` momentarily so that I can just paste the path and open that file directly?

**Comment by abo-abo** [comment]
Maybe I don't fully understand, but pressing <kbd>C-x C-f C-y</kbd> followed by <kbd>C-m</kbd> or <kbd>C-j</kbd> opens the file for me. Isn't that what you want?

**Comment by kaushalmodi** [comment]
You're right, it works that way!

I just did not proceed to the final `C-m` hit because I saw this :)

![image](https://cloud.githubusercontent.com/assets/3578197/18172173/6f6d87f2-7032-11e6-9f12-10ac6be87147.png)

**Comment by abo-abo** [comment]
The behavior is the same as `find-file` dealing with `//`.

I could do something fancy, like e.g. `cd` to `setup-files` and insert `setup-ag.el`, but the `cd` is likely an unwanted side-effect that's hard to cancel. Whereas with the current way, you can <kbd>C-y</kbd> and undo with <kbd>C-_</kbd> or <kbd>C-k</kbd>.

It's a bit unfortunate that it appears that there's 0 cands, but the tradeof with the above advantage is worth it, I think.

**Comment by kaushalmodi** [comment]
> but the cd is likely an unwanted side-effect that's hard to cancel. 

I agree. I am fine with this workaround.
