### ISSUE TITLE
Auto resize minibuffer window ?

### ISSUE THREAD

**Issue by Yevgnen** [abo-abo/swiper#649]
Hi, I'm trying to switch from `helm` to `swiper` since `ivy` is really much faster. How can I make the minibuffer window to auto resize base on the number of the candidates? I've set `ivy-fixed-height-minibuffer` to nil (default), but seems doesn't work.

<img width="749" alt="screen shot 2016-09-04 at 08 52 45" src="https://cloud.githubusercontent.com/assets/16749790/18228341/f891cfba-727c-11e6-9ab4-5cd2e09e1576.png">

Any help will be appreciated! Thanks!

By the way, I like the high integrated `helm`'s interface but I prefer `ivy`'s completion system :)

**Comment by abo-abo** [comment]
The minibuffer will automatically grow up to `ivy-height` lines (15 is the default).

Unfortunately, due to the way Emacs minibuffer works, I currently don't know if it's possible to shrink the minibuffer window. Suggestions welcome.

**Comment by Yevgnen** [comment]
Thanks for you reply! But what's difference when `ivy-fixed-height-minibuffer` is set to `t` or `nil` ?

By the way, when there's no matches, I got

<img width="135" alt="screen shot 2016-09-05 at 17 34 11" src="https://cloud.githubusercontent.com/assets/16749790/18243717/fb0db908-738e-11e6-9379-3e462ca712d3.png">

**Comment by abo-abo** [comment]
The difference is that with the default settings you'll get a 3 line high minibuffer when you eval:

```elisp
(ivy-read "test:" '("1" "2"))
```

But with `ivy-fixed-height-minibuffer` set, the height will be 15, not 3.


> By the way, when there's no matches, I got

That's what it's supposed to look like.

**Comment by Yevgnen** [comment]
Got it! Thanks! `swiper` is awesome!

**Comment by therockmandolinist** [comment]
> Unfortunately, due to the way Emacs minibuffer works, I currently don't know if it's possible to shrink the minibuffer window. Suggestions welcome.

I'm wondering if something similar to the current option when pressing `C-o <` (which I believe executes the command `hydra-ivy/ivy-minibuffer-shrink`) could help here? So if the number of results < the height in lines, adjust based on the same method this function uses, by the adequate number of lines. 

I barely dabble in elisp beyond my own init file though, so I'm mostly just thinking aloud here.

**Comment by andrebeat** [comment]
This may be a bit off-topic but would it be feasible to provide results in a different window (similar to what helm does)?

**Comment by abo-abo** [comment]
@andrebeat It's possible to do it in a different window, see `ivy-display-function`. But doing it there brings a whole set of other problems, e.g. resizing the current window configuration to fit in another window.

**Comment by basil-conto** [comment]
Does setting `resize-mini-windows` to `t` resolve this issue? See also #1807 and #1809.

**Comment by Yevgnen** [comment]
No...

**Comment by basil-conto** [comment]
@Yevgnen Could you please elaborate?

**Comment by Yevgnen** [comment]
Sorry...

> Unfortunately, due to the way Emacs minibuffer works, I currently don't know if it's possible to shrink the minibuffer window. Suggestions welcome.

Setting the `resize-mini-windows` to `t` changes nothing. I currently have no idea about this and maybe it's probably impossible to have this feature... The issue may also in packages like `ido-vertical-mode`.

**Comment by basil-conto** [comment]
I see. Though setting `resize-mini-windows` doesn't resolve the issue at the moment, I think it should be made to do so, either by patching Ivy or even Emacs itself.

**Comment by jcs090218** [comment]
I have this, and it works.

```el
(defun ivy-resize--minibuffer-setup-hook ()
  "Minibuffer setup hook."
  (add-hook 'post-command-hook #'ivy-resize--post-command-hook nil t))

(defun ivy-resize--post-command-hook ()
  "Hook run every command in minibuffer."
  (when ivy-mode
    (shrink-window (1+ ivy-height))))

(add-hook 'minibuffer-setup-hook 'ivy-resize--minibuffer-setup-hook)
```

But I have no idea why it works.

**Comment by Yevgnen** [comment]
@jcs090218 That looks interesting!

**Comment by abo-abo** [comment]
Thanks, please test.
