### ISSUE TITLE
Can't change selected buffer candidate when input is empty

### ISSUE THREAD

**Issue by tsdh** [abo-abo/swiper#65]
With https://github.com/abo-abo/swiper/commit/eb43e4a5096462bd819c61ef54903ac9a038b60a when I do `C-b b` I get all buffers as candidates, and the "other buffer" is preselected.  However, when I hit `<up>` or `<down>` to select another candidate, nothing happens.  Only after I've typed at least one char as input pattern `<up>` and `<down>` start working again.

**Comment by abo-abo** [comment]
Oops, sorry. Should be fixed now.

**Comment by tsdh** [comment]
Yes, it is.
