### ISSUE TITLE
imenu *Rescan* not needed if imenu-auto-rescan is t

### ISSUE THREAD

**Issue by Dickby** [abo-abo/swiper#650]
If imenu-auto-rescan is t, the option _Rescan_ is not needed inside the imenu.

**Comment by abo-abo** [comment]
Can you be more specific, I don't understand what you want.

**Comment by Dickby** [comment]
The first entry in counsel imenu is always "*Rescan*" for rescanning the active buffer.
if the variable "imenu-auto-rescan" is set to t, the buffer is rescanned every time i use imenu, i think that the "*Rescan*" entry is not needed in that case. 
I know that imenu has the "*Rescan*" option by itself, but with counsel it is always visible, I don't know if it is easily possible to hide this option in counsel-imenu, but it would be nice.

**Comment by abo-abo** [comment]
> The first entry in counsel imenu is always "Rescan" for rescanning the active buffer.

I never see "Rescan". What versions are you using (Emacs/swiper)?

**Comment by Dickby** [comment]
emacs version 25.1.5
swiper from melpa swiper-20160901.737

**Comment by Wilfred** [comment]
I think this is an Emacs bug, not a counsel issue.

`M-x imenu` offers `*Rescan*` regardless of the value of `imenu-auto-rescan`. I agree that in this case, Emacs should not offer `*Rescan*`.

However, if you use `M-x counsel-imenu`, `*Rescan*` is never offered.

**Comment by Dickby** [comment]
Right,
thanks!
