### ISSUE TITLE
Strange font lock of swiper

### ISSUE THREAD

**Issue by Yevgnen** [abo-abo/swiper#651]
Hi!

I read the excellent post [Better fuzzy matching support in Ivy](http://oremacs.com/2016/01/06/ivy-flx/) and try it(integrating `flx`) in my Emacs, but find something strange of `swiper`.

Inputing exactly the same thing (the candidate as manually input content and the query) as the last image in the link, `swiper` and `ivy-minibuffer-*` gives 

<img width="749" alt="screen shot 2016-09-05 at 20 21 02" src="https://cloud.githubusercontent.com/assets/16749790/18247726/bb491912-73a6-11e6-9af7-401293dc714e.png">

But `counsel-M-x` gives 
<img width="749" alt="screen shot 2016-09-05 at 20 25 01" src="https://cloud.githubusercontent.com/assets/16749790/18247743/dc689fc8-73a6-11e6-9c21-c4c4c8ae666f.png">
which is the same as the image given in the post.

Shouldn't they have similar font lock ? I mean, the matched neighbouring char should have the same color in the `swiper` case.

A minimum test snippet is 

    (require 'package)
    
    (setq package-archives '(("marmalade" . "http://marmalade-repo.org/packages/")
                             ("gnu" . "http://elpa.gnu.org/packages/")
                             ("melpa" . "https://melpa.org/packages/")
                             ("org" . "http://orgmode.org/elpa/")))
    
    (package-initialize)
    
    (unless (and (file-exists-p (expand-file-name "elpa/archives/marmalade" user-emacs-directory))
                 (file-exists-p (expand-file-name "elpa/archives/gnu" user-emacs-directory))
                 (file-exists-p (expand-file-name "elpa/archives/melpa" user-emacs-directory))
                 (file-exists-p (expand-file-name "elpa/archives/org" user-emacs-directory)))
      (package-refresh-contents))
    
    (unless (package-installed-p 'use-package)
      (package-refresh-contents)
      (package-install 'use-package))
    
    (setq use-package-verbose t
          use-package-enable-imenu-support t)
    (require 'use-package)
    
    (use-package swiper
      :ensure t
      :bind (("C-s" . swiper))
      :init (setq ivy-height 15
                  ivy-count-format "(%d/%d) "
                  ivy-use-virtual-buffers t
                  ivy-initial-inputs-alist nil
                  ivy-re-builders-alist '((t . ivy--regex-fuzzy))
                  swiper-include-line-number-in-search t)
    
      (use-package flx
        :ensure t
        :after swiper))

    ;; Test content from the post
    ;; visual-line-mode
    ;; global-visual-line-mode
    ;; doc-view-set-slice-using-mouse
    ;; vc-git-log-view-mode
    ;; vc-git-log-edit-mode
    ;; hydra-vi-toggle/whitespace-mode-and-exit
    ;; variable-pitch-mode
    ;; hydra-vi-toggle/auto-fill-mode-and-exit
    ;; doc-view-set-slice-from-bounding-box

Thanks!

**Comment by abo-abo** [comment]
Please test, I had to change a lot of stuff.

**Comment by Yevgnen** [comment]
Thanks for you quick fix ! I'm glad to see this after I wake up.

Now I find something new in the newest commit
<img width="1386" alt="screen shot 2016-09-06 at 07 45 03" src="https://cloud.githubusercontent.com/assets/16749790/18258328/fb85fac2-7405-11e6-854b-72a5aee12281.png">

You can see that regex match in the minibuffer and in the origin buffer is inconsistent. For instance, I think both of them should highlight the substring `name`.

**Comment by abo-abo** [comment]
The highlight in the buffer is new, and I think it's superior:
![swiper-fuzzy-highlight](https://cloud.githubusercontent.com/assets/2937359/18275813/e70f7ae4-7448-11e6-8261-bbe36f40cce8.png)

The highlight in the minibuffer is done using flx, which is usually used for fuzzy sorting (all commands except swiper). I think it's useful to keep the highlights by flx in the minibuffer, since it gives insight into how it sorts. But removing the flx highlight specifically for swiper isn't worth the hassle, I think. But I'll keep it in mind, might replace it with the new highlight function once it's stable.

**Comment by Yevgnen** [comment]
Thanks for your explanation.
