### ISSUE TITLE
counsel-git-log produces "error code 1"

### ISSUE THREAD

**Issue by glucas** [abo-abo/swiper#652]
Trying out `counsel-git-log` for the first time and I always get an error code. I'm running on Windows so my guess is some issue with my environment, but figured it is worth reporting.

**Comment by glucas** [comment]
OK, it does seem to be an environment issue. In the `*counsel*` buffer I found: 

    'GIT_PAGER' is not recognized as an internal or external command, operable program or batch file.

**Comment by abo-abo** [comment]
Just try running the same command in the shell. This is what `counsel-git-log-function` calls for input `test`:

    $ GIT_PAGER=cat git log --grep 'test'

**Comment by glucas** [comment]
Thanks for the quick reply. I updated my comment above: my shell isn't bash so setting the variable this way doesn't work.

Not sure the best way to do this without depending on the Unix-style variable. This works with something like 

    cmd /C "set GIT_PAGER=cat && git log --grep 'test'"

to run the command in a separate shell. Otherwise something like setting and then reverting the variable would be necessary.

Maybe just requiring a bash-style shell is sufficient here.

**Comment by abo-abo** [comment]
Customize `counsel-git-log-cmd` and see if it works. You're on Windows, right?

**Comment by glucas** [comment]
Yes, I'm on Windows. 

Thanks, this works for me:

    (setq counsel-git-log-cmd "git log --grep \"%s\"")

This also works:

    (setq counsel-git-log-cmd "set GIT_PAGER=cat && git log --grep \"%s\"")
