### ISSUE TITLE
Performance regression in commit e98883f50f5794

### ISSUE THREAD

**Issue by hpdeifel** [abo-abo/swiper#653]
Ivy is currently so slow for me that it is barely usable. Typing letters has a noticeable lag. `git bisect` revealed commit e98883f50f5794 as the culprit.

This lag happened in all ivy commands that I tested (`counsel-M-x`, `ivy-find-file` and a few others).

I can't reproduce it with plain `emacs -Q`, but calling `(package-initialize)` with an otherwise empty config suffices to show the bug.

Replacing `(require 'flx nil 'noerror)` with `nil` in `ivy--format-minibuffer-line` also makes ivy fast again.

**Comment by abo-abo** [comment]
Works fine for me. Here's the profiler result:

    ivy--exhibit                              33          0.271637048   0.0082314256
    
Less than 0.01 second is spent on filtering and redisplay after each key press.

**Comment by hpdeifel** [comment]
I get

     ivy--exhibit   59          8.5247626979  0.1444875033

that doesn't sound much, but feels incredibly laggy.

`profiler.el` says that 86% of the time is spend in the `and` in `ivy--format-minibuffer-line` where the `(require 'flx nil 'noerror)` is that I mentioned. Strangely it doesn't show any children of this `and`.

Keep in mind that this only happens when `(package-initialize)` is called. I have quite a number of packages installed, so maybe the `require` has to go through all these package include paths to determine that flx is not there. Profiling `require` itself gives me:

    require        1276        8.8469242039  0.0069333261

But that must be wrong, since replacing that `require` with `nil` fixes the problem.

**Comment by abo-abo** [comment]
You mean removing only the require or the whole highlighting statement? Removing the require is, of course, and easy fix.

**Comment by hpdeifel** [comment]
I mean this diff:

```diff
diff --git a/ivy.el b/ivy.el
index e74c0c5..7468e2e 100644
--- a/ivy.el
+++ b/ivy.el
@@ -2695,7 +2695,7 @@ SEPARATOR is used to join the candidates."
                       str))
                    (cl-incf i)))))
             ((and
-              (require 'flx nil 'noerror)
+              nil
               (or (eq ivy--regex-function 'ivy--regex-fuzzy)
                   (and (eq ivy--regex-function 'swiper--re-builder)
                        (let ((caller (ivy-state-caller ivy-last)))
```

Since I don't have `flx` installed, this is equivalent in my case and much faster

**Comment by jferguson-gnubio** [comment]
I also got a huge performance regression, that I assume is the same thing, moving from counsel-20160826.2343 to counsel-20160906.750 from melpa.  Sorry I haven't done a proper bisect, but it sounds the same.  `counsel-M-x` and `counsel-find-file` are very slow to start up.

**Comment by jferguson-gnubio** [comment]
Apologies I'm not particularly proficient at Elisp, profiling etc, but with some experimentation on a variation of the patch hpdeifel suggested, for `counsel-M-x`

```
(require 'flx nil 'noerror) => 5627 cpu samples
(featurep 'flx)             => 942 cpu samples
```

I think the culprit might be that I have the `auto-compile-on-load` package, which seems to result in a lot of the `require` overhead.

**Comment by abo-abo** [comment]
Please check if it's better now.

**Comment by hpdeifel** [comment]
Yes, that's much better.

Thanks!

**Comment by jferguson-gnubio** [comment]
Works nicely - excellent, thank you.

**Comment by abo-abo** [comment]
Thanks for the confirmation.
