### ISSUE TITLE
Font lock problem of `ivy--regex-ignore-order`

### ISSUE THREAD

**Issue by Yevgnen** [abo-abo/swiper#654]
Hi,

It seem that the font lock works unexpectedly when using `ivy--regex-ignore-order`.

<img width="1386" alt="screen shot 2016-09-07 at 08 10 44" src="https://cloud.githubusercontent.com/assets/16749790/18295273/c30c8a4e-74d2-11e6-960d-835bfbee3bb1.png">

I guess `file` and `expand` should be highlighted ?

Minimum config for reproducing can be

```
(require 'package)

(setq package-archives '(("marmalade" . "http://marmalade-repo.org/packages/")
                         ("gnu" . "http://elpa.gnu.org/packages/")
                         ("melpa" . "https://melpa.org/packages/")
                         ("org" . "http://orgmode.org/elpa/")))

(package-initialize)

(unless (and (file-exists-p (expand-file-name "elpa/archives/marmalade" user-emacs-directory))
             (file-exists-p (expand-file-name "elpa/archives/gnu" user-emacs-directory))
             (file-exists-p (expand-file-name "elpa/archives/melpa" user-emacs-directory))
             (file-exists-p (expand-file-name "elpa/archives/org" user-emacs-directory)))
  (package-refresh-contents))

(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))

(setq use-package-verbose t
      use-package-enable-imenu-support t)
(require 'use-package)

(use-package swiper
  :ensure t
  :bind (("C-s" . swiper))
  :init (setq ivy-height 15
              ivy-count-format "(%d/%d) "
              ivy-use-virtual-buffers t
              ivy-initial-inputs-alist nil
              ivy-re-builders-alist '((t . ivy--regex-ignore-order))
              swiper-include-line-number-in-search t))
```

Thanks !

**Comment by jyp** [comment]
I've done some diagnosis on this one. 
A special formatting function is when `ivy--regex-ignore-order` is active. This formatting function is activated in `ivy--format-minibuffer-line` under the condition `(cond ((eq ivy--regex-function 'ivy--regex-ignore-order)`.

This condition works typically when avy callers do not specify a re-builder. Unfortunately, `swiper` unconditionally overwrites the re-builder with its own function, `swiper--re-builder`, so the test fails, and we get the default formatting function. 

I suppose that the appropriate solution would be to support custom formatting functions, and have swiper provide the corresponding implementation.

**Comment by abo-abo** [comment]
@jyp Patches welcome. I don't use `iyv--regex-ignore-order`, so it's not a priority for me to make it look nice.
