### ISSUE TITLE
https://melpa.org/packages/ivy-20160818.708.tar: Not found

### ISSUE THREAD

**Issue by fconcklin** [abo-abo/swiper#655]
Recent pull from M-x package-install ivy returns the following error:

    https://melpa.org/packages/ivy-20160818.708.tar: Not found

**Comment by syohex** [comment]
I suppose your package archive are old. Please  do `M-x package-refresh-contents` and retry.

**Comment by abo-abo** [comment]
This is a rare MELPA problem that goes away if you try again.
