### ISSUE TITLE
Docs suggest using counsel keybinds when counsel is not installed

### ISSUE THREAD

**Issue by ian-kelling** [abo-abo/swiper#658]
http://oremacs.com/swiper/

Just reading top to bottom, I install swiper, I read the functions I'm supposed to be trying out, and the first one I try, counsel-find-file, does not exist. Google, figure it out, ok, but the getting started doc should not have lead me into that situation. It seems it should have told me to install counsel too.

**Comment by gguimaraesbr** [comment]
+1

**Comment by abo-abo** [comment]
Thanks.
