### ISSUE TITLE
Symbol's value as variable is void: recentf-list

### ISSUE THREAD

**Issue by ninrod** [abo-abo/swiper#659]
So I've just add ivy in my init.el: 

```lisp
  (use-package ivy
    :ensure t
    :config
    (ivy-mode 1)
    (setq ivy-use-virtual-buffers t)
    (setq ivy-count-format "(%d/%d) ")
  )
```

`find-file` is working as expected. I loaded a bunch of files with that with suceess. 
But when I invoke `M-x ivy-recentf` I get this message (in the screenshot).

But it should not be the case because the recentf file has to have something. Aparently `find-file` is not creating a recentf file. How Ivy knows what files where recent opened through find-file?

<img width="450" alt="screen shot 2016-09-10 at 12 55 01 pm" src="https://cloud.githubusercontent.com/assets/8352747/18411821/4a76bbd2-7756-11e6-817d-1af6d2296bed.png">

**Comment by ninrod** [comment]
additional info: my `.emacs.d` actually is a symlink to another directory that lives inside a git repo in `~/.dotfiles/conf/emacs.d`.

**Comment by Yevgnen** [comment]
Since `recentf-list is a variable defined in ‘recentf.el’`,  you should add something like 

    (require 'recentf)
    (recentf-mode 1)

to your `.emacs` or `.emacs.d/init.el`

**Comment by abo-abo** [comment]
Thanks.
