### ISSUE TITLE
Calling `counsel-git-grep' with argument

### ISSUE THREAD

**Issue by jdahm** [abo-abo/swiper#66]
Excellent work with this so far! I use `counsel-git-grep` routinely.

I would like to bind M-. to call this with the word/symbol at point instead of `xref-find-definitions` using TAGS. I don't have much experience with this. Can I wrap a defun to call this with some default text or do you need to add an argument to `counsel-git-grep`?

**Comment by abo-abo** [comment]
You can use something like this:

```elisp
(defun cgg-at-point ()
  (interactive)
  (counsel-git-grep
   (thing-at-point 'symbol)))
```

But you can also go with the defaults and just call `counsel-git-grep` followed by <kbd>M-n</kbd>.
In all functions that use ivy, the initial <kbd>M-n</kbd> will set thing-at-point to the input.

**Comment by jdahm** [comment]
Oh, I like that even more. Thanks!
