### ISSUE TITLE
Feature request: results/input order

### ISSUE THREAD

**Issue by therockmandolinist** [abo-abo/swiper#663]
I was looking for a way to have ivy expand up, in the opposite direction to the default. What I mean is the input line would stay at the bottom where it usually is, the first choice would be above that, etc. (so items would be sorted in reverse, as in [command-t](https://github.com/wincent/command-t) for vim).

Absolutely loving ivy, by the way.

**Comment by abo-abo** [comment]
It looks and feels really weird. But enjoy.

**Comment by therockmandolinist** [comment]
Wow, thanks for your quick reply.

I kinda get why it might seem weird, but I thought would be nice to have the option, and this would allow for minimal eye movement if auto-resize of the minibuffer ever happens.

Thanks again, though!

**Comment by abo-abo** [comment]
You're welcome.

The look and feel is indeed a matter of taste. What I like about the defaults is the offset for the reading position: it's not very comfortable for me to look at the very bottom or very left of the screen. That's why I also like the Emacs' default 5 pixel left margin.

**Comment by therockmandolinist** [comment]
I didn't realize this, but this _is_ autoresizing the minibuffer too! That's pretty neat.

I also noticed when I include `(setq ivy-flip t)`, the input is on the bottom, but the first choice is still on top of the minibuffer for me. Is there any way to get the first choice directly above the input, the next after that, etc.?
