### ISSUE TITLE
counsel-M-x does not show "c++-mode"

### ISSUE THREAD

**Issue by sachdevaprash** [abo-abo/swiper#664]
Steps to reproduce:
1. Call counsel-M-x
2. Search for "c++-mode"

Result: You see only "c-mode".
Expected result: "c++-mode"

**Comment by syohex** [comment]
Input is treated as regexp. You need to input `c\+\+-mode`.

**Comment by sachdevaprash** [comment]
So it is intended to be this way? Is there a way to disable interpreting it as regex?

**Comment by therockmandolinist** [comment]
This isn't quite an answer to your question, but if you use flx for autocompletion (install [flx](https://github.com/lewang/flx) and do
```
(setq ivy-re-builders-alist
      '((counsel-ag . ivy--regex-plus)
        (swiper . ivy--regex-plus)
        (t . ivy--regex-fuzzy)))
```

(my setup for now, anyway, just means use flx in general except with counsel-ag and swiper), typing `c++-mode` or even `c++mode` or `c+mode` works. Of course, this is a different kind of fuzzy completion that acts a little differently and is more flexible, but spaces are interpreted literally and I'm not yet sure whether i prefer this or the default just yet.

**Comment by sachdevaprash** [comment]
Thanks for the info. I'll close the issue.

I would imagine that there are not too many such cases as `c++-mode`, so it's worth keeping it in regex mode.
