### ISSUE TITLE
Put the focus in `*ivy-occur *` after `ivy-occur` during `swiper`

### ISSUE THREAD

**Issue by Yevgnen** [abo-abo/swiper#665]
Hi !

When people do an `ivy-occur` during a `swiper` session, it's more likely to work on the `*ivy-occur ***` buffer. So, it would be nice to focus on it automatically after `ivy-occur` like `helm-moccur-save-results` and `helm-grep-save-results`. Thanks!

**Comment by abo-abo** [comment]
Thanks. It might have been a regression, I think previously the behavior was to select `*ivy-occur*`.
