### ISSUE TITLE
Somehow I can't tab-complete things inside term after enabling ivy-mode

### ISSUE THREAD

**Issue by shackra** [abo-abo/swiper#667]
So, yesterday I migrated from Helm to Ivy. While using `find-file` I noticed that TAB will not auto-complete the name of a file/dir and enter into it, so I bind ivy-alt-done to TAB for the ivy-mode-map.

Today I was doing something inside multi-term and trying to tab-complete the name of a directory and got this error:

```
Debugger entered--Lisp error: (no-catch exit nil)
  throw(exit nil)
  exit-minibuffer()
  ivy--done("toggle-debug-on-error")
  ivy-done()
  ivy-alt-done(nil)
  call-interactively(ivy-alt-done)
  yas--fallback()
  yas-expand()
  call-interactively(yas-expand nil nil)
  command-execute(yas-expand)
```

And a text is inserted in the buffer where I tried using TAB, in this case, `toggle.debug-on-error` was inserted in my scratch buffer (that was the last thing the cursor was on before reproducing the bug).

For now, I'll revert my bind on the TAB key as a workaround, hope this is a valid bug.

**Comment by abo-abo** [comment]
Looks like an issue with `yas-global-mode`, since there's no `(throw 'exit)` anywhere in `ivy`. Try disabling `yas-global-mode`.

**Comment by Mehran-Baghi** [comment]
Hi and thank you for this excellent package.
Can I use tab for cycling between suggestions for example when I find file (C-x C-f)?

**Comment by basil-conto** [comment]
Can this issue be closed until further notice?

**Comment by abo-abo** [comment]
OK, closing until there some new info.
