### ISSUE TITLE
Using `ivy-call` when completing file names does not pass full path to action

### ISSUE THREAD

**Issue by oantolin** [abo-abo/swiper#668]
I've been adding file operations as actions for `counsel-find-file` and discovered that depending on how I call the action sometimes the action function receives a full path and some times just the bit actually shown in the ivy minibuffer. For example, say you have:

```elisp
(defun delete-file-and-reset-ivy (file)
  (delete-file file)
  (ivy--reset-state ivy-last))

(ivy-set-actions
   'counsel-find-file
   '("d" delete-file-and-reset-ivy "delete"))
```

If you run `counsel-find-file` and use that action from `ivy-dispatching-done` (by default on `M-o`), `delete-file-and-reset-ivy` gets passed a full path. If instead you use the action from `ivy-dispatching-call` (`C-M-o`) then `delete-file-and-reset-ivy` just gets the candidate as shown in the minibuffer (so the `delete-file` calls fails as it looks for the file in the wrong directory). If you set the action in `ivy-read-action` and then use `ivy-done` you get the full path but if instead you use `ivy-call` you also get just the candidate, not the full path.

I believe that the `-done` and the `-call` functions should behave consistently, passing full paths if `ivy` is being used to complete file names.

Digging a bit in the source code it seems that the full path magic happens in `ivy--done`: it tests to see if `ivy-directory` is non-null and if so, it uses `(expand-file-name text ivy--directory)` instead of just the candidate `text`. `ivy-done` calls `ivy--done` and `ivy-dispatching-done` calls `ivy-done`.

(There is also `ivy-alt-done` which, if `ivy--directory` is non-null, calls `ivy--directory-done` which seems much more complicated than just `(expand-file-name text ivy--directory)`, but also contains `expand-file`. Maybe this extra behaviour should also happen for `ivy-done`?)

The `-call` functions on the other hand, never check if `ivy--directory` is non-null.

Also, the default action for `counsel-find-file` has `(find-file (expand-file-name x ivy--directory))`, and if I'm understanding the logic correctly the call `expand-file-name` is redundant.

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by oantolin** [comment]
It works great, thanks!
