### ISSUE TITLE
counsel-ag doesn't work with TRAMP

### ISSUE THREAD

**Issue by bricewge** [abo-abo/swiper#669]
For example doing `counsel-ag` with a buffer containing the file`/ssh:myserver:/etc/apt/sources.list` will result on a search on `/home/username/` on the `localhost` machine. This also appear when the buffer display a file opened as `sudo` on the `localhost`.

The expected behaviour would be to search from the opened file on the remote machine if `ag` is installed or as `sudo` if the file was openned as `sudo`.

**Comment by abo-abo** [comment]
Does ag even work on a remote machine?

**Comment by bricewge** [comment]
I don't thinks so. But it shouldn't be an issue since TRAMP give the ability to run commands on the remote box.
It looks like this behaviour is already present in [`ag.el`](https://github.com/Wilfred/ag.el/issues/115#issuecomment-233944994).

**Comment by abo-abo** [comment]
Please test, `ag` needs to be installed on the remote box.

**Comment by bricewge** [comment]
You fixed it. And you were blazing fast.
Thanks a lot for your work en emacs packages, they are awesome !
