### ISSUE TITLE
`colir` not installed when installing swiper through Melpa?

### ISSUE THREAD

**Issue by kaushalmodi** [abo-abo/swiper#67]
Getting this error:

> ad-Advice-require: Cannot open load file: No such file or directory, colir

**Comment by abo-abo** [comment]
Oops, I forgot that the swiper MELPA recipe was special.
I've sent the fix to milkypostman/melpa#2721.

**Comment by abo-abo** [comment]
Fixed now. Thanks for reporting.

**Comment by srustamo** [comment]
I get `Cannot open load file: No such file or directory, colir` in emacslient, pressing <kbd>C-s</kbd> (bound to `swyper`). In the same terminal running full emacs does not raise this error. 
<kbd>M-x</kbd> bound to `counsel-M-x` also gibes this error in `emacsclient`

**Comment by srustamo** [comment]
Apparently I had a very old daemon running, restarting it solved the problem.
