### ISSUE TITLE
Feature request: ivy-occur focus buffer after C-c C-o

### ISSUE THREAD

**Issue by sam217pa** [abo-abo/swiper#670]
I'd like Ivy-occur to grab the point after I call it with C-c C-o. 
I can do it with *Occur* with : 
```lisp
(add-hook 'occur-hook
          '(lambda ()
             (switch-to-buffer-other-window "*Occur*")))
```
But I did not find a way to get the Ivy buffer name programmatically (it changes with the query). 

Emacs Help has the `help-window-select` option with the behavior I'd love to have with ivy-occur.

Thanks !

**Comment by abo-abo** [comment]
It should already do it. There was a commit this week about it. Please check.

**Comment by sam217pa** [comment]
Awesome ! Thanks
