### ISSUE TITLE
counsel-ag broken?

### ISSUE THREAD

**Issue by technician77** [abo-abo/swiper#672]
I'm using NT-emacs 25.1 RC2 64bit on Windows 7. I use cygwin for the unix utils. Everything fine with swiper, ivy and counsel, but I'm not able to get counsel-ag working. It either gives me no output or it freezes the whole emacs. Currently I'm using my old ag.el for ag which works fine. I can't rule out that I'm too stupid to use counsel-ag, so I hope to find out about my stupidity with this this issue.

From my understanding I switch directory using M-x "cd", then I execute M-x "counsel-ag" then I enter a word I'm searching for as a normal string, not as a regexp and I expect counsel-ag to search the directory I'm currently in using ag. So either this is  somehow wrong or counsel-ag is broken, because there is no output ever even though there should be matches.

Then I would like to use counsel-ag with a different directory. I tried to use the syntax mentioned under describe-function but I couldn't figure it out. Could you give a simple specific command example how to make counsel-ag search for "bla" in "Z:/Tools/cygwin64/home/myuser/.emacs.d/org/test/" ?

Kind regards,
tech77

**Comment by abo-abo** [comment]
Try to eval this:

```elisp
(shell-command-to-string "ag --version")
;; and this
(shell-command-to-string "ag --nocolor --nogroup  -- test")
```

I'm not on Windows, but I've heard that `counsel-ag` works there.

**Comment by technician77** [comment]
First, your code does not produce any output on my system when I "eval-region" on them. Second, you might have to know that shells and terminals are utterly broken  on nt-emacs and cygwin-emacs-w32. I've wasted a lot of time on them. They work for sure on linux and mac, but not on windows. Problem is they do work to some small extend but my result is that they are too much broken to be usable.

So I tried eshell and shell anyway. The first command works, the second causes the buffer to hang. Emacs still works though, so I can kill the buffer. I tried the commands directly on the cygwin bash. There they work both. That was also my result with most of my other test in the past. It works directly on the cygwin bash but do not dare to try them in emacs. The shells in emacs do not seem to represent a real usable shell.

Even with that said, ag.el works fine. And ag.el must use the same ag on cygwin as counsel-al would. There must be some things that it does differently. Since I'm not a coder I have no idea what.

Output on the cygwin bash:
```
myuser@mypc /home/myuser
$ ag --version
ag version 0.31.0

Features:
  +jit +lzma +zlib

myuser@mypc /home/myuser
$ cd Z:/Temp

myuser@mypc /cygdrive/z/Temp
$  ag --nocolor --nogroup  -- bla
temp.txt:1:  (setq printer-name "bla")

test.txt:1:bla
```

**Comment by technician77** [comment]
The shell problems might have to do with the problem mentioned in [https://www.emacswiki.org/emacs/NTEmacsWithCygwin](url)

On the other hand ag.el seems able to work around this.

I have tried cygwin emacs-w32 but I went back to nt-emacs. Cygwin emacs-w32 looked promissing, it can do more things than nt-emacs but it's still not working 100%. Tried to get picocom working in that. Dev came to the conclusion that the terminal from emacs in cygwin-w32 is not a native one.

Haven't tried the fakecygpty solution yet, seemed too much effort for me. I draw the line here. If the shells are broken they are broken. If either the emacs devs or cygwin devs care I won't either. So no shells with emacs on windows.

Kind regards,
tech77

**Comment by abo-abo** [comment]
> If neither the emacs devs nor the cygwin devs careing I won't either

Not my problem either:)

> Even with that said, ag.el works fine

I suggest you use that then. Or `counsel-git-grep` or `counsel-pt`, or a proper OS.

**Comment by technician77** [comment]
Well, not everybody on business-pc's can choose their OS. Pt seems to be a viable alternative to ag, will try if that works with counsel but I won't get my hopes high since calling mechanism is quite likely the same. Well the idea was that you might look into the code of ag.el to check out what they do differently in order to improve your own code, but it seems Windows users aren't emacs package devs target audience.

**Comment by technician77** [comment]
PT is not maintained through cygwin. I could compile it myself but then it would need manual updating which is cumbersome. O.k. counsel-ag or pt for me, back to ag.el. If I find a solution for the problem elsewhere I'll drop a note here.

**Comment by igorepst** [comment]
`counsel-ag` works for me with Emacs 25.1 + ag from [MSYS2](https://sourceforge.net/projects/msys2/) on Windows 7 after using the following:
`(setq counsel-ag-base-command "ag --vimgrep --nocolor --nogroup %s")`

@abo-abo  `--vimgrep` was used once, according to #303

**Comment by technician77** [comment]
Found the reason for the problems: I defined powershell as my default shell. It seems the way counsel-al works is incompatible with that. Ag.el seems to take a different approach accessing ag. Anyway after removing that definition counsel-al worked.
