### ISSUE TITLE
Select multiple files to open in counsel-find-file

### ISSUE THREAD

**Issue by CSRaghunandan** [abo-abo/swiper#673]
Hello, I just installed and setup `swiper`, `ivy`, and `counsel`. I miss one feature of `helm`, that is being able to mark some of the candidates and execute an action. 
Sometimes, i would want to open multiple files inside a folder. How can I achieve this by marking multiple files and opening the marked files ?

I'm also having some trouble understanding how `swiper-multi` is supposed to work. When I invoke the command, I get a list of buffers that are open for the current session. How do I select multiple buffers to search in using `swiper-multi` ?

**Comment by abo-abo** [comment]
Use <kbd>C-M-m</kbd> or <kbd>C-M-n</kbd> to select multiple files or buffers.

**Comment by CSRaghunandan** [comment]
There is something *majorly broken* with my installation of `swiper-multi` 
I invoked `swiper-multi` and if i press <kbd>C-M-m</kbd> or <kbd>C-M-n</kbd> on any candidate, it deletes the entire contents of my current buffer ? I've no idea whats happening. And the swiper search will not return anything.

**Comment by abo-abo** [comment]
Thanks, I just fixed `swiper-multi`. I rarely use it, `swiper-all` is superior in 95% cases.

**Comment by CSRaghunandan** [comment]
> Thanks, I just fixed `swiper-multi`. I rarely use it, `swiper-all` is superior in 95% cases.

Oh I see. I guess i'll just `swiper-all` for most of my needs then. Thanks
