### ISSUE TITLE
ivy-avy error `exit-minibuffer: No catch for tag: exit, nil` 

### ISSUE THREAD

**Issue by CSRaghunandan** [abo-abo/swiper#674]
Whenever I invoke `ivy-avy` on any buffer I get this :- 
<img width="579" alt="screen shot 2016-09-14 at 3 58 50 pm" src="https://cloud.githubusercontent.com/assets/5226809/18509028/49ed7840-7a94-11e6-8251-5515674836ab.png">

and when I select something using the search keys, I get this error `exit-minibuffer: No catch for tag: exit, nil` and the entire buffer is replaced by `ivy-avy` and I'd have to undo to get the contents back. Any idea why this is happening ?

**Comment by abo-abo** [comment]
> Any idea why this is happening ?

`ivy-avy` isn't meant to be called with <kbd>M-x</kbd>. You should only call it from a completion session, the default shortcut is <kbd>C-'</kbd>.

It's a small Emacs nuisance: to bind `ivy-avy` to a key, I have to declare it as `(interactive)`. But then it shows up in the <kbd>M-x</kbd> list, even though it's not meant to be called stand-alone.

**Comment by CSRaghunandan** [comment]
I see, thanks for clearing things up :)  Closing the thread.
