### ISSUE TITLE
Fetch results from spotlights for counsel

### ISSUE THREAD

**Issue by CSRaghunandan** [abo-abo/swiper#675]
With helm, I could fetch results from `spotlight` for mac when using in `helm-for-files` and open files super fast (`recentf-mode` would be better for most purposes but, I used this on rare occasions). Is it possible to do the same with `counsel` ?

**Comment by abo-abo** [comment]
Never used a mac, but have a look at this: https://melpa.org/#/spotlight.

**Comment by CSRaghunandan** [comment]
That was exactly what I needed :) Thanks for the very quick response.
