### ISSUE TITLE
Magit/Projectile: Setting completing-read-function needed?

### ISSUE THREAD

**Issue by floli** [abo-abo/swiper#677]
Hello,

ivy documentation recommends to set ```(setq magit-completing-read-function 'ivy-completing-read)``` and ```(setq projectile-completion-system 'ivy)```. However, having neither of these set (but ```ivy-mode``` enabled) both work nicely with ivy and use it as completion.

Am I missing features I would get otherwise? Or subtle bugs? Or is this information just outdated (for me)?

Thanks!

**Comment by abo-abo** [comment]
I don't think you're missing anything for `magit`. The mentioned customization was necessary before, apparently it isn't now.

For `projectile`, it might be a bit of extra customization you could do.  For example, you could customize `ivy-re-builders-alist` specifically for projectile.  But if you want to get more completion features in projectile, check out https://github.com/ericdanan/counsel-projectile.

**Comment by floli** [comment]
Thanks for clarification.

Yeah, I'm already using counsel-projectile.

Should this issue remain open as a reminder to update the doc? For me, it can be closed.

**Comment by abo-abo** [comment]
> Should this issue remain open as a reminder to update the doc?

Thanks, I'll update the doc eventually, it doesn't hurt to have these two lines of code anyway.
