### ISSUE TITLE
Home directory behavior

### ISSUE THREAD

**Issue by sachdevaprash** [abo-abo/swiper#679]
This is a subtle difference in the way Swiper deals with the home directory. The home directory seems to be accessible with pressing `~`, so `C-x C-f ~.emacs` would open the .emacs file in the home directory. This behavior is incompatible with the default emacs `find-file` behavior of using `~/` for home directory. This leads to unfamiliar behavior, such as pressing `C-x C-f ~/.emacs` when in home directory and finding that you have reached file `/.emacs`

**Comment by abo-abo** [comment]
The defaults aren't perfection, there's always room for improvement. 

I think the ability to cd to home with only <kbd>~</kbd> rather than <kbd>~/</kbd> is an enhancement rather than regression.

**Comment by sachdevaprash** [comment]
Let me elaborate on my point and then you can choose to ignore it if you still like.

Typing `C-x C-f ~/.emacs`  produces the text `~//.emacs` in the minibuffer. In most terminals (I checked bash, zsh and eshell), `~//.emacs` corresponds to `~/.emacs`, but `counsel-find-file` opens `/.emacs`.

**Comment by UnwashedMeme** [comment]
@sachdevaprash I came across this as well, there's a pull-request and code you can copy in if you want at https://github.com/abo-abo/swiper/pull/687 we've been unable to come up with any good way to integrate this without breaking existing behavior.

**Comment by sachdevaprash** [comment]
@UnwashedMeme That seems like what I need. Thanks!
Can't this behavior be based on a variable to decide how ```~``` functions?

**Comment by abo-abo** [comment]
Now you can set the variable to get the behavior that you want.
