### ISSUE TITLE
Switching to hidden buffers with ivy

### ISSUE THREAD

**Issue by tsdh** [abo-abo/swiper#68]
It seems it's impossible to switch to a hidden buffer (a buffer whose name starts with a space) using ivy.  At first, I've thought the problem is that with `ivy--regex` or `ivy--regex-plus` spaces are wild, so I've set

```elisp
(setq ivy-re-builders-alist '((read-file-name-internal
                               . (lambda (x)
                                   (concat "^" (regexp-quote x))))
                              (internal-complete-buffer
                               . (lambda (x)
                                   ;; If the input starts with a space, ensure
                                   ;; that this must match literally.
                                   (ivy--regex-plus (if (string-match-p "^ " x)
                                                        (concat  "^[[:space:]]" x)
                                                      x))))
                              (t . ivy--regex-plus)))
```

But that seems to be only part of the problem.  When do <kbd>C-x b SPC</kbd> I get zero completions although the regexp build by my lambda above would match hidden buffers.  So it seems like the hidden buffers are never offered to ivy at all.

Oh, and this seems to confirm that:

```elisp
;; Empty input => only normal buffers are offered
(internal-complete-buffer "" (lambda (x) x) t)
;;=> ("*scratch*" "*Help*" "dot-emacs.el" "*ielm*" "*Group*" "*Messages*"
;;    "*imap log*" "*nntp-log*" ".newsrc-dribble" "*helm*")

;; Input starting with " " => only hidden buffers are offered
(internal-complete-buffer " " (lambda (x) x) t)
;;=> (" *Minibuf-1*" " *Minibuf-0*" " *code-conversion-work*" " *Echo Area 0*"
;;    " *Echo Area 1*" " *code-converting-work*" " *edit-server*" ...)
```

So I guess ivy must ask for all completions whenever the input string toggles between not starting with a space and starting with a space.

**Comment by abo-abo** [comment]
> It seems it's impossible to switch to a hidden buffer (a buffer whose name starts with a space) using ivy.

It's also impossible with helm. Not giving all the candidates is illogical, but slightly convenient in this case.

> So I guess ivy must ask for all completions whenever the input string toggles between not starting with a space and starting with a space.

Should mostly work with the last commit. The only thing is that spaces aren't significant for an update with the default `ivy--regex`. So another character needs to be typed for the update to take place.

**Comment by tsdh** [comment]
@abo-abo There is some regression which brought this issue in existence again.  `C-x b SPC` shows only all non-hidden buffers as completion candidates whereas it should list only hidden buffers.

The problem is that the `cond`-branch in `ivy-exhibit` which contains the special case for hidden buffers is never entered because its test expression `(eq (ivy-state-collection ivy-last) 'internal-complete-buffer)` is always nil because `(ivy-state-collection ivy-last)` returns the list of (non-hidden) buffer names instead of `'internal-complete-buffer`.

**Comment by abo-abo** [comment]
6d4f2b3216 mostly fixed this one.

**Comment by tsdh** [comment]
Yes, thank you!
