### ISSUE TITLE
Hide hidden files

### ISSUE THREAD

**Issue by floli** [abo-abo/swiper#685]
Hello,

how can I make ```counsel-find-file``` to hide hidden files, i.e. files that start with a dot?

Do I need to implement a regex builder for that?

Thanks!

**Comment by abo-abo** [comment]
It already hides the dot (hidden) files. To show them, enter input starting with a dot.

**Comment by floli** [comment]
![screenshot_20160923_111838](https://cloud.githubusercontent.com/assets/1028028/18780852/b4a9ceee-817f-11e6-80a3-20c87a7eb4cf.png)

Huh? Here is looks differently. I enter "sc" to filter and it also displays ".scribus" and alike. See attached screen shot.

All setup I did is:
```
(use-package counsel
  :ensure t
  :config
  (setq ivy-use-virtual-buffers t
        ivy-count-format "(%d/%d) "
        ivy-height 20)
  (ivy-mode t)
  :bind (
         ("C-x C-f" . counsel-find-file)
         ("C-h C-v" . counsel-describe-variable)
         ("C-h C-f" . counsel-describe-function)
         ("M-x" . counsel-M-x)
         ("C-s" . swiper)))
```

**Comment by abo-abo** [comment]
On my system, the input `cu` in home shows only `Documents`. But the input `.cu` shows additionally `.cups` and `.curlrc`.

**Comment by abo-abo** [comment]
Oh, I see that you need to set `counsel-find-file-ignore-regexp` for it to work.

**Comment by floli** [comment]
Would you paste you regexp here? I've found the regexp hiding lock and temp files, but extending it with dot files is such a pain in elisp regexes.

**Comment by manuel-uberti** [comment]
I got this in my configuration:
```
(setqcounsel-find-file-ignore-regexp
        (concat
         ;; File names beginning with # or .
         "\\(?:\\`[#.]\\)"
         ;; File names ending with # or ~
         "\\|\\(?:\\`.+?[#~]\\'\\)"))
```

**Comment by abo-abo** [comment]
@manuel-uberti Thanks for the info. I use only the simple dotfiles regexp.

**Comment by manuel-uberti** [comment]
I think I _borrowed_ it from @kaushalmodi. :-)

**Comment by CSRaghunandan** [comment]
@manuel-uberti  Thanks for the info :) I was looking for something like this a few days ago

**Comment by CSRaghunandan** [comment]
@abo-abo Is it possible to have something like `counsel-find-file-ignore-regexp` for `counsel-projectile-find-file` ? I see there's no ignore-regexp variable for `counsel-projectile-find-file`

**Comment by abo-abo** [comment]
@CSRaghunandan You'll have to ask @ericdanan for that feature: https://github.com/ericdanan/counsel-projectile/issues

**Comment by kaushalmodi** [comment]
@CSRaghunandan In my experience, `M-x projectile-find-file` works just fine using the `ivy` backend once you set `(setq projectile-completion-system 'ivy)`. I do not use `counsel-projectile`.

Now I also force the projectile cache to be generated strictly using `ag`. Using `.agignore` I have a fine control on what files I need to add to the cache. That way `M-x projectile-find-file` gives me a filtered list to search from right from the beginning.. `ivy` does not need to job of filtering over there :)

[My `projectile` file caching setup using `ag`][1]

[1]: https://github.com/kaushalmodi/.emacs.d/blob/664ad66cba42b60f757850daeb379d84eb23a03b/setup-files/setup-projectile.el#L96-L107

**Comment by CSRaghunandan** [comment]
@kaushalmodi  I've only tiny problem with your method. `projectile-find-file` completely ignores the dot files altogether and i can't open them with `projectile-find-file`.  I'd have to resort to `counsel-find-file` for that purpose. Is that how it's supposed to work ?

**Comment by kaushalmodi** [comment]
@CSRaghunandan Yes, if you want `ag` to use the `.agignore`, it would ignore `.` files by default. That's usually good, but bad in this case if you need the dot files. 

If you choose not to use ignore files (`-U`, `-u`), then you'll get the dot files too. But I don't think that would be a better option. 

Before running it through projectile, I would do something like `ag -g '' > temp.txt` (or the command that works for you) and do a quick check if it contains the files that you expect. 

There are few workarounds to access the dot files. If they are few in number and something that you access frequently, you can bind their `find-file` calls to keys. 

Or, you can go ahead  and write a little script that appends to the `ag` generated cache (which could be quite some work).

Finally, you would pick the approach that works for you :) May be `ag` is not the way to go.

**Comment by CSRaghunandan** [comment]
@kaushalmodi  Thanks for the info.
well, I guess i'll just stick to using `counsel-find-file` for the rare case I need to edit a dot file :)

**Comment by ericdanan** [comment]
Glad you found a solution.

I guess you could also use projectile's built-in mechanism to ignore files: either locally through a `.projectile` file (or `.gitignore` if in a git project...), or globally through the variable `projectile-globally-ignored-files`.

**Comment by abo-abo** [comment]
@ericdanan How do you un-ignore `projectile-globally-ignored-files` for the current session? I don't see functionality for that in projectile.el.

**Comment by kaushalmodi** [comment]
Here's another solution that I have been experimenting lately and seems to work just fine ..

**Use `rg` instead of `ag`!**

The benefit is that `rg` allows white-listing files (`ag` does not). A good thing is that the devs of `ag` and `rg` have agreed upon naming their ignore files as simply `.ignore` instead of having `.agignore` and `.rgignore`. This works with the latest master branch builds of both. :)

Now you can use the same `.ignore` for both, and add whitelisting for the dot files that you need to show up in the projectile file cache.

[This recent commit in my config][1] sets `rg` instead of `ag` as the default binary to use for projectile file cache.

[1]: https://github.com/kaushalmodi/.emacs.d/commit/6beb2156b0d6181b0881cc714de1780129bb038f

**Comment by ericdanan** [comment]
Sorry for the confusion. First of all, I wanted to post this comment in [the counsel-projectile issue referenced above](https://github.com/ericdanan/counsel-projectile/issues/10), where @CSRaghunandan said that @kaushalmodi 's setup to ignore files using `ag` solved his problem. And my comment was only about ignoring files, not having the possibility to unignore them, which is the initial topic of the issue I'm replying to.

Anyway, if I understand correctly, the goal here would to possibly have `counsel-projectile-find-file` ignore (and unignore) files that are not ignored by projectile. Is this correct? In this case I guess one could simply try to use `counsel--find-file-matcher` in `counsel-projectile-find-file`. Then `counsel-find-file-ignore-regexp` would apply there as well. If more flexibility is needed, one could add a variable `counsel-projectile-find-file-ignore-regexp` to use a separate regexp for `counsel-projectile-find-file`.

**Comment by ericdanan** [comment]
To be sure, as it seems to me that the orignial issue is fixed, I wouldn't want the counsel-projectile specific issue to block closing this. If @CSRaghunandan or anybody else is interested in having some feature implemented in counsel-projectile, I would suggest that they open an issue or send a PR there.

**Comment by abo-abo** [comment]
@ericdanan Thanks, closing.
