### ISSUE TITLE
help with counsel-shell-command

### ISSUE THREAD

**Issue by njdan5691** [abo-abo/swiper#689]
Hi,

I  use M-: (shell-command) often, and have turned on the history, I would love to have a counsel interface instead of the default behavior. I'm pretty new to elisp but this snippet was my first attempt
at it, using counsel-describe-function as a start. Well obviously this did not work. Would someone be kind enough to help.

Thanks in advance 

```
(defun counsel-shell-command ()
  "Forward to `shell-command'."
  (interactive)
  (ivy-read "Shell Command: "
            (let (cands)
              (mapatoms
               (lambda (x)
                 (when (fboundp x)
                   (push (symbol-name x) cands))))
              cands)
            :keymap counsel-ag-map
            :history 'counsel-shell-command-symbol-history
            :require-match t
            :sort t
            :action (lambda (x)
                      (shell-command
                       (intern x)))
            :caller 'counsel-shell-command))
```

**Comment by abo-abo** [comment]
Try this:

```elisp
(defun counsel-shell-command-history ()
  (interactive)
  (ivy-read "cmd: " shell-command-history
            :action 'insert
            :caller 'counsel-shell-command-history))

(define-key minibuffer-local-shell-command-map
    (kbd "C-r") 'counsel-shell-command-history)
```

Invoke your `shell-command` as usual. But press <kbd>C-r</kbd> to search though history.

**Comment by njdan5691** [comment]
Thanks, after some tweaking i got my function down to this, which works as I expected. I tried your variant but get "Command attempted to use minibuffer while in minebuffer. I'm happy with what I came up with, but would like to get your version to work also. Again thanks for your help.

```
(defun counsel-shell-command ()
  "Forward to `shell-command'."
  (interactive)
  (ivy-read "Shell Command: "
 						shell-command-history
            :action (lambda (x)
                      (shell-command x))
            :caller 'counsel-shell-command))
```

**Comment by therockmandolinist** [comment]
@njdan5691 I had to add `(add-to-list 'shell-command-history x)` to the lambda in your version in order for any extra commands executed from within `counsel-shell-command` to appear on the history list.

Though having the option to edit the command does seem nice.

**Comment by abo-abo** [comment]
> it inserts the command into the current buffer, not the minibuffer

Do you have the latest ivy version?

**Comment by therockmandolinist** [comment]
I believe I do

**Comment by abo-abo** [comment]
@therockmandolinist It should insert into the current buffer. Was the minibuffer current when you called the command? You need to call it through a binding when already in the minibuffer, not through `M-x` or a binding from top-level.

**Comment by therockmandolinist** [comment]
Oh yeah, I see. Nevermind, I was being silly and calling the function by name. Thanks for clearing that up!

**Comment by njdan5691** [comment]
This is what I ended up with, the @abo-abo version wrapped in use-package. Works perfect, thanks.

```
    (use-package simple
      :commands (shell-command)
      :config
      (defun counsel-shell-command-history ()                                                                 
        (interactive)
        (ivy-read "cmd: " shell-command-history
                  :action 'insert
                  :caller 'counsel-shell-command-history))

      (define-key minibuffer-local-shell-command-map
        (kbd "C-r") 'counsel-shell-command-history))

```

**Comment by abo-abo** [comment]
The new command `counsel-shell-command-history` and <kbd>C-r</kbd> is now added to `counsel-mode`, no extra config necessary.

Thanks to all for contributing to the discussion.

**Comment by njdan5691** [comment]
I don't use counsel-mode, I need to use find-file without the counsel extension, because I use environment variables when locating my files, and have not figured out how to do that with counsel yet.

**Comment by JohnLunzer** [comment]
@abo-abo, I've been trying, without success to replicate your counsel-shell-command-history for use with dired-do-async-shell-command.

Do you have any idea how to get a similar C-r map to what you've done with the regular shell command? I can't seem to figure out with map to put the define-key into.

**Comment by abo-abo** [comment]
@JohnLunzer glad you found the solution. The code you used is also part of `counsel-mode`, it binds <kbd>C-r</kbd> in `minibuffer-local-map`.
