### ISSUE TITLE
git-commit-mode isn't a major-mode anymore

### ISSUE THREAD

**Issue by tarsius** [abo-abo/swiper#692]
In version two of Magit, `git-commit-mode` isn't a major-mode anymore. It's now a minor-mode which can be combined with whatever major-mode is most suitable for the commit message format used by a project. The default is `text-mode`, but something like `markdown-mode` might also make sense in some cases.

`counsel-at-git-issue-p` should be adjusted accordingly. (Also there is a typo in the doc-string of that function.)

**Comment by abo-abo** [comment]
Thanks.
