### ISSUE TITLE
No info docs when installed from elpa

### ISSUE THREAD

**Issue by jdahm** [abo-abo/swiper#697]
I'm installing Ivy from elpa, and the doc directory path seems to not get added automatically to `Info-directory-alist`. After a bit of digging I found this in the packaging section of the Emacs info doc:

```
If the content directory contains a file named ‘dir’, this is assumed to be an Info directory file made with ‘install-info’.
```

Is it possible to easily get this added by default? It seems like a hassle to add the path manually after the `package-install`.

**Comment by abo-abo** [comment]
I'll try to remember to do this on release. Apparently, putting `ivy.info` in the base directory should work as well.

**Comment by skangas** [comment]
It would be great if you could fix this, which would really help the usability of the package.

> If the content directory contains a file named dir, this is assumed to be an Info directory file made with install-info. See Invoking install-info. The relevant Info files should also be present in the content directory. In this case, Emacs will automatically add the content directory to Info-directory-list when the package is activated. 

This is from:
https://www.gnu.org/software/emacs/manual/html_node/elisp/Multi_002dfile-Packages.html

I think Magit does this correctly on install:
https://github.com/magit/magit/blob/master/Documentation/Makefile

Thanks,
Stefan Kangas

**Comment by abo-abo** [comment]
Thanks for the pointers. The 0.12.0 release on ELPA should have the info pages set up. Please test.

**Comment by skangas** [comment]
Works for me. Thanks!

**Comment by abo-abo** [comment]
Thanks, closing the issue.
