### ISSUE TITLE
error code 2 when using counsel-grep on certain modes

### ISSUE THREAD

**Issue by CSRaghunandan** [abo-abo/swiper#699]
Not sure why, but I'm getting `error code 2` when using `counsel-grep` in `haskell-mode` and `js2-mode`, `css-mode`, `web-mode`. It's working fine in the other modes I suppose. I'll report if it's not working in any other modes.

Why is this happening ?

**Comment by abo-abo** [comment]
No idea, just run the equivalent command in the shell and see what happens.

**Comment by CSRaghunandan** [comment]
I did a quick check of `counsel-grep-base-command` it's value is `grep -nE \"%s\" %s`. 
I assume the first`%s` is the search string and the second `%s` is the file name? Am I correct?
This commands works fine when run under shell or using `grep` command in emacs

**Comment by CSRaghunandan** [comment]
I find this very strange. `counsel-git-grep` works absolutely fine, I'm not sure why `counsel-grep` does not work only for a few specific modes. Can I check which command is being executed for `counsel-grep` for the current buffer I'm in ?
