### ISSUE TITLE
Error in pattern can render ivy-mode in a weird, broken state

### ISSUE THREAD

**Issue by zhaojiangbin** [abo-abo/swiper#70]
In ivy-mode, if there is any error from `post-command-hook (ivy--exhibit)`:
1. Some keys in ivy-minibuffer-map, such as `C-n`, `C-p`, `C-s`, `C-r`, etc. stop working while the others such as `C-M-n`, `C-M-p`, `C-j`, `RET` continue to work.
2. The candidates no longer update as the pattern changes, and the selection is stuck with the initial.

This is easily reproduced as below:
1. `C-x b` to call `switch-to-buffer`.
2. Type `\` (backslash) and watch the message `Error in post-command-hook (ivy--exhibit): (invalid-regexp "Trailing backslash")` showing up.

I am aware of `M-q` for `ivy-toggle-regexp-quote` but, hey, we do make mistakes and forget things. :)

MELPA version 20150429.532.

**Comment by abo-abo** [comment]
Thanks for the report, this was a very important issue.

> I am aware of M-q for ivy-toggle-regexp-quote

Good, but it's much better to solve an error than to ignore or work-around it.
