### ISSUE TITLE
counsel-grep-or-swiper: error code 2

### ISSUE THREAD

**Issue by brunoqc** [abo-abo/swiper#700]
When I run counsel-grep-or-swiper and type something I get "error code 2".

I have grep installed. Not sure how to debug.

GNU Emacs 25.1.1 (x86_64-unknown-linux-gnu, GTK+ Version 3.20.9) of 2016-09-18

**Comment by CSRaghunandan** [comment]
I had opened a thread about the same problem a few hours ago. The problem happens when there is a `space` in the directory name which contains the file in which you are running `counsel-grep` or `counsel-grep-or-swiper`. Remove the space and it should work fine

**Comment by abo-abo** [comment]
@brunoqc Does that solve your problem?
@CSRaghunandan Thanks, I'll try to make it work for directories with spaces.

**Comment by brunoqc** [comment]
Removing the space did fix the problem and I also don't have the problem with the new version (even if there's a space).

**Comment by abunbux** [comment]
Did not solve the problem.
![Screenshot_20190802_140211](https://user-images.githubusercontent.com/14283097/62366000-532b9900-b52e-11e9-9952-5672f5913938.png)

**Comment by abunbux** [comment]
found a mistake - 
`(let ((cmd (cond ((executable-find "rg")
                    "rg -S --no-heading --line-number --color never '%s' %s")
                   ((executable-find "ag")
                    "ag -S --noheading --nocolor --nofilename --numbers '%s' %s")
                   (t counsel-grep-base-command))))
    (setq counsel-grep-base-command cmd))`

after commenting - everything works
