### ISSUE TITLE
Better `counsel-semantics`?

### ISSUE THREAD

**Issue by xuhdev** [abo-abo/swiper#702]
`helm-semantics` seems displaying nicer list of different types of symbols: https://github.com/jorgenschaefer/elpy/issues/866#issuecomment-210412472

Is it possible to improve `counsel-semantics` like that?

**Comment by abo-abo** [comment]
A better `counsel-semantic` is available:

- in `lispy` for LISP dialects
- in `lpy` for Python
- in `function-args` for C/C++

**Comment by Yevgnen** [comment]
A dirty solution, you can still remove the `helm-semantic` dependency by copying one or two more helm functions. Since I still use `helm`, I don't mind no matter how dirty it is. 😂

    ;; Counsel semantic
    (defvar counsel-semantic--tags-cache nil)
    (defun counsel-semantic ()
      (interactive)
      (require 'helm-semantic)
      (when (semantic-parse-tree-needs-update-p)
        (semantic-parse-tree-set-needs-update))
      (setq counsel-semantic--tags-cache (semantic-fetch-tags))
      (ivy-read "Semantic tags: "
                (with-temp-buffer
                  (helm-semantic--fetch-candidates counsel-semantic--tags-cache 0)
                  (split-string (buffer-substring (point-min) (point-max)) "\n" t))
                :preselect (thing-at-point 'symbol)
                :require-match t
                :action (lambda (candidate)
                          (let* ((pos (if (string-prefix-p " " candidate)
                                          (next-single-property-change 0 'semantic-tag candidate (length candidate))
                                        0))
                                 (tag (get-text-property pos 'semantic-tag candidate)))
                            (semantic-go-to-tag tag)))
                :caller 'counsel-semantic))
    
    (defun counsel-semantic-or-imenu ()
      (interactive)
      (if (semantic-active-p)
          (call-interactively #'counsel-semantic)
        (call-interactively #'counsel-imenu)))

<img width="751" alt="screen shot 2016-12-28 at 4 34 27 pm" src="https://cloud.githubusercontent.com/assets/16749790/21517638/8e517a48-cd1b-11e6-9de1-5eb4ebabd1e8.png">

**Comment by abo-abo** [comment]
@Yevgnen That's a pretty good solution. It's nice to reuse the candidate list of `helm-semantic`, too bad it's not cleanly returned by a single function.

**Comment by eflanigan00** [comment]
Any update on this? I'd love to remove helm-semantic-or-imenu from my keybindings :100:

**Comment by Yevgnen** [comment]
No from me... I'm still using my mixed version of `counsel-semantic`...

```
  ;; Counsel semantic
  (defvar counsel-semantic--tags-cache nil)
  (defun counsel-semantic ()
    (interactive)
    (require 'helm-semantic)
    (when (semantic-parse-tree-needs-update-p)
      (semantic-parse-tree-set-needs-update))
    (setq counsel-semantic--tags-cache (semantic-fetch-tags))
    (ivy-read "Semantic tags: "
              (with-temp-buffer
                (helm-semantic--fetch-candidates counsel-semantic--tags-cache 0)
                (split-string (buffer-substring (point-min) (point-max)) "\n" t))
              :preselect (thing-at-point 'symbol)
              :require-match t
              :action (lambda (candidate)
                        (let* ((pos (if (string-prefix-p " " candidate)
                                        (next-single-property-change 0 'semantic-tag candidate (length candidate))
                                      0))
                               (tag (get-text-property pos 'semantic-tag candidate)))
                          (semantic-go-to-tag tag)))
              :caller 'counsel-semantic)
    (run-hooks 'imenu-after-jump-hook))

  (defun counsel-semantic-or-imenu ()
    (interactive)
    (if (semantic-active-p)
        (call-interactively #'counsel-semantic)
      (call-interactively #'counsel-imenu)))
```

**Comment by abo-abo** [comment]
@xuhdev Thanks, please test.
@Yevgnen Thanks for the pointer.
@eflanigan00 Thanks for the donation.

**Comment by eflanigan00** [comment]
@abo-abo 
I don't see any class variables or methods like in xuhdev's original link. I notice that `counsel-imenu` shows them.

Can you also add the `counsel-semantic-or-imenu` from Yevgnen?
Thanks for the great work!

**Comment by abo-abo** [comment]
> I don't see any class variables or methods

Nice catch, fixed.

> Can you also add the counsel-semantic-or-imenu from Yevgnen?

Added.

> Thanks for the great work!

You're welcome.

**Comment by xuhdev** [comment]
It works well. Thanks!
