### ISSUE TITLE
ivy-switch-buffer: filtering does not preserve virtual buffer ordering

### ISSUE THREAD

**Issue by Wilfred** [abo-abo/swiper#706]
I use `ivy-switch-buffer` with `ivy-use-virtual-buffers` and it generally does exactly what I want.

However, if I kill a buffer, then try to switch to buffer with the same name, I accidentally reopen the previous file:

![lib_rs_counsel](https://cloud.githubusercontent.com/assets/70800/19333038/cae08b4a-90bf-11e6-9274-ac64b1ea94dd.png)

In this picture, I've just killed a lib.rs buffer. I have two other files called lib.rs open. However, typing `C-x b lib.rs RET` reopens the lib.rs file I just closed.

Is it possible to reorder the results to prevent this?

**Comment by abo-abo** [comment]
It looks like the case here is the perfect match logic: when you type in the exact candidate name, it will be selected no matter where in the list it is.

I think if you type in only `lib`, the virtual one will be lower in the list.

**Comment by Wilfred** [comment]
This doesn't seem to be the case:

![package_json](https://cloud.githubusercontent.com/assets/70800/19360701/89fcf030-914d-11e6-80a7-1ec26e511884.png)

What would you expect to happen in this case?

**Comment by abo-abo** [comment]
> What would you expect to happen in this case?

The virtual buffers are always below for me. What settings are you using?

**Comment by Wilfred** [comment]
I think my only relevant setting is this one:

```
(setq ivy-re-builders-alist '((t . ivy--regex-ignore-order)))
```

I have set four other ivy related settings: https://github.com/Wilfred/.emacs.d/blob/40cc6ebc474f04d14762f3898677589f17781373/user-lisp/minibuffer-completion-customisations.el#L47-L70

I'm not seeing virtual buffers at the bottom. In one case (note the case difference), I am even seeing the virtual buffers in the middle:

![cask_ordering](https://cloud.githubusercontent.com/assets/70800/19407200/470e5928-9268-11e6-8cf2-72611b3606fd.png)

Is there code to ensure that virtual buffers are last? Could you point me at it?

**Comment by abo-abo** [comment]
See `ivy--buffer-list`. It has an append of current buffers and virtual buffers.

**Comment by Wilfred** [comment]
OK, so `ivy--buffer-list` is only called once, and ordering is correct at that point. It's only when I start typing characters to narrow down the options that the order is not preserved.

This seems odd because my understanding of `ivy-sort-fnctions-alist` is that we shouldn't change the ordering for buffers.

**Comment by Wilfred** [comment]
I think the problem might be this line in `ivy--filter`:

```lisp
(setq ivy--old-cands (ivy--sort name cands))
```

This seems to be putting `package.json` first in the list of candidates, even though it's a virtual buffer.

**Comment by abo-abo** [comment]
Likely the issue with `ivy--regex-fuzzy` and `flx`: `flx` doesn't care if a buffer is virtual or not when sorting.

**Comment by Wilfred** [comment]
I have a stupid question: why does `ivy--filter` sort at all?

**Comment by Wilfred** [comment]
Aha, I think I see the problem. I have the following in my init.el:

```lisp
(setq uniquify-buffer-name-style 'post-forward-angle-brackets)
```

This means that the virtual buffer name is just `package.json`, whereas the existing buffers have prefixes: `eslint/package.json` and so on. Since `ivy-sort-function-buffer` prefers a prefix match, it is prioritising the virtual buffer name over the uniquified buffer name.

**Comment by abo-abo** [comment]
Can you make a generic fix for uniquify? Patches welcome.
Otherwise, you can adjust your `ivy-sort-matches-functions-alist` setting.

**Comment by abo-abo** [comment]
> How would you feel about a patch to ivy-sort-function-buffer that ensures virtual buffers are always last?

Sounds good.
