### ISSUE TITLE
ivy-overlay should require 'overlay.el'

### ISSUE THREAD

**Issue by Dickby** [abo-abo/swiper#707]
not shure but on my emacs it only works if i require 'overlay'

**Comment by abo-abo** [comment]
I have no `overlay.el` on my system. All functions used (`overlay-put` etc) are C functions.

**Comment by Dickby** [comment]
It's not working on my emacs:
GNU Emacs 26.0.50.12

**Comment by Dickby** [comment]
if i require overlay it is working for short time and then it gives the error:
ivy--insert-minibuffer: Args out of range: #<buffer *scratch*>, 0, 1

**Comment by abo-abo** [comment]
> if i require overlay it is working for short time and then it gives the error:
> ivy--insert-minibuffer: Args out of range: #, 0, 1

Please provide a reproduction scenario.

Also, what error do you get if you don't `(require 'overlay)`?

**Comment by Dickby** [comment]
i start emacs with -Q
M-x package-initialize
M-x ivy-mode
M-x customize-variable
ivy-display-funktion
set it to overlay
save for session only
M-x

and i get the error message
Wrong type argument: number-or-marker-p, nil

**Comment by abo-abo** [comment]
You don't need to customize anything, it's all automatic. The overlay function will be used only from `ivy-completion-in-region`.

**Comment by Dickby** [comment]
so how do i enable it to show completion in an overlay?

**Comment by Dickby** [comment]
to it thanks.
