### ISSUE TITLE
Unable to return alist when collection is a function

### ISSUE THREAD

**Issue by jtbm37** [abo-abo/swiper#709]
Consider the following snippet
``` lisp
(defun find-candidates ()
'(("foo" . 1) ("foo2" . 2)))

(ivy-read "find symbols:" #'find-candidates))
```
The list will be empty.

However this snippet
``` lisp
(ivy-read "find symbols:" '(("foo" . 1) ("foo2" . 2))))
```
The list will show foo and foo2.

The reason I am looking to reproduce the same result with a function is because I need to call an asynchronous function (with `dynamic-collection` set to `t`) which will return an alist of which each cdr contains extra values for each different actions.

Is this intended or is this a bug ?

**Comment by jtbm37** [comment]
The same snippet with the function but with `dynamic-collection` set to `t` throws an error in `ivy--format`

**Comment by jtbm37** [comment]
It took me a long time to figure it out but at least I got to read and understand the code.
`find-candidates` in this case must set the state collection to the original alist but return a string list.

This works:
```lisp
(defun find-candidates ()
  (let ((result '(("foo" . 1) ("foo2" . 2))))
    (setf (ivy-state-collection ivy-last) result))
    ("foo" "foo2"))

(ivy-read "find symbols:"
              #'find-candidates
              :dynamic-collection t)
               
```

Let me know if this is not the right way to do it.

**Comment by jtbm37** [comment]
Even if the above works, I don't really like the fact that I have to build 2 different lists, one for display and one for the actions.

**Comment by jtbm37** [comment]
The above is not a good solution since I am changing `ivy-state-collection` to a collection from a function, therefore when changing input the function will not be called again.

**Comment by abo-abo** [comment]
Your example does not adhere to the `completing-read` interface. You can test it like this (disable `ivy-mode` and press <kbd>TAB</kbd>):

```elisp
(defun find-candidates (str pred _)
  '(("foo" . 1) ("foo2" . 2)))

(completing-read "test: " 'find-candidates)
```

The interface requires the function to take 3 args and to return a list of strings.

I suggest to either do it like this:

```elisp
(let ((cands '(("foo" . 1) ("foo2" . 2))))
  (ivy-read "find symbols:" cands))
```

Or like this:

```elisp
(defun find-candidates (str pred _)
  (let ((props '(1 2))
        (strs '("foo" "foo2")))
    (cl-mapcar (lambda (s p) (propertize s 'property p))
               strs
               props)))

(ivy-read "find symbols:" #'find-candidates)
```

**Comment by jtbm37** [comment]
Oh sorry my example was not complete. My actual code had 3 optional arguments on `find-candidates`.

That works perfectly. Thanks for your help.

Do you think it's worth updating the [documentation](http://oremacs.com/swiper/) to include this example ?

**Comment by abo-abo** [comment]
> Do you think it's worth updating the documentation to include this example ?

I think it's worth. Can you make a PR?

**Comment by jtbm37** [comment]
Will do.
