### ISSUE TITLE
Feature request: a different approach for filtering candidates

### ISSUE THREAD

**Issue by zhaojiangbin** [abo-abo/swiper#71]
My elisp knowledge is limited so please tell me if I am making no sense.

Prior to #62, ivy builds a regexp from the input and filters the given collection using the compiled regexp. As far as I understand it:

1. A pattern like "foo bar" accepts candidate "foo-bar" but not candidate "bar-foo". While this perhaps meets user expectation in most cases, it can still be undesirable in some.
2. To create or modify backslash constructs in the pattern, the user must type `M-q` twice to enter and exit from the "regexp-quote state". Forgetting doing this can end up in error (see #70). By the way, `ivy-toggle-regexp-quote` appears to be inconsistent: it does not hide the candidates if `M-q` is pressed with empty input so there is no visual clue as when the input is not empty.

#62 adds the capability to exclude matched entries from the candidate list. So "foo !bar" accepts "foo-abc" but not "foo-bar". However, it seems that it only supports one exclusion at most and the exclusion must be the last one (I don't fully understand how `ivy-re-builders-alist` works so it can be that I just need to customize this variable.)

So I want to discuss a different approach:

1. The input string is compiled into a list of regexps - each substring separated by spaces is an independent pattern.
  - A pattern is detected as starting with a non-space character and ending with a non-backslash character followed by a space. For example, if the input is `ab cd\ e\   \.xh ` (note there are two spaces between `e\` and `\.`), there would be three regexps compiled from: `ab`, `cd\ e\ ` and `\.xh`, respectively.
  - Normally the regexp list is rebuilt only at the end of last pattern. For example, if the input starts with `ab `, the first regexp is compiled for pattern `ab`. When the input becomes `ab cd\ e\  ` (note two spaces at end), the second regexp is compiled from pattern `cd\ e\ ` and appended to the list, so on and so forth.
  - A special key in `ivy-minibuffer-map` can rebuild the regexp list at any time. This can save the user from having a trailing space in the input. It also helps when the user modifies the patterns anywhere other than at the end of input.
2. Each time the regexp list is rebuilt, the regexps are applied to the candidates in order. Each application removes zero or more entries from the candidate list.
  - If the input is `one !two three four\|five`, the regexp list would have regexps compiled from `one`, `!two`, `three`, `four\|five`.
  - And if the candidates are {`one only`, `one and two`, `two only`, `three and one`, `onetwothreefour`, `onethreefourfive`, `one-three-five`},
  - After applying the first regexp, `one`, the candidates would be left with {`one only`, `one and two`, `three and one`, `onetwothreefour`, `onethreefourfive`, `one-three-five`}.
  - After the second application, `!two`, the candidate list would have {`one only`, `three and one`, `onethreefourfive`, `one-three-five`}.
  - The third regexp application, `three`, would turn the candidate list into {`three and one`, `onethreefourfive`, `one-three-five`}.
  - The last regexp, `four\|five`, would leave only {`onethreefourvie`, `one-three-five`} in the candidate list.

Comparing to the existing approach, I think this new one has the following advantages:

1. There is no need of `ivy-toggle-regexp-quote` so it will be easier for the user to make full use of Emacs regexp.
2. Exclusions are no more difficult than inclusions. There can be as many exclusions and at any place in the input as the user wants.
3. It meets user expectation more, IMHO - an input "foo bar" would match both candidate "foo-bar" and candidate "bar-foo". To match only "foo-bar", there are still "foo.+bar" and "foo.*bar".
4. Most importantly, reducing candidates requires less thinking ahead. The user does not need to order the patterns in certain ways - input "one !two three" would have the same result as "!two one three", or "one three !two"...

There are of course disadvantages:

1. To rebuild the regexps and apply them, the input must have a trailing space, or the user must press a special key.
2. The candidates are no longer updated as frequently as when the input changes character by character. On the other hand, this might be a good thing as it requires less computation and less redraw, in particular with large number of candidates.
3. Splitting input into patterns is more difficult than just `split-string`.

My knowledge about elisp programming is not up to the level to determine whether this model is easy to implement, and more importantly, whether it can scale up. So it is totally fine if you tell me it is not a good idea.

**Comment by abo-abo** [comment]
>     A pattern like "foo bar" accepts candidate "foo-bar" but not
>     candidate "bar-foo". While this perhaps meets user expectation
>     in most cases, it can still be undesirable in some.

I see this as a feature. It would be bad if "foo bar" would match "bar-foo". But it's all easily customizable.

>     To create or modify backslash constructs in the pattern, the
>     user must type M-q twice to enter and exit from the
>     "regexp-quote state". Forgetting doing this can end up in error
>     (see #70).

This is fixed now.

> By the way, ivy-toggle-regexp-quote appears to be inconsistent: it
> does not hide the candidates if M-q is pressed with empty input so
> there is no visual clue as when the input is not empty.

File a separate issue, please.

> #62 adds the capability to exclude matched entries from the
> candidate list. So "foo !bar" accepts "foo-abc" but not
> "foo-bar". However, it seems that it only supports one exclusion at
> most and the exclusion must be the last one (I don't fully
> understand how ivy-re-builders-alist works so it can be that I just
> need to customize this variable.)

How it works: "want1 also2 also3 ! dont1 neither2 nor3".

> So I want to discuss a different approach: So it is totally fine if
> you tell me it is not a good idea

It's not a good idea for the generic completion. Surely, I don't want it as the default.  But you can write this function for yourself, and customize `ivy-re-builders-alist`.

I'll explain the interface. Write this to use `ivy--regex-plus` for all your matching.

```elisp
(setq ivy-re-builders-alist
    '((t . ivy--regex-plus)))
```

Here's how it currently looks like:

```
(defun ivy--regex-plus (str)
  "Build a regex sequence from STR.
Spaces are wild, everything before \"!\" should match.
Everything after \"!\" should not match."
  (let ((parts (split-string str "!" t)))
    (cl-case (length parts)
      (0
       "")
      (1
       (ivy--regex (car parts)))
      (2
       (let ((r2 (ivy--regex (cadr parts)))
             (r1 (ivy--regex (car parts))))
         (list (cons r1 t)
               (cons r2 nil))))
      (t (error "Unexpected: use only one !")))))
```

The interface expects you to return a list:

```
'(("regex-that-you-want 1" . t)
  ("unwanted-regex 2" . nil)
  ("unwanted-regex 3" . nil)
  ("regex-that-you-want 2" . t)
  ;; ...
  )
```

So the interface really doesn't limit your freedom in the matching. You can do whatever you want.  You can even implement regex look-ahead that Emacs regex doesn't support.

> My knowledge about elisp programming is not up to the level to determine whether this model is easy to implement

I'm closing this issue, but you should try to implement your matcher. You can ask me of something is unclear on ivy or Elisp side. I recommend TDD:

```elisp
(require 'ert)
(ert-deftest ivy-regex-plus-1 ()
  (should (equal (ivy--regex-plus "one two ! three four")
                 (("\\(one\\).*?\\(two\\)" . t)
                  ("\\(three\\).*?\\(four\\)")))))
```

**Comment by zhaojiangbin** [comment]
> It's not a good idea for the generic completion.

Would you mind elaborating? By "generic completion", did you mean swiper? I have to admit that I was not thinking of swiper when this approach shaped up in my mind.

In my opinion, having the same syntax for matching lines in buffers and for matching candidates in complete reading functions is the best feature of ivy. If a different matching approach has to give up on this feature, I would not think that a good idea, too.

> I see this as a feature. It would be bad if "foo bar" would match "bar-foo".

Sorry that I was not clear. I was certainly not saying how ivy does matching is a bug. I think I understand how you think of matching. And as is, it works most of the time for me. Only in some rare cases I wish that it could be more flexible. But it may be just that I don't know how to use ivy to its full strength.

>The interface expects you to return a list:
```elisp
 '(("regex-that-you-want 1" . t)
  ("unwanted-regex 2" . nil)
  ("unwanted-regex 3" . nil)
  ("regex-that-you-want 2" . t)
  ;; ...
  )
```

This is where I don't quite get it. I know that `ivy-re-builders-alist` already has the default value `((t . ivy--regex-plus))`. What do I need to "return a list" like your suggested? If, for example, I want to have `foo bar` to match both `foo-bar` and `bar-foo`, what should I do?

> but you should try to implement your matcher. You can ask me of something is unclear on ivy or Elisp side.

I truly appreciate it that you're offering your help here. I am taking it. :) I hope I can find time soon to try it myself, even just for purpose of learning. What will be the best way to contact you if I want to ask you questions?

**Comment by abo-abo** [comment]
> Would you mind elaborating? By "generic completion", did you mean
> swiper? I have to admit that I was not thinking of swiper when this
> approach shaped up in my mind.

I mean the completion that a new user gets, with zero customizations to `ivy`. That one should be as un-surprising and simple as possible.

> This is where I don't quite get it. I know that
> ivy-re-builders-alist already has the default value ((t
> . ivy--regex-plus)). What do I need to "return a list" like your
> suggested? If, for example, I want to have foo bar to match both
> foo-bar and bar-foo, what should I do?

I mean that you can write your own function that looks a bit like `ivy--regex-plus`, and then replace `ivy--regex-plus` with this new function in `ivy-re-builders-alist`.

> I truly appreciate it that you're offering your help here. I am
> taking it. :) I hope I can find time soon to try it myself, even
> just for purpose of learning. What will be the best way for you if I
> want to ask you questions? I don't want to be intrusive.

You can ask on this issue.

A code that can flip parts looks like this:

```elisp
(defun ivy--regex-like-helm (str)
  (let* ((subs (split-string str " +" t))
         (len (length subs)))
    (cl-case len
      (1
       (setq ivy--subexps 0)
       (car subs))
      (t
       (setq ivy--subexps len)
       (let ((all (mapconcat #'identity subs "\\|")))
         (mapconcat
          (lambda (x)
            (if (string-match "^\\\\(.*\\\\)$" x)
                x
              (format "\\(%s\\)" x)))
          (make-list len all)
          ".*?"))))))

(setq ivy-re-builders-alist '((t . ivy--regex-like-helm)))
```

Setting `ivy--subexps` is only important for the swiper highlighting. If you want to use this one for swiper as well, you have to patch it currently, since it's hard-wired to use `ivy--regexp`.  You you can just rename this one to `ivy--regex` in your own config.
