### ISSUE TITLE
Ivy Minibuffer prompt 

### ISSUE THREAD

**Issue by surya46584** [abo-abo/swiper#710]
I am seeing this issue after recent update of the packages.

step 1. after emacs starts, find files by consel-recentf.
step 2. call eg: anzu-query-replace 

I am seeing in the mini prompt the output from the step 1 i.e Recentf file list.
basically State from the previous completion is retained.

any help or tips to debug the issue is appreciated.
thanks

**Comment by abo-abo** [comment]
I can't reproduce. Try to reproduce yourself with `emacs -Q` and loading only ivy and anzu.

**Comment by surya46584** [comment]
hi, resolved this issue. i had also added mode called "focus" and it is causing this weird behavior.
thanks for the response in time.
