### ISSUE TITLE
it's only once possible to use ivy-wgrep-change-to-wgrep-mode.

### ISSUE THREAD

**Issue by Dickby** [abo-abo/swiper#711]
Use counsel-ag and search for something,
then type C-c C-o for 'ivy-occur'
to have the matches in an ivy-occur-grep-mode buffer.

C-x C-q for ivy-wgrep-change-to-wgrep-mode to edit the buffer
C-x C-s for saving the changes.

Now C-x C-q again will just invoke read-only-mode and not 
ivy-wgrep-change-to-wgrep-mode again

**Comment by abo-abo** [comment]
Thanks, I can reproduce, but the fix isn't trivial. I'll fix it when I can, don't know how soon. Patches welcome.

**Comment by mwolson** [comment]
Further, saving the change with `C-x C-s` after a wgrep session seems to remove every ivy-occur keybinding.
