### ISSUE TITLE
counsel-ag file list

### ISSUE THREAD

**Issue by njdan5691** [abo-abo/swiper#716]
Is there a way I can get access to the list of files that my current counsel-ag session is matching. Like a keybinding that could setup to have the file list sent to a function.

**Comment by njdan5691** [comment]
Actually I should have read first this [Issue](https://github.com/abo-abo/swiper/issues/715), Your response to this issue is pretty much what I was looking for

**Comment by abo-abo** [comment]
OK, closing.
