### ISSUE TITLE
C-c C-o in counsel-imenu could use imenu-list

### ISSUE THREAD

**Issue by Dickby** [abo-abo/swiper#720]
if imenu-list is installed it could be used by counsel-imenu.

**Comment by abo-abo** [comment]
What advantage does `imenu-list` bring?

**Comment by Dickby** [comment]
it shows the categories like variables types and so on, and it's possible to fold those categories.

**Comment by Dickby** [comment]
by the way, in ivy-occur imenu it seems like read-only isn't enabled

**Comment by abo-abo** [comment]
Read-only-mode is enabled now. You can try to hook up `imenu-list` with `ivy-set-occur` in your config. I'm still not sure it's worth.

**Comment by Dickby** [comment]
Thanks
