### ISSUE TITLE
counsel-find-files should sort by shortest match

### ISSUE THREAD

**Issue by hmelman** [abo-abo/swiper#723]
I'd like counsel-find-file to sort shortest matches first. Here's my example that I keep running into while working on a tutorial:

```
(1/2) Find file: ~/Projects/quick_tutorial/request_response/tut
tutorial.egg-info/
tutorial/
```

I think "tutorial/" should sort before "tutorial.egg-info/" because it's a complete prefix and is shorter. I'm not sure why it's not sorting that way, I fear that it's because . is before / and that shouldn't be in consideration (/ just indicates it's a directory, not that it's part of the name).

 From #551 I'm still using `ivy-sort-function-buffer` in `ivy-sort-matches-functions-alist` for `counsel-find-file`. I looked in customize at `ivy-sort-matches-functions-alist` and in the wiki for a list of builtin sort functions and didn't fine one. Scanning ivy.el didn't help for a quick solution because it wasn't clear which functions with the word sort were suitable here (my attempt to use `ivy-sort-file-function-default` failed and I didn't have the time track down why) or what precisely they did (most docstrings seemed short and inadequate, `ivy--sort-files-by-date` says "Re-soft", `ivy-sort-function-buffer` says "Prefer first "^*NAME", then "^NAME"" and I don't know what that means).
1. Is there a sort function to do what I want? For use in either `ivy-sort-functions-alist` or `ivy-sort-matches-functions-alist`? 
2. It would be nice if there was some centralized place in documentation that described sort options.

**Comment by abo-abo** [comment]
I don't see why you got confused, your request is trivial to implement once you see how `ivy--sort-files-by-date` works:

```elisp
(setq ivy-sort-matches-functions-alist
      '((t)
        (ivy-switch-buffer . ivy-sort-function-buffer)
        (counsel-find-file . ivy--sort-by-length)))

(defun ivy--sort-by-length (_name candidates)
  (cl-sort (copy-sequence candidates)
           (lambda (f1 f2)
             (< (length f1) (length f2)))))
```

It's not great UX in my opinion, though; a plain alphabetic sort is better.

**Comment by hmelman** [comment]
Here's what I found confusing. I wanted to change the sort order and I didn't know internals. I figured there was a set of sort functions to choose from but I couldn't find a list. The ivy manual didn't really describe sorting choices. In the Ivy Customize Group I found:

    ivy-sort-functions-alist
    ivy-sort-matches-functions-alist

This was one more function than I expected but the description of the second explained it enough. Though I'm still not quite sure what sorting the candidates once buys you if you're always sorting the matches afterwards. An example might help. Also the name of the first might be clearer if it was 	`ivy-sort-candidates-functions-alist` and its docstring should refer to the second.

So, looking in my customizations I found `ivy-sort-function-buffer` which I find an odd name, usually `-function` is at the end. I think `ivy-sort-buffers-function` would be better. I was hoping the customize buffer would have a drop down of different function but it didn't help (just: none, prefixes first, custom).

As I looked in ivy.el for other sort functions I found:

    ivy-sort-file-function-default (x y)
    ivy-sort-file-function-using-ido (x y)
    ivy--sort-files-by-date (_name candidates)
    ivy--sort (_name candidates)
    ivy--prefix-sort (name candidates)
    ivy-sort-function-buffer (name candidates)
    ivy--flx-sort (name candidates)

I knew I wasn't using ido so `ivy-sort-file-function-using-ido` wasn't going to help me, but it's the only one that said it was for `ivy-sort-functions-alist` which was nice, but then I wondered if any of the others were.

I was confused why some were `ivy-sort-` and some were `ivy--sort-`, usually `--` means an internal function. Given there are two alists I though maybe the `ivy-sort-` were for one and the `ivy--sort-` for the others? The docstrings didn't help me much. E.g., 

    (defun ivy-sort-file-function-default (x y)
      "Compare two files X and Y.
    Prioritize directories."

doesn't say how they're compared. It's just alphabetically by name with directories first, but you have to read the code to see that. The name and first line are equally discriptive if this compared by length of name.

The args should have been a clue, but I didn't notice them. It seems `ivy-sort-functions-alist` wants functions that take (x y) args to compare and `ivy-sort-matches-functions-alist` wants functions that take (name candidates). It's still confusing that of the (name candidates) functions, one didn't use -- in the name but all the others did.

All these docstrings are somewhat different. Also they say "re-sort" but they're not destructive, they just return a new sorted list. The names are all of a different form. I think they should be:

    ivy-sort-files-by-date
    ivy-sort-files-by-name
    ivy-sort-files-by-prefix
    ivy-sort-files-by-flx
    ivy-sort-buffers-by-relevance

And it would be great if they appeared in the customize drop down for `ivy-sort-matches-functions-alist`. Also it would be nice if the docstring described the required function signature more than just referring to `ivy--prefix-sort`. Do these need to filter candidates that match name or is that already done and name is just there if it's needed to help in the sorting (as in flx)?

As you say, sorting by length alone isn't great, I had wondered if there was an easy way to combine sorting methods without just writing a new custom function. I'm not sure, but if there were, it should be described somewhere.

So that's what confused me. I was hoping I could just change something to use `string<` or something, but that's not the case and at the time I didn't have time to dive in further. Now that I do, I think my original fear was correct, that at the point of `ivy-sort-matches-functions-alist` it's just comparing strings and directory names have / appended. So I think I want to write a sort that ignores a trailing / and does a comparison and then my length problem goes away.

**Comment by hmelman** [comment]
FYI, this seems to work:

```elisp
(defun ivy-sort-files-function (_name candidates)
  "Sort CANDIDATES files alphabetically ignoring trailing slashes.
Meant for use in `ivy-sort-matches-functions-alist' so 
directories will have a trailing /, ignore it so foo.txt is after foo/."
  ;; Perhaps add a check for if directories should sort first
  (cl-sort (copy-sequence candidates)
           (lambda (x y)
             (string< (if (string-suffix-p "/" x) (substring x 0 -1) x)
                      (if (string-suffix-p "/" y) (substring y 0 -1) y)))))
```

**Comment by abo-abo** [comment]
> FYI, this seems to work:

Glad it works. You can PR this if you want and have the CA.

**Comment by ZelphirKaltstahl** [comment]
Here is a now working version:

```elisp
(defun xiaolong/ivy--sort-by-length (x y)
  "Sort given filenames X and Y according to string length.
However, give directories priority."
  (let ((cleaned-x (if (string-suffix-p "/" x) (substring x 0 -1) x))
        (cleaned-y (if (string-suffix-p "/" y) (substring y 0 -1) y)))
    (let ((length-comparison-result (string-length<= cleaned-x cleaned-y))
          (x-wins t)
          (y-wins nil))

      ;; ;; debug
      ;; (message "\ncomparing: \nx: %s,\ny: %s" cleaned-x cleaned-y)
      ;; (if (file-directory-p cleaned-x)
      ;;     (message "%s" "cleaned-x is dir")
      ;;   (message "%s" "cleaned-x is not dir"))
      ;; (if (file-directory-p cleaned-y)
      ;;     (message "%s" "cleaned-y is dir")
      ;;   (message "%s" "cleaned-y is not dir"))

      (let ((result
             ;; compare
             (if (file-directory-p cleaned-x)
                 (if (file-directory-p cleaned-y)
                     length-comparison-result
                   x-wins)
               (if (file-directory-p cleaned-y)
                   y-wins
                 length-comparison-result))))
        ;; ;; debug
        ;; (if result
        ;;     (message "%s" "x wins!")
        ;;   (message "%s" "y wins!"))

        result))))
```
