### ISSUE TITLE
Error in enabling ivy-mode after latest update in MELPA

### ISSUE THREAD

**Issue by CSRaghunandan** [abo-abo/swiper#726]
After the latest update in MELPA (version `20161024.2134`),  I am getting an error when I try to enable `ivy`. I got the following error :- `Error (use-package): ivy :init: Symbol’s value as variable is void: boolean` . It used to work fine  without any issues before. What's going on? 

For the moment, I reverted back to previous version of `ivy` (version `20161021.22141`) which is working fine.

I'm running emacs 25.1-1 on mac os el capitan.

**Comment by manuel-uberti** [comment]
I can confirm this issue, having it too. Emacs version: GNU Emacs 25.1.1 (x86_64-w64-mingw32) of 2016-09-17

**Comment by gtms** [comment]
Same issue here. Reverting temporarily to ido on GNU Emacs 25.1.1 (x86_64-apple-darwin15.6.0, NS appkit-1404.47 Version 10.11.6 (Build 15G1004)) of 2016-09-20.

**Comment by spatz** [comment]
Fixed in PR #724.

**Comment by rsuhada** [comment]
I have a  general question: what to do in these cases, when something breaks after update? Is there a way to revert to the previous version with use-package? Doesn't seems so... 

(I have the same issue with GNU Emacs 24.5.1 (x86_64-pc-linux-gnu, GTK+ Version 3.16.6))

**Comment by CSRaghunandan** [comment]
> I have a general question: what to do in these cases, when something breaks after update? Is there a way to revert to the previous version with use-package? Doesn't seems so...

I have set `delete-by-moving-to-trash` to `t` and after package update is done, the old file will be in my *trash* or *recycle bin*. If something breaks down, I can remove the new update and put back the old version which is in trash and restart emacs.

**Comment by abo-abo** [comment]
Hi this is fixed now. Sorry for the inconvenience, forgot to `make test` before `git push`.
