### ISSUE TITLE
Seems newest ivy package causes compilation issues

### ISSUE THREAD

**Issue by Atman50** [abo-abo/swiper#729]
Even if I wipe out ~/.emacs.d/elpa and reinstall all packages I continue to get tracebacks:

Debugger entered--Lisp error: (void-variable boolean)
  (custom-declare-variable (quote ivy-magic-tilde) (list (quote funcall) (list (quote function) (function (lambda nil t)))) "When non-nil, ~ will move home when selecting files.\nOtherwise, ~/ will move home." :type boolean)
  eval-buffer(#<buffer  *load*> nil "/home/adtaylor/.emacs.d/elpa/ivy-20161024.2134/ivy.el" nil t)  ; Reading at buffer position 80092
  load-with-code-conversion("/home/adtaylor/.emacs.d/elpa/ivy-20161024.2134/ivy.el" "/home/adtaylor/.emacs.d/elpa/ivy-20161024.2134/ivy.el" nil t)
  load("/home/adtaylor/.emacs.d/elpa/ivy-20161024.2134/ivy" nil t)
  #[257 "\300\301\302#\207" [load nil t] 5 "\n\n(fn FEATURE)"]("/home/adtaylor/.emacs.d/elpa/ivy-20161024.2134/ivy")
  mapc(#[257 "\300\301\302#\207" [load nil t] 5 "\n\n(fn FEATURE)"] ("/home/adtaylor/.emacs.d/elpa/ivy-20161024.2134/ivy-overlay" "/home/adtaylor/.emacs.d/elpa/ivy-20161024.2134/ivy" "/home/adtaylor/.emacs.d/elpa/ivy-20161024.2134/colir"))
  package--load-files-for-activation([cl-struct-package-desc ivy (20161024 2134) "Incremental Vertical completYon" ((emacs (24 1))) nil nil "/home/adtaylor/.emacs.d/elpa/ivy-20161024.2134" ((:keywords "matching") (:url . "https://github.com/abo-abo/swiper")) nil] :reload)
  package-activate-1([cl-struct-package-desc ivy (20161024 2134) "Incremental Vertical completYon" ((emacs (24 1))) nil nil "/home/adtaylor/.emacs.d/elpa/ivy-20161024.2134" ((:keywords "matching") (:url . "https://github.com/abo-abo/swiper")) nil] :reload :deps)
  package-unpack([cl-struct-package-desc ivy (20161024 2134) "Incremental Vertical completYon" ((emacs (24 1))) tar "melpa" nil ((:url . "https://github.com/abo-abo/swiper") (:keywords "matching")) nil])
  #[256 "\306\307!r\211q\210\310\311\312\313\314!\315\"\316$\216\301c\210\317\320\300!\210+\210\211\205

**Comment by Atman50** [comment]
Perhaps my ivy config has something to do with it:

```elisp
(use-package ivy :ensure t
  :diminish (ivy-mode . "")
  :bind
  (:map ivy-mode-map
   ("C-'" . ivy-avy))
  :config
  (ivy-mode 1)
  ;; add ‘recentf-mode’ and bookmarks to ‘ivy-switch-buffer’.
  (setq ivy-use-virtual-buffers t)
  ;; number of result lines to display
  (setq ivy-height 10)
  ;; does not count candidates
  (setq ivy-count-format "")
  ;; no regexp by default
  (setq ivy-initial-inputs-alist nil)
  ;; configure regexp engine.
  (setq ivy-re-builders-alist
	;; allow input not in order
        '((t   . ivy--regex-ignore-order))))
```

**Comment by Atman50** [comment]
Easier to read backtrace
![screenshot from 2016-10-25 10-10-38](https://cloud.githubusercontent.com/assets/3370807/19689438/5f7a88e8-9a9b-11e6-86c8-6652f83b1592.png)

**Comment by pickardjoe** [comment]
dcec964a6f09ccc1d51c645992b8be2797a8475f fixed it for me.  It was a typo.  Try making the change manually in 'ivy.el'.

**Comment by Atman50** [comment]
Awesome! That fixed it. Thanks pickardjoe!
