### ISSUE TITLE
ivy-partial-or-done inserts a space

### ISSUE THREAD

**Issue by tsdh** [abo-abo/swiper#73]
When I do `C-x C-f R` the only completion is `Repos/`.  When I hit `<tab>` now to complete it and resume completing, it completes to `Repos/ ` (note the trailing space).

**Comment by abo-abo** [comment]
Yes, it's kind of the point of it. I wanted to get around the overhead of pressing <kbd>TAB SPC</kbd> in succession. Which I think is a frequent scenario. Do you have a use case against this approach?

In any case, I can make it customizable.

**Comment by tsdh** [comment]
Well, file completion is my use case against this approach.  Say I want to find `~/Repos/el/swiper/ivy.el`, then I expected that `Re<tab>e<tab>sw<tab>i<tab>.<tab-twice-or-ret>` does that.  I.e., for ``~/Repos/el/swiper/` my inputs are good enough so that there's always just one match and thus `ivy-partial-or-done` is equivalent to `ivy-alt-done`.  The input `i` in `~/Repos/el/swiper/` leaves as candidates `ivy.el` and `ivy-test.el`, so `<tab>` partially completes to the input `ivy`, and then entering `.` leaves just one candidate (because I use a re-builder `(concat "^" (regexp-quote input))` for finding files.

With 4ad1ab2 this works for me now.  Thanks!
