### ISSUE TITLE
Symbol's value missing: boolean

### ISSUE THREAD

**Issue by KZiemian** [abo-abo/swiper#731]
I'm using swiper-helm and today it stop working with, because anytime when I try to use swiper-helm and plain swiper too I get a message "Symbols value as variable is void: boolean". I remove and install again swiper-helm, but that don't work. Does anyone have this same problem?

I am apologized if I wasting your time, I just want to know that is problem in my version of code, before I try deal with code in more serious way.

**Comment by dougad** [comment]
I think its similar with my issue https://github.com/abo-abo/swiper/issues/730

waiting for some solution :(

**Comment by KZiemian** [comment]
You are right, everything working after update of ivy.

Thank for keeping this works going.
