### ISSUE TITLE
ivy-fixed-height-minibuffer wrong size

### ISSUE THREAD

**Issue by DarthFennec** [abo-abo/swiper#732]
This isn't a big problem, just a small annoyance. When I enable `ivy-fixed-height-minibuffer`, it works fine. However, when I also enable `ivy-add-newline-after-prompt`, the minibuffer is one row smaller than it should be, unless/until it fills up, at which point it becomes the correct height.

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by DarthFennec** [comment]
Thanks, but this did not fix the issue for me. Oddly, it didn't seem to do anything at all.

I took a look myself, and I got it to work for me. PR is #737
