### ISSUE TITLE
Escaping of $ not working properly in counsel-git-grep

### ISSUE THREAD

**Issue by cocreature** [abo-abo/swiper#734]
Searching for `name\$` using counsel-git-grep works just as expected. However when I append something to that and search for `name\$1` I get the error

```
fatal: -e option, 'name\': Trailing backslash
```

It looks like the error is due to the shell (I tried bash and zsh) transforming `"name\\$1"` to `"name\"` because it interprets `$1` as a variable. `counsel-ag` does not suffer from this problem.

**Comment by abo-abo** [comment]
Can't reproduce in bash, grepping for `name$1`. I get a result just fine.

Here's the equivalent command for bash:

    git --no-pager grep --full-name -n --no-color -i -e 'name$1' -- './*' ':!*.htm'

**Comment by cocreature** [comment]
Sorry I completely forgot about this issue and I can’t reproduce it anymore. Thanks for all your great work, counsel is a pleasure to use.

**Comment by abo-abo** [comment]
You're welcome.
