### ISSUE TITLE
Missing information for possible actions on pressing ``` M-o ``` ?

### ISSUE THREAD

**Issue by hhnr** [abo-abo/swiper#736]
I have looked through the ivy user manual briefly, couldn't find what i was looking for. When ivy offers a list of selections, by pressing `M-o`, we could choose different actions to run. For example, with `ivy-mode` enabled and by pressing `C-x b`, ivy shows list of buffers to switch. By pressing `M-o` we can see a list of options, like k to kill the buffers. Is this list of actions documented somewhere? In case of switch-to-buffer there are multiple actions and in case of find-file only one action is there. 

I'm asking this question because one of the functionality i use is kill buffer when a list of buffers is shown in switch to buffer command. 

In case of `ido-mode` we can use `C-k` to kill the first candidate. And in case of `helm-mode` we can use `M-D` to delete the current highlighted buffer. Both of these key bindings and functionalities are mentioned in ido  and helm documentation respectively.

It took me a while to figure out that ivy had this functionality. 

Thanks,
Hari

**Comment by abo-abo** [comment]
You're right, the action lists are not documented.

You can examine `ivy--actions-list` to see all of them, and use `ivy-add-actions` to extend them.

Documentation patches welcome, but an Emacs copyright assignment is required, see the README.

**Comment by rdotdk** [comment]
Thanks for the quick reply. I don't have a copyright assignment as of now. I'll send a mail to FSF regarding copyright.

**Comment by basil-conto** [comment]
> I have looked through the ivy user manual briefly, couldn't find what i was looking for.

Does [`(ivy) Actions`](http://oremacs.com/swiper/#actions) do the job? If not, what sort of documentation is desired?

> In case of switch-to-buffer there are multiple actions and in case of find-file only one action is there.

That is probably because you are using `ivy-switch-buffer`, which is a reimplementation of `switch-to-buffer` using `ivy-read`, and vanilla `find-file`, which does not use `ivy-read`. For more featureful file name completion consider using `counsel-find-file` instead.

**Comment by abo-abo** [comment]
I think this can be closed now. If new info is available on this, please open a new issue.
