### ISSUE TITLE
(wrong-type-argument window-live-p #<frame emacs@IdeaPad 0x1224f10>)

### ISSUE THREAD

**Issue by joostkremers** [abo-abo/swiper#739]
Just updated `ivy` and now whenever I try to run `swiper`, I get the following error:

    (wrong-type-argument window-live-p #<frame emacs@IdeaPad 0x1224f10>)

Also happens with `emacs -Q -L  .elpa/ivy-20161026.2249/ -L .elpa/swiper-20161011.747/`.

I can provide a backtrace, if that's helpful.

**Comment by abo-abo** [comment]
Please recompile and reload all files that depend on ivy. I extended a `cl-defstruct` statement in ivy.el yesterday and that requires a recompile of all packages that require ivy.

**Comment by joostkremers** [comment]
Yep, that works. Thanks for the quick reply!
