### ISSUE TITLE
swiper--update-input-ivy: Wrong type argument: window-live-p

### ISSUE THREAD

**Issue by swarnendubiswas** [abo-abo/swiper#740]
I have started running into this issue with `swiper`, possibly after recent updates. The error is `swiper--update-input-ivy: Wrong type argument: window-live-p`. I get this with both Emacs 25.1 and the development version. 

I can reproduce the issue evaluating the following snippet with `emacs -Q` and invoking `swiper`.

```
(require 'package)
(setq package-user-dir (expand-file-name "~/.emacs.d/elpa/")
      package-enable-at-startup nil)
(add-to-list 'package-archives
             '("melpa" . "https://melpa.org/packages/") t)
(package-initialize)

(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))
(eval-when-compile
  (require 'use-package))

(use-package swiper 
  :ensure t
  :bind ("C-c r" . ivy-resume)
  :config
  (setq swiper-use-visual-line t
        swiper-action-recenter t))
```

**Comment by frostidaho** [comment]
Try removing & reinstalling ivy/swiper/counsel. I was having this bug until I removed all of the 3rd party packages

**Comment by abo-abo** [comment]
@frostidaho Thanks, that's the correct solution. Unfortunately, there's not yet a way for package.el to trigger a recompile automatically.

**Comment by sjLambda** [comment]
M-x byte-recompile-directory on the swiper directory will fix that as abo-abo suggested elsewhere. No need to reinstall everything.

**Comment by stefanq** [comment]
@sjLambda 
I found a swiper directory ~/.emacs.d/elpa/swiper-20161011.747
Opened it and did byte-recompile-directory on it but this has no effect.
Doing byte-recompile-directory on the whole elpa directory also had no effect (also not after emacs restart).

Removing & reinstalling ivy/swiper/counsel helped though.

**Comment by sjLambda** [comment]
Interesting. I also recompiled and nothing changed, but after I first
deleted all the *.elc files before byte compiling, then it worked.

Also, I don't know if this has any bearing: I usually download the latest
trunk from savannah.

**Comment by guylyons** [comment]
I ran into the same issue with this. After removing the swiper package and reinstalling it is now working fine.

**Comment by marczz** [comment]
Recompiling the swiper directory **do work**, but just issuing M-x `byte-recompile-directory` has no effect because (C-h f byte-recompile-directory) : _recompilation happens when a `.elc' file exists but is older than the `.el' file._ and here the .elc files are up-to-date. You have to delete the .elc files, then issue
C-u M-x `byte-recompile-directory` you will be prompted if you want to compile each uncompiled .el file.

I suppose that people that had issue when recompiling have not seen the message _(Total of 0 files compiled, 3 skipped)_

**Comment by rsuhada** [comment]
Just a small note - marczz solution works (don't forget the "C-u" before M-x `byte-recompile-directory` and after compilation reload (restart emacs).
