### ISSUE TITLE
Swiper broken with I-search "Wrong type argument: window-live-p"

### ISSUE THREAD

**Issue by papachan** [abo-abo/swiper#741]
I just updated latest realeas with emacs 25.5.1 and i have this output when i try to use I-search with swiper:

`swiper--update-input-ivy: Wrong type argument: window-live-p`

**Comment by mrkkrp** [comment]
The same here.

**Comment by omajid** [comment]
See #740. The fix is to remove ivy/swiper/counsel (and any dependencies?). I removed `~/.emacs.d/elpa` and reinstalled everything and now it works fine.

**Comment by abo-abo** [comment]
Thanks @omajid, that's the correct fix. I wish there was a feature in package.el for triggering the recompilation automatically. This type of issue pops up from time to time in other places as well.
