### ISSUE TITLE
Strange Ivy/Counsel behaviour for commands

### ISSUE THREAD

**Issue by rakanalh** [abo-abo/swiper#747]
Hello,

I recently switched to using Ivy instead of Helm... however, one of things i found weird is basically when triggering rgrep through M-x.

In helm:
1) Enter search word
2) Select which file extensions i would like to search (*.py, Makefile, *.css .. etc) without any prefixed directories
3) Select the base directory in which the search is conducted.

In Counsel:
1) Enter search word
2) Type in the regex? i would like to search with... This is basically where it gives me my current `pwd`/*.py or whatever i want to search
3) Select the base directory.

I find step 2 a little weird because it includes entering both the directory and the extension, which is nice btw but the 3rd step would be redundant in that case. Otherwise step 2 should let me select the file type (extension) and step 3 would have me select the base directory.

Here are some screenshots for step 2 & 3 for rgrep

![Image1](http://i.imgur.com/KI9xrSP.png)

![Image2](http://i.imgur.com/V3Xjxb3.png)

Is this a bug? if not, is it configurable?

**Comment by abo-abo** [comment]
> Is this a bug?

It's not a bug, that's the default behavior of `rgrep`.

> if not, is it configurable?

I don't think so. I use either `counsel-git-grep` or `counsel-ag` for the task.

**Comment by rakanalh** [comment]
@abo-abo thanks for the reply. As i said, i am comparing behaviours with Helm and finding some differences.
I tried counsel-ag... seems like its only searching open buffers for the keyword i am providing and not behaving like rgrep. Is this also intended?

counsel-git-grep seems to do the trick nevertheless

**Comment by rakanalh** [comment]
rename-file command also seems to have a weird behaviour if i try to rename a file called `json_configuration.py` to `configuration.py` ... while i am writing configuration.py it seems to be filtering existing files until `json_configuration.py` is the only one left and the rename just does nothing because pressing enter selected the `json_configuration.py` name rather than the one i typed.

**Comment by abo-abo** [comment]
> rename-file command also seems to have a weird behaviour if i try to rename a file called json_configuration.py to configuration.py ... while i am writing configuration.py it seems to be filtering existing files until json_configuration.py is the only one left and the rename just does nothing because pressing enter selected the json_configuration.py name rather than the one i typed.

For these situations you need to press <kbd>C-M-j</kbd> instead of <kbd>C-j</kbd> or <kbd>C-m</kbd>.

**Comment by rakanalh** [comment]
Thank you for clarifying
