### ISSUE TITLE
ivy seems to get confused about live windows

### ISSUE THREAD

**Issue by stsquad** [abo-abo/swiper#749]
I haven't found a decent reproducer yet but I'm wondering if it's due to starting a Emacs daemon in terminal mode then closing it before bringing up an X11 window:

    Debugger entered--Lisp error: (wrong-type-argument window-live-p #<frame #qemu-mttcg 0x5e92b38>)
      window-end(#<frame #qemu-mttcg 0x5e92b38> t)
      swiper--update-input-ivy()
    ...rest of backtrace elided due to noise...

Is there anyway to reset ivy-last to unwedge ivy?

**Comment by abo-abo** [comment]
This issue is solved by recompiling/reloading all ivy-related files. See #741 #740 #739

**Comment by stsquad** [comment]
Ahh I missed that when searching issues as they were all closed. Sorry for the noise.

**Comment by stsquad** [comment]
this is a very old issue now and I haven't seen this in ages.

**Comment by abo-abo** [comment]
Thanks.
