### ISSUE TITLE
cursor following and recenter after choose in counsel-pt

### ISSUE THREAD

**Issue by kimim** [abo-abo/swiper#751]
Hi abo-abo,

I want achieve two thing,

1. is it possible to move the cursor in buffer to the position selected in counsel-pt, as same as in swiper?
2. how to recenter the buffer when choose the occurance in counsel-pt? When the line is chosen by type Enter, the line of the buffer is not in center, is it possible to recenter it as the way next-error in compile mode do? when (setq next-error-recenter 20), the cursor will always located at line 20.

Thanks.
BRs,
Kimi

**Comment by Yevgnen** [comment]
For 1, do you mean `C-M-p` and `C-M-n` ?

**Comment by kimim** [comment]
@Yevgnen Yes! Thanks for your suggestions.

**Comment by abo-abo** [comment]
I don't use `counsel-pt` so far. But PR to fix it is welcome.

**Comment by kimim** [comment]
@abo-abo PR created for this case. now, when I do ivy-done or ivy-call at counsel-grep, counsel-ag, counsel-pt, the cursor will always in the center of the buffer. 
could you help to review my code. Thanks.

**Comment by abo-abo** [comment]
Thanks, I merged the PR with minor changes.

**Comment by kimim** [comment]
I am glad that I can contribute to ivy. Thank you for creating this excellent package.
