### ISSUE TITLE
Ignoring "./" and "../" in counsel-find-file?

### ISSUE THREAD

**Issue by parbo** [abo-abo/swiper#752]
I've tried using (setq counsel-find-file-ignore-regexp "\\`\\.") and other variants, but no matter what, the current and parent directories appear. I have some stuff in deep folder hierarchies where I'd just like to C-j my way down.

**Comment by abo-abo** [comment]
See `ivy-extra-directories`.

**Comment by parbo** [comment]
:+1:

**Comment by wpcarro** [comment]
> See `ivy-extra-directories`.

By this, do you mean to remove `'("../" "./")` from `ivy-extra-directories`? I'd like to remove these directories from a single function call, is `let` (see below) the best way to temporarily disable these variables?

```elisp
(let ((ivy-extra-directories '()))
  (counsel-find-file "~/Dropbox/org"))
```

Is there an existing function that already does this? I'd prefer consuming that if it exists.

Thanks!

**Comment by abo-abo** [comment]
@wpcarro using the let binding as you do now is the way to go.
