### ISSUE TITLE
On 25.1, holding ↓ or ↑ makes Emacs hang indefinitely

### ISSUE THREAD

**Issue by michalrus** [abo-abo/swiper#753]
The title says it all. =)

After switching to Emacs 25.1, when I press, say, `M-x` and then `↓` and hold it long enough for X11 to start repeating it, I can only get 3-4 items down the list, CPU usage goes up to 100%, and Emacs hangs. Pressing `C-g` afterwards helps.

This happens with all Ivy completions, `counsel-find-file`, `counsel-grep-or-swiper` etc.

Versions:
* ivy                20160905.940
* swiper             20160905.940
* counsel            20160906.750

**Comment by michalrus** [comment]
Update: with all three versions at 0.8.0, everything works perfectly. Guess, I’ll move back to MELPA Stable with Ivy. =)

**Comment by abo-abo** [comment]
Can't reproduce, I suggest to reinstall the packages and restart.

**Comment by michalrus** [comment]
Hmm, reinstalling wouldn’t change anything, since it’s NixOS. =)

If you can’t reproduce, let’s close this, as I’m perfectly happy with stable versions, now.

Thank you!
