### ISSUE TITLE
swiper--update-input-ivy: Wrong type argument: window-live-p, #<frame F2 0x103a68e68>

### ISSUE THREAD

**Issue by 0x4ec7** [abo-abo/swiper#754]
See [https://github.com/redguardtoo/emacs.d/issues/518](url)

**Comment by redguardtoo** [comment]
I can reproduce the issue on emacs-nox 24.4.1, debian 8.6,

**Comment by abo-abo** [comment]
A recompile and reload should solve it.

**Comment by robbyoconnor** [comment]
This fixed it <3

**Comment by 0x4ec7** [comment]
Recompilation does solve the problem. Thanks.
