### ISSUE TITLE
Loading focus breaks ivy-mode

### ISSUE THREAD

**Issue by thblt** [abo-abo/swiper#755]
When [focus mode](https://melpa.org/#/focus) is loaded (without activating `focus-mode`,  `(use-package focus)` or `(require 'focus)` is enough), ivy starts behaving strangely: typing M-x, C-g then M-: displays the M-x completion buffer again, except that it behaves likes the normal `eval-expression` minibuffer (that is, completions are for M-x, but input is interpreted as in M-:).   More generally, ivy completion windows seems to be completely unrelated to the context.

## Steps to reproduce

From `emacs -Q` (with both ivy and focus installed), evaluate this:

```elisp 
(require 'package)
(package-initialize)

(require 'ivy)
(require 'focus)
(ivy-mode t)
``` 

Press M-x, C-g, M-: 

**Result**: the M-x window appears again, complete with M-x prompt, instead of the expected "Eval:" prompt.  Suggested completions are interactive commands names, but result is correctly evaluated as elisp (just accepting a suggested interactive command and pressing return fails with "Trailing garbage following expression")

C-x-f  C-g M-: displays find file instead of M-x where the Eval: prompt should be, and so on.

The bug doesn't appear if `(require 'focus)` is commented out. 

## Configuration

I can reproduce this bug in either Emacs 24 or 25 from official repositories in Debian Stretch (=testing).  I've also experienced it in ArchLinux with packaged Debian 25, although I haven't tried the exact steps above in this distro, the problem should be the same.

Emacs 24 use latest ivy and focus from Melpa, Emacs 25 use latest ivy and focus from Melpa *stable*. 

As this is a package incompatibility, I'm tagging @larstvei, the author of focus-mode.

**Comment by larstvei** [comment]
Hi, thanks for providing such a nice description of the problem. Focus is the package that is causing the issue. I've located the issue, but have not completely worked out how to mend the issue without breaking a feature. I expect to have it sorted out by tomorrow.

**Comment by thblt** [comment]
Fixed by the commit above.

**Comment by abo-abo** [comment]
@thblt @larstvei thanks.
