### ISSUE TITLE
Can I get smex sorting in all of my Ivy completions?

### ISSUE THREAD

**Issue by raxod502** [abo-abo/swiper#756]
I really like the sorting order provided by Smex (which is automatically used by Ivy in `counsel-M-x`), and prefer it to any other sorting order (fuzzy, out-of-order, regular, ...). Is it technically feasible to use the Smex engine for not only `counsel-M-x`, but also `counsel-describe-function`, `counsel-describe-variable`, Ivy's `completing-read`, and so on?

This could be difficult because a different `smex-items` file would be required for each different type of command, and in an ideal world some commands would have a file for each, say, project (for instance, using a `completing-read` to select a namespace to switch to in a Clojure project). But I don't know enough to determine the feasibility of such a proposal. What do you think?

**Comment by abo-abo** [comment]
This is certainly feasible and I'd love to have such a feature. But I don't have time currently to implement it.

See #436 for discussion on this topic, I close this issue since it's a duplicate.
