### ISSUE TITLE
`ivy-display-function-lv` is not defined

### ISSUE THREAD

**Issue by jtamagnan** [abo-abo/swiper#759]
It seems like one of the choices for `ivy-display-function`, `ivy-display-function-lv` is undefined

**Comment by abo-abo** [comment]
Quoting the doc of `ivy-display-function`:

> See https://github.com/abo-abo/swiper/wiki/ivy-display-function.

The experimental choices are present for reference. They are not included in `ivy.el` because they lack polish and introduce dependencies. People that want to add them to their own config have the reference to the wiki page.
