### ISSUE TITLE
ivy-partial-or-done shouldn't always be done on double-tab

### ISSUE THREAD

**Issue by tsdh** [abo-abo/swiper#76]
Currently, typing `<tab>` twice in a row signals to `ivy-partial-or-done` that it should be done.  However, that's not the right thing in all cases.

Consider you have `~/some/long/path/to/file.txt` where each of these directories contains just one file or subdirectory.  Here, I expect that `C-x C-f so<tab><tab><tab><tab><tab>` would open `foo.txt`.  However, that doesn't work because typing `<tab>` twice in a row is handled as "done".

In my opinion, the "done" check cannot simply be `(eq this-command last-command)`.  Instead, it must also hold that the `last-command` couldn't do anything.  In my scenario above, the first `<tab>` completed `so` to `some/`, so the next `<tab>` should have normal "try completion first before assuming I'm done" semantics again.

**Comment by abo-abo** [comment]
I've forwarded to `ivy-alt-done` to fix a different issue.
I think it should fix this one as well. Can you please check.

**Comment by tsdh** [comment]
Yes, the commit for one of the other issues fixed this one, too.  I'm closing the issue.  Thanks!

**Comment by tsdh** [comment]
Reopening due to a very minor issue: When I want to find a nonexistent file, now the confirmation prompt (`confirm-nonexistent-file-or-buffer` set to `t`) appears after hitting `<tab>` twice so to actually find it, I have to type `<tab>` three times in a row.

Also, there's no confirmation prompt at all when switching to a nonexistent buffer.  I'm not sure if that's a regression or if your commit implementing #60 didn't handle buffers.

**Comment by tsdh** [comment]
Yep, now I get the confirmation prompt for files and buffers.

What's still there is the triple `<tab>` to find a nonexistent file or buffer (two tabs give the confirmation prompt, the third tab confirms and opens the file or buffer).  But that's probably ok and intended.  When I use `<return>` instead of `<tab>` when finding a nonexistent file or buffer, it works exactly as expected, i.e., the first `<return>` already gives the confirmation prompt.

**Comment by abo-abo** [comment]
Double tab should work now, with your settings.

**Comment by tsdh** [comment]
Confirmed.  Thank you!

**Comment by basil-conto** [comment]
*Many years later...*

I don't entirely agree with the approach here: `confirm-nonexistent-file-or-buffer` handling should not be forced on all completion which happens over `read-file-name-internal` or `internal-complete-buffer`, as this can lead to false negatives and false positives, and is not what vanilla Emacs does.

Instead, `ivy-done` should be agnostic to `confirm-nonexistent-file-or-buffer`, and completion commands (e.g. `ivy-switch-buffer`, `counsel-find-file`) that know they are visiting potentially nonexistent candidates should use the result of `(confirm-nonexistent-file-or-buffer)` the function as the corresponding `:require-match` argument. This requires actually handling `confirm` and `confirm-after-completion` values for `:require-match` which Ivy does not currently do, but I am currently finalising a patch which does what I propose.
