### ISSUE TITLE
counsel-m-x cd doesn't work

### ISSUE THREAD

**Issue by parbo** [abo-abo/swiper#760]
When I do M-x cd, I get completion support and so on, but when I press RET there's no change. The global value for default-directory is still nil. Have I misconfigured something?

**Comment by parbo** [comment]
`(use-package counsel
  :ensure t
  :config
  (setq counsel-find-file-ignore-regexp
        (concat
         ;; File names beginning with # or .
         "\\(?:\\`[#.]\\)"
         ;; File names ending with # or ~
         "\\|\\(?:\\`.+?[#~]\\'\\)"))
  :bind
  (("M-x" . counsel-M-x)
   ("C-x C-f" . counsel-find-file)
   ("<f1> f" . counsel-describe-function)
   ("<f1> v" . counsel-describe-variable)
   ("<f1> l" . counsel-load-library)
   ("<f2> i" . counsel-info-lookup-symbol)
   ("<f2> u" . counsel-unicode-char)
   ("C-c o" . counsel-git)
   ("C-c g" . counsel-git-grep)
   ("M-y" . counsel-yank-pop)
   :map ivy-minibuffer-map
   ("M-y" . ivy-next-line)))

(use-package ivy
  :ensure t
  :diminish ivy-mode
  :init
  (ivy-mode 1)
  :config
  (setq ivy-use-virtual-buffers t)
  (setq ivy-display-style 'fancy)
  (setq ivy-wrap t)
  (setq ivy-re-builders-alist
        '((swiper . ivy--regex-plus)
          (t . ivy--regex-fuzzy)))
  (setq ivy-initial-inputs-alist nil)
  (setq ivy-extra-directories nil)
  :bind
  (("C-c b" . ivy-resume))
  )

(use-package swiper
  :ensure t
  :bind
  (("C-s" . swiper))
  )
`

**Comment by abo-abo** [comment]
Thanks, please test. While `cd` should work fine now, some other file-based command may potentially break because of this change.
