### ISSUE TITLE
How can I bind a key to exit an ivy / minibuffer interaction

### ISSUE THREAD

**Issue by jsyjr** [abo-abo/swiper#762]
I have [F1] bound to ivy-switch-buffer.  Once the ivy interaction start I would like a second [F1] to quit just as if I had typed [C-g].  Any suggestions?

**Comment by abo-abo** [comment]
(define-key ivy-minibuffer-map (kbd "<f1>") 'keyboard-quit)

**Comment by jsyjr** [comment]
I had already tried that.  It does not work.  Notice that I am attempting to use [F1] to invoke ivy-switch-buffer and once inside the ivy interaction to use [F1] to cancel.  I have exactly your suggestion wrapped in 

    (eval-after-load "ivy" (define-key ivy-minibuffer-map (kbd "<f1>") 'keyboard-quit))

Yet within the ivy interaction [F1] is bound to ivy-switch-buffer.

**Comment by abo-abo** [comment]
This works for me:

    (eval-after-load "ivy"
      '(define-key ivy-minibuffer-map (kbd "<f1>") 'minibuffer-keyboard-quit))
    (global-set-key (kbd "<f1>") 'ivy-switch-buffer)

Note that you had an error in `eval-after-load` (a quote is needed). Also, the command should be `minibuffer-keyboard-quit`.

**Comment by jsyjr** [comment]
Thank you.  That does indeed work.
