### ISSUE TITLE
use swiper+ivy-occur to delete/replace certain lines/values?

### ISSUE THREAD

**Issue by zeltak** [abo-abo/swiper#763]
Hi

i just discovered a cool tip that allows one to use emacs occur and then press 'e' and search and replace that buffer which changes the original buffer

I was wondering if the same can be achieved with swiper+ivy-occur? that is use swiper to search for a string (lets say page) and then in the relevant ivy occur buffer either quick delete or use query replace to operate on that narrowed buffer which is reflected in the original buffer.

is that possible? if not anyone know of other methods of doing that?

best

Z

**Comment by abo-abo** [comment]
Install `wgrep`, press <kbd>C-x C-q</kbd> to edit, press <kbd>C-c C-c</kbd> to finish.

**Comment by basil-conto** [comment]
Can this issue be closed?

**Comment by abo-abo** [comment]
Yes :)
