### ISSUE TITLE
swiper-all navigation breaks after invalid regexp

### ISSUE THREAD

**Issue by Wilfred** [abo-abo/swiper#765]
Given a buffer with the following contents:

```
foo=[1,2,3]
foo=[4,5,6]
```

And the following ivy settings:

```lisp
(setq ivy-re-builders-alist '((t . ivy--regex-ignore-order)))
```

`M-x swiper-all RET foo=\[`  breaks ivy. I cannot move between results in the minibuffer (e.g. by pressing C-n and C-p).

I get the following error in `*Messages*`:

```
Error in post-command-hook (ivy--exhibit): (invalid-regexp "Trailing backslash")
```

The problem seems to occur when I've typed `foo=\` but haven't yet typed the `[`.

**Comment by abo-abo** [comment]
Thanks for the report, I can reproduce it.

I never use `ivy--regex-ignore-order` and don't have too much time right now, so I would really appreciate a PR with a fix.

Here's what a volunteer can do:

1. Eval this to see the error comes from a bad regex:

    (swiper-all-function "foo=\\")

2. Eval this to see where the bad regex comes from:

    (ivy--regex-ignore-order "foo=\\")
    ;; =>
    ;; (("foo=\\" . t))

3. Update `ivy--regex-ignore-order` to return `"foo=\\\\"` in this case.

4. Add an ERT test for this to `ivy-test.el`.

**Comment by Wilfred** [comment]
Thanks, that's really helpful. I've created a PR along the lines you described.
