### ISSUE TITLE
How to make fuzzy matcher as default in swiper search? 

### ISSUE THREAD

**Issue by wudixiaotie** [abo-abo/swiper#769]
Everytime I search with Key <kbd>C</kbd>-<kbd>s</kbd>, I have to toggle to fuzzy matcher use key <kbd>C</kbd>-<kbd>o</kbd> <kbd>m</kbd>.

But in buffer select mode(<kbd>C</kbd>-<kbd>x</kbd> <kbd>C</kbd>-<kbd>b</kbd>), the default matcher is fuzzy.

**Comment by Yevgnen** [comment]
Maybe you want `(add-to-list 'ivy-re-builders-alist '(swiper . ivy--regex-fuzzy))`?

**Comment by wudixiaotie** [comment]
I set
```
(setq ivy-re-builders-alist
        '((swiper . ivy--regex-fuzzy)
          (t . ivy--regex-fuzzy)))
```
still not working

**Comment by am** [comment]
Same here, any solution for this?

**Comment by abo-abo** [comment]
Can't reproduce, the code by @wudixiaotie works for me.
