### ISSUE TITLE
Minibuffer collapses to one line after some time

### ISSUE THREAD

**Issue by rootzlevel** [abo-abo/swiper#77]
Here's what happens if I reduce the number of candidates enough that they fit in less space than `ivy-height`:

  1. Nothing, the candidates are displayed as before with empty lines filling the remaining space.
  2. After a few seconds, the window collapses down to one line so I can' t see any candidates at all. (The candidate number is still displayed and correct)
  3. After another few seconds, the window resizes again; now to the minimum height to display all candidates.

**Comment by rootzlevel** [comment]
I'm sorry, I can't reproduce that in a fresh emacs instance.

But nevertheless it happeed, so I'll try to reproduce it today close the bug if I can't. Maybe my emacs instance just was in some weird state

**Comment by abo-abo** [comment]
OK, thanks for reporting.

**Comment by rootzlevel** [comment]
Ok, I have an emacs instance that behaves that way, again. How can I debug the issue?

(The commonality between my two emacsen that showed the bug, that I can see right now, is: They were (fairly) long running (a day or so) and have a lot of tramp-buffers open)

**Comment by rootzlevel** [comment]
Ok, I found a minimal testcase: It happens if a tramp buffer with auto-revert-mode is open. Closing the buffer makes the issue go away.

**Comment by abo-abo** [comment]
Thanks a lot, I'll try to look into this soon. Can you eval `ivy-height`?

**Comment by rootzlevel** [comment]
I've set `ivy-height` to 20

**Comment by abo-abo** [comment]
And it's still 20 /during/ the bug?

**Comment by rootzlevel** [comment]
Ok, so I tried the following:

```
(defun hpd/trace-ivy-width ()
  (interactive "")
  (with-current-buffer (get-buffer-create "*ivy-height-trace*")
    (insert (format "ivy-heigth: %d\n" ivy-height))))

(define-key ivy-minibuffer-map (kbd "<f1>") 'hpd/trace-ivy-width)
```

Pressing <kbd>F1</kbd> loggs `ivy-height: 20`, but also immediatly expands the buffer to the minimum needed width to display all candidates. (Just the same as what happens if I don't press <kbd>F1</kbd> (or any other key for that matter) and instead wait a few seconds)

**Comment by abo-abo** [comment]
See if the last change helps. I'm just guessing here.

**Comment by rootzlevel** [comment]
Unfortunately that didn't fix it. But I tried to set `resize-mini-windows` permanently to `t`, and that prevents this bug from happening (it's not good workaround of course, since the constant size changing is irritating, but the bug doesn't occur)

**Comment by abo-abo** [comment]
Can you reliably reproduce the bug with tramp? Or you still have to keep a very long working session?  Does the bug reoccur quickly once it happens for the first time?  Could you try to reproduce with `emacs -Q`?

**Comment by rootzlevel** [comment]
No, I still can't reliably reproduce the bug, but it happens every time with tramp buffers and auto-revert-mode after a few hours (haven't tried to meassure the exact time). Also, if it occurs for the first time, it always does afterwards, until I close all tramp buffers. If I reopen them, the bug immediatly reappears.

**Comment by rootzlevel** [comment]
I almost thought this bug had fixed itself, when it happened again. But this time without tramp buffers but multiple emacsclient-frames open on the same server. Also, this time it was shortly after the start of the emacs server.

I still cannot reproduce it reliably and also haven't been able to see it in emacs -Q, yet.

**Comment by tumashu** [comment]
1. if you set minibuffer truncate-line to t,  menu disapear
2. if main window too small, menu disapear too.

**Comment by rootzlevel** [comment]
Nice! I haven't used multiple-frame configurations in the last months, but I'll see If I can still reproduce this. Would be really nice if it's fixed

**Comment by amosbird** [comment]
When truncate-line is `t`, this issue still exists. 

Here is the reproduce steps,
```
make plain
eval (add-hook 'minibuffer-setup-hook (lambda () (interactive) (setq-local truncate-lines t)))
C-x C-f
M-o
```
