### ISSUE TITLE
Face of `counsel-recentf` candidates are being affected by `ivy-virtual`.

### ISSUE THREAD

**Issue by Yevgnen** [abo-abo/swiper#770]
This happens when `ivy-virtual-abbreviate` is set to `'full`.

Test file 

```
(package-initialize)

(setq ivy-use-virtual-buffers t
      ivy-virtual-abbreviate 'full)

(custom-set-faces
 '(ivy-virtual ((t (:foreground "red" :weight bold)))))

(recentf-mode 1)

(require 'ivy)
(ivy-mode 1)

(require 'counsel)
(counsel-mode 1)
```

Run `counsel-recentf` to open some files, the run `ivy-switch-buffer`, again run `counsel-recentf` will see the differences, as

![recentf](https://cloud.githubusercontent.com/assets/16749790/20237352/66ca4b38-a90a-11e6-8306-5b81f797dda9.gif)

**Comment by abo-abo** [comment]
Thanks, this should fix it.
