### ISSUE TITLE
Wrong base command of `counsel-pt` after `ivy-resume`

### ISSUE THREAD

**Issue by Yevgnen** [abo-abo/swiper#777]
Reproducing:

Run `counsel-pt` for `PATTERN`, then close, then run `ivy-resume`, the candidates that match `PATTERN` may still be displayed, but the command run this time is in fact `ag`(by printing `ag-cmd` in function `counsel-ag-function`), since `counsel-pt` calls `counsel-ag`.

Thanks !

**Comment by manuel-uberti** [comment]
It is not happening with `counsel-rg`, which uses `counsel-ag` as well.

**Comment by abo-abo** [comment]
Thanks, should be fixed in #1474.
