### ISSUE TITLE
using ivy as projectile completion systems breaks ivy

### ISSUE THREAD

**Issue by CSRaghunandan** [abo-abo/swiper#779]
This took me **hours** to figure out what was causing this bug :(  `ivy` was working fine with `projectile` till yesterday. That's when things started acting really weird and buggy.  I notice 2 really bad problems so far :
* `find-file` is broken. emacs opens the wrong directory when I execute `find-file` on a file (this problem whens I've at least 2 projectile projects open).
* `projectile` mixes up files from different projects as it's own. Here is an example : 
<img width="230" alt="screen shot 2016-11-16 at 9 05 19 pm" src="https://cloud.githubusercontent.com/assets/5226809/20353352/95046e3c-ac40-11e6-9874-b678fabe81d9.png"> 

When I execute `projectile-switch-to-buffer` the `4-length.hs` file belong to a completely different project, yet it's identified as being part of `arcade-rs` project.

I'm not sure what's wrong with my emacs config that's causing `ivy` to break like this :(  I tried tinkering with `ivy` and `projectile` config files, but I was unable to find what's causing this problem. I suspect some dependent package got updated which broke my config?? 

Link to config files :
* [projectile](https://github.com/CSRaghunandan/.emacs.d/blob/master/setup-files/setup-projectile.el)
* [ivy](https://github.com/CSRaghunandan/.emacs.d/blob/master/setup-files/setup-ivy.el)

I'm running emacs 25.1.1 on mac osx el capitan.

**Comment by abo-abo** [comment]
I haven't had any problems, and I can't guess the cause of the error.

If you want help, you'll need to provide a recipe to reproduce this with `emacs -Q` and:

1. Relevant elisp setup.
2. Relevant files for projects.
3. List of key sequences to reproduce the bug.

**Comment by swarnendubiswas** [comment]
I have the same issue with `find-file` after the recent update, I will see if I can provide a recipe. But maybe it is other projects which are breaking `ivy`.

**Comment by CSRaghunandan** [comment]
@abo-abo  Here's how I reproduced the problem in `emacs -q` :
* evaluate `(package-initialize)`
* enable projectile -> enable ivy -> enable counsel
* evaluate `(setq projectile-completion-system 'ivy)`
* open at least 2 files from any two(or more) projectile projects
* run `projectile-switch-to-buffer` (sometimes `find-file` opens wrong directory, and other times it works correctly. There is no surefire way of reproducing the bug. It depends on your project) and watch out for files that don't belong in the project.

@swarnendubiswas Can you check if you encounter the issue when doing the steps I wrote above?

**Comment by swarnendubiswas** [comment]
@CSRaghunandan It worked during my test, no problems. 

I also tried to narrow down the source, but it seems a bit non-deterministic.

**Comment by kaushalmodi** [comment]
Found the culprit commit!

https://github.com/abo-abo/swiper/commit/2237916a4ebd427ff9dae3ad9cda46a35ce7ace4#commitcomment-19874210

**Comment by julienfantin** [comment]
Hmm actually this doesn't fix the issue I reported.
