### ISSUE TITLE
ivy-alt-or-done on a file jumps back to ~/

### ISSUE THREAD

**Issue by julienfantin** [abo-abo/swiper#782]
Not sure which commit broke this, but with `counsel-find-file` when calling `ivy-alt-or-done` with a file selected doesn't open it and jumps back to the user home directory.

**Comment by wenjie2wang** [comment]
Same thing happens for ESS (Emacs Speaks Statistics).  `M-x R` and hitting Enter simply jumps back to the home directory.  Hitting enter does not open ESS.  Disable ivy-mode fixes the problem.

**Comment by kaushalmodi** [comment]
+1

**Comment by julienfantin** [comment]
Here's the commit that breaks things for me: aacba19ad5f4e9a9e0767376b714b47db3320bb7

**Comment by kaushalmodi** [comment]
I have sent something like this 2/3 times in past few days, but I haven't been able to recreate the issue consistently. When all that happened I was deep into some work and unable to get time for elisp debug. I'll keep a watch out for when this happens next. 

The last time this happened was when I was saving a file as another file using `C-x C-w`. The new file was non existent, and then I did `ivy-alt-done` when I finished typing the new path, and the whole path reset to `~/`.

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by julienfantin** [comment]
Fixed, thank you!

**Comment by wenjie2wang** [comment]
Fixed.  Thanks!
