### ISSUE TITLE
Using ivy-format-function-arrow with counsel-yank-pop?

### ISSUE THREAD

**Issue by therockmandolinist** [abo-abo/swiper#783]
Is there a way to use `ivy-format-function-arrow` with `counsel-yank-pop`? It would be nice if the arrow pointed to the first line in the current selection, for example.

If this is not possible, do you know a way to temporarily set the `ivy-current-match` face only for `counsel-yank-pop`? I like using an arrow and no face for `ivy-current-match`, but since the arrow doesn't format `counsel-yank-pop`,  I can't tell which yank is selected.

**Comment by abo-abo** [comment]
You can redefine what `counsel--yank-pop-format-function` does with `advice-add`:

```elisp
(advice-add
 'counsel--yank-pop-format-function
 :override
 (lambda (cand-pairs)
   (ivy--format-function-generic
    (lambda (str)
      (mapconcat
       (lambda (s)
         (ivy--add-face (concat "> " s) 'ivy-current-match))
       (split-string
        (counsel--yank-pop-truncate str) "\n" t)
       "\n"))
    (lambda (str)
      (counsel--yank-pop-truncate str))
    cand-pairs
    counsel-yank-pop-separator)))
```

**Comment by therockmandolinist** [comment]
That works nicely, and gives me something to work with should I want to modify it. As always, thank you for being so helpful.

**Comment by abo-abo** [comment]
You're welcome.
