### ISSUE TITLE
Duplicate entries in completion for `load-library`

### ISSUE THREAD

**Issue by rootzlevel** [abo-abo/swiper#79]
As the title says. Maybe duplicates should always be filtered

**Comment by abo-abo** [comment]
It can't be done easily.
On my system, it takes 1 whole second to remove the duplicates for this particular completion.
For others it could take much more.

```elisp
(setq cands (locate-file-completion-table
             load-path (get-load-suffixes) "" nil t))
(benchmark-run (cl-remove-duplicates foo :test 'equal))
;; =>
;; (0.950888108 0 0.0)
```

This issue needs to be fixed in the core Emacs.
See, for example, http://debbugs.gnu.org/cgi/bugreport.cgi?bug=20365.

**Comment by abo-abo** [comment]
Try `counsel-load-library` instead of `load-library`. It has a feature for resolving the duplicate libraries.  You also can type <kbd>C-.</kbd> to jump to library instead of loading it.
