### ISSUE TITLE
Question about counsel-M-x

### ISSUE THREAD

**Issue by eflanigan00** [abo-abo/swiper#791]
I've switched from helm-M-x
It shows the following:

    Emacs Commands History
    cmd_h1
    cmd_h2

    Emacs Commands
    cmd1
    cmd2

This makes it really easy to run previous commands. 
In counsel I can do M-p to get previous selections but the visual is really nice.
Is there a way to enable a similar behaviour?

Thank you for all your hard work, I love your packages!!

**Comment by ardpp** [comment]
you should use smex for that, see e.g. https://github.com/abo-abo/swiper/issues/629

**Comment by abo-abo** [comment]
Thanks @ardpp.

@eflanigan00 If you install `smex`, the `counsel-M-x` command will use it automatically to sort the commands by their frequency.

**Comment by eflanigan00** [comment]
Thank you, I added a bullet in the FAQ on the wiki. Feel free to modify it as you feel fit.

**Comment by abo-abo** [comment]
Looks good, thanks.
