### ISSUE TITLE
Thank you for ivy

### ISSUE THREAD

**Issue by vkz** [abo-abo/swiper#793]
Creating custom *commands* and *actions* is so simple with *ivy*. I just felt like saying **big thanks** to  the author. 

Dear @abo-abo thank you for taking the time and care to create *ivy*.

**Comment by abo-abo** [comment]
You're welcome. I enjoy it quite a bit myself too.

To anyone who enjoys Ivy: please consider contributing to the development of this package:

1. Improvements to [the wiki](https://github.com/abo-abo/swiper/wiki) are most welcome, and anyone can post their snippets and workflows there freely.
2. Improvements to [doc/ivy.org](https://github.com/abo-abo/swiper/blob/master/doc/ivy.org) are also very welcome, although you'll need an Emacs CA, just like for the code.
3. There are currently 59 open issues. Besides PRs to fix them, confirmations of reproduction and suggestion are welcome as well.
