### ISSUE TITLE
Question: How to ignore ".." in find-library? 

### ISSUE THREAD

**Issue by nixmaniack** [abo-abo/swiper#794]
Not exactly sure where to look at. I have already set `counsel-find-file-ignore-regexp` to hide hidden files and `ivy-extra-directories` to `nil` so that I shouldn't get `.` and `..` in the listing. But couldn't figure why `find-library` isn't working as expected. 

<img width="234" alt="screenshot 2016-11-25 05 49 38" src="https://cloud.githubusercontent.com/assets/542810/20611589/81019d8a-b2d3-11e6-9ff3-a20741fffc95.png">

**Comment by abo-abo** [comment]
You can use `counsel-load-library`.

**Comment by nixmaniack** [comment]
Would be nice to have `counsel-find-library` - I just want to visit the file to take a look and not necessarily load it. 

I think I can reuse your code to build `counsel-find-library` but better to see it in counsel or a simpler way to filter out `..` in `find-library` output.

**Comment by abo-abo** [comment]
You can find with `counsel-load-library`. Just press <kbd>C-.</kbd> instead of <kbd>RET</kbd>. Same approach as `counsel-M-x`.

**Comment by nixmaniack** [comment]
Nice! Didn't know about that. Thanks!
