### ISSUE TITLE
feature request: (defun swiper (&optional pattern)

### ISSUE THREAD

**Issue by zhaojiangbin** [abo-abo/swiper#8]
EDIT: The issue subject might be unclear. What I'd like to suggest is to add an optional argument to the ```swiper``` function as the default regexp.

The idea is that swiper can thus be integrated with isearch like ```helm-swoop-from-isearch```. Another integration, for example, can be with ```thing-at-point```.

Very nice package, by the way. I tried the ivy backend and like it.

**Comment by abo-abo** [comment]
Thanks, should be working now.
