### ISSUE TITLE
swiper-helm: Symbol's value as variable is void: ivy-re-builders-alist

### ISSUE THREAD

**Issue by jack99999** [abo-abo/swiper#80]
i started getting this error a few days ago whenever i try to run swiper-helm

fwiw, i update to the latest packages every day.

jack

**Comment by abo-abo** [comment]
Please check if you still have an old version of the stand-alone package "ivy" installed. If so, remove it: the new version that comes together with "swiper" package defines `ivy-re-builders-alist`.

**Comment by jack99999** [comment]
that's fixed it :)

many thanks for the instant diagnosis

jack
