### ISSUE TITLE
swiper search not working after update

### ISSUE THREAD

**Issue by AssailantLF** [abo-abo/swiper#805]
I haven't changed my (admittedly complex) Emacs configuration at all, besides updating all my packages, and now the plain swiper search function is giving an error.

The error is:

>Wrong type argument: window-live-p, #<frame emacs@DESKTOP-AWS5JA 0000000001C66C48>

Every other part of ivy/swiper is working correctly, just not the regular search. Any ideas or tips on tracking down what's causing this for me?

**Comment by abo-abo** [comment]
You need to recompile and reload `swiper.el`.

**Comment by AssailantLF** [comment]
That was it, thanks. I'll keep this in mind in case it happens in the future.
