### ISSUE TITLE
find-file : text is read only

### ISSUE THREAD

**Issue by CSRaghunandan** [abo-abo/swiper#806]
`counsel-find-file` has one major problem with new update. Here's how you can reproduce the bug:
* open `counsel-find-file`
* press `C-n` `C-p` or `up` `down` keys any number of times
* press `C-h` or `backspace` and ivy shouts: `Text is readonly`

**Comment by CSRaghunandan** [comment]
Upon further investigation, I found out `hungry-delete-mode` latest update broke `counsel-find-file`.

Otherwise, when `hungry-delete-mode` is disabled, `counsel-find-file` works fine. Hence closing issue

**Comment by CSRaghunandan** [comment]
I'm not sure what's wrong, but I'm getting this error again. 
Steps to reproduce:
* open a projectile project using `projectile-switch-to-project`
* execute `counsel-find-file` or `find-file` 
* press delete/backspace to go up a directory. `ivy` gets really mad at me and yells: `Text is readonly`

**Comment by CSRaghunandan** [comment]
My bad, this was due to a small bug in my config which caused smartparens to be enabled in `minibuffer-inactive-mode` which caused this bug. Sorry for wrongly reporting.

Closing this issue.

**Comment by jiacai2050** [comment]
I have this issue in emacs-plus with smartparens-global-strict-mode, disable this global mode solve this issue.
