### ISSUE TITLE
Spaces in filepath with ivy-occur

### ISSUE THREAD

**Issue by aagaard** [abo-abo/swiper#811]
It seems that a filepath with spaces cannot be searched with ivy-occur.

Setup:
emacs -Q
emacs-version -> GNU Emacs 25.1.1

Replication
Goto to file with spaces in filepath
(require 'ivy)
(counsel-grep-or-swiper)
Type some text
C-c C-o -> 4 candidates with every word in the filepath

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by aagaard** [comment]
Works! Thanks 👍
