### ISSUE TITLE
Feature idea: Merge bookmarks and find-file

### ISSUE THREAD

**Issue by justbur** [abo-abo/swiper#813]
I don't like to have too many bookmarks so I usually bookmark the directory of the relevant projects I'm working on. This means that I typically use `counsel-bookmark` then drop into dired and open a file from there. What would make sense to me and I think be a nice feature would be if in another command you could bring up a list of bookmarks but selecting a bookmark that represents a directory would immediately start a `find-file` session. So it's as if the bookmarks make up a virtual directory that are a starting point for `find-file`. Does that make sense and what do you think?

**Comment by manuel-uberti** [comment]
This sounds great to me.

**Comment by justbur** [comment]
A simple way to do this would just be to have `counsel-find-file` be the action that applies to directories, but I was thinking it would be interesting to be able to return to the list of bookmarks without exiting ivy as if it is really a directory of symlinks (or something like that).

**Comment by joedicastro** [comment]
I think that it would be best to have a separate command to do that, like `counsel-grep-or-swiper`, thus something like `counsel-find-file-or-bookmarks` and keep the original `counsel-find-file` to those that do not to prefer to have both things together. I think that's a good idea, BTW.
