### ISSUE TITLE
Two questions in order to contribute to the package

### ISSUE THREAD

**Issue by joedicastro** [abo-abo/swiper#814]
Hi @abo-abo, 

I'm developing at the moment some new commands and functionality for this package, which I have intend to contribute with a pull-request in an immediate future (I have already two new working counsel commands), but in order to do that properly I have some questions:

1. I see that you use in this package the popular function `mapconcat` to join strings like in this example: `(mapconcat #'identity counsel-org-tags ", ")` but since Emacs 24.4 there are several string manipulation functions in the library `subr-x` like `string-join` which let us to do something like `(string-join counsel-org-tags ",")` to do the same thing. Obviously this raises the question about the backward compatibility with older Emacs versions. So my questions are: What is your criteria about this?, How many Emacs versions do you intend to be compatible with? Is it O.K. to use that function instead of `mapconcat`? 

2. I know that I need the Emacs Copyright Assignment, but my doubt is if I have to wait until the Pull-request is done or if I can start the process now in order to speed things. 

Thanks for you time, regards.

**Comment by manuel-uberti** [comment]
I can answer your question number 2: it takes a variable amount of time to obtain you CA, so if you plan to contribute just start asking for it.

That's what I did.

**Comment by joedicastro** [comment]
Thanks @manuel-uberti. I'll start it right now!

**Comment by abo-abo** [comment]
> What is your criteria about this?, How many Emacs versions do you intend to be compatible with? Is it O.K. to use that function instead of mapconcat?

I aim for compatibility with `emacs-24.3` since that's what's is commonly installed through `apt-get`.  In any case, I still like `mapconcat` more, since it's flexible.

> I know that I need the Emacs Copyright Assignment, but my doubt is if I have to wait until the Pull-request is done or if I can start the process now in order to speed things.

I suggest to start it as soon as you can, since it can take a while. This November, there was a blog post from FSF that scanned PDF are also acceptable (instead of snail mail). Ask the FSF clerk about that, maybe it will be faster than the usual average of one month.

**Comment by joedicastro** [comment]
Thanks @abo-abo I'll use `mapconcat` then, not problem at atll. 👍 
Thanks also for the suggestion of the use of PDF for the FSF process, I prefer that way also.

One more question. I have already two new counsel commands and I have the intention of develop some more to full-fill my needs and add some interesting ones (as I see it). The two ones that I had now have a common nexus and it have sense to add them in a unique PR, the other would not. What do you prefer, that I have all the commands develop and make a single PR or to make separate PRs grouping related/similar commands? As you wish.

**Comment by abo-abo** [comment]
> separate PRs grouping related/similar commands

This is better, I think.

**Comment by joedicastro** [comment]
I think that too. Well, this weekend I would submit the first PR (I want to test it well before submit it), and I'll tell you when the FSF process is completed in order to merge it if you wish. Thanks! I close this now.

**Comment by basil-conto** [comment]
Note that `string-join` is equivalent to calling `mapconcat` with `#'identity` as its first argument. So the only benefit of using `string-join` is saving a few characters typed.

See #1629 for further discussion on the pros and cons of using `subr-x` definitions.
