### ISSUE TITLE
Tramp inconsistency with counsel-find-file

### ISSUE THREAD

**Issue by justbur** [abo-abo/swiper#817]
Steps: 
  1. `emacs -Q`
  2. `M-x package-initialize`
  3. `M-x counsel-mode`
  4. `C-x C-f / TAB =>` listing of root directory
  5. `M-: (require 'tramp)`
  6. `C-x C-f / TAB =>` listing of tramp protocols

I don't think the result here should depend on whether tramp is loaded, don't you?

**Comment by abo-abo** [comment]
The same thing happens with the default completion. I think it's intended.

**Comment by justbur** [comment]
ok, that's fine. I can just require tramp on startup. I still find it odd, because I doubt most people are explicitly loading tramp and therefore cannot be sure if it is loaded at a particular time.
