### ISSUE TITLE
How to use start-of-line regexp?

### ISSUE THREAD

**Issue by kaushalmodi** [abo-abo/swiper#82]
Hi,

Here is a test file

```
E 123
W 123
E 123
D E123
```

I wanted to match only the 1st and 3rd lines by using the expression `^E`. But that does not work.
If I use just `E` for search in swiper, it also returns the 4th line, which I don't want.

Can you add support for `^`?

Thanks.

**Comment by abo-abo** [comment]
It's not easy to do. The actual candidates passed to `ivy-read` are:

    ("1 E 123" "2 W 123" "3 E 123" "4 D E123")

If I don't append the line number to each candidate, it's possible to get two candidates that are `equal`.  And what to do then?  It's still doable using the `display` property for line numbers, and also comparing the matches not with `equal` but with `equal-and-text-properties-equal` (alternatively, keep another copy of each candidate, e.g. `("E 123" . "1 E 123")`).  But then I expect the performance to drop. I have to think about this.

**Comment by kaushalmodi** [comment]
If the user entered expression is `^E`, why not try to do an internal match with something like `[0-9]+ +E`? Here `[0-9]+` matches with the line numbers you appended.

**Comment by abo-abo** [comment]
Thanks for the suggestion, that approach is simple and should work well.
