### ISSUE TITLE
suggestion: an idea from helm

### ISSUE THREAD

**Issue by joedicastro** [abo-abo/swiper#83]
One thing that I like a lot from Helm is the function `helm-delete-minibuffer-contents` that is bound to `C-k` so that you can delete the complete string that you entered into the minibuffer with a single keystroke. It's very helpful sometimes.

[This][1] is how is implemented in Helm:
```emacs
(defun helm--delete-minibuffer-contents-from (from-str)
  ;; Giving an empty string value to FROM-STR delete all.
  (require 'helm-utils)
  (let ((input (minibuffer-contents)))
    (helm-reset-yank-point)
    (if (> (length input) 0)
        ;; minibuffer is not empty, delete contents from end
        ;; of FROM-STR and update.
        (helm-set-pattern from-str)
        ;; minibuffer is already empty, force update.
        (helm-force-update))))

(defun helm-delete-minibuffer-contents (&optional arg)
  "Delete minibuffer contents.
When `helm-delete-minibuffer-contents-from-point' is non--nil,
delete minibuffer contents from point instead of deleting all.
Giving a prefix arg reverse this behavior.
When at end of minibuffer delete all."
  (interactive "P")
  (let ((str (if helm-delete-minibuffer-contents-from-point
                 (if (or arg (eobp))
                     "" (helm-minibuffer-completion-contents))
                 (if (and arg (not (eobp)))
                     (helm-minibuffer-completion-contents) ""))))
    (helm--delete-minibuffer-contents-from str)))
```

What do you think about that? Do you like it for ivy?

[1]: https://github.com/emacs-helm/helm/blob/master/helm.el#l4227-l4251

**Comment by abo-abo** [comment]
> What do you think about that? Do you like it for ivy?

No. I want `ivy` to have an intuitive editing area. This means that <kbd>C-k</kbd> should call `kill-line`.  For example: `foo bar` <kbd>M-b</kbd> <kbd>C-k C-y C-y</kbd> will result in `foo barbar` input.

You can bind it in your config though. It's very simple:

```elisp
(define-key ivy-minibuffer-map (kbd "C-k") 'delete-minibuffer-contents)
```

What I do currently to delete minibuffer contents: <kbd>C-x h DEL</kbd>.

**Comment by joedicastro** [comment]
Oh, thanks! I missed that command, I made an `apropos-command` last night but I suppose I was too tired! :smile:

Of course, I understand your point of view. I am one of those irreverents that comes from Vim and do not care too much about the default Emacs bindings, my fault. But your approach is more reasonable and respectful with the most of Emacs users. :ok_hand:
