### ISSUE TITLE
ivy completion lists invisible in 20161215

### ISSUE THREAD

**Issue by franburstall** [abo-abo/swiper#832]
Just updated to 20161215 version from melpa and ivy's candidate lists are no longer visible!

I see the top line with the numbers of candidates, the mini-buffer grows as though to show the candidate list but no candidates are visible.  

This is emacs24.4 under linux.

**Comment by abo-abo** [comment]
Can you please check the current git master? I think it's fixed now.

**Comment by franburstall** [comment]
Yup---that fixes it!

Thanks for the swift response!

**Comment by abo-abo** [comment]
Thanks.
