### ISSUE TITLE
Manual should recommend installing counsel instead of swiper

### ISSUE THREAD

**Issue by nickmccurdy** [abo-abo/swiper#833]
The manual recommends that users install with `M-x package-install RET swiper RET`, which makes sense because ivy would also be installed. However, the recommended configuration in the manual also includes counsel commands. I thought that counsel was a dependency of one of these packages, so I was confused as to why I didn't have it. As a result, I think we should replace this with `M-x package-install RET counsel RET` in the docs, or at least recommend that in the counsel configuration section.

**Comment by abo-abo** [comment]
Thanks.

**Comment by nickmccurdy** [comment]
Thanks! I like the note about pull in the other packages as dependencies, I didn't realize it at first.
