### ISSUE TITLE
Support for virtual buffers

### ISSUE THREAD

**Issue by joedicastro** [abo-abo/swiper#84]
`Ido` has this idea of virtual buffers (using  the `ido-use-virtual-buffers` variable) via the `recentf` package, that you can see the recent buffers (*in other color*) that you opened in the past even when they are not already opened.
It's very handy for those files/buffers which you work frequently.

What do you think about that? Do you like it for `ivy`?

**Comment by abo-abo** [comment]
> What do you think about that? Do you like it for ivy?

I haven't used the feature for ido yet. Sounds cool though, I'll try to add it.

**Comment by jdahm** [comment]
This would be nice to have this as an option.

I tried it a while back and actually found it distracting. Instead I created `counsel-recentf` in my init.el and bound it to C-x C-r as usual. https://github.com/jdahm/dotfiles/blob/master/emacs/.emacs.d/init.el

**Comment by joedicastro** [comment]
> This would be nice to have this as an option.

Of course, that was always my initial intention, not as a default. :ok:

**Comment by abo-abo** [comment]
`ivy-mode` will use your `ido-use-virtual-buffers` setting.

**Comment by joedicastro** [comment]
> ivy-mode will use your ido-use-virtual-buffers setting.

It wouldn't be better to use an own variable?, some like `ivy-use-virtual-buffers`, after all, once the `smex` people accepted your pull-request, I probably would not use `ido` anymore :smile:

**Comment by abo-abo** [comment]
Fine, `defcustom` is more visible as well.

**Comment by joedicastro** [comment]
I tested it and it not seems to work:

with `ido-mode`:

![2015-05-08-195432_960x533_scrot](https://cloud.githubusercontent.com/assets/390964/7542324/112c79d8-f5bc-11e4-8138-2af45c15367d.png)

with `ivy-mode` (of course, `ivy-use-virtual-buffers` is set to `t`):

![2015-05-08-195545_960x533_scrot](https://cloud.githubusercontent.com/assets/390964/7542346/3d118e44-f5bc-11e4-912e-277765a288c9.png)

**Comment by abo-abo** [comment]
Are you sure you're calling `ivy-switch-buffer`? It may be a binding issue.

**Comment by joedicastro** [comment]
Oh my! I'm so stupid, I was using the hydra, and didn't updated the hydra head! My fault, sorry! :cry:
