### ISSUE TITLE
counsel-ag: how to sync the project directory with projectile

### ISSUE THREAD

**Issue by gitten** [abo-abo/swiper#840]
I have noticed that while working on my current project, counsel-ag does not always search the main project directory that projectile-ag does. I prefer the ivy interface and would like to figure out how to ensure counsel-ag is using the same project root directory as projectile. If you could point me in the right direction to understand how to customize this and point out what I am not understanding, that would be great!

**Comment by CSRaghunandan** [comment]
`counsel-ag` by default searches only the current directory where you run the command. To search the project root, you could do something like this:
```

(defun counsel-ag-project-at-point ()
    "use counsel ag to search for the word at point in the root project directory"
    (interactive)
    (counsel-ag (thing-at-point 'symbol) (projectile-project-root)))
```

**Comment by abo-abo** [comment]
See `counsel-projectile-ag` from `counsel-projectile`.

**Comment by gitten** [comment]
Great! Thanks @CSRaghunandan, some intersting stuff I can play with. @abo-abo, thanks for the great tools! Maybe one day you can do a blog post on how to start learning to build tools like Ivy, at least discussing where to start and most important things to keep in mind. Closing ticket, thanks guys!
