### ISSUE TITLE
counsel-ag returns error code 127 in macOS

### ISSUE THREAD

**Issue by yamafaktory** [abo-abo/swiper#844]
Hi and thanks a lot for the great work,

On macOS Sierra (10.12.2) with `ag` installed via *brew*, the `counsel-ag` command returns `error code 127` when triggered (> 3 characters). I also used the same Emacs settings on Archlinux and everything is fine.

I tried to play with what was mentioned in https://github.com/abo-abo/swiper/issues/672 without success.

```shell
ag --version
ag version 1.0.2

Features:
  +jit +lzma +zlib

emacs --version
GNU Emacs 25.1.1
```

Thanks!

**Comment by abo-abo** [comment]
> I tried to play with what was mentioned in #672 without success.

What do you eval and what is the output? Likely you just need to adjust the ag shell command, since it changes from version to version apparently.

**Comment by yamafaktory** [comment]
Thanks @abo-abo for the guidance, I finally figured it out. For the record, the `ag` command was not directly available in Emacs:

```shell
brew info ag
...
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d

zsh completion has been installed to:
  /usr/local/share/zsh/site-functions
```

My fix, for now, is to use the following:

```elisp
(if (eq system-type 'darwin)
    (setq-default counsel-ag-base-command "/usr/local/Cellar/the_silver_searcher/1.0.2/bin/ag --vimgrep --nocolor --nogroup %s"))
```
