### ISSUE TITLE
autoselect only candidate.

### ISSUE THREAD

**Issue by Dickby** [abo-abo/swiper#846]
Hi,
how about the option to autoselect the candidate if it's the only one?
This could be helpful in some custom counsel packages.
for example : https://github.com/syohex/emacs-counsel-gtags/issues/7

**Comment by abo-abo** [comment]
This differs from the behavior of the built-in `completing-read`. And often the user is allowed to enter text that does not match any of the candidates. What you suggest would prevent the user from having a chance to do that.

**Comment by Dickby** [comment]
It could be an option to toggle on or off.
What would be nessesary for counsel-gtags is that it autoselects the candidate only if there is just one from the beginning.

**Comment by Dickby** [comment]
If the initial-input just gives only one candidate it would open it directly.
This would be nice for counsel-dash too.

**Comment by abo-abo** [comment]
If `initial-input` gives 1 candidate, the user may still want to edit `initial-input` for it to match more things.

**Comment by Dickby** [comment]
Right, it wouldn't make sense in that case. But couldn't it be an optional thing?

**Comment by fabacino** [comment]
@abo-abo Would you consider a PR which addresses this issue? In the aforementioned `counsel-gtags` package the problem was "solved" by loading the all the candidates and bypassing `ivy` completely in case there is just one.

**Comment by abo-abo** [comment]
@fabacino A PR with a custom variable to decide whether to return immediately or not would be fine.

**Comment by abo-abo** [comment]
Fixed in #1039
