### ISSUE TITLE
keybinding conflicts with ergoemacs

### ISSUE THREAD

**Issue by QikeLi** [abo-abo/swiper#849]
I really like this package, but it caused many keybinding conflicts with ergoemacs (https://ergoemacs.github.io/). Would you please suggest a solution so that I can still use ergoemacs while harnessing the full power of swiper? Thank you!

**Comment by abo-abo** [comment]
I don't use ergoemacs. I suggest raising an issue with that package. A few key rebinds will solve the problem.
