### ISSUE TITLE
Can I complete with <enter>? 

### ISSUE THREAD

**Issue by tumashu** [abo-abo/swiper#85]
I want to complete directory with <enter>, when complete cadid is a file, open it.  How to config? thanks.

**Comment by abo-abo** [comment]
It's unclear what you're asking. Use `<kbd></kbd>` tags for keyboard shortcuts, or at least escape stuff with backquotes.

**Comment by tumashu** [comment]
oh, sorry. I want to complete directory with  "enter", but don't  open file. How to config?

**Comment by abo-abo** [comment]
I don't understand the difference between "complete" and "open". Can you give an example?

**Comment by tumashu** [comment]
The "complete" i said is just "show a directory or file path in minibuffer but don't open this file" , then i can type a key to open it.
