### ISSUE TITLE
Make counsel-rg prompt for extra args when using prefix arg.

### ISSUE THREAD

**Issue by dieggsy** [abo-abo/swiper#851]
Would be nice if `counsel-rg` did this (`counsel-ag` does since commit 4dd650c67452b4e61c27824372bbe5cc013723df, and as I understand it the code for the two is almost identical).

**Comment by abo-abo** [comment]
It would be nice to bring these functions into a single interface. There's quite a bit of code duplication there.

**Comment by therockmandolinist** [comment]
I agree. What do you think the best way to unify these is? A macro? A single function with an argument specifying which search utility to use? 

I could potentially give this a try.

**Comment by izahn** [comment]
I really miss this. Is there currently any way to pass extra arguments to `rg` when calling `counsel-rg` interactively?

**Comment by abo-abo** [comment]
@izahn What's your use case? I mean which setting you use for `counsel-rg-base-command`, and which flags do you want to add to it?

**Comment by izahn** [comment]
I often want to add a `-t` or `-g` flag to search only specific file types in the common case where searching everything is too slow. I use the default `counsel-rg-base-command` setting.

**Comment by abo-abo** [comment]
@izahn Thanks, but it's still not clear for me what `-t` or `-g` do. It seems `rg` has no man entry.

In any case, you should be able to add extra args now with a prefix arg.

**Comment by noctuid** [comment]
`rg` should have a manpage:

```
       -t, --type TYPE ...
              Only search files matching TYPE.  Multiple type flags may be provided.  Use the --type-list flag to list all available
              types.
...

**Comment by abo-abo** [comment]
@noctuid Thanks. I just tried <kbd>C-u C-c k RET</kbd> `-t org` <kbd>RET</kbd> `tes` in this repository. It works as expected.

**Comment by dieggsy** [comment]
Closing as https://github.com/abo-abo/swiper/commit/83d85ac4b8376c1c297791c485f4dd017f5cb505 solved this. Thanks

**Comment by d1egoaz** [comment]
FYI keep and eye on https://github.com/abo-abo/swiper/pull/1559
