### ISSUE TITLE
Searching projectile with ag, unable to jump to file locations (Windows 10)

### ISSUE THREAD

**Issue by Custodia** [abo-abo/swiper#852]
I'm on windows 10 (work computer) using spacemacs with pretty much the basic configurations.

When searching with `SPC` / or `SPC s a p` I do get the correct results in the minibuffer but it does not contain the filenames with the lines, which means that when I press enter I do not jump into the correct line of the correct file.

I have a friend with a very similar setup of emacs, the only differences we could find was a) he was still using helm b) he had manually configured the ag command with `(setq helm-ag-base-command "C:/ProgramData/chocolatey/bin/ag --vimgrep")`

The output format of ag seems to be the same for windows and linux so I don't think that is it. Does ivy have a similar setting for the ag base command?

**Comment by abo-abo** [comment]
See `counsel-ag-base-command`.

**Comment by Custodia** [comment]
Thanks for your quick response!

Where should this variable be overridden in? If I set it in `(defun dotspacemacs/user-config ())` it gets overridden with the version in counsel.el

**Comment by Custodia** [comment]
I was able to manually change the variable, however this did not fix my problem.

When I run `ag --nocolor --nogroup` outside of emacs the output format is correct.

Not entirely sure how I could debug this further since I can't reproduce the format that appears inside emacs.

**Comment by Custodia** [comment]
Doing `(defcustom counsel-ag-base-command "ag --nocolor --nogroup -- \"%s\"")` fixed this issue for me on windows, there are other places ag is still broken though, I'll see if I can find other uses.

**Comment by Custodia** [comment]
Sorry, I was mistaken, it did not fix my issue.

**Comment by joncol** [comment]
Has a solution been found for this? I also don't get any results when running counsel-ag on Windows. I'm also using the Chocolatey version of ag.

**Comment by joncol** [comment]
Changing `counsel-ag-base-command` works for me:

```elisp
(when (eq system-type 'windows-nt)
  (setq-default counsel-ag-base-command
                "ag --vimgrep --nocolor --nogroup %s"))
```
This is on Emacs 25.2 and Chocolatey's ag package.

**Comment by joncol** [comment]
OK. My bad, I had missed that `counsel-ag` wasn't running in the project's root directory. Installing the package `counsel-projectile` and using `counsel-projectile-ag` solved this.

**Comment by abo-abo** [comment]
@Custodia If the issue is solved for you as well, please close.

**Comment by joncol** [comment]
@abo-abo: Isn't it a good idea to use the above `counsel-ag-base-command` in the package source? Seems nice to have things work by default.

**Comment by abo-abo** [comment]
@joncol I agree. If you can verify that your proposed default value works correctly for all three popular OS.

**Comment by joncol** [comment]
@abo-abo: I was just thinking of changing the default on Windows. As far as I know the current default works well on Linux and Mac OS.

**Comment by angrybacon** [comment]
@joncol Not sure it's acceptable to have Windows-specific code on ELPA.

**Comment by abo-abo** [comment]
> Changing counsel-ag-base-command at least produces some results:

Looks like you just add `--vimgrep` to the default command; `--vimgrep` isn't essential and is not supported by older versions of `ag`.

**Comment by joncol** [comment]
@abo-abo: I just tried and it is indeed `--vimgrep` that makes it work on Windows. When removing that, I get no search results.

**Comment by joncol** [comment]
@abo-abo: Something I noticed is that without `--vimgrep`, the path separator of the found filenames is backslash, while with `--vimgrep` it is forward slash. Could this matter?

**Comment by eflanigan00** [comment]
I was able to get counsel-ag to work on windows with the following:

    (setq counsel-ag-base-command "c:/Users/my_name/path/ag.exe  --vimgrep --nocolor --nogroup %s")

**Comment by abo-abo** [comment]
@eflanigan00 Thanks.
@Custodia Does that work for you?

**Comment by Custodia** [comment]
It does 👍
