### ISSUE TITLE
Multi-cursor fails after setting counsel-M-x

### ISSUE THREAD

**Issue by lgatto** [abo-abo/swiper#856]
After setting 
```
(global-set-key (kbd "M-x") 'counsel-M-x)
```
in my `.emacs` file, when invoking `M-x mc/edit-beginnings-of-lines` (or `M-x mc/edit-ends-of-lines`), the content of the buffer I was editing is replaced with the name of the function that I wanted to invoked - for example

![2017-01-13-202742_518x443_scrot](https://cloud.githubusercontent.com/assets/384198/21944565/c8f5eaca-d9ce-11e6-87c5-cb0569a20a06.png)

I can reproduce the error using GNU Emacs 25.1.1 (x86_64-unknown-linux-gnu, GTK+ Version 2.24.23) of 2016-10-14, `ivy` 20170109.626, `counsel` 20170104.737 and `swiper` 20161213.719, all from melpa, as follows:

```el
(add-to-list 'load-path "/path/to/.emacs.d/elisp/")
(require 'install)
(require 'package)
(package-initialize)

(require 'multiple-cursors)
(ivy-mode 1)
(setq ivy-use-virtual-buffers t)
(global-set-key "\C-s" 'swiper)
(global-set-key (kbd "C-x C-f") 'counsel-find-file)

(global-set-key (kbd "M-x") 'counsel-M-x)
```
Starting `emacs -q`,multi-cursor` will work when evaluating all but the last line above. After evaluating the last line, the error described above appears.

Please let me know if there is any other information I need to provide.

**Comment by abo-abo** [comment]
Open your `~/.emacs.d/.mc-lists.el` file and make sure commands like `ivy-done` are on the `mc/cmds-to-run-once` list and not on `mc/cmds-to-run-for-all` list. Reload that file as well.

**Comment by lgatto** [comment]
Thank you very much for your help. Will close the issue, as it is solved. 

Just out of curiosity/education, how would I have been able to find the solution myself (sorry if it's obvious and I missed it).

**Comment by abo-abo** [comment]
> Just out of curiosity/education, how would I have been able to find the solution myself (sorry if it's obvious and I missed it).

The way `multiple-cursors` works, is that it asks you "Do you want to do the command once or for all cursors? [y/n]" each time it encounters a new command.  It happens to me sometimes that I give the wrong answer, and there's no way to undo it without a google search that reveals that the settings are stored to `.mc-lists.el`.

I think a lot of users encounter this problem and know how to solve it from experience.

**Comment by basil-conto** [comment]
> Will close the issue, as it is solved.

Can this issue be closed, then?

**Comment by abo-abo** [comment]
I think so, thanks.
