### ISSUE TITLE
counsel-rg returning same result twice

### ISSUE THREAD

**Issue by 1-9** [abo-abo/swiper#861]
From the recent update, I see counsel-rg returning the results twice.
One Result with full path one with the filename.

**Comment by abo-abo** [comment]
Can you pinpoint the commit for which this changed?

**Comment by 1-9** [comment]
Reverting this change fixed the issue.

https://github.com/abo-abo/swiper/commit/c2b0d30515a2fe2741c850b5bb699cf56b69b9d0

**Comment by manuel-uberti** [comment]
@abo-abo can it be reverted as @1-9 suggests?

**Comment by abo-abo** [comment]
Reverted, let me know if this fixes the issue.

**Comment by manuel-uberti** [comment]
Issue's gone. Thank you.
