### ISSUE TITLE
[BUG] not compatible with org-capture-templates %^g

### ISSUE THREAD

**Issue by stardiviner** [abo-abo/swiper#862]
I have a org-capture template:
```elisp
(setq org-capture-templates
      (append '(("w" "org-drill [w]ords"
                 entry (file my-org-drill-words-file)
                 "* %^{word} %^g
:PROPERTIES:
:DRILL_CARD_TYPE: %^{Difficulty|simple|twosided|multisided|hide1cloze}
:END:"
                 :empty-lines 1
                 ))
              org-capture-templates))
```

When in position `%^g`. Org-mode will prompt for a tag. I use `ivy` to select tag `drill`.
But got the following error. When I use elisp code `(org-drill nil "w")` also have this error:

```
Debugger entered--Lisp error: (error "Capture abort: (wrong-type-argument listp t)")
  signal(error ("Capture abort: (wrong-type-argument listp t)"))
  error("Capture abort: %s" (wrong-type-argument listp t))
  ad-Advice-org-capture
  apply(ad-Advice-org-capture
  org-capture(nil "w")
```

When I disable `ivy-mode`, Emacs default complete function works good. Also `helm-mode` works good too.

System Info 💻

- OS: gnu/linux
- Emacs
    - Emacs: 26.0.50.12
    - Graphic display: t

**Comment by abo-abo** [comment]
Can't reproduce, works fine for me. It seems to be connected you some advice in your config that you have around `org-capture`.

**Comment by stardiviner** [comment]
You're right, After I remove adivce on `org-capture`, problem is solved.
