### ISSUE TITLE
counsel-find-file-extern

### ISSUE THREAD

**Issue by dzklaim** [abo-abo/swiper#863]
hi. thank you for your work :) I would like to know if it is possible to execute the external app asynchronously when using the command counsel-find-file-extern.

**Comment by abo-abo** [comment]
Yes, that's how it works right now, as long as your app is associated to the file type on your system.

**Comment by dzklaim** [comment]
It does not work for me. emacs hangs until I close the application. If I use openwith I have no problems. the applications are correctly associated with the file types on ~/.config/mimeapps.list. I'm using emacs 25.1 +  nixos.

**Comment by Mengesh** [comment]
You can redefine `counsel-locate-action-extern` function to run `xdg-open` in background by adding ampersound `&` at the end.

```
      (defun counsel-locate-action-extern (x)
        "Use xdg-open shell command, or corresponding system command, on X."
        (interactive (list (read-file-name "File: ")))
        (if (and (eq system-type 'windows-nt)
                 (fboundp 'w32-shell-execute))
            (w32-shell-execute "open" x)
          (call-process shell-file-name nil
                        nil nil
                        shell-command-switch
                        (format "%s %s"
                                (cl-case system-type
                                  (darwin "open")
                                  (t "xdg-open"))
                                (concat (shell-quote-argument x) " &")))))
```

**Comment by basil-conto** [comment]
I think this was fixed in #1401.

**Comment by abo-abo** [comment]
@dzklaim @Mengesh Could you please test and confirm that this was fixed?

**Comment by Mengesh** [comment]
Fixed! Thanks

**Comment by abo-abo** [comment]
OK, closing the issue.
