### ISSUE TITLE
counsel-rg shows extra absolute path results

### ISSUE THREAD

**Issue by oss4390116** [abo-abo/swiper#864]
I've noticed with the latest changes the counsel-rg command now shows absolute path results which duplicate the relative path results.  Before only the relative path results were shown.  In the simple example below, I would only expect to see the second result.

<img width="738" alt="counsel-rg" src="https://cloud.githubusercontent.com/assets/4198897/22346593/7ba0f8c4-e3b9-11e6-8af9-ac1f82ef60a0.png">

**Comment by abo-abo** [comment]
I could reproduce it once, but after reloading the bug is gone. Can you try to recompile/reload/restart?

**Comment by oss4390116** [comment]
Ah, looks like the commit yesterday (https://github.com/abo-abo/swiper/commit/2f70c568b441277d5df565e585befe627f00b051) fixed the problem.  Thanks!
