### ISSUE TITLE
find-library offers many ../ options when ivy-mode is active

### ISSUE THREAD

**Issue by Wilfred** [abo-abo/swiper#873]
When ivy-mode is enabled, `M-x find-library` offers lots of `../` options (286 in my current Emacs instance):

![screen shot 2017-02-03 at 16 32 32](https://cloud.githubusercontent.com/assets/70800/22599363/97ff11b0-ea2e-11e6-8dfc-22748c3c94b0.png)

However, when ivy-mode is disabled, `M-x find-library` only offers one `../` option:

![screen shot 2017-02-03 at 16 33 15](https://cloud.githubusercontent.com/assets/70800/22599383/aaae25d0-ea2e-11e6-82ca-d4f69124ceec.png)

Selecting a `../` option simply gives the error `find-library-name: Can't find library ../` so perhaps ivy-mode should simply filter this out?

**Comment by abo-abo** [comment]
See `counsel-load-library` for a function that does this in a proper way. To find instead of loading press <kbd>C-.</kbd>.

**Comment by Wilfred** [comment]
Thanks, that's very useful. I can't see the `C-.` find option when pressing `M-o` in `counsel-load-library` -- is that expected?

**Comment by abo-abo** [comment]
> Thanks, that's very useful. I can't see the C-. find option when pressing M-o in counsel-load-library -- is that expected?

No, I forgot to add it :). Could you fix?

**Comment by Wilfred** [comment]
Turns out there's `counsel-find-library` too!

**Comment by abo-abo** [comment]
Oh. I forgot there was a PR for that some time ago:).
