### ISSUE TITLE
counsel-find-symbol just throws exit

### ISSUE THREAD

**Issue by Wilfred** [abo-abo/swiper#874]
Calling `M-x counsel-find-symbol` just gives me:

```
exit-minibuffer: No catch for tag: exit, nil
```

am I using the command incorrectly?

**Comment by abo-abo** [comment]
Here's how it works:

```elisp
(defvar counsel-describe-map
  (let ((map (make-sparse-keymap)))
    (define-key map (kbd "C-.") #'counsel-find-symbol)
    (define-key map (kbd "C-,") #'counsel--info-lookup-symbol)
    map))
```

You are not meant to use it from top-level, only from `counsel-describe-map`. Functions that use that map:

- counsel-describe-variable
- counsel-describe-function
- counsel-M-x
- counsel-load-library
- counsel-find-library

**Comment by abo-abo** [comment]
The question is answered, closing.

Would be cool if we could blacklist some commands from showing up in `execute-extended-command`. Would make sense for `counsel-find-symbol`.
