### ISSUE TITLE
swiper-all ignores case unconditionally

### ISSUE THREAD

**Issue by Wilfred** [abo-abo/swiper#880]
Given a file that contains the following:

```
foobarqux = 1
foobarQux = 2
```

`M-x swiper` uses smart case, so `rqux` matches both lines, but `rQux` only matches the second line.

However, `M-x swiper-all` is always case insensitive (note I have `case-fold-search set to `t`). As a result, `rQux` matches both lines in this file.

Ideally `swiper-all` would use the same smart-case logic.

**Comment by abo-abo** [comment]
Thanks, fixed.
