### ISSUE TITLE
How does projectile actions work?

### ISSUE THREAD

**Issue by noorul** [abo-abo/swiper#882]
I am planning to switch to ivy for projectile. But I think ivy does not support taking specific action from selection window. Like C-c p p M-g in helm world. Or am I need to do something extra?

**Comment by manuel-uberti** [comment]
You could have a look at [counsel-projectile](https://github.com/ericdanan/counsel-projectile).

**Comment by noorul** [comment]
I thought this is something that might be part of ivy.

After reading this http://oremacs.com/2015/07/23/ivy-multiaction/ it looks like author wants the user to have custom actions.

**Comment by abo-abo** [comment]
@noorul You can use `counsel-projectile`, it's got many cool actions and a lot of pre-configured stuff.

But you can also add actions yourself if you want:

```elisp
(ivy-set-actions
 'projectile-completing-read
 '(("e" (lambda (x) (interactive) (message "x is %S" x))
    "echo")))
```

The only info here that's specific to projectile is the use of `projectile-completing-read` key, which is defined in `projectile-completing-read` in projectile.el.
To call the above action: <kbd>C-c p p M-o e</kbd>.

**Comment by abo-abo** [comment]
The question is answered, closing.
