### ISSUE TITLE
Suggestion: edit a directory name within a file path

### ISSUE THREAD

**Issue by jsyjr** [abo-abo/swiper#883]
When I use ediff-files I often am comparing two files at identical locations in two parallel workspaces.  After I navigate to file A ediff prompts me with file A's directory.  At that point I really want to change just the workspace name to specify file B.  Before ivy completion I was able to do that.

A possible ivy implementation might be to have backspace and C-backspace have slightly different bahaviors.  Backspace would behave as today, removing and discarding path components.  C-backspace would likewise remove path components but would not discard them.  Rather each successive C-backspace would push the removed component onto a restore list.  (The contents of this list might remain displayed in the minibuffer in a dimmed face.)  Once a directory name had been entered the terminating slash would add back the pending restore list.

**Comment by basil-conto** [comment]
This also relates to the following issues: #1333, #1424, #1590.

**Comment by basil-conto** [comment]
In #2434 it was suggested to use <kbd>C-M-y</kbd> (`ivy-insert-current-full`) to work around this limitation.

**Comment by abo-abo** [comment]
Thanks, I've documented in the manual that `ivy-insert-current-full` is the way to go in case the user wants to edit the full path.

**Comment by basil-conto** [comment]
@abo-abo Does that also address the other related issues #1424 and #1590?

**Comment by abo-abo** [comment]
@basil-conto Yes, thanks. I've closed them as well.
