### ISSUE TITLE
dash as TAB in counsel-describe-variable/function?

### ISSUE THREAD

**Issue by unhammer** [abo-abo/swiper#886]
Would it be possible to have the "-" do a TAB if there no direct hits in `counsel-describe-variable` and friends? E.g. if I type `swi-` and there are no matches starting with the exact string `swi-` , it'll simply do a TAB and turn into `swiper-`. 

The regular `describe-variable` does something almost like this, where if you type `swi-`, you can tab-complete on things matching `swi.*-` (having to do one extra TAB would also be preferable to having it say **match required** and give no hits, as it currently does).

**Comment by abo-abo** [comment]
Try this code:

```elisp
(defun counsel-describe-dash ()
  (interactive)
  (let ((old-len (length ivy-text)))
    (ivy-partial)
    (when (eq old-len (length (ivy--input)))
      (insert " -"))))

(define-key counsel-describe-map "-" 'counsel-describe-dash)
```

**Comment by unhammer** [comment]
Oh that works great :-) I guess this can be closed then …
