### ISSUE TITLE
Please explain the need for with-ivy-window in counsel-find-file

### ISSUE THREAD

**Issue by pasja** [abo-abo/swiper#889]
Hello abo-abo,

I simply do not understand, what does the purpose of the `with-ivy-window` macro within `counsel-find-file`?

It behaves really strange in my pc, please see the attached screenshot.

Basically it is an `emacs -Q` and i load only swiper at commit `d23d1fe`
Within the interactive `counsel-find-file` call i browse and commit the `/tmp/a` directory with several hits of  `TAB`.
Then it opens the target buffer in a new emacs window, and the cursor stays in the minibuffer.
If i remove that macro from the function, it works as plain `find file`

Output of `M-x emacs-version`
```
GNU Emacs 24.5.1 (x86_64-pc-linux-gnu, GTK+ Version 3.18.9) of 2016-04-17 on lgw01-04, modified by Debian
```

Thanks for your dedicated work on ivy!

![ivy-strangeness](https://cloud.githubusercontent.com/assets/472806/22932633/e75d47e8-f2c8-11e6-87cf-0d4d2715984f.png)

**Comment by abo-abo** [comment]
In the past versions, the action was called in the context of the minibuffer window.  So `with-ivy-window` macro was used to execute code in the context of the window in which `ivy-read` was originated.

But since a while, the action is called in the context of the original window, so `with-ivy-window` is a no-op.

I can't reproduce your scenario on ether my current version or `24.5.2`. Do you get the same problem using arrows and <kbd>C-m</kbd> / <kbd>C-j</kbd>?

**Comment by pasja** [comment]
Hello,

Just managed to test it.
I've got the same results with arrows and <kbd>C-m</kbd>/<kbd>C-j</kbd>

If it is a no-op anyways, could you accept a PR where the macro and it's usage get removed?

**Comment by abo-abo** [comment]
It's a no-op only in action functions. It's useful in ivy's internal functions.

Can you explain in more detail what's wrong? I didn't understand your earlier message.

**Comment by pasja** [comment]
Hello,

I hope that the following gif explains it better than my writing.
Please see it here: https://gfycat.com/PessimisticFalseBetafish

Anyway, I have created PR #911 to remove that no-op-call, please check it.

Thanks!

**Comment by abo-abo** [comment]
I still can't reproduce with this sequence:

    emacs=emacs-24.5 make plain

<kbd>C-x C-f //tmp TAB TAB</kbd> re-uses the single window when opening `dired`, it doesn't do a split like your gif.

**Comment by pasja** [comment]
Hello,

My last idea is that you are trying to reproduce this issue with a pristine emacs, compiled from upstream source, while i use the ubuntu provided one.

I will try to compile an emacs from the upstream source, and try to reproduce it by myself.

**Comment by pasja** [comment]
Hello, 

As with `GNU Emacs 25.1.1 (x86_64-pc-linux-gnu, GTK+ Version 3.22.12) of 2017-04-23, modified by Debian` and ivy commit `30e8b83` I am not able to reproduce it again, I close this issue and the referred PR.

I guess the problem lies within that specific emacs version, which I do not use anymore as the jessie -> strech transition is over in my systems.

**Comment by abo-abo** [comment]
Thanks for the info.
