### ISSUE TITLE
Swiper from isearch

### ISSUE THREAD

**Issue by kaushalmodi** [abo-abo/swiper#89]
Hi,

I'd like to share this snippet borrowed from `helm-swoop` which I find very useful.

Sometimes I am searching for something using the regular `isearch` and I change my mind and want to use `swiper` for that instead.

This snippet helps.. I bind it to `M-i` in `isearch-mode-map`:

```el
    (defun swiper--from-isearch ()
      "Invoke `swiper' from isearch.

https://github.com/ShingoFukuyama/helm-swoop/blob/f67fa8a4fe3b968b7105f8264a96da61c948a6fd/helm-swoop.el#L657-668
"
      (interactive)
      (let (($query (if isearch-regexp
                        isearch-string
                      (regexp-quote isearch-string))))
        (isearch-exit)
        (swiper $query)))
```

**Comment by abo-abo** [comment]
Great, shame I no longer use `isearch`:).

Could you create a new page on the [wiki](https://github.com/abo-abo/swiper/wiki) with your code?

**Comment by joedicastro** [comment]
Actually, what could be an excellent idea would be to made an `isearch-forward` (in my case it would be better an `evil-search-forward`) after match the *swiper query* to be able to navigate between the candidates without need to call `swiper` againl.

@abo-abo is there any variable where that match keeps stored? then I think that I could make that happen in my config.

**Comment by abo-abo** [comment]
@joedicastro see `ivy-text` and `ivy--current`.

**Comment by joedicastro** [comment]
Well, as I told, I made my function to achieve that as following:

```emacs
(defun joe-swiper ()
       (interactive)
       (swiper)
       (add-to-list 'regexp-search-ring ivy-text))
```

Works fine, you make a `swiper` and after that you can move through the `isearch` results without the need to do a `swiper` again. So, yoi get the best of both worlds, you can use `swiper` as regularly and as a substitute of `isearch`. To me is precious, because move between the results in *evil* is as simple as use <kbd>n</kbd> and <kbd>N</kbd>

**Comment by abo-abo** [comment]
If there are spaces in `ivy-text`, you should use `(ivy--regex ivy-text)` instead to build a proper regex.

**Comment by joedicastro** [comment]
Oh, thanks! I made the change. :smile:

**Comment by lionel-** [comment]
@abo-abo Any chance of integrating @joedicastro change? This is really useful for Evil users.

**Comment by lionel-** [comment]
to Evil users:

I also find the following makes Swiper much more natural to use:

```lisp
  (defun my-swiper-update-search-ring (&rest args)
    (add-to-list 'regexp-search-ring (ivy--regex ivy-text)))

  (advice-add 'ivy-next-line :after #'my-swiper-update-search-ring)
  (advice-add 'ivy-previous-line :after #'my-swiper-update-search-ring)
```

This updates the search ring when you hit C-n or C-p. For some reason I often C-g from a search to get back to where I was, and then after a while I use Evil search motions to quickly cycle through the matches of the previous search. Without these advices it doesn't work.

**Comment by abo-abo** [comment]
@lionel- If you press <kbd>C-g</kbd>, `swiper--cleanup` will be called anyway. Might want to advise that instead, to modify the regex ring a bit less.

Also, cycling matches after a search - `ivy-occur` can do that too. I recently added `wgrep` functionality to that as well, if you want to edit the matches.

**Comment by lionel-** [comment]
Hmm I'd rather not update the ring when I just cancel a search without moving through it.

By the way, this is not `(add-to-list)` that should be used in all these commands, but `(add-to-history)`. The former doesn't push old elements in front of the ring so it won't work with repeated searches. The latter pushes in front and makes sure the ring size doesn't increase indefinitely. It also checks for duplicates at the front of the list.

In addition C-n and C-p should update the direction of the search, so here are updated advices for this use case:

```lisp
  (defun my-swiper-update-search-ring-forward (&rest args)
    (add-to-history 'regexp-search-ring (ivy--regex ivy-text))
    (setq isearch-forward t))

  (defun my-swiper-update-search-ring-backward (&rest args)
    (add-to-history 'regexp-search-ring (ivy--regex ivy-text))
    (setq isearch-forward nil))

  (advice-add 'ivy-next-line :after #'my-swiper-update-search-ring-forward)
  (advice-add 'ivy-previous-line :after #'my-swiper-update-search-ring-backward)
```
