### ISSUE TITLE
Feature request: multiple inputs for org-set-tags

### ISSUE THREAD

**Issue by Wilfred** [abo-abo/swiper#890]
When using ivy-mode with auto-insert, I can insert multiple keywords and terminate with ivy-alt-done.

I'd like to do something similar with org-set-tags. Currently I can only input a single tag `:foo:` or I can manually type `:foo:bar:`. I'd like to be able to type `:foo:` and the closing `:` trigger completion again.

* Is this doable?
* Would this need to be a separate command `counsel-org-set-tags` or could this automatically hook in to org?
* Is there precedent for selecting (and removing) multiple values from a list in ivy or counsel? (I.e. can I shamelessly copy from an existing command?)

**Comment by abo-abo** [comment]
> Is this doable?

Yes.

> Would this need to be a separate command counsel-org-set-tags or could this automatically hook in to org?

Can't be done automatically.

> Is there precedent for selecting (and removing) multiple values from a list in ivy or counsel? (I.e. can I shamelessly copy from an existing command?)

See `counsel-org-tag`. How it works: just press <kbd>C-M-m</kbd> (`ivy-call`) or <kbd>C-M-n</kbd> (`ivy-next-line-and-call`) to toggle each tag. Exit with either <kbd>C-m</kbd> or <kbd>C-j</kbd> or <kbd>C-M-j</kbd>.  The accumulated tag state is displayed in the prompt.

**Comment by Wilfred** [comment]
Fantastic, I didn't spot that. I did look at whether there was a counsel command, but stupidly I looked for something containing 'set-tag`. Thanks.
