### ISSUE TITLE
Allow ido or none for specific use Cases: (helm-completing-read-handlers-alist)

### ISSUE THREAD

**Issue by jmercouris** [abo-abo/swiper#892]
In helm, the following is very useful:
helm-completing-read-handlers-alist

the reason for this is that ivy breaks compatibility with some packages, consider my earlier bug report: https://github.com/jorgenschaefer/elpy/issues/1084

according to the author of Elpy, Elpy supports the standard interface for completion, which breaks when used in conjunction with Ivy

**Comment by jmercouris** [comment]
so, as is clear from the elpy thread, I think this feature is kind of necessary...

**Comment by drym3r** [comment]
I quoute forcer from #emacs: 

> ivy.el already has a facility to disable the mode for certain commands. Sadly that list is hardcoded and not extensible. You could edit ivy.el line 1749, to add elpy-doc there.

Maybe just making this editable would solve the problem.

**Comment by abo-abo** [comment]
Thanks, I added the defcustom. But it's a hotfix rather than a solution. The purpose of a completion engine is to work, instead of not to work, and it should be trivial to make elpy completion work with ivy.

Check out https://github.com/abo-abo/lpy. It provides great inline completion for Python, among other things.

**Comment by jmercouris** [comment]
Thank you for the fix! Ivy has been a life changer for me!!
I would agree that it is a hotfix, but unfortunately things are rarely ideal :(

I may take a look at lpy, but I’m very satisfied with elpy so far. Once again, thanks!

**Comment by drym3r** [comment]
Thanks!
