### ISSUE TITLE
counsel-grep-or-swiper is saving buffer before allowing a search causing annoying delays

### ISSUE THREAD

**Issue by moesasji** [abo-abo/swiper#894]
When using counsel-grep-or-swiper on a large file the buffer gets written to disk before the search window opens. For the file (6500 lines) that I'm currently working on that causes a delay of ~4 seconds to get a search window after each file change. In my case this is made worse as the save operation also triggers a babel-tangle of the file, but even without the tangle operation it is unbearable slow.

I'm not sure why this is being done as overwriting files without asking when searching for something in a buffer is not expected behavior, which has bitten me a couple of times already.

Hence the question: is it possible to remove the (save-buffer) in the counsel-grep-or-swiper function, see below?
```
      (progn
        (save-buffer)
        (counsel-grep))
    (swiper--ivy (swiper--candidates))))
```

**Comment by abo-abo** [comment]
Not possible. `counsel-grep` is simply a wrapper around shell's `grep`. If the file is not saved, `grep` will instead operate on the old version of the file.

What's weird here is the 4 second delay. I never have that, even for larger files. Does it take 4 seconds only to `save-buffer`?

**Comment by moesasji** [comment]
It takes about 4 seconds for a manual save of this buffer combined with tangling the code fragments that are in the file into a separate file. In other words the delay of 4 seconds that I'm seeing is for saving two big files as well as the org-babel-tangle operation itself. The org-babel-tangle operation is what causes most of the delay, not the save itself. Without the tangle the delay is just a fraction of a second and acceptable.

Although this use-case doesn't work nicely with counsel-grep-or-swiper I clearly just need to rethink how I do the tangle operation. Feel free to close.

**Comment by abo-abo** [comment]
OK. Have a look at `swiper-all`. Since it operates on buffers instead of files, there's no need to save.
