### ISSUE TITLE
feature request: save mark where swiper starts

### ISSUE THREAD

**Issue by zhaojiangbin** [abo-abo/swiper#9]
Like how isearch does it.

Also as of the MELPA version 20150313.1425, if <kbd>C-g</kbd> is pressed during swiping, or if <kbd>RET</kbd> is pressed with a pattern not found, the point stays at where swiper exits. It would be nicer if the point can be restored to where swiper started, in these cases.

**Comment by abo-abo** [comment]
Should be fixed now, thanks.
