### ISSUE TITLE
ivy--transform-re: void-variable swiper-map

### ISSUE THREAD

**Issue by rootzlevel** [abo-abo/swiper#90]
in `emacs -Q`:

```
(add-to-list 'load-path ".../swiper")
(require 'ivy)
(ivy-mode)
(call-interactively 'find-file)
```

results in the above error.

**Comment by abo-abo** [comment]
Thanks.

**Comment by rootzlevel** [comment]
Unfortunately, the emacs -Q recipe in my original comment still produces the same error. I would reopen the issue, but github doesn't let me

**Comment by abo-abo** [comment]
Fine, I'll have to look at it later. You can `(require 'swiper)` as a work-around.

**Comment by abo-abo** [comment]
Should be better now. Thanks again.
