### ISSUE TITLE
`ivy-push-view` should remember windows split size

### ISSUE THREAD

**Issue by freesteph** [abo-abo/swiper#903]
As mentioned in the [introductory blog post](http://oremacs.com/2016/06/27/ivy-push-view/), `ivy-push-view`/`ivy-pop-view` don't remember the size of the different windows that make up the view. It would be nice if they did.

**Comment by clemera** [comment]
I wonder why ivy views do not use `current-window-configuration` and `set-window-configuration` to store/restore the views?

**Comment by clemera** [comment]
Okay I figured it out:: `set-winodw-configuration` does not restore closed buffers. But I think storing window configurations along with the file information would work. I will add that to my config and PR later if there is interest.

**Comment by clemera** [comment]
Okay I figured it out: window-configurations don't restore closed buffers.

**Comment by clemera** [comment]
Here is a quick hack which saves the layout when storing with `ivy-push-view` and restores it when choosing it `ivy-switch-buffer`:

    (define-advice ivy-push-view (:around (fun &optional arg) restore-sizes)
      "Store the window conf."
      (let* ((res (apply fun arg))
             (name (if (stringp (caar res))
                       ;; new
                       (caar res)
                     ;; update
                     (car (rassoc res ivy-views)))))
        (put-text-property 0 1 'ivy-view-wc (current-window-configuration) name)))


    (define-advice ivy--switch-buffer-action (:around (fun &rest args) restore-sizes)
      "Restore window conf."
      (let* ((buffer (car args))
             (view (and (not (zerop (length buffer)))
                        (assoc buffer ivy-views)))
             (wc (and view (get-text-property 0 'ivy-view-wc (car view)))))
        (apply fun args)
        (when wc
          (set-window-configuration wc))))

**Comment by clemera** [comment]
If I would reimplement ivy-push-view I would probably use `window-persistent-parameters` to store the file path via a window parameter and then restore those after loading the window configuration. If there is interest I can make a PR.

**Comment by abo-abo** [comment]
@clemera Sounds good. Please PR.

**Comment by clemera** [comment]
Okay, how should I handle the changes to user option `ivy-views`? The new format would map ivy view names to window configurations. Maybe I should create another user option which allows to choose which format to use? What do you think is the best way to approach this?

**Comment by abo-abo** [comment]
I think we should parse every element of `ivy-views`. If it matches `(memq (car-safe x) '(horz vert))`, use the old logic. Those config options are meant to make it easy to be written down by hand, instead of created on the fly by `ivy-push-view`.

**Comment by clemera** [comment]
Thanks, that makes sense.  I will submit my PR on the weekend.
