### ISSUE TITLE
counsel-git-like functionality for a directory tree which is not in git repository

### ISSUE THREAD

**Issue by volodymyrprokopyuk** [abo-abo/swiper#906]
**Feature**: recursively search files by pattern in a directory tree which is not in git repopository

**As a** user of ivy/counsel mode
**When** I search files by pattern in a directory tree which is not in git repository
**Then** a list of all possible files that match the pattern in the whole directory tree is present
**And** I can select a file to open it in a buffer

I'm looking for a functionality that is already implemented by `counsel-git` function for a git repository. I would like to be able to recursively search files by pattern when a current directory where I started emacs is not part of git repository. When I'm in a regular directory which is not git repository `counsel-git` says "Not in git repository"

This functionality could be implemented using the following approaches:
1. `ag -g <pattern> <current directory>` ag command searches for file names instead of file content when `-g` option is provided
1. `find <current directory> -name *<pattern>*` find command searches for file names when `-name` option is provided

I think the `<current directory>` where I started emacs should be stored in a variable to be referenced when searching.

I'm new to ivy/counsel mode. I don't know if this functionality is already present in a ivy/counsel mode. Could someone, please, point me to the functionality if it is already implemented.

**Comment by manuel-uberti** [comment]
Does `counsel-ag` do what you're looking for? You can customize `counsel-ag-base-command` to set it to what you need.

**Comment by abo-abo** [comment]
See `find-file-in-project` or `projectile`.

**Comment by Mugu-Mugu** [comment]
I think what you want is already implemented in `counsel-file-jump`. There is also `counsel-dired-jump` for directories.
The starting directory is an optional parameter for both command.
Note that both are synchronous and can thus have a noticeable startup time for deep directory tree.

**Comment by abo-abo** [comment]
@Mugu-Mugu Thanks, I forgot about those. I should integrate them into my workflow at some point.

**Comment by volodymyrprokopyuk** [comment]
Thank you very much for all of your comments! `counsel-file-jump` is what I was looking for! @Mugu-Mugu thank you!
