### ISSUE TITLE
require-match and empty input

### ISSUE THREAD

**Issue by Bad-ptr** [abo-abo/swiper#909]
Testcase:
```elisp
(completing-read "Test: " () nil t)
```
With ivy enabled I can only abort with `C-g`, or `C-u C-j`. (more precisely I can not exit from minibuffer with `exit-minibuffer` and empty input)
With ivy disabled I can press `RET` and get `""` result.
The [emacs manual says](https://www.gnu.org/software/emacs/manual/html_node/elisp/Minibuffer-Completion.html):

> However, empty input is always permitted, regardless of the value of require-match; in that case, completing-read returns the first element of default, if it is a list; "", if default is nil; or default. 

Well I'm understand that this is a very rare case, but I'd like if ivy will be as much consistent with the standard `completing-read` as it is possible. 
I have a code where I bind a key to the `mb-local-map` which allows me to exit(it calls `exit-minibuffer`) and restart `completing-read` with a different collection. Initially it may be empty collection. This works with standard completing-read, but not with ivy.

**Comment by spluque** [comment]
I came across this post while looking for a way to tell ivy to complete the null string "" for filename completion in the minibuffer.  If I understand correctly from here, `ivy` does not allow for it?

**Comment by abo-abo** [comment]
> If I understand correctly from here, ivy does not allow for it?

This is allowed with <kbd>C-M-j</kbd> (`ivy-immdiate-done`), also bound to <kbd>C-u C-j</kbd>.
It allows to return *any* string, including the empty one, ignoring whether the string is in the collection or not.

**Comment by abo-abo** [comment]
@Bad-ptr I added a check for the null collection. Should be enough, I think. Thanks.

**Comment by spluque** [comment]
When using filename or directory completion, it seems impossible to even get to a null string; when I delete everything in the minibuffer, the null string is not in the candidates, so I see either the tramp methods or some directory

**Comment by abo-abo** [comment]
@spluque that's how it's supposed to work; you can still use <kbd>C-M-j</kbd>.

**Comment by spluque** [comment]
Sorry to insist @abo-abo , but when I do that (`C-M-j`) I don't get the null completion, but the current directory which is what is shown as soon as I request the filename or directory completion with e.g. `C-x C-f` which I've bound to `counsel-find-file`.  What am I missing? Thanks for this great library.

**Comment by abo-abo** [comment]
@spluque Please open a new issue describing specifically what you want to achieve in general (like create a file), not just the small detail of getting an empty string.
