### ISSUE TITLE
Completions List

### ISSUE THREAD

**Issue by joedicastro** [abo-abo/swiper#91]
With `ido` if you, for example, wanted to add a tag in **org-mode** you can press <kbd>TAB</kbd> to show you a *Completion List* and can select the candidates.

Is it possible to do this with `ivy`?

**Comment by abo-abo** [comment]
Which `org-mode-command` are you reffering to?

**Comment by joedicastro** [comment]
It is a command that do many things depending on context, `org-ctrl-c-ctrl-c`, but `ido` let you get that *Completion List* in various commands, e.g. `smex` and `switch-buffer`. I think that it does it with `ido-complete`

**Comment by abo-abo** [comment]
> It is a command that do many things depending on context, org-ctrl-c-ctrl-c, but ido let you get that Completion List in various commands, e.g. smex and switch-buffer. I think that it does it with ido-complete

OK, so the command is determined. Can you supply a minimal file and position for which `org-ctrl-c-ctrl-c` offers a completion list for `ido-mode`?

**Comment by joedicastro** [comment]
```
* one                                                            :test:other:
* two 
```

If you execute the command over `two` and press <kbd>TAB</kbd> them you get a list with *test* and *other*

**Comment by abo-abo** [comment]
OK, I see it now. It works fine for adding one tag, if there are none.  It also work fine if you want to unset all tags and set one.  I'll see tomorrow for the rest.

**Comment by abo-abo** [comment]
Closing this one, since the new command `counsel-org-tag` is a solution.
