### ISSUE TITLE
Emacs shell: counsel-company and TAB

### ISSUE THREAD

**Issue by manuel-uberti** [abo-abo/swiper#910]
This is what I am doing:

- <kbd>M-x</kbd> `shell`
- `cd De` <kbd>TAB</kbd>

I get `No completion found` in the echo area. However, if I do:

- <kbd>M-x</kbd> `shell`
- `cd De` <kbd>C-M-i</kbd>

I get this correctly in my shell prompt: `~ % cd Desktop/`

<kbd>TAB</kbd> is bound to `counsel-company` (to be more specific: `:bind ([remap completion-at-point] . counsel-company)`, while <kbd>C-M-i</kbd> is bound to `complete-symbol`.

Is it possible to make `counsel-company` pop up the available candidates in `shell-mode`?

<kbd>TAB</kbd> works as expected in `eshell`.

Thank you

**Comment by abo-abo** [comment]
I suggest to simply restore the default key binding:

    (define-key shell-mode-map "\t" 'completion-at-point)

**Comment by manuel-uberti** [comment]
Thanks, it works.
