### ISSUE TITLE
How to ignore first match completion ?

### ISSUE THREAD

**Issue by sam217pa** [abo-abo/swiper#912]
Hi, 

Say I'm in dired in the following directory.

```
.
├── analysis
└── data-raw
```

Now if I press `+` to insert a subdirectory that I want to call `data`:

```
.
├── analysis
├── data
└── data-raw
```

Ivy will try to complete with `data-raw` and I can't just add a new subdir when target is shorter than the first default completion. I hope I am clear enough here ?

I read the entire ivy help but did not find what I was looking for.

Thanks for your awesome work on the `ivyverse` ;)

**Comment by ardpp** [comment]
Check `ivy-immediate-done` which is bound to `C-M-j` during completion in the mini buffer. This should actually be in the manual.

**Comment by sam217pa** [comment]
Thanks ! I somehow managed to get pass this specific paragraph …

**Comment by abo-abo** [comment]
> Thanks for your awesome work on the ivyverse ;)

You're welcome.

@ardpp Thanks for helping out, I've been in meetings all day.
