### ISSUE TITLE
ivy-hydra.el missing from MELPA packages

### ISSUE THREAD

**Issue by cpbotha** [abo-abo/swiper#913]
I have latest ivy (20170307.1108) and swiper (20170225.356) installed from melpa.

When I try to eval `(hydra-ivy/body)` I see the following error: `eval: Cannot open load file: No such file or directory, ivy-hydra`

(this is what happens when I do `C-o` during a `counsel-grep-or-swiper`)

Indeed, I can't find `ivy-hydra.el` in my installed packages, although I do see it here on github.

Is this a bug in the packaging?

**Comment by abo-abo** [comment]
`ivy-hydra` is available as a seperate package on MELPA. This is because it's useful to have Ivy not depend on Hydra.

**Comment by cpbotha** [comment]
Aah thank you! I somehow missed this when looking through the available packages.
