### ISSUE TITLE
Recipient completion with Ivy in mu4e erases contents

### ISSUE THREAD

**Issue by thblt** [abo-abo/swiper#914]
(What follows is a copy of https://github.com/djcb/mu/issues/1029)

## Expected or desired behavior

In a mu4e compose buffer, completing e-mail recipient address with Ivy should replace the partial string with the full e-mail and optional name. 

## Actual behavior

A few characters at the left of the point get erased when completing.

Eg, the buffer looks like (point is at `|`):

```
From: Thibault <thblt@anna>
To: eds|
Subject: 
--text follows this line--
```

I hit tab to get completions, select `dif.eds@listes.univ-paris1.fr`, press RET, the buffer becomes:

``` 
From: Thibault <thblt@anna>
dif.eds@listes.univ-paris1.fr
Subject: 
--text follows this line--
```

(notice the To: gets dropped)

 - It seems that that *the number of characters deleted is equal to the number of characters to the left of the fragment used for completion*.  Eg, if I complete from "dif" instead of "eds", everything works well.   If I complete from "s@listes", the buffer becomes:

    ```
    From: Thibault <thblt@annadif.eds@listes.univ-paris1.fdif.eds@listes.univ-paris1.fr
    --text follows this line--
    ```

 - The bug occurs whether the Ivy completion buffer gets actually displayed or not (ie, if there's only one alternative, the problem still occurs)

 - This happens only with Ivy.  I haven't been able to reproduce the bug with neither company-mode nor Helm. 

## Steps to reproduce

From `emacs -q` (i use lowercase q to get mu4e in the load path in Debian), require ivy and mu4e.

 - Enter Compose mode
 - Put the point in the "To:" field
 - Start entering a part of a name or e-mail, but not the leftmost part (ie, for someone@example.com, not "some" or "someone".)
 - Accept a completion if the ivy buffer appears.

## Versions of mu, mu4e/emacs, operating system etc.

 - Up-to-date Debian Stretch
 - Packaged Emacs 25.1
 - Packaged mu4e 0.9.18-1

**Comment by abo-abo** [comment]
I can't reproduce it. Used:

- Emacs 25.1
- [current master of mu4e](https://github.com/djcb/mu/commit/22e11fc112dcfd01356cc5faf01f4d9d1a134b06).
- [current master of swiper](https://github.com/abo-abo/swiper/commit/f94c15c8cb40f7a9959a3ffcd2052bb3a118eb3f)
- `emacs -Q` to avoid interference from any packages

**Comment by thblt** [comment]
I just tried again, and the behaviour is in fact a bit strange.  From `emacs -Q` (25.2rc2) as well, running packaged mu4e from Debian Stretch and latest Ivy from Melpa Stable, whenever I activate ivy-mode and press tab in the To: field, I get a company-like popup completion list which, actually, behaves perfectly well.  If I turn off ivy-mode again, I get the standard Emacs completion ("Click on a completion to select it", etc.).  I don't know if this is a recent change in Ivy I'd have missed or if something's misbehaving.  I've used the following initialization code:

``` elisp
(setq package-user-dir (concat
			user-emacs-directory
			"/elpa"
			(number-to-string emacs-major-version)
			)
      ) ; This is a cheap hack to avoid Emacs 24 and 25 sharing 
        ; the same Elpa folder and complaining, shouldn't have any
        ; effect.

(package-initialize)

(add-to-list 'load-path "/usr/share/emacs/site-lisp/mu4e")

(require 'ivy)
(require 'mu4e)
```  

The practical issue is solved for me (recipient completion works), so this can be closed I think; or I can  investigate further if you want (eg to make sure Ivy completion actually works.  As I said, I'm not sure it's actually Ivy I'm seeing).  

Thanks a lot for your help (and your packages!)

**Comment by abo-abo** [comment]
> As I said, I'm not sure it's actually Ivy I'm seeing

It's Ivy:)

> Thanks a lot for your help (and your packages!)

You're welcome.

**Comment by pmagwene** [comment]
I'm seeing the issue reported above with ivy-20170416.1021

**Comment by abo-abo** [comment]
@pmagwene Can't reproduce with latest mu4e and ivy. If you can reproduce, open a new issue.
