### ISSUE TITLE
"This file is part of GNU Emacs" (or is it?)

### ISSUE THREAD

**Issue by wasamasa** [abo-abo/swiper#915]
Initially I thought this was a copy/paste error.  Then I saw the `Copyright (C) 2015-2016  Free Software Foundation, Inc.` line.  Then I saw that [swiper is on GNU ELPA](http://elpa.gnu.org/packages/swiper.html).  Then I saw that swiper on GNU ELPA isn't actually hosted there.

So, is swiper (and everything else around it) still part of Emacs or isn't it?

**Comment by abo-abo** [comment]
> Then I saw that swiper on GNU ELPA isn't actually hosted there.
>
> So, is swiper (and everything else around it) still part of Emacs or isn't it?

swiper is hosted both on GNU ELPA and on Github.
The ELPA repository gets updated each time I release a stable version.

A very large number of the ELPA packages work the same way.

**Comment by wasamasa** [comment]
Well, that's a noble goal to host it both on GNU ELPA and GitHub, but why does the GNU ELPA page say "This package is not in GNU ELPA any more." in its description?

**Comment by abo-abo** [comment]
Oh yea. By popular demand, `swiper 0.7.0` -> `ivy 0.8.0`. On ELPA, `ivy 0.8.0` bundles `ivy`, `swiper` and `counsel`. On MELPA, they are separate.

The rename makes sense, since `swiper` ~ `helm-swoop`, and `ivy` ~ `helm`.

**Comment by abo-abo** [comment]
And of course ELPA, being smart like it is, still lets the users download `swiper 0.7.0`, the last version of that package that was available.
Effectively, `swiper 0.7.0` was removed and `ivy 0.8.0` was added, but ELPA doesn't understand renames.

**Comment by abo-abo** [comment]
The question is answered, closing.
