### ISSUE TITLE
Hard coded 200 limit for counsel-git-grep

### ISSUE THREAD

**Issue by ideasman42** [abo-abo/swiper#917]
While running git-grep on a large project I ran into the limit of 200 items and found this is hard coded.

`head -n 200`

Having a limit makes sense to prevent hanging emacs, but could this be made configurable?

**Comment by abo-abo** [comment]
I use <kbd>C-c C-o</kbd> (`ivy-occur`) to avoid this limitation. You still see the precise amount of matches, and it's not too useful to scroll through more than 200 candidates in the minibuffer window.

**Comment by abo-abo** [comment]
Looking through the old issues, I haven't changed my opinion on this. I'd like to keep it the way it is.
