### ISSUE TITLE
Make ivy-immediate-done easily discoverable

### ISSUE THREAD

**Issue by cubranic** [abo-abo/swiper#918]
Even though I know that `ivy-immediate-done` exists, it's not a frequent action in my use and so I often forget the shortcut by the next time I need it. Can this be made more easily discoverable, i.e., shown during the completion?

**Comment by abo-abo** [comment]
> Can this be made more easily discoverable, i.e., shown during the completion?

Press <kbd>f1 m</kbd> during completion (or whatever your key binding for `describe-mode` is).
Press <kbd>q</kbd> to dismiss the popup.

**Comment by cubranic** [comment]
At least with Spacemacs, <kbd>f1 m</kbd> opens the Ivy help page, but it can't be searched the usual way because the mini buffer is already in use. :-(

**Comment by abo-abo** [comment]
> but it can't be searched the usual way because the mini buffer is already in use. :-(

Use:

    (setq enable-recursive-minibuffers t)

Then you can search the help window.

I also use:

    (minibuffer-depth-indicate-mode 1)
