### ISSUE TITLE
will `ivy-read' mode add pinyin support?

### ISSUE THREAD

**Issue by paul-xie-rs** [abo-abo/swiper#919]
For example:
文件 can be matched by input `wenjian' rather than input `文件' itself.

Now, to find something mixed with chinese character,  I need to toggle the input method on and off. It's boring me very much. I hope `ivy-read' can add pinyin support.

**Comment by abo-abo** [comment]
I don't speak/write Chinese. But PRs welcome.

You can have this functionality even with just user config.
Write your own regex builder and customize `ivy-re-builders-alist`.

Here's a function to get you started:

```elisp
(defun re-builder-pinyin (str)
  (or (pinyin-to-utf8 str)
      (ivy--regex-plus str)))
```

Here, `pinyin-to-utf8` is a function that you have to write. It takes ASCII and returns UTF8 if it recognizes the input as pinyin;
otherwise, it returns nil.

**Comment by paul-xie-rs** [comment]
OK, I'll have a try. Thank you very much

**Comment by paul-xie-rs** [comment]
I try to write this function. But encounter some problems:

In Chinese, Pinyin to chinese character is a 1 to N problem. For example:
`wen' may refer to 问文闻温稳..... and so on. 

So if I insert `wen', I don't know what should I return. 

Further more, it is hard to recognize `wen' as pinyin since many English words also begin with it.

I wonder can I convert chinese characters in all candidates to pinyin before match?
(defun utf8-to-pinyin (str)
  pinyin)

If I write a funciton `utf8-to-pinyin' converting str `文' to `wen'. Can I reach my goals with this function?

**Comment by abo-abo** [comment]
You could have the start input char tell how to interpret the input:

- `!wen` means: use pinyin for the following word, or all following words if you want.
- `wen` means: use ascii.

Also look at `pinyinlib` on MELPA.

**Comment by paul-xie-rs** [comment]
(defun re-builder-pinyin (str)
  (or (pinyin-to-utf8 str)
      (ivy--regex-plus str)
      (ivy--regex-ignore-order)
      ))

(setq ivy-re-builders-alist
      '(
        (t . re-builder-pinyin)
        ))

(defun pinyin-to-utf8 (str)
  (cond ((equal 0 (length str))
         nil)
        ((equal (substring str 0 1) "!")
         (mapconcat 'pinyinlib-build-regexp-string
                    (delete ""
                            (split-string
                             (replace-in-string str "!" "") ""))
                    ".*"))
        nil))

**Comment by abo-abo** [comment]
You're welcome. Consider adding this code to swiper's [wiki](https://github.com/abo-abo/swiper/wiki) or making your own package on MELPA.
