### ISSUE TITLE
ivy-immediate-done to create a new directory

### ISSUE THREAD

**Issue by jackkamm** [abo-abo/swiper#920]
Suppose I have existing directory "foobar/", and I want to create a new file "foo/bar", inside a new directory "foo/". It seems like there is no way to do this in ivy: typing "foo/" will enter into the directory "foobar/", since "foo" partially matches "foobar", whereas typing "foo" and then "C-M-j" will create a new file "foo" instead of a new directory "foo/".

**Comment by abo-abo** [comment]
New directories are created with <kbd>+</kbd> in `dired-mode`, or `make-directory`.
Press <kbd>+</kbd> `foo` <kbd>C-M-j</kbd>. Create a new file after creating a directory.

**Comment by jackkamm** [comment]
OK, that works, I will try out that workflow, or maybe bind `make-directory` to a key if I don't like it.
Thanks for all your great work on ivy, I really enjoy it!

**Comment by abo-abo** [comment]
You're welcome. Happy hacking.
