### ISSUE TITLE
New ivy-switch-buffer command to switch exclusively to an ivy-view?

### ISSUE THREAD

**Issue by unbildung** [abo-abo/swiper#929]
While setting up a `hydra` to take care of my window management, it occurred to me that it would be convenient to create some `hydra` shortcuts for not only `ivy-push-view` and `ivy-pop-view`, but also for an `ivy-switch-buffer` command that lists only the window layouts saved to `ivy-views`. In other words, I want to be able to switch to a saved view without having to first call `ivy-switch-buffer` and then type `{` or scroll down to the bottom of the list. From looking at, for instance, https://github.com/abo-abo/swiper/issues/644#issuecomment-244455350, I see that you can get creative with how you can exclude certain types of buffers from the `ivy-switch-buffer` listing; is there a way to list **_only_** buffers that start with `{}`? I'm sure there is a way to do this, but it's well beyond my coding abilities.

I know this doesn't have anything to do with `hydra` necessarily, but what I want is something like this:

```
(defhydra hydra-layout (:color amaranth :hint nil)
    "layout control panel"
    ("v" ivy-push-view "save layout" )
    ("V" ivy-pop-view "delete a layout")
    ("l" ivy-switch-view "select a layout")
    ("q" nil))
```
—where `ivy-switch-view` or something to that effect would list my saved `ivy-views` in the minibuffer.

P.S. I don't know how to code, but using and playing around with your packages has been delightful and very helpful in how I use Emacs. Thank you for your work and ideas.

**Comment by abo-abo** [comment]
Try this code:

```elisp
(defun ivy-switch-view ()
  (interactive)
  (let ((ivy-initial-inputs-alist
         '((ivy-switch-buffer . "{}"))))
    (ivy-switch-buffer)))
```

**Comment by unbildung** [comment]
Works perfectly! Thank you!
