### ISSUE TITLE
A regex with brackets is only matched after deleting a character

### ISSUE THREAD

**Issue by rootzlevel** [abo-abo/swiper#93]
For example in the package menu, if I want to search for a package that is being updated using swiper, I type `[ID]  package` to find both entries. This regex doesn't immediately match after I type it, but only after I delete a character again.

The problem is probably, that ivy caches the results for `[ID` (which are none, because the regex is invalid) and doesn't notice that new matches can appear after typing the closing bracket.

**Comment by abo-abo** [comment]
I don't understand, why do you type `[ID]`?

**Comment by rootzlevel** [comment]
To match a package that is either deleted or installed. The package menu indicates that by either `I` or `D`. But that was only an example. The same happens for every regex containing bracket expressions.

**Comment by rootzlevel** [comment]
To clarify, here's another example. Suppose you have this buffer:

```
foo
bar
```

Typing `[fb]` in swiper should match both lines (and highlights that in the buffer), but doesn't display any candidates.

**Comment by abo-abo** [comment]
OK, I see it now. I always input `[]` at once, so I haven't encountered this before. You can try to use this method as well for now: first input `[]`, then `fb`.
