### ISSUE TITLE
Swiper search replace regexp in long file

### ISSUE THREAD

**Issue by thorstengrothe** [abo-abo/swiper#931]
I have an long Latex file with a lot of macros to be changed. Unfortunately I'm not very fit in regex, so I hope this is the right place to ask. I would like to use swiper and search/replace the macros:

1. `\PRT{1223abc}`--> the numbers and strings in the brackets are different for every `\PRT`. I would like to delete every `\PRT{}` in the document. In Swiper `\\PRT{` finds all `\PRT's `but not the content of the braces.
2. `\begin{solution}[nLines=2]` --> the number is different every time. I would like to delete every `\begin{solution}[]` in the document.
5. `\begin{question}[6]` --> Change square bracket to braces for every `\begin{question}[]`. in the document.

Thorsten Grothe

**Comment by abo-abo** [comment]
Search for `\\prt{.*}`, replace with the empty string. Same approach for other questions.

**Comment by thorstengrothe** [comment]
Thank you very much, works fine!

**Comment by abo-abo** [comment]
Glad to help.
