### ISSUE TITLE
Add current input to candidates (optionally?)

### ISSUE THREAD

**Issue by Stebalien** [abo-abo/swiper#933]
Note: this only applies when `require-match` is false.

One can currently use `C-M-j` (`ivy-immediate-done`) to use the current input instead of using the selected candidate. However, this is rather unintuitive and I can never remember how to do it when I need it (I don't need it all often enough to remember how).

One solution is to append/prepend the current input to the candidates, possibly with a different face to indicate that it's not an actual candidate. This does cost an extra row of screen space for what is effectively redundant information.

An alternative is to allow the user to move the selection cursor up above the first entry and into the input prompt (that is, visually highlight the text in the input prompt as if it were a selected candidate). This saves a row but is a bit less intuitive. However, it could be made more obvious by visually selecting the input field when there are no matches (to help teach the user that this can be done).

Thoughts? This is obviously a low-priority feature request but it's something I (and others) have found annoying many times.

**Comment by abo-abo** [comment]
Interesting idea, thanks. I'm very busy this week, and probably the next one. But I'll try to look into this sometime. Might be a simple solution to a long standing problem.

**Comment by manuel-uberti** [comment]
`C-M-j` is now muscle memory for me, but I can see @Stebalien point.

Among the proposed alternatives, I prefer the first one. Much more intuitive, IMHO.

**Comment by braham-snyder** [comment]
The second proposal (allow users to select the input prompt as a candidate) makes more sense to me--I'm really not a fan of the redundancy of the first proposal (append or prepend the currently input text as an additional candidate). While appending or prepending is inarguably more discoverable, I'd imagine @Stebalien's suggestion:
> [input-prompt-selection] could be made more obvious by visually selecting the input field when there are no matches (to help teach the user that this can be done)

would work quite well.

**Comment by fabacino** [comment]
The second suggestion has been implemented by now, which hopefully resolves this issue. Everybody interested is encouraged to try it out by setting `ivy-use-selectable-prompt` to `t`. See #1059 for more information.

**Comment by abo-abo** [comment]
@fabacino Thanks for the ping.

I'm closing the issue to keep the overall issue count from being too much. If the suggested fix doesn't work for you, open a new issue.
