### ISSUE TITLE
Ivy action M-o not working anymore

### ISSUE THREAD

**Issue by thorstengrothe** [abo-abo/swiper#935]
Until now M-o executes actions for ivy in the minibuffer. But after the last update this is not working anymore. Did you changed the key?

Thorsten

**Comment by abo-abo** [comment]
I made some modifications to fix #924. Right now <kbd>M-o</kbd> performs the action in the caller's window, not the minibuffer, which I think is a good approach.

For example, here are my global extra actions:

```elisp
(defun ora-insert (x)
  (insert
   (if (stringp x)
       x
     (car x))))

(defun ora-kill-new (x)
  (kill-new
   (if (stringp x)
       x
     (car x))))

(ivy-set-actions
 t
 '(("i" ora-insert "insert")
   ("w" ora-kill-new "copy")))
```

E.g. `counsel-M-x` <kbd>M-o i</kbd> will correctly insert the candidate into `*scratch*`.

What's your specific issue?

**Comment by thorstengrothe** [comment]
Ah I see. I was wondering because flyspell-correct-ivy uses ivy-actions to save a word to the personal dic for example. That does not work anymore. Here's my setup

```
(use-package flyspell-correct-ivy
  :ensure t
  :after flyspell
  :general
  (:keymaps 'flyspell-mode-map
            "<f8>"   'flyspell-correct-previous-word-generic)
  )
```
So I have a word in the buffer marked by flyspell, hit f8 --> suggestions are shown in the minibuffer --> hit M-o to perform an ivy-action and save it to the personal dic.

I will test your examples and see how I can adjust it!

**Comment by abo-abo** [comment]
I just tested it and <kbd>M-o s</kbd> still works on my system. Please try to reinstall/recompile the relevant packages and restart Emacs.

**Comment by thorstengrothe** [comment]
OK thanks for your super fast support, I will test and tell you if it works tomorrow!

**Comment by thorstengrothe** [comment]
Ok, found the error it's use-package:

**use-package-20170218.132** works fine 
with 
**use-package-20170319.12** it does not, flyspell-correct does not show me any actions when hitting 
M-o.
Hm, do you have an idea?

**Comment by abo-abo** [comment]
It's possibly related to the load order. Try putting `ivy-set-actions` later in the code.

**Comment by thorstengrothe** [comment]
Yesterday I updated melpa and with the newest use-package it works now fine!!

**Comment by therockmandolinist** [comment]
@thorstengrothe the `:after` keyword in `use-package` was broken: https://github.com/jwiegley/use-package/pull/439

**Comment by abo-abo** [comment]
Seems solved, closing.
