### ISSUE TITLE
ivy-done from counsel-yank-pop during counsel-ag, from a read-only buffer: "ivy-call: Buffer is read-only"

### ISSUE THREAD

**Issue by braham-snyder** [abo-abo/swiper#937]
showed up within the last week or so, perhaps related to the fixes to https://github.com/abo-abo/swiper/issues/924

**Comment by abo-abo** [comment]
Thanks for the report. This is indeed a big issue. It's hard to figure out how to juggle this recursive state properly, especially since debugging minibuffer windows is awkward.  I'll try to fix this today, possibly by reverting #924.

**Comment by abo-abo** [comment]
Please test.

**Comment by braham-snyder** [comment]
👌
