### ISSUE TITLE
Feature request: allow M-backspace to delete dirs in path in find-file

### ISSUE THREAD

**Issue by zhaojiangbin** [abo-abo/swiper#94]
A minor annoyance.

When editing the path at prompt in `find-file`, <kbd>M-backspace</kbd> works only in the file name part. Once hit the right most slash, the meta key must be let go for deleting the dirs with <kbd>backspace</kbd>.

Meanwhile, <kbd>C-d</kbd> can only delete dirs but not the file name in path.

**Comment by abo-abo** [comment]
> Meanwhile, C-d can only delete dirs but not the file name in path.

I don't understand this one. Is it a separate issue?

**Comment by zhaojiangbin** [comment]
> I don't understand this one. Is it a separate issue?

Yeah `C-d` was kind of an issue, too, for being inconsistent. But I think `C-d` is not used as often as `backspace` and `M-backspace` for editing path in `find-file`.

Now that we have `backspace` and `M-backspace` work consistently through out, there will be even less need for `C-d`. At least I don't see it bothering me anymore.

Thanks for the fix.

**Comment by abo-abo** [comment]
> Yeah C-d was kind of an issue, too, for being inconsistent.

Can you explain (with a recipe)? I don't understand why it's inconsistent.

**Comment by zhaojiangbin** [comment]
For the inconsistency:
1. When the path is ended with a slash, such as "~/path/dir/", `C-d` works same as `backspace`. There is no way, as far as I can tell, that one can move the cursor backward to delete a character with `C-d`.
2. When the path does not have a slash at the end, such as "~/path/dir/file", one can move the cursor backward up to the rightmost slash with `C-a` or `C-b`. `C-d` then works as `delete-char`.

Now I think the problem is more with the keys `C-a` and `C-b` - they cannot move backward beyond slashes.

When the path does not have a slash at the end, and the cursor is at the end of input, and there is at least one candidate, the result of pressing `C-d` is kind of interesting (I am not sure I would call it a bug, but definitely was not expecting it):

- It starts as below. The cursor color is red. Selected candidate is highlighted with underline.
![screen shot 2015-05-12 at 9 02 31 am](https://cloud.githubusercontent.com/assets/4935788/7592229/f9ccd3aa-f886-11e4-964c-6da6a34f792f.png)

- After pressing `C-d`.
![screen shot 2015-05-12 at 9 02 41 am](https://cloud.githubusercontent.com/assets/4935788/7592233/01057c44-f887-11e4-938c-251958378b73.png)

- Ivy always appends the first candidate to the input, regardless where the selection is.

- When there is no candidate, pressing `C-d` results in "End of buffer".

Pressing `M-d` in the same situation behaves similar - ivy deletes the first "subword" from the first candidate, then appends the rest to the input.

**Comment by abo-abo** [comment]
Thanks for the description, I didn't notice this before.

**Comment by zhaojiangbin** [comment]
> Pressing M-d in the same situation behaves similar - ivy deletes the first "subword" from the first candidate, then appends the rest to the input.

@abo-abo By any chance, did you forget fixing `M-d`?
