### ISSUE TITLE
Melpa Stable Release is almost a year behind

### ISSUE THREAD

**Issue by cowboyd** [abo-abo/swiper#945]
We noticed this because the interface for the `counsel-ag` function had changed, and more recent packages were calling it with too many arguments. 

https://github.com/abo-abo/swiper/commit/e38b23c83db53cb6d83e66137ec4b382a38e61bb

It looks likes this change happened some time ago. Perhaps another stable release is due?

**Comment by abo-abo** [comment]
A release was underway a few months ago. But I didn't finish the release notes; now I have to add > 150 more commits to my unfinished release notes. I'll try to do it soon-ish, maybe this weekend.
