### ISSUE TITLE
Tab completion doesn't work with :dynamic-collection

### ISSUE THREAD

**Issue by xendk** [abo-abo/swiper#946]
I've tried making use of ivy-read for opening the file of a class in PHP, using ede-php-autoload. `ede-php-autoload-complete-type-name` will take the prefix of a namespace/class, and provide completions, so I figured I should combine it with `:dynamic-collection` in order to reevaluate the candidates as one narrows down the selection.

It doesn't seem to work with tab completion, which is rather unfortunate. Am I missing something?

**Comment by abo-abo** [comment]
Can you provide a minimal working code example so that I can debug it?

**Comment by xendk** [comment]
```lisp
(defun xen-test ()
  (interactive)
  (ivy-read
   "Test: "
   #'xen-test-cantidates
   :dynamic-collection t
   :action (lambda (x) (message "%S" x))
   :history 'xen-test-history
   :require-match t
   :sort t
   :caller 'xen-test))

(defun xen-test-cantidates (str)
  (list "PrefixA" "PrefixB" "PrefixC"))
```

Running xen-test and typing "Pre" and pressing tab, I'd expect it to expand to "Prefix" but nothing happens. Pressing tab again selects "PrefixA".

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by xendk** [comment]
:+1: Works like a charm.

BTW, thanks for ivy, avy, swiper and hydra.
