### ISSUE TITLE
Misspelling and Action Description Consistency

### ISSUE THREAD

**Issue by shellhead** [abo-abo/swiper#949]
Some very minor things I came across.

There is a misspelling on https://github.com/abo-abo/swiper/blob/master/counsel.el#L432, I believe this should be "find" instead of "fild"

The `find-file-other-window` is used in three different places, each with a different description. For consistency, it may be nice to have them all be "other window" (no hyphen) for all.

Since these are minor, is it possible to open up a PR without the copyright assignment form filled out?

**Comment by abo-abo** [comment]
Thanks.

> Since these are minor, is it possible to open up a PR without the copyright assignment form filled out?

I fixed the issues before reading up to this part:). You can PR with changes up to 15 lines (cumulative) without a CA.
