### ISSUE TITLE
Incorrect rgrep globs with ivy-immediate-done/ivy-alt-done

### ISSUE THREAD

**Issue by brianhlin** [abo-abo/swiper#950]
I'm sure you're sick of `rgrep` issues but I've read all the other ones without finding a working solution. The issue is that `ivy-immediate-done` and `ivy-alt-done` include the path when trying to enter a glob that's contained in the suggested default (i.e. entering `*` when the default suggestion is `*.el`). The following should reproduce the issue: `C-x C-f foo.el M-x rgrep bar RET * C-u C-j RET`. (alternatively, use whatever `ivy-immediate-done` is bound to instead of `C-u C-j`). This results in the following warning in the `*grep*` buffer:

 ```
 find: warning: Unix filenames usually don't contain slashes (though pathnames do).  That means that '-name ‘/home/blin/*’' will probably evaluate to false all the time on this system.  You might find the '-wholename' test more useful, or perhaps '-samefile'.  Alternatively, if you are using GNU grep, you could use 'find ... -print0 | grep -FzZ ‘/home/blin/*’'.
 ```

**Version:** 20170406.553 from MELPA

**Comment by abo-abo** [comment]
Thanks.
