### ISSUE TITLE
The new M-o action lists break in middle of words

### ISSUE THREAD

**Issue by thblt** [abo-abo/swiper#953]
The new `M-o` action list in 0.9.x is really cool, but with long lists (eg, with Projectile), it breaks lines in the middle of words:

![2017-04-10-103007_631x710_scrot](https://cloud.githubusercontent.com/assets/2453136/24852678/adf32230-1dd8-11e7-82ce-dd933b86d8d0.png)

It would probably be best to only break before a binding (eg `[a]: do something^[b]: do something else`), where `^` is a “breaking space” (and all other spaces are non-breaking), or at least to use word wrap (and, if possible, a non-breaking space after the binding).

Thanks!

**Comment by floli** [comment]
A config option to break after every option, like it was without ivy-hydra, would also be very nice!

**Comment by abo-abo** [comment]
Thanks, please test.
