### ISSUE TITLE
Tab can enter inconsistent state in counsel-find-file

### ISSUE THREAD

**Issue by Stebalien** [abo-abo/swiper#955]
Sorry for the vague title, this is a bit of an odd issue. To reproduce:

1. Create directories `~/foo/`, `~/foo/bar/`, and `~/.bar/`.
2. Touch files `~/foo/bar/a` and `~/.bar/b`.
3. `cd` (in emacs) to `~/foo/`.
4. Run `counsel-find-file`.
5. Type `~` then `bar`. You should see `~/.bar` selected.
6. Hit `TAB`. Counsel should now tell you that you are in directory `bar/` (no prefix) and will list no files.
7. Hit enter to enter to open a dired here. The dired will open at `~/foo/bar/`.

However, at step 6, I expected to see `~/.bar` (the selected entry).

**Comment by abo-abo** [comment]
> Hit TAB. Counsel should now tell you that you are in directory bar/ (no prefix) and will list no files.

On my system, the directory becomes `~/.bar` and `b` is listed. Can you reproduce with `emacs -Q`?

**Comment by Stebalien** [comment]
Yes. However, I'm using a recent emacs build from git:

> GNU Emacs 26.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.10) of 2017-04-04


From a clean `~/.emacs.d`:

```
M-x package-install RET ivy RET
M-x cd RET foo RET
M-x counsel-find-file RET ~bar TAB RET
```

This enters `~/foo/bar` instead of `~/.bar`.

**Comment by abo-abo** [comment]
Ah I see now. I was supposed to be in `~/foo` before `counsel-find-file`. I can reproduce it now.

**Comment by abo-abo** [comment]
Thanks, please test.

**Comment by Stebalien** [comment]
Confirmed fixed. Thanks!
