### ISSUE TITLE
case-sensitive rename user experience problem

### ISSUE THREAD

**Issue by timofeytt** [abo-abo/swiper#958]
The related rename-functionality with auto-complete makes it hard to rename into case-sensitive versions of the same file. You have to use `C-M-j`. This appears to be like a user experience problem. 
Originally posted here:
https://github.com/syl20bnr/spacemacs/issues/8715

**Comment by abo-abo** [comment]
It's not as simple as it seems. Suppose you have a file `FooBar` in the directory, you enter `foo` and press <kbd>RET</kbd>. What should `ivy` do?

1. If you return `foo`, you can't open `FooBar` anymore, unless you type out the name completely.
2. If you return `FooBar`, as it's done now, it's convenient to open files and create files with unique names; but inconvenient to create new files which match the existing file names. Except it's not that inconvenient if you know you have to press <kbd>C-M-j</kbd>.

There are already many issues open on this topic. If you have a good idea, let me know.

**Comment by timofeytt** [comment]
Well, this problem exists in the context of renaming files and when only a single match is returned. It could be addressed with a specific fix for this situation, since it's rare in comparison to overall use.
A case can be made for a general solution to keep UI consistent. Why not just include what the user has typed as an option above the case-insensitive matches?
So it would like this:
1    Find file: ~/partial-name-typing
partial-name-typing
match 1 *
match 2
match 3

match 1 is selected just like it is currently, but the user has the option to go up one item to select exactly what he typed. This is graphical and discoverable without the need to know a special keybinding.

I don't know how Emacs works, but maybe you can also go up to select the input line:
1    Find file: ~/partial-name-typing *
match 1
match 2
match 3

**Comment by timofeytt** [comment]
cc @madand @duianto

**Comment by abo-abo** [comment]
> The name of the file started with an upper-case, and I wanted to lower-case it. It works ok the other way around.

    (setq ivy-case-fold-search-default nil)

But then `foo` won't match `Foo` any more.

**Comment by madand** [comment]
I like the way this is handled in Helm. When invoking helm completion, there is an optional keyword parameter which decides whether the completion session is allowed to return custom result. If this parameter is true, helm adds a virtual candidate with the exact user's input on top of the visible candidates list. User then can select that candidate using `C-p`.

I think it should be sticky (always visible, regardless of the scrolling position of the other candidates) and also somehow visually distinguished from the regular candidates (in Helm they prepend "[?] ").

To be fair, I am totally OK with `C-M-j`. Yet, I agree its not intuitive for newcomers.

**Comment by Stebalien** [comment]
See https://github.com/abo-abo/swiper/issues/933 for a related discussion.

**Comment by madand** [comment]
@Stebalien nice catch. I guess this issue should be closed as a duplicate then.

**Comment by timofeytt** [comment]
I'm leaning towards the second approach. In the case of creating/renaming it should automatically select the input line if it's different (case-sensitive) from the matches. However, there should be an option to select the input line (up arrow) in all use cases.

**Comment by fabacino** [comment]
Please see https://github.com/abo-abo/swiper/issues/933#issuecomment-310638597 for a possible solution to this issue.

**Comment by abo-abo** [comment]
@fabacino Thanks, closing.
