### ISSUE TITLE
is there a key map for helm-find-files-up-one-level in counsel

### ISSUE THREAD

**Issue by handrake0724** [abo-abo/swiper#961]
I was using helm for months and now considering to use ivy-mode.
I am wondering if there is a counsel counterpart for helm-find-files-up-one-level because it is handy when I am navigating directories.

Thanks in advance.

**Comment by abo-abo** [comment]
`counsel-up-directory` bound to `C-<backspace>`.

**Comment by handrake0724** [comment]
it works. Thanks.

**Comment by abo-abo** [comment]
OK, closing the issue.
