### ISSUE TITLE
ivy-grid-mode

### ISSUE THREAD

**Issue by notuntoward** [abo-abo/swiper#962]
I've just started experimenting with ivy, and one thing I miss from ido, is the modeline display you get with the ido-grid-mode package.  It's more space efficient, so you can see more in one glance.

Is there such a thing for ivy?

**Comment by abo-abo** [comment]
No. You can probably make one using `ivy-format-function`.

**Comment by notuntoward** [comment]
Thanks, I'll take a look.

**Comment by innerout** [comment]
Probably you ask for this https://github.com/clemera/ivy-explorer .

**Comment by notuntoward** [comment]
Yes, that's pretty much it.  Thanks!

**Comment by abo-abo** [comment]
Thanks, closing.
