### ISSUE TITLE
Swiper creates a phantom state for winner-mode

### ISSUE THREAD

**Issue by campugnatus** [abo-abo/swiper#963]
It seems that ivy conflicts with the built-in winner-mode. It takes two calls to winner-undo (instead of the usual one) to revert the window state if any of the ivy functions were called after the last layout change.

Steps to reproduce:

1. Change window configuration (e.g. split windows or switch to another buffer)
2. Invoke swiper.
3. Close swiper.
4. Call winner-undo (via a hotkey). Nothing happens.
5. Call winner-undo once again. Now it has changed the window configuration to the state it was in before the step 1.

Winner-mode has a configuration variable `winner-boring-buffers` which can be used to make it ignore certain changes in the layout. So I invoked swiper and called `buffer-name` function from within. It returned `" *Minibuf-1*"`. I added this to the `winner-boring-buffers` list, but to no effect.

**Comment by abo-abo** [comment]
Seems it was intended by `winner-mode`. Try:

    (remove-hook 'minibuffer-setup-hook 'winner-save-unconditionally)

**Comment by campugnatus** [comment]
Indeed, this has solved the problem. Wonder why would winner enforce that.

Thanks!
