### ISSUE TITLE
Idea for a counsel-switch-buffer

### ISSUE THREAD

**Issue by xendk** [abo-abo/swiper#964]
How about a `counsel-switch-buffer` that's basically like `ivy-switch-buffer`, but changes the buffer when changing candidate?

It would make buffer switching swiper-like, and I believe that sometimes recognizing the buffer you're looking for would be faster than remembering it's name.

**Comment by abo-abo** [comment]
You can do that now, using <kbd>C-M-n</kbd> instead of <kbd>C-n</kbd>.

**Comment by xendk** [comment]
Indeed I can, and ctrl-g still reverts to the original buffer, so that's swell.

But when `ivy-switch-buffer` is called, it preselects the next buffer, and to see that, it's `C-M-m`, so it's not quite swiper-like. Any way of telling ivy to do `ivy-call` on each selection change?

And being a arrow keys user, I'd suggest to bind `M-<down>` and `M-<up>` to their n/p counterparts.

**Comment by abo-abo** [comment]
> Any way of telling ivy to do ivy-call on each selection change?

<kbd>C-o c</kbd>, then e.g. <kbd>jjjjjkkkf</kbd>.

**Comment by xendk** [comment]
OK, now i better grok ivy, this is exactly what I was imagining:

```elisp
(defun xen-switch-buffer ()
  "Switch to another buffer."
  (interactive)
  (let ((this-command 'ivy-switch-buffer))
    (ivy-read "Switch to buffer: " 'internal-complete-buffer
              :matcher #'ivy--switch-buffer-matcher
              :preselect (buffer-name (other-buffer (current-buffer)))
              :action #'ivy--switch-buffer-action
              :keymap ivy-switch-buffer-map
              :caller 'ivy-switch-buffer
              :update-fn 'ivy-call)))
```

**Comment by abo-abo** [comment]
Neat. Not sure I'd like this on all the time, but I see the appeal:)
