### ISSUE TITLE
how to save position in find-file

### ISSUE THREAD

**Issue by earthIsAPrisonIfYouNotAwareItCanNotOut** [abo-abo/swiper#967]
It is conveniently to provide a key binding to save position when use `C-x C-f`in particular file path
Wander if how to achieve it

**Comment by abo-abo** [comment]
You're talking about bookmarks. They're not the job of `C-x C-f`.

**Comment by earthIsAPrisonIfYouNotAwareItCanNotOut** [comment]
Is there a way to quickly jump to filepath which I want (just like `org-attch` to pick up the file path)

**Comment by abo-abo** [comment]
Try <kbd>M-o b</kbd>.

**Comment by earthIsAPrisonIfYouNotAwareItCanNotOut** [comment]
the command `face menu-set-bold`?

**Comment by abo-abo** [comment]
I meant <kbd>C-x C-f M-o b</kbd>.

**Comment by earthIsAPrisonIfYouNotAwareItCanNotOut** [comment]
nice shortcut!

**Comment by earthIsAPrisonIfYouNotAwareItCanNotOut** [comment]
I's a pity the key binding not use in `org-attach`

**Comment by earthIsAPrisonIfYouNotAwareItCanNotOut** [comment]
Isn't it?
