### ISSUE TITLE
counsel-company doesn't correctly complete in some instances

### ISSUE THREAD

**Issue by gnuvince** [abo-abo/swiper#969]
Consider the following Rust program: 

```rust
fn main() {
    let s = String::new();
    s.ext|
}
```

When at the cursor (indicated with the `|`), invoking `M-x counsel-company` will insert the text `extend` after `ext` i.e., the third line becomes `s.extextend`.

The same behaviour happens in the following C program, but with a slightly different result: the prefix `pu` is replaced with `pput`.

```c
#include <stdio.h>
int main(void) {
    pu|
}
```

- Emacs 25.2
- Ivy 9.1 (mepla-stable channel) and 20170416 (melpa channel)
- Rust-mode, racer-mode, and cargo-mode from melpa (20170411, 20170218, 20170203)
- Built-in cc-mode
- company from melpa (20170328)

**Comment by abo-abo** [comment]
What's your source of completions for C?

**Comment by gnuvince** [comment]
The variable `company-backend` is set to `nil`.  Is that what you're looking for?

**Comment by abo-abo** [comment]
Not really. The completions have to come from somewhere. Which code produces the list, e.g. `("push", "pull", ...)`?

**Comment by Wilfred** [comment]
I think you want to look at `company-backends` rather than `company-backend`. This is often a buffer-local variable, so look at its value in the relevant buffers.

**Comment by gnuvince** [comment]
It seems that removing the call to `company-complete-common` inside `counsel-company` eliminates the problem in the two example I provided.  I don't yet know if it creates other problems elsewhere.

**Comment by abo-abo** [comment]
@gnuvince Thanks, please test.
