### ISSUE TITLE
Ivy deletes org-capture input if S-SPC is pressed

### ISSUE THREAD

**Issue by gorgonical** [abo-abo/swiper#971]
When using org-capture to capture any kind of headline, if I type S-SPC, the input will vanish. The input is being captured at the mini-buffer, and it's obvious that ivy is active in the minibuffer because of the candidate counter at the beginning. This is a bit of a problem because I don't always clear the shift key after typing capitals.

These are the buffers I've configured for ignore:
```
 '(ivy-ignore-buffers
   (quote
    ("\\` " "\\*Org.*" "personalorg\\.org" "\\*Capture.*")))
```

This should match those capture buffers, but it doesn't.

**Comment by abo-abo** [comment]
What are your capture settings? How can I reproduce the issue?

**Comment by gorgonical** [comment]
I tested it with all of my templates, and it's reproducible by typing any text in either the headline field or the outcome text on my projects, and pressing S-SPC. I don't know exactly which settings might effect this, so I've attached a file of all of my settings that configure org or should interact with org directly.

According to describe-key, S-SPC ''should'' translate to SPC, but it doesn't in the context of ivy completion.

[orgsettings.txt](https://github.com/abo-abo/swiper/files/955487/orgsettings.txt)

**Comment by abo-abo** [comment]
OK, I can reproduce the issue now. Two questions:

- Why do you press <kbd>S-SPC</kbd>?
- Why not use e.g. `%?` in place of `%^{Title of book}`? I use that in all my templates.

**Comment by gorgonical** [comment]
I'm pressing `S-SPC` because when I type capitals, sometimes my finger doesn't come off the shift key before I press the spacebar, only because my thumb is always on the spacebar.

Almost all of my templates can safely use the cursor position instead of the prompt, except the ones where I have multiple prompts. As far as I can tell you can only have one cursor position expansion.

**Comment by abo-abo** [comment]
The issue can be solved with:

```elisp
(define-key ivy-minibuffer-map (kbd "S-SPC") nil)
```

I think this can be closed.
