### ISSUE TITLE
how to convert find-file style to projectile style

### ISSUE THREAD

**Issue by earthIsAPrisonIfYouNotAwareItCanNotOut** [abo-abo/swiper#972]
I gave a issue about the `find-file`recently
something I have not expressed exactly is -
how to convert `find-file`style (find file per layer) to `projectile` style (find file directly)

**Comment by therockmandolinist** [comment]
Do you mean recursively inside the current directory?

**Comment by abo-abo** [comment]
I think you want `counsel-file-jump`.

**Comment by earthIsAPrisonIfYouNotAwareItCanNotOut** [comment]
@therockmandolinist recursively the filename I type and appear all that possible directories which is matched
@abo-abo not yet..
