### ISSUE TITLE
counsel-yank-pop ignores some kill-ring entries

### ISSUE THREAD

**Issue by vonkempnz** [abo-abo/swiper#973]
I've noticed that counsel-yank-pop seems to not display some entries from the kill-ring. I don't know the exact criteria, but it seems to ignore short entries that contain contain non-ASCII characters. 

For example, the following kill-ring entries do not appear in the counsel-yank-pop completion list: 

```
"•"
"×"
"©" 
```

The entries:

```
"• "
"× "
"© " 
```

are similarly ignored. However the entries:

```
"• abcd"
"× abcd"
"© abcd"
```
and 

```
"•
×
©"
```

all appear in the list as expected.

Also, an unrelated question:- if I do an accidental yank-pop (via M-y), Emacs tells me that the "Previous command was not a yank". However, the behaviour of counsel-yank-pop is different, bringing up the completion list regardless of the previous command. Can I change this?

If it matters, I'm running swiper 0.9.0 and mac-port Emacs 25.2.1 on macOS 10.12.4, although I see the same result on GNU NS Emacs.

**Comment by vonkempnz** [comment]
I just tested a bit further and it seems counsel-yank-pop ignores _all_ kill-ring entries less than three characters long. Is this intentional?

**Comment by abo-abo** [comment]
> Is this intentional?

Well, it is in the code; I don't remember why I put it there. Probably because it's faster to type out 1-2 chars than to call `counsel-yank-pop`.

**Comment by abo-abo** [comment]
> However, the behaviour of counsel-yank-pop is different, bringing up the completion list regardless of the previous command. Can I change this?

There's no reason to change it. The default restriction is pretty arbitrary and inconvenient. And you can quit `counsel-yank-pop` with <kbd>C-g</kbd>.

**Comment by abo-abo** [comment]
I removed the restriction. I guess it's useful for copying weird Unicode chars and selecting them with <kbd>C-n</kbd>.
