### ISSUE TITLE
counsel-m-x prefixes '^' when ivy--regex-ignore-order

### ISSUE THREAD

**Issue by jtpavlock** [abo-abo/swiper#975]
Is there a way to remove this behavior? It'd be nice not to have to backspace in order to get my intended regex operation. Thank you.

**Comment by abo-abo** [comment]
You can adjust `ivy-initial-inputs-alist` if you want.

**Comment by jtpavlock** [comment]
Just what I was looking for, thanks! Sorry if that was obvious, I'm fairly new to all of this.

**Comment by abo-abo** [comment]
You're welcome, no problem.

**Comment by neojski** [comment]
How do I actually properly customize this? If I run customize command ivy-initial-inputs-alist doesn't seem to be there.

**Comment by abo-abo** [comment]
@neojski You can use `setq`:

```elisp
(setq ivy-initial-inputs-alist
      '((org-refile . "^")
        (org-agenda-refile . "^")
        (org-capture-refile . "^")
        (counsel-M-x . "^")
        (counsel-describe-function . "^")
        (counsel-describe-variable . "^")
        (counsel-org-capture . "^")
        (Man-completion-table . "^")
        (woman . "^")))
```

**Comment by neojski** [comment]
Right, but can I override just a single one easily?

**Comment by abo-abo** [comment]
@neojski Yes, use `add-to-list`.

**Comment by joech4n** [comment]
For any other newbies like me (and using [Spacemacs](http://spacemacs.org/)), I added this to my `.spacemacs`:

```
(setq ivy-initial-inputs-alist nil)
```
