### ISSUE TITLE
Can't create a directory with a certain name if a directory that begins with that name already exists

### ISSUE THREAD

**Issue by stephenlam** [abo-abo/swiper#979]
I have a ~/GitHub directory. When using counsel-M-x in conjunction with make-directory, I cannot create a directory at ~/git. I'm able to create a directory ~/gitx but not ~/git, since ivy will attempt to complete to ~/GitHub when that is not my intention.

**Comment by therockmandolinist** [comment]
I think you're looking for `C-M-j` or `ivy-immediate-done`.

**Comment by stephenlam** [comment]
Thanks, that worked.

**Comment by abo-abo** [comment]
@therockmandolinist Thanks.
