### ISSUE TITLE
[Discuss]  "Don't open directory" mode

### ISSUE THREAD

**Issue by tumashu** [abo-abo/swiper#98]
When the below configure enable,  ivy-mode will only open file and don't open directory, this mode is more simple and predictable。。。

How to use:
1. when type "enter",  if current candidate is a directory,  complete its subdir,  when current candidate is a file, open this file.
2. if user want to open directory, type "C-f".

I suggest this mode can include ivy-mode doc as an example.

```
(require 'swiper)
(ivy-mode 1)

(setq ivy-extra-directories nil)

(defun eh-ivy-partial-or-done ()
  (interactive)
  (or (ivy-partial)
      (ivy-alt-done)))

(defun eh-ivy-open-current-directory ()
  (interactive)
  (when ivy--directory
    (let ((dir ivy--directory))
      (message (format "Open directory: %s" dir))
      (delete-minibuffer-contents)
      (ivy--done dir))))

(define-key ivy-minibuffer-map (kbd "TAB") 'eh-ivy-partial-or-done)
(define-key ivy-minibuffer-map (kbd "<return>") 'ivy-alt-done)
(define-key ivy-minibuffer-map (kbd "C-f") 'eh-ivy-open-current-directory)

```

**Comment by abo-abo** [comment]
You can put your stuff at https://github.com/abo-abo/avy/wiki. Just create a separate page.
