### ISSUE TITLE
Disable line numbers in Swiper minibuffer

### ISSUE THREAD

**Issue by 0rdy** [abo-abo/swiper#983]
Is there a way to disable line numbers in Swiper?
![screenshot-2017-05-03_00-43-06](https://cloud.githubusercontent.com/assets/9018005/25640803/c21362ca-2f99-11e7-9864-dba42434c3e5.png)

**Comment by abo-abo** [comment]
No, there's no way to do it. But you can use `swiper-all`, which doesn't show line numbers.

**Comment by Ergus** [comment]
Hi:

Actually I have the opposite problem. I want the numbers in minibuffer and I don't have them:

![image](https://user-images.githubusercontent.com/6975176/84095064-908a6e00-a9fe-11ea-9cca-4cd68b662cae.png)

**Comment by abo-abo** [comment]
@Ergus maybe you're using `swiper-isearch` and not `swiper`?

**Comment by Ergus** [comment]
Yes, that's actually the problem.

**Comment by NightMachinery** [comment]
Is there some elisp hack that can make the line numbers go away for `swiper`? (and not `swiper-isearch`, which doesn't have the line numbers to begin with)

I don't want `swiper-all`.

**Comment by NightMachinery** [comment]
@Ergus 

`swiper-include-line-number-in-search` might work?

**Comment by basil-conto** [comment]
> Is there some elisp hack that can make the line numbers go away for `swiper`? (and not `swiper-isearch`, which doesn't have the line numbers to begin with)

Does this fit the bill?

```el
(with-eval-after-load 'ivy
  (ivy-configure 'swiper
    :display-transformer-fn
    (lambda (cand)
      (remove-list-of-text-properties 0 1 '(display) cand)
      cand)))
```

> `swiper-include-line-number-in-search` might work?

No, that only controls whether `swiper`'s line numbers are part of the searchable text (together with their line contents).  `swiper` uses line numbers unconditionally, irrespective of this user option:

https://github.com/abo-abo/swiper/blob/4546ce0ca4655512387116b02939ef42ae21fb9f/swiper.el#L567-L570

I don't know why this is the case (or why it has to be).  I'm sure patches would be welcome if someone would like to add a user option to control the presence of line numbers in `swiper`.  Might need to check whether existing code expects line numbers, though.
