### ISSUE TITLE
Cannot install package

### ISSUE THREAD

**Issue by EgZvor** [abo-abo/swiper#987]
When executing `M-x package-install`, I get the following error
```
Package does not untar cleanly into directory ivy-20170416.1021/
```
I'm on Windows 10.
I added path to tar in git-for-windows and used emacs shell successfully to run it.
There's also a warning
```
Warning: premature EOF parsing tar file
```

**Comment by abo-abo** [comment]
Installs fine for me. Probably a `package-install` hiccup; restart Emacs and try again.
