### ISSUE TITLE
counsel-git-grep matches the pattern to file names in addition to file contents

### ISSUE THREAD

**Issue by zhaojiangbin** [abo-abo/swiper#99]
When the pattern happens to be matching part of a file path in the git repo, all lines from that file, containing the pattern or not, are listed as candidates, in addition to matching lines from other files.

In the attached screenshot, I wanted to rename a file from "hydra-ext.el" to "hydra-ex.el" so I was searching "hydra-ext" to change all occurrences to "hydra-ex". `counsel-git-grep` also gave me **all** lines from hydra-ext.el:

![screen shot 2015-05-11 at 10 32 07 pm](https://cloud.githubusercontent.com/assets/4935788/7580647/f6339534-f82d-11e4-963b-16ea89cbd78f.png)

If this is by design, any chance to make this behaviour optional?

**Comment by abo-abo** [comment]
> If this is by design, any chance to make this behaviour optional?

Not really by design, it's just convenient to implement it this way.  You can avoid the problem if you change your pattern to ": hydra-ext".  I'll make a better fix later.

**Comment by zhaojiangbin** [comment]
Can you turn it around, i.e. make ":hydra-ext" to include matching file names and "hydra-ext" to match file contents only? IMHO, the latter is what most users expect. But, of course, if the better fix is coming soon, don't bother.
