### ISSUE TITLE
merge of faces ivy-modified-buffer and ivy-switch-buffer-faces-alist 

### ISSUE THREAD

**Issue by mallt** [abo-abo/swiper#992]
I was wondering if it is currently possible to merge the faces `ivy-modified-buffer` and `ivy-switch-buffer-faces-alist`? I would like to show modified buffers in italic for example and keep the rest of the mode specific face attributes of the `ivy-switch-buffer-faces-alist`, but `ivy-modified-buffer` seems to always override the mode specific face now.

Thanks!

**Comment by abo-abo** [comment]
Thanks, please check.

**Comment by mallt** [comment]
Works perfectly, thanks a lot!
