### ISSUE TITLE
Yank current candidate or copy current candidate to buffer

### ISSUE THREAD

**Issue by Somelauw** [abo-abo/swiper#993]
I would like it if there were a function ivy-copy-to-buffer which would copy the current selection to the most recently used buffer. I know this can be done with hippy-expand but that isn't very precise.

Another possibility would be a function which saves the current candidate to kill-ring (so I can yank it somewhere later). There's already a function ivy-kill-ring-save, which copies all items, but sometimes I want to copy the current result only

**Comment by abo-abo** [comment]
Since some weeks ago, for any `ivy` completion:

- <kbd>M-o w</kbd> will copy the current candidate to the kill ring.
- <kbd>M-o i</kbd> will insert the current candidate into the current buffer.

**Comment by Somelauw** [comment]
@abo-abo thanks, I needed those
