### ISSUE TITLE
open buffer in split window 

### ISSUE THREAD

**Issue by alexdreptu** [abo-abo/swiper#994]
Is it possible to define-key ivy-minibuffer-map to open buffer in split windows vertically and horizontally? I've not found any ivy functions that I can use but I'm sure there must be something I'm missing.

**Comment by abo-abo** [comment]
There's `ivy-switch-buffer-other-window`. Also, <kbd>M-o j</kbd> for `ivy-switch-buffer`. You can customize either `ivy-minibuffer-map` or use `ivy-set-actions` for `ivy-switch-buffer` in your config.

**Comment by alexdreptu** [comment]
I am using ```ivy-switch-buffer``` and  ```ivy-switch-buffer-other-window``` but it doesn't let me choose how to open the buffer. What i'm asking is if there's a way to open a buffer either horizontally or vertically split in the current window I'm in at the moment. Like vim / evil let's me do. Here's an example of what I use with neotree:
```elisp
(evil-define-key 'normal neotree-mode-map
    (kbd "o") 'neotree-enter
    (kbd "s") 'neotree-enter-vertical-split
    (kbd "x") 'neotree-enter-horizontal-split))
```
Pressing ```o``` opens the file in the current window (last window I was in before switching to neotree), pressing ```s``` open the file in a vertically split window and ```x``` in a horizontally split window. I would like to do the same with ```C-s``` / ```C-x``` or similar when i'm in ```ivy-switch-buffer```. It's very useful and offers a great workflow. Is it possible?
