### ISSUE TITLE
ivy-highlight-face taking priority over ivy-current-match

### ISSUE THREAD

**Issue by aaronjensen** [abo-abo/swiper#995]
I feel like this wasn't the case earlier, but today things that are highlighted in describe-variable do not show the ivy-current-match face when they are selected making it hard to know which one is selected.

I have ivy-highlight-face customized and ivy-current-match themed.

```
 '(ivy-highlight-face ((t (:background "#383b31"))))
```

![20170509-232307-vglj0](https://cloud.githubusercontent.com/assets/8588/25885635/76bad158-350e-11e7-9b20-974e081c8a9a.png)

![20170509-232314-mew41](https://cloud.githubusercontent.com/assets/8588/25885639/7b4f4dc0-350e-11e7-8bc6-20bf6b59e31b.png)

Is there some face priority that I've messed up somehow by customizing? Or is there a bug? Thanks!

**Comment by aaronjensen** [comment]
It looks like ivy-current-match doesn't get set in that case:

```
"#(\"
shell-command-with-editor-mode
rcirc-mode-hook
ffap-string-at-point
org-highest-priority
glyph-table
fundamental-mode-abbrev-table
foob
find-directory-functions
global-highlight-parentheses-mode
org-todo-line-tags-regexp
org-mobile-agendas
mail-self-blind
mouse-scroll-min-lines
lm-history-header\" 0 1 (read-only nil ws-butler-chg chg) 1 31 (face ivy-highlight-face read-only nil ws-butler-chg chg) 31 69 (read-only nil ws-butler-chg chg) 69 89 (face ivy-highlight-face read-only nil ws-butler-chg chg) 89 137 (read-only nil ws-butler-chg chg) 137 161 (face ((background-color . \"#2ec1316926c0\") . ivy-highlight-face) read-only nil ws-butler-chg chg) 161 162 (read-only nil ws-butler-chg chg) 162 195 (face ivy-highlight-face read-only nil ws-butler-chg chg) 195 222 (read-only nil ws-butler-chg chg) 222 240 (face ivy-highlight-face read-only nil ws-butler-chg chg) 240 241 (read-only nil ws-butler-chg chg) 241 256 (face ivy-highlight-face read-only nil ws-butler-chg chg) 256 257 (read-only nil ws-butler-chg chg) 257 279 (face ivy-highlight-face read-only nil ws-butler-chg chg) 279 280 (read-only nil ws-butler-chg chg) 280 297 (face ivy-highlight-face read-only nil ws-butler-chg chg))"
```

**Comment by abo-abo** [comment]
Works fine for me. Can you reproduce with `emacs -Q`?

**Comment by aaronjensen** [comment]
Yes:

```
(require 'package)

(add-to-list 'package-archives '("melpa" . "http://melpa.org/packages/"))


(package-initialize)
(package-install 'ivy)
(package-install 'counsel)
(package-install 'monokai-theme)
(require 'ivy)
(load-theme 'monokai)

(ivy-mode 1)

(custom-set-faces
 '(ivy-highlight-face ((t (:background "#383b31")))))
```

It seems like the backgrounds from the two faces overlay one another somehow (If I set them to vastly different colors I can see that when the two are combined they're something different). I don't know how that works in emacs.

**Comment by aaronjensen** [comment]
Some screenshots of the background combination i'm seeing:

![20170510-215631-eowbl](https://cloud.githubusercontent.com/assets/8588/25933434/93f9e7dc-35cb-11e7-8261-970e0020417a.png)
![20170510-215657-kckpq](https://cloud.githubusercontent.com/assets/8588/25933438/987fb8cc-35cb-11e7-827f-5be390736571.png)

**Comment by aaronjensen** [comment]
FYI, I posted on emacs.stackexchange as well, as this seems like an emacs specific thing that I just do not understand: https://emacs.stackexchange.com/questions/32723/what-is-causing-background-colors-to-blend

**Comment by aaronjensen** [comment]
Ah! It seems that ivy is using colir to blend backgrounds explicitly: https://github.com/abo-abo/swiper/blob/master/ivy.el#L2427

Ok, so I'm not crazy 😄  I'll use this knowledge to update my color scheme so that I can see the blended color.

@abo-abo feel free to close this if you think this is a non-issue.

**Comment by abo-abo** [comment]
OK, so your issue was that red, when blended with green resulted in brown?

That's not a bug, it's a feature:) Instead of using either one or the other background color, it composes them, so that it's clear that two backgrounds apply.

**Comment by aaronjensen** [comment]
@abo-abo No, see my original post. My issue was that grey and dark grey resulted in darker grey, making it very hard for me to see the currently selected item.

**Comment by abo-abo** [comment]
Then you'll just have to tweak `ivy-highlight-face`.

**Comment by Yevgnen** [comment]
What is `ivy-highlight-face` for ?
<img width="365" alt="screen shot 2017-05-14 at 3 03 54 pm" src="https://cloud.githubusercontent.com/assets/16749790/26031900/9207aab6-38b6-11e7-9f79-84f4c58cc593.png">

**Comment by abo-abo** [comment]
> What is ivy-highlight-face for ?

Highlight variables that were declared with `defcustom`. Also, highlight functions that are commands.

**Comment by d1egoaz** [comment]
@abo-abo ohhh, that's why some items were highlighted!.
is there any way to disable this behavior without doing:
`   '(ivy-highlight-face ((t (:background nil :foreground nil))))`
?

thanks!
