### ISSUE TITLE
Counsel-git-grep only searches lines that contain '' on windows

### ISSUE THREAD

**Issue by Custodia** [abo-abo/swiper#996]
When I do `counsel-git-grep` in a repository it only displays lines containing ''.

When you specify the regex you want to search for it narrows down the lines with '' in them.

**Comment by abo-abo** [comment]
Try to debug the issue by evaling this in the appropriate directory:

```elisp
(let* ((string "test")
       (cmd (format counsel-git-grep-cmd
                    (setq ivy--old-re (ivy--regex string t)))))
  (shell-command-to-string cmd))
```

If it doesn't work, eval only `cmd`, and paste it into your terminal.

**Comment by Custodia** [comment]
Running the whole command I get `Debugger entered--Lisp error: (wrong-type-argument stringp nil)`

Running the cmd block only I get `Symbol's function definition is void: cmd`

**Comment by abo-abo** [comment]
Try:

```elisp
(let* ((string "test")
       (cmd (format "git --no-pager grep --full-name -n --no-color -i -e '%s'"
                    string)))
  (shell-command-to-string cmd))
```

**Comment by Custodia** [comment]
It's reporting a empty string when I run that. What way do you want me to run the command? Doing eval-buffer isn't doing anything and tediously typing the command to eval returns an empty string.

I also have a theory on what might be happening here. `''` shouldn't be a valid search expression at all, I think it's getting escaped somewhere. Running from console that I way I get the same results as I do when searching from emacs.

**Comment by Custodia** [comment]
Actually I was testing powershell, in cmd '' is a valid search string

**Comment by tomliang880611** [comment]
Same for me. But it works fine having run the following. Seems in cmd, windows has issue parse '', while it works file for git bash and powershell.

```emacs-lisp
(setq counsel-git-grep-cmd-default "git --no-pager grep --full-name -n --no-color -i -e \"%s\"")
```

**Comment by Custodia** [comment]
@tomliang880611 hey, sorry to bother but where did you add that?

**Comment by tomliang880611** [comment]
@Custodia I added that in my init.el somewhere after the swiper is loaded.

**Comment by Custodia** [comment]
Sorry for the delayed response, it does work after making that modification.
