### ISSUE TITLE
Using ivy-fixed-minibuffer-height with ivy-display-function-overlay

### ISSUE THREAD

**Issue by basil-conto** [abo-abo/swiper#997]
#### Issue

When  `ivy-fixed-minibuffer-height` is enabled and a completion uses `ivy-display-function-overlay` as its `ivy-display-function`, the minibuffer's height is set to `ivy-height` (plus 0 or 1) in `ivy--minibuffer-setup`, as seen in the following two screenshots:

![2017-05-11-185005_1600x900_scrot](https://cloud.githubusercontent.com/assets/9121222/25963859/bab57562-367a-11e7-9b54-01813980931f.png)

![2017-05-11-185017_1600x900_scrot](https://cloud.githubusercontent.com/assets/9121222/25963864/beb0b690-367a-11e7-98dc-dd07517e994e.png)

#### Questions

* Does this behaviour ever make sense, or should `ivy-fixed-minibuffer-height` and `ivy-display-function-overlay` be mutually exclusive?
* Is there a way to customise this behaviour without having to advise or modify `ivy--minibuffer-setup`?

**Comment by abo-abo** [comment]
Thanks.
